### ISSUE TITLE
Stop adding torrents without TorrentDef

### ISSUE THREAD

**Issue by LipuFei** [Tribler/tribler#1011]
We are adding torrents into the database with the actual torrent files. The information we put into the database is the one we get from the SearchCommunity. The magnet link is created by ourselves and it only contains the infohash, which is useless.

For more information, see the `addExternalTorrentNoDef` method in `TorrentDBHandler`.

**Comment by NielsZeilemaker** [comment]
This is required because of the foreign key from channeltorrents. If we need the .torrent for all ChannelTorrents, you need a lot of diskspace.
