### ISSUE TITLE
No way to change anonymity level after download has started

### ISSUE THREAD

**Issue by QQCucumber** [Tribler/tribler#1013]
I saw on the website there was an Anonymity tab where you could change the setting for the download, but it no longer seems to exist. I've looked in every nook and cranny but it seems like the only way to go from an anonymity level of 5 to 2, is to delete the torrent and then find it again and this time choose a lower setting.

**Comment by francescodiorazio** [comment]
Thanks Whirm.  I was wondering if the setting was hidden, but it's just not a feature right now.  Would love to have this since you can increase download speed by lowering the anonymity level, but after download I'd like to increase the anonymity level.
