### ISSUE TITLE
WebUI: Allow to run Tribler as daemon

### ISSUE THREAD

**Issue by kordianbruck** [Tribler/tribler#1015]
With the anonymity feature implemented, we need some strong nodes to pass traffic through. Many Torrent release groups have core-seeder system, where they first distribute the new torrent to a small group of nodes before uploading this data to the public trackers. This in turn ensures that when the mass of new peers hits, everyone will get good speed and there is not a single initial peer having to supply all the parts.

Many people use servers to leech and seed torrents (called web seeds) which overall ensures that files get distributed quickly.

What I'm getting at is, that as long as Tribler has no form of running on Linux without the requirement of an UI, there will be no web seeds, which would provide much help in anonymity of the peers with weak connections and speed up the network in general. These web seeds also have the positive aspect of being always on, so improving the general stability of the whole network.

**Comment by devos50** [comment]
I've created a Twistd plugin which allows Tribler to run as daemon 👍

**Comment by DJPlaya** [comment]
Please rename, i dont see this being related to "WebUI"
