### ISSUE TITLE
Update channel management interface

### ISSUE THREAD

**Issue by egbertbouman** [Tribler/tribler#102]
Update the channel management interface according to the screen mockups from our GUI designers:

![my channel editable view manage](https://f.cloud.github.com/assets/3785124/400793/22766eaa-a8c1-11e2-9a70-b924551442bf.jpg)
![my channel editable view](https://f.cloud.github.com/assets/3785124/401012/a0942bf6-a8cb-11e2-8a4a-c6532b472fef.jpg)
![my channel normal view with description](https://f.cloud.github.com/assets/3785124/400795/2298d99a-a8c1-11e2-8aec-7c7acb39a539.jpg)
![my channel normal view](https://f.cloud.github.com/assets/3785124/400796/229cc35c-a8c1-11e2-94ea-c0ff82626582.JPG)

**Comment by devos50** [comment]
Maybe for next year?

**Comment by qstokkink** [comment]
This issue has been superseded with the release of Tribler 7.
