### ISSUE TITLE
Avoid relaying filtered torrents to other users

### ISSUE THREAD

**Issue by cathalgarvey** [Tribler/tribler#1025]
Hi, great work on Tribler's internal OR network, really happy to see this implemented in a mainstream client targeted at end users!

Lots to suggest to make Tribler even more amazing, but one thing that jumps out at me is that, by implementing OR routing in this way, am I not at risk of relaying illegal or immoral materials into an onion routing circuit for others? In other words, if I am by default a potential "exit node" for other Tribler users into swarms of, for example, child porn, am I not then directly responsible for providing that data through the OR link?

This should be an easy fix, because most swarms are clear-text, so I can set up my client to identify swarms by keywords or lists of blacklisted infohashes, and have my client refuse to act as an exit to those swarms. So, consider this a feature request please.

The status-quo in Tribler is not only that I may be helping horrible people get their fap material, but that I may be legally at risk as it will appear that _I_ am the one downloading abuse material, or at least that I knowingly allowed others to use my connection for that purpose!

**Comment by synctext** [comment]
Closing this issue, Tribler should never run as "exit node". Only for (cmdline) experts.
