### ISSUE TITLE
High DPI usability problem

### ISSUE THREAD

**Issue by select** [Tribler/tribler#1034]
I wanted to test the latest version as I'm quite exited that you release the onion routing feature. But unfortunately my display destroys your UI

A solution would be to make the modals resizable.

Tribler 6.4
Lenovo Yoga2
Ubuntu 14.10
Resolution: 3200x1800

![screenshot from 2014-12-19 12 30 12](https://cloud.githubusercontent.com/assets/1164760/5503722/d8418f82-877a-11e4-841e-c15eb34de164.png)

Please contact me if you need further testing on my side. I'm very interested in making your project work!

**Comment by select** [comment]
yes sry, I was busy but I'll get to it within this week

**Comment by whirm** [comment]
@synctext Could you take a look and see if you can reproduce it? It looks like the same issue we had with the opt-in dialog in your computer.

**Comment by synctext** [comment]
new GUI coming, closing.
