### ISSUE TITLE
Quicker/Easier way to add new torrents

### ISSUE THREAD

**Issue by fgblomqvist** [Tribler/tribler#1044]
Tribler has come a long way during the last couple of years, but I feel like it is lacking when it comes to making it easy for the user to add more content to the network (an aspect which is vital for it to gain more users).

A flow, for downloading something, which I feel is both natural and smooth is this:
Search in Tribler > If requested content doesn't exist search elsewhere > Add torrent to Tribler > Select which favorited channels (and/or your own) channel to add the torrent to OR Right click the added torrent and choose "Add to channel > [Shows a list of the favorited channels and your own]"

Right now, I have to go to the channel, click edit (which does not make sense to me at all since I don't really want to edit the channel, only the contents of it) and then add the torrent from my library.

Another option could be to allow the user to automatically add all torrents added to Tribler to their own channel at least.

I would really appreciate some input on these ideas!

**Comment by phoglenix** [comment]
A potentially great solution to getting more content into the network, and making it easier, would be to allow users to create channels based on torrent rss feeds. It would bring in content from outside the network and make some good quality channels available to everyone.

**Comment by whirm** [comment]
@phoglenix we actually have this feature since a long time ago: you can set the RSS source in: Channels -> My channel -> create channel -> Manage

**Comment by phoglenix** [comment]
Oh, thanks! Great that it exists! Too bad it is hard to find :(

**Comment by whirm** [comment]
@phoglenix yeah, the UI needs some love...

**Comment by phoglenix** [comment]
I gave the rss feed a try and it seems that it doesn't work for magnet links, only .torrent files. So there's still definite room for improvement here.

**Comment by whirm** [comment]
@phoglenix Could you open an issue for any improvement you deem necessary?

Thanks!

**Comment by phoglenix** [comment]
@whirm Done! #1160

**Comment by synctext** [comment]
closing this feature request from few years ago. Gigachannel feature enables great crowdsourcing and easier adding content.
