### ISSUE TITLE
[Feature] Monitored directories and tracking file name changes

### ISSUE THREAD

**Issue by generalmanager** [Tribler/tribler#1046]
One of the biggest problems of all data-centric p2p software like bittorrent is that people stop uploading data before a 1:1 ratio is reached.
I believe that in many cases the traditional workflow and limited storage space are to blame.

After a download is finished, users often change the name of the names of files and folders, move the file(s) to a different directory and delete small files with additional information on the content like .nfos.
This is such widespread behaviour that tools to automate this process like [FileBot](http://www.filebot.net/) are very popular with regular users of p2p software.

If it was possible to define a list of directories which are constantly monitored with the file hashes beeing compared to active torrents, one could easily seed (at least the main files of a directory) forever.

A manual retargeting [as µtorrent allows ](http://lifehacker.com/5612315/how-to-seed-moved-or-renamed-files-in-bittorrent) is not sufficient because even nice people are lazy and don't want to waste disk space by storing the files in multiple times.

**Comment by synctext** [comment]
closing this feature request from 5 years ago. Could re-open if needed, we aim for the Youtube model: never worry about files; just stream.
