### ISSUE TITLE
[enhancement] save a result page to a tab 

### ISSUE THREAD

**Issue by r1k0** [Tribler/tribler#1047]
Given the time a search takes (generally have to click every few minutes and/or wait a few hours) a user might much like to save the actual results of a search in a tab below Results so he can input another search while not losing the results of the previous search.

Clicking on the tab could fillup the Search input bar and let the user refresh the search.
Maybe have an option to restrict the number of tabs to an appropriate default. 

The idea is to do multiple Search in parallel and ideally have an option that would autorefresh/search those results tabs every few minutes.

Is that reasonable?

**Comment by synctext** [comment]
closing this feature request from 5 years ago. Could re-open if needed, search is sufficiently fast now.
