### ISSUE TITLE
still troubles, w uninstall path &

### ISSUE THREAD

**Issue by irungentootoo** [Tribler/tribler#1048]
app try uninstall tribler from c:\program files (x86)\tribler but app instaalled on other disk path.
& 640version too loong checking update (stuck) & stuck on "starting session and ungradiong database" too long

**Comment by whirm** [comment]
I can't reproduce this issue, If you are still getting it with the latest release, please create a new issue with detailed steps on how to reproduce it.

Thanks for your report!
