### ISSUE TITLE
Redesign of the Family Filter

### ISSUE THREAD

**Issue by gjedeer** [Tribler/tribler#1052]
It looks like anything with the word "girl" in it is marked as "Xxx" and blocked by the family filter. It's a word which generates a lot of false positives:

http://www.imdb.com/find?q=girl&&s=tt&ref_=fn_al_tt_mr

**Comment by LipuFei** [comment]
This could be a good enhancement although it's for videos:
https://github.com/ryanjay0/miles-deep

**Comment by ichorid** [comment]
State-of-the-art of the text classification today is [BERT](https://towardsdatascience.com/bert-text-classification-in-3-lines-of-code-using-keras-264db7e7a358).

To train it, we can use dataset from https://github.com/cental/stc described in [this](http://cental.fltr.ucl.ac.be/team/~panchenko/11_Camera_ready_paper.pdf) paper by https://github.com/alexanderpanchenko.

**Comment by qstokkink** [comment]
In the upcoming version of Tribler, the family filter is removed in its entirety.

Some rationale. We no longer have random torrents pushed onto people's front page, nor do we have thumbnails. The most people will see is offensive torrent titles and, hopefully, only if they were looking for them.

Perhaps we will come crawling back from this decision, but for now this issue has been superseded.
