### ISSUE TITLE
Anonymous UL/DL and Relay bandwidth usage ignores settings?

### ISSUE THREAD

**Issue by Arceliar** [Tribler/tribler#1053]
Tested using low bandwidth limits in the global (not per-torrent) settings, 16 kBps in the up and down directions.

The anonymous download test file seems to ignore it. I've seen it go as high as 120 kBps for 20-30 seconds at a time. Haven't tried other files yet. It spends long stretches of time at 0 kBp, so the average is probably below the limit, but I don't think that's intentional.

Using the same 16 kBps upload/download limit, relay traffic (or other background traffic coming from tribler, but symmetric enough that I assume it's relays) hovers at around 40-50 kBps for both upload and download. I thought maybe there's a minimum limit of 50 kBps, but setting everything to unlimited rates doesn't appear to increase bandwidth usage, so I think it's just being ingored for relay traffic too.

EDIT: the anon UL/DL is clearly visible in the speed graph for the test file. The suspected relay traffic was checked locally with iftop, and cross-checked with my router's bandwidth monitoring tools (in an otherwise idle network).

**Comment by Dmole** [comment]
Relay bandwidth seems to be saturating my connection choking out the downloads.

**Comment by ichorid** [comment]
related/duplicate of #2187

**Comment by Dmole** [comment]
@ichorid please close the newer of the duplicates.
1053 < 2187
