### ISSUE TITLE
Addressing the various security improvements

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1066]
Several issues where listed by "Yawning Angel" on Tor mailing list.

A casual review brought up some issues and we here provide a structured reaction to them. All issues are addressed already or will be fixed soon.
In general, the reviewer is correct, our code needed to be written more clearly and dead code was insufficiently cleaned. 
Issues:
- [x] issue: How not to do Diffie-Hellman:    key = pow(dh_received, dh_secret, DIFFIE_HELLMAN_MODULUS) which relied on gmpy.rand which was improperly seeded
- Reaction: We're actually not sure if this was the case, but we change the seeding of the gmpy.rand method to make sure were always using a seeded rand now. Moreover, we aim to replace this custom DH with the one implemented in M2Crypto asap.
- Reaction2: The gmpy.rand is cannot be saved, removed all references to it.
- [x] issue: one-time AES keys are generated with python's random.randint()
- Reaction: Fortunately not used for long-term keys, cause by the now famous ImportError which prevented PyCrypto from being imported.
- [x] issue: How not to do RSA: def rsa_encrypt(key, element):
- Reaction: RSA was never used in the tunnels, implemented while researching homomorphic encryption. This was for a paper published in WIFS 2013 http://dx.doi.org/10.1109/WIFS.2013.6707798. In this paper we implemented/evaluated three different approaches to Private Set Intersection-problem and tested their applicability in a P2P system. One of these approaches used RSA, which if used in unpadded mode (http://en.wikipedia.org/wiki/Homomorphic_encryption#Unpadded_RSA) has homomorphic properties. However, neither M2Crypto/PyCrypto allowed us to generate such an compatible key. Therefore, we wrote a small piece of python which allowed us to do so, hence the "compatible_key" method https://github.com/Tribler/tribler/blob/devel/Tribler/community/privatesemantic/crypto/rsa.py#L23.
This shouldn't be used in the wild, and wasn't/isn't used in the tunnels.
A pull request is submitted which fixes the dodgy optional_crypto file, by removing the optional part.
- [ ] issue: ECB-AES128 usage in the code.
Yes, we are aware of this issue. ECB-AES128 needs to be replaced asap with our new code that adds packet loss resilience. We aim to use CTR mode instead, and compensate for UDP packet loss with optimistic decryption that uses sequence number estimation, please read our detailed report: http://repository.tudelft.nl/view/ir/uuid%3Ace3bd867-6540-426d-87d0-348bdf78279d/

**Comment by whirm** [comment]
@synctext I guess this is not going to be finished for 6.4.2, right?

**Comment by NielsZeilemaker** [comment]
@whirm If you add the new dispersy pointer to next, I'll have a go at changing the tunnel community this weekend to see if I can get it too work with the new curve25519.

**Comment by whirm** [comment]
@NielsZeilemaker I guess you can branch off that branch and send one back to devel when it works :)
http://jenkins.tribler.org/job/GH_Tribler_pull-request-tester_devel/3143/

**Comment by synctext** [comment]
@Yawning  Creation of fake accounts remains a key vulnerability for self-organising systems in general and thus Tribler. I have now a draft 10-page write-up of how we aim to deal with Sybil attacks (3 defense layers). The recent Lizard Squad events make this quite relevant it seems. Have you worked on this research topic?

@NielsZeilemaker  impressive progress (https://github.com/Tribler/dispersy/pull/385). Thnx!

@whirm for 6.4.2 I guess we just ship it when we have sufficient bug fixes and improvements.

**Comment by NielsZeilemaker** [comment]
@Yawning I made most of the changes in a new pull request #1117.
Some remarks
* I'm not ckecking if the EXP() operations produced the point at infinity. I was hoping nacl is doing that for me crypto_box_beforenm method, is that right?
* I'm checking if the explicit nonce is overflowing, but not removing the circuit just yet.

Could you have a look if I made any blatant mistakes?

**Comment by synctext** [comment]
@Yawning Hopefully the most pressing issues in the code are fixed with Pull request #1188.

We're testing this now and are thinking of disabling the "exit" node functionality. Only offer downloading from hidden seeds in upcoming versions.

**Comment by whirm** [comment]
@synctext: @NielsZeilemaker said that this was basically done. Can you close this if it's OK?

**Comment by Baigle** [comment]
Any thoughts? http://arxiv.org/abs/1507.05724v1?utm_source=webopsweekly&utm_medium=email

**Comment by whirm** [comment]
I'm closing this, one, @synctext feel free to reopen it if it's not really finished.

**Comment by synctext** [comment]
An update on the 2018 status of these security matters for people which followed a link from 2014 or beyond.

Dispersy was correctly identified by Yawning Angel as a vulnerability. We have build a replacement. We are now in the process of removing Dispersy for [our new overlay](https://github.com/Tribler/py-ipv8).

**Comment by dreamflasher** [comment]
@synctext Was the last point `ECB-AES128 usage in the code` ever fixed? In 2014 you wrote this needs to be fixed asap – but the ticket was closed without ticking the checkbox/a later reference.

**Comment by egbertbouman** [comment]
@dreamflasher We moved to AES-GCM back in 2015, and more recently we started using ChaCha20/Poly1305. We just forgot to tick the checkbox.

**Comment by dreamflasher** [comment]
@egbertbouman Thank you very much for the swift update, I am very happy to hear that!
