### ISSUE TITLE
Session/LaunchManyCore needs refactoring

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1070]
Right now it's a mess, it has ad-hoc code to initialize each component individually, doesn't allow to be selective on what gets disabled, etc...

Let's talk about what we want to do with it and which problems we want to solve.

**Comment by vandenheuvel** [comment]
@devos50 Could you rename this one to a title including `LaunchManyCore`?

**Comment by qstokkink** [comment]
All of the features/refactorings in the OP have been implemented. Any other feature/refactoring requests should get their own issue.
