### ISSUE TITLE
Github's .zip archives don't contain the repo's submodules

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1077]
See #1075

We will have to manually upload the source for each release.

**Comment by mornfall** [comment]
Not true, current zip is missing dispersy again.

**Comment by whirm** [comment]
@mornfall yes, because github doesn't pack the submodules in. That's why I added a .tar.xz with the whole set of sources, including both submodules. I guess you misread my last comment :)

https://github.com/Tribler/tribler/releases/download/v6.5.0-rc6/Tribler-v6.5.0-rc6.tar.xz
