### ISSUE TITLE
DHT only used for get_peers

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/tribler#109]
If we can expose the DHT of LibTorrent we can remove our DHT implementation. Only a get_peers method is required.

After, we can redirect the miniswarm get_peers request and the DHT libswift node to use the libtorrent DHT instead.

**Comment by LipuFei** [comment]
@NielsZeilemaker @egbertbouman @whirm @synctext I guess this one can be closed.

**Comment by NielsZeilemaker** [comment]
Why? Is the pymdht already removed?

**Comment by LipuFei** [comment]
@NielsZeilemaker Not yet.

**Comment by whirm** [comment]
@devos50 do you want to take care of this guy?

**Comment by ardhipoetra** [comment]
Libtorrent has `get_peer_info` for every valid torrent handle. What's the different between this function and the one in pymdht?

**Comment by synctext** [comment]
@ardhipoetra Interesting API handle: http://www.rasterbar.com/products/libtorrent/manual.html#torrent-handle

Looks somewhat similar! pymDHT only returns non-validated IP addresses, Libtorrent tries a handshake with them.
Please try if you can download a .torrent file and access the peer info with this Libtorrent API. It initiates uTP handshakes then, so it really measures the swarm size. These calls might not be exposed in the Python wrapper.

**Comment by ardhipoetra** [comment]
@synctext yes, we can get list of peers using that function. And it's available on python binding. 

Test code can be found in [This gist](https://gist.github.com/ardhipoetra/457b35882d16289b4c50)

Tested with [this](http://linuxtracker.org/index.php?page=torrent-details&id=5aec5ee9f2d044316fe1de29d221452103ceb958&hit=1) and it was okay.

**Comment by whirm** [comment]
should we move this to an early milestone?

**Comment by ardhipoetra** [comment]
An update:

in version 1.1.0.0 (the most recent one), there are new function called 'dht_get_peers` providing a swarm's infohash. This can be done without joining the actual swarm. We have to monitor `alert` to get the peer list.

The bad news is, python binding implementation is not perfect, if I may say. The discussion in arvidn/libtorrent#602 still ongoing till now.

**Comment by whirm** [comment]
nice, let us know when it gets into a usable state!

**Comment by synctext** [comment]
update needed op dht_get_peers status in libtorrent and Python wrapper. Few years past since issue was created.

**Comment by devos50** [comment]
It seems that the `get_peers` method is exposed in libtorrent 1.1 but as @egbertbouman's comment says, we still require a manual DHT announce. I'm not sure whether that's possible yet.

**Comment by aldenml** [comment]
@devos50 I think `session_handle:: dht_announce` is what you are looking for

**Comment by devos50** [comment]
I guess this issue has been sufficiently addressed.
