### ISSUE TITLE
v6.3.5: All files in the torrent has the same downloaded percentage

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#1108]
Total downloaded percentage is shown and grows instead of individual file percentages.

This is definitely not true, as some files are completed (I used "Include" and "Exclude" funtions multiple time, also restarted Tribler from crash/freeze on this torrent).

**Comment by whirm** [comment]
Can you reproduce it with latest release?

Thanks!

**Comment by whirm** [comment]
I've just downloaded a multifile torrent, each file % gets updated correctly with latest ```next```.
Closing this one. 
If you are able to reproduce this with 6.4.2 when it gets released, please open a new issue.
