### ISSUE TITLE
Support for Webtorrent

### ISSUE THREAD

**Issue by HostFat** [Tribler/tribler#1111]
Have you seen this project?
https://github.com/feross/webtorrent

It needs support from clients, so maybe you can give a look :)

**Comment by gjedeer** [comment]
Sounds like a bad idea for the overall network - browsers are designed to consume content and that's what people use them for. I don't imagine normal people leaving a browser tab open just to seed the video they just watched. They will mostly leech.

**Comment by whirm** [comment]
I agree with @gjedeer, it also fragments the network without adding any advantage other than being able to run it in a web browser.
I don't think we will ever implement this.
