### ISSUE TITLE
After updating from v6.3.5 to v6.4.1, it stuck on "Checking tribler version"

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#1115]
No messages get logged to console.

**Comment by vi** [comment]
After moving away `~/.Tribler` to `~/.Tribler.bak` it got though. After `cp  ~/.Tribler.bak/dlcheckpoints/* ~/.Tribler/dlcheckpoints/` it also remembered the downloads.

**Comment by whirm** [comment]
@vi Could you confirm that copying the old DB back to .Tribler makes Tribler fail again?

**Comment by vi** [comment]
Backed up current `.Tribler`, restored old v6.3.5 `.Triber`. 

`Checking Tribler version...`

I have just noticed that it's also big: sqlite directory is 543.7MiB. Maybe it's just slow? I see some CPU and IO activity...

**Comment by whirm** [comment]
@vi we've seen that the torrent migration is quite slow on some machines but we haven't investigated further as we are seriously thinking about killing the torrent collection altogether and just share magnets with some metadata associated.

I've sent a pull request that should deal with the cross-filesystem issues you where having.

Do you still have the 6.3.5 data around to test again with 6.4.2?

Thanks!

**Comment by vi** [comment]
The migration can be slow, but in this case it should be mentioned in the message to use (not just `Checking Tribler version`), 

I have `~/.Tribler` backup for 6.3.5, but not the torrent collection was removed.

> just share magnets with some metadata associated.
Will Tribler be self-sufficient, i.e. will the network of only other Tribler clients, without other non-Tribler torrent peers still work?

**Comment by whirm** [comment]
The part I've seeing being slow was the torrent parsing/migration and you see the infohashes passing trough. 
In your case it was before that?
I'll have a look and see what's going on before we get to that point.

RE being self-sufficient: yes, it would collect the torrent info from the DHT as when you click on a standard magnet link.

**Comment by whirm** [comment]
@vi: We are working on a branch  which uses a leveldb based torrent store instead of the collected_torrent_files directory:

https://github.com/whirm/tribler/tree/torrent_store_migrator

That branch includes the upgrade code too, so it will ingest all your torrent files into the new store.

It will also store the torrent stuff in ```.Tribler``` instead of ```TriblerDownloads```, just so you know.

Could you put a copy or your old backup in place and tell us how it behaves for you?

Have in mind that you will need to install python-leveldb to be able to run this branch.

Thanks!

**Comment by whirm** [comment]
As a note for comparison: On my machine it takes about 10 minutes to do the whole verification/migration procedure with a 2.1 GB collected_torrent_files directory.

**Comment by vi** [comment]
Restored v3.6.5-backed-up `.Tribler`, tried running whirm/tribler@3676ea36c0b2f33023ae3fd7f3f4f3248c191d57. It "ingested" the collected torrent files, but after that stopped `Failed to upgrade the on disk data.` with 

```
ERROR   1422662120.63         upgrade:70    failed to upgrade: Cannot call rmtree on a symbolic link
Traceback (most recent call last):
  File "/home/vi/home/tribler/tribler/Tribler/Core/Upgrade/upgrade.py", line 54, in check_and_upgrade
    yield torrent_migrator.start_migrate()
  File "/home/vi/home/tribler/tribler/Tribler/Core/Upgrade/torrent_upgrade64.py", line 64, in start_migrate
    self._migrate_torrent_collecting_dir()
  File "/home/vi/home/tribler/tribler/Tribler/Core/Upgrade/torrent_upgrade65.py", line 70, in _migrate_torrent_collecting_dir
    rmtree(self.torrent_collecting_dir)
  File "/usr/lib/python2.7/shutil.py", line 232, in rmtree
    onerror(os.path.islink, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 230, in rmtree
    raise OSError("Cannot call rmtree on a symbolic link")
OSError: Cannot call rmtree on a symbolic link
```

Probably it tried to rmtree the `~/TriblerDownloads/collected_torrent_files` which is a symlink to other partition in my setup.

By the way `~/.Tribler/collected_torrents` `~/.Tribler/sqlite` and `~/.Tribler/dlcheckpoints` are also good candidates to be symlinked away from "home" partition to "storage" partition...

Also note about free space pressure: LevelDB tends to perform slower and slower when out of disk space (it waits for some space to be reclaimed and attempts again to store the new data). Migration of `collected_torrent_files` to `collected_torrents` is not "streamlined", it temporarily requires twice as much of the storage. And if there is no free disk storage available, it will "stuck", not fail early.

Maybe you should delete each collected torrent file individually after adding them to LevelDB, and not try `rmtree` after the end (what if some unrelated data gets in the way?). Unknown unidentified files (not a torrent or thumbnail or something like that, with non-standard name) should not be removed.

Also I think location of "heavy" caches and settings should be overridable, and by default (on Linux) it should be `~/.cache/enki/` and `~/.config/enki/` respectively (and respect `XDG_*`) not just big `~/.Enki`.

**Comment by whirm** [comment]
I don't think we are going to support symlinking stuff around any time soon. 

However some paths can be configured trough ```libtorrent.conf``` and we would accept PRs that add some more if they make sense.

RE deleting torrent files when adding them to LevelDB, that's how we are doing it: https://github.com/whirm/tribler/blob/torrent_store_migrator/Tribler/Core/Upgrade/torrent_upgrade65.py#L106

The only thing that could be done is to make sure we have enough space in the target dir for the upgrade procedure to succeed.

**Comment by whirm** [comment]
@vi I've created an issue for the disk space thingie and I'm closing this one as your issues has to do with manually symlinking stuff around which you should be able acomplish by editing paths in ```libtribler.conf````

**Comment by vi** [comment]
Missing link to the disk space issue: https://github.com/Tribler/tribler/issues/1189
