### ISSUE TITLE
exception.attribute error

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1136]
Failing when installing this version on Mac
http://jenkins.tribler.org/job/Build-Tribler_OSX_next/101/

Or is the .Tribler directory messed up?
(version number differs, also got error with older version)
![tribler_mac_error_after_tunnelcommnity_optout](https://cloud.githubusercontent.com/assets/325224/5668987/4d4965b2-9774-11e4-9bfe-cfcbb33e4c53.png)

**Comment by LipuFei** [comment]
@synctext Do a cleanup to remove all the `*.pyo` and `*.pyc` file to see if it works:
```
find -name '*.pyc' -delete
find -name '*.pyo' -delete
```

**Comment by LipuFei** [comment]
Should be fixed by #1138. Please try again with the latest `next`.

**Comment by synctext** [comment]
Sorry, forgot to mention...
Works smooth with tunnelcommunity enabled.
But when disabled, the normal download popup fails with this error.

**Comment by LipuFei** [comment]
@synctext I also found the problem, and I just merged another PR #1138 to fix this. Please fetch the latest `next` and try again.

**Comment by LipuFei** [comment]
@synctext It's fixed in #1138.
