### ISSUE TITLE
Please add setting to limit connections

### ISSUE THREAD

**Issue by shadowym** [Tribler/tribler#1141]
Tribler is overwhelming my router and causing slow downs.  I don't have this problem with uTorrent.  Probably because it has a setting to limit the number of connections.  Please consider adding this feature to Tribler.  Other than that I think it's great.

**Comment by David-Leudolph** [comment]
I agree. It would be nice to have such an option.

**Comment by dufernst** [comment]
Bump.
It actually crashes my router while not having added any channels to it and having only one active download (a Ubuntu torrent obviously ;)).

Details of the router we have can be found here:
http://experiabox-info.nl/images/Handleiding_KPN_ExperiaBox_ZTE_VDSL.pdf

**Comment by devos50** [comment]
Fixed in #2622

**Comment by GrimBShrout** [comment]
Agreed. Tribler has an overwhelming impact due to the amount of sockets it attempts to create. 

Only problem is it utilizes both UDP & TCP for transport protocols, it may be more difficult to do. If it were only TCP this most likely would already be an option.
