### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by tukkek** [Tribler/tribler#1142]
Following the steps outlined for Debian and got this exception on running tribler.sh

Traceback (most recent call last):
  File "Tribler/Main/tribler.py", line 28, in <module>
    run()
  File "Tribler/Main/tribler.py", line 24, in run
    from Tribler.Main.tribler_main import run as run_main
  File "/home/alex/bin/tribler/Tribler/Main/tribler_main.py", line 18, in <module>
    from Tribler.Main.Utility.compat import (convertSessionConfig, convertMainConfig, convertDefaultDownloadConfig,
  File "/home/alex/bin/tribler/Tribler/Main/Utility/compat.py", line 17, in <module>
    from Tribler.Core.SessionConfig import SessionStartupConfig
  File "/home/alex/bin/tribler/Tribler/Core/SessionConfig.py", line 20, in <module>
    from Tribler.Core.defaults import sessdefaults
  File "/home/alex/bin/tribler/Tribler/Core/defaults.py", line 22, in <module>
    from collections import OrderedDict
ImportError: cannot import name OrderedDict

**Comment by LipuFei** [comment]
@tukkek `OrderedDict` is new in python 2.7. Could check your python version?

**Comment by whirm** [comment]
We should add a python version check.

**Comment by tukkek** [comment]
Please do. I have been searching for something like this for a while now. I think it is a major trend on technology, with huge implications for worldwide culture.

Having it not even run was a disappointment not to mention an entry barrier if I ever saw one. If you let me know when progress is made I'd be happy to give it another try.

**Comment by whirm** [comment]
@tukkek I've just sent a PR to ```next```, could you check that branch out once it gets merged?

**Comment by tukkek** [comment]
I did my best to find this info on github but I am not cloning everything just to `git log`. If you can please update me when it gets merged.

**Comment by whirm** [comment]
@tukkek  You should have followed this pull request I referenced https://github.com/Tribler/tribler/issues/1153, it's merged now. :)
