### ISSUE TITLE
GPG signed builds needed

### ISSUE THREAD

**Issue by taoeffect** [Tribler/tribler#1152]
You are distributing security-critical software, the responsible thing to do is to post the developer GPG keys somewhere and for each binary that you distribute include a link to the signature for that binary on its download page.

Without doing this you are exposing your users to potential malware, etc.

Thank you,
Greg

**Comment by whirm** [comment]
We are going to GPG sign a SHA256.txt along with the released files.

Thanks for reminding us of this!

**Comment by whirm** [comment]
Last RC already came with an PGP armored SHA1.txt file.

I'll put the public key on the git repository ASAP.
