### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_peers'

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#1157]
```
Traceback (most recent call last):
  File "/home/vi/home/tribler/tribler/Tribler/Main/tribler_main.py", line 716, in sesscb_states_callback
    self.tunnel_community.monitor_downloads(dslist)
  File "/home/vi/home/tribler/tribler/Tribler/community/tunnel/community.py", line 1226, in monitor_downloads
    self.create_rendezvous_points(info_hash, hops=hops.get(info_hash, 2))
  File "/home/vi/home/tribler/tribler/Tribler/community/tunnel/community.py", line 1288, in create_rendezvous_points
    self.trsession.lm.mainline_dht.get_peers(info_hash, Id(info_hash), dht_callback)
AttributeError: 'NoneType' object has no attribute 'get_peers'
```

This message is printed to console each 3-4 seconds.

Version: 29a52aaa153276e2890c33aab7a412f13be90591 , with appropriate submodules.

On v6.4.1 it was the same.

**Comment by whirm** [comment]
Let's wait for the whole crypto overhaul to be finished before dealing with these bugs as they will probably not be there anymore. 
Depends on https://github.com/Tribler/tribler/issues/1066

**Comment by whirm** [comment]
@rjruigrok I'm assigning a few issues that depend on the tunnel community refactor, I guess most of them will be just checking that they don't happen anymore and closing them.

**Comment by rjruigrok** [comment]
@whirm Thats fine. I'll check them in the next few days.

**Comment by rjruigrok** [comment]
Does not happen anymore. :)
