### ISSUE TITLE
anonymous proxy popup needs improvement

### ISSUE THREAD

**Issue by corpaul** [Tribler/tribler#1169]
The text is quite hard to read and the choices are not really clear... this popup can use some improvement :) (e.g. make 2 images for choices Anonymous / Non-anonymous and hide the text that is in the popup right now behind a link or something)

**Comment by whirm** [comment]
It's important that people read the text so I wouldn't hide it behind a link, but we really should improve the actual text.

**Comment by corpaul** [comment]
Yes, I was thinking something more along the lines of this

https://moqups.com/corpaul/DG6zFbQA

**Comment by whirm** [comment]
Yeah, something like that would be nice...

**Comment by whirm** [comment]
Closing this one as the plan is to remove the dialog entirely on the next release.
