### ISSUE TITLE
No longer serve by default as an "Exit node" flag

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1174]
By default Tribler acts as an exit node and relay for others.

Numerous users demand that we only enable relaying by default.
The "exit node" functionality should only be enabled when the user explicity configures this in the configuration panel. 
An exit node user also needs to be connectable in order to support the hidden seeding functionality.
Provide an informational popup _or_ check the Tribler connectability status and only then enable this exit flag.

Implemented as a simple addition to the introduction-request message. Each anonymous relay tunnel community member advertises with two flags if: they are willing to serve as an exit node and if they are connectable.

UPDATE: We're thinking of disabling the "exit" node functionality. Only offer downloading from hidden seeds in upcoming versions.

UPDATE2: in the upcoming version we can add with minor effort an "Exit node" flag to the introduction-request (plus also a connectability flag). So we don't need the credit mining fully operational for proper seeding and finding seeds.

**Comment by whirm** [comment]
Depends on #1066

**Comment by synctext** [comment]
After more thinking and forum discussion I'm now in favor of just adding an "Exit node" flag  in the config screen. It's a quick fix and then we can decide later if we go with the "only darknet mode".
Forum post by Roli: http://forum.tribler.org/viewtopic.php?f=2&t=7143&p=11662&sid=83bbed72b5ce09a38cf3432c8f4110d0#p11635

**Comment by rjruigrok** [comment]
I'll try to get this working in the coming week.

**Comment by synctext** [comment]
@rjruigrok Good to hear progress on this ticket.

@whirm @LipuFei : please review the approach taken by Rob
https://github.com/Tribler/tribler/compare/devel...rjruigrok:exitnode-switch

As suggested we should release this soon. When this is done and there are no other pressing open issues (DB upgrade fully done?) we can build an RC1 and start testing a new release!
