### ISSUE TITLE
Overridable cache storage; more XDG on Linux

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#1186]
Currently Tribler uses one big `~/.Tribler` directory where both configs and gigant SQLite database is stored. Maybe a LevelDB with torrent files going to be there as well.

It is not optimal and versatile.

Tribler's directory should be split in two parts: cache (collected torrent files, big sqlite database) and config (settings and current downloads, subscribed channels, maybe some little user-specific database, etc.).

The cache directory should be overridable. It can span multiple gigabytes, so user may want to store it separately (like downloads).

On GNU/Linux default cache and settings directories may be [`~/.cache/tribler` and `~/.config/tribler`](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html), respecting XDG's environment variables.

**Comment by synctext** [comment]
Respecting the XDG environment variables would be a great thing to have. If somebody can work on this as a nice "Tribler introduction exercise" that would be really great. Love to accept a pull-request on this.

We're understaffed in Tribler. The main developers focus until the summer is getting anonymous downloading+seeding working smoothly plus fixing (severe) performance/usability bugs.

**Comment by whirm** [comment]
@vi the torrent store is already configurable trough ```libtribler.conf``` btw.

**Comment by vi** [comment]
I think this setting should be in GUI.

And it should affect not only torrent storage, but also the big SQLite database.

**Comment by whirm** [comment]
@vi I agree, but that would mean storing the private data (private keys, messages generated by you, etc...) in a separate DB, so that's not a trivial task. 

You could create an issue for exposing some of this paths on the settings window tough. That's would be a task more likely to be picked up by a volunteer.

**Comment by synctext** [comment]
Gigachannels now replace all LevelDB stuff with Magnet link only approach.
