### ISSUE TITLE
Tribler should check for free disk space when executing various tasks

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1189]
For instance, when migrating to the new torrent store, we will need to see if we have roughly the same free disk space in `.Tribler` than `collected_torrent_files` is taking at that moment.

**Comment by vi** [comment]
I think disk space should be checked not only when migration, but in other cases as well.

There may be GUI setting "Disk space to keep reserved", and if Tribler detects that free space is less than this thesholder, it stops growing the data (or downloading, if the thesholder is triggered on TriberDownloads's partition).

**Comment by xoriole** [comment]
Fixed by https://github.com/Tribler/tribler/pull/7496
