### ISSUE TITLE
Streaming doesn't work (win7, a hint to localize the problem needed)

### ISSUE THREAD

**Issue by YakovL** [Tribler/tribler#1194]
So, my problem is basically -- streaming doesn't work. Which means:
* the grey line that marks download progress is shown and move to the right;
* the video is actually downloaded (I'm even capable of watching it with VLC more-or-less realtime -- sometimes I have to restart it, though);
* the orange circle that shows the position stands still, both "pause" and "stop" are displayed orange;
* if I move it to an arbitrary point (already downloaded), the screen shows the download splash-screen (grey circle, "Loading 0%" and it doesn't change), the "play" button is displayed grey and "stop" -- orange

I guess, it's not with everybody on Windows 7, and I have to mention that I have "similar" problems with Popcorn Time, too: https://git2.popcorntime.io/jira/browse/PT-1425

**Comment by whirm** [comment]
@LipuFei can you try to reproduce it on the win7 box? Thx!

**Comment by YakovL** [comment]
Any progress with this? By the way, Popcorn Time team have solved the similar problem: https://git.popcorntime.io/popcorntime/desktop/issues/49

**Comment by whirm** [comment]
@YakovL That is fixed and working on our testing W7 box for current devel.
Next release should be fine for you too.

**Comment by YakovL** [comment]
@whirm just to be sure, which release should I be looking at?

**Comment by whirm** [comment]
The next one will be v6.5
