### ISSUE TITLE
Making the list of torrents/channels/etc into a series of lists.

### ISSUE THREAD

**Issue by brandc** [Tribler/tribler#1195]
I have noticed that a significant amount of CPU time is used displaying lists of torrents/channels/etc. 

Dividing the lists into pages of lists each containing 50 or so items each should solve the problem.

**Comment by whirm** [comment]
Have you profiled Tribler and found out that the GUI part rendering the list consumes a lot of CPU or you just saw that there's a lot of CPU usage when searching for stuff? Have in mind that when doing searches you will (hopefuly) receive lots of responses which have to be cryptographically verified and processed, stored to disk, etc...

**Comment by brandc** [comment]
Disconnected from the internet and put .Tribler on ramdisk.

**Comment by whirm** [comment]
That would save you IO more than CPU time.

**Comment by brandc** [comment]
If it is not connected to the internet, and all queries are from ram disk then what could it be doing to cause such latency?

**Comment by whirm** [comment]
A bunch of different things, but the way to find out is to profile the process.

**Comment by synctext** [comment]
That is an interesting (offline) experiment...!

Perhaps this is due to the feature that we reduce screen flickering. If we do a wx.repaint every time new search results come in, the result is continues screen rewriting. Very annoying., therefore we bundle the rewrites and only repaint every .5 - 1 second (vaguely recall).

**Comment by brandc** [comment]
Sorry, it took me a little while to post this.

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.004    0.004   94.860   94.860 Tribler/Main/tribler.py:27(run)
        1    0.001    0.001   91.719   91.719 /home/iron/tmp/tribler__/Tribler/Main/tribler_main.py:1098(run)
        1    0.000    0.000   71.853   71.853 /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py:8008(MainLoop)
        1    0.000    0.000   71.852   71.852 /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py:7299(MainLoop)
        1   24.200   24.200   71.852   71.852 {wx._core_.PyApp_MainLoop}
 3840/436    0.209    0.000   44.409    0.102 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/__init__.py:109(invoke_func)
       31    0.194    0.006   32.701    1.055 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_body.py:1079(CreateItems)
       28    0.005    0.000   27.161    0.970 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_body.py:1026(OnIdle)
      156    0.118    0.001   26.300    0.169 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_body.py:23(__init__)
      151    0.021    0.000   26.234    0.174 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_item.py:57(__init__)
      150    0.009    0.000   26.075    0.174 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_item.py:753(__init__)
      150    0.044    0.000   24.519    0.163 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_item.py:757(AddComponents)
      151    0.030    0.000   23.303    0.154 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_item.py:297(AddComponents)
  344/261    0.027    0.000   21.440    0.082 /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py:14665(<lambda>)
      151    0.164    0.001   16.448    0.109 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_item.py:63(AddComponents)
      156    0.348    0.002   14.246    0.091 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_body.py:58(AddComponents)
      7/6    0.001    0.000   13.842    2.307 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_body.py:926(SetData)
      7/6    0.000    0.000   13.840    2.307 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_body.py:941(doSetData)
      7/6    0.005    0.001   13.839    2.306 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_body.py:965(__SetData)
    13/12    0.001    0.000   12.991    1.083 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/__init__.py:122(invoke_func)
    22/20    0.001    0.000   11.038    0.552 /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py:7692(Yield)
    22/20    1.936    0.088   11.037    0.552 {wx._core_.Yield}
        1    0.005    0.005   10.635   10.635 /home/iron/tmp/tribler__/Tribler/Main/tribler_main.py:141(__init__)
        2    0.000    0.000    8.397    4.198 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list.py:260(_on_data)
        2    0.000    0.000    8.395    4.198 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list.py:1902(SetData)
        8    8.074    1.009    8.074    1.009 {time.sleep}
      150    0.056    0.000    6.723    0.045 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_item.py:765(AddButtons)
      300    0.065    0.000    6.647    0.022 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_item.py:308(AddButton)
        1    0.010    0.010    6.588    6.588 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/MainFrame.py:122(__init__)
       60    0.026    0.000    5.882    0.098 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_body.py:757(OnChange)
        1    0.000    0.000    5.525    5.525 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list.py:352(_on_data_delayed)
        1    0.041    0.041    5.524    5.524 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list.py:356(_on_data)
        1    0.006    0.006    5.445    5.445 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list.py:2109(SetData)
      756    0.095    0.000    5.058    0.007 /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_controls.py:1130(__init__)
      464    0.198    0.000    5.007    0.011 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/widgets.py:1001(__init__)
      695    0.062    0.000    4.979    0.007 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/widgets.py:23(__init__)
      756    4.831    0.006    4.844    0.006 {wx._controls_.new_StaticText}
        1    0.003    0.003    4.043    4.043 /home/iron/tmp/tribler__/Tribler/Main/tribler_main.py:954(OnExit)
      301    0.038    0.000    3.995    0.013 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/widgets.py:1095(__init__)
      961    0.097    0.000    3.755    0.004 /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_windows.py:62(__init__)
        3    0.000    0.000    3.744    1.248 /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_windows.py:701(ShowModal)
        3    3.472    1.157    3.744    1.248 {wx._windows_.Dialog_ShowModal}
 1980/608    0.700    0.000    3.638    0.006 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_body.py:197(AddEvents)
      836    0.030    0.000    3.558    0.004 /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py:10555(Layout)
      836    3.490    0.004    3.527    0.004 {wx._core_.Window_Layout}
      961    3.505    0.004    3.507    0.004 {wx._windows_.new_Panel}
     7259    0.387    0.000    3.284    0.000 /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py:3890(Bind)
        1    0.028    0.028    3.137    3.137 /home/iron/tmp/tribler__/Tribler/Main/tribler_main.py:15(<module>)
      757    0.129    0.000    3.134    0.004 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_item.py:110(_add_control)
    18/12    0.007    0.000    2.826    0.235 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list.py:439(__init__)
      460    0.046    0.000    2.781    0.006 /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_controls.py:1052(__init__)
     7259    0.528    0.000    2.768    0.000 /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py:3992(Bind)
      172    0.007    0.000    2.747    0.016 /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py:9076(SetVirtualSize)
      172    2.740    0.016    2.740    0.016 {wx._core_.Window_SetVirtualSize}
      460    2.620    0.006    2.620    0.006 {wx._controls_.new_StaticLine}
      321    0.012    0.000    2.583    0.008 /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py:13053(Layout)
      321    2.469    0.008    2.571    0.008 {wx._core_.Sizer_Layout}
        2    0.002    0.001    2.519    1.259 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_details.py:121(__init__)
        1    0.002    0.002    2.413    2.413 /home/iron/tmp/tribler__/Tribler/community/tunnel/tests/test_libtorrent.py:45(start)
        1    0.000    0.000    2.389    2.389 /home/iron/tmp/tribler__/Tribler/Core/Session.py:463(start)
        1    0.009    0.009    2.379    2.379 /home/iron/tmp/tribler__/Tribler/Core/APIImplementation/LaunchManyCore.py:100(register)
    26232    0.556    0.000    2.240    0.000 /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py:3873(Connect)
      307    0.078    0.000    2.235    0.007 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_item.py:320(ShowSelected)
        1    0.001    0.001    2.014    2.014 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/MainFrame.py:445(startDownload)
      340    0.027    0.000    1.951    0.006 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_body.py:341(ShowSelected)
        1    0.020    0.020    1.884    1.884 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/MainFrame.py:12(<module>)
       86    0.025    0.000    1.879    0.022 /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/lib/scrolledpanel.py:46(SetupScrolling)
        1    0.004    0.004    1.867    1.867 /home/iron/tmp/tribler__/Tribler/Core/APIImplementation/LaunchManyCore.py:180(init)
        1    0.002    0.002    1.706    1.706 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/MainFrame.py:1009(OnCloseWindow)
    26232    1.685    0.000    1.685    0.000 {wx._core_.EvtHandler_Connect}
        4    0.000    0.000    1.647    0.412 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list.py:860(__init__)
 3548/322    0.696    0.000    1.611    0.005 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_body.py:342(IsSelected)
      197    0.121    0.001    1.552    0.008 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/widgets.py:1044(OnPaint)
        1    0.001    0.001    1.546    1.546 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_details.py:268(createAllTabs)
        3    0.001    0.000    1.487    0.496 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list.py:1012(__init__)
        1    0.000    0.000    1.474    1.474 /home/iron/tmp/tribler__/Tribler/Core/DecentralizedTracking/mainlineDHT.py:25(init)
        1    0.000    0.000    1.474    1.474 /home/iron/tmp/tribler__/Tribler/Core/DecentralizedTracking/pymdht/core/pymdht.py:50(__init__)
        1    0.001    0.001    1.458    1.458 /home/iron/tmp/tribler__/Tribler/Core/DecentralizedTracking/pymdht/core/controller.py:43(__init__)
        1    0.459    0.459    1.454    1.454 /home/iron/tmp/tribler__/Tribler/Core/DecentralizedTracking/pymdht/core/bootstrap.py:46(__init__)
       86    0.011    0.000    1.437    0.017 /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/lib/scrolledpanel.py:75(_SetupAfter)
      123    0.012    0.000    1.419    0.012 /usr/lib/python2.7/re.py:226(_compile)
      116    0.009    0.000    1.400    0.012 /usr/lib/python2.7/sre_compile.py:494(compile)
      118    0.002    0.000    1.394    0.012 /usr/lib/python2.7/re.py:188(compile)
      465    0.183    0.000    1.338    0.003 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/widgets.py:1016(SetBitmapLabel)
       13    0.001    0.000    1.302    0.100 /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_misc.py:1356(Notify)
       13    0.001    0.000    1.302    0.100 /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py:14760(Notify)
        3    0.000    0.000    1.291    0.430 /home/iron/tmp/tribler__/Tribler/Core/Video/VLCWrapper.py:18(invoke_func)
        1    0.000    0.000    1.286    1.286 /home/iron/tmp/tribler__/Tribler/Core/Video/VLCWrapper.py:46(_init_vlc)
        1    0.000    0.000    1.286    1.286 /home/iron/tmp/tribler__/Tribler/Core/Video/VLCWrapper.py:65(get_vlc_mediactrl)
      2/1    0.000    0.000    1.284    1.284 /home/iron/tmp/tribler__/Tribler/vlc.py:1297(__new__)
        1    1.282    1.282    1.284    1.284 /home/iron/tmp/tribler__/Tribler/vlc.py:3228(libvlc_new)
     3216    0.141    0.000    1.245    0.000 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/widgets.py:1076(Bind)
        2    0.001    0.001    1.244    0.622 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/channel.py:235(__init__)
     1130    0.044    0.000    1.222    0.001 /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py:9952(SetBackgroundColour)
        1    0.005    0.005    1.220    1.220 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/channel.py:2(<module>)
        2    0.005    0.002    1.214    0.607 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/channel.py:267(_PostInit)
        1    0.011    0.011    1.213    1.213 /home/iron/tmp/tribler__/Tribler/Main/Utility/Feeds/rssparser.py:2(<module>)
       21    0.042    0.002    1.180    0.056 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_body.py:523(__init__)
     1130    1.178    0.001    1.178    0.001 {wx._core_.Window_SetBackgroundColour}
       65    0.012    0.000    1.177    0.018 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/SearchGridManager.py:904(_do_gui_callback)
       10    0.004    0.000    1.175    0.118 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list.py:494(_PostInit)
      150    0.052    0.000    1.160    0.008 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list.py:2053(CreatePopularity)
       19    0.008    0.000    1.099    0.058 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/widgets.py:1482(InsertPage)
       18    0.022    0.001    1.089    0.060 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/list_body.py:1348(__init__)
       18    0.001    0.000    1.077    0.060 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/widgets.py:1479(AddPage)
      197    0.029    0.000    1.008    0.005 /home/iron/tmp/tribler__/Tribler/Main/vwxGUI/widgets.py:1069(GetBitmap)

**Comment by NielsZeilemaker** [comment]
Tribler constucts the lists in a lazy manner. When you scroll down it will create more items to fill the screen. No need for any paging.
