### ISSUE TITLE
Update database upgrade scripts

### ISSUE THREAD

**Issue by LipuFei** [Tribler/tribler#1228]
Put all database cleanup related tasks here so that we can easily modify the database upgrade script before release.

NOTE:  We only need to modify the upgrade script for task 1-3, because table and columns have already been removed from the SQL script.

 - [ ] Remove `click_position` and `reranking_strategy` column from `MyPreference` table
 - [x] Remove `UserEventLog` table
 - [x] Remove `TorrentSource` table and `source_id` column in `Torrent` table
 - [ ] Remove `TorrentCollecting` table
 - [ ] Remove `thumbnail` column from `Torrent` table
 - [ ] Replace `torrent_file_name` column in `Torrent` table with `is_collected` (an integer)
 - [ ] Remove `progress` column in `MyPreference` table
 - [ ] Move the tribler downloads dir from Desktop to Downloads #1099

**Comment by synctext** [comment]
No idea what the progress column in MyPreference is used for. Feel free to cleanup.

**Comment by LipuFei** [comment]
@whirm I was thinking about this. I don't think trying to migrate `TriblerDownloads` directory from `Desktop` to `Downloads` would not be a good idea because the `destination_dir` column in `MyPreference` table has references to where the downloads are. So if we do so, it will make a lot of troubles and we have to do a lot of work to make sure everything is ok...

So, let's close this.

**Comment by LipuFei** [comment]
@whirm If you agree, you can also close #1099

**Comment by whirm** [comment]
@LipuFei so the existing downloads will finish on the old place and the new ones will go to the new one.

Good enough.
