### ISSUE TITLE
Ability to change default page (home, downloads, etc.)

### ISSUE THREAD

**Issue by Cassolotl** [Tribler/tribler#1262]
(Most of the issues on this are really complex and way over my head, so I completely understand if this is a low priority, but it bugs me so here it is.)

I'm never interested in the Home page of Triblr. If there could be a setting that lets me set my default homepage upon opening Triblr that would be great. I'd like to set it to open on Downloads.

**Comment by devos50** [comment]
@whirm do we really want this one in 6.6?

**Comment by whirm** [comment]
No, we can have this done on the new gui instead, I'll move it

**Comment by synctext** [comment]
Homepage should become more interesting with recommendations.
