### ISSUE TITLE
Move FamilyFilter settings into Session

### ISSUE THREAD

**Issue by LipuFei** [Tribler/tribler#1264]
The FamilyFilter is in `Tribler/Core`, but the actual settings are in `Tribler/Main/Utility/utility.py`, called `family_filter`. Should we move it into Session instead?

**Comment by alex9311** [comment]
Hi, I'm part of a group for Delft's Software Architecture class and we are investigating Tribler. We are looking for smaller areas we can help in. If you decide that the FamilyFilter settings should be moved and you think it is something someone who isn't closely involved with your project could do,  please let us know! (@alex9311 or @JeffGoderie)

**Comment by whirm** [comment]
@alex9311 @JeffGoderie  could you join ```#tribler``` at freenode? We can find some tasks for you guys to choose from.

Thanks!

**Comment by synctext** [comment]
@alex9311 @JeffGoderie @whirm 
Nice to hear you are joining us for this coursework. FamilyFilter is a very boring thing to work on. 
We should be able to brainstorm and come up with something more exciting.
Is this suppose to be online-meeting and collaboration only? A physical 30minutes of interactivity might be productive+ get me to understand your talents and interests.

**Comment by synctext** [comment]
@alex9311 @JeffGoderie
After some thinking, are you specifically looking for smaller, clearly defined tasks, realistic for newcomers..?

**Comment by JeffGoderie** [comment]
Hi, the course asks for one or more useful contributions. However, the course has more aspects beside the contributions as well, making up for a large portion of the time set for the course, therefore we probably are not capable of doing a large contribution. So we'd say that smaller/medium sized tasks are preferred, and while they probably have to be suited for newcomers, they don't have to be fully defined I suppose.

As for the interactivity, this is allowed, and supposedly even recommended. There are actually 2 more members to our group: @binnimar & @PetervB.

**Comment by synctext** [comment]
@binnimar @PetervB @alex9311 @JeffGoderie
Before coding, the first easy tasks are documentation. Always a chronic lack of this.
What info did you miss when new to Tribler as an interested pro-user/developer and where can we put this info?

**Comment by JeffGoderie** [comment]
First of all, sorry for the late reply, I, and I think the rest of the team missed to notification of your reply.

When first trying to get Tribler working we encountered a dependency problem, which we managed to fix and we added the corresponding documentation to the README.md in the main project repo (https://github.com/Tribler/tribler/pull/1260).

One thing we noticed when going through the repository is that there are no specific guidelines for development. There is no explanation of where specific files should go (in what packages), no file naming policies, and no fixed rules on comments in code (some have a clear explanation, others have no comments at all). We did notice that there is a starting point for new developers (https://github.com/Tribler/tribler/wiki/Tribler-Development-Pointers), so our suggestion would be to come up with specific rules concerning this, and add it to this document (and add a clear link to this document in the main README.md)

Maybe we should move this conversation from this issue to a new one (or FreeNode), to avoid comment cluttering on this issue?

**Comment by LipuFei** [comment]
@binnimar @PetervB @alex9311 @JeffGoderie. Besides all the packages metioned in the `README.md`, you also need `libsodium` and `python-cryptography`. You can find the `.deb` packages in the following links:

1. http://packages.ubuntu.com/vivid/libsodium13
2. http://packages.ubuntu.com/vivid/python-cryptography

Another thing is that I am planing to do this recently, but then you will not be able to do it for your course project. Could you confirm that you have decided to do this? Then I can leave it to you. Thanks!

**Comment by JeffGoderie** [comment]
@LipuFei, those were the packages we had the problems with. Therefore we wrote the small addition to the README.md (Pull request #1260).

If we can help by writing guidelines for new developers, we would be glad to do so. Is there a specific project member to address for the required details (e.g. what guidelines you would like new devs to follow)?

**Comment by LipuFei** [comment]
@JeffGoderie You can ask me if you have any question. :)

For the coding standard, please follow PEP8.

**Comment by synctext** [comment]
@binnimar @PetervB @alex9311 @JeffGoderie
Development pointers documents are quite advanced. Can you try for 1 week to test,fix, update + expand the Dispersy tutorial (s) : https://github.com/Tribler/tribler/wiki#overlay-protocol-for-synchronization
That should be a realistic achievable task ?

**Comment by alex9311** [comment]
@synctext 
We will take a look at testing, fixing, and updating the dispersy tutorials over the next week. Thank you for the suggestion, we will be in contact!

@LipuFei (or @synctext  )
Are there any smaller code-related tasks we can try to take on as well?

**Comment by whirm** [comment]
@alex9311 you could check the issues marked with the ```needs volunteer``` tag some of them are easy, some others are quite isolated from the bulk of Tribler's code (IE the automatic version checker, auto-updater, etc...)

**Comment by LipuFei** [comment]
@alex9311 Unfortunately I think we have finished most small refactory tasks, but I will let you know when I find something.

**Comment by Hivemind-pulse** [comment]
This issue can be closed since it has become outdated. The FamilyFilter is no longer in `Tribler/Core`

**Comment by devos50** [comment]
@Hivemind-pulse the family filter is part of the Tribler core. Also, I moved the settings to the general configuration file a while ago so this issue is not relevant anymore.
