### ISSUE TITLE
Windows and OSX Build and Packaging Documentation

### ISSUE THREAD

**Issue by TorDevz** [Tribler/tribler#1266]
Hi everybody,

A few of us would like to contribute to tribler development but need help getting started. 

Could anybody update the build and packaging documentation for windows and OSX?

It seems some of the dependencies are broken, a requirements.txt or a shell/bat script and instructions would be very helpful for devs who want to get involved.

Thanks

**Comment by whirm** [comment]
@LipuFei could you take care of this?

@TorDevz in the meanwhile, you could take a look at ```debian/control``` so see the dependency list.

**Comment by devos50** [comment]
We have some documentation now about building/developing Tribler on OS X and Windows.
