### ISSUE TITLE
Just creating this so I can be informed when there is a windows version for non-coders.

### ISSUE THREAD

**Issue by Innomen** [Tribler/tribler#1271]
I hope someone comments here when that happens or tells me how to accomplish that end. Thank you for your time :)

**Comment by whirm** [comment]
What do you mean by a windows version for non-coders? An installer?

**Comment by Innomen** [comment]
Obviously.

**Comment by whirm** [comment]
Well, we've always had the download links on the main site: https://www.tribler.org/ 
Also, as any other github project you can go to the releases page: https://github.com/Tribler/tribler/releases and get the latest releases from there too.

**Comment by Innomen** [comment]
Well that's just another reason github is awful. I guess that's why you felt it wise to make your own page :)

Why I was mislead:

On the main page is says:
"Windows and OSX TODO"

And on "https://github.com/Tribler/tribler" releases is hidden in tiny grey on white text buried between "branches" and "contributors." And I wasn't even looking for that word. the whole rest of the net uses words like download and installer, etc.

But hey, thanks. Now I know. I'll give it a stab. :)
