### ISSUE TITLE
structured performance suite?

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1287]
in the far _far_ future after anonymous downloading is completed and used by 1+ million people, we can focus on performance. A structured performance test for Tribler is very difficult. What is typical network traffic to process? How good is the UDP NAT puncturing doing? What peers am I connected to for search?

We need to evaluate various options, as we already have a mature unit testing framework using Nose, crafted Gumby, messed around with systemtap, and developed Jenkins AllChannels experiments to detect issue. Starting on yet another framework is wrong. It is nice to see what others are offering: http://speed.pyston.org/comparison/ ( code: http://github.com/tobami/codespeed )

**Comment by synctext** [comment]
This ticket describes what is known as 'performance regression tests'. 
Excellent way to test the fresh new core, red flag if performance drops. For instance, below more than 2 standard deviations below the average of last 10 runs.

**Comment by synctext** [comment]
Next step on this issue is spend maximum a single day on listing the various performance parameters already in various issues (Tribler bootstrap time, maximum anon download speed, bootstrap time till first remote query). Then do a first throw away prototype in 1 week to learn from. Or another approach to go towards Github Actions integration. 
Traditional [graph-based benchmarking](https://stackoverflow.com/questions/7596612/benchmarking-python-vs-c-using-blas-and-numpy) example.
<img src=https://user-images.githubusercontent.com/325224/134493206-e03abf4a-c1e9-4daf-8f12-a038a46c2d87.png width=300>

**Comment by devos50** [comment]
Related work (GUI tester - runs every PR):

![screenshot_edit_channel_thumbnail_description](https://user-images.githubusercontent.com/1707075/134903955-6e4851f8-d2c0-4290-aab2-d4ee8c56b2d9.jpg)

See [here](https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_GUI_macOS/2896/artifact/tribler/src/tribler-gui/tribler_gui/screenshots/) for all screenshots taken by the GUI tester.
