### ISSUE TITLE
Is this azureus_properties needed?

### ISSUE THREAD

**Issue by LipuFei** [Tribler/tribler#1289]
Is this `azureus_properties` in torrent file and `TorrentDef` needed? No actual code is using those things.

**Comment by whirm** [comment]
I think this is from when we had the python torrent engine from ABC

**Comment by LipuFei** [comment]
@synctext @whirm Can we remove it?

**Comment by synctext** [comment]
sure, feel free to delete. Just be confidant it does not break stuff, like this that I found with a quick Google search: `azureus_properties/dht_backup_enable`
