### ISSUE TITLE
Strange files in Tribler/Core/Utilities

### ISSUE THREAD

**Issue by LipuFei** [Tribler/tribler#1290]
There are some strange files `Tribler/Core/Utilities`, such as `clock.py`, `Crypto.py`, and `encoding.py`. What are they used for?

**Comment by NielsZeilemaker** [comment]
I think clock was/is used by rawserver to do some crazy timing on windows, I tried to understand what was happening there -> failed. 
Crypto.py should die.
Encoding.py was build by boudewijn to be a more efficient type of serialization than json (it obviously isn't) but it's used by the channels I think so we can't get rid of it.

**Comment by synctext** [comment]
You do a call to simple `get_time()` and you end up with undocumented and for me unexpected `_MAXFORWARD` + `_FUDGE` added for free [clock.py : L21](https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Utilities/clock.py#L21) ?
Bloody h*ll or is this somewhat normal? Crazy timing?

After this grant writing is done, I should really spend a month playing and browsing our code base.

**Comment by NielsZeilemaker** [comment]
Like I said, I tried to make sense of it and failed. At first I thought this was fixable, but I think we should remove RawServer altogether to get rid of stuff like this.

**Comment by synctext** [comment]
Thnx @NielsZeilemaker 
@LipuFei  please work with @whirm and try to come up with an approach to clean this up.

**Comment by whirm** [comment]
The RawServer can't be removed until all the database stuff is moved out of the dispersy thread. I already implemented an endpoint that used the twisted stuff but we lost too much packets when IO was high. 
We started doing work in that direction (moving all the SQL stuff out of the constructor so they could be called from the database thread pool) but we found too many difficulties and we decided to leave it be for a while.
@synctext  Do you want us to give the DB stuff refactoring another shot so we can use the twisted endpoint again?

**Comment by NielsZeilemaker** [comment]
Alternatively we could use the standalone endpoint which is a thread
reading packets from a socket.
That's more or less what we need right?
2015-02-27 15:21 GMT+01:00 Elric Milon <notifications@github.com>:
