### ISSUE TITLE
Dispersy: peer discovery community (no more initial bootstrap servers)

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#13]
To bootstrap the search, allchannels and other communities we currently require connectable servers.

The aim of this enhancement is that all connectable peers automatically form a community bootstrap overlay. An alternative is to use our DHT, but connectability and lack of NAT-awareness make this less attractive. Similar to the Kazaa 2001 and Buddycast 2005 design we probably better use a local host-cache with the 200+ peers which we've seen in every community.

The Tribler installer will no longer include a hard-coded list of 16 bootstrap servers, but a "peer_cache.txt" with a few hundred peers to find the network. On a daily basis we refresh this peer_cache with stable connectable peers. Plus we put this updated file in the Linux/Mac/Windows installers.

**Comment by synctext** [comment]
See: https://github.com/Tribler/dispersy/issues/81
Code: https://github.com/Tribler/dispersy/blob/devel/discovery/bootstrap.py

**Comment by whirm** [comment]
@synctext but we aren't bundling one with Tribler yet, so the bootstrap servers are still needed.
