### ISSUE TITLE
Using Tribler with a VPN stops the download

### ISSUE THREAD

**Issue by xur86x** [Tribler/tribler#1301]
I recently got myself a VPN (Private Internet Access, to be exact) and it seems to conflict with tribler. As soon as I start it, tribler stops downloading/uploading. When I deactivate it everything runs as usual.
I liked the idea of having an extra layer of anonymity in addition to the 5 hops, but it seems that's not possible (yet).
It could be something in the settings of the VPN that causes this, but I don't think that's it.

**Comment by whirm** [comment]
Does restarting Tribler once the VPN is up help?

**Comment by xur86x** [comment]
I just restarted it and now I get 5KB/s speeds, which is at least something. How exactly does the reputation system work? Could it be that a VPN affects it?

**Comment by whirm** [comment]
Tribler doesn't notice when your network config changes, so you need to restart it.

Do you get 5KB/s by using tunnels and VPN?

The reputation system is still not working on the latest release, so don't worry about that.

**Comment by xur86x** [comment]
That low download speed could also come from less peers uploading. Since I can't be sure let's just ignore this for now. The VPN is as fast as my normal speed so I'm pretty sure it is not the cause for the low speeds. Is it possible that Tribler automatically recognizes if I connect to a VPN while running?

**Comment by whirm** [comment]
Tribler doesn't care/check if you are using a VPN or not.

If you are enabling the tunneling and using 5 hops, getting 5KB/s is perfectly normal, (each layer adds overhead, and the whole tunnel chain will go as fast as the slower link minus the overhead) 

Try lowering to 1 hop and see if it improves.

**Comment by xur86x** [comment]
It's actually getting around 15 to 50 now, so everything seems fine. Thanks for the help.

**Comment by whirm** [comment]
Enjoy! :)
