### ISSUE TITLE
Fix freeSpace() or drop it

### ISSUE THREAD

**Issue by LipuFei** [Tribler/tribler#1305]
`freeSpace()` in `SqliteCacheDBHandler.py` doesn't work any more. We either fix it or drop it.

Now every torrent is stored in `state_dir`, so if we want to check the disk space, we need to check the drive that holds `state_dir` but not `TriblerDownloads`.

**Comment by whirm** [comment]
We should fix it. And I guess we should check for disk space issues on all the directories Tribler writes data to.

**Comment by ichorid** [comment]
"It is better to ask for forgiveness than approval" (C)
