### ISSUE TITLE
make search community backwards compatible after Libswift removal

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1316]
avoid changing the Community ID.
As this would significantly reduce content discovery and search results.

**Comment by whirm** [comment]
This means either:
 * Reverting the PR I made removing the swift hash from the message and changing the CID and keep sending a dummy hash around with each query.
 * Re-implement it by using the community version system which we agreed on not using because it was buggy and test/fix the community version stuff.

**Comment by synctext** [comment]
Community version are to be avoided indeed, if possible.

What is the easiest solution?
How costly are dummy hashes ? would that confuse/cripple the older peers? (no Libswift to download).
A lightweight version system would be nice; keeping track of what version they speak and adjusting for each peer.

**Comment by whirm** [comment]
Well, reverting a commit is quite easy :D It won't confuse anyone, It's just wasted bandwith.

As for the lightweight version system, we should have to look at it.

**Comment by synctext** [comment]
OK. How many bytes are search-request and search-responses? How much do we waste then?

**Comment by whirm** [comment]
I don't know, I guess it mostly depends on the amount of items on the response message, Ill check tomorrow.

**Comment by whirm** [comment]
@synctext it's 2 bytes per torrent on the response message.

**Comment by whirm** [comment]
I'm reverting the changes and we can apply them again or a modified version of it when we decide what to do.
