### ISSUE TITLE
Remotetorrenthandler

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/tribler#1333]
ERROR   1426280548.55 RemoteTorrentHandler:615   failed to save data for download f907a77bdc515feb7e2701bf80d0094dbd1047cd.torrent: node port not int, but ```<type 'long'>```

**Comment by LipuFei** [comment]
@NielsZeilemaker Looks like the torrent file has a non-integer port number, but the message is missing the last part. It should be "but `repr(type(port))`". Could you find that missing part?

**Comment by NielsZeilemaker** [comment]
It said long, so I guess it's a simple fix
