### ISSUE TITLE
Custom python installation breaks tribler

### ISSUE THREAD

**Issue by tm45** [Tribler/tribler#1346]
When there is a file /usr/local/bin/python, tribler (6.4.3) won't start. After removing or renaming this file, tribler works fine. It seems tribler doesn't explicitly rely on system python (/usr/bin/python), but to python set by the current environment, which, if custom python is installed, is /usr/local/bin/python.

Please update all the shebangs in tribler's python files so that they explicitely refer to /usr/bin/python.
 .

**Comment by whirm** [comment]
If you want Tribler to use a specific python interpreter, just put its location first on your $PATH.  
Using the one in the environment is the right thing to do (allows one to use virtualenvs, etc.)

Thanks for your report.

**Comment by tm45** [comment]
I forgot to mention that I installed Tribler as Ubuntu package (tribler_6.4.3_all.deb). I agree that in source code shebangs must refer to python from current environment. But when packaged for Ubuntu or another OS, the program must explicitly rely on a particular python interpreter, which it should list as its dependency and which also must be installed by the package manager. The package tribler_6.4.3_all.deb depends on globally installed python-2.7, so the shebangs should be modified to refer to /usr/bin/python2.7.

**Comment by whirm** [comment]
Ah, that makes more sense :) 

I'll fix that.

Thanks for the report!
