### ISSUE TITLE
set_megacache() should go away

### ISSUE THREAD

**Issue by LipuFei** [Tribler/tribler#1355]
Those DBHandlers are just different wrappers for the database core. Since we always initialize the database core anyway, this settings option doesn't make any sense and the it simply makes tests fail because they forget to set megacache to True.

**Comment by LipuFei** [comment]
@corpaul Are you still having trouble with the megacache? I plan to fix this after #1353.

**Comment by corpaul** [comment]
well, not trouble, but I wanted to use a session in a unit test and to use the database I had to enable the megacache. I'm not using a session anymore but it still doesn't really make sense to me :)

**Comment by NielsZeilemaker** [comment]
Tribler should be able to run without a database, why do we always initialize the database?

**Comment by LipuFei** [comment]
Because we have to check the version number from the database.

**Comment by NielsZeilemaker** [comment]
Only if you have a database, if you turned it off it doesn't make sense to check the version

**Comment by LipuFei** [comment]
So now the upgrade happens before the session starts. During the upgrade, if there is no database, we will create one (which is the latest version), if there is a database, we check its version and do some upgrade if needed. So, after the upgrade, there will definitely be a working database.

I agree that Tribler should be able to run without a database, but putting the Tribler version into the database is creating this annoying trouble: we have to initialize the database first if we want to check the version and do upgrade.

**Comment by NielsZeilemaker** [comment]
The upgrade is started in the Session.prestart method, which already has access to the sessionconfig.
Simply check there if the megacache is enabled, and only perform the upgrade then.

**Comment by NielsZeilemaker** [comment]
In the Tribler upgrader check if db != NULL

**Comment by LipuFei** [comment]
ok, I will have a try.

**Comment by ichorid** [comment]
RIP Dispersy
