### ISSUE TITLE
Is it possible the video player in iOS/Android?

### ISSUE THREAD

**Issue by bagusflyer** [Tribler/tribler#1357]
I'm wondering if it's possible to run the video player running on mobile devices like iOS or Android? Thanks

**Comment by synctext** [comment]
We have initial code for running parts of Tribler on Android. The video player integration has prven to be difficult:
http://jenkins.tribler.org/job/Build-AT3-ARM-32/
http://jenkins.tribler.org/job/Build_Test-TSAP_Android_pull-requests/
http://jenkins.tribler.org/job/Build_Test-TSAP_Android_master/

Documentation in the form of 3 large reports: 
http://repository.tudelft.nl/search/ir/?q=android+tribler

**Comment by bagusflyer** [comment]
Thanks. I see. No iOS support by far?

**Comment by synctext** [comment]
no iOS sadly, Android app Beta now operational. closing...
