### ISSUE TITLE
Can't insert https:// link to torrent file into Tribler

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#1361]
For example, `https://tails.boum.org/torrents/files/tails-i386-1.3.2.torrent`.

**Comment by vi** [comment]
Can't insert `file://` link as well...

**Comment by whirm** [comment]
thanks for your report!

**Comment by vi** [comment]
For the utter completion there can also be `data:application/x-bittorrent,application/x-bittorrent...` URLs, but that's really extra.

Thanks for the implementation.
