### ISSUE TITLE
Icon in low resolution in Ubuntu 14.04

### ISSUE THREAD

**Issue by qherreros** [Tribler/tribler#1363]
The unity icon on the left bar appears to be in low resolution. It looks kind of ugly.
![screenshot from 2015-04-09 19 36 16](https://cloud.githubusercontent.com/assets/7406885/7074086/c6b54390-deef-11e4-9c83-598fdfe58db4.png)

**Comment by whirm** [comment]
thanks for the report!

**Comment by Dmole** [comment]
Is there an SVG version somewhere or does it need to be remade?
Also there should not be 2 of them;
5b70f64faddaebe479c1f0df153f02f5  src/tribler-gui/tribler_gui/images/tribler.png
7cc5ffc0090f0eaff811e8971effc650  build/mac/resources/icon_sources/appicon.png
