### ISSUE TITLE
Using tribler without "anonymous download" option

### ISSUE THREAD

**Issue by zuperia** [Tribler/tribler#1367]
What is when you forget  the anonymous download option or it didn't asked for because you choose streaming and there wasn't any anonymous option. Does it mean that tribler was completly not anonymous. Can you be caught easily because of this?

**Comment by whirm** [comment]
If you don't enable tunneling, it will download the torrent the same way any other torrent client out there.

Also, have in mind what the tunneling opt-in dialog tells you: With the current implementation, Tribler will act as an exit node for other peers' downloads too, which is really not advisable if you are not absolutely sure about what you are doing.

**Comment by zuperia** [comment]
Can you be tracked easily without anonymous option? Have there been cases when somebody used it in the past without anonymous option and was caught?

**Comment by whirm** [comment]
You will be in the same situation as if you would be using any other bittorrent client out there.
