### ISSUE TITLE
Anonymous downloading and fallback for end-to-end crypto

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1390]
The GUI should clearly communicate to the user:

 - [ ] "Download anonymously using proxies"
 Displays slider for selecting circuit length between 1 and 3 hops. 
 Always shown but grayed-out when box is not ticked.

Set your preference (radio button)
  - [ ] Find hidden seeders, fallback to anonymous Bittorrent after 2 minutes
  - [X] Find hidden seeders, fallback to anonymous Bittorrent after 5 minutes
  - [ ] Darknet Mode: no time-out and exclusively download with strong end-to-end encryption

Protection while seeding:
- [X] Darknet mode: Hidden seeding, never seed naked in Bittorrent (can not be disabled)

**Comment by rjruigrok** [comment]
Can be closed :+1:

**Comment by synctext** [comment]
For the archives..
This was replaced with concurrent download via exit nodes and hidden seeders. A superior approach.
