### ISSUE TITLE
Port forwarding: random port and always use that one

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1391]
Lock-down of anonymous downloads for unconnectable peers.

During the install process a random port is selected.
Communicated to the user that they need to port forward this.

Only connectable people have anonymity. Check if users are connectable and clearly communicate _why_ anonymous downloads are disabled...

**Comment by synctext** [comment]
Current code uses the special "-1" valued for port number. Then it's randomly selected _every_ session. Unpractical for port forwarding.

**Comment by lfdversluis** [comment]
@synctext Isn't an option in the settings panel a much better approach? Then the user can select the port (s)he wants and forward that one. Doesn't conflict then if something is running on the randomly selected port.

**Comment by synctext** [comment]
Yes, that randomly suggested port can be altered in the Settings panel.
The special "-1" construction should just go.

**Comment by lfdversluis** [comment]
Note to self. There is both the **dispersy** port and the **libtorrent** port (two distinct different ports). Both need to be connectible.

**Comment by lfdversluis** [comment]
Just an update. I've agreed with @devos50 (some weeks ago) that we can add a field in the settings menu of Tribler where one can set these ports, which Tribler then always will use.

We might need to adapt functions i.e. `getRandomPort` to never use a list of ports that **may** be used. So even though they are currently not in use, it still won't select them to be safe.

**Comment by qstokkink** [comment]
Most of this issue has been resolved. On the backend the port -1 is still used, but we will probably never get rid of this.

**Comment by themusicgod1** [comment]
What does this mean?  I see anonymous seeding seems to work even without an open port, but is this true for new torrents that you create/seed? "Only connectable people have anonymity." is this still in any sense true?   Since the "firewall status" port doesn't change doesn't that make it easy for ISPs to block all tribler traffic?

**Comment by qstokkink** [comment]
@themusicgod1 Even if you're not connectable, your download data gets anonymized. The information of this thread is horribly outdated (which I why I closed the issue).
