### ISSUE TITLE
[feature] Start streaming a video for a torrent outside the search

### ISSUE THREAD

**Issue by YakovL** [Tribler/tribler#1395]
Workflow: I founded a torrent outside Tribler's search engine and started downloading it with Tribler. I'd like to start Streaming the video from it. But as far as I can see, there's no such option for now. So, here's the feature request: please add this possibility (or let me know if I've overlooked it [in v6.4.3]).

**Comment by whirm** [comment]
You can double click on any video file on the torrent and streaming will start for it.

I guess it could be made clearer :)

Thanks for your report and feel free to reopen this issue if it's not working for you.

**Comment by YakovL** [comment]
@whirm Ah, not the torrent itself but even a file inside it.. ok, this sound logical, but only if one knows that this is implemented. I'd suggest that some sort of hint should be displayed when the download starts. The hint should point where to click to start streaming, I think.

**Comment by YakovL** [comment]
@whirm should I edit and reopen this issue?

**Comment by whirm** [comment]
@YakovL just create a new one :)
