### ISSUE TITLE
New version check from Tribler

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#14]
We should add a way to check if there's a newer Tribler release. At least for when it crashes so we don't get reports for possibly fixed bugs.

**Comment by whirm** [comment]
@synctext, @LipuFei I think we should start updating the version index again what do you guys say if we fix it for 6.5?

**Comment by NielsZeilemaker** [comment]
If you're going to change it, please upgrade it to https

**Comment by ThomasdenH** [comment]
Wouldn't it make sense to have an 'official' Tribler channel that uploaded all versions of Tribler? This way the updating would also be impossible to shut down.

**Comment by whirm** [comment]
@ThomasdenH Yeah, that would be cool. But it would take more work too...

**Comment by devos50** [comment]
Some work has been done on this issue in #2072 and it will be completed when the new GUI goes live in #2153.
