### ISSUE TITLE
set_max_desired_speed() in LibtorrentDownloadImpl

### ISSUE THREAD

**Issue by LipuFei** [Tribler/tribler#1405]
`set_max_desired_speed()` in `LibtorrentDownloadImpl` is never used. However, `RateManager` uses `LibtorrentDownloadImpl.get_max_desired_speed()` to set max speed, for example:
```
d.set_max_speed(dir, d.get_max_desired_speed(dir))
```
The `set_max_speed()` is defined in `DownloadConfig`.

@NielsZeilemaker Do you know if this is a bug or we are intended to do this?

**Comment by NielsZeilemaker** [comment]
I think we can remove our own custom ratemanager since swift is gone. Libtorrent has one of its own.

**Comment by LipuFei** [comment]
ok, I will do it.

**Comment by LipuFei** [comment]
@NielsZeilemaker BTW, how about the `SeedingManager`? Is it also related to swift?

**Comment by NielsZeilemaker** [comment]
I think so, and those policies as well.
I think the upload/download limits are already controlled by libtorrent, but verify that first.

**Comment by LipuFei** [comment]
ok. thanks!

**Comment by LipuFei** [comment]
I just checked. Both policies are still being used but we only need to use `LibtorrentMgr` to set the max upload and download speeds. So I think it is safe to remove those two policies and replace the speed setting code with things such as `LibtorrentMgr.set_upload_rate_limit()`.

**Comment by NielsZeilemaker** [comment]
I would add the runtime callback here
https://github.com/Tribler/tribler/blob/devel/Tribler/Core/APIImplementation/LaunchManyCore.py#L724
