### ISSUE TITLE
Remove some session locks in LaunchManyCore and Libtorrent

### ISSUE THREAD

**Issue by LipuFei** [Tribler/tribler#1410]
@NielsZeilemaker Since you have changed the RawServer to a twisted thing, I guess all those NoDispersyLocks do not make sense any more, and they can be removed, right?

**Comment by LipuFei** [comment]
I was trying to remove the policies and I found there is a lot of functions in LaunchManyCore and Libtorrent that have crazy chains of callbacks. It's already giving me a big headache... If it is ok to remove them, I will try to do it as well.

**Comment by NielsZeilemaker** [comment]
Sure, I would keep some of the locks around the download list
Op 8 mei 2015 12:36 PM schreef "Lipu Fei" <notifications@github.com>:

**Comment by vandenheuvel** [comment]
@devos50 Could you assign this to me? This is close to https://github.com/Tribler/tribler/issues/2286.

**Comment by synctext** [comment]
Closing this issue, please re-open if still relevant after ASYNC refactor work.
