### ISSUE TITLE
Filtered exit nodes

### ISSUE THREAD

**Issue by kb-** [Tribler/tribler#1411]
It would be nice to have some control over the exit node behavior to limit or avoid false copyright infringement notices. 3 possibilities could be offered :
- Exit node active
- Filtered exit node
- Exit node disabled

The filtered exit node could offer the possibility to filter the IP ranges from one's country (and maybe known VPN IPs) to avoid being monitored. There could also be a white list / black list of contents who can pass the exit node.

I don't know if it's very efficient but for now I'm filtering the IPs of my country with my firewall, for Tribler only.

**Comment by whirm** [comment]
The next release (6.5) will have points 1 and  implemented.

The second one shouldn't be hard to implement, simply by exposing the blacklisting feature in libtorrent ```session::set_ip_filter()``` on Tribler's UI,

Unfortunately, we are too understaffed to be able to give much priority to this issue. We would gladly accept it as a contribution tough.

**Comment by synctext** [comment]
Yeah, the prior default setting was not good. Exit node behavior now needs to be explicitly enabled.
