### ISSUE TITLE
Make the option to stream from the already started download more apparent

### ISSUE THREAD

**Issue by YakovL** [Tribler/tribler#1420]
So, as was pointed in comments to the previously formulated issue https://github.com/Tribler/tribler/issues/1395, it's not obvious that it's possible to start streaming from a torrent that is being downloaded.

Possible solutions to that: on download start from a file/magnet link (not from the Tribler's search, where the "stream" button is present), if the torrent contains a video file some sort of popup should appear: either with "It's possible to start streaming. To do so, open the "Files" tab below and double-click video" text or with some more direct button (if the torrent contains only one video file, it can be just "The torrent contains a video file. Start streaming?" dialogue with "yes" and "no" answers).

Best regards,
Yakov.

**Comment by YakovL** [comment]
Another option: in the list of downloads, in torrent details, files tab in lines corresponding to video files add "stream" button (or add somewhere in the "torrent details" tab).

**Comment by lfdversluis** [comment]
@YakovL A new GUI is being developed. This GUI will feature streaming more prominently :+1:

**Comment by synctext** [comment]
Thnx! we're now a Youtube-like GUI. closing...

**Comment by YakovL** [comment]
@synctext, could you specify what does "we're now" mean? In 6.5.2 (which is current version) it's still the old interface with this issue: I have to search for this github ticket to remember how to use streaming if I forgot to start with it.

**Comment by qstokkink** [comment]
@YakovL Even though the new GUI has been introduced a while ago, we're still in the process of stabilizing the code before we do a full release. To get an impression of the new Tribler, you can find the alpha release here: https://github.com/Tribler/tribler/releases/tag/v7.0.0-rc2
