### ISSUE TITLE
Donating to content-sharers right from the client?

### ISSUE THREAD

**Issue by YakovL** [Tribler/tribler#1421]
Ok, this is may be an idea that requires too much time/work investment (not only in terms of the client, also in protocol itself), but at least I'd like to hear what do you think.

### Inception
When a torrent client allows to search, download and even stream inside it, it's quite natural to forget that there are people behind the scene who produced the content/software. And to support them, a way to donate as simply as downloading/streaming is would be useful. Imagine the torrent list with the "download", "stream" and "donate" buttons.

### Implementation
Unfortunately, this requires changes not only in the client, but in the torrents themselves. But, actually, changes in the protocol/torrent format are not necessary: it's enough to add a new file, say named "donating details.txt" which contains some data. So, just the file format has to be designed and then the client can parse it.

### What a client can do, some challenges
So, what that "Donate" button can do? Well, I can see at least 3 roots:

1. pay from inside the app. This is the most user-friendly root, but of'course it creates a lot of issues and work required: implementation of the whole secure payment stuff, still security issues etc. Obviously this is not a way to go.
2. go to the page referenced in "donating details.txt". This is simple to implement and still can be quite effective: some services like paypal allow to pay in a couple of clicks. But here another security issue rises: the link can lead to a malicious website.
3. finally, instead of going to the page intended to be donation page, a client can do some "preview" of the address: either use whitelist, blacklist, visual preview of the address or another form. For whitelist, even approach 1. can be implemented afterwards

As there's still an amount of money to choose, I think visual preview (+ may be whitelist) is good enough since API of some services allows to form links that contain the amount of money. That can be references in "donating details.txt" as well: say, it contains

    https://somepayservice.com/index.html?donate=true&to=id12345&amount=%a

and when a user clicks "Donate", a dialogue shows the link and an amount of money that can be changed, and `%a` is substituted with the desirable amount, inserted via the dialogue.

Also, the "Donate" button can be shown when a movie has been watched via streaming.

### File format
For the approach 3. it seems that "donating details.txt" can contain just

    url: https://somepayservice.com/index.html?donate=true&to=id12345&amount=%a

and other lines can be reserved for other `name: value` stuff like

    recommended donation/default amount: 10USD
    description: [some url]
    where to find the next version (when the downloaded software is updated): [some url to torrent/magnet link]

Encoding of the file probably should be UTF-8.

### Other notes
Funny enough, if this works properly, this can even force some companies to try this share + dontae (or "pay what you want" [1]) model because of piracy: it may be more profitable to create a torrent with an official release and payment details and get donations from that rather than allow a pirate to create it and get money for "nothing".

Still, making money by others (not the author) may be an issue to think about.

There are some projects that look like they'll appreciate this (say, LibreOffice) and there's a number of succeses of the "pay what you want" model [1] like "In Rainbows" by Radiohead [2].

So, what do you think about the idea itself; and about implementing this in Tribler?

[1] https://en.wikipedia.org/wiki/Pay_what_you_want
[2] https://en.wikipedia.org/wiki/In_Rainbows#Release

**Comment by whirm** [comment]
Let's see when @synctext has some time to have a look at this.

**Comment by NielsZeilemaker** [comment]
Frostwire has taken a different approach and actually proposes a change to the .torrent file

https://github.com/frostwire/frostwire-desktop/wiki/Extending-a-Torrent%27s-info-map-with-Cryptocurrency-Wallet-addresses-and-a-Creative-Commons-license.-BitTorrent-meets-Bitcoin

**Comment by ThomasdenH** [comment]
I'd love this. I would even opt in if Tribler could have advertisements to support content providers.

**Comment by synctext** [comment]
If anybody has time to work on this great! please re-open then, closing now.
