### ISSUE TITLE
Anonymous = 1 flag in the infopart of a torrent file. Necessary?

### ISSUE THREAD

**Issue by rjruigrok** [Tribler/tribler#1423]
As discussed with @whirm and @LipuFei , is there a good reason for adding an anonymous=1 flag to the info section of a torrent (and changing the infohash by this)? Getting the torrent file is not done anonymously, it reveals the identitiy. The only reason why the torrent is needed now, is to set the anonymous=1 flag, but the torrent is not saved afterwards. Peers for anonymous torrents can only be found within the tunnel community, so it's not necessary to have DHT enabled here. 

I discovered the problem in `MainFrame.py`, where the creating of an anonymous torrent fails when the torrent is not fetched yet when clicking on the download button. The only way to circumvent this problem is by bypassing the anonymous=1 flag through blocking the anonymous download until the torrent is fetched, or by removing the whole anonymous=1 logic at all.

**Comment by synctext** [comment]
A mechanism is needed for hidden seeder discovery.

Current solution is based on the DHT to find introduction-points for an info_hash. By using anonymous=1 you have a nice deterministic algorithm. You can also simply use: hidden seeding DHT SHA1 = info_hash + 1. But that sounds like a terrible hack to me.

**Comment by whirm** [comment]
Right now we don't have any other way to anonymously fetch the torrent data. For the time being lets really use use it as it is:

  - plain search
  - plain torrent fetch
  - set anonymous=1 so the infohash changes deterministically
  - recompute the hash (we aren't doing this right now, so the whole thing was pointless)
  - load the updated torrentdef into the tunneled session

**Comment by synctext** [comment]
To add to Whirm his comment, after Libtorrent has fetched the .torrent we get a notification. Then you can add code add anonymous=1 and recompute the hash.

**Comment by egbertbouman** [comment]
@whirm The hash is recomputed [here](https://github.com/Tribler/tribler/blob/devel/Tribler/Main/vwxGUI/MainFrame.py#L543). Currently, hidden services is disabled by default, so it only gets executed during the test ;)

BTW, a workaround for the problem that @rjruigrok is describing is only allowing the user to set the hop count once the SaveAs dialog has downloaded the torrent.

**Comment by rjruigrok** [comment]
@egbertbouman In the next release hidden services will be enabled by default without the possibility to download over proxies, only as a fallback when downloading from a hidden seeder fails. 

We also thought about locking the anonymity options in the dialog until a torrent is downloaded, but it might be even nicer solution to use the 'fetching torrent...' status download status. Will have a look at this later on wednesday. ;)

**Comment by rjruigrok** [comment]
Solution from @egbertbouman is part of #1422. :)
