### ISSUE TITLE
3100 walker failures in 22 hours

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1428]
When running latest devel code we see frequent failure to contact the bootstrap trackers.
This has a severe impact on performance.

![tribler_6trackers_not_responsive_3100_drops__may2015](https://cloud.githubusercontent.com/assets/325224/7726566/5926ab82-ff03-11e4-87cf-6c51a5bc1824.png)

**Comment by synctext** [comment]
For the past 45minutes only 5 trackers are unresponsive :-)

**Comment by LipuFei** [comment]
@synctext I am closing this one at the moment. We have the per-community statistics now, so if it happens again, we will know which communities are failing more than usual.
