### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'mid'

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1432]
(stand alone tunnel)
ERROR   1432308530.29            main:33    Yappi not installed, profiling options won't be available
INFO    1432308530.29            main:368   Exit-node disabled
ERROR   1432308530.50   LibtorrentMgr:115   could not restore dht state, starting from scratch
INFO    1432308530.50            main:129   Using port 50109
ERROR   1432325904.15        dispersy:1724  exception during handle_callback for extend
Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/dispersy.py", line 1719, in _update
    messages[0].handle_callback(messages)
  File "/home/pouwelse/GITHUB/tribler/Tribler/community/tunnel/tunnel_community.py", line 1015, in on_extend
    mid=candidate.get_member().mid.encode('hex'))
AttributeError: 'NoneType' object has no attribute 'mid'

**Comment by rjruigrok** [comment]
Can be closed :+1:
