### ISSUE TITLE
Proposal: EmerCoin NVS as magnet link storage

### ISSUE THREAD

**Issue by maxihatop** [Tribler/tribler#1455]
Hi,
I would like to make your attention into Emercoin Name-Value storage, NVS: 
http://emercoin.com/DNS_and_Name-Value_Storage 
This decentralized storage has feature to store and distribute magnet links,  see "Magnet" in the document, and table 2. In opposite to another technologies, this is truthfully distributed system,
and cannot be blocked/censored/alerted, etc. Anyone able load and manage his magnet link, but nobody else. I think, decentralized link storage is very suitable for your decentralized system. 
For cooperate, contact EmerCoin team: team(well known symbol)emercoin.com.
We will happy to assist you, and provide initial funds for experiments.

**Comment by NielsZeilemaker** [comment]
I made a quick attempt at seeing if I could connect to the EmerCoin deamon, and it worked. I've succesfully enabled the rpc and call issue request for keys using the json rpc.

@maxihatop I'm going to integrate it into Tribler by using a emc: prefix. If you type this into the searchbox the string after it will be passed to the EmerCoin deamon. I'll replace the emc: with magnet:  before passing the string.

**Comment by maxihatop** [comment]
Perfect, thanks for quick progress! You performed awesome job!
I will test/use next week - tomorrow I will leave city, and this week will not be available.

**Comment by maxihatop** [comment]
UPD: 
I downloaded Tribler 6.4.3 from officvial site, tried to search "emc:example", found just "automatic test".
question: How to configure access and using EMC-wallet for search?

**Comment by NielsZeilemaker** [comment]
It's not in Tribler yet, I'll create a pull request for it probably this week. Then after its merged, you can test it out.

**Comment by maxihatop** [comment]
OK. I have additional interesting idea, which, I believe, easy to implement, and it will add more power to the Tribler. Imagine for example:

When I found some magnet link in EMC NVS, and it starts download (or download complete), I click right mouse button over the download line for this file, and in the drop-down menu I can select item "Copy EMC address for donation".
Thereafter, I can donate some EMCs to anonymous owner of this magnet link, as "thank you".

By this, way, there will be incentive to people upload magnet links to quality and needful files.

**Comment by NielsZeilemaker** [comment]
That's basically already implemented by the guys at frostwire:
https://github.com/frostwire/frostwire-desktop/wiki/Extending-a-Torrent%27s-info-map-with-Cryptocurrency-Wallet-addresses-and-a-Creative-Commons-license.-BitTorrent-meets-Bitcoin

Have a look at their spec, to see if you can fit in Emercoin.

**Comment by maxihatop** [comment]
I read that doc. That proposal is regarding to add info into *.torrent files, not into crypto. For example, they shows Bitcoin in doc, while Bitcoin has only basic functionality. Because of EMC supports standard Bitcoin JSON API, it ready to work in this system, too. 
Again: their proposal about torrent extension, is not about crypto extension. 
And any crypto can work with this proposal.
Also, I would like note - I dislike idea to send tips directly from a torrent program, by security reason. Many torrent program are freeware, and enemy can generate his own build of torrent client, distribute it, and when client sends to wallet "walletpassphrase" command for 
unlock wallet and send tips - this version of torrent client transfers out all money from wallet.
I strictly prefer enter password into wallet only.

**Comment by NielsZeilemaker** [comment]
I agree, it's nicer/safer to send the emc: payment option to the emc wallet instead of trying to integrate it. Is there such a functionality exposed in the API?

**Comment by maxihatop** [comment]
Yes, of course. Emercoin supports all bitcoin API commands, including "sendtoaddress".
See bitcoin API here: http://we.lovebitco.in/bitcoin-qt/command-reference/

**Comment by synctext** [comment]
Please re-open if anybody has devel time for this. closing now....
