### ISSUE TITLE
Tunnel tests don't have captions in their screenshots

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/tribler#1456]
Please add some captions to the screenshots taken by jenkins, see
http://jenkins.tribler.org//job/GH_Tribler_pull-request-tester_devel/4288/artifact/output//Screenshot-42.png

**Comment by rjruigrok** [comment]
I will incorporate this in the next PR I'm currently working on :+1: (next PR will be distinguishing different types of exitnodes for circuits, exit nodes are only necessary for anon downloading, hidden services should work without any exit enabled circuits).

**Comment by rjruigrok** [comment]
Can be closed
