### ISSUE TITLE
The anontunnel tests take over 12 minutes to run

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1459]
Is there anything that can be done to improve that? 

With the new parallel test execution, all the tests except for the anontunnel ones are done in ~5 minutes and then the whole thing waits for those to finish. 

As a last resort, we could split those in two modules so than at least we can execute them concurrently.

**Comment by rjruigrok** [comment]
Weird, the events for the tunnel tests are timed for 90 or 140 seconds, 12 minutes is too long. Especially the latest test written by @egbertbouman takes long. 
I'll have to look into this, but any suggestion on a possible cause is welcome!

**Comment by egbertbouman** [comment]
@rjruigrok What makes you say that? Looking at the [timings](http://jenkins.tribler.org/job/GH_Tribler_pull-request-tester_devel/4292/testReport/Tribler.Test.test_tunnel_community/TestTunnelCommunity/) from the most recent successful run, it looks like the most recent test doesn't take that long at all.

**Comment by rjruigrok** [comment]
Nope, my mistake. 
I looked into the time into experiment graph, see http://jenkins.tribler.org/job/GH_Tribler_pull-request-tester-turbo_devel/5/artifact/output//utimes.png, but understood it wrong. I thought that the individual tests took over 12 minutes, but it is a cumulative graph. All consecutive tests in the same file are executed after each other. 

Splitting them up would be indeed the best solution, will incorporate this in my next PR. I assume they all run isolated from each other, so they can't find each others candidates in the communities when tests run in parallel?

**Comment by rjruigrok** [comment]
Tests are separated over 3 different files now, can be closed too.
