### ISSUE TITLE
make the method dispersy._forward public

### ISSUE THREAD

**Issue by snorberhuis** [Tribler/tribler#1469]
This method is used within Tribler multiple times, but is accessed publicly while it is a protected method. 
The method should be changed into a public method so no pylint errors are given in the code.

`store_update_forward( [messages], false ,false, true )` can also be used and will result in only `_forward` being called. But in the documentation of that method it is mentioned that false should mostly only be used for debugging purposes.

**Comment by NielsZeilemaker** [comment]
@snorberhuis could you create this issue in the dispersy github repo.
