### ISSUE TITLE
New metadata design

### ISSUE THREAD

**Issue by LipuFei** [Tribler/tribler#1477]
@NielsZeilemaker I am removing old metadata stuff. Do you know if this `modification` message was made for metadata or it already existed before that? Thanks!

**Comment by NielsZeilemaker** [comment]
Existed before it

**Comment by LipuFei** [comment]
Looks like they are closely related, even with this `MetadataTypes` table, which seems to be useful only to the metadata thing. Do you know why?

**Comment by NielsZeilemaker** [comment]
I think you rewrote parts of it + the Metadata stuff is inspired by the old modification messages

**Comment by LipuFei** [comment]
Now we plan to make a new metadata message in the Channel, but only the owner of the Channel can create it and there is no versioning feature for that: once a metadata is created for a ChannelTorrent, it's never going to be replaced.

So I am removing all the old stuff, but this `modification` thing is getting me confused. At least I don't remember making those things myself...

The problem is this `MetadataTypes` table. It's no longer useful. But if I remove it, it will break the `modification` message code in Channel.

**Comment by NielsZeilemaker** [comment]
A channel in closed and semi-open state already works like this. I wouldn't redesign it if I were you. 
Also I don't think it's worth it breaking compatibility with the current channels. I would only replace allchannel. 

As for the MetadataTypes what's in that table?

**Comment by LipuFei** [comment]
The names of metadata types, such as `name`, `description`, `swift-thumbnails`, etc.

**Comment by NielsZeilemaker** [comment]
BTW, why are you removing the metadata community? I would modify it by disabling the bloomfilter sync and letting peers announce infohashes they have information for. Then similar to the ping pong messages in the remote search community, a peer could decide which metadata to collect. 
If you only collect metadata from your favorite communities, most spam should dissappear

**Comment by NielsZeilemaker** [comment]
BTW, those types already existed. I would keep that table. 
The types aren't predefined, you can add types on the future and still be backwards compatible

**Comment by LipuFei** [comment]
Got it, I thought that table was made later.

We want to enable and propagate thumbnails only for the Channels that a user has subscribed to. If we use the old metadata community, it will propagate all data regardless of what a user's subscriptions are, which will eat up a lot more disk space. Another thing is that, if we propagate everything, some unwanted thumbnails from other Channels may arrive at user's storage, which is not a very nice thing.

**Comment by LipuFei** [comment]
Anyway, adding a new message in Channel seems to be the easiest way to do this. That's why we decide to have it this way.

**Comment by NielsZeilemaker** [comment]
You might be able to do so by just using the current modification messages. Egbert made some code once which checked if a channel was open after downloading a file. If it was it added some ffmpeg output. 
I would reuse/extend this scheme and add support for tftp thumbnails, just add a new type and the newer peers would start to download them

**Comment by synctext** [comment]
morning, thnx for the comments Niels. Reusing things more sounds good...

**Comment by whirm** [comment]
@NielsZeilemaker let me write down the possibilities here to se if I understand them:

 * Add an extra message to the Channel community and bump community version:
   - New peers will receive the new messages if they have joined the community and then ask for the thumbnails to the message sender.
   - Old peers will just not sync this new message and that's it.

 * Reuse the old Metadata community:
  - Everybody joins the single Metadata community.
  - All the metadata messages related to all channels get synced by everybody, but the thumbnails don't get downloaded if we haven't joined the channel the metadata message is for.
  - Once we join a channel, we scan trough the whole history and fetch all the metadata messages related to that channel and by using the tastebuddies thing we look for peers to fetch the thumbnails from.

I think the first way is way cleaner.

**Comment by NielsZeilemaker** [comment]
Or number three, use the modification message already existing in the
channel community
Op 18 jun. 2015 2:20 PM schreef "Elric Milon" <notifications@github.com>:

**Comment by whirm** [comment]
@NielsZeilemaker ah, I see, I understood this message was part of the metadata community solution.
So that would basically be the first one without it being an extra message but one that already exists which is even better.

**Comment by NielsZeilemaker** [comment]
Jup, and I think Egbert was already using this message to publish metadata images

**Comment by LipuFei** [comment]
@NielsZeilemaker @whirm I agree to reuse the `modification` message is a good idea because we don't need to recreate the infrastructure again. But we cannot reuse the metadata types such as `swift-thumbnails` because messages of those metadata types are already in our current network, and the thumbnail paths they carry are not what we want this time (we use SHA1 hash of the thumbnail as identifier). So we have to create a new metadata type and ignore the old ones.

Another thing I've been thinking about is what if we fail to download a thumbnail through TFTP? If we only download a thumbnail when we get a `modification` message and some how the download failed, then we will never download this thumbnail again unless a different `modification` message arrives with the same thumbnail hash as the one we failed to download. So perhaps we should also add a new ping-pong-like meta-message to find out who has this thumbnail. Whenever we try the load the metadata of a torrent and the thumbnail is not on local disk, we can use this message to get the thumbnail again.

**Comment by NielsZeilemaker** [comment]
Regarding your last comment, this was basically implemented by downloading the thumbnail in the check method, and only accepting it if it was downloaded, see:
https://github.com/Tribler/tribler/blob/devel/Tribler/community/channel/community.py#L738

**Comment by LipuFei** [comment]
@NielsZeilemaker Ah, I see, didn't notice that. Thanks!

**Comment by ichorid** [comment]
RIP Dispersy
