### ISSUE TITLE
Documentation: find scientific articles linked to our rewarding good behavior work

### ISSUE THREAD

**Issue by palmaway** [Tribler/tribler#149]
Goal: determine the feasibility of publishing our proof-of-work research in Nature
Outcome: list of Nature.com article on indirect reciprocity or other topic with overlap to us.
Planning: May-June

This issue builds heavy upon: #5 for indirect-reciprocity and #119 for getting sufficient usage. 

Essential problem is how large the gap is between our experimental work with an attempt at behavioral change of 1 million people to classical game theory type of work in Nature.

[Nature.com search on indirect reciprocity](http://www.nature.com/search/executeSearch?sp-q-1=&sp-q=indirect+reciprocity&sp-p=all&sp-c=25&sp-m=0&sp-s=&sp-a=sp1001702d&sp-sfvl-field=subject|ujournal&sp-x-1=ujournal&sp-p-1=phrase&submit=go)

**Comment by VoR0220** [comment]
MaidSafe is doing some lovely work. Here is their Sybil Attack prevention mechanism: 

http://systemdocs.maidsafe.net/content/attacks/birthday_paradoxsybil_attack.html
