### ISSUE TITLE
Videoplayer does not work 

### ISSUE THREAD

**Issue by jordansteeves** [Tribler/tribler#1509]
The videoplayer tab is greyed out and not clickable for anywhere inside the application. 

Details:
Tribler 6.4.3 on OSX 10.10.3

![trible](https://cloud.githubusercontent.com/assets/1646659/8392823/564b110c-1cac-11e5-8aa6-bafa8a7c75e9.png)

**Comment by whirm** [comment]
We  don't have an embedded video player on OSX.

We will just remove the greyed out tab to not confuse our users :)

Thanks for the report!
