### ISSUE TITLE
Allow 0.0.0.0:0 as destination to tunnel data through circuits back and forth

### ISSUE THREAD

**Issue by rjruigrok** [Tribler/tribler#1530]
Currently when the key-request is relayed to the seeder, the dispersy wan address is used as source. This causes the seeder to respond to the dispersy port of the introduction point over an exit socket. 
https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/hidden_community.py#L400

```
relay_circuit.tunnel_data(self.dispersy.wan_address, TUNNEL_PREFIX + message.packet)
```

It would be nice not to use dispersy wan here, and to set 0.0.0.0:0 as the source, to pass messages through a circuit to the last hop. This currently only works one way, to send messages back to the originator of the circuit.

**Comment by qstokkink** [comment]
@egbertbouman I believe you are fixing this, so I'll assign you.

**Comment by qstokkink** [comment]
@egbertbouman is this fixed now?
