### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by brandc** [Tribler/tribler#1540]
I was using the down arrow key to preload everything in a channel, and this is what showed up in the log.
```
Traceback (most recent call last):
  File "/home/iron/tmp/tribler/Tribler/Main/vwxGUI/list_body.py", line 1396, in <lambda>
    self.Bind(wx.EVT_MENU, lambda event: self.SelectNextItem(True), id=adownId)
  File "/home/iron/tmp/tribler/Tribler/Main/vwxGUI/__init__.py", line 119, in invoke_func
    return func(*args, **kwargs)
  File "/home/iron/tmp/tribler/Tribler/Main/vwxGUI/list_body.py", line 1301, in SelectNextItem
    select].GetSize()[1] + 1) / self.GetScrollPixelsPerUnit()[1]
KeyError: 'K\r`\xc0p\xd69.\xb7\x98\xb7^\x01\xb8\xa4\xacS\xc7^\x8d'
```

Edited by @whirm: One copy of the stacktrace is enough.

**Comment by LipuFei** [comment]
@whirm I am not sure if I can fix this for `6.5`... Those list problems in the GUI is always a big headache.

**Comment by whirm** [comment]
@LipuFei let's do it for 6.6

**Comment by whirm** [comment]
@brandc thanks for the report!

**Comment by NielsZeilemaker** [comment]
Basically this line:
https://github.com/Tribler/tribler/blob/devel/Tribler/Main/vwxGUI/list_body.py#L1297
needs a call to self.HasItem(select) and then it should be fixed.

**Comment by devos50** [comment]
@whirm is this one fixed?

**Comment by whirm** [comment]
I don't see the check that @NielsZeilemaker mentioned there, so I assume it's not.
