### ISSUE TITLE
Windows Permission Denied error

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1548]
Not allowed to write to the log file, when closing Tribler 6.5RC1.
![permission_denied](https://cloud.githubusercontent.com/assets/325224/8573461/f8c2ac54-2591-11e5-9c77-22413744c602.png)

**Comment by LipuFei** [comment]
@synctext This cannot be fixed. This `tribler.exe.log` is generated by `py2exe` automatically.

**Comment by egbertbouman** [comment]
@LipuFei We used to store it in %APPDATA% on Windows, which seems to be the logical place for this. If I recall correctly, we actually used a patched version of py2exe (it's on the Windows XP builder).
