### ISSUE TITLE
Update Dispersy pointer when the memory leak issue is closed/fixed

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1551]
Update Dispersy pointer when the memory leak issue is closed/fixed: Tribler/dispersy#442

[bug moved to Tribler/dispersy]

**Comment by NielsZeilemaker** [comment]
Clearly a Dispersy issue, could you move this issue there?

**Comment by qstokkink** [comment]
As Dispersy is almost gone, I will close this issue.
