### ISSUE TITLE
Is there a limit on the amount of resources Tribler will dedicate to proxying for other peer's circuits?

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1562]
Or it will try to attend all requests and go down in flames if there are too many requests?

**Comment by rjruigrok** [comment]
There is a limit which defaults to 100 concurrent relays or exits to be allowed. It's in https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/tunnel_community.py#L916

**Comment by whirm** [comment]
@rjruigrok  Have you tried reaching the limit? Does Tribler still work?

**Comment by rjruigrok** [comment]
I tried it once, Tribler works fine. The bottleneck is not with the amount of circuits it is participating in, but the downloading / seeding bandwidth taking place over these circuits. Via the settings panel it is possible to limit the bandwidth of torrent seeding / downloading, but there is no way to limit the bandwidth for relaying data to others yet (mentioned earlier in #1053). 

I think the limiting of bandwidth for relaying should be done in the socks server, but I'm not familiar with this part of the code.

**Comment by whirm** [comment]
Did you test it with a 100Mbit symmetrical connection?

**Comment by rjruigrok** [comment]
On the eduroam network or the Tribler wifi, not completely sure, it's been some months ago. But it was just a test with circuits / relays, not sure if there was any relaying activity on these circuits. 
My mac was always going down in flames, with or without tunnels. Frying an egg on top is not that hard.  :smiley:

**Comment by rjruigrok** [comment]
Just meaning it gets hot, very hot, full cpu load. But it stays working.
