### ISSUE TITLE
download state not correctly restored

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1568]
To recreate, download a torrent, pauze the download, restart Tribler, it will incorrectly resume downloading.

**Comment by whirm** [comment]
@LipuFei can you take care of this?

**Comment by LipuFei** [comment]
@synctext Could you try to reproduce this?

**Comment by BmetaMax** [comment]
I've also been having this error. I mentioned it in a different bug, but just saw this bug filing and so wanted to verify I'm seeing it too. To clarify, I'm on rc2, have recently performed a clean install.
I would add that I've stopped downloads several times, performed a clean shutdown, and upon reopening tribler all downloads are resumed whereas in 643 the same stopped downloads would remain stopped; I have several extremely large ones that I currently don't have the disk space to let complete, but would like to have still in my list at their current progress once I get another drive installed.

**Comment by synctext** [comment]
reproduced.
Hey guys, just did update to latest devel. Still not restoring correctly if I stopped seeding, restart, it resumes seeding again.

commit c4fa55709551cc44013e8123b5cf25e3a6f9b0ec
Merge: 871f23d c98c07b
Author: Elric Milon <whirm@users.noreply.github.com>
Date:   Mon Aug 24 14:23:44 2015 +0200

**Comment by BmetaMax** [comment]
I confirm I'm also still having this on rc4.

**Comment by whirm** [comment]
Yeah, we haven't addressed that yet.

**Comment by whirm** [comment]
@synctext , @BmetaMax: This build should fix this issue:
http://jenkins.tribler.org/job/Publish_tribler_next/146/

Reopen if it doesn't.

**Comment by BmetaMax** [comment]
I can confirm rc4_36 fixed this issue for me, yay thanks! I hope my post doesn't reopen the issue.
