### ISSUE TITLE
All Anonymous Downloads and Uploads Stuck at "Building Circuits"

### ISSUE THREAD

**Issue by snifong** [Tribler/tribler#1570]
**OS:** Sabayon Linux 15.X (Gentoo)
**Version:** Latest (as of 07/20/2015) version pulled from git.
**Reproducible?** Yes
**Tribler Config Settings:** Anonymous download set to low (1).  I've tried medium (2) and high (3) also and the same thing happens.

**Steps to Reproduce Hung Download:**
1. Launch Tribler
2. Search for a file to download
3. Select it and click download
4. Dialog pops up asking "Download anonymously using proxies". Make sure that is **checked**.
5. Click OK
6. Click Downloads to view the file status
7. Status changes from "Initializing" to "Building Circuits" and remains there. File never begins to download.

**Steps to Reproduce Hung Upload:**
1. Launch Tribler
2. Search for a file to download
3. Select it and click download
4. Dialog pops up asking "Download anonymously using proxies". Make sure that is **unchecked**.
5. Make sure "Encrypted anonymous seeding using proxies" is **checked**.
6. Click OK
7. Click Downloads to view the file status
8. File downloads successfully.
9. Status changes from "Initializing" to "Building Circuits" and remains there. File never begins seeding.

**Comment by whirm** [comment]
This feature is not yet on a released version of Tribler, so there's almost nobody acting as proxies right now. We have a few dedicated boosters maybe where offline when you tried? I'm just downloading an Ubuntu iso in tunneled mode at 2.5 MB/s right now.

**Comment by snifong** [comment]
There used to be a 1-5 level slider for anonymity.  I don't know what version that was 6.3.4 maybe.  I almost always used at least a 3 and it worked fine.  What's different under the covers about the 1-3 slider?  Still using the same network, right?

**Comment by whirm** [comment]
AFAIK it got reduced to 1-3 because 4-5 was just too slow to be useful at all.
The anontunnel community has changed a lot, since the last release.
RE ports, I think it's using the same port than the rest of the dispersy traffic.
@rjruigrok could you answer this better/correct me?

**Comment by rjruigrok** [comment]
@whirm That's correct, nothing changed related to the ports. 

Regarding the 'building circuits' state, it will stay in this state until at least 4 circuits are built. And when using a circuit length larger than 1, those circuits should all end in a different exit-node, but as they are scarce in the current version, this may take some time. 

@whirm, it might possibly be related to trackers running old versions, but I'm not really sure about that. Some months ago there was an issue where trackers were dropping dispersy introduction messages from the tunnelcommunity because additional payload was appended causing a length check to fail. @LipuFei  updated some of them, but not all. Possibly it's related to this?

**Comment by snifong** [comment]
I'm not sure what happened but today I started it up and the "Launching Tribler" dialog box status read "upgrading database ... this may take some time" (or something like that).  After a little bit, it launched and I tested it with a Ubuntu ISO and it worked.  Then I tested it with the same file I was trying before when I opened the ticket and it worked with that one also.

```git pull``` didn't pull any new files so I'm not sure what happened but it's working.

**Comment by whirm** [comment]
@snifong good to know. 
Remember that we use several submodules, so you need to ```git submodule update --recursive``` after updating the main repo.

Let us know if you find more issues :)

Cheers.

**Comment by badde-media** [comment]
OS: Windows 10
Version: Latest (as of 08/12/2018) version pulled from website (7.0.2).
Reproducible? Yes
Tribler Config Settings: Anonymous download set to low (1). I've tried medium (2) and high (3) also and the same thing happens.

Problem: Same as snifong posted 3 years go. Still not fixed? No anonymous downloads possible at all, no matter which settings are used. Ubuntu download without anon works fine. Reproducible, tested with several torrents. All downloads hang at "Building circuits" and never start loading.

**Comment by devos50** [comment]
@badde-media there were some problems with our infrastructure. Could you try again?
