### ISSUE TITLE
What is in place to prevent voting spam?

### ISSUE THREAD

**Issue by brandc** [Tribler/tribler#1571]
Could someone just generate elliptic curve signing keys really quickly, sign one channel, and distribute the bad data?

**Comment by brandc** [comment]
I'm guessing some sort of puzzle system similar to bitcoin. A puzzle of a given memory and computational difficulty in order to sign a channel and increase the popularity rating.

**Comment by whirm** [comment]
@brandc yes, there's no protection against spam voting right now. But when you subscribe to a channel, you also help propagating it over the rest, so that also helps with keeping the good channels visible.

**Comment by brandc** [comment]
That answers my question.
