### ISSUE TITLE
The Tribler forum is under attack

### ISSUE THREAD

**Issue by vvs-** [Tribler/tribler#1572]
There is a massive spam attack ongoing. Please, disable new registrations and posts from new users.

**Comment by brandc** [comment]
If you have not noticed, the tribler github has been idle for almost a week now.

**Comment by synctext** [comment]
yep, also our Jenkins infrastucture was under attack. Somebody compromised a build image.  Busy week... So lack of communication,but stuff is happening.

**Comment by whirm** [comment]
@synctext I have no admin rights on the forum, can you disable new registrations? I can take care of banning existings users.

**Comment by vvs-** [comment]
According to the forum logs they are registering at a rate of a several per minute. If something is not done quickly they will flood the forum completely. I can't stay behind the computer all the time.

**Comment by whirm** [comment]
@vvs-: @synctext is on vacation, so it may take some time for he to reply. Bad timing for a spam attack :(

**Comment by whirm** [comment]
@vvs- I've gone directly into the database and set myself as admin :D  

I've just disabled user registration.

**Comment by vvs-** [comment]
> I've just disabled user registration.

Hourray! I can finally relax. Thanks!

**Comment by whirm** [comment]
@vvs- thanks for the help! I'll be looking at solutions for the forum spam problems shortly.
