### ISSUE TITLE
On Mac OSX 10.9.5 Tribler exits immediately after launch

### ISSUE THREAD

**Issue by jbshirk** [Tribler/tribler#1576]
Please let me know what other information would be helpful. I used the OSX install package.

**Comment by LipuFei** [comment]
Hi @jbshirk, thank you for the report! Could you open your Warning Console to see if there is any output? Thanks in advance!

**Comment by jbshirk** [comment]
I need a few clues about what/where/how.

**Comment by whirm** [comment]
Sorry for the delay, here's how to do it:

Go to the launch pad -> other -> console

Thanks!

**Comment by whirm** [comment]
@jbshirk Are you still having issues with this?

**Comment by whirm** [comment]
Closing due to lack of feedback, feel free to reopen with the required info if the issue still affects you.

Thanks!

**Comment by jbshirk** [comment]
10/31/15 9:29:29.250 AM Tribler[80062]: Traceback (most recent call last):
     10/31/15 9:29:29.252 AM Tribler[80062]:   File "<string>", line 5, in <module>
     10/31/15 9:29:29.252 AM Tribler[80062]: ImportError
     10/31/15 9:29:29.253 AM Tribler[80062]: ImportError: 
     10/31/15 9:29:29.254 AM Tribler[80062]: ImportError: No module named csv
     10/31/15 9:29:29.254 AM Tribler[80062]: ImportError: No module named csv
     10/31/15 9:29:31.608 AM Tribler[80062]: ERROR   1446298171.61            util:269   Exception raised on the reactor's thread.
     10/31/15 9:29:31.609 AM Tribler[80062]:  Traceback from this thread:
     10/31/15 9:29:31.609 AM Tribler[80062]:   File "/Applications/Tribler.app/Contents/Resources/__boot__.py", line 389, in <module>
     10/31/15 9:29:31.609 AM Tribler[80062]:   File "/Applications/Tribler.app/Contents/Resources/__boot__.py", line 336, in _run
     10/31/15 9:29:31.609 AM Tribler[80062]:   File "/Applications/Tribler.app/Contents/Resources/tribler.py", line 34, in <module>
     10/31/15 9:29:31.609 AM Tribler[80062]:   File "/Applications/Tribler.app/Contents/Resources/tribler.py", line 26, in run
     10/31/15 9:29:31.610 AM Tribler[80062]:   File "Tribler/Main/tribler_main.pyo", line 1112, in run
     10/31/15 9:29:31.611 AM Tribler[80062]:   File "Tribler/Main/tribler_main.pyo", line 175, in __init__
     10/31/15 9:29:31.615 AM Tribler[80062]:   File "Tribler/Main/tribler_main.pyo", line 434, in InitStage1
     10/31/15 9:29:31.620 AM Tribler[80062]:   File "Tribler/Core/Session.pyo", line 161, in prestart
     10/31/15 9:29:31.620 AM Tribler[80062]:   File "Tribler/dispersy/util.pyo", line 45, in helper
     10/31/15 9:29:31.621 AM Tribler[80062]:   File "Tribler/dispersy/util.pyo", line 266, in blockingCallFromThread
     10/31/15 9:29:31.621 AM Tribler[80062]:  Traceback from the reactor's thread:
     10/31/15 9:29:31.622 AM Tribler[80062]:    File "twisted/internet/defer.pyo", line 139, in maybeDeferred
     10/31/15 9:29:31.622 AM Tribler[80062]:   File "Tribler/Core/CacheDB/sqlitecachedb.pyo", line 84, in initialize
     10/31/15 9:29:31.623 AM Tribler[80062]:   File "Tribler/Core/CacheDB/sqlitecachedb.pyo", line 180, in _open_connection
     10/31/15 9:29:31.624 AM Tribler[80062]: Traceback (most recent call last):
     10/31/15 9:29:31.624 AM Tribler[80062]:   File "Tribler/Main/tribler_main.pyo", line 1112, in run
     10/31/15 9:29:31.625 AM Tribler[80062]:   File "Tribler/Main/tribler_main.pyo", line 175, in __init__
     10/31/15 9:29:31.625 AM Tribler[80062]:   File "Tribler/Main/tribler_main.pyo", line 434, in InitStage1
     10/31/15 9:29:31.625 AM Tribler[80062]:   File "Tribler/Core/Session.pyo", line 161, in prestart
     10/31/15 9:29:31.626 AM Tribler[80062]:   File "Tribler/dispersy/util.pyo", line 45, in helper
     10/31/15 9:29:31.626 AM Tribler[80062]:   File "Tribler/dispersy/util.pyo", line 270, in blockingCallFromThread
     10/31/15 9:29:31.627 AM Tribler[80062]:   File "<string>", line 2, in raiseException
     10/31/15 9:29:31.627 AM Tribler[80062]: CorruptedDatabaseError: Failed to load database version: SQLError: no such table: MyInfo

**Comment by jbshirk** [comment]
I can't tell what version, date on files is Jan 28 2015

**Comment by whirm** [comment]
@jbshirk could you try this build:

http://jenkins.tribler.org/job/Build-Tribler_OSX_next/166/

And tell me if it works for you?

Be aware that once you upgrade from 6.4.x to 6.5.x the on disk format will change and you won't be able to use that data with older Tribler versions, so backup .Tribler/ if you want to have this option.

**Comment by jbshirk** [comment]
11/4/15 9:31:14.000 AM kernel[0]: hfs: mounted Tribler on device disk2s2
    11/4/15 9:31:15.167 AM mds[76]: (Normal) Volume: volume:0x7ff0098e2a00 ********** Bootstrapped Creating a default store:1 SpotLoc:(null) SpotVerLoc:(null) occlude:0 /Volumes/Tribler
    11/4/15 9:32:08.000 AM kernel[0]: hfs: unmount initiated on Tribler on device disk2s2
    11/4/15 9:33:12.664 AM Tribler[1645]: ERROR   1446647592.66            util:237   Exception raised on the reactor's thread 'Failed to load database version: SQLError: no such table: MyInfo'.
    11/4/15 9:33:12.676 AM Tribler[1645]:  Traceback from this thread:
    11/4/15 9:33:12.676 AM Tribler[1645]:   File "/Applications/Tribler.app/Contents/Resources/__boot__.py", line 399, in <module>
    11/4/15 9:33:12.676 AM Tribler[1645]:   File "/Applications/Tribler.app/Contents/Resources/__boot__.py", line 336, in _run
    11/4/15 9:33:12.677 AM Tribler[1645]:   File "/Applications/Tribler.app/Contents/Resources/tribler.py", line 84, in <module>
    11/4/15 9:33:12.677 AM Tribler[1645]:   File "/Applications/Tribler.app/Contents/Resources/tribler.py", line 74, in __main__
    11/4/15 9:33:12.677 AM Tribler[1645]:   File "/Applications/Tribler.app/Contents/Resources/tribler.py", line 57, in run
    11/4/15 9:33:12.677 AM Tribler[1645]:   File "Tribler/Main/tribler_main.pyo", line 1061, in run
    11/4/15 9:33:12.678 AM Tribler[1645]:   File "Tribler/Main/tribler_main.pyo", line 143, in __init__
    11/4/15 9:33:12.678 AM Tribler[1645]:   File "Tribler/Main/tribler_main.pyo", line 386, in InitStage1
    11/4/15 9:33:12.678 AM Tribler[1645]:   File "Tribler/Core/Session.pyo", line 161, in prestart
    11/4/15 9:33:12.678 AM Tribler[1645]:   File "Tribler/dispersy/util.pyo", line 47, in helper
    11/4/15 9:33:12.679 AM Tribler[1645]:   File "Tribler/dispersy/util.pyo", line 234, in blockingCallFromThread
    11/4/15 9:33:12.679 AM Tribler[1645]:  Traceback from the reactor's thread:
    11/4/15 9:33:12.679 AM Tribler[1645]:    File "twisted/internet/defer.pyo", line 140, in maybeDeferred
    11/4/15 9:33:12.680 AM Tribler[1645]:   File "Tribler/Core/CacheDB/sqlitecachedb.pyo", line 83, in initialize
    11/4/15 9:33:12.680 AM Tribler[1645]:   File "Tribler/Core/CacheDB/sqlitecachedb.pyo", line 179, in _open_connection
    11/4/15 9:33:12.680 AM Tribler[1645]: Traceback (most recent call last):
    11/4/15 9:33:12.681 AM Tribler[1645]:   File "Tribler/Main/tribler_main.pyo", line 1061, in run
    11/4/15 9:33:12.681 AM Tribler[1645]:   File "Tribler/Main/tribler_main.pyo", line 143, in __init__
    11/4/15 9:33:12.682 AM Tribler[1645]:   File "Tribler/Main/tribler_main.pyo", line 386, in InitStage1
    11/4/15 9:33:12.682 AM Tribler[1645]:   File "Tribler/Core/Session.pyo", line 161, in prestart
    11/4/15 9:33:12.682 AM Tribler[1645]:   File "Tribler/dispersy/util.pyo", line 47, in helper
    11/4/15 9:33:12.682 AM Tribler[1645]:   File "Tribler/dispersy/util.pyo", line 238, in blockingCallFromThread
    11/4/15 9:33:12.683 AM Tribler[1645]:   File "<string>", line 2, in raiseException
    11/4/15 9:33:12.683 AM Tribler[1645]: CorruptedDatabaseError: Failed to load database version: SQLError: no such table: MyInfo

**Comment by whirm** [comment]
Ok, that's looking better. 

It also seems your Sqlite DB got corrupted somehow. Could you enter ~/.Tribler/sqlite/ and move all `tribler.*`files somewhere else and see if that makes Tribler work as it should again? 

Don't delete the files as I may ask you to forward them to me so I can analyze them.

Thanks!

**Comment by jbshirk** [comment]
That worked. It's up. No errors in System Log console.

**Comment by whirm** [comment]
Great!

Closing this one, feel free to report any other issues you have.
