### ISSUE TITLE
The bittorrent icon on the download items should go

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1585]
As we only support bittorrent transfers now.

**Comment by NielsZeilemaker** [comment]
Add a tunnel icon?

**Comment by whirm** [comment]
And remove the anonymous column, yeah, that would be nice.

**Comment by devos50** [comment]
@whirm this one is easy to fix I guess?

**Comment by whirm** [comment]
I guess, but don't waste too much time otherwise.
