### ISSUE TITLE
Keep sorting torrents

### ISSUE THREAD

**Issue by ThomasdenH** [Tribler/tribler#1590]
Right now, the download panel sorts when clicking an option, but the order stays the same, even though the value to sort by changes. For example, when sorting on ETA one torrent might suddenly download much quicker and therefor get a faster ETA without this being reflected in the torrent order.

**Comment by lfdversluis** [comment]
@whirm I think this can be assigned to 6.6 or 6.7. Maybe we can include it in the alpha, or just go with the new gui?

**Comment by whirm** [comment]
Let's do it for the new gui, it would be a waste of effort to do it on WX and then throw it away.

**Comment by lfdversluis** [comment]
@whirm I fully agree.

**Comment by synctext** [comment]
with a Youtube-ish GUI this all changes. true.

**Comment by devos50** [comment]
This issue should be fixed in the new Tribler 7 GUI.
