### ISSUE TITLE
Consider torrents without ETA taking the longest

### ISSUE THREAD

**Issue by ThomasdenH** [Tribler/tribler#1591]
When sorting torrent by ETA, could you please change it so that completed torrents and torrents that don't download are sorted below torrents that have an estimated time. This way, it is an easy way to see what torrent will be complete the soonest, as it is on top of the list, which torrent will take a while, since it will be at the bottom of the still downloading torrents, and which torrent are complete, since they will be on the bottom of the list.

**Comment by whirm** [comment]
Good idea, thanks!
