### ISSUE TITLE
Noob question: helpful to move previously collected .torrent files?

### ISSUE THREAD

**Issue by Cathryne** [Tribler/tribler#1600]
Hi!

I wanted to migrate from another torrent client to Tribler and noticed that the previous one had many of its .torrent files still stored. Is it helpful to Tribler to just drop them into the `collected_torrents` folder, or can they only be utilised if they have been written by Tribler itself?

Thanks for any advice!

**Comment by synctext** [comment]
hi, Tribler should be able to use them.

if you want to download the content of those .torrent files, simply use the upper right '+' icon. Manually adding them to the collected_torrents file requires a bit of work.

**Comment by Cathryne** [comment]
Hi Johan,

What work is required to add them to the collected_torrents? I don't want
to download their content, just add the .torrent files themselves to the
searchable pool.

Cheers,
Cathryne

**Comment by whirm** [comment]
You will need to insert them into the leveldb called ```collected_torrents``` in the ``.Tribler``` directory with the binary infohash as key.

This is done automatically when upgrading to the latest stable version but you could copy that part of the code into a small script that does this for you if you know a bit of python.
