### ISSUE TITLE
Running Tribler directly from repository in Arch Linux

### ISSUE THREAD

**Issue by EnolRekcah** [Tribler/tribler#1601]
After cloning and executing the "tribler.sh" script I get the following error: "ImportError: No module named cryptography.hazmat.backends". At the moment I'm stuck. Previous errors could be fixed through the installation of the corresponing dependencies but this one seems to be tougher,

**Comment by LipuFei** [comment]
Hi @EnolRekcah, thank you for the report. This error is caused by missing the `cryptography` python module. Could you try to install this module and try again?

**Comment by EnolRekcah** [comment]
Hey, you were right LipuFei. Thank you very much. The "python2-cryptography" module was missing. I also had to install "python2-plyvel" and "python2-decorator". Now it is functioning ;) Is it normal that the window title says "Tribler 6.4.0-GIT" although I cloned the repository?

**Comment by LipuFei** [comment]
@EnolRekcah It is normal. We didn't update this title in the source code so that's why you see "Tribler 6.4.0-GIT".

**Comment by EnolRekcah** [comment]
Okay, perfect.
