### ISSUE TITLE
RC-3 and RC-3 g61899 not being able to build circuits for anonymous donwloading.

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#1602]
I'm on Windows 10. The anonymous torrenting doesn't work. Works fine with encrypted anonymous seeding, but not anonymous downloading. Getting a lot of errors. Tribler also have an error when trying to close. Pastebin of a bit of the log file. Most stuff are just the same thing going since i left it going over the night so see if it would work, and i assume that's what here are so many of those. 

http://www.pastebin.ca/3125198

Also, new to testing Tribler and using github, so correct me if there is any mistakes or lacking information i should provide.

**Comment by LipuFei** [comment]
@Thomasedv Thank you for the report. I have made a fix for a problem in the log file you provided. Could you have a try when the next release becomes available? Thank you!

**Comment by Thomasedv** [comment]
Will do once it's out.

**Comment by whirm** [comment]
@Thomasedv Could you try this build? 
http://jenkins.tribler.org/job/Publish_tribler_next/133/artifact/Tribler_6.5.0-rc3-7-gdc80e16.exe

**Comment by Thomasedv** [comment]
Ok, it's a bit complicated now. After installing the build it did not change anything at first. Restarted the computer just to be sure, and to my surprise it started working! I then decided to test to see if i got an error when closing Tribler. I did, and at that moment i had a few of the anonymous torrents in progress. (Adding as info as it may be related) Got an error, and check log file for information. I then went to start  Tribler up again, and as soon as "building circuits" appear it stopped responding and was quickly decide by windows that it needed to be closed.  It then continued to crash several times at the same phase. 

Just did a new restart of my computer, and it did not crash. I let it be for a while(while writing this) and it eventually managed to connect and the anonymous download works. Closing it and i receive the error and it crashes like usual. So it seems, with my limited knowledge, to be caused by the closing of the application to not be closed correctly which makes it unable to start properly until the computer has done a restart for some reason. 

Here is a mega link(which i hope works) to the log, since it was slightly to large for pastebin and pastebin removed 4 invalid characters which might be of relevance. If there is any other method you prefer in getting the files, let me know. I'm new to github and reporting issues in general so i take any advice i can get.

**Comment by whirm** [comment]
It's fine like this :)

I'll let @LipuFei have a look at it tomorrow.

Thanks a lot for your work!

**Comment by Thomasedv** [comment]
A new and probably not related problem, but getting an error popup for each torrent i add. Still works fine, but there seems to be an error. Also kind of feel bad for pointing so many problems out, especially after seeing the length of the logs... 


New log file for this problem, a good change the part of the other one is in it too. 
https://mega.nz/#!RAhmFBiL!cbJw6MR998WaGNLLwivdoEJTKeXvAgojoUycnZjFxYU

**Comment by whirm** [comment]
It seems you have a corrupt download state file. To make sure, could you rename the ```dlcheckpoints``` directory and see if that fixes it? If so, maybe you could send us the contents so we can see what the issue is.

Also, we are going to add a check for that so that corrupt download state files will just be dropped instead.

**Comment by Thomasedv** [comment]
Ok, so for a lot of reasons things just went wrong. Not just with tribler, while going through files my secondary hard drive partition suddenly turned into a weird storage format and said on space left on it. (Exactly 0....)  Also had more freezes, crashes and other things happen to Tribler.
So i ended up removing every trace of Tribler i could find on the computer and see how things will be with a clean install. Might be something wrong during installation or from a previous version doing something bad. Restarted the computer and installed Tribler_6.5.0-rc3-7-gdc80e16.exe which you gave me in an earlier comment.

So far, it launched well the first time. Everything works normal except for an error message each time a torrent was added. Still downloads them. Closed it got an error during the closing Tribler menu. Next time i started it, it worked fine, took some time(expected) but finally started downloading without crashing. Currently it's fine, but i'll try and see how things go, and if the problem occurs during future start ups, i'll let you know. 

This is the log file so far: 
https://mega.nz/#!pFhxkT5B!5ehnNtMuYoFcYRTek755dW2Bd6jHHeqZZjI9qeYyDiE

**Comment by whirm** [comment]
@Thomasedv that's unrelated to Tribler but maybe you should do a smart test run to make sure you disk is not dying.

Could you update to RC4? The issues you described should be (mostly?) fixed.

**Comment by Thomasedv** [comment]
Yeah know that's unrelated to tribler. I restarted the computer and it was fine. Will look more into that.

Wish i had noticed RC4 was out earlier. Will test it out and report back.

**Comment by Thomasedv** [comment]
Installed it. Adding torrents and closing tribler is without error now. So that's great! Tribler now starts successfully most of the time now. Had it crash once, but i'm not sure what the cause was. 

Had one error pop up during downloading though. Which was this. 

>Unable to load logging config from 'logger.conf' file.
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\SearchGridManager.pyo", line 606, in _do_gui_callback
  File "Tribler\Main\vwxGUI\list_details.pyo", line 935, in OnRefresh
  File "Tribler\Main\vwxGUI\__init__.pyo", line 119, in invoke_func
  File "Tribler\Main\vwxGUI\list_details.pyo", line 1300, in _Refresh
  File "wx\_controls.pyo", line 4594, in SetItemColumnImage
PyAssertionError: C++ assertion "id >= 0 && id < GetItemCount()" failed at ..\..\src\msw\listctrl.cpp(771) in wxListCtrl::SetItem(): invalid item index in SetItem

After that, Tribler crashed when i tried to close it. Nothing in the log file. Opening Tribler, it does connect fine but does a "checking" of each download, and resume each once that's completed.

**Comment by Thomasedv** [comment]
Works so fine i think this is solved right now. So i'll close and possbily make a new issue if the problem appears again.

**Comment by whirm** [comment]
@LipuFei seems that the flag issue is still not fixed :(
