### ISSUE TITLE
Seeding although I disabled it and set limit to 0 KB/s

### ISSUE THREAD

**Issue by EnolRekcah** [Tribler/tribler#1606]
I'm seeding although I disabled seeding to both Tribler-Peers and Bittorrent-Peers. I also set the Upload-Limit to 0 KB/s.

**Comment by whirm** [comment]
I've just reproduced it: Go to settings, disable seeding for both Tribler and Bittorrent peers, save and restart, download an ubuntu iso. It will stay in seeding mode.

**Comment by EnolRekcah** [comment]
What do you mean by "It will stay in seeding mode"?

**Comment by whirm** [comment]
It will not unload the torrent when it's finished downloading.

**Comment by EnolRekcah** [comment]
Yeah I know. But why is it uploading anyway? I mean I have disabled it.

**Comment by whirm** [comment]
I confirmed the bug, we still have to fix it :)

**Comment by EnolRekcah** [comment]
Okay thanks.
