### ISSUE TITLE
download is not running

### ISSUE THREAD

**Issue by kucenkelate** [Tribler/tribler#1610]
my 6.5 rc3 is refusing to download.

**Comment by kucenkelate** [comment]
http://s18.postimg.org/mqe89h621/tribler.jpg

[url=http://postimg.org/image/qmrk5gr1h/][img]http://s18.postimg.org/qmrk5gr1h/tribler.jpg[/img][/url]

**Comment by kucenkelate** [comment]
http://s1.postimg.org/ou2azo47j/tribler2.jpg

[url=http://postimg.org/image/jvesl50ej/][img]http://s1.postimg.org/jvesl50ej/tribler2.jpg[/img][/url]

**Comment by whirm** [comment]
Can you set it to 1 hop and see if it works?

Thanks!

**Comment by kucenkelate** [comment]
no change as i cannot get it to connect even to 1 hop.

**Comment by kucenkelate** [comment]
it halt at "building circuits"

**Comment by kucenkelate** [comment]
check the screenshot

http://s4.postimg.org/7po6jgpkd/rc4.jpg

**Comment by kucenkelate** [comment]
if choose  "no" for annom while choosing the torrent,i will able to download. So no link can be made if "download with proxies" was chosen. Without it,no annom will be enforced,right?

http://s7.postimg.org/mu3ghznuj/RC4_0.jpg

**Comment by kucenkelate** [comment]
If i untick this,will i be protected?

**Comment by kucenkelate** [comment]
if i untick the fuction,will i be protected from been seen? i found out that if did not use the fuction..i can download BUT if i choose the function..it will stay at "building circuits" forever.

http://s10.postimg.org/8pmtkl47t/Annom.jpg

**Comment by whirm** [comment]
If you don't use the tunneled download, it behaves as any other torrent client.

On the screen shot I see the downloads are set to 2 hops. Set it to one hop and see if it works. (We have some exit nodes running to help bootstrap the tunnel community, but the intermediary helpers will not be up until at least mid September. And as this is unreleased code, practically nobody is there to act as a tunnel helper.

**Comment by Thomasedv** [comment]
This issue was solved for me in RC-4, so i suggest trying that if you haven't.
