### ISSUE TITLE
Tribler is not in AUR

### ISSUE THREAD

**Issue by juanda-097** [Tribler/tribler#1627]
es{Tribler no está en los repositorios de Arch linux y no he podido instalar tribler en manjaro debido a eso.

PS:Al parecer lo han eliminado de los repositorios comunitarios

Gracias por vuestra atención}

en{Tribler is not in the repositories of Arch Linux and I could not install Tribler in Manjaro because of that.

PS: apparently they have been removed from the community repositories

Thank you for your attention}

**Comment by whirm** [comment]
We are not mantaining any repositories as we lack the manpower to do that, but it would be really nice if somebody could take care of this.

Gracias por el aviso :)

**Comment by xantares** [comment]
hey:
https://aur.archlinux.org/packages/tribler/

I'm not sure about some dependencies, it seems some aren't used anymore (pil? aspw? crypotgraphy ?):
https://github.com/Tribler/tribler/blob/devel/debian/control

**Comment by whirm** [comment]
That's great! thanks!

aspw is used in `sqlitecachedb.py` PIL is used in `VideoUtility.py`

Cheers!

**Comment by juanda-097** [comment]
Hi xantares the package that you have chosen is not stable, is a developer version of tribler which is not yet well developed and have some bugs, please change the package to the version 6.4.3(branch: master not develop).

Thank you for your attention.

**Comment by xantares** [comment]
Hi,
I can't get v6.4.3 to work, here's a traceback:
```
Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/Main/tribler_main.py", line 1112, in run
    abc = ABCApp(params, installdir, is_unit_testing)
  File "/usr/share/tribler/Tribler/Main/tribler_main.py", line 175, in __init__
    session = self.InitStage1(installdir)
  File "/usr/share/tribler/Tribler/Main/tribler_main.py", line 371, in InitStage1
    dlcfgfilename = get_default_dscfg_filename(self.sconfig.get_state_dir())
  File "/usr/share/tribler/Tribler/Main/globals.py", line 50, in get_default_dscfg_filename
    return os.path.join(state_dir, STATEDIR_DLCONFIG)
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```
SessionConfigInterface.get_state_dir returns None, any help on this ?
