### ISSUE TITLE
Security Account and password for WebUi

### ISSUE THREAD

**Issue by ncc2906** [Tribler/tribler#1634]
WebUi have no security control access, please add it
Thanks

**Comment by devos50** [comment]
WebUI is not maintained anymore and will be removed when the new GUI goes live.

**Comment by egbertbouman** [comment]
Working on a brand new webUI in Angular.
![image](https://user-images.githubusercontent.com/3785124/33545746-65377f42-d8df-11e7-950f-48ee183f622b.png)

**Comment by ichorid** [comment]
Web UI is dead (at least for now).
