### ISSUE TITLE
Peerblock

### ISSUE THREAD

**Issue by kucenkelate** [Tribler/tribler#1645]
Latest version rc4 refused to complete the building circuit if the peerblock is running. tried to get fix from peerblock but not avail.

**Comment by whirm** [comment]
Are plain torrent downloads working?

Did any older version of Tribler work with Peerblock?

**Comment by BmetaMax** [comment]
I've used peerblock with 643 for a long while, however you MUST set it to allow HTTP connections or it will default block all connections to peers.
After that it just takes occassional adjustments as it will block blacklisted IP's, whether or not you personally want to allow connections to/from tribler at those IP's- most of them are blacklisted for being known p2p points.

**Comment by colin1497** [comment]
What BmetaMax said.  I just started RC5 w/ peerblock and a couple anon seeds and it took some time to set up circuits, but it happened eventually.  It just has to discover enough non-blacklisted clients.

**Comment by kucenkelate** [comment]
"HTTP" is always allowed,sire...

1. Tixati is running well but with low speed....

2. Tribler cannot complete the circuits...

"Details about network security diagnosis: 

Settings that might be blocking the connection:
Provider name: 		-
Provider description: 	-
Filter name: 		PeerBlock Flow Inbound Filter for IPv4.
Provider context name: 	-

Details about network security diagnosis: Tribler

Settings that might be blocking the connection:
Provider name: 		-
Provider description: 	-
Filter name: 		PeerBlock Flow Outbound Filter for IPv4.
Provider context name: 	-"

http://s2.postimg.org/c02s8zpih/My_List.jpg
http://s2.postimg.org/4hjn0cy5l/Peerblock_tribler.jpg

is it too much?

**Comment by kucenkelate** [comment]
"HTTP" is always allowed,sire...

1. Tixati is running well but with low speed....

2. Tribler cannot complete the circuits...

"Details about network security diagnosis: Tixati

Settings that might be blocking the connection:
Provider name: 		-
Provider description: 	-
Filter name: 		PeerBlock Flow Inbound Filter for IPv4.
Provider context name: 	-

Details about network security diagnosis: Tribler

Settings that might be blocking the connection:
Provider name: 		-
Provider description: 	-
Filter name: 		PeerBlock Flow Outbound Filter for IPv4.
Provider context name: 	-"

http://s2.postimg.org/c02s8zpih/My_List.jpg
http://s2.postimg.org/4hjn0cy5l/Peerblock_tribler.jpg

is it too much?

**Comment by whirm** [comment]
All the Tribler/Dispersy/anontunnel traffic is UDP and going trough the same port. (Except for the plain bittorrent traffic which uses it's own and the separate DHT implementation which also uses a dedicated one) The only TCP traffic Tribler can generate is when it talks to TCP bittorrent trackers.

**Comment by whirm** [comment]
If the red list are blacklisted IP's you are blocking known good IPs (such as our dispersy trackers used for bootstrap)

I would make a post on the forums and see if any fellow user can help you. We are too understaffed right now to give support to issues with third party stuff. Sorry :(

**Comment by kucenkelate** [comment]
mind to tell me the our dispersy trackers' address?

**Comment by synctext** [comment]
Could you please try disabling all blockers for a bit, is that giving Tribler RC5 the troubles?

The accurate list of trackers+IPv4
https://github.com/Tribler/dispersy/blob/devel/discovery/bootstrap.py

Their IPv4 is resonable stable. but subject to rate changes.

hope this helps with the blocking.

**Comment by whirm** [comment]
Let's move this discussion to the forums as it's not a Tribler issue.
