### ISSUE TITLE
Can the Tribler project collaborate with zeronet?

### ISSUE THREAD

**Issue by Mrkebubun** [Tribler/tribler#1646]
i just visited zeronet project i think tribler can work togather with zeronet.
please take look.
www.zeronet.io

**Comment by whirm** [comment]
Edited title to actually describe what the request is.

Thanks for your heads up!

**Comment by UC3829** [comment]
Some other related projects:

https://en.wikipedia.org/wiki/Osiris_%28Serverless_Portal_System%29
http://www.osiris-sps.org/

http://project-maelstrom.bittorrent.com/
http://blog.bittorrent.com/tag/maelstrom/

**Comment by synctext** [comment]
zeronet is moving into another direction as Tribler.
Not really compatible.
