### ISSUE TITLE
Can torrent Pause be a discrete option from Stopped? (Enhancement suggestion if feasible)

### ISSUE THREAD

**Issue by BmetaMax** [Tribler/tribler#1662]
First I don't know how feasible this is, but over the weekend I was thinking that some additional pause functionality would be nice to have. Admittedly, this is based off my method of usage and I don't know how many other people use tribler the same and if they would benefit.
Use case- Complete pause of all active torrents, different than stopping all, which would restart only those files not in stopped state. For example, I leave a lot of files in stopped state that I simply don't currently have the disk space for but when I do would like to be able to start, however in the context menu from the tray icon my only choices are stop all and resume all, but I don't want to resume the stopped torrents I don't have space for so if I could pause all active torrents, then restart them discreetly from the stopped torrents instead of how it currently works of having to either manually selecting those I want to start from the main window or starting them all from the context menu and then stopping the ones I don't want to let run.
Other use-cases where this might be good:
1. if someone's switching network connections, only pausing to change IP's or establish a VPN per se and though socketed connections would have to be renegotiated at least the files wouldn't have to be re-initialized from scratch.
2. Temporary shutdown, if a user needs to pause all up & down in order to free up bandwidth on a limited connection, but then will resume shortly and doesn't want to lose the peer connections.

Other use cases may apply that I haven't thought of.

**Comment by whirm** [comment]
Yeah, that would be a nice feature.

**Comment by ichorid** [comment]
Haven't seen anyone asking about such feature. Closing this one.
