### ISSUE TITLE
Issue: During installation of Tribler after having a prior biuld installed it says it'll delete from a default directory even though that's not where Tribler is installed.

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#1664]
Basically, on my W10 computer, i have Tribler installed in a folder under disk D somewhere. When i try to install a build it would say it's going to delete the old from from "C:\Program Files (x86)\Tribler" Which is not the location, or even close. I'm not sure which effects this could have on the program, if another installation is made too. It's says it's going to remove rc-5(installing a more recent build) which is my current one, and i'm not sure if it shows it wrong or not. I'd just delete my installation from the correct folder manually but i'm not sure if there are other files that should stay in the folder or if there are files elsewhere(like in the roaming folder) that are supposed to be affected, and probably are. Since you can't choose where it'll uninstall you kind of are stuck. 

Also the folder it says it'll delete from does not exist. And after running the remover of it, the folder remains in D which means nothing has changed, and i can still use Tribler even though i just ran the remover which popped up after trying to install the newer build. 

There is a simple way to circumvent, and that's simply using the uninstall file in the folder itself which will target the right place.

**Comment by whirm** [comment]
Hm, never noticed that. 

We will get that fixed.

The only issue there that bug brings is that it abandons files on the real file location. The .Tribler dir gets updated by Tribler itself at startup time, so no problem there.

Thanks for the report!

**Comment by whirm** [comment]
@lfdversluis could you see if this bug is still there after all your unstaller modifications?

**Comment by lfdversluis** [comment]
@whirm This will be still there. I have seen the string that the uninstaller targets and that is the $InstallDir. I have not seen code that changes this if the user specifies something else.

**Comment by whirm** [comment]
I guess it should use a registry entry for that?

**Comment by lfdversluis** [comment]
@whirm I'll take a look at it

**Comment by whirm** [comment]
great
