### ISSUE TITLE
Explore files should select the file

### ISSUE THREAD

**Issue by adamjimenez** [Tribler/tribler#1668]
Right click a download -> Explore files.
This opens a file explorer window with the correct location. It would be nice if it automatically selected the file as well. (win 7)

**Comment by colin1497** [comment]
Actually, I find that explore files wants to open the default download directory, even if you've got another directory configured, and even if the torrent is located in another directory.

**Comment by BmetaMax** [comment]
in 643 it opened the correct/actual subfolders 9/10 times for me. With rc5 it opens the default top level directory I have set in tribler settings. So I'd say it's probably related to the fixes, I guess I assumed it would go back to working eventually but good to bring it up.

**Comment by adamjimenez** [comment]
In Win 10, it always goes to the correct folder for me. But it doesn't select the file if it's a single file being downloaded. This would be useful when you have a lot of files in your download directory.

**Comment by whirm** [comment]
As a new GUI is being written, I'll assign this to the new gui milestone as a reminder to implement this properly there.

Thanks for all the feedback!

**Comment by synctext** [comment]
Changed with Gigachannel hand-coded QT GUI.

**Comment by devos50** [comment]
@synctext this issue is not solved yet. Do we want to address this or not?
