### ISSUE TITLE
Sometimes when adding a previously downloaded torrent, name is blank [Still Exists 6.6.0-exp1 G1725b60]

### ISSUE THREAD

**Issue by colin1497** [Tribler/tribler#1669]
This is existed in 6.4 and exists in the 6.5 RC's at some level (saw it today).

When you remove a torrent, but later re-add it, sometimes it doesn't show the name.  I don't know what exact circumstances are required to recreate it.  I think they've gotten better in 6.5 because I've seen it less, but I definitely saw it today.

In 6.4 I often removed and re-added torrents as part of the "download public, seed anon" workflow, and I saw this happen maybe 10% of the time.  Sorry I don't have more info.

**Comment by colin1497** [comment]
Verified behavior in RC6.

**Comment by whirm** [comment]
@colin1497 This is when removing it on the same run? Does it happen when you restart Tribler inbetween? 

Have you noticed that now you can choose safe seeding for a download which should do exactly what you want?

**Comment by colin1497** [comment]
Just removed the torrent I had exhibiting this behavior, restarted tribler, added it, and again got no name.  I have never seen this behavior when downloading a new torrent, only when adding one that was already downloaded, but it happens relatively frequently in that case and has in every version of Tribler that I've used, so this is not a new bug.

I am aware of the new feature, actually #1684 is when using this feature and also applies to this particular torrent.  It was at 20% redownloading it anon when I restarted, but when I added the torrent back after restart it checked it and started again downloading it anon, even though I unchecked the box to download anon in the dialog and am theoretically only seeding anon.

**Comment by colin1497** [comment]
FYI, just had this happen again.  Had a download that somehow wasn't flagged as anon, so I removed and added it and had the problem.

Also, had this error log last time I shut down, may be related to the files not being flagged as anon after restart (or may not have anything to do with issues I have open):

Traceback (most recent call last):
  File "Tribler\Main\Dialogs\AddTorrent.pyo", line 96, in OnAdd
AttributeError: 'ManageChannelFilesManager' object has no attribute 'startDownloadFromArg'
ERROR   1448521932.44             log:443   Unhandled Error
Traceback (most recent call last):
  File "threading.pyo", line 763, in run
    
  File "Tribler\Core\Utilities\twisted_thread.pyo", line 55, in _reactor_runner
    
  File "twisted\internet\base.pyo", line 1192, in run
    
  File "twisted\internet\base.pyo", line 1201, in mainLoop
    
--- <exception caught here> ---
  File "twisted\internet\base.pyo", line 797, in runUntilCurrent
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 1064, in on_data
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 722, in relay_packet
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 1255, in crypto_relay
    
  File "Tribler\community\tunnel\crypto\tunnelcrypto.pyo", line 81, in decrypt_str
    
  File "cryptography\hazmat\primitives\ciphers\base.pyo", line 174, in finalize
    
  File "cryptography\hazmat\backends\openssl\ciphers.pyo", line 137, in finalize
    
cryptography.exceptions.InvalidTag: 

Unhandled Error
Traceback (most recent call last):
  File "threading.pyo", line 763, in run
    
  File "Tribler\Core\Utilities\twisted_thread.pyo", line 55, in _reactor_runner
    
  File "twisted\internet\base.pyo", line 1192, in run
    
  File "twisted\internet\base.pyo", line 1201, in mainLoop
    
--- <exception caught here> ---
  File "twisted\internet\base.pyo", line 797, in runUntilCurrent
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 1064, in on_data
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 722, in relay_packet
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 1255, in crypto_relay
    
  File "Tribler\community\tunnel\crypto\tunnelcrypto.pyo", line 81, in decrypt_str
    
  File "cryptography\hazmat\primitives\ciphers\base.pyo", line 174, in finalize
    
  File "cryptography\hazmat\backends\openssl\ciphers.pyo", line 137, in finalize
    
cryptography.exceptions.InvalidTag: 
Unable to rename the log file!

**Comment by colin1497** [comment]
I restarted it again and it crashed again on exit, following log, may be unrelated:

Traceback (most recent call last):
  File "wx\_core.pyo", line 14669, in <lambda>
  File "wx\lib\delayedresult.pyo", line 82, in __call__
  File "Tribler\Main\vwxGUI\__init__.pyo", line 119, in invoke_func
    
  File "Tribler\Main\vwxGUI\list.pyo", line 1545, in _ShowSuggestions
  File "wx\_core.pyo", line 14619, in __getattr__
wx._core.PyDeadObjectError: The C++ part of the ListBody object has been deleted, attribute access no longer allowed.

**Comment by whirm** [comment]
@colin1497 If you get different stack traces, please create separate issues (If there's no report for that one already) or we will probably miss some.

I'll have a look at these ASAP.

Thanks!

**Comment by colin1497** [comment]
@whirm probably need to try and do builds a little more frequently so people aren't distracted by closed issues.  I'm not suggesting automated nightly builds or anything, but it's been a while since there was an updated test build.  Just thinking out loud.

**Comment by whirm** [comment]
@colin1497 we do have [automated builds](https://jenkins.tribler.org/job/Publish_tribler_next/) 
That job will build packages for all supported platforms every time a fix gets merged into `next`. 
I guess the `CONTRIBUTING.md` file could do with some instructions on how to backup `.Tribler` and test the latest stabilization branch build to make sure the bug they are reporting is not already fixed or made irrelevant.

Are you up for it? :)

**Comment by Pathemeous** [comment]
Made a PR: #1785.

**Comment by colin1497** [comment]
Sorry, been a bit busy.  Probably trying to provide best feedback I can is all the contribution I can make at this time.

**Comment by colin1497** [comment]
Sure, not a big deal at all to copy my .tribler directory and try to reproduce in the latest tribler_next build.

**Comment by colin1497** [comment]
Just wanted to verify that this still exists in 6.5.  Just accidentally started 2 DL's as anon in a 6.5 RC nightly build.  Realized I hadn't upgraded in a while, checked, saw the release, downloaded, shut down tribler, installed 6.5 release as upgrade.  The 2 downloads were there, trying to download anon, but otherwise no problems.  I then:

1) copied magnet link
2) removed download (NOT download + data)
3) pasted magnet link in search box, hit search
4) selected to download torrent, seed anon

Now both downloads are without a name in my download list in tribler.

**Comment by devos50** [comment]
@whirm we believe this issue is related to the name being set to `NULL` in the database when removing a torrent but we should further investigate this.

**Comment by lfdversluis** [comment]
@colin1497 We tried reproducing this bug but we are unable to do so. Does this error happen with specific torrents? Any non utf-8 (hebrew, chinese, kanji) characters in it? Or unicode perhaps?

it would be awesome if you found a consistent reproducible way with a given torrent.

**Comment by colin1497** [comment]
I can't give you a reproducible scenario.  Here's what I know:

1) It doesn't happen the first time you download a torrent.  It happens only if you delete a torrent and then add it again.  Most often I have it when I improperly select privacy settings and want to change them.
2) Once it happens, I can't get tribler to correct the problem.  the @devos50 description sounds accurate, the name is getting set to null and never gets overwritten no matter what the user does.

**Comment by colin1497** [comment]
Update: just had it happen on a new download.  I deleted my torrent cache and it fixed it for that one, but didn't fix it for one of the older ones that was broken.  I deleted my databases and it fixed it for everything.  Of course, I lost my channel....

**Comment by synctext** [comment]
Colin, when you delete a torrent in Tribler you get a popup I assume. Do you delete on disk also?

**Comment by colin1497** [comment]
Sometimes?  Sometimes I may want to keep it on the disk and restart as non-secure?  That's what started this thread, before there was a functionality to download torrent and seed tribler I would download torrent, copy magnet, delete torrent (not files), search magnet, download tribler and now I would be seeding tribler.

**Comment by colin1497** [comment]
Just reproduced again in recent build.  Had a torrent that wasn't seeding for some reason, wasn't sure why, so I removed it from my list, put the magnet in the search box, now I have a torrent with no name that is seeding.

**Comment by devos50** [comment]
I think I found out what's causing this. A magnet link has a special part (`dn`) that specifies the display name of the magnet download in a client. If that part is absent, the displayed name for the download is blank.

We should have a better default name when adding a magnet link without `dn` element.

**Comment by colin1497** [comment]
That's interesting.  The question is: why does this happen only the 2nd time?  I'm copying the magnet link *from Tribler* in most, if not all, cases.  Should Tribler be adding this `dn` element if it doesn't exist?
