### ISSUE TITLE
IOError: IO error: lock /home/quite/.Tribler/LOCK: already held by process

### ISSUE THREAD

**Issue by quite** [Tribler/tribler#1676]
Just found this thing, tribler... Fairly hard to get up and running, I must say. Or is that just me...

After managing to squeeze in all dependencies, I found the code broken and submitted a small fix #1675.

Now tribler just complains with the error in title, and I got a bit tired. What up with LOCK?

**Comment by synctext** [comment]
Yes, sadly, hard to get running.. Complex stuff. Can you please try the latest Devel code?
Lot of changes past year. Closing for now, please re-open if you still get stuck.
