### ISSUE TITLE
Video broadcasting with SwarmPlayer

### ISSUE THREAD

**Issue by UC3829** [Tribler/tribler#1677]
I am opening an issue here because the Tribler forum appears offline (http://forum.tribler.org/)

I have been looking for a good p2p broadcasting application because I want to start a live TV channel with original content, conversation & interviews.  I see that Wikipedia says:

"Tribler also features a built-in video streamer known as SwarmPlayer."
https://en.wikipedia.org/wiki/Tribler

However, I cannot figure out how to broadcast a live video stream with Tribler.  Is this a hidden feature?

If you have a p2p video streaming technology that works, maybe you should create a dedicated application like Acestream or Sopcast, please.  Those other applications are less than perfect and need some competition.  =)

**Comment by whirm** [comment]
Live streaming support was removed due to lack of manpower to maintain it. You can look at the PSPP reference implementation project: https://github.com/libswift/libswift Which was developed at our university too and was used to offer that feature in Tribler.

BTW, the forums are up again :)

**Comment by whirm** [comment]
I'm closing this now, feel free to reopen it if you have more questions.

Thanks!

**Comment by UC3829** [comment]
I just wanted to add these references for any users or developers who may be interested in a similar project.

http://www.swirl-project.org/
https://github.com/skunkwerks/swirl
