### ISSUE TITLE
Forum is inaccessible

### ISSUE THREAD

**Issue by eaglgenes101** [Tribler/tribler#1678]
Well, the "forum under attack" issue fit in the issue tracker well enough, so I guess this will do well too. 

Anyway, I'm not able to connect with forum.tribler.org. It times out all connections to it, and ping packets are never responded to, not even with an error message. Can others confirm that they are experiencing forum downtime too?

**Comment by synctext** [comment]
yeah, our proxmox server is down. reinstalling fresh..
