### ISSUE TITLE
Dependency issue with python-wxgtk2.8

### ISSUE THREAD

**Issue by nllz** [Tribler/tribler#1681]
Hi all,

Am on Debian Jessie / Stable / 8, and am trying to install Tribler, but there is an issue with an unmet dependency: python-wxgtk2.8. I have python-wxgtk3.0 and python-wxgtk3.0-dev installed, but Tribler won't install, and v2.8 is not in the repositories. 

Any suggestions?

Best,

Niels

**Comment by themusicgod1** [comment]
Debian has asked tribler to migrate away from wxwidgets 2.8 and removed tribler from debian because of their lack of interest in moving away from it (last I read, it was one of two packages in debian that still was based on 2.8).

This issue is basically #875

**Comment by whirm** [comment]
@nllz You can get WX 2.8 from either either the oldstable or experimental repos. 

@themusicgod1 I'll have a look at the patch ASAP, thanks for the heads up!

I'll start working on the WX3 migration as soon as 6.5 is released. That should have been done a long time ago.

**Comment by nllz** [comment]
@themusicgod1 Install in Debian with package in report is not working either :(

$ sudo apt-get install tribler 
[sudo] password for #####: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package tribler is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'tribler' has no installation candidate

**Comment by whirm** [comment]
> $ sudo apt-get install tribler

If Tribler is not on the Debian repositories, this won't work. You will need to first install WX 2.8 from debian experimental or oldstable and then download the `.deb` from the `releases` tab and install it.

**Comment by whirm** [comment]
@nllz: If you need more directions, please create a post on [Our forums](http://forum.tribler.org) describing your issue.

Cheers!

**Comment by nllz** [comment]
@whirm I think the problem is a bit more complicated since Tribler is listed in the Debian repo.

**Comment by BoringUserWhoCantCode** [comment]
Same Problem. python-wxgtk2.8 is not in Jessie main repos.

This should not be closed. It should be re-opened for contributors.
This is a legitimate issue that needs the code to migrate on to python-wxgtk3.0, not python-wxgtk2.8.

I think, at least.

**Comment by devos50** [comment]
@BoringUserWhoCantCode we are working on this. Our upcoming Tribler 6.6 alpha contains full support for python-wxgtk3 so this should solve the problem. See for instance PR #2047 where most of the work regarding wx3 has been done.

**Comment by whirm** [comment]
@BoringUserWhoCantCode We are working in releasing the last bugfix release for v6.5. Shortly after we will release the first v6.6 Alpha which as @devos50 said has wx3.0 support among other things.

**Comment by BoringUserWhoCantCode** [comment]
Awesome work, indeed.

Can't wait to try it when this is solved.

Thank you all very much for your efforts.
