### ISSUE TITLE
Why is "Pioneer One" used as a test?

### ISSUE THREAD

**Issue by themusicgod1** [Tribler/tribler#1688]
Seems like this is just asking for trouble using copyrighted material in a test.  Am I missing something? is it not proprietary?

https://github.com/whirm/tribler/commit/4faa5b8ea8bb073c3b11e7c6e69b6507471a5cbe
https://github.com/Tribler/tribler/tree/devel/Tribler/Test/data

**Comment by themusicgod1** [comment]
Looks like they did release it on bittorrent, disregard

**Comment by whirm** [comment]
We also have a Gbit/s seeder on the files we use for testing/experiments now, so everybody benefits :)
