### ISSUE TITLE
"Exit node" description should be more clear.

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#1690]
> By allowing Tribler to be an exit node, it's possible to become a proxy for someone elses traffic. 
This may cause problems in some countries.

Does it proxy _only_ BitTorrent traffic or somebody can send spam though Tribler's exit node like with Tor?

I may want to allow other's bittorrent though this station, but don't want to get into an open proxy blacklist.

**Comment by whirm** [comment]
It's a UDP proxy, so no worries about that, it also has some content filters to only let pass bittorrent-looking traffic.

Just to double check: @egbertbouman can you confirm this?

**Comment by whirm** [comment]
@vi I'll update the warning text with a better description ASAP.

**Comment by egbertbouman** [comment]
@whirm Yup, it should only allow BitTorrent/dispersy traffic.

**Comment by whirm** [comment]
@egbertbouman thx!
