### ISSUE TITLE
v6.5.0-rc6: Download bandwidth limit is not observed

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#1700]
Configured for 200 KiB/sec down, 100 KiB/sec up, but actually downloading 1.3 MiB/s (and counting).

Anonymity is turned on both ways.

**Comment by whirm** [comment]
@rjruigrok is bandwith throttling implemented on the tunnel community?

**Comment by whirm** [comment]
Actually it's libtorrent who should be controlling this even with anon downloads...

**Comment by whirm** [comment]
I'll have a look, thanks for the report!

**Comment by vi** [comment]
I don't remember observing such behaviour in v6.4.3

**Comment by whirm** [comment]
Well, the tunnel community got mostly rewritten after 6.4.3 so it makes sense.

**Comment by vi** [comment]
Why it's not Tribler v7.0 then?

**Comment by whirm** [comment]
Because it was an experimental feature I guess. @synctext?

**Comment by vi** [comment]
Note that I have discovered previously absent context menu item "Bandwidth allocation" for a download, suggesting that it is possible to set bandwidth per-download.

That's nice feature, but I think the global limit should still be applied together with per-download limit.

**Comment by rjruigrok** [comment]
@emilon as far as I know, no bandwidth throttling is available in the
tunnel community. The limits for libtorrent will continue to work when
downloading/uploading files. But all the bandwidth related to relaying and
exiting somelne else's data is not limited.

The tunnel community has some functions that monitor the relayed / exited
data, they are used for bartercast and signing certificates for donating
bandwidth where @snorberhuis is working on. But limiting bandwidth is
something that stilll must be done. I would prefer a solution in the socks
wrapper, as it is the lowest level.

Op zaterdag 31 oktober 2015 heeft Vitaly Shukela <notifications@github.com>
het volgende geschreven:

**Comment by whirm** [comment]
@rjruigrok is the socks wrapper used for forwarded traffic?
