### ISSUE TITLE
v6.5.0-rc6 Wrong status is displayed for a file being downloaded

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#1702]
I see `Status: Torrent file is being downloaded from the DHT (10.2%).`

It should be `Downloading (10.2%)`

**Comment by whirm** [comment]
Hm, how do you reproduce this? I'm seeing "Downloading @XXKB/s (XXX%)" (checked on about 20 downloads)

**Comment by vi** [comment]
Found a torrent using search and downloaded it.

**Comment by vi** [comment]
Now I see "Seeding 100%" in the download list, but still "Torrent file is being downloaded from the DHT" in Status in lower pane.

**Comment by lfdversluis** [comment]
Reproduced the issue, see https://gyazo.com/75a48cf8c7ee14e66bb436aba4c83560 in the panel it says downloading from dht, in the status it is fine. Investigating now.
