### ISSUE TITLE
Maybe Tribler v6.5.0 should be called v7.0.0?

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#1703]
Storage of collected torrents files got changed in a major way, requiring migration.

User is probably not expected to start Tribler <= 6.4.3 after starting the new Tribler...

That looks more like a Tribler v7.

**Comment by whirm** [comment]
@synctext maybe you wan to join the discussion?

We usually consider the third digit (bugfix releases) to keep on disk backwards compatibility, 2nd is new features (often requiring on disk data changes like the new torrent and thumbnail storage system), and third is major breakage such as protocol-level incompatibilities.

What we maybe could do is to have a dialog warning people about on disk compatibility changes before going forth.

Maybe a .zip backup could be done too.

**Comment by lfdversluis** [comment]
Just my cents here, I guess launching all the items planned for 6.7 (credits, ratio enforcement, code/speed improvements, (major) gui update, multichain etc.) can be called v7. 6.6 contains the upgrade to wx3 with additional bug fixes; some items but nothing major (I think).

**Comment by vi** [comment]
The main issue that there is migration procedure from 6.4 to 6.5 (delecting collected_torrent_files, etc.) and user is not supposed to downgrade back to 6.4. That may be called "breaking change" requiring major version bump.

**Comment by devos50** [comment]
Since 6.5 is already released, we cannot make it backwards compatible with 6.4.3 unfortunately. We should keep this in mind for next releases.

**Comment by whirm** [comment]
What we should do, is to offer to make a backup of the data before the migration or keep a different state directory for each new Tribler on disk format change like other programs do, (Android Studio comes to mind).

**Comment by lfdversluis** [comment]
@whirm This issue can be closed, it is no longer relevant. Re the backup of the data, if it's desirable it should go into a new issue (wasn't there one?). Apparently backwards compatibility may be broken more in the future, as per @synctext mention in #2106.

**Comment by whirm** [comment]
@lfdversluis that's a differend kind of break, one thing is breaking on disk format compatibility and the other is protocol compatibility.

**Comment by synctext** [comment]
The naming convention is actually never documented or formalized. It's user-uptake focused.
The convention I used so far was something like: new major number when release has an understandable killer feature that can be explained in a TorrentFreak/Arstechnica post.

Putting this aside, 7.0 probably has a lot of radical changes (QT GUI, credits, Android, etc.).

**Comment by synctext** [comment]
Current plan... Next version with GUI re-write will be 7.0
When anonymous download goes out of Beta: 8.0
