### ISSUE TITLE
Download table columns visibility editor has misleading UI and can't be opened without any downloads.

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#1704]
In tribler v5.4.3 downloads showed "ratio" field (and was able to sort by it).

Now I don't see it.

Without ratio or accumulated upload size user don't see the relative popularity of his shared content.

**Comment by whirm** [comment]
Thanks!

**Comment by whirm** [comment]
Do you mean v6.4.3? I can't see this ratio field on the sorting option list.

**Comment by vi** [comment]
Yes, v6.4.3, the previous version.

**Comment by whirm** [comment]
I've installed that version on windows, and on the "sort by" list, there's only  name, progress, ETA, down speed, up speed, connections, anonymous, no ratio there. Maybe it was an older version?

**Comment by vi** [comment]
Maybe I confused it with sorting by progress or by ETA. Or maybe sorting by progress implicitly (or by chance) sorted it by ratio among "Seeding" entries.

Anyways, if it is as easy to sort by ratio as by other columns, why not have such option?

**Comment by vi** [comment]
Update: I opened a context menu on a download and saw the misleading "Show labels" context menu item.

There I can enable ratio column. After enabling the ratio column, I can also sort by it.

Reformulating the issue to be about misleading UI rather about absense of a feature.

**Comment by vi** [comment]
It should be "Show columns" instead of "Show labels". This menu should be openable from the header line `Sort by  | Download state | File size ------------ | Filter downloads`, not from the context menu of a download.

**Comment by whirm** [comment]
Thanks for the update!

**Comment by devos50** [comment]
@whirm should be easy to fix but not a top priority for now I guess.

**Comment by whirm** [comment]
The "columns" label part could be fixed quickly and the rest taken as a usability reminder for the new UI.
