### ISSUE TITLE
Error: u'file too short

### ISSUE THREAD

**Issue by renang010** [Tribler/tribler#1705]
Hi,
I am using OS X El Capitan and Tribler 6.5.0 - rc5.

After a couple of minutes of download, Tribler stops and pops the message: Download stopped on error: u'file too short: reading p: 1485 b:0 s: 524288 (read: 0)'.

Hit ok, message disappears, and then it pops up again. Indefinitely. 

Renan

**Comment by whirm** [comment]
Could you upgrade to https://jenkins.tribler.org/job/Build-Tribler_OSX_next/166/ as it contains some fixes for OSX.

And if it still happens, quit Tribler and  temporarily rename your `.Tribler` directory to something else and see if this fixes your issue? This is just to check if there's a corrupt file on the state dir that is triggering this message.

**Comment by renang010** [comment]
New build worked. thanks.
