### ISSUE TITLE
6.5.0.RC6 Ratio not working

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#1709]
I have set my seeding ratio to three, I am seeding and is already on 11.8, normally it should stop when I reach my ratio setting.
Also log file is not receining any errors, while this RC6 abends quite a few times with errors, but none appear witin log.
This is on a Zotac ID42 with 12 gig memory, Windows 10 Pro x64.

**Comment by whirm** [comment]
Could you open a different issue for the errors you are getting which don't get written to the log file?

Thanks for your reports!

**Comment by whirm** [comment]
Fixed by #1725
