### ISSUE TITLE
OS X caught Tribler burning CPU

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#1713]
http://pastebin.com/nVCjMYSD

**Comment by whirm** [comment]
Did it hang it was working properly?

**Comment by Dmole** [comment]
I woke up, logged in and found it was not running, but I would guess it hung in a tight loop for OS X to kill it because I do plenty of CPU warming activities and never had this happen before.

**Comment by whirm** [comment]
I guess it's too late for you to have a look at the logs to see if there's anything that could help us?

**Comment by Dmole** [comment]
console logs are in the pastebin, don't see any more in ~/Tribler

**Comment by whirm** [comment]
Oh, I see.
Tribler on OSX is know to consume more CPU than it should. I suspect something is wrong on the GUI/WX side, but I haven't had time to investigate on this.
If you add this to the new tunnel community, which does a lot of en/decryption and you have a proper internet connection, it can get pretty hot. 

I will probably have a couple of master students working on splitting the GUI from the core so we will be able to have a headless version of Tribler and another one which will work on migrating Tribler to WX 3.0. That will possibly help with this issue.

**Comment by synctext** [comment]
An older version of what we also see in #2504.
Closing this ticket, as it's over a year old. With our new core we could re-open if happens again.
