### ISSUE TITLE
Can't install Tribler 6.5.0-rc6 on Kubuntu

### ISSUE THREAD

**Issue by Konstamokh** [Tribler/tribler#1715]
I successfully opened the .deb installer, but when I click on "Install Package" nothing happens.
Could someone check if this is just me or every Kubuntu installation?

**Comment by whirm** [comment]
Have you tried doing it from the command line?

**Comment by Konstamokh** [comment]
dpkg: dependency problems prevent configuration of tribler:
 tribler depends on ffmpeg | libav-tools; however:
  Package ffmpeg is not installed.
  Package libav-tools is not installed.
 tribler depends on libjs-excanvas; however:
  Package libjs-excanvas is not installed.
 tribler depends on libjs-mootools; however:
  Package libjs-mootools is not installed.
 tribler depends on libsodium13; however:
  Package libsodium13 is not installed.
 tribler depends on python-apsw; however:
  Package python-apsw is not installed.
 tribler depends on python-cherrypy3; however:
  Package python-cherrypy3 is not installed.
 tribler depends on python-decorator; however:
  Package python-decorator is not installed.
 tribler depends on python-feedparser; however:
  Package python-feedparser is not installed.
 tribler depends on python-gmpy; however:
  Package python-gmpy is not installed.
 tribler depends on python-leveldb; however:
  Package python-leveldb is not installed.
 tribler depends on python-libtorrent (>= 0.16.4); howe
dpkg: error processing package tribler (--install):
 dependency problems - leaving unconfigured
Processing triggers for gconf2 (3.2.6-3ubuntu5) ...
Processing triggers for man-db (2.7.4-1) ...
Processing triggers for menu (2.1.47ubuntu1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu3) ...
Processing triggers for mime-support (3.58ubuntu1) ...
Errors were encountered while processing:
 tribler

Apparently I'm missing many packages that tribler needs.

**Comment by Konstamokh** [comment]
Well, I installed the missing dependencies and now it works.
My question now is, why didn't it show a dialogue that asks if I want to install the missing dependencies when I clicked on install?

**Comment by whirm** [comment]
@Konstamokh I wouldn't know, sorry. I'm not familiar with Kubuntu anymore (I haven't used it for years)

Closing this as it's not Tribler related. Don't hesitate to open another issue if you have any issue with it.

Enjoy!

**Comment by Konstamokh** [comment]
So, it's probably a bug with Kubuntu specifically? Not Ubuntu in general?
If I experience it with the next stable release of Tribler, I will probably open another issue.
I think a stable release should not run into problems while installing, even if those problems are easily fixed. One reason why people are afraid of Linux distributions is using the Terminal and developers should try to attract those people by making this use of the Terminal unnecessary.
(At least for "mainstream" applications like, for example, torrent clients.)

**Comment by whirm** [comment]
I would say it's a bug on the package manager (last time I used kubuntu it used Adept, I don't know if it still is the case) But Tribler can't do much about it, we generate a valid package and the package manager has to be able to deal with that. Maybe you could open an issue on Kubuntu's package manager issue tracker, you could link to the particular .deb that's failing for you if you have others that work. 
Also, I guess there wasn't any message telling you something was wrong that you overlooked, right?

**Comment by Konstamokh** [comment]
I'm pretty sure there was no message. I just clicked on install and nothing happened.
I'll try it again sometime after I uninstall Tribler and a few packages it depends on. If it still doesn't work, I'll open a bug report.
What OS are you using at the moment?

**Comment by whirm** [comment]
I've been using Debian SID for years now.
