### ISSUE TITLE
Feature request: Sequential download without starting player

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#1718]
I prefer using external player.

v6.5.0-rc6 also crashes with segfault when it tries to start video (after buffering).

Untangling sequential mode from player would be nice.

For example, in Files tab there can be third option "Download sequentially" in addition to "Include" and "Exclude".

**Comment by whirm** [comment]
Could you create a separate issue for the segfault issue?

Thanks!

**Comment by ichorid** [comment]
Another reason to use external VLC #5388

**Comment by qstokkink** [comment]
This has been solved years ago. The REST API has a `/api/downloads/{infohash}/stream/{fileindex}` (upcoming 8.0 release, `/downloads/{infohash}/stream/{fileindex}` on older releases) endpoint to serve this functionality.
