### ISSUE TITLE
Reduce the number of Pylint errors

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#1728]
The number of Pylint errors is huge. Some effort should be made in order to decrease the number of Pylint errors.

Moreover, we can add a feature that automatically rejects pull requests that increase the number of Pylint errors.

**Comment by whirm** [comment]
It's more or less set up on jenkins.
The only issue we have is that it compares against the latest PR run, we need to find a way to make it compare against upstream devel/next or make a small script that does that. We should start enforcing it post-6.5.

**Comment by Solomon1732** [comment]
Some of the pylint errors arise from it checking for py2 syntax while the project has switched to py3.
