### ISSUE TITLE
Increase code coverage by running unit tests on OS X and Windows too

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#1729]
Currently, the code coverage covers 48% of the conditional statements. This number can be increased by also running unit tests on OS X and Windows since many of the statements are only executed on specific platforms. At the end of the build process, the code coverage reports can be merged.

**Comment by whirm** [comment]
Not only that, but it will allow us to catch bugs on non-Linux platforms way quicker than now. We notice stuff is broken on Windows when we start a release cycle which greatly delays releases.
I would love to have this up and running for the release after 6.5

**Comment by devos50** [comment]
I've setup a job to run the unit tests on windows (not with Gumpy unfortunately since a required import of Gumpy is missing on Windows - have to investigate this one). See http://jenkins.tribler.org/job/GH_Tribler_unittests_win32/ for the build status.

**Comment by whirm** [comment]
If I where you, I would start by skipping the tunnel tests and maybe the download tests too until all the others pass as those don't pass 100% of the time. Once you have it working, you can enable and debug them.

**Comment by devos50** [comment]
Unit tests on the Windows VM are working pretty well out of the box, except for the tunnel/hidden community tests. They still have the timeout problem which should be solved.

**Comment by whirm** [comment]
@devos50 well, those happen on Linux too, so it may not be a Windows-only bug.

**Comment by devos50** [comment]
@whirm almost done with this one! Should be finished in a few days when the Windows tests are also working.

**Comment by whirm** [comment]
@devos50 feel free to add the test runner to the pull request tester, also don't forget to configure the subjob so it doesn't abort all other jobs when failing and add the coverage report to the coverage check job (I did that already for the OSX job you connected)
