### ISSUE TITLE
Tribler always shows the upgrade splash for a fraction of a second

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1733]
Even if no upgrade is needed.

**Comment by lfdversluis** [comment]
Probably fixed in #1756 but tests have to be fixed yet. (Just referencing for now).

**Comment by lfdversluis** [comment]
Should be fixed by #1800

**Comment by devos50** [comment]
@lfdversluis this issue is not fixed by #1800 since the `show_upgrade_dialog` is still always shown on startup. Reason for this is that the observer is listening for the `NTFY_FINISHED` changetype which is always triggered. Instead, this changetype should be `NTFY_STARTED`.
