### ISSUE TITLE
Error opening file for writing

### ISSUE THREAD

**Issue by mackhina** [Tribler/tribler#1736]
Receive this error when attempting to install 6.5.0-r-c6. 

![triblr](https://cloud.githubusercontent.com/assets/15932899/11285328/aa24b24e-8f5a-11e5-9d82-b09e9c238691.PNG)

**Comment by whirm** [comment]
Do you have enough free space? 
Maybe your download got corrupted? Check it's MD5 or SHA256 against the provided ones.
Is your filesystem/hard disk healthy?

**Comment by mackhina** [comment]
70+GB of free space on the drive. Disk appears to be working fine in all other aspects. Everything is updated as well. I've just downloaded the file a second time and I still get the same error? 

Windows 10
Tribler_6.5.0-rc6.exe

**Comment by whirm** [comment]
It's working just fine here on my win 10 testing machine.

Is Tribler running while you run the installer?

Could you do this to see if for some reason that file is being held open by some other process?

https://superuser.com/questions/117902/find-out-which-process-is-locking-a-file-or-folder-in-windows/643312#643312

If that doesn't shed any light, maybe you could try tracing the installation process with
https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx
and see if we get some clue on why this is happening.

**Comment by whirm** [comment]
Closing due to lack of feedback, please feel free to reopen the issue if you are still interested.
