### ISSUE TITLE
Right click stop fails to do anything

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#1742]
OS X
rc6-8
stop button on the bar is also ineffective.

**Comment by whirm** [comment]
Please, read the `CONTRIBUTING.md` file and provide the required info.

**Comment by Dmole** [comment]
Tribler 6.5.0-rc6-8-g785f442
OS X 10.11.5
To reproduce, click stop, and note the option won't grey out after any time or number of stop attempts.
nothing in the log.
Deleting select torrents (or likely moving .Tribler) is a workaround.
No other software installed would interfere Tribler.

**Comment by whirm** [comment]
@devos50 are you able to reproduce this on your mac?

**Comment by whirm** [comment]
@devos50 ping!

**Comment by devos50** [comment]
@whirm pong

Will test it out in a moment!

**Comment by devos50** [comment]
Unable to reproduce it, tested it both on my laptop and the Mac Mini. @Dmole does it happen for every torrent that you add?

**Comment by Dmole** [comment]
No, but also I'm now using rc5 because of https://github.com/Tribler/tribler/issues/1706#issuecomment-168088779

**Comment by devos50** [comment]
@Dmole could you try out https://jenkins.tribler.org/job/Build-Tribler_OSX_devel/488/artifact/tribler/dist/Tribler-6.5.0-rc5-228-gd6e0ea8.dmg (fresh builded `.dmg`) to see whether it boots and the stop button is working?

**Comment by devos50** [comment]
The linked `.dmg` file linked above is incorrect. I've linked another one in #1706.

I've tested this new build both on my 10.10 and 10.11 machine and I'm unable to reproduce the issue.

**Comment by devos50** [comment]
@whirm I'm not able to reproduce this one. @Dmole do you still experience this problem?

**Comment by Dmole** [comment]
This was torrent specific so it's hard to reproduce. Likely it will crop up again unless some safety/threading/timeout/etc was added.

**Comment by whirm** [comment]
I'll close this then, @Dmole please reopen it if you manage to reproduce it again :)
