### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#1743]
Download stopped on error: u'Too many open files: /Users/user/Downloads/TriblerDownloads/folder/file.jpg'

**Comment by whirm** [comment]
Please, read the `CONTRIBUTING.md` file and provide the required info.

**Comment by Dmole** [comment]
Tribler 6.5.0-rc6-8-g785f442
OS X 10.11.5
To reproduce, click stop, and note the option won't grey out after any time or number of stop attempts.
Relevant log entry:
 3248 Nov 22 03:01:03 comp.local Tribler[77773]: ERROR   1448179263.89    tribler_main:578   main: Error: u'Too many open files: /Users/user/Downloads/TriblerDownloads/folder/file.jpg'
Deleting select torrents (or likely moving .Tribler) is a workaround (obviously as it's an issue with a specific torrent).
No other software installed would interfere Tribler.

**Comment by whirm** [comment]
@Dmole could you please trigger this bug and then provide a list of (censored) files that the Tribler process has opened?

https://stackoverflow.com/questions/20974438/get-list-of-open-files-descriptors-in-os-x

Thanks!

**Comment by whirm** [comment]
Closing due to lack of feedback.

Please feel free to reopen the issue if you are still interested.

**Comment by Dmole** [comment]
I will try to reprodice as soon as the exit node shortage is fixed.

**Comment by whirm** [comment]
@Dmole it is, we've got 3 1Gb/s servers up and running :)

**Comment by Dmole** [comment]
I can't find the use case that caused this... I'll comment again if I see it again. Though I'm stuck using rc5 due to other rc6 bugs so the issue may have been new to rc6.

**Comment by whirm** [comment]
@Dmole Ok, let's see if it comes back when you can use a more recent version.
Thanks!
