### ISSUE TITLE
CONTRIBUTING.md OS X log file 

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#1745]
CONTRIBUTING.md:
"Attach Tribler's log file found in %APPDATA% on Windows or on ~/.Tribler/ on Linux/OSX..."

> ls -1 ~/.Tribler/ | grep log
pymdht.log
> file ~/.Tribler/pymdht.log 
~/.Tribler/pymdht.log: empty
> grep -i tribler /private/var/log/system.log | wc -l
 26

Please update CONTRIBUTING.md to point tot the correct log file.

**Comment by whirm** [comment]
@devos50 could you take care of this? You are more familiar with OSX than I am.

**Comment by devos50** [comment]
I will take a look!

**Comment by devos50** [comment]
@whirm do we write to a log file? Since I can't find anything in the code that hints towards a `tribler.log` file or something alike in the `.Tribler` directory.

**Comment by whirm** [comment]
@devos50 nope, it goes to `/private/var/log/system.log` as @Dmole says.
