### ISSUE TITLE
Master branch has not been updated in two years

### ISSUE THREAD

**Issue by Pathemeous** [Tribler/tribler#1752]
The last commit on master is from 2 Aug 2013.
There is a rough 4,000 commits difference between `next` and `master`.
The [latest release](https://github.com/Tribler/tribler/commit/07fd5e083894c4442f0d1e162a96dbd565c7ed58) was tagged on `devel`, contrary to the convention of putting all releases on `master`.

Keeping an up-to-date `master` helps attracting potential open source developers. Out of sync branches can repulse them.

**Comment by whirm** [comment]
@Pathemeous the default branch is set to devel, so whenever you clone the repo, devel will be checked out.

But yes, we should either update the master branch with each release, that's what was supposed to be done, but as you can see, it did't really happen.

**Comment by Pathemeous** [comment]
I tried creating a pr to see if fast-forwarding was possible, but it was not.

Maybe we should start updating the master branch again with the next release?

**Comment by whirm** [comment]
Yes, or maybe even just drop it. All releases are tagged anyway.

**Comment by Pathemeous** [comment]
Unless `master` has extra protection, which it doesn't (`devel` is the only protected branch), having that extra layer does not add anything, so then I'd favour dropping it.

**Comment by vandenheuvel** [comment]
@devos50 Could `master` be used for `x.y.z` milestones in between `x.y` releases, while `next` contains only minor fixes upon the current `x.y` release? If you think this doesn't add value, the branch can probably be deleted.

**Comment by devos50** [comment]
Managing two branches is already complicated due to the cherry-picking process that has to be done. I would argue that we drop it. @qstokkink what do you think?

**Comment by qstokkink** [comment]
@devos50 I very much approve of dropping it.

**Comment by devos50** [comment]
Great, I removed the master branch.
