### ISSUE TITLE
multi-lingual interface

### ISSUE THREAD

**Issue by Venca24** [Tribler/tribler#1753]
I miss the ability to translate the interface of Tribler into different languages.

**Comment by whirm** [comment]
Yeah, I guess this would help a lot with user adoption.

**Comment by Pathemeous** [comment]
The benefit will only really be significant for countries with low level of English bilingualism.
Also, since the Tribler user base (I suspect) is generally more technical and active on the internet, the chance that additional languages attract more users seems relatively low.

That said, it is a nice quality of life improvement.

I would not mind working on a (Brazilian) Portuguese version.
Do we already have a Dutch client? If not, I could obviously do that too.

**Comment by whirm** [comment]
There's many countries that match the description :)

I can do Spanish and Catalan and could get somebody to do Romanian, French and Italian.

**Comment by devos50** [comment]
Good idea! We can make a separate file with all strings in the GUI or something like that.

Using https://docs.python.org/2/library/gettext.html might be a good starting point?

**Comment by whirm** [comment]
Yes, we should use something like that, but we should check if WX provides some built-in gettext functionality already.

Don't start working on this though, we have many other things that are more important than that.

Everything [here](https://github.com/Tribler/tribler/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+milestone%3AV6.5+-label%3A%22needs+feedback%22+-assignee%3Asynctext+sort%3Acreated-asc+) has priority over anything else.

Any issue on the `Backlog` milestone should be discussed with @synctext or me before being worked on. 
Before starting the next release cycle, we will review them and decide what gets done for the next milestone.

**Comment by Anth0rx** [comment]
I am not that much into Python programming. I would volunteer to translate Tribler into German. By the way: Do you have tips on how a newbie could possibly contribute to Tribler and learn more about Python?

**Comment by whirm** [comment]
@Anth0rx For Tribler to be translatable, we would need to extract all strings into a `.pot` (see [this](https://en.wikipedia.org/wiki/Gettext))  file, then we can translate that file into all the languages we want. It's not technically difficult to do, but you need to know a bit of python to not break the code when doing it.

There's lots of ways you can help, from the top of my head: promoting python, reporting bugs, checking if existing bugs are still valid/duplicated/fixed and can be closed, submitting patches...

re learning python, you can check the beginners guide on the [https://wiki.python.org/moin/BeginnersGuide](on the official python wiki), lots of info there.

Thanks for the interest!

**Comment by mrcruz** [comment]
I want to get into the development of Tribler and localization looks like a reasonable task to start with. I'm a experienced developer and I localized some apps before. The thing is: Python is not my forte. Are there any further discussions on this or should I start with @whirm last comment? I have never localized a Python project before but I'm willing to put the time.

**Comment by qstokkink** [comment]
Hey, thanks for your interest in Tribler. If you want pointers on internationalization (i18n), you can check out this link:

https://lokalise.com/blog/beginners-guide-to-python-i18n/

That said, there are a lot of strings in our interface and they are not separated cleanly from the code. If that does not scare you off, you can find the GUI code here:

https://github.com/Tribler/tribler/tree/devel/src/tribler-gui/tribler_gui

**Comment by mrcruz** [comment]
I did some work on #5479
