### ISSUE TITLE
[Win] Unable to find vcvarsall.bat

### ISSUE THREAD

**Issue by intel478** [Tribler/tribler#1758]
Following https://github.com/Tribler/tribler/blob/devel/doc/Tribler%20development%20on%20Windows.md#running-tribler

During LevelDB bin\buildout.exe command:
```
error: Setup script exited with error: Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat). Get it from http://aka.ms/vcpython27
An error occurred when trying to install Cython 0.23.4. Look above this message for any errors that were output by easy_install.
```

*Solution*: install https://www.microsoft.com/en-us/download/details.aspx?id=44266

**Comment by devos50** [comment]
@intel478 this one is fixed right?

**Comment by intel478** [comment]
Yes, but I've added the VC subdirectory to my PATH as well to find vcvarsall.bat from the dev-cmd: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC

**Comment by whirm** [comment]
is that on the windows README?

**Comment by intel478** [comment]
Yes, https://github.com/Tribler/tribler/blob/devel/doc/Tribler%20development%20on%20Windows.md#running-tribler

**Comment by whirm** [comment]
Good!
