### ISSUE TITLE
build scripts

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#1768]
Tribler needs some. It's no longer 1998, we should not have to hunt for dependencies.
yum, apt, port, brew, even Microsoft is catching up; 
http://blogs.technet.com/b/packagemanagement/archive/2015/04/29/introducing-packagemanagement-in-windows-10.aspx

**Comment by Dmole** [comment]
This works on OS X:
```bash
sudo port install git ffmpeg py27-pip py27-wxpython-3.0 swig swig-python py27-m2crypto py27-macholib py27-twisted libsodium
git clone --recursive  https://github.com/Tribler/tribler.git
cd tribler
mkdir vlc
find / -mount -iname ffmpeg | head -n 1 | xargs -I {} cp "{}" vlc/
Tribler/Main/Build/update_version_from_git.py
```
Temp patch: https://trac.macports.org/attachment/ticket/49910/Portfile.diff

Then you need 2 patches on tribler:
```bash
mac/makedistmac.sh
@@ -18 +18 @@ PYTHON_VERSION=2.7
-PYTHON="arch -i386 /Library/Frameworks/Python.framework/Versions/$PYTHON_VERSION/bin/python$PYTHON_VERSION"
+PYTHON="/opt/local/Library/Frameworks/Python.framework/Versions/$PYTHON_VERSION/bin/python$PYTHON_VERSION"
```
```bash
Tribler/Main/Build/Mac/setuptriblermac.py
@@ -260 +260 @@ setup(
-            + ["/Users/tribler/Workspace_new/install/lib/libsodium.dylib"]
+            + ["/opt/local/lib/libsodium.dylib"]
```
then you can build
```bash
./mac/makedistmac.sh
```

**Comment by devos50** [comment]
You are using wx3 to run Tribler which is currently not fully supported (I will try to solve this as soon as possible). You should try to install wx2.8 for OS X. Note that wx2.8 makes use of `carbon` which is only supported on 32-bit systems. This means that your other dependencies (such as M2Crypto, libtorrent) should be 32-bit as well.

**Comment by whirm** [comment]
Could we get the useful parts of this as a PR?
Thanks!

**Comment by Dmole** [comment]
yes 2.8 worked.

**Comment by Dmole** [comment]
While those dependencies get Tribler Running there is a (dependency unrelated I think) bug
```python
  File "./tribler/Tribler/community/tunnel/crypto/tunnelcrypto.py", line 41, in verify_and_generate_shared_secret
    crypto_auth_verify(auth, dh_received, shared_secret)
TypeError: crypto_auth_verify() takes exactly 2 arguments (3 given)
```

**Comment by devos50** [comment]
@Dmole I spent some time working on a new builder for OS X with updated dependencies, see #1858

**Comment by Dmole** [comment]
Thanks.
I guess the next step would be to reduce the 156 lines in
https://github.com/Tribler/tribler/blob/devel/doc/development/development_on_osx.rst
to `brew install tribler` or `port install tribler` .

**Comment by Dmole** [comment]
PR: https://github.com/Tribler/tribler/pull/2819
