### ISSUE TITLE
improve "Duplicate download" warning

### ISSUE THREAD

**Issue by Cathryne** [Tribler/tribler#1770]
Currently (v6.4.3) that warning just has an OK option that closes the whole `Add external .torrent` dialogue. I think it could be improved by:

a) automatically switching the main window to the Downloads section and selecting the torrent in question, or
b) adding a `select different .torrent` button, so one can start another torrent faster.

Thanks for your work on Tribler :-)

**Comment by whirm** [comment]
Thanks for your suggestion!
