### ISSUE TITLE
PYMDHT logging should be fixed

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1772]
It contains lots of debug stuff with CRITICAL level misleading people into thinking there's something wrong like in #1769.

**Comment by Pathemeous** [comment]
Should the logs be entirely removed, or should they be moved to a lower priority level (like `DEBUG`)?

**Comment by whirm** [comment]
AFAIR there where both unreasonably high level logger calls and prints. I think @LipuFei already sent a PR with fixes for the print part, but I would check just in case.

I wouldn't remove log entries as I don't think @rauljim would be happy with that :)

Sould I assign this one to you then?

**Comment by Pathemeous** [comment]
Yes please!

**Comment by rauljim** [comment]
@whirm @LipuFei @ gaohuazuo
This thread reminds me that I have a couple of open PRs in Pymdht.
Unfortunately, my family and work keep me busy and I have no time to maintain Pymdht. :-(

I'll mark my Pymdht repo as stale/dead/unmaintained.
If it makes sense for you guys, I can put a link in my README pointing to a Pymdht repository that is alive.

You can always reach me for a quick question via email but keeping my repo semi-alive is just frustrating for these good people who send me issues and PRs and wait forever for me to act on them.

**Comment by whirm** [comment]
@rauljim I will fork it to the Tribler organization then.

Thanks for your work!

**Comment by whirm** [comment]
Done, @Pathemeous, you can branch off the current HEAD and do whatever it makes sense to you for each log entry (delete it if it's obvious stale debugging stuff, lower otherwise, etc.).

**Comment by Pathemeous** [comment]
Will do, could you assign me?

**Comment by synctext** [comment]
We now have EgbertDHT !
