### ISSUE TITLE
Bizzare issue, extremely slow downloads.

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#1777]
Ok, first of all, i'm not sure if this is even a Tribler issue or my internet provider did something or a system update messed something up. (Though there seems that none have been installed when it started happening.) I'm merely posting to see possible reasons as to why this could happen. 

On Win10, internet speed around 20/20 on a good day, as low as 5/5 other days. Now at 17/17. All units in Mbps. 

It all started out as another problem, Tribler didn't want to build circuits at all, eternally stuck on that part. I tried everything, including trying other builds that worked before. Wiped Tribler, and the folder appdata/roaming folder. Also no error logs for this at any point. Got everything removed, fresh install, and the same thing happened. Left for a few hours and finally it breaks the curse, it goes to downloading! But any anonymous torrents are not starting to download, or going at the speed of o-2 KB/s... Most of the time completely stopped. Using only 1 hop, and added one with 2 to see if that was actually different. Also have some completed torrents that i added and are seeding, though none of them are uploading anything at all. The one at two hops are actually faster at 30 KB/s and up to 95 according to the speed graph. 

Summary, multiple computer restarts, two clean installs, tried running as administrator, multiple builds tested, some that i knew worked before, and the one it broke on first also just stopped working for no reason. Also tried another wireless network that reaches the computer with not being able to build circuits after 10 minutes, about 20 after that it's working as the main network does, no speed at all, nothing is downloading and the 2 hops one is still building. 

No hops working fine - 1.2-1.4 MB/s average speed

1 Hops, the regularly used one 0.8 MB/s average speed, After that moment at, 0 to 10 KB/s.

2 Hops, not used much before so i don't remember any expected speed, 0-100 KB/s, 30-50 on average.

Seeding - No uploading working. (The ones that actually download something have some up speed, sometimes...)

Now using the latest build, "Tribler_6.5.0-rc6-45-g95b9186"

Running on W10, Tribler installed on hard drive D.

**Comment by whirm** [comment]
Yeah, I posted a reply on the forums about this, It's not a bug, it's simply that there's not enough helpers on the network. The big ones that the university provided to help while the network is still small, where hosted on rented servers and its contract expired the 1st of December. They are working on a new contract but it'll take some days more.

**Comment by Thomasedv** [comment]
Ok, all i needed to know. I was just worried it was something wrong. Thanks.
