### ISSUE TITLE
Discussion: Rename .Tribler folder (in appdata/Roaming)

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#1778]
Folders that start with a dot are not allowed on Windows (go to your desktop, right click, new -> new folder and name it .test -> error). While it *does* work with a hack [like this](http://stackoverflow.com/questions/10744305/how-to-create-gitignore-file), I think removing the dot is a better approach overall. I noticed that (at least on windows) no other folder in Roaming starts with a dot.

**Comment by whirm** [comment]
They are allowed, it's just the file manager being silly. If you create it with a different name and then rename it, it works fine. I wouldn't touch this.

**Comment by lfdversluis** [comment]
Ok, closing in that case.
