### ISSUE TITLE
MultiChain part of standard Tribler unit test

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1781]
complete scenario file for unit test

add existing scenario files to standard PR tester: https://jenkins.tribler.org/job/GH_Tribler_pull-request-tester_devel/
Existing written scenario, like: https://github.com/snorberhuis/gumby/blob/devel/experiments/multichain/multichain_integrated_single.scenario
Ensure that the scenario files do not overload the test machine.
Create a screenshot of the results: ![image](https://cloud.githubusercontent.com/assets/325224/11717606/e26d4812-9f51-11e5-98ca-95ca6f2f5d17.png)

After integration: check counters and fix

**Comment by whirm** [comment]
@synctext Just to clarify, you are talking about running the experiment in parallel with the tests, right?

**Comment by synctext** [comment]
yes.
Could be nice part of the standard test suite, if rock solid stable.

**Comment by whirm** [comment]
If it's using scenario files it's using gumby, it would be neither trivial or a good idea to have tests depending on that. What I think we should have is a comparative experiment execution system added to gumby. 

Similar to the performance regression analysis paper but way simpler (no systemtap involved, just some basic metrics comparison against the results from the target branch).

All this experiments could be run in parallel with the unit tests and the results reported on each PR. If the changes make any of them worse than the current code, it fails the build.

This should be pretty easy to implement and we could even use @corpaul's already existing code.

But for starters, I would just create a new job that gets triggered with each PR, this way we get a link to the resulting report just like with the tests and then we can keep improving it.

**Comment by synctext** [comment]
Good point. Lets keep it as simple as possible for now. A new job with this picture as output. 
No performance regression yet. That is where we want to end up later. Just a picture using .gv format generated using cmdline tools, like we did 7 years ago.
http://kayapo.tribler.org/trac/raw-attachment/wiki/SwarmBasedReputationConsensus/bartercast_graph_all_records_till_0806.gv

**Comment by pimveldhuisen** [comment]
First image:
https://jenkins.tribler.org/job/MultiChain_integrated_experiment_pim/43/
This could be refined some more of course.

**Comment by pimveldhuisen** [comment]
The experiment now renders svg images with colored nodes:
https://jenkins.tribler.org/job/MultiChain_integrated_experiment_pim/61/
Green nodes are origin nodes (light green: origin for both peers, dark green: origin for one of the peers).
Red nodes are half signed nodes.
Is this sufficient to close this issue?

**Comment by synctext** [comment]
![image](https://cloud.githubusercontent.com/assets/325224/12618675/3126cab2-c515-11e5-890b-09034294546f.png)
Yes, Looks good; feel free to close it.
