### ISSUE TITLE
Android Devel on Jenkins

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1782]
adb connection
One Android phone
Buildozzer
Compile: wip_shadow_internet_android, https://github.com/Tribler/tribler/tree/wip_shadow_internet_android
running Kivy code
takes screenshot

**Comment by brussee** [comment]
Template: https://jenkins.tribler.org/job/Build-AT3-ARM-32/

**Comment by brussee** [comment]
Stuck on probable external issue #1791

**Comment by brussee** [comment]
>  Currently rewriting recipes.

All necessary recipes are done! https://github.com/kivy/python-for-android/pull/405#issuecomment-168715685 (2 waiting for approval)

**Comment by devos50** [comment]
@brussee good work :+1:

**Comment by brussee** [comment]
- [x] adb connection
- [x] One Android phone
- [x] Buildozzer -> new P4A toolchain
- [x] Compile: wip_shadow_internet_android, https://github.com/Tribler/tribler/tree/wip_shadow_internet_android
- [x] running Kivy code
- [x] takes screenshot

**Comment by synctext** [comment]
+1  good progress

**Comment by brussee** [comment]
# Run on Jenkins & make nice graphs: #2231

**Comment by brussee** [comment]
The new P4A toolchain is up and running on Jenkins now! https://github.com/Tribler/tribler/pull/2476#issuecomment-258394077

@synctext This can be closed.
