### ISSUE TITLE
ccache: invalid option -- 'L' 

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#1791]
The Buildozer script in the android branch unexpectedly spits out this error during compilation:

https://gist.github.com/brussee/f6f15eb566aaf9f47db7

expecting an external issue...

**Comment by whirm** [comment]
Is Buildozer using ccache on purpose? (I haven't used ccache in like 10 years) If it's not required by Buildozer, maybe you could uninstall it and see.

**Comment by brussee** [comment]
Yes, it appears so: ''' sudo apt-get install build-essential ccache '''
https://buildozer.readthedocs.org/en/latest/installation.html?highlight=ccache

**Comment by whirm** [comment]
try to uninstall ccache anyway

**Comment by brussee** [comment]
Check build dependencies for Ubuntu
Packages missing: cython 
It might break the compilation, except if you installed thoses packages manually.
Check environment
*snip*
kivy/graphics/vbo.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
 error: command 'arm-linux-androideabi-gcc' failed with exit status 1

**Comment by brussee** [comment]
Resolved, onto the next issue:
```
Check build dependencies for Ubuntu
Packages missing: cython 
It might break the compilation, except if you installed thoses packages manually.
Check environment
```
https://gist.github.com/brussee/bc376f8491a9e2ac42a4

**Comment by whirm** [comment]
@brussee maybe you could open a ticket on the buildozer issue tracker, specifying ccache version, Linux distro and version, etc...
