### ISSUE TITLE
Clean cython build error

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#1792]
From: https://gist.github.com/brussee/bc376f8491a9e2ac42a4
```
Check build dependencies for Ubuntu
Packages missing: cython 
It might break the compilation, except if you installed thoses packages manually.
Check environment
**snip**
kivy/graphics/vbo.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
 error: command 'arm-linux-androideabi-gcc' failed with exit status 1
```

As per instructions I did install manually: https://buildozer.readthedocs.org/en/latest/installation.html?highlight=cython

```
$ sudo pip install --upgrade cython

The directory '/home/paul/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/paul/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: cython in /usr/local/lib/python2.7/dist-packages
```

**Comment by brussee** [comment]
Likely solution: https://github.com/kivy/buildozer/issues/251#issuecomment-162437006

**Comment by whirm** [comment]
For higienic reasons, don't install pip stuff as root. Use `--user` instead so it gets installed into your `$HOME`.

**Comment by brussee** [comment]
I cleaned up as much of the pip packages I could and reinstalled them as --user.
Reinstalled fresh version of cython, both OS and python. Did not see any errors there.

**Comment by brussee** [comment]
Now I get this: https://gist.github.com/brussee/f90753397393bd61310d
```
running build_ext
failed to import Cython: /home/paul/.local/lib/python2.7/site-packages/Cython/Compiler/Scanning.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8
error: Cython does not appear to be installed
```

**Comment by whirm** [comment]
I may be finding the wrong libraries (maybe some of the manually instaled stuff?).
Do an `ldd /home/paul/.local/lib/python2.7/site-packages/Cython/Compiler/Scanning.so` to see if it's finding the wrong stuff.

**Comment by brussee** [comment]
$ ldd /home/paul/.local/lib/python2.7/site-packages/Cython/Compiler/Scanning.so
	linux-vdso.so.1 =>  (0x00007ffc86fb0000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbd309a6000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbd305dc000)
	/lib64/ld-linux-x86-64.so.2 (0x00005595e2cde000)

According to the code from: https://docs.python.org/2.7/faq/extending.html#when-importing-module-x-why-do-i-get-undefined-symbol-pyunicodeucs2
I do have the appropriate python build....

**Comment by brussee** [comment]
Maybe the interpreter for cross-compiling is 32bit? My system is 64 bit. Old issue where I got this idea from: https://github.com/zeromq/pyzmq/issues/165#issuecomment-3464487

**Comment by whirm** [comment]
I'll come by in a bit and we can have a look at it.

**Comment by brussee** [comment]
Aborted this approach last year. Switched to the new p4a toolchain.
