### ISSUE TITLE
Jenkins buildozer not found

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#1795]
What's up with the installation of buildozer being succesful and not found at the same time?

+ pip install --upgrade --user buildozer
Requirement already up-to-date: buildozer in /home/jenkins/.local/lib/python2.7/site-packages
Requirement already up-to-date: pexpect in /home/jenkins/.local/lib/python2.7/site-packages (from buildozer)
Requirement already up-to-date: ptyprocess>=0.5 in /home/jenkins/.local/lib/python2.7/site-packages (from pexpect->buildozer)
Cleaning up...
+ buildozer -v android debug deploy run logcat
/tmp/hudson6140516840180351460.sh: 4: /tmp/hudson6140516840180351460.sh: buildozer: not found
Build step 'Execute shell' marked build as failure

**Comment by brussee** [comment]
Had to provide the full path:  /home/jenkins/.local/bin/buildozer

**Comment by whirm** [comment]
I would rather add `~/.local/bin` to the `PATH`, there's probably more stuff that got installed there.
