### ISSUE TITLE
Not strictly necessary to startup the GUI when testing the tunnels

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#1799]
When testing the tunnels, we noticed that a GUI is started. We believe this is not necessary and Tribler can test the tunnels without a GUI. Downloads can be started by invoking the `start_download` method in `Session` instead of starting a download through the `StartDownload` method in `MainFrame`.

**Comment by whirm** [comment]
We would also need the gui side of the tunnel stuff to be tested independently of the session.

**Comment by devos50** [comment]
@whirm indeed, I will create a seperate issue for that.

**Comment by qstokkink** [comment]
@devos50 this has been fixed for a long time, right?

**Comment by devos50** [comment]
@qstokkink absolutely!
