### ISSUE TITLE
Create tests that checks whether upgrading of older Tribler versions is working

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#1801]
We should have tests that test whether upgrading the database to a newer version is working. This can be done by placing old and/or corrupt .Tribler directory in the tests and invoke the upgrader.

**Comment by whirm** [comment]
6.5 has been delayed due to a bug introduced in the upgrader that went undetected due to the lack of tests.

**Comment by devos50** [comment]
@whirm I can add a test with a 'real' older database (like we discussed before). There already is a test available that is using a clean database.

**Comment by whirm** [comment]
Isn't the 10MB DB used on the tests a real DB?

**Comment by devos50** [comment]
@whirm the 10MB database is too old to be upgraded so it only checks whether an exception is thrown. No actual upgrade of that database is done.

**Comment by whirm** [comment]
I see, then yeah, let's run a copy of the oldest version of Tribler that is still able to talk to recent versions and let it generate a more recent DB

**Comment by devos50** [comment]
I've written some tests to test the upgrade process in #2046.
