### ISSUE TITLE
Mark unit tests as failed if an exception occurred

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#1811]
Currently, when an exception is thrown, the test still continues to run. We should add a Twisted log observer to check whether there are errors and if so, mark the test as failed.

**Comment by whirm** [comment]
Another example of an uncaught exception: #1817

**Comment by devos50** [comment]
@whirm can you assign this one to the 6.6 milestone? I think it's important to have this one.

**Comment by whirm** [comment]
It slipped through the cracks
