### ISSUE TITLE
"Building circuits" loop

### ISSUE THREAD

**Issue by Anth0rx** [Tribler/tribler#1816]
At the moment I am experiencing a loop in the "Building circuits" stage of an anonymous download. Sometimes I get to the actual download stage with no traffic throughput at all.

Regards
Anth0rx

**Comment by whirm** [comment]
Are you are getting error messages on the logs?

If not, it probably just is that there's not enough peers proxying traffic. The university provided some new servers to help boost the network until critical mass is reached and I'm setting them up as I write. Should be better soon.
