### ISSUE TITLE
We should have a single config file/object

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1822]
That's why we have sections, it doesn't make sense to have 3 different ways to access/set config options with different features (one upgrades across config versions, the other doesn't even check for that, etc.) which leads to silly bugs and general confusion.

I would also discuss if it's worth switching to ConfigObj, it makes some things easier.

**Comment by whirm** [comment]
I really think we should have this done for the `new gui` milestone, otherwise the insanity will keep creeping on new code (for instance the configuration REST endpoint).

**Comment by devos50** [comment]
@whirm do you agree if I give priority on this one immediately after wx is removed?

**Comment by whirm** [comment]
@devos50 what else do you have on your plate other than the new gui and the REST iface?

**Comment by devos50** [comment]
@whirm except for writing the thesis and some outstanding issues for 6.6 release, nothing as far as I know.

**Comment by whirm** [comment]
If @synctext has nothing to say and we don't find anything more important/urgent until then it's fine by me.

**Comment by devos50** [comment]
@whirm I can also focus on it now if you want since it would benefit Tribler overall. I think it will take a few days however to implement.

**Comment by whirm** [comment]
@devos50 let's wait for @synctext feedback on this. Also, the new GUI is more important and I would like to have an initial version merged ASAP.
