### ISSUE TITLE
Catchall excepts must die

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1823]
Tribler is plagued with catchall excepts that hide bugs under the rug and make debugging unnecessarily difficult.

For instance `tribler_main.py` has several of them in a row.

We need to check which exceptions make sense to catch and crash/log properly the rest.

**Comment by themusicgod1** [comment]
This could be a student task couldn't it?

**Comment by whirm** [comment]
sure

**Comment by devos50** [comment]
@whirm during the next weeks we can take a quick look through the code to see where this happens. Don't think this is a task that can be assigned to one particular person.

Additional question: how can we make sure that we know which exception can and should be caught?

**Comment by whirm** [comment]
There's very few cases where you want to catch all exceptions, that usually happens when you want to clean up something before continuing and even then you will raise the exception again.

You can see the calls the function makes and figure out the exact exceptions it should be catching (if at all).

**Comment by lfdversluis** [comment]
An attempt to remove some is made in #2055

**Comment by xoriole** [comment]
We can close this since the code base has undergone several epic refactorings
