### ISSUE TITLE
Item list for content of Problem Description within thesis.tex

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1847]
test-driven development
quality assurance infrastructure
#1846 My Updates on frontpage

...

![20160104_162744](https://cloud.githubusercontent.com/assets/325224/12116503/893dfd9a-b3ba-11e5-9b33-98e6bd2a8549.jpg)

Outcome: add text simply as a comment below.

**Comment by devos50** [comment]
This one has been written a long time ago.
