### ISSUE TITLE
Shutdown procedure should be streamlined

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1848]
Right now there's sleeps in two places, which hog the main thread for a long time and even trip the watchdog when shutting down after running a test.

This will also make each individual test finish quicker and reduce the overall test execution time.

**Comment by qstokkink** [comment]
@devos50 was this part of the fixes currently merged in devel?

**Comment by devos50** [comment]
Ah yeah this issue is now completed I guess. It's twistified as much as possible :)
