### ISSUE TITLE
error encountered while installing tribler in Ubuntu 15.10

### ISSUE THREAD

**Issue by AbhimanyuAryan** [Tribler/tribler#1861]
sudo dpkg -i tribler_6.4.3_all.deb              
[sudo] password for cooldudeabhi: 
Selecting previously unselected package tribler.
(Reading database ... 380196 files and directories currently installed.)
Preparing to unpack tribler_6.4.3_all.deb ...
Unpacking tribler (6.4.3) ...
dpkg: dependency problems prevent configuration of tribler:
 tribler depends on libjs-excanvas; however:
  Package libjs-excanvas is not installed.
 tribler depends on libjs-mootools; however:
  Package libjs-mootools is not installed.
 tribler depends on python-apsw; however:
  Package python-apsw is not installed.
 tribler depends on python-cherrypy3; however:
  Package python-cherrypy3 is not installed.
 tribler depends on python-feedparser; however:
  Package python-feedparser is not installed.
 tribler depends on python-gmpy; however:
  Package python-gmpy is not installed.
 tribler depends on python-libtorrent (>= 0.16.4); however:
  Package python-libtorrent is not installed.
 tribler depends on python-m2crypto; however:
  Package python-m2crypto is not installed.
 tribler depends on python-netifaces; however:
  Package python-netifaces is not installed.
 tribler depends on python-twisted; however:
  Package python-twisted is not installed.
 tribler depends on python-wxgtk2.8; however:
  Package python-wxgt
dpkg: error processing package tribler (--install):
 dependency problems - leaving unconfigured
Processing triggers for gconf2 (3.2.6-3ubuntu5) ...
Processing triggers for man-db (2.7.4-1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu3) ...
Processing triggers for bamfdaemon (0.5.2~bzr0+15.10.20150627.1-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.58ubuntu1) ...
Errors were encountered while processing:
 tribler

**Comment by whirm** [comment]
Tribler depends on wx2.8 which is on the `universe` repositories, so you will need to enable that.

http://packages.ubuntu.com/wily/python-wxgtk2.8

Cheers!

**Comment by AbhimanyuAryan** [comment]
Thanks worked

**Comment by whirm** [comment]
Great, enjoy! :)
