### ISSUE TITLE
Clean up the mac license file so the OS X .dmg opens faster

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#1862]
The license file seems to be too long which causes the .dmg file to take longer to load (about 3 seconds). I've already reduced the amount of loading time by using an external script to inject the EULA in the .dmg file.

The file loads even faster if we make the license agreement shorter. @synctext can you take a look at this? The file I'm using right now is https://github.com/devos50/tribler/blob/builder_osx_64bit/Tribler/Main/Build/Mac/mac_license.txt.

**Comment by synctext** [comment]
if it improves speed use something like this 3-line version:

This software is released under the LGPL license by Delft University of Technology. Included third party libraries and software modules may have different licences. For details see the included file tribler/licence.txt or http://github.com/tribler/tribler.. etc.
