### ISSUE TITLE
Tribler installer size could be easily reduced by deleting unused vlc plugins and libraries

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1863]
Currently we are shipping everything, but we don't really need stuff like dvd support or cacalib output.

**Comment by svnpenn** [comment]
For goodness sake, what the hell is going on with the size?

Program     | Size
------------|------
Tribler     | 86 MB
qBittorrent | 16 MB
PicoTorrent | 3 MB

**Comment by synctext** [comment]
yeah, our installer includes a lot. On Windows a complete VLC installer, full Python interpreter, lots of libraries, and 3 versions of VB. Can be slimmed down.

**Comment by lfdversluis** [comment]
VLC takes a lot indeed (58%)
![vlc is big](https://gyazo.com/91a023896d17eea614371a1880539b6c.png)

**Comment by ichorid** [comment]
another reason to remove embedded VLC #5388

**Comment by devos50** [comment]
This issue is not addressed yet right? We still ship every plugin available on Windows and therefore this issue should still be open.

**Comment by eproxus** [comment]
The Windows 64-bit installer is currently 160 Mb (!). Seems the size has doubled since this issue was first raised.

**Comment by qstokkink** [comment]
Most of the installer size can be attributed to `PyQt5`. My `<Tribler install dir>/lib/PyQt5` directory clocks in at just **over 400 MB** (!). Almost everything else in Tribler is in the order of a few MB at most.

Removing non-essential Qt5 files (or [switching away from Qt5 altogether](https://github.com/Tribler/tribler/issues/7736)) seems like a good idea.
