### ISSUE TITLE
pop_alert in LibtorrentMgr.py is deprecated

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#1891]
The `pop_alert` method in `LibtorrentMgr.py` (https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Libtorrent/LibtorrentMgr.py#L444) is deprecated, see https://github.com/arvidn/libtorrent/blob/13c33694638a414ae6207d5fb3f5dc313d019c1d/bindings/python/src/session.cpp#L485. We should probably be using the newer `pop_alerts` method.

Maybe we can compile libtorrent with the `TORRENT_NO_DEPRECATE` flag, run Tribler with that compiled libtorrent and see what breaks?

**Comment by whirm** [comment]
Let's focus on getting the new testing/building infrastructure up and running and 6.6 with WX3 out of the door and we will take care of this later. Not a priority.

**Comment by devos50** [comment]
This one is fixed #1990.
