### ISSUE TITLE
Tribler is producing errors in the first seconds after startup

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#1893]
When starting up Tribler, searching for `Pioneer` and clicking the stream button, Tribler is showing an exception:

![5740f4098d7a8aa70f9e18521bea78f1](https://cloud.githubusercontent.com/assets/1707075/12513622/1bb81702-c11f-11e5-9797-93edf64747dd.png)

Exception:

```
Jan 22 15:48:05 MBP-van-Martijn Tribler[2089] <Notice>: Traceback (most recent call last):
Jan 22 15:48:05 MBP-van-Martijn Tribler[2089] <Notice>:   File "Tribler/Main/vwxGUI/MainFrame.pyo", line 581, in startDownload
Jan 22 15:48:05 MBP-van-Martijn Tribler[2089] <Notice>:   File "Tribler/Main/vwxGUI/__init__.pyo", line 128, in invoke_func
Jan 22 15:48:05 MBP-van-Martijn Tribler[2089] <Notice>:   File "Tribler/Main/vwxGUI/SearchGridManager.pyo", line 658, in playTorrent
Jan 22 15:48:05 MBP-van-Martijn Tribler[2089] <Notice>: AttributeError: 'NoneType' object has no attribute 'Reset'
```

**Comment by whirm** [comment]
Does it happen on a non-OSX system? (Can't reproduce it on Linux and Tribler doesn't support the embedded video player on OSX, so it's probably just trying to access an attribute that hasn't been initialized.

**Comment by devos50** [comment]
@synctext has encountered it too.

**Comment by synctext** [comment]
Somewhat similar behavior on Ubuntu 15.10.
Searching for ```Pioneer``` and then streaming an entry freezes Tribler.

![reproducable_freeze_after_startup](https://cloud.githubusercontent.com/assets/325224/12514005/38d590a6-c121-11e5-99ee-f0d3fb664c76.png)

**Comment by whirm** [comment]
@synctext that's not the same bug as @devos50's it's not freezing on his case.

As you can all see, the GUI code is a disaster. These bugs where probably there on 6.4 too, so I don't think it's a smart decision to delay 6.5 even more due to those.

Let's talk about it on Monday if you want, but I'd rather have 6.5 out and then see if these bugs are happening too on 6.6 with WX3.

We could make 6.6 a GUI bug fixing release, or just decide to code a new GUI from scratch :)

**Comment by devos50** [comment]
I agree with @whirm, we can focus on these issues when we overhaul parts of the GUI/are creating libtribler.

**Comment by synctext** [comment]
Agreed, better leave this for 6.5.1 or even later.
Feel free to release RC7 on forum.

**Comment by LipuFei** [comment]
@whirm Look at this: https://github.com/Tribler/tribler/blob/devel/Tribler/Main/vwxGUI/list.py#L2181
I guess it's meant to happen on Mac.

**Comment by devos50** [comment]
Well, I removed the stream button on OS X in #1978 so this error cannot occur anymore. Still, this is not the best fix since video playback should work on OS X. In the new GUI I'm working on, playback on Mac will probably be possible.
