### ISSUE TITLE
Disable dispersy et al. when running gui tests

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#1901]
test_gui_dialogs.py starts dispersy. Not needed if we only want to test the gui.

**Comment by whirm** [comment]
Some dialogs feed on data provided by the communities, so we have to have a closer look at it and see what can be done for each case.

**Comment by devos50** [comment]
I already disabled Dispersy in some of the tests in PR #2555, however, there might be some additional tests where Dispersy can be disabled.

**Comment by devos50** [comment]
We have separate GUI tests now so this issue is not relevant anymore.
