### ISSUE TITLE
The tunnel community sometimes leaves a dirty reactor when running the tests

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1905]
One instance of this happening (current `devel`):

https://jenkins.tribler.org/job/GH_Tribler_pull-request-tester/5573/testReport/junit/Tribler.Test.test_remote_search/TestMixedRemoteSearch/test_remotedownload/

**Comment by whirm** [comment]
The build was cleaned up, so I'm closing it as it has no available traceback anymore. :(

**Comment by devos50** [comment]
@whirm yeah we should copy the stack trace into the issue so we keep a reference to it.

**Comment by whirm** [comment]
Yeah, either this or marking the build as persistent on jenkins.
