### ISSUE TITLE
6.5.0 - RC7 - Extremely slow, unusable 

### ISSUE THREAD

**Issue by renang010** [Tribler/tribler#1910]
Upgraded to 6.5-RC7

Trying to download a file with 8000+ seeders, 3000+ leachers. Connections: sometimes is different than 0, Down speed: most of the time is 0, and sometimes < 0.5 KB/s.

I am on OS X 10.11.

RG

**Comment by renang010** [comment]
Update: It is working now.

**Comment by whirm** [comment]
Great, let us know if you find any other issues!

**Comment by twilsonco** [comment]
@renang010 Could you update the numbers? Before you were getting 0-0.5KB/s. What was it after it started working?
