### ISSUE TITLE
El Capitan version 10.11.4  build 15E33e

### ISSUE THREAD

**Issue by Whyisdaddy** [Tribler/tribler#1911]
Tribler never  gets past the first screen saying 

Starting session and upgrading database (it may take a while)  2 hours and 5 min. latter its still
sitting in the same place, it will work on my imac osx 10 X.

 but not El Capitan 10.11.4

any suggestions ?
Thank's
![screen shot 2016-01-30 at 2 00 29 pm](https://cloud.githubusercontent.com/assets/4367006/12697791/e77bb642-c759-11e5-840a-5455e54cf2fd.png)

**Comment by whirm** [comment]
Could you check the log console and paste Tribler's output?
Thanks!

**Comment by Whyisdaddy** [comment]
I would be glad to where is it Tribler never gets past the visible screen notice.

**Comment by whirm** [comment]
It's a bundled OSX utility (Console app in your Applications/Utilities folder)

**Comment by Whyisdaddy** [comment]
i hope this is what you needand thank you.

**Comment by whirm** [comment]
I'm not seeing anything, did you attach something to the github notification email?

**Comment by Whyisdaddy** [comment]
I tryer but is gave me an error, I sent an email with a attachment to it, I'll Try again

**Comment by Whyisdaddy** [comment]
[Archive.zip](https://github.com/Tribler/tribler/files/113160/Archive.zip)
hope this helps

**Comment by whirm** [comment]
I see it's getting stuck but not much more, could you upload Tribler's log file located in your `~/.Tribler/`?

Thanks!

**Comment by Whyisdaddy** [comment]
ok I think this is what you are looking for
[logger.conf.zip](https://github.com/Tribler/tribler/files/113992/logger.conf.zip)

**Comment by whirm** [comment]
Oh, sorry, turns out there's a mistake on our documentation and Tribler doesn't write to this log file on OSX.

Could you please execute this on a terminal: `syslog -C | grep Tribler > /tmp/tribler.log` and upload it?

**Comment by Whyisdaddy** [comment]
ok i did it but I'm not sure what I'm looking for and were it is

**Comment by whirm** [comment]
go to `/tmp` with the file browser and you will see a `tribler.log` file there. If you don't know how to get there, just run this on the terminal and it will be created on your home directory instead:

`syslog -C | grep Tribler > ~/tribler.log`

**Comment by Whyisdaddy** [comment]
[tribler.log.zip](https://github.com/Tribler/tribler/files/114136/tribler.log.zip)
ok here you go.

**Comment by whirm** [comment]
@Whyisdaddy thanks!

That's the relevant part of the log for reference:
```
Jan 28 20:39:17 Daddys-MacBook Tribler[11149] <Notice>: Traceback (most recent call last):
Jan 28 20:39:17 Daddys-MacBook Tribler[11149] <Notice>:   File "<string>", line 5, in <module>
Jan 28 20:39:17 Daddys-MacBook Tribler[11149] <Notice>: ImportError: No module named csv
Jan 28 20:39:40 Daddys-MacBook spindump[502] <Notice>: Saved spin report for Tribler version 0.0.0 (0.0.0) to /Library/Logs/DiagnosticReports/Tribler_2016-01-28-203940_Daddys-MacBook.spin
Jan 28 20:41:00 Daddys-MacBook spindump[502] <Notice>: Saved cpu_resource.diag report for Tribler version 0.0.0 (0.0.0) to /Library/Logs/DiagnosticReports/Tribler_2016-01-28-204100_Daddys-MacBook.cpu_resource.diag
Jan 28 20:48:44 Daddys-MacBook spindump[502] <Notice>: Saved hang report for Tribler version 0.0.0 (0.0.0) to /Library/Logs/DiagnosticReports/Tribler_2016-01-28-204844_Daddys-MacBook.hang
Jan 28 20:48:54 Daddys-MacBook Tribler[11378] <Notice>: Traceback (most recent call last):
Jan 28 20:48:54 Daddys-MacBook Tribler[11378] <Notice>:   File "<string>", line 5, in <module>
Jan 28 20:48:54 Daddys-MacBook Tribler[11378] <Notice>: ImportError: No module named csv
Jan 28 20:48:54 Daddys-MacBook Tribler[11378] <Notice>: 20:48:54: Deleted stale lock file '/Users/russelrhoades/tribler-russelrhoades'.
Jan 28 20:49:12 Daddys-MacBook spindump[502] <Notice>: Saved spin report for Tribler version 0.0.0 (0.0.0) to /Library/Logs/DiagnosticReports/Tribler_2016-01-28-204912_Daddys-MacBook.spin
Jan 28 20:49:23 Daddys-MacBook spindump[502] <Notice>: Saved spin report for Tribler version 0.0.0 (0.0.0) to /Library/Logs/DiagnosticReports/Tribler_2016-01-28-204923_Daddys-MacBook.spin
Jan 28 20:50:32 Daddys-MacBook spindump[502] <Notice>: Saved cpu_resource.diag report for Tribler version 0.0.0 (0.0.0) to /Library/Logs/DiagnosticReports/Tribler_2016-01-28-205032_Daddys-MacBook.cpu_resource.diag
Jan 28 21:56:18 Daddys-MacBook spindump[502] <Notice>: Saved hang report for Tribler version 0.0.0 (0.0.0) to /Library/Logs/DiagnosticReports/Tribler_2016-01-28-215618_Daddys-MacBook.hang
Jan 29 09:21:47 Daddys-MacBook Tribler[852] <Notice>: Traceback (most recent call last):
Jan 29 09:21:47 Daddys-MacBook Tribler[852] <Notice>:   File "<string>", line 5, in <module>
Jan 29 09:21:47 Daddys-MacBook Tribler[852] <Notice>: ImportError: No module named csv
Jan 29 09:21:47 Daddys-MacBook Tribler[852] <Notice>: 09:21:47: Deleted stale lock file '/Users/russelrhoades/tribler-russelrhoades'.
Jan 29 09:22:16 Daddys-MacBook spindump[681] <Notice>: Saved hang report for Tribler version 0.0.0 (0.0.0) to /Library/Logs/DiagnosticReports/Tribler_2016-01-29-092215_Daddys-MacBook.hang
Jan 29 09:23:31 Daddys-MacBook Tribler[887] <Notice>: Traceback (most recent call last):
Jan 29 09:23:31 Daddys-MacBook Tribler[887] <Notice>:   File "<string>", line 5, in <module>
Jan 29 09:23:31 Daddys-MacBook Tribler[887] <Notice>: ImportError: No module named csv
```

**Comment by whirm** [comment]
@Whyisdaddy just to make sure: You are running Tribler 6.5-RC7, right?

**Comment by Whyisdaddy** [comment]
Yes i am using 6.5-rc7

**Comment by Whyisdaddy** [comment]
i sorry its 6.4.3

**Comment by Whyisdaddy** [comment]
ok i just downloaded 6.5-RC7 and it works !!!

**Comment by whirm** [comment]
Great! :D 

Closing this then!

**Comment by synctext** [comment]
@whyisdaddy impressive effort to help us forward. Please report more bugs when you find them.. We really need more Mac feedback.

**Comment by Whyisdaddy** [comment]
Well thank you I'm running into something new I think one of my computers my imac works without issue
but my laptop i use in a different room is wireless and Tribler can't find any channels and I am not sure why? its the newest version the last version will not work on my laptop , This laptop is used to test apple new operating systems I have been helping test these updates and system changes for them for a few years now. and I am wondering it this could be a problem for Tribler?
