### ISSUE TITLE
The file size filter widget is gone

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1912]
I guess because of the wx migration?

**Comment by devos50** [comment]
I also don't see this widget on OS X (with a checkout of the `next` branch). I will take a look.

**Comment by whirm** [comment]
Oh, hadn't noticed that, let me check on the macbook

**Comment by whirm** [comment]
Yup, not showing here either.

**Comment by devos50** [comment]
@whirm I will checkout next and try to fix it there.

**Comment by whirm** [comment]
Great, weird that it works fine on windows and Linux

**Comment by devos50** [comment]
It seems that the widget is not displayed the moment is it is added to the `wx.BoxSizer`. When not using a `wx.BoxSizer`, it displays correctly.

**Comment by whirm** [comment]
Amazing

**Comment by devos50** [comment]
@whirm I did an attempt to fix it in PR #1923. Can you please test it on the Macbook? I'm unable to test it since I only have 64-bit systems. It's looking fine on Linux now (see https://jenkins.tribler.org/job/GH_Tribler_pull-request-tester/5636/).

**Comment by whirm** [comment]
Oh, I merged it before seeing this, next time add the WIP tag to the PR or ask me there :)

I'll test it right away.

**Comment by devos50** [comment]
Yeah asking it on the PR was better. I don't have permissions to add labels to issues btw.

I've implemented the changes in this PR on `devel` and tested it there. The widget was visible now when using the code on `devel` but since this is 6.5 related, I opened this PR against `next` ;)

**Comment by whirm** [comment]
Hm, I'll have a look and see if I can give that kind of permission.

**Comment by whirm** [comment]
Yeah, it's showing on osx 32bit.

**Comment by devos50** [comment]
Great! :+1:

**Comment by whirm** [comment]
Shows on windows too
