### ISSUE TITLE
wx.Notebook on 64 bit is bugged using wx 3

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#1919]
Bug is [known](http://trac.wxwidgets.org/ticket/16561) yet no confirmed fix.
100% triggers on windows 64 bit.

With the error `CRITICAL:UnhandledExceptionCatcher:Unhandled exception raised while running the test: <class 'wx._core.PyAssertionError'> PyAssertionError(u'C++
assertion "m_growableRows[n] < nrows" failed at ..\\..\\src\\common\\sizer.cpp(1874) in wxFlexGridSizer::AdjustForGrowables(): invalid growable row index',)`

problem is in `channel.py` line 1500

**Comment by devos50** [comment]
@whirm can you assign me on this one? It's wx3 related.
