### ISSUE TITLE
Move parts of README into wiki and translate it into german

### ISSUE THREAD

**Issue by Anth0rx** [Tribler/tribler#1922]
Hey, 
I have already mentioned that I want to start to contribute to this awesome project. This week I added dependencies for Arch Linux and now I want to take that a step further. I volunteer to do some documentation/wiki maintenance stuff to get familiar with the whole project. I also plan to translate the wiki into german.

Regards
Anth0rx

**Comment by devos50** [comment]
Hi, great that you want to help! Any help on this project is greatly appreciated and starting with documentation is indeed a good way to learn more about the system and familiar with it (writing more documentation is also a part of my thesis, maybe we can work together on some parts?). I've also learned a lot by just looking at the code (with a more high-level view) and see how various components interact with each other.

Maybe @whirm can give some more information about what kind of documentation we are missing and what the biggest priorities are at the moment regarding documentation.

If you have any questions about the code, please let us know :)

**Comment by synctext** [comment]
@Anth0rx adding German language support to Tribler would also be an awesome contribution... If you have bit of Python experience, should be realistic.

**Comment by whirm** [comment]
@Anth0rx great to read that :)

re documentation: I'd rather have the documentation on the [git repository](https://github.com/Tribler/tribler/tree/devel/doc) than on the wiki. It's easier for us to review changes and it's simpler to keep it in sync with the current code.

Let us know if you need any help/guidance. Also there's usually someone at the #tribler IRC channel on freenode, so feel free to hang around there if you want.

**Comment by lfdversluis** [comment]
Hi @Anth0rx !
Awesome that you want to help Tribler further. Every contribution helps the project advance. We are currently documenting a lot of things, (see PR #1872 and #1875 for example), so there will be plenty of things to translate later on. 
Feel free to join the IRC, we are happy to answer questions

**Comment by Anth0rx** [comment]
Okay nice. @whirm Wouldn't it be better to transfer the [wiki](https://github.com/Tribler/tribler/wiki) into the [repository](https://github.com/Tribler/tribler/tree/devel/doc) so we have all the documentation in one place?

@synctext I am learning Python at the moment. For now I will remain translating the documentation to get more familiar with Tribler.

**Comment by whirm** [comment]
@Anth0rx Yeah, but only the code related part (how to package/develop/etc.) The more abstract or general stuff should stay in the wiki. It would be nice that anything moved to git is checked for validity first.

**Comment by Anth0rx** [comment]
Okay, and if i wanted to translate the wiki as well? Is that possible?

**Comment by whirm** [comment]
Sure, I guess you could create a /german/ subdir? Haven't thought much about the wiki to be honest. Maybe @synctext has some opinions.

**Comment by Anth0rx** [comment]
The wiki is not part of the repository, right? @synctext Can you tell me how to create a multilingual wiki page, so the visitors are able to select a language first?

**Comment by whirm** [comment]
@Anth0rx the wiki is a separate git repository, re multilingual wiki, I don't think github has support for this, just create a /de/ or /german/ subdir with the documentation in there.

**Comment by Anth0rx** [comment]
But did't you say:

> @Anth0rx Yeah, but only the code related part (how to package/develop/etc.) The more abstract or general stuff should stay in the wiki. It would be nice that anything moved to git is checked for validity first.

**Comment by whirm** [comment]
The wiki IS a git repository (whenever you do modifications, a new commit gets created automatically for them) when I refer to the git repository, I'm talking about the main one that contains the Tribler code.

**Comment by Anth0rx** [comment]
However this doesn't solve the multilingual Problem :/

**Comment by whirm** [comment]
Just add a subdir per language and we can add links to these on the sidebar of the wiki.

**Comment by Anth0rx** [comment]
Okay, thanks ;)

**Comment by Anth0rx** [comment]
I get confused with all the repositories :O If you mean adding a subdir in the "wiki repo" how do that work?

**Comment by whirm** [comment]
How I see it is: 
 - If it's code related documentation (building, sending PRs, reporting issues, development guidelines, etc) it goes to the git repository. This way we can keep it in sync with the existing code even if it differes across branches or commit history.
 - If it's academic/research or non specifically code related, it goes to the wiki. This kind of stuff tends to evolve on its own.

I hope I'm explaining myself :)

**Comment by Anth0rx** [comment]
Okay, assuming I want to translate parts of the wiki: It is possible to download the wiki as a repository or to edit it online. You said I should create a /german subdir. This will only work if I download the wiki-repo. But I can't just add a subdir and commit it. That will cause problems because I do not have the permissions :(

**Comment by lfdversluis** [comment]
@Anth0rx make a fork of github. Then checkout your fork. Translate your stuff and commit it to your fork. Then create a pull requests :+1:

**Comment by Anth0rx** [comment]
@lfdversluis You cannot fork the wiki. I am just able to **clone** the wiki but then I cannot commit any changes :(

**Comment by whirm** [comment]
@Anth0rx oh well... Let me have a look a it.

**Comment by whirm** [comment]
@Anth0rx It doesn't even support subdirs, I tried it and it gets confused. Maybe just prepend `DE` to each page then?

**Comment by Anth0rx** [comment]
Hmm, okay. That's an option ;) I will try that for sure :P

**Comment by vandenheuvel** [comment]
@devos50 I believe this can be closed.
