### ISSUE TITLE
GetSubBitmap invalid bitmap region

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#1931]
When running `test_gui_dialogs.py` I encountered an exception:

`Exception: Test raised 2 unhandled exceptions, last one was: PyAssertionError(u'C++ assertion "rect.x >= 0 && rect.y >= 0 && rect.x + w <= bmpData->m_width && rect.y + h <= bmpData->m_height" failed at ../src/gtk/bitmap.cpp(990) in GetSubBitmap(): invalid bitmap region',)`

When I ran it again it passed, maybe worth taking a look at though.

Ubuntu 15.10, 64 bit amd, using wxgtk3.0

**Comment by devos50** [comment]
This can be reproduced by resizing Tribler very fast to a smaller window. When resizing back to a bigger window, the assertion is thrown. Only happens using GTK.

**Comment by lfdversluis** [comment]
@whirm can you assign this issue to me please?

**Comment by whirm** [comment]
But isn't that fixed by @devos50's minimum window size PR?

**Comment by lfdversluis** [comment]
No, that was the segfault. the violent resizing fix in my PR fixes this issue.

**Comment by whirm** [comment]
Ah, I see
