### ISSUE TITLE
No channels matching tv assertion when running tests

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#1938]
When running `test_channel_search `, I get the following error:

```
======================================================================
ERROR: test_channel_search (Tribler.Test.test_remote_search.TestRemoteChannelSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/GH_Tribler_pull-request-tester/tribler/Tribler/Test/test_as_server.py", line 72, in check
    process_unhandled_exceptions()
  File "/home/jenkins/workspace/GH_Tribler_pull-request-tester/tribler/Tribler/Test/util.py", line 111, in check_exceptions
    raise Exception("Test raised %d unhandled exceptions, last one was: %s" % (exc_counter, last_exc))
Exception: Test raised 1 unhandled exceptions, last one was: AssertionError('no channels matching tv',)
```

**Comment by whirm** [comment]
This is because the test fails. It will sometimes happen as it connects to the internet and does real queries. If it doesn't get a result in time, it will fail.

**Comment by devos50** [comment]
According to the screenshots, it got results. I will investigate the tests to see what's going on here.

**Comment by whirm** [comment]
@devos50 have in mind that it is looking for channels, not just for results, so maybe you got file results but not channel results.

**Comment by devos50** [comment]
@whirm This test is triggering in around 25% of the runs. Do you have any suggestions on how we can rewrite this test?

**Comment by whirm** [comment]
That's not a good test for starters, but I guess the best way to patch it up a bit until we have proper ones written would be to instance a Tribler session that has some content and inject that candidate in the one being tested so it always finds somebody with content that matches the search results in time.

**Comment by devos50** [comment]
@whirm what do you think about disabling the check whether there are results or not on the tests that searches for content? It seems that this is the only error that shows during the tests now and then.

**Comment by whirm** [comment]
I would prefer to see why it fails and try to fix it, or at least make it more reliable.

**Comment by devos50** [comment]
Could it be that it is connecting to peers that have no metadata about the particular channels matching `tv`?

**Comment by whirm** [comment]
Could be, but in principle it keeps rotating candidates and the search is not one shot, so the results should arrive sooner or later.
