### ISSUE TITLE
Make the installer install in `program files` when installing 64 bit

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#1943]
currently it installs to `program files x86`

**Comment by lfdversluis** [comment]
@whirm Could you assign this one and #1878 to me?

**Comment by lfdversluis** [comment]
Closing as it is fixed

**Comment by whirm** [comment]
@lfdversluis Don't forget that the jobs still need updating.

**Comment by lfdversluis** [comment]
@whirm The jobs already pass the argument to the update git from py script. Both builders have the new NSIS + plugins installed. Am I missing something here?
