### ISSUE TITLE
Create local webserver and add tests to test torrent and rss downloading

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#1944]
In PR #1942 we changed remote torrents to local ones because one of the dependencies dropped and a lot test broke.

We should set up a webserver of our own to host some torrent files that will always be available, or at least under our control to fix to also test if using remote downloading works using additional tests.

**Comment by devos50** [comment]
@whirm maybe you can give one of us access to the bbq so we can install apache/nginx and setup a HTTP file server? It's not that hard to do and should take little time.

**Comment by whirm** [comment]
nope, the test needs to start a basic web server itself. Bad idea to have tests depending on external stuff as you have seen repeatedly :)
