### ISSUE TITLE
Segmentation fault when resizing Tribler to a very small size

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#1945]
When resizing Tribler to a very small window, a segmentation fault triggers. This happens when GTK is used as backend for wxPython.

**Comment by lfdversluis** [comment]
On Ubuntu 15.10 it does not segfault but the canvas is completely blank. Everything, from menu to panel is gone when you resize it back.

**Comment by whirm** [comment]
Just limit the minimum size of the main window. The layout is really bad and buttons will start piling up past a certain point anyway.

**Comment by lfdversluis** [comment]
I doubt this will fix the issue completely. I think that resizing it to the minimum and then resize it full screen again will still leave parts blank.

**Comment by lfdversluis** [comment]
Ok so now the segfualt suddenly triggered as well on ubuntu. Weird that the 2 times i tried earlier it did not work. But now we now it's there on ubuntu too.

**Comment by lfdversluis** [comment]
This can be closed now, right?
