### ISSUE TITLE
Dispersy assertion error

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#1950]
See [this jenkins run](https://jenkins.tribler.org/job/GH_Tribler_pull-request-tester/5709/artifact/output/test_runners_output/00002.err/*view*/)

A `exceptions.AssertionError: [(<Tribler.dispersy.candidate.Candidate object at 0x7fcf4fef5b10>, 'PJJP\x02\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'), (<Tribler.dispersy.candidate.Candidate object at 0x7fcf4fef5210>, 'PJJP\x02\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')]` assertion triggered.

Also noticed 

```
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
[00007fcf00001268] xcb_xv vout display error: no available XVideo adaptor
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

in the logs

**Comment by whirm** [comment]
Paste the whole stracktrace when reporting a bug, otherwise everyone has to click on the link and it's harder to find duplicate reports.

the second part is not a Tribler error, but libvlc complaining about stuff that's missing on the host system, you can ignore it.

**Comment by whirm** [comment]
Also, depending on the stacktrace, this should go to the dispersy bug tracker instead.

**Comment by lfdversluis** [comment]
@whirm right. Should I close this one and open one on dispersy?

**Comment by whirm** [comment]
it depends on what triggers that exception. If you can't see what the cause is, tell me and I'll have a look when I can.

**Comment by lfdversluis** [comment]
@whirm I havent really taken a good look at it. I was looking trough the logs why the build failed and saw this error. Decided to post it to keep track of its existence. But sure, please investigate it further.

**Comment by devos50** [comment]
Probably we received a corrupt message. We can't do much about this unfortunately but we shouldn't assert for bad packets. I've fixed this a while ago.
