### ISSUE TITLE
Attribute error in Tribler/Core/CacheDB/sqlitecachedb.py

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#1951]
An `exceptions.AttributeError: 'NoneType' object has no attribute 'cursor'` error was thrown in [this jenkins run](https://jenkins.tribler.org/job/GH_Tribler_pull-request-tester/5709/artifact/output/test_runners_output/00004.err/*view*/).

**Comment by whirm** [comment]
That happens when Tribler shuts down shortly after starting, the shutdown procedure in Tribler is pretty bad. 
We will take care of all this once libtorrent is decoupled from the GUI.

**Comment by devos50** [comment]
This one has been fixed a long time ago 👍
