### ISSUE TITLE
Convert blocking SQL calls to deferreds

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#1968]
This issue is to track which instances that make of SQL statements can be converted to [deferreds](https://twistedmatrix.com/documents/14.0.1/core/howto/defer-intro.html). Using deferreds to perform SQL ensures that during I/O, the thread will not block, preventing performance loss.

Below a list of instances that can probably be converted to using Deferreds; if you encounter a method that can be converted, let me know!
- [ ] **database.py** (in community/multichain/), almost all methods.
- [x] **tracker_manager.py** the **initialize** method.
- [x] **tracker_manager.py** the **add_tracker** method.
- [x] **tracker_manager.py**, **most** methods.
- [x] **home.py** (in vwxGui) the **_printDBStats** method.
- [x] **SearchGridManager.py** the **savePlaylistTorrents** method.
- [ ] **community.py** in dispersy the **on_missing_identity** method.
- [ ] **dispersy.py** the **sanity_check** method.

**Comment by devos50** [comment]
I will let you know if I see any DB calls that can be transferred to deferred objects.

Maybe it's a good idea to create some (small) benchmarks with and without blocking DB calls and see how much % performance gain can be obtained?

Btw, the sqlite database is not the only database we are using (for instance, we also use LevelDB). Can we also make these calls non-blocking?

**Comment by lfdversluis** [comment]
@devos50 Yes, @whirm thinks the multichain community can be a good first benchmark to see how much we gain. Maybe that a really small benchmark could already provide some insight, let's try that out.

**Comment by whirm** [comment]
@devos50 the LevelDB store has been async since the beginning.

**Comment by ichorid** [comment]
RIP Dispersy
