### ISSUE TITLE
Unused methods in Tribler/Core/VideoUtility.py

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#1970]
In `Tribler/Core/VideoUtility.py`, there are some unused methods:

- `preferred_timecodes`
- `get_thumbnail` (only used by `preferred_timecodes`)
- `colourfulness` (only used by `preferred_timecodes`)
- `meanstdv` (only used by `colourfulness`)

What should we do with these methods? Should we remove them or make them usable in some way (for instance, as an API endpoint)?

**Comment by whirm** [comment]
No idea, never looked at that.

**Comment by lfdversluis** [comment]
In that case, do you see them being used in the future? Any purpose at all? If they work out of the box, you could convert them. If these can be changed by library calls or are simply broken, i'd say get rid of them.

**Comment by LipuFei** [comment]
@whirm Those methods are used to generate thumbnails from a given video file. They used to be used by the MetadataCommunity. `colourfulness()` is used to check for XXX.

**Comment by whirm** [comment]
Yeah, I guess we should keep this for when the thumbnails are back up
