### ISSUE TITLE
Creating of a torrent file with multiple files raises an assertion in libtorrent

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#1971]
When creating a torrent file using the `create_torrent` method in `torrent_utils.py`, libtorrent gives an assertion:

```
A precondition of a libtorrent function has been violated.
This indicates a bug in the client application using libtorrent

file: '../../src/file_storage.cpp'
line: 449
function: void libtorrent::file_storage::add_file(const std::string &, size_type, int, std::time_t, const std::string &)
expression: m_files.empty()
```

This assertion does not trigger when using a release libtorrent or a libtorrent with assertions disabled.

This might be due to the fact that we are using the `add_files` method to add files to the libtorrent filestorage. Instead, I suspect that we should use the `add_file` method (see https://github.com/arvidn/libtorrent/blob/master/bindings/python/make_torrent.py#L36).

**Comment by LipuFei** [comment]
I remember there indeed were some unsolved bugs in `create_torrent()`, mainly related to creating a single-/multi-file torrent.

**Comment by whirm** [comment]
@devos50 you fixed that one already, right?

**Comment by devos50** [comment]
@whirm this one is fixed.
