### ISSUE TITLE
Unused methods in osutils.py

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#1974]
When analyzing the `osutils.py` file, I encountered some unused methods:

- `getcpuload`
- `read_proc_stat`
- `getupload` (what is/was the purpose of this method? Getting the total upload speed on OS X?)

Any suggestions on what to do with them? I don't think they are needed since the cpu load can easily be queried using `psutil`. Moreover, I don't see any purpose for `read_proc_stat` in Tribler itself (we are using it in Gumby however to get the resource usage), neither do I for the `getupload` method.

**Comment by LipuFei** [comment]
I don't think they are used in tribler. Should be moved to gumby if that's where it belongs.
