### ISSUE TITLE
Refactor Category class so it is not dependent on a session

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#1986]
Currently, a `Session` object is passed to the constructor of `Category`. The only purpose of this session in the `Category` class is to get the installation directory of Tribler (which is a string).

I propose to break the dependency between `Session` and `Category` so `Category` can be used without a running `Session`. Instead, the installation directory is passed to the constructor of `Session`.

**Comment by whirm** [comment]
Isn't there a static method in some module that tells you this?

**Comment by whirm** [comment]
https://github.com/Tribler/tribler/blob/be52821a6384eb861427c2964a9a7060450df3ef/Tribler/Core/Utilities/install_dir.py#L42

**Comment by devos50** [comment]
@whirm you mean `determine_install_dir` in `install_dir.py`?

**Comment by whirm** [comment]
I say go ahead

**Comment by devos50** [comment]
Will do, can you assign me to this issue?

**Comment by whirm** [comment]
Try to see if you can find more cases of the Session being used just for that, that will help a lot decoupling which will make testing easier.

**Comment by devos50** [comment]
Yep, already found one more instance. In the sqlite database constructor, the session is also passed and only a specific path of this session is used. I will make a separate issue for that one.
