### ISSUE TITLE
The session is not shuttinng down properly

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1989]
That's on current devel:

https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/82/testReport/junit/Tribler.Test.test_remote_search/TestMixedRemoteSearch/test_remotedownload/

Apparently either Session or Dispersy are reporting the shutdown completion prematurely or the communities aren't being unloaded correctly.

**Comment by LipuFei** [comment]
@whirm At the end of the log you can see that after dispersy has fully stopped (after this line),
```
DEBUG   1456475830        dispersy:Dispersy:2201 Checking dispersy stop results
```
Another 8 `CircuitRequestCache`s has been added, which are probably the 8 uncleaned `CircuitRequestCache`s got complained about at the end.

Perhaps it's a good idea to shutdown the network first? Or we can emit a signal when dispersy is fully shutdown, and other services that depend on dispersy and communities should subscribe to this signal and handle the shutdown gracefully.

**Comment by whirm** [comment]
When a community is shut down, it should not leave anything behind, and the tunnel community is. So that needs to be fixed. I guess the community should not allow new circuits to be created and then shut down all existing ones before exiting,

**Comment by LipuFei** [comment]
@whirm Would it be a good idea to make a shutdown flag for TaskManager and set a "has_stopped" flag, and in register_task(), we can check this flag and avoid adding new tasks after shutdown?

**Comment by whirm** [comment]
@LipuFei I think that it would be better to do that at a higher level, when stopping, the communities should flush their pending messages and stop their subsystems properly. Also, ignoring a task registration doesn't make the task go away, it will be simply not accounted for.

**Comment by LipuFei** [comment]
Agree, because I don't like to repeat things like `if stopped: return` in all functions, I was thinking about something that saves some typing.

**Comment by devos50** [comment]
The link to the report is broken unfortunately so I'm unable to see the exact issue (I think it's the bug with the `DiscoveryCommunity` described in https://github.com/Tribler/dispersy/pull/513). Moreover, we refactored the shutdown procedure recently so it's more streamlined.
