### ISSUE TITLE
Tribler does not operate

### ISSUE THREAD

**Issue by SenikaRu** [Tribler/tribler#1992]
#### Please, fill all relevant items: ####

- [ ] I have read CONTRIBUTING.md

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
6.5.0
##### Operating system and version: #####
windows10 Version 1511 for x64-based Systems
##### Expected behavior: #####
Tribler window shows up
##### Actual behavior: #####
Tribler window show for a breif moment and gets off. Not shown on the taskbar but It's operating when I look at Task Manager. When I double click .torrent file error message appears.
##### Steps to reproduce the behavior: #####
Uninstalled Tribler and reinstalled after a while and this error occurs after reinstall. Uninstalled and reinstall again and problem persists after recovery to the point before tribler was first installed,
##### Relevant log file output: #####
Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 183, in __init__
  File "Tribler\Core\Session.pyo", line 419, in start
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 105, in register
  File "Tribler\Core\leveldbstore.pyo", line 76, in __init__
LevelDBError: Corruption: 1 missing files; e.g.: collected_torrents/000007.sst
Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 1060, in run
  File "Tribler\Utilities\Instance2Instance.pyo", line 42, in __init__
  File "socket.pyo", line 228, in meth
error: [Errno 10061] No connection could be made because the target machine actively refused it

**Comment by whirm** [comment]
Apparently your leveldb database got corrupted somehow?

Could you please rename `%APPDATA%/.Tribler/collected_torrents` and try again?

**Comment by SenikaRu** [comment]
What file should I change the name?
There is '000008.log' 'CURRENT' 'LOCK' 'LOG' 'LOG.old' 'MANIFEST-000006' in 
%APPDATA%/.Tribler/collected_torrents

**Comment by whirm** [comment]
Change the name of the directory called `collected_torrents` to something else like `collected_torrents_bak`

**Comment by SenikaRu** [comment]
It worked!!! I think just erasing collected_torrents might actually work.
Thanks!!!!

**Comment by whirm** [comment]
Nice, glad to help. 

Did you have a system crash or power outage recently?

**Comment by SenikaRu** [comment]
maybe recovery after using was the problem

**Comment by whirm** [comment]
In any case, I've created an issue for this kind of things, it would be nice if Tribler could recover from this kind of corruptions by itself.

Thanks!
