### ISSUE TITLE
The tunnel helper should have bandwith usage settings implemented

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1994]
Right now if goes full steam ahead and the only limits are bandwidth and CPU availability. 
There's not a lot of people interested on running those, at least let's make it easy for them by allowing to use only a portion of the available bandwidth.

@synctext should this be taken care of by the MSC students? 

@synctext should this be part of the 6.6 milestone?

**Comment by egbertbouman** [comment]
Since there are currently no plans for implementing such a feature, I'm closing this issue.
