### ISSUE TITLE
Add support for anonymous downloads and file picking in the start_download method of LibtorrentMgr

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#1998]
Currently, the `start_download` method in `LibtorrentMgr` does not support anonymous downloads and selection of files to be downloaded. Support for these features should be added.

**Comment by egbertbouman** [comment]
As far as I know, ```LibtorrentMgr``` doesn't have a ```start_download``` method, but ```Session``` does. Anonymous downloads can be started with this method by passing it a ```DownloadConfig``` with a positive number of hops.

**Comment by egbertbouman** [comment]
I guess you were referring to a method that hasn't been merged yet (in this [PR](https://github.com/Tribler/tribler/pull/1997/files)). My bad :P

**Comment by devos50** [comment]
@egbertbouman indeed, I'm moving the start of a torrent download to the Tribler Core (where it essentially belongs). This makes it possible for me to start a download from a url/file/magnet link using the upcoming HTTP API :+1:

**Comment by devos50** [comment]
This one has been added (you can pass the amount of hops/files to the `start_download` method).
