### ISSUE TITLE
package directory 'Tribler/Core/DecentralizedTracking/pymdht/core' does not exist

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2003]
If I run setup.py https://github.com/Tribler/tribler/archive/v6.5.0.tar.gz cross-compile for android-arm it fails:
```
[DEBUG]:   	package init file 'Tribler/Core/DecentralizedTracking/pymdht/__init__.py' not found (or not a regular file)
[DEBUG]:   	error: package directory 'Tribler/Core/DecentralizedTracking/pymdht/core' does not exist
```
Am I missing something (in the source package)? Are the submodules not included in the release?

**Comment by devos50** [comment]
@brussee in the `tar.gz` file, the `Tribler/Core/DecentralizedTracking/pymdht` directory seems to be empty, not sure why. @whirm is this a bug?

**Comment by lfdversluis** [comment]
It's submodule, looks like it wasn't added properly.

**Comment by whirm** [comment]
Github doesn't add submodules to the source archives built by them and we can't disable it. Either use the .tar.xz provided together with the installers which is packed by jenkins and contains everything, or check out the `v6.5.0` tag on git and make sure you update the submodules.

**Comment by brussee** [comment]
Using .tar.xz works. Thanks @whirm!
Solution implemented upstream https://github.com/kivy/python-for-android/pull/685
