### ISSUE TITLE
Plyvel support can be removed from Tribler

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#2005]
@brussee Fixed python-levedb and sent a recipe to python4android upstream's so Tribler can use the same bindings across all supported OSs.

@devos50 just to confirm: OSX is not using plyvel either, right?

**Comment by devos50** [comment]
No, the OS X builder uses `leveldb`: https://github.com/Tribler/tribler/blob/devel/Tribler/Main/Build/Mac/setuptriblermac_64bit.py#L20

**Comment by lfdversluis** [comment]
@whirm Can you close this one as leveldb is only available in the user repository of arch linux and thus we need to keep the support for plyvel as this package is available in pacman.

**Comment by whirm** [comment]
Yes, this should be done when/if Arch gets python-leveldb in the official repos or debian gets plyvel instead.
