### ISSUE TITLE
win\makedist.bat is broken on devel

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#2014]
https://jenkins.tribler.org/job/Build-Tribler_WinSrvr2008R2_64_devel/

tribler.nsi got moved but the old .bat didn't get updated.

**Comment by lfdversluis** [comment]
`makedist` is the old, untouched version. The new version is `makedist_win`. This file was [added](https://github.com/lfdversluis/tribler/blob/208533cf2857367e9cedf67abb2ee7128db47e51/win/makedist_win.bat) and merged in #1872. This was done to ensure we would could still call the old builder from current devel using the old settings.

**Comment by lfdversluis** [comment]
@whirm is the wrong file configured on Jenkins? If so, sorry!

**Comment by whirm** [comment]
I don't know, but if this file is not supposed to work, it should be removed.

**Comment by lfdversluis** [comment]
@whirm ok, then I'll delete the old makedist. Should I rename the `makedist_win` to `makedist` ?

**Comment by whirm** [comment]
I don't know how you have set that up, but everything that's there needs to work and if the jobs need to be updated due to any change, you should do that too once any changes get merged.

**Comment by whirm** [comment]
That's the new parallel job I created to build devel:
https://jenkins.tribler.org/job/Build_Tribler_devel/
If I'm using the wrong jobs, feel free to update it, also disable whatever job got obsoleted by your changes with a comment on the description and tell me about them please.

**Comment by lfdversluis** [comment]
It's currently building on the wrong machine: `Building remotely on Builder-WinSrvr2008R2_64_tudelft (WinServer2008R2-x64) in workspace C:\workspace\jenkins\workspace\Build-Tribler_WinSrvr2008R2_64_devel`

The new `makedist_win.bat` has paths changed (e.g. just a folder 'ffmpeg' in the build folder instead of something like 'ffmpeg-20150107-git-919e038-win32-static'), this has been changed on the new building machine (proxmox 102 & 103).

I can change this if you'd like.

**Comment by whirm** [comment]
Sure, and remove any leftover stuff from the `devel` branch too. thanks!

**Comment by lfdversluis** [comment]
I also took the liberty of adding the new 32 bit builder to that job.

**Comment by whirm** [comment]
it means the job that's complaining has a "copy artifacts from another job" step and the job it tries to copy stuff from doesn't exist.

**Comment by lfdversluis** [comment]
@whirm Thanks for explaning. The issue [is fixed](https://jenkins.tribler.org/job/Build_Tribler_devel/). This one can be closed I guess.

**Comment by whirm** [comment]
The 32 and 64 bit versions of the installer have the same name so one overwrites the other when collecting the artifacts. Also, I guess the 64 bit installer still puts Tribler in `program files (x86)`, right?

**Comment by lfdversluis** [comment]
Yes #1943 is not fixed yet. Them having the same name makes sense when you look at the script, it only replaces __GIT__ and does not differentiate the name.

**Comment by whirm** [comment]
The 64 bit piece is not part of the Tribler version but the installer, so it needs to be changed on the packager/installer side.

**Comment by lfdversluis** [comment]
@whirm see #2030 I have not tested it yet. I think I will modify my 64 bit builder to target my branch for now.

**Comment by whirm** [comment]
Yes, I saw it after commenting.

Sure, feel free to update the branch until it works.

Once they work, we should link them to the PR runner to make sure we aren't breaking the installers.
