### ISSUE TITLE
Handling unavailable trackers from channels

### ISSUE THREAD

**Issue by ardhipoetra** [Tribler/tribler#2015]
Some trackers in a channel does not responding to request when 'scraping'. For example, tracker from torrentbox (http://tracker.torrentbox.com:2710/announce) or ccc.de(udp://tracker.ccc.de:80/announce). Is there any way to 'blacklist' those trackers so it doesn't burden the system?

**Comment by whirm** [comment]
The trackers that don't respond get flagged and the next contact attempt is scheduled over increasingly long periods AFAIR.

**Comment by whirm** [comment]
Please, close the issue if that's all,
