### ISSUE TITLE
Torrent files should be removed from the torrent store when freeSpace is called

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2020]
The `freeSpace` method in `sqlitecachedbhandler.py` should probably also remove the torrent it is removing from the database, from the torrent store in order to actually clean up space.

**Comment by whirm** [comment]
Yeah, apparently nothing is cleaning the torrent store...

**Comment by lfdversluis** [comment]
Should be fixed by #2025

**Comment by lfdversluis** [comment]
@whirm Can you close this one?
