### ISSUE TITLE
Tribler's "twistification": refactor all functions that require a callback as argument to return a Deferred instead

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#2032]
A couple examples:

 - `create_engine_wrapper()`
 - `network_create_engine_wrapper()`

**Comment by lfdversluis** [comment]
I have refactored these now in a PR: #2057 I suggest that when someone encounters such a scenario, (s)he creates an issue which can then be targeted by another PR to keep the overview, rather than one big issue.
