### ISSUE TITLE
Won't start application

### ISSUE THREAD

**Issue by dukst** [Tribler/tribler#2045]
#### Please, fill all relevant items: ####

- [+ ] I have read CONTRIBUTING.md

- [ +] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Relevant log file output: tribler.exe.log:
Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 183, in __init__
  File "Tribler\Core\Session.pyo", line 419, in start
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 152, in register
  File "Tribler\dispersy\dispersy.pyo", line 49, in <module>
Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 1067, in run
  File "Tribler\Main\tribler_main.pyo", line 306, in __init__
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
  File "Tribler\Main\tribler_main.pyo", line 876, in onError
  File "traceback.pyo", line 233, in print_exc
  File "traceback.pyo", line 128, in print_exception
  File "traceback.pyo", line 13, in _print
  File "C:\Python27\x86\lib\site-packages\py2exe\boot_common.py", line 74, in write
  File "encodings\utf_8.pyo", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xcf in position 30: invalid continuation byte
The reactor was not clean after stopping:
>     <DelayedCall 0x45f4a30 [9.82099986076s] called=0 cancelled=0 LoopingCall<15>(VoteCastDBHandler._flush_to_database, *(), **{})()>
>     <DelayedCall 0x450e5f8 [114.789999962s] called=0 cancelled=0 LoopingCall<120>(LevelDbStore.flush, *(), **{})()>
>     <DelayedCall 0x450e620 [114.789999962s] called=0 cancelled=0 LoopingCall<120>(LevelDbStore.flush, *(), **{})()>
>     <DelayedCall 0x45f4cd8 [294.820999861s] called=0 cancelled=0 LoopingCall<300>(update_nr_torrents, *(), **{})()>

**Comment by lfdversluis** [comment]
@dukst Thanks for the report. We will take a look at it.
@whirm I think you fixed this issue, or attempted to at least. Was this already included in 6.5.1 ?

**Comment by whirm** [comment]
@devos50: The unicode error comes from py2exe's stdout/stderr highjack AFAIR. There should be an issue around with a similar stacktrace. (Running short on time and on an ubercrappy internet connection, so I'll leave the search to you)

**Comment by whirm** [comment]
@lfdversluis Just noticed I replied to @devos50 instead of you for some reason

**Comment by synctext** [comment]
@dukst this week we are aiming to fix this bug...

**Comment by lfdversluis** [comment]
Taking care of this one now. @whirm assign it to me pelase.

**Comment by lfdversluis** [comment]
@dukst I have taken a look at the error and discussed it with @whirm. It looks like our new builders have an upgraded version of py2exe, which the program that was throwing the error. Could you test [this build on your machine](https://jenkins.tribler.org/job/Build-Tribler_Win64/lastSuccessfulBuild/artifact/tribler/dist/Tribler_6.5.0-rc5-569-ga2f1238_x64.exe) and **check only if it starts** ? This is a development version and things may not be 100% stable.

If you verify that you can at least start tribler with the build I have linked, then we found this issue.

**Comment by whirm** [comment]
@dukst: @lfdversluis forgot to mentiont that before starting this development version, you should back up `%APPDATA%\.Tribler` just in case.

**Comment by lfdversluis** [comment]
@whirm good point. Thanks for noticing!

**Comment by zor1984qq** [comment]
Thank you. I have not being able to test it while I just scratching the surface of newly installed Deepin Linux but from the point that I digging in with previous Sabayon installation it can be fixed up by just pulling git clone and syncing tribler software with recent git repositaries and then just starting it from "sh" any vtt terminal. For the OS level I have no Sabayon installation for now and their package base called Entropy is well maintained in some ways but not these special case. Mainly it is refers to the some changes in python 2->3 whole world migration and some stalled pieces of code in particular tribler software. I think there is no reason to test such things to me in Linux Deepin cause it is based on Debian/Deepin unstable repo's branches and I think it works somehow anyway since you probably well tested these patches on your hardware and just want it to see how these would work on the others machines. Anyway thank you for reporting these and taking care of it.

**Comment by dukst** [comment]
@synctext thank you! Good luck! :)

**Comment by dukst** [comment]
@lfdversluis Thanks, I'll do that today and write here.

**Comment by whirm** [comment]
@dukst the file got rotated out of the build history, get that one instead: https://jenkins.tribler.org/job/Build-Tribler_Win64/130/artifact/tribler/dist/Tribler_6.5.0-rc5-586-g38c8850_x64.exe

**Comment by dukst** [comment]
@whirm @lfdversluis This is Tribler for a 64-bit version? My Windows Vista is 32 bit. It does not start. Tribler.exe log:
Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 183, in __init__
  File "Tribler\Core\Session.pyo", line 419, in start
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 152, in register
  File "Tribler\dispersy\dispersy.pyo", line 49, in <module>
Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 1067, in run
  File "Tribler\Main\tribler_main.pyo", line 306, in __init__
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
  File "Tribler\Main\tribler_main.pyo", line 876, in onError
  File "traceback.pyo", line 233, in print_exc
  File "traceback.pyo", line 128, in print_exception
  File "traceback.pyo", line 13, in _print
  File "C:\Python27\x86\lib\site-packages\py2exe\boot_common.py", line 74, in write
  File "encodings\utf_8.pyo", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xcf in position 30: invalid continuation byte
The reactor was not clean after stopping:
>     <DelayedCall 0x45f4a30 [9.82099986076s] called=0 cancelled=0 LoopingCall<15>(VoteCastDBHandler._flush_to_database, *(), **{})()>
>     <DelayedCall 0x450e5f8 [114.789999962s] called=0 cancelled=0 LoopingCall<120>(LevelDbStore.flush, *(), **{})()>
>     <DelayedCall 0x450e620 [114.789999962s] called=0 cancelled=0 LoopingCall<120>(LevelDbStore.flush, *(), **{})()>
>     <DelayedCall 0x45f4cd8 [294.820999861s] called=0 cancelled=0 LoopingCall<300>(update_nr_torrents, *(), **{})()>

**Comment by dukst** [comment]
Closed by mistake, sorry. Open!

**Comment by lfdversluis** [comment]
@dukst Ah didn't notice your 32 bit version. Let me link you another build. Hang on :)

**Comment by lfdversluis** [comment]
@dukst A freshly cooked 32 bit version: https://jenkins.tribler.org/job/Build-Tribler_Win32/lastSuccessfulBuild/artifact/tribler/dist/Tribler_6.5.0-rc5-586-g38c8850_x86.exe

Please try it out and check if it opens. If it doesn't we need to dive further, else we know what's wrong.

**Comment by lfdversluis** [comment]
@dukst Don't forget to back up %APPDATA%\.Tribler just in case.

**Comment by dukst** [comment]
@lfdversluis @whirm Twice installed - both times not start. 
Folder appdata/Roaming/.Tribler can be downloaded here: https://yadi.sk/d/VrT4QfevqzoYs

**Comment by synctext** [comment]
@dukst excellent feedback. thank you for helping to get this bug(s) out. We'll try to get you something that works soon.
Dispersy is acting out hmmmm.

**Comment by whirm** [comment]
@dukst I would delete that upload if I where you, it contains private stuff. (we never asked for you to upload it, just back it up in case the experimental build corrupts it somehow)

**Comment by whirm** [comment]
That's a DLL issue, it's probably missing a dependency.

Let's trace Tribler's startup so we can see which dll on the chain it's failing to load for you.

Could you download/unzip process monitor: https://technet.microsoft.com/en-us/sysinternals/bb896645

Then:

1: Start it, go to Filter > Filter... and add a "Process name is tribler.exe then include" filter.
2: Start Tribler
3: When it crashes, go back to process monitor and click on File > Save and save the log with the default params and attach it to this issue?
 
Thanks!

**Comment by whirm** [comment]
@lfdversluis I'll leave it to you from here (have a look at the uploaded trace to see what's missing.

**Comment by lfdversluis** [comment]
@whirm Thanks! Could you update the old builder to install a more recent py2exe? It seems to at least get the unicode bug out of the way.

@dukst I wanted to point out that this is indeed a different error. It looks like a DLL is missing that your version of Windows may be lacking. If you could provide us with the trace from the process monitor we would be grateful.

**Comment by whirm** [comment]
@lfdversluis which version are we sporting on the new builder?

**Comment by lfdversluis** [comment]
@whirm I've just checked and judging by the installer still in the Downloads folder and the `__init__.py` in the site-packages it is version `0.6.9`.

**Comment by lfdversluis** [comment]
https://sourceforge.net/projects/py2exe/files/py2exe/0.6.9/ Looks like it is the most recent one still. Hasn't been updated in years.

**Comment by whirm** [comment]
Updated, this build should contain the installer with the new py2exe: https://jenkins.tribler.org/job/Build_Tribler_next/7/

**Comment by dukst** [comment]
@whirm @lfdversluis 
[Logfile.zip](https://github.com/Tribler/tribler/files/220870/Logfile.zip)

**Comment by lfdversluis** [comment]
@dukst Thanks! I opened the file but cannot find an error in there. Could you run procmon.exe, then start tribler, make it crash and then save the logfile? Thanks for your effort in hunting this bug!

**Comment by dukst** [comment]
@lfdversluis I did just that. OK, will make a second attempt

**Comment by dukst** [comment]
@lfdversluis 
[Logfile.zip](https://github.com/Tribler/tribler/files/221424/Logfile.zip)

**Comment by dukst** [comment]
@lfdversluis tribler and his behavior :) - 

[Logfile1.zip](https://github.com/Tribler/tribler/files/221430/Logfile1.zip)

**Comment by lfdversluis** [comment]
Hi @dukst, I went through you log but it seems still incomplete. There is no error related to a file not being found and I was missing the process exit line, which indicated that not a full capture happened. Just to make sure you capture everything, can you do the following steps?

1. Open procmon.exe and wait a second or two
2. Run tribler.exe, make it crash and if any error dialog shows press ok.
3. wait for the tribler process to be killed on your computer.
4. go back to procmon and save the log.

Thanks a lot!

**Comment by synctext** [comment]
@lfdversluis  The Logfile1.zip contains the starting of Tribler, but no crash info of any kind?

**Comment by lfdversluis** [comment]
@snorberhuis

**Comment by whirm** [comment]
It does contain the bug happening:

```
File "Tribler\dispersy\dispersy.pyo", line 49, in 
```

corresponds to:

```
import netifaces
```

which imports `netifaces.pyd`. 

If you look at the procmon dump, this happens at 7:11.54.

**Comment by lfdversluis** [comment]
@whirm As what is this bug categorized? NO SUCH FILE or NAME NOT FOUND in procmon?

**Comment by whirm** [comment]
The .pyd is being found (look at the dump, it looks for it in several locations until it finds it)

**Comment by lfdversluis** [comment]
It is indeed found, but in `logfile.pml` near the end at `18:11:54:5794` it reports a `SUCCESS ` on finding `netifaces.pyd` and no more traces of netifaces come after that.

**Comment by whirm** [comment]
I only see events until `7:11:54.5465` ?

https://gyazo.com/8ef656db48f052ea4d229d706e1b1f42

**Comment by dukst** [comment]
@lfdversluis Good evening. All instructions for using ProcessMonitor are performed. Made two more attempts, send the logfile. Also sent two screenshots with the program's message about its collapse. I would be glad if it will help you in the work.
[Logfile.zip](https://github.com/Tribler/tribler/files/224261/Logfile.zip)

[Screenshots.zip](https://github.com/Tribler/tribler/files/224269/Screenshots.zip)

**Comment by lfdversluis** [comment]
Good evening to you too @dukst . Thanks a lot for your effort in helping track down this bug! I am sure that we will find it with your help. I will investigate the log files soon.

**Comment by whirm** [comment]
@dukst while @lfdversluis does his thing, could you install VS2008 redist and see if Tribler starts after that?

https://www.microsoft.com/en-us/download/details.aspx?id=29

Thanks!

**Comment by lfdversluis** [comment]
Ok an update: It looks like we are shipping a wrong version of the Microsoft Visual C++ runtime. We are installing 2010 (MSVC100.dll) while using dependency walker on 6.5.1 only MSVCR90.dll shows up as dependency, indicating that we need to ship the 2008 version. @dukst If you could please verify installing the 2008 C++ runtime @whirm linked works, then I will update it and this bug should be fixed :+1:

**Comment by dukst** [comment]
@whirm @lfdversluis MC VC++ 2008 Redistributable x86 9.0. 30729. 40148 is already on computer. Also MS VC++2005 and MC VC++2010. Do you recommend to reinstall the 2008 version?

**Comment by lfdversluis** [comment]
Hi @dukst Thanks for your reply :+1:  The regular version of tribler on https://www.tribler.org should work with the MS VC++ 2008 + 2010 redistributables. You could try reinstalling (or repairing), but if this doesn't work then something else is missing :(. 

If you are up for it, you could do the following:

1. Download [Dependency walker](http://www.dependencywalker.com/). (it's only ~500kb luckily :D)
2. Open dependency walker and open/load `netifaces.pyd` in the program. `netifaces.pyd` can be found in `C:\Program Files (x86)\Tribler` (or where you've installed Tribler).
3. Now you should see something like [this screen](https://gyazo.com/c2699ee2a1e7430b22475a161c5b62cf).
4. Make sure everything in the top left window is collapsed except for the `netifaces.pyd`, like [this](https://gyazo.com/26cb1e09178715e1dfb2e3b2ac0666c9) - **What does this show for you?**
5. In the bottom screen click on "module" to sort them by name. Scroll down a bit until you reach the "MSVC" section, you should get something like [this](https://gyazo.com/2c65b1724d9f21ccc0dbcfe37cfd1085) - **What do you see here?**

if you can provide us with screenshots for example of your output then it would help us a lot in seeing if it can find `MSVCR90.dll` (which we suspected was missing) on your machine.

Thanks for your help & replies, it really helps us tracking this issue!

**Comment by lfdversluis** [comment]
Also, @dukst, if you start up tribler having installed al the distributables, do you still get the line `File "Tribler\dispersy\dispersy.pyo", line 49, in`?

**Comment by dukst** [comment]
@lfdversluis Send screenshots of Dependency walker. Thank you for the introduction to such an interesting program! I'm sorry that I'm not a programmer and can't read all the information myself! :)

[Screenshot_Dependancy_Walker.zip](https://github.com/Tribler/tribler/files/229838/Screenshot_Dependancy_Walker.zip)

**Comment by lfdversluis** [comment]
No problem @dukst I am glad you are enthusiastic towards new programs. When I first used Dependency walker I amazed too :D 

Thanks for your screenshots! I will take a look at them later this afternoon.

**Comment by dukst** [comment]
@lfdversluis Line 49:
Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 183, in __init__
  File "Tribler\Core\Session.pyo", line 419, in start
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 152, in register
  File "Tribler\dispersy\dispersy.pyo", line 49, in <module>
Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 1067, in run
  File "Tribler\Main\tribler_main.pyo", line 306, in __init__
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
  File "Tribler\Main\tribler_main.pyo", line 876, in onError
  File "traceback.pyo", line 233, in print_exc
  File "traceback.pyo", line 128, in print_exception
  File "traceback.pyo", line 13, in _print
  File "C:\Python27\x86\lib\site-packages\py2exe\boot_common.py", line 74, in write
  File "encodings\utf_8.pyo", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xcf in position 30: invalid continuation byte
The reactor was not clean after stopping:
>     <DelayedCall 0x45e9b20 [10.3270001411s] called=0 cancelled=0 LoopingCall<15>(VoteCastDBHandler._flush_to_database, *(), **{})()>
>     <DelayedCall 0x450e6e8 [115.296000004s] called=0 cancelled=0 LoopingCall<120>(LevelDbStore.flush, *(), **{})()>
>     <DelayedCall 0x450e710 [114.980999947s] called=0 cancelled=0 LoopingCall<120>(LevelDbStore.flush, *(), **{})()>
>     <DelayedCall 0x45e9dc8 [295.328000069s] called=0 cancelled=0 LoopingCall<300>(update_nr_torrents, *(), **{})()>

**Comment by lfdversluis** [comment]
Hi @dukst. I forgot that you cannot run the normal version of tribler (yet) because of the unicode bug we have fixed earlier by upgrading py2exe. So the stack trace you just posted is (naturally) identical to the first.

From your screenshots I can conclude that it finds MSVCR90.dll which means your C++ 2008 redistributable can be found. This means another .dll file that is required cannot be found. 

Would you be able to sort the bottom area by icon (click on the area left of "module") and screenshot all the items that have a yellow "?" in front of it? This indicates a [Missing module.](http://www.dependencywalker.com/help/html/hidr_module_list_view.htm). 

I will then go through that list and hopefully spot something that should be there but is not. (note: a lot of items will have this yellow "?" in front of them, many of them will not be relevant).

Sorry for the troubles!

**Comment by lfdversluis** [comment]
@dukst I just learned from @whirm that you can save the dependency walker report by going to `file > save as`. Could you sent me your dependency walker report? Then I can have a look and hopefully find the bugger :D

**Comment by dukst** [comment]
@lfdversluis I think the error is not in tribler, a bug in windows vista on my computer. I would not like to University Delft distracted from the important things in looking for errors in vista and repair my computer :) I set tribler on my other computer with windows 7, works without problems. But, of course, if the idea is to help find a bug in tribler, then I'm happy to help. In the archive report of Dependency Walker
 in different formats and a screenshot of the MSVC section.
[DependencyWalker.zip](https://github.com/Tribler/tribler/files/234732/DependencyWalker.zip)

**Comment by lfdversluis** [comment]
I went trough the trace: three missing dlls `NTDLL.dll`, `SHLWAPI.dll` and `IEFRAME.dll`. None of them seem really relevant. NTDLL can be related to a graphic driver update > http://answers.microsoft.com/en-us/windows/forum/windows_7-windows_programs/programs-close-faulting-module-ntdlldll/54aaaec5-2b53-4e9f-b9a7-b7889a1cd4b6?auth=1.

The SHLWAPI and IEFRAME are related to IE explorer apparently: https://msdn.microsoft.com/nl-nl/library/windows/desktop/bb776779%28v=vs.85%29.aspx

Also shlwapi is "The tables in this document list wrapper functions from Shlwapi.dll that provide limited Unicode functionality to Windows 95, Windows 98, and Windows Millennium Edition (Windows Me)." : https://msdn.microsoft.com/en-us/library/windows/desktop/bb759845%28v=vs.85%29.aspx

So it looks like it is not something we can fix from our side. @whirm thoughts?

**Comment by whirm** [comment]
Yes, I'm afraid there's not much more we can do. I'll close this.

@dukst thanks for all the help figuring that one out!
