### ISSUE TITLE
List items cannot be selected very well on OS X using wx3

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2048]
In the wx3 GUI on OS X, list items are not always selectable. I suspect that the label is eating the click event instead of the list row.

**Comment by NielsZeilemaker** [comment]
Have a look at https://github.com/Tribler/tribler/blob/devel/Tribler/Main/vwxGUI/list_body.py#L208 that's our recursive mouse event binder. Maybe for wx3 you need to change/update it.
