### ISSUE TITLE
Why do you have checksum sha512 or better gpg .sig for downloads?

### ISSUE THREAD

**Issue by merlinnusr** [Tribler/tribler#2053]
Check the situations with transmission 
[TRANSMISSION ISSUE](https://www.transmissionbt.com/ )
this guy have a malware in their software . 
This situation it's possible in **Tribler **.

**Comment by whirm** [comment]
I don't understand your statement. Do you mean we could get hacked and malware could be embedded in our packages? How would moving from SHA256 to SHA512 for the signed hashes would help with that?

**Comment by merlinnusr** [comment]
You can distribuit a public key and sig a tribler download in a case of hacking the users can verify the checksums of .sig package Or you can publish a Sha*.txt.sig with checksums and this will be authentified with GPG key. is irresponsible only have packages without verification

**Comment by merlinnusr** [comment]
If you could have a checksum of the dmg binary, it would have prevented the spread of malware

**Comment by whirm** [comment]
We've been had signed checksum files for a few releases already.

https://github.com/Tribler/tribler/releases/download/v6.5.1/SHA256.txt.asc 
https://github.com/Tribler/tribler/releases/download/v6.5.1/SHA1.txt.

**Comment by merlinnusr** [comment]
Im glad to hear that ,but why is not public in main page.

**Comment by whirm** [comment]
@merlinnusr good point, I'll update the issue title for that and get it fixed soon.
