### ISSUE TITLE
Windows 10 installation: error running after installation

### ISSUE THREAD

**Issue by Koris** [Tribler/tribler#2056]
After installing Tribler, I get an error 'Ordinal not found' when I effectively want to start it.

- [ x ] I have read CONTRIBUTING.md

- [ x ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
6.5.1

##### Operating system and version: #####
Windows 10

##### Expected behavior: #####
Up running

##### Actual behavior: #####
Error : the ordinal 1 could not be located in the dynamic link library C:\Program Files (x86)\Tribler\IPHLPAPI.dll

##### Steps to reproduce the behavior: #####
Install and run Tribler

##### Relevant log file output: #####

Traceback (most recent call last):
  File "tribler_exe.py", line 99, in <module>
  File "Tribler\Main\tribler.pyo", line 47, in <module>
    
  File "Tribler\Core\Utilities\twisted_thread.pyo", line 8, in <module>
    
  File "twisted\internet\reactor.pyo", line 39, in <module>
    
  File "twisted\internet\selectreactor.pyo", line 200, in install
    
  File "twisted\internet\selectreactor.pyo", line 74, in __init__
    
  File "twisted\internet\base.pyo", line 498, in __init__
    
  File "twisted\internet\posixbase.pyo", line 289, in installWaker
    
  File "twisted\internet\posixbase.pyo", line 79, in __init__
    
  File "socket.pyo", line 191, in __init__
    
socket.error: [Errno 10106] The requested service provider could not be loaded or initialized

**Comment by whirm** [comment]
Thanks for the report!

**Comment by lfdversluis** [comment]
@Koris Could you try to replace this dll with the `IPHLPAPI.dll` in C:/Windows/System32`. Also check your network driver is up to date.

**Comment by Koris** [comment]
I have copied the dll and it works now! Thanks!

**Comment by lfdversluis** [comment]
@Koris Great! Feel free to close the issue :+1:

**Comment by whirm** [comment]
I don't think this can be considered fixed.

@lfdversluis is that DLL shipped in windows by default?

**Comment by lfdversluis** [comment]
@whirm yes it is default in the windows32 folder

**Comment by whirm** [comment]
so why are we shipping it?

**Comment by lfdversluis** [comment]
@whirm Good question. First time I've seen this error being reported and had to search a bit to find it was default in win32

**Comment by lfdversluis** [comment]
[py2exe has some criteria](http://www.py2exe.org/index.cgi/OverridingCriteraForIncludingDlls) as what it copies and what not. I have included now this dll and some others in the dll_exclude list and am running a test build on jenkins which I'll install on proxmox 144

**Comment by whirm** [comment]
@lfdversluis nice! Maybe we should check if newer py2exe alternatives are smarter about this stuff...

**Comment by lfdversluis** [comment]
@whirm We can certainly add that on the todo list, py2exe has not been updated in a long time. Most likely the project has stopped.

**Comment by devos50** [comment]
Yeah, py2exe is not developed anymore.

**Comment by whirm** [comment]
@lfdversluis maybe we could sync it to the new GUI release.

**Comment by devos50** [comment]
@whirm yeah, we probably need to do some tweaking of the builders when we are going to bundle Qt.

**Comment by lfdversluis** [comment]
@whirm Probably. We should look for a good alternative from time to time.

**Comment by devos50** [comment]
I vote for [pyinstaller](http://www.pyinstaller.org) 💃 . From the website:

> ... As an example, libraries like PyQt, Django or matplotlib are fully supported

**Comment by lfdversluis** [comment]
https://github.com/pyinstaller/pyinstaller Looks like a really alive and well maintained project. PyQT support is a bonus. Looks like we found a good replacement already

**Comment by lfdversluis** [comment]
@whirm can you close this one?
