### ISSUE TITLE
select all with ctrl-a

### ISSUE THREAD

**Issue by adamjimenez** [Tribler/tribler#2061]
feature request: press ctrl-a on downloads view to select all.

**Comment by lfdversluis** [comment]
@adamjimenez This will most likely not be in the upcomming alpha of 6.6. @devos50 do you think this is a nice addition for the new gui? I wonder if more users would appreciate this feature :grey_question:

**Comment by adamjimenez** [comment]
It seems like a natural interaction for me and I end up shift-clicking to select which is a little more awkward.

**Comment by lfdversluis** [comment]
@adamjimenez It could very well be. I wonder if there are more people who find this instinctive and would like this feature implemented. Also, I cannot assign labels to issues, so it will probably tagged later on by another tribler team member.

**Comment by devos50** [comment]
@lfdversluis @adamjimenez I think it's not that hard to implement in the upcoming alpha actually. I will to implement it tomorrow. Whether it is suitable for the new GUI depends on whether and how we are going to display downloads (should discuss this with @whirm and @synctext).

**Comment by synctext** [comment]
OK!  tomorrow late afternoon I have a small slot left to discuss open issues

**Comment by devos50** [comment]
@adamjimenez I implemented this feature in #2047 :)

**Comment by adamjimenez** [comment]
Thank you, that was quick. Great project.
