### ISSUE TITLE
circuits_needed dict should be cleaned up when there aren't any more downloads

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2068]
Added a magnet link and selected to download anon, removed the download but my terminal kept spamming lines `ERROR   1459763994.46 tunnel_community:534   creating circuit 844298149 of 3 hops. First hop: <ip>`. Looks like it keeps trying to build circuits?

**Comment by egbertbouman** [comment]
No need to investigate this: it doesn't :P

The ```TunnelCommunity``` keeps a dict (called ```circuits_needed```), which specifies how many circuits we need for each #hops. Values from this dict are never removed. Perhaps it's a good idea to empty this dict when the are no more downloads.

**Comment by lfdversluis** [comment]
@egbertbouman Ah that explains, thanks! Yeah that would be a good idea as we are trying to create circuits for non-existant downloads now :confused:

**Comment by qstokkink** [comment]
Alright, the current execution order is as follows:
 1. LibtorrentDownloadImpl is started and calls TunnelCommunity.build_tunnels() with its required hop count.
 2. TunnelCommunity then tries to create and maintain a pool of settings.max_circuits circuits.
 3. Once settings.min_circuits are READY, the download starts.

Now what would need to be added is:
 1. Some LibtorrentDownloadImpl is removed (not just stopped) and signals the TunnelCommunity that it no longer needs x hops.
 2. Either by means of checking all running downloads (eww) or some internal counter derived from build_tunnels() (:+1:) the TunnelCommunity then decides to keep the pool for other downloads or remove its circuits for that hop count.

**Comment by devos50** [comment]
@qstokkink I have this now: https://github.com/Tribler/tribler/pull/2701/commits/f39d26401c0d2941c8e70f83c256f4ac543fa279

**Comment by qstokkink** [comment]
@devos50 That will only do something when ALL downloads have been removed (anon, non-anon, different hop counts) and will only remove circuits of one particular hop count (granted, I don't think we mix hop counts at the moment, but this is not future proof).

So yeah, it is an improvement if you have Tribler running without any downloads, but I would suggest expanding your functionality a little bit more (see my previous comment). I'd try to cover, at least, when the amount of anon downloads reaches 0 (regardless of hop count) and not simply all downloads.

**Comment by devos50** [comment]
@qstokkink something like this? https://github.com/Tribler/tribler/pull/2701/commits/d7aa269fd3f22ed36a773dab9b3204f813e4b91d

**Comment by qstokkink** [comment]
@devos50 perfect 😄
