### ISSUE TITLE
If you're doing a new graphical user interface also, might this time you use a tool kit like qt?

### ISSUE THREAD

**Issue by brandc** [Tribler/tribler#2073]
If you're actually doing a new graphical interface and I'm not misunderstanding. I think wxgtk is holding this project with the minute and complex rendering errors that you get with it.

**Comment by devos50** [comment]
@brandc thank you for your suggestion. Actually, the new GUI is created in qt using PyQT and the qt designer. You can check it out here: https://github.com/devos50/TriblerGUI. Feedback is very welcome :+1:

**Comment by brandc** [comment]
Thanks for the fast response, I look forward to the new qt interface
