### ISSUE TITLE
Tribler/readme.txt should be removed

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#2074]
This readme is 6 years old and I don't think it contains any relevant information anymore.

https://github.com/Tribler/tribler/blob/devel/Tribler/readme.txt

**Comment by devos50** [comment]
@whirm I totally agree! Want me to open a PR for that?

**Comment by devos50** [comment]
@whirm can you assign @lfdversluis to this one (PR is open already)?

**Comment by whirm** [comment]
Oops
