### ISSUE TITLE
Idea: clean the reactor after every tests to prevent cascading error

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2075]
@devos50 and I were discussing the current situation with the tests and thought of the following. Perform the check if the reactor is dirty, if it is print all the stuff like we do now. But in addition **clean** the the reactor so that the next tests won't show the dirty reactor issue if it doesn't leave a dirty reactor behind.
This keeps the overview of which test is the culprit (well it is the first that has this issue obviously) and keeps your local terminal more clean when running tests locally.

There is no real downside to this as the PR tester will fail anyway with the first occurrence.

Thoughts?

**Comment by whirm** [comment]
Sounds good. We should also check for TCP/UDP listeners.

**Comment by lfdversluis** [comment]
@whirm Those are already present right? I get "test left listening port on <port> behind". Very useful.

**Comment by whirm** [comment]
oh, true, @devos50 implemented that already :D
