### ISSUE TITLE
Purpose of channelcast_supporter.py and search_supporter.py

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2076]
Can anyone explain the purpose of `channelcast_supporter.py` and `search_supporter.py `? It seems to enter a `SearchCommunity`/`ChannelcastCommunity`. Are we actually using these scripts?

**Comment by whirm** [comment]
# used to 'support' .torrent files dissemination of different channels.

The first one is a headless booster for channel communities.

The second one answers incoming search with results from the megacache.

**Comment by devos50** [comment]
Thanks for the explanation. Maybe it's better to move these scripts to a separate directory (i.e. a `tools` or `scripts` directory)?

**Comment by whirm** [comment]
I would convert those to twisted plugins, like the tunnel helper, the tracker, etc.

**Comment by synctext** [comment]
Never used anymore.. Could be archived

**Comment by whirm** [comment]
If the headless Tribler allows you to disable enough stuff, maybe these two scripts would not make much sense anymore (they are way lighter than running a full blown Tribler ATM)
