### ISSUE TITLE
Exception when running tests on Windows

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2081]
When running tests on the win64 builder, sometimes the following error is raised:

```
======================================================================
ERROR: test_watchdog_print_all_stacks (Tribler.Test.Core.test_instrumentation.TriblerCoreTestWatchDog)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Test\test_as_server.py", line 71, in check
    result = fun(*argv, **kwargs)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Test\Core\test_instrumentation.py", line 110, in test_watchdog_print_all_stacks
    self.watchdog.print_all_stacks()
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Core\Utilities\instrumentation.py", line 175, in print_all_stacks
    self.printe("\n### ThreadID: %s Thread name: %s" % (thread_id, thread_names[thread_id]))
KeyError: 868
```

During the past months, I've seen the same error once or twice, also on other platforms. It seems like the threads returned by `threading.enumerate()` is not always the same as the threads given by `sys._current_frames().items()`.

@whirm Is it an idea to add a check to see whether the `thread_id` key exists in `thread_names`? If it doesn't, at least the tests won't fail.

**Comment by whirm** [comment]
I guess a new thread is being spawned after the names are collected?

Maybe we could make it a function that fetches the name from the output of enumerate() instead of generating a dict, it will be slower but it's not like we care about performance there :)

**Comment by devos50** [comment]
Yeah that might explain this behavior. Shall I add this to my unit test improvement PR?

**Comment by whirm** [comment]
Go ahead

**Comment by devos50** [comment]
@whirm see https://github.com/Tribler/tribler/pull/2046/commits/6bbada0459a3c6817b00f9482ef3aa9c6cf5fc28 :)

**Comment by whirm** [comment]
Looks great!
