### ISSUE TITLE
The PR tester should run the tests on the lowest version of Ubuntu we support too

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#2082]
We could create a container for it. 

This way I could stop asking if people has tested changes against an old libtorrent, etc. :)

**Comment by devos50** [comment]
@whirm what version of libtorrent do we have installed on bbq?

**Comment by whirm** [comment]
1.0.7-1

**Comment by devos50** [comment]
What about installing an older version of libtorrent on BBQ?

**Comment by whirm** [comment]
that would mean downgrading bbq's Debian or having to build it by hand

**Comment by devos50** [comment]
I don't think this is relevant anymore.
