### ISSUE TITLE
Show grid button doesn't work 

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2084]
When testing a new build I and @devos50 observed that @devos50's new show grid button is not doing anything on windows (64 bit).

**Comment by lfdversluis** [comment]
@whirm Can you assign @devos50 to this?

**Comment by devos50** [comment]
I just tested on Windows 32- and 64-bit, both from the installer and from source (latest commit on `devel` branch). In all tests, the grid icon seems to work correctly i.e. it shows the grid cells when clicked and the button itself turns to orange. @lfdversluis did you test it on a specific proxmox machine?

**Comment by lfdversluis** [comment]
@devos50 Yes, on proxmox 144

**Comment by devos50** [comment]
Ah I don't have acces to that machine. @whirm can you give me access to it?

**Comment by whirm** [comment]
done

**Comment by devos50** [comment]
I just tested it on proxmox 144, the button is working perfectly. Maybe you built an older version? I remember that I made a change to the action being triggered of the button a while ago.

**Comment by lfdversluis** [comment]
@devos50 If it wasn't merged at that time, maybe it's possible. If you confirmed it is working on that machine now using the latest devel, then i'll close this one.

**Comment by lfdversluis** [comment]
Confirmed it is working. So this one is closing.
