### ISSUE TITLE
Downloads are not cleaned properly

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2089]
While investigating why the download status is broken, I found that while having `0` downloads, I get the following lines:

```
length of magnetlist: 0
self.torrent.magnetstatus: None
self.torrent.magnetstatus: None
```

Where the `self.torrent.magnetstatus: None` is in the `UpdateStatus` function in the `list_details.py` file. There should not be a function call as there are no downloads present.

**Comment by whirm** [comment]
Good find
