### ISSUE TITLE
Pylint checker configuration discussion

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2092]
The new pylint checker is working now but it needs some tweaking regarding the configuration it accepts. Let's use this issue to discuss which options should be enabled and disabled.

_My opinion:_
I would like to disable the following checks:
- `C0103: (invalid-name)`: sometimes, we override methods from frameworks that do not confirm to this (i.e. the `render_GET` method is an invalid name according to Pylint).
- `W0613: (unused-argument)`: often, we cannot use a passed if we are overriding a method.

I'm also not sure whether is is necessary to write a docstring for every method. I think this might be unnecessary so I suggest to also disable `C0111 (missing-docstring)`. We have many small methods which are self-explanatory and not necessarily need comments in my opinion. Unfortunately, there is no easy way to distinguish an easy method from a complex method.

**Comment by whirm** [comment]
**To everyone involved:** have a look at the `pylintrc` config file before writing anything to get an idea of the options we have.

* C0103: have in mind that we can set our own regexps for that and that individual violations can be whitelisted.

* W0613: We can still ignore the argument with `_`

* C0111: can be tuned with:
```
# Minimum line length for functions/classes that require docstrings, shorter
# ones are exempt.
docstring-min-length=-1
```

**Comment by lfdversluis** [comment]
I like the docstring enforcement as I am now having a blast of the past in the negative sense. The current logic when adding magnet links is already amazing, having no documentation and functions like [these](https://github.com/Tribler/tribler/blob/devel/Tribler/Main/Utility/GuiDBTuples.py#L215) hurt my brain.

**Comment by lfdversluis** [comment]
Can we also ignore certain issues like missing docstring in tests? Makes no sense to add a docstring for every def test_*

**Comment by whirm** [comment]
There's many tests that aren't really descriptive about what they are supposed to be testing.

**Comment by lfdversluis** [comment]
I agree, but isn't that a fault of the tests themselves? Unit tests should be as small and as descriptive as possible.

**Comment by devos50** [comment]
Sometimes small unit tests are not possible. It can be quite a challenge to setup all the required objects and to invoke the right methods at the right time, leading to large unit tests. So in this case, I would say we need indeed a docstring to explain what we are exactly testing.

**Comment by whirm** [comment]
Sometimes even small tests have misleading/ambiguous names or use magic numbers, compare values in tuples without any explanation, etc. Many of these could be improved by using a better function name or constants. Others really need a docstring.

**Comment by lfdversluis** [comment]
Yup, hence my preferably statement :D

**Comment by devos50** [comment]
I think we have a decent and mature Pylint configuration right now so I will close this issue.
