### ISSUE TITLE
Proposal: unit tests that are always running on a machine

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2094]
I would like to propose to continuously run unit tests on a machine. We have many race conditions/dirty reactor issues that are occurring in a very small fraction of the test runs. By running the unit tests many times and by automatically extracting and analysing Python stack traces, we can see which issues are occurring frequently.

We can either do this in Jenkins or by using a simple bash script. We can create a dedicated website that shows stack traces that showed up and where we can read the (analysed) logs that are written by the tests.

Ideas/comments on this?

**Comment by whirm** [comment]
I pretty sure that after the GUI separation, many of those will be gone. 

What do you say we delay the discussion until after this has been done?

Running the tests non-stop is easy, what's not so easy is fetching the stack traces from the xml reports, the logs..., seeing which ones are identical and merging them toghether, etc. Would be cool to have, but I think everyone has enough on his plate ATM.

**Comment by devos50** [comment]
I don't really think this is necessary anymore since the unit tests are quite stable now and I believe most of the race conditions have been fixed. I will close this issue, however, if there is interest in this feature, let me know.
