### ISSUE TITLE
Tunnel community keeps consuming more and more memory

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#2102]
Quote from @devos50:

```
Also, relay_session_keys in TunnelCommunity becomes pretty big after a while. Maybe keys for a circuit not properly cleaned up?
```

(from: https://github.com/Tribler/tribler/issues/2000#issuecomment-210787710)

**Comment by whirm** [comment]
Partially dupe (see: https://github.com/Tribler/tribler/issues/2068)

**Comment by whirm** [comment]
Edited to only leave the non-dupe part of the issue

**Comment by qstokkink** [comment]
This seems to be fixed now.
