### ISSUE TITLE
Tribler avatar (mugshot) is not working

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2104]
When working on the new GUI, I was looking for a way to fetch the avatar of other users (as they are displayed in comments). However, there is no way and mechanism available to fetch avatars from other users. Also, when setting your own avatar, they are not shared in the network!

For the comments, a default placeholder image is displayed but I feel this should be fixed, especially if we want to make Tribler more graphically appealing. I think this is similar to the work of adding thumbnails to torrents/channels.

**Comment by lfdversluis** [comment]
Do they resemble a use case? Do we want to? Have this worked in the past actually? So many questions...

**Comment by whirm** [comment]
I wouldn't give much priority to this. Just leave that stuff out of the first version of the GUI unless @synctext has something else to say about it.

**Comment by synctext** [comment]
old code, should be removed. 
back from our decentral Facebook days..
