### ISSUE TITLE
Shipping visual C++ and C redistributables

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2107]
I have investigated which libraries need which runtimes using dependency walker on Windows (64 bit), the results:

| Library   |      Dependency      |
|----------|:-------------:|
| Python | MSVCR90.dll |
| M2Crypto |  MSVCR100.dll |
| LevelDB |    MSVCR110.dll   |
| LibTorrent | MSVCP110.dll & MSVCR110.dll |
| netifaces | MSVCR100.dll |
| apsw | MSCR90.dll |

We can either install all the three (actually four) runtimes or recompile the ones of 100 to make use of 110 (2012) ?

**Comment by whirm** [comment]
I'd recompile. But lets first fix the 6.5.X builder so we can do the last 6.5 release and move forward.

**Comment by lfdversluis** [comment]
@whirm I do not have access to the old builder, can you add the `Visual C++ Redistributable for Visual Studio 2012`, `Visual C++ Redistributable for Visual Studio 2010` and `Visual C++ Redistributable for Visual Studio 2008` (32 bit I guess in the old builder) to the build folder? And add the following lines to the .nsi file:
```
; Install MSVCR 2008, 2010, 2012
 SetOutPath "$INSTDIR"
 File vc_redist_90.exe
 ExecWait "$INSTDIR\vc_redist_90.exe /q /norestart"
 File vc_redist_100.exe
 ExecWait "$INSTDIR\vc_redist_100.exe /q /norestart"
 File vc_redist_110.exe
 ExecWait "$INSTDIR\vc_redist_110.exe /q /norestart"
```

That should run all three of them.

**Comment by lfdversluis** [comment]
edit: I have made a PR and installed the redists on the old builder.
