### ISSUE TITLE
Installer runs twice

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2110]
While running the new builder installer I noticed that Tribler (and possibly also the old installer) runs the installation and uninstallation section twice. This is confusing and has to be investigated :)

**Comment by lfdversluis** [comment]
@whirm Ok I just tested the installer of 6.5.1 with install and uninstall and that one does not (luckily) run twice. It seems my tribler is running check runs twice. So the blocker tag can be removed. Issue is still for 6.6

**Comment by whirm** [comment]
It still is blocker, we can't ship a 6.6 with an installer that runs twice :)

**Comment by lfdversluis** [comment]
Ah I was thinking blocker was for the current release, no idea why because the milestone clearly says 6.6. Sorry :p

**Comment by lfdversluis** [comment]
@whirm Can you assign this to me?
