### ISSUE TITLE
Can't change anonymity mode after the download has already started

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2111]
#### Please, fill all relevant items:
- [glanced though] I have read CONTRIBUTING.md
- [no] I have tried with the latest pre-release version and I still can reproduce the issue.
##### Tribler version/branch+revision:

v6.5.1 built from git
##### Operating system and version:

Linux Debian (32bit on 64-bit)
##### Expected behavior:

There is a menu item that allows editing anonymity settings (number of hops, upload-only, etc.) after the download has already started.

The menu item can be somewhere near "Change download location..." or near "Bandwidth allocation->".
##### Actual behavior:

I see no such element in GUI. There only a read-only "Anonymous:" column in the table.

**Comment by whirm** [comment]
Thanks!

**Comment by khonkhortisan** [comment]
https://github.com/Tribler/tribler/issues/1013

**Comment by devos50** [comment]
Duplicate instead, will close this one.
