### ISSUE TITLE
Tribler fills RAM to MAX size

### ISSUE THREAD

**Issue by MESWEB** [Tribler/tribler#2123]
#### Please, fill all relevant items: ####

- [ ] I have read CONTRIBUTING.md

##### Tribler version/branch+revision: #####
6.5.1 but in tab bar is 6.2.1
##### Operating system and version: #####
Ubuntu 14.04
##### Expected behavior: #####
Tribler filling RAM to max size when starts
##### Actual behavior: #####
Tribler frozen for about a 5 minutes and fill RAM to MAX size (My comp have 8GB) by python3 process.
##### Relevant log file output: #####
No related was printed to console, although Tribler constantly prints backtraces about NoneType or about dropped packets even during normal operation.

**Comment by whirm** [comment]
Tribler can't run on python3.

re the title bar showing 6.2.1. Are you running a version from git or the official package?

Could you start Tribler and paste the output of `ps aux | grep python` while it's running and the output of `cat $(ls -1atr /tmp/*-tribler-*log | tail -1)` after closing Tribler?

**Comment by MESWEB** [comment]
No U r wrong. When I start Tribler then python process is starting (python-O Tribler/Main/tribler.py) and this process going to max of RAM and next freeze computer. Yes I have downloaded from official site and file have sign 6.5.1 but after installing I see on tab 6.2.1. Check screenshot I'm make it for U.
![zrzut ekranu z 2016-04-22 12 50 24](https://cloud.githubusercontent.com/assets/2931024/14739786/36ba9f86-088a-11e6-9de4-d1365ab65e29.png)

**Comment by whirm** [comment]
Something is wrong with the Tribler copy you are running on this screenshot.

How did you obtain the source code? (provide step by step instructions of what you did) 

Do you have more copies of Tribler installed?

**Comment by MESWEB** [comment]
I just downloaded this copy from official website, next I just install and few day later I'm download firs two torrents. So few days ago I want download movie ~8GB and I see this issue. Now I was try delete torrent 8GB but nothing changed still filling RAM. No I have only one version of Tribler.

**Comment by whirm** [comment]
The website provided link points to: https://github.com/Tribler/tribler/releases/download/v6.5.1/Tribler-v6.5.1.tar.xz

Which SHA1 is: dc6246f89a6350b0fb400c66898b0885b7ec2f81

If I download, unpack and execute `cd tribler && ./tribler.sh` I get a working Tribler showing the right version (6.5.1) on the title bar. 

Is that exactly what you did?

**Comment by MESWEB** [comment]
No I have file .deb tribler_6.5.1_all.deb (1404932 bits) from [https://github.com/Tribler/tribler/releases/download/v6.5.1/tribler_6.5.1_all.deb](url)

**Comment by whirm** [comment]
I've downloaded/installed the .deb and ran `tribler` on a terminal and it works fine:

![2016-04-26-145443_3120x1920_scrot](https://cloud.githubusercontent.com/assets/529494/14820755/4307c78c-0bc8-11e6-98b4-5018bfdb40f6.png)

Can you please describe what you are doing _step by step_?

**Comment by MESWEB** [comment]
Sorry my mistake. After reinstalling Tribler I found reason of my error. Tribler version 6.2.0 is a default in Ubuntu app center when I try install new version I have error: libsodium13. What I should to do? I have installed already libsodium.

**Comment by whirm** [comment]
@MESWEB what version of libsodium do you have installed?

**Comment by MESWEB** [comment]
Latest libsodium-1.0.10.tar.gz from - [https://download.libsodium.org/libsodium/releases/](url)

**Comment by whirm** [comment]
@MESWEB why aren't you installing the version provided by Ubuntu?

**Comment by MESWEB** [comment]
How?

**Comment by whirm** [comment]
If you install the tribler .deb, libsodium13 should be installed as a dependency.

1.0.10 is libsodium18, which is not supported by tribler 6.5.1, you either need to:

 a)  Wait for 6.5.2 which should be out next week at most.

 b) Install a developer build (which is not validated)  from https://jenkins.tribler.org/job/Build_Tribler_next/10/ 

 c) Edit `/usr/lib/python2.7/dist-packages/Tribler/dispersy/libnacl/libnacl/__init__.py` as root and modify the line that looks like:

```python
__SONAMES = (13, 10, 5, 4)
```

so it looks like:

```python
__SONAMES = (18, 13, 10, 5, 4)
```

**Comment by MESWEB** [comment]
Ok thanx. I'll wait for new version. Thanks for help.

**Comment by whirm** [comment]
You are welcome :)
