### ISSUE TITLE
We need to get rid of the sleeps on the tests and most of the ones on the code

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#2130]
In general it's a sign of broken/racy tests and they extend test execution time.

Quick grep reveals:
- [ ] Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py:            time.sleep(1)
- [ ]  Tribler/Core/Utilities/instrumentation.py:            sleep(0.2)
- [ ] Tribler/Core/Video/VideoPlayer.py:                time.sleep(1)
- [x] Tribler/Main/channelcast_supporter.py:    time.sleep(5)
- [ ] Tribler/Main/metadata-injector.py:        time.sleep(10)
- [ ] Tribler/Main/metadata-injector.py:    time.sleep(5)
- [ ] Tribler/Main/tribler_main.py:            sleep(0.1)
- [ ] Tribler/Main/tribler_main.py:                sleep(3)
- [ ] Tribler/Main/tribler_main.py:        sleep(5)
- [ ] Tribler/Test/API/test_seeding.py:            time.sleep(10)
- [ ] Tribler/Test/API/test_seeding.py:            time.sleep(0.1)
- [ ] Tribler/Test/API/test_seeding.py:        time.sleep(1)
- [ ] Tribler/Test/API/test_seeding.py:        time.sleep(5)
- [ ] Tribler/Test/API/test_seeding.py:        time.sleep(5)
- [ ] Tribler/Test/test_bartercast4_community.py:                sleep(1.0)
- [ ] Tribler/Test/test_bartercast4_community.py:            sleep(0.1)
- [ ] Tribler/Test/test_bartercast4_community.py:            sleep(10)
- [ ] Tribler/Test/test_remote_torrent_handler.py:            sleep(0.1)
- [ ] Tribler/Test/test_remote_torrent_handler.py:        sleep(1)
- [ ] Tribler/Test/test_remote_torrent_handler.py:            sleep(0.1)
- [ ] Tribler/Test/test_remote_torrent_handler.py:        sleep(1)
- [ ] Tribler/Test/Core/test_notifier.py:            time.sleep(0.01)
- [ ] Tribler/Test/test_as_server.py:            time.sleep(0.1)
- [ ] Tribler/Test/test_as_server.py:            time.sleep(1)
- [ ] Tribler/Test/test_as_server.py:        time.sleep(2)
- [ ] Tribler/Test/test_as_server.py:            time.sleep(1)
- [ ] Tribler/Test/test_as_server.py:                time.sleep(seconds)
- [ ] Tribler/Test/test_as_server.py:        time.sleep(1)
- [ ] Tribler/Test/test_multichain_community.py:        time.sleep(10 + 2)  # 10 seconds is the default timeout for a signature request in dispersy
- [ ] Tribler/Test/test_torrent_checking.py:        sleep(31)
- [ ] Tribler/Test/test_video_server.py:        time.sleep(5)
- [ ] Tribler/Test/test_video_server.py:        time.sleep(2)
- [ ] Tribler/Test/test_video_server.py:            time.sleep(1)

**Comment by devos50** [comment]
Many of the sleeps above are related to the startup process of Tribler (which I will refactor once the `devel` branch becomes free).

**Comment by lfdversluis** [comment]
Random idea. Once we get devel into next after 6.5.2. How about simply removing all of them (or one by one) and watch it burn, if any fires?
Then we know where stuff needs fixing with race conditions. Do note however that I am going to primary focus on the tunnels so I wont have my priorities on hunting race conditions. Unless of course the sleeps in the tunnels need refactoring. But we'll find that out.

**Comment by pimveldhuisen** [comment]
Note that the first 9 and the last 3 grep results are not test, but actual code, which doesn't really fit this issue. (It is arguably much, much worse though.)

**Comment by whirm** [comment]
Fixed :)

**Comment by devos50** [comment]
All sleeps besides the ones in the `VideoServer` are removed. The sleeps in `VideoServer` cause no harm since it's executed on a separate thread. Getting rid of these sleeps requires twistification of the video server which is a separate issue.

Note that there are many sleeps in Dispersy, however, they will be fixed when we make Dispersy asynchronous.
