### ISSUE TITLE
app-to-app communicator on Android

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2131]
Create a first app for automagic NAT puncturing and traversal on Android.

The app will connect to others which installed this app and try to establish a connection with them. This is the only functionality of this app: getting an UDP NAT puncture to others. Part of this functionality is discovering others and coordinating a puncture attempt. On this first screen of the app the currently discovered other app installs are shown. For each other user the status of the puncture is show in real-time. Builds upon the ideas of [this work](www.cs.ucr.edu/~zhiyunq/pub/sigcomm11_netpiculet.pdf).
![image](https://cloud.githubusercontent.com/assets/325224/14783647/5c7851be-0af1-11e6-8561-1942820933b1.png)

_Testing_ This app will be released on TUDelft Android account, source code on Github, and with Tweakers coverage we aim to obtain test users. 

_No-server-needed_ Only 1 app is needed, without any dedicated server software. TUDelft will provide two Nexus 6 test phones with two fixed wifi-based IPv4 numbers. These will run the dedicated app and serve as hard-coded servers running the client servers and facilitate peer discovery.

_PEX_ PEX builds on the no-server-needed part to discover others. Simply use the Peer Exchange message to decentralise the peer discovery. Use a simple PEX implementation. Only [implement the ut_pex message](http://svn.tribler.org/abc/branches/boudewijn/beps/bep_0034.rst) without the added and dropped extras.

_many ports_ One idea to evaluate is to open 60000 UDP listen ports from your app. This extreme approach would capture all incoming packets.

_puncturing_ Implement the puncture-request message to conduct the actual NAT traversal with the help of another user. [Essential approach](http://dispersy.readthedocs.org/en/devel/system_overview.html#peer-discovery) description, see section [4 for another description](http://www.ds.ewi.tudelft.nl/fileadmin/pds/reports/2013/PDS-2013-002.pdf)  of this, plus [IETF draft](https://tools.ietf.org/html/draft-ietf-ppsp-peer-protocol-00#section-3.7)

Starting point: https://github.com/MaStanford/AndroidSimpleNetworkInfo

Possible sprints (2 weeks each):
- [ ] Working app with 2 hard coded Android phones
- [ ] Implement scalable peer discovery
- [ ] Effective UDP puncture mechanism with green and red lights
- [ ] Test with 20+ test users, polish, Tweakers promo, and release on Google Play

**Comment by whirm** [comment]
Why does this have to be a standalone app instead of one based on @brussee's work?

**Comment by synctext** [comment]
@whirm Another student, first Java prototype.. :-)

**Comment by whirm** [comment]
yeah, but that will mean having to reimplement it from scratch in python, I think that will be a waste of effort. 

Isn't it better to directly implement the prototype feature on the existing codebase?

**Comment by synctext** [comment]
This project by design is isolated from the huge Tribler/Dispersy code base.

If it works this method cannot be easily be integrated into Dispersy. Sometimes you need 10 tries before it punctures on Android with 3G/4G carrier networks. Dispersy only tries stuff once and only once.

**Comment by synctext** [comment]
First running code: https://github.com/Jaapp-/app-to-app-communicator

**Comment by synctext** [comment]
Goals:
PEX operational with 1 PC emulated Phone, 2x android devices
Lookup local IPv4 and wifi/3G info plus include this as text field in PEX as info for overview screen of app.
Puncture-request message
ToastNotifier for each incoming UDP packet of a _new_ phone.

**Comment by synctext** [comment]
Detailed report on NAT puncturing: http://www.ds.ewi.tudelft.nl/reports/2010/PDS-2010-007.pdf

**Comment by synctext** [comment]
Public connectable App Port (Still TCP-only..)
![screenshot_20160523-113252](https://cloud.githubusercontent.com/assets/325224/15466541/74ab602e-20da-11e6-9e88-6976f03c4f1c.png)

**Comment by synctext** [comment]
Advanced feature: voting on external IPv4 https://github.com/Tribler/dispersy/blob/devel/dispersy.py#L738

**Comment by Jaapp-** [comment]
Tribler IP 
130.161.211.254

Use Datagram Socket instead of Socket
UDP puncture
Generate random peer-specific hash, send with each message to be able differentiate between data from peers
Don't establish a connection with self
Include carrier, more information, with messages
Save instance state, don't lose list on redraw.
Implement proper OnPause / OnStop
Use service instead of activity?

**Comment by synctext** [comment]
Algorithm for peer list:
 - continuously actively crawl the app-to-app overlay (start on app open)
 - Using PEX you obtain a list of peers to which this peer has an active connections.
 - You attempt to establish a connection, resulting in either a green or red status
 - [Puncture-request message](http://dispersy.readthedocs.io/en/devel/wire_protocol.html#dispersy-puncture-request) is used for NAT traversal
 - [identify carrier](https://developer.android.com/reference/android/net/NetworkInfo.html) and wireless technology used (3G/4G/wifi)
 - Bonus: determine roughly the IP address pool by repeatedly turning of data connectivity (3G/4G/wifi) and using the app to determine your assigned public IP number.

**Comment by synctext** [comment]
The walker is getting operational. No more Hello World or keyboard entry popup. Tighter GUI design:
![gui](https://cloud.githubusercontent.com/assets/325224/15888705/45db57c8-2d68-11e6-8c60-e442261a37b4.png)

**Comment by synctext** [comment]
Stability issues, GUI mistakes, but running!
![screenshot_20160616-144218](https://cloud.githubusercontent.com/assets/325224/16117105/afc4c55c-33d0-11e6-993a-35668f2b583d.png)

**Comment by synctext** [comment]
ToDo: permanent storage of the unique identifier. Overwrite Peer-List duplicates upon arrival, only keep last incoming packet of same hash.

**Comment by synctext** [comment]
Fixes and polish:
 - 5 Second real-time update
  - outgoing peers
  - WAN address (not WAN vote) + "local IP"
  - last ping to each peer
 - graceful handling of 4G to wifi switch.
 - permanent storage of the unique identifier. 
 - Overwrite Peer-List duplicates upon arrival, only keep last incoming packet of same hash.
 - stability....

**Comment by synctext** [comment]
@YourDaddyIsHere our progress from earlier this year

**Comment by synctext** [comment]
Good demo app, now project has finished
