### ISSUE TITLE
Reduce amount of vc redist we ship

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2133]
Currently we ship 2008, 2010 and 2012 of the C++ redistributables. Packages need to be recompiled to use either on or two versions. Currently the dependencies are as follows.

| Library   |      Dependency      |
|----------|:-------------:|
| Python | MSVCR90.dll |
| M2Crypto |  MSVCR100.dll |
| LevelDB |    MSVCR110.dll   |
| LibTorrent | MSVCP110.dll & MSVCR110.dll |
| netifaces | MSVCR100.dll |
| apsw | MSCR90.dll |

**Comment by devos50** [comment]
@lfdversluis the `netifaces` package appeared to be dependent on `MSVCR90.dll` on the 32-bit machine but not on the 64-bit machine so I recompiled it from source, installed it to the `site-packages` and tested it. So `netifaces` now depends only on `MSVCR90.dll`.

So if I manage to recompile `M2Crypto` with VS2012, we only have two dependencies left.

**Comment by devos50** [comment]
The `M2Crypto` on the 64-bit builder is now also dependent on `MSVCR90.dll`. I tested on Windows 10 and it seems to work. Can you test on windows 7 and 8? See https://jenkins.tribler.org/job/Build-Tribler_Win64/191/ for a builded version. After it works, please remove `vc_redist_100.exe` from the builders.

**Comment by lfdversluis** [comment]
@devos50 did you verify the packes with dependency walker?

**Comment by devos50** [comment]
@lfdversluis yes, see https://gyazo.com/3750b9733094e75abf25b6951f2cb1b6 and https://gyazo.com/cd954bd21d90187c0219f35c75d0dada

**Comment by lfdversluis** [comment]
Ok then i'll test the builds using the proxmoxes

**Comment by lfdversluis** [comment]
Works on win 8

**Comment by lfdversluis** [comment]
The reason I asked for dependency walker is that if it still tries to find msvc100.dll, it will find it because it is installed on my machine and the proxmoxes because of earlier installers being ran.

**Comment by lfdversluis** [comment]
@whirm I believe this one can be closed as #2168 was merged.
