### ISSUE TITLE
Version 6.5.1 stuck on installation; database never finishes updating

### ISSUE THREAD

**Issue by baldyj** [Tribler/tribler#2136]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.md Yes.
- [x] I have tried with the latest pre-release version and I still can reproduce the issue. ?

##### Expected behavior: #####
I was performing an upgrade and expected to be able to use Tribler.

##### Actual behavior: #####
The installation is stuck 

##### Steps to reproduce the behavior: #####
I've uninstalled the program and tried to reinstall.  I've restarted the computer numerous times.

##### Relevant log file output: #####

[triblerexelog.txt](https://github.com/Tribler/tribler/files/235921/triblerexelog.txt)

EDIT(@whirm): Fix formatting

**Comment by whirm** [comment]
From your log:

```CorruptError: CorruptError: database disk image is malformed```

Your sqlite database is corrupted. Did your system crash lately? Are your hard disks/filesystems/RAM healthy?

To fix that you will need to remove the corrupted databases so they get recreated:

Open `%APPDATA%\.Tribler` and delete the `sqlite` directory.

Let me know if Tribler works after doing this.

**Comment by baldyj** [comment]
Hi,

Sorry for the delay in responding.  Your fix worked!  It's up and running.
As for the health of my system, I think it's generallyn O.K.  The crash
probably occured while I was trying to update Tribler.

Anyway, thanks very much.

**Comment by whirm** [comment]
Glad to help!

I'll create an issue to add a check for this during startup.
