### ISSUE TITLE
Defining the e2e encryption problem, and are there any proposed solutions?

### ISSUE THREAD

**Issue by brandc** [Tribler/tribler#2140]
I see the demand for end to end crypto come up a lot in the issues, so I tried to write something on the topic in a similar way to a math proof:

Defining the problem:
>Strong cryptographic algorithms exist and work
>Even if a perfect cryptographic algorithm existed, it would fail without authentication.
>>How the point of encryption is violated without authentication (given the definition of authentication is knowing who you're talking to):
>>>even if what you say is encrypted, if you can't be sure who you're talking to, you also can't be sure if what you say is hidden, as is the definition of encryption.

Common solutions for the authentication problem and some thoughts (any currently proposed solutions specific for Tribler?):
>Traditional cental model of authentication:
>>Doesn't scale easily, and as history has shown takes one trusted signer to lose their private key to bring down the system's ability to reliably authenticate anything.
>>Revocation in the traditional cental model of authentication has proven to be difficult, as more central sources become trusted.
>>At some point someone will lose their private if the system is large enough and the ability to do so is possible.

>Ring of trust model:
>>Revocation is still a problem in this model; however, one lost private key only compromises a small subset of the system.
>>Has proven to be reliable, but is more difficult and has many similar issues to central model plus it's not as easy to use.
>>Being reasonably sure, as is in the ring of trust model, one can and usually gets a high grade of authentication.
>>>A possible solution to the lack of peers would be to have users sign each others keys at varying levels of trust and build a network outwards of trusted peers.

**Comment by synctext** [comment]
we use the Tor wire protocol. With their e2e handshake for hidden services. Our extension and modification remove the need for any central server.  
note: our code is far from as mature as their 13 years old codebase.
