### ISSUE TITLE
SingleInstanceChecker is not properly implemented

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#2148]
It even detects pylint processes as Tribler's.

It should be reimplemented by writing a `lock` file containing the current process PID to the state dir. This would eliminate false positives and several Tribler processes using different state dirs could coexist without need of disabling the single instance check.

Note that the current implementation makes some tests randomly fail when mistaking pylint for a Tribler process:

```
Tribler.Test.test_i2i_download.TestI2IDownload.test_i2i_running (from nosetests)
Failing for the past 1 build (Since Failed#960 )
Took 5.1 sec.
Error Message

Did not even create a session
-------------------- >> begin captured logging << --------------------
DEBUG   1461689740  test_as_server:TestI2IDownload:559  waiting for session instance
INFO    1461689740 SingleInstanceChecker:SingleInstanceChecker:38   Linux cmd returned 16651 pylint
16652 pylint
16659 pylint
16660 pylint
16661 pylint
16662 pylint
16663 pylint
16664 pylint
16665 pylint
16666 pylint
INFO    1461689740    tribler_main:Tribler.Main.tribler_main:1046 Client shutting down. Detected another instance.
INFO    1461689740    tribler_main:Tribler.Main.tribler_main:1066 Client shutting down. Sleeping for a few seconds to allow other threads to finish
--------------------- >> end captured logging << ---------------------
```

**Comment by devos50** [comment]
That's a bad implementation lol. I will try to refactor and reimplement it this weekend.

**Comment by whirm** [comment]
Great! 

Have in mind that twistd provides this feature and in the future we will have both the GUI and the core running at the same time.
