### ISSUE TITLE
Performance improvement: Move from json to ujson

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2155]
As we are and will make good use of json, a lot of performance can be gained if we use [ujson](https://github.com/esnme/ultrajson). It is significantly faster than the default library and it's quite the low hanging fruit.

I have check and they are both in the debian and ubuntu repositories available.
@whirm If we would like this, can you assign this to me?
@devos50 I think your new GUI and server/client model can also greatly benefit from this. Shall I PR on your PR with changes?

SO post on it and some people reporting faster times: http://stackoverflow.com/questions/706101/python-json-decoding-performance

edit: Not to mention it is a C library so we release the GIL too.

**Comment by devos50** [comment]
Looks good. I can image that this would be beneficial for very large JSON objects (i.e. querying all torrents in a specific channel). My next endpoint will be the fetching of the RSS feeds on a channel but after that, I want to create an endpoint to get all channels in Tribler (possibly with a limit parameter). This JSON object will be huge so I think that we can use this endpoint to get a better indication of the speedup.

Or if you want to work on it already, you can also use my [fake endpoint provider](https://github.com/devos50/testtriblerapi) (where you can already fetch all channels/torrents in a channel).

**Comment by whirm** [comment]
I agree this is a cheap improvement and the dependency can be made optional. But it's an extra dependency and the % of time spent serializing json in Tribler will probably be pretty low in general terms.

Let's wait for the API to be more or less stable and then you can do a benchmark and see how it improves performance for Tribler in a more concrete way (so it will look better in your thesis).

**Comment by lfdversluis** [comment]
@whirm Yes, I am first focussing on the DB stuff anyway. Once the API becomes mature, I will take a look and test.

**Comment by devos50** [comment]
Just did a little check with the endpoint that fetches all channels. Encoding 11000 channels (around 2 MB) into a JSON dictionary only takes around 54 milliseconds so I don't think think we can gain a lot of speedup here since it's already quite fast.

**Comment by lfdversluis** [comment]
@devos50 54 ms is indeed not to much. I wonder if using tribler regularly how much time e.g. per hour is spent on en/decoding json?. It's only one install after all, so definitely a low hanging fruit.

If it turns out that time spent doing json stuff is negligible then we can stick to the builtin library.

**Comment by devos50** [comment]
A while ago, we verified that this provides zero to none additional speed.
