### ISSUE TITLE
How to Install On Raspberry Pi 3 ?

### ISSUE THREAD

**Issue by liberodark** [Tribler/tribler#2165]
Hello,

Have RPI version ?

Cordialy

**Comment by Dmole** [comment]
https://github.com/Tribler/tribler/blob/devel/doc/Tribler%20development%20on%20Linux.md

**Comment by devos50** [comment]
Hi,

The link @Dmole provided is correct and at the end of the guide, you should be able to run Tribler from source. If you encounter any problem when following the guide, please create a new issue and we are able to help.

At the moment, we do not have a Debian package available in the repos but we are working on that.

**Comment by whirm** [comment]
@liberodark latest stable release has no binary components, so you can just install the .deb on your RPI. It will punish your storage, so make sure your `.Tribler/` dir is not on a flash memory.

**Comment by mskogly** [comment]
The link is 404

**Comment by Dmole** [comment]
https://github.com/Tribler/tribler/blob/devel/README.rst
