### ISSUE TITLE
Can't remove "Initializing..." download from list

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2170]
#### Please, fill all relevant items:
- [no] I have read CONTRIBUTING.md
- [no] I have tried with the latest pre-release version and I still can reproduce the issue.
##### Tribler version/branch+revision:

v6.5.1
##### Operating system and version:

Debian
##### Expected behavior:

Can remove any download. "Remove download" or "Remove download + data" menu items inaccessible.
##### Actual behavior:

No option to remove the stuck download. Only "Force start" menu item is accessible.
##### Steps to reproduce the behavior:

Stuck downloads happen rather moderately often, espeically when trying to download an old, dead torrent.

**Comment by devos50** [comment]
Thanks for the report. I think this is an issue we should fix before we release 6.6 (and I think it isn't that hard to fix, just enable the stop/remove button when a download is in the initialising state).

**Comment by devos50** [comment]
In Tribler 7, the remove download button is now always enabled and removing downloads should work correctly. Please reopen this issue if you experience the problem again.
