### ISSUE TITLE
Loading the Dispersy communities should be done in Session

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2172]
Loading the Dispersy communities is a typical task of the Tribler core. Currently, we are loading the communities in `tribler_main.py` which I think is not the right place for this task.

I propose to move the loading of the Dispersy communities to the `session.py` file when we are removing the wx stuff.

**Comment by whirm** [comment]
I would make it hang from Session, but in a separate component.

**Comment by devos50** [comment]
Dispersy communities are now loaded in LaunchManyCore.py
