### ISSUE TITLE
Call to unexisting methods in SearchGridManager

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2174]
There are some method calls in SearchGridManager to methods that are not available in Tribler, see  https://github.com/Tribler/tribler/blob/devel/Tribler/Main/vwxGUI/SearchGridManager.py#L1516. Note that `subscribe`, `spam` and `unsubscribe` calls. They do not exist in the `VoteCastDBHandler` class.

**Comment by lfdversluis** [comment]
Will be gone with #2355

**Comment by devos50** [comment]
@lfdversluis thanks for linking!

**Comment by devos50** [comment]
Since the wx GUI will be removed soon, I will close this issue since it will not be fixed.
