### ISSUE TITLE
[devel] Filtering in channels shows results only for a moment

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2184]
#### Please, fill all relevant items:
- [no] I have read CONTRIBUTING.md
- [no] I have tried with the latest pre-release version and I still can reproduce the issue.
##### Tribler version/branch+revision:

b60d3b126ddfcafc2a939c32ca6b9a97a962f561 devel
##### Operating system and version:

Debian
##### Expected behavior:

Can filter content in a channel
##### Actual behavior:

For most filter queries, filtered result flashes though, then it shows "0 items matching (my query)"
##### Steps to reproduce the behavior:

Open Tribler, go to All channels, go to a popular channel (for example, "Kickass torrents"), type something in filter box. For most queries, I see [partial?] results briefly, then they disappear.

I have found one query that does produce relatively stable results: "horrible" (or substring).  After typing it, I see 2 to 5 results (not stable). Sometimes I see some results disappearing after a brief moment.
##### Relevant log file output:

Nothing relevant, only `ERROR   1463008596.94 tunnel_community:535   creating circuit 2613163978 of 2 hops. First hop: ...` (why is it an error?)

**Comment by lfdversluis** [comment]
Confirmed it's not working well. Results never disappear for me on ubuntu 15.10, but Rasperberry pi does not show when searching for "pi", seen same behavior with different queries.

**Comment by whirm** [comment]
@vi: Created a new bug for the wrong log levels on the tunnel community:

https://github.com/Tribler/tribler/issues/2201

**Comment by lfdversluis** [comment]
I think this should be fixed by QT, I think this is low priority now.

**Comment by devos50** [comment]
Yeah, this weird glitch (?) should not happen in the Qt GUI (at least, I haven't seen weird flashes of data so far). Please reopen the issue if you encounter the problem again in the new GUI.
