### ISSUE TITLE
[devel] Restarting Tribler started from Git checkout fails

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2185]
#### Please, fill all relevant items:
- [no] I have read CONTRIBUTING.md
- [no] I have tried with the latest pre-release version and I still can reproduce the issue.
##### Tribler version/branch+revision:

b60d3b1 devel
##### Operating system and version:

Debian
##### Expected behavior:

Tribler restarts
##### Actual behavior:

Tribler shuts down
##### Steps to reproduce the behavior:

Start Tribler from Git checkout (without installing it anywhere), modify settings, accept restart proposition.
##### Relevant log file output:

```
Traceback (most recent call last):
  File "/home/vi/home/tribler/tribler/Tribler/Main/tribler.py", line 7, in <module>
    from Tribler.Core.Utilities.install_dir import determine_install_dir
ImportError: No module named Tribler.Core.Utilities.install_dir
```

**Comment by whirm** [comment]
Thanks!

**Comment by whirm** [comment]
@colin1497 restarting when running a non-packaged version of Tribler is simply not implemented.

**Comment by vi** [comment]
If it is tricky to implement then a proper message should be shown instead.

**Comment by whirm** [comment]
I don't think it's tricky. Simply it hasn't been done yet. (we have to prioritize).  That's something that a volunteer could contribute with relative ease.

**Comment by devos50** [comment]
There's no restart dialog anymore so this issue can be considered as solved.
