### ISSUE TITLE
Feature request: sort downloads by date

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2186]
The adding date may be explicitly stored at database or just retrieved from filesystem (from TriblerDownloads).

**Comment by whirm** [comment]
@devos50 do you want to have a look at this one for the new GUI?

**Comment by devos50** [comment]
I've added this kind of information to the download config file, available in the next PR :)

![3a41df20b040ae5845c76a860bf446dc](https://cloud.githubusercontent.com/assets/1707075/22102193/d8b1182e-de36-11e6-902e-9654c827da25.png)

**Comment by vi** [comment]
"Added on" columns seems to have disappeared in Tribler 8.

**Comment by egbertbouman** [comment]
Next release, we'll add an option to include/exclude columns. That way you can decide for yourself which data should be displayed (see also https://github.com/Tribler/tribler/issues/8331).
