### ISSUE TITLE
Shall consumed anonymity balance decrease counter instead of increasing?

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2189]
Currently I see balance dropping (with approximately the same rate as Total rising). As far as I understand, Balance = Consumed anonymity traffic - Contributed anonymity traffic.

I think it should be reverse: Balance = Contributed anonymity traffic - Consumed anonymity traffic.

People tend to maximize their values, not minimize. Seeing negative balance makes user feel indebted to contribute to anonymity (by enabling Tribler's anonymous mode somewhere). Growing positive number feels allright.

Too small contribution balance (for example, less than -200 MB) may be shown red.

**Comment by lfdversluis** [comment]
I tend to agree to this for the psychological effect. When it was added I also wondered why I was going negative, after the explanation it because clear but you cannot explain every Tribler user this.

**Comment by Captain-Coder** [comment]
This was definately my intent when I implemented this. The total counter needs to count everything. This is usefull for people who have a bandwidth cap, it should provide a resonable estimate for the bulk of the bandwidth used. So this counter simply counts received+sent through the anon tunnels. 

For the balance counter mostly my thought was "a positive balance should be a positive thing". The trouble for the balance comes from the fact that a relay is neutral, they recieve data and send the exact same amount out again. So how much has this relay "consumed"? I'd say 0. But it's contribution might be counted differently. The counter actually counts <anon up> - <anon down>. So in practical terms, it will only rise if you are the source of anonymized traffic, i.e. seeding (more than you are leeching)

We could change the way the counter works to reflect a true "contribution" (details to be discussed) or perhaps the use of the word "contribution" in the balance mouse-over is misleading and we could change it to something like "Anonimity Consumption Balance".

**Comment by vi** [comment]
I though, that 
* produced anonymous bandwidth = bandwidth we relayes for others (for their seeding/leeching); 
* consumed anonymous bandwidth = bandwidth others relayed for us (for our seeding/leeching).

I think all three counters (consumed for leeching, consumed for seeding, produced by relaying) should be visible. How to define balance is another question:

* balance = relay - anon_seed - anon_leech
* balance = relay - anon_leech
* balance = relay + anon_seed - anon_leech

but relaying should definitely bump the counter.

**Comment by qstokkink** [comment]
I believe this is properly fixed with #3492 now (though non-anon payout is still open #3718).
