### ISSUE TITLE
[devel] Removing torrents from my channel works with a delay

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2190]
##### Tribler version/branch+revision:

b60d3b126ddfcafc2a939c32ca6b9a97a962f561 devel
##### Expected behavior:

Removed torrent from my channel immediately disappears. Or there is indication that removal is in progress.
##### Actual behavior:

It disappears from the list after some delay. No indication of background operation.

**Comment by whirm** [comment]
It gets removed once dispersy notices, I'm not sure how this should be represented on the GUI.

**Comment by devos50** [comment]
There is a bug in the old GUI which makes it take longer before the torrent is removed from your channel. In the new GUI, the torrent gets removed almost instantly.
