### ISSUE TITLE
[devel] Ratio does not increase

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2191]
##### Tribler version/branch+revision:

b60d3b126ddfcafc2a939c32ca6b9a97a962f561 devel
##### Expected behavior:

Value in "Ratio" column increase as uploading goes on
##### Actual behavior:

Ratio has been reset to 0.00 for all downloads and stays 0.00. Worked well in v6.5.1.

**Comment by devos50** [comment]
@vi I've added the ratio information to the downloads page in #2691 and I've added info about the ratio, total bytes uploaded and total bytes downloaded to the API response of the request to  `/downloads`. I can confirm that the ratio works correctly for new downloads and this information is saved after Tribler is restarted.
