### ISSUE TITLE
[devel] "Remove all" fails in my channel

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2192]
##### Tribler version/branch+revision:

b60d3b126ddfcafc2a939c32ca6b9a97a962f561 devel
##### Expected behavior:

"Remove all" works like selecting every torrent and pressing "Remove selected"
##### Actual behavior:

It gets ignored.

**Comment by lfdversluis** [comment]
@devos50 Didn't you do something to selecting multiple rows recently?

**Comment by devos50** [comment]
I'm positive that it works in the new Tribler 7 GUI and I just tested it with several torrents 👍
