### ISSUE TITLE
GUI gets blocked while creating a big torrent

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2193]
b60d3b126ddfcafc2a939c32ca6b9a97a962f561 devel, also was in 6.5.1/6.5.0.

**Comment by lfdversluis** [comment]
Most likely because this operation is done on the main thread (wx thread) that the GUI is running on, shouldn't be the case and will become impossible with 6.7 as the GUI runs separate from the core.

@whirm Is this a 6.6 issue though?

**Comment by whirm** [comment]
It should be fairly easy to push the torrent creation to the threadpool and make the gui call async

**Comment by devos50** [comment]
It is on the thread pool currently so this should be fixed: https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Session.py#L744
