### ISSUE TITLE
[devel] Newly created torrent file named after directory and can't be renamed

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2195]
#### Please, fill all relevant items:
- [ ] I have read CONTRIBUTING.md
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.
##### Tribler version/branch+revision:

b60d3b126ddfcafc2a939c32ca6b9a97a962f561 devel
##### Steps to reproduce the behavior:
- Go to my channel
- Press "+ Add ..."
- Press "Create"
- Press "Browse"
- Choose a single file
- Observe selected "Combine files into a single torrent" and grayed "Create separate file for every file" and grayd "Specify a name" containing **file** name.
- Press "Create torrent(s)"
- Accept "This will add 1 new .torrents to this Channel. Do you want to continue"?
- Wait until the torrent shows up
##### Expected behavior:

The torrent and a download is named after the **file** (like was displayed in the creation dialog)
##### Actual behavior:

The torrent and a download is named after the **directory** containing that file (in my case "TriblerDownloads").  Trying to add another file from the same directory overwrites torrent file and creates a duplicate.

**Comment by lfdversluis** [comment]
Definitely a bug, thanks for reporting :)
