### ISSUE TITLE
[devel] Can't make newly created torrent anonymous

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2196]
##### Tribler version/branch+revision:

b60d3b126ddfcafc2a939c32ca6b9a97a962f561 devel
##### Expected behavior:

Can create new torrent as anonymous or change download to be anonymous after creating
##### Actual behavior:

All newly created torrents are non-anonymous
##### Steps to reproduce the behavior:

Follow steps from #2195.

**Comment by devos50** [comment]
It's now possible to change the anonymity of a download after adding it. However, there was an error where a newly created torrent would not download after being added to your channel. I will fix this in a coming PR and then close this issue.
