### ISSUE TITLE
[devel] Tribler re-checks all downloads on starup

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2199]
b60d3b126ddfcafc2a939c32ca6b9a97a962f561 devel

After I close Tribler and start it again, it re-checks all the downloads.
I think it should be only recheck if there may be issues (e.g. filesystem modification date changed or some peer rejected chunks from the file)

**Comment by lfdversluis** [comment]
@whirm I think this was the original report. I think it can be closed too with #2265 ?
