### ISSUE TITLE
Measure IO time spend when running the unit tests

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2215]
To gain insight into the IO time consumed by tribler, I will profile the functions with yappi in databamanagers such as `sqlitecacbedb` to measure the time spent on IO time when running the unit tests.

Output:

| Disk type | Runtime tests | IO Time |
| --- | --- | --- |
| SSD |  |  |
| SATA |  |  |

**Comment by lfdversluis** [comment]
Small update: ran the unit tests a while ago and measured the sqlitecachedb class of Tribler running the Tribler unit tests (so dispersy also runs but **not** captured. The results indicated around 1-2% of the time was spend on IO, not significant at all thus.

Dispersy has a lot more IO and therefore impact. Running the Dispersy unit tests and profile dispersy should already indicate how much of dispersy is doing IO.

**Comment by lfdversluis** [comment]
Running only the dispersy unit tests and profile Dispersy shows similar results. Here is a screenshot when only filtering on database items:

![% of time spend in DB functions](https://gyazo.com/2232f5f5a4dab8d07b7df6ebed5aa704.png)

The .incl is the percentage of time spent in that function, which amounts to ~4%. So the unit tests do not perform much database activity (as somewhat expected).
I think an idle run of tribler communities (allchannel, search etc.) provide better insight of actual behavior.

**Comment by ichorid** [comment]
RIP Dispersy
