### ISSUE TITLE
Fix the jenkins idle run tests to create a basis for ensuring tribler doesn't break when introduction the storm DB manager

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2218]
First step:
- [x] Fix the one week job (and apply the same fix to the 86 hour, 1 day etc.)
- [x] Replace the idle run with @devos50 twistd plugin
- [ ] Join hardcoded channels
- [x] Let it run idle for +- 30 minutes so Tribler syncs
- [ ] Check if any crashes occurred
- [ ] Analyse the results.

The results include:
- Time spent on (blocking) IO (?)
- # synced packets
- CPU consumption (Gumby provided)
- Memory consumption (Gumby provided)
- IO traffic (Gumby provided)

The second step would be:
- [ ] Start a few Tribler instances having a well-packed database and a few from scratch, with the database etc. empty. Make sure they are 
- [ ] Run them in an isolated environment
- [x] Let them run idle for +/- 30 min or so they start syncing
- [ ] Check for crashes
- [ ] Analyse the results

**Comment by synctext** [comment]
We have an ORM now!
