### ISSUE TITLE
Merge Dijjer functionality

### ISSUE THREAD

**Issue by idcrisis** [Tribler/tribler#2224]
Hello coders, 

- Please find it within yourselves to integrate 'Dijjer' functionality into this.

https://code.google.com/archive/p/dijjer/

The ability to configuration-less stream over UDP from behind NATs with bandwidth offloading to peers is useful.

- Convert each node into a Teredo / Miredo server+client ( with support for public internet routing). This could allow all nodes to maintain a private-public and private-private presence. All communication can then be over UDPv6/pure ethernet/Websocket. And each connection/browser tab can be over a different and discard-able address. It may also be possible to maintain a xxhash based DNS ( again both public and private ) and routings table on most nodes ( with increase in cache size proportional to time on network ). More on reliable UDP here:

http://www.streamingmedia.com/Articles/ReadArticle.aspx?ArticleID=85316

TCP socket memory requirements is currently not scalable unless one can implement 'Enuff' like event based zero copy network queues. 

The use of 'erlang'/'rust' programming languages could allow for easy updates to the protocol till it settles.

- Use an RNG generator independent of OS ( like libhavege ). Should increase throughput of encrypted connections.

- Gridcoin support will increase participation and thus redundancy no end.

Thanks.

**Comment by whirm** [comment]
@synctext maybe you want to have a look at this one?

**Comment by synctext** [comment]
that is unmaintained Java code. Not something we can use.
