### ISSUE TITLE
Minimal viable Android app

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2231]
- [x] Search results
- [x] Click to stream
- [x] Record video
- [ ] Extract thumbnail
- [x] Create My Channel
- [x] Add to My Channel
# Performance experiments:
- [x] Startup time
- [x] Cpu usage during idle, tunnels, download, streaming (HD)
- [ ] Search results response time
- [x] REST API benchmark
- [x] Multichain record creation cost
- [x] Code coverage
- [x] CProfiler 10 min. run
- [x] Publish content 1 to 10 devices

**Comment by synctext** [comment]
- Coming 3 weeks: finish 3 thesis chapters...
 - Then minimal viable product: VLC playback.
 - Launch Beta
 - Measure & experiment

**Comment by synctext** [comment]
Progress with app, now VLC integration is complete. Search results are fast and responsive.
![screenshot_20161020-164747](https://cloud.githubusercontent.com/assets/325224/19564903/5459f034-96e5-11e6-8c2e-6bb00f207b9d.png)

Shown above are the sub-second search results from Tribler network (if you have a premium phone).
![screenshot_20161020-164140](https://cloud.githubusercontent.com/assets/325224/19564930/7101e7fa-96e5-11e6-836b-72c1b2853afb.png)
Great progress is the bundeling of VLC. Not as a hard to maintain library, but simply a bundled .APK within the overall Tribler.apk

**Comment by synctext** [comment]
Key experiment: content dissemination experiment with a several phones.
 - 1 phone has channel.
 - 10 phones get subscribed to the same channel
 - continuously add file to source phone (10+ swarms in seconds)
 - see them appear at the various screens with a refresh

**Comment by synctext** [comment]
Please focus on .tex for existing Multichain experiment results.

**Comment by synctext** [comment]
Thesis ref: [example from Nijmegen on how to frame and sell privacy](https://pep.foundation/docs/pEp-whitepaper.pdf)

**Comment by informusica** [comment]
Reference on social media and the news: http://www.digitalnewsreport.org/

**Comment by informusica** [comment]
- placeholders for each new shadow chapter
- 10 times power on of devices => logs
- multichain graphs => 3 graphs
- migrate results that are concretely there
- make new design chapter in terms of functionality. No bullets but text.
- for chapters with unstructured content, reshuffle content WITHOUT REWRITING OR ADDING CONTENT.

**Comment by brussee** [comment]
- [ ] placeholders for each new shadow chapter
- [ ] 10 times power on of devices => logs
- [ ] multichain graphs => 3 graphs
- [ ] migrate only those results that are concretely there
- [ ] make new design chapter in terms of functionality. No bullets but text
- [ ] for chapters with unstructured content, reshuffle content WITHOUT REWRITING OR ADDING CONTENT.
- [ ] if all this is done, refer back to your draft scratch pad and migrate non-covered content to appropriate chapters

**Comment by informusica** [comment]
@synctext some now-backlog items that may ultimately be expanded, but only if time allows, and not before halfway November:

- power on / power off timings: script is available to assess more than 10 runs
- power on / power off timings: currently using time.time() rather than device time. That would need some programming (parsing) to resolve though. Only touch if time and supervisor allow. :)

**Comment by informusica** [comment]
- [ ] new design chapter: no bullets but text
- [ ] migrate non-covered content from draft.tex to appropriate chapters
- [ ] migrate non-bullets from old thesis
- [ ] results: put figures in the *.tex. Explain rationale of test, used metrics, setup, results, again not in bullets but in text.
- [ ] for chapters with unstructured content, reshuffle content WITHOUT REWRITING OR ADDING CONTENT.
- [ ] if time left, fill in further details in chapters but write blindly and not in bullets.

**Comment by synctext** [comment]
Thesis .PDF download link: https://github.com/brussee/thesis/raw/master/thesis.pdf

**Comment by synctext** [comment]
Final experiment:
 - Finished video recording, time is 0
 - Create torrent latency
 - Add torrent to channel
 - Arrived at phone 1 to 4

**Comment by synctext** [comment]
http://www.npr.org/sections/alltechconsidered/2016/11/14/500214959/internet-freedom-wanes-as-governments-target-messaging-social-apps

**Comment by synctext** [comment]
Title brainstorm: "attack-resilient media using phone-to-phone networking"

Possible additional experiment: measure transfer time between various phones of 25MB clips or show power consumption during phone-to-phone exchange (max 1 day experiment).

**Comment by synctext** [comment]
Latest [results of weekend work by hard working student](https://jenkins.tribler.org/job/Build-Tribler_Android-Python/lastBuild/). Scenario is manual transfer between phones + fast spreading if there is some networking:
![phone-to-phone_networking](https://cloud.githubusercontent.com/assets/325224/20456453/3102cd78-ae77-11e6-9ca7-c1c8f0d81a8c.png)

Here you can see how fast a video spreads between a bunch of Internet-connected phones. Likely potential is that it can reach a worldwide audience within 1 minute, without any servers or video support infrastructure. Pure phone-to-phone networking.

![performance_of_phone-to-phone_networking](https://cloud.githubusercontent.com/assets/325224/20456492/d908dce2-ae77-11e6-9e3c-e8c7377245c4.png)

**Comment by synctext** [comment]
[Official thesis .pdf file](https://github.com/Tribler/tribler/files/646286/thesis.41.pdf)

**Comment by qstokkink** [comment]
This thesis has long since been completed.

**Comment by ProphetZarquon** [comment]
It looks like the Android version hasn't been updated in five years. Is an Android app no longer in active development? Android has more devices active than Windows 10, & recent Android versions constitute a significant percentage of active devices overall. Considering the sizable resources & connectivity available on many Android devices, I would expect development of an Android version to be a high priority for any software project hoping to improve global connectivity & freedom of communication. 

Is there some Tribler package for Android that I'm not seeing, or has that branch been abandoned for some reason? If so, why?

**Comment by synctext** [comment]
True, Android app would reach a massive audience.

Sadly we are a non-profit project without the resources needed to do a good app currently. Our focus is on the desktop and build a thriving community there first.

**Comment by qstokkink** [comment]
> Is there some Tribler package for Android that I'm not seeing,

Yes, we have expanded upon this PR and are still working on several apps. However these are for specialized use cases such as just the passport logic or just the market logic. Now that we have trimmed the fat off Tribler a bit, we can start looking at running the full Tribler stack on Android again.

**Comment by synctext** [comment]
All activity now moved here #4827.
