### ISSUE TITLE
The tunnel community depends on cherrypy

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#2239]
It should be using Twisted's facilities.

**Comment by lfdversluis** [comment]
Is this really a bug? More like enhancement right?

**Comment by whirm** [comment]
It shouldn't be using it, that was an oversight from my side when I merged the PR. 
It's holding a dependency that should be gone when all the wx gui code is gone. (the web iface is also using cherrypy, and I was planning on removing it at the same time than WX).
