### ISSUE TITLE
Add rewind (jump in playback) keyboard shortcuts for streaming

### ISSUE THREAD

**Issue by YakovL** [Tribler/tribler#2241]
I'm using Tribler 6.5.1. When watching a video using streaming I sometimes want to jump several seconds back or forth, but doing it by exiting fullscreen mode and moving the "cursor" is not convenient, so it would be lovely if keyboard shortcuts are implemented. I'd propose ctrl+left/right for 1 min rewind and shift+left/right for 3 sec rewind (and may be alt+left/right for 10 sec rewind) like [in VLC](https://www.shortcutworld.com/en/win/VLC-Media-Player_1.html).

**Comment by ichorid** [comment]
another argument in favor of using an external VLC #5388

**Comment by ichorid** [comment]
Streaming is :skull:

**Comment by YakovL** [comment]
@ichorid could you be a little more specific? Is there some news page where I can find a summary? I don't see anything on the main page nor on the forum among recent threads

**Comment by ichorid** [comment]
Well, we removed streaming from Tribler completely ))
