### ISSUE TITLE
Live Streaming with Tribler

### ISSUE THREAD

**Issue by defnax** [Tribler/tribler#2245]
Hello Devs,

What with Live Streaming on Tribler?
it was planned, but its removed completly from Tribler?

It would be cool to stream, live via Webcam, Desktop, Video source to Tribler.

more old infos:
https://www.tribler.org/LiveStreamingBeta/
https://www.tribler.org/LiveStreaming/
https://www.tribler.org/StreamingExperiment/
https://www.tribler.org/Tutorials/ExampleFeedSetups/

**Comment by synctext** [comment]
This is no longer a goal.

We made operational prototypes,but we need to focus our functionality and resources sadly.
