### ISSUE TITLE
Tribler stops seeding a download after I play and stop it.

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2247]
##### Tribler version/branch+revision:

devel, a59a8f38195a01722993c1c8dbe600d636e5afae
##### Steps to reproduce the behavior:
1. Choose some completed video file download in "Seeding" state
2. Play It
3. Stop the player, remove it from player's list by pressing "X"
##### Expected behavior:

The download goes on seeding both while playing and after stopping the player
##### Actual behavior:

The download gets into "Completed" state.

**Comment by devos50** [comment]
This now works correctly in Tribler 7. I've tested it using a video torrent and after playing it, it remains in the seeding state.
