### ISSUE TITLE
Tribler should listen to the system themes on Linux

### ISSUE THREAD

**Issue by Getron** [Tribler/tribler#2249]
Hi

Just installed the tribler, and i'm on Netrunner 2016.01 Arch KDE Rolling release Linux, with the dark theme and QtCurve.

Tribler doesn't listen to default theme from system, it is just white, and some spaces dark.

Can we make it to adapt itself to the system themes on Linux?

It would be great.
![auswahl_236](https://cloud.githubusercontent.com/assets/5913218/15736791/7c9b1f7a-28a2-11e6-962f-7ff4ff0b3c6c.png)

**Comment by whirm** [comment]
Thanks for the report!

A new (Qt based) GUI is on its final stages of development which sports a non-native look (will look the same on Linux/OSX/Windows).

I'll close this as won't fix.
