### ISSUE TITLE
The relevance ranking algorithm when searching in Tribler needs to be redesigned

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2250]
When searching in Tribler, search results (which can consist of torrents and channels) are ranked according to several criteria. Channels and torrents are sorted separately from each other. The associated channels of the torrents are also determined and in case a torrent is present in more than one channel, the channel with the highest number of votes is taken.

Channels are sorted based on the number of torrents in the channel. The algorithm to sort torrents is more complex. First, an array of five scores are constructed. These values are determined as follows:
1. The number of matching keywords in the name of the torrent
2. The number of matching keywords in the name of the files the torrent contains
3. The position of the lowest matching keyword in the torrent name. For instance, when searching for ‘Away From Keyboard’ and ‘of’ is a matching keyword, this position will be 2.
4. The number of matching keywords in the extensions of the file names of the torrent.
5. A score that is based on several (normalised) attributes of the torrent. This score is determined after the set of local search results are constructed. The following formula is used: _score = 0.8 \* normalized_num_seeder - 0.1 \* normalized_num_negative_votes + 0.1 \* normalized_num_subscriptions_. Note that the number of negatives votes and number of subscriptions do not exist anymore and will always be 0. 

After the torrents and channels are sorted, the results are put in a list. Every five torrent results, a channel result is inserted. This is to make sure that channels are also showing up in the search results (and more important, are visible to the user).

Also, I think it’s better to not be dependent on other search results to make streaming torrents from the database possible (like we do now when normalising). In other words, the final relevance score in the new algorithm should only be dependent on the data that this torrent object has.

I will start thinking about a new (more simple) algorithm that we could use for this and add the proposal in this issue.

**Possible improvements:**
- Improve the relevance algorithm by taking the number of matches inside the torrent name/torrent file names in consideration. For instance, when searching for 'pioneer one', a torrent named 'pioneer one collection' probably has a higher relevance than a torrent named 'pioneer one - episode 3, season 4'. This will prevent situations like the following, when I expect 'test_tribler.txt' to show up higher than 'test.tribler.upc.iso'.
  ![9167a65ab13479c028a35e1a9625f2c6](https://cloud.githubusercontent.com/assets/1707075/15743437/c190e7b8-28c5-11e6-89d5-4f81cce49faf.png)
- I think the lowest matching term criteria should be removed or get lower priority since I doubt that it's always true that terms that are matching earlier in torrent A than in torrent B makes torrent A more relevant. For instance, torrent A = "game of thrones" and torrent B = "thrones in someplace". If a user searches for 'thrones', torrent B will be marked as more relevant which feels weird.
- Users are making mistakes when typing. For instance, if I type "triler", I might mean "Tribler" or "triller" so I would like to see results that are matching these queries. This can be achieved by calculating the [levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) with know keywords. One issue here is performance. Fortunately, sqlite contains support for levenshtein collation.
  ![4c590b44f5fabf0762f4fc29c01f7fa8](https://cloud.githubusercontent.com/assets/1707075/15744471/688b2e1a-28cc-11e6-8464-76da46097431.png)
- The sorting of the channels is currently only dependent on the number of torrents in the channel. If I'm not mistaken, it is not even sorted on the matching in the name! See the following example for instance, where I expect the channel with 'pirate' in the name, to show up higher:
  ![f29b7edfd88b07d83b8d69d10746db87](https://cloud.githubusercontent.com/assets/1707075/15779688/0a5b68b4-299e-11e6-9e0c-d14bf7673f1b.png)
- When building the FTS3 index in the sqlite database, duplicate words are removed. This means that when searching for 'years', a torrent named 'best years' will be ranked equal to a torrent named 'years and years'. However, 'years and years' should have a higher relevance since the word 'years' occurs twice. Another example is when searching for 'iso'. A torrent file that contains 100 iso files is ranked equivalent to a torrent file that only has one iso file.
- By removing the number of seeders criteria when sorting, less popular torrent have a better chance of coming up higher in the lists, increasing the chance the user will download these and seed the torrent afterwards.
- Our current algorithm only returns results that matches all given keywords. So when searching for 'pirate audio', only torrents returned that have both terms in it, are returned. It might be better to show the user also torrents matching 'pirate' and matching 'audio' (while still giving more relevance to torrents that matches 'pirate audio').

**Proposal for a new algorithm:**

The new algorithm should take the matching with keywords better into account and be less dependent on other (confusing) variables such as number of seeders and number of torrents in the channel.
- The first step should be to adjust our FTS3 index to not filter out duplicate keywords in the torrent name, file names and file extensions. This will have consequences on the amount of storage required and requires rebuilding the FTS3 index in the upgrader.
- Slightly change the FTS matching query to account for partial term results.
- Use the [BM25F](https://en.wikipedia.org/wiki/Okapi_BM25) algorithm to determine the relevance of the query in the torrent name, file names and file extensions. Note that we have to calculate the BM25 score three times. After that, we can take a weighted average of these scores. The score of the torrent name matching should have the highest priority. The relevance scores are sent to the GUI over the REST API.
- Channel name matching is done in the same way, however, the only difference is that we are not using FTS for the channels. We also calculate the BM25 score of the channel name matching. These relevance scores are sent to the GUI over the REST API.
- If after several seconds there are no incoming results, fetch the keyword(s) with the closest Levenshtein distance from the database and display them to the user with a message similar to the following: "No results found so far. Did you mean to search for ..."?

The above algorithm takes all of the improvements into account I outlined above.

**Comment by devos50** [comment]
@whirm I need this for the new GUI and I almost have a proposal ready. Can you adjust the milestone and assign the issue to me?

**Comment by devos50** [comment]
A first implementation of the algorithm as outlined above can be found here: https://gist.github.com/devos50/71b44339914259c82515f21846ee8173.

**Comment by synctext** [comment]
nice!
please try to write text and document this in a thesis.tex manner, instead of less formal issue rockets.  saves work..

**Comment by themusicgod1** [comment]
It might be worth considering that names aren't the only important thing a keyword search may be looking for - a 'deep search' of the content of files, too, used to be possible in earlier p2p networks (especially within special parts of files, like ID3 tags) and may yet be an important feature, long term to keep our eyes on.

Another thing worth thinking about is whether something like 'pagerank' could be relevant - whereas we have categories/channels that contain torrents, if you search for, for example 'thrones'
if there's a channel of thrones it might be worth giving some kind of priority, even if a small amount, to all the torrents on that channel -- 
Channel: thrones
  S01E01.theora.ogg.torrent.magnet
  S01E02.theora.ogg.torrent.magnet
  S01E03.theora.ogg.torrent.magnet
etc

**Comment by synctext** [comment]
@themusicgod1 Yes, we need accurate metadata, proper pageranking/itemranking, and good ID3 stuff.

btw. Worked on this myself 16 years ago, sadly never got solved (http://cd.ro.nu/hypermail/1046.html). Maybe an extra 16 years:-)

**Comment by synctext** [comment]
Re-opening this issue again. To also show this have getting attention in past years. Last update was 5 years ago.
![image](https://user-images.githubusercontent.com/325224/116089054-c120d800-a6a2-11eb-8830-b6748939ca59.png)
ToDo: do a maximum 1-week only improvement sprint with basic heuristics. We will learn along the way, evaluate and come up with better design. Learn-by-doing methodology. Each matching swarm gets a score to determine the ranking. Basic score is the swarm size. (e.g. 2000 peers swarm get higher ranking than 10 peers). Heuristics:

1. Biggest swarm first: Biggest swarm matching the keyword nicely should come first.
1. One word matching rule: If you search for the creative commons movie "Sintel", the shortest matching swarm should be promoted. Matches such as ```the.script.from.the.movie.Sintel.pdf``` get lower score. Penalty if you have too many non-matching words.
1. First word is the best rule: searching for "Sintel", the match "Sintel-Part-II" gets higher score than "Part-of-Sintel". 
1. Maximum matching rule. Search for multiple terms, like open source movie: "The Internet's Own Boy: The Story of Aaron Swartz". Penalty if you do not match all original search terms.
1. No extra in-between words rule. Searching for "Internet's Own Boy" places results such as "Internet's _very_ Own Boy" and "Internet's _very special_ Boy _person_" lower than the exacter match: "Internet's Own Boy _- Aaron Swartz_"

**Comment by ichorid** [comment]
> 6. When a channel matches exactly the name of the "keyword search terms" it is shown in _expanded state_. See example

Yep. The users were even [asking for something like that](https://forum.tribler.org/t/how-to-update-information-about-channel/6648/4).

**Comment by kozlovsky** [comment]
Regarding the ideal search UI, I think it should satisfy the following guidelines:
1. As [multiple](https://9gag.com/gag/apvG1Z9) [memes](https://knowyourmeme.com/memes/google-page-two) [said](https://digitalsynopsis.com/tools/google-serp-design/), nobody goes to the second page of Google search. For me, it means that it is more important to display the most relevant results at the top of the list than to display the most extended result list possible. And this, in turn, means that **pagination of the result list is not necessary**. It is enough to display a single result page with several hundred torrents, but these torrents should be the best match for a query, with the most relevant results at the top.
2. **The search should be fast**. As Google [reports](https://ai.googleblog.com/2009/06/speed-matters.html), even a slight delay in displaying search results affects user experience. For me, it means the Tribler search UI should not add artificial delays to integrate local and remove search results. It is better to provide local results as fast as possible and display remote results later.
3. The difference between local and remote results is a technical detail of Tribler implementation. What was remote before the search becomes local right after, so it is confusing to display remote and local results on separate tabs, and they **should be displayed in a single list** (as we have now).
4. On the other side, displaying the remote results should not lead to situations when a user attempts to click on a torrent and a new remotely received torrent is inserted into the same position at that moment, which leads to the opening of a wrong torrent. So, **displaying remote results should not be confusing to the user**.
5. The search result list should not display multiple torrents with the same title, as it is hard for a user to find a difference between them. With the current UI, we have results for some searches where the entire first page willed with precisely the same title without any distinction between result rows. In my opinion, it is better to **collapse multiple results with the identical title** into a single group and expand it later on to user demand.

I'll try to demonstrate the UI prototype that satisfies these guidelines.

**Comment by kozlovsky** [comment]
The screenshot demonstrates how the proposed search UI looks. It does not contain any complicated UI elements. After a user types in a query string, it immediately sees local results (within seconds). If later remote results bring some new torrents, a search title starts displaying the number of remotely received torrents and updates this number dynamically. The user can click on the title of the search page to immediately add received torrents to the result list. In that case, new torrents are sorted according to the rank and inserted in the proper places. In the current draft implementation, these new torrents have the `*  ` symbol added to the beginning of the title so that it is possible to easily found the remote results in the result list for debugging purposes. If we use this concept of the simplified search UI instead of the prefix, we can temporarily highlight remotely received torrents with a bright color.

![2022-06-17_07-50-06](https://user-images.githubusercontent.com/2931136/174236307-2088a547-e1f7-438c-a483-1be8a733c6c9.png)

**Comment by synctext** [comment]
progress since 6 years! let not be afraid of a single refresh, users hate to click on things for them to be useful.

Search: display local results and don't wait for remote search. Wait maximum 2000 ms for remote search to come in?

Data driven:
- measure typical remote search response time?
- build a workload model?

**Comment by synctext** [comment]
Would be great to see live "Debian", Ubuntu, etc search demo here recorded with something [like Peek in GIF format](https://github.com/phw/peek).

**Comment by synctext** [comment]
Solid progress, now we have [dark SQL magic](https://github.com/Tribler/tribler/pull/7025/files#r984426069) :partying_face: 
Search is now much better with this upcoming PR. One issue still pending with performance. There has been a huge variance in showing results in the GUI (100 ms upto 3 seconds, with exceptional outliers of 10 seconds). Still unknown; race condition?? (still guessing)

**Comment by synctext** [comment]
@mg98 old 2016 issue, relevant for phd research.

**Comment by synctext** [comment]
Shifting this issue to phd student @mg98  :smiley:
