### ISSUE TITLE
Alert for save_resume_data

### ISSUE THREAD

**Issue by ardhipoetra** [Tribler/tribler#2251]
I noticed that there are not any alert for receiving `save_resume_data`. I have mentioned this in closed PR https://github.com/Tribler/tribler/pull/1990. 

A bit explanation : 
In previous (deprecated) call, `write_resume_data` is synchronously (blocked call) returned the so-called resume data. 

In new call, `save_resume_data` is returned immediately (in my case : `None`). After resume data is ready, it will report an alert `save_resume_data_alert` (or `save_resume_data_alert_failed` if failed) which contains dictionary-format of resume data.

**Comment by whirm** [comment]
So download state is not being stored to disk ever?

**Comment by ardhipoetra** [comment]
Yes, I think so.

User can still resume the torrent downloading because libtorrent recheck download target.

**Comment by whirm** [comment]
Well, that explains several reports about downloads been checked every time Tribler started.

**Comment by devos50** [comment]
Yeah it's quite annoying to have downloads rechecked every time on startup. Should be an easy one to fix however, just create a new alert type and process it in `LibtorrentDownloadImpl` by writing the resume data to the `.state` config file :)

**Comment by lfdversluis** [comment]
Nice find @ardhipoetra This bug was described here: #2199 and should be fixed I guess by your fix 👍

**Comment by ardhipoetra** [comment]
This is fixed, right?

**Comment by whirm** [comment]
Isn't that fixed already?

**Comment by ardhipoetra** [comment]
Can I close this?

**Comment by whirm** [comment]
If it's fixed, sure.
