### ISSUE TITLE
RestAPI is needs connection priority for GUI

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2255]
The twisted plugin running in an Android service process is starting to drop connections quite soon after a fresh install.
It appears that for example the tunnel community makes the gui requests wait and very often time out.
Every dropped gui request to the api is a show stopper to the user, so must be prioritized.

**Comment by whirm** [comment]
There's no such thing as priorities on Twisted. This is more an issue about the tunnel community hogging the twisted thread with long running function calls. Those should be split and/or pushed to the thread pool. 

What kind of latencies are you getting?

I'm assigning this to @lfdversluis as he's the one that's supposed to move the crypto stuff to the threadpool once he's done with the DB IO.

**Comment by brussee** [comment]
@lfdversluis What is your status on moving things to the threadpool?

**Comment by brussee** [comment]
@whirm About 30 to 60 seconds! The fastest phone here is doing better.

**Comment by lfdversluis** [comment]
@brussee AFAIK @qstokkink is assigned to the tunnel community. I assume he will resolve this issue too

**Comment by qstokkink** [comment]
@brussee If you have to wait for me to resolve this: it will be a couple of weeks before I even start work on the tunnel community.

**Comment by whirm** [comment]
I would expose the max amount of circuits on the config so it can be lowered on android

**Comment by brussee** [comment]
I lowered this hard coded value for now: 59ab7c760f191388b4caa89787da2b82ac9c64ce

**Comment by devos50** [comment]
@brussee is that change effective for you?

**Comment by brussee** [comment]
I'll let it run tonight and see what happens.

**Comment by devos50** [comment]
I just installed Tribler on my raspberry pi and it's very slow (even with the tunnel community disabled!). Also, it's taking up my full CPU:

```
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
21908 pi        20   0  186588  58200  14664 R 101.0  6.1   1:26.00 twistd
```

This really limits Tribler running on embedded devices 👎

**Comment by lfdversluis** [comment]
And that was even the latest raspberry pi 3 model B+ :-1:

**Comment by brussee** [comment]
This is what happened this morning:
```
07-12 09:04:50.894 7832-7953/org.tribler.android:service_Triblerd I/Triblerd: Traceback (most recent call last):
07-12 09:04:50.894 7832-7953/org.tribler.android:service_Triblerd I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 91, in _osrandom_rand_bytes
07-12 09:04:50.894 7832-7953/org.tribler.android:service_Triblerd I/Triblerd:   File "/home/paul/.local/share/python-for-android/build/other_builds/python2-openssl-sqlite3/armeabi-v7a/python2/python-install/lib/python2.7/os.py", line 752, in urandom
07-12 09:04:50.894 7832-7953/org.tribler.android:service_Triblerd I/Triblerd: NotImplementedError: /dev/urandom (or equivalent) not found
```

**Comment by whirm** [comment]
@devos50 could you run triblerd with the profiler enabled for a while?

**Comment by devos50** [comment]
@whirm ran it for around 50 minutes, see this call grind file:

[tribler_twistd.log.zip](https://github.com/Tribler/tribler/files/360121/tribler_twistd.log.zip)

**Comment by whirm** [comment]
![2016-07-13-121534_3120x1920_scrot](https://cloud.githubusercontent.com/assets/529494/16800028/8eb40ac0-48f3-11e6-8f5f-209e071785af.png)

**Comment by brussee** [comment]
Right now a limit of 10 max_relays_or_exits gets acceptable response times to the GUI it appears.

**Comment by devos50** [comment]
@brussee that sounds good. What about disabling the tunnel community completely on embedded devices?

**Comment by brussee** [comment]
If this setting (https://github.com/Tribler/tribler/commit/59ab7c760f191388b4caa89787da2b82ac9c64ce) is exposed to the user he/she can make this decision for him/herself.

**Comment by ichorid** [comment]
RIP Twisted
