### ISSUE TITLE
Investigate if __init__s are doing DB IO and remove them if so.

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2256]
We are going to move to an async IO system and as __init__s are supposed to be synchronous, calls to what eventually will lead to DB IO will have to be moved away.

**Comment by lfdversluis** [comment]
Bartercast seems to do io in the init, havent found much else (my mac mini is slow so some tests timeout)

**Comment by devos50** [comment]
This issue is not relevant anymore.
