### ISSUE TITLE
Tribler has a scalability problem when adding torrents with many files

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2258]
As we found out last week with the chardet being slow issue, having a torrent with many files seem to slow down the processing significantly, something is off.

We should plot/visualize/print this behaviour (create fake torrents with many files) and fix it. Then rerun the same torrents and verify the plotted/visualized/printed behaviour is better.

**Comment by lfdversluis** [comment]
@devos50 do you know in which module/file this was?
@whirm can you assign me?

**Comment by devos50** [comment]
Yes, when adding the torrent `bak_multiple.torrent` in the `Tribler/Test` data directory. The specific test is `Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint:TestDownloadsEndpoint.test_get_downloads`.

**Comment by whirm** [comment]
I wouldn't give this one much priority. That's not an operation that happens often and we've got plenty of important issues to address.

**Comment by synctext** [comment]
This actually might still be quite relevant in the Age Of Gigachannel.
