### ISSUE TITLE
Tribler checks already downloaded files too often

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2281]
##### Tribler version/branch+revision: #####

devel, 7cd6ed7402d22772e4a09c4520bec1b8553e1fc8

##### Expected behavior: #####

Tribler checks downloads only if it really suspects it may be broken (updated modification date, mismatched file size, explicit user request, rejected block while seeding).

##### Actual behavior: #####

All downloads are checked every time Tribler starts, consuming CPU and IO and delaying seeding.

##### Steps to reproduce the behavior: #####

1. Ensure you have many downloads in "Seeding" state;
2. Restart Tribler

**Comment by lfdversluis** [comment]
Semi-dup of #2199 it should be fixed by #2265

**Comment by lfdversluis** [comment]
@whirm I think this can be closed with #2265 ?

**Comment by whirm** [comment]
Yes, thanks!
