### ISSUE TITLE
Invalid call to increase_bytes_sent() in routing.py

### ISSUE THREAD

**Issue by pimveldhuisen** [Tribler/tribler#2283]
https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/routing.py#L104

Here increase_bytes_sent() is called with the circuit_id (of type long) as the first argument.
However, increase_bytes_sent() only does something when called with a Circuit, RelayRoute or TunnelExitSocket object. This leads to several useless calls per second.

We should either remove this statement or fix it. Additionally, increase_bytes_sent() should probably explicitly fail when called with an improper value.

**Comment by whirm** [comment]
@pimveldhuisen will you fix this?

**Comment by pimveldhuisen** [comment]
@whirm At the moment I'm not sure whether we should 'fix' the statement, changing the actual behavior of Tribler (which seems somewhat risky as I don't fully understand all the tunnel code) or just delete the line (which seems wrong). I guess you can assign me for now, if I can't work it out I'll ask for help.

**Comment by whirm** [comment]
There is no one related to the tunnel code anymore so I don't know if you will get much help :D

**Comment by egbertbouman** [comment]
@pimveldhuisen I think you can just change the ```self.circuit_id``` to ```self``` and it should work as intended.

**Comment by synctext** [comment]
Thnx @egbertbouman for your help. See below a clear fault in byte counting of the tunnel community.  (devel, Ubuntu14.04, commit 113ff1bdd6a0e4f67c86b0c6bb30520fc1e30b45)

During this expertiment I was also solidly uploading several MByte. However, no significant tunnel upload traffic was counted (2.4 KByte in picture).
@pimveldhuisen @Ewout Can we create a unit test for this? Like moving 100MByte both ways through a tunnel and checking the stats.

![tribler_6 6 pre_34mbyte_down_2kbyte_up__byte_counting_bug](https://cloud.githubusercontent.com/assets/325224/16294279/04bcd2e4-3920-11e6-8dd8-739e325f6e8d.png)

**Comment by synctext** [comment]
91GByte-14.4MByte have gone missing. Three different amounts for the tunnels:
 - 91 GByte Upload in _library_ view in just 1 swarm
 - 51 GByte in _community_ total upload counter
 - 2.4 KByte in a typical upload multi-chain _record_ in recent activity (6000 x 2.4 KByte = 14.4MByte overall total)
 - 2-25 MByte in a typical _received signature request_ (89 GByte overal estimate, see parsing and investigation below)

Running the latest devel on Ubuntu.
commit 4d13aebf06287e98613a7a49580532b0af252bcd
Date:   Fri Jun 24 16:49:26 2016 +0200

Parsed the logfile with 804 signature requests.
```grep 'Received signature' cmd.log  | sed 's/INFO.*Up = //' |sed 's/MB.*]//' | awk '{sum+=$1} END {print "AVG=",sum/NR; print "TOTAL=",sum/NR*5935,"MB"}'
AVG= 15.1244
TOTAL= 89763.2 MB```


```
INFO    1466923419.59       community:189   Received signature request for: [Up = 4MB | Down = 1 MB]
INFO    1466923419.92       community:249   Persisting sr: ujJ1y0EJ1mVJcDU4PF2unmunWr0H6jxjpeERpke5Rvs=
INFO    1466923419.94       community:210   Sending signature response.
INFO    1466923420.95       community:189   Received signature request for: [Up = 25MB | Down = 8 MB]
INFO    1466923421.13       community:249   Persisting sr: e2iwktZrZPT+2Ri70sx7sC50EEiWT63enziIFrk6XtE=
INFO    1466923421.16       community:210   Sending signature response.
INFO    1466923424.19       community:131   MULTICHAIN: Schedule Block called. Candidate: {95.211.155.142:22914} UP: 2646 DOWN: 1350075
INFO    1466923424.36       community:269   Persisting sr: pYaHmjIhL28AgdaQ3jxPyjFWI661p48PaQ0sPPSeiWc=
INFO    1466923424.41       community:227   Signature response received. Modified: True
INFO    1466923424.41       community:238   Valid 1 signature response(s) received.
INFO    1466923424.41       community:259   Persisting sr: pYaHmjIhL28AgdaQ3jxPyjFWI661p48PaQ0sPPSeiWc=
INFO    1466923425.08       community:288   Crawler: Received crawl request from node 0R/a315oIE1nTpvrdz1TLUhDYEU=, from sequence number 5907
INFO    1466923426.27       community:288   Crawler: Received crawl request from node 0R/a315oIE1nTpvrdz1TLUhDYEU=, from sequence number 5910
INFO    1466923430.60       community:189   Received signature request for: [Up = 17MB | Down = 6 MB]
INFO    1466923430.73       community:249   Persisting sr: o9TTd9D8E6BVsB9HvniWZr0zoepdjLeENrFUR0y6/lY=
INFO    1466923430.73       community:210   Sending signature response.
INFO    1466923430.74       community:189   Received signature request for: [Up = 4MB | Down = 1 MB]
INFO    1466923430.87       community:249   Persisting sr: 1Fyy+jiDYZchMUkC4Y4qTwfKjSwj43hwDcJtDa2G3g4=
INFO    1466923430.87       community:210   Sending signature response.
```
![tribler_6 6pre_51gbyte_upload](https://cloud.githubusercontent.com/assets/325224/16360939/c97f90b8-3b7c-11e6-883b-69ff7b8d0099.png)

![tribler_6 6pre_three_different_upload_bytes_amounts](https://cloud.githubusercontent.com/assets/325224/16360923/cf5f546a-3b7b-11e6-9def-c316df26aa6c.png)

**Comment by pimveldhuisen** [comment]
@synctext This is a very useful report, and this is definitely something we should look into. However, this issue refers to a specific line in the code that is unrelated to this problem. I would suggest moving this to a new, separate issue.

**Comment by synctext** [comment]
Nice! Running  commit c983ea553e92e09127f36d41dd3abe6f503a9594
Date:   Mon Jun 27 15:31:46 2016 +0200

Uploads are making more sense. However... Below you can see numerous log entries as 22 tunnels are arranging their multi-chain records within a span of 10 seconds. They _all_ come from the same IPv4:port combo ? _95.211.155.142:6373_

```
INFO    1467054158.94       community:131   MULTICHAIN: Schedule Block called. Candidate: {95.211.155.142:6373} UP: 398204 DOWN: 1779917
INFO    1467054158.98       community:269   Persisting sr: O+EQcchU6TEB+qEQqYP1e71Q4iiLvEr+Qu3xNG0LjWM=
INFO    1467054158.99       community:131   MULTICHAIN: Schedule Block called. Candidate: {95.211.155.142:6373} UP: 1773494 DOWN: 32797491
INFO    1467054159.04       community:269   Persisting sr: yyj2l7NNexv1pz3cmmEqoo1mzmGw7AYU/JXSEQql9GU=
INFO    1467054159.04       community:131   MULTICHAIN: Schedule Block called. Candidate: {95.211.155.142:6373} UP: 5607873 DOWN: 5164112
INFO    1467054159.08       community:269   Persisting sr: Y0woWpHdY4yUWPTOVTQqSXHXa39lEQ5DujFXLM79Yrw=
INFO    1467054159.08       community:131   MULTICHAIN: Schedule Block called. Candidate: {95.211.155.142:6373} UP: 1949598 DOWN: 17743703
INFO    1467054159.13       community:269   Persisting sr: vuIBqvUVb5bFJbjLy9OdHNCvZpcY9Kl+FfhePPAODow=
INFO    1467054159.13       community:131   MULTICHAIN: Schedule Block called. Candidate: {95.211.155.142:6373} UP: 7637854 DOWN: 40531515
INFO    1467054159.17       community:269   Persisting sr: dPhyPj3nIkmtXCDlI6es1eeaLX5c25ibDOhjI7YlFKw=
INFO    1467054159.18       community:131   MULTICHAIN: Schedule Block called. Candidate: {95.211.155.142:6373} UP: 41737495 DOWN: 22887482
INFO    1467054159.22       community:269   Persisting sr: CbyNCZWDCmMfviUa6GewGLn7aLuhZtpe7cQEfeZTdYc=
INFO    1467054159.22       community:131   MULTICHAIN: Schedule Block called. Candidate: {95.211.155.142:6373} UP: 852995 DOWN: 3774810
INFO    1467054159.26       community:269   Persisting sr: xlUWMCt7PQO37cEzNIrFVMS3TUInPdBFGUjCQidn4yY=
INFO    1467054159.26       community:131   MULTICHAIN: Schedule Block called. Candidate: {95.211.155.142:6373} UP: 703691 DOWN: 12153432
INFO    1467054159.29       community:269   Persisting sr: s/F1Halsjkc8eE1FnaQwuhVaZ733sdJ4Uk/2fvGMtkk=
INFO    1467054159.31       community:227   Signature response received. Modified: True
INFO    1467054159.31       community:238   Valid 1 signature response(s) received.
INFO    1467054159.31       community:259   Persisting sr: O+EQcchU6TEB+qEQqYP1e71Q4iiLvEr+Qu3xNG0LjWM=
INFO    1467054159.32       community:227   Signature response received. Modified: True
INFO    1467054159.32       community:238   Valid 1 signature response(s) received.
INFO    1467054159.32       community:259   Persisting sr: yyj2l7NNexv1pz3cmmEqoo1mzmGw7AYU/JXSEQql9GU=
INFO    1467054159.32       community:227   Signature response received. Modified: True
INFO    1467054159.32       community:238   Valid 1 signature response(s) received.
INFO    1467054159.32       community:259   Persisting sr: Y0woWpHdY4yUWPTOVTQqSXHXa39lEQ5DujFXLM79Yrw=
INFO    1467054159.33       community:227   Signature response received. Modified: True
INFO    1467054159.33       community:238   Valid 1 signature response(s) received.
INFO    1467054159.33       community:259   Persisting sr: vuIBqvUVb5bFJbjLy9OdHNCvZpcY9Kl+FfhePPAODow=
INFO    1467054159.33       community:227   Signature response received. Modified: True
INFO    1467054159.33       community:238   Valid 1 signature response(s) received.
INFO    1467054159.33       community:259   Persisting sr: dPhyPj3nIkmtXCDlI6es1eeaLX5c25ibDOhjI7YlFKw=
INFO    1467054159.34       community:227   Signature response received. Modified: True
INFO    1467054159.34       community:238   Valid 1 signature response(s) received.
INFO    1467054159.34       community:259   Persisting sr: CbyNCZWDCmMfviUa6GewGLn7aLuhZtpe7cQEfeZTdYc=
INFO    1467054159.34       community:227   Signature response received. Modified: True
INFO    1467054159.34       community:238   Valid 1 signature response(s) received.
INFO    1467054159.34       community:259   Persisting sr: xlUWMCt7PQO37cEzNIrFVMS3TUInPdBFGUjCQidn4yY=
INFO    1467054159.36       community:227   Signature response received. Modified: True
INFO    1467054159.36       community:238   Valid 1 signature response(s) received.
INFO    1467054159.36       community:259   Persisting sr: s/F1Halsjkc8eE1FnaQwuhVaZ733sdJ4Uk/2fvGMtkk=
INFO    1467054163.78       community:131   MULTICHAIN: Schedule Block called. Candidate: {95.211.155.142:6373} UP: 1150831 DOWN: 2846565
INFO    1467054163.83       community:269   Persisting sr: Yo0rKWMbsOVO2xOgKbWDo6duTb/8Wm3/1vmI/WpCods=
INFO    1467054163.83       community:131   MULTICHAIN: Schedule Block called. Candidate: {95.211.155.142:6373} UP: 1012618 DOWN: 1059247
INFO    1467054163.86       community:269   Persisting sr: +eU5BAuWpRc4OkYhAfMT3wVkUoZO6J4EOh2ng3RMmvk=
INFO    1467054163.86       community:131   MULTICHAIN: Schedule Block called. Candidate: {95.211.155.142:6373} UP: 1292280 DOWN: 5059025
INFO    1467054163.90       community:269   Persisting sr: T51u9sczGa0T4JLAX0lUj1S4KiftazzLXX7+ZyzKkaQ=
INFO    1467054163.90       community:131   MULTICHAIN: Schedule Block called. Candidate: {95.211.155.142:6373} UP: 1415705 DOWN: 2101102
INFO    1467054163.94       community:269   Persisting sr: HVxtgH/ilynXszya67Jt9uvd9S36wCvHWxke8YccvkU=
INFO    1467054163.94       community:131   MULTICHAIN: Schedule Block called. Candidate: {95.211.155.142:6373} UP: 315861 DOWN: 4253444
INFO    1467054163.99       community:269   Persisting sr: GY+rNdW/2ygMaQo+2yFu70KfKo49+Tz+e2fGj9AHm4M=
INFO    1467054164.00       community:131   MULTICHAIN: Schedule Block called. Candidate: {95.211.155.142:6373} UP: 102430945 DOWN: 79462571
INFO    1467054164.04       community:269   Persisting sr: KQrJWH5XQE//BnLCbh9zQtw/Z5bbdYA32xXF1Z5X7Oc=
INFO    1467054164.04       community:131   MULTICHAIN: Schedule Block called. Candidate: {95.211.155.142:6373} UP: 3262447 DOWN: 9290172
INFO    1467054164.07       community:269   Persisting sr: OKcwVCzX64S5zkatg1cH+hhDFk6WsUnYB5dyKIRgJq0=
INFO    1467054164.07       community:131   MULTICHAIN: Schedule Block called. Candidate: {95.211.155.142:6373} UP: 4001849 DOWN: 12411703
INFO    1467054164.11       community:269   Persisting sr: tcIDzyL0ihggNSxIqGSytFwsOdWsB2bhMs4AmWWZlF4=
INFO    1467054164.11       community:131   MULTICHAIN: Schedule Block called. Candidate: {95.211.155.142:6373} UP: 23490367 DOWN: 43008963
INFO    1467054164.14       community:269   Persisting sr: afurRvHbUAbd2/OBUPfTF0KlrTjuSkY80EqUQK+9cjw=
INFO    1467054164.14       community:131   MULTICHAIN: Schedule Block called. Candidate: {95.211.155.142:6373} UP: 1057765 DOWN: 6818480
INFO    1467054164.18       community:269   Persisting sr: ObS39H3IhHtzccH42GTo34wSR5h+0mSCIW36R45EjHA=
INFO    1467054164.18       community:131   MULTICHAIN: Schedule Block called. Candidate: {95.211.155.142:6373} UP: 1344422 DOWN: 10855949
INFO    1467054164.22       community:269   Persisting sr: YV05+m6tnCQvJS6mM11qSZhPxvGbgeRrIsamNglIfcc=
INFO    1467054164.22       community:227   Signature response received. Modified: True
INFO    1467054164.22       community:238   Valid 1 signature response(s) received.
INFO    1467054164.22       community:259   Persisting sr: Yo0rKWMbsOVO2xOgKbWDo6duTb/8Wm3/1vmI/WpCods=
INFO    1467054164.22       community:227   Signature response received. Modified: True
INFO    1467054164.22       community:238   Valid 1 signature response(s) received.
```

![tribler_6 6pre_upload_bytes_in_tunnel](https://cloud.githubusercontent.com/assets/325224/16392098/6ef202f0-3caa-11e6-9ed5-6088ed3e8ffa.png)
