### ISSUE TITLE
Refactor the add torrent to channel endpoint

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2284]
I would like to propose two changes to the add torrent to channel endpoint:
- We can easily pass the torrent file data using a HTTP multipart request instead of passing the base64 data of the torrent file. I've already done this here: https://github.com/devos50/tribler/commit/2d0efe15e3a12d2c231eb021b600447b269d77b2. After that, we can easily add torrents to your channel using something like:

```
curl -X PUT -F "file=@/path/to/my/file.torrent" -F "additional_data=bla"
```
- Currently, when adding a torrent to your channel using a url/magnet, we are making a PUT request to `mychannel/torrents/{theurl}`. This is problematic since I currently assume that torrents are identified by their infohash and not by their url. I think it might be better to add an extra field to the request when adding a torrent file to your channel, specifying the source (file/url/magnet).

@brussee what are your thoughts on this?

**Comment by ichorid** [comment]
While working on this, please note that GigaChannel now supposes that objects are uniquely identified by pk+id keypair. This means that now we are truly REST compliant in a sense that one could POST the same infohash twice and get two new objects.
