### ISSUE TITLE
Running test on test_events_endpoint with other test using setUpFileServer produces error

### ISSUE THREAD

**Issue by ardhipoetra** [Tribler/tribler#2288]
Tested on the most updated `devel` branch.

I keep getting an error about `AssertionError: The reactor had readers/writers left` in some testcases. It seems the problem relies whenever I run **together** test : `test_events_endpoint` with other test that use `setUpFileServer` function. 

It is tested with `Test/test_libtorrent_download.py` and `Test/API/test_download.py`.

**Comment by devos50** [comment]
@ardhipoetra I just noticed that this is related to #2292 ;)

**Comment by devos50** [comment]
@ardhipoetra this is fixed in #2293.
