### ISSUE TITLE
Left readers/writers check is broken

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2292]
When running the tests on devel, I noticed something very weird.

```
iMac-van-MA:tribler_endpoints martijndevos$ nosetests Tribler/Test/Core/Modules/RestApi/test_events_endpoint.py Tribler/Test/Core/Modules/RestApi/test_my_channel_endpoints.py -vx
Testing whether we still receive messages that are in the buffer before the event connection is opened ... ok
Testing whether the event endpoint returns search results when we have search results available ... ok
Testing whether the API returns the right JSON data if a channel is created ... ok
Testing whether the API returns the right JSON data if a channel is created ... ok
Testing whether the API returns a formatted 500 error if DuplicateChannelNameError is raised ... ok
Testing whether the API returns the right JSON data if description parameter is not passed ... ok
Testing whether the API returns a 400 and error if the name parameter is not passed ... ok
Testing whether the API returns response code 404 if no channel has been created ... ok
Testing whether the API returns the right JSON data if a channel overview is requested ... ok
Testing whether the API returns response code 404 if no channel has been created when fetching torrents ... ok
Testing whether the API returns an error if an unknown endpoint is queried ... ok
Testing whether the API returns the right JSON data if no channel has been created when fetching rss feeds ... ok
Testing whether the API returns the right JSON data if a torrents from a channel are fetched ... ok
test_add_torrent_from_magnet_to_my_channel_without_description (Tribler.Test.Core.Modules.RestApi.test_my_channel_endpoints.TestMyChannelModifyTorrentsEndpoint) ... ok
Testing whether a torrent can be added to a channel using the API ... ERROR

======================================================================
ERROR: Testing whether a torrent can be added to a channel using the API
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/martijndevos/Documents/tribler_endpoints/Tribler/Test/test_as_server.py", line 281, in tearDown
    super(TestAsServer, self).tearDown(annotate=False)
  File "/Users/martijndevos/Documents/tribler_endpoints/Tribler/Core/Utilities/twisted_thread.py", line 151, in errback
    failure.raiseException()
  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/martijndevos/Documents/tribler_endpoints/Tribler/Test/test_as_server.py", line 153, in checkReactor
    self.assertFalse(selectable_strings, "The reactor had readers/writers left")
AssertionError: The reactor had readers/writers left
```

I've pinpointed the problem to the events tests which are not closing the event socket properly (which is my bad), however, the assertion triggers only when running a test that is NOT decorated with `@deferred`?!

This example should be easily reproducible by creating a very simple test without `@deferred` decorator, running `test_events_endpoint.py` and that simple test afterwards.

**Comment by devos50** [comment]
For now, I will fix the `test_events_endpoints.py` tests but if this check worked correctly, it would not have  been merged in the first place which should have been the case.

**Comment by ardhipoetra** [comment]
In my case, one of the test is using `@deferred` decorator but still producing those errors

**Comment by whirm** [comment]
@lfdversluis you implemented this check right? should I assign this to you?

**Comment by lfdversluis** [comment]
@devos50 do you mean that this check should also fire WITH a `@deferred` decorator above a test?

**Comment by devos50** [comment]
@lfdversluis when running `Tribler/Test/Core/Modules/RestApi/test_events_endpoint.py`, it ignores the open event socket I'm leaving behind. The reader/writers check does not recognize this somehow and the tests are passing as you can see in my posted logs.

It gives an error however on the first test that is not decorated with `@deferred` so I'm suspecting that something goes wrong with the check when we have `@deferred` above the test.

**Comment by lfdversluis** [comment]
Maybe nose is doing weird stuff then.. hmm

**Comment by lfdversluis** [comment]
Do you use Twisted's reactor or nose's?

**Comment by lfdversluis** [comment]
I just checked it's identical to Twisted's Trial Janitor check here: https://github.com/twisted/twisted/blob/trunk/twisted/trial/util.py#L171 so I doubt there is something wrong with the check. I think it's the combination of nose + this that goes wrong.

**Comment by whirm** [comment]
Haven't looked at the code, but maybe the check is not running on the right thread on all cases or something like that?

**Comment by whirm** [comment]
In any case it needs to be investigated and fixed

**Comment by devos50** [comment]
I haven't got any errors with the reader/writer check during the last months so I will close this issue and reopen it if it happens again.
