### ISSUE TITLE
Unexist flags calculate_file_hashes

### ISSUE THREAD

**Issue by ardhipoetra** [Tribler/tribler#2296]
In libtorrent 1.1.0.0, flags `calculate_file_hashes` is not exist. This will produce an exception whenever function `create_torrent_file` is called.

Reference : https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Utilities/torrent_utils.py#L30

**Comment by devos50** [comment]
Has been fixed in https://github.com/Tribler/tribler/pull/2555/commits/2decc49933ff518920f7bc9b07c801a6848e7ab6
