### ISSUE TITLE
Credit investments test: donate 1 TByte anonymously

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#23]
Credit investments going live: 

Ability to Donate 1TByte of disk space to the community and get top download priority.
Critically depends on ticket: #5 and to lesser extend #21.
An undersupply detection mechanism seeks out swarms which are low on seeders.
The investment function download parts of these swarms and engages in partial seeding to earn credit. Seeding is done anonymously through proxies, critical dependency with #22.

Test idea: Tribler automatically fills 100MByte of disk, can be disabled on front-screen.

First test version is limited to few thousand Libswift test swarms which are included in Tribler and seeded. Desired outcome of the test is evenly spread out partial seeding. If we do artificial repeated downloads from 1 swarm, we boost demand and peers should see this as an attractive investment.

**Comment by Baigle** [comment]
I can help provide 1TB, though I will be limited on the async upload speed. If it proves to be very successful and help is still needed then I can do some upgrading.

**Comment by synctext** [comment]
The core of the credit mining branch: https://github.com/egbertbouman/tribler/blob/channel_boosting/Tribler/Policies/BoostingManager.py

**Comment by synctext** [comment]
@ardhipoetra All yours for 9 months:-)

**Comment by ardhipoetra** [comment]
As I mentioned in #21, these are the ingredients that may be used for Terabyte seeding : 

* Collection of torrents and logs : my [dropbox](https://www.dropbox.com/sh/qksj651s4cux5l6/AAA_XZPSLAc2V4SkEWueQo2Xa?dl=0)
* Collection of `.torrents` only (14248), zipped. Will be in bbq soon (I hope)
* The crawler (can be extended to facilitate other site) : https://github.com/ardhipoetra/legal-torrent-crawler
* Channel (currently only holds 3000 torrents) : 822e5c3fb617164133d242f0cccebab609d80974. For channel, I keep it in my local machine.

**Comment by synctext** [comment]
In November 2013 we had the first credit mining code. We now re-visited this feature as part of our micro-economy work. The general major re-factor work of Tribler in general is paying off. Screenshot shows live boosting of a selected torrent channel subscription with several MBytes per second. Tribler shown here is beginning to discover swarms, investing in certain swarms, and beginning to earn a modest amount of credits by uploading in 1 swarm. Note, credits are only earned by uploading to other Tribler users or other compatible clients.
![credit_miningg__live_jan2018](https://user-images.githubusercontent.com/325224/35040184-83fd39d0-fb80-11e7-88c8-404799792f0e.png)

**Comment by synctext** [comment]
Moving all activity to newer issue: https://github.com/Tribler/tribler/issues/6519
