### ISSUE TITLE
Move 'managers' to core

### ISSUE THREAD

**Issue by ardhipoetra** [Tribler/tribler#2304]
I think the 'managers' (`LibraryManager`, `ChannelManager`, `TorrentManager`) in `Tribler/Main/vwxGUI/SearchGridManager.py` should be moved to Core. This is important for GUI-Core separation. Currently, those managers relies in GUIUtility and mixes up some stuff in GUI.

**Comment by devos50** [comment]
This issue is not relevant anymore since they will be removed soon ;)
