### ISSUE TITLE
Proposal: use pyinstaller to build Tribler 7 and onwards on Windows/OS X

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2319]
I've investigated [pyinstaller](http://www.pyinstaller.org) and it seems to work (almost!) out of the box on both OS X and Windows. Some minor tweaks were needed to make it work. For instance, I had to change the path of the wx images in the frozen bundle. Also, I had to implement a custom hook due to [this bug](https://github.com/pyinstaller/pyinstaller/issues/1935) on Windows (which should be solved in the next release). In my minimal build, there are some files which are not correctly imported yet but changing the paths to support these missing files is easy.

Creating the package on OS X takes around 2 minutes and on Windows around 10 minutes (I'm not sure why it's so much slower on Windows). All necessary modules are automatically detected and imported. Building the Tribler package is only one command away: `pyinstaller tribler.spec` (in the `.spec` file, various options such as additional imports and hooks are specified).

Overall, I'm very happy with the usability of pyinstaller and I think we should use it for the next Tribler release with the new GUI. (Py)Qt is automatically packaged too. An additional advantage is that we have one script for both building on Windows and OS X which means less code to maintain.

**Comment by lfdversluis** [comment]
Sounds great, we would still need NSI installer as unlike the name it is not an installer right?

**Comment by devos50** [comment]
@lfdversluis yes exactly, we still need NSIS unfortunately. It also seems that the Windows bundle is very small (only around 70MB), probably due to the fact that it's stripping DLLs.

**Comment by lfdversluis** [comment]
70MB is pretty large, I believe the current installer is ~70MB too.

**Comment by devos50** [comment]
Done already!
