### ISSUE TITLE
Splitting the events in the events endpoint on newline is not reliable

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2335]
In #2324, we discussed about the usage of the newline as separator of JSON documents. This is not reliable enough since the JSON itself may contain newlines. So we need to think of another approach.

I'm thinking about prefixing each event with the length of the coming event dictionary. This could for instance be encoded in 4 bytes. This way, we can read the events connection like:
- read the 4 bytes
- read the number of bytes contained in the previous read 4 bytes

@whirm @lfdversluis @brussee what do you think about this approach? Any other suggestions?

**Comment by whirm** [comment]
Something like this would probably be better:

https://github.com/evolvIQ/splitstream

But it's not on Debian and it's a C module. :(

**Comment by whirm** [comment]
https://pypi.python.org/pypi/ijson/

**Comment by whirm** [comment]
Or maybe even better: every new line, try to parse the buffer, if parsing fails, read until next new line and append to the original buffer and so on.

**Comment by lfdversluis** [comment]
Imo that is quite an ugly way to implement a stream parser.

**Comment by whirm** [comment]
It's not a stream parser (there's several separate json documents on the stream and each gets completely parsed or not at all)

It's not pretty, but anything else short than using a splitstream-like library or directly switching to stream parsing (ijson) becomes complex and expensive (if you track bracket balancing you need to start checking if they are inside of strings, etc.).

**Comment by whirm** [comment]
@devos50 have you checked if qt has a streaming json parser?

**Comment by brussee** [comment]
@devos50 I've looked online and found the same solution as you propose to be te best one.

**Comment by brussee** [comment]
Right now I've solved this }{ issue by an ugly split and merge: https://github.com/brussee/tribler/commit/04db91ca6298354114ae23133e1af0e80f3ea1dc

**Comment by synctext** [comment]
https://pypi.python.org/pypi/cobs/

that should do the trick, use the 0x00 with byte stuffing.

**Comment by ichorid** [comment]
@devos50 , is it still a problem?

**Comment by devos50** [comment]
This is still a problem, but our events do not contain newlines.

**Comment by ichorid** [comment]
Actually, SSE standard supports multiline like this:
```
data: first line\n
data: second line\n\n
```

To reduce our codebase a bit we could adopt something like https://github.com/aio-libs/aiohttp-sse

**Comment by ichorid** [comment]
As was pointed out by @devos50 , this is not a problem since we only send JSON-packed dicts for events, and JSON escapes newlines automatically. So, closing this one.
