### ISSUE TITLE
Credit mining (tests) are dependent on GUI code (GUIDBTuples)

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2356]
During the removal of the wx code, I found out that the credit mining tests (in particular, `test_creditmining_sys.py` are dependent on the (soon to be removed) `GuiDbTuples` package. See for instance `test_chn_lookup` where you are using `CollectedTorrent`.

A quick search learned me that the `GuiDbTuples` package is also used in `BoostingSource.py` and `credit_mining_util.py`.

@ardhipoetra can you refactor this so they are not using `GuiDbTuples` as soon as possible?

**Comment by ardhipoetra** [comment]
It also has dependency with `TorrentManager` (in `Main/vwxGUI/SearchGridManager.py`). Is there any module to replace that now?

**Comment by devos50** [comment]
@ardhipoetra that depends on what you need from the `TorrentManager`. Can you explain that?

**Comment by ardhipoetra** [comment]
basically, all the process from having only the infohash, to really get the torrent file, store it to torrent_store or database, and an object representation of a torrent.

I need `ChannelManager` as well, but I think I have workaround for that.

In any case, I'm looking at it now.

**Comment by devos50** [comment]
@ardhipoetra how much work would it be to create a minimal method for that in `Session` or `LaunchManyCores` (or some other file)?

**Comment by ardhipoetra** [comment]
I'm finishing it right now and it in the testing phase

**Comment by ardhipoetra** [comment]
This issue should be close by the https://github.com/Tribler/tribler/pull/2398
