### ISSUE TITLE
Percentage in "Files" tab for a download all show total downloaded percentage instead of per-file one.

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2370]
##### Tribler version/branch+revision:

7cd6ed7402d22772e4a09c4520bec1b8553e1fc8 devel
##### Operating system and version:

Linux Debian
##### Steps to reproduce the behavior:
1. Somehow have a download with multiple files, of which only the first file is included and downloaded, and the second and rest files are not downloaded and not included;
2. Observe "Files" tab for this download:
   
   ```
   First file 150 MB Included 100.00%
   Second file 150 MB Excluded 
   ...
   ```
3. Now include the second file.
4. Observe the "Files" tab:
##### Expected behavior:

```
First file 150 MB Included 100.00%
Second file 150 MB Included 0.00%
...
```
##### Actual behavior:

```
First file 150 MB Included 50.00%
Second file 150 MB Included 50.00%
...
```

Include third file:

```
First file 150 MB Included 33.00%
Second file 150 MB Included 33.00%
Third file 150 MB Included 33.00%
...
```

**Comment by whirm** [comment]
@devos50 could you make sure the new gui doesn't have this problem?

**Comment by devos50** [comment]
@whirm I can almost guarantee that the right percentages are displayed in the new Qt GUI.

**Comment by vi** [comment]
Still reproducible in commit 3985b3dd0a25f5ca09e98411e85cc43cd94375a2

**Comment by lfdversluis** [comment]
@vi The new QT gui is not on devel yet, but still an open PR. If this bug will be fixed, it will be done on the **next** branch. Soon devel will have no wx gui anymore (the current gui).

**Comment by synctext** [comment]
@vi thnx for all the hardcore testing!

We very much would like to make you the first field tester of the completely redone GUI. if you have time in 1-2 weeks. you would work directly with devs, via irc preferably. sounds fun?

**Comment by vi** [comment]
I juse use Tribler and report bugs along the way, that doesn't look like a "hardcore testing".

But if needed I can also try [the QT GUI](https://github.com/Tribler/tribler/pull/2153), if it is not too early for this.

**Comment by devos50** [comment]
@vi can you check whether this happens in the new GUI?

**Comment by vi** [comment]
No.

**Comment by devos50** [comment]
I can confirm that this works correctly in the latest alpha release.
