### ISSUE TITLE
RestAPI test_create_torrent_endpoint failing randomly

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#2371]
##### Tribler version/branch+revision: #####
tribler/devel 29b37ecc2f2acf55d8ca73c61c54dc6ba9052f35
##### Operating system and version: #####
Confirmed on *Ubuntu 15.10* and *Jenkins test Linux builder*
##### Behavior: #####
Running:
```
nosetests -x Tribler/Test/Core/Modules/RestApi/test_create_torrent_endpoint.py
```
Alternates between outputs:
```
$ nosetests -x Tribler/Test/Core/Modules/RestApi/test_create_torrent_endpoint.py
...
----------------------------------------------------------------------
Ran 3 tests in 6.995s

OK
```
And:
```
$ nosetests -x Tribler/Test/Core/Modules/RestApi/test_create_torrent_endpoint.py
...
----------------------------------------------------------------------
Ran 3 tests in 13.038s

OK
Exception in thread DHT (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/home/quinten/tribler/triblerofficial/Tribler/Core/DecentralizedTracking/pymdht/core/minitwisted.py", line 91, in run
  File "/home/quinten/tribler/triblerofficial/Tribler/Core/DecentralizedTracking/pymdht/core/minitwisted.py", line 105, in run2
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'critical'
```

**Comment by brussee** [comment]
My guess is that the logger is not instantiated: _logger.critical(...)

**Comment by brussee** [comment]
Also, the linked commit https://github.com/Tribler/tribler/commit/29b37ecc2f2acf55d8ca73c61c54dc6ba9052f35#diff-ea1baee298743f04208b92034249ed48R174

"Could not check torrent file: a ValueError was thrown" should be: "Check revealed ValueError: ..."

**Comment by qstokkink** [comment]
I had the same error in my unittests today: it was fixed by closing all of the Session's db handlers and calling Session.shutdown on tearDown(). @devos50 is this shutdown happening in the REST API tests?

**Comment by devos50** [comment]
@qstokkink are you still experiencing this issue?

**Comment by qstokkink** [comment]
@devos50 it seems to have been fixed.

**Comment by devos50** [comment]
great!
