### ISSUE TITLE
The video server should be rewritten so it's using Twisted

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2391]
Our current video server is dependent on `VideoPlayer` which in turn is dependent on the wx GUI. Moreover, the video server contains a lot of blocking code (`time.sleep` and `threading.event` occurrences), making the reactor and Tribler block when the user watches a video.

This video server should be rewritten in Twisted, making use of a static `File` object. The following should happen when a request to this video server is made:
- we should intercept the range in the request. This range should be converted to the offset of the requested file in bytes. If these bytes are available, just return the `File` object immediately. If they are not available, set the download priority of these bytes to the maximum and return a deferred that fires when these bytes are available.
- also, when a request comes in, we should check which file is requested and set the priority of other files on this download to zero.

**Comment by brussee** [comment]
@synctext So until this complete rewrite is done, we don't have a video server that will work on Android.

**Comment by synctext** [comment]
ai, bummer. @brussee
have you browsed the previously running code of various other projects? Three groups got it working. 

One I could find quickly: 
https://github.com/synctext/bsc-project/blob/master/Work/vlc-android/src/com/tudelft/triblersvod/example/TorrentVideoPlayerActivity.java

Seek is more complex then linear download.  better then download full and play. But first document existing code...

**Comment by synctext** [comment]
https://github.com/javto/Tribler-streaming/blob/master/Work/Tribler_Streaming/src/com/softwarrior/libtorrent/LibTorrent.java

**Comment by synctext** [comment]
Obviously: https://github.com/Tribler/tribler-android

**Comment by synctext** [comment]
tsap codebase with rpc calls for streaming:
https://github.com/wtud/tsap/blob/master/tsap/src/org/videolan/libvlc/LibVLC.java

btw refreshing to see all this old code..

**Comment by devos50** [comment]
@brussee I'm pretty sure that the video player works with the Twistd plugin (recently checked). I was probably confused about the 'VideoPlayer' class being dependent on the GUI but iirc, it works without. Can you try it? Just use curl or wget to test it.

**Comment by ichorid** [comment]
Probably fixed in #5301
