### ISSUE TITLE
Skipped multichain test_on_tunnel_remove_NoneType

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2410]
Regarding: https://github.com/brussee/tribler/blob/70584a84f3c7979911c08b01d0aa40f004ff7159/Tribler/Test/Community/Multichain/test_multichain_community.py#L166

> Test the on_tunnel_remove handler function to handle a NoneType

@pimveldhuisen What do you mean by this? Should it swallow or raise an Exception?

**Comment by pimveldhuisen** [comment]
The test was design to check if the function properly returns a TypeException when called with invalid types. The test broke however when the signature of on_tunnel_remove() was changed. I think commit https://github.com/Tribler/tribler/pull/2408/commits/25feb3fea84a519b8131892c030cde360eee3a33 should have fixed this. If we think testing for Expections is redundant/too much hasle, we can remove the test entirely.

**Comment by whirm** [comment]
@pimveldhuisen can you send a PR re-enabling the test?

**Comment by devos50** [comment]
@pimveldhuisen if you want a break from Gumby, can you take a look at this one?
