### ISSUE TITLE
Mac import error mock -> six / wraps

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2425]
The Mac test runner ```cannot import name wraps```
https://jenkins.tribler.org/job/GH_Tribler_PR_tests_mac/2205/testReport/nose.failure/Failure/runTest/

Probably due to wrong ```six``` version (from the os) that overrides the version installed from pip.
```
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.pyc
```
https://jenkins.tribler.org/job/GH_Tribler_PR_tests_mac/2206/testReport/nose.failure/Failure/runTest/

This blocks PR #2423 that solves tests instability of issue #2147 and #2409

**Comment by devos50** [comment]
I will take a look tomorrow when I'm at EWI.

**Comment by devos50** [comment]
@whirm @brussee fixed this one by removing the older `six.py`. The unit tests on OS X are now passing.

**Comment by brussee** [comment]
Excellent!
