### ISSUE TITLE
Link or embed vlc on Android

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2426]
Use external player for now: #2427

**Comment by whirm** [comment]
I would rather keep using the external player to simplify things for us. People can always install vlc.

**Comment by whirm** [comment]
@synctext what do you say?

**Comment by brussee** [comment]
It will either be a separate app or embedded on the Java side.
So from the python perspective it will always be external, unless we use pyjnius to launch it.

**Comment by whirm** [comment]
Sure, that's what I meant, having it embedded on the java side means we have to maintain it.

**Comment by brussee** [comment]
Right now the VLC installer package (.apk) is embedded in Tribler.apk and can be installed from there.
However it is also possible to have an embedded player just like the desktop version: https://github.com/Tribler/tribler/pull/2476/commits/69f8652a3e6d4b7798c0fe6541d1ba9a8f8980e6

**Comment by devos50** [comment]
I guess this one is completed according to the last comment?

**Comment by brussee** [comment]
@synctext wanted a true builtin player like desktop Tribler, that mimics the Java VLC app (I did compile the lib.so files successfully for Android, but did not create a Java GUI for it). However, @MaChengxin may move into a different direction with #2060.

**Comment by synctext** [comment]
hey!
Current solution is great for now. At some point compile and fully integrate VLC. Makes Tribler ready to use immediately.

**Comment by ichorid** [comment]
must be moved to a separate repository
