### ISSUE TITLE
No module named pbr.version

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2434]
What is this test trying to do with https://pypi.python.org/pypi/pbr ?
```
07-06 20:11:50.352 27393-27516/org.tribler.android:service_Triblerd I/Triblerd: test_unsubscribe_channel_not_subscribed (Tribler.Test.Core.Modules.RestApi.Channels.test_channels_subscription_endpoint.TestChannelsSubscriptionEndpoint) ... ok
07-06 20:11:50.356 27393-27516/org.tribler.android:service_Triblerd I/Triblerd: Failure: ImportError (No module named pbr.version) ... ERROR
07-06 20:11:53.028 27393-27516/org.tribler.android:service_Triblerd I/Triblerd: test_my_channel_endpoint_create (Tribler.Test.Core.Modules.RestApi.Channels.test_create_channel_endpoint.TestCreateChannelEndpoint) ... ok
```

**Comment by devos50** [comment]
@brussee I've never heard of that library before but it seems to be related to setuptools:

> PBR is a library that injects some useful and sensible default behaviors into your setuptools run.

Could you somehow print the import trace to see which module is importing this `pbr` module?

**Comment by brussee** [comment]
It turns out that the Mock module somehow requests pbr.version. We don't use it anymore currently afaik.
