### ISSUE TITLE
Tribler eats CPU even with no network

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2444]
##### Tribler version/branch+revision:

63f49df0c2ffca5da9bc8e80abee1aad1aa0645f, devel
##### Operating system and version:

Linux Debian 32-bit
##### Steps to reproduce the behavior:
1. Run Tribler with a number of downloads active
2. Turn off networking
##### Expected behavior:

Tribler gets into dormant state, not consumes [much] system resources until network is present again.
##### Actual behavior:

Tribler consumes about 6% of CPU. strace if full of `futex`, `gettimeofday`, `epoll_wait`, `clock_gettime`, `epoll_ctl`, `time`, `timerfd_settime`, `poll` syscalls. How often does Tribler need to look at the clock? Can't Tribler just sit still and wait for network?

I suspect Tribler may use CPU not effectively (i.e. drain battery) with the network present as well...

**Comment by ichorid** [comment]
Still true even for refactored 7.5 !

**Comment by egbertbouman** [comment]
On my Windows machine CPU drops as soon as I turn off networking. Looks like it could be OS dependent.

**Comment by xoriole** [comment]
CPU drops significantly when the network is turned off, so I guess this issue is fixed. Please feel free to reopen if the issue is still reproducible.

![Screenshot from 2021-07-14 15-22-20](https://user-images.githubusercontent.com/1442867/125629406-1c9382b2-c6c9-4727-8582-f32a2d6d8705.png)
