### ISSUE TITLE
Disable code coverage on some files

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2450]
I don't think it makes sense for some files to check for the code coverages. Examples include:
- `Tribler/vlc.py`
- The `Tribler/community/template` package
- The `Tribler/community/demers` package
- Various stand-alone scripts in `Tribler/Main`
- The `pymdht` package

Disabling checks on the packages above will substantially improve the code coverage statistics.

**Comment by whirm** [comment]
I think all standalone scripts should be moved outside of the Tribler package too.

**Comment by devos50** [comment]
This issue is not relevant anymore.
