### ISSUE TITLE
NoseXUnit plugin requires decades old coverage module 2.85 and conflicts with XCoverage requirement of coverage>=3.4

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2453]
07-09 18:45:49.827 2113-2254/org.tribler.android:service_Triblerd I/Triblerd: /data/user/0/org.tribler.android/files/lib/python2.7/site-packages/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin nosexunit = nosexunit.plugin:NoseXUnit: (coverage 4.1 (/data/data/org.tribler.android/files/lib/python2.7/site-packages), Requirement.parse('coverage==2.85'))

**Comment by brussee** [comment]
07-10 17:40:35.140 14654-14768/org.tribler.android:service_Triblerd I/Triblerd: /data/user/0/org.tribler.android/files/lib/python2.7/site-packages/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin xcover = nosexcover.nosexcover:XCoverage: (coverage 2.85 (/data/data/org.tribler.android/files/lib/python2.7/site-packages), Requirement.parse('coverage>=3.4'))

**Comment by whirm** [comment]
AFAIK we don't use this package at all

**Comment by brussee** [comment]
It is indeed integrated nowadays. Which explains the old version on pypi.
