### ISSUE TITLE
crowdsourcing Metadata 

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2455]
Allow any user to improve the metadata. Examples of existing approaches:

![image](https://cloud.githubusercontent.com/assets/325224/16715714/59c8ccf4-46e8-11e6-9936-605a1e80f79f.png)

![image](https://cloud.githubusercontent.com/assets/325224/16715701/13e58c90-46e8-11e6-865b-dd9d3c8d572c.png)

![image](https://cloud.githubusercontent.com/assets/325224/16715732/e7cae6cc-46e8-11e6-993a-4ac9e04da421.png)

Time slicing is too heavy for Tribler, out of scope. Just metadata.
![image](https://cloud.githubusercontent.com/assets/325224/16715718/6d8959c0-46e8-11e6-8f96-cab27f6c6dd1.png)

**Comment by lfdversluis** [comment]
A wiki-like approach? What would be editable within and outside Tribler?

**Comment by synctext** [comment]
Refocus this issue on torrent channels based on magnet links with rich metadata. Thesis goal is to deploy creation and search of rich metadata. More ambitious goal would be to do integrating of voting to obtain _trustworthy_ metadata.

Each channel can only be modified by the channel owner. Users vote on the quality of channels and quality emerges from the Tribler user collective. It is easy to copy an entire channel, re-use quality content from a channel, and re-mix channels. Thus leading indirectly to crowdsourcing. We specifically avoid the problem of edit wars, collaborative editing, and undo changes. This leads to a realistic master project. Only with an active community in place, we can move to the next stage and experiment with more sophisticated crowdsourcing models.

The torrent channel is expanded with a new type: _rich metadata channels_. Channels owners indicate the content type of each magnet link. We still keep it simple: 1 magnet link has 1 rich metadata description. First step is to create a simple editor inside Tribler. It supports several content types. Combining enriching of music, podcast, movies, vloggers, scientific articles, etc. :
![image](https://user-images.githubusercontent.com/325224/35151512-e58fd24e-fd1e-11e7-828d-3e032cf38932.png)
![image](https://user-images.githubusercontent.com/325224/35151574-1f0ffa4e-fd1f-11e7-9c9e-0fe9ec0e5b98.png)
![image](https://user-images.githubusercontent.com/325224/35151692-90c79fac-fd1f-11e7-83c0-4308e989962c.png)
Next step is then creating a new _rich metadata search_ community.

This master thesis puts the foundations in place for rich metadata. In the future we want to integrate collaborative tools. For instance, we assume scientific papers are available in Tribler and [we can semi-automatically create survey papers](https://github.com/synctext/HackingScience). Still out of scope:
![image](https://user-images.githubusercontent.com/325224/35151308-2cdbc726-fd1e-11e7-915d-5e9df6739165.png)

**Comment by synctext** [comment]
Demonstrates the content type idea (radio button or drop down):
![image](https://user-images.githubusercontent.com/325224/36090247-e947d2be-0fdf-11e8-883d-0a8eb7266f38.png)
Combining enriching of music, podcast, movies, vloggers, scientific articles, etc
A lot of metadata frameworks exist, [you could select this very old one](http://dublincore.org/documents/profile-guidelines/). Keep data model _very_ simple, never more then 4 fields per content type. We see how users like it, then expand based on real-world feedback.

**Comment by svanschooten** [comment]
@devos50 Do you have time to walk through the stack this afternoon? I have a doctors appointment in an hour, so I'll be at the lab after lunch. I've seen most of the code, and have looked into QT last week, but it still is a bit fuzzy.

**Comment by synctext** [comment]
He is on vacation this week. But others should be able to help.

**Comment by svanschooten** [comment]
First step: adding a field containing a single metadata entry (content type in this case, based on the Youtube VideoCategories API), and starting to structure the metadata information.
Started implementing a Metadata community, still bit fuzzy on what is needed there.
![tribler-content-types](https://user-images.githubusercontent.com/3600842/36384782-bf1e9584-1590-11e8-9a20-f61c725841c4.png)

**Comment by svanschooten** [comment]
Got my community running, peers can exchange messages (directed and broadcast), next step is to define the behavior of the community and the message types that can be sent.

@synctext should I look at a more branching metadata structure such as [here](https://github.com/svanschooten/tribler/blob/devel/Tribler/community/metadata/category.py) (based on youtube, piratebay and dublincore).
The other option would be to flatten the structure and create a more generic metadata structure (not following the classic and modern frameworks), and create something more generic. What would you advise?

Next step would be to structure the database and messages sent.

**Comment by devos50** [comment]
@svanschooten I would advise to keep it as simple as possible for now and not go wild with many different metadata types/complicated structures for now.

**Comment by svanschooten** [comment]
@devos50 welcome back! I agree, that is why I re-researched the desired structure, when I have something solid I'll implement a data structure which I can store in the database (also start implementing the distribution mechanics).

Due to a family crisis I have not been able to come to the lab Friday and today, but I have done some reading and thinking on the categorization issue: most content management systems use a tree based structure to define archetypes, subtypes and properties, though I have come across some interesting work. Twitter has published a [content categorization method](https://www.researchgate.net/publication/259889714_Twitter_Content_Categorisation_A_Public_Library_Perspective) that looks interesting, though it is not directly applicable to our case.

Based on these articles and papers I have opted to design a more 'flat' category structure, which I have [documented on my repository](https://github.com/svanschooten/tribler/blob/devel/Tribler/community/metadata/CATEGORIES.md).

**Comment by synctext** [comment]
#1150  is about to start soon. First finish this quick MAX 4 week prototype, then think how to build on top of scalable channels. When the're hopefully ready!

Write rich metadata on Trustchain? (e.g. so barter records, voting for channels, trading honesty, and metadata enrichment). Then we have 4 contexts of reputations to merge somewhat.

**Comment by svanschooten** [comment]
Fixed my packing issue, added category based payload types and added them to the community communication.
First working UI is done, now to couple the UI to the community: This includes basic parsing of datatypes based on regex (simplest method for now).
Major overhaul to the ContentType and Category models to make them easily adaptable.

![metadata_v1](https://user-images.githubusercontent.com/3600842/36752172-8a260b82-1c02-11e8-97a3-d848bc1e6b57.png)
The fields are dynamically added with the accessory parsing method, field name and label.
These are based on the fields defined in the Category models.

Only problem is that the community now can't discover the other peers, so the test script for the community does not receive anything... Test script checks is peer list is not empty each second, but stays empty.

**Comment by svanschooten** [comment]
- Implemented a lot more generics today, makes constructing metadata Categories much easier without a test for all types.
- Created an endpoint in the REST interface to let the UI talk to the MetadataCommunity.
- Added MetadataCommunity to the config and LaunchManyCore.
- Community mini-test working with twisted

Next (@synctext ??): writing metadata to persistence layer, more UI screens (only on torrent add for now) or better metadata models?

**Comment by svanschooten** [comment]
Looking at most metadata models, they approach it from an unstructured data angle, they usually have a (semi-) fixed tree structure for fields, but no simple and straightforward approaches to storing it using a relational database:
[This paper uses a generic field implementation with a mapping algorithm](http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=4426938).
If also found [this paper using oldschool RDF](https://link.springer.com/content/pdf/10.1007%2F3-540-48005-6_7.pdf).
[A patent that I can not understand...](https://patentimages.storage.googleapis.com/0a/e6/21/b8a48338c5bd81/US6505205.pdf).
[RFC-ish description of how dublincore was designed](https://www.rfc-editor.org/rfc/pdfrfc/rfc2413.txt.pdf).
[Theses guys developed a xml storing mechanism](http://delivery.acm.org/10.1145/510000/502939/p31-khan.pdf?ip=145.94.9.134&id=502939&acc=ACTIVE%20SERVICE&key=0C390721DC3021FF%2E512956D6C5F075DE%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35&__acm__=1520159750_ed39cc37c8240fa4966782fee60dddac).
[This pretty decent explanation on how you should see and organise metadata](http://www.dlib.org/dlib/april02/weibel/04weibel.html?).

I do not want to introduce more dependencies, but I think a noSQL storage method would be easiest?
Or maybe something generic like:
`
MetadataTable:
- (id) ID
- (string) infohash
- (string) title
- (string) category
- (string) content type

FieldsTalbe:
- (id) ID
- (id) metadata ID
- (string) name
- (string) value
`

**Comment by synctext** [comment]
> MetadataTable:
> - (id) ID
> - (string) infohash

Why do you want to make the ```infohash``` more unique with an ID ? :-)

Consider adopting [distributing scientific works as your test community](https://arxiv.org/help/bulk_data_s3) for your entire thesis {or something else additionally; http://bt.etree.org}. Or create a tool and test how many hours it takes to put stuff like 400k scientific journals in your rich metadata. a.k.a. ```Giga-Scraper``` idea. Next step: finish prototype and create a .pdf seeding channel.

Just make an music table, movie, clip, series, vlog, ebook, adult entertainment, other ~~images~~ table etc. Keep it simple for your 4-week prototype. try to remove content and subtype construct: just 1 category level. ID3 simple, for instance, no fancy XML, nosql, or RDF. Just a _fixed_ structure please. Probably per content type. In 1996 Eric Kemp created ID3, the defacto framework for audio metadata. Strings are either space- or zero-padded. Unset string entries are filled using an empty string. ID3v1 is 128 bytes long. [Table with fields is copied from Wikipedia](https://en.wikipedia.org/wiki/ID3#Layout)

Field | Length | Description
------------ | -------------  | ------------- 
header |	3 |	"TAG"
title |	30	|30 characters of the title
artist|	30|	30 characters of the artist name
album|	30|	30 characters of the album name
year|	4|	A four-digit year
comment|	28 or 30|	The comment.
zero-byte|	1|	If a track number is stored, this byte contains a binary 0.
track|	1|	The number of the track on the album, or 0. Invalid, if previous byte is not a binary 0.
genre|	1|	Index in a list of genres, or 255

ID3v1 pre-defines a set of genres denoted by numerical codes. Keeps it trivial...

Future: #3484 After this 4-week prototype is completed, explore more advanced architecture. We are prototyping using our Trustchain idea as the only storage paradigm in Tribler. It would contain: bandwidth barter transactions, voting for channels, trading of bandwidth coins #3326. Additionally, possibly rich metadata of channels; this thesis. Warning: this idea for yet another Tribler overhaul would take years to complete and get stable!

**Comment by svanschooten** [comment]
The underlying data model has bee simplified and abstracted more, to provide generic reading and setting handles. Is completely flat now.
Also a basic database and repository implementation is done, both with an in-memory and persistent layer.

TODO: 
- insert metadata into the database from the community.
- extend the code with docs.
- an UI implementation for showing the metadata has to be implemented.
- tests

**Comment by svanschooten** [comment]
**Refined thesis subject: Searching in enriched metadata using deduplicated tag clouds.**
 - Use tokeninzing to revert word to stem form, then linking it in the tag cloud.
 - Use k-means clustering to find subclouds to create more rigid linking, overlap in clouds could indidate same/similar entries (partly removes duplication, word polymorphism and locality issues)
 - Cloud distribution during search by receiving k-linked clusters from near neighbours.
 - Fluid metadata structure, community defined data.
 - Voting on better tags will create weighted clouds, making deduplication easier.

**Comment by devos50** [comment]
It might be helpful for you to sync with @xoriole, your ideas seems to overlap somewhat.

**Comment by xoriole** [comment]
@devos50 It was quite a long discussion. Lots of ideas floating. We'll see how the design materializes.

**Comment by ichorid** [comment]
related to #6217

**Comment by synctext** [comment]
[tagging and RSS historical analysis plus failings](https://news.ycombinator.com/item?id=31459103)
