### ISSUE TITLE
Blocking add_torrent in network_create_engine_wrapper in LibtorrentDownloadImpl

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2465]
@lfdversluis Made the method network_create_engine_wrapper to return a deferred and I added a failure case.
This should be refactored to be async:

From: http://www.rasterbar.com/products/libtorrent/manual.html#async-add-torrent-add-torrent

> You add torrents through the add_torrent() function where you give an object with all the parameters. The add_torrent() overloads will block until the torrent has been added (or failed to be added) and returns an error code and a torrent_handle. In order to add torrents more efficiently, consider using async_add_torrent() which returns immediately, without waiting for the torrent to add. Notification of the torrent being added is sent as add_torrent_alert.

**Comment by ichorid** [comment]
refactored the :fire::smiling_imp::fire:  out of the stuff
