### ISSUE TITLE
Callback not called when fetching metainfo from DHT

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2477]
When performing some experiments with fetching metainfo from the DHT, I noticed that the callback passed in the `download_torrentfile` method in `Session` is not called. Also, according to the comments above this method, the callback is called with the fetched metainfo but from the code, this does not appear to be the case.

The whole callback mechanism when fetching torrents from the DHT should be refactored so it is using deferreds instead of manual callback methods.

**Comment by ichorid** [comment]
refactored the stuff to hell, so probably solved already
