### ISSUE TITLE
Decoding error in add torrent to channel (with tdef) endpoint

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2478]
When adding a torrent to a channel with the base64-encoded data, the data encoding used is `application/x-www-form-urlencoded`. In this encoding, plus characters `+` are replaced by a space when decoded. This makes the base64 data corrupt and base64-decoding is not possible anymore.

There might be more characters which are replaced but I'm not sure about that.

**Comment by whirm** [comment]
Let's switch to the raw binary upload as we said

**Comment by devos50** [comment]
Well, it has been fixed by making sure that the data is properly URL-encoded but uploading raw binaries might be better. It requires a bit more work though.
