### ISSUE TITLE
test_remote_channel_search: timeout expired before end of test (120.000000 s.)

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2486]
```
Tribler.Test.test_remote_search.TestRemoteChannelSearch.test_remote_channel_search (from nosetests)
Failing for the past 1 build (Since Failed#2866 )
Took 2 min 0 sec.
Error Message

timeout expired before end of test (120.000000 s.)
```
https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/2866/testReport/junit/Tribler.Test.test_remote_search/TestRemoteChannelSearch/test_remote_channel_search/

**Comment by whirm** [comment]
Remember to paste the relevant stacktraces/logs as the build logs get rotated pretty quickly
