### ISSUE TITLE
Current allchannel experiment errors.

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2489]
Found at least one (haven't checked other nodes) node crashing in build 976.

https://jenkins.tribler.org/job/Tribler/job/Experiments/job/AllChannel+Channelcommunity_devel/976/artifact/output/localhost/node057/00033.err/*view*/

In build 977 several (I've searched this one thoroughly): 
### node 029

https://jenkins.tribler.org/job/Tribler/job/Experiments/job/AllChannel+Channelcommunity_devel/977/artifact/output/localhost/node029/process_guard.log
1. https://jenkins.tribler.org/job/Tribler/job/Experiments/job/AllChannel+Channelcommunity_devel/977/artifact/output/localhost/node029/00029.err/*view*/
2. https://jenkins.tribler.org/job/Tribler/job/Experiments/job/AllChannel+Channelcommunity_devel/977/artifact/output/localhost/node029/00041.err/*view*/
3. https://jenkins.tribler.org/job/Tribler/job/Experiments/job/AllChannel+Channelcommunity_devel/977/artifact/output/localhost/node029/00049.err/*view*/
### node 042

https://jenkins.tribler.org/job/Tribler/job/Experiments/job/AllChannel+Channelcommunity_devel/977/artifact/output/localhost/node042/process_guard.log
1. https://jenkins.tribler.org/job/Tribler/job/Experiments/job/AllChannel+Channelcommunity_devel/977/artifact/output/localhost/node042/00004.err/*view*/
### node 043

https://jenkins.tribler.org/job/Tribler/job/Experiments/job/AllChannel+Channelcommunity_devel/977/artifact/output/localhost/node043/process_guard.log
1. https://jenkins.tribler.org/job/Tribler/job/Experiments/job/AllChannel+Channelcommunity_devel/977/artifact/output/localhost/node043/00047.err/*view*/
### node 054

https://jenkins.tribler.org/job/Tribler/job/Experiments/job/AllChannel+Channelcommunity_devel/977/artifact/output/localhost/node054/process_guard.log
1. https://jenkins.tribler.org/job/Tribler/job/Experiments/job/AllChannel+Channelcommunity_devel/977/artifact/output/localhost/node054/00040.err/*view*/

**Comment by synctext** [comment]
_exceptions.AttributeError: 'NoneType' object has no attribute '_channelcast_db'_

Thats a bad TraceBack..
This is without your Storm enhancement?

**Comment by lfdversluis** [comment]
This is the old channel experiment, it's not even my job. I am only using this as a reference point for my work :)

**Comment by synctext** [comment]
all seems the same error, but only looked briefly

**Comment by lfdversluis** [comment]
Yes, they are the same. I had this exact error too and figured it was due to my async work, but apparently that's not the case. This probably means that a node is not done yet with finishing going online. If it's not online yet and has to join the community (as the scenario dictates) then you get this error. This code should be completely synchronous but apparently we have a race condition.

**Comment by lfdversluis** [comment]
To further reinforce the argument of a race condition: under heavy load it seems to trigger more. When my work was committing per database interaction I saw this a lot more.

**Comment by whirm** [comment]
This looks like a shutdown stacktrace?

**Comment by qstokkink** [comment]
We wont fix this, instead we will rely on the new implementation of #3615 to obsolete this issue.
