### ISSUE TITLE
test_bootstrap.py:TestBootstrapServers.test_servers_are_up is consuming all the memory on bbq

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2490]
Cannot run things on BBQ via Jenkins now.

https://jenkins.tribler.org/computer/bbq/executors/0/causeOfDeath

**Comment by ardhipoetra** [comment]
I think it has been like this since this morning. Do you have access to the physical machine (ssh?) to check this out?

**Comment by lfdversluis** [comment]
No, only @whirm does

**Comment by whirm** [comment]
There where a few of this taking all the memory on bbq: 
```
jenkins  38963  1.8 63.9 46680044 42121540 ?   Sl   Jun02 1386:47 /usr/bin/python /usr/bin/nosetests -v -l test-bootstrap-summary dispersy/tests/test_bootstrap.py:TestBootstrapServers.test_servers_are_up
```

**Comment by whirm** [comment]
If it starts again I'll hook in the debugger.
