### ISSUE TITLE
Error in batercast4 tests

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2492]
https://github.com/Tribler/tribler/blob/devel/Tribler/Test/test_bartercast4_community.py#L55

No Idea why test currently works, but this is an attribute, not a function (`running`). Calling this in the `CallCondition` definitely returns an error. Fixing it in my PR.

**Comment by qstokkink** [comment]
`self.CallCondition` calls `has_finished()` which returns the negation of of the `running` attribute of a `LoopingCall`. This should work just fine. What's the problem/error?

**Comment by lfdversluis** [comment]
Ah my bad, was late when I encountered it. It errored on my side, probably because of my changes I guess. In any case, I fixed it on my side and this one looks fine too. Closing.
