### ISSUE TITLE
Tests in test_twisted_rawserver are racy

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/tribler#2495]
Tests [like this one](https://github.com/Tribler/tribler/blob/devel/Tribler/Test/test_twisted_rawserver.py#L43) currently work fine because they are scheduled from the nose thread onto the twisted thread. However, with my deferred refactor this test will now run inside the (nose) reactor, and suddenly start behaving racy. The list is missing items sometimes or they are in a different order.

**Comment by devos50** [comment]
This issue has been fixed in #2573
