### ISSUE TITLE
Prioritization of the pieces is not correctly applied when seeking in a downloading video

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2508]
When streaming a download and seeking in that video immediately, it appears that the prioritization of the pieces is not correctly done. It looks like libtorrent always first finishes downloading the first 10% of the download before it jumps to the pieces being requested.

I suspect that this bug lies in the prioritization system but it might also be some issue in libtorrent (which I don't expect actually but it is a possibility).

**Comment by synctext** [comment]
this is a quick fix for video header downloading.

 You need the first MByte(s) for seek. Some formats also need the last MByte, e.g. trailer, before seek works.

**Comment by devos50** [comment]
Ah in that case it's not a bug but a feature. I will close this issue.
