### ISSUE TITLE
It shouldn't be possible to create Channel with no names

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#2525]
Right now it's not possible to do it from the GUI but it still is possible to do it because of a mistake on the code or via the API.

**Comment by devos50** [comment]
It's not possible anymore with the code changes in #2739 (in particular, https://github.com/Tribler/tribler/pull/2739/commits/ed6f7441b0929756cc0267f842af4ed9f73ee95c). This is both addressed in the GUI and the core.
