### ISSUE TITLE
VLC ? 

### ISSUE THREAD

**Issue by jemadux** [Tribler/tribler#2526]
i dont like to use vlc but i want to totem .. why there is that dependency on vlc ?

**Comment by whirm** [comment]
We use libvlc for the embedded player.

**Comment by synctext** [comment]
@jemadux we would love to integrate more video players in our client.
You can use Totem also. After downloading using Tribler, goto your file system browser and activate Totem from there. Should work in Win/Linux/Mac...

Hope this answers your question.
