### ISSUE TITLE
Events endpoint not started first

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2527]
The events start and upgrade finished events come AFTER other dispersy events. This should not be the case.

```
08-22 17:19:42.113 8950-9223/org.tribler.android:service_Triblerd I/Triblerd: WARNING:Could not resolve bootstrap candidate: dispersy2.st.tudelft.nl:6422
08-22 17:19:42.113 8950-9223/org.tribler.android:service_Triblerd I/Triblerd: WARNING:Could not resolve bootstrap candidate: dispersy1.st.tudelft.nl:6421
08-22 17:19:42.183 8912-8972/org.tribler.android V/responseHeaders: Transfer-Encoding: chunked
08-22 17:19:42.183 8912-8972/org.tribler.android V/responseHeaders: Date: Mon, 22 Aug 2016 15:19:42 GMT
08-22 17:19:42.183 8912-8972/org.tribler.android V/responseHeaders: Content-Type: text/json
08-22 17:19:42.183 8912-8972/org.tribler.android V/responseHeaders: Server: TwistedWeb/15.5.0
08-22 17:19:42.203 8912-8972/org.tribler.android V/readLine: {"type": "events_start"}
08-22 17:19:42.313 8912-8972/org.tribler.android D/parseEvent: empty event body: {"type": "events_start"}
08-22 17:19:42.318 8912-8972/org.tribler.android V/onEvent: EventsStartEvent; handlers: 1
08-22 17:19:42.318 8912-8972/org.tribler.android V/readLine: {"type": "upgrader_finished"}
08-22 17:19:42.318 8912-8972/org.tribler.android D/parseEvent: empty event body: {"type": "upgrader_finished"}
08-22 17:19:42.318 8912-8972/org.tribler.android V/onEvent: UpgraderFinishedEvent; handlers: 1
08-22 17:19:42.318 8912-8972/org.tribler.android V/readLine: {"type": "tribler_started"}
08-22 17:19:42.318 8912-8972/org.tribler.android D/parseEvent: empty event body: {"type": "tribler_started"}
08-22 17:19:42.323 8912-8972/org.tribler.android V/onEvent: TriblerStartedEvent; handlers: 1
```

**Comment by devos50** [comment]
@brussee which other dispersy events do you mean? Do you mean the logging from the Dispersy library?

`08-22 17:19:42.113 8950-9223/org.tribler.android:service_Triblerd I/Triblerd: WARNING:Could not resolve bootstrap candidate: dispersy2.st.tudelft.nl:6422`

**Comment by brussee** [comment]
Sometimes a huge list of discovered channels is outputted at the same time as the started events. I understand that dispersy may log before that, although it makes no sense that resolving the bootstraps is faster than the very very first thing Tribler should do: output startup progress events.

**Comment by lfdversluis** [comment]
If it's synchronous it may be that dispersy is started first which will output said channels? Then the startup procedure continues and Tribler outputs its events? I don't know the code so just naming a possibility here.

**Comment by devos50** [comment]
Actually, after some recent refactoring, the events endpoint is started very early during the boot process, even before opening the database and way before starting Dispersy. Also, we removed the events buffer a while ago. So I think this issue is not relevant anymore. Please reopen it if it needs more attention or if I missed something.
