### ISSUE TITLE
Feature Request: Add Tracker to Torrent

### ISSUE THREAD

**Issue by 0x27** [Tribler/tribler#2529]
A good feature to have would be the ability to add a tracker to a torrent that appears to be badly seeded (or relying on some dead trackers). For whatever reason, this usually works out pretty well for me in other clients to "revive" torrents that initially seem to be dead.

**Comment by gitbugged** [comment]
Definitely interested in this feature as well. Over 90% of the trackers included are dead, which make it much more difficult for Tribler to get started.

I wrote python hack to wipe all trackers from the entire DB and inject my own, it's not overly pretty but it works, and maybe someone else can find it useful.

[injecttrackers.py](https://github.com/Tribler/tribler/files/1321870/injecttrackers.txt)

**Comment by qstokkink** [comment]
We have facilities to add trackers to downloads:

https://github.com/Tribler/tribler/blob/3e6a3e20012d97e369b5384f4b81b1e35dd4d95d/src/tribler/core/libtorrent/download_manager/download.py#L867-L870

We could implement this feature by simply exposing this method to the GUI.

**Comment by qstokkink** [comment]
I tried the approach that I mentioned above and this seems to work just fine. Now, I need an GUI design. I'm thinking of adding a column to the `trackers` table of a download's details:

<table>
<tr><th>Add/Remove</th><th>Tracker</th><th>Status</th></tr>
<tr><td></td><td>[DHT]</td><td>Working</td></tr>
<tr><td></td><td>[PeX]</td><td>Working</td></tr>
<tr><td>( Remove button )</td><td>Tracker 1</td><td>Working</td></tr>
<tr><td>( Remove button )</td><td>Tracker 2</td><td>Not contacted yet</td></tr>
<tr><td>( Add button ) </td><td colspan=2>[ INPUT FIELD ]</td></tr>
</table>

**Comment by qstokkink** [comment]
When solving this, we should probably also include #1797 and allow the GUI to move trackers "up and down" to increase/decrease their priority.

**Comment by qstokkink** [comment]
My initial prototype is here: https://github.com/qstokkink/tribler/tree/add_tracker_add

I think I'll drop the initial prototype though. After sleeping on this, I think it might be better to simply have a right-click context menu that allows you to change tracker priority, remove trackers, and add a tracker.

**Comment by qstokkink** [comment]
We can use `react-sortable-hoc` to re-order trackers to change their priority.

Demo: http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/drag-handle?_k=29udje
Source: https://github.com/clauderic/react-sortable-hoc/blob/master/examples/drag-handle.js
