### ISSUE TITLE
Thesis: Using distributed blockchains to cultivate trust in a peer group

### ISSUE THREAD

**Issue by pimveldhuisen** [Tribler/tribler#2533]
## Thesis: Using distributed blockchains to cultivate trust in a peer group
- Design a system that can account for user interactions that is:
  - Accurate
  - Tamper-proof 
  - Scalable
- Implement this system
- Test and evaluate this system
- Use this system to select peers that can be trusted, and interact with them further to create self reinforcing trust.

**Comment by synctext** [comment]
"Cultivating online trust in complex self-organising systems" Nice title/storyline.

Background story: we tried multichain, needs churn resilience, Tribler future-proof architecture means creating a generic "trust cultivation" module. Essential requirement is that this can be re-used in other systems, proven to work in Tribler.

Self-reinforcing trust is a more cold and rational term. Cultivating is more associated with organic and human touch. Interesting.

**Comment by synctext** [comment]
Design: why create records every 10min, not every 10MByte ?

Experiments brainstorm:
 - Load balancing experiment (live walk peer overload, already a Gumby graph)
 - Record requesting methods experiments
 - scalability and long-term viability usage (long-term == 10 years)
 - SCIENCE: graph sampling, informativeness and accuracy of sharing ratio (Dedault Dispersy wlak, live walk, etc.). Scenario: join existing 100s Dispersy peers with filled database, +1 new user.

October goal: generate scenario, based on real behavior from our crawl. Either: give existing records or do 1 download/second for 3 hours == 10k downloads of Multichain records.

**Comment by synctext** [comment]
Public ongoing thesis text : https://www.sharelatex.com/project/573db2896f2d756841e3def8

**Comment by synctext** [comment]
- 3-page intro is too compressed
 - avoid layer and architecture when talking about components
 - Relate to the Hoffman model (http://dl.acm.org/citation.cfm?id=1592452)
 - term to use: tamper-proof or attack-resilience ?
 - emergent problem or just requirement of a solution?
 -

**Comment by synctext** [comment]
ToDo for thesis roadmap:
 - [Gumby PR fix &cleanup](https://github.com/Tribler/gumby/pull/240)
 - Live edges: #2458  Gumby evaluation and deployment
 - Load balancing experiments, etc. See Above.
 - #2087 Design and protocol description for Thesis Design Chapter.

**Comment by synctext** [comment]
Related work:
 - [Rep on the block : A next generation reputation
system based on the blockchain](http://www.the-blockchain.com/docs/A%20next%20generation%20reputation%20system%20based%20on%20the%20blockchain.pdf)
 - [Feedback based reputation on top of the Bitcoin Blockchain](https://arxiv.org/pdf/1502.01504.pdf)

**Comment by synctext** [comment]
Experiments:
 - walker: (un)directed, (non)live and most-reputed-peer first
 - load balancing, discovery, etc.

**Comment by synctext** [comment]
Discovery experiment (Gumby) scenario:
 - join existing 100-1000 Dispersy peers with filled database, +1 new user.
 - Existing peers all have filled databases and converged after running for 1 hour
 - Existing peers know each other "trust vectors", simply multi-chain record are distributed
 - Focus of all numerical results is on the +1 peer event, after 1 hour.
 - For this new peer: each walk is recorded and discovered Multichain records are logged
 - Key outcome: X-axis the

**Comment by synctext** [comment]
Trace-driven simulator, inside Jenkins: https://jenkins.tribler.org/job/Tribler/job/Experiments/job/multichain/job/walker/ws/

**Comment by synctext** [comment]
bug: the exploration is not monotone increasing.

**Comment by pimveldhuisen** [comment]
> bug: the exploration is not monotone increasing.

To clarify: the exploration _is_ actually monotonically increasing, the bug is in the plot script, which renders this in a weird way. Should still be fixed ofcourse.

**Comment by synctext** [comment]
Revisiting the non-backwards compatible design with deep walker integration. Unified primitive for:
  - peer discovery
  - NAT puncturing
  - Trust record collection

Thus together forming _trusted peer discovery suitable for NAT constrained Internet connections_.

![multichain_walker_design__2016](https://cloud.githubusercontent.com/assets/325224/21257833/6db69ebc-c37a-11e6-91c6-1cfaabf0e46a.png)

**Comment by synctext** [comment]
Recent changes: design chapter
[msc_thesis (7).pdf](https://github.com/Tribler/tribler/files/693650/msc_thesis.7.pdf)

**Comment by synctext** [comment]
Good. Finish "Live edges" work in Dispersy, repeat nice load balancing graphs.
Measure discovery and dissemination of records. See experiments above (+1 peer, etc.)

**Comment by synctext** [comment]
[msc_thesis___Pim_Veldhuisen (1).pdf](https://github.com/Tribler/tribler/files/779833/msc_thesis___Pim_Veldhuisen.1.pdf)
  - base problem description on theory ( reciprocity, repeated interaction, 5-rules for evolution of cooperation, etc)
  - Design of Record Creation functionality
  - 3.2 Asynchronicity ==> concurrency
  - 3.3 Half-block Protocol ?
  - missing Chapter 4 intro
  - ```a shitload of blocks```
  - Page 25, online_nodes : connected_neighbors

**Comment by synctext** [comment]
[msc_thesis___Pim_Veldhuisen (2).pdf](https://github.com/Tribler/tribler/files/821411/msc_thesis___Pim_Veldhuisen.2.pdf)

**Comment by synctext** [comment]
4.2 Experiments; Would call it emulation, not simulation.
4.3.2 Alpha Release of Multichain
Start chapter 5 with What and Why. Role of Alpha parameter.
_Knowing who has cooperated in the past is a good building block for durable future cooperation. In this chapter we experiment with various algorithm to efficiently discover who cooperated in the past. Issues such as load balancing and discovery speed are key._

**Comment by synctext** [comment]
Page 3, try to say in first line why Tribler is relevent here.
2.2    The Multichain : not a problem, e.g. tamper-proof records

**Comment by synctext** [comment]
Abstract
'that can achieve this idea in BitTorrent networks' please polish
'The fist step'
'The Multichain system as a whole is not yet completed, but this' make stronger and positive
'1986 Science article Garrett Hardin' 1968

**Comment by YourDaddyIsHere** [comment]
[Leveraging blockchains to establish cooperation - Pim Veldhuisen - Master's thesis.pdf](https://github.com/Tribler/tribler/files/1061660/Leveraging.blockchains.to.establish.cooperation.-.Pim.Veldhuisen.-.Master.s.thesis.pdf)

Final thesis from delft repository

**Comment by themusicgod1** [comment]
1) p19 sha256 is introduced without citation

2) p21-23 re whitewashing -- If someone's client is honestly written but broken, it might accidentally lie. I can't count the number of times that tribler has crashed for me while I tried to get it to upload something (in fact it just did so while I was writing this post) ...at least for me, 99%+ of the time that I'm not uploading something I download it's because of a software bug.  The exponential step-up of trust on page 22 is a clever way of dealing with this.  It's certainly a blurry line between the cases of 'attacker' and 'broken code' but still, not all lies are intentional - intent should matter when punishing liars in principle.  How might this look in practice?  If A downloads from B, B has record of A downloading but A "forgets" and continues on as if nothing happened.  Would A be a liar in this case and punished for it?

3)
>  Therefor, an optimal value for φ lies likely around 0.05, depending on the exact characteristics of the network.

φ is dependent upon how important reputation is.  If the only purpose of reputation is to encourage the shadow of the future, maybe 0.05 is ok.  But depending on the ratio of attackers/buggy clients versus honest nodes, the value of reputation may be different to different network participants.

**Comment by synctext** [comment]
Final .PDF: https://repository.tudelft.nl/islandora/object/uuid:0bd2fbdf-bdde-4c6f-8a96-c42077bb2d49/datastream/OBJ/download
