### ISSUE TITLE
[FEATURE REQUEST] Sending Tribler to tray.

### ISSUE THREAD

**Issue by ghost** [Tribler/tribler#2536]
The software is amazing as is. It'd be amazing to send Tribler to tray and not worry about accidentally closing the window.

**Comment by lfdversluis** [comment]
@devos50 I recall you have this implemented in the new GUI?

**Comment by devos50** [comment]
@lfdversluis at the moment when you press the close button in the new GUI, Tribler is closed completely. @ghost thanks for the suggestion, I will take a look at it!

**Comment by devos50** [comment]
Duplicate of #1054.
