### ISSUE TITLE
TrustChain: Implement limited requests for blocks by a crawler walker

### ISSUE THREAD

**Issue by pimveldhuisen** [Tribler/tribler#2538]
Blocks can currently only be requested in a way aimed at retrieving the complete state by the crawler. When regular nodes will also collect some blocks we require more precise requests for specific blocks for performance/scalabillity reasons. This can be implemented by:
- [ ] Allowing 'crawl' requests for a different public key. (Node A can ask node B for all blocks it has from the chain of node C)
- [ ] Allow a limit parameter in 'crawl' requests (Node A can ask node B for it's last x blocks)
- [ ] Allow for gradual exploration of a chain by sending a request for blocks around a certain interval. There are three parameters: start_of_know, stop_of_know and limit. The first two parameters are sequence numbers which denote blocks that the requesting node already has. When node A sends a request to node B, node B will send its most recent blocks, until it reaches either the limit, or the stop_of_know. If the limit is reached first, these blocks will be sent. If the stop_of_know block is reached first, the node will proceed with sending the most recent blocks that are less recent than start_of_know, until the limit is reached.

**Comment by ichorid** [comment]
Is this still actual, or we're done with Trustchain? @qstokkink , @grimadas , @devos50 ?

**Comment by devos50** [comment]
Yes, this kind of crawl has been implemented already in TrustChain!
