### ISSUE TITLE
[Bug] Erratic channel selection behaviour

### ISSUE THREAD

**Issue by kazerniel** [Tribler/tribler#2543]
##### Tribler version/branch+revision:

6.5.2
##### Operating system and version:

Win7 Pro x64
##### Expected behavior:

When I click on a channel, it should show the channel's name and information below.

When I click visit channel, it should show the name of the channel and the torrents belonging to the channel I selected.
##### Actual behavior:

When I click on a channel, it often shows the correct channel's information on the bottom, but there are some channels where it just refuses to, and repeatedly shows some other channel's information instead. This behaviour is erratic, often it shows me the correct information belonging to a channel once, but after clicking on another channel, it refuses to show the first selected channel's information when I click on it again. When I go down the channel list by keyboard up/down keys, there are some missing and duplicate entries in the bottom box this way. (Sometimes waiting a bit solves the issue, other times it doesn't.)

When I click visit channel, it adds another layer of erratic behaviour, sometimes it shows the torrents of the channel I selected, but on the top shows the wrong channel name (and in the left sidebar a third, different channel name). Other times neither the torrents or the title on top belong to the channel I clicked to visit, but some other channel I visited before.
##### Steps to reproduce the behavior:

Start Tribler, try to click on various channels, optionally click on visit channel.

**Comment by lfdversluis** [comment]
@devos50 I think this is a wx bug, what do you think?

**Comment by synctext** [comment]
hi people, tricky to understand this problem.

Tribler may take 20+ seconds to respond. Especially if you are subscribed to over a dozen channels. It sometimes is slow to respond.

Could you perhaps make a screenshot of the problem?

**Comment by kazerniel** [comment]
Screenshots here: http://imgur.com/a/xd3M7

**Comment by lfdversluis** [comment]
Looks like a visual bug, should be inspect just to make sure. Unless @devos50 can confirm this issue is not present in the new GUI?

**Comment by devos50** [comment]
@kazerniel @lfdversluis I believe this is a GUI issue and I haven't seen this kind of behaviour in the new GUI. Probably, the updating of the bottom splitter view is not performed correctly. We won't give much priority to this and I will leave this issue open until the new GUI (#2153) is ready and we have verified that this kind of behaviour is not present in the new interface.

**Comment by devos50** [comment]
We don't have the bottom splitter view anymore when selecting channels and torrents so this issue can be considered as invalid.
