### ISSUE TITLE
change anonimity level

### ISSUE THREAD

**Issue by sirber** [Tribler/tribler#2546]
##### Tribler version/branch+revision: #####
6.5.2
##### Operating system and version: #####
Windows 10

Hi, would be nice to have an option to change anonimity level once the torrent have been added. Also have the option to set the anonimity level when adding a torrent.

**Comment by devos50** [comment]
Thank you for your suggestion. This is indeed something I've been considering to implement but due to time constraints, I haven't been able to implement this.

I hope we can have this feature in the Tribler 7 release.

**Comment by khonkhortisan** [comment]
https://github.com/Tribler/tribler/issues/2111

**Comment by synctext** [comment]
thnx. Yes, duplicate. closing..
