### ISSUE TITLE
Download slow

### ISSUE THREAD

**Issue by PingouinArmy** [Tribler/tribler#2556]
Hello I'm new on Tribler and I'm a a little bit lost.
I have a very very slow download even if I'm in fast download/low protection mode. What can I do with bittorrent it takes me less than 20 minutes for 1 giga and here I have 8 hour to go.
(I'm downloading from another torrent website because the channels doesn't seems to have what I look for) 
Hope someone can help me out because I like thios project and would be sad to have to leave it
In hope for an answer
Pingouin Army
PS : I don't have a fluent english so please excuse my errors

**Comment by synctext** [comment]
thnx for reporting this.
We're working hard to make Tribler faster. We need more people to donate their upload bandwidth...

**Comment by PingouinArmy** [comment]
What do you mean by donating bandwith if it's not to much asked ?

**Comment by ichorid** [comment]
Seems dead. @PingouinArmy  feel free to reopen.
