### ISSUE TITLE
New feature: Full screen and pause playback in the Player

### ISSUE THREAD

**Issue by slrslr** [Tribler/tribler#2558]
Hello,

i found being unable to quickly control playback in the Tribler media player.

Can You please allow Esc key to quit full screen.
Space key or mouse left click to pause/resume/start playback.
Doubleclick video to show fullscreen
(same as Media Player Classic)

Thank you for considering

**Comment by devos50** [comment]
Hi,

A full screen mode is currently implemented in the new GUI when playing a video. This mode can be left by pressing the Esc button.

Your second suggestion is still pending (using the space/mouse left click key to control playback). I will implement this when I finish the work on the user interface.

**Comment by devos50** [comment]
@slrslr the second suggestion is also fixed in the new GUI: https://github.com/Tribler/tribler/pull/2153/commits/8cccf2c34c00f2489148ed8fa8cad7bce3dc8642 👍
