### ISSUE TITLE
Big files download stopping during the download

### ISSUE THREAD

**Issue by PingouinArmy** [Tribler/tribler#2562]
Hi, just wanted to report another error who seems to occur on large files download. The peers are connected but I don't receive anything from them.
Hoping it can help you or you can help me 
![screenshot_4](https://cloud.githubusercontent.com/assets/22530759/19050586/86202e6e-89af-11e6-89c4-9cb6fd00165a.png)

**Comment by devos50** [comment]
The availability is quite low (0.63), probably indicating that the whole file is not available in the network so I don't think this is a Tribler issue. Please reopen the issue if it happens for all of your downloads so we can investigate it better. Thanks!
