### ISSUE TITLE
tribler is running but window not displayed

### ISSUE THREAD

**Issue by adbstyle** [Tribler/tribler#2565]
Issue type: Bug

#### Please, fill all relevant items:
- [no] I have read CONTRIBUTING.md
- [no] I have tried with the latest pre-release version and I still can reproduce the issue.
##### Tribler version/branch+revision:

6.5.2 for os x
##### Operating system and version:

os x sierra 
version 10.12
##### Expected behavior:

tribler window is displayed after starting the application / when application is running - like any other application.
##### Actual behavior:

tribler window is not displayed after starting the application
![image](https://cloud.githubusercontent.com/assets/1103935/19210669/db88b75e-8d29-11e6-91c7-db279490ae2e.png)
although it is visible when displaying all windows
![image](https://cloud.githubusercontent.com/assets/1103935/19210672/09b7e92e-8d2a-11e6-8de7-afe4959a89a0.png)
clicking on the windows show again the emtpy desktop - does not display the tribler window
##### Steps to reproduce the behavior:

start/run tribler
![image](https://cloud.githubusercontent.com/assets/1103935/19210641/e71633b8-8d28-11e6-929c-dfed650bc409.png)
tribler is starting
![image](https://cloud.githubusercontent.com/assets/1103935/19210646/061a6d60-8d29-11e6-8877-da86caaa3f6f.png)
tribler is running
![image](https://cloud.githubusercontent.com/assets/1103935/19210653/2b2f237a-8d29-11e6-9817-5e33df84e9a2.png)

**Comment by devos50** [comment]
Thank you for your bug report. I didn't update my laptop to Sierra yet so I'm unable to verify this, however, I heard some people having the same issue with other applications.

I'm not sure whether this will be fixed for the old wx GUI. I will make sure that the new GUI works on Sierra.

**Comment by devos50** [comment]
I've tested the latest alpha (https://jenkins.tribler.org/job/Build-Tribler_OSX_devel/) and it's working correctly on Sierra.
