### ISSUE TITLE
Warning: torrent collecting directory not found, skip: None

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2579]
Rebased from #2523 to #2576 on devel and got the warning as stated in the title (in the log on Android). However the default collected_torrents dir exists and is non-empty.

torrent_upgrade65.py line 55:
`self._logger.warn(u"torrent collecting directory not found, skip: %s", self.torrent_collecting_dir)`

torrent_upgrade64.py line 88:
`raise RuntimeError(u"The torrent collecting directory doesn't exist: %s", self.torrent_collecting_dir)`

**Comment by devos50** [comment]
I can confirm that this error happens when running Tribler for the first time.
