### ISSUE TITLE
Tribler v6.6.0-exp1 segfaults regularly on Fedora 24

### ISSUE THREAD

**Issue by jalbstmeijer** [Tribler/tribler#2582]
Hi,

Can anyone tell me how to collect useful data for the developers to be able to debug these segfaults?

Gr, Justin

**Comment by devos50** [comment]
Hi,

Thank you for your report. Is this issue present when performing specific operations in Tribler or does it happen at random?

**Comment by jalbstmeijer** [comment]
Till now mostly when browsing the channels list.

**Comment by devos50** [comment]
@jalbstmeijer I guess that this issue can be addressed to the wx library we are using for our user interface. Do you get some more information when it segfaults (i.e. an assertion that fails)?

**Comment by devos50** [comment]
Closing due to lack of feedback. Please reopen this issue if you experience problems in the upcoming release of Tribler 7.
