### ISSUE TITLE
Torrent deleted from channel event

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2584]
Dispersy receives and processes events that constitute removing a torrent from a channel, but no event is fired over the eventstream of the API.

**Comment by brussee** [comment]
I could not find an observer of NTFY_TORRENT and NTFY_DELETE, so I am wondering if this event is even fired internally.

**Comment by devos50** [comment]
I can't find it either. Do you need this notification?

**Comment by brussee** [comment]
Yes, it will enable auto-sync of my channel. Currently discovered torrents (#2585) is working very nicely!
