### ISSUE TITLE
Run script at X (post processing)

### ISSUE THREAD

**Issue by jkaberg** [Tribler/tribler#2588]
It would be very beneficial to do post processing after Tribler is done, so I suggest you add an option where one can specify to run an script (or several) depending on pre defined circumstances (eg. downloaded, moved, deleted etc.)

You'd need to pass som vital enviroment variables to the script, I'd suggest:
- torrent hash
- torrent name
- full path to torrent download location
- torrent label
- type (singel or multi file torrent)
- filename (only for single file torrents) - this is needed for files placed in the download root (where you can't loop through the directory to get the correct file(s))

I'm a big fan of Deluge's [execute](http://dev.deluge-torrent.org/wiki/Plugins/Execute) plugin which does this, but adding functionality to execute different scripts depending on 'state' would be very nice.

**Comment by devos50** [comment]
Thank you for your suggestion!

**Comment by qstokkink** [comment]
Now that we have a REST API, you should be able to do all of the above.. and more!

Of course - because it IS a REST API - events must be polled, you will not get them pushed (like described in the OP). With some basic scripting, this should be functionally equivalent though.
