### ISSUE TITLE
following magnet link attempts to open a new Tribler session, Windows 10 (6.6.0-exp1-g172b60)

### ISSUE THREAD

**Issue by colin1497** [Tribler/tribler#2593]
When clicking a magnet link from Firefox 49.0.2 in Windows 10 with Tribler open, instead of passing the magnet link to the active session, it attempts to open a second Tribler session, which stalls and must be killed with task manager.  At some point I believe that this behaved correctly in a prior version, or perhaps before Tribler was uninstalled and reinstalled dozens of times while testing?

With Tribler closed this works correctly, starting a new Tribler session and opening the link.

**Comment by synctext** [comment]
thnx for reporting yet another bug!
Clicking on magnet links is core functionality,that should just work...

**Comment by devos50** [comment]
Thanks for the report!

**Comment by devos50** [comment]
I've fixed this several days ago and tested it on Windows, both with Tribler closed and with an open session (see https://github.com/Tribler/tribler/blob/devel/TriblerGUI/tribler_app.py#L19). It should now behave correctly (not open a second session) in Tribler 7 (which will be released soon).
