### ISSUE TITLE
Metadata injector

### ISSUE THREAD

**Issue by loadletter** [Tribler/tribler#2603]
I have an headless system alredy running rtorrent, but I wanted to contribute to tribler's distributed search engine, the metadata-injector.py script seems to do what I want but is there any way to directly add a .torrent?

**Comment by devos50** [comment]
Hi, you can create a channel and add your own torrents to that channel. This channel will be discoverable by other users and other users can download the torrents that are available in this channel. You can also add playlists to bundle related groups of `.torrent` files.

Note that `metadata-injector.py` is quite outdated and probably does not work anymore. We have a refactoring of our metadata system on the roadmap but we cannot give an estimate of when this will be done.
