### ISSUE TITLE
open market for real-estate crowdsourcing

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2606]
Market platforms such as AirBnB, eBay, Uber, and Blandlord.com bring supply and demand together.

Based on our ongoing "[blockchain-regulated markets](https://github.com/Tribler/tribler/issues/2559)" we now explore usage in various domains. This issue addresses an open market for crowdsourcing in real-estate.

Outcome of initial brainstorm sketches:
![real_estate_market_screens](https://cloud.githubusercontent.com/assets/325224/19860624/a9d85954-9f89-11e6-9b13-9e9df48963d1.png)

Sprints:
 - Week 1-2: Write-up of context and understanding of problem, understand related initiatives. [Describe at least 10 initiatives](https://www.google.nl/search?q=crowdfunding+real-estate). Learn Python.
 - Week 3-4: Apply Python. Visualize the concept using [PyQT designer](https://www.google.nl/search?q=pyqt) with 4 operational screens. Feedback round from bank.
 - Week 5-6:
 - Week 7-8:

Roadmap: 
 - Feb/Jan:  we have 3 components ready in draft: operational market + GUI implemented in QT + business case
 - till April: define API between market and business logic, create business logic core, integrate the market, business logic, and GUI.
 - April: present MvP results

Various markets for real-estate already exist, such as:
![blandlord_rotterdam_4percent](https://cloud.githubusercontent.com/assets/325224/19862992/ca5ea314-9f92-11e6-8e6a-2c2bb219ffc7.png)

Plus an operational crowdsourcing market, running locally which TUDelft indirectly has access to:
![kapitaal_op_maat](https://cloud.githubusercontent.com/assets/325224/19863023/e6221522-9f92-11e6-9893-76c52094b44f.png)

**Comment by synctext** [comment]
Big promises website, big amounts, high return, risky:
![fundrise__real-estate](https://cloud.githubusercontent.com/assets/325224/19933533/f5a54f8c-a113-11e6-86ad-79688452c19a.png)

**Comment by synctext** [comment]
ToDo for next week:
 - Each picture of assignment with piece of text
 - pretty digital pictures of each screenshot
 - reading of real-estate stuff
 - understanding disruption of crowdsourcing
 - problem description first draft

**Comment by vi** [comment]
Is it somehow Tribler-related?

**Comment by synctext** [comment]
@vi not a core Tribler feature indeed, we're making Tribler broader and business friendly with this.

**Comment by synctext** [comment]
Thank you for the update, please leave the screen demo .PNG files here.

(ToDo: add @katiaas)

**Comment by ahovanesyan** [comment]
[chapter 1 [draft].pdf](https://github.com/Tribler/tribler/files/608513/chapter.1.draft.pdf)

**Comment by ahovanesyan** [comment]
Progress so far:
![place_loan_request](https://cloud.githubusercontent.com/assets/5951182/20557342/670afef8-b16b-11e6-959d-ef9dbd31e551.png)
![requested loans 2](https://cloud.githubusercontent.com/assets/5951182/20557353/7363379c-b16b-11e6-8c18-03918546291f.png)
![openmarket](https://cloud.githubusercontent.com/assets/5951182/20557359/790945ec-b16b-11e6-9c9b-8855a9a0b66a.png)
![investorsportfolio](https://cloud.githubusercontent.com/assets/5951182/20557379/84f14eea-b16b-11e6-8638-dbdb403c8551.png)

**Comment by Jumba** [comment]
[BEP chapter one [draft 2].pdf](https://github.com/Tribler/tribler/files/613391/BEP.chapter.one.draft.2.pdf)

**Comment by ahovanesyan** [comment]
Customer journeys
![borrowers-flowchart](https://cloud.githubusercontent.com/assets/5951182/20797443/044f8f24-b7db-11e6-9aa7-9075e4df023e.jpg)
![financial-institution-flowchart](https://cloud.githubusercontent.com/assets/5951182/20797441/044e3656-b7db-11e6-8d72-899ad64bba66.jpg)
![investors-flowchart](https://cloud.githubusercontent.com/assets/5951182/20797442/044ed16a-b7db-11e6-9c95-0521f0e24aed.jpg)

**Comment by synctext** [comment]
After problem description: "defining the customer journey".

**Comment by seuushi** [comment]
[BEP-draft3.pdf](https://github.com/Tribler/tribler/files/641703/BEP-draft3.pdf)

Added new chapter: Defining the customer journey + processed feedback

**Comment by synctext** [comment]
Please document you sprint goals here today or so and try to wrap-up documenting what you did in past two weeks in BEP thesis draft report.

**Comment by katiaas** [comment]
Our sprint backlog for this week:
- Read about dispersy
- Linking the rest of the screens
- Networking with dispersy
- Process feedback chapter 3
- Start writing chapter 4

We currently have an issue with overleaf, so we will add a new draft of the thesis to this issue tomorrow.

**Comment by Jumba** [comment]
[BEP Draft 5.pdf](https://github.com/Tribler/tribler/files/663417/BEP.Draft.5.pdf)

**Comment by seuushi** [comment]
[BEP-draft-6.pdf](https://github.com/Tribler/tribler/files/695892/BEP-draft-6.pdf)

**Comment by synctext** [comment]
Great milestone: running code using Dispersy on multiple laptops.

**Comment by ahovanesyan** [comment]
First draft of the complete thesis: [bep full draft 1 .pdf](https://github.com/Tribler/tribler/files/712370/bep.full.draft.1.pdf)

**Comment by seuushi** [comment]
Minor changes to the first draft. If you haven't read it yet, please read this one: 
[BEP-full-draft-2.pdf](https://github.com/Tribler/tribler/files/714237/BEP-full-draft-2.pdf)

**Comment by synctext** [comment]
Please add nice screenshots here.

**Comment by synctext** [comment]
Code works on Ubuntu 14.04 and information is stored on blockchain.
```
XPS13:~/GITHUB/decentralized-mortgage-market>python2.7 market.py 
Using a new user
INFO:market.community.community:Example community initialized
ING  is OFFLINE
RABO  is OFFLINE
ABN  is OFFLINE
MONEYOU  is OFFLINE
ABN  is ONLINE
INFO:market.community.community:Persisting sr: ODZjMzliNzVhMTMxZDFjYmYwMDhiYTgzZDlkNjFjOTdiMTk3NjMzYThhNjg1ZTg2YzI2YjUwMTdm
ZTVlZTA2Yg==
INFO:market.community.community:Persisting sr: MzJmY2YwNGEzZjEyYjVlMDQwOGU3ZWIwOWQ0MDc3YzJlY2Q2NzQ2NDIwMzlhZDRhNjkwNTZkNzQw
NWI4MGQxMg==
INFO:market.community.community:Persisting sr: ZDRlNjJhYjJkNTMxMDViNTc5NDlkOGRiM2EyZjk3NDQxOWU3MmI5NTBlZjkxNDg4MTIzMDYwOWZj
OTllYTNjOQ==
```
![hypotheek_place_loan](https://cloud.githubusercontent.com/assets/325224/22102008/1630cf4c-de36-11e6-97e6-5d0048fa0445.png)
![hypotheek_portfolio](https://cloud.githubusercontent.com/assets/325224/22102009/16345e64-de36-11e6-9083-43a72781b42d.png)
![hypotheek__campaign_overview](https://cloud.githubusercontent.com/assets/325224/22102007/1630ac24-de36-11e6-84be-c1adfa3163ec.png)

**Comment by synctext** [comment]
[crowdfunded_mortgages.pdf](https://github.com/Tribler/tribler/files/719790/crowdfunded_mortgages.pdf)

**Comment by seuushi** [comment]
This is the thesis as sent to the bachelor project committee.
[decentralized- mortgage-market.pdf](https://github.com/Tribler/tribler/files/727738/decentralized-.mortgage-market.pdf)

**Comment by synctext** [comment]
Public repo of the code: https://github.com/Jumba/decentralized-mortgage-market

**Comment by synctext** [comment]
proof-of-principle prototypes ready for industrial uptake, closing issue.

**Comment by synctext** [comment]
[2017 thesis by Bart: "Block and Mortar](https://repository.tudelft.nl/islandora/object/uuid%3Abe64e8ed-6e28-489f-a84b-7661cae75e91)
