### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#2619]
I thought I read wx was going to be removed but just in case it's going to stay;

`
Process:               Tribler [63958]
Path:                  /Applications/Tribler.app/Contents/MacOS/Tribler
Identifier:            Tribler
Version:               0.0.0 (0.0.0)
Code Type:             X86 (Native)
Parent Process:        ??? [1]
Responsible:           Tribler [63958]
User ID:               501

Date/Time:             2016-11-15 08:00:30.904 -0500
OS Version:            Mac OS X 10.12.1 (16B2555)
Report Version:        12
Anonymous UUID:        9B05D90F-8820-3005-3775-BA1FE637354D

Time Awake Since Boot: 510000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000054
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0x54:
--> 
    __TEXT                 0000000000001000-000000000000c000 [   44K] r-x/rwx SM=COW  /Applications/Tribler.app/Contents/MacOS/Tribler

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.python.python             	0x03927597 subtype_dealloc + 183
1   org.python.python             	0x038d212c instancemethod_dealloc + 220
2   _core_.so                     	0x06bf09ea wxPyCallback::~wxPyCallback() + 62
3   libwx_macud-2.8.0.8.0.dylib   	0x06dedd39 wxEvtHandler::~wxEvtHandler() + 99
4   _core_.so                     	0x06bf0ebc wxPyApp::~wxPyApp() + 84
5   _core_.so                     	0x06c36307 wxIntersectRect(wxRect*, wxRect*) + 226413
6   _core_.so                     	0x06bfb253 wxPySwigInstance_Check(_object*) + 731
7   org.python.python             	0x039087ac dict_dealloc + 156
8   org.python.python             	0x0392788f subtype_dealloc + 943
9   org.python.python             	0x038f14a5 frame_dealloc + 133
10  org.python.python             	0x038f16b5 frame_dealloc + 661
11  org.python.python             	0x038f16b5 frame_dealloc + 661
12  org.python.python             	0x038f16b5 frame_dealloc + 661
13  org.python.python             	0x039a511c tb_dealloc + 188
14  org.python.python             	0x03907439 insertdict_by_entry + 217
15  org.python.python             	0x03909b71 PyDict_SetItem + 129
16  org.python.python             	0x03909cb2 PyDict_SetItemString + 66
17  org.python.python             	0x0398b7d4 PyImport_Cleanup + 244
18  org.python.python             	0x0399bc64 Py_Finalize + 276
19  Tribler                       	0x00004145 0x1000 + 12613
20  Tribler                       	0x000025d0 main + 768
21  Tribler                       	0x00001f45 start + 53

`

**Comment by devos50** [comment]
Thanks for the report! Wx will indeed be removed in the next version of Tribler; the first (alpha) version will be released very soon so we won't prioritise this.

If you have any other issues, let us know!
