### ISSUE TITLE
Torrents in the megacache don't get the trackers updated from more recent torrent files.

### ISSUE THREAD

**Issue by vvs-** [Tribler/tribler#262]
Adding a torrent with the same infohash does not update MegaCache. If the new torrent has updated trackers they won't get updated in MegaCache either and download will rely on DHT only. This might gravely affect torrents with a small number of seeds.

**Comment by LipuFei** [comment]
@whirm I will work on this one after we merge your torrent_store PR.

**Comment by whirm** [comment]
@LipuFei ok, I also think it's better to wait
