### ISSUE TITLE
Tribler is sharing download information in the SearchCommunity

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2636]
https://github.com/Tribler/tribler/blob/devel/debian/README.Debian

Are we still exchanging download information? As far as I'm aware we aren't so it could be removed.

**Comment by devos50** [comment]
It appears that we are still exchanging the download history when performing remote searches. Info hashes of downloads are saved to the preferences table in the SQLite database. When creating an introduction request, all downloads are added to a bloom filter in the introduction message. When the other peers receives an introduction message, an overlap is calculated and stored, however, this overlap is never used.

@synctext I argue to remove the taste buddy code from the `SearchCommunity`. It currently is unused and we can remove much code that way. What do you think?

**Comment by qstokkink** [comment]
The taste buddy code drives the torrent collecting, do you want to get rid of this too?
Or do you propose to keep it and use it again later (when collecting through the multichain)?

**Comment by devos50** [comment]
@qstokkink we should keep torrent collecting. Where exactly is the taste buddy code being used? Maybe I missed it during my investigation.

**Comment by synctext** [comment]
We used to have semantic overlay with taste clustering. That allows scalability. Otherwise we need another .torrect collecting strategy.

**Comment by devos50** [comment]
I've thought about it and looked at the code again: it seems that the overlap is being used: we keep the 10 peers with the highest overlap and exchange torrents with them. The download information is not exchanged as info hashes, instead, a bloom filter is used to keep track of the downloads of the user so the data is not directly exchanged to other peers.

Still, I believe it's not that hard to find out what a taste buddy has downloaded: just scrape the info hashes of popular torrents and verify whether they are in the bloom filter.

Also, when starting a download, we have the option to make it hidden so the download is not added to the preferences table and will not be exchanged with other users. However, this hidden parameter is as far as I've seen unused. @qstokkink @synctext suggestions?

**Comment by qstokkink** [comment]
Having everyone use a hidden download will effectively disable torrent collecting (all hidden downloads = no shared torrents = no torrent collection). So we can't have users do that.

I guess the way to "anonymize" a user's downloads is to send a random sample of collected torrents and downloaded torrents. But then taste buddies would no longer make sense; then it would be random torrent collecting. Which may be what we want to do?

Another option would be to collect torrents based on visited/favorited channels, instead of downloaded torrents.

**Comment by devos50** [comment]
@qstokkink making all download hidden will only affect the verified candidates in the SearchCommunity: data will still be exchanged with these peers. However, if you meet a peer that has some overlap with the downloads, exchanging data with this peer is preferred.

In fact, when starting Tribler from a clean state, this is exactly what happens since you don't have any downloads (yet). Still, we collect torrents from other peers.

I'm not sure to what extend the taste buddy mechanism speeds up discovery of torrents. I believe the idea is that you are discovering content that you might like, however, at the moment I'm collecting all kinds of content so I don't feel like the taste buddy mechanism has a huge impact on the torrent collecting itself.

About collecting torrents based on visited channels: the idea is that users subscribe to channels they like. We might help them by having some kind of popup that triggers when a user visits a channel frequently. This popup suggests that users should subscribe to the channel if they like it.

Concluding, I think that random torrent collecting is not a bad alternative for what we have now, especially if the taste buddies are not providing much additional benefits at the moment (maybe they had more impact in older versions of Tribler?).

**Comment by qstokkink** [comment]
@devos50 I wasn't suggesting to add a subscription mechanism we already have, but to define the overlap as the shared channel subscriptions between users.

That said, if the taste buddies indeed are not providing any practical benefit, there is no need to keep the mechanism.

**Comment by devos50** [comment]
Hmm maybe we should postpone this one to Tribler 7.1 or even after that. Also, we now have a student that works on AllChannel/search mechanism so maybe this issue has some relevance to him.
