### ISSUE TITLE
core stream error: cannot pre fill buffer

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2652]
Video playback does not work even for video files that are being seeded, also after force-recheck.

``core stream error: cannot pre fill buffer``

**Comment by brussee** [comment]
I have copied the files back like #2650 and now it works with the videoserver on the phone and playback on the pc, however:

``vdpau_avcodec generic error: decoder profile not supported: 8``

**Comment by brussee** [comment]
This happens for 0% downloaded video torrents and most likely also by this bug: #2650.

**Comment by devos50** [comment]
I'm also getting the `cannot pre fill buffer` message occasionally (probably due to the fact that the VLC has to wait for the data to be downloaded by libtorrent), however, videos are still playing for me so I don't think this error is caused by the VLC error that is being thrown.
