### ISSUE TITLE
Issue when a tunnel is removed

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2655]
```
RNING:TunnelLogger:Got pong (1949740343) from ('95.211.155.142', 49889),
I am <Member 90334 17a4a82c3fabd656074b9c83947e6695ce345b22>
WARNING:SearchCommunity:message from <Candidate 211.116.88.46:7759>
cannot be found in the request cache, skipping it
WARNING:TunnelLogger:Removing relay 1245271599 too old
WARNING:TunnelLogger:Removing relay 377303990 too old
Unhandled Error
Traceback (most recent call last):
 File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
   self._target(*self._args, **self._kwargs)
 File "/local/git/tribler-test/TriblerGUI/core_manager.py", line 65, in
start_tribler_core
   reactor.run()
 File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line
1195, in run
   self.mainLoop()
 File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line
1204, in mainLoop
   self.runUntilCurrent()
--- <exception caught here> ---
 File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line
798, in runUntilCurrent
   f(*a, **kw)
 File
"/local/git/tribler-test/Tribler/community/multichain/community.py",
line 414, in on_tunnel_remove
   if self._public_key > candidate.get_member().public_key:
exceptions.AttributeError: 'NoneType' object has no attribute 'public_key'
```

It seems like the candidate has been removed when the tunnel is closed.

**Comment by devos50** [comment]
I'm getting quite some reports about this in our crash report backend. I will increase the priority of this issue.

**Comment by qstokkink** [comment]
I guess you could intercept the calls which remove candidates in the TunnelCommunity and store them until the Multichain community is done with them. You would have to overwrite/decorate the following functions:
https://github.com/Tribler/dispersy/blob/devel/community.py#L1464
https://github.com/Tribler/dispersy/blob/devel/community.py#L1560

I would not consider this to be a great design decision, but it works.

**Comment by devos50** [comment]
@qstokkink what if a candidate is available in the tunnel community but not in the multichain community?

**Comment by qstokkink** [comment]
@devos50 the candidate forwarded to MultiChainCommunity.on_tunnel_remove() [is owned/managed by the TunnelCommunity](https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/tunnel_community.py#L588).

A candidate is basically a glorified version of a (host, port) tuple anyway: what you are really after is the associated Dispersy member (which is owned by the shared Dispersy object). What community takes care of the tuple value isn't really that important (until you get race conditions like this one of course 😃).

A prettier way to solve this would be to forward the member id with the tunnel removal notification, instead of the candidate. You could then retrieve the member (and its public key) from the database.

**Comment by devos50** [comment]
@qstokkink thanks for the explanation!

I agree with your second solution and I also think it's better than overriding methods. If you have time, could you implement your solution? I would like to have this one fixed before I release the second alpha version :)

**Comment by qstokkink** [comment]
@devos50 As far as I could see it should be safe to change the `NTFY_TUNNEL -> NTFY_REMOVE` to forward a member instead of a candidate, as this only seems to be used in the MultiChainCommunity. Do you agree this is safe and the MultiChainCommunity is the only subscriber to this event?

**Comment by qstokkink** [comment]
@devos50 Oh, and could you assign me please?

**Comment by devos50** [comment]
@qstokkink I just verified that it should be safe to change it 👍

**Comment by qstokkink** [comment]
@devos50 Thanks!

**Comment by qstokkink** [comment]
@devos50 Upon further inspection, I guess it would make more sense using a fresh temporary Candidate object with a correct Member in the notification. Even though it would objectively be better to use Members throughout the MultiChainCommunity, the guys working on it would probably kill me if I refactored everything to use them.

**Comment by devos50** [comment]
@qstokkink yeah, please use `Candidate` objects. We don't want to refactor too much in the multichain community since there's also a rather large open PR (#2135).

**Comment by qstokkink** [comment]
Memo for myself:
https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/routing.py#L197 
Fix RelayRoute mid assignment.

**Comment by qstokkink** [comment]
@devos50 #2704 seems to be working, however: I don't have any test case to check if this actually fixes this issue. Do you have a way to make the MultiChainCommunity fail reliably?

**Comment by devos50** [comment]
No, there's not test case for it but I guess you can quite easily get the system in a state where the `candidate.get_member()` returns None (using mocking).

**Comment by qstokkink** [comment]
@devos50 well yes, but this fix avoids the get_member() ever returning `None` for established Circuits/RelayRoutes/ExitSockets. Are there any Gumby experiments where this happens maybe?

**Comment by devos50** [comment]
@qstokkink not that I know. Can you try to have the code at least covered by a test case?

**Comment by qstokkink** [comment]
@devos50 This might be a very fat test. I believe it to fail as follows (in this exact order):

1. _A_ creates a circuit with first hop _B_
2. _B_ times out/is unreachable/etc. and gets removed from _A_'s community candidates
3. _A_'s community finds out the circuit is dead through the ping/heartbeat mechanism and fires a circuit removed, with the candidate that has already been cleaned

To show this fix works, _B_ first needs a full-on member association in (1). This would be normal behavior before a Circuit is used, but this makes the test a little bigger. (2) and (3) are pretty easy to simulate though.

**Comment by devos50** [comment]
Indeed, that quite a big test since we need both multichain, tunnel community and we need to setup circuits and manage them.

I remember that this error happens frequently when running Tribler idle (since the error happens in the background) so we can try the fix in our alpha 2 release and see whether the error is still reported?

**Comment by devos50** [comment]
@qstokkink but if you want to write the test, please go ahead 👍

**Comment by qstokkink** [comment]
@devos50 On one hand I am kind of scared of writing that test, on the other hand I think it would be the responsible thing to do.

**Comment by devos50** [comment]
Writing tests is never a bad thing to do since it really helps us to capture errors when making impactful changes. Also, others may benefit from that test and extend/copy it.

**Comment by qstokkink** [comment]
@devos50 Alright, fix is confirmed. We should be good to go.
