### ISSUE TITLE
[devel][Windows specific] Instant shutdown on Windows

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#2657]
##### Tribler version/branch+revision: #####
`devel`

##### Operating system and version: #####
Windows 7

##### Expected behavior: #####
Add to `unload_community()` of any community inheriting from `dispersy.Community`:
```
from twisted.internet.task import deferLater
yield deferLater(reactor, 10.0, lambda: None)
print "I waited for 10 seconds before exiting"
```
This should wait for 10 seconds on application exit and then print "I waited for 10 seconds before exiting".

##### Actual behavior: #####
On Linux (tested on Ubuntu 15.10) this works as intended.
On Windows the application instantly shuts down.

This is particularly nasty when the `unload_community()` is supposed to kill other processes (which a certain PR is doing).

**Comment by devos50** [comment]
@qstokkink I've fixed the shutdown of the application on Windows in https://github.com/Tribler/tribler/pull/2649/commits/f5f3b601ac46c94c7052819cd86308cef699ee7a so please cherry-pick and test with that commit whether it works correctly now :)

**Comment by devos50** [comment]
Also, it had to do with the fact that there is no `SIGTERM` being sent on Windows.

**Comment by qstokkink** [comment]
That was quick 😮

**Comment by devos50** [comment]
I've fixed it yesterday in the evening already ;)

**Comment by qstokkink** [comment]
Hmm.. f5f3b601ac46c94c7052819cd86308cef699ee7a is not the only commit required for the fix I guess:
![gracetime](https://cloud.githubusercontent.com/assets/3630389/20624010/adc98df0-b30a-11e6-81dc-ffe6d25eeb40.png)

I assuume this will be fixed with https://github.com/Tribler/tribler/pull/2649 though, right?

**Comment by devos50** [comment]
@qstokkink you should rebase since the grace time has been removed in https://github.com/Tribler/tribler/commit/57067694de504a0177d3364dfdfdb6343d992643

**Comment by qstokkink** [comment]
@devos50 Sorry that was sloppy of me. Confirmed https://github.com/Tribler/tribler/commit/f5f3b601ac46c94c7052819cd86308cef699ee7a as a fix, closing this issue.

**Comment by devos50** [comment]
Great! I will reference this issue in my big fix PR.
