### ISSUE TITLE
Trying to add duplicate download shows unfriendly error message

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2662]
##### Tribler version/branch+revision: #####

v7.0.0-alpha1 6bda08fab632a38fbb3fc4e9f4073e23b2d8df7a

##### Operating system and version: #####

Linux

##### Steps to reproduce the behavior: #####

1. Start Tribler core with `twistd -n tribler`
2. Start GUI with `./tribler.sh`
3. Press "+" button.
4. Add torrent from file
5. Press "Download"
6. Press "+" button
7. Add torrent from the same file
8. Press "Download".

##### Expected behavior: #####

Showing the message about duplicate download, like old Tribler GUI

##### Actual behavior: #####

> Request error. An error occured during the request: None

@devos50

**Comment by devos50** [comment]
Thanks for the report! Should be an easy fix by adding a message to a `DuplicateDownloadException` 👍

**Comment by devos50** [comment]
See https://github.com/Tribler/tribler/pull/2649/commits/1eed7eda62b7fdcb9a194eeeccb73e795a300e5a
