### ISSUE TITLE
Error when decrypting circuit payload

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2663]
We received this report in our crash reporter backend:

```
Traceback (most recent call last):
File "/usr/share/tribler/TriblerGUI/event_request_manager.py", line 85, in on_read_data
raise RuntimeError(json_dict["event"]["text"])
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/usr/share/tribler/TriblerGUI/core_manager.py", line 65, in start_tribler_core
reactor.run()
File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
self.mainLoop()
File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
self.runUntilCurrent()
--- <exception caught here> ---
File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 798, in runUntilCurrent
f(*a, **kw)
File "/usr/share/tribler/Tribler/community/tunnel/tunnel_community.py", line 1158, in on_data
encrypted = self.crypto_in(circuit_id, encrypted, is_data=True)
File "/usr/share/tribler/Tribler/community/tunnel/tunnel_community.py", line 1299, in crypto_in
hop.session_keys[ORIGINATOR_SALT])
File "/usr/share/tribler/Tribler/community/tunnel/crypto/tunnelcrypto.py", line 76, in decrypt_str
salt_explicit, gcm_tag = struct.unpack_from('!q16s', content)
struct.error: unpack_from requires a buffer of at least 24 bytes
```

**Comment by devos50** [comment]
@qstokkink can you take a look at this issue if you have time?

**Comment by qstokkink** [comment]
@devos50 sure. At first glance it seems like _content_ is not set.

**Comment by qstokkink** [comment]
I _assume_ what has happened here is that a relay circuit was removed (too many circuits, time-out, etc.) and then data was sent over it anyway. This would cause a false negative for [`is_relay()`](https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/tunnel_community.py#L1152), consequently having `on_data()` trying to decode the message as if it was its own circuit.

My suggested fix would be to turn the current [`else` clause](https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/tunnel_community.py#L1155) into an `elif circuit_id in self.active_data_circuits()`.

**Comment by devos50** [comment]
Great, that is nonetheless a case that we should handle. Do you have time to implement a fix for this and create a PR? If so, please try to first capture the error in a (simple) unit test.

**Comment by qstokkink** [comment]
@devos50 I need a little break from the stupid Windows issues of # 2607 anyway: I'll create the PR.

**Comment by devos50** [comment]
@qstokkink thanks!

**Comment by qstokkink** [comment]
Small addendum:
The `circuit_id` could also validly be in `self.exit_sockets`, instead of `self.active_data_circuits()`.
The correct else condition would be:
`elif circuit_id in self.active_data_circuits() or circuit_id in self.exit_sockets`

**Comment by qstokkink** [comment]
My first intuition was correct, my second suggestion (the circuit removal thing) will actually correctly throw a CryptoException.

There are only two ways of reproducing this behavior:
 1. Receiving an intentionally truncated packet (header needs to be correct)
 2. LibTorrent sends an empty packet

The implication of this behavior, assuming that no one actually took the time to mount an attack, is that someone's LibTorrent decided to send an empty string. I will fix this for the receiver in my PR: do we also want to catch this at the sender (avoiding useless circuit load)?

**Comment by qstokkink** [comment]
Even though the actual fix for this is trivial, I could not find any obvious misuse of `send_packet()` in the code. We should be wary of the fact that the bug still exists, probably limiting functionality in some way.
