### ISSUE TITLE
[Enhancements] Feedback on GUI in Tribler-alpha1-47-gaa92b5f

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#2668]
Loving the new look, but got some proposed improvements for the future, Tested on windows 10.

* Remembering what the last download was.

At the moment of writing, batch adding torrents don't work, but i believe it is like i'm describing. When adding multiple torrents at once, the download confirmation dialog pops-up, and you get to pick a location. With 6.6.0 (and maybe some other versions, i can't remember) after picking the download location for the first torrent, the second torrent downloads window would keep that location. Thus, if all torrents were going to the same space, you'd only need to select the location once if it wasn't the default, whereas now, you need to change it for each torrent when adding them. 

This also applies to when single torrents are added, as it only uses default location each time, and does not remember what you selected prior. 

* Drop down menu with recently picked locations when selecting download.

The drop down option present in the old GUI made selecting a different common location easier, if it was a location that wasn't default, or wasn't the one you used last time. It provided a quick and easy functionality compared to navigating to the correct place with the browse option. 

* Longer "NAME" column in torrents section.

Well, the same with windows explorer(which never learns), the name column usually covers for a single word of the torrent name. Roughly 15 characters showing, is a little low. A option to change default length(preferred, to account for different screens) or a longer one in general. Used with a 1080p 27" monitor for reference. Right now for me, i got almost 30 of dead space on the right side, which could be used by making the torrent name column longer. 

* The ability to batch select torrents from a folder (without picking everything in the directory folder)

This functionality was in the former GUI, but does not seem to be in the new one. As when browsing you aren't allowed to select multiple objects anymore. 

* white border around torrent details, as well as the tab buttons "Details", "Files", "Trackers", and "Peers"

Well, i'm guessing it's in the works. But, it's currently a small inconsistency in the GUI style. I do love the new dark GUI though, much easier on the eyes, and much smoother and more reliable. Hope i don't sound like i complain to much. Just a bit eager on things. 

* Unable to see percentages on the with background, before the torrents download has gotten far enough to have orange behind it. 

Disclaimer, i'm red-green colorblind, but those are in a white/ very light grey color right? I need to get pretty close to the screen to see the percentage.

**Comment by devos50** [comment]
Thanks! This kind of feedback is valuable for us and we will take these points in consideration!

**Comment by devos50** [comment]
Addressed in #2701:

- white border around torrent details, as well as the tab buttons "Details", "Files", "Trackers", and "Peers"
- Unable to see percentages on the with background, before the torrents download has gotten far enough to have orange behind it.
