### ISSUE TITLE
Error when adding magent link. Tribler 7.0.0-alpha1-47-gaa92b5f

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#2669]
Error when attempting to add magnet link, both when Tribler is open and not. Does not allow adding the torrent.   

Windows 10
Tribler 7.0.0-alpha1-47-gaa92b5f (x64)

Result: http://i.imgur.com/lMFlKUV.png 

Pressing Download, you get an error message stating "missing infohash".

**Comment by devos50** [comment]
Thanks, this one is interesting. The magnet link itself does not contain an infohash so the download is unable to start. In fact, it seems that this magnet link is used for direct distribution given the `xs` field (exact source).

We should capture this error in a more appropriate way.

**Comment by Thomasedv** [comment]
It may indeed be the magnet links that are broken somehow, it seems others work ass expected. i guess i fucked up a little by finding the fastest magnet link available when testing it...
