### ISSUE TITLE
Headless (non-GUI) Version

### ISSUE THREAD

**Issue by mjowe** [Tribler/tribler#267]
It was mentioned in the forums, that it would be nice to run Tribler on a server system without GUI.
http://forum.tribler.org/viewtopic.php?f=2&t=1333
http://forum.tribler.org/viewtopic.php?f=2&t=1851
http://forum.tribler.org/viewtopic.php?f=2&t=3845

**Comment by pguth** [comment]
+1

**Comment by devos50** [comment]
@whirm can you assign me on this one?

**Comment by whirm** [comment]
@devos50 As a first I would go for a non-interactive and headless version first: You start it and it runs till you press control+C

**Comment by devos50** [comment]
This can be accomplished by the work of #1961 and #2029. When these are done, we are able to create a very basic command-line interface.

**Comment by synctext** [comment]
background server + REST api now in devel..

**Comment by gjedeer** [comment]
I'd like to test it, how do you run that? Some command line switch?

**Comment by devos50** [comment]
@gjedeer nice that you want to test it! You can either run it with the GUI using:

```
./tribler.sh
```

The command for running it headless is:

```
twistd -n tribler
```

I will think about adding a flag to the main Tribler script to toggle GUI/non-GUI version.

Please note that this version is in very early alpha phase so it might contain some instabilities which we are currently trying to fix.

**Comment by gjedeer** [comment]
Thanks! It crashes on startup but I expected that.

If I may suggest something, a second script like `./tribler-headless.sh` may be easier to discover than a flag.

**Comment by loadletter** [comment]
@gjedeer I've got it running after upgrading ```python-twisted``` and ```python-cryptography``` as suggested in https://github.com/Tribler/tribler/issues/2504
