### ISSUE TITLE
Tribler 7.0.0-alpha1-47-gaa92b5f does not remember changed default download location between runs. 

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#2670]
Set location to E:\something\something, and remembered to press save and gets message changes are saved. (done multiple times for good measure)
Closeing and reopening Tribler, then checking out settings, and default download location is set to the default option. (C:\Users\Username\Downloads\TriblerDownloads)

**Comment by devos50** [comment]
That's weird. I guess the setting itself is not saved correctly. We will investigate it!

**Comment by pimotte** [comment]
https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Session.py#L239 is the culprit. It overwrites the value on boot.
