### ISSUE TITLE
Crash when attempting to add torrents from directory.

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#2672]
Windows 10
Tribler 7.0.0-alpha1-47-gaa92b5f (x64)

Tribler crashes instantly when trying to batch add torrents from directory. 6 Torrents was attempted at once, and it crashed instantly on "add" when the confirmation warning came up after selecting the directory.

Error: http://i.imgur.com/KCqEhgY.png

**Comment by devos50** [comment]
Thanks!

**Comment by brussee** [comment]
2 files on devel https://github.com/Tribler/tribler/commit/1d9c3596a40dbc32bb7d75ea1aebb5acec3ea863
fails:
```
An error occurred during the request:

metainfo not dict
```
