### ISSUE TITLE
Crash when we receive a package with an invalid IP address

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2673]
This is something is Dispersy that should be investigated. When we receive a packet that contains an invalid IP, an assertion triggers that leads to a GUI crash. I think the packet should be dropped instead.

```
Traceback (most recent call last):
File "/usr/share/tribler/TriblerGUI/event_request_manager.py", line 85, in on_read_data
raise RuntimeError(json_dict["event"]["text"])
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/usr/share/tribler/TriblerGUI/core_manager.py", line 65, in start_tribler_core
reactor.run()
File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
self.mainLoop()
File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
self.runUntilCurrent()
--- <exception caught here> ---
File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 798, in runUntilCurrent
f(*a, **kw)
File "/usr/share/tribler/Tribler/dispersy/endpoint.py", line 247, in dispersythread_data_came_in
in strip_if_tunnel(packets)],
File "/usr/share/tribler/Tribler/dispersy/candidate.py", line 30, in __init__
assert self.is_valid_address(sock_addr), sock_addr
exceptions.AssertionError: ('50.90.131.179', 0)
```

**Comment by qstokkink** [comment]
I have two comments on this:
 1. I agree that this should not completely crash the GUI
 2. It should not even be possible to create, let alone send, a 0 port (non-tunnel) candidate: we should be on the lookout for the bug that caused this.

**Comment by synctext** [comment]
just wow...

**Comment by vi** [comment]
> possible to create, let alone send

Anything can arrive from network. One should assume malicious peer sending specially crafted packets to crash/hack Tribler nodes.

**Comment by qstokkink** [comment]
@vi Correct and I agree. However, this is more likely to be a symptom of a bug than an attack or a message integrity issue. Therefore we should not just catch and log the exception, but investigate the source of the error. Otherwise the bug will silently remain in Tribler and people will forget about it.

**Comment by devos50** [comment]
@qstokkink I think that finding this is searching for a needle in a haystack: this error can be triggered by any community that sends messages. I'm proposing the following 'fix': https://github.com/devos50/dispersy/commit/883c8667760201de73b4383f344c12d6e5795782. What do you think?

**Comment by qstokkink** [comment]
@devos50 you can still extract the community and (meta)message id from the packet, you just need to find a way to trigger the error and log the packet. Then you need to find where the message type is constructed. The amount of work required -once you have a failure and a logged packet- is rather small.

The key here is logging the packet. So I suggest a slight alteration of your fix: a substitution of `is_valid_address`, which decorates `is_valid_address` and logs the packet if the value is `False`. Something like:

```python
def is_valid_address_or_log(sock_addr, data):
    if is_valid_address(sock_addr):
        return True
    else:
        logging.error("<<error msg>> " + data)
        return False
```

If you want to get really fancy you could even extract the community name and meta message name from `data` for the error message.

**Comment by devos50** [comment]
@qstokkink thanks for the suggestion! I've changed the code according to your proposal.
