### ISSUE TITLE
Crash due to TorrentChecker UnicodeEncodeError url

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2678]
``WARNING:TorrentChecker:Got session error for URL http://retracker.local/announce?size=33098770156&comment=nana-aida-film-039-s-collection.html&name=Nana+Aida+Film%26%23039%3Bs+Collection+%28Madonna%2C+Attackers%2C+BeFree%29+%5Bcen%5D+%5B2011-2014+%E3%E3.%2C+All+Sex%2C+Married+Woman%2C+Rape%2C+Mother-in-law%2C+Female+Teacher%2C+DVDRip%5D+%5B28+%D4%E8%EB%FC%EC%EE%E2%5D: [Failure instance: Traceback (failure with no frames): <type 'exceptions.UnicodeEncodeError'>: 'ascii' codec can't encode characters in position 481-482: ordinal not in range(128)
]``

**Comment by devos50** [comment]
After the holiday, I will make sure that this issue will be fixed 👍
