### ISSUE TITLE
LibTorrentMgr UDP problems

### ISSUE THREAD

**Issue by Captain-Coder** [Tribler/tribler#2680]
- [X] I have read CONTRIBUTING.rst

- [X] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Pimv/halves_2

##### Operating system and version: #####
Arch Linux (Version: rolling release :P)
LibTorrent 1.1.1

##### Expected behavior: #####
LibTorrent connects through the local annon proxy, failing that it should not connect at all.

##### Actual behavior: #####
LibTorrent gets some weird udp listen error. Unsure where it comes from.

##### Steps to reproduce the behavior: #####
run gumby experiment multichain_integraded_4_instances.scenario

##### Relevant log file output: #####
Printed the settings:

LibTorrent Settings: {'enable_outgoing_tcp': False, 'anonymous_mode': True, 'outgoing_port': 0, 'num_outgoing_ports': 1, 'enable_outgoing_utp': True, 'enable_incoming_tcp': False, 'enable_incoming_utp': True}
Setting Proxy settings: type: 2 hostname 127.0.0.1 port 39011 username  pass  proxy hostnames True proxy peer connections True

INFO:OneShotProcessProtocol:[process_guard.py -c...] OUT: Download infohash=0d6bb, hops=2, down=0, up=0, progress=0.0, status=DLSTATUS_CIRCUITS, peers=0, cand=6
INFO:OneShotProcessProtocol:[process_guard.py -c...] OUT: want -1 data circuits of length 2
INFO:OneShotProcessProtocol:[process_guard.py -c...] OUT: Got Alert: type: <class 'libtorrent.listen_succeeded_alert'> data successfully listening on [TCP] [::]:27020
INFO:OneShotProcessProtocol:[process_guard.py -c...] OUT: Got Alert: type: <class 'libtorrent.listen_succeeded_alert'> data successfully listening on [TCP] 0.0.0.0:27025
INFO:OneShotProcessProtocol:[process_guard.py -c...] OUT: Got Alert: type: <class 'libtorrent.listen_succeeded_alert'> data successfully listening on [UDP] 0.0.0.0:27025
...
INFO:OneShotProcessProtocol:[process_guard.py -c...] OUT: Got Alert: type: <class 'libtorrent.listen_failed_alert'> data listening on socks5 : 0.0.0.0:65535 failed: [accept] [Socks5] Connection refused
...
INFO:OneShotProcessProtocol:[process_guard.py -c...] OUT: Got Alert: type: <class 'libtorrent.udp_error_alert'> data UDP error: Connection refused from: 0.0.0.0

it then proceeds to download it anyway, ignoring the annon setting.

**Comment by brussee** [comment]
> it then proceeds to download it anyway, ignoring the annon setting.

D'oh!

**Comment by qstokkink** [comment]
Judging from the port (65535) it seems that [get_random_port](https://github.com/Tribler/tribler/blob/69445f0537d8e87bd01d2ca8bdc94a69c9819503/Tribler/Core/Utilities/network_utils.py#L14) has exhausted all its options. This could be due to bad luck (starting with a random port close to 65535). The `get_random_port` should probably be constructed differently.

Furthermore, we should listen for the `listen_succeeded_alert` and `listen_failed_alert` in [process_alert](https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py#L520) and delay [can_create_engine_wrapper](https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py#L254) until `listen_succeeded_alert` has succeeded for the SOCKS5 server ports. Possibly we need to use a different port.

**Comment by Captain-Coder** [comment]
The Got Alert log lines are the alerts that libtorrent generates, it does not call our get_random_port python function. The experiment fails deterministically, so I doubt its a one time rng which is not in our favour. (Unless gumby messes with the rng for determinism) Tribler specified port 27025 to use, which libtorrent sends a listen_succeeded_alert for. The listen failed alert reads 65535. I had assumed the 65535 port was an indication of an error. My ulimit when running this experiment seems to be 1024, so even with 4 tribler instances I doubt I'd have exhausted my ports.

**Comment by qstokkink** [comment]
Oh wait, I read that error log wrong: it's trying to reach a SOCKS5 proxy which should be listening on port 65535, but it's either refusing the connection or not listening on that port. This is still suspicious port though.

**Comment by qstokkink** [comment]
This should be fixed by #2788

**Comment by devos50** [comment]
Yes indeed, I will close it!
