### ISSUE TITLE
Won't start. No module named "twisted.internet" ?

### ISSUE THREAD

**Issue by tytower** [Tribler/tribler#2683]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

**Comment by tytower** [comment]
This is the error I get on a 32 bit Puppy Precise 5.7.1 - Do I need to get something else?

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/Tribler/Main/tribler.py", line 47, in <module>
    from Tribler.Core.Utilities.twisted_thread import reactor, stop_reactor
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Utilities/twisted_thread.py", line 8, in <module>
    from twisted.internet import reactor
ImportError: No module named twisted.internet

**Comment by devos50** [comment]
@tytower thank you for your report. It seems like the `twisted` dependency is not installed correctly so you need to install that package with the package manager that your OS provides.

Please let me know whether that solved the problem!

**Comment by tytower** [comment]
Thank you for your fast response . I installed  python-twisted_11.1.0 through the Puppy Package Manager and that appears to have fixed that but I still get no GUI .  Opened in a terminal it says "tribler started"

**Comment by devos50** [comment]
@tytower good to hear that it's somehow working now. We removed the `wx` GUI dependency a while ago but if you want to use an older version of Tribler, you need `wx`.

Please open another issue if you experience problems with Qt5 and we can provide more help if needed 👍
