### ISSUE TITLE
Tribler should advise OS not to cache the file being checked

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2685]
##### Tribler version/branch+revision: #####

e744e2ca7090b9f3258694125e52f7fe66194e96 devel

##### Operating system and version: #####

Linux

##### Steps to reproduce the behavior: #####

Make Tribler to recheck one or all downloads

##### Actual behavior: #####

Tribler reads files being checked sequentially and the files get cached, evicting more use useful content from system cache and slowing down the whole system.

##### Expected behavior: #####

Before reading the file, Tribler uses [`posix_fadvise`](http://man7.org/linux/man-pages/man2/posix_fadvise.2.html) (or some portable analogue) to tell OS to limit caching of this file.

Maybe just POSIX_FADV_SEQUENTIAL will be enough.

**Comment by vi** [comment]
Workaround: manually evict cached pages while Tribler is rechecking everything:

```
while true; do sleep 5 || break; vmtouch -e -m 100G  TriblerDownloads; done
```

**Comment by ichorid** [comment]
This should be addressed to Libtorrent project directly. We are in no control of this low-level stuff.
