### ISSUE TITLE
The algorithm to show pieces in the piece bar should be changed

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2690]
When clicking on a download, it shows a bar with piece progress. Now image that there is a download active with many pieces (3000+). Currently, each piece is drawn as a vertical line where the width of this line is determined by the width of the widget divided by the amount of pieces.

While this simple method works when there are few pieces for a download, it fails when we have many pieces due to the width of the drawn pieces being to small. This leads to overlap between lines, giving a wrong indication of the piece progress. This causes downloads that are completed for around 40% appear like all the pieces are being downloaded. When making the Tribler window bigger (and the width of each drawn piece larger), the problem disappears.

**Comment by qstokkink** [comment]
You could calculate the amount of pieces _n_ which the pixel overlaps and the summation _S_ of the completion statuses of each of these overlapped pieces (0 or 1). Note: 0 <= _S_ <= _n_ and 1 <= _n_.

Then you could specify the color of a pixel in __HSL__ as follows:
HSL(26, 100, 50 + 50 *(1 - _S_/_n_))

This will blend from pure white to orange as the amount of completed pieces covered by a pixel increases.

**Comment by devos50** [comment]
@qstokkink amazing algorithm, thanks! I will implement it in a moment to see how it works 👍

**Comment by synctext** [comment]
cool! can we have a 10k pieces test torrent in the unit tests?

**Comment by devos50** [comment]
Final result: 
<img width="856" alt="fc58f00769c592ceefa76ded073a8c12" src="https://cloud.githubusercontent.com/assets/1707075/21942062/c016c54e-d9cb-11e6-93cc-4f52c1b11451.png">

**Comment by qstokkink** [comment]
Just to trigger everyone's O.C.D.: the orange in the lower bar is slightly brighter than the orange in the top bar: you're welcome.

**Comment by synctext** [comment]
I love bike shedding!
plus testing alpha releases....

**Comment by qstokkink** [comment]
To be fair, it does look better with the lower one being brighter, here it is with matching orange:
![](https://i.gyazo.com/5bfdc21fdefdf76144488b2e94fdeb32.png)

**Comment by devos50** [comment]
@qstokkink that's not a really fair comparison since your image has a progress of 42% and mine has a progress of 68%, influencing the drawing :)

Also, when the progress is 100%, the color (almost) matches the color in the smaller progress bar.

**Comment by qstokkink** [comment]
@devos50 are you having second thoughts about the brighter color?
