### ISSUE TITLE
No GUI to include/exclude all/multiple files

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2692]
##### Tribler version/branch+revision: #####

b97f36e310db0f3206148f673e47e54d8b36f5f1 from #2691 
743adf068b8fcc97b09c437655b1b83c3c954884 from devel

##### Operating system and version: #####

Linux Debian, Awesome window manager

##### Expected behavior: #####

Can easily select all (or range of) files in a download and include them.

##### Actual behavior: #####

Can only include files one by one. Selection on files quickly disappear. Can't select multiple files.

**Comment by devos50** [comment]
Thanks for the report! 👍
