### ISSUE TITLE
Add documentation spelling checker to PR checks

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#2702]
We should automatically check PRs for spelling errors in the documentation. This should hopefully guarentee there will be no (further) spelling errors introduced in PRs.

I have made a bash script which will take care of checking all `.rst` files in the current directory (excluding git submodules) for unknown words:
https://gist.github.com/qstokkink/0b6f7aed57f698f87df4dd77feb18e9f
This approach uses the `aspell` library and can be extended with custom words (nice to filter out words like "Tribler" and "Dispersy" and such).

We could also consider doing the same for docstrings in the code.

**Comment by qstokkink** [comment]
To conform with the rest of the PR reports I also added a modification which produces an HTML page:
https://gist.github.com/qstokkink/0b6f7aed57f698f87df4dd77feb18e9f#file-spellchecker_html-sh

**Comment by qstokkink** [comment]
@devos50 Do you mind if I play around on Jenkins with this for a bit? Without adding it to the actual PR chain of course. I think I can use a copy of GH_Tribler_PR_pylint_check to do this pretty easily.

**Comment by devos50** [comment]
@qstokkink no problem. But if you have some time left and you want to contribute, I would like some help with the outstanding issues for Tribler 7 (see https://github.com/Tribler/tribler/milestone/13).

**Comment by qstokkink** [comment]
@devos50 thanks and yeah, I've been looking at those issues as well. After a long day of bugfixes though, one also craves some entertainment in the form of bringing the grammar hammer down upon forgotten documentation.

**Comment by qstokkink** [comment]
Alright: GH_Tribler_PR_spelling_check should be able to be added to the `Tests and style` jobs of GH_Tribler_PR whenever you like.

**Comment by devos50** [comment]
@qstokkink you can add it if you want 👍

**Comment by qstokkink** [comment]
@devos50 Alright, I'll use #2709 for testing.

**Comment by qstokkink** [comment]
Woop woop: https://jenkins.tribler.org/job/GH_Tribler_PR_spelling_check/3//artifact/output/spelling_report.html

**Comment by devos50** [comment]
I noticed, good job :)

**Comment by devos50** [comment]
I guess this issue can be closed now?

**Comment by qstokkink** [comment]
Yea, we should also make a new one to actually correct the errors :D
