### ISSUE TITLE
Including files with `+` characters in the file name fails.

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2705]
##### Tribler version/branch+revision: #####

8eadecd94da2849b54e801bc90c61b93694989ff #2701 

##### Steps to reproduce the behavior: #####

1. Have download where some excluded files have character `+` in the name
2. Try to include them

##### Expected behavior: #####

Value in "included" column changes from "no" to "yes", file gets moved from `.unwanted`.

##### Actual behavior: #####

Value stays `no`, file stays in `.unwanted`

##### Relevant log file output: #####

Nothing special that differs from successful include.

**Comment by vi** [comment]
assign @devos50

**Comment by devos50** [comment]
Thanks for the report!

**Comment by devos50** [comment]
Verified this and found another bug when adding a torrent to your channel with a `+` in it. This happened because I didn't url-encode the data when sending it to Tribler. Probably the same problem arises here.

**Comment by devos50** [comment]
It was the same problem; will be fixed in the next PR.
