### ISSUE TITLE
MULTICHAIN: Tunnel candidate not found

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#2717]
I have been seeing some TunnelCommunity entries in the 1h experiment log:
```
WARNING:TunnelLogger:MULTICHAIN: Tunnel candidate not found
```
This is only printed when previously established (Candidate + Member object) community members can no longer be found. Since the socket address is known, there is no need for this condition to occur (this is all the information needed to construct a Candidate object - see the recently implemented [copy_shallow_candidate()](https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/tunnel_community.py#L505)).

**Comment by devos50** [comment]
@qstokkink want to solve this issue?

**Comment by qstokkink** [comment]
@devos50 sure, I'll fix this up tomorrow

**Comment by devos50** [comment]
@qstokkink great, thanks!
