### ISSUE TITLE
Detect PR documentation spelling regression

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#2719]
Right now the documentation spelling checker only compiles a report of the spelling errors in a PR's documentation. Ideally we would like to have this fail if the amount of spelling errors increases.

**Comment by devos50** [comment]
That would be nice indeed :)

**Comment by qstokkink** [comment]
@devos50 Should we include the spelling checker as a submodule so people can check their spelling offline (instead of having to fire a PR)?

**Comment by devos50** [comment]
@qstokkink I don't think people that are working on documentation will do that frequently so imo it's fine to keep it in the PR check. Also, I would like to keep the stuff in the repo Tribler-related and not pollute it with external tools.

**Comment by qstokkink** [comment]
Alright, the PR check now shows the added violations and fails the spelling check if new unknown words are introduced:
![check_preview](https://cloud.githubusercontent.com/assets/3630389/21955442/9363206a-da6b-11e6-8b68-e7a22c5ea22f.png)
