### ISSUE TITLE
Tribler frontpage resize issue: scrollbar or empty space

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2724]
_low priority_

![tribler7_scrollbar_appearing](https://cloud.githubusercontent.com/assets/325224/21965435/fc899016-db5f-11e6-9c63-5d32a5537656.png)

When making Tribler 7 wide and small, a scrollbar appears on the side. If we make Tribler very thin and tall, no other squares appear.
![tribler_7_scrollbar__empty_space](https://cloud.githubusercontent.com/assets/325224/21965456/667f5c44-db60-11e6-8365-62f55eb93551.png)

**Comment by ichorid** [comment]
RIP recommended screen
