### ISSUE TITLE
Not all correct bits set before transmission error in Dispersy when creating introduction request

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2726]
Got this one in the error reporter today:

```
Traceback (most recent call last):
File "/srv/home/stephane/Public/src/tribler/TriblerGUI/event_request_manager.py", line 91, in on_read_data
raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Failure instance: Traceback: <type 'exceptions.AssertionError'>: does not have all correct bits set before transmission
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:1199:run
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:1208:mainLoop
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:828:runUntilCurrent
/usr/lib/python2.7/dist-packages/twisted/internet/task.py:239:__call__
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:150:maybeDeferred
/srv/home/stephane/Public/src/tribler/Tribler/dispersy/community.py:1217:take_step
/srv/home/stephane/Public/src/tribler/Tribler/dispersy/community.py:2702:create_introduction_request
]
```

@qstokkink can you say anything about this? Could this be a bug somewhere in Dispersy?

**Comment by qstokkink** [comment]
This occurs when the bloomfilter tests positive for (one or more) packets it shouldn't be set to contain. How this would happen is unknown to me.

**Comment by devos50** [comment]
Yeah, I think this one will be quite hard to track. I will keep an eye on the amount of reports of this error in our backend and postpone it.

**Comment by devos50** [comment]
Dispersy is end of life.

**Comment by devos50** [comment]
This one might show up during our application tests, as seen here: https://jenkins-ci.tribler.org/job/Deployment-Tests/job/Run_Tribler_Release/job/Run_Ubuntu_18.04/40/console.

After some debugging, I suspect that there is an incoming packet between https://github.com/Tribler/dispersy/blob/devel/community.py#L2703 and https://github.com/Tribler/dispersy/blob/devel/community.py#L2717. This 'new' packet should result in the assertion error, since the packets already in the bloom filter, and the packets fetched from the database do not match. This is rare but it could happen.

@qstokkink I suggest a quick fix by commenting out the assertions on line 2731 and 2732. Do you agree?

**Comment by qstokkink** [comment]
As I've undeprecated the bloomfilter, we'll have to properly fix it now. We should probably make it throw a proper exception to tell the programmer that the bloomfilter is full.

**Comment by devos50** [comment]
Well, I don't think it is related to the bloomfilter itself but caused by (incorrect) logic that interacts with the bloomfilter, and makes assumptions on its content. See my previous post 👍

**Comment by synctext** [comment]
Bloom filter are guaranteed to be void of false negatives. Will have occasionally a false positive. Is this clear in the logic and documented in .py comments what happens?
(Or completely unrelated...)

**Comment by synctext** [comment]
Never mind, old Dispersy only...

**Comment by qstokkink** [comment]
@devos50 ah I thought you meant that the new incoming packets were filling it up, I read that wrong. If it is indeed what you say, it's fine to comment that out: yes.
