### ISSUE TITLE
Error when sorting the list of downloads

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2729]
Got this bug report:

```
Traceback (most recent call last):
File "TriblerGUI\widgets\downloadwidgetitem.py", line 77, in __lt__
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Not sure what happens here. I think this might occur when adding an additional download to an already-sorted list?

**Comment by qstokkink** [comment]
The error is that either `self.download_info` or `other.download_info` is `None` when sorting on `"progress"`.
My intuition would be that this `None` value is set in [`on_download_item_clicked()`](https://github.com/Tribler/tribler/blob/96e4c70c775f15c606f7f25c6e3973b9d190f33f/TriblerGUI/widgets/downloadspage.py#L180) through some exotic multiple selection case.

**Comment by devos50** [comment]
Managed to reproduce it by adding a torrent when sorting on the `progress` column :)
