### ISSUE TITLE
Arch Linux dependencies are out of date

### ISSUE THREAD

**Issue by vandenheuvel** [Tribler/tribler#2732]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
devel, 19ecae714f037916c8ae8a05c962d7e2914331d2

##### Operating system and version: #####
Arch Linux, kernel version 4.8.13-1

The dependencies listed for Arch Linux [here](https://github.com/Tribler/tribler/blob/devel/doc/development/development_on_linux.rst#L67) are no longer up to date. It appears that dependencies python2-chardet, python2-pyqt5, qt5-svg and phonon-qt5-vlc and their dependencies were required for me to run Tribler with GUI. Also, dependencies python2-gmpy2, python2-pillow and wxpython2.8 seem no longer used.

**Comment by vandenheuvel** [comment]
With the dependencies described above, running Tribler on Wayland with Sway works seamlessly. This includes the video player.

**Comment by devos50** [comment]
Thanks!

**Comment by vandenheuvel** [comment]
Updated this in pr https://github.com/Tribler/tribler/pull/2733.

**Comment by vandenheuvel** [comment]
Second try in pr https://github.com/Tribler/tribler/pull/2736.
