### ISSUE TITLE
ALpha v.7 build #341 console window output @ Windows 10

### ISSUE THREAD

**Issue by slrslr** [Tribler/tribler#2734]
##### Tribler version/branch+revision: #####
Alpha v7, Build #341 - https://jenkins.tribler.org/job/Build-Tribler_Win64/341/

##### Operating system and version: #####
Windows 10 Home 64bit

i apologize if this is wrong place to post this.

I ran the downloaded Tribler_7.0.0-alpha2-4-g19ecae7_x64.exe (build 341) installer. It invited me to delete previous Tribler version. It completed and installed new version (destination folder was Program Files, but because my previous version was in Program Files x86, i selected x86 folder. After installation, i launched Tribler and there is a console window with output:

> Qt: Untested Windows version 10.0 detected!
> Warning: option --plugin-path no longer exists.
> Warning: option --plugin-path no longer exists.
> QSslSocket: cannot resolve TLSv1_1_client_method
> QSslSocket: cannot resolve TLSv1_2_client_method
> QSslSocket: cannot resolve TLSv1_1_server_method
> QSslSocket: cannot resolve TLSv1_2_server_method
> ERROR:TriblerGUI:Got Tribler core error: 1
> Qt: Untested Windows version 10.0 detected!
> ERROR:root:No json object could be decoded from data:

Unsure if this is expected behavior, just wanted to share.

When searched for "suits" using search field on the top of the Tribler screen, Tribler crashed and i sent report i was invited to send. It happened multiple times, just do one search after another. Search worked couple of times but after like 2 searches it crashed.

**Comment by devos50** [comment]
Thank you for your report. The console is expected behaviour and helps us to debug crashes.

I examined the crash report and it's an issue that I've already solved but these changes aren't merged into our upstream repository yet. The next alpha release will not have this error.
