### ISSUE TITLE
Tribler will not delete file that was played/paused inside "Video player"

### ISSUE THREAD

**Issue by slrslr** [Tribler/tribler#2735]
Tribler version/branch+revision:

Alpha v7, Build #341 - https://jenkins.tribler.org/job/Build-Tribler_Win64/341/
Operating system and version:

Windows 10 Home 64bit

##### Expected behavior: #####
Tribler should delete all files related to the torrent when i select to remove torrent including data.

##### Actual behavior: #####
Tribler have not deleted one file which was in the "Video player" and was "paused" in the player. I think in the player was also other files of the torrent, but only this one which was active in the player was not deleted.

##### Steps to reproduce the behavior: #####
Have a torrent with some video file, play the video in the inbuild player and pause it. Then right click on torrent and select to delete it and select to delete including data. You can see on your HDD that it left one file that was "active" in the player. Such file can not be deleted because WIndows says it is opened by Tribler. When i go to inbuild Video player, file is not there so i assume i need to re-open Tribler in order file can be deleted. I reproduced it on multiple torrents.

Hope Tribler can be instructed to release torrent's files from player so it does not miss any file when deleting torrent including data.

**Comment by devos50** [comment]
Thanks for the report! 👍
