### ISSUE TITLE
Tribler refuse to DL torrent into path which contains diacritics

### ISSUE THREAD

**Issue by slrslr** [Tribler/tribler#2737]
##### Tribler version/branch+revision: #####
Alpha v7, Build #341 - https://jenkins.tribler.org/job/Build-Tribler_Win64/341/
##### Operating system and version: #####
Windows 10 64bit Home
##### Expected behavior: #####
Tribler working with paths containing diacritics
##### Actual behavior: #####
Tribler says "Invalid destination directory specified"
##### Steps to reproduce the behavior: #####
Add torrent / select save path for torrent's data (in my case: "X:\Instruktážní vzdělávací") and confirm.
Tribler returns:
Request error
An error occured during request:
Invalid destination directory specified

In my language (czech) we use diacritics: ě š č ř ž ý á í é

**Comment by devos50** [comment]
Thanks for this report! There are still some errors regarding unicode paths out there and it seems that you have found one of them. We will test it and make sure it will be fixed in the next release.

**Comment by devos50** [comment]
Turned out that I forgot to decode the destination path when adding a new torrent, will be fixed in the next PR.
