### ISSUE TITLE
Stopping torrent during "Building circuits" will leave it on that state in the UI, not "Stopped".

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#2746]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

Tribler_7.0.0-alpha2-34-g67f495c_x64.exe (from Jenkins)

##### Operating system and version: #####
Windows 10 Home,
Version 1607
OS-Build: 14393.693
 
##### Expected behavior: #####
Selected torrent will change to state "Stopped".

##### Actual behavior: #####
Torrent remains on "Building Circuits" even though every other torrent with same amount of hops (i had them set to 1) will work as normal. Restarting Tribler, the stopped torrents seem to remain in an active state, so if it would have seeded after establishing circuits, then it will do that when you start, same if it would download. I'm no aware if the torrent actually downloads when it's locked in "Building circuits". Either the state is not saved, or it's not changed when you do try to stop it. 

Side note, sometimes you get the option to stop said torrent when you right click, stopping, and then starting will make it work like normal again. Don't think you need to stop if first, haven't investigated enough. 

##### Steps to reproduce the behavior: #####
Open Tribler, go to downloads, and stop a torrent(that will be active once circuits are built) while in "Building circuits" state.

##### Relevant log file output: #####
No log output.

**Comment by devos50** [comment]
Confirmed, will be fixed in the next release.
