### ISSUE TITLE
Current GUI does not support high DPI display

### ISSUE THREAD

**Issue by EinNarr** [Tribler/tribler#2748]
Currently running Tribler with a 4K 15 inch display. The letters are extremely small and the label on buttons are only partly visible.

Any way it gonna support dynamic DPI scaling?

**Comment by devos50** [comment]
That would be nice but it's currently not considered as high priority so I will move it to a later milestone.

**Comment by qstokkink** [comment]
![tribler_scaling](https://cloud.githubusercontent.com/assets/3630389/23213119/fe1b63a6-f909-11e6-951c-b600c81bc8f0.png)

**Comment by wcruppel** [comment]
FYI, in the meantime, you can workaround by using QT_SCALE_FACTOR environment variable, example QT_SCALE_FACTOR=2 works nice on my 4K TV.

**Comment by devos50** [comment]
@wcruppel that's a good workaround, thanks for reporting this! We should add this to our README.
