### ISSUE TITLE
Tribler crashing when receiving invalid packet in Dispersy

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2750]
This is something we already observed before: Tribler crashes when we receive a packet that is invalid in Dispersy by throwing an `AssertionError`. However, an assertion is in my opinion not the way to handle the invalid packets since we cannot guarantee that packets we receive, are always correct. See the following stack trace for instance (IP address removed though):

```
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 91, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "lib\multiprocessing\process.py", line 114, in run

File "TriblerGUI\core_manager.py", line 61, in start_tribler_core

File "lib\site-packages\twisted\internet\base.py", line 1195, in run

File "lib\site-packages\twisted\internet\base.py", line 1204, in mainLoop

--- <exception caught here> ---
File "lib\site-packages\twisted\internet\base.py", line 798, in runUntilCurrent

File "Tribler\dispersy\endpoint.py", line 252, in dispersythread_data_came_in

File "Tribler\dispersy\dispersy.py", line 1466, in on_incoming_packets

exceptions.AssertionError: [('<Candidate xxx.xxx.xxx.xxx:1897>', "'\\x00\\x1d'")]
```

I propose to make a method in `dispersy.py` that returns `True` when a packet is valid and passes all checks. If it does not pass the check, we do not process it.

@qstokkink do you agree with this?

**Comment by synctext** [comment]
the Dispersy parser should simply be robust to all possible inputs, including the _lethal_ '\\x00\\x1d' string...

No need to first do a Dispersy parser, then a processor. I think we have protocol buffers for that at some point. But @qstokkink can decide all this.

**Comment by qstokkink** [comment]
I second @synctext's opinion. 

However, I would like to mention that Dispersy is spring-loaded with a lot more of these types of asserts. Right now, it is very easy to selectively shut down other Tribler/Dispersy users with modified packets.

So, until we reach Dispersy Nirvana, I suggest we simply hook up a general exception handler (or AssertionError handler) on the `dispersythread_data_came_in()` function. This will make it substantially more difficult to search-and-destroy other users.

**Comment by devos50** [comment]
@qstokkink you mean something like this? https://github.com/Tribler/dispersy/pull/522

**Comment by qstokkink** [comment]
@devos50 Yes, that would do it. 👍
