### ISSUE TITLE
"Running" multiple downloads before tribler starts causes problems. 

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#2751]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.
 

(Sorry for vague title, was not sure how to avoid making the title a paragraph to explain well.)
##### Tribler version/branch+revision: #####
Tribler_7.0.0-alpha2-34-g67f495c_x64.exe (from Jenkins)

##### Operating system and version: #####

Windows 10 Home,
Version 1607
OS-Build: 14393.693

##### Expected behavior: #####
Running two(or more) .torrent files rapidly, will open Tribler normally and let you select specifics for each download.

##### Actual behavior: #####
The opening and download selection works well, however, the issue is that when you press download, you get taken from the start screen to the downloads page, and this removes every download selection windows except the first one (that you pressed download on.) So, the download pop-up disappears, and won't appear again, even if you run open new torrents the download selection will not appear. 

##### Steps to reproduce the behavior: #####
Double click on multiple torrents, while Tribler is closed. Press download on that first torrent, and you'll be taken out of the download selection screen to the downloads list. Since i use a torrent download and run program, they will all start Tribler roughly at the same time, causing the issue. (Unless i have Tribler open already.) Only times this didn't happen was when Tribler didn't move to the downloads screen after pressing download on the first torrent. 

Workaround: Select any torrent file with triblers add torrent function, this will cause all attempted torrents to appear (i think, many of them at least. Didn't count) and make the function work as expected again. (Did not try magnet and directory adding.)

##### Relevant log file output: #####
None.

**Comment by synctext** [comment]
ahhh. thnx! Magnet links can start a Tribler instance. Launching Tribler using multiple .torrent files fails.
got it.

**Comment by devos50** [comment]
Turned out to be a race condition when adding a Windows, I already have a fix available.
