### ISSUE TITLE
API returns invalid JSON when adding a torrent twice

### ISSUE THREAD

**Issue by vandenheuvel** [Tribler/tribler#2755]
##### Tribler version/branch+revision: #####
devel, 67f495c194b4286b3c82a07676ea228430ac8957

##### Operating system and version: #####
Ubuntu 16.10

##### Expected behavior: #####
Tribler returns some sensible error in valid JSON.

##### Actual behavior: #####
The API returns the code below:
```
{"error": {"message": "This download already exists.", "code": "DuplicateDownloadException", "handled": false, "trace": ["  File \"/usr/lib/python2.7/dist-packages/twisted/web/server.py\", line 190, in process\n    self.render(resrc)\n", "  File \"/usr/lib/python2.7/dist-packages/twisted/web/server.py\", line 241, in render\n    body = resrc.render(self)\n", "  File \"/usr/lib/python2.7/dist-packages/twisted/web/resource.py\", line 250, in render\n    return m(request)\n", "  File \"/home/user/tribler/Tribler/Core/Modules/restapi/downloads_endpoint.py\", line 273, in render_PUT\n    unicode(parameters['uri'][0], 'utf-8'), download_config)\n", "  File \"/home/user/tribler/Tribler/Core/Session.py\", line 282, in start_download_from_uri\n    return self.lm.ltmgr.start_download_from_uri(uri, dconfig=dconfig)\n", "  File \"/home/user/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py\", line 520, in start_download_from_uri\n    return succeed(self.start_download(torrentfilename=argument, dconfig=dconfig))\n", "  File \"/home/user/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py\", line 576, in start_download\n    raise DuplicateDownl
```

##### Steps to reproduce the behavior: #####
Add a torrent using the API, wait until the download is finished, add the same torrent again.

**Comment by devos50** [comment]
@vandenheuvel the API should never return invalid JSON. Which tool did you use to get this?

**Comment by vandenheuvel** [comment]
I used `curl`.

**Comment by devos50** [comment]
@vandenheuvel maybe curl is truncating content somehow? Could you try another tool?

**Comment by Dmole** [comment]
curl is the old stable standard, it's unlikely to misbehave.
what was the exact full command (and output with -v )?

**Comment by vandenheuvel** [comment]
The exact command was
`curl -X PUT http://10.0.3.128:8085/downloads --data "uri=file:/home/user/test.torrent"`.
Now that I've restarted my machine (and Tribler), I can't reproduce the issue. But @MaxVanDeursen is my witness :)

**Comment by devos50** [comment]
Maybe it was some terminal-related issue then?
