### ISSUE TITLE
api doc is 404

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#2757]
This page is 404:
https://www.tribler.org/api/
from this page:
https://www.tribler.org/TriblerAPIRationale/
should point to here:
http://tribler.readthedocs.io/en/latest/restapi/introduction.html

**Comment by EinNarr** [comment]
https://github.com/Tribler/tribler.github.com
This contains the website. But we cannot find /api there.
@devos50

**Comment by devos50** [comment]
Thank you. Our website is very old and contains a lot of outdated information. I've redirected the api to the readthedocs page so it should be ok now.
