### ISSUE TITLE
searching for a very long string causes screen re-size

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2759]
search for a string like this in Tribler, triggers a re-size (on Mac at least) "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

**Comment by qstokkink** [comment]
I cannot reproduce this on Mac. I assume it has been fixed already.
