### ISSUE TITLE
Watch folder doesn't seem to heed anonymity setting.

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#2764]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Tribler_7.0.0-alpha2-34-g67f495c_x64.exe (from jenkins)

##### Operating system and version: #####

Windows 10 Home,
Version 1607
OS-Build: 14393.693

##### Expected behavior: #####
Torrents in watch folder will be added with anonymity, set to 1 hop. As per Tribler settings and thus the same as default behavior when you add a torrent without changing anything.

##### Actual behavior: #####
Torrents added without no hops. 

##### Steps to reproduce the behavior: #####
Set up watch folder, add torrents to it. Torrents will download without a hop. 

##### Relevant log file output: #####
No output.

**Comment by devos50** [comment]
Good find, thanks for the report!
