### ISSUE TITLE
Add a torrents comment in the details tab.

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#2767]
Just a minor suggestion, as torrents have the info stored in their state file already, but have no implementation as far as i've noticed. Just add another line under "Details", where torrent size, status, and such are. 

Potentially add support for clicking a link(URL) too. Only reason i say link support is because i noticed a torrent added a link to their site in a comment. Though, that's depends more on if you want to be able to open link from Tribler. I know i won't use that particularly often, but the option is always nice.

**Comment by devos50** [comment]
Thanks for the suggestion!

**Comment by devos50** [comment]
This has been implemented on the `next` branch already.
