### ISSUE TITLE
Tribler 7 alpha violates cookielaw

### ISSUE THREAD

**Issue by Captain-Coder** [Tribler/tribler#2769]
#### Please, fill all relevant items: ####
- [x] I have read CONTRIBUTING.rst
- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Tribler 7 alpha 3

##### Operating system and version: #####
Windows 7 (x86-64)

##### Expected behavior: #####
Tribler should ask for an ok on installing VLC, as per the [cookielaw](https://cookierecht.nl/cookiewet/ook-installatie-van-additionele-software-valt-onder-de-cookiewet/)

Also it doesn't uninstall if I remove tribler.

And I rather expect tribler to use my system default media player (vlc is the 4th one on my system!), and not embed its own. But that is a different issue.

##### Actual behavior: #####
Tribler installs VLC w/o any notification, not approval.

##### Steps to reproduce the behavior: #####
Run the windows installer for Tribler.

##### Relevant log file output: #####
N/A

**Comment by Dmole** [comment]
"...Arch Linux ... windows installer..."
The cookie law should be satisfied with popular package management systems like pacman/apt/yum because they ask if installing additional packages to fill dependencies is OK. The Windows package manager is lacking so likely the windows installer should just list all bundled libraries.

**Comment by ThomasdenH** [comment]
It depends. If the libraries are used inside Tribler I think (I'm not a lawyer) you could argue that since it is part of the software the cookielaw does not apply. In the example from the link the installed software is completely independent from eachother.

**Comment by Captain-Coder** [comment]
Whoops on the OS version, I copy pasted from another of my issues :) I'll correct it.

But VLC really installs as a separate packege, it shows up in the Programs part of the control panel, I have to remove it separately, it installs hooks in the context menu of windows explorer etc... I think there is a very good case that it does violate the cookielaw.

**Comment by devos50** [comment]
We should adapt Tribler so it can run properly without VLC installed. I suggest to hide (or disable) the video player button in this case.

**Comment by devos50** [comment]
Pushing this one to a later milestone.

**Comment by synctext** [comment]
it could be a solution to have a checkbox in the installer. Such as 'install required streaming software like VLC'. Default is on.
This clutters the user experience. I'm not in favor of this solution. we're not installing malware or software with Tribler. just one giant megaclient...

**Comment by synctext** [comment]
do we not list all our bundeled packages on Windows?
