### ISSUE TITLE
Torrents that have a destination to a harddrive that's not plugged in, won't appear when Tribler starts.

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#2771]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Tribler_7.0.0-alpha2-34-g67f495c_x64.exe

##### Operating system and version: #####
Windows 10 Home,
Version 1607
OS-Build: 14393.693

##### What happens: #####
Not entirely sure if this is a bug, or intended behavior. When Tribler is downloading a something to drive I for example, when you close Tribler, and unplug I, and then start Tribler, said torrent won't appear in the list at all. 

Plugging in drive and restarting Tribler, and everything works like normal. 

One would expect tribler to raise a error, or warn user some torrents are hidden or stopped due to target drive is missing. 

##### Steps to reproduce the behavior: #####
Download to a drive you can unplug/detach, close tribler, and then detach drive. Restart Tribler. Said torrent will be gone.  

##### Relevant log file output: #####
No log output as far as i noticed.

**Comment by devos50** [comment]
As far as I know, we don't have any check for a valid destination. Does this also happen when using a flash drive?

**Comment by Thomasedv** [comment]
I use a external HDD with a size of 2 TB. Connected with USB, i don't really know if there's a difference from Windows perspective. 

I don't think i have USB at hand to test at the moment.

**Comment by devos50** [comment]
I've just checked with a flash drive and I'm getting the following error in my terminal:

```
Traceback (most recent call last):
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 661, in resume_download
    self.add(tdef, dscfg, pstate, setupDelay=setupDelay)
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 343, in add
    os.makedirs(dscfg.get_dest_dir())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Volumes/OS X Base System'
```

This explains why the torrent is not added, we should catch the `OSError` and let the download go in error state.
