### ISSUE TITLE
Unwanted download at every start

### ISSUE THREAD

**Issue by Antiade** [Tribler/tribler#2775]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

**Comment by devos50** [comment]
@Antiade I think you have credit mining enabled somehow. Can you check whether this is enabled in your Tribler configuration file (located at `~/.Tribler/libtribler.conf`)?

**Comment by Antiade** [comment]
You're right. I've checked the dedicated folder and the files are cumulating there, but I can't find the settings for credit mining in the GUI. 

[Tribler]
version_info = {'first_run': 1478460796, 'version_id': '6.6.0-exp1'}
maxuploadrate = 50
saveas = /home/------------/Downloads/TriblerDownloads
default_number_hops = 3
use_webui = True
use_emc = True
window_width = 1024
window_height = 726
window_x = 0
window_y = 24
recent_download_history = ["/home/---------/Downloads/TriblerDownloads"]
confirmonclose = 1
maxdownloadrate = 0
default_anonymity_enabled = True
default_safeseeding_enabled = True
sash_position = -185
family_filter = 0
webui_port = 8080
emc_ip = 127.0.0.1
emc_port = 8332
emc_username = tribler
emc_password = tribler
showsaveas = 1
i2ilistenport = 57891
mintray = 0
free_space_threshold = 104857600
last_reported_version = None

[downloadconfig]
version = 15
saveas = /home/-------/Downloads/TriblerDownloads
max_upload_rate = 0
max_download_rate = 0
mode = 0
hops = 0
selected_files = []
correctedfilename = None
safe_seeding = True
seeding_mode = ratio
seeding_ratio = 1.0
seeding_time = 60.0
user_stopped = False
time_added = 0

**Comment by devos50** [comment]
@Antiade please see the `libtribler.conf` file (not `tribler.conf`).

**Comment by Antiade** [comment]
Sorry. Thank you for your patience.
[general]
version = 15
state_dir = None
install_dir = /usr/share/tribler
ip = 0.0.0.0
minport = 7760
maxport = 7760
bind = []
ipv6_enabled = 0
ipv6_binds_v4 = 1
timeout = 300.0
timeout_check_interval = 60.0
eckeypairfilename = /home/--------/.Tribler/ec.pem
megacache = True
nickname = Tribler User
mugshot = None
videoanalyserpath = /usr/bin/ffmpeg
peer_icon_path = /home/----------/.Tribler/icons
live_aux_seeders = []
ec_keypair_filename_multichain = /home/---------/.Tribler/ec_multichain.pem

[allchannel_community]
enabled = True

[channel_community]
enabled = True

[preview_channel_community]
enabled = True

[search_community]
enabled = True

[tunnel_community]
socks5_listen_ports = [-1, -1, -1, -1, -1]
exitnode_enabled = True
enabled = True

[multichain]
enabled = True

[barter_community]
enabled = False

[metadata]
enabled = True
store_dir = /home/---------/.Tribler/collected_metadata

[mainline_dht]
enabled = True
mainline_dht_port = -1

[torrent_checking]
enabled = 1

[torrent_store]
enabled = True
dir = /home/-----------/.Tribler/collected_torrents

[torrent_collecting]
enabled = True
dht_torrent_collecting = True
torrent_collecting_max_torrents = 50000
torrent_collecting_dir = None
stop_collecting_threshold = 200

[libtorrent]
enabled = True
lt_proxytype = 0
lt_proxyserver = None
lt_proxyauth = None
utp = True
anon_listen_port = -1
anon_proxytype = 2
anon_proxyserver = ('127.0.0.1', [51861, 53333, 11373, 22654, 48395])
anon_proxyauth = None
max_connections_download = -1

[dispersy]
enabled = True
dispersy_port = 7759

[video]
enabled = True
path = /usr/bin/vlc
port = -1
preferredmode = 0

[upgrader]
enabled = True

[watch_folder]
enabled = False
watch_folder_dir = /home/----------/Downloads/TriblerWatchFolder

[http_api]
enabled = True
port = 8085

[credit_mining]
enabled = True
max_torrents_per_source = 20
max_torrents_active = 50
source_interval = 100
swarm_interval = 100
share_mode_target = 3
tracker_interval = 200
logging_interval = 60
boosting_sources = ['http://bt.etree.org/rss/bt_etree_org.rdf']
boosting_enabled = ['http://bt.etree.org/rss/bt_etree_org.rdf']
boosting_disabled = []
archive_sources = []
policy = seederratio

**Comment by devos50** [comment]
@Antiade under `[credit_mining]`, please change `enabled = True` to `enabled = False` 👍

**Comment by Antiade** [comment]
Fixed. Thanks again.
