### ISSUE TITLE
Would it be more modular using relative import?

### ISSUE THREAD

**Issue by EinNarr** [Tribler/tribler#2785]
Currently I am coding a Kodi add-on for Tribler. I found that all internal import in Tribler are using absolute import. This would make it difficult for people who may want to run Tribler as a module, because it will not find the right path. Would it be better if Tribler can use relative import instead?

**Comment by synctext** [comment]
if coming days Martijn and Egbert don't object.. then you're OK to make your first pull request to improve our code.

**Comment by egbertbouman** [comment]
Not sure about this. I think it's clearer to keep using absolute imports.

**Comment by devos50** [comment]
@EinNarr I'm against using relative imports for various reasons. First, if we are going to change the import style, we should change everything which is quite a lot work and error prone. Second, I think relative imports are less readable than absolute imports (actually, I believe relative imports are even discouraged by a PEP style).

Also, it's not that hard to add the Tribler directory to your (python) path.
