### ISSUE TITLE
Peers: -1

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2786]
##### Tribler version/branch+revision: #####

bf615b01b5c987243ea990372ef8c68c65c0820f  v7.0.0-alpha3

##### Operating system and version: #####

Linux Debian

##### Actual behavior: #####

![r](https://cloud.githubusercontent.com/assets/173219/22805856/886875b4-ef30-11e6-97ad-62a80e834dbc.png)

Slowly fluctuates between -1, 0 and 1.

**Comment by devos50** [comment]
That's a weird bug. Is the download anonymous?

**Comment by vi** [comment]
Yes.
