### ISSUE TITLE
SOCKS5 Server should never deny associate requests

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#2787]
Currently the SOCKS5 server denies libtorrent's proxy connection if the tunnel community does not have enough circuits, see https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/Socks5/server.py#L223 .

Libtorrent's response to this, is to not use the proxy and start a naked download.

Usually this is symptomatic of [the tunnel community not being registered correctly in tests](https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py#L265). However, this may also occur in the wild if circuits are dropped in between [can_create_engine_wrapper](https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py#L253) and [network_create_engine_wrapper](https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py#L288) calls (__bad!__).

**Comment by devos50** [comment]
@qstokkink do you want to take a look at this?

**Comment by qstokkink** [comment]
@devos50 sure

**Comment by egbertbouman** [comment]
For anonymous downloading we're setting libtorrent's anonymous_mode to
True. Isn't that supposed to prevent this from happening?

**Comment by qstokkink** [comment]
@egbertbouman if it's supposed to, it isn't doing it. Just found this: Arvid [shared on stackoverflow](http://stackoverflow.com/a/39069606) that it should be the `force_proxy` setting.

**Comment by egbertbouman** [comment]
@qstokkink That's good to know! I guess we should use that as well, then.
