### ISSUE TITLE
Tribler 7.0 download colums, resize is not remembered

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#2796]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

**Comment by devos50** [comment]
I consider this not very high priority and I will move it to a later milestone.

**Comment by da2x** [comment]
Is there any more to this than QHeaderView saveState() and restoreState()?

**Comment by drew2a** [comment]
Fixed in
- #8020
