### ISSUE TITLE
Alpha 2 : Pick download location not working as in 6.5

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#2797]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Expected behavior: #####
When I pick a location like d:\TVSERIES\SERIENAME\SEASON01 the files should be placed in this folder.
##### Actual behavior: #####
An extra folder is created equal to the torrent name and the torrent file with the same name is placed in that folder.

##### Steps to reproduce the behavior: #####
Just download a torrent and select a location

**Comment by Thomasedv** [comment]
Isn't it not up to Tribler, but how the files are themselves that does this? Some torrents come as a single files, some come as a folder with one or more files. If so, the only thing Tribler can do, is show if the torrent is a folder with files or just a file/files, as it doesn't do that well right now. (It's been mentioned as an enhancement elsewhere.)

**Comment by Nubro01** [comment]
It used to work before 6.5.2, just means that if a location is picked and it differs from the default like d:\TRIBLER  that the torrent information should be adjusted. In the 6.5 period, I just picked the correct location and I was done. After 6.5.2 I have to stop seeding and delete the Torrent and move files to the correct location, meaning extra work and less seeding if I want my files to be properly organized.

**Comment by devos50** [comment]
We tested our the functionality of Tribler and we agree that the current way Tribler stores its downloads, is the correct one. Therefore I will close this issue.

**Comment by Nubro01** [comment]
I will check, if this is the case. Since it didn't work before, I am now always downloading to D:\tribler and moved the files manually.

**Comment by Nubro01** [comment]
I checked and it is STILL WRONG!!!, With 6.5.2, one could pick a location and the selected file was placed within that selected folder and NO extra folder was created with the name of the Torrent. After 6.5.2 the extra folder is created like in D:\Tribler\TVSeries\Greys Anatomy\Season14\Greys.Anatomy.S14E16.XviD-AFG , that last folder shoud NOT be created. At least is was not with 6.5.2. I only selected the avi file to be downloaded and still it was in its own folder, meaning it is of no use. With 6.5.2 my downloads always came in their correct location, without manual intervention. Now I still have to do things manually.

**Comment by Nubro01** [comment]
Hi,

I just tested and added some comments to this issue, but I was unable to see these comments.
This is still NOT WORKING as it was within 6.5.2, still an extra folder is created with the name of the Torrent. With 6.5.2 when one selected a special folder, just the selected file was placed in that folder. Since 6.5.2 and EXTRA folder is created which makes it much harder to NOT manually maintain your files. Instead of a folder structure of D:\TVSeries\SERiename\Seasonxx\ and then all the single selected files, you now get an extra folder for each created file for that specific serie. Meaning, you have to remove the Torrents and move the files. If they would be in the correct folder then I could keep seeding, now I stop seeding until I reach the max, remove the torrent to be able to move the file needed.
If one would NOT select a special folder, but instead kept the default location like D:\tribler then you are correct and to keep the default folder clean an extra folder should be created, but not when selecting a folder, different from the default location!!!!!

Regards

Ron

Van: Martijn de Vos [mailto:notifications@github.com]
Verzonden: donderdag 22 maart 2018 15:00
Aan: Tribler/tribler
CC: Ron Nuberg; Author
Onderwerp: Re: [Tribler/tribler] Alpha 2 : Pick download location not working as in 6.5 (#2797)


Closed #2797<https://github.com/Tribler/tribler/issues/2797>.
