### ISSUE TITLE
Tribler 7: Downloaded location, no history like in 6.5

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#2798]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Expected behavior: #####
When picking a location for the files to download, a history was shown of the last 15 downloads, selection was fast.
##### Actual behavior: #####
Now we have to browse the file system every time we download a different Torrent.
##### Steps to reproduce the behavior: #####
Pick a download location, no history like in 6.5, where, by the way, the behaviour also changed from previous versions, when Niels Zeilmaker created this feature. The history showed before the correct path. In 6.5.2 the last folder like \Season01 was not remembered. For some strange reason a certain Tribler developper created a seperate folder which equals the torrent name, in the selected download location.

**Comment by devos50** [comment]
I revived this functionality in a recent commit (https://github.com/Tribler/tribler/commit/87646cef268c8ab5b0ee65edfcfc103517d4ea1c). Should be available in the upcoming beta.
