### ISSUE TITLE
TunnelCommunity Tunnels should inherit from the same base class

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#2799]
Right now there are three types of tunnels in the TunnelCommunity which are used throughout the code as `tunnel` objects. This leads to a lot of duplicate code, both in the handlers of these classes and between the classes themselves.

We could get rid of some confusion and duplicate code if we refactor the following classes into one superclass (let's say the `Tunnel` class):

```python
class TunnelExitSocket(DatagramProtocol, TaskManager):
        self.sock_addr = sock_addr
        self.circuit_id = circuit_id
        self.community = community
        self.creation_time = time.time()
        # MISSING self.last_incoming
        self.bytes_up = self.bytes_down = 0
        self.mid = mid

class Circuit(object):
        self.first_hop = first_hop
        self.circuit_id = circuit_id
        self.proxy = proxy
        self.creation_time = time.time()
        self.last_incoming = time.time()
        self.bytes_up = self.bytes_down = 0
        self.mid = mid

class RelayRoute(object):
        self.sock_addr = sock_addr
        self.circuit_id = circuit_id
        # MISSING self.community
        self.creation_time = time.time()
        self.last_incoming = time.time()
        self.bytes_up = self.bytes_down = 0
	self.mid = mid
```
Notes:
1. Non-duplicate members have been omitted.
2. 2 member fields would need to be added overall in the three classes.

Examples:
https://github.com/Tribler/tribler/blob/devel/Tribler/community/multichain/community.py#L411
https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/tunnel_community.py#L520
https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/tunnel_community.py#L1397
https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/tunnel_community.py#L1417

**Comment by devos50** [comment]
Yeah that's a lot of duplication. I agree with a common superclass.

**Comment by qstokkink** [comment]
Fixed in IPv8.
