### ISSUE TITLE
Tribler Alpha 351 build 15 feb 2017 Download stops at 99% with lst download stats still active

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#2800]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Expected behavior: #####
When download message pops up of Torrent download completed, Download shows 100% and seeding and peers are back to 0
##### Actual behavior: #####
Download stays at 99% with latest numbers like 4.2 download and 18 peers.
##### Steps to reproduce the behavior: #####
Just download a Torrent.

**Comment by devos50** [comment]
@Nubro01 does this happen for all of your torrents? I'm thinking that the last missing piece is not available in the swarm.
