### ISSUE TITLE
Anonymous seeding is not working at all!

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#2801]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Expected behavior: #####
When seeding anonymous, upload should start
##### Actual behavior: #####
No seeding at all, even after 3 days and ratio stays of course at 0%
##### Steps to reproduce the behavior: #####
Just download a Torrent and keep anonymous seeding on.

**Comment by devos50** [comment]
We recently (2 days ago) deployed a fix for hidden seeding which should be contained in the next version.
