### ISSUE TITLE
Create a screen that displays an overview of your accumulated trust level and community contributions

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2803]
We should have a screen that gives an overview of the amount of trust that you have earned in Tribler. Initially, this can be a very easy metric, i.e. the difference between the amount of bytes that you have contributed and the amount that you have taken from other peers. We can incrementally improve this metric to make it more sophisticated.

**Comment by devos50** [comment]
Initial design:

![tribler_trust](https://cloud.githubusercontent.com/assets/1707075/23057917/9ffe8246-f4f2-11e6-8a81-bea0f6181fe0.png)

For the graph, I'm using matplotlib. We can also use this library to create other plots such as a history of download/upload speed.

**Comment by devos50** [comment]
Idea: add the number of peers you have interacted with during the past to make it a bit more social.

**Comment by synctext** [comment]
This is the live ```BarterBrowser``` deployed in [2008, see the technical report](https://github.com/Tribler/tribler/files/785967/PDS-2008-005.pdf):
![trust_browser_ape](https://cloud.githubusercontent.com/assets/325224/23104062/d7f640c8-f6c6-11e6-816c-f4faaf227075.png)
```
After we deployed BarterCast, we started a Tribler peer and allowed it to run continuously
for a month At the end of this period, the MegaCache contained information about the upload
and download behavior of 2351 peers in total, 118 of which directly bartered with this peer.
In order to make all this gossip on bartering visible we created a real-time BarterBrowser.
A screenshot of the BarterBrowser with live statistics is shown in Figure 7.
The large peer at the center depicts the local peer, other peers are positioned around it,
connected by edges induced by barter gossip.
```

**Comment by devos50** [comment]
Fixed in #2804.

**Comment by synctext** [comment]
@devos50 can you please update the image with the latest from repo, some point this week?

**Comment by devos50** [comment]
@synctext still had it in my documents directory 👍 

<img width="1280" alt="trust_screen" src="https://cloud.githubusercontent.com/assets/1707075/23372119/a2bc7c42-fd1a-11e6-9547-3d2646e5c04b.png">

**Comment by synctext** [comment]
Also works on Ubuntu now, just small color mismatch.
![tribler7__web_of_trust__uploaded_34gbyte](https://cloud.githubusercontent.com/assets/325224/23865431/f5e25cf6-0815-11e7-9870-346aca6f28d4.png)
