### ISSUE TITLE
Tribler 7 alpha3's web api binds to WAN IP

### ISSUE THREAD

**Issue by egbertbouman** [Tribler/tribler#2806]
Right now if you're connectable on port 8085, others can remote control your Tribler instance. IPs of potential targets can be easily found by crawling a recently added community. Not very anonymous, we should fix this asap.

**Comment by synctext** [comment]
@devos50 @egbertbouman The Dev team will further expand. We need code review or other procedures to try to catch this stuff as much as possible.
