### ISSUE TITLE
API port used by the GUI should be configurable by the user

### ISSUE THREAD

**Issue by egbertbouman** [Tribler/tribler#2807]
While finding https://github.com/Tribler/tribler/issues/2806, I noticed that the port for the web api seems to be hard-coded in 3 different places:
* core_manager.py
* tribler_request_manager.py
* tribler_window.py

Also, the port does not respect the setting in libtribler.conf

**Comment by devos50** [comment]
Addressed this issue in #2809; I think we need to hard-code the API port in at least one location in the GUI to keep the GUI and core truly separated.

**Comment by egbertbouman** [comment]
Instead of calling set_http_api_port, can't we just call **get**_http_port? This would get rid of the hard-coded port and also respect libtribler.conf.

**Comment by devos50** [comment]
A part of this issue got addressed, will postpone the rest of this issue to 7.1 milestone, together with the remote control.
