### ISSUE TITLE
Error not triggering bug report

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#2810]
v7.0.0-alpha3
See attached image

![te](https://cloud.githubusercontent.com/assets/1793802/23096738/b7015302-f5f0-11e6-854b-1e032a2bac90.png)

**Comment by devos50** [comment]
The error is not critical in a sense that it does not prevent a correct functioning of Tribler. I'm wondering whether this is due to a corrupt torrent or due to something in Tribler. Any way you can pass me the magnet link so I can try it myself?

**Comment by Dmole** [comment]
It was something in Tribler, because starting up v6.5.2 reset ~/.Tribler/sqlite then using v7.0.0-alpha3 again the issue was no longer and torrents previously not visible suddenly were... It's annoying how nothing is selectable in the new UI, but more importantly this issue was related to an issue that prevented the correct functioning of Tribler so having at least an option to send the full error as a bug report might help. The backup of ~/.Tribler/sqlite is >1GB which seems a bit large; maybe related.
