### ISSUE TITLE
portable biometric-based trust

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2812]
### Hacking Lab assignment TUDelft ###

Fingerprints are a fascinating way of identification. Biometric identification is a key primitive that is able to create trust in a large variety of scenarios. This project is focused on demonstrating that primitive in a specific practical scenario: a secure secret meeting.

The problem scenario is meeting people in a remote location and establishing their identity without the danger of an analog man-in-the-middle attack. Within this scenarios passports can’t be relied on, they can be falsified. You will hack together an Android app designed to identity people with extensive measures for tamper-resistance.

You will use the tamper-proof blockchain developed at TUDelft to store encrypted fingerprint images. You will design a procedure to arrange and securely identify members secure meeting members. You can assume, for instance, that encrypted fingerprints of all participants are stored beforehand on the Delft blockchain, Out-of-band trust may be assumed, encrypted fingerprints on the blockchain are authentic. An important danger is the easily duplication of fingerprint data. Once your fingerprint data leaks, you need new fingers. You can assume any modern smartphone has the storage capacity to download a complete replicate of all fingerprints and locally search fingerprint data. This portability and lack of traceability provides makes your Android app very generic. In general your app and usage procedures should provide portable trust with biometric validation. 

You are required to use the TUDelft blockchain-lab.org software for storage. If your hack is operational we will arrange a presentation of your work to the State Agency for Identity Data, responsible for Dutch passports. Semi-random list of available software: https://github.com/rtshadow/biometrics
https://github.com/cloudmesh/example-project-nist-fingerprint-matching 
https://github.com/Mauin/RxFingerprint

Use fingerprint scanner, etc

**Comment by Saminobi** [comment]
@Saminobi

**Comment by julianfx** [comment]
Hello I am also in the group

**Comment by Roccy** [comment]
@jorenham
@luHub
@jrauhamaa
@Roccy

**Comment by Roccy** [comment]
@shashankpr

**Comment by synctext** [comment]
tasks for next week:
  - Android fingerprint bitmap export
  - Feature extraction
  - database search

Existing software, compile it, and missing elements.

**Comment by synctext** [comment]
Please ignore for now, suggest focus on core fingerprint matters first. Blockchain solution by TUDelft:
  - http://blockchain-lab.org
  - docs: http://repository.tudelft.nl/islandora/object/uuid:59723e98-ae48-4fac-b258-2df99d11012c
  - spec: https://github.com/Tribler/tribler/wiki/Multichain-specifications
  - code: https://github.com/Tribler/tribler/blob/devel/Tribler/community/multichain/community.py

**Comment by jorenham** [comment]
Repo: https://github.com/jorenham/fingerblox

**Comment by jorenham** [comment]
![blockchain fingerprint 1](https://cloud.githubusercontent.com/assets/6208662/23366552/640210ce-fd07-11e6-8a21-8bab89de98b8.png)

**Comment by jorenham** [comment]
https://www.google.nl/search?q=bluetooth+fingerprint+scanner+android

**Comment by Saminobi** [comment]
Fingerprint Extraction:

* Example: https://www.youtube.com/watch?v=7VsMJI24mO8
* Steps: http://answers.opencv.org/question/6364/fingerprint-matching-in-mobile-devices-android-platform/

**Comment by synctext** [comment]
Task for final project prototype:
- Android app 
- [Sift for fingerprint feature extraction](http://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_feature2d/py_sift_intro/py_sift_intro.html)
- [Fingerprint Identification Using SIFT-Based Minutia Descriptors and Improved All Descriptor-Pair Matching](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3658737/)

**Comment by jorenham** [comment]
Github.com/jorenham/fingerblox

**Comment by synctext** [comment]
https://github.com/noureldien/FingerprintRecognition
Does it already exists ???? evaluate & study their code in detail.
![image](https://cloud.githubusercontent.com/assets/325224/23699958/85adaa8a-03f1-11e7-8e27-a75f7191818d.png)
• Fingerprint Recognition in runtime using images captured from mobile.

• Feature extraction using Gabor filter, redge orientation and SIFT. Feature matching using SIFT and RANSAC.

• This project is built using Java, Android and OpenCV. Also built in MATLAB.

• The project is done as a part of coursework for 'Advanced Computer Vision' subject, MSc Artificial Intelligence, University of Southampton.

**Comment by Roccy** [comment]
![Screenshot Camera Preview Fingerblox app](https://cloud.githubusercontent.com/assets/4048476/23955064/2503add0-0999-11e7-88d7-d0641691c444.png)

Using a fisheye/macro lens that can easily be put on a smartphone camera, a proper quality image can be taken of the fingerprint.

**Comment by synctext** [comment]
As discussed:
- important to have a wow-factor demo
- first step is camera focus problem (OK to really fix this with assembly hacking)
- background versus skin detection
- histogram equalization
- use dataset to bypass the camera problem in upcoming 2-week sprint
- [extract phone capabilities](http://stackoverflow.com/questions/11681262/android-camera-focus-mode), shown on screen

From the existing app:
```
Raw fingerprint image
Make grayscale
Mask with ellipse
Histogram equalisation
Ridge orientation filter
Thresholding
Thinning
SIFT feature extraction
RANSAC matching
```

**Comment by jorenham** [comment]
https://github.com/jorenham/fingerblox/releases/tag/V0.1

**Comment by synctext** [comment]
Sorry, release not working for me. Please test on various phones and fix.
![screenshot_20170323-182526](https://cloud.githubusercontent.com/assets/325224/24291681/3d8adaac-108a-11e7-8b79-2c70fde58204.png)

**Comment by jorenham** [comment]
@synctext should be fixed now

**Comment by synctext** [comment]
Works!
The install procedure can hopefully be improved by bundling the lib. I successfully made a fingerprint picture of a round-shaped coffee cup. Impressive Zebra! Keep up this pace please..
![screenshot_20170324-222307](https://cloud.githubusercontent.com/assets/325224/24321617/ec116e62-1150-11e7-9534-e01bca07aa0b.png)

![screenshot_20170325-082540](https://cloud.githubusercontent.com/assets/325224/24321615/e9771e18-1150-11e7-91bf-484d44906fea.png)

**Comment by jorenham** [comment]
Biometric authentication on the blockchain apparently already exist:
https://humaniq.co/

**Comment by synctext** [comment]
Cool.
Surely they have a server in there somewhere for banking. good find.

'''
Our open source stack and APIs will be available for startups and other businesses to build services on our core technologies to stimulate the ecosystem and circular economy even further. The Ethereum Blockchain APIS ad makes it easy for any business to easily adapt their service and plug it into Humaniq’s network to reach a huge, untapped audience. We will also be starting a fund to help grow and accelerate some of our young startup partners.
'''

**Comment by synctext** [comment]
https://github.com/FingerJetFXOSE/FingerJetFXOSE

**Comment by synctext** [comment]
> wow-factor animated GIF of user experience

Re-use play store listing in report for easy-to-understand explanation.

**Comment by jorenham** [comment]
@synctext I can't seem to upload another version to the Play Store unless we have a privacy policy URL.
What should I enter there?

**Comment by synctext** [comment]
Current report :
[portable-biometric-based.pdf](https://github.com/Tribler/tribler/files/1007792/portable-biometric-based.pdf)

**Comment by synctext** [comment]
Published final article: https://arxiv.org/abs/1706.03744

**Comment by thinhtp** [comment]
@synctext Hi sir, 
We can use fingerBlox for detect fingerprint classification in 5 types Tent arch, Arch, Whorl, Ulnar loop, radial loop, for faster matching algorithm. 
Can we do this, please?

**Comment by synctext** [comment]
@thinhtp You are very much invited to build upon this work! Have fun.

**Comment by synctext** [comment]
Closing this issue for now, until new students are available to work on this topic.
