### ISSUE TITLE
Parsing manually in Tribler.Core.Utilities.tracker_utils should be avoided

### ISSUE THREAD

**Issue by vandenheuvel** [Tribler/tribler#2817]
I think `tracker_utils.py` should be rewritten as the code is error prone. In case others agree, you can have a look at [this commit](https://github.com/vandenheuvel/tribler/commit/6adfeb330400a1d773062198956561d35ee0375f) for which I can create a PR.

**Comment by devos50** [comment]
I agree. Your code looks ok and is less error prone indeed. If you open a PR, I will review it 👍
