### ISSUE TITLE
Channel and torrent suggestion endpoint might not be working properly

### ISSUE THREAD

**Issue by EinNarr** [Tribler/tribler#2822]
The restAPI of both these endpoints are not returning exact number of results as specified in the http requests. Usually it returns several results less than the specified limit.

**Comment by devos50** [comment]
I guess that this can be attributed to the fact that a fresh Tribler state directory does not contain enough torrents to meet the `limit` parameter requirement, resulting in fewer torrents returned than specified by the `limit`. This is expected behavior, therefore I will close this issue.
