### ISSUE TITLE
Crash in hidden tunnel community

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2824]
Got this one in the bug reporter:

```
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 92, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "lib\multiprocessing\process.py", line 114, in run

File "TriblerGUI\core_manager.py", line 63, in start_tribler_core

File "lib\site-packages\twisted\internet\base.py", line 1195, in run

File "lib\site-packages\twisted\internet\base.py", line 1204, in mainLoop

--- <exception caught here> ---
File "lib\site-packages\twisted\internet\base.py", line 798, in runUntilCurrent

File "Tribler\community\tunnel\hidden_community.py", line 250, in monitor_downloads

File "Tribler\community\tunnel\hidden_community.py", line 619, in create_introduction_point

exceptions.AttributeError: 'NoneType' object has no attribute 'add_peer'
```

We aren't checking whether the download exists (https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/hidden_community.py#L619) like here: https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/hidden_community.py#L607. Should be an easy fix :)

**Comment by qstokkink** [comment]
Hmm.. in this case I think the specific download should not be updated in `self.download_states`, to make sure the introduction point does get added if the download turns out to exist next `self.monitor_downloads()`.

**Comment by devos50** [comment]
@qstokkink could you create a commit for that so I can cherry-pick it into #2815?

**Comment by qstokkink** [comment]
@devos50 The solution I presented is not bullet-proof yet, we may need something more aggressive.

What (I believe) is happening is that `monitor_downloads()` receives a DownloadState before libtorrent finishes initializing the download. So by doing the above, there is still a race condition where data may come over the circuit before `monitor_downloads()` has been called again to initiate the introduction point (which was the whole reason why the unit test failed).

If the `find_download()` call fails I think the proper solution would actually be to add it to the callback of the download intialization, which we should be able to retrieve from the `dslist` passed to `monitor_downloads()`. @devos50 my guess is that we need to wait for the `LibtorrentDownloadImpl` `handle` deferred, do you agree?

**Comment by devos50** [comment]
That's a good usage of Twisted. I agree with your solution. Can you implement this and create a PR for it?

**Comment by qstokkink** [comment]
Sure, assign me please.

**Comment by devos50** [comment]
@qstokkink that new icon :D

**Comment by egbertbouman** [comment]
@qstokkink @devos50 I don't really see how libtorrent not having initialized the handle could lead to this error. After all, accorrding to the traceback it's the LibtorrentDownloadImpl that's not there. 

I think the problem is something else. I've looked at the monitor_download function, and when we retry to create an introduction point, we don't check that if the download is still there. So, when you remove the download at just the wrong time, it will still retry, causing this error. I've included a fix in https://github.com/Tribler/tribler/pull/2811.

**Comment by devos50** [comment]
@egbertbouman that looks like my initial suggestion in the first post. I guess that should fix the issue indeed.

**Comment by egbertbouman** [comment]
@devos50 The eventual fix was clearing `self.infohash_ip_circuits[info_hash]`, so that's a little different.

**Comment by synctext** [comment]
What is the status of this ticket?

**Comment by devos50** [comment]
@synctext see my comment on #2765

**Comment by devos50** [comment]
This one has been fixed already 👍
