### ISSUE TITLE
get_unicode_sys_argv() of hacks.py is unused and should be removed

### ISSUE THREAD

**Issue by MaxVanDeursen** [Tribler/tribler#2827]
I think the function get_unicode_sys_argv() of hacks.py should be removed, as it is unused. I have already created a [commit on my forked repository](https://github.com/MaxVanDeursen/tribler/commit/cbc76bdcbc73331b69febb2117340dae72a0b125) for which I can create a PR.

**Comment by devos50** [comment]
Please create a PR :+1
