### ISSUE TITLE
Code complexity too high in utilities.py

### ISSUE THREAD

**Issue by MaxVanDeursen** [Tribler/tribler#2838]

**Comment by MaxVanDeursen** [comment]
Could someone please assign me this issue?

**Comment by devos50** [comment]
For a more scientific approach, you might want to use some metric as evidence that the code complexity was indeed bad and after your refactoring that it has improved. For instance, you could use cyclomatic complexity (https://en.wikipedia.org/wiki/Cyclomatic_complexity) as a base metric for this.

It's not necessary for now but just something to keep in mind :)

**Comment by Dmole** [comment]
I don't see anything overly complex in https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Utilities/utilities.py but someone should run https://www.pylint.org/ ( possibly via http://www.pydev.org/manual_adv_pylint.html ) on Tribler which can give complexity warnings.
