### ISSUE TITLE
Potential crash when deleting watch folder torrent file that is "in use" (downloading) 

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#2847]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Tribler 7.0.0 alpha2 123-something (From Jenkins)

##### Operating system and version: #####
Windows 10

##### Expected behavior: #####
After removing file from the folder, Tribler should work like normal. 

##### Actual behavior: #####
Crashes when .torrent file is removed. The torrent itself was downloading. 

##### Steps to reproduce the behavior: #####
**Unable to reproduce so far!**

What i did do:
Have active torrent downloading, that's been added by the use of a watch folder. Remove file. Came back to Tribler with this error.

Starting Tribler again, the download of that torrent also continued as normal. 

It was the only thing i did, as said file was added to the folder by accident, so i wanted to delete it before removing it in Tribler, as it would just cause it to be re-added. Deleted the file, and it was crashed. Not sure if i deleted it at a bad time, since i can't reproduce the issue. I also know a .torrent file isn't in use after the torrent is added, so i don't know why this happened, excuse the bad worded title.

##### Relevant log file output: #####

![tribler crash](https://cloud.githubusercontent.com/assets/1584461/23677567/f23e2f2e-0380-11e7-998d-f7ab95650335.PNG)

Note, the windows error is that file can't be found.

**Comment by devos50** [comment]
@Thomasedv thanks for your report!
