### ISSUE TITLE
Trust in Suply chain platforms

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2851]
The goal of this thesis is to create a prototype for an open supply chain platform (30 ECTS).

This prototype will consists of a user-interface, architectural description, market analysis, and threat analysis (e.g. exit scams). This user-interface will be then reviewed by experts and should be compatible with the decentral market technology of TUDelft. Shown here:
![image](https://cloud.githubusercontent.com/assets/1707075/23568630/a4ea0496-005b-11e7-83bb-7301980efaf6.png)

Supply chain finance is a huge market. Companies such as [PrimeRevenue processes about $120 billion USD in transactions per year, for about 20,000 clients](https://en.wikipedia.org/wiki/PrimeRevenue)

![image](https://cloud.githubusercontent.com/assets/325224/23849129/9462de28-07da-11e7-93bb-bed354266e31.png)

Delft startup TradeCloud is creating a closed platform to connect various players in the chain. See this blog [for details on what matters there](https://themamtasethi.wordpress.com/2016/10/15/12-key-metrics-for-supply-chain-management/). More advanced material, for instance, [towards trusted tradelanes](repository.tudelft.nl/view/tno/uuid:c31021f1-9618-4b85-bfba-606d7bf76f7c/)
![image](https://cloud.githubusercontent.com/assets/325224/23849243/186e7bd2-07db-11e7-94dd-920d3011df2c.png)

The second [low-hanging fruit application for open matching platforms is return cargo](http://www.nytimes.com/2010/04/22/business/energy-environment/22SHIP.html). Lot of trucks run empty and very little coordination is going on. Current closed [platform is Teleroute ](http://teleroute.com/en_en/teleroute-freight-exchange/reduce-empty-running-by-43)

**Comment by AnthiTsil** [comment]
![trust](https://cloud.githubusercontent.com/assets/26378720/23849726/e6d84650-07dc-11e7-8788-da7657f0f61c.png)

**Comment by synctext** [comment]
ToDo next sprint:

Size of scame | name
------------ | -------------
$12 million | [Evolution drug market exist scam](https://www.theguardian.com/technology/2015/mar/18/bitcoin-deep-web-evolution-exit-scam-12-million-dollars)
$3 million | [eBay and Interpol fugitive](https://nakedsecurity.sophos.com/2013/10/29/fbi-hunt-for-seven-fugitives-involved-in-multimillion-dollar-ebay-car-scam/) |
? | [Golf balls](http://www.dailymail.co.uk/news/article-1235839/Conman-dubbed-The-Man-millions-biggest-eBay-fraud-exploding-golf-balls-fake-clubs.html)

**Comment by AnthiTsil** [comment]
Starting thoughts for research questions...
RQ1: How could blockchain disrupt data monopolists?
RQ2: Is there an opportunity to build a common platform that could host supply chains that are providing vitally different services?
RQ3: What would be the building elements of such a platform?
RQ4: How would such a platform look like?
RQ5: How could user’s trust towards using such a platform be built?

**Comment by synctext** [comment]
we will continue in logistics, if new funding becomes available.
