### ISSUE TITLE
Tribler does not remember its maximized state

### ISSUE THREAD

**Issue by Lehmax** [Tribler/tribler#2866]
#### Please, fill all relevant items: ####

- [ ] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
7.0.0-beta
##### Operating system and version: #####
Windows 10 with latest updates installed
##### Expected behavior: #####
Tribler should remember the maximized state.
##### Actual behavior: #####
When maximizing Tribler and exiting it will be back to its non-maximized state when it's started again.
##### Steps to reproduce the behavior: #####
Start tribler
maximize it
exit
start again
##### Relevant log file output: #####
I'll put it here if it's relevant and not reproducible on your computer.

**Comment by xoriole** [comment]
Cannot reproduce the issue with the latest build Tribler 7.0.2
