### ISSUE TITLE
Bandwidth limit is not applied

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2870]
##### Tribler version/branch+revision: #####

devel d12a8515b4f3fd976030b2bb04e2796dd5788499

##### Operating system and version: #####

Linux

##### Expected behavior: #####

After saving bandwidth limit settings, it is applied immediately: download rate goes from 2M to 500K.

##### Actual behavior: #####

No effect after applying the setting. Even after waiting for some minutes. Or after stopping and starting the download.

**Comment by devos50** [comment]
I'm not sure whether we can change this setting on runtime. I think we should restart lib torrent. I think the easiest thing to do here is to give a prompt that the user should restart Tribler in order for the changes to be active.

**Comment by vi** [comment]
Was is so in previous version of Tribler? I expect bandwidth limit to be easy-to-adjust option, not requiring re-initialisation of whatever.

**Comment by devos50** [comment]
@vi it turns out that this feature is not working at all. I've just refactored some code and made sure that the bandwidth settings are working correctly. Also, they take effect immediately when saving the settings in the GUI now 👍 . Will be included in my next fixes PR.
