### ISSUE TITLE
Can't start seeding for some of the downloads.

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2871]
##### Tribler version/branch+revision: #####

devel d12a8515b4f3fd976030b2bb04e2796dd5788499

##### Expected behavior: #####

Explicitly starting a 100% completed "Stopped" download forces seeding (at least until Tribler is restarted) in any case.

##### Actual behavior: #####

Some (but not all) downloads at 100% and 2.0 ratio refuse to transition to "Seeding" state even If I go to preferences, switch to "Unlimited seeding", restart Tribler, ensure that the unlimited seeding setting is in effect and try to start the download. It briefly goes to "Downloading", then to "Stopped". Force recheck does not fix it.

**Comment by vi** [comment]
Found workaround: after activating "change anonymity" (to the same value as it was before), it rechecks, then seeds the download.

**Comment by vi** [comment]
Still reproducible for cf60d11468b5d8e80c84780fe632d7cc5ada8e19. The workaround still works.

**Comment by devos50** [comment]
This issue should be already fixed. Please reopen if the issue persists.
