### ISSUE TITLE
Sign Tribler.app final bundle and Windows .exe

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2872]
Before releasing Tribler 7, we should check the signing process of the .exe on Windows and the .app on macOS.

**Comment by devos50** [comment]
The .exe on Windows is now signed:

![0a77ae6696599084947e5ec454ee42ae](https://cloud.githubusercontent.com/assets/1707075/26752659/63c24f0e-4855-11e7-84b6-78132c825cf4.png)

**Comment by qstokkink** [comment]
Signing of the Mac .app will be deferred to the 7.1 release.

**Comment by devos50** [comment]
We successfully signed `Tribler.app` with my developer credentials, using the `codesign` tool. Since I do not want to use my own private key to do this, we should check whether the TU Delft has an Apple Developer account, or create one for the Tribler team.

**Comment by devos50** [comment]
I stil haven't heard anything back from our ICT department. I will move this issue to backlog since I do not expect that we will get a valid signing certificate anytime soon.

**Comment by synctext** [comment]
just to document our journey somewhat.
From 11 May 2015 until 2018 we used DigiCert. Digicert certificate for Build signing.

We could use the Surfnet facilities, they offer support.
https://dracc.commonsconservancy.org/

**Comment by qstokkink** [comment]
Thanks to @xoriole the Apple release is now signed. The only remaining issue is now Windows, for which there is a separate issue here: #5648
