### ISSUE TITLE
Seeding Option (Time) not working

### ISSUE THREAD

**Issue by Halbon** [Tribler/tribler#2874]
#### Please, fill all relevant items: ####

- [ ] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
7 beta
##### Operating system and version: #####
Windows 10
##### Expected behavior: #####
Seeding Options in Settings.
If I set "Seeding for (hours:minutes) to "1:00," it should stop seeding after one hour from completion of the download.

##### Actual behavior: #####
Time setting does not come in effect. Files are still "Active" and "Seeding" after one hour.

##### Steps to reproduce the behavior: #####
Set "Seeding for (hours:minutes) to whatever time to see if newly completed download would stop at the set time.

**Comment by devos50** [comment]
I confirm that this is not working correctly. I've just fixed it and tested it throughly. The fix will be included in the next release.
