### ISSUE TITLE
Torrent file with non-ascii characters in its name fails to load

### ISSUE THREAD

**Issue by Halbon** [Tribler/tribler#2875]
#### Please, fill all relevant items: ####

- [ ] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
7 beta

##### Operating system and version: #####
Windows 10

##### Expected behavior: #####
Any torrent file will load to download regardless of the file name

##### Actual behavior: #####
It says "unable to read torrent file data" because it cannot parse the file name. Example is Japanese. If I hit "Download" I will get "Request error - An error occurred during the request:" and only option is to "Close" the screen. No file gets loaded. 

##### Steps to reproduce the behavior: #####
Open a torrent file with Non-ascii characters in its file name
##### Relevant log file output: #####
![2017-03-20_0023triblererror](https://cloud.githubusercontent.com/assets/26534257/24088734/66395318-0d04-11e7-9d7a-df7e6c2571f4.png)

**Comment by devos50** [comment]
@halbon I've just tested this on Windows 10, Tribler 7 beta and I'm unable to reproduce this issue. Can you make sure the torrent is valid i.e. by feeding it to another torrent download program?

**Comment by Halbon** [comment]
@devos50 Can you add 「あいうえお」to your torrent file name and try to double-click to open using Tribler. You should get the above screen. Yes, the file is normal. To workaround it, I rename the file to let's say, "a.torrent" and it runs correctly with Tribler.

**Comment by min050820** [comment]
Is this closed? I tried the same thing with Tribler 7.2.2 and it failed to parse the file.

Could you please verify this again?

**Comment by qstokkink** [comment]
Seems to work on `7.3`, Ubuntu `18.04`:

![afbeelding](https://user-images.githubusercontent.com/3630389/56024546-87c1dd80-5d10-11e9-83a8-f571ebfce02c.png)
