### ISSUE TITLE
no Tribler-v7.0.0-beta.tar.xz release archive

### ISSUE THREAD

**Issue by xantares** [Tribler/tribler#2880]
Hello,

The usual .tar.xz release archive is no more available with latest beta.
This was helpful to build tribler as it contained the git submodules (dispersy?).

Is this missing ? Or am I supposed to package tribler otherwise ?

**Comment by devos50** [comment]
This turned out to be a small inconsistency between our Jenkins job; we are building this beta from a different branch which had another job assigned. Should be fixed with the next (beta?) release.
