### ISSUE TITLE
magnet links without .torrent completed do not get stored

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2881]
when closing Tribler the `fetching metadata` in progress get deleted/forgotten.
(as reported on Forum.tribler)

**Comment by devos50** [comment]
The checkpointing of a download only happens when we have the metadata of the torrent. I'm not sure what the reason behind this was exactly but it has been this way for a very long time. I will take a look.

**Comment by qstokkink** [comment]
This was fixed in #3069.
