### ISSUE TITLE
Prediction market for climate change

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2882]
This is a long-term idea to showcase the special abilities of our decentral market. Everybody can invest against/on climate change within minutes. This is impossible today.

Other people [already thought of this](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2372321), but we could actually build it and make it popular. This goes beyond simple [weather derivatives](https://en.wikipedia.org/wiki/Weather_derivative) and [smart contracts](https://github.com/AugurProject/augur-core#augur-core).

Given the perfect market assumption, we can make a market that pays out a lot of money if climate change turns out to be a [liberal hoax](http://www.cfact.org/2014/02/16/global-warming-hysteria-the-acid-rain-scare-and-other-money-making-megamyths/) again.. Or profit from global doom. If enough people participate, the trading price of the stock should indicate [the likelihood of an outcome](https://www.wired.com/2017/03/forget-bitcoin-blockchain-reveal-whats-true-today-tomorrow/). We need a new type of smart contract, driven by unbiased real-world analog input: temperature. To make it more exciting we will use the sensitive polar ice cap average temperature. A prediction market contract trades between 0 and 100%. Thus investing 1 Euro in 2030  +5 `polar ice cap` avg yield a clear probability of this occurring. Yes, this is similar to [betting on bankruptcies](http://www.dbresearch.de/PROD/DBR_INTERNET_EN-PROD/PROD0000000000252032/Credit+default+swaps%3A+Heading+towards+a+more+stabl.PDF). 
To top it all off, create another prediction market playing on the likelihood that US, Brazil, and half of Europe [turn into a desert](https://scholar.google.nl/scholar?cluster=830695582842466151) by 2050.

This also has a social purpose, our work will put hard numbers to climate change probability and doubt. "Much of the doubt occurs among individuals who support free markets, and the doubt is fueled by the argument that governments and government-funded climate scientists are not accounting for information that is inconsistent with the climate consensus."

The open hard-core science problem: who is allowed to record _the truth_ on the blockchain?
(in this case temperature and drought-levels)
Current partial-implemented [rich-get-richer approach](http://blog.augur.net/guide-to-augurs-rep/): "By owning Reputation and participating in the accurate reporting on the outcomes of events, you are entitled to a portion of Augurs market fees. Each Reputation token entitles you to 1 / 22,000,000 of Augurs total market fees." (we offer an alternative with our zero-fee market, based on the self-governance principle)

**Comment by devos50** [comment]
Relevant literature:

- http://augur.strikingly.com/blog/what-is-an-automated-market-maker
- http://augur.strikingly.com/blog/augur-s-automated-market-maker-the-ls-lmsr

**Comment by synctext** [comment]
another prediction project with some initial code "truthcoin": https://github.com/psztorc/Truthcoin

**Comment by synctext** [comment]
Too far of our core focus, closing.
