### ISSUE TITLE
Booting a second tunnel community leads to errors

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2885]
Got this one in the bug reporter:

```
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 92, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "lib\multiprocessing\process.py", line 114, in run

File "TriblerGUI\core_manager.py", line 63, in start_tribler_core

File "lib\site-packages\twisted\internet\base.py", line 1195, in run

File "lib\site-packages\twisted\internet\base.py", line 1204, in mainLoop

--- <exception caught here> ---
File "lib\site-packages\twisted\internet\base.py", line 798, in runUntilCurrent

File "Tribler\dispersy\endpoint.py", line 253, in dispersythread_data_came_in

File "Tribler\dispersy\dispersy.py", line 1488, in on_incoming_packets

File "Tribler\dispersy\dispersy.py", line 685, in get_community

File "Tribler\dispersy\community.py", line 226, in init_community

File "Tribler\community\tunnel\tunnel_community.py", line 316, in initialize

File "Tribler\community\tunnel\Socks5\server.py", line 309, in start

File "lib\site-packages\twisted\internet\posixbase.py", line 478, in listenTCP

File "lib\site-packages\twisted\internet\tcp.py", line 983, in startListening

twisted.internet.error.CannotListenError: Couldn't listen on any:55661: [Errno 10048] Elk socketadres (protocol/netwerkadres/poort) kan normaal slechts n keer worden gebruikt.
```

This is probably caused by a member that receives a packet that is meant for an older tunnel community (we recently changed the ID of this community) so another tunnel community is started. This new community wants to use the same socks5-ports as the old one, leading to the crash above.

@egbertbouman or @qstokkink what should we do with this? We can either support multiple tunnel communities in one session but then we need to give this new community fresh socks5 ports. We could also refuse loading a second tunnel community and just drop this packet (probably the easiest solution and it makes sense since the older communities should not be supported anymore).

**Comment by qstokkink** [comment]
This might be due to packets coming in when the TunnelCommunity has just been unloaded and Tribler is shutting down.

**Comment by devos50** [comment]
Tribler is not shutting down in the crash reports we received according to the environment variable 'Shutting_down' so I don't think that is the cause.

**Comment by qstokkink** [comment]
To summarize discussion:
Current proposed fix is to disable community lazy loading on packet arrival at https://github.com/Tribler/dispersy/blob/8dd28a0af67198179d493d0b204e15d5eaaeb417/dispersy.py#L1488 (using auto_load=False) as this can reload an unloaded community.
To be certain this is the root cause of the bug, we need a reproducible scenario though.

**Comment by qstokkink** [comment]
Alright can confirm that `initialize()` is called twice by running the following test (packet incoming after community unload):

```python

from twisted.internet.defer import inlineCallbacks
from Tribler.dispersy.candidate import Candidate
from Tribler.dispersy.util import blocking_call_on_reactor_thread
from Tribler.Test.test_as_server import TestAsServer


class TestUnloadTC(TestAsServer):

    def setUpPreSession(self):
        super(TestUnloadTC, self).setUpPreSession()
        self.config.set_dispersy(True)
        self.config.set_tunnel_community_enabled(True)

    def create_valid_packet(self, community):
        meta = community.get_meta_message(u"cell")
        conversion = community.get_conversion_for_message(meta)

        meta = community.get_meta_message(u"dht-request")
        message = meta.impl(distribution=(1,), payload=(42, 1, "0"*20))
        return conversion.convert_to_cell(message.packet)

    @blocking_call_on_reactor_thread
    @inlineCallbacks
    def test_unload_receive(self):
        tunnel_community = self.session.lm.tunnel_community
        dispersy = self.session.lm.dispersy

        some_candidate = Candidate(("1.2.3.4", 1234), False)
        some_packet = self.create_valid_packet(tunnel_community)

        dispersy.on_incoming_packets([(some_candidate, some_packet),])

        self.assertIn(tunnel_community, dispersy.get_communities())

        yield tunnel_community.unload_community()

        self.assertNotIn(tunnel_community, dispersy.get_communities())

        dispersy.on_incoming_packets([(some_candidate, some_packet), ])

        # Interestingly enough the above line calls initialize() again,
        # but this assert will still pass:
        self.assertNotIn(tunnel_community, dispersy.get_communities()) 
```

**Comment by devos50** [comment]
I think I have an idea what's going on here. The tunnel community does not get loaded again after unloading (unloading of the TunnelCommunity only happens on shutdown which was not the case in the received errors). The problem is that we recently changed the master member of the TunnelCommunity. Other clients still have a classification entry in the Dispersy database of this old community. When Tribler starts, the new tunnel community will be loaded. However, when they receive a message with the community ID of the old tunnel community, this old community will be loaded again since a classification can be determined.

Removing any subclass of TunnelCommunity from the auto load dictionary in Dispersy fixes this problem thanks to this check: https://github.com/Tribler/dispersy/blob/8dd28a0af67198179d493d0b204e15d5eaaeb417/dispersy.py#L682 so I will go for the EDIT2 solution of @qstokkink (calling `undefine_auto_load`). This 'fix' will make sure that only one tunnel community will be loaded which is the one used as specified in `LaunchManyCore`.
