### ISSUE TITLE
Public decentral markets with privacy for traders

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2887]
Financial markets offer significant privacy to trading firms.
Leakage of market positions and trade history offers a competitive advantage.
So traders will only operate on decentral markets if their privacy is protected. Regulators have obviously more access.

Builds upon: #2559

**Comment by synctext** [comment]
ToDo: system architecture figure + initial system design that links Tunnel community, orderbook in Python, relaying, spam-prevention, etc..

**Comment by basvijzendoorn** [comment]
[Report with Problem Description and Architecture](https://www.sharelatex.com/project/58c7d6390d2b81b36b2736a3`)

**Comment by synctext** [comment]
Problem of DDoS with Tor-based orderbook relays

**Comment by devos50** [comment]
Related work: Bitsquare (https://bitsquare.io):

![bitsquare](https://cloud.githubusercontent.com/assets/1707075/24904293/5116f928-1eb0-11e7-8c26-c7fc1d618c71.png)

They seem to use Tor together with mainnet.

**Comment by synctext** [comment]
Current idea to prevent bid/ask spam is to either use a cybercurrency or TrustChain (reputation based solution). 

Current [fee in Bitcoin](https://anduck.net/bitcoin/fees/) does not enable microtransactions for bid/asks. It is $4 dollar to each KByte for 97.2% of blocks:
![image](https://cloud.githubusercontent.com/assets/325224/25436267/1aaf6e94-2a93-11e7-83b6-822eaabfdbf4.png)

**Comment by synctext** [comment]
{thoughts}
We did a latency measurement 8 years ago: http://kayapo.tribler.org/trac/wiki/LatencyEstimationReport

Would be good for experimental results and incremental progress to have an operational and solid "latency community". A deployed system produces thesis results and good building block for proxy development. Measured latencies for proxies and limit orderbooks can then be used. DDoS focus; self-reinforcing trust.

**Comment by synctext** [comment]
Ongoing coding work on latency community, proxies, etc :
- https://github.com/basvijzendoorn/tribler/branches
- single autonomous response time measurement community
- Response time = network latency + Dispersy processing time + Dispersy magic black hole spend in queue waiting time

![image](https://user-images.githubusercontent.com/325224/27134803-03ee685e-5117-11e7-877c-4c0c6f68ba66.png)

**Comment by basvijzendoorn** [comment]
![histogram](https://user-images.githubusercontent.com/5420915/27785741-d95da614-5fde-11e7-88f3-c818a973d0f1.png)
![histogram2](https://user-images.githubusercontent.com/5420915/27785742-d983bf16-5fde-11e7-9d20-bf82a6f1f832.png)

**Comment by synctext** [comment]
[It all happened in just 45 millisecond on GDAX market](https://www.bloomberg.com/news/articles/2017-06-30/the-45-millisecond-ether-flash-crash-prompts-search-for-remedies)

```
The crash at 3:30 p.m. New York time on June 21 drove the currency down to 10 cents
from $317.81.  The cause, White said, was a single $12.5 million trade -- one of the
biggest ever-- placed by a customer as a market order, or a request to sell immediately.
That pushed ethereum to $224.48, but the pain didn’t end there. The decline triggered
sell orders from traders who’d requested to bail on the currency if prices fell to
certain levels, and prompted GDAX to liquidate some margin trades.
```

**Comment by basvijzendoorn** [comment]
Clear target build the lowest latency overlay.

**Comment by basvijzendoorn** [comment]
![crawls](https://user-images.githubusercontent.com/5420915/28133901-a69a89da-6741-11e7-8535-7cb68a2426ad.png)
![latencies](https://user-images.githubusercontent.com/5420915/28133902-a6a0df56-6741-11e7-8f19-451412e4fe21.png)

**Comment by synctext** [comment]
Nice progress! Next steps:
- thesis documentation, packet layout, experiment description, Why/What, etc.
- add value to market community by replacing the default Dispersy overlay with a low-latency overlay
- orderbooks are in sync faster, can be argued
- low-latency overlay experiments and _deployment_
- Future steps: privacy aspect.

**Comment by devos50** [comment]
@basvijzendoorn  see https://cloud.githubusercontent.com/assets/3785124/22742749/33eb4aca-ee18-11e6-9898-675a23a287cf.png

**Comment by basvijzendoorn** [comment]
@basvijzendoorn https://github.com/Tribler/dispersy/pull/526

**Comment by synctext** [comment]
Thesis-level Gumby experiment:
- give each user a fixed latency
- use a certain real-world dataset, like https://pdos.csail.mit.edu/archive/p2psim/kingdata/
- goal is to build a low-latency overlay effectively and efficiently
- compare different algorithms
- first assume all nodes fully connectable, enhanced version preserve the Disparsy NAT traversal mechanism
- determine (best class of) algorithms

**Comment by basvijzendoorn** [comment]
Upon introduction request: Predicting what the latency would be for the requester.

**Comment by synctext** [comment]
prime example of low-latency network, Bitcoin enhancement: http://bitcoinfibre.org/stats.html

**Comment by basvijzendoorn** [comment]
https://www.sharelatex.com/project/592c19a601647e1979114c42

**Comment by synctext** [comment]
Current status. Created a Dispersy latency community; but now moved [into Dispersy itself](https://github.com/Tribler/dispersy/compare/devel...basvijzendoorn:latency_overlay_backward). This implementation runs on DAS5, can measure node-to-node ping times, gossip these results using a ```dispersy-request-latencies``` message, and builds a hard-coded lowest latency peer discovery mechanism (thus killing exploration and randomness).

Using this collected ping times various existing network distance algorithms, [such as GNP](http://www.cs.rice.edu/~eugeneng/research/gnp/). Key challenge ```Upon introduction request: Predicting what the latency would be for the requester.```. Thus we only need to calculate the latency for a single node every few seconds.

**Comment by basvijzendoorn** [comment]
Idea: Do real ICMP request to measure ping times without NAT puncturing.

**Comment by basvijzendoorn** [comment]
Master Thesis link: https://www.sharelatex.com/project/592c19a601647e1979114c42
Current status: Read the background literature more carefully, understand the peer discovery mechanism better. Read and experimented with peer discovery code. Started working on including literature in master thesis.
Centralized algorithms
[Vivaldi](http://www.cs.ucsb.edu/~ravenben/classes/276/papers/vivaldi-sigcomm04.pdf)
[GNP](https://www.cs.rice.edu/~eugeneng/papers/INFOCOM02.pdf)
Decentralized algorithms
[NPS](https://www.cs.rice.edu/~eugeneng/papers/USENIX04.pdf)
[PIC](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.67.7989&rep=rep1&type=pdf)

Idea: Use ranking metric as described in the GNP literature. Also use relative error as new error function.
Thought about incremental algorithm that recalculates the coordinates of a new peer plus his neighbours upon introduction. In normal conditions these are around 10 coordinates. With a fast walker around 30 coordinates are recalculated. A maximum number of coordinates for recalculation can be set. The coordinates set their new position based on the latencies of their neighbours. Thus when a new peer is introduced his measured latencies plus all the latencies measured of his neighbours should be send with the message. Peer introduction happens on:
`on_introduction_request`
`on_introduction_response`
`on_puncture`

**Comment by synctext** [comment]
System model:
  - decentral, all agents only have incomplete local knowledge
  - agents gossip their latency to other agents. Each latency measurement is cryptographically signed by both agents. (free to use sign-anything policy for prototype)
  - incoming gossip messages contain a list of neightbor identities and measured latencies
  - each agents is free to misreport latencies if another agent is willing to collude
  - network coordinates are updated in an incremental fashion with each incoming signed message.
  - We assume some agents have a high minimum latency due to delays in the last-mile link.

Status: thesis has first experiments. Ready for experiments with incremental updates and runtime measurements.

**Comment by basvijzendoorn** [comment]
Status: Have a working incremental model. Next steps: Experiments and tweak current model.
Metrics:
1. Ranking and Error summation metric for accuracy
2. Algorithm runtime in ms
3. Effects on decentral market

Latency sharing gives the possibility to report false latencies, message delaying. Possible solutions give some protection but not full protection.

**Comment by synctext** [comment]
Dataset: Cornell-King 2500 x 2500 node Latency https://www.cs.cornell.edu/people/egs/meridian/data.php

Current thesis status: chapter focus fixed.

Next step: solid experiment, focus on the core, explore trade-off accuracy and computational time, write 1-3 pages, already polished thesis style.

- First experiment: 0 to 2500^2 matrix of information. Each incremental step we measure the computational time of the algorithm, as the matrix is expanded by 1 row and column. X-axes the matrix size, Y-axis the runtime. Plus several curves for various algorithm settings from naive to dumb and fast.
- Second experiment is exploring the accuracy with full information and fast heuristics.
- Third experiment is full info, heuristics and partial info in decentral Tribler setting.

**Comment by basvijzendoorn** [comment]
Current status:
Dataset: king 1740 X 1740 latency nodes https://pdos.csail.mit.edu/archive/p2psim/kingdata/
Thesis status: Described and developed computational time metric ranking and relative error accuracy metrics, Experiment graphs added. [Latex thesis](https://www.sharelatex.com/project/592c19a601647e1979114c42)

Experiment one, two and three run.

Proposed next steps: Add more settings, Experiment four, Experiments with decentralized market.

**Comment by synctext** [comment]
- Top-20 is a bad metric, by definition 100% accurate at 20 "datapoint".
- Added latency+gossip of measurements inside Dispersy core community.py class: https://github.com/basvijzendoorn/dispersy/blame/fb415eb1bd98e7b6be778b3be6b2dd4b7619979c/community.py
- Create clean and ready to deploy code !
- Can it run for days, not grow in memory and CPU usage? (continuous running mode; real-time mode, fresh measurements)

**Comment by basvijzendoorn** [comment]
[Delft_University_of_Technology_Thesis_and_Report.pdf](https://github.com/Tribler/tribler/files/1445650/Delft_University_of_Technology_Thesis_and_Report.pdf)

Status: Experiment 3 and four done. Clean and ready to deploy code.

Proposal: Continue with writing.
Experiment 3 and 4 measurements start after some time instead of from the beginning.

**Comment by synctext** [comment]
- implemented low-latency community! Uses Gumby, _directed introduce_, coinflip decentral algorithm on DAS5 with real Tribler community.
- Goal-drive experimental section: _the goal of our experiments is to compare various network coordinate algorithms to create a low-latency overlay_.
- Key experiment: cost of joining as new peer to a converged low-latency overlay.
- When you come online: __Cost in Bytes to find your lowest-latency neighbors__.
- Split in central full latency vector and decentral 'tribler' experiments. incomplete information, local viewpoint. Real P2P view. The cost of decentralisation. How to present?
- itteration, 1 per second equals 3600 latency measurements per peer per hour. Fast discovery of lowest latency neighbors.
- 3 or 4 algorithms with a name. Simple, Naive, Guido97, MicrosoftPaper2012, 10-steps, ?
- Readable figures on greyscale.
- X-axis?
- "This lack of knowledge results in sub-optimal solutions in the above example." no thriller writing style, put the relevance in first sentence. like: _another example of an algorithm with only sub-optimal solution because future events are unknown is the k-server problem. News events are unpredictable and journalists are sent to jobs, without knowing the next event. This results in inefficiencies"._  More fitting for intro chapters probably.

**Comment by basvijzendoorn** [comment]
Next steps:
1. Do all experiments:
- third and fourth experiment with all algorithms.
- cost of entering experiment.
- latency difference in privacy of market assignment measured with statistical difference.

2. Explenation of algorithms.

**Comment by synctext** [comment]
Comments:
- in general; lot of pieces of text. Making progress. Please focus on creating a single storyline.
- intro of problem in either Chapter 1 or 2. Illustration:
![image](https://user-images.githubusercontent.com/325224/33119870-9cb74416-cf70-11e7-9c07-32f220401d3f.png)

- Chapter 3: "In order to solve the complexity problems of the GNP algorithm in the decentralized Tribler setting we introduce an incremental algorithm approach to stretch the computation of the solution over time." _too complex for opening sentence_ More like: privacy and latency matter for online markets. We now focus on incremental algorithms to predict the latency to a given Internet location. This is the cardinal primitive for building a low-latency overlay, as we shall demonstrate within our experimental section.
- k-server is an explanatory example, but needs it's own dedicated Figure 3.1 ?
- is the chapter focus _incremental latency prediction_.
- where discuss: state-of-the-art and GNP ? The 2004 MIT Vivaldi system:
![vivaldi_network_latency_mit_2004](https://user-images.githubusercontent.com/325224/33120059-3af90542-cf71-11e7-999a-5ad9034ad511.png)
- Mention methods, but no need to include other people formulas (unless you created a superior one).
- reposition Chapter 4 (basic algorithm)? 
- Perhaps move Tribler peer discovery after all latency matters.
- (last on ToDo) Explain how you made your own latency algorithm; including the 4 variants.

**Comment by basvijzendoorn** [comment]
[optional-subtitle(3).pdf](https://github.com/Tribler/tribler/files/1542983/optional-subtitle.3.pdf)

**Comment by synctext** [comment]
Quick comments:
- continue polish __start at the start__ 2.
- _The NPS algorithm improves the GNP algorithm by decentralizing it._ perfect opening line of section.
- 3.5. GEOLOCATION APPROACHES, focused exclusively on the MaxMind 2007 experiment.
- 5.1. LOW LATENCY OVERLAY, General system model

**Comment by devos50** [comment]
I think the title of this issue is outdated (the focus of this thesis has changed over time)?

**Comment by synctext** [comment]
Thesis progress:
- mostly on Gumby, 1 page of thesis writing
- bug fixing of experimental code
- experimental thesis code nearly finished
- 20 node experiment, ranking of coordinate accuracy. Re-uses GNP methodology / figure
![image](https://user-images.githubusercontent.com/325224/34770999-4539b1e2-f603-11e7-9206-8c27e0a87a47.png)

- https://jenkins.tribler.org/job/pers/job/latency_exp_basvijzendoorn/37/artifact/output/ranking.png

**Comment by basvijzendoorn** [comment]
https://www.sharelatex.com/project/5a3bc4af38c4a5721edbf694

**Comment by synctext** [comment]
- the low-latency overlay in Dispersy has a 100% bias. Lowest-latency is always picked.
- Dispersy (trusted peers; then 50% re-visit, 25% reply to introduction-response, 25% react to introduced by 3rd peer)
- this creates a hammering effect, where the same peer is selected; however due to fluctuations and error in lowest-peer estimation this effect is reduced.
- for trading this is dramatic: peer with high-latency connectivity are never picked

**Comment by basvijzendoorn** [comment]
[thesis.pdf](https://github.com/Tribler/tribler/files/1743626/thesis.pdf)

**Comment by basvijzendoorn** [comment]
Accuracy of top 10 latency peers. A new entering peer is dotted and a peer at the beginning of the experiment is solid. A new entering peer has an advantage because the quality of introductions are higher.
![ranking_normal2](https://user-images.githubusercontent.com/5420915/36893458-678d8a34-1e08-11e8-9f26-140171f7db23.png)

**Comment by basvijzendoorn** [comment]
[final_thesis.pdf](https://github.com/Tribler/tribler/files/1859495/final_thesis.pdf)

**Comment by synctext** [comment]
- Chapter 2: what related work is covered in this chapter. Overlays, Latency estimation algorithms, and their combination. 
 - "optimization functions are often part of the latency estimation algorithms." please let the reader know this vital info in the 1st line of this new section.
- instead of blocks of text with isolated algorithms; good storyline connects them. For instance, in a publication from 200x the Vivialdi algorithm was the ?first? to propose a decentral algorithm...
PIC is the first scalable distributed approach.
- Section 3.1 use word _requirement_ in first sentence.
- "A peer on the internet cannot be directly messaged because the NAT firewall blocks incoming
communication." Many users now lack a direct Internet connection.. etc..
- 64% of the computers connected to the internet do Network Address Translation [cite the source paper]
- NAT-compatible requirement; discovering others through a NAT.
- "Eclipse attacks have large implications on P2P systems that use block-chain."
  add explicitly that _the eclipse attack is a very prowerful and very generic attack. We will now provide several examples from the world of cryptocurrencies. We selected this example, as cryptocurrency overlay hacks have direct financial consequences._
- code coverage results
- "Figure 5.7: The figure shows the ranking accuracy metric calculated every 10 seconds in a decentralized experiment with 500 nodes". Please focus on first 100-steps and the performance when you get 1 till 100 latency vectors to work with out of 500 nodes. Not 2400 steps, where all nodes in a 500-node overlay have been visited numerous times.
- Final thesis experiment: it takes 1000 seconds for 10 peers to find 64% of their top-10 low-latency overlay neighbors. 200 steps to converge somewhat in a 500 node network. 
- Figure 5.11: The figure shows the total upload and download for the 10 new entering peers, please covert Y-axis to MByte.
- please be honest about the strength of results. For instance: The quality of the introductions are not that great. It's all not that impressive yet. Future work: better algorithms. Now it takes a loooong time. 
- Conclusion chapter: needs more content. Please swing by all requirements, your design, and how much of the requirements have you met; given the experimental proof. Implication for trading privacy and onion routing.

**Comment by basvijzendoorn** [comment]
[thesis.pdf](https://github.com/Tribler/tribler/files/1870773/thesis.pdf)

**Comment by synctext** [comment]
please fix: "In the default setting in the low latency overlay latency information
is obtained every second with the ping-pong mechanism from every peer in the
neighbourhood."

> "the other 50% of node selections a peer with a low latency toward the selecting
peer is chosen."

Currently implemented:
- New peer discovered: every 5 seconds, introduction-req.
- ping cycle 2 seconds, ``ping``` and ```pong``` exchange includes latency of 10 peer. each peer keeps a local ping history list. This linear list is pushed serially to all other peers. Keep counter of what is already sent per peer. (difficult to read from thesis text)
- claim "ik weet het 100% zeker": problem is the latency estimation algorithm. If the dataset is synthetic (e.g. not King dataset) and latency estimation thus accurate, it should work 100%. 

Proof of running code experiment:
- remove the top-8 and 50% random overlay for ```taking a step```.
  - use the overlay algorithm as [specified in Jan](https://github.com/Tribler/tribler/issues/2887#issuecomment-361562460)
  - should converge fast, especially with good predictive dataset.
  - keep track of a lowest-latency top-10 and never let them go.
  - always step to the currently found top-10 lowest latency peers (pick one of 10).
  - pick random 500 points in a X-axes and Y-axes system (from 1 to 500; 500 x 500 points)
  - each node has a simple coordinate and your latency algorithm should work 100% accurate.
  - latency is equal to geo-coordinates. 500 points == 500 milliseconds.

**Comment by basvijzendoorn** [comment]
[thesis.pdf](https://github.com/Tribler/tribler/files/1906069/thesis.pdf)

**Comment by synctext** [comment]
Completed: [final master thesis report](https://repository.tudelft.nl/islandora/object/uuid%3A3bf51816-d0e3-48fe-a794-6a4f5713baae)
