### ISSUE TITLE
Graph on trust page has unlogical axis after clearing state directory

### ISSUE THREAD

**Issue by vandenheuvel** [Tribler/tribler#2892]
On https://github.com/Tribler/tribler/commit/82ad3239d1a2c2c83910653c482bc07e7f693794.

If one starts Tribler with an empty state directory, the graph has negative values. The y-axis should have only non-negative values. Moreover, the x-axis shows multiple years in the past and in the future. Maybe this should be the upcoming days?

![screenshot from 2017-03-31 19-56-24](https://cloud.githubusercontent.com/assets/20440137/24562871/de507f58-163b-11e7-88a5-0b435412d3ba.png)

**Comment by devos50** [comment]
I just fixed it, will open PR today :)

![trust_screen](https://cloud.githubusercontent.com/assets/1707075/24646418/32d53d60-191c-11e7-97eb-7a84fb564d70.png)

**Comment by vandenheuvel** [comment]
@devos50 Looks great!
