### ISSUE TITLE
[feature request] Sorting mode and column order is not preserved across Tribler GUI restarts

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2898]
##### Tribler version/branch+revision: #####

devel 4803abba128e2f70cffc3c3892d10817015ea20b

##### Operating system and version: #####

Linux

##### Expected behavior: #####

Closing Tribler GUI and re-opening it restores approximately the same visual state (including scroll positions in lists and column widths)

##### Actual behavior: #####

I need to rearrange columns and sort by "added date" anew.

@devos50

**Comment by ichorid** [comment]
duplicate of #1261
