### ISSUE TITLE
"Error: no Json object could be decoded from data:" When checking health on torrents (searching)

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#2902]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Tribler_7.0.0-beta-53-g4803abb_x64.exe	

##### Operating system and version: #####
Windows 10, creators update

##### Expected behavior: #####
Using Tribler search feature, you can search and then click on torrents to get a health state.  

##### Actual behavior: #####
It does seem to work as intended, but console is riddled with, 
"QIODevice::read: device not open"
"ERROR:root:No json object could be decoded from data:"

##### Steps to reproduce the behavior: #####
Search for torrent, click on any of them (might not happen on non-standard torrents that appear in the first few lines that are auto-checked.) Should happen with some of them. This could potentially lead to search results not working/appearing. Had that happened, but i can't really be sure if they are related or not. 

Also used a VPN at the time, if that's related. (I notice Trilber uses a lot of extra time to start up with a VPN active. )

##### Relevant log file output: #####
```
QIODevice::read: device not open
ERROR:root:No json object could be decoded from data:
```

**Comment by Thomasedv** [comment]
Also want to add, there's a fair chance that this, or multiple searches causes a full GUI disconnect, so searches won't have anything, download/upload speeds are frozen, etc. Core still works, but you can't do much, and can't close the program properly either.

**Comment by devos50** [comment]
@Thomasedv thank you for your report! I had some more reports about this but I'm unable to reproduce this. Does it happen consistently for you? If so, could you please send me your state directory (by email, it might contain some sensitive information about your downloads) so I can try it myself and see whether I can reproduce the bug?

Thanks!

**Comment by Thomasedv** [comment]
Unfortunately, i did a clean installation of Tribler, prior to your comment. But i got around to test it today. This time without a VPN, to kinda remove that variable. I did a search, highlighted the top torrent result, and just held down the down arrow to cause it to check everything it highlighted. Got a lot of errors some times, and a few other times. Things stil worked as normal though. But, most errors where the No json could be decoded part, but not the QIODevice not open part was not here, only saw that 3 times in testing around. 

The errors did seem to come in batches as well, as soon as one come, there was a good list of them in the console. As if one bad health check, caused every other pending result to fault. Also, did not have any part of the UI break on me this time. 

I would also guess the delay caused by the use of a VPN might cause the issue to happen more frequently. 

And although unable to produce it, i would have guessed that one issue would be that Tribler gets some delayed information about the health of a torrent, after you search for something else, and then the entry in the GUI is already removed, which might cause some kind of issue.  But since i also get errors on the first search, without any other done after it, i'd assume that's not it, or at least not the mian part of the issue. (Though, i'm not sure why "QIODevice::read: device not open" only happens rarely, and might be caused by this. Thus the inclusion of this.)
