### ISSUE TITLE
Neverending checking

### ISSUE THREAD

**Issue by Antiade** [Tribler/tribler#2903]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: 
tribler_7.0.0-beta

##### Operating system and version: 
Ubuntu 16.10

##### Expected behavior: 
When I start Tribler, it should build circuits, check the downloads status and continue downloading.

##### Actual behavior: 
When I start Tribler it builds the circuits, but the checking stops before 10% of any download. When I try to close it, the closing never ends and I've to suspend the computer just to get the attached log though it results still running.

##### Steps to reproduce the behavior: 
Just run Tribler

##### Relevant log file output: 
Traceback (most recent call last):
  File "/usr/share/tribler/TriblerGUI/widgets/downloadspage.py", line 243, in on_download_removed
    if json_result["removed"]:
TypeError: 'NoneType' object has no attribute 'getitem'

**Comment by devos50** [comment]
We assume this to be fixed.
