### ISSUE TITLE
bugs with Signature_request and Request_cache

### ISSUE THREAD

**Issue by YourDaddyIsHere** [Tribler/tribler#2904]
multichain community creates a signature-request sub-message with **allow_signature_response(self, request, response, modified)** [here](https://github.com/Tribler/tribler/blob/4803abba128e2f70cffc3c3892d10817015ea20b/Tribler/community/multichain/community.py#L159) . (well just keep the parameter list of allow_signature_response() in mind, we will talk about it later)

And in community base class, the allow_signature_response() is used to create a signature_request_cache [here](https://github.com/Tribler/dispersy/blob/8dd28a0af67198179d493d0b204e15d5eaaeb417/community.py#L2305), the response_func in this case is allow_signature_response()

[the signature_request_cache may be time out eventually:](https://github.com/Tribler/dispersy/blob/8dd28a0af67198179d493d0b204e15d5eaaeb417/requestcache.py#L84), when it time out, it calls: self.response_func(self, None, True, *self.response_args).

well, notice that the parameters list (self, None, True, *self.response_ args) doesn't fit 
 allow_signature_response(self, request, response, modified) where the response is a sub-message rather than a boolean, and modified is a boolean rather than a response_args

So, it seems to be a little bug.

**Comment by devos50** [comment]
A unit test should be written for this to verify this bug.

**Comment by devos50** [comment]
We're using IPv8 now for our blockchain so this issue should be solved.
