### ISSUE TITLE
Establish + Real-time display of Blockchain trust

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2905]
# this is the master ticket of the TI2806 Blockchain Context Project

All major updates will be displayed here.

_This is a cutting edge research project within a highly competitive emerging research area. This assignment is suitable for scientific publication, ambitious students, and honor track participants._

Within this project you will build a solution to establish + visualize trust. The basic technique of using reputations to craft trust has been pioneered 22 years ago by eBay. Showing rating of both sellers and buyers on marketplaces provide basic trustworthiness hints. Online market Silk Road created honesty amongst online drug dealers using simplistic trust building mechanism, resulting in a 2.2% ratio of unsatisfactiory deals.

We build trust based upon well-known techniques of tamper-proof datastructures, recently popular under the name blockchain. For basic information about Blockchain technology, see this online book: https://d28rh4a8wq0iu5.cloudfront.net/bitcointech/readings/princeton_bitcoin_book.pdf or the video lectures: http://bitcoinbook.cs.princeton.edu/

A blockchain database is provided, used to retrieve various transaction records, you must use these transactions to calculate trust scores. Trust scores need to be updated in real-time. As a starting point you will get a real-world blockchain transactions dataset in SQLight. An existing (expensive) algorithm in Python is provided. You will need to explore the literature on algorithms such as PageRank and EigenTrust to understand various performance trade-offs. You will need to understand how to visualize trust and other constraints. Will your work scale to blockchain databases with 10k or even 100k transactions? Your final product will be a tested and documented piece of software, superior to existing prototype:
https://github.com/Tribler/ tribler/issues/2803

Current operational implementation to show trust within a Bittorrent client with Tor-like relay protocol:
![image](https://cloud.githubusercontent.com/assets/1707075/23372119/a2bc7c42-fd1a-11e6-9547-3d2646e5c04b.png)

**Comment by synctext** [comment]
Different sub-projects:
- trust somebody within an app using public/private key cryptography, offer an alternative to [the nerd-only approach](https://en.wikipedia.org/wiki/Key_signing_party)
- create a blockchain-based web-of-trust
- strengthen a web-of-trust with complete privacy using person-to-person IBAN bank transfers and encrypted challenge/response handshakes.
- create a real-time visualisation of web-of-trust, like [this work from 16 years ago](http://bailando.sims.berkeley.edu/papers/infovis01.pdf) and [recent node.js like stuff](https://github.com/feross/p2p-graph) based on experimental Python code.
- expand the existing approach within Tribler with a [random-walk algorithm](www.cs.yale.edu/homes/spielman/462/2010/lect16-10.pdf) 
- Use hardware to securely store your identity outside your smartphone, for instance using Yubikey with the  HMAC-based One-time Password Algorithm (HOTP) or the Time-based One-time Password Algorithm (TOTP)

**Comment by MrHug** [comment]
And a permanent record for GitHub. The groups have been assigned based on their preferences:

- Bulls, Bears, and Wolves: create a blockchain-based web-of-trust (bullet 2)
- Blockchainboys: create a real-time visualisation of web-of-trust (bullet 4)
- Chainabletech: strengthen a web-of-trust with complete privacy using person-to-person IBAN bank transfers and encrypted challenge/response handshakes. (bullet 3)
- NervousFish: trust somebody within an app using public/private key cryptography, offer an alternative to the nerd-only approach. (bullet 1)

**Comment by devos50** [comment]
Implementation of our scalable blockchain approach: https://github.com/Tribler/tribler/tree/devel/Tribler/community/multichain

**Comment by synctext** [comment]
## Progress overview

A total of 20 student in 4 teams. All teams have produced a prototype.

* Team: _Android app with easy to use pairing_
Prevent MITM attack for key pairing. Use rythm tapping or pictogram ordered tapping. [100+ pull requests and discussions in repo](https://github.com/ericcornelissen/NervousFish/pull/181)

* Team: _create a blockchain-based web-of-trust_
[Key product is a Java based implementation of the Trustchain blockchain](
https://github.com/deepweeb/B-B-W/blob/master/app/src/main/java/nl/tudelft/b_b_w/model/GetDatabaseHandler.java#L209). Will result in a library for storage of trust in identity of contacts. Thus Trustchain library for the other teams.

* Team: _validate people in your web-of-trust with IBAN bank transfers_
BankChain using the [Bunq semi-open API](https://codecov.io/gh/MatthijsKok/TI2806-Contextproject/src/develop/BankChain/app/src/main/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqInterceptor.java) and [CI](https://codecov.io/gh/MatthijsKok/TI2806-Contextproject/tree/develop/BankChain/app/src/main/java/nl/tudelft/ewi/ds/bankchain). Can [make](https://github.com/MatthijsKok/TI2806-Contextproject/issues/102) challenge and/response using payment-description field.

* Team: _create a real-time visualisation of web-of-trust in Python_
[PR on main codebase](https://github.com/Tribler/tribler/pull/2958). [Operational Linux code](https://github.com/vandenheuvel/tribler/branches) with trust calculations.

* Team: _customs office, Hyperledger prototype_
(advised by Zeki)

**Comment by MrHug** [comment]
@synctext 
You can find an apk from the *Android app with easy to use pairing*-team [here](https://github.com/ericcornelissen/NervousFish/releases/tag/0.6)

**Comment by TimSpeelman** [comment]
# Sneak preview of the Tribler Trust Network Visualization:
![tribler_trust_display_preview](https://user-images.githubusercontent.com/3309415/27142730-461d7ade-512c-11e7-9faf-2a51e76ebc47.PNG)

**Comment by ghabbenjansen** [comment]
![screenshot tribler](https://user-images.githubusercontent.com/15870543/27395330-b5621bce-56af-11e7-9ee8-60edb4b0e091.png)

**Comment by Ishadijcks** [comment]
ChainableTech
Final report [Draft]
[Contextproject_Draft_Report_ChainableTech_BankChain.pdf](https://github.com/Tribler/tribler/files/1095497/Contextproject_Final_Report.2.pdf)

**Comment by yinghaodai** [comment]
[BlockchainBoys Final Report Draft.pdf](https://github.com/Tribler/tribler/files/1095537/BlockchainBoys.Final.Report.Draft.pdf)

**Comment by ericcornelissen** [comment]
Draft for the [NervousFish app](https://github.com/ericcornelissen/NervousFish) (i.e. Team: Android app with easy to use pairing) can be found 
[here (pdf)](https://github.com/Tribler/tribler/files/1095562/Final.report.draft_NervousFish_TI2806.pdf)

**Comment by ymte** [comment]
[bulls-bears-wolves.pdf](https://github.com/Tribler/tribler/files/1096009/bulls-bears-wolves.pdf)

**Comment by joskuijpers** [comment]
[ChainableTechnologies.zip](https://github.com/Tribler/tribler/files/1112376/ChainableTechnologies.zip)

Final reports and information.

**Comment by vandenheuvel** [comment]
All of our [deliverables](https://github.com/Tribler/tribler/files/1112587/blockchainboys.zip) in a single zip.

**Comment by ericcornelissen** [comment]
All deliverables (including the final report) for the Nervoush Fish app can be downloaded [here](https://github.com/Tribler/tribler/files/1112818/Nervous.Fish.zip)

**Comment by synctext** [comment]
Releases of self-sovereign identity Android Apps:
- [Key attestation with MITM attack prevention](https://github.com/ericcornelissen/NervousFish/releases) (tapping, rythm, NFC, QR codes).
-  [Bank IBAN for sybil attack prevention](https://github.com/MatthijsKok/TI2806-Contextproject/releases)

**Comment by synctext** [comment]
All work now moved to #10, closing this issue.
