### ISSUE TITLE
Backporting to Python 2.6

### ISSUE THREAD

**Issue by hbiyik** [Tribler/tribler#2906]
I have noticed that Python 2.6 is not supported by Tribler Core.

see:
https://github.com/hbiyik/script.module.triblercore/commit/fb790c242575c42a55a8830fb1fbaec1f429af54

Problems i have noticed:
1) argparse, collections is not supported in py26, i have used backports of those modules
2) even though some modules both exist on p27 & 26 methods and attributes are not idetical. IE on windows with python 2.6 there is no os.kill. I have ported same functionality with ctypes. . Also on android even though with python27, randomfile module raises exceptions sometimes, this is an issue with kodi though. I have shamelessy patched that in a very ugly way :).
3) python26 compiler does not understand dict comprehensions, and as far as i could see they are in alot of places in the code

Python 26 is basically %90 of android kodi users interpreter, even though i hate it, i think i got used to that.
What is yout thoughts on this? Is py26 officially supported, or will be supported? this is kind of blocker.

And also what do you think about creating anew module for compatability issues, all those tricky modules, and methods can be called from there, and tihs can be used as an interface.

This is important because my branch is not sync with devel, if i start to fix those one day same effort will be lost on rebasing and merging. I have only started tribler core with py26 and done some json queries, did not fully fix everything all code needs to be revised.

**Comment by hbiyik** [comment]
hi tribler team, sorry if i keep spamming your issue tracker, i will start rebasing from latest-devel and backport to 2.6 hopefully this weekend. Seems like this issue is a boring one, no-one wants to deal with :) if you enjoy the results i can pr when done.

**Comment by synctext** [comment]
wow. py26 would be an amazing PR.
Lot of boring work indeed... 90% of Kodi users is a solid argument.

Unit tests and windows,Linux,Mac passing tests might require some lib installs on Jenkins I guess. Good luck with this hard work!

**Comment by synctext** [comment]
oyeah. please open a WIP PR already today for early feedback by the team

**Comment by hbiyik** [comment]
thanks for showing the direction, i will clean up my repo, organise and rebase after that create a wip pr, to receive feedback.

**Comment by hbiyik** [comment]
https://github.com/Tribler/tribler/pull/2921

**Comment by vandenheuvel** [comment]
@hbiyik after some discussion, it was decided that it is not a good idea to merge https://github.com/Tribler/tribler/pull/2921 into the official Tribler codebase. The most important reason that led to this decision is that it is too cumbersome to require developers to write python2.6 compatible code. Even though your work is very much appreciated and we would love to have many KODI users using Tribler, there will come a moment where Tribler is ported to python3 and we simply don't have the manpower to maintain both forks.

We propose the following: you fork Tribler and make it backwards compatible for 2.6 and get KODI to work from there. New features are developed in this official Tribler repository and (given that the effort required isn't too large) we will make PR's on your 2.6 fork to keep the two compatible for the near future. We will try to support you using the small amount of time we have. You can use our Jenkins server for continuous integration.

**Comment by hbiyik** [comment]
@vandenheuvel, i can see your points, backporting is done in a fashion that main tribler code wont need to be altered so this will come handy in case of merging, so no need for even a PR i can rebase and merge upstream branch easily so you guys dont need to spare time to PR also.

Is there any stable branch including latest functions, is "next" for this purpose? Or should i follow devel?

**Comment by devos50** [comment]
@hbiyik I recommend you to use the `next` branch for that. This branch currently contains the code for our first  Tribler 7 release candidate and is stable enough for production. The `devel` branch contains bleeding-edge code with features that might not be tested in the wild yet.

**Comment by hbiyik** [comment]
ok agreed, do you want the PR to stay opened or closed? since backport merging is a long deadline for your agenda, may be before official releases or may be before tagging, it will stay long in there is i dont close :).

**Comment by synctext** [comment]
Please make Kodi operational with Tribler first with with py2.7 and get a smaller user base from there. With a fully working app then focus on py2.6 support. Full userbase. Good roadmap?

**Comment by hbiyik** [comment]
@synctext py26 backport is already done in this pr, the discussion was how to manage the codebase. And i will use a fork of tribler + dispersy and maintain it, and einarr can depend my fork. if we were to go without android and py26 it would fail without question. i have been there before.

**Comment by vandenheuvel** [comment]
@synctext if a 2.6 fork will be made, @hbiyik might as well start with 2.6 right away. Getting it to work with 2.7 first is only beneficial if the 2.6 backwards compatibility has to be merge in the official repository.

**Comment by synctext** [comment]
Dispersy on py2.6 might take some time. right? Tribler should run OK on our Google Pixel Android devices.

**Comment by hbiyik** [comment]
@synctext nah, it is also already done, 
https://github.com/hbiyik/dispersy/commit/03a7dfb510ba1d28763c84dd6984993798147f43
https://github.com/hbiyik/dispersy/commit/2969de4532dde150407d49636e5d1d272e778b04

again the question is future maintenance and im green with it.

**Comment by cclauss** [comment]
Can this issue be closed?   Python 2.6 end of life was more than five years ago and https://snarky.ca/stop-using-python-2-6 was written three years ago.

**Comment by devos50** [comment]
It is very unlikely that we will continue with this since we already have trouble porting to Python 3. I will close this issue.

**Comment by synctext** [comment]
Kodi is also moving to Python3. Great news.
https://kodi.tv/article/attention-addon-developers-migration-python-3
