### ISSUE TITLE
Twistify the removal of torrents in the core

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2907]
We should make the removal of torrents asynchronous. This is possible by using the `torrent_deleted_alert` (http://www.rasterbar.com/products/libtorrent/manual.html#torrent-deleted-alert) and return a deferred in the `remove_torrent` method in the `LibtorrentMgr` class.

This allows us to get rid of the ugly hard-coded timeouts when removing torrents (i.e. https://github.com/Tribler/tribler/blob/devel/Tribler/Core/APIImplementation/LaunchManyCore.py#L435).

**Comment by qstokkink** [comment]
This seems to be called a `torrent_removed_alert` in my libtorrent version.

**Comment by qstokkink** [comment]
The only alerts I get when changing the anonymity are:

```
stats_alert: big_buck_bunny_1080p_stereo.ogg: [1015] 0 0 0 0 0 0 0 0 0 0
stats_alert: big_buck_bunny_1080p_stereo.ogg: [1000] 0 0 0 0 0 0 0 0 0 0
torrent_removed_alert:  -  removed
tracker_announce_alert:  -  (http://blender.waag.org:6969/announce) sending announce (stopped)
alert:  - 
```

The `lt.alert.category_t.storage_notification` alert mask is present.

Maybe we should hook this up to `torrent_removed_alert` instead?
