### ISSUE TITLE
Digital voting pass

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2918]
Goal is to digitize the current Dutch voting pass (first prototype).

This voting pass prevents double voting and check if this citizen is allowed to vote. 

This project is a first step to increase the digital steps in the voting process. Critical requirement is ensuring trust, integrity, security, auditability,  etc. Currently it seems to have occurred that people moving between municipalities obtained _two_ voting passes, obviously we want to prevent this irregularity. 

Manual counting takes hours to process but is highly trusted, [see this stone-age analog process in detail](http://nos.nl/artikel/2165112-gemeenten-willen-graag-terug-naar-computerstemmen.html).

[specifications of voting pass](https://teacherschannel.s3.amazonaws.com/tenant-docs/35/q7nhfqgf142w_rml_r61c8-s60lwcw07rbb5bs0z6sdf18b-6k6np4ksd_vfp4rv15_h3wnn5w10s1.pdf)

[Trust is the cardinal issue](http://wijvertrouwenstemcomputersniet.nl/English) in this BEP project.

Currently the government is experimenting with creating a smaller and more [managable analog](https://www.tweedekamer.nl/kamerstukken/plenaire_verslagen/kamer_in_het_kort/coalitie-verdeeld-over-experiment-met-nieuw) voting pass.
![image](https://cloud.githubusercontent.com/assets/325224/25444540/cb9d0a96-2aab-11e7-8258-9f92e58bb4d9.png)

_blockchain_  could this solve various fraud issues?

**Comment by landgenoot** [comment]
Repositories:
https://github.com/landgenoot/digital-voting-pass-server
https://github.com/landgenoot/digital-voting-pass-app

The research process is tracked in the issues in the server repo.

**Comment by wkmeijer** [comment]
Project Plan
[Digital_voting_pass_Project_Plan.pdf](https://github.com/Tribler/tribler/files/967451/Digital_voting_pass_Project_Plan.pdf)

**Comment by synctext** [comment]
Scope question: partly digital voting. No changes required in legacy procedures and infrastructure.
Problem of identification and authentication in voting station. Role of smartphone?

**Comment by landgenoot** [comment]
We tackled the problem that we were unable to verify a signature from a dutch travel document due to Elliptic Curves signatures instead of RSA.
Will update the [pypassport](https://github.com/landgenoot/pypassport-2.0) library and add support asap.

We are still having an issue with the limit of the bytes which can be signed by the travel document. This is limited to exactly 8 bytes according to the ICAO standard.
SHA1 or SHA256 hashes have lengths 20 and 32 byte respectively. Therefore these hashes cannot be signed by a travel document.

Hashfunctions with smaller sizes a not recommended for cryptographic usage.
@synctext Do you think that it is safe to sign a hash in parts?

**Comment by sgort** [comment]
### Concept
Voornemen is oplossing bieden voor digitaal verkrijgen stem pas.

1. Tip: Benader het vanuit de functie van de stem pas, niet de stem pas zelf, nl. het persoonlijk kunnen claimen van je recht om te stemmen!

1.  We blijven de stem pas uitdelen
a.	Papier
b.	BSN + public key reisdocument = digitaal token

1.  Stemmen
a.	Zelf aangeven dat je digitaal wilt stemmen
i.	Reisdocument is het vehicle (omdat elk reisdocument een unieke privé sleutel heeft)
ii.	Met reisdocument verkrijg je stembiljet door eenmalig uitgave digitaal token
b.	Papier
i.	Papieren stem pas inleveren
ii.	Stembiljet verkrijgen

1. Met stembiljet stemmen <-- het stemmen zelf is verder buiten scope
### Architectuur vragen
Complimenten voor de praktische benadering en tastbaar zoeken naar te realiseren prototype / concept. Realiseer je dat er vele vragen onderweg zijn die (on)bewust een antwoord krijgen. Probeer die te benoemen en formuleer je keuze(s) en overwegingen daarbij.

- Hoe self-sovereign is een reisdocument eigenlijk?
- Standaard ECDSA mogelijk aanpassen tgv cryptotechnologie?
- Plaatsen we de (betere?) beveiliging van deze oplossing in referentie t.o.v. het bestaande proces?
- Is gas ‘prijs’ ethereum echt relevant?
- Welke opties zijn er voor het elimineren geclaimde recht (ie voorkomen double spending digitale token)
o	(…)
o	(…)

**Comment by wkmeijer** [comment]
Attached research report concludes the research phase of the project.
[Digital_Voting_Pass_Research_report.pdf](https://github.com/Tribler/tribler/files/989462/Digital_Voting_Pass_Research_report.pdf)

**Comment by synctext** [comment]
thnx! good stuff. please include the ICTU argumentation:
We have self-driving cars soon. In the future it is likely that the new generation of citizens are not willing willing to vote, unless it is electronic from any place using any approved device.

Please add 4.2  "trust requires uncompromising usage of open source technology" or something. all hardware used should be open hardware licensed to build trust with voters.... it is essential to provide end-to-end integrity checks to ensure correct functioning of the ecosystem.. etc.

Bonus:  that 8 Byte sign restriction.. try to get rid of that using a 3DES aanpak (CBC chaining):
by using a standard string of specially crafted repeated and chained signatures we are able to iteratively sign standard SHA256 signatures... hash collision.. etc... (argument/proof included..)..

**Comment by landgenoot** [comment]
CBC seems to be a really clever solution, thanks!

**Comment by wkmeijer** [comment]
@synctext 
Thanks for your feedback, we added the ICTU argument in the introduction and updated 4.2.
[Digital_Voting_Pass_Research_report_v2.pdf](https://github.com/Tribler/tribler/files/1000475/Digital_Voting_Pass_Research_report_v2.pdf)

**Comment by synctext** [comment]
Please include the foundation for trusted identity: https://en.wikipedia.org/wiki/Physical_unclonable_function
That is the key component to guarantee the system integrity.

**Comment by wkmeijer** [comment]
Pictures of our wall. Our global planning as we drew it in the sprint planning.
![Wall picture 1 (global planning of sprints](https://cloud.githubusercontent.com/assets/7383936/26059214/345a9f7e-3981-11e7-85c6-623e99bda347.jpg)
![Wall picture 2](https://cloud.githubusercontent.com/assets/7383936/26059213/34594a34-3981-11e7-9547-122c5c2ede6e.jpg)

**Comment by wkmeijer** [comment]
@synctext Here are the screenshots of the app, I've included all the possible screens, feel free to use as little or as many as you want. Retrieved data is the signed 8-byte '0a1b2c3d4e5faabb' hexstring, signed with my passport.
Starting screen
![Homescreen](https://cloud.githubusercontent.com/assets/7383936/26061249/a35fa706-3987-11e7-9964-3dbbbe7d3d74.png)
NFC disabled error
![screenshot_2017-05-15-15-37-20](https://cloud.githubusercontent.com/assets/7383936/26061248/a32bea2e-3987-11e7-89c7-435c0d888f6d.png)
Retrieved signed data (192 byte)
![screenshot_2017-05-15-15-38-37](https://cloud.githubusercontent.com/assets/7383936/26061250/a36ee626-3987-11e7-83bd-af9d366b8368.png)
Retrieved signed data 2 (different because non-deterministic)
![screenshot_2017-05-15-15-38-48](https://cloud.githubusercontent.com/assets/7383936/26061246/a32276a6-3987-11e7-96cc-965a7a2d92a9.png)
Retrieved signed data 3 with pop-up of BSN from datagroup 1 of passport
![screenshot_2017-05-15-15-38-58](https://cloud.githubusercontent.com/assets/7383936/26061247/a327c44e-3987-11e7-825d-8d3c482f4bc9.png)

**Comment by landgenoot** [comment]
Research report updated according to feedback (thanks to @jellelicht !).

[Digital_Voting_Pass___Research_report.pdf](https://github.com/Tribler/tribler/files/1013868/Digital_Voting_Pass___Research_report.2.pdf)

**Comment by wkmeijer** [comment]
[Final report chapter 1 draft](https://github.com/Tribler/tribler/files/1024774/Digital_voting_pass_Final_report_Ch1_draft.pdf)

**Comment by synctext** [comment]
[The current operational app](https://github.com/digital-voting-pass/digital-voting-pass-app) can now ([.apk](https://github.com/digital-voting-pass/digital-voting-pass-app/blob/feature/91_load_voting_token_amount/app/build/outputs/apk/app-debug.apk)):
- e-passport lib: fully talk to Dutch identity documents, both NFC and OCR of the machine readable zone.
- integrated blockchain fabric. [Enhanced C++ library of Multichain with full-node Bitcoin support](https://github.com/digital-voting-pass/digital-voting-pass-multichain).
- created new Multichain fabric, using the Eliptic Curve similar to the one used within the Dutch e-passport
- On top of Passport-Multichain _voting tokens_ can be created. Allowing the owner of a passport to vote, the electronic equivalent of a voting pass.

**Comment by landgenoot** [comment]
Draft final report: 
[Digital_voting_pass___Final_report (1).pdf](https://github.com/Tribler/tribler/files/1057443/Digital_voting_pass___Final_report.1.pdf)

**Comment by wkmeijer** [comment]
Overview of the current voting process and the proposed new voting process using the digital voting pass.
[Current voting process](https://github.com/Tribler/tribler/files/1057449/StemmenHuidig.pdf)
[Proposed voting process](https://github.com/Tribler/tribler/files/1057448/StemmenNieuw.pdf)

**Comment by wkmeijer** [comment]
https://www.nrc.nl/nieuws/2017/06/06/ruim-7600-stemmen-niet-meegeteld-bij-verkiezingen-a1561918

**Comment by synctext** [comment]
Problem description:
- fraud
- ease of use
- efficiency
- willingness to vote in an analog fashion in coming decades
- dummy-proof, friction-less procedure

**Comment by landgenoot** [comment]
Feedback first SIG upload:

> Beste,
> 
> Hierbij ontvang je onze evaluatie van de door jou opgestuurde code. De evaluatie bevat een aantal aanbevelingen die meegenomen kunnen worden in de laatste fase van het project.
> 
> Deze evaluatie heeft als doel om studenten bewuster te maken van de onderhoudbaarheid van hun code en dient niet gebruikt te worden voor andere doeleinden. 
> 
> Mochten er nog vragen of opmerkingen zijn dan hoor ik dat graag.
> 
> Met vriendelijke groet,
> Dennis Bijlsma
> 
> 
> 
> [Analyse]
> De code van het systeem scoort 4 sterren op ons onderhoudbaarheidsmodel, wat betekent dat de code bovengemiddeld onderhoudbaar is. De hoogste score is niet behaald door een lagere score voor Unit Size.
> 
> Voor Unit Size wordt er gekeken naar het percentage code dat bovengemiddeld lang is. Het opsplitsen van dit soort methodes in kleinere stukken zorgt ervoor dat elk onderdeel makkelijker te begrijpen, te testen en daardoor eenvoudiger te onderhouden wordt. Binnen de langere methodes in dit systeem, zoals bijvoorbeeld de 'Camera2BasicFragment.setUpCameraOutputs'-methode, zijn aparte stukken functionaliteit te vinden welke ge-refactored kunnen worden naar aparte methodes. Commentaarregels zoals bijvoorbeeld 'Find out if we need to swap dimension to get the preview size relative to sensor coordinate' zijn een goede indicatie dat er een autonoom stuk functionaliteit te ontdekken is. Het is aan te raden kritisch te kijken naar de langere methodes binnen dit systeem en deze waar mogelijk op te splitsen.
> 
> In bovenstaand voorbeeld valt het overigens op dat het bestand "Copyright 2014 The Android Open Source Project" bevat. De packagenaam (com.digitalvotingpass.camera) is echter van jullie, dus het wekt de indruk dat jullie het oorspronkelijke bestand hebben aangepast. Ik heb dit daarom opzettelijk als voorbeeld genomen: als je er voor kiest om andermans code te adopteren en aan te passen, ben je vanaf nu ook verantwoordelijk voor het onderhoud van deze code.
> 
> De aanwezigheid van test-code is in ieder geval veelbelovend, hopelijk zal het volume van de test-code ook groeien op het moment dat er nieuwe functionaliteit toegevoegd wordt. 
> 
> Over het algemeen scoort de code bovengemiddeld, hopelijk lukt het om dit niveau te behouden tijdens de rest van de ontwikkelfase.
> 
> 
> Dennis Bijlsma | Senior Consultant

**Comment by landgenoot** [comment]
[Digital_voting_pass___Final_report.pdf](https://github.com/Tribler/tribler/files/1073921/Digital_voting_pass___Final_report.7.pdf)

Draft report

**Comment by synctext** [comment]
The SIG rules of code review include: each library you include in your project becomes your responsibility and you need to ensure sufficient quality.

However, this e-voting pass project includes a whole blockchain infrastructure in the form of a library. Fixing numerous person-years of code is not realistic.

**Comment by kc1212** [comment]
Recent publication on voting https://dl.acm.org/citation.cfm?id=3019841
not sure if it's related to this work, but might be interesting

**Comment by jonathanraes** [comment]
[Digital_voting_pass___Final_report.pdf](https://github.com/Tribler/tribler/files/1095303/Digital_voting_pass___Final_report.1.pdf)

2nd Draft final report

**Comment by synctext** [comment]
- MOSCOW pointer sentence in intro + 1 line this is a thesis project.
- blockchain and e-passport prototype
- fault-tolerance and attack-resilience 
- thousands votes are lost in the last election.
- with accusations that Russia has electronically attacked US-presential elections..
- easy to read picture for chapter 1 or 2 (illustrate analog voting pass).
- intro : we use the blockchain as a tamper-proof database. ensure integrity
- all appendixes are pointed to and have intro sentence.
- Voting passes from a live blockchain
- add screenshots to chapters
- chapter 6: MBytes ?
- _needs overall polish_

**Comment by synctext** [comment]
(final) report ?

**Comment by Jaapp-** [comment]
About halfway through final readthrough.
[report.pdf](https://github.com/Tribler/tribler/files/1102799/report.pdf)

**Comment by landgenoot** [comment]
Thanks Jaap, looks good!
Maybe you should also post it to https://github.com/Tribler/tribler/issues/2925

**Comment by klikooo** [comment]
@syntext we have come up with the following structure for the presentation:

- Opening
- Problem description
  - Paper
  - Digital
- Research towards new solutions
- Partial solution (voting pass)
- Blockchain
  - Problem identity
 - MRTD 
 - Proposed solution
 - OCR
 - jMRTD
 - Wallet
 - ePassportChain (different elliptic curve)
 - Demo
 - Code quality
 - Expert review

Do you have any comments/feedback?

**Comment by synctext** [comment]
please post .pdf of .ppt... Suggest add problems with paper 14000 vote diff.

**Comment by wkmeijer** [comment]
[Draft presentation (pdf)](https://github.com/Tribler/tribler/files/1113134/Digital_Voting_Pass_presentation_draft.pdf)

**Comment by wkmeijer** [comment]
Second feedback of SIG

> [Hermeting]
> 
> In de tweede upload zien we dat zowel de omvang van het systeem als de score voor onderhoudbaarheid is gestegen. Op het gebied van Unit Size zien we een bescheiden verbetering ten opzichte van de eerste upload. Let wel op dat je niet aan de ene kant aan het refactoren bent, en vervolgens aan de andere kant weer net zo goed nieuwe lange methodes aan het toevoegen bent.
> 
> Ook is het goed om te zien dat jullie naast nieuwe productiecode ook aandacht hebben besteed aan het schrijven van nieuwe testcode. De hoeveelheid nieuwe tests kan nog wel iets beter.
> 
> Uit deze observaties kunnen we concluderen dat een deel van de aanbevelingen van de vorige evaluatie zijn meegenomen in het ontwikkeltraject.

**Comment by synctext** [comment]
Project finished with 91-page final report, see above, closing issue...
