### ISSUE TITLE
2.0 Rc1 Not Working (Tribler vs Windows 10 v1703?)

### ISSUE THREAD

**Issue by Halbon** [Tribler/tribler#2924]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
2.0rc1
##### Operating system and version: #####
Windows 10 Home 1703

##### Expected behavior: #####
Building Circuit -> Inactive for all the completed ones, downloading & active for all the current ones.

##### Actual behavior: #####
With many attempts, most of the time, everything stops at "Building Circuit." That's it. Sometimes I get lucky after 10 or 15 min that some goes into Downloading but no connection. Other stuck at "Building Circuit." Configuration was blown off at the upgrade from beta to rc1? No firewall port. I had to re-install to see it there but nothing improved. I went back to beta, which worked before but now no. 

##### Steps to reproduce the behavior: #####
I upgraded to Windows 10 1703 few days ago. I was still on beta and Tribler behaved a bit funny (froze) but it was happening time to time anyways so I did make sure both Inbound and Outbound rules are set with Windows Firewall and rebooted Tribler, which worked fine. I upgraded to rc1 yesterday with same setup and everything stopped. I restarted Tribler numerous times, rebooted PC, re-installed, ran the app as Admin, etc. Now back to beta, The symptom is the same so I suspect more for Tribler vs new Windows 10 update. I opened a reliable torrent file with uTorrent and it went without a hitch. So, it is just Tribler, unfortunately...

##### Relevant log file output: #####
I don't see any error message. it's the same undetected Windows 10 version and TLS messages.

**Comment by Halbon** [comment]
Realized I have a laptop with Windows 10 v1607 on it. I installed Tribler for the 1st time using rc1. It installed correctly, things ran pretty fast and the 1st torrent, worked.
Should I try completely uninstalling Tribler on my main including the settings? I know it gets deleted anyways but the installation message did not say this was first time opening it...
Please let me know a proper step for a complete uninstall and I can try that.

**Comment by Halbon** [comment]
Sorry for bubbling, but the reset (from faq) worked. I lost my entire list but I re-installed rc1 and now it flows fine. If this happens for everyone then it is a bug but otherwise, it probably just me...

**Comment by synctext** [comment]
thnx for the report.
Good to hear what went wrong and nice that it now works!

**Comment by Halbon** [comment]
Johan,

Actually everything else works MUCH MUCH better.
Even better than the beta.
So much were fixed, performance is now definitely realistic in terms of
download speed with hop or hops.
Thank you so much working to better this product and I love it!
Just wanted to send a compliment instead of pounding on a bug report!

**Comment by devos50** [comment]
Great to hear that, thanks and enjoy! :)
