### ISSUE TITLE
autonomous self-replicating code

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2925]
Goal: creating healthy exit-node network through cybercurrency.

Previously a TUDelft thesis project created an initial implementation of the [autonomous self-replicating code concept](http://repository.tudelft.nl/islandora/object/uuid:a1b443c7-8b37-4263-ae96-d38bc8b8f397).

next step: _go live_ 

Key features:
- earn cybercurrency using the Tribler blockchain
- provide Tor-like exit node services
- unpermissioned [open compute API](https://www.google.nl/search?q=bitcoin+vps) in Python (Scrapy, urllib2,BeautifulSoup,lxml,..)
- post [births and life events](https://twitter.com/pleb_net) on Twitter
- sell Tribler credits for Bitcoin on open market
- auto-buy-bot
  - provide initial market liquidity
  - automagically buying Tribler credits
  - create healthy exit-node network of 25+ servers

Planning:
- 2 week sprints
- 1 chapter of documentation per sprint
- Week 1-2 focus: initial experiment: Selenium, Singapore server, Dispersy community
- Week 3-4 focus: open compute API? (light-weight, fast, robust, high-volume support)
- Week 5-6: earn, sell, and buy?
- Week 7-8:

Include in the report a detailed analysis of why the previous code could not be re-used and why clean-slate implementation was started.

**Comment by Jaapp-** [comment]
Project

VPS configuratie kiezen via evolutie
- python module
- kies aanbieder en configuratie
- evolutie op basis van:
	- server niet kunnen kopen
	- downtime
	- aantal reputatie
	- bandbreedte
	- ram
	- storage
	- levensverwachting
	- prijs
- leer van ouders
- optioneel: leren van familie voor meer data
	- kans-gebaseerde mutaties op succesvolle configuraties


VPS kopen
- automatisch via selenium
- reverse-engineer registratie high level
	- niet erg vatbaar voor bot-detectie
- apis vaak niet beschikbaar
	- cloud misschien niet mogelijk/legaal
- utopia: via AI veranderende websites opvangen, nieuwe hosts
	- niet te doen
- kopen kan breken
	- error communiceren via blockchain/centraal systeem?
	- dispersy gebruiken om errors door te sturen
- twitter account aanmaken om leven te laten zien
	- ook goede marketing
	- #plebnet
- tijdelijke mailserver gebruiken
	- VPS mailtjes ontvangen
- grafische omgeving nodig voor selenium
	- op server via xvfb zoals project vorig jaar

VPS instantieren
- ansible
	- er bestaat een tribler role / playbook
	- ssh gegevens van gekochte server linken
	- ubuntu 14.04 / 16.04

Reputatie minen
- exit node?
	- risico DMCA
	- annulering vanuit VPS
	- wel veel meer reputatie minen
	- moreel verantwoord?
- periodiek/continu controle programma
	- kijkt of alles nog draait
	- kijkt voor updates vanuit github repo
	- server restart opvangen
- bestanden downloaden
	- minder reputatie in de korte termijn
	- meer reputatie in de lange termijn
- mining loggen
- website met informatie hosten
	- ouders, kinderen
	- markt prijs
	- life-expectancy
	- geminede reputatie

Reputatie verkopen
- wisselkoers achterhalen
	- MC <-> BTC
	- vraag en aanbod bijhouden
	- handels strategie bepalen
- levensverwachting bepalen
	- schatting maken van verwachte aantal BTC op basis van mining rate
	- end-of-life VPS opties bekijken
- handels mechanisme
	- redelijk hoge wisselkoers: alles verkopen
- reputatie / btc doorgeven aan kinderen
	- wallet doorgeven
	- reputatie
	- alles verkopen aan eind van lifecycle




Tests
- Unit tests
	- alle python code unit testen
	- continuous integration via dedicated jenkins server
	- moet selenium kunnen testen

- Ansible testen
	- of virtuele servers binnen proximox server
	- of automatisch nieuwe proximox server aanmaken, daarop ansible script runnen

- Markt simulatie
	- testen van handels mechanisme
	- verkopen als wisselkoers gunstig is

- Integratie/regressie test
	- constant productie server draaiend
	- blijft minen
	- geen exit node, misschien russische VPS?
	- detecteer fouten bij updates

**Comment by Jaapp-** [comment]
Main repository
https://github.com/rjwvandenberg/PlebNet

**Comment by Jaapp-** [comment]
The priority is to get the end-to-end system architecture operational instead of putting intelligence in each or every module.

**Comment by synctext** [comment]
docker as run everywhere execution model, from-the-source, other ?

**Comment by synctext** [comment]
https://www.reddit.com/r/Bitcoin/comments/50zapi/whats_the_best_vps_hosting_service_that_accepts/
https://www.google.nl/search?q=vps+bitcoin+review

**Comment by rjwvandenberg** [comment]
Sprint 2 will focus on creating the robust open compute api, aptly named Cloudomate.
[Initial System Architecture](https://github.com/rjwvandenberg/PlebNet/blob/master/doc/Images/System%20Architecture.jpg)
[Agent Creation](https://github.com/rjwvandenberg/PlebNet/blob/master/doc/Images/Agent%20Creation.jpg)
[VPS Registration & Payment](https://github.com/rjwvandenberg/PlebNet/blob/master/doc/Images/Buy%20VPS%20Simple.jpg)

Agents may communicate with each other through decentralized mailing systems. We implemented a sophisticated mailing system, with agents from Delft, Singapore and New York sending each other greet messages: [Agents sending greetings](http://i.imgur.com/ZS7rhT8.png) Messages arrived within seconds after joining the network. Further work may fall outside the project requirements, so this project will be put on notice. [Dispersy_communication branch](https://github.com/rjwvandenberg/PlebNet/tree/dispersy_communication)

We performed a data transfer test between VPS s hosted by DigitalOcean. Data rates around the globe varied between 8.2MB/s and 44MB/s. A 1TB bandwidth cap may be consumed within days. This may cause problems if the agent gets shutdown without being able to instantiate new agents. We must take care to review hoster policies and select suitable hosters.

In sprint 1 we reviewed the previous BEP project on autonomous self-replicating code and applied their methods. Especially selenium may be too resource heavy to run on a cheap VPS. Other problems included too tightly coupled modules. A detailed report will follow.

**Comment by synctext** [comment]
ToDo: 
- document _first prototype of a permission-less open compute API_
- renew existing VPS subscription or simply always let die. ?
- table that Bitpay is the cool kid, largest VPS provider reach for dev time.
- 

![image](https://cloud.githubusercontent.com/assets/325224/26058367/ecc029f2-397d-11e7-92ad-ebae56ecb0f3.png)
![image](https://cloud.githubusercontent.com/assets/325224/26058370/f1835bbc-397d-11e7-94d1-fc8cbc8bc02a.png)
![image](https://cloud.githubusercontent.com/assets/325224/26058374/f5c8c86a-397d-11e7-8f0b-a14b431672fe.png)

**Comment by MitchellHop** [comment]
![cloudomatepip](https://cloud.githubusercontent.com/assets/5709613/26678634/b7074712-46d1-11e7-94e1-731a689c1d77.PNG)
![output](https://cloud.githubusercontent.com/assets/5709613/26678639/bb6e7f14-46d1-11e7-9cd7-0b8e1827766f.gif)
![output2](https://cloud.githubusercontent.com/assets/5709613/26678641/befc4774-46d1-11e7-883b-57557ad2b4de.gif)

**Comment by devos50** [comment]
Amazing! 👍

**Comment by synctext** [comment]
very impressive!

**Comment by Jaapp-** [comment]
[report.pdf](https://github.com/Tribler/tribler/files/1057565/report.pdf)

**Comment by synctext** [comment]
Expand chapter 1, also add picture of, for instance, 1) buy server 2) buy cloud server 3) buy VPS with Bitcoin.

Experiment with GIT based timing of 3 providers. Start till (Github URL) first success with real Bitcoin transaction (blockchain-browser). Table with VPS provider, minutes of development, LoC, code coverage, etc?

Performance analysis.
Please add timing (time-to-buy-and-Hello-world) and performance graphs (speedtest, etc.).

**Comment by rjwvandenberg** [comment]
![dockerbuild](https://user-images.githubusercontent.com/5699518/26974677-bd63c530-4d1c-11e7-974c-ea183c1f7155.png)
Tribler exitnode including decentralized market is now available as a docker image. Built directly from the master branch of plebnet. [](https://hub.docker.com/r/plebnet/tribler_market/)

**Comment by Jaapp-** [comment]
[report.pdf](https://github.com/Tribler/tribler/files/1074886/report.pdf)

**Comment by synctext** [comment]
Please focus on report writing. 
For instance, chapter 6, Actual money trials

**Comment by synctext** [comment]
new report ?

**Comment by Jaapp-** [comment]
[report.pdf](https://github.com/Tribler/tribler/files/1104722/report.pdf)
Report now on our own issue.

**Comment by Jaapp-** [comment]
The first time we're seeing our decentralized autonomous entity (DAE) reproduce and trying to earn money on our market to fork more children.
![2017-06-29-170136_905x764_scrot](https://user-images.githubusercontent.com/3542526/27694538-a515bbe8-5cec-11e7-8f15-b5f19ba5461d.png)

**Comment by rjwvandenberg** [comment]
In the end the server selection for cloudomate proved insufficient. Operating autonomously will require a very strict cherrypicking based on DMCA policies and registration procedures. Even then the internal setup of servers was shown to differ from what may be expected, requiring additional step after server activation. Out of the current 8 providers none have been reliable enough for an autonomous system.

In the final test we encountered some very specific errors, to correctly handle these additional code improvements to cloudomate and PlebNet are required. Especially the interaction between the two programs will have to be more rigid.

For tribler integration, the plebnet_plugin used by twisted did not incorporate the tunnel_helper instance directly, this will have to be done to avoid running a seperate twistd instance for market and tunnel_helper. 

PlebMail was succesfully used to monitor the status of the Plebs:
![final_contribution 1](https://user-images.githubusercontent.com/5699518/27959118-77755154-6326-11e7-9efe-40ca89711ebb.png)

A final graph of the upload of some of the servers at this moment. (only a few remain running)
![performance](https://user-images.githubusercontent.com/5699518/27959532-1ea963ba-6328-11e7-8942-71b67e16a050.png)

[PlebNet repository](https://github.com/rjwvandenberg/PlebNet)
[Cloudomate repository](https://github.com/jaapp-/cloudomate)
[tribler fork for PlebNet](https://github.com/rjwvandenberg/tribler)

**Comment by rjwvandenberg** [comment]
For the next month plebnet will run as exitnodes on the following servers that remain:
linevast, pulseservers, abelohost, hidemyhost, underground, aminserve, flokinet and offshorededi 
These last 6 were bought without making use of cloudomate and if they stay online for the next month, they may be suitable for use with plebnet. 
Near real time updates on the status may be seen on the following site:
[plebnet live status](http://178.62.213.155/)

**Comment by synctext** [comment]
impressive !

**Comment by Dmole** [comment]
Was adding a VPN layer for VPSs with incompatible DMCA policies considered?
http://compare.wikia.com/wiki/Vpn_Provider

**Comment by devos50** [comment]
@Dmole actually, we considered that a few weeks ago and it's on our wishlist to implement that in one of the coming releases 👍

**Comment by synctext** [comment]
Next: _going live in Tribler_
We are ready for the next steps this year with the maturing of our token economy and self-replicating code. The initial step is to provide advanced CloudOmate to ordinary users of Tribler, who are not experience traders, market makers, or command-line Linux experts. With the integration of the Bitcoin wallet we can expose buying servers to our users. Target the following for a new V7.3 or V7.4 version. It is a killer feature for press attention. 

"buy mining hardware" button in Tribler. Next screen showing _Earn tokens automatically. Use your Bitcoin or Ethereum wallet to buy the following (step 1 of 3)_:
- [ ] Buy server + install protective VPN
  - [X] + relay fully encrypted traffic + credit mining of disk space
  - [ ] + exclusively used for myself, no earning of credit by helping others
- [ ] merely buy and install protective VPN

**Comment by devos50** [comment]
@thijmensjf @codesalad @vwigmore this ticket is all yours for the coming ten weeks! 👍

**Comment by devos50** [comment]
Literature to start with:
- https://repository.tudelft.nl/islandora/object/uuid%3Aa1b443c7-8b37-4263-ae96-d38bc8b8f397?collection=education (TENNET)
- https://repository.tudelft.nl/islandora/object/uuid%3A08841cf0-8ddf-4354-9c99-bc7c270d67fd?collection=education (PlebNet)
- https://github.com/Tribler/tribler/issues/3238 (Master students who worked on Cloudomate)
- https://github.com/Tribler/tribler/issues/3240 (Master students who worked on VPN integration in Cloudomate)

**Comment by devos50** [comment]
Overall goal: Setup, deploy and optionally evaluate an end-to-end Botnet with self-replicating servers. Use the existing Cloudomate software to buy (and monitor) new servers, use PlebNet to install Tribler and deploy an exit node (optionally with VPN protection). Finally, sell earned bandwidth tokens on our decentralized market.

First sprint:
- Perform a requirement analysis -> create MOSCOW model
- Explore what's working and what not
  - Setting up IDE, getting familiar with the existing code

**Comment by thijmensjf** [comment]
# Sprint 1 Logs

## Tribler
* Tested the new Tribler version including marketplace
* Fixed incorrect import in PlebMail so no errors for now, PlebMail should be deleted later

## Cloudomate
* Made several test vps purchases, found out that BitPay gateway needed to be updated
* Providers using BitPay should be usable now (Linevast, Blueangelhost for sure)
* Fixed some Jenkins tests most test work the exceptions being: buying a vps instance of ccihosting, undergroundprivate or pulseservers. Both undergroundprivate and ccihosting changed their gateway that is used to buy a server in bitcoins. pulseservers has issues when trying to buy a vps server with cloudomate but these errors also happen when trying to buy it  manually so the error is on their side. And finally the coinbase tests fail this is because the test url isn’t supported anymore. Unable to find a suitable replacement but when done this should be a quick fix.


## PlebNet
* We looked at other possible ways to package PlebNet
	* [Snaps](https://snapcraft.io/) would provide an easy to containerize PlebNet along with its dependencies. This unfortunately does **not** work because mounting virtual filesystems is not permitted on most vpses.
* We decided to continue with an install script (which as been fixed to work again)
* Incorrect method calls to Cloudomate fixed
* Structure of Settings file created by PlebNet adjusted for Cloudomate
* List of VPS no longer hard-coded but retrieved from Cloudomate for the initial agent
* Started refactoring
* Found bug where agent can only buy one server per VPS provider because of one single email used


## Monitoring
* Implemented an IRC client for communication and monitoring purposes. The plebbot is able to provide information regarding its configuration and status, and gives a regular heartbeat to notify about its existence. This allows monitoring the size and performance of the plebpopulation.
![image](https://user-images.githubusercontent.com/5962972/39694238-ed4b27c8-51e6-11e8-9fd3-ef8773c7d6df.png)
* The error handling (reconnecting when the connection is lost etc.) should still be improved.
* implemented a logger to store the application process information.

**Comment by vwigmore** [comment]
Current progress

- Refactoring of PlebNet
Restructured the program architecture and the in- and external dependencies. This resulted in better understandable code. 
moved from 400+ loc to ~100 per class
split up files based on their job and dependencies
created controllers for external processes (Tribler/Electrum/…) to join their dependencies.
![image](https://user-images.githubusercontent.com/9844091/40063125-eb0de2f8-585c-11e8-871a-c90d8b570265.png)
![image](https://user-images.githubusercontent.com/9844091/40063141-f7f1840c-585c-11e8-971c-bfea0f0e637e.png)
- Setting up Jenkins for PlebNet
PlebNet now has its own Jenkins job on the jenkins.tribler server which runs all tests in the PlebNet/tests folder. The build is not automatically triggered as it is configured to run on github/vwigmore/plebnet

**Comment by synctext** [comment]
- "controllers" are simply the APIs?
- only 1 VPS provider operational, VPN support not yet tested
- where to document?
- make life easy for the 4th BEP group on this topic?
- expand final thesis with 1 chapter each sprint?
- what is the next sprint theme?
- Proxmox emulation

**Comment by thijmensjf** [comment]
The current version of the report:
[Bachelor_Project_2018_BotNet.pdf](https://github.com/Tribler/tribler/files/2025931/Bachelor_Project_2018_BotNet.pdf)

**Comment by vwigmore** [comment]
Added coverage report building for plebnet on jenkins 
![screenshot from 2018-05-22 13-03-31](https://user-images.githubusercontent.com/9844091/40358791-c0f864ca-5dc0-11e8-9b08-e55b63f19b61.png)

**Comment by devos50** [comment]
Current status at the beginning of week 6:
- PlebNet script working, some issues with upgrading Pip. Please try to use Debian 9 as base OS on servers.
- Market API explored, encountered some issues when creating asks/bids due to the unavailability of matchmakers. Try to run a second Tribler instance and it should work.
- PlebNet install script installs another instance of Electrum. Try to use the Electrum daemon of Tribler instead, this simplifies the script.
- There is some code to automatically post issues on a Github repository. Integration of this functionality is pending.

**Comment by codesalad** [comment]
Our Sprint 3:
![sprint3](https://user-images.githubusercontent.com/9729649/40611758-ebad8ba8-6277-11e8-80ae-7da21d4741c5.PNG)

Report: 
[Bachelor_Project_2018_BotNet.pdf](https://github.com/Tribler/tribler/files/2044808/Bachelor_Project_2018_BotNet.pdf)

We mainly focussed on preparing for SIG, Jenkins and proxmox end-to-end testing this sprint. We'll add more to the report this week as proxmox integration is done and jenkins, marketplace are prioritized in sprint 4.

**Comment by vwigmore** [comment]
First upload to SIG complete with a total coverage of 76%
![coverage](https://user-images.githubusercontent.com/9844091/40788759-1667515a-64f1-11e8-800e-e5f0fcf4619e.png)

**Comment by vwigmore** [comment]
The current version of the report:
[Bachelor_Project_2018_BotNet (4).pdf](https://github.com/Tribler/tribler/files/2067586/Bachelor_Project_2018_BotNet.4.pdf)

**Comment by codesalad** [comment]
**Proxmox**

**Listing options with Cloudomate**
![cloudomate purchase](https://user-images.githubusercontent.com/9729649/40910771-540cbb0e-67ed-11e8-93c1-3971247d5283.gif)

**Purchasing container with Cloudomate**
![cloudomate purchase 2](https://user-images.githubusercontent.com/9729649/40910842-7b27de62-67ed-11e8-88d5-26494059a236.gif)

**An invoice is created using the Bitpay API**
![cloudomate purchase 4_edit_0](https://user-images.githubusercontent.com/9729649/40910866-8e64ab22-67ed-11e8-861b-27f01add2f3f.gif)


**Accessing server**
![cloudomate purchase 3](https://user-images.githubusercontent.com/9729649/40910896-a38401ec-67ed-11e8-9fb2-a724553905e5.gif)
You can also create and destroy the container through the `/manage` "API". Containers are created and destroyed with ansible scripts (we don't use snapshots because the proxmox machine's filesystem doesn't allow that). This allows us to test things such as installing the server and monitoring on a clean container, making sure the install scripts are not missing anything.

**Comment by codesalad** [comment]
![sprint4](https://user-images.githubusercontent.com/9729649/40912730-b0f3acf6-67f2-11e8-8a0f-c3c3c0c349f8.png)

Most of the items were finished, installing VPN is going to be a task for this sprint (5)

**Comment by devos50** [comment]
Sprint 5 is just finished. Report of this sprint will be posted on this ticket today.

Issues:
- TUN/TAP is not enabled by default on all servers. One might have to enable it from within the client area of a particular VPS.
- 

What's working right now:
- Instaling Plebnet + running Tribler as an exit node
- Creating a Bitcoin wallet and/or testnet wallet using Tribler
- Creating transactions to the market API
- Transferring funds to another server works manually, should be automated

Sprint 6 goals:
- Make sure all components you created during the previous sprints, are functional. This is the most important goal for this sprint 👍 
- Monitoring (debugging workflow).
- Investigate the viability of VPN integration (please make this a lower priority issue)

**Comment by thijmensjf** [comment]
[Bachelor_Project_2018_BotNet (1).pdf](https://github.com/Tribler/tribler/files/2089460/Bachelor_Project_2018_BotNet.1.pdf)

**Comment by codesalad** [comment]
**Naive bidding bot created**
The bot looks for `http://localhost:8085/market/asks` items and places a bid against these (works for both TBTC and BTC, depending on Tribler setup). 

Currently, sometimes transactions show up as a failed transaction (but price and quantity are transferred). Because `asks` are not removed when transactions are not complete, the bot may place multiple bids. A lower timeout for asks could be set to relieve this.

```
12/06/2018 18:25:20:Coin type is: TBTC
12/06/2018 18:25:20:Starting new HTTP connection (1): localhost
12/06/2018 18:25:20:http://localhost:8085 "GET /market/asks HTTP/1.1" 200 1528
12/06/2018 18:25:20:[Ask]: 0.0001131 TBTC 500.0 MB
12/06/2018 18:25:20:[Making a bid]:  0.0001131 TBTC 500.0 MB
12/06/2018 18:25:20:Starting new HTTP connection (1): localhost
12/06/2018 18:25:20:http://localhost:8085 "PUT /market/bids HTTP/1.1" 200 None
12/06/2018 18:25:20:{u'created': True}
12/06/2018 18:25:30:[Ask]: 0.0001131 TBTC 500.0 MB
12/06/2018 18:25:30:[Making a bid]:  0.0001131 TBTC 500.0 MB
12/06/2018 18:25:30:Starting new HTTP connection (1): localhost
12/06/2018 18:25:31:http://localhost:8085 "PUT /market/bids HTTP/1.1" 200 None
12/06/2018 18:25:31:{u'created': True}
```

**Comment by thijmensjf** [comment]
The current version of our report can be found [here](https://github.com/Tribler/tribler/files/2107455/Bachelor_Project_2018_BotNet.2.pdf)

**Comment by thijmensjf** [comment]
Currently (re)writing our report, as it has to be handed over comming Saturday. 

Implemented some features regarding data collection to expand the monitoring options. Every ten minutes the data (uploaded and downloaded MBs, MB/BTC/TBTC balance etc.) from the agents is stored and this used to automatically create graphs.
![fig__deltas_for_mb_balance](https://user-images.githubusercontent.com/5962972/41720072-3148cf04-7562-11e8-8d29-10c5dec68f3f.png)
![fig__deltas_for_uploaded](https://user-images.githubusercontent.com/5962972/41720073-3162a8ac-7562-11e8-935d-26a98461ed33.png)
![fig__values_for_mb_balance](https://user-images.githubusercontent.com/5962972/41720075-31960800-7562-11e8-9a14-091091850483.png)

For now these figures do not tell that much, as the time span is short (~24 hours), but during the demo we will have collected data for 2 weeks. This should be usable to gain an insight in the effectiveness of PlebNet.

**Comment by thijmensjf** [comment]
And we have created a logo for PlebNet, as it was lacking one:
![logo](https://user-images.githubusercontent.com/5962972/41720203-9aa5803c-7562-11e8-8007-fef430fe4f0d.png)

**Comment by synctext** [comment]
Your [promo slides presented here](http://blog.bythebay.io/post/175108476331/johan-pouwelse-at-rethink-trust) upcoming Friday?

**Comment by vwigmore** [comment]
Final version of the report as send per email 
[Bachelor_Project_BotNet.pdf](https://github.com/Tribler/tribler/files/2133729/Bachelor_Project_BotNet.pdf)

**Comment by codesalad** [comment]
@synctext This is one of the gifs we've prepared.
A "real-time" network viewing tool for PlebNet

![demo_vision](https://user-images.githubusercontent.com/9729649/42031541-16e66e28-7ac6-11e8-8ddd-c2db87de599f.gif)

I will send you the rest via e-mail.

**Comment by codesalad** [comment]
As requested, I'm uploading the slides/images/videos for [presentation](http://blog.bythebay.io/post/175108476331/johan-pouwelse-at-rethink-trust) here as well.

### Slide 1:
![logos](https://user-images.githubusercontent.com/9729649/42047944-057c374e-7b02-11e8-800b-2c0da85481ca.png)

- PlebNet is an autonomous self-replicating botnet
- Running Tribler Exitnode
- Self-replicates by purchasing servers with Cloudomate using earned Bitcoins 


### Slide 2

- An agent will clone itself on the new server
- Cloudomate is installed, Tribler is installed

     [demo_clone.gif (video->gif->huge file)](https://drive.google.com/open?id=1opQ2gx8hes85c8Hmu8SZQIrZpDIsGIE1)
    ​​​​
     [demo_clone.mp4](https://drive.google.com/open?id=16tjoEaaEgr-GT_paVl1m6TLK_lUxpL7i)


### Slide 3:

- The network can be monitored in real-time
- Graphs show the exit node's performance over ti​​me.

    ​​ [demo_vision.gif](https://drive.google.com/open?id=14_kihL9wuuipKU_Hec2voAkGTw1R09GQ)

     [demo_vision.mp4](https://drive.google.com/open?id=1U2GmmELjCS6t1RLe6FjZ7M3aKb8AcPsi)

**Comment by thijmensjf** [comment]
As our cycle in the project is ending, we will provide a final status update regarding the project. 

First of all there is a final version of the report, which can be found 
[here](https://github.com/Tribler/tribler/files/2163544/Bachelor_Project_2018_BotNet.pdf)

The slides of our final presentation can be found 
[here](https://github.com/Tribler/tribler/files/2163568/Eindpresentatie.pdf)

All in all it can be concluded that PlebNet is working end-to-end now, which is demonstrated in the following videos. 

[stage 1 - initialization of a agent](https://drive.google.com/file/d/1VpF2pWaYO_b1XTScaNcDIPj1bsTHw3wL/view?usp=sharing)
[stage 2 - create an offer on the market](https://drive.google.com/open?id=1u4zmLmxdVQjPa2bkT-7wUsaEO90FNhQP)
[stage 3 - buying a new VPS via cloudomate](https://drive.google.com/open?id=1K8xvqL6htXee1KnzdrhieHlBkB1F8JeZ)
[stage 4 - replicating on a new instance](https://drive.google.com/open?id=1OBO_w0zNnOYzXQgpAXszIcjg9j4b5ukw)
[monitoring via the IRC](https://drive.google.com/open?id=1cBo3LEVcpExLli4czUIwmcpb53a0UmEf)

**Comment by synctext** [comment]
[Official TUDelft repo of thesis](https://repository.tudelft.nl/islandora/object/uuid%3A614efc19-e6a9-453f-8084-2e2c54ddd93f) (has link to .pdf)

**Comment by synctext** [comment]
Related work:
![image](https://user-images.githubusercontent.com/325224/69265504-a99a1180-0bc9-11ea-9723-3136212c7882.png)
"[Mitogen is a Python library](https://mitogen.networkgenomics.com/) for writing distributed self-replicating programs."

**Comment by devos50** [comment]
This ticket will be used for the upcoming software project, starting this Monday. Project description (locked in ProjectForum):

> The goal of this Bachelor end project is to create a Bitcoin-based entity which can earn money, mutate, multiply, and dies. We provide a crude starting project which needs decades of further work in order to be considered 'really' living. This project builds upon existing code that creates autonomous life. Two previous groups have worked on this system and their documentation can be found in the TU Delft repository (see here and here). Recently, two groups of master students have expanded the project.

> You will create an Internet-deployed system which can earn money, replicate itself, and which has no human control. In the past, humanity has created chess programs that it can no longer beat. The distant future of an omniscient computer system that on day chooses to exterminate humanity in the Terminator films is not the focus of your project. You will create software that is beyond human control and includes features such as earning money (Bitcoin) and self-replicating code (the software buys a server and spawn a clone). Earning money consists of helping others become anonymous using the Tor-like protocols developed at TUDelft and our own bandwidth token designed for this purpose, called Tribler tokens. A cardinal unanswered question is how to securely pass the wallets with Tribler tokens and Bitcoin to the offspring servers. You Python software is able to accomplish some parts of the following functionality:
• Earn income in a form of a bandwidth token (existing code).
• Sell these earned tokens on a decentralized market for Bitcoin or other currencies.
• Buy a server with Bitcoin or Ethereum without human intervention (see our existing PyPi scripts).
• Login to this Linux server and install itself with code from the Github repository.
• Automatically buy and install VPN protection to hide the outgoing traffic from the servers.

> The software should be able to have a simplistic form of genetic evolution. Key parameters will be inherited to offspring servers and altered with a mutation probability. For instance, what software version of yourself to use (latest release?), what type of server to prefer buying (quad core, 4GB mem, etc), and whether you offer Tor exit node services for income or not. Bitcoins owned by TUDelft will be used to bootstrap your research.

**Comment by synctext** [comment]
@devos50 This will be used instead of Gitlab, feel free to give a 1-line pointer to this repo of TUDelft rules require you to leave notes there. All weekly meeting notes will be posted here (unless you GDPR-protest...)

**Comment by devos50** [comment]
@synctext I'm also using our other tickets on the Tribler repo for meeting notes so I'm totally fine with that.

**Comment by daangoossens22** [comment]
![Screenshot from 2020-06-19 11-22-44](https://user-images.githubusercontent.com/62295482/85117584-5f404800-b21f-11ea-9e33-6e91644ecdc0.png)
Getting the qtables through the IRC chat has been implemented, by calling !qtables{nick} you can get the qtable of the node that has that specific nick.

**Comment by daangoossens22** [comment]
I made the pull request both for Dollynator and cloudomate. Sorry for the delay.

most important changes made in Dollynator:
- gossiping implemented
- qd-learning implemented
- port the code to python 3.6
- a new market strategy implemented (namely crossover moving average)

Changes made in cloudomate:
- fixed the wallet code, so that it doesn't give an error mid purchase (with the latest electrum)
- fixed the providers linevast and qhoster
- linevast deletes accounts after purchasing and I have no idea why. From what I read and what I experienced this provider seems like a scam, and I don't recommend using it anymore.
- qhoster works, but it doesn't integrate with dollynator, not because of ubuntu 16.04 (because dollynator can work both on 16.04 and 18.04), but because the kernel version is too low to support some modules of tribler, so it cannot run tribler.

For a short summary of the gossiping and qd-learning, I will point to the readme in the dollynator repo. The best explaination of the specific parts, I will point to the related sections in our final report (which I linked in this message)
[Dollynator - Final Report.pdf](https://github.com/Tribler/tribler/files/4929974/Dollynator.-.Final.Report.pdf).

Another future recommendation that I forgot to say during the presentation Q&A, is if you want to run dollynator reliable for long periods of time, probably some dynamic adding of vps providers should be added or changing the vps providers code while it is still running (so while it replicated it get the latest code for cloudomate, which is probably already done, but should be checked). This is because the vps providers sites change a lot, which makes them not work anymore for dollynator/cloudomate, but if you want the botnet to run for a long time this should be accounted for. This is probably a hard problem, but maybe a good problem for a next group to solve.

Another tip while fixing cloudomate is to first buy an instance of the vps provider manually and check if that provider works for dollynator and then fix the code for it. Don't make the same mistake that I made to first fix the code and then later find out that it doesn't work with dollynator anymore, because of a kernel version (or something else).

**Comment by qstokkink** [comment]
It seems like this project has been completed years ago. I'll close this issue now.
