### ISSUE TITLE
Lockup when adding torrent with malformed tracker to channel

### ISSUE THREAD

**Issue by loadletter** [Tribler/tribler#2929]
#### Please, fill all relevant items: ####

- [X] I have read CONTRIBUTING.rst

- [X] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
v7-rc1 (next@0b49771947681e1f2219a1d029fbbb76f4f6a8f7)
and
devel@e865f5c122937a85095c5d81115a01b6638f0422 (run without GUI)
##### Operating system and version: #####
Debian 8 (Jessie)
##### Expected behavior: #####
Tribler ignores the bad tracker and adds the .torrent to channel
##### Actual behavior: #####
Core freezes running at 100%, CPU, GUI stops updating, log stops updating after PUT request with no message, requires sigkill to terminate.
##### Steps to reproduce the behavior: #####
1) download [this torrent](http://itorrents.org/torrent/3094CD7BDE8F8A6AE2A264F53482317E5646B2FE.torrent) where one of the tracker urls contains binary junk
2) add to own channel
##### Relevant log file output: #####
Nothing

**Comment by devos50** [comment]
Thank you for this report! We are hunting a bug for a while now where the core and GUI freezes for no reason. Is this issue reproducible for you?

**Comment by loadletter** [comment]
I don't leave my computer on for more than 1 day so I haven't noticed any other issues.

Also, I don't know if this is the right place, but I've noticed that in the statistics/trbiler API endpoint there's always an high number of failures and pending compared to success, like 
```
"torrent_queue_stats": {"failed": 216, ...  "type": "TFTP", "pending": 300, "success": 16}
```
Is it normal?
I've forwarded both 7759 and 7760 (UDP&TCP) on my router

**Comment by qstokkink** [comment]
@loadletter Yes, having a lot of failing trackers is quite normal. Also, I'm not seeing any malformed tracker URLs in this torrent (Ubuntu 15.10). My tracker list for this torrent looks like this (external tracker inspection tool on the left, Tribler on the right):
![tracker_list](https://cloud.githubusercontent.com/assets/3630389/25778728/3a49a7b6-3307-11e7-888b-88776635451e.png)
Could you perhaps supply the malformed tracker url?

I'll keep this running for a few hours and report back.

**Comment by loadletter** [comment]
Whoops, looks like those torrent cache websites actually edit trackers and other info, those are the originals:

https://my.mixtape.moe/dtyvkd.torrent
https://my.mixtape.moe/yqktoe.torrent
https://my.mixtape.moe/pvpzut.torrent

Also I think simply adding the torrent for download worked but adding to channel caused the lockup.

**Comment by qstokkink** [comment]
@loadletter Thanks! Those crashed me immediately.

```python
Traceback (most recent call last):
  File "/home/quinten/tribler/tribler/TriblerGUI/event_request_manager.py", line 99, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Failure instance: Traceback: <type 'exceptions.UnicodeDecodeError'>: 'utf8' codec can't decode bytes in position 38-40: invalid continuation byte
/usr/lib/python2.7/dist-packages/twisted/web/resource.py:250:render
/home/quinten/tribler/tribler/Tribler/Core/Modules/restapi/torrentinfo_endpoint.py:122:render_GET
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:317:addCallback
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:306:addCallbacks
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:588:_runCallbacks
/home/quinten/tribler/tribler/Tribler/Core/Modules/restapi/torrentinfo_endpoint.py:71:on_got_metainfo
/usr/lib/python2.7/json/__init__.py:243:dumps
/usr/lib/python2.7/json/encoder.py:207:encode
/usr/lib/python2.7/json/encoder.py:270:iterencode
]
```

**Comment by devos50** [comment]
Classic Unicode error, should be easy to fix.

Unfortunately, I don't think this is the notorious GUI freeze bug but it's still a bug.

Feel free to fix it if you want, else I can fix it this afternoon.

**Comment by qstokkink** [comment]
@devos50 Am I understanding this code correctly:

1. [A `json.dumps` with `ensure_ascii=True` is being performed on a dict outputted from `fix_unicode_dict()`](https://github.com/Tribler/tribler/blob/next/Tribler/Core/Modules/restapi/torrentinfo_endpoint.py#L71).
2. [`fix_unicode_dict()` only removes invalid unicode characters, it does not make sure all characters are in ASCII "space"](https://github.com/Tribler/tribler/blob/next/Tribler/Core/Modules/restapi/util.py#L162).

From my point of view, anything using `fix_unicode_dict()` with `json.dumps` should be crashing continuously ( ➡️ is this being used anywhere else?). Adding `ensure_ascii=False` to the `json.dumps` will fix the dumping (`json.load` handles this output without any extra flags).

Is this solution consistent with the rest of the code? (The other solution would be to base64 encode/decode everything)

**Comment by devos50** [comment]
@loadletter @qstokkink it doesn't throw an error on Mac but as @loadletter already implied, the core jumps to 100% CPU utilization. I will investigate this freezing behavior first since it might has something to do with the notorious GUI freeze.

**Comment by qstokkink** [comment]
Small update, the stable cross-platform way to load and dump json seems to be:

```python

serialized = json.dumps(my_object, ensure_ascii=False)
json.loads(serialized, encoding='latin_1') # Python's name for ISO-8859
```
