### ISSUE TITLE
Make a possibility to add multiple torrent files at once.

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2945]
Make a possibility to add multiple torrent files at once, as [requested by user97](https://forum.tribler.org/t/tribler-7-release-candidate-2-please-test)

**Comment by Thomasedv** [comment]
Pardon for asking, isn't this already working in current Tribler versions? Unless i am mistaking what it means to add multiple files. We can add multiple .torrents files at once, or even a whole directory. You can also run multiple files manually by clicking and have them appear one after another in Tribler, and all you need to do is press download on each of them. The only different option is magnet link/url, which doesn't really have any good or practical way to add multiple ones at the same time as far as i can see. 

I haven't used release candidate 2 yet, but it's working like that for me on Windows 10, on an earlier version of Tribler. (possibly release candidate 1) And this was supposedly added in #2744 a long time ago, at least selecting multiple files from a folder, and adding them.

**Comment by devos50** [comment]
This is already working as far as I'm aware. Please reopen this issue if I'm mistaken.
