### ISSUE TITLE
Multiple DHT Response messages in Hidden Tunnel Community

### ISSUE THREAD

**Issue by Captain-Coder** [Tribler/tribler#2950]
hidden_community.py:308 (dht_callback) can (and in gumby does) get fired multiple times, the final time with an empty (or None) list of peers. This causes multiple dht-response messages to be tunneled back. The first one is handled fine, but the further messages will not have a corresponding dht-request outstanding in the communities request cache.

This is difficult to fix since there is no idea of when a lookup might be done. And batching it runs a real risk of taking longer than the request timeout (which could be set higher for a dht-request). A minimalistic fix/workaround is to change line 340 to a get instead of a pop and rely on the request cache to expire the item eventually.

**Comment by Captain-Coder** [comment]
I since found that this is intended behaviour. The pymdht runs the callback with 0 results after it is done with the lookup. It is also  possible that it will run the callback multiple times with multiple results (and then end with one invokation of 0 results). This generates multiple dht-response messages back to the requester. So indeed the best fix is to .get() instead of .pop() the dht request cache.

Possebly .pop() it when it has 0 results, since that will be the last message. But that does not account for out of order delivery of dispersy messages.

**Comment by devos50** [comment]
@egbertbouman is this issue still relevant if your DHT community is used?

**Comment by egbertbouman** [comment]
@devos50 Nope, the DHTCommunity will only call the callback once (using a deferred).
