### ISSUE TITLE
Proper handling of torrent when streaming and afterwards.

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#2957]
##### Tribler version/branch+revision: #####
Release candidate 1. 

Currently, when streaming a file, Tribler set that file to included, and uses sequential downloads (if past issues are still correct) All other files in the torrent are set to "not included". 

This is multi-part, as the things about to be mentioned are a bit connected. (Can make multiple issues if needed)

1. Tribler should be able to exit streaming mode. (I believe i saw this once before, but i couldn't find the issues with some lazy searching.)

2. Tribler should restore the included files to how it was as you started to stream after  you are done. Currently, you end up with a completed torrent with only one file done.  There are multiple ways to possibly handles this:

- Simply save the "included or not" before going to the streaming state,, and restore it when streaming is stopped. (On potential crash, it won't be restored unless it's saved to a location though and Tibler has a way to do it, which seems like a big extra hassle to deal with..)

- (Best in my opinion) Make the streaming state, (when only one file is included, all others not) a memory only thing, so that once streaming stops or Tribler closes, and then start again, it will read the torrent data as it was prior to streaming, and continue right off where it was (apart from the fact that more of the torrent is downloaded now.) Now, no proper way to stop streaming and restore info to prior based on the torrent. 

3. Make it so that once the streaming file is completely downloaded, let Tribler continue on files that where included prior to streaming. It's bad that it stops a download, making the user wait for the next video in the list longer, because instead of downloading, Tribler stops the torrent. And you can't start it until you stop streaming for that torrent(so say, you finish watching the episode in a series). This happens according to what was included, or potentially selected as next one up by the user, so ensure the right one is downloaded. (If not, go alphabetically? Series are usually named so that this would work.)  This would probably significantly reduce wait time for user, between watching multiple videos in a torrent. Of course, mileage varies depending on download speeds.

There are other issues mentioning sequential downloads of files(that aren't streaming) and priority of them, so i won't add this here, but mention that this might be worth implementing at the same time, as the system is generally working around the same things. Could also save a lot of hassle later on if the interest came up later after some of this was implemented.

**Comment by devos50** [comment]
Thank you for your helpful suggestions! We will take a look at them after the Tribler 7 release.

**Comment by emarsk** [comment]
The streaming "feature" is the worst aspect of Tribler. I just want to download my torrents and this streaming thing is disruptive and confusing. I'd like an option to disable the video player and the streaming feature altogether.

Tribler brings very nice concepts, but its usability is overall terrible and this issue is a major example.

**Comment by devos50** [comment]
@emarsk we are aware of the issues with the video player. In our upcoming release (7.5), we have refactored the entire channel mechanism and therefore were not able to address this issue yet. We will consider solving this issue in our 7.6 release and aim to give this issue more attention.

**Comment by hbiyik** [comment]
All of those are fixed in

https://github.com/Tribler/tribler/pull/5301
