### ISSUE TITLE
frequently seen strange logging information about "timeline" in console while running tribler

### ISSUE THREAD

**Issue by YourDaddyIsHere** [Tribler/tribler#2959]
##### Operating system and version: #####
Ubuntu 16.04

##### Relevant log file output: #####

The logging information is like: 
WARNING:Timeline:FAIL time:6 user:24375 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:24378 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:24377 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:24376 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:24379 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:17222 -> permit^channel (no authorization)

it seems that my global_time in timeline are too small (only six, compared with that of other users) so I would see all incoming message as a "end of time" attack so I would simply drop almost all useful reply from other users (as a consequence, I can't download even a single byte) from other user.

And it seems that my global_time doesn't grow at all , it is always 6.
I don't know is that a bug or is there something wrong with my enviroment.

Just report it.

**Comment by MaChengxin** [comment]
Did you directly observed this log in the terminal? What is the log file you mentioned in the comment?
Are you running some tasks with Tribler?

**Comment by devos50** [comment]
I think this is due to old clients sending messages to newer clients. It's not something critical and the message is just dropped without being processed. We should probably lower the logging level of this warning.

**Comment by devos50** [comment]
I don't think this issue is relevant anymore since Dispersy is end-of-life. I will close this one.
