### ISSUE TITLE
Tribler home screen allows you to highlight invisible rectangles

### ISSUE THREAD

**Issue by vandenheuvel** [Tribler/tribler#2960]
Arch Linux, cf60d11468b5d8e80c84780fe632d7cc5ada8e19

By clicking and dragging I was able to highlight invisible rectangles.
![screenshot from 2017-05-19 18-40-58](https://cloud.githubusercontent.com/assets/20440137/26257994/49515f92-3cb2-11e7-81a9-8ed663cd8f50.png)
![screenshot from 2017-05-19 18-40-38](https://cloud.githubusercontent.com/assets/20440137/26258002/4d6cc35a-3cb2-11e7-93a2-935d149995b1.png)
![screenshot from 2017-05-19 18-41-16](https://cloud.githubusercontent.com/assets/20440137/26258008/5337a6e2-3cb2-11e7-95d6-39a74cba3cc7.png)

Once I selected the first, I could highlight more of them by clicking. Resizing the screen was possible. Clicking in the search bar let the highlighted squares disappear. After that, a normal click let me highlight a square again. My state directory was empty when this bug occurred.

**Comment by qstokkink** [comment]
You can also do this in Windows. The selection box then consists of a dotted line instead of a blue rectangle.

**Comment by ichorid** [comment]
The home screen should be replaced by the "new arrivals feed" screen in #5015, so no point in fixing this one.
