### ISSUE TITLE
GUI crash when pressing the new star button

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2961]
##### Tribler version/branch+revision: #####

devel cf60d11468b5d8e80c84780fe632d7cc5ada8e19

##### Operating system and version: #####

linux

##### Steps to reproduce the behavior: #####

1. Start Tribler Core
2. Start Tribler GUI
3. Press the new star button

##### Expected behavior: #####

It shows something

##### Actual behavior: #####

GUI crashes and proposes to send a report

##### Relevant log file output: #####

```
  File "/home/tribler/tribler/TriblerGUI/widgets/trustpage.py", line 109, in received_multichain_blocks
    self.plot_absolute_values()
  File "/home/tribler/tribler/TriblerGUI/widgets/trustpage.py", line 119, in plot_absolute_values
    plot_data[1].append(datetime.datetime.strptime(block["insert_time"], "%Y-%m-%d %H:%M:%S"))
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '323031372d30352d32312031363a31383a3337' does not match format '%Y-%m-%d %H:%M:%S'
```

@devos50

**Comment by devos50** [comment]
This issue has been fixed already.
