### ISSUE TITLE
Unsupported Windows version

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#2962]
##### Expected behavior: #####
No warning message
##### Actual behavior: #####
![afbeelding](https://cloud.githubusercontent.com/assets/1146496/26370254/885df400-3ff7-11e7-8e1f-e87ef5918944.png)

##### Steps to reproduce the behavior: #####
Install Tribler 7.0 RC2

**Comment by qstokkink** [comment]
This is related to #2872 . Once we get our signing tool working again, this will be fixed (which _should_ be before the official 7.0 release).

**Comment by devos50** [comment]
Since it's related to #2872 I will close this issue. We will try to fix this before the Tribler 7 release.
