### ISSUE TITLE
Error on adding torrent. decode() 

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#2967]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
RC-2 2
##### Operating system and version: #####
Windows 10

##### Expected behavior: #####
Torrent adds normally.

##### Actual behavior: #####
After selecting download location, i get the message:
![image](https://cloud.githubusercontent.com/assets/1584461/26745915/31b76cdc-47ed-11e7-890e-929b17317945.png)

Torrent contains lots of weirdly named files, possibly due to them being another language. (I think japanese, but that's not the characters that show in Tribler.) 

##### Steps to reproduce the behavior: #####
Add torrent(presumably with Japanese characters), select where to download, and press add. 

No log output.

**Comment by devos50** [comment]
We had some issues in the past with more exotic torrents. Are you able to provide us the faulty torrent so we can debug this (if you rather not expose it on the internet, you can can also send it to me by email if you wish)?

**Comment by devos50** [comment]
@Thomasedv thank you! I received the torrent and verified that I get the same error when trying to add it to the downloads. In addition, the characters in the torrent info field seems to be off.
