### ISSUE TITLE
Download state in GUI not stable upon add/remove torrent

### ISSUE THREAD

**Issue by VincentKetelaars** [Tribler/tribler#297]
Version 6.2.0

MyChannel allows you to add torrents your are currently downloading/seeding. Later you can remove them again. Both of these actions tend to take several seconds to complete, i.e. to be visualized in the GUI. It would greatly improve user experience if this was reduced to no waiting at all.

Removing torrents can only be done one at a time or all together. The obvious gap is several at once. This could be solved by allowing multiple torrents to be selected.

Adding torrents can also be done only one at a time, although it less cumbersome than removing them. A small dialog which allows selecting several would be a nice improvement.

**Comment by qstokkink** [comment]
Managing a lot of downloads is a pain if they take several seconds to have some operation complete. Since credit mining will bring a lot of downloads, I'm moving this up.

**Comment by synctext** [comment]
Closing this ticket. Long live Gigachannels..

**Comment by qstokkink** [comment]
This issue is actually about the time it takes between clicking stop in the GUI and the GUI updating the status on a **download** and **not on a channel**. As such, it is not resolved.

**Comment by qstokkink** [comment]
I have updated the title of this issue to reflect the open problem.
