### ISSUE TITLE
[Question] What is the fastest way to shutdown the reactor?

### ISSUE THREAD

**Issue by hbiyik** [Tribler/tribler#2977]
If session.shutdown() sequence takes more than 5 seconds to complete, my implementation will face problems service-wise (basically kodi will lock-up, and need to be terminated from task manager).

Sometimes, torrentchecker class, sometimes downloads, sometimes dispersy takes too mcuh time to shutdown, what is fastest way to shutdown the session reactor, graceful enough to launch as-is on next launch. May be some extra-time can be win by terminating the sockets directly for the peer connections, and let the other ends to time out.

Any suggestions would be helpfull.

**Comment by qstokkink** [comment]
I know the fastest way is [`reactor.crash()`](http://twistedmatrix.com/documents/current/api/twisted.internet.base.ReactorBase.html#crash), I wouldn't quite call it graceful though.

**Comment by hbiyik** [comment]
:) still wont do the trick though with reactor threads running all around blocking the IO, i think i found a way to tell kodi stop being stubborn and increased the shutdown timer more than 5 seconds. (tesing in various forms)

But for optimization may be it can be considered for time consuming active tasks should also monitor shutdown sequence even if the task is already fired.

ie: torrentchecker, health check for all trackers including dht may take time up to 15-20 secs, if shutdown request is done while this task is being executed
 shutdown will wait for the task to finish.

**Comment by devos50** [comment]
@hbiyik I agree but we are waiting until the request is done for a reason (which I can't remember anymore unfortunately). I believe it had something to do with the DNS resolution task which could not be cancelled. I would rather leave it like this for the Tribler 7 release but we might consider testing what happens when we just terminate the connection and shutdown immediately.
