### ISSUE TITLE
Generic transaction blocks for the MultiChain community

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2980]
I would like to propose generic transaction blocks for the MultiChain community. I need this community for the market to store transactions between traders and the current format of the Multichain is not suitable for this purpose. This means I have to copy the whole community code and make my modifications, leading to a cluttered PR and unnecessary code in the repository. I'm positive that this will happen more often in the future when people use the community.

I propose to slightly modify the structure of multichain blocks to allow generic `tx` blocks. First, I think we should get rid of the hard-coded public key/signature/struct lengths (see the first few lines of `block.py`) and use the `encode()` and `decode()` functions so we can have fields of dynamic lengths. Next, I think we should combine the `up`, `down`, `total_up` and `total_down` fields into a generic string type. This requires some modifications to the database and breaks backwards compatibility (which is not a huge deal since we recently merged true halves, breaking backwards compatibility anyway). Note that these changes also require us to split the validator.

The final design allows developers to create a subclass of `MultiChainCommunity` and design their own transactions using method overriding. We should think a bit further on how to design this in particular. For the Tribler MultiChain (used to account up- and downloads) we can make a `TriblerMultiChainCommunity` subclass.

@qstokkink could you give some comments/pointers on my proposal? I would like to work on this during the weekend (unless you want to do it :) since it has quite some impact on the outstanding market PR. Thanks!

**Comment by qstokkink** [comment]
I agree with `up`, `down`, `total_up` and `total_down` being poured into some generic string/binary blob and having some `encode()` and `decode()` function.
But, why do you want to get rid of the public key and signature lengths as well? They are very nice for fast parsing of a message.

So right now we have:
`"! Q Q Q Q {0}s I {0}s I {1}s {2}s".format(PK_LENGTH, HASH_LENGTH, SIG_LENGTH)`
Corresponding to:
self.up, self.down, self.total_up, self.total_down, self.public_key, self.sequence_number, self.link_public_key, self.link_sequence_number, self.previous_hash, self.signature if signature else EMPTY_SIG)

I'd change this to:
`"! {0}s I {0}s I {1}s {2}s Q".format(PK_LENGTH, HASH_LENGTH, SIG_LENGTH)`
Corresponding to:
self.public_key, self.sequence_number, self.link_public_key, self.link_sequence_number, self.previous_hash, self.signature if signature else EMPTY_SIG), len(blob)
And then append the blob to the packet data when encoding.

Also, I have a better name than `TriblerMultiChainCommunity`: `TrustChain` 😃

**Comment by devos50** [comment]
@qstokkink thanks for the feedback. Your approach sounds fine. I quite like the `encode` and `decode` functions since I'm using them in the market community but keeping them for performance is fine.

Naming it `TrustChain` is an interesting one. In that case, our technology is referred to as `MultiChain` while `TrustChain` denotes our Tribler-specific community. I would rather have it the other way around where `TrustChain` describes our technology (this is also consistent with the journal submission). This means we still need a name for the subclass.

**Comment by qstokkink** [comment]
@devos50 Just to be clear: I'm not suggesting to remove the `encode` and `decode`, but to only use them for decoding the binary blob/generic string.

I guess this would indeed be a good time to rename the base to `TrustChain`. As for the subclass.. `BandwidthChain`, `Tit4TatChain`, `RelayChain`, `TrustTorChain`, `ShareChain`, `BTChain`, `HelpChain`, `AidChain` or even just `TriblerChain`? `TriblerMultiChain` is a bit underwhelming.
