### ISSUE TITLE
Lagging tunnels confuse LibTorrentDownloadImpl after download remove

### ISSUE THREAD

**Issue by Captain-Coder** [Tribler/tribler#2984]
Imagine the following sequence of events:
1. add download A with 2 hops
2. tunnels get built for download A.
3. remove download A.
4. add download B with 2 hops

At this pont the tunnels that where built for A will still be around. This causes TunnelCommunity.tunnels_ready to report that all is fine. In turn this causes LibTorrentDownloadImpl.can_create_engine_wrapper to _not_ call TunnelCommunity.build_tunnels. Which is bad, since it is the job of build_tunnels to keep track of the current number of downloads. Thus the end result is that the TunnelCommunity thinks no tunnels are needed and the download stalls. (Without much indication as to why)

I tried some easy fixes but my attempts all broke some other aspect of LibTorrentDownloadImpl.can_create_engine_wrapper. This seems like fragile code in need of a redesign/cleanup. I don't absolutely need this to work for my experiments, so I might not (probable) fix this.

**Comment by synctext** [comment]
The vulnerable period for this bug is 5 minutes after all anon download complete. New anon downloads get messed up. This needs attention at some point.

**Comment by devos50** [comment]
It seems that this has been fixed already: https://github.com/Tribler/py-ipv8/blob/96e4a7a8d3cf16268aeddfadcfc93ecf73a56799/ipv8/messaging/anonymization/community.py#L224. Therefore, I will close this issue. Please reopen it if it's not fixed for some reason.
