### ISSUE TITLE
Use standard locations for Tribler directories and files

### ISSUE THREAD

**Issue by mihaic** [Tribler/tribler#299]
Instead of [user home dir]/.Tribler and [desktop]/TriblerDownloads, use standard locations.

For Linux, use Freedesktop.org standards, perhaps through [PyXDG](http://freedesktop.org/wiki/Software/pyxdg/):
http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
http://www.freedesktop.org/wiki/Software/xdg-user-dirs/

For Mac OS, I found this after a quick search:
https://developer.apple.com/library/mac/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html

For Windows, this looks like a good place to start:
http://msdn.microsoft.com/en-us/library/windows/apps/hh967755.aspx

**Comment by Pathemeous** [comment]
Also add an uninstall script for Mac. Couldn't find it myself.

**Comment by whirm** [comment]
@Pathemeous You just have to throw the app bundle to the trash.

**Comment by Pathemeous** [comment]
Friend of mine did that, the .Tribler in the home directory remained after the install.

**Comment by whirm** [comment]
Ah, I see what you mean. Do you really need a script to remove a directory?

**Comment by Pathemeous** [comment]
Not so much for the action, but something that removes it automatically when the application is uninstalled would be nice.

**Comment by whirm** [comment]
Can you trigger scripts when an app bundle gets deleted on OSX?

**Comment by devos50** [comment]
I don't think it is possible to detect when an app got deleted and perform actions after that. I also think it's not a big problem since when I execute `ls -la ~` , I see many left-over files from programs I've already uninstalled.

**Comment by qstokkink** [comment]
After 11 years, some things changed in our file management. Our files are now in the appropriate locations, and user data files can now be removed through the `Settings / Versions` tab (to remedy the lack of an "uninstall" script on Mac). We will make no further changes to the locations or uninstall scripts and I'll close this issue.
