### ISSUE TITLE
FTBFS : dh_install: Cannot find (any matches for) "Tribler/schema_sdb_v*.sql" (tried in "." and "debian/tmp")

### ISSUE THREAD

**Issue by themusicgod1** [Tribler/tribler#2991]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

next b5ac1be98

##### Operating system and version: #####

Ubuntu 17.04 zesty

##### Expected behavior: #####

build successfully with debuild -us -uc -b

##### Actual behavior: #####
running install_scripts
   debian/rules override_dh_install
make[1]: Entering directory '/home/themusicgod1/tribler/git/tribler'
dh_install --exclude=.git
dh_install: Cannot find (any matches for) "Tribler/schema_sdb_v*.sql" (tried in "." and "debian/tmp")
dh_install: tribler missing files: Tribler/schema_sdb_v*.sql
dh_install: missing files, aborting
debian/rules:24: recipe for target 'override_dh_install' failed
make[1]: *** [override_dh_install] Error 255
make[1]: Leaving directory '/home/themusicgod1/tribler/git/tribler'
debian/rules:18: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc -b failed

##### Steps to reproduce the behavior: #####
debuild -us -uc -b

##### Relevant log file output: #####
na failed while building

**Comment by themusicgod1** [comment]
bizarre.  I had this being reproduced on 2 computers with different setups and now i can't reproduce this.

**Comment by qstokkink** [comment]
@themusicgod1 Thanks for testing again, we also couldn't reproduce this on `next`. However, this is a real (reproducible) issue on `devel` (which will become the 7.1 release), therefore I will reopen this.

**Comment by NoNameForMee** [comment]
It looks like this is caused by commit https://github.com/Tribler/tribler/commit/46f5abde70b44c84bfa8310febbf1ab170e982f0#diff-aec7762ce08d9fb46adcc0b1414ab6b9 which changed the location of the .sql file.

I suspect it would simply be solved by changing https://github.com/Tribler/tribler/blob/devel/debian/tribler.install#L3 to reflect the new location `Tribler/Core/CacheDB/` instead of the old `Tribler/`
