### ISSUE TITLE
Sonarcube is not updating automatically

### ISSUE THREAD

**Issue by MaxVanDeursen** [Tribler/tribler#2997]
As shown on [this sonarcube link on the Tribler Jenkins server](http://jenkins.tribler.org:9000/overview?id=2846), the last time Sonarcube scanner has updated is at the 23rd of March 2017. Shouldn't this scanner be ran each time a commit is pushed into an open PR?

**Comment by devos50** [comment]
It has been fixed, see http://jenkins.tribler.org:9000/overview?id=2846 and https://jenkins.tribler.org/job/GH_Tribler_PR_sonarqube_check/2577/console

Apparently, the Sonarqube scanner was not hooked up and not executed for some weird reason. I've extended the Sonarqube scanner so it also automatically fetches the status of the quality gate and displays it in the console log of the Jenkins job.
