### ISSUE TITLE
website tribler.org also in our black-theme using bootstrap framework of blockchain-lab.org

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2998]
Requires maximum of 1 afternoon of polish.
- same style as 7.0
- screenshots
- general polish

![image](https://user-images.githubusercontent.com/325224/27191758-1a6f1456-51f9-11e7-9e2c-72acd79c3a98.png)

**Comment by qstokkink** [comment]
Just changing the colors already helps a lot:
![tribler org_recolor](https://user-images.githubusercontent.com/3630389/27336071-c6010ac6-55ce-11e7-8b92-33f91c90eda5.png)
