### ISSUE TITLE
Crash on key error

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#3001]
- [x] I have read CONTRIBUTING.rst

- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Tribler rc2-13

##### Operating system and version: #####
Windows 10

##### Expected behavior: #####
No crash
##### Actual behavior: #####

Crash on key error

##### Steps to reproduce the behavior: #####
Tribler was idle, no active downloads. Thing were seeding. 

##### Relevant log file output: #####
![image](https://user-images.githubusercontent.com/1584461/27259695-64117f00-5419-11e7-8fff-cc8e58793306.png)

**Comment by qstokkink** [comment]
Thanks for the report!

@devos50 I think the best way to solve this, is to create a wrapper around calls to `mapping[stream[index]]` in `encoding.py` which throws a `ValueError` if the key does not exist. Your thoughts?
