### ISSUE TITLE
IOError on launch. Tribler RC2-84

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#3008]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Tribler rc2-84 from Jenkins, Windows 64 bit version, build 404. 

##### Operating system and version: #####
Windows 10

##### Expected behavior: #####
Installation of Tribler and successful startup. 

##### Actual behavior: #####
Crash on startup, GUI stuck on loading gears. 

##### Steps to reproduce the behavior: #####
Install build, (previous build was rc2-13 ) Not a fresh install. 

##### Relevant log file output: #####
![image](https://user-images.githubusercontent.com/1584461/27407421-7b117478-56d8-11e7-84e5-9abcb0842fb6.png)

That file location to the folder Tribler is the install folder. However! Tribler is looking for a folder named Tribler, in my install directory, and there is none.

**Comment by Thomasedv** [comment]
Copied the folder named Tribler from the tribler_source folder, and got it to start up. However met with lots of extra error warnings in the GUIsee image below. Though not exactly sure if it should be considered an issue as this might be because of my attempted workaround. 

![image](https://user-images.githubusercontent.com/1584461/27407998-f996c544-56da-11e7-8143-6bd06e2e9e2c.png)

**Comment by qstokkink** [comment]
Thanks for the report, we will be stabilizing the `devel` (7.1) branch after the release of 7.0 (`next`).

**Comment by devos50** [comment]
@vandenheuvel @MaxVanDeursen do you have time to investigate and fix this issue?

**Comment by devos50** [comment]
Partially fixed by #3009

**Comment by vandenheuvel** [comment]
Probably, [this](https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Config/tribler_config.py#L20) line isn't doing what I would expect it to on that platform. Besides that, I currently have no time to investigate further.
