### ISSUE TITLE
WIP: tribler screenshots for new gui

### ISSUE THREAD

**Issue by mitchellolsthoorn** [Tribler/tribler#3010]
![27142730-461d7ade-512c-11e7-9faf-2a51e76ebc47](https://user-images.githubusercontent.com/1785526/27434376-d29f950a-5758-11e7-8471-698fada68cf9.PNG)
![27395330-b5621bce-56af-11e7-9ee8-60edb4b0e091](https://user-images.githubusercontent.com/1785526/27434379-dab780b8-5758-11e7-907c-5a172f6a0efb.png)
<img width="1280" alt="a2bc7c42-fd1a-11e6-9547-3d2646e5c04b" src="https://user-images.githubusercontent.com/1785526/27434378-dab67c04-5758-11e7-8c1d-8de4a57599fa.png">
![screenshot from 2017-06-22 13-43-03](https://user-images.githubusercontent.com/1785526/27434380-dab928be-5758-11e7-8a96-d2f10dfb37c8.png)
![screenshot from 2017-06-22 13-43-09](https://user-images.githubusercontent.com/1785526/27434381-dabb59fe-5758-11e7-9fe3-31c3914e878a.png)
![screenshot from 2017-06-22 13-43-36](https://user-images.githubusercontent.com/1785526/27434383-dabeaeec-5758-11e7-834a-7a290b6380fc.png)
![screenshot from 2017-06-22 13-44-25](https://user-images.githubusercontent.com/1785526/27434382-dabd2b9e-5758-11e7-8266-c43cc0fefaae.png)
![screenshot from 2017-06-22 13-45-17](https://user-images.githubusercontent.com/1785526/27434384-dac851f4-5758-11e7-861c-d9de511f1879.png)
![screenshot from 2017-06-22 13-46-32](https://user-images.githubusercontent.com/1785526/27434385-dac94906-5758-11e7-8b9d-01c66e4634d2.png)
![screenshot from 2017-06-22 13-47-21](https://user-images.githubusercontent.com/1785526/27434389-dad3cd04-5758-11e7-94bf-5ab44735ea5e.png)
![screenshot from 2017-06-22 13-47-54](https://user-images.githubusercontent.com/1785526/27434386-dacf38c0-5758-11e7-9887-bd09efc6f4cb.png)
![screenshot from 2017-06-22 13-51-49](https://user-images.githubusercontent.com/1785526/27434387-dad2d71e-5758-11e7-8e2d-7b5112775668.png)
![screenshot from 2017-06-22 13-52-11](https://user-images.githubusercontent.com/1785526/27434388-dad31f8a-5758-11e7-9c35-f439aad729e9.png)
![screenshot from 2017-06-22 13-53-20](https://user-images.githubusercontent.com/1785526/27434390-dada7e74-5758-11e7-8676-535094c10f0d.png)
![screenshot from 2017-06-22 13-54-49](https://user-images.githubusercontent.com/1785526/27434391-dadaf2fa-5758-11e7-93df-60d5a20b54ca.png)
![screenshot from 2017-06-22 13-54-57](https://user-images.githubusercontent.com/1785526/27434392-dae187e6-5758-11e7-8722-ff6f8d8a4139.png)
![screenshot from 2017-06-22 13-55-03](https://user-images.githubusercontent.com/1785526/27434395-daea3f12-5758-11e7-94f0-20ea6a3acff1.png)
![screenshot from 2017-06-22 13-55-43](https://user-images.githubusercontent.com/1785526/27434393-dae8b746-5758-11e7-8c0f-f514f95ab532.png)
![screenshot from 2017-06-22 13-56-21](https://user-images.githubusercontent.com/1785526/27434394-dae9d91e-5758-11e7-856d-0965a2a17898.png)
![screenshot from 2017-06-22 13-58-57](https://user-images.githubusercontent.com/1785526/27434397-daef863e-5758-11e7-80f0-6ba28d7a21d9.png)
![screenshot from 2017-06-22 13-59-15](https://user-images.githubusercontent.com/1785526/27434396-daef1a32-5758-11e7-91b1-03b7e1f584f7.png)
![screenshot from 2017-06-22 13-59-25](https://user-images.githubusercontent.com/1785526/27434398-daf4bfc8-5758-11e7-90e8-183ff5f369f8.png)
![screenshot from 2017-06-22 13-59-35](https://user-images.githubusercontent.com/1785526/27434399-dafdc744-5758-11e7-8ea6-eb823421e24b.png)

**Comment by mitchellolsthoorn** [comment]
@qstokkink

**Comment by qstokkink** [comment]
@mitchellolsthoorn thanks, it's done: https://github.com/Tribler/tribler.github.com/pull/28

**Comment by synctext** [comment]
![tribler_trust_network_browser_2017_small](https://user-images.githubusercontent.com/325224/35043085-8260c4ba-fb8b-11e7-9225-2a01661df25b.PNG)
