### ISSUE TITLE
Error with undecorated Tribler window and monocrome icon

### ISSUE THREAD

**Issue by pimlie** [Tribler/tribler#3011]
A minor issue, but if you have an undecorated Tribler window and tick the 'Use monochrome icon' option, then Tribler will crash because it cant find any icon to change. Its correct that it cant find any because the window bar doesnt exists.

See [my](https://github.com/pimlie/docker-tribler-vnc) docker container for an use case.

```
Traceback (most recent call last):
  File "/opt/tribler/TriblerGUI/widgets/settingspage.py", line 38, in on_use_monochrome_icon_checkbox_changed
    self.window().update_tray_icon(use_monochrome_icon)
  File "/opt/tribler/TriblerGUI/tribler_window.py", line 208, in update_tray_icon
    self.tray_icon.setIcon(QIcon(QPixmap(get_image_path('monochrome_tribler.png'))))
AttributeError: 'TriblerWindow' object has no attribute 'tray_icon'
```

**Comment by qstokkink** [comment]
Thanks for the report, it seems `QSystemTrayIcon.isSystemTrayAvailable()` is not being checked in `update_tray_icon()` on the `devel` branch. This should be an easy fix.

**Comment by pimlie** [comment]
Follow-up question, why exactly is the monochrome setting stored in `$HOME/.config/TUDelft/Tribler.conf` and not like most of the other settings in `$HOME/.Tribler/triblerd.conf`? 

It took me a while to find this location so I could manually remove the monochrome setting :)
