### ISSUE TITLE
Tribler7: firewall recommendations

### ISSUE THREAD

**Issue by pimlie** [Tribler/tribler#3015]
.

**Comment by pimlie** [comment]
Btw, it looks like its easier to just disable upnp in my firewall. With upnp disabled, it looks like connections are initiated over port `7760` but with upnp enabled tribler wants to connect over those dynamically assigned ports which are still blocked in my filter firewall.

**Comment by hThoreau** [comment]
I would also like to have an answer for this, as I use restrictive Firewall rules as well. I setup "Settings > Connection > Firewall-status > Current port" to "51413", I also forwarded this port on my router. At the same tab, alongside "Status", it reads "Your connection is working properly.", but I'm still unable to make anonymous downloads - they get stuck at "building circuits".
