### ISSUE TITLE
Memory leak in Tribler GUI

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#3016]
##### Tribler version/branch+revision: #####

devel 6a9058e32d7ecdc766d73982f465c185c65d8aae
It wasn't so before.

##### Operating system and version: #####

Linux

##### Steps to reproduce the behavior: #####

1. Start Tribler Core
2. Start Tribler GUI
3. Show downloads page
4. Wait

##### Expected behavior: #####

Memory consumption depends only on number of downloads, searched content and so on.

##### Actual behavior: #####

Memory consumption depends also on the time GUI was running

`  6.8 GiB +  35.3 MiB =   6.9 GiB	python2.7`

Stopping the GUI without stopping Core reclaimed most of the memory.

**Comment by devos50** [comment]
This is most likely fixed. Please reopen this issue if it is not fixed for you.
