### ISSUE TITLE
Broken encoding while adding a torrent from file + no included files afterwards.

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#3017]
##### Tribler version/branch+revision: #####

devel 6a9058e32d7ecdc766d73982f465c185c65d8aae

##### Operating system and version: #####

Linux

##### Steps to reproduce the behavior: #####

1. Start Tribler Core
2. Start Tribler GUI
3. Remove old version of a torrent (without data)
4. Move away (rename) the respective directory on filesystem
5. Add torrent from file
6. Observe **broken encoding** in filenames. Guess anyway and mark included files.
7. Accept the download.

##### Expected behavior: #####

It begins downloading the selected files, showing initially "Downloading 0%"

##### Actual behavior: #####

The torrent is visible in "Seeding 100%" state. For all files "included: no".

Manually marking files as included again in "Files" pane (filenames encoding are OK there) makes it download them like usual, showing correct status.

P.S. So it actually internally *does* support all excluded files, although GUI shows it strangly.

**Comment by ichorid** [comment]
Related to  #3418

**Comment by ichorid** [comment]
Merging it into #3418
