### ISSUE TITLE
Add scipy as dependency for the market

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3022]
Apparently, scipy is needed as dependency for the market so the docs should be updated.

**Comment by qstokkink** [comment]
I needed the following steps to make it work on a Windows 32-bit system:

1. DL numpy+mkl .whl from http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy
2. `pip install numpy-1.11.3+mkl-cp27-cp27m-win32.whl` 
3. DL scipy .whl from http://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy
4. `pip install scipy-0.19.1-cp27-cp27m-win32.whl`
