### ISSUE TITLE
Import error in btc_wallet on Linux

### ISSUE THREAD

**Issue by vandenheuvel** [Tribler/tribler#3027]
Latest devel, 72b7d4fb425be36581557796179737be76578448. Arch Linux.

When starting Tribler an `ImportError` is raised in `btc_wallet.py`, [line 16](https://github.com/Tribler/tribler/blob/devel/Tribler/community/market/wallet/btc_wallet.py#L16): `ImportError: No module named lib`

**Comment by devos50** [comment]
Are you sure you have the `electrum` submodule?

```
git submodule init
git submodule update
```

**Comment by vandenheuvel** [comment]
That solved it, thanks.
