### ISSUE TITLE
Creating a wallet without a keyring

### ISSUE THREAD

**Issue by vandenheuvel** [Tribler/tribler#3028]
Latest devel, cddfbad065c9a1425e3889f2d45391d15da8480b.

When creating a bitcoin wallet without a keyring, a new one is automatically created. I'm being asked to input a password for this new keyring on the command line while Tribler just hangs in the `creating...` window. This is not intuitive and running Tribler without the command line would probably not end well.

**Comment by sum01** [comment]
Just built on Arch, using KDE/Plasma as my DE, and it stalled waiting on `Kwallet`, which I had previously disabled as I never used it. Re-enabling it and it correctly opened Kwallet, let me sign with my key, and finally opened.

**Comment by devos50** [comment]
We removed the Electrum wallet in Tribler 7.1, including the keyring mechanism.
