### ISSUE TITLE
Stuck on downloading - Linux (devel)

### ISSUE THREAD

**Issue by sum01** [Tribler/tribler#3029]
EDIT: Why is this labelled enhancement and not bug?

- [x] I have read CONTRIBUTING.rst

##### Tribler version/branch+revision: #####
cddfbad065c9a1425e3889f2d45391d15da8480b
##### Operating system and version: #####
Linux `4.11.6-3-ARCH`
##### Steps to reproduce the behavior: #####
Installed via [my custom PKGBUILD](https://github.com/sum01/aur-packages/blob/master/tribler-git/PKGBUILD) 
```
cd /usr/share/tribler
./tribler.sh
```
Then added [Ubuntu 17.04 torrent](http://releases.ubuntu.com/17.04/ubuntu-17.04-desktop-amd64.iso.torrent) to test (after enabling 2 hops).
##### Expected behavior: #####
The torrent downloads anonymously via 2 hops.
##### Actual behavior: #####
It pulls meta data and builds circuits, then hangs at 0% on Downloading.
##### Relevant log file output: #####
Mostly spam of
`WARNING:Timeline:FAIL time:6 user:11262 -> permit^channel (no authorization)` but with various times and user nums.

Between spam of the timeline fails it also shows lots of `WARNING:AllChannelCommunity:drop a 123 byte packet duplicate message by member^global_time (1) [dispersy-undo-own] from {LOCAL_IPHERE IPHERE}` 

And also some `WARNING:AllChannelCommunity:drop a 123 byte packet duplicate message by member^global_time (1) [dispersy-undo-own] from {LOCAL_IPHERE IPHERE}`

**Comment by qstokkink** [comment]
Did the torrent have UDP trackers?
Some torrents only have HTTP trackers, which we don't allow to avoid abuse of our anonymization network. Consequently, torrents with only HTTP trackers will need to use pure DHT, which can take a long time (and/or not start at all if other peers don't support/allow DHT).

**Comment by sum01** [comment]
Well it's the official Ubuntu torrent download. I've tried with both 17.04 and the 16 LTS, both get stuck on
> 0% Downloading

When I click trackers it shows DHT as working, but with 0 peers. In fact, it shows all the trackers as having 0 peers.
![tribler-error](https://user-images.githubusercontent.com/19376155/27747703-4795abb4-5d9a-11e7-9233-8d8e28e8e323.png)

**Comment by sum01** [comment]
I was about to close Tribler when I got this
```
Traceback (most recent call last):
  File "/usr/share/tribler/TriblerGUI/event_request_manager.py", line 123, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Failure instance: Traceback: <class 'networkx.exception.NetworkXError'>: pagerank_scipy: power iteration failed to converge in 100 iterations.
/usr/lib/python2.7/site-packages/twisted/internet/base.py:1243:run
/usr/lib/python2.7/site-packages/twisted/internet/base.py:1252:mainLoop
/usr/lib/python2.7/site-packages/twisted/internet/base.py:878:runUntilCurrent
/usr/lib/python2.7/site-packages/twisted/internet/task.py:239:__call__
--- <exception caught here> ---
/usr/lib/python2.7/site-packages/twisted/internet/defer.py:150:maybeDeferred
/usr/share/tribler/Tribler/community/market/community.py:1251:compute_reputation
/usr/share/tribler/Tribler/community/market/reputation/pagerank_manager.py:29:compute
/usr/lib/python2.7/site-packages/networkx/algorithms/link_analysis/pagerank_alg.py:472:pagerank_scipy
]
```

**Comment by vandenheuvel** [comment]
@sum01 This is a separate issue. Would you be so kind to create a separate issue ticket?

**Comment by sum01** [comment]
Tried `7.0.0-rc3` via the current [AUR pkgbuild](https://aur.archlinux.org/packages/tribler/) and it's basically the same issue, it gets stuck on retrieving metadata.

**Comment by devos50** [comment]
This torrent does not have any UDP trackers, therefore it will not bootstrap into the swarm. We plan on supporting TCP trackers but this is a lower-priority issue (#2681)

**Comment by sum01** [comment]
I have this happen with all torrents I've tried. Is there a torrent I can test to see if it works as intended?

**Comment by qstokkink** [comment]
You can check them in http://torrenteditor.com/ and see if the trackers start with `udp://` (as mentioned support for trackers starting with `http://` is not implemented).
