### ISSUE TITLE
Race condition when live-edge walker starts too early

### ISSUE THREAD

**Issue by vandenheuvel** [Tribler/tribler#3032]
Sometimes, on Windows 64, [this](https://jenkins.tribler.org/job/GH_Tribler_PR_tests_win64/4640/testReport/junit/Tribler.Test.Core.Modules.RestApi.test_trustchain_endpoint/TestTrustchainStatsEndpoint/test_get_blocks/) error is reported.

```
[Failure instance: Traceback: <type 'exceptions.AssertionError'>: Should not be called before open(...)
C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\dispersy\community.py:1212:start_walking
C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\dispersy\community.py:1175:switch_to_normal_walking
C:\Python27\lib\site-packages\twisted\internet\task.py:194:start
C:\Python27\lib\site-packages\twisted\internet\task.py:239:__call__
--- <exception caught here> ---
C:\Python27\lib\site-packages\twisted\internet\defer.py:149:maybeDeferred
C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\community\trustchain\community.py:403:take_step
C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\dispersy\endpoint.py:125:get_address
]
```

I think the `get_address` of `StandaloneEndpoint` was called before the `open` method was caused, triggering an assert.

Note that this happened on the `master` branch of my fork. I however suspect that this error isn't caused by our changes, but is caused by an existing race condition.

Update: The same error now also happened on my `remove_locks` branch, which has unrelated changes with the master branch, with respect to devel. See [this](https://jenkins.tribler.org/job/GH_Tribler_PR_tests_mac/4760/testReport/junit/Tribler.Test.Core.Modules.RestApi.test_trustchain_endpoint/TestTrustchainStatsEndpoint/test_get_blocks/?auto_refresh=false) log. Note that those tests are successful on Linux.

**Comment by qstokkink** [comment]
Hmm.. weird, it really shouldn't be walking before the Endpoint is open.

**Comment by devos50** [comment]
I haven't seen this error in a long time, closing this issue.
