### ISSUE TITLE
Latest Build don't run on Windows 10 >= build 16226

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3035]
- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Tribler_7.0.0-rc2-106-gec34872_x64
##### Operating system and version: #####
Windows 10 x64 build 16232
##### Steps to reproduce the behavior: #####
Start tribler
##### Expected behavior: #####
Normal start up
##### Actual behavior: #####
A few build ago Startup resulted in file not found E:\Program Files\Tribler\tribler\Tribler\Core\Config\config.spec. Appeared tribler_source was expected to be called tribler, so copied file to expected folder after creating it manually.
latest build do not give any arror, they just do not start, log screen is flashing and gone, no logfile to be found.

**Comment by qstokkink** [comment]
This should be fixed in newer builds.
