### ISSUE TITLE
Use https for sending reports

### ISSUE THREAD

**Issue by pimlie** [Tribler/tribler#3036]
I noticed that error reports are sent to a non-https [server](https://github.com/Tribler/tribler/blob/2e376f475a6b38ca20c2c31488a48c7095c1e09a/TriblerGUI/dialogs/feedbackdialog.py#L96). Any plans to eg add a letsencrypt certificate to that machine?

**Comment by qstokkink** [comment]
Good point. We should add this after the big 7.0 release imo.

**Comment by devos50** [comment]
Sentry is sending error reports over a HTTPS connection which resolves this issue 👍 

(@drew2a thanks for testing!)
