### ISSUE TITLE
Very high cpu load, running at ~100%

### ISSUE THREAD

**Issue by pimlie** [Tribler/tribler#3043]
- [X] I have read CONTRIBUTING.rst

- [X] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
$ git status
On branch next
Your branch is up-to-date with 'origin/next'.
nothing to commit, working directory clean

##### Operating system and version: #####
Ubuntu 16.04

Possible duplicate of #2444 and/or #2504, creating a new issue as those issues are talking about 5-10% cpu and for me its running at 100%. 

As mentioned before I am running tribler in a docker container and connect to it through vnc. I currently have 10 downloading torrents with a combined download//uploading speed of just ~5KB/s. So really not that much. A `ps aux` shows two python2.7 processes. The one with the higher id of the two is running at near 100% all the time for me (but does go down to 40% briefly). The other process is variating between 0 and 40% cpu. My monitoring software which uses a 5min interval shows at least 100% cpu usage continously.

See below for a 5min strace output.
```
# time strace -c -p 25488
strace: Process 25488 attached
strace: [ Process PID=25488 runs in x32 mode. ]
strace: [ Process PID=25488 runs in 64 bit mode. ]
^Cstrace: Process 25488 detached
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 88.55    0.126021           5     24487           select
  7.19    0.010234           0    153057     14502 futex
  2.81    0.004000         333        12           close
  0.99    0.001408           0     68876           sendto
  0.26    0.000363           0     44239     13310 recvfrom
  0.16    0.000230           0     32145           read
  0.02    0.000033           0      6404           write
  0.01    0.000013           0      1333           fstat
  0.01    0.000010           0     15742           lseek
  0.00    0.000000           0        10           open
  0.00    0.000000           0      2387           mmap
  0.00    0.000000           0      2380           munmap
  0.00    0.000000           0         2           socket
  0.00    0.000000           0         4         2 connect
  0.00    0.000000           0         2           shutdown
  0.00    0.000000           0        82           getsockname
  0.00    0.000000           0         4           getsockopt
  0.00    0.000000           0       730           fcntl
  0.00    0.000000           0         1           fdatasync
  0.00    0.000000           0     11094           epoll_ctl
  0.00    0.000000           0        12           getrandom
------ ----------- ----------- --------- --------- ----------------
100.00    0.142312                363003     27814 total

real	4m54.783s
user	0m0.492s
sys	0m4.796s
```

Because of the recvfrom errors, maybe related to #3015? Tribler log shows a lot of the following messages (on average logged every 2 seconds):
```
WARNING:SearchCommunity:message from <Candidate X.X.X.X:Y> cannot be found in the request cache, skipping it
```

**Comment by qstokkink** [comment]
I suspect this is due to our anonymity layer not being too happy about messages being dropped. Could you try disabling anonymity (temporarily)?

**Comment by pimlie** [comment]
Is there a 'one setting to rule them all' or should I disable it for each torrent manually? The GUI is by times also very sluggish, then it takes >10 secs for the context menu to appear after a right click etc.

**Comment by qstokkink** [comment]
@pimlie I'm sorry, I forgot we removed the anonymity on/off switch from the GUI: in the tribler config folder (`~/.Tribler/`) there should be a file called `triblerd.conf`. Under `[tunnel_community]` it should say `enabled = True`. If you change this setting to `enabled = False`, this will disable all of the anonymity logic.

**Comment by pimlie** [comment]
thanks, is there a way to confirm that this setting has been applied correctly? I restarted tribler, and after waiting for the re-checks to finish its still running at 100+%. Currently downloading at ca 5MB/s with 5 torrents.

```
# time strace -c -p 1913
strace: Process 1913 attached
strace: [ Process PID=1913 runs in x32 mode. ]
strace: [ Process PID=1913 runs in 64 bit mode. ]
^Cstrace: Process 1913 detached
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 98.49    7.379689         609     12117           select
  1.38    0.103264           1    109861     10904 futex
  0.11    0.008000         296        27           close
  0.01    0.000939           0     51144           read
  0.01    0.000558           0     12385           sendto
  0.00    0.000120           0      3226           fstat
  0.00    0.000087           0      6121           mmap
  0.00    0.000073           0       228           recvfrom
  0.00    0.000073           0     15159           epoll_ctl
  0.00    0.000065           0      6117           munmap
  0.00    0.000022           0     44038           lseek
  0.00    0.000000           0      1816           write
  0.00    0.000000           0        27           open
  0.00    0.000000           0         1           brk
  0.00    0.000000           0       228           getsockname
  0.00    0.000000           0       862           fcntl
  0.00    0.000000           0        34           getrandom
------ ----------- ----------- --------- --------- ----------------
100.00    7.492890                263391     10904 total

real	13m11.290s
user	0m0.620s
sys	0m3.600s
```

**Comment by qstokkink** [comment]
@pimlie if you saved the conf file, that should be enough. It appears I was wrong though, and it wasn't actually the anonymization. I'll have to see if I can reproduce this somehow.

**Comment by pimlie** [comment]
Not sure if this will help as my python debugging experience is limited, but I ran tribler with `gdb python <pid>`  attached and often (say half the time) when I interrupt tribler (so let gdb continue then interrupt with ctrl+c at random intervals) then give a `py-list` command it is on [this](https://github.com/Tribler/tribler/blob/next/Tribler/Core/DownloadState.py#L294) line.

**Comment by qstokkink** [comment]
Looking at the syscalls again, this might very well be related to #2620. In other words, the Twisted reactor is going haywire (for some reason).

**Comment by devos50** [comment]
@pimlie by any chance, do you have a torrent download that contains many files or file pieces?

**Comment by devos50** [comment]
I've tried to create a torrent with 1000 files with some random data in it and I've added the torrent to my downloads. The method you indicated only takes around 18ms to complete which isn't very long. We need some more information to debug this issue.

**Comment by qstokkink** [comment]
@devos50 I also feel that this might be due to single core execution. We should probably look into look into virtualizing a single core machine for testing.

**Comment by devos50** [comment]
@qstokkink that's quite easy to setup for us right now. Maybe @xoriole is interested in setting up (and extending my) automated tests, both on a single core and multiple cores, under different OS versions.

**Comment by devos50** [comment]
Closing due to lack of feedback.
