### ISSUE TITLE
Missing dependencies for Build-Tribler_Win*_devel jobs

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3045]
- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

Error: could not find paymentrequest_pb2.py. Create it with 'protoc --proto_path=lib/ --python_out=lib/ lib/paymentrequest.proto'

##### Tribler version/branch+revision: #####
Build 9 juli 2017
##### Operating system and version: #####
Windows 10 insider build 16237
##### Steps to reproduce the behavior: #####
Start Tribler
##### Expected behavior: #####
Normal startup tribler gui
##### Actual behavior: #####
Log screen starts and stops with this error

**Comment by qstokkink** [comment]
We have some new dependencies for the `devel` branch. Please execute
`pip install cherrypy chardet configobj cryptography decorator dnspython ecdsa feedparser jsonrpclib keyring netifaces networkx pbkdf2 pillow protobuf pyaes pysocks requests twisted win_inet_pton` (from [the documentation](https://github.com/Tribler/tribler/blob/devel/doc/development/development_on_windows.rst)).

There are still two undocumented dependencies for Windows as well, I documented how to get them here:
https://github.com/Tribler/tribler/issues/3022#issuecomment-311352306

**Comment by Nubro01** [comment]
Opened a new issue with the same problem for Windows build 16251 and july 26th Tribler build.

**Comment by qstokkink** [comment]
To solve this, we need to reset the [bbq](https://jenkins.tribler.org/computer/bbq/) builder a.s.a.p. and execute the commands I listed above on our Windows builders.

**Comment by devos50** [comment]
I will do that on Monday. Note that Otto also has access to the server room ;)

**Comment by qstokkink** [comment]
I just installed the dependencies on the win 64 builder and tested throught the installer myself. I'm still getting:
`Error: could not find paymentrequest_pb2.py. Create it with 'protoc --proto_path=lib/ --python_out=lib/ lib/paymentrequest.proto'`
This might be a compilation issue.

**Comment by Nubro01** [comment]
Ls,

Ik heb de laatste build geprobeerd van https://jenkins.tribler.org/job/Build-Tribler_Win64_devel/lastBuild/ maar het werkt nog steeds NIET!
Nog steeds dezelfde fout!
Ik gebruik de aller nieuwste Windows 10 x64 Insider build 16257

Ron Nuberg

Van: Martijn de Vos [mailto:notifications@github.com]
Verzonden: dinsdag 22 augustus 2017 10:29
Aan: Tribler/tribler
CC: Ron Nuberg; Author
Onderwerp: Re: [Tribler/tribler] Missing dependencies for Build-Tribler_Win*_devel jobs (#3045)


Closed #3045<https://github.com/Tribler/tribler/issues/3045> via #3063<https://github.com/Tribler/tribler/pull/3063>.

**Comment by qstokkink** [comment]
@Nubro01 Hmm, it seems we need to build a few more times for all of the changes to trickle down into the build.
In the mean time, this is the version I stabilized and confirmed to work on my Windows 10 PC: https://jenkins.tribler.org/job/pers/job/Build-Tribler_Win64_qstokkink/
This build _should definitely_ work.
