### ISSUE TITLE
Missing scrollbar in downloads overview

### ISSUE THREAD

**Issue by pimlie** [Tribler/tribler#3047]
- [X] I have read CONTRIBUTING.rst

- [X] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
$ git status
On branch next
Your branch is up-to-date with 'origin/next'.
nothing to commit, working directory clean

##### Operating system and version: #####
Ubuntu 16.04

The downloads overview has no scrollbar when the detail screen is hidden. This means that if you click on a torrent, move the scrollbar to the right, then click one of the upper tabs (eg Downloading or Completed) you cannot scroll left anymore. You have to click on the torrent to get the details screen again, then scroll to the left and click on one of the upper tabs again to hide the details screen.

**Comment by qstokkink** [comment]
I can't reproduce this on Ubuntu 16.04, the scrollbar correctly moves to the bottom of the screen for me.

**Comment by pimlie** [comment]
Sorry, I meant the horizontal scrollbar not the vertical:
![tribler](https://user-images.githubusercontent.com/1067403/29569774-cae8dbd8-8754-11e7-93a4-5fdcba244fb3.png)

If you click on a running torrent a horizontal scrollbar will appear, if dont have the torrent detail screen open there is no horizontal scrollbar as you see in the above image.

**Comment by qstokkink** [comment]
@pimlie Oh wow, you have bigger issues. Your entire GUI is rendering incorrectly.

**Comment by pimlie** [comment]
@qstokkink The big black box is my doing, not Tribler's if thats what you thought ;)

**Comment by qstokkink** [comment]
@pimlie Ah, that would explain half the artifacts. The vertical scrollback location also looks screwed up though. There shouldn't be any horizontal grey lines there.

**Comment by pimlie** [comment]
@qstokkink actually that is not the vertical scrollbar, I am running Tribler in a docker container and currently connect to it with a vnc client (but I can also connect with my browser through novnc). The Tribler window is configured to run without any decoration, so what you see on the right is the border of the vncviewer and actually part of the github window that was behind it.
Sorry for the confusion :)

Btw, you can check my docker config here: https://github.com/pimlie/docker-tribler-vnc

**Comment by qstokkink** [comment]
@pimlie Alright, I'll have a go with your config tomorrow.

**Comment by pimlie** [comment]
@qstokkink In that case please note that the docker image will be hard linked to an old (checked out) git version of tribler. So probably best after starting the container would be to run `docker exec -it docker-tribler-vnc bash` to login to the container, then in the container run `apt update && apt install git` and manually clone/checkout the `next` branch to `/opt/tribler`. After that its easiest to restart the docker container (`docker restart docker-tribler-vnc`) to run the new tribler version.

I am using `TightVNC Viewer version 1.3.10` to connect.

**Comment by qstokkink** [comment]
@pimlie thanks for the info 👍

**Comment by synctext** [comment]
@pimlie thank you with the numerous issues you posted. really vital work. Now that summer is over we aim to have an RC3 within 1 or 2 weeks.

**Comment by pimlie** [comment]
@qstokkink I forgot to mention, tribler runs by default in the top window layer so its always in the front and eg prevent the menubar from showing.

Maybe that is related to this issue but at least that also means that some popup windows do not show. If I remember correctly on of them is the developer mode window. If you want to change this behaviour you can edit `/root/.config/openbox/rc.xml` in the container and just comment out the xml tag: `<!-- layer>above</layer -->`. You can hit `supervisorctl restart all` within the container (but then Tribler sometimes gives some error about a property containing 'video' and keeps restarting, sorry cant remember exactly and cant find anything in the logs). Or restart the docker container.

@synctext thats great news, thanks. Really looking forward to it!

**Comment by pimlie** [comment]
Hmm, I just restarted my docker container and reconnected with vnc and actually now I also have a horizontal scrollbar (without the torrent detail screen). But as you can see in my previous image it wasnt there.

So come to think about it, probably this is a non-issue as it might still be possible for tribler to be larger than my vnc window and that the scrollbar is there but just not in my 'vnc view'.

**Comment by qstokkink** [comment]
@pimlie I just got your docker image working and ironically enough even though pressing just about any button would crash Tribler, the scrollbars did work correctly.

**Comment by qstokkink** [comment]
@pimlie it's very likely due to the Docker configuration (somehow): we test regularly on Ubuntu 16.04/16.10 barebones and VMs and I have never seen Tribler as unstable as this.

**Comment by pimlie** [comment]
Ok thanks for checking, I have never had errors when clicking buttons but the GUI can be quite sluggish sometimes indeed. Will see if I can sort things out with my docker config, maybe its related to using a virtual frame buffer or missing lxde config.

Closing the issue as it appears to be a non-issue.

**Comment by pimlie** [comment]
@qstokkink fyi, I updated my docker containers to include support for the alpine distribution and automatic build of different variants for different versions (currently only v7 is supported, mostly due to dependencies). Although you might not officially want to support alpine builds and/or vnc/novnc, I would at least like to offer the tribler organisation the possibility to take over that repository in case you are interested. Having default support for (no)vnc could be interesting for e.g. remote seed boxes.

The reason I included support for alpine is because its much more light weight and the images are much smaller. See below for an overview of the image tags and sizes that are created by the build command (currently only prerelease as there is no stable v7 yet):

![image](https://user-images.githubusercontent.com/1067403/29821641-f4844d28-8cc8-11e7-9385-e2aa60fa3d83.png)

**Comment by qstokkink** [comment]
@pimlie that seems like a nice base for deployment testing (although we would have to brush up our testing pipeline a bit to do image based testing). This might be a good idea to offer on tribler.org when we release Tribler 7?

@devos50 @egbertbouman @synctext do you have any input on this?

**Comment by qstokkink** [comment]
@pimlie we've had a talk during our coffee break this morning and we decided to go the Docker route for testing once we get our new (powerful, great & amazing) server in a few months. Do you have these Dockerfiles publicly available somewhere?

**Comment by pimlie** [comment]
@qstokkink Thanks, you can find everything in my docker repository: https://github.com/pimlie/docker-tribler-vnc

There is probably one major design decision I made that needs some explaining. I could have used dependencies between the novnc -> vnc -> tribler images so eg the tribler-vnc images used the same docker layers as the tribler image. For now I have decided against that as currently all logic is in the Dockerfile's which makes it very clear to understand whats going on. If you would want to extend the images from each other you would probably first need to write a script to build the (tribler, tribler-vnc and tribler-novnc) Dockerfile's per distribution. But that would make the build process more complicated / less clear and I didnt like that at the moment. Also I dont think users will pull multiple image variants. 
Another disadvantage of this is that the build process takes a bit longer.

**Comment by qstokkink** [comment]
@pimlie thanks for the link, we can make good use of your work when we revisit this in a few months.
