### ISSUE TITLE
Cannot install on ubuntu 17.04, without wxgtk2.8

### ISSUE THREAD

**Issue by Gabrielxinxin** [Tribler/tribler#3048]

**Comment by devos50** [comment]
Please provide some more information about this issue so we can investigate this.

**Comment by EinNarr** [comment]
@Gabrielxinxin 
I guess you are probably dealing with a outdated version of Tribler. Starting from Tribler 7, it uses QT instead of wxgtk. You could either manually install wxgtk2.8, as it is no longer in the installation guide, or download the newer version of Tribler.
