### ISSUE TITLE
tribler default on ubuntu

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#3056]
https://docs.google.com/forms/d/e/1FAIpQLScOZggYro5S5okO8yhoGI5h2ucicBZPGGLYGOI6dINA1WSTzQ/viewform

**Comment by qstokkink** [comment]
Thanks for the heads up. Sadly, due to our dependency chain, we have very little chance of getting into any package manager right now though. But this is definitely a long-term goal.

**Comment by Dmole** [comment]
What's wrong with the dependency chain?
Ubuntu 18.04 LTS will be updating versions of all sorts of packages.
Last I looked everything was in macports so getting into that would be trivial but mac users are happy with the .app.
Arch uses the latest so that to should be easy to get into though the market segment would be less than Ubuntu or Mac.
Fedora/CentOS would be harder because it's slower moving and would likely require the video plugin disabled due to non-free parts of ffmpeg, but that's no loss.
so try for Ubuntu 18

**Comment by themusicgod1** [comment]
more on the topic of ubuntu...one big step to getting into ubuntu/mint/other distros is to get into debian.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836852 is the wnpp report for that.

**Comment by Dmole** [comment]
I think Tribler should have 2 branches and try to get the LTS one into Debian... would need a modular protocol first as past changes have made old builds inoperable.

**Comment by devos50** [comment]
The modular design aligns with our vision, yet it requires invasive changes. At this point, we are not ready to engineer this.

Maybe getting IPv8 into the Debian repositories is a nice first step? @qstokkink

**Comment by qstokkink** [comment]
Getting IPv8 into Debian and pip, is on my wishlist.
