### ISSUE TITLE
Tribler build july 26th Windows 10 build 16251 dependenties missing

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3058]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.
Yes
##### Operating system and version: #####
Windows 10 Insider build 16251
##### Steps to reproduce the behavior: #####
Tribler does not start
##### Relevant log file output: #####
Untested Windows version 10.0 detected!
Error: could not find paymentrequest_pb2.py. Create it with 'protoc --proto_path=lib/ --python_out=lib/ lib/paymentrequest.proto'

**Comment by Nubro01** [comment]
Build 413 still has the same problem. Please explain what I can do to fix this myself.

**Comment by qstokkink** [comment]
You don't have Protocol Buffers installed. If you have `pip`, you can run `pip install protobuf` from the command line.

Once you have Protocol Buffers, you will also hit some other missing dependencies. You can find the complete list in my previous comment: https://github.com/Tribler/tribler/issues/3045#issuecomment-314328593

**Comment by qstokkink** [comment]
@Nubro01 Hold up, I just realised you are grabbing the `.exe` from the build and are not running from the source code. In this case, you have three options:

1. Wait another week for us to install the dependencies on the builder \*
2. Run from the source code (not recommended)
3. Run the stable build instead of the bleeding edge code: https://jenkins.tribler.org/job/Build-Tribler_Win64_next/

I will adopt https://github.com/Tribler/tribler/issues/3045 as the main issue and close this one.

\* We need to do a physical reset of the building server: our only employee authorized to access the server room and do this, is on vacation.

**Comment by Nubro01** [comment]
Correct,

The below link/build is running perfectly. Just those after this build are missing dependantties..

Ron

Van: Quinten Stokkink [mailto:notifications@github.com]
Verzonden: zaterdag 19 augustus 2017 11:26
Aan: Tribler/tribler
CC: Ron Nuberg; Mention
Onderwerp: Re: [Tribler/tribler] Tribler build july 26th Windows 10 build 16251 dependenties missing (#3058)


@Nubro01<https://github.com/nubro01> Hold up, I just realised you are grabbing the .exe from the build and are not running from the source code. In this case, you have three options:

  1.  Wait another week for us to install the dependencies on the builder *
  2.  Run from the source code (not recommended)
  3.  Run the stable build instead of the bleeding edge code: https://jenkins.tribler.org/job/Build-Tribler_Win64_next/

I will adopt #3045<https://github.com/Tribler/tribler/issues/3045> as the main issue and close this one.

* We need to do a physical reset of the building server: our only employee authorized to access the server room and do this, is on vacation.

**Comment by Nubro01** [comment]
Correction, This version starts, but it abends every time, when I try to search or add a Torrent.  It asks if I want to send the report, which I do and I hope you guys receive.

Regards

Ron

Van: Ron Nuberg [mailto:nubro01@hotmail.com]
Verzonden: donderdag 24 augustus 2017 11:14
Aan: Tribler/tribler; Tribler/tribler
CC: Ron Nuberg; Mention
Onderwerp: RE: [Tribler/tribler] Tribler build july 26th Windows 10 build 16251 dependenties missing (#3058)

Correct,

The below link/build is running perfectly. Just those after this build are missing dependantties..

Ron

Van: Quinten Stokkink [mailto:notifications@github.com]
Verzonden: zaterdag 19 augustus 2017 11:26
Aan: Tribler/tribler
CC: Ron Nuberg; Mention
Onderwerp: Re: [Tribler/tribler] Tribler build july 26th Windows 10 build 16251 dependenties missing (#3058)


@Nubro01<https://github.com/nubro01> Hold up, I just realised you are grabbing the .exe from the build and are not running from the source code. In this case, you have three options:

  1.  Wait another week for us to install the dependencies on the builder *
  2.  Run from the source code (not recommended)
  3.  Run the stable build instead of the bleeding edge code: https://jenkins.tribler.org/job/Build-Tribler_Win64_next/

I will adopt #3045<https://github.com/Tribler/tribler/issues/3045> as the main issue and close this one.

* We need to do a physical reset of the building server: our only employee authorized to access the server room and do this, is on vacation.
