### ISSUE TITLE
v7.0.0-rc2 doesn't suggest a correct folder of the previous Tribler version to uninstall and didn't ask if want so

### ISSUE THREAD

**Issue by YakovL** [Tribler/tribler#3061]
So, the issue is simple: on Win 10, I've got Tribler 6.5.2 and I installed 7.0.0-rc2. Before installing, setup suggested to uninstall the old version, but suggested a wrong path to it (a default one) and gave me no chance to change it. I've installed it to a different folder.

This is a minor issue for me if Tribler 6 uninstaller can uninstall it without touching Tribler 7 (I haven't tried yet). I also have to notice that one may want to preserve the old version during testing v7, so such option seems desirable.

**Comment by qstokkink** [comment]
Thanks for the suggestion, that sounds like a sane feature to have when we release 7.0.

**Comment by qstokkink** [comment]
@devos50 Could this be due to us switching from our `py2exe` setup to the `pyinstaller` setup? If so, I'm assuming we will have to make a separate `Tribler 6 uninstaller` to get rid of Tribler < 7.

**Comment by devos50** [comment]
@YakovL I suspect that you've installed a 32-bit version of Tribler 6.5.2, which is installed to `Program Files (x86)` by default. When you install a 64-bit version, it's default installation location is in the `Program Files` directory.

We should check the current installation directory of Tribler and set the path to that.

**Comment by qstokkink** [comment]
The installation directory is set here:
https://github.com/Tribler/tribler/blob/6bda08fab632a38fbb3fc4e9f4073e23b2d8df7a/Tribler/Main/Build/Win/tribler.nsi#L150

**Comment by qstokkink** [comment]
Actually after examining the issue we ran into this commit: https://github.com/Tribler/tribler/commit/2b6f79b4ef111c8ec2c86be96e40dd7566c8da31#diff-a3e75e911c8cab932e3d8d744a0fbb84 .

In the past the default location would always be written to the uninstall dir. This means that we are unable to detect Tribler installations which were not installed to the default path before version `6.5.2`. We are terribly sorry, but you will have to uninstall the previous version manually using the `uninstall.exe` in the older folder.

**Comment by YakovL** [comment]
@devos50 nope, I've installed both 6.x.x and 7.0.0 to custom directories

@qstokkink I see. Probably this should be mentioned in the 7.x.x installation wizard
