### ISSUE TITLE
Stuck on (turning gears) loading screen

### ISSUE THREAD

**Issue by pimlie** [Tribler/tribler#3066]
- [x ] I have read CONTRIBUTING.rst

- [x ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
/opt/tribler# git status
On branch next
Your branch is up-to-date with 'origin/next'.

##### Operating system and version: #####
both alpine linux as ubuntu 16.04

This is happening quite often the last couple of months. As mentioned before I am running Tribler in a docker container and connect with vnc. Sometimes when I restart Tribler (or the docker container itself) Tribler will not start anymore and hangs on the first loading screen with the double turning gears (so before the menu on the left is loaded).
This happened yesterday evening and I thought lets see if it will do anything in the morning but its still stuck at the gears. It seems no output has been sent to a logfile (yet).

(I thought I had seen an issue about this before but cant seem to find it at the moment)

An strace of the main process is as follows:
```
 time strace -c -p 3569
strace: Process 3569 attached
^Cstrace: Process 3569 detached
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 94.73    0.072573           1     77617           poll
  2.47    0.001892           0     22045      3904 futex
  1.68    0.001289           0     70166           write
  0.42    0.000325           0     34982           writev
  0.41    0.000315           0     31507           read
  0.15    0.000112           0      4462           clone
  0.11    0.000082           0      4462           mprotect
  0.03    0.000020           0      4462           mmap
  0.00    0.000000           0         1           restart_syscall
------ ----------- ----------- --------- --------- ----------------
100.00    0.076608                249704      3904 total

real	3m43.813s
user	0m0.264s
sys	0m5.160s
```

--edit--
to clarify, restarting tribler again does not help. Also switching from the alpine to the ubuntu container and back doesnt help. But both containers are linked to the same `$HOME/.Tribler` volume. 

I looked in the `.Tribler` folder and noticed a `triblerd.lock` file which was persistent also when I shutdown Tribler. After shutting down Tribler, removing the lock file manually then starting Tribler again it proceeds immediately to the normal 'home' screen.

**Comment by devos50** [comment]
Hmm I completely agree, we need more insight in the boot process of Tribler, something like a line in the GUI indicating the status. This makes it easier for us to debug. I will work on this 👍

**Comment by qstokkink** [comment]
We should probably also add an error pop up when we find an existing `triblerd.lock` file, like https://github.com/Tribler/tribler/issues/3041#issuecomment-324254260.

**Comment by pimlie** [comment]
@qstokkink It seems to me that the lock file behaves like a pid file as it only contains the process id of the last running tribler process. I think the real problem is this line: https://github.com/Tribler/tribler/blob/e197fb0cbf0c0b71c0041a3fec06617630136a4d/Tribler/Core/Modules/process_checker.py#L36

You only check if the process is active but _not_ if the active process is really a tribler instance.

If you run docker in a container the process id's start from 1 again every time you restart the container. So when tribler crashes (and doesnt remove the lock file) and you restart the container the change is bigger (then in a non-container system) that a process with the same pid as the lock file exists. Eg in a normal system the process id assignment has a bigger randomisation factor (if you can call it that) then in a docker container, so the chance you will hit this specific scenario is smaller.

**Comment by qstokkink** [comment]
We could give the user a pop-up to `launch anyway` if a lock file is found.

**Comment by mahlersand** [comment]
I have the same problem. Stacktrace as follows:

Log configuration file not found at location '<path-to-tribler>/tribler/TriblerGUI/logger.conf'
free(): invalid next size (fast)
Exception in thread tribler-pipe-read:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "<path-to-tribler>/tribler/TriblerGUI/core_manager.py", line 173, in <lambda>
    pipe_thread = Thread(target=lambda: self.pipe_wait(parent_conn), name="tribler-pipe-read")
  File "<path-to-tribler>/tribler/TriblerGUI/core_manager.py", line 158, in pipe_wait
    cmd, arg = child_conn.recv()
EOFError

Im also Debian - Based.

Weirdly the first startup after re-cloning it does start, but afterwards it doesn't anymore. Removing the .Tribler folder in $HOME doesn't help. Downloading tribler's rc5 .deb has inverted bahaviour. Console output is stuck at "Starting Tribler" at first start after removing .Tribler, but works after restart.

**Comment by devos50** [comment]
@mahlersand thank you for your report. Are you using packages from Debian stable or testing?

**Comment by mahlersand** [comment]
@devos50 I'm using packages from Debian Testing.

**Comment by danyg** [comment]
I had the same problem on Windows 7, I use to use the port 8085 for some internal web server, I saw that tribler start opening up to 1000 thread connecting to that port, I moved the server on port 8085 to another port, and problem fixed.

Hope it helps
