### ISSUE TITLE
Config option for http api interface

### ISSUE THREAD

**Issue by remielowik** [Tribler/tribler#3078]
Currently the RESTfull api binds to localhost. If you want to run headless on an external server(nas for example) it would be nice to be able to access this. Therefor i suggest either listening on 0.0.0.0 by default or by adding a config option to change the default.

**Comment by devos50** [comment]
@remielowik thank you for your suggestion. We actually did that as a security feature to prevent external parties from controlling your Tribler instance. We intend to implement some kind of authentication mechanism and offer users the possibility to open up their client to the outside world 👍
