### ISSUE TITLE
Web client?

### ISSUE THREAD

**Issue by remielowik** [Tribler/tribler#3079]
I've been searching for a working webclient for the restfull api, is there even one available? or is it already integrated into the client?

**Comment by synctext** [comment]
we aim to facilitate this soon. Once the Tribler V7.0 release os stable we aim to support webclient. Key feature is authentication. Thus a secured emote login into Tribler REST api.

**Comment by ichorid** [comment]
The web client is dead (for now).

**Comment by mrcruz** [comment]
Is there more information on this decision? since the team is progressing on [making tribler run headless](#4189 ) I was thinking of start working on a web interface. What is the rational on halting this?

**Comment by ichorid** [comment]
@mrcruz , the team has limited human resources to support several clients. We are already heavily invested in our QT stuff, so there is no reason for us to switch to another technology. The plan is to first work out a perfect Core and REST interface with the QT stuff we got now, then hire some GUI pros to design a proper GUI in something like QML, so it will work both through the web and on a desktop. As an alternative, there is a plan to use [Kodi]( #2694) as a GUI.

**Comment by mrcruz** [comment]
Thanks for the message @ichorid. I understand and appreciate that the team is focusing on the important stuff. I will browse a bit more for something else that I can contribute.

**Comment by ichorid** [comment]
@mrcruz , there is one thing you can help us with. We were going to migrate our tests suite to `pytest` framework and use `Mock` class. If done properly, it can decrease the tests suite codebase size 2-4 times and enable parallel testing on developer machines, which will speed up the tests about 10 times.

You can read more about pytest in an excellent [Hypermodern Python series of articles](https://cjolowicz.github.io/posts/hypermodern-python-01-setup/).

**Comment by devos50** [comment]
@ichorid porting our entire test base to `pytest` might be too much of a challenge for a relative new contributor. As I also encountered, it requires some very specific knowledge of the constructs we are using in both Tribler and our test suite. If you are still interested in doing so, I started the port to `pytest` on my [personal fork](https://github.com/devos50/tribler/tree/pytest). Please check out that code.

Instead, I would recommend some tasks that can be completed more incrementally and gradually, such as #5030 or #5233. There are likely many more issues that are suitable for new contributors. @mrcruz is there any component/part of Tribler you would prefer working on?
