### ISSUE TITLE
Torrent download stuck on Building Circuits

### ISSUE THREAD

**Issue by ThomasdenH** [Tribler/tribler#3087]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Branch: next
Revision: c7f3eaf52e5ccea57468f8be8fcfc6e99f5ac6d9

##### Operating system and version: #####
Windows 10, x64

##### Steps to reproduce the behavior: #####
1. Start Tribler
2. Add a Torrent, either from file or from magnet

##### Expected behavior: #####
The torrent starts building circuits and then starts downloading.

##### Actual behavior: #####
The torrent gets stuck at 'Building circuits'. There is no log file available. Uninstalling Tribler and removing .Tribler from /AppData/ has no effect.

##### Relevant log file output: #####
No log file in /AppData/Roaming.

**Comment by devos50** [comment]
@ThomasdenH we restarted some of our relay servers. Could you try again to see whether the torrents get past the building phase now?

**Comment by ThomasdenH** [comment]
Yes, it is downloading now. Does this mean the issue is solved?

**Comment by devos50** [comment]
@ThomasdenH yes it is, however, we still need to get more insights in the circuit building process to be able to better debug this issue 👍
