### ISSUE TITLE
Create a sophisticated deployment test on Windows

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3090]
For stability, we require a deployment test on our proxmox machines for windows platform (Win7, Win8 & Win10).

I propose that this deployment test does the following operations:
- fetch the latest tribler_setup.exe from Jenkins
- run the installer
- check if Tribler was installed properly
- run Tribler
    -  check for dependency errors
    -  check if process is running
    -  check for errors
- perform REST APIs check 
- (optional) take a screenshot
- restore a snapshot of the virtual machine

During the test, there are many sanity checks. If one of these checks fail, we fail the job.

**Comment by xoriole** [comment]
Deployment test available here:
https://jenkins.tribler.org/job/GH_Tribler_PR_deployment_tests/
