### ISSUE TITLE
Is filecoin a $257 Million bubble or a pyramid scheme?

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3097]
_A **critical** analysis of a $257 million dollar ecosystem._

Create a survey paper within 7 weeks. Possible points to cover:

- Introduction
- 15 years of documented failure
  - first failed attempt in 2000, [mojonation](https://slashdot.org/story/00/10/09/1826243/forget-napster-gnutella-enter-mojo-nation) documented in a [paper](http://www.cs.kent.edu/~javed/class-P2P12F/papers-2006/mojonation.pdf)
  - Tor community various [dead attempts](https://blog.torproject.org/blog/tor-incentives-research-roundup-goldstar-par-braids-lira-tears-and-torcoin) and 2014 [proposal](https://www.petsymposium.org/2014/papers/Ghosh.pdf)
  - our [horrible slow progress](https://github.com/Tribler/tribler/issues/2559#issuecomment-307353664) within Tribler after 12 years of work.
- analysis [of launch publicity](https://www.coindesk.com/257-million-filecoin-breaks-time-record-ico-funding/) and [social media discussions](https://www.reddit.com/r/filecoin/).
- Is the design technically feasible
  - brief technical overview
  - proof-of-space time properties
  - Analysis of Sybil attack vulnerabilities, DDoS, transactions spamming, and attacks in general.
  - Is the market part under-specified? Both in-chain storage and especially the off-chain retrieval market.
  - critical IPFS dependancy
  - the zero lines of code problem
- Is the design economically feasible?
  - is there a market balance?
  - will it be stable?
  - how will supply or demand disruption influence price?
- [investors exclusion](https://btcmanager.com/filecoin-ico-accredited-investors-only/)
- Is this a pyramid scheme? 
Already a reward for early investors.
Use the scientific 1975 rule, "[A Probability Model of a Pyramid Scheme__1975.pdf](https://github.com/Tribler/tribler/files/1303385/A.Probability.Model.of.a.Pyramid.Scheme__1975.pdf)".
- Is it a bubble?
  - is there a realistic valuation for initial investors?
  - would a fork make all early investment worthless?

Disclaimer: we are not neutral parties. We developed our own [Bandwidth-as-a-Currency](http://news.bbc.co.uk/2/hi/technology/6971904.stm) vision many years ago. In August 2007 we released our first prototype together with Harvard University.

**Comment by backender** [comment]
My response to an interview of Juan Benet:
https://www.reddit.com/r/filecoin/comments/71egv1/filecoin_vs_airbnb_and_a_simple_calculation/

**Comment by synctext** [comment]
'''
This in fact means, the $257'000'000 launched at the Filecoin ICO require 95'185'185'185 Gigabyte (95'185 Petabyte) of storage to be offered by storage miners. 
'''
nice methodology. Would be great to generate multiple such compares.

**Comment by backender** [comment]
Almost done with Section 2 (ICO analysis) -- after studying legal documents for quiet a while. Here some serious facts about the Simple Agreement for Future Token (SAFT):

Reasoning about the worst possible scenario:
>"...SAFTs will be used to fund the Company’s development of a decentralized storage network that enables entities to earn Filecoin (the “Filecoin Network”)."

Funds can be invested in whatever development they find to be appropriate.

>“Dissolution Event” means (i) a voluntary termination of operations of the Company..."
Throwing the bat is an option.

>"If immediately prior to the consummation of the Dissolution Event, the assets of the Company that remain legally available for distribution to the Purchaser and all holders of all other SAFTs (the “Dissolving Purchasers”), as determined in good faith by the Company’s board of directors, are insufficient to permit the payment to the Dissolving Purchasers of their respective Returned Purchase Amounts, then the remaining assets of the Company legally available for distribution will be distributed with equal priority and pro rata among the Dissolving Purchasers in proportion to the Returned Purchase Amounts they would otherwise be entitled to receive pursuant to this Section 1(b). "

Then, only what is left right before the Dissolution Event will be payed out the investors as well as the other owners (e.g. early investors/PL people).

... and there is more.

About to tackle technical weaknesses in this week.

**Comment by backender** [comment]
Draft for today's meeting: https://github.com/backender/filecoin-survey/releases/tag/0.1

**Comment by synctext** [comment]
2012 Microsoft patent [from Sven Seuken, worked with him on bandwidth-as-currency when I was at Harvard from 2007 onwards](www.google.tl/patents/US8626566)

**Comment by backender** [comment]
Current progress: https://github.com/backender/filecoin-survey/milestones?direction=asc&sort=due_date&state=open

<img width="794" alt="screen shot 2017-10-02 at 16 55 08" src="https://user-images.githubusercontent.com/955179/31083702-ab6d60cc-a792-11e7-8774-188a66153f4d.png">

**Comment by synctext** [comment]
Spammy, clickbait-storyline, but still interesting read: https://tokeneconomy.co/the-analysis-filecoin-doesnt-want-you-to-read-e60d5243f17c

**Comment by backender** [comment]
This is perhaps a bit off-topic but I was reading a lot about IPFS and I think it has the potential to become huge. If you think about it, IPFS could not only replace HTTP (sorry for my comment earlier this week, IPFS is obviously not built on top of HTTP) but also extend on the idea of static file storage and introduce Publish/Subscribe functionality. Hence, implicitly provide message queuing functionality for any given content. Since the IPFS filesystem applies versioning on top of the Merkle DAG. Looking at the from another perspective, every new version of a directory/folder could essentially represent the state of a topic/channel/queue/(whatever you wanna call it). Providing new versions to clients (e.g. pushing the new file/message) wouldn't even mean that nodes have to store the last consumed state for every connected client, instead, with a heavier, pull-based client, the client node itself would know its last consumed state and thus could just as for the next state (e.g. next message).
There is already a lot of discussion going on about pub/sub here: https://github.com/ipfs/notes/labels/pubsub

In terms of Filecoin, this would open the doors for decentralized pay-as-you-go streaming.

**Comment by backender** [comment]
Created an overview of according to their [specs](https://github.com/libp2p/specs)
![libp2p 1](https://user-images.githubusercontent.com/955179/31390933-7d471604-add5-11e7-960e-f8d56bc6c078.png)

**Comment by synctext** [comment]
[Filecoin and others compared](http://www.zerohedge.com/news/2017-10-15/blockchain-driven-bandwidth-new-super-currency). Plus also links to our 2007 work.

**Comment by backender** [comment]
Just stumbled over this one today: https://decentralize.today/decentralized-storage-wars-storj-v-sia-v-filecoin-v-maidsafe-27dc3d37434f.
Only discusses about token distribution but contains a nice comparison.

**Comment by backender** [comment]
Current state of report to discuss today:
https://github.com/backender/filecoin-survey/releases/tag/0.2

**Comment by synctext** [comment]
- Spell checker ("incentiviszed").
- Bitswap lacks a real incentive mechanism, just local counters for now: https://github.com/ipfs/ipfs/issues/26
- Yet another storage coin, now with "Like-button" model : http://www.flixxo.com/assets/docs/flixxo-white-paper_v0.4.pdf

**Comment by synctext** [comment]
use a Celeb to grow following and market cap: https://news.ycombinator.com/item?id=15609654

**Comment by synctext** [comment]
crashed ICO https://www.bloomberg.com/news/articles/2017-11-01/shining-star-of-initial-coin-offerings-crashing-back-to-earth

**Comment by backender** [comment]
Draft without Abstract/Conclustion, pre-grammar/wording correction: [filecoin_survey.pdf](https://github.com/Tribler/tribler/files/1444422/filecoin_survey.pdf)

**Comment by backender** [comment]
Today on HN: https://medium.com/@dennyk/why-and-how-the-cryptobubble-will-burst-de9bc7fc5332

**Comment by backender** [comment]
Tulip mania: https://www.coindesk.com/ubs-economist-compares-bitcoin-to-tulip-mania/

**Comment by backender** [comment]
New and complete draft ready: https://github.com/backender/filecoin-survey/releases/tag/0.4
[filecoin_survey (4).pdf](https://github.com/Tribler/tribler/files/1452071/filecoin_survey.4.pdf)

**Comment by synctext** [comment]
impressive work. good text

'''The fact that Protocol Labs has proven enormous technical capabilities by building IPFS and libp2p leads to believe that mastering the upcoming hurdles by building Filecoin will be handled in equal elegance.'''

polish:
Therefore, in our calculations __we__ compare the valuation of both companies against each other by opposing their resources.

**Comment by synctext** [comment]
try to make a "deliberately simple model" instead of back of the envelope calculations and expand that section. Please read SIGCOMM fluid modeling work from 13 years ago : [Modeling and performance analysis of BitTorrent-like peer-to-peer networks](https://nsl.cs.sfu.ca/teaching/05/880_p2p/Papers/QS04.pdf). Try to fit and apply this methodology for airbnb, eBay, uber, and non-market leader Lyft.

**Comment by synctext** [comment]
[Solid material for an intro](https://www.bloomberg.com/news/articles/2017-11-29/for-bitcoin-skeptics-the-question-is-what-will-pop-this-bubble) @backender a .tex update coming?
![image](https://user-images.githubusercontent.com/325224/33421992-5000733c-d5b4-11e7-9f91-9bde00c77df1.png)

**Comment by backender** [comment]
https://github.com/backender/filecoin-survey/releases/tag/0.5

**Comment by backender** [comment]
Paper regarding "trade execution optimization": https://www.cis.upenn.edu/~mkearns/papers/rlexec.pdf

**Comment by synctext** [comment]
ToDo for remainder of year: start of master thesis with 5 weeks of prototyping the Lehman Brothers 2006 paper.

**Comment by synctext** [comment]
please upvote :+1:  https://www.reddit.com/r/filecoin/comments/7gmzds/scientific_study_is_filecoin_a_257_million_ponzi/

**Comment by backender** [comment]
Also here https://news.ycombinator.com/item?id=15816729

**Comment by backender** [comment]
https://news.ycombinator.com/item?id=15816729

**Comment by synctext** [comment]
Can you alter the ycombinator title to:
Scientific ICO study "Is Filecoin a $257 million Ponzi scheme?" Delft Uni. [pdf]

**Comment by synctext** [comment]
Or not alter the title, it works, on frontpage!
![image](https://user-images.githubusercontent.com/325224/33441441-f506348c-d5f2-11e7-89a1-e1ecacb7ab11.png)

**Comment by synctext** [comment]
Filecoin is estimating that they will go live with a testnet [Q4 2018 or early 2019](https://filecoin.io/blog/update-2018-q1-q2/). They made impressive progress, but security and complexity concerns have not been addressed. Their codebase is close for the following stated reason:
```
Avoid Distractions. Having an open, public codebase generates lots of questions, issues,
pull-requests, and other interactions, all of which require significant developer time investment
in aggregate. These distractions can be very frequent for projects with a lot of attention, and
can consume large fractions of our team’s time.
```

[Sia testnet](https://sia.tech/) indicates there is no demand for decentralised storage: 4.1PB offered, 191TB, _95% of capacity is just idle!_ A throw-away price does not seems to fix this trust problem:

```
On average, Sia's decentralized cloud storage costs 90% less than incumbent
cloud storage providers. Storing 1TB of files on Sia costs about $2 per month,
compared with $23 on Amazon S3.
```

**Comment by mamba219** [comment]
Any updates on Storj coin 
They released Tardigrade.io

**Comment by synctext** [comment]
The promise of 99% profit, join [NOW](https://github.com/adityajo/sarcasmbot)! The crypto bubble is still expanding at a "healthy" rate:
![image](https://user-images.githubusercontent.com/325224/115512094-e0260100-a281-11eb-8fb0-4f123a45800c.png)
"Ethereum is 5.5 years into a 6-year planned upgrade to greatly reduce the costs",
"after the planned upgrade later this year, high profit margins (99%+)."
From: https://ethereumcashflow.com/
