### ISSUE TITLE
incentive against forking: lose your private key

### ISSUE THREAD

**Issue by oguzhanersoy** [Tribler/tribler#3106]
Copy this inside TrustChain: https://eprint.iacr.org/2017/394.pdf

Your ed25529 leaks when you sign the same block number twice and double spend..

**Comment by synctext** [comment]
This is _really_ a scientific breakthrough. It solves the scalability versus security conundrum.

**Comment by ichorid** [comment]
Related to #4719

**Comment by qstokkink** [comment]
@xoriole actually implemented this in IPv8 already 😃

**Comment by qstokkink** [comment]
Side note: but we don't use it because it's incredibly scary.

**Comment by devos50** [comment]
But it’s a cool feature nonetheless!
