### ISSUE TITLE
Full-Secure Off-chain Scheme with Unbounded Throughput 

### ISSUE THREAD

**Issue by Zhijieren** [Tribler/tribler#3107]
Problem: Scalability Issue in Blockchain

Blockchain is essentially a distributed asynchronous BFT system for unchangeable and append-only data. The BFT part is the bottle-neck for the throughput in a large network. To summarise, BFT conditions in a (ledger-like) blockchain are:

- Agreement (Consistency): If an honest node agrees that a tx is valid, another honest node cannot agree otherwise.
- Validity (Correctness): If a tx is invalid, it will not be agreed by any honest node.
- Termination (Finality): If a tx is known to an honest node, it will eventually be known to all honest nodes.

State-of-the-Art

The cost that we need to achieve all three conditions differs from model to model, assumptions to assumptions. Basically,

- strong asynchronous and BFT assumptions: No possible (CAP theorem, FLP impposibility)
- weak asynchronous or probabilistic finality: O(N^2) message complexity (PBFT, etc.)
- weak synchronous with incentive and rational nodes: O(N) message complexity (POW, POS, etc.)
- optimistic BFTs (good connections, less Byzantine nodes): O(N) message complexity (Byzcoin, etc.)

Then, when the network is large, even O(N) message complexity is not desirable. Hence, some compromise must be made on the three conditions:

- Agreement: DAG (tangle, byteball).
- Validity: Centralised solutions (Ripple, Corda, Fabric), Off-chain (Bitcoin-NG, Lightning Network), or Dependent Validity (tangle, Stellar).
- Termination: Sharding (Ethereum, Omniledger)

Our solution

Here are a few keywords to characterise our system:

1. Off-chain structure: A main chain with individual chains for each node, nodes periodically send hashes of their blocks to the main chain.
2. Interest-based model: we assume that holder of the money taking good care of it until is is spend (very realistic assumption). More precisely, we assume that one of the involved parties in a transaction is benefited from it and will care about this transaction unless it has been used as a source for another transaction.
3. Uncompromised reliability: In interest based model, it is proved that both Agreement and Validity conditions hold.
4. Interest based termination: Then, we prove that the Termination Condition actually holds for all nodes that care about the money.
5. Spontaneous sharding achieves unbounded throughput: Since in real-life, not everyone cares about every transaction. If everyone only cares about his own money, then this scheme is as good as the optimal sharding solution, which achieves unbounded throughput.

How good is this scheme?

It is amongst the best schemes out there if you don't want to sacrifice Agreement and Validity. It is at least as good as sharding.

It is also very generic since as long as the interest-based model holds, we can use this scheme to achieve unbounded throughput for any blockchain system, including conditional payment (most of the smart contract).

It has many other advantages like flexibility, privacy, and storage efficiency.

Route Map:

Sep: Finish the paper for ledger-like blockchain.
Oct: Extend it to conditional payment and run simulations.

**Comment by ichorid** [comment]
Basically, solved by [Noodle2](#4719 )
