### ISSUE TITLE
Report error if Tribler could not load

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3120]
There is already error reporting provided through a FeedbackDialog in Tribler but it works only if the application is already running and not when it is just booting up. So, it would be nice to show a dialog or something displaying errors if Tribler fails to run, especially in Windows environment where user runs the application by double-clicking the .exe file.

**Comment by qstokkink** [comment]
I made [https://github.com/Tribler/tribler/blob/next/check_os.py](check_os.py) especially for these types of errors. Currently it only does one check itself, but it should be easy to expand upon.

**Comment by xoriole** [comment]
Yes, I see and I agree. We can certainly expand upon it.

As check_os.py depends on PyQt for showing dialog, it is possible that there could be error itself in loading PyQt itself. So, as a fallback option, we could use something like tkinter dialogs to show errors. (Just a suggestion)

**Comment by qstokkink** [comment]
@xoriole good point, we should port `error_and_exit()` to `Tkinter` instead.

**Comment by qstokkink** [comment]
This is what I turned `error_and_exit()` into:
![afbeelding](https://user-images.githubusercontent.com/3630389/31007175-eae0b6cc-a4ff-11e7-928b-d622961c49a0.png)

**Comment by xoriole** [comment]
@qstokkink Nice
