### ISSUE TITLE
Display logs in Debug Pane

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3121]
Currently logs are either displayed on console or written in file. It would be easier for visual debugging if the logs are also displayed on the debug pane which already contain other useful information

**Comment by xoriole** [comment]
@devos50 @qstokkink I think PyZMQ pub/sub model could be a good choice for implementing this. Basically a publisher log handler and the debug pane as a subscriber.

What do you guys think about this?
[Asynchronous Logging via PyZMQ](http://pyzmq.readthedocs.io/en/latest/logging.html)

**Comment by qstokkink** [comment]
@xoriole seems like overkill. We need to go through the debugendpoints to share data with the GUI anyway.

**Comment by devos50** [comment]
I agree with @qstokkink, just create a GET /debug/log endpoint that returns the log file and display it in the GUI (maybe specify a number of max lines as parameter?)

**Comment by xoriole** [comment]
Here is a screenshot of the debug pane Logs tab
![tribler_logs](https://user-images.githubusercontent.com/1442867/31068627-25d76b76-a759-11e7-89e4-6d837390dfdb.png)
