### ISSUE TITLE
Exporting torrent, name of file wrong

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3131]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.
Yes
##### Tribler version/branch+revision: #####
7 RC 3
##### Operating system and version: #####
Windows 10 build 16299
##### Steps to reproduce the behavior: #####
Exxport a Torrent
##### Expected behavior: #####
Name of file to be name of the Torrent, not the name of the info hash
##### Actual behavior: #####
File name = Info hash name, which is not really clear.

**Comment by qstokkink** [comment]
I can't reproduce this on Ubuntu 16.10. We will have to verify this on Windows.

**Comment by Nubro01** [comment]
Maybe you are interested in the files involved?

Regards

Ron

Van: Quinten Stokkink [mailto:notifications@github.com]
Verzonden: vrijdag 6 oktober 2017 16:12
Aan: Tribler/tribler
CC: Ron Nuberg; Author
Onderwerp: Re: [Tribler/tribler] Exporting torrent, name of file wrong (#3131)


I can't reproduce this on Ubuntu 16.10. We will have to verify this on Windows.

**Comment by Nubro01** [comment]
Regarding the Torrents I have send. I am seeding them Anonymous, maybe we can test and upgrade the speed, because at the moment seeding anonymous is very slow and connections are dropping and reappear.

Ron



Van: Quinten Stokkink [mailto:notifications@github.com]
Verzonden: vrijdag 6 oktober 2017 16:12
Aan: Tribler/tribler
CC: Ron Nuberg; Author
Onderwerp: Re: [Tribler/tribler] Exporting torrent, name of file wrong (#3131)


I can't reproduce this on Ubuntu 16.10. We will have to verify this on Windows.

**Comment by Nubro01** [comment]
Since version of Oct 10th 2017, when exporting Torrent name is presented and exported. 
Thanks.
