### ISSUE TITLE
Creating Torrent in My Channel does not work!

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3132]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.
7 RC 3
##### Tribler version/branch+revision: #####
7 RC 3
##### Operating system and version: #####
Windows 10 build 16299
##### Steps to reproduce the behavior: #####
Create my channel and try to create a Torrent from a folder.
##### Expected behavior: #####
Like in 6.5.2. A Torrent is created, the torrent is checked and added to Library
##### Actual behavior: #####
File is added with a name of Ibler and it starts downloading instead of checking and seeding.

**Comment by qstokkink** [comment]
I can reproduce this:
- If you use a single file it works fine.
- If you select multiple files (through either CHOOSE DIRECTORY or CHOOSE FILES) it will try to download the new torrent from 0%.

**Comment by qstokkink** [comment]
@xoriole Maybe this? https://stackoverflow.com/questions/31840502/qt-folder-browser-opening-more-than-once
