### ISSUE TITLE
Unhandled error in Torrent Checker

### ISSUE THREAD

**Issue by EinNarr** [Tribler/tribler#3135]
Keep receiving similar error like this:
ERROR:root:Traceback (most recent call last):
  File "/home/bohao/tribler/TriblerGUI/event_request_manager.py", line 123, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Failure instance: Traceback: <type 'exceptions.RuntimeError'>: torrent already exists in session
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:1199:run
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:1208:mainLoop
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:828:runUntilCurrent
/usr/lib/python2.7/dist-packages/twisted/internet/task.py:239:__call__
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:150:maybeDeferred
/home/bohao/tribler/Tribler/Core/CreditMining/BoostingManager.py:422:scrape_trackers
/home/bohao/tribler/Tribler/dispersy/util.py:37:helper
/home/bohao/tribler/Tribler/Core/TorrentChecker/torrent_checker.py:198:add_gui_request
/home/bohao/tribler/Tribler/Core/TorrentChecker/session.py:732:connect_to_tracker
/home/bohao/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py:394:get_metainfo

It seems that if we have already got the torrent in libtorrent, let's say we are downloading it, when checking the torrent health, it will raise an unhandled error.
[https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Libtorrent/LibtorrentMgr.py#L394](https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Libtorrent/LibtorrentMgr.py#L394)

**Comment by devos50** [comment]
This one should be fixed after the latest next to devel backport (we made sure that there's a seperate session being used for torrent health lookups).
