### ISSUE TITLE
Tribler 7 RC3: Failed to execute script pyi_rth_qt5

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3143]
- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
tribler 7, builth oct 8th
##### Operating system and version: #####
Windows 10 build 15063, never installed tribler on it!!!
##### Steps to reproduce the behavior: #####
Clean First Tribler install and install build oct 8 2017
##### Expected behavior: #####
Normal startup
##### Actual behavior: #####
Abend
##### Relevant log file output: #####
C:\WINDOWS\system32>cd\

C:\>cd program files

C:\Program Files>cd tribler

C:\Program Files\Tribler>tribler.exe
Traceback (most recent call last):
  File "lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_qt5.py", line 56, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 546, in load_module
ImportError: DLL load failed: Kan opgegeven module niet vinden.
Failed to execute script pyi_rth_qt5

**Comment by Nubro01** [comment]
Tied on other machine where I normally test with Windwos 10 build  16299.15 and there Tribler start's normally, but current 3 Torrents where files are located in E:\Tribler, start downloading, while they were already seeding in previous version.
Removing them, to try to import does not work, because they reappear, check and start downlopading again.

**Comment by Nubro01** [comment]
Exploring files shows location C:\Users\nubro01\Downloads\TriblerDownloads while options clearly shows E:\tribler. Saved options again and restarted. but no success, will again remove appdata\roaming.Tribler and try again importing.

**Comment by Nubro01** [comment]
Import single and folder with multiple Torrents works great again. Thanks.

**Comment by Nubro01** [comment]
Checking is done 3 times before files are finally seeding. With average of 8 gig file size it takes a long time and this with just 3 Torrents in Library!!!

**Comment by Nubro01** [comment]
Installed Oct 12th 2017 version and very first Tribler install started and gave a message building first ........
After that the console windows showed a lot of messages. I do not know if this is read when I close the issue, so please close after having read this.

Regards

INFO    1507835586.12 single_application:23    __init__()
INFO    1507835586.12 single_application:49      self._outSocket.error() = '2'
INFO    1507835586.12 single_application:60    __init__(): returning
Warning: option --plugin-path no longer exists.
Warning: option --plugin-path no longer exists.
INFO    1507835588.71 event_request_manager:117   Will connect to events endpoint
qt.network.ssl: QSslSocket: cannot resolve SSL_set_alpn_protos
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_alpn_select_cb
qt.network.ssl: QSslSocket: cannot resolve SSL_get0_alpn_selected
INFO    1507835591.11 event_request_manager:42    Got Tribler core error: 1
INFO    1507835594.52 event_request_manager:117   Will connect to events endpoint
WARNING:SearchCommunity:message from {192.168.0.150:7759 217.105.146.6:7759} cannot be found in the request cache, skipping it
WARNING:TorrentChecker:No tracker to select from, skip
WARNING:SearchCommunity:message from {192.168.1.246:7759 75.27.240.192:7759} cannot be found in the request cache, skipping it
WARNING:SearchCommunity:unable to find conversion to decode 0001fb04df93369587ec8fd9b74559186fa356cffda8fa0000000000000002c0a814021e4f771191f71e4fbbe8 in [<DefaultConversion 0000 [dispersy-dynamic-settings, dispersy-missing-identity, dispersy-missing-sequence, dispersy-missing-message, dispersy-puncture-request, dispersy-undo-other, dispersy-signature-response, dispersy-destroy-community, dispersy-introduction-response, dispersy-identity, dispersy-signature-request, dispersy-authorize, dispersy-puncture, dispersy-missing-proof, dispersy-revoke, dispersy-undo-own, dispersy-introduction-request]>, <SearchConversion 0002 [dispersy-missing-message, torrent-collect-request, dispersy-signature-response, search-response, dispersy-missing-identity, torrent-collect-response, dispersy-puncture-request, dispersy-undo-other, dispersy-dynamic-settings, dispersy-undo-own, dispersy-introduction-request, dispersy-missing-sequence, dispersy-destroy-community, dispersy-introduction-response, dispersy-identity, dispersy-signature-request, dispersy-revoke, dispersy-puncture, torrent-request, search-request, dispersy-authorize, dispersy-missing-proof, torrent]>]
WARNING:SearchCommunity:_on_incoming_packets: drop a 45 byte packet (received packet for unknown conversion) from <Candidate 83.149.70.6:6424>
WARNING:SearchCommunity:message from {192.168.1.20:7759 62.167.119.47:7759} cannot be found in the request cache, skipping it
WARNING:Timeline:FAIL time:5 user:140 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:38 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:242 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:243 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:241 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:244 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:245 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:246 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:247 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:249 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:250 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:251 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:4 user:104 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:252 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:64 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:253 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:254 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:255 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:256 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:67 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:257 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:258 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:259 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:260 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:261 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:4 user:104 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:262 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:263 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:264 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:49 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:265 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:266 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:267 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:268 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:269 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:4 user:270 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:271 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:272 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:273 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:274 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:275 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:276 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:277 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:278 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:279 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:280 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:281 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:282 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:283 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:284 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:285 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:286 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:4 user:287 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:288 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:289 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:126 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:4 user:295 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:296 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:4 user:297 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:290 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:291 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:292 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:293 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:294 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:298 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:299 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:4 user:300 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:4 user:301 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:4 user:302 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:303 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:304 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:306 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:314 -> permit^channel (no authorization)
WARNING:SearchCommunity:message from {10.64.97.247:7759 91.238.127.60:7759} cannot be found in the request cache, skipping it
WARNING:PreviewChannelCommunity:drop a 468 byte packet duplicate message by member^global_time (2) [torrent] from <Candidate 86.143.17.18:7759>
WARNING:PreviewChannelCommunity:drop a 789 byte packet duplicate message by member^global_time (2) [torrent] from <Candidate 86.143.17.18:7759>
WARNING:PreviewChannelCommunity:drop a 536 byte packet duplicate message by member^global_time (2) [torrent] from <Candidate 86.143.17.18:7759>
WARNING:PreviewChannelCommunity:drop a 874 byte packet duplicate message by member^global_time (2) [torrent] from <Candidate 86.143.17.18:7759>
WARNING:Timeline:FAIL time:919 user:309 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:1748 user:309 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:2926 user:308 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:3641 user:308 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:4655 user:307 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:4712 user:307 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:4994 user:307 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:5318 user:307 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:5548 user:307 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:5637 user:307 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:6335 user:307 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:6496 user:307 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:7427 user:307 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:7673 user:307 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:8200 user:310 -> permit^torrent (no authorization)
WARNING:SearchCommunity:unable to find conversion to decode 0001fb04df93369587ec8fd9b74559186fa356cffda8fa00000000000000026452c2891e4f6452c2891e4f6b2b in [<DefaultConversion 0000 [dispersy-dynamic-settings, dispersy-missing-identity, dispersy-missing-sequence, dispersy-missing-message, dispersy-puncture-request, dispersy-undo-other, dispersy-signature-response, dispersy-destroy-community, dispersy-introduction-response, dispersy-identity, dispersy-signature-request, dispersy-authorize, dispersy-puncture, dispersy-missing-proof, dispersy-revoke, dispersy-undo-own, dispersy-introduction-request]>, <SearchConversion 0002 [dispersy-missing-message, torrent-collect-request, dispersy-signature-response, search-response, dispersy-missing-identity, torrent-collect-response, dispersy-puncture-request, dispersy-undo-other, dispersy-dynamic-settings, dispersy-undo-own, dispersy-introduction-request, dispersy-missing-sequence, dispersy-destroy-community, dispersy-introduction-response, dispersy-identity, dispersy-signature-request, dispersy-revoke, dispersy-puncture, torrent-request, search-request, dispersy-authorize, dispersy-missing-proof, torrent]>]
WARNING:SearchCommunity:_on_incoming_packets: drop a 45 byte packet (received packet for unknown conversion) from <Candidate 83.149.70.6:6424>
WARNING:Timeline:FAIL time:271 user:311 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:275 user:312 -> permit^torrent (no authorization)
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:TrackerManager:skip invalid tracker: u'http://bt.rutracker.org'
WARNING:Timeline:FAIL time:12 user:315 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:24 user:315 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:126 user:318 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:138 user:318 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:142 user:318 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:146 user:318 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:157 user:318 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:220 user:320 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:222 user:320 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:232 user:319 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:240 user:320 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:257 user:322 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:458 user:321 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:732 user:316 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:1333 user:317 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:1428 user:317 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:35 user:324 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:36 user:324 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:37 user:324 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:41 user:324 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:42 user:324 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:43 user:323 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:99 user:323 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:103 user:323 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:104 user:323 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:105 user:323 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:106 user:323 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:203 user:325 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:175 user:272 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:932 user:272 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:1148 user:272 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:1301 user:272 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:1321 user:272 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:1861 user:272 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:3879 user:272 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:4475 user:272 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:5498 user:272 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:7693 user:314 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:7872 user:314 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:9468 user:314 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:9635 user:314 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:11052 user:314 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:11079 user:314 -> permit^torrent (no authorization)
WARNING:SearchCommunity:message from {192.168.20.2:7759 119.17.145.247:7759} cannot be found in the request cache, skipping it
WARNING:SearchCommunity:unable to find conversion to decode 0001fb04df93369587ec8fd9b74559186fa356cffda8fa0000000000000002c0a80f661e4fd8f0058a1e4f9f25 in [<DefaultConversion 0000 [dispersy-dynamic-settings, dispersy-missing-identity, dispersy-missing-sequence, dispersy-missing-message, dispersy-puncture-request, dispersy-undo-other, dispersy-signature-response, dispersy-destroy-community, dispersy-introduction-response, dispersy-identity, dispersy-signature-request, dispersy-authorize, dispersy-puncture, dispersy-missing-proof, dispersy-revoke, dispersy-undo-own, dispersy-introduction-request]>, <SearchConversion 0002 [dispersy-missing-message, torrent-collect-request, dispersy-signature-response, search-response, dispersy-missing-identity, torrent-collect-response, dispersy-puncture-request, dispersy-undo-other, dispersy-dynamic-settings, dispersy-undo-own, dispersy-introduction-request, dispersy-missing-sequence, dispersy-destroy-community, dispersy-introduction-response, dispersy-identity, dispersy-signature-request, dispersy-revoke, dispersy-puncture, torrent-request, search-request, dispersy-authorize, dispersy-missing-proof, torrent]>]
WARNING:SearchCommunity:_on_incoming_packets: drop a 45 byte packet (received packet for unknown conversion) from <Candidate 83.149.70.6:6424>
WARNING:Timeline:FAIL time:6 user:333 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:323 -> permit^channel (no authorization)
WARNING:SearchCommunity:unable to find conversion to decode 0001fb04df93369587ec8fd9b74559186fa356cffda8fa00000000000000026452c2891e4f6452c2891e4f92ac in [<DefaultConversion 0000 [dispersy-dynamic-settings, dispersy-missing-identity, dispersy-missing-sequence, dispersy-missing-message, dispersy-puncture-request, dispersy-undo-other, dispersy-signature-response, dispersy-destroy-community, dispersy-introduction-response, dispersy-identity, dispersy-signature-request, dispersy-authorize, dispersy-puncture, dispersy-missing-proof, dispersy-revoke, dispersy-undo-own, dispersy-introduction-request]>, <SearchConversion 0002 [dispersy-missing-message, torrent-collect-request, dispersy-signature-response, search-response, dispersy-missing-identity, torrent-collect-response, dispersy-puncture-request, dispersy-undo-other, dispersy-dynamic-settings, dispersy-undo-own, dispersy-introduction-request, dispersy-missing-sequence, dispersy-destroy-community, dispersy-introduction-response, dispersy-identity, dispersy-signature-request, dispersy-revoke, dispersy-puncture, torrent-request, search-request, dispersy-authorize, dispersy-missing-proof, torrent]>]
WARNING:SearchCommunity:_on_incoming_packets: drop a 45 byte packet (received packet for unknown conversion) from <Candidate 83.149.70.6:6424>
WARNING:Timeline:FAIL time:40 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:41 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:43 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:44 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:45 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:46 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:47 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:48 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:49 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:50 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:103 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:104 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:105 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:106 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:107 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:108 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:109 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:110 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:111 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:112 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:133 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:134 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:135 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:136 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:137 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:138 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:139 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:140 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:141 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:142 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:163 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:164 user:335 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:5 user:495 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:499 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:340 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:500 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:501 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:502 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:4 user:496 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:497 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:498 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:503 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:504 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:505 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:506 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:5 user:507 -> permit^channel (no authorization)
WARNING:Timeline:FAIL time:6 user:508 -> permit^channel (no authorization)
WARNING:SearchCommunity:message from {192.168.56.1:7759 188.119.20.231:58129} cannot be found in the request cache, skipping it
WARNING:Timeline:FAIL time:22 user:514 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:34 user:514 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:40 user:513 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:46 user:515 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:57 user:511 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:58 user:511 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:65 user:512 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:66 user:512 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:66 user:510 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:74 user:510 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:81 user:510 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:82 user:510 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:83 user:510 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:113 user:516 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:95 user:517 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:126 user:517 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:252 user:517 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:299 user:517 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:320 user:517 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:335 user:517 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:350 user:517 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:361 user:517 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:463 user:510 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:523 user:510 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:527 user:510 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:610 user:510 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:659 user:510 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:672 user:510 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:8 user:518 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:5510 user:520 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:6337 user:520 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:6443 user:520 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:7240 user:520 -> permit^torrent (no authorization)
WARNING:Timeline:FAIL time:7357 user:520 -> permit^torrent (no authorization)
WARNING:TorrentChecker:Got session error for URL udp://tracker.openbittorrent.com:80: [Failure instance: Traceback (failure with no frames): <type 'exceptions.ValueError'>: UDP tracker failed for url udp://tracker.openbittorrent.com:80
]
WARNING:MultiChainCommunity:removing ('47.17.27.191', 14809) {192.168.70.102:7759 47.17.27.191:14809} in favor of ('47.17.27.191', 47983) {192.168.70.102:7759 47.17.27.191:47983}
WARNING:SearchCommunity:drop a 191 byte packet invalid puncture identifier [dispersy-puncture] from {192.168.0.42:7759 78.206.178.124:7759}

**Comment by qstokkink** [comment]
As per request, closing this issue now that the entire Tribler team has read it.
