### ISSUE TITLE
Tribler abends on different Windows size with different error.

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3146]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.
Yes
##### Tribler version/branch+revision: #####
Tribler 7 oct 8 build Windows x64
##### Operating system and version: #####
Windows 10 X64 build 16299.15
##### Steps to reproduce the behavior: #####
Start tribler check 3 Torrents in Library
##### Expected behavior: #####
Tribler to run normal
##### Actual behavior: #####
tribler abends after +/- 10 minutes
##### Relevant log file output: #####
When Tribler windows is on smallest size 640x480 I get following error after 10 minutes of seeding.

Warning: option --plugin-path no longer exists.
Warning: option --plugin-path no longer exists.
qt.network.ssl: QSslSocket: cannot resolve SSL_set_alpn_protos
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_alpn_select_cb
qt.network.ssl: QSslSocket: cannot resolve SSL_get0_alpn_selected
Unhandled error in Deferred:

ERROR:root:Traceback (most recent call last):
  File "TriblerGUI\event_request_manager.py", line 123, in on_read_data
RuntimeError: [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'persistence'
lib\site-packages\twisted\internet\base.py:1243:run
lib\site-packages\twisted\internet\base.py:1252:mainLoop
lib\site-packages\twisted\internet\base.py:878:runUntilCurrent
lib\site-packages\twisted\internet\task.py:239:__call__
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:150:maybeDeferred
Tribler\community\market\community.py:1715:compute_reputation
]

When on Windows size 1920x1200 I get this

Warning: option --plugin-path no longer exists.
Warning: option --plugin-path no longer exists.
qt.network.ssl: QSslSocket: cannot resolve SSL_set_alpn_protos
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_alpn_select_cb
qt.network.ssl: QSslSocket: cannot resolve SSL_get0_alpn_selected
Unhandled error in Deferred:

ERROR:root:Traceback (most recent call last):
  File "TriblerGUI\event_request_manager.py", line 123, in on_read_data
RuntimeError: [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'persistence'
lib\site-packages\twisted\internet\base.py:1243:run
lib\site-packages\twisted\internet\base.py:1252:mainLoop
lib\site-packages\twisted\internet\base.py:878:runUntilCurrent
lib\site-packages\twisted\internet\task.py:239:__call__
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:150:maybeDeferred
Tribler\community\market\community.py:1715:compute_reputation
]

QWindowsWindow::setGeometry: Unable to set geometry 600x470+660+356 on QWidgetWindow/'FormWindow'. Resulting geometry:  600x745+660+356 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 389x469, maximum size: 16777215x16777215).
QWindowsWindow::setGeometry: Unable to set geometry 600x470+660+356 on QWidgetWindow/'FormWindow'. Resulting geometry:  600x745+660+356 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 389x469, maximum size: 16777215x16777215).

**Comment by devos50** [comment]
@Nubro01 it seems that you are testing the bleeding-edge development branch where this is a known issue. Please stick to the release candidate builds (which can be downloaded here: https://jenkins.tribler.org/job/Build_Tribler_next/). Thanks!

**Comment by Nubro01** [comment]
Martijn,

I have a Ziggo 250/25 internet connection and I use what they call the Connectbox. I switched from a Cisco 3925 modem, because they said that I would get IPv6.
Of course they lied and the modem only gives out a IPv4 address. Friends who switched from KPN to Ziggo, also got a Connectbox and since they are new, they did get IPv6.
When I look at the peers downloading from my seeding I see also IPv6 ip addresses, do you have any idea how this is possible?
Internally I have IPv6 active, but it looks to me that this Connect box, somehow let’s IPv6 pass through, how else can these address appear with my Tribler peer overview?

Regards

Ron

**Comment by Nubro01** [comment]
Version since oct 10th 2017 runs very stable.
