### ISSUE TITLE
System Tray icon remains after shutdown

### ISSUE THREAD

**Issue by wcruppel** [Tribler/tribler#3147]
- [X] I have read CONTRIBUTING.rst
- [X] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
7.0 RC3
##### Operating system and version: #####
Windows 10 1703
##### Steps to reproduce the behavior: #####
1) Start Tribler.
2) Stop Tribler.
3) System Tray Icon remains. Hovering mouse over icon causes icon to disappear (hence we know the process has exited).
##### Expected behavior: #####
System tray icon is removed on shutdown.
##### Actual behavior: #####
System tray icon remains after shutdown.
##### Relevant log file output: #####
There doesn't appear to be anything relevant in the log files, though I have attached what there is.

[tribler-info.log](https://github.com/Tribler/tribler/files/1367024/tribler-info.log)

**Comment by qstokkink** [comment]
We might need to do [this](http://www.qtcentre.org/threads/4948-QSystemTray-stays-longer-than-it-should-!?s=54baa71c338821bea84d51ee772b2435&p=25833#post25833) manually to fix this.
