### ISSUE TITLE
Tribler 7 RC3 uses a dependency not in the Arch Linux repos

### ISSUE THREAD

**Issue by vandenheuvel** [Tribler/tribler#3149]
On e8ae41e33890a144d5d1d62f6a58ce8c60ae2f5f, Arch Linux.

The `python2-meliae` package is necessary to run Tribler 7 RC3. This package is however not listed as a dependency in the `doc/development/development_on_linux.rst` file. Moreover, it is not available in the Arch Linux repositories; one must retrieve it from the AUR. I'm not sure if this desirable, as it would be the first dependency outside of the Arch repos. After installing `python2-meliae` from the AUR, RC3 progressed further into the startup process.

**Comment by qstokkink** [comment]
This is the list of dependencies for `next`: https://github.com/Tribler/tribler/blob/next/doc/development/development_on_linux.rst . As such this should be fixed during the next `next` to `devel` backport.
