### ISSUE TITLE
Tribler 7 RC3 hangs on startup

### ISSUE THREAD

**Issue by vandenheuvel** [Tribler/tribler#3150]
On tag `v7.0.0-rc3`, https://github.com/Tribler/tribler/commit/e8ae41e33890a144d5d1d62f6a58ce8c60ae2f5f. Arch Linux based on 4.13.4-1. I have installed the `python2-meliae` package from the AUR.

When starting Tribler without a state directory, I receive the following error:
```
INFO    1507545687.25 single_application:23    __init__()
INFO    1507545687.32 single_application:49      self._outSocket.error() = '0'
INFO    1507545687.32 single_application:52    received QLocalSocket.ConnectionRefusedError; removing server.
INFO    1507545687.32 single_application:64    close()
INFO    1507545687.32 single_application:71    close(): returning
INFO    1507545687.32 single_application:60    __init__(): returning
INFO    1507545687.64 event_request_manager:117   Will connect to events endpoint
INFO    1507545687.66 event_request_manager:42    Got Tribler core error: 1
INFO    1507545687.68   sqlitecachedb:136   begin page_size upgrade...
INFO    1507545687.69   sqlitecachedb:140   ...end page_size upgrade
INFO    1507545687.69   sqlitecachedb:160   Initializing new database...
INFO    1507545687.70   sqlitecachedb:181   Reading database version...
INFO    1507545687.70   sqlitecachedb:185   Current database version is 28
INFO    1507545687.70   sqlitecachedb:203   Beginning the first transaction...
INFO    1507545687.71 torrent_upgrade65:25    torrent collecting directory not found, skip: None
INFO    1507545687.71   sqlitecachedb:225   Start committing...
INFO    1507545687.71   sqlitecachedb:238   Beginning another transaction...

```
The GUI loading screen does show up (the grinding gears), but I am not yet being asked for my keyring password.

**Comment by hovancik** [comment]
I'm seeing similar from time to time on debian: 

the screen with gears shows up but nothing after... What helps sometimes is to restart app, but mostly I need to reinstall.

**Comment by xoriole** [comment]
Encountered a similar problem. Tribler gets stuck on the loading screen.
Looking at the log, this was the last logged message:
```
Inconsistency detected by ld.so: dl-tls.c: 493: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
```
It seems like the issue is because of a race condition between tls allocation at thread creation and dlopen  ([here](https://sourceware.org/ml/libc-alpha/2016-01/msg00220.html)) as the problem is temporary and Tribler runs fine next time on restart.

**Comment by vandenheuvel** [comment]
For me this problem was very much consistent, suggesting it is not caused by a race condition.

**Comment by jalbstmeijer** [comment]
I see the same behavior with 7rc2 on Fedora 26, without exception.

**Comment by hovancik** [comment]
Now it's happening to me all the time. Reinstall is not helping.Starting from command line is not showing any error.
