### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'setParent'

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3153]
AttributeError: 'NoneType' object has no attribute 'setParent'
##### Steps to reproduce the behavior: #####
Go to My Channel --> TORRENTS --> Click on ADD button at the bottom right
On popup menu, select 'Create torrent from file(s)' --> it opens the 'Create a new torrent page' with the form. Without filling up anything in the form, click 'CREATE' button. It shows a notice box saying you should add at least one file to your torrent. Close the notice box by clicking on 'CLOSE' button.

Now, select any other tab on My channel (eg. SETTINGS) and then again select TORRENTS tab and try to create a torrent from files but without selecting any files just like above. As expected it shows the same notice box saying you should add at least one file to your torrent. Now, try to close the notice box by clicking the 'CLOSE' button. On clicking twice, Tribler terminates with a stack trace listed below.

##### Expected behavior: #####
Notice box should close without error

##### Actual behavior: #####
Tribler terminates with error

##### Stack Trace ######
```python
Traceback (most recent call last):
  File "/home/sandip/personal/tribler/TriblerGUI/widgets/createtorrentpage.py", line 88, in on_dialog_ok_clicked
    self.dialog.setParent(None)
AttributeError: 'NoneType' object has no attribute 'setParent'```

**Comment by qstokkink** [comment]
Probably related to #3138

**Comment by xoriole** [comment]
This seems to be fixed in latest `next`
