### ISSUE TITLE
Anonymous seeding slow

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3155]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.
Yes Oct 12th 2017 version
##### Operating system and version: #####
Windows 10 Insider build 17004
##### Steps to reproduce the behavior: #####
Download Torrent none anonymous and seed anonymous
##### Expected behavior: #####
When seeding anonymous whole upload speed should be used.
When seeding none anonymous, I seed sometimes xx MBs.
##### Actual behavior: #####
Seeding anonymous is in 800 bytes and sometimes in 2 Kb, but never MBs!
I understand that the leecher is responsible, but I still wonder why does a leecher not grab my 20MBs upload speed?

**Comment by Nubro01** [comment]
When I examine the seeding, I sometimes so peeks of a leecher of 600 kB/s, but after a second it is back at 2 kB/s or less, so???

**Comment by qstokkink** [comment]
This is probably related to #3065.

**Comment by Nubro01** [comment]
Quinten,

If you ever want to test anonymous uploading then I can start a Tribler on my Asus Z170 Premium with I7 6700K with the attached 3 Torrents. I have Ziggo 250/25.
At this very moment I am seeding these three Torrents with 3 hops and sometimes I see uploads with a few bytes.
Email me in advance with a date and time if you want test this.

Regards

Ron Nuberg

**Comment by qstokkink** [comment]
@Nubro01 thanks for the offer, but there is no need to sacrifice your machine for testing. The team just got 11 new servers and we plan to use these for stress testing and bugfinding. When we (finally) get the main 7.0 release out, we can focus on anonymous seeding performance. We should also be getting new developers soon to aid in this process.
