### ISSUE TITLE
fix_torrent error

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#3161]
##### Tribler version/branch+revision: #####
7.0.0-rc3

##### Operating system and version: #####
macOS 10.13

##### Steps to reproduce the behavior: #####
rm -r ~/.Tribler
open Tribler-7.0.0-rc3.app
add torrent from file

##### Expected behavior: #####
torrent starts downloading 

##### Actual behavior: #####
An error occurred during the request:

```
{
   "error":{
      "message":"",
      "code":"IOError",
      "handled":false,
      "trace":[
         "  File \"twisted/web/server.py\", line 190, in process\n",
         "  File \"twisted/web/server.py\", line 241, in render\n",
         "  File \"twisted/web/resource.py\", line 250, in render\n",
         "  File \"Tribler/Core/Modules/restapi/downloads_endpoint.py\", line 273, in render_PUT\n",
         "  File \"Tribler/Core/Session.py\", line 300, in start_download_from_uri\n",
         "  File \"Tribler/Core/Libtorrent/LibtorrentMgr.py\", line 537, in start_download_from_uri\n",
         "  File \"Tribler/Core/Libtorrent/LibtorrentMgr.py\", line 580, in start_download\n",
         "  File \"Tribler/Core/Utilities/utilities.py\", line 269, in fix_torrent\n"
      ]
   }
}
```

**Comment by Dmole** [comment]
Workaround:
`prename 's/[^\.0-9a-zA-Z ]+//g' *.torrent`

**Comment by devos50** [comment]
@Dmole could you please provide us the torrent that gives the error? You can either put it here or send it to me personally if you wish (see my Github profile for my mail address).

**Comment by Dmole** [comment]
@devos50 sent.

**Comment by devos50** [comment]
@Dmole thank you. We received your torrent and we've pinpointed the exact error, which happens when there's a special character (`+`, `&`, etc) in the torrent name. This character is escaped out when performing a GET request to the Tribler core.
