### ISSUE TITLE
Download/Torrent remove does not work

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3169]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.
oct 19th version
##### Tribler version/branch+revision: #####
Tribler 7 RC3
##### Operating system and version: #####
Windows 10 x64 Insider build 17017
##### Steps to reproduce the behavior: #####
Anonymous download, change it to no anonymous and try to delete
##### Expected behavior: #####
Torrent is remove from Library
##### Actual behavior: #####
None anonymous removed Torrent is added again as anonymous.
When trying to remove download+data an error occurs and I have send 3 reports, I just hope they arrive a message reply, like report received would be handy.

**Comment by devos50** [comment]
@qstokkink managed to reproduce this one so we will take a look at it. Thanks for reporting!

**Comment by qstokkink** [comment]
@devos50 yes, this also happens when changing anonimity level. I believe @xoriole reproduced this when removing downloads. I'm not sure what caused this though, it used to work flawlessly before and I don't believe we made any changes to the libtorrent classes since.

**Comment by Nubro01** [comment]
it's still happening with version of oct 20th.
Could it be something with the database, the torrent reappearing must come from somewhere?
If the delete is not committed then who knows what happens.

**Comment by Nubro01** [comment]
With downloading the Torrent for all seasons of "the Xfiles" an extra torrent was added called "Extra's" most of the these files where also within the orginal Torrent. When I tried to delete, it kept reappearing, what ever I tried.
When I deleted the "the Xfiles" Torrent, than I was also able to delete this "Extra's" torrent without any problem. guess these two where coupled someway?

**Comment by qstokkink** [comment]
I can still reproduce this, so I will open it again.

**Comment by Nubro01** [comment]
Today with Nov 10th version, I wanted to remove an old Torrent and files where deleted, but it reappeared again and tried to download again. Because I had already copied the file I needed to the correct locations, this is not needed, but what ever I try, this thing will NOT REMOVE, so???

**Comment by qstokkink** [comment]
@Nubro01 weird. Could you open a new issue for this?
