### ISSUE TITLE
Changing Anonymous hop counter, triggers a check of the whole file.

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3173]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.
Yes
##### Tribler version/branch+revision: #####
Tribler 7
##### Operating system and version: #####
Windows 10 Insider 17017
##### Steps to reproduce the behavior: #####
Right click an entry with the Library and select a different number of hops
##### Expected behavior: #####
Hop counter is changed and files are not checked.
##### Actual behavior: #####
Hop counter is changed and file is checked again.

**Comment by qstokkink** [comment]
Dev. note: this can probably be achieved by modifying the LibTorrent checkpoint file directly to share it between LibTorrent sessions.
