### ISSUE TITLE
how to add custom widget in tribler?

### ISSUE THREAD

**Issue by haidang12** [Tribler/tribler#3175]
#### Please, fill all relevant items: ####
I am doing Hello World tutorial about Tribler but I can not find the "Add widget" button to add my widget. Can anyone help me? Thanks in advance

**Comment by qstokkink** [comment]
As it appears no one is able to answer your question: could you elaborate on what it is you are trying to do exactly (and which hello world tutorial you are following)?

**Comment by haidang12** [comment]
I am trying to do follow this tutorial [https://www.tribler.org/WidgetDeveloping/Tutorials/HelloWorld/](url).

**Comment by ichorid** [comment]
old GUI is dead
