### ISSUE TITLE
Ratio reached and increased no seeding

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3178]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.
oct 27th 2017 version
##### Tribler version/branch+revision: #####
Tribler 7
##### Operating system and version: #####
Windows 10 Insider 17025
##### Steps to reproduce the behavior: #####
Seed a Torrent and wait until it reaches ratio 5
Try changing to Unlimited seeding and start the seeding, it is stopped!
##### Expected behavior: #####
When changing to unlimited  seeding and start the seeding it should start.
##### Actual behavior: #####
When changing to unlimited, seeding is not starting.
**When changing anonymous to no Anonymity, ratio is reset to 0 and seeding can be started!!!**

**Comment by qstokkink** [comment]
I can confirm this behavior for a ratio of 0.5 as well. Once the torrent is stopped it can never be started again (start/recheck doesn't work).
