### ISSUE TITLE
How can I report a security vulnerability to Tribler team? 

### ISSUE THREAD

**Issue by roshanpty** [Tribler/tribler#3179]
I have come across a potential security issue in one of the Tribler systems. Where should I send the details to?

**Comment by devos50** [comment]
Hi, thank you for your interest helping us. Please send the report to my personal email (see my Github profile) and I will discuss it with the development team 👍

**Comment by roshanpty** [comment]
Sure, I have sent the details to you.

**Comment by devos50** [comment]
We got the details and fixed the vulnerability.

**Comment by attritionorg** [comment]
Can you confirm this is the fixing commit: https://github.com/Tribler/tribler/commit/1b04b936ac339769fc45b55d59bde7f67f85d010

**Comment by qstokkink** [comment]
@attritionorg don't worry: the vulnerability was in our (web) server architecture, not in the Tribler code.
