### ISSUE TITLE
Can not watching streaming video on Tribler

### ISSUE THREAD

**Issue by Hoangle123** [Tribler/tribler#3182]
I built Tribler from source code in github. It usually interrupts and I can not watch streaming video. Its user interface does like the interface I see in Window version. I think it is the 7 beta version. Where could I find the older version of tribler. I think it operate more stably.
This is my Tribler screen shot
![screenshot from 2017-11-01 16-52-38](https://user-images.githubusercontent.com/33053708/32270509-c8a7e3d0-bf28-11e7-8be8-a51d7aaa5eae.png)

#### Please, fill all relevant items: ####

- [ ] I have read CONTRIBUTING.rst

- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

**Comment by qstokkink** [comment]
You can find the older release with source code here:
https://github.com/Tribler/tribler/releases/tag/v6.5.2
