### ISSUE TITLE
Does not work on Ubuntu 17.10

### ISSUE THREAD

**Issue by sirber** [Tribler/tribler#3211]
##### Tribler version/branch+revision: #####
6.5.x and 7.0.x

##### Operating system and version: #####
Ubuntu 17.10

##### Steps to reproduce the behavior: #####
1) dpkg -i XXX.deb
2) apt -f install

##### Expected behavior: #####
Would install and work

##### Actual behavior: #####
6.5 is getting removed
7.0 install but doesn't launch

**Comment by xoriole** [comment]
It would be helpful if you could provide us the tribler logs located inside `.Tribler/logs` directory.

**Comment by sirber** [comment]
Here's some logs and screenshots:

![screenshot from 2017-11-09 08-29-23](https://user-images.githubusercontent.com/3911428/32607813-20e718d6-c528-11e7-949e-79b2ce56474a.png)
[tribler-error.log](https://github.com/Tribler/tribler/files/1457733/tribler-error.log)
[tribler-info.log](https://github.com/Tribler/tribler/files/1457734/tribler-info.log)
[tribler_700rc3_ubuntu1717.log](https://github.com/Tribler/tribler/files/1457721/tribler_700rc3_ubuntu1717.log)

**Comment by sirber** [comment]
https://github.com/Tribler/tribler/issues/3142

**Comment by sirber** [comment]
v7: Worked by adding the missing python module. Sorry I did not debug it further the first time.
