### ISSUE TITLE
Tunnel helpers are consuming a lot of disk space

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3218]
Our tunnel helpers are using a lot of disk space. More specifically, they are writing data to `/var/log/syslog` and `/var/log/daemon.log`. Investigation of the syslog shows that the log is filled with the following line:

```
Nov 13 09:02:34 LSW-83 twistd[12371]: 2017-11-13 09:02:32+0100 [twisted.internet.protocol.Factory] Could not accept new connection (EMFILE)
```

**Comment by qstokkink** [comment]
http://blog.izs.me/post/56827866110/wtf-is-emfile-and-why-does-it-happen-to-me

> The error code EMFILE means that a process is trying to open too many files.

**Comment by xoriole** [comment]
Twisted is removed already from the code base and the log mentioned should no longer present, so closing the issue. Please reopen if the issue still exists.

**Comment by devos50** [comment]
Even though Twisted has been removed, the provided [systemd file for exit nodes](https://github.com/Tribler/tribler/blob/main/build/systemd/anontunnel_helper%40.service) (and in general, journalctl processes) by default writes stdout and stderr to `/var/log/syslog`, which can then grow to considerable size.

I'm not sure if this is something we should fix in the `systemd` file or whether this is a system setting specific to one machine (I think the latter).
