### ISSUE TITLE
Torrent not removing

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3222]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.
nov 10th version
##### Operating system and version: #####
Windows 10
##### Steps to reproduce the behavior: #####
Add a Torrent to the Tribler download folder and start it.
When done try to remove the torrent.
When deleted, files are removed but Torrent is added again with full selection of all files and Anonymous YES, while it was no before!!!!
##### Expected behavior: #####
Torrent is removed.
##### Actual behavior: #####
Torrent is added again and downloaded again with Anonymous yes.
##### Relevant log file output: #####
I cleared my appdata\Rouming\/Tribler folder and after changing the default download folder to d:\Tribler, the present *.torrent files where automatically added.

**Comment by qstokkink** [comment]
I cannot reproduce this issue on `Ubuntu 16.10`, I have tried removing torrents which are:
 - Not anonymous, downloading, all files selected
 - Not anonymous, downloading, not all files selected
 - Not anonymous, seeding, all files selected
 - Not anonymous, seeding, not all files selected
 - Not anonymous, seeding, all files selected, changed default download folder
 - Not anonymous, seeding, not all files selected, changed default download folder

**Comment by qstokkink** [comment]
Upon further investigation, it seems the Windows **build** is very broken right now (also #3223). This doesn't seem to happen when running from the source code.

**Comment by Nubro01** [comment]
tried with Nov 14th x64 Windows version.
Tribler download location is D:\Tribler
As soon as the xx.torrent file is present within this folder, the Torrent is added as soon as you try to delete it.
It is added completely and all files are included, although some of them might previously be excluded.
Even if the file was originally Anonymous=No, it is added with Anonymous=yes
As soon as I remove the file from the Tribler download location, it is normally deleted!!!!

**Comment by qstokkink** [comment]
With the merge of #3260, all of the mentioned issues *should* be fixed.
