### ISSUE TITLE
Uninstall folder is grayed

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3227]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.
Nov 14th version
##### Tribler version/branch+revision: #####
Tribler 7
##### Operating system and version: #####
Windows 10 Insider 17025
##### Steps to reproduce the behavior: #####
Install Tribler on d: drive!
Install new version and it wants to uninstall from "c:\Program files\Tribler" uninstall input box is grayed, so unable to change and nothing is deleted from d: 
##### Expected behavior: #####
Uninstall correctly removes files from d: location
##### Actual behavior: #####
Nothing it deleted and during install some files are deleted.
My C: is an SSD and to prevent it from wearing I want to install on D: until the final version arrives.

**Comment by xoriole** [comment]
Fixed with [PR #3234](https://github.com/Tribler/tribler/pull/3234)

**Comment by Nubro01** [comment]
Thanks

Van: Sandip Pandey [mailto:notifications@github.com]
Verzonden: woensdag 22 november 2017 15:00
Aan: Tribler/tribler
CC: Ron Nuberg; Author
Onderwerp: Re: [Tribler/tribler] Uninstall folder is grayed (#3227)


Closed #3227<https://github.com/Tribler/tribler/issues/3227>.
