### ISSUE TITLE
Change anonymity on a torrent: torrent gets removed

### ISSUE THREAD

**Issue by sirber** [Tribler/tribler#3231]
##### Tribler version/branch+revision: #####
Latest 7 RC

##### Operating system and version: #####
Ubuntu 17.10

##### Steps to reproduce the behavior: #####
Right click a torrent, change anonymity.

##### Expected behavior: #####
Torrent keeps downloading

##### Actual behavior: #####
Torrent disappear

**Comment by devos50** [comment]
Thank you for your report. Could you please try the latest version (https://jenkins.tribler.org/job/Build_Tribler_next/149/) to see whether this is fixed?

**Comment by sirber** [comment]
the linked version, tested on windows, do not show the reported issue
