### ISSUE TITLE
Tribler GUI is slow to start (especially with a detached core)

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#3233]
##### Tribler version/branch+revision: #####

3c27358561f525829728c81a9aa01e930f5a38a7 devel

##### Steps to reproduce the behavior: #####

1. Start stand-alone core
2. Start `./tribler.sh`

##### Expected behavior: #####

The window shows up rather fast

##### Actual behavior: #####

Python modules for entire core (twistd, wallet, keyring) get loaded (even though core isn't started) before GUI can show up.

@devos50

**Comment by devos50** [comment]
We don't support a detached core anymore. Therefore, I close this issue.

**Comment by vi** [comment]
Why no detached core?

How to run Tribler headless then? Or how to economize computer resouces when GUI is not needed? Or how to make downloads keep going even when GUI crashes with error?

**Comment by qstokkink** [comment]
@devos50 isn't a detached core vital for the GUI/Core milestone?
