### ISSUE TITLE
Self sovereign identity - group 10

### ISSUE THREAD

**Issue by GijsWeterings** [Tribler/tribler#3236]
# 
# IdentityChain

Students:

- @GijsWeterings
- @LiamClark
- @Schubbcasten
- @Recognition2
- @eanker

Repository:
https://github.com/GijsWeterings/IdentityChain

## Self-Sovereign Identity

IdentityChain is a Self-Sovereign Identity app based on [TrustChain](https://www.sciencedirect.com/science/article/pii/S0167739X17318988). It aims to facilitate a system where identity can be decentralized, and give control of the use of identity data back to the user. Identity in this case is built up from all attestations made between the user and other parties. Each block on the TrustChain is signed by the user and a second party, and contains a zero knowledge proof.

## Zero knowledge proof

In the IdentityChain app zero knowledge range proofs can be generated, proven and verified.
The implementation is build upon the paper “[An Efficient Range Proof Scheme](http://ai2-s2-pdfs.s3.amazonaws.com/6bdb/0c85de3b38113c30c99b63a9fb48190af73e.pdf)” by Kun Peng and Feng Bao. This means that we can proof a number is in a certain range, without disclosing the number itself. For example, you can proof that you are older then 18 whilst buying alcohol, without telling your real age. 

## Network discovery and communication

The IdentityChain app is designed for local, face-to-face interactions. To facilitate the process of connecting between devices, IdentityChain makes use of [*Network Service Discovery*](https://developer.android.com/reference/android/net/nsd/NsdManager.html) **(NSD). 

On startup, the app announces itself to the network. Other devices running the app on the same network can now discover the peer device, and connect directly via local IP.

Once a peer connection is made, a gRPC channel is set up between the devices, which is encrypted to ensure safe communication.

## Attestations

A peer can request attestation for a certain claim from another peer. He will send a half-block containing a zero-knowledge proof. This creates an attestation request on the side of the attestee. This request can be accepted or rejected and when accepted the zero knowledge proof gets verified and the block gets then signed and sent back to the requester.

## Verifications

The IdentityChain app can also verify blocks created by other people. 
Verification is an interactive protocol between the attestee and the verifier.
This protocol checks all parameters of the zero-knowledge proof.

## Screenshots
![](https://d2mxuefqeaa7sj.cloudfront.net/s_FA4A66FA020261CFD77B30A0A2A8A0ED2DCFDCCA43BE7FE0E43C51BDC0108A30_1516112314899_photo_2018-01-16_15-18-24.jpg)
![](https://d2mxuefqeaa7sj.cloudfront.net/s_FA4A66FA020261CFD77B30A0A2A8A0ED2DCFDCCA43BE7FE0E43C51BDC0108A30_1516112314924_photo_2018-01-16_15-18-16.jpg)
![](https://d2mxuefqeaa7sj.cloudfront.net/s_FA4A66FA020261CFD77B30A0A2A8A0ED2DCFDCCA43BE7FE0E43C51BDC0108A30_1516112314887_photo_2018-01-16_15-18-12.jpg)

![](https://d2mxuefqeaa7sj.cloudfront.net/s_7E0F2799B0BC058100BF18AE103A87F799551F3662E2E6ECDB446F519043D9F8_1516113708440_file.png)

![](https://d2mxuefqeaa7sj.cloudfront.net/s_7E0F2799B0BC058100BF18AE103A87F799551F3662E2E6ECDB446F519043D9F8_1516114327169_file.png)

**Comment by qstokkink** [comment]
**W.I.P.**
I will keep track of overall information for your project in this post.

**Comment by qstokkink** [comment]
Heads up:
Your first meeting is `21st November 2017, 14:30`

**Comment by qstokkink** [comment]
For next meeting `5th December 2017`:

 - Have a functional Blockchain implementation
 - Have a functioning ZKP implementation

**Comment by qstokkink** [comment]
First and foremost: best wishes for 2018!
Your meeting tomorrow will be in this building:
https://www.google.nl/maps/dir//51.9990903,4.3785233/@51.999109,4.3785435,18.08z/data=!4m2!4m1!3e2?hl=en
In room 3.420 (third floor).

**Comment by eanker** [comment]
@qstokkink We would like to have our presentation on the 26th of januari is that possible for you?

**Comment by qstokkink** [comment]
@eanker for me it's fine: please send out an e-mail to the course instructors so we can check if the other instructors are available.

**Comment by synctext** [comment]
```convert -delay 200 -loop 0 iden*jpeg iden*png identitychain_all.gif```
![identitychain_all](https://user-images.githubusercontent.com/325224/35620813-8ae10a08-0682-11e8-8cda-34fa52313013.gif)

**Comment by Schubbcasten** [comment]
First release including the report can be found here:

https://github.com/GijsWeterings/IdentityChain/releases/tag/v1.0.0
