### ISSUE TITLE
TrustChain: Build you own blockchain - group 1

### ISSUE THREAD

**Issue by boninggong** [Tribler/tribler#3237]
You will create your own blockchain, almost from scratch. Your blockchain will be special! Your blockchain will be the first in the world to operate on smartphones exclusively. Your blockchain will not need servers, miners, consensus nodes, PCs, central entities, oversight bodies, governments, banks, or any other impurity. Just phones. Your blockchain should not rely on any server, require no infrastructure, and trust no entity except itself. It thus also becomes increasingly attack-resilient and with offline support it will not even depend on The Internet itself.

The two students helping you as TAs in this course have already implemented a starting point for you. You will build upon their work and create an operational Android-based implementation capable of talking to the live network. The protocol is Trustchain, the 3rd generation blockchain created by TUDelft scientists. Read the scientific paper. A more extensive master thesis from mathematics is also available.

TrustChain is capable of creating trusted transactions among strangers without central control. This enables new areas of blockchain use with a focus on building trust between individuals. Our innovative approach offers scalability, openness and Sybil-resistance while replacing proof-of-work with a mechanism to establish the validity and integrity of transactions. TrustChain is a permission-less tamper-proof data structure for storing transaction records of agents. We create an immutable chain of temporally ordered interactions for each agent. It is inherently parallel and every agent creates his own genesis block. TrustChain includes a novel Sybil-resistant algorithm named NetFlow to determine trustworthiness of agents in an online community. NetFlow ensures that agents who take resources from the community also contribute back. We demonstrate that irrefutable historical transaction records offer security and seamless scalability, without requiring global consensus. Experimentation shows that the transaction throughput of TrustChain surpasses that of traditional blockchain architectures like Bitcoin. We show by using extracted data from a live network that TrustChain has sufficient informativeness to identify freeriders, leading to refusal of service.

The live network can be seen here in a real-time overview. Your "Part I" starting point for software engineering can be found here on Github. Documentation on Android Trustchain. A key element of your "Part II" project is to implement networking. Another Delft project to take inspiration from is creating an academically pure Android-to-Android overlay, with it's own live deployment on Google Play.

Functionality to implement in your Android app: take a photo, sign this photo, publish on your blockchain, browse the Trustchain of others, validate their chain signatures, see their signed photos, and optionally support offline features.

Group Members:
@ClintonCao
@TimBuckers
@Michieldoesburg
@LaurensWe
@boninggong

**Comment by ClintonCao** [comment]
TODO for next sprint:
- Read TrustChain documentation.
- Read and checkout Android TrustChain implementation.
- Get familiar with overlay.
- Android - App to App communication. 
- Bitcoin transaction gossip.
- Plan in a meeting with the TAs

Next meeting with Johan: **28 November 2017**

**Comment by ClintonCao** [comment]
TODO for next sprint:
- Read about Churn models 
- Overlay should be Churn resilient and attack resilient

**Comment by boninggong** [comment]
Meeting 04-12-2017

TODO:

- Username screen en sending over app to app network.
- Local information activity to show a users name, IP etc.
- Show list of connections that are open only.
- Make connectection screen of two users more user friendly, see the illustration below.
- Create option to user input message to the connected user.
- Clear console with user friendly output that makes clear what is happening.

**Comment by synctext** [comment]
Update:
- integrated app-to-app communicator with Trustchain
- will do upstream PullRequest _today_
- next step: polish, overlay and IPv8 live integration

**Comment by synctext** [comment]
![image](https://user-images.githubusercontent.com/325224/33603945-964ed370-d9b4-11e7-8821-0e39897767e6.png)

**Comment by laurensWe** [comment]
Normally the GUI in the working case: 

![trustchain android test](https://user-images.githubusercontent.com/11706242/33603996-bbf1fc56-d9b4-11e7-8f52-77964e5704d4.png)

**Comment by synctext** [comment]
In a future sprint, link to: https://github.com/Tribler/tribler/issues/3272

**Comment by boninggong** [comment]
Sprint and tasks for week 2.4, see issues and assignees on the fork repository.

Next meeting with Johan: **12 December 2017 - 16:00**

**Comment by synctext** [comment]
Status update:
- software engineering Quality Assurance !
- ToDo: 4G and 3G communication
- PR with upstream app
- talk to wallet team
- future sprint: inbox indicator of pending signature requests (hint in main screen, detail when clicked)
- polish

**Comment by TimBuckers** [comment]
Update afgelopen week:

* Tests (Junit and Espresso unit tests) reached 25% code coverage with exclusion of activities.
* Public keys: 
   * Sent over p2p messages (before Trustchain communication)
  * Stored along with origin net address in cache. 
* Blockchain explorer
  * View your own Trustchain
  * View others Trustchain 
  * Trustchain visually more clear 
    * Colors based on publicKey
  * Info page
* Information screen about the color scheme of the connections and Trustchain
* Change initial bootstrap address
  * Remembering last used IP address
  * Input validation

![current state trustchain android](https://user-images.githubusercontent.com/9843576/34162019-9f4dd042-e4d2-11e7-9f3b-6b5fc70ef012.png)

**Comment by synctext** [comment]
Progress:
- [cool Travis coverage report](https://codecov.io/gh/ClintonCao/CS4160-trustchain-android/commits)

**Comment by TimBuckers** [comment]
![image](https://user-images.githubusercontent.com/9843576/34727645-deca1574-f557-11e7-89f9-df9124e79179.png)

**Comment by synctext** [comment]
Sprint feedback:
- mbox as first screen ?!? only claim lower screen row, inbox notifier on front page.
- ToDo 3rd time: 4G and 3G communication fix
- refactor UDP messaging: merge direct IPv4:port connect of trustchain and app-to-app stack.

**Comment by synctext** [comment]
Final documentation is contribution to: http://trustchain-android.readthedocs.io/

**Comment by synctext** [comment]
- new release asap
- merging direct connect TCP IPv4:port with the app-to-app stack nearly complete
- modified Introduction-request message to include ```username``` in the hashmap (UserNameStorage)
- new release not today; expected next week
- stability; observed a app crash. magic is to catch exceptions.

**Comment by synctext** [comment]
Talking to @wkmeijer and @klikooo about the app. Testing with few phones and latest Google Play code with inboxes. Overlay is a bit better, but still mostly broken. Friday I will feature this app at Stanford. Would be nice if it's in better shape. Thnx.

**Comment by synctext** [comment]
btw Seems that the bootstrap server keep old IPv4 numbers/peers for hours.
Unconnectable peers should be purged after 5-ish failed attempts or a few minutes timeout by the overlay.

**Comment by laurensWe** [comment]
Latest release:
https://github.com/ClintonCao/CS4160-trustchain-android/releases

**Comment by laurensWe** [comment]
Short url: http://bit.ly/2n2l8rQ

**Comment by synctext** [comment]
Photo donated to the Public Domain. No copyrights claimed.
![overlay_android_manual_test__jan2018](https://user-images.githubusercontent.com/325224/35271864-b435387a-0033-11e8-8f35-c9b10b6f34cd.jpg)

**Comment by TimBuckers** [comment]
![img_20180123_114422](https://user-images.githubusercontent.com/9843576/35271985-0047ecf8-0034-11e8-9d5a-ba2c5884c8dd.jpg)

**Comment by TimBuckers** [comment]
![screenshot_20180123-115803](https://user-images.githubusercontent.com/9843576/35272244-df07f924-0034-11e8-927f-b605a7dc2def.jpg)

**Comment by TimBuckers** [comment]
![img_20180123_120604_547](https://user-images.githubusercontent.com/9843576/35272542-d955cc58-0035-11e8-8862-f0294017fea5.jpg)

**Comment by synctext** [comment]
Status?
- as always, primary function of overlay: 3G 4G
- compare to app-to-app original code and connectability
- readthedocs (walkthrough of overlay, view chain, send mesg, inbox, sign ; in 5-ish screenshots)
- polish is low priority.

**Comment by wkmeijer** [comment]
@synctext This latest version is now available as an update in the [play store](https://play.google.com/apps/testing/nl.tudelft.cs4160.trustchain_android).

**Comment by devos50** [comment]
@wkmeijer maybe could you also publish the APK on the Github repo (https://github.com/wkmeijer/CS4160-trustchain-android/releases)?

**Comment by synctext** [comment]
Thnx,updated.
Mental notes on versioning.. New abilities or security features are hard to deploy. Any update of an overlay is required to know and understand the version of peers it sees. Updates MUST either create a new isolated network akin to a hard fork or be fully backwards compatible.

**Comment by boninggong** [comment]
The screenshots for a walkthrough of the app can be downloaded from: https://drive.google.com/open?id=1OwmJVxRF91V9ENGMebDRsIhpUZIavFjR

We will include these later in the readthedocs file and give a more descriptive explanation of each step and all the functions that are implemented.

**Comment by synctext** [comment]
```convert -delay 150 -loop 0 1\-* [2-9]* 1[1-9]* all.gif```
![trustchain_android__signature_requests_and_mailbox](https://user-images.githubusercontent.com/325224/35418338-f8bca6cc-0231-11e8-966a-ad82eee456d5.gif)

**Comment by TimBuckers** [comment]
The final Pull Request is online https://github.com/wkmeijer/CS4160-trustchain-android/pull/81
This includes:
- Documentation added: Read the docs completed and read me finished
- Extra comments in the code 
- More Tests
- Final small improvements 

@synctext

**Comment by synctext** [comment]
Quick feedback on performance for input to grading:
- good testing, with multiple types of tests and approaches https://codecov.io/gh/ClintonCao/CS4160-trustchain-android
- taking code ownership, added test of other people code
- quality of code and engineering excellence
  - aggressive 5 second overlay with operational 3G and 4G connectivity
  - real-time update of signatures and signed blocks
  - working block crawler and inbox
- documentation in .html or .pdf not directly linked, two added chapters, 3-ish pages each. Did not take ownership of all docs or added themselves to author list.
- positive work ethic
