### ISSUE TITLE
Growing Life using Blockchain - Group 7

### ISSUE THREAD

**Issue by Erackron** [Tribler/tribler#3238]
Group members:
- @TCatshoek
- @JWooning
- @TheFrog
- @harapuia
- @Erackron

**Comment by devos50** [comment]
Relevant literature:
- https://repository.tudelft.nl/islandora/object/uuid%3A08841cf0-8ddf-4354-9c99-bc7c270d67fd

**Comment by jwooning** [comment]
Todo's week 1:
- Lezen van beide papers
- Zorgen dat code draait
- Overleg met andere groep over Cloudomate
- GitHub projecten forken (PlebNet, Cloudomate)
- Kijken hoe we testen kunnen aanpakken (lastig met unittests en bitcoins e.d.)
- Nadenken over wat we doen met Bitcoins die server verdient

**Comment by TheFrog** [comment]
In the existing code, the following parts must be tested:

- claudomate
- PletNet
- market (Tribler)
- reputationCoins (Tribler)

Innovation ideas:

- VPN
- Agents communications
- Alternative sources of revenue: for example file hosting and/or trading
- Genetic algorithms: current usage and actual feasible usages (selectively seeding)
- Pricing and market

The decision has been made to first focus on getting the existing parts of the code working.

**Comment by jwooning** [comment]
We will focus on work for Claudomate first:
- Migrate to python3
  - Requires to change Mechanize to MechanicalSoup
- Support automatic buying of VPNs
- Fix broken VPS'
- Additional VPS providers
- Create shared BitCoin wallet for testing purposes

**Comment by TheFrog** [comment]
Already done:

- Python3 update
- Swap mechanize to mechanicalsoup

For cloudomate, fixing providers is a work in progress:
- Blueangelhost (@Erackron)
- CCIHosting (@jwooning)
- Crowncloud (@Harapuia)
- Legionbox (@TCatshoek)
- Linevast (@jwooning)
- Pulseservers (@TheFrog)
- Rockhoster (@Erackron)
- Underground (@TheFrog)

Furthermore, @TCatshoek will try to take a look at the payment providers and actually paying for a server.

**Comment by TheFrog** [comment]
Now working are:

- Blueangelhost
- CCIHosting
- Legionbox (triggers fraud detection, trying to circumvent this)
- Linevast
- Pulseservers
- Rockhoster (support for new payment needed)
- Underground

Work must still be done on:
- Crowncloud
- Legionbox
- Rockhoster

**Comment by Erackron** [comment]
# Meeting with previous project owner
## VPS Providers
### Current Provider notes
- BlueAngelHost: full e-mail domain was blocked
- Linevast: Worked pretty well
- Crowncloud: Instant termination on DMCA
- Rockhoster: Took a long time for VPS to be delivered (multiple days)
- Underground: Cheaper options are practically always 'out of stock'

### New options suggested by previous project owners
- OffshoreDedi: https://offshorededi.com/
- FloKiNet: https://flokinet.is/
- AMinServe: https://aminserve.com/
- AbeloHost: https://abelohost.com/
- HideMyHost: http://www.hidemyhost.com/

### Promising new options that would still have to be investigated
- ChunkHost: https://chunkhost.com/
- AlexHost: https://alexhost.md/
- Leaseweb: https://www.leaseweb.com/
- Shinjiru: https://www.shinjiru.com/
- Alibabahost: https://alibabahost.com/
- Hostkey: https://hostkey.com/
- WRZHost: https://wrzhost.com/

## Cloudomate OS compatibility
- Never tested on anything other than linux
  - Windows: Default binary does not have a CLI, python version does
  - OS X: CLI executable is located in default OSX locations instead of /usr/bin

## Possible Ideas:
- JSON RPC API instead of CLI
- Investigating Non-DMCA compliant hosters might be an idea to improve server longeivity

**Comment by TheFrog** [comment]
Todo's for the group are:

- Buying a (or two) server(s) @TCatshoek 
- Python3.4 support @Harapuia 
- Fixing Crownload @TheFrog
- Adding support for Coinpayments payment provider (for Rochester) @Erackron 
- VPNs: Code structure @jwooning 
- VPNs: List of providers
- VPNs: Implementing providers

Todo's that (for now) will not be done:

- Improving the code quality
- Adding more VPSs

**Comment by Erackron** [comment]
## VPN Provider options
### Requirements
**Must Have**
- Bitcoin payment option
- A scrape friendly website (no captcha)
- Favourable download/torrent policy (To allow tribler exit node traffic)
- OpenVPN support

**Should Have**
- BitPay/Coinbase as payment provider (speeds up integration with current cloudomate code)
- Favourable log storing policy (i.e.: not storing them)

### Providers that seem to match these criteria
- ExpressVPN: https://www.expressvpn.com/ (BitPay)
  Might have captcha for login though, so depends on the registration process and vpn config file
- IPVanish: https://www.ipvanish.com/ (BitPay)
- NordVPN: https://nordvpn.com/ (BitPay)
- PrivateInternetAccess: https://www.privateinternetaccess.com (BitPay)

**Comment by TheFrog** [comment]
More VPN providers that allow P2P traffic, accept Bitcoin payments, do not log traffic are, and support OpenVPN:

- AzireVPN
- ExpressVPN
- FrootVPN
- IVPN
- LiquidVPN
- Mullvad
- OVPN.com
- SecureVPN.to
- Trust.Zone
- VPNSecure

**Comment by TCatshoek** [comment]
Successfully bought a vps from legionbox. Transaction fees are going to be a problem though.

**Comment by TCatshoek** [comment]
Last sprint:
- [x] Buying a (or two) server(s) @TCatshoek
- [x] Python3.4 support @Harapuia
- [x] Fixing Crownload @TheFrog
- [x] VPNs: Code structure @jwooning
- [x] VPNs: List of providers @Erackron
- [ ] VPNs: Implementing providers

Next sprint:
- [ ] Automated integration tests up until payment for all providers
- [ ] Figure out a way to test clientarea
- [ ] Test vps with tribler and vpn
- [ ] Possibly a demo next week
- [ ] Mechanical turk for solving captchas (?)

Won't do:
- Dispersy (will take too much time)

**Comment by TheFrog** [comment]
For less than 10$/month, there are four VPN providers than conform to all must haves and should haves:

- LiquidVPN ($4,55/month)
- FrootVPN (€4,99/month)
- AzireVPN (€5/month)
- PrivateInternetAccess ($6,95/month)

**Comment by devos50** [comment]
Please remember that your meeting next week Tuesday (12:00) will be with Johan 👍

**Comment by Harapuia** [comment]
Forgot from last week:
Pull request accepted on Mechanical soup in order to fix compatibility with python 3.4
https://github.com/MechanicalSoup/MechanicalSoup/pull/171

**Comment by TCatshoek** [comment]
Next sprint:

- [ ] Get exit node working properly ( @tcatshoek )
- [ ] Test legionbox again, make sure demo is working properly ( @Harapuia )
- [ ] Buy another server, crowncloud, let @Harapuia know if it works ( @tcatshoek )
- [ ] Refactor vps hoster code ( @TheFrog, @Erackron ) 
- [ ] Demo propaganda (gifs, video, images, etc.) (everyone)
- [ ] More tests ( @jwooning )
- [ ] Refactor config ( @Erackron  )

**Comment by Erackron** [comment]
Next sprint:
- [ ] Make sure we can deploy on PyPi (@erackron) (preferably before 24th)
- [ ] Document rationale behind design decisions
- [ ] Finish VPS refactor (@TheFrog @Erackron)
- [ ] Finish commandline refactor (@Erackron)
- [ ] Figure out specific work points for PlebNet (@TCatshoek)
- [ ] Start work on PlebNet (@jwooning @TCatshoek @Harapuia)
- [ ] Fix PlebNet install scripts (@TCatshoek)
- ... More to come

Next meeting: 16th January 12:00

**Comment by synctext** [comment]
[For Stanford exposure](https://cyber.stanford.edu/bpase18) I need input for slides on 23Jan at the latest. PlebNet needs to be updated by 25Jan at the latest. Happy hacking!

**Comment by TCatshoek** [comment]
Plebnet todo:
- [ ] Convert to python 3
- [ ] Adapt to new version of cloudomate
- [ ] Update electrum dependency
- [ ] Check if we can update to the latest version of tribler (@devos50 ?)

**Comment by devos50** [comment]
Next meeting: Monday 22 January, 12:00. Please don't forget to post your progress + TODO list for this week on the ticket.

**Comment by devos50** [comment]
Please fix the errors during the unit tests, see https://jenkins.tribler.org/job/Cloudomate_PR_tests_linux/96/console

You can run the tests again by commenting 'retest this please' on the PR.

**Comment by TheFrog** [comment]
During our meeting last Tuesday we promised to propose a date for our final grading meeting. Taking into account our exams, we would like to propose January 29 in the morning. Is that possible @devos50 @synctext ?

**Comment by TheFrog** [comment]
Todo's for this week:
- [ ] Pull request @Erackron 
- [x] Images/animations for the Stanford demo, and the ReadMe @jwooning 
- [ ] Report @jwooning 
- [ ] Working PlebNet with the new version of Cloudomate, and placing this on a VPS @TCatshoek @Harapuia 
- [ ] Presentation @TheFrog
- [x] Hoster refactor @TheFrog @Erackron 
- [x] ClientArea clean-up and fixes @TheFrog @Erackron 
- [ ] Preparing demo @Erackron

**Comment by TheFrog** [comment]
Some GIFs that show how to use Cloudomate to purchase a VPS, a VPN and using a VPS (getting the status, connection through SSH).

![purchase_vpn](https://user-images.githubusercontent.com/3180670/35234057-3047e528-ffa0-11e7-9af4-d877d59c9406.gif)
![purchase_vps](https://user-images.githubusercontent.com/3180670/35234058-305cd0be-ffa0-11e7-99fb-d7c3bb2dea79.gif)
![ssh_vps](https://user-images.githubusercontent.com/3180670/35234059-3070d9ec-ffa0-11e7-9e19-681d62a26489.gif)

**Comment by TCatshoek** [comment]
As requested, a running exit node:

![exitnode_shorter](https://user-images.githubusercontent.com/5961113/35242599-482f466c-ffba-11e7-92db-4587452b675c.gif)

Source video: https://drive.google.com/open?id=18pT0Kyj6CqxTsXqc-F6txGZ3W0BFEeDL

**Comment by devos50** [comment]
Cloudomate 1.0 has been released, thanks for your contributions! https://pypi.python.org/pypi/cloudomate

**Comment by synctext** [comment]
https://twitter.com/TriblerTeam/status/956624056907849728
"We are experimenting with Self-replicating Autonomous Organisms (SAO). Today we released V1.0 of Cloudomate. It's a frameworks for online robots to buy new hardware, replicate, evolve. Part of our bandwidth token economy. Earn tokens as Tor-like exit-node. https://pypi.python.org/pypi/cloudomate "

**Comment by Erackron** [comment]
In terms of deliverables, here is the current modified plebnet code we'll be using for the demo: 
https://github.com/Erackron/PlebNet/tree/plebbeun/
Or in terms of a fixed commit: https://github.com/Erackron/PlebNet/tree/da287455d7d75674ba7d73aebd81357003343c43

The cloudomate code is already merged into https://github.com/Tribler/cloudomate
