### ISSUE TITLE
update our badges (really 318000 downloads)

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3254]
update our [Readme.rst](https://github.com/Tribler/tribler/blob/devel/README.rst) file with fancy stuff from https://shields.io/

badges: Do we really have 318000 downloads of Tribler ? wow.

https://img.shields.io/github/downloads/tribler/tribler/latest/total.svg

**Comment by qstokkink** [comment]
You can also do:
https://img.shields.io/github/downloads/tribler/tribler/v6.5.2/total.svg
To get the version info with the download count.
![](https://img.shields.io/github/downloads/tribler/tribler/v6.5.2/total.svg)

**Comment by devos50** [comment]
This will be fixed with an upcoming next-to-devel update.

**Comment by qstokkink** [comment]
Fixed.
