### ISSUE TITLE
tribler log filling up, since nov 15th build

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3255]
[ ] I have tried with the latest pre-release version and I still can reproduce the issue.
Yes
##### Tribler version/branch+revision: #####
Tribler 7 build nov 22th
##### Operating system and version: #####
Windows 10 Insider build 17046
##### Steps to reproduce the behavior: #####
 Start Tribler and log is filling up
##### Expected behavior: #####
Just relevant messages appering like before.
##### Actual behavior: #####
With just 3 files within the Library Messages keep appearing
[triblerlog-20171123.txt](https://github.com/Tribler/tribler/files/1498541/triblerlog-20171123.txt)

##### Relevant log file output: #####
Log attached!

**Comment by qstokkink** [comment]
You can set the logging levels in the [logger.conf](https://github.com/Tribler/tribler/blob/devel/logger.conf) file in your Tribler folder if the logging is too verbose for your tastes.

Removing `infoMemoryHandler` from this line will disable the INFO-level log completely:

https://github.com/Tribler/tribler/blob/f0e0493cef1bf41e1488b1034b221f5272e69f06/logger.conf#L12

**Comment by Nubro01** [comment]
Removing it from line 5, caused Tribler not to startup.
Undoing it and removing it from line 12 did not do the trick, messages kept coming.
Why change it and if you do tell us!~

Regards

Ron

Van: Quinten Stokkink [mailto:notifications@github.com]
Verzonden: donderdag 23 november 2017 10:48
Aan: Tribler/tribler
CC: Ron Nuberg; Author
Onderwerp: Re: [Tribler/tribler] tribler log filling up, since nov 15th build (#3255)


You can set the logging levels in the logger.conf<https://github.com/Tribler/tribler/blob/devel/logger.conf> file in your Tribler folder if the logging is too verbose for your tastes.

Removing infoMemoryHandler from this line will disable the INFO-level log completely:

https://github.com/Tribler/tribler/blob/f0e0493cef1bf41e1488b1034b221f5272e69f06/logger.conf#L12

**Comment by qstokkink** [comment]
@Nubro01 Weird, as a workaround you can also set the following to `ERROR` instead of `INFO`:

https://github.com/Tribler/tribler/blob/f0e0493cef1bf41e1488b1034b221f5272e69f06/logger.conf#L11

A fun fact: this is actually how Tribler logging was always supposed to work, it has just been broken for years and only recently fixed.

@xoriole Removing `infoMemoryHandler` from the handlers should not have crashed Tribler, or should it?

**Comment by Nubro01** [comment]
That worked. Thanks.

About the fun fact, The log used to be written out to a file in C:\Users\userid\AppData\Roaming, but since this beta, it appears in a Dos Command window, maybe this is because of Windows 10 Insider ???
The current file in that old location is only one kb and not filling up. Its creation date is 15/09/2017, so?
I would prefer that log to be written to a specific location and not this one because it is on an ssd, but I could always move it myself with an mlink or so.

Regards

Ron

Van: Quinten Stokkink [mailto:notifications@github.com]
Verzonden: donderdag 23 november 2017 11:50
Aan: Tribler/tribler
CC: Ron Nuberg; Mention
Onderwerp: Re: [Tribler/tribler] tribler log filling up, since nov 15th build (#3255)


@Nubro01<https://github.com/nubro01> Weird, as a workaround you can also set the following to ERROR instead of INFO:

https://github.com/Tribler/tribler/blob/f0e0493cef1bf41e1488b1034b221f5272e69f06/logger.conf#L11

A fun fact: this is actually how Tribler logging was always supposed to work, it has just been broken for years and only recently fixed.

@xoriole<https://github.com/xoriole> Removing infoMemoryHandler from the handlers should not have crashed Tribler, or should it?

**Comment by xoriole** [comment]
@Nubro01  
In addition to console logs shown previously, we have added additional handlers to write INFO and ERROR level logs to .Tribler/logs directory. These logs are useful for us in fixing/debugging the reported issues (if uploaded by the reporter).

`infoMemoryHandler` and `errorMemoryHandler` are responsible for writing INFO and ERROR level logs and written log files can be found inside .Tribler/logs directory. To disable writing the logs you can simply remove these handlers from LINE 12 (not from line 5) listed under `[logger_root]` section.

To prevent displaying the detailed logs on the console, setting the log level to ERROR should do the trick. To not show (almost) completely, you can remove the `default` handler from LINE 12.

**Comment by qstokkink** [comment]
@Nubro01 Yes, the console window is for debugging purposes. The official Tribler 7.0 release will not have this window.

@xoriole do you know if the default logging handlers support different file locations?

**Comment by xoriole** [comment]
@qstokkink default logging handler is StreamHandler which only displays the logs in the console. The other two handlers which write logs to file does not support different file locations as of current implementation and the default location is .Tribler/logs directory.
I think we can add the support for different file locations to the backlog for now.

**Comment by qstokkink** [comment]
@xoriole would you mind creating the issue for that (with some sort of indication of what we would need to change to facilitate the different locations)?

**Comment by Nubro01** [comment]
Quinten,

When monitoring the peers that I seed to, the report is very restless, new lines are added and delete all the time.
With version 6.5 one could sort the list on up or download speed, which made the report more easily to track.
I just opened an issue regarding the upload speed and cpu usage and I suddenly noticed an upload speed of 1.8 Mbs and because of the restless reporting, it was hard to find which ip address I was seeding. With the sort option it would have appeared on top of the list, so……

Regards

Ron

**Comment by devos50** [comment]
This issue should have been fixed already since we lowered the logging level for the tunnel messages from INFO to DEBUG 👍
