### ISSUE TITLE
Metainfo lookup seems to freeze the Tribler core under some circumstances

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3269]
I was browsing through the crash reporter and it looks like a request to `/torrentinfo` freezes the core (I observed this by subsequent requests timing out). This sometimes results in a crash since in PyQt, request callbacks are invoked with `None` if a timeout occurs.

I reproduced this error by clicking through the list of search results at a fast rate and managed to freeze the core for around 10 seconds. I also noticed that this usually happens when performing a DHT request.

Finally, this error happened for me on Mac but I also saw that it happened on Windows.

**Comment by qstokkink** [comment]
I believe this PR is supposed to fix it: https://github.com/Tribler/tribler/pull/3266
Can you check if that resolves it?

**Comment by synctext** [comment]
Great to see this progress!

500 people are going to hear about RC4 in our main auditorium. Hope we have it ready then..

btw Aug 2007, Bartercast launch, thinking of calling myself Blockchain Grandpa:-)

**Comment by synctext** [comment]
Wednesday 6Dec https://blockchaingers.org/events/tech-deep-dive
