### ISSUE TITLE
IPv8: testnet with 1000 nodes

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3272]
Problem: _numerous groups in the Blockchain Engineering class need a live Trustchain network to talk to._

A clean IPv8 network will be created on 1000 unique IPv4:port combinations without backward compatibility (Dispersy,PermID,etc.) 
This network will have actual data on their Trustchain and live edges #2979 #2458 .

For a good visualization and discussion of security matters, see: https://github.com/Tribler/tribler/issues/2623#issuecomment-324906432

**Comment by qstokkink** [comment]
I made a branch with a script to spawn 1000 IPv8 instances: https://github.com/qstokkink/py-ipv8/tree/1000instances

This will most likely fry the server though.
