### ISSUE TITLE
show the bandwidth usage of Tribler itself (minus Bittorrent traffic)

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3286]
For our expert users it is important to known what is going on and look at pretty graphs. See this nice [example from IPFS bitswap algorithm](https://github.com/ipfs/go-ipfs/issues/1750). Secondary motivation: show how Tribler has lower overhead then similar offerings.

![image](https://user-images.githubusercontent.com/325224/33829660-72e4e1f6-de71-11e7-8230-6da1ee2df8c5.png)

For debugging it is also very helpful to understand what is happening and going wrong. See for instance [how the IPFS people are getting bug reports with 8 GBytes of daily bandwidth usage for a full node](https://github.com/ipfs/go-ipfs/issues/3429). Their debugging info:
```
for p in /ipfs/bitswap/1.1.0 /ipfs/dht /ipfs/bitswap /ipfs/bitswap/1.0.0 /ipfs/kad/1.0.0 ; do echo ipfs stats bw --proto $p && ipfs stats bw --proto $p  && echo "---" ; done

ipfs stats bw --proto /ipfs/bitswap/1.1.0
Bandwidth
TotalIn: 0 B
TotalOut: 0 B
RateIn: 0 B/s
RateOut: 0 B/s
---
ipfs stats bw --proto /ipfs/dht
Bandwidth
TotalIn: 1.6 GB
TotalOut: 2.8 GB
RateIn: 2.9 kB/s
RateOut: 7.1 kB/s
---
ipfs stats bw --proto /ipfs/bitswap
Bandwidth
TotalIn: 7.3 GB
TotalOut: 47 MB
RateIn: 2.0 kB/s
RateOut: 0 B/s
---
ipfs stats bw --proto /ipfs/bitswap/1.0.0
Bandwidth
TotalIn: 0 B
TotalOut: 0 B
RateIn: 0 B/s
RateOut: 0 B/s
---
ipfs stats bw --proto /ipfs/kad/1.0.0
Bandwidth
TotalIn: 0 B
TotalOut: 0 B
RateIn: 0 B/s
RateOut: 0 B/s
```

**Comment by qstokkink** [comment]
@xoriole is this done now?

**Comment by qstokkink** [comment]
> @xoriole is this done now?

@xoriole small bump ⬆️

**Comment by drew2a** [comment]
I'm also curious "is this done now?" :)

**Comment by qstokkink** [comment]
Confirmation from @xoriole: we implemented the overlay statistics a few years ago.
