### ISSUE TITLE
We should consider supporting adding magnet links in RSS feeds to a channel

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3296]
Currently, we assume that all torrents in a RSS feed are provided with an HTTP/HTTPS uri. However, there are many feeds out there that provide their torrents with a magnet link (for instance, http://showrss.info/show/272.rss). They are currently not imported into your channel. We should perform DHT lookups for each of these torrents and add them to the channel. Note that this requires some refactoring and better twistification of the RSS feed parser.

**Comment by ichorid** [comment]
RSS feed parser is dead along with Dispersy.
