### ISSUE TITLE
visualisation of Tribler Internet traffic [EtherApe]

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3304]
We need to show to the user that they are part of a Tribe. This improves their sense of community and their social network around our protocols. Use something like [EtherApe](http://etherape.sourceforge.net/) in debug mode.

```
EtherApe is a graphical network monitor for Unix modeled after etherman.
Featuring link layer, IP and TCP modes, it displays network activity graphically.
Hosts and links change in size with traffic. Color coded protocols display.
It supports Ethernet, FDDI, Token Ring, ISDN, PPP, SLIP and WLAN devices, plus
several encapsulation formats. It can filter traffic to be shown, and can read packets
from a file as well as live from the network. Node statistics can be exported.
```

![image](https://user-images.githubusercontent.com/325224/34104174-b554cc9e-e3ef-11e7-9af8-ce98c4ab2ba5.png)

**Comment by ichorid** [comment]
Solved by trust graph
