### ISSUE TITLE
Tribler's streaming feature not working, instead forcing to stop the download as well.(probable bug)

### ISSUE THREAD

**Issue by katteasis** [Tribler/tribler#3310]
I have been using Tribler for quite some time now for downloading and streaming videos from torrents.It was working all fine and I liked it so much, but I am having trouble while streaming and downloading videos.

## Actual Problem:

I think It has all started when I updated to version 6.5.2, because I was using an older version, and t was working fine until last week when I updated to version 6.5.2.

**These days I can't stream video. When I click on stream it works file, starts the download and loading, but after sometime when loading reaches to 100 %, it automatically resets it to 0 again and stops downloading as well instead of playing the video.**

### I've tried to record a small video about the issue I'm reporting here.

https://youtu.be/jfsUqWQg9eY

___
As you can see in above video, instead of playing video starts to load again from 0 but never goes up. In fact it automatically stops the download as well. And when I try to resume the download it won't happen, first I have to stop the streaming. And again if I try to stream video it again stops the download.
____
***System I am Using: 64bit operating system, x64 based processor.
OS: windows 8 pro.
Processor: Intel Core I5***
____
#### How to reproduce this bug?

*  Search videos on tribler and select stream option which is supposed to stream torrent videos.
* Wait until video loads to 100 %,Now  it will stops loading instead of playing.
*  Go to download tab, you wil notice video has already stopped.
* Try resuming the download it won't work.
* Stop the streaming (which is not happening anyway) and try resuming download,now it will work.
<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@katteasis/tribler-s-streaming-feature-not-working-instead-forcing-to-stop-the-download-as-well-probable-bug">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by xoriole** [comment]
Thank you for reporting. Tribler 6.5.2 is not supported anymore. We're very close to releasing Tribler 7.0. We recommend you to try [Tribler 7.0.0-rc4](https://github.com/Tribler/tribler/releases) and let us know if you still have problem streaming.

**Comment by katteasis** [comment]
Thanks for Letting me know.
