### ISSUE TITLE
Eternal Tribler shutdown - USB storage

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3312]
Various events seem to create these never ending shutdown events (normally shotdown goes nicely fast now).
For instance, saving on a USB drive. Then Libtorrent can't find a file anymore and Tribler hangs in error unrecoverable state. How shall we communicate this difficulty to the user?

This can force users to force quit Tribler and having to reboot their computer (Mac), as Tribler has a background process. This stops Tribler from correctly restarting if another Tribler instance is still hanging.

![eternal_shutdown](https://user-images.githubusercontent.com/325224/34338682-6b843e0c-e96b-11e7-9e2b-725b068b5c0c.jpg)

**Comment by ichorid** [comment]
Fixed in 7.5
