### ISSUE TITLE
popup UI fail

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#3313]
##### Tribler version/branch+revision: #####
7 rc4

##### Operating system and version: #####
OS X 10.11.6

##### Steps to reproduce the behavior: #####
navigate without addressing a popup

##### Expected behavior: #####
UI continues to work

##### Actual behavior: #####
clicking on anything in the main window has no effect, popup outline is visible

**Comment by xoriole** [comment]
@Dmole Could you please elaborate which popup you are referring to?

**Comment by Dmole** [comment]
No; because only the outline is shown.

**Comment by devos50** [comment]
@Dmole could you post a screenshot?

**Comment by Dmole** [comment]
If it happens again.
I have since restarted it 2 times sending an auto bug report.

**Comment by xoriole** [comment]
@Dmole Have you encountered this issue in the latest version of Tribler (7.0.1)?

**Comment by Dmole** [comment]
This one was hard to reproduce, closing for now.
