### ISSUE TITLE
Trustchain daily transaction volume crawler and real-time visualisation 

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3318]
Compare Trustchain / IPv8 overlay live network. (only needed once we have usage). great network health monitoring tool.

Create live crawler with key metric for scientific publication. Create a graph of past years volume of Bitcoin, Etereum and possibly IOTA. Add our discovered transactions, half blocks, unique seen nodes, and daily active nodes.

Include pictures like:
https://pbs.twimg.com/media/DADx-06XYAETHSc?format=jpg

**Comment by devos50** [comment]
A Trustchain block explorer would also be very cool to have, something like https://blockexplorer.com and https://cardanoexplorer.com.

**Comment by qstokkink** [comment]
Storing all of the chains of the entire network will come at a significant resource cost though, also CPU-wise. We will need a beefy server to handle this.

**Comment by devos50** [comment]
Duplicate of #3508
