### ISSUE TITLE
Continuous request to /downloads leads to higher CPU usage

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3319]
In the GUI, we perform a request to `/downloads` every second, even when the downloads are not visible. This leads to higher CPU usage since libtorrent has to be queried and statistics have to be gathered and parsed. Additionally, this leads to additional file descriptors and 'pollutes' the history of requests in the crash reporter.

I propose to only perform a request to fetch downloads when the user actually has the page with downloads open. While this adds a small delay before users are able to see what they are downloading, I think it significantly saves resources in the long run. Also, this is quite easy to implement, requiring changing only a few lines of code.

@qstokkink @egbertbouman @xoriole @synctext what do you think?

**Comment by qstokkink** [comment]
I think it should be fine to stop it when the user leaves the downloads page.

In the worst case, if performance turns out to be unacceptable, we could also throttle down the amount of requests when the user is not viewing the downloads page.

**Comment by xoriole** [comment]
I also think it should be okay. We can verify that with some tests, of course.

As an alternative, what're your views on using WebSockets? A consistent reconnecting WebSocket connection between the core and the GUI, then the core could simply push the download updates (or anything) through it.

**Comment by qstokkink** [comment]
I will include this in #3328.

**Comment by devos50** [comment]
nice!
