### ISSUE TITLE
Jenkins performance suite to drive progress

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3325]
#1287 If you can't measure it, you can't improve it. Helps us focus on right things. Drives our forward progress. Ultimately run them for each PR: Any change should strictly improve the metric. Core Tribler features are: search, stream, and share. We need a single score number for each build. Capture average download speed accurately. How to measure spend CPU cycles? Our 8 core performance metrics: 
-‎anon stream
-‎anon download
-stream
-‎download
-‎search
-‎idle 24h
-‎anon seed
-‎first 1h bootstrap

inspiration,be an effective engineer:https://gist.github.com/rondy/af1dee1d28c02e9a225ae55da2674a6f

**Comment by devos50** [comment]
For example, see our existing Jenkins job (https://jenkins.tribler.org/job/Test_Tribler_idle_run_1H/1220/). A very basic improvement could be to extend this job with 20 pre-selected downloads (Ubuntu/Debian torrents).

![fd_usage](https://user-images.githubusercontent.com/1707075/37831093-92015320-2ea4-11e8-90cd-4e9df6e3acda.png)

**Comment by synctext** [comment]
@ichorid @xoriole Good plan. If the downloading is integrated (e.g. https://cdimage.debian.org/debian-cd/current/amd64/bt-dvd/debian-9.4.0-amd64-DVD-1.iso.torrent x 20) we can buy some servers with real remote links. Next week I can buy some https://flokinet.is/vps-server.php Romania & Iceland servers for usage as Jenkins_client.

**Comment by synctext** [comment]
We need to visit network-awareness issue again, after token economy is up and running in initial form. Redo [some work from 13 years ago](http://www.ds.ewi.tudelft.nl/~iosup/mprobe05gp2pc.pdf). Tribler becomes a portable network performance measurement lab. Tribler measures all available bandwidth after install. Within Jenkins and servers on various continents, it does this daily.
First step, do a simple download test, inform the user, like:
![image](https://user-images.githubusercontent.com/325224/37874839-201a5542-3037-11e8-9763-17f42d8ee606.png)

**Comment by ichorid** [comment]
I created a [Jenkins performance test](https://jenkins.tribler.org/job/Performance_tests) for 1-hop download on a local machine. It sets up Seeder<->Router<->Leecher test on the loopback device of isolated "bare-metal" machine, and produces simple download speed plots, like this one:
![result](https://user-images.githubusercontent.com/2509103/40484201-0cdecd8e-5f5b-11e8-9321-a335b612339c.png)

The test runs on daily schedule.

Suggestions for further modifications are welcome.

**Comment by devos50** [comment]
@ichorid nice!

It would be nice to extend the test a bit and let the Jenkins job fail when no data is being transmitted at all during the test. Next, I can add jour performance test to the nagios checker and we monitor the job.

**Comment by qstokkink** [comment]
Cool. I guess you could also run it multiple times and produce a shaded error bar plot so we can judge stability.

**Comment by devos50** [comment]
After some discussion, we conclude that we by now have an extensive set of tests on Jenkins, both for validation and performance. Therefore, we believe that we can close this issue.
