### ISSUE TITLE
TORrentcoin

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3326]
This is the overview issue for the launch and mining pool organisation of TORrentcoin.

Token mining against media censorship.

Our work combines the two key fully decentralised technologies ever created by computer experts: Bittorrent and blockchains, plus we add TOR-like privacy.

**Comment by xoriole** [comment]
To make it a success, it is important that users perceive the value of bandwidth tokens. Looking at the current userbase of Tribler, we see there are some users more active than others and have a large balance. We should try to increase the interactivity of the user using bandwidth tokens. For this, we should support
- donation to the channel
- transfer bandwith to the user (public key)

**Comment by synctext** [comment]
Yes. Possible uses of our token:
- Reward content creators through their their channels.
- Trade tokens on the marketplace
- Direct transfer of tokens to any other user

Artists get 100% of spendable tokens. No other ecosystem gives the full reward to content creators. Other ecosystems sometimes take 30% cut of all revenues and are build for rent seeking.

**Comment by qstokkink** [comment]
I'll close this issue because I don't think we'll EVER launch a mining pool organisation.
