### ISSUE TITLE
Deployment tests failing occasionally

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3327]
I noticed that our deployment tests are failing occasionally, possibly due to the fact that the core cannot be reached with HTTP requests. Also, machines are sometimes not rebooting after a rollback. After manually starting these machines, it usually works again.

**Comment by xoriole** [comment]
Moved most of the windows & ubuntu server to the new server and the deployment tests seem pretty stable so I'm closing this issue for now.
