### ISSUE TITLE
using pkgr to publish Linux/BSD releases?

### ISSUE THREAD

**Issue by fenollp** [Tribler/tribler#3332]
What do you think about using https://packager.io to automatically build & publish releases?
It creates dedicated apt/yum repos. It's free for open source projects. I am not affiliated with them.

If you like this I'm ready to provide help. I'd rather install from apt than from a deb.

**Comment by qstokkink** [comment]
Thanks for the heads-up, the functionality certainly seems desirable. I do not like the fact that we need to sacrifice/authorize a GitHub account to the `packager.io` gods though (but this can of course easily be solved by a throwaway account).

@devos50 what do you think?

**Comment by devos50** [comment]
@fenollp thank you for your suggestion. We already have the functionality to build `.deb` files in our own Jenkins server (https://jenkins.tribler.org/job/Build-Tribler_Ubuntu-64_next/) and this build works ok. Sending it to an apt repo would be a nice addition.

I see on their website that 'Currently, you can package applications written in Ruby, NodeJS, or Go.' and Tribler is written in Python so I'm not sure how that would work outs. However, if you think it's somehow possible, please feel free to contribute! You could create a fork of the Tribler repository and try it out if you want 👍

**Comment by qstokkink** [comment]
We've come a long way since this issue was created. By now, we're (almost) exclusively depending on GitHub Actions to build and publish.
