### ISSUE TITLE
What is the correct function to stop and remove a download?

### ISSUE THREAD

**Issue by EinNarr** [Tribler/tribler#3333]
I tried several functions. Most of them doesn't work properly.
function **stop** in class **LibtorrentDownloadImpl** works well, but it do not provide ability to remove the download or content.

function **stop_remove** in class **LibtorrentDownloadImpl** do not work properly if **removecontent** flag is given True. With removestate=True, removecontent=True it cannot stop anything. With removestate=False, removecontent=True it doesn't remove the content at all

function **remove_download** in class **Session** works better, but it randomly cannot stop some of the torrents, which happens quite often.

So...What should be the correct way to do this?

**Comment by qstokkink** [comment]
Starting and stopping downloads should be done through the Session (so yes `Session.remove_download()` is the one you need).

If you add and remove downloads through the Session and `yield` for the deferreds they return, you *should* never have any issues. If you do: please provide a minimal example so we can fix it.

**Comment by EinNarr** [comment]
@qstokkink 
Here it is how I called it. Without the '#' of course.
https://github.com/EinNarr/tribler/blob/CreditMining_operation/Tribler/Core/CreditMining/BoostingTorrent.py#L169
It works sometimes. There are always some tasks that are not stopped or removed after calling this function.

**Comment by qstokkink** [comment]
The function returns a Deferred object for which you need to wait. You can either use [`blockingCallFromThread`](http://twistedmatrix.com/documents/13.2.0/api/twisted.internet.threads.blockingCallFromThread.html) or [`@inlineCallbacks` and `yield`](http://twistedmatrix.com/documents/10.2.0/api/twisted.internet.defer.inlineCallbacks.html) to accomplish this.

Because the rest of your code seems to be fully synchronous I suggest using `blockingCallFromThread` in your case.

**Comment by EinNarr** [comment]
I tired with blockingCallFromReactorThread, inlineCallbacks and yield. It is still acting the same.

I suppose if I am not using any of them, if I wait long enough, the download should be eventually stopped. But that is not happening.

**Comment by qstokkink** [comment]
Can you create a minimal example?

**Comment by EinNarr** [comment]
I found it is actually not the problem of libtorrent not deleting the torrent. It is more likely that GUI is not aware of the update. I am looking up the code to find what is behind this. #3354

**Comment by devos50** [comment]
I will close this issue. Let's continue the discussion in #3354.
