### ISSUE TITLE
multichain community not found after upgrade

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3342]
When upgrading from Tribler 6.4.3 (and probably 6.5 from informal testing) towards the latest V7.0.0-rc4-40-g1f66204 the multichain community fails to load.

Reproduced on an Ubuntu 16.04 LTS box with the following Megacache (old, created on Jan 15  2017 with V6.4.3):
[no_multichain_after_upgrade_from_Tribler_6.4.3.tar.gz](https://github.com/Tribler/tribler/files/1622020/no_multichain_after_upgrade_from_Tribler_6.4.3.tar.gz)
Please investigate using these .Tribler files or a freshly made one to test integration and upgrade scripts. This .Tribler contains two non-anonymous downloads of CreativeCommons content and a single channel vote. 

![image](https://user-images.githubusercontent.com/325224/34819338-bc591b04-f6bd-11e7-8058-3694ba99c94d.png)

![image](https://user-images.githubusercontent.com/325224/34819377-d69090e2-f6bd-11e7-9645-e6001a72b284.png)

**Comment by devos50** [comment]
Thanks for reporting and providing the state dir! I managed to reproduce it so let's see what's the cause of this error.
