### ISSUE TITLE
Check for zombie Tribler instance at start up

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3348]
When Tribler is force killed or exits due to some unexpected error, it sometimes leaves behind a zombie core process and subsequent relaunch of Tribler fails.

One solution to this issue could be to check for such processes and kill it before starting the fresh instance of Tribler. But the issue with this approach is that it could lead to database or data corruption if the previously running instance was writing to disk.

For now, I suggest using a popup dialog to inform the user if there is already running instance of Tribler and ask the user if he wants to force restart. A caution message could also be included in the pop up to indicate the possibility of data corruption.

![tribler-warning](https://user-images.githubusercontent.com/1442867/34871545-66edbca2-f78e-11e7-97d6-daa0944fb7b0.png)

**Comment by EinNarr** [comment]
Seconded. This is quite an common and annoying issue. If possible I wish it could also be a feature in terminal so that I won't need to check and kill process after every crash.
