### ISSUE TITLE
In certain situation, the downloadspage in Tribler GUI is displaying torrents that are already deleted

### ISSUE THREAD

**Issue by EinNarr** [Tribler/tribler#3354]
![screenshot from 2018-01-14 12-35-30](https://user-images.githubusercontent.com/15276621/34915728-71ebce5c-f92b-11e7-9e0f-1774091268f7.png)
All the download tasks in this screenshot is deleted already by calling session.remove_download(), and they are actually already removed from the libtorrent, but they keep showing up in the page.
I am still looking up the code to see what's behind this.

Please enlighten me if anyone knows what could be the reason of this.

**Comment by qstokkink** [comment]
For some reason, the `LaunchManyCore.downloads` dictionary still contains them then. This means that [`remove()`](https://github.com/Tribler/tribler/blob/devel/Tribler/Core/APIImplementation/LaunchManyCore.py#L433) was not called, or errored out somehow.

**Comment by EinNarr** [comment]
I will check that. However, the reply from download_endpoint is correct, without all the "ghost torrents".
Could also be simply display problem.

**Comment by qstokkink** [comment]
That is interesting. Then you should check out [`downloadspage`](https://github.com/Tribler/tribler/blob/devel/TriblerGUI/widgets/downloadspage.py) in the TriblerGUI and check out the `download_widgets` dict.

**Comment by EinNarr** [comment]
Update: It seems to be Qt problem. downloadpage.window().downloads_list.columnCount() is returning constant value(13 at first when there are 10 downloads), but the actual number of downloads visible keeps growing.

**Comment by EinNarr** [comment]
Bug found: it is within downloadpage.on_received_downloads(). The remove download code cannot handle multiple torrents removed at the same time, thought it designed to do.
It first record the index of all "to be delete" widget, and then delete all of them. However, delete one widget would change the index of all widgets after it. This could cause the problem that the widget cannot be found and delete, and it could even delete wrong widget, causing the widget for some torrents are forever missing.
I will open a PR for this.

**Comment by EinNarr** [comment]
#3355

**Comment by devos50** [comment]
Thanks for finding and pinpointing this problem 👍

**Comment by devos50** [comment]
Fixed by #3355
