### ISSUE TITLE
Generally need catch encoding exceptions

### ISSUE THREAD

**Issue by EinNarr** [Tribler/tribler#3365]
GUI and loggers in Tribler seem not to catching encoding problems. (logger seems only support ASCII and GUI supports Unicode?)
![screenshot from 2018-01-18 12-59-14](https://user-images.githubusercontent.com/15276621/35097195-727c6454-fc4f-11e7-8bbd-6f52521a6255.png)

**Comment by devos50** [comment]
As far as I know, we fixed most unicode errors when adding downloads. Please rebase after merging #3364  on the latest `devel` branch and try again.

**Comment by devos50** [comment]
Since we cannot reproduce it, we close this issue.
