### ISSUE TITLE
CI for latest devel is broken

### ISSUE THREAD

**Issue by vandenheuvel** [Tribler/tribler#3367]
See https://github.com/Tribler/tribler/pull/3366.

**Comment by qstokkink** [comment]
This is solved by #3364

**Comment by vandenheuvel** [comment]
Do you know which specific commit solves this issue?

**Comment by qstokkink** [comment]
@vandenheuvel c9e0526fd47254ef4bde67addbffcc60f94e309e should be the one

**Comment by vandenheuvel** [comment]
Thanks!

**Comment by qstokkink** [comment]
👍
