### ISSUE TITLE
TestSearchCommunity.test_torrent_search is not deterministic on Linux

### ISSUE THREAD

**Issue by vandenheuvel** [Tribler/tribler#3373]
See [test #5762](https://jenkins.tribler.org/job/GH_Tribler_PR/5762/) and [test #5763](https://jenkins.tribler.org/job/GH_Tribler_PR/5763/). Both test c5038c57df8b6131d4cce1af00e5630252fba53f but the first fails TestSearchCommunity.test_torrent_search while the second passes.

**Comment by qstokkink** [comment]
We are switching to a different AllChannel and Search structure, see #3489.
