### ISSUE TITLE
Tribler 7 download badge and download stats

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3398]
__lowest priority__

For accurate recordkeeping... Additional non-Github Downloads: 190,861
[From our early days at SF.NET](https://sourceforge.net/projects/tribler/files/stats/timeline?dates=2006-02-06%20to%202018-01-25&period=daily).

![download_stats_sourceforge__2006-2018](https://user-images.githubusercontent.com/325224/35392083-f0f803a6-01e0-11e8-90b8-b3d1eccc0e8d.png)

Download counter on Tribler.org frontpage could also use the SourceForge.net stats where Tribler was register on Feb 2006. We're still missing the roughly 1.8 million direct downloads we had from Tribler.org directly in Delft. Those statistics also need sorting out at some point.

```
2006-02 | 0
2006-03 | 19,509
2006-04 | 16,590
2006-05 | 27,365
2006-06 | 8,562
2006-07 | 3,728
2006-08 | 4,090
2006-09 | 5,102
2006-10 | 4,795
2006-11 | 2,648
2006-12 | 2,959
2007-01 | 2,762
2007-02 | 2,175
2007-03 | 4,128
2007-04 | 1,368
2007-05 | 1,144
2007-06 | 292
2007-07 | 286
2007-08 | 259
2007-09 | 339
2007-10 | 399
2007-11 | 220
2007-12 | 170
2008-01 | 170
2008-02 | 166
2008-03 | 154
2008-04 | 197
2008-05 | 152
2008-06 | 135
2008-07 | 198
2008-08 | 116
2008-09 | 132
2008-10 | 275
2008-11 | 217
2008-12 | 159
2009-01 | 105
2009-02 | 56
2009-03 | 104
2009-04 | 81
2009-05 | 61
2009-06 | 112
2009-07 | 139
2009-08 | 204
2009-09 | 197
2009-10 | 183
2009-11 | 194
2009-12 | 226
2010-01 | 325
2010-02 | 90
2010-03 | 135
2010-04 | 138
2010-05 | 58
2010-06 | 108
2010-07 | 43
2010-08 | 52
2010-09 | 65
2010-10 | 65
2010-11 | 159
2010-12 | 156
2011-01 | 68
2011-02 | 52
2011-03 | 31
2011-04 | 23
2011-05 | 50
2011-06 | 17
2011-07 | 42
2011-08 | 26
2011-09 | 110
2011-10 | 128
2011-11 | 26
2011-12 | 11
2012-01 | 13
2012-02 | 187
2012-03 | 71
2012-04 | 37
2012-05 | 19
2012-06 | 15
2012-07 | 58
2012-08 | 1,529
2012-09 | 1,380
2012-10 | 1,380
2012-11 | 1,222
2012-12 | 1,588
2013-01 | 1,502
2013-02 | 1,364
2013-03 | 1,355
2013-04 | 1,251
2013-05 | 1,131
2013-06 | 1,952
2013-07 | 1,543
2013-08 | 1,130
2013-09 | 985
2013-10 | 956
2013-11 | 1,557
2013-12 | 1,774
2014-01 | 1,406
2014-02 | 1,451
2014-03 | 1,795
2014-04 | 1,541
2014-05 | 1,629
2014-06 | 1,425
2014-07 | 1,494
2014-08 | 1,864
2014-09 | 1,188
2014-10 | 1,056
2014-11 | 1,162
2014-12 | 1,240
2015-01 | 1,531
2015-02 | 1,194
2015-03 | 1,054
2015-04 | 1,056
2015-05 | 909
2015-06 | 798
2015-07 | 852
2015-08 | 902
2015-09 | 890
2015-10 | 936
2015-11 | 750
2015-12 | 971
2016-01 | 1,200
2016-02 | 1,102
2016-03 | 1,863
2016-04 | 1,784
2016-05 | 1,123
2016-06 | 1,097
2016-07 | 1,731
2016-08 | 1,215
2016-09 | 779
2016-10 | 943
2016-11 | 815
2016-12 | 819
2017-01 | 836
2017-02 | 663
2017-03 | 722
2017-04 | 604
2017-05 | 608
2017-06 | 528
2017-07 | 568
2017-08 | 599
2017-09 | 494
2017-10 | 721
2017-11 | 690
2017-12 | 1,110
2018-01
```

**Comment by synctext** [comment]
After my retirement I will write a book and re-open this issue :book: :boom:

**Comment by qstokkink** [comment]
@synctext I think we can actually solve this issue to a certain extent: at least the README badge part.

The CSV that you can download from SourceForge only contains the total number of downloads per month, not the downloads per release. That is a bummer. However, you can do something like this:

https://img.shields.io/badge/downloads@%3C7.02-10_Quadrillion-green (`-` is the separator and `%3C` is the `<` symbol)
![](https://img.shields.io/badge/downloads@%3C7.02-10_Quadrillion-green)

If we manually sum the downloads we can provide both the pre-SF and the SF badge ourselves.

**Comment by qstokkink** [comment]
How about the following instead of our current list of download badges?

![](https://img.shields.io/badge/total_downloads_pre_2006-1.8M-brightgreen) ![200,635](https://img.shields.io/badge/total_downloads_SourceForge-200k-brightgreen) ![](https://img.shields.io/github/downloads/Tribler/tribler/total?label=total%20downloads%20GitHub) ![](https://img.shields.io/github/downloads/Tribler/tribler/latest/total)
