### ISSUE TITLE
Unicode Download Location crash on Linux

### ISSUE THREAD

**Issue by VNovotna** [Tribler/tribler#3421]
#### Please, fill all relevant items: ####

- [*] I have read CONTRIBUTING.rst

- [*] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
next on a733321cc168ce8a0a8564c365f1c9f028f4e22b
also tested on v7.1.0-mining-preview and 7.0.0

##### Operating system and version: #####
Arch Linux x64, kernel 3.14, Gnome Shell, all up to date

##### Expected behavior: #####
Start file download

##### Actual behavior: #####
UnicodeEncodeError and crash 

##### Steps to reproduce the behavior: #####
Set download directory to something with unicode. Mine was `/home/viky/Stažené`.
The original `/home/viky/TriblerSomething` was ok. 

##### Relevant log file output: #####
in `~/.Tribler/logs/tribler-gui-error.log`
```
ERROR   1517352358.56  tribler_window:84    Traceback (most recent call last):
  File "/home/viky/tribler/TriblerGUI/tribler_window.py", line 488, in on_start_download_action
    self.dialog.dialog_widget.files_list_view.topLevelItemCount())
  File "/home/viky/tribler/TriblerGUI/tribler_window.py", line 321, in perform_start_download_request
    encoded_destination = destination.encode('hex')
  File "/usr/lib/python2.7/encodings/hex_codec.py", line 24, in hex_encode
    output = binascii.b2a_hex(input)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u017e' in position 14: ordinal not in range(128)
```

**Comment by VNovotna** [comment]
Similar crash happens also when starting Tribler and having unicode character in path where Tribler is:
```
Traceback (most recent call last):
  File "run_tribler.py", line 25, in <module>
    from TriblerGUI.tribler_window import TriblerWindow
  File "/home/viky/Stažené/tribler/TriblerGUI/tribler_window.py", line 25, in <module>
    from TriblerGUI.debug_window import DebugWindow
  File "/home/viky/Stažené/tribler/TriblerGUI/debug_window.py", line 22, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvas
  File "/usr/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 14, in <module>
    line for line in traceback.format_stack()
  File "/usr/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 16, in <genexpr>
    if not line.startswith('  File "<frozen importlib._bootstrap'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 22: ordinal not in range(128)
```
In this case Tribler crash on start without even showing UI.

**Comment by qstokkink** [comment]
The first issue in op is because hex encoding can't deal with unicode, this should be an easy fix:

```
>>> a = u'\u017e'
>>> a.encode('hex')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\encodings\hex_codec.py", line 24, in hex_encode
    output = binascii.b2a_hex(input)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u017e' in position 0: ordinal not in range(128)
```

The second issue is within the `matplotlib` dependency. That is a nasty one, we should discuss how to fix this.

**Comment by qstokkink** [comment]
Small update on the second half of this issue: this is a bug in newer versions of matplotlib, because of their misuse of `unicode_literals`. Here is the minimal example extracted from https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/__init__.py : 

`Stažené.py`:
```python
from __future__ import unicode_literals

import traceback

_backend_loading_tb = "".join(line for line in traceback.format_stack())
```

I don't think we can fix this from our codebase.
