### ISSUE TITLE
Fatal error:pyi_rth_qt5

### ISSUE THREAD

**Issue by otofoto** [Tribler/tribler#3450]
Tribler 7 x86: Failed to execute script pyi_rth_qt5

OS: Windows XP

It seems that PyQt5/Qt5 is no longer support Windows XP. See http://doc.qt.io/qt-5/windows-issues.html

Both Products (XP, 2003 Server) are EOL and have no longer support from Microsoft.

For XP support need to compile PyQT5 with "-target xp" switch (see link above)

**Comment by devos50** [comment]
Thank you for your report. We don't support Windows XP anymore. Supporting this platform would take a significant amount of time for us and we have to recompile many of our libraries. Tribler should be compatible with newer versions of Windows (at least Windows 7).
