### ISSUE TITLE
How to change save path/directory destination for saving torrent payload files?

### ISSUE THREAD

**Issue by slrslr** [Tribler/tribler#3454]
##### Tribler version/branch+revision: #####
7.0.0 x64 downloaded today from tribler.org, previously i used alpha version so i have %appdata%/.Tribler from previous version. Before alpha i had 6.x verion.
##### Operating system and version: #####
Windows 10 64bit
##### Issue: #####
When i go to Downloads section, i see my torrents there and i click one of them and on Details tab i see "Destination" (save path, directory where payload should be saved), but i can not find how to change it / relocate torrent data. I know i can manually find appropriate file and edit it: C:/Users/Username/AppData/Roaming/.Tribler/dlcheckpoints/torrentmagnethere.state , but how to do that in Tribler?

**Comment by devos50** [comment]
@slrslr unfortunately, moving torrents to another location is not supported at the moment. We will consider adding this to Tribler!

**Comment by ichorid** [comment]
Related to #4222

**Comment by ichorid** [comment]
Solved long time ago by someone. The feature is there now for quite some time :shrug:
