### ISSUE TITLE
AttributeError: 'SettingsPage' object has no attribute 'dialog_widget'

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3459]
From reporter - Tribler 7.0.1 (#12564)
> Changed log file directory while Tribler was running

Traceback (most recent call last):
File "TriblerGUI\widgets\settingspage.py", line 76, in on_choose_log_dir_clicked
AttributeError: 'SettingsPage' object has no attribute 'dialog_widget'

**Comment by devos50** [comment]
This is probably fixed already.
