### ISSUE TITLE
blockchain for health

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3477]
The outcome of our first brainstorm session within the medical domain:
![blockchain__healthcare_architecture_v1](https://user-images.githubusercontent.com/325224/36596799-3275c9d0-18a7-11e8-97f8-e7b225842b82.png)
_Disclaimer: this is just a starting point for discussion and discover flaws in our simplistic thinking._

The goal is to see if we can formulate a realistic field trial as a very light-weight attempt to learn-by-doing. The above system architecture depicts the most simple use-case involving 1 person from each stakeholder. 80% of the above technology pieces have already been created in other projects by the Tribler team. But never used in this context. Integration and applying domain expertise is expected to take the majority of time.

This trial brings key innovations to the healtcare sector:
- self-sovereign identities and digital signatures
- personal medical records
- **[straight-through processing](https://scholar.google.com/scholar?q=straight-through+processing) of electronic business transactions** 

The key enabling technology is the blockchain, which makes the trust of the government portable (e.g. legally-valid electronic signatures). Many economic sectors have already transitioned beyond batch processing and week-long delays within backoffices with manual checks of paper-based information. This trial consists of digital trusted information flows between strongly authenticated parties. By using encrypted information flows on our scalable blockchain datastructure we achieve tamper-proof record keeping. For authentication we aim to integrate in due time with eIDAS _high_ compliant mechanisms. We have an operational prototype as an alternative for the UZI-pas, using our patent-free [software-based PUF](#3064); using physics as a foundation for security. Where possible we should use the message and protocol specifications approach of the MedMij organisation ([see in Dutch only](https://afsprakenstelsel.medmij.nl/display/PUBLIC/Architectuur+en+technische+specificaties)). Their system architecture is based technologies like Oauth and TLS (central-server based). This will cause cause problems with a self-sovereign approach. For instance _De PKI-O-certificaten dienen aangeschaft te worden bij een vertrouwensdienstverlener, zoals Logius_.

Our work is based on the pioneering work of [HIE of one](http://hieofone.org/). This volunteer-driven  (e.g. @shihjay2) initiative realized the state-of-the-art in the field by [connecting](https://noshemr.wordpress.com/) uport, OpenID, HIE authorisation server, and a electronic health record system. Their mobile app can login to several dozen hospitals and retrieve medical records. [whitepaper](https://github.com/Tribler/tribler/files/1752231/HIE.of.One.White.Paper.pdf)
![image](https://user-images.githubusercontent.com/325224/36597307-04b4a8c0-18a9-11e8-9dca-0ea80e44426f.png)
Our approach is not as sexy as MIT proposals. We propose to first apply approaches with established effectiveness discovered 20-ish years ago, before trying experimental and unproven technology. Whitepapers from MIT (not peer reviewed scientific publications) [propose to solve the data, privacy, and security in healthcare using multiparty crypto tricks](https://www.healthit.gov/sites/default/files/1-78-blockchainandhealthitalgorithmsprivacydata_whitepaper.pdf). We have some experience there. In prior work from we fully implemented and evaluated the efficiency of [additively homomorphic encryption, namely the Paillier cryptosystem](https://cora.ucc.ie/bitstream/handle/10468/4767/Zeilemaker_Erkin_Palmieri_et_al_WIFS2013.pdf). This stuff is not yet ready to leave the lab.

As an initial step to obtain participation and feedback, the 4 students of TUDelft will implement a first demo in coming weeks. This demo will measure the willingness of various parties to explore options and conduct a field trial. Background information: Prof.dr. Wouter [van Solinge](https://www.youtube.com/watch?v=OI_u4pml-5o) has done pioneering work at UMC Utrecht with personal eHealth apps ([in dutch only](http://www.umcutrecht.nl/nl/Over-Ons/Nieuws/2016/Patienten-UMC-Utrecht-krijgen-eigen-regie-in-zorg)). 

We have initial participation of RvIG, the identity provider in our Kingdom.

**Comment by synctext** [comment]
First concrete step: 
- add support for attestations in Trustchain app
- find libs such as https://github.com/scipr-lab/libsnark and https://github.com/bbuenz/BulletProofLib
- how to handle UX of well known trusted public keys of municipalities (QR scan? +add to trusted keys address book)
- integrate BSN claim and government certificate proof
- possible goal: attestation of birth (official doctor attestation, claim of parent and doctor; genesis baby block)

**Comment by synctext** [comment]
Clear roadmap for coming 2 weeks:
- make the trustchain app maintainable - [big refactor to make it long-term viable](https://github.com/klikooo/CS4160-trustchain-android/branches)
- Core features:
  - trustchain: scalable blockchain on Android
  - android-to-android overlay: no PC needed
  - IPv8 attestations: zero-knowledge proofs, claims and attestations using [BulletProofLib](https://github.com/bbuenz/BulletProofLib)
  - scan of government-issued identity proofs using NFC
  - code coverage, docs and solid unit tests
- update Trustchain on App Store, continuous integration, just put it live...
- Future possibilities: [https://github.com/abhn/marvel](Marvel - Face Recognition With Android & OpenCV) and our own [open source fingerprint lib Fingerblox](https://play.google.com/store/apps/details?id=org.fingerblox.fingerblox)

**Comment by shihjay2** [comment]
Thanks for the mention to the [HIE of One](https://github.com/shihjay2/hieofone-as).  Your discussion here is very interesting to us; I'm including [Adrian Gropper](https://github.com/agropper) who works with me on the HIE of One project.  We are both happy to assist and to also learn from your discussions how we can leverage self-sovereign identity, blockchain to our goals of improving health information technology, security, and privacy.

**Comment by qstokkink** [comment]
https://github.com/qstokkink/ipv8-android-app/blob/master/app/src/main/java/org/ipv8/android/restapi/json/AttestationRESTInterface.java

**Comment by synctext** [comment]
Progress reporting:
- refactor & rewrite [protocol buffers now used extensively](https://github.com/klikooo/CS4160-trustchain-android/blob/2_claim_functionality/app/src/main/java/nl/tudelft/cs4160/trustchain_android/appToApp/PeerHandler.java)
  (prior path SQLite storage, then ProtoBuf, into appToApp, then BEncode, finally UDP sockets)
  - single [.proto file](https://github.com/klikooo/CS4160-trustchain-android/blob/2_claim_functionality/app/src/main/java/nl/tudelft/cs4160/trustchain_android/Message.proto) not only trustchain, but also appToApp shared between them.
```
message TrustChainBlock {
    bytes public_key = 1;
    int32 sequence_number = 2;
    bytes link_public_key = 3;
    int32 link_sequence_number = 4;
    bytes previous_hash = 5;
    bytes signature = 6;
    Transaction transaction = 7;
    google.protobuf.Timestamp insert_time = 8;
``` 
- please add ```transaction_type``` inside trustchain for role, claim, and other record types.
- important observation: using QR codes gives the self-sovereign citizen the feeling of control over the information flow, wireless communication is too abstract. Same reason that government officials with a "control reflex" prefer QR codes above wireless. (read it, you can steal it; problem of QR codes)
- Bulletprooflib](https://github.com/bbuenz/BulletProofLib) works ! But just Android 8.0 and higher. As we seen yesterday, the Stanford algorithms have acceptable performance for 4-bits, but not for real-world cases. Thus we need Quinten zero-knowledge Python REST API matters probably.
- currently attestations is 1978 technology: signed with private key certificates. 
- [IPv8 attestations](https://github.com/qstokkink/ipv8-android-app/blob/master/app/src/main/java/org/ipv8/android/restapi/json/AttestationRESTInterface.java) can be used as Python backend, simply send/receive binary claim blobs and True/False tests.

**Comment by synctext** [comment]
Progress to date:
- [Trustchain + overlay: .proto Single Protocol Buffer message definition](https://github.com/klikooo/CS4160-trustchain-android/blob/master/app/src/main/java/nl/tudelft/cs4160/trustchain_android/message/Message.proto)
- 8548 lines of generated code by Protocol Buffers [serialising and de-serialising each message](https://github.com/klikooo/CS4160-trustchain-android/blob/master/app/src/main/java/nl/tudelft/cs4160/trustchain_android/message/MessageProto.java) into a byte array for UDP messaging.
- TUDelft implementation by @qstokkink of [zero-knowledge proof](https://github.com/qstokkink/py-ipv8/blob/master/ipv8/attestation/wallet/primitives/attestation.py#L137).
- No out-of-sleep feature on Android. dead overlay.
- update ```on_packet()``` every second a screen refresh and update message-timeout values on screen.
- design and implement a [fault-resilient overlay](https://www.google.nl/search?q=how+to+design+an+overlay+network). **make flawless**. Add last send message + got last response message
- seen passport scan NFC work! (also crash upon requesting permissions).

Core [Network.java](https://github.com/klikooo/CS4160-trustchain-android/blob/master/app/src/main/java/nl/tudelft/cs4160/trustchain_android/network/Network.java#L172) code :
```
        MessageProto.Message.Builder messageBuilder = MessageProto.Message.newBuilder()
                .setSourcePeerId(hashId)
                .setDestinationAddress(ByteString.copyFrom(peer.getAddress().getAddress().getAddress()))
                .setDestinationPort(peer.getAddress().getPort())
                .setPublicKey(ByteString.copyFrom(publicKey.toBytes()))
                .setType(INTRODUCTION_REQUEST_ID)
                .setPayload(MessageProto.Payload.newBuilder().setIntroductionRequest(request));

        sendMessage(messageBuilder.build(), peer);
```

**Comment by synctext** [comment]
Status:
- zero-knowledge proof: not yet operational in Java
- timer added for UDP packets
  - please make it easy to understand
  - From / To directionality and simply a counter which jumps to "0".
  - :arrow_left: and :arrow_right:
- claims and attestation in GUI, first version
- Next sprints:
  - see example [attestation IPv8 docs by Dan](https://github.com/DanGraur/IPv8-documentation)
  - networking stress test
  - goal (see above): attestation of birth (official doctor attestation, claim of parent and doctor; genesis baby block)
  - code coverage travis and codecov ?

**Comment by synctext** [comment]
Good progress. Tomorrow is demo day.. Is newest version on Google.play? Can you please add a "release version" into the info tab, for instance?

**Comment by wkmeijer** [comment]
The newest version will be online in a few hours, finalizing the last tests for backwards compatibility now. I'll also come by to update the bootstrap phone.

**Comment by wkmeijer** [comment]
We did another [small release](https://github.com/klikooo/CS4160-trustchain-android/releases/tag/0.303) to the play store with some minor fixes:
- added a notice that the app is still running on exit through home button
- fixed bug where all chains were displayed as "my chain"
- fixed bug where peers in chain explorer weren't named correctly
- fixed pop-up loop in ocr scanning when denying permissions

**Comment by synctext** [comment]
Progress:
15,513 additions and 6,513 deletions in [Pull Request](https://github.com/wkmeijer/CS4160-trustchain-android/compare/master...klikooo:master). Out of which 9234 is outgenerated from app/src/main/java/nl/tudelft/cs4160/trustchain_android/message/MessageProto.java.
Simple Android studio build

Final sprint: 
- theme ```performance analysis``` and maturity of code
- code coverage with graphs/pictures in report _.rst format_
- integrate blinking lights with the Send and Receive text. Only update every 500ms
- stress test at scale and documented results with actual graphs
  - indicate mobile phone provider, wifi details, phone model
  - 100 nodes per phone, solid network...
  - KByte of traffic in time
  - connection health (lot of incoming traffic while others have little incoming traffic)
  - profiling
- claim and attestation [documentation](https://tools.ietf.org/html/draft-pouwelse-trustchain-01#section-4.2) for your implementation
- offline block signing and _documentation_

**Comment by wkmeijer** [comment]
The[ last release](https://github.com/klikooo/CS4160-trustchain-android/releases/tag/0.310) is now also available in the play store.
[Documentation](http://trustchain.readthedocs.io/en/latest/) is up to date. Jonathan is finishing creating the performance graphs, so they will be visible on readthedocs tomorrow.

Things that changed since last time:

- Fixes for UI glitches for long usernames
- Update UI response when message is received
- Offline block sending functionality through QR codes and Android Beam
- Stress testing functionality, one phone can now start numerous peers for stress testing
- Connection statistics

All the code is on https://github.com/klikooo/CS4160-trustchain-android for now. The documentation is on http://trustchain.readthedocs.io. This can be moved to the wkmeijer/CS4160-trustchain-android and the trustchain-android.readthedocs tomorrow.

**Comment by wkmeijer** [comment]
Todo's:
- Signed introduction requests, currently unsigned message with public key, unicode username and ip address
- offline send, user may be confused when the reply step is completed
- sequence number in mutualblock (in inbox) is not displayed correctly
- mychain collapses the directed graph into a list, which is difficult to display. Currently the chain is odered on sequence numbers that occurs first in a block, so it mixes the peer and in the linked peer.
- Passport scan results never leave your device, not stored on any blockchain.
- Can communicate and sign bytes with passport chip.
- 3g/4g connection only works with KPN/Telfort network, T-Mobile (confirmed), Vodafone (confirmed), Tele-2 (confirmed) have a carrier grade nat which blocks incoming connection.

**Comment by synctext** [comment]
@klikooo implement binary transfer. summer project
- enable generic remote electronic signature of any .PDF file or picture
- [Micro Transport Protocoll 4 Java](https://github.com/iiljkic/utp4j)

**Comment by synctext** [comment]
Related master thesis 2019: "[MediTrail: a blockchain-based tamper-proof auditable access log for medical data](https://repository.tudelft.nl/file/File_17372aae-eaf5-4050-ae99-c5a5a6148647)
