### ISSUE TITLE
Anonymous download speeds are slower when using threadpool message handling instead of reactor thread message handling

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3482]
When fixing the tunnel experiment on the DAS5, I noticed that it's faster to have IPv8 handle messages on the reactor thread than on the thread pool, how counter-intuitive it may sound. This experiment has been performed with a single exit node and no intermediate relays.

When handling messages on the thread pool:

![07a34c4cbd2cae54c3fef5dfd4bf658737033d3a_speed_down](https://user-images.githubusercontent.com/1707075/36736204-5014ce08-1bd8-11e8-85d9-219fc8e6f144.png)

When handling messages on the reactor thread:

![cdc2629ebd3da6c06725509c69a66668d41d6202_speed_down](https://user-images.githubusercontent.com/1707075/36736222-5ae011da-1bd8-11e8-965e-c712544149a7.png)

I probably need to do some more experimentation to find out why this happens but right now, this is not my highest priority 👍 . @qstokkink do you have any ideas?

**Comment by qstokkink** [comment]
Some background, the threadpool switch is as follows:

```python
if listener.use_main_thread:
    blockingCallFromThread(reactor, self._deliver_later, listener, packet)
elif reactor.running:
    reactor.callInThread(self._deliver_later, listener, packet)
```

This means that `blockingCallFromThread` provides better throughput than `reactor.callInThread`. This is pretty strange.

**Comment by synctext** [comment]
Is this experiment repeatable?

**Comment by qstokkink** [comment]
Memo: we should check out the Twisted version (should be >=17).

**Comment by devos50** [comment]
@qstokkink I'm using the latest version of Twisted on bbq (where I run my anon download experiment):

```
>>> import twisted
>>> twisted.__version__
'17.9.0'
>>> 
```

@synctext it's repeatable, however, I made some changes already to my experiment. I think it's a good idea that we create a stand-alone anonymous download experiment (with just 1 exit node) that downloads a torrent and plot the download speeds after the experiment is done. This experiment should run every night and fail if there are no transferred bytes. We can hook this up to our Nagios checker.

**Comment by qstokkink** [comment]
I just profiled the CPU usage and calls, comparing the `blockingCallFromThread` with `reactor.callInThread`.

- The `reactor.callInThread` spends much less CPU time than `blockingCallFromThread`, as expected.
- The per-function call count doesn't differ much.

For some unknown though, the `blockingCallFromThread` method is noticably faster for the higher-level community functionality.

**Comment by devos50** [comment]
We now only use the thread pool for the tests and the `callFromThread` in production.
