### ISSUE TITLE
Explore using Libtorrent as our database, filesystem, and dissemination solution

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3484]
Seed, stop seeding, modify file/blob, redo hash check, seed.

Block alignment is essential. Bittorrent pieces align with fixed-sized Trustchain records? Or variable size? Filesystem for multiple chains?

First: seek related work! This stuff has been beaten to death in the past 30 years. Post papers, architectures, ideas.

**Comment by ichorid** [comment]
We could use [Linear Tape File System](https://github.com/LinearTapeFileSystem/ltfs) for this stuff.

**Comment by ichorid** [comment]
As everyone will have their own blockchain/filesystem, it would be reasonably fast. And one could defrag it sometimes, cleaning the unneeded stuff. To do incremental updates, one could use torrent "update torrent" feature, adding new variable-sized blocks in the form of files. This could be described as a "streamed filesystem".
The only problem I could see with this approach is the problem of updates latency. It is not very well suited for usage scenarios that require sub-second updates.

**Comment by qstokkink** [comment]
We could use this: [https://www.libtorrent.org/manual-ref.html#ssl-torrents](https://www.libtorrent.org/manual-ref.html#ssl-torrents) for tying the libtorrent download to the channel owner's public key on the transport level (SSL).

**Comment by arvidn** [comment]
there's even a [mutable_torrent_support](https://libtorrent.org/reference-Create_Torrents.html#flags_t) flag for ``create_torrent()``, to configure it to pad large files to be piece aligned.

**Comment by qstokkink** [comment]
@arvidn thanks, it seems we wont even need to make it a merkle tree torrent with our structure then.

**Comment by qstokkink** [comment]
Moved the development of this to my fork: https://github.com/qstokkink/tribler/blob/allchannel2/Tribler/community/allchannel2/structures.py

**Comment by devos50** [comment]
Random idea: dissemination of content metadata could be rewarded with bandwidth tokens when being performed over anonymous tunnels (see ticket #3337). This would work better if we have (a set of) thumbnails attached to each content torrent. Whether this reward scheme is a good idea or not, is open for discussion. We could even provide something like 'hidden channels' where channel content metadata is only seeded over end-to-end tunnels. I'm not sure about the legal implications of this though.

**Comment by qstokkink** [comment]
@devos50 In principle I think this is a good idea. I also added a secret feature in #3489 to directly store metadata alongside the magnetlinks in the channels. Providing incentive to share the channels would be good.

It does strike me as overkill for most channels to actually use tunnels for infohash dissemination. Actually downloading the channel contents might lend itself more to anonymization & payout.

This brings up another question: should you be paid equally for relaying tunnel traffic, exiting tunnel traffic and sharing channels? Should it be a marketplace which can be mined?

**Comment by synctext** [comment]
Lets keep things as simple as possible for 2018..

**Comment by qstokkink** [comment]
#3489

**Comment by synctext** [comment]
Attacking Merkle Trees with a second preimage attack https://news.ycombinator.com/item?id=16572793

**Comment by ichorid** [comment]
TrustChain blocks can have arbitrary size and contents. Currently, we store the user's TrustChain in the SQLite database and spread it out using IPv8 queries. But TrustChain is, by definition, an _append-only_ data structure. This means we can write it into a file on disk as it grows, and periodically publish it in a torrent, as we do with GigaChannels.

In fact, GigaChannel already features simple and efficient code to do just that: periodically dump binary data into file chunks, dynamically compressing the dumped data with LZ4 (and serving queries through IPv8).
GigaChannel allows us to hone our methods of managing collective-access to append-only data created by users. If it proves to be successful, eventually **GigaChannel can become one with TrustChain**.

As a first step towards this goal, we could add sidechain support to TrustChain, so we can experiment with various forms of sidechain offloading.

**Comment by synctext** [comment]
Please focus on a minimal viable PR. This is outside the sprint scope. We have another ticket on using torrents for Trustchain, it seems like a smart idea. We will explore later.

**Comment by ichorid** [comment]
@synctext , this was exactly my point: we first finish the current GigaChannel PR and release 7.2. Then, when we get enough experience with using Libtorrent as a channels dissemination engine we continue with this issue (TrustChain merging).

**Comment by devos50** [comment]
We believe this issue has been sufficiently addressed with our recent gigachannel efforts. We are now using libtorrent as underlying mechanism to disseminate magnet links and metadata.
