### ISSUE TITLE
[BSc Seminar] Exploring the scalability of various blockchains

### ISSUE THREAD

**Issue by clenrock** [Tribler/tribler#3488]
This ticket will contain the progress of the Bachelor Seminar course.

Project description:
Supervisor: @devos50 

Blockchain technology holds the promise to transform the way trust is cultivated between strangers. Bitcoin created money without the need for banks. In the past, people were required to trust a central bank and a host of other intermediaries when making payments. The fundamental technology of Bitcoin, blockchain, radically reduced the need to trust financial middlemen. It bootstrapped an economy where no one can be stopped from spending their money. Despite widespread speculation and ecosystems being worth billions, blockchain in general suffers from scalability issues due to inefficient mechanisms for fraud prevention. Bitcoin is theoretically limited to seven transactions per second and Ethereum has a throughput of around 20 transactions per second. There have been various scalability efforts like proof-of-stake, sharding and tree-like block graphs, however, broader adoption of blockchain stays out. Recent work of our group explores more scalable solutions with unbounded scalability by using a novel technique called implicit consensus. Our experimentally evaluated consensus mechanism dubbed CHECO has superior scalability compared to other solutions. The goal of this project is to review the scalability of (recently proposed) blockchain solutions. Due to the abundance of proposed cryptocurrencies, you should select the most interesting and/or scalable blockchain fabrics and briefly evaluate them in your survey. The evaluation should be focussed on public, permissionless blockchain ledgers. Note: this is a challenging assignment, recommended only for honour students or potential cum-laude students. Prior knowledge of blockchain is helpful but not required. References

Vukolić, Marko. "The quest for scalable blockchain fabric: Proof-of-work vs. BFT replication." International Workshop on Open Problems in Network Security. Springer, Cham, 2015. Ren, Zhijie, et al. "Implicit Consensus: Blockchain with Unbounded Throughput." arXiv preprint arXiv:1705.11046 (2017).

**Comment by clenrock** [comment]
The version of the paper:
[exploration-state-art.pdf](https://github.com/Tribler/tribler/files/1875600/exploration-state-art.pdf)

**Comment by devos50** [comment]
Lightning feedback (in addition to the feedback provided yesterday):

- make the first sentence of abstract amongst these lines: _the limited throughput of many blockchain solutions prevent the adoption of this relatively new technology at larger scales_ (here you immediately explain the problem)
- in the abstract, explain what you're doing (i.e. _this paper conducts an exploration of state-of-the-art blockchain solutions that aim to address the scalability problem. By doing X and Y, we conclude Z_). Take a look at the abstract of other surveys.
-_Nowadays a lots of companies make_ -> _Many companies provide value by acting as the intermediary during transactions..._ or _the business model of many companies is based on acting as the intermediary..._
- replace the word 'banks' by financial institutions (slightly more general)
- consider adding this graph to your paper (2nd page, at the top of the page): https://blockchain.info/nl/charts/avg-confirmation-time. Maybe you can find a better graph that demonstrates the scalability problem?

**Comment by clenrock** [comment]
The final snapshot of the paper, before the deadline of 12 April
[exploration-state-art (1).pdf](https://github.com/Tribler/tribler/files/1893911/exploration-state-art.1.pdf)

**Comment by devos50** [comment]
This paper has been completed and graded.
