### ISSUE TITLE
Drag & drop torrent file in Tribler to download

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3505]
Would be nice to drag & drop a torrent file in Tribler window and a download dialog shows up to download the torrent.

**Comment by qstokkink** [comment]
We would have to handle [drop events](http://doc.qt.io/qt-5/qdropevent.html) and check for the correct [mime data](http://doc.qt.io/qt-5/qmimedata.html) of torrent files (we will need to see if this is consistent between platforms as well).
