### ISSUE TITLE
real-time graph of trustchain transactions per second

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3508]
For V7.2 or beyond...

Easy to understand graphs are required to show the 10000 tps that Trustchain is proven to be capable of. Compare it to other real-world deployed systems without central servers such as Bitcoin and Ethereum. statistics.tribler.org shows a great format, excellent to re-use. Other example:

![tps_animates](https://user-images.githubusercontent.com/325224/37480212-f0f21d28-287e-11e8-893b-5d509efb3d96.gif)

**Comment by devos50** [comment]
I've published an initial, very basic version of my TrustChain explorer, written in AngularJS: http://130.161.119.212/home. This is mostly used by me for debugging payouts/market transactions.

![tcexplorer](https://user-images.githubusercontent.com/1707075/42375797-07275bde-811d-11e8-87ce-41264a1de31e.png)

**Comment by devos50** [comment]
Made a quick visualization of TrustChain using `vis.js`. The graph contains 5000 nodes and took a few minutes to render on my computer.

![c1d7634c1869dc6d025767399eedeb30](https://user-images.githubusercontent.com/1707075/42640533-ccf22b26-85f2-11e8-8f8c-3db8302cc939.png)

**Comment by synctext** [comment]
The real live Trustchain?  COOL

**Comment by devos50** [comment]
Yes, it's the live trust chain :)

I've deployed my small application on explorer.tribler.org. Right now, Trustchain has 131k created (half) blocks, which is way higher than I estimated actually. The visualisation backend has performance bottlenecks when displaying over 1000 nodes unfortunately so for now, I've limited this to the 100 most recent blocks.

**Comment by devos50** [comment]
I just added a toggle to switch between mainnet and testnet to the live crawler. You can now also see the transaction created on the testnet (which mostly consists of my own tests for the market) 👍

**Comment by qstokkink** [comment]
Trustchain has been removed and, therefore, this issue is no longer relevant.
