### ISSUE TITLE
lintian warnings in next

### ISSUE THREAD

**Issue by ghost** [Tribler/tribler#3511]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

next + 2a1d342

##### Operating system and version: #####

ubuntu 17.10 artful

##### Expected behavior: #####

no lintian warnings while building on debian

##### Actual behavior: #####

6 warnings:

- W: tribler: extra-license-file usr/lib/python2.7/dist-packages/Tribler/Core/DecentralizedTracking/pymdht/LGPL-2.1.txt (this will probably have to be done by debian packager/maintainer, see  qstokkink's comment)
- W: tribler: extra-license-file usr/lib/python2.7/dist-packages/Tribler/Core/DecentralizedTracking/pymdht/LICENSE.txt (this will probably have to be done by debian packager/maintainer, see  qstokkink's comment)
-  W: tribler: extra-license-file usr/share/tribler/Tribler/dispersy/libnacl/LICENSE
- [ ] W: tribler: command-in-menu-file-and-desktop-file tribler usr/share/menu/tribler:6
-  W: tribler: executable-not-elf-or-script usr/share/tribler/Tribler/dispersy/tests/__init__.py
-   W: tribler: executable-not-elf-or-script usr/lib/python2.7/dist-packages/Tribler/dispersy/tests/__init__.py

This will range somewhere from a 'nice to have' to a prereq for debian issue 836852 ( https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836852 ), depending how stringent debian DDs are (ie probably closer to the latter)

##### Steps to reproduce the behavior: #####

( 0) add new changelog entry to make sure it'll build if necessary )
1) debuild -us -uc -b

##### Relevant log file output: #####

n/a

**Comment by qstokkink** [comment]
The extra license files we cannot fix, these are submodules. The other 3 we should be able to do something about.

**Comment by devos50** [comment]
Since Dispersy is end-of-life, we won't fix the license issues in the Dispersy directory.

**Comment by qstokkink** [comment]
So the clash is between:

 - https://github.com/Tribler/tribler/blob/next/debian/tribler.menu
 - https://github.com/Tribler/tribler/blob/next/Tribler/Main/Build/Ubuntu/tribler.desktop

I guess the only way to fix this, is by making a separate `.desktop` file specifically for Debian.

**Comment by ichorid** [comment]
Thanks for checking! :+1: let's reopen this one, to stay with tradition :wink:
