### ISSUE TITLE
don't recommend things you're already downloading

### ISSUE THREAD

**Issue by themusicgod1** [Tribler/tribler#3513]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

  Installed: 7.0.1-next+2a1d342

##### Operating system and version: #####

  ubuntu 17.10 artful

##### Expected behavior: #####

When tribler recommends torrents to me via the main screen, the 'recommended for you'...I should be able to click on them and download them without hassle.

##### Actual behavior: #####

1) I click on one of the torrent's download icon (not saying which one, sorry) 
2) the Download Torrent window comes up.  click download
3) "Request Error : an error occurred during the request
this download already exists."  ( this error is correct, I am apparently already downloading it )

##### Steps to reproduce the behavior: #####

see above

##### Relevant log file output: #####

INFO    1521431583.11          server:285   Closing session, reason unspecified
ERROR   1521431583.30    rest_manager:54    [Failure instance: Traceback: <class 'Tribler.Core.exceptions.DuplicateDownloadException'>: <class 'Tribler.Core.exceptions.DuplicateDownloadException'>: This download already exists.
/usr/lib/python2.7/dist-packages/twisted/web/http.py:1442:dataReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:1768:_finishRequestBody
/usr/lib/python2.7/dist-packages/twisted/web/http.py:1845:allContentReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:766:requestReceived
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/web/server.py:190:process
/usr/lib/python2.7/dist-packages/twisted/web/server.py:241:render
/usr/lib/python2.7/dist-packages/twisted/web/resource.py:250:render
/usr/share/tribler/Tribler/Core/Modules/restapi/downloads_endpoint.py:295:render_PUT
/usr/share/tribler/Tribler/Core/Session.py:313:start_download_from_uri
/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py:568:start_download_from_uri
/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py:592:start_download_from_magnet
/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py:627:start_download
]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 190, in process
    self.render(resrc)
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 241, in render
    body = resrc.render(self)
  File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/share/tribler/Tribler/Core/Modules/restapi/downloads_endpoint.py", line 295, in render_PUT
    unquote_plus(unicode(parameters['uri'][0], 'utf-8')), download_config)
  File "/usr/share/tribler/Tribler/Core/Session.py", line 313, in start_download_from_uri
    return self.lm.ltmgr.start_download_from_uri(uri, dconfig=dconfig)
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 568, in start_download_from_uri
    return succeed(self.start_download_from_magnet(uri, dconfig=dconfig))
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 592, in start_download_from_magnet
    return self.start_download(tdef=tdef, dconfig=dconfig)
  File "/usr/share/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 627, in start_download
    raise DuplicateDownloadException("This download already exists.")
DuplicateDownloadException: <class 'Tribler.Core.exceptions.DuplicateDownloadException'>: This download already exists.

Incidentally I think this is part of #21 - if you've got 1000 torrents going, you're going to
a) totally lose track what you are and are not downloading 
b) more and more of the 'recommended' stuff, if the recommendation engine is working at all, is going to be a hit if you've got a lot of torrents going.

**Comment by xoriole** [comment]
@themusicgod1 Thank you for reporting. You are indeed right. We need to improve the recommendation engine.
