### ISSUE TITLE
Tribler installer overwrites VLC installation

### ISSUE THREAD

**Issue by reharmsen** [Tribler/tribler#3545]
##### Tribler version/branch+revision: #####
7.0.2

##### Operating system and version: #####
Windows 10 (1709)

##### Steps to reproduce the behavior: #####
Install latest VLC (3.0.1)
Install Tribler 7.0.2

##### Expected behavior: #####
VLC remains untouched (i.o version 3.0.1)

##### Actual behavior: #####
VLC got replaced by a much older version (2.2.6)

**Comment by devos50** [comment]
Theoretically, it should be enough to include `libvlc.dll` and `libvlccore.dll` with the Tribler installation. This would leave the VLC version installed on the OS untouched. It requires some changes to our existing NSIS installation scripts, however.

**Comment by reharmsen** [comment]
Thanks for the quick fix
