### ISSUE TITLE
Tribler 7.1 not shutting down normally

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3565]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
build 05-04-2018
##### Operating system and version: #####
Windows 10 Insider build 17639
##### Steps to reproduce the behavior: #####
STart Tribler 7.1 and try to shutdown.
##### Expected behavior: #####
Notmal Shutdown
##### Actual behavior: #####
Mining shutdown message shows in log, but no actual shutdown is done.
When closing the log window, Tribler is closed, but when restarted all files are checked, meaning the shutdown was an abend.

**Comment by devos50** [comment]
Thank you for your report. Could you check your Tribler logs whether there are any interesting errors there?

**Comment by Nubro01** [comment]
I do not see any shutdown related error's, but since tribler is not shuttingdown, unless I close the log window...

ERROR   1523180955.10       community:299   Exception occurred while handling packet!
Traceback (most recent call last):
  File "Tribler\pyipv8\ipv8\deprecated\community.py", line 296, in on_packet
  File "Tribler\pyipv8\ipv8\deprecated\community.py", line 245, in on_introduction_request
  File "Tribler\pyipv8\ipv8\deprecated\community.py", line 76, in _ez_unpack_auth
  File "Tribler\pyipv8\ipv8\messaging\serialization.py", line 295, in unpack_to_serializables
  File "Tribler\pyipv8\ipv8\messaging\serialization.py", line 234, in unpack_multiple
  File "Tribler\pyipv8\ipv8\messaging\serialization.py", line 208, in unpack
  File "Tribler\pyipv8\ipv8\messaging\serialization.py", line 106, in unpack_from
PackError: Failed to unserialize IntroductionRequestPayload
PackError: Could not unpack item 5: QQHHBH
error: unpack_from requires a buffer of at least 23 bytes

**Comment by xoriole** [comment]
@Nubro01 Could you try the latest build [Build 197](https://jenkins.tribler.org/job/Build-Tribler_Win64_next/197/) and let us know if the problem persists?

**Comment by Nubro01** [comment]
I have a start up problem with the lastest 3 builds, see my other issue.

**Comment by Nubro01** [comment]
After a while I am able to force shutdown on the Tribler main screen and that NOW works, but after restart most of the files are checked again and with >= 4 gig files, this takes a long time!!!!

**Comment by Nubro01** [comment]
![afbeelding](https://user-images.githubusercontent.com/1146496/38809300-5d5a6b24-4183-11e8-84e5-3ff20914dc74.png)

**Comment by Nubro01** [comment]
So please, before force shutdown close all files normally!

**Comment by Thomasedv** [comment]
Also, getting incomplete shutdown.  Things like this in log: 
![image](https://user-images.githubusercontent.com/1584461/39084196-9aee508a-4571-11e8-8fee-c787509679c3.png)

The negative data circuits slowly increases up to 0. 

Also noticed errors like in #3587 and the unpack error mentioned above. Currently using dev version Tribler exp1-116.

**Comment by devos50** [comment]
@Thomasedv we're working on these issues. The negative number of data circuits required is a problem indeed and we should look into it. I will open a separate issue for it. Thanks for reporting!

**Comment by Nubro01** [comment]
FInally, the Mai 22nd 2018 version, does a normal shutdown on Windows 10 build 17672.
Thanks.

**Comment by synctext** [comment]
Great work fixing this guys!

**Comment by Nubro01** [comment]
Hi,

Could you please write or point me to an article explaining the number of hops within anonymous seeding?
I have  a Ziggo 250/25 connection, but since I seed everything Anonymous, I hardly see any uploads. Probably because only a few people download anonymous?
When I try it myself, I hardly get any download speed, so my downloads are still not anonymous and when done, I manually set it to one hop. Or should I put them on 3 hops? What is the difference in upload speed?

I have asked a friend, who lives in the neighborhood, to also install the beta and download a file none and with anonymity that I was seeding. In all cases my computer/ip address was not found.
Is this because I am still at IPv4/NAT or what? If he can’t find me can others?
Within my library I see sometimes a high peers count, but none of them seem to use me, so???

Regards

Ron

[cid:image001.png@01D3F343.9512EC00]
