### ISSUE TITLE
Tribler download listview shows download speed while seeding

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3566]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.
Yes
##### Tribler version/branch+revision: #####
Tribler 7.1 build 05-04-2018
##### Operating system and version: #####
WIndows 10 insider build 17639
##### Steps to reproduce the behavior: #####
Start Tribler and open download listview and have all seeding Torrents as Anonymous!!!
##### Expected behavior: #####
When details show down or up speed, something should be shown within peer detail, maybe just an anonymous line?
##### Actual behavior: #####
While seeding there is a download and upload speed of bytes, but when selecting the torrent, the peers detail show NOTHING, no download or even upload lines, but the treeview does shows seeds and peers and upload and download speed of bytes. Whenever download speed >= 1 KB then a leacher is shown in peers detail.

**Comment by devos50** [comment]
@Nubro01 thank you for your report. I'm not sure whether I completely understand your issue. Do you want to extend the information under the 'peers' section in the download details pane? Could you please clarify this?

**Comment by Nubro01** [comment]
![afbeelding](https://user-images.githubusercontent.com/1146496/38466116-852d41cc-3b24-11e8-9afe-563e612ce5ee.png)

Hope this helps?

**Comment by Nubro01** [comment]
I am seeding, so why do I see a download speed?

**Comment by Nubro01** [comment]
When seeding is > bytes then I do see something.

![afbeelding](https://user-images.githubusercontent.com/1146496/38466165-30faf08a-3b25-11e8-801d-85ea211b6ccc.png)

**Comment by qstokkink** [comment]
The BitTorrent protocol keeps communicating with other people: this is where the download speed comes from.

So, this is not download speed for the file you downloaded. Instead, it is download speed to communicate the completion percentages, download flags, countries, etc. etc. of other people.

**Comment by arvidn** [comment]
I believe it will be mostly REQUEST messages and HAVE messages, when pieces complete.

**Comment by devos50** [comment]
@arvidn thanks for clarifying this. I will close this issue since it's not an issue 👍 . Please let me know if you have any other questions!

**Comment by arvidn** [comment]
I do get the impression, though, that a lot of users aren't interested in "protocol overhead", but really just *payload* transfers. Similarly to how the TCP/IP overhead isn't reported. My reading of this report is "the list view should only show payload transfer rates".
