### ISSUE TITLE
Not getting any uploads or at least any "credit" for it. 

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#3569]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

Tribler_7.1.0-exp1-79-g141600e96_x64.exe

##### Operating system and version: #####
Windows 10

##### Steps to reproduce the behavior: #####
Use Tribler

##### Expected behavior: #####
Get uploads and credit for them. 

##### Actual behavior: #####
0 MB uploaded

##### Relevant log file output: #####
Not sure if it's relevant to this, but the error logs are riddled with this:

```
Traceback (most recent call last):
  File "Tribler\pyipv8\ipv8\deprecated\community.py", line 296, in on_packet
  File "Tribler\pyipv8\ipv8\deprecated\community.py", line 245, in on_introduction_request
  File "Tribler\pyipv8\ipv8\deprecated\community.py", line 76, in _ez_unpack_auth
  File "Tribler\pyipv8\ipv8\messaging\serialization.py", line 295, in unpack_to_serializables
  File "Tribler\pyipv8\ipv8\messaging\serialization.py", line 234, in unpack_multiple
  File "Tribler\pyipv8\ipv8\messaging\serialization.py", line 208, in unpack
  File "Tribler\pyipv8\ipv8\messaging\serialization.py", line 106, in unpack_from
PackError: Failed to unserialize IntroductionRequestPayload
PackError: Could not unpack item 5: QQHHBH
error: unpack_from requires a buffer of at least 23 bytes
```

##### Notes: #####
Currently have 0 MB uploaded, 0 people helped, yet a whole ton of downloaded. 
Most of my torrents have always been slow on tribler to upload, most never goes beyond 1 in ratio to begin with. But many are around 0.2 - 0.5 in ratio, yet i have no credit for any of it. I feel like a huge freeloader, and according to stat in Tribler, i technically am.

**Comment by devos50** [comment]
In Tribler, you only receive tokens when you upload to other peers in our darknet. Due to limitations in the mechanism, 'plain' seeding is not rewarded by any tokens. Since we recently changed the overlay identifier, it might be that there are not a sufficient amount of users operating in this overlay, limiting the amount of uploaded data.

Note that you can also earn tokens by relaying encrypted traffic for others, which should automatically happen when running Tribler. How fast you accumulate tokens this way, depends on the number of other users downloading, and their settings.

Please let me know whether this clarifies your observation. For now, I will close this issue since it's not likely to a be a technical problem but if it turns out to be, it will be reopened.

**Comment by Thomasedv** [comment]
It does clarify it. I guess my uncertainty came from the fact that i'm used to having more "uploads" than downloads with the older tribler versions. I understand that is changed, i just wasn't aware that the impact would be literally everything i uploaded. 

Another question would be, choosing to be an exit node, would count as "uploading" for others right?

**Comment by devos50** [comment]
Exiting data as exit node yields you bandwidth tokens indeed.

We will clarify this behaviour in the token overview screen 👍

**Comment by synctext** [comment]
We used to have a seeding to Tribler users for tokens and
Seeding in Bittorrent without tokens. You could turn each on/off separately. 
We should have that again perhaps + turn encrypted relaying off/on.

**Comment by Thomasedv** [comment]
@devos50 I got a little question on how much you "pay" for a download. Last time i had a lot on of downloads, but this time, i only added one. And by the time it was finished i was at -1300 MB, and yet the download was of size 550 MB. Although i understand that Tribler adds some extra with communication, it's a bit much to see a "cost" of over the double of the torrent size. So, i just wondered if this is normal?

**Comment by devos50** [comment]
@Thomasedv you pay for each hop. In particular, if I have the following 2-hop circuit:

downloader <-> relay node <-> exit node

and a total of 250MB of data flows from the exit node to the downloader, then the downloader pays 750MB in total (500MB to the relay node and 250MB to the exit node). The rationale for this is that the relay node processes (encrypt/decrypt) 250MB of incoming data and 250MB of outgoing data. The exit node encrypts 250MB of outgoing data.

Hope this explains your question!

**Comment by Thomasedv** [comment]
Indeed! Thanks!
