### ISSUE TITLE
Tribler 7.1 April 16th version no install on D:\

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3586]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.
Yep
##### Tribler version/branch+revision: #####
April 16th 2018
##### Operating system and version: #####
WIndows 10 build 17643
##### Steps to reproduce the behavior: #####
Install tribler
##### Expected behavior: #####
Normal install
##### Actual behavior: #####
Install fails when D:\Program files is selected

**Comment by xoriole** [comment]
Could you be more specific in what way it fails? Does the installer complete installation or it gets stuck after selecting the install location?

**Comment by qstokkink** [comment]
@xoriole can you reproduce this?

**Comment by Nubro01** [comment]
Last version was ok again.
