### ISSUE TITLE
IOError in log on shutdown

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#3587]
- [x] I have read CONTRIBUTING.rst

- [] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Tribler_7.1.0-exp1-74-g3ca007f2d_x64

##### Operating system and version: #####
Windows 10

##### Steps to reproduce the behavior: #####
Unknown

##### Relevant log file output: #####

![image](https://user-images.githubusercontent.com/1584461/38955927-4e3f2150-4356-11e8-8c6c-e36a2b1caa9c.png)

I'm not sure if this is a problem or not, but i thought i'd at least post and issue and let you know it's there.

**Comment by qstokkink** [comment]
This is a weird one, I do not have an answer (yet) but I can share my observations:

 - This is happening when `logging` is performing a `stream.write()`.
 - The error code is 0, so there is "nothing wrong".
 - There are some suggestions available (`https://github.com/Microsoft/` `vscode/issues/36630#issuecomment-350063413`, `https://github.com/robotframework/` `robotframework/issues/2709#issuecomment-345646329`)

**Comment by Thomasedv** [comment]
Update, this error is also spotted in longer running tribler instances. 

![image](https://user-images.githubusercontent.com/1584461/39092489-2b25adae-460f-11e8-80f2-2e78549169b5.png)

Also, at the moment of taking this screenshot, Tribler is using about 9 GB of memory... Is this a new bug, or could it be related to the errors with logging? Or should i open an issue for memory leaks? 

Currently, on Tribler 7.1.0 exp1-122 and it's been running for ~12 hours only.  And the download speeds are really slow to update if not frozen, and stopping a torrent takes a while before it's updated in the GUI.

**Comment by qstokkink** [comment]
@Thomasedv the `logging` thing is a known (hard-to-fix) Windows obscurity.

The slowdown in the GUI is probably not related, could you make a separate issue for this?

**Comment by Thomasedv** [comment]
@qstokkink Will do!

**Comment by devos50** [comment]
@Thomasedv we recently added a memory dumper to Tribler. Could you help us by providing us with a memory dump that we can analyse? I.e. after running Tribler for an hour?

Instructions to create a memory dump: if you enable developer mode in the settings pane (general tab), you will see a _debug_ menu item to the left. From the debug pane, you are able to dump the memory content of the Tribler GUI and the Tribler core process (from the top of my head, under the system -> memory pane). If you could share these files with us by email or some other means, we will process them and pinpoint what's causing the excessive memory usage. Please note that these dumps might contain the info hashes of torrents you're downloading so you could consider sending them to us directly by email.

**Comment by Thomasedv** [comment]
@devos50 I'll do it once i let it run for a while, and have seen it increase notably in memory size.

**Comment by devos50** [comment]
@Thomasedv thank you!

**Comment by qstokkink** [comment]
This issue is actually bigger than just this error. No error during shutdown of a component should hinder the shutdown of others. Even an obscure error like this should be caught and handled.

**Comment by ichorid** [comment]
The startup-shutdown routines were completely redone for 7.5. Closing this.
