### ISSUE TITLE
Tribler wants a negative amount of circuits

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3596]
As reported in #3565, sometimes Tribler seems to want a negative number of circuits. This might be caused by the shutdown procedure, where circuits are closed and counters could be messed up.

Screenshot:

![39084196-9aee508a-4571-11e8-8fee-c787509679c3](https://user-images.githubusercontent.com/1707075/39093136-d9d1896c-461a-11e8-8d6c-e3d6d2986a84.png)

**Comment by egbertbouman** [comment]
This seems to happen when we have circuits, but don't need them. For instance you have 32 circuits, and need 0. In that case the counter shown in the logs will be -32.

The circuits that we don't need will eventually timeout, and won't be recreated. So, the counter should go to 0 after some time.

**Comment by qstokkink** [comment]
Does this happen when removing downloads?

**Comment by devos50** [comment]
I also observed this when running the Tribler application tester. I guess we can place an assert there and add some logging statements to see what's causing this.
