### ISSUE TITLE
GUI slowdown possible memory leak related.

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#3597]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Tribler 7.1.0 exp-1-122

##### Operating system and version: #####
Windows 10

##### Steps to reproduce the behavior: #####
Use tribler regularly. 

##### Expected behavior: #####
Same update speed as startup

##### Actual behavior: #####
GUI values seems to slow down or hang up. Though GUI is still usable, anything that seems to get info from or interact with core, goes slow or is stopped.

**Comment by devos50** [comment]
I managed to reproduce this somewhat with our automated application tester. Both the memory of the GUI and core increases after running for over one night, with some downloads in the background. I will try to make some memory dumps.

**Comment by devos50** [comment]
A few memory leaks in the GUI has been fixed recently, after which the memory usage increase seemed to significantly slow down. I will run Tribler for extended periods of time on different platforms to detect other leaks 👍

**Comment by qstokkink** [comment]
@devos50 can we close this?

**Comment by devos50** [comment]
I fixed all memory issues I'm aware of but I need some more work to run the application tester reliably on Windows for extended periods of time. For now, I guess we can close this issue. I will reopen it when the memory leak resurfaces.
