### ISSUE TITLE
Make REST API available from other machines

### ISSUE THREAD

**Issue by cranphin** [Tribler/tribler#3607]
Currently the REST API is only available on the same machine (localhost).

It would be nice to be able to control tribler from another machine.
I think for this all that's needed is to add a configuration option for http api binding interface, and use this here:
https://github.com/Tribler/tribler/blob/f40349a187f3cfa4010ef5c67a44d5a739497b12/Tribler/Core/Modules/restapi/rest_manager.py#L32
Where it replaces '127.0.0.1'.

Ofcourse it could also be always set to '0.0.0.0', but I guess that would be not preferable security wise :)

**Comment by qstokkink** [comment]
Related to #3079 .

> Ofcourse it could also be always set to '0.0.0.0', but I guess that would be not preferable security wise :)

Indeed: we don't want to expose any the API through HTTP, this is very dangerous. Once we start supporting HTTPS we will add this option.
