### ISSUE TITLE
Pressing a strange button near settings shows "multichain community not found"

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#3611]
##### Tribler version/branch+revision: #####

v7.0.2

##### Operating system and version: #####

Linux

##### Steps to reproduce the behavior: #####

Start Tribler, press the "handshake" button at a top panel near settings.

##### Expected behavior: #####

Something meaningful is displayed.

##### Actual behavior: #####

Error message and only a template page shown.

**Comment by xoriole** [comment]
I suppose the latest build should already include the fix for this issue.
https://jenkins.tribler.org/job/Build-Tribler_Ubuntu-64_next/426/

**Comment by qstokkink** [comment]
Since we don't have any feedback I will assume this to be fixed.
