### ISSUE TITLE
A public key to trust

### ISSUE THREAD

**Issue by amuuza** [Tribler/tribler#3612]
Hi,

If I want to download Tribler I go to
https://www.tribler.org/download.html
and cannot find any signature.
If I go to
https://github.com/Tribler/tribler/releases
I see the hashes are signed with key ID B9FCA9DC,
but don't know where is the public key nor a reference to it anywhere.

Thank you.

**Comment by xoriole** [comment]
@amuuza We appreciate your concern regarding the public key to trust.
Key used for signing the releases is the PGP key of the founder of Tribler, Prof. Johan Pouwelse.
You can find the public key in MIT PGP Key server here:
https://pgp.mit.edu/pks/lookup?op=vindex&search=0x9DD1E058B9FCA9DC

**Comment by amuuza** [comment]
Thank you!
