### ISSUE TITLE
Anonymous tunnels community

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#3619]
This Epic contains all issues related to anonymization feature in Tribler.
(Managed by ZenHub)

**Comment by devos50** [comment]
@ichori you might consider organizing all these 'epic' tickets in a Github project?

**Comment by ichorid** [comment]
@devos50, I am organizing it using ZenHub.com. It is more convenient to use than GitHub Projects.

**Comment by synctext** [comment]
Moving things to "Epic Column" in Github project Trello-like board...
