### ISSUE TITLE
Startup Errors

### ISSUE THREAD

**Issue by BluesGator** [Tribler/tribler#3635]
#### Please, fill all relevant items: ####

- [ ] I have read CONTRIBUTING.rst

- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Actual behavior: Series of 42 error message pop-ups 
![triblererror](https://user-images.githubusercontent.com/39414115/40246565-3cf55e5c-5a97-11e8-8b1f-9cadfb1a60d2.png)
#####

**Comment by xoriole** [comment]
@BluesGator Thank you for the issue report. 
Could you tell us if your windows is 32 or 64-bit version and if you have a previous VLC installation?

**Comment by BluesGator** [comment]
64 bit Windows and VLC 2.2.6 Umbrella
