### ISSUE TITLE
TypeError: download_callback() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3639]
From reporter - Tribler 7.1.0-exp2
```python
Traceback (most recent call last):
File "TriblerGUI\tribler_request_manager.py", line 381, in <lambda>
TypeError: download_callback() takes exactly 1 argument (2 given)
```

**Comment by qstokkink** [comment]
The signatures of these two don't seem to add up:
https://github.com/Tribler/tribler/blob/eda807908ed092c288d7f43f080574d5ba46e9a4/TriblerGUI/tribler_request_manager.py#L310
https://github.com/Tribler/tribler/blob/eda807908ed092c288d7f43f080574d5ba46e9a4/TriblerGUI/tribler_request_manager.py#L381
