### ISSUE TITLE
Encrypted anonymous seeding using proxies option checked, does not work.

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3644]
##### Tribler version/branch+revision: #####
Everry version since first 7.1 build
##### Operating system and version: #####
WIndows 10 build  17672
##### Steps to reproduce the behavior: #####
In settings, general, check this option. Download a Torrent not anonymous and with 7.0 it would start seeding anonymous, with 7.1 it does not.
##### Expected behavior: #####
When finished downloading it would check and seed anonymous automatically.
##### Actual behavior: #####
When download is done, Torrent starts seeding none anonymous.
!!! When right click on Torrent in Library, just selection menu should come up, it should NOT act as if a left click was also done!!!! Test on left or right mousebutton click and do not act on mousebutton down event.

**Comment by devos50** [comment]
Hmm I'm pretty sure we had some code for this: when a download is finished and it should start seeding safely, it would be re-added with one hop anonymity. I have the feeling that the code got removed at some point. I will check this.

**Comment by devos50** [comment]
@Nubro01 this is caused by https://github.com/Tribler/tribler/pull/3187 where we removed the functionality that a torrent is added back when completed. @qstokkink can you comment on this one, in particular, why this code was removed?

**Comment by qstokkink** [comment]
@devos50 that code was removed because it caused a race condition where you could no longer remove downloads (#3169).

**Comment by devos50** [comment]
But removal of this code leads to this issue unfortunately. I do not see see how it causes the problem in #3169.

**Comment by qstokkink** [comment]
@devos50 https://github.com/Tribler/tribler/pull/3187/files#diff-5bafa75f4a19b8acdf8d580545a24d16L580
