### ISSUE TITLE
Install defaults to download\Triblerdownloads despite download setting is at E:\Tribler

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3645]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.
Yes
##### Tribler version/branch+revision: #####
Mai 22nd 2018
##### Operating system and version: #####
Windows 10 1803, main desktop, normally use laptop
##### Steps to reproduce the behavior: #####
Run old 7.0 version and update to beta 7.1
##### Expected behavior: #####
Settings/General Download folder is E:\Tribler, expect old files to be found there and checked
##### Actual behavior: #####
Despite the fact that General setting is still at E:\Tribler, all torrents are updated to be located at downloads\TriblerDownloads, causing all files to be downloaded again, despite the fact that they already exist in E:\Tribler.
I have to export all Torrents to E:\Tribler, remove Torrent+data from Library and after the remove they are added automatically and checked. I like this automatic loading in this case.

**Comment by devos50** [comment]
Related to #3556 

We should definitely write a test for this to capture and fix this. It can mess with the downloads of users that upgraded Tribler.
