### ISSUE TITLE
Show version in the UI

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#3647]
Most applications use the menu design pattern and have a "Help > About" where the Version and other information is listed.

Tribler should have a version number somewhere in the UI.

related; make ppa/copr/macports/homebrew/windows-PackageManagement so auto upgrade is the default.

**Comment by devos50** [comment]
@Dmole in Tribler 7.1 (and the experimental releases) we show the version of Tribler in the title bar and if I remember correctly, I've also added this information to the debug pane. Creating a separate about window with some basic information (including version number) would not take too much time I guess.
