### ISSUE TITLE
UnicodeEncodeError and DecodeError in log

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#3654]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Tribler 7.1 exp2-28

##### Operating system and version: #####
Windows 10

##### Steps to reproduce the behavior: #####
Unknown

##### Relevant log file output: #####

![image](https://user-images.githubusercontent.com/1584461/40735604-df0d715e-643b-11e8-9a47-25b8e7482067.png)

**Comment by devos50** [comment]
@Thomasedv does this crash your Tribler instance? If not, I guess we can ignore it. You probably stumbled upon a tracker with some unicode characters that could not be encoded. @qstokkink what do you think?

**Comment by Thomasedv** [comment]
No crash, so it's all good. I just saw it pretty frequently in the log.

**Comment by devos50** [comment]
Okay, then it is likely an invalid tracker 👍
