### ISSUE TITLE
Microsoft Github plan

### ISSUE THREAD

**Issue by ghost** [Tribler/tribler#3662]
### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [na] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

all

##### Operating system and version: #####

all

##### Steps to reproduce the behavior: #####

na
##### Expected behavior: #####

Not having Microsoft in control of development repository

##### Actual behavior: #####

Microsoft is buying Github

##### Relevant log file output: #####

na

Microsoft is 'Embracing' Github - what is the Tribler dev team's plan to avoid being extinguished by Microsoft?  Is there any plan to move to a different platform?

See: https://github.com/upend/IF_MS_BUYS_GITHUB_IMMA_OUT

**Comment by qstokkink** [comment]
I guess we will wait and see what changes. Should it be required, we have more than enough replica's of our source tree to move elsewhere.

**Comment by ThomasdenH** [comment]
Git is designed for perfect data portability. Even in the (extremely unlikely) worst case scenario where GitHub decides to go offline entirely without notice, it is trivial to push the local repository to another site. GitHub issues and PR's are another thing, but they're so integral to the GitHub business that I don't see them disappearing anytime soon.

So as with any other company, don't worry but be ready to switch.

**Comment by Dmole** [comment]
All paying projects should move to gitlab so the money goes into the further development of open source. (but that's nothing new)

All projects that are freeloading should move  to github to let Micro$oft foot the bill (in order to avoid burdening gitlab).

why gitlab?

- it's the most popular alternative [vs](https://thishosting.rocks/best-github-alternatives/)
- it has ab open source version used by Debian.
- it uses google cloud (and google makes open source like android and chromium) [ref](http://www.datacenterknowledge.com/cloud/how-did-gitlab-scale-slashdot-effect-point-and-click)

**Comment by qstokkink** [comment]
We're one month in and the whole ordeal has been pretty uneventful. I don't think this requires any more of our attention.

**Comment by synctext** [comment]
Made a repo backup: https://gitlab.com/synctext/tribler/
Should be self-hosted in the future in our own country under Dutch law, like this active Gitlab server, https://courses.ewi.tudelft.nl/gitlab

Another item on our ToDo list is creating real-time duplicates of the whole repo. Get a self-hosted enterprise server and sync using Github Connect. https://help.github.com/enterprise/2.15/admin/guides/developer-workflow/connecting-github-enterprise-server-to-github-com/

**Comment by synctext** [comment]
See https://twitter.com/TriblerTeam/status/1085138958122663936 for insightful discussion that resulted in re-opening this ticket. Thnx former @ghost account.

**Comment by qstokkink** [comment]
> We're one month in and the whole ordeal has been pretty uneventful. I don't think this requires any more of our attention.

6 years later and Microsoft has still not killed our project. We even get free Virtual Machines to test and build our code now. 🎉

I believe GitHub is now recognized as a stable and neutral-ish OSS publishing platform by even the Dutch government (e.g., in Dutch, https://www.digitaleoverheid.nl/overzicht-van-alle-onderwerpen/open-source/in-de-praktijk/). Of course, I'm sure Artificial Intelligence is learning from us how to write code.. but I guess that's acceptable.

I don't see any need - at all - for external replication right now. Nobody is going to maintain this anyway (case and point, the backup linked to above). Not to mention the confusion in trying to figure out the "one true repo". In the very _very_ worst case, what I said earlier is still true:

>  Should it be required, we have more than enough replicas of our source tree to move elsewhere.

I'll close this issue once again.
