### ISSUE TITLE
IPv8 distributed apps

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3670]
Master thesis idea:
- permissionless execution of Python code
  - No permission needed
  - Removes all dependency from servers
  - architecture without any single-point-of-failure
  - Open innovation and module growth
  - source code distribution and forking by design
- how to build trust for dAPP developers
  - star ratings for dAPP authors
  - code reviews and endorsements
  - prevent fake vote flooding (e.g. Sybil attack)
  - re-use Trustchain
- IPv8 execution engine
- dAPP discovery and update service
  - display all discovered dAPPs
  - View and click-to-execute untrusted code
- package manager
  - Python code is published as a swarm
  - Source code inside a bittorrent swarm
  - ```info_hash``` as a single requirement to identify, download, install, and run code.
- runtime environment
  - event-based intra-package communication bus (local-only)
  - dAPP-to-dAPP overlay, each running app joins the IPv8 overlay with the same app
  - dAPP version updates are gossiped around on this overlay
  - dAPPs: [Loading Python modules/plug-ins at runtime](https://copyninja.info/blog/dynamic-module-loading.html)

Possible sprints:
- seed swarm with Hello World; import and run
- add IPv8 and execution engine V1
- gossip random list of hashes of discovered code.
- implement client-server protocol of popular Android apps and possible re-use [GCM push tokens](https://github.com/google/gcm)

**Comment by ichorid** [comment]
This apps should not touch your local state. Sandboxing everything, VMs for security.

**Comment by synctext** [comment]
Duplicate of #2943. Closing this one. moving content.

This 2018 ticket is basically a new hipster, buzzword compliant version of 1999 work: **plugins**.

**Comment by synctext** [comment]
Mental note: p2p recommendation combines security with multimedia and distributed.
