### ISSUE TITLE
REST code duplication between IPv8 and tribler

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#3673]
There is some duplication in the REST endpoint logic between IPv8 and Tribler. We could probably consolidate the two code-bases.

https://github.com/Tribler/py-ipv8/tree/master/ipv8/REST

https://github.com/Tribler/tribler/tree/next/Tribler/Core/Modules/restapi

**Comment by ichorid** [comment]
@egbertbouman , your opinion on this? Is it possible? Is it worth the effort?

**Comment by egbertbouman** [comment]
I don't really have a strong opinion on this. I suppose we could at least remove `RESTEndpoint`/`RESTResponse` from Tribler and use the corresponding classes from IPv8 instead.

**Comment by qstokkink** [comment]
This used to be worse with the Twisted wrapping code being copy pasted between Tribler and IPv8. Even still, it is worth making sure we have as little duplication as possible: less code, less bugs.

**Comment by qstokkink** [comment]
Did the check. With the new aiohttp endpoint this concerns only several lines of duplication. We have bigger fish to fry.
