### ISSUE TITLE
Unable to switch to not Anonymous

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3683]
- [x] I have tried with the latest pre-release version and I still can reproduce the issue.
yes, June 20th 2018 version
##### Tribler version/branch+revision: #####
7.1
##### Operating system and version: #####
WIndows 10 Insider 17692
##### Steps to reproduce the behavior: #####
Download a Torrent and set it to Anonymous, after checking try to change it to not Anonymous
##### Expected behavior: #####
Torrent should check and stay as not Anonymous
##### Actual behavior: #####
Torrent is checked with Anonymous set to No in the listview, when done, Anynomous is set to Yes and the file is checked AGAIN!!! Why check the files when you switch from no to yes Anonymous???

**Comment by qstokkink** [comment]
@devos50 could this be the anonymous seeding thing?

**Comment by devos50** [comment]
@qstokkink most likely.

@Nubro01 if you enable 'safe seeding', the torrent will enter anonymous mode after it has finished downloaded. This is necessary to established the end-to-end encrypted circuits that enable safe and anonymous seeding. Could this explain your observation?

**Comment by qstokkink** [comment]
I think the issue is that we have no way to turn this feature off. We should probably disable safe seeding when changing the hop count.

**Comment by Nubro01** [comment]
I have tried this on another machine, where an older version was running and I was able to switch anonymous off, for all files, but still NO seeding occured. After 10 minutes I stopped and installed the latest version and as soon as Tribler got up, it started checking all files again and turned them all to Anonymous yes. I believe this is caused when you adjusted the code to enable the option Default download settings/Encrypted anonymous using proxy. I will set this option to off and see what happens.
This checking is taking a lot of my time. Why is checking once not enough?

**Comment by Nubro01** [comment]
With build of june 26th this is fixed, however.... Anonymous seeds are staying on Building circuits and when changed to anonymous no then they are seeding, but also without any upload speed.

**Comment by qstokkink** [comment]
@Nubro01 there are currently no exit nodes running anywhere. Once these come online you will be able to download anonymously again.

**Comment by Nubro01** [comment]
![afbeelding](https://user-images.githubusercontent.com/1146496/42077121-1e570796-7b78-11e8-8bf7-0174bc4ca5f9.png)

Still no anonymous seeding, with june 28th version, even normal seeding does not do anything, probably also related to still no exit nodes running?
