### ISSUE TITLE
Error: No module named pyipv8.ipv8.keyvault.private.libnaclkey

### ISSUE THREAD

**Issue by FFY00** [Tribler/tribler#3700]
I am trying to [package Tribler](https://aur.archlinux.org/packages/tribler/) for Arch Linux but I keep running into this issue.

#### Please, fill all relevant items: ####

- [X] I have read CONTRIBUTING.rst

- [X] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
  - Brach: `next`
  - Version (release.revision.commit): `7.1.0.exp3.r2.9fc4ae18b`

##### Operating system and version: #####
Arch Linux, up-to-date as of 29 Jun 2018 3pm.

##### Steps to reproduce the behavior: #####
Open tribler.

##### Expected behavior: #####
No error.

##### Actual behavior: #####
I get the error below. I already tried to manually install [`py-ipv8`](https://github.com/Tribler/py-ipv8) but the error persists.

##### Relevant log file output: #####
```
Traceback (most recent call last):
  File "run_tribler.py", line 63, in <module>
    start_tribler_core(base_path, api_port)
  File "run_tribler.py", line 22, in start_tribler_core
    from Tribler.Core.Session import Session
  File "/home/anubis/git/tribler/Tribler/Core/Session.py", line 18, in <module>
    import Tribler.Core.permid as permid_module
  File "/home/anubis/git/tribler/Tribler/Core/permid.py", line 10, in <module>
    from Tribler.pyipv8.ipv8.keyvault.private.libnaclkey import LibNaCLSK
ImportError: No module named pyipv8.ipv8.keyvault.private.libnaclkey
```

**Comment by qstokkink** [comment]
Did you checkout from git? (If so, did you clone recursively?)

**Comment by FFY00** [comment]
Hum, that's probably the problem. Submodules are not included in the release. And when I cloned the repository I forgot about the submodules. I am gonna close this, if for some strange reason this wasn't the issue, I will re-open. Thanks :smile:.
