### ISSUE TITLE
ERROR:root:Fault Handler module not found.

### ISSUE THREAD

**Issue by FFY00** [Tribler/tribler#3701]
I am running into this error. Running tribler as root seems to fix it.

#### Please, fill all relevant items: ####

- [X] I have read CONTRIBUTING.rst

- [X] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
  - Brach: `next`
  - Version (release.revision.commit): `7.1.0.exp3.r2.9fc4ae18b`

##### Operating system and version: #####
Arch Linux, up-to-date as of 29 Jun 2018 3pm.

##### Steps to reproduce the behavior: #####
Open tribler.

##### Expected behavior: #####
No error.

##### Actual behavior: #####
I get the error below.

##### Relevant log file output: #####
```
ERROR:root:Fault Handler module not found.
Traceback (most recent call last):
  File "run_tribler.py", line 70, in <module>
    should_kill_other_tribler_instances()
  File "/usr/share/tribler/check_os.py", line 145, in should_kill_other_tribler_instances
    pid = get_existing_tribler_pid()
  File "/usr/share/tribler/check_os.py", line 129, in get_existing_tribler_pid
    process_checker = ProcessChecker()
  File "/usr/share/tribler/Tribler/Core/Modules/process_checker.py", line 15, in __init__
    self.state_directory = state_directory or TriblerConfig().get_state_dir()
  File "/usr/share/tribler/Tribler/Core/Config/tribler_config.py", line 47, in __init__
    self.validate()
  File "/usr/share/tribler/Tribler/Core/Config/tribler_config.py", line 83, in validate
    raise InvalidConfigException(msg="TriblerConfig is invalid: %s" % str(validation_result))
Tribler.Core.exceptions.InvalidConfigException: <class 'Tribler.Core.exceptions.InvalidConfigException'>: TriblerConfig is invalid: {u'dispersy': True, u'general': True, u'channel_community': True, u'preview_channel_community': True, u'watch_folder': True, u'trustchain': True, u'download_defaults': True, u'allchannel_community': True, u'credit_mining': True, u'popularity_community': True, u'torrent_collecting': True, u'ipv8': {'bootstrap_override': False, 'enabled': True, 'address': True}, u'search_community': True, u'metadata': True, u'libtorrent': True, u'mainline_dht': True, u'resource_monitor': True, u'torrent_store': True, u'wallets': True, u'torrent_checking': True, u'tunnel_community': True, u'market_community': True, u'http_api': True, u'video_server': True}
```

**Comment by qstokkink** [comment]
Apparently your `'bootstrap_override'` setting is bad. Could you share the value of this setting with us? (You should be able to find your `tribler.conf` in `~/.Tribler/`).

**Comment by devos50** [comment]
@qstokkink @FFY00 this is caused when running the Tribler version from a few commits ago (when we were using a different kind of value for the `bootstrap_override` option. Removing the `bootstrap_override` option in the configuration file should fix it.

**Comment by FFY00** [comment]
`bootstrap_override` is `None`. I removed it from `tribler.conf` and it worked.

I release the package: https://aur.archlinux.org/packages/tribler/
I am gonna add a pinned comment warning about this issue.

Thanks :smile:.

**Comment by FFY00** [comment]
I am sorry, should I keep this open?

**Comment by devos50** [comment]
Nope, thanks for creating the package for arch linux, very helpful 👍
