### ISSUE TITLE
Undefined names: 'score' and 'MediaDiscovererDescription'

### ISSUE THREAD

**Issue by cclauss** [Tribler/tribler#3704]
Undefined names have the potential to raise NameError at runtime...

flake8 testing of https://github.com/Tribler/tribler on Python 2.7.14

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./Tribler/Core/Modules/restapi/util.py:92:12: F821 undefined name 'score'
    return score
           ^
./TriblerGUI/vlc.py:4779:50: F821 undefined name 'MediaDiscovererDescription'
                   ctypes.POINTER(ctypes.POINTER(MediaDiscovererDescription)))
                                                 ^
./TriblerGUI/vlc.py:4791:41: F821 undefined name 'MediaDiscovererDescription'
                   None, ctypes.POINTER(MediaDiscovererDescription), ctypes.c_size_t)
                                        ^
3     F821 undefined name 'score'
3
```

**Comment by qstokkink** [comment]
@devos50 this is part of the default vlc bindings, right?

**Comment by devos50** [comment]
@qstokkink yes, `vlc.py` is a (slightly modified) copy of the official VLC bindings.

Regarding the first error, this is a bug and I will create a PR for this to fix it. Thank you for reporting it!
