### ISSUE TITLE
kalilinux nethunter nexus 6 cyanhacker rom

### ISSUE THREAD

**Issue by oakes8585** [Tribler/tribler#3708]
i use tribler and its great!!

I have kalilinix nethunter installed on a custom cyanhacker rom on my nexus 6 id love to see a armhf installable version of this that can be accesiable via web interface and or installible apk that will connect to the installed software. Also if connecting to a seedbox such as dedi via ssh or ftp through this software using the phone would be awsome so files could be shared viseversa....just a idea!!!?

**Comment by ichorid** [comment]
related to #5327 and #4189
