### ISSUE TITLE
MAC fail: 'qrcode' module is missing. This module can be instalked through apt-get or pip

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3725]
When trying to partially empty some tokens, error is shown. Installed standard exp3 release. Mac version.

Btw the button is called 'empty', even when just partially moving 1% of tokens.

**Comment by qstokkink** [comment]
@devos50 this is one of the nasty electrum imports right?

**Comment by devos50** [comment]
@qstokkink it is part of the Electrum GUI.

The `qrcode` package was not installed on the Mac. I've installed it and PyInstaller should now bundle it. I've started a new build, see https://jenkins-ci.tribler.org/job/Build-Tribler_OSX_next/5/ 👍 . This should fix the issue.
