### ISSUE TITLE
Give the user insight in the history of received/spent bandwidth tokens

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3731]
We should give the user more insight in the user interface regarding the history of bandwidth tokens. A basic list that shows the history of incoming/outgoing bandwidth tokens should already address this.

**Comment by qstokkink** [comment]
We should be able to recycle the call from `http://explorer.tribler.org/users` for this.

**Comment by synctext** [comment]
Give detailed log-level info. With a clear "only you can see this:" these tokens are earned at Time T:
- by encrypted relaying
- by being an exit node (non default!)
- by seeding swarm "XYZ"
- by credit mining investment

**Comment by devos50** [comment]
The public TrustChain records do not provide enough information to determine what the exact activity was that changed the token balance of a specific user. I suggest to seperately store this information in the local database of Tribler, the moment the user signs an incoming block or creates a new block.

While I can use the existing Tribler database to do so, I would probably only pollute it even more and it will be replace soon by #3775. So I would rather wait for this PR to be merged and use the metadata store. @ichorid am I correct that your database is suitable to store arbitrary events in Tribler (that are not gossiped around in the network)?

**Comment by ichorid** [comment]
@devos50 , MetadataStore is designed to do just that: store metadata for torrents and other kinds of stuff, serialize it and upload/download it in bulk with Libtorrent. So, it is not suitable for anything else.
However, you can use Pony to manage your own database and create your own class structure. You can use MetadataStore design as a reference.
That was one of the ideas behind that pull request: use MetadataStore as a 'pilot' for universal Pony ORM adoption over the whole Tribler/IPv8 codebase.

**Comment by devos50** [comment]
Idea: swarm-specific statistics and payout breakdown. It would require bandwidth accounting on the level of individual downloads.
