### ISSUE TITLE
Remove outline around selected cell/item in downloads page. 

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#3740]
##### Tribler version/branch+revision: #####
Tribler 7.1 exp-3 61
##### Operating system and version: #####
Windows 10

##### Problem: #####
When the user clicks a download, to get information or perform a action on it, it will get a dotted outline around that part of it, which serves no real purpose here.
Since the parent/container is a QTreeWidget (i think, since the items are QTreeWidgetItems that populate the page), i think adding this to the stylesheet should do the job.

`QTreeWidget {outline: none; }`

If i recall correctly, since last i encountered this, it's not something that shows the same on other OSes, but i don't think this change is going to affect any other platforms in a negative way.

**Comment by devos50** [comment]
This should be easy to fix, thanks for the report! 👍

**Comment by devos50** [comment]
I think the GUI tests on Windows highlight this behaviour:

![screenshot_download_trackers](https://user-images.githubusercontent.com/1707075/42724837-bb3ed84c-8779-11e8-9e64-ed5e0002b3c8.jpg)
