### ISSUE TITLE
Tribler not starting Jul 15th edition and previous

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3748]
##### Operating system and version: #####
Asus Z170 Premium, Windows 10 17713 insider, I get the below errors
On a Dell E6400 laptop, same windows version and Tribler version all is fine.
##### Steps to reproduce the behavior: #####
Installed previous and last version and on laptop all is ok, but on desktop I get below error.
What is causing it?

Thanks
##### Relevant log file output: #####
E:\program files\tribler>tribler.exe
:0: UserWarning: You do not have a working installation of the service_identity module: 'cannot import name opentype'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
Traceback (most recent call last):
  File "run_tribler.py", line 86, in <module>
  File "check_os.py", line 228, in enable_fault_handler
  File "Tribler\Core\Config\tribler_config.py", line 47, in __init__
  File "Tribler\Core\Config\tribler_config.py", line 83, in validate
Tribler.Core.exceptions.InvalidConfigException: <class 'Tribler.Core.exceptions.InvalidConfigException'>: TriblerConfig is invalid: {u'dispersy': True, u'general': True, u'channel_community': True, u'preview_channel_community': True, u'watch_folder': True, u'trustchain': True, u'download_defaults': True, u'allchannel_community': True, u'credit_mining': True, 'popularity_community': True, u'torrent_collecting': True, u'ipv8': {'bootstrap_override': False, 'enabled': True, 'address': True}, u'search_community': True, u'metadata': True, u'libtorrent': True, u'mainline_dht': True, u'resource_monitor': True, u'torrent_store': True, u'wallets': True, u'torrent_checking': True, u'tunnel_community': True, u'market_community': True, u'http_api': True, u'video_server': True}
Failed to execute script run_tribler

**Comment by Nubro01** [comment]
Created another account on my machine and added a shortcut to tribler.exe and it started, so???
What got corrupted on my normal desktop account and how to fix it. Remove everything from appdata and again lose all my statistics.

**Comment by xoriole** [comment]
Thank you for reporting. Seems like an issue with the upgrader. Could you try the latest build [Tribler_7.1.0-exp3-74-gba7746c68_x64.exe](https://jenkins-ci.tribler.org/job/Build-Tribler_Win64_next/12/artifact/tribler/dist/Tribler_7.1.0-exp3-74-gba7746c68_x64.exe)? This commit [88337c4e33219fa2d4257efdf03f54373399e2ba](https://github.com/Tribler/tribler/commit/88337c4e33219fa2d4257efdf03f54373399e2ba) should have fixed it. Please let us know if the issue persists.

**Comment by Nubro01** [comment]
Sorry, I had a backup of my current Torrents, so I delete the appdata\Roaming\.Tribler folder, because I was unable to rename it and imported the saved Torrents. I lost my status of course, but that was already only counting down.
I did notice however, that the import checked the files and when they changed to ANONYMOUS, they were checked AGAIN!!!!!! and for xx gig files this is VERY annoying, especially when they are all on the same disk!!!

**Comment by qstokkink** [comment]
I think the remainder of this issue is already captured in #3173 , so I will close this one.
