### ISSUE TITLE
Download location

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#3750]
~/Downloads/TriblerDownloads/credit_mining/

Is created regardless of the "Download location" setting.  

Tribler 7.1.0-exp3

**Comment by Dmole** [comment]
yah rm the folder (that should not exist) while tribler is running to get that.

**Comment by qstokkink** [comment]
It seems like credit mining is using the default download path:

https://github.com/Tribler/tribler/blob/d230247ee7cc8c21ff0d6bee9b4de4db00b39674/Tribler/Core/CreditMining/CreditMiningManager.py#L43

As in this line:

https://github.com/Tribler/tribler/blob/b096b9bf48a3ac815c104408f84259b639ac7014/Tribler/Core/Modules/restapi/settings_endpoint.py#L105

It is not receiving a custom `CreditMiningSettings` object as `settings`.

**Comment by qstokkink** [comment]
We should probably change the `CreditMiningManager` to take `session.config.get_torrent_store_dir()` when given a session.
