### ISSUE TITLE
Race condition on tunnel close

### ISSUE THREAD

**Issue by Captain-Coder** [Tribler/tribler#3767]
- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Devel

##### Operating system and version: #####
Arch Linux (rolling release)

##### Steps to reproduce the behavior: #####
Under heavy load, try to close a tunnel in use (ie due to tunnel lifetime or byte limit).

##### Expected behavior: #####
The tunnel will close and trafic will be routed through a new tunnel

##### Actual behavior: #####
In communities/triblertunnel/dispatcher.py, after circuit_dead() has run the tunnel is still in state READY to allow delayed closure. If there is pending data from the local libtribler, on_socks5_udp_data() will run immediately (before the tunnel is actually closed) and can (and will) reselect the circuit that was just closed. This leaves a reference to the old tunnel in dispatcher's destinations map, even after the tunnel is eventually closed. The dispatchers destinations map never recovers.

**Comment by Captain-Coder** [comment]
In end user tribler instances the severity is somewhat mitigated by the round robin selection strategy, having a roughly 1 in 8 chance of having the closed tunnel be reselected. If there is pending data to multiple peers, this might make a black hole out of multiple destinations if it occurs.

On my experiments (that have only 1 tunnel for simplicity) this nearly 1 in 1 chance is quite noticable. I have patched my version to have an extra tunnel state (UNSELECTABLE) that will not allow the selection strategy to select this tunnel. But for all other intents it is an alias for READY. Although functional, I found this patch unsatisfactory and inellegant. I would recommend trying to find another solution.

**Comment by egbertbouman** [comment]
@qstokkink No, I haven't. To fix this I would already be happy with changing the state of a circuit. Perhaps we can introduce a CLOSING state, and merge this with the existing BROKEN state. Additionally, we would be moving the call to ```circuit.destroy()``` from ```remove_circuit_info()``` to ```remove_circuit()```.

**Comment by qstokkink** [comment]
@egbertbouman do you have time to implement that?

**Comment by egbertbouman** [comment]
@qstokkink Sure, I'll make a PR.

**Comment by qstokkink** [comment]
@egbertbouman this was fixed in https://github.com/Tribler/py-ipv8/pull/206 right?

**Comment by egbertbouman** [comment]
@qstokkink Yes, this one is fixed.
