### ISSUE TITLE
OpenSSL.SSL.Error

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3768]
From reporter - Tribler 7.1.0-exp3 (#15432)
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 127, in on_read_data
RuntimeError: [Failure instance: Traceback (failure with no frames): <class 'twisted.web._newclient.ResponseNeverReceived'>: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]>]
]
```

**Comment by qstokkink** [comment]
Hmm.. this seems like it will have to go into the nasty [`Session.unhandled_error_observer`](https://github.com/Tribler/tribler/blob/next/Tribler/Core/Session.py#L159).

**Comment by qstokkink** [comment]
Actually, I guess that won't work as this is a GUI error.

**Comment by qstokkink** [comment]
Mystery solved: this is due to an older version of Twisted. We should decide whether or not to support this (IPv8 already demands a new version of Twisted anyway).
