### ISSUE TITLE
Switch from jenkins-ci.tribler.org to jenkins.tribler.org

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#3784]
Our main Jenkins should live at `jenkins.tribler.org`. The student environment should be something else.

Also, we'll have to update the documentation.

**Comment by xoriole** [comment]
`jenkins-ci.tribler.org` is switched to `jenkins.tribler.org` and both domains are valid so no links (in the documentation) with any of the domain names should break. Closing this issue for now.
