### ISSUE TITLE
Anonymous stay on building circuits

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3787]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Expected behavior: #####
Anonymous seeding to say seeding
##### Actual behavior: #####
Anonymous seeds have status building circuits, when switching to none anonymous they syart seeding.

**Comment by devos50** [comment]
@Nubro01 could you please try to download the very latest build (see https://jenkins-ci.tribler.org/job/Build_Tribler_next). we recently made some changes to the underlying protocols for anonymous downloading.

**Comment by Nubro01** [comment]
I tried the last one from august 14th, but yesterday that failed to start on my laptop and it only came up with the logfile. Went to my desktop and that version used to work, but now stayed on building circuits.
Downloaded and installed lhis version also on my I6700K desktop and there it worked.
Thanks. Will try and see what is wrong with that same version on my laptop.

**Comment by devos50** [comment]
Thank you for your feedback. Please create a new issue with the error you observe so we will look into it 👍 . I will close this issue for now.
