### ISSUE TITLE
Can tribler.ci start runinng Pylint on Python 3 in allow_failures mode?

### ISSUE THREAD

**Issue by cclauss** [Tribler/tribler#3792]
There are lots of Python 3 incompatibilities that Pylint can show us if we run it on Python 3.

Related to #3705

#### Please, fill all relevant items: ####

- [X] I have read CONTRIBUTING.rst

- [X] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
https://github.com/Tribler/tribler

##### Operating system and version: #####
GitHub

##### Steps to reproduce the behavior: #####
Look at tribler.ci output

##### Expected behavior: #####
Pylint fails when run on Python 3

##### Actual behavior: #####
Pylint passes all tests yet this repo contains Python 3 syntax errors

**Comment by devos50** [comment]
A few days ago, I've checked out how much effort it would be to run Tribler in Python 3. There are many nasty things we have to convert. We also have to consider upgrading our submodules (Dispersy, IPv8, pymdht and Electrum).

We first want to focus on removing Dispersy from Tribler. This should be possible after #3775 is merged and extended to include metadata gossiping.

**Comment by devos50** [comment]
We have automated tests (unit tests + GUI tests): https://jenkins-ci.tribler.org/job/GH_Tribler_PR/

Besides that, we also have validation experiments to test specific components of our technology stack: https://jenkins-ci.tribler.org/job/validation_experiments/

This should give us a foundation when moving to Python 3.

**Comment by cclauss** [comment]
@qstokkink @devos50 I have a poor knowledge of Jenkins.  Are these tests being run on Python 2 and Python 3 or are they only being run on Python 2?

**Comment by qstokkink** [comment]
They are only being run on Python 2.

**Comment by cclauss** [comment]
Is there a way to also run them in parallel on Python 3 in __allow_failures__ mode?  This is easy on Travis CI but I an not sure if it would be possible in Jenkins.
