### ISSUE TITLE
Improve the "building circuits" message

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#3793]
The past few days Tribler [next](https://jenkins-ci.tribler.org/job/Build_Tribler_next/lastSuccessfulBuild/artifact/tribler_7.1.0-exp3-126-ga1a8b816d_all.deb) is stuck on "building circuits"
This has happend in the [past](https://github.com/Tribler/tribler/issues?utf8=%E2%9C%93&q=is%3Aissue+building+circuits+in%3Atitle+) due to an exit node shortage,
and maybe API changes that are not backwords compatible.

I reccomend showing the user an informative message like "no exit nodes found, link to make your own",   
 "Please upgrade in order to connect to the Tribler network", and whatever other common / forseable issues may be addressesd by the user.

**Comment by devos50** [comment]
@Dmole we recently made a non-backward compatible change to the tunnel community. I recommend downloading the very latest version from our infrastructure directly. Tribler 7.0.2 should work correctly.

We will consider adding a message to the downloads when no circuits can be constructed. However, there are many reasons why circuits cannot be built, besides the reason you mention (i.e. peers that cannot be NAT punctured).

Please let me know whether downloading the latest version fixes the issue for you 👍

**Comment by Dmole** [comment]
>  I recommend downloading the very latest version from our infrastructure directly
I think that's what I linked to in the OP.

>  peers that cannot be NAT punctured
It's more likely the issue is not "everyone else"

> We will consider adding a message to the downloads when no circuits can be constructed
Please, basicly something to change the users interpretation from "Tribler is broke go back to 2001 and use a VPN" to "here is how to keep using this cool distributed solution that sometimes requires TLC".

**Comment by Dmole** [comment]
Hmm, I just installed the RC, got the most popular torrent from the most popular torrent site and Tribler has been stuck on "building circuits" for 10+ minutes, can't stop the torrent either.
exit nodes down, ISP port blocking me, bug in build, who knows?

**Comment by Dmole** [comment]
Thanks for the update,

So a "Please Upgrade" would be a good massage in this case.

Untill such a feature is implemented, as this is maby the 4rd time that has happend should the download button on https://www.tribler.org redirect to a some page that list what builds are working with maybe a link to https://github.com/Tribler/tribler/releases ?

**Comment by devos50** [comment]
After some discussion, we decided that it would be nice to add a new download state to each download (where it is finding exit nodes). We will try to address this in 7.3.
