### ISSUE TITLE
Upgraded few pip packages on ubuntu now on search got an error SQLError: no such module: fts4

### ISSUE THREAD

**Issue by zor1984qq** [Tribler/tribler#3794]
#### Please, fill all relevant items: ####

- [ ] I have read CONTRIBUTING.rst

- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Operating system and version: #####
ubuntu budgie 18.04 LTS
##### Steps to reproduce the behavior: #####
launch and try to making search request
##### Expected behavior: #####
actual search
##### Actual behavior: #####
SQLError: no such module: fts4

**Comment by qstokkink** [comment]
I believe this is caused by the newest version of `apsw`. If you `pip uninstall` that and use `apt install python-apsw`, everything should work again.
