### ISSUE TITLE
Reactor management in unit tests: trial vs nose

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3799]
We observed that we spawn a separate, threaded reactor when running the unit tests. While this seems to work, we also found out that the `trial` test runner, created by the Twisted team, spawns a reactor on the main thread.

We could consider to switch to the trial runner. This allows us to get rid of all the `blocking_call_on_reactor_thread` decorators since the reactor runs on the main thread already. We can also drop all `deferred` decorators since trial can handle these already. I'm not sure about how to set timeouts yet.

On the other hand, switching to trial requires some engineering effort. I already did some work in https://github.com/Tribler/tribler/pull/3796 but I found that more investigation is required to make trial work for all tests. We also have to upgrade our code coverage scripts and see whether they are compatible with the trial runner.

Regarding performance and test duration, I think there is very little to win by switching to trial. Maybe the stability of the tests improve a bit but other than that, I don't think there are other desired effects (and the code becomes a bit cleaner).

**Comment by qstokkink** [comment]
This is a good idea.
