### ISSUE TITLE
 tribler/Tribler/Core/Utilities/configparser.py needs to be renamed

### ISSUE THREAD

**Issue by cclauss** [Tribler/tribler#3801]
This file has a name collision with https://docs.python.org/3/library/configparser.html that it will want to import so PyLint wil rasie a __W0406: (import-self), : Module import itself__ error when we move to Python 3.  This was not a problem in Python 2 because https://docs.python.org/2.7/library/configparser.html uses __ConfigParser.py___ so there is no name collision.

#### Please, fill all relevant items: ####

- [ ] I have read CONTRIBUTING.rst

- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

**Comment by devos50** [comment]
Thank you for your report. Maybe we should make a separate Python 3 milestone?
