### ISSUE TITLE
Too much checking torrent.

### ISSUE THREAD

**Issue by Aldo-f** [Tribler/tribler#3805]
#### Please, fill all relevant items: ####
- [x] I have read CONTRIBUTING.rst
- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
7.0.2
7.1.0-beta

##### Operating system and version: #####
Windows 10 home
v 1803

##### Steps to reproduce the behavior: #####
Changing anonymity from none to 1 hop.
Changing anonymity from 1 hop to none.
(on D-disk; for tiny and huge torrents; Tribler installed on D)

##### Expected behavior: #####
After building circuits starting to upload/download.

##### Actual behavior: #####
First checks, (then building circuits,) then seeds.
Doesn't need to check, the torrent doesn't change. 

##### Relevant log file output: #####
Didn't find relevant log files on %APPDATA%\.Tribler\logs

##### Also: ##### 
Can't seem to successfully shut down Tribler, it always asks me to force shutdown.
And even that takes more than five minutes, so i need to use task manager to shut it down.
(not a problem in 7.1.0-beta (on C-disk))

**Comment by devos50** [comment]
Thank you for your report. When changing anonymity, Tribler internally removes the torrent from libtorrent and adds it again, with different parameters.

It should not be hard to preserve the state of a download and inject it when re-adding the download to libtorrent. We will give some priority to this issue. @egbertbouman do you want to take this one?

**Comment by egbertbouman** [comment]
@devos50 Sure, I'll take a look. It should just be a matter of reusing the resume data. This will also prevent the download/upload counters from resetting.

**Comment by arvidn** [comment]
I don't really know what Tribler does with the torrent when removing it and re-adding it, but chances are that it could be changed in-place (unless you're actually changing the torrent itself, causing the info-hash to change).

The way to prevent the re-checking is to save resume data for the torrent. This is an asynchronous operation and will return the resume data in an alert. In the current stable version of libtorrent you get back a bencoded buffer than can then be passed back in via the `add_torrent_params` object.

In master (the next major release of libtorrent), this has been simplified a bit by separating the serialisation of the resume data from returning it. There, the resume data is all stored in a structured form in the `add_torrent_params` object directly, and it can then be serialised/deserialised to its bencoded form independently.
