### ISSUE TITLE
torrent with zero-length file causes ZeroDivisionError

### ISSUE THREAD

**Issue by l2dy** [Tribler/tribler#3815]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
v7.1.0-beta
##### Operating system and version: #####
macOS 10.13.6
##### Steps to reproduce the behavior: #####
1. Add a torrent with an empty file. 
[temp.zip](https://github.com/Tribler/tribler/files/2321304/temp.zip)
2. Click Files tab with the added task selected.
##### Expected behavior: #####
No errors thrown, task doesn't stuck at Checking.
##### Actual behavior: #####
"
Request error
An error occurred during the request:

float division by zero
"
##### Relevant log file output: #####
```
ERROR   ...                  __init__:1198 (RESTRequest)  [Failure instance: Traceback: <type 'exceptions.ZeroDivisionError'>: float division by zero
twisted/protocols/basic.py:571:dataReceived
twisted/web/http.py:1752:lineReceived
twisted/web/http.py:1845:allContentReceived
twisted/web/http.py:766:requestReceived
--- <exception caught here> ---
twisted/web/server.py:190:process
twisted/web/server.py:241:render
twisted/web/resource.py:250:render
Tribler/Core/Modules/restapi/downloads_endpoint.py:255:render_GET
Tribler/Core/Modules/restapi/downloads_endpoint.py:93:get_files_info_json
Tribler/Core/DownloadState.py:163:get_files_completion
]
Traceback (most recent call last):
  File "twisted/web/server.py", line 190, in process
  File "twisted/web/server.py", line 241, in render
  File "twisted/web/resource.py", line 250, in render
  File "Tribler/Core/Modules/restapi/downloads_endpoint.py", line 255, in render_GET
  File "Tribler/Core/Modules/restapi/downloads_endpoint.py", line 93, in get_files_info_json
  File "Tribler/Core/DownloadState.py", line 163, in get_files_completion
ZeroDivisionError: float division by zero
```

**Comment by devos50** [comment]
Interesting edge case! We should add a check here and simply report this file as completed I guess 👍
