### ISSUE TITLE
Importing torrent with unicode filename shows garbled name

### ISSUE THREAD

**Issue by l2dy** [Tribler/tribler#3816]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
v7.1.0-beta
##### Operating system and version: #####
macOS 10.13.6
##### Steps to reproduce the behavior: #####
1. Import this torrent. 
[p.zip](https://github.com/Tribler/tribler/files/2321371/p.zip)

##### Expected behavior: #####
![u](https://user-images.githubusercontent.com/14329097/44626457-478e2600-a90c-11e8-89b1-df29189e6fd8.png)
##### Actual behavior: #####
Importing:
![gu](https://user-images.githubusercontent.com/14329097/44626467-815f2c80-a90c-11e8-989b-0bd3e9f36cab.png)
Displayed correctly afterwards:
![u](https://user-images.githubusercontent.com/14329097/44626457-478e2600-a90c-11e8-89b1-df29189e6fd8.png)

**Comment by devos50** [comment]
Thanks for reporting this!

**Comment by qstokkink** [comment]
The reason we always convert everything to UTF-8 is because QT only accepts UTF-8 right now. We would need support for other character encodings in the GUI to fix this. In other words: the GUI needs to be rewritten so that each torrent name is a tuple of a `(character_encoding : str, data : str)`. Torrents already come with a "suggested" character encoding map, so that part is indeed trivial.

**Comment by qstokkink** [comment]
Interesting, upon further inspection, both the `startdownloaddialog` and the `torrentdetailstabwidget` use the path from the metainfo directly:

https://github.com/Tribler/tribler/blob/4e7bae6c55b9c4d36d255a1b689857c3c9e08490/TriblerGUI/widgets/torrentdetailstabwidget.py#L64

**Comment by qstokkink** [comment]
This problem is twofold.

1. There is a character set problem. If I encode the filename as hex and decode it again, the character passes through.

```patch
diff --git a/Tribler/Core/Modules/restapi/torrentinfo_endpoint.py b/Tribler/Core/Modules/restapi/torrentinfo_endpoint.py
index 06db49aa5..c00baf3c9 100644
--- a/Tribler/Core/Modules/restapi/torrentinfo_endpoint.py
+++ b/Tribler/Core/Modules/restapi/torrentinfo_endpoint.py
@@ -76,6 +76,8 @@ class TorrentInfoEndpoint(resource.Resource):
                 # Note: in libtorrent 1.1.1, bencode throws a TypeError which is a known bug
                 pass
 
+            metainfo['info']['name'] = metainfo['info']['name'].encode('hex')
+
             request.write(json.dumps({"metainfo": metainfo}, ensure_ascii=False))
             self.finish_request(request)
 
diff --git a/Tribler/pyipv8 b/Tribler/pyipv8
index 9ad0b85c2..d89d7bb42 160000
--- a/Tribler/pyipv8
+++ b/Tribler/pyipv8
@@ -1 +1 @@
-Subproject commit 9ad0b85c28454a0f4fbae2eb01f34bc7410538ed
+Subproject commit d89d7bb42e4647cf34f14966b9c3ae0bf1632f8a-dirty
diff --git a/TriblerGUI/dialogs/startdownloaddialog.py b/TriblerGUI/dialogs/startdownloaddialog.py
index 1956919a0..d6664483c 100644
--- a/TriblerGUI/dialogs/startdownloaddialog.py
+++ b/TriblerGUI/dialogs/startdownloaddialog.py
@@ -126,7 +126,7 @@ class StartDownloadDialog(DialogContainer):
         if 'files' in metainfo['info']:  # Multi-file torrent
             files = metainfo['info']['files']
         else:
-            files = [{'path': [metainfo['info']['name']], 'length': metainfo['info']['length']}]
+            files = [{'path': [metainfo['info']['name'].decode('hex')], 'length': metainfo['info']['length']}]
 
         # Show if the torrent already exists in the downloads
         if 'download_exists' in metainfo and metainfo['download_exists']:
```

2. The start download dialog can't handle the character set even if the character is passed properly: 
![afbeelding](https://user-images.githubusercontent.com/3630389/45226061-3ce57080-b2be-11e8-98c2-49c5bcd6cd91.png)

**Comment by qstokkink** [comment]
Follow-up on (2): whether or not (correctly formatted) `str` or `unicode` is passed doesn't matter.
