### ISSUE TITLE
Double dock icons on macOS

### ISSUE THREAD

**Issue by l2dy** [Tribler/tribler#3817]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
v7.1.0-beta
##### Operating system and version: #####
macOS 10.13.6
##### Steps to reproduce the behavior: #####
1. Open Tribler.
##### Expected behavior: #####
Only one dock icon.
##### Actual behavior: #####
Two dock icons / one extra invisible app, both disappear if I close the visible one.
![docki](https://user-images.githubusercontent.com/14329097/44626606-ac4a8000-a90e-11e8-899a-6ca914c15bcc.png)

**Comment by l2dy** [comment]
Yes, it always happens.

**Comment by devos50** [comment]
The second app, does it always appear as if it's starting up?

**Comment by l2dy** [comment]
No, it will stop jumping after a while. But I think this is controlled by macOS.

**Comment by l2dy** [comment]
Here's all tribler processes in htop tree view.
![htop](https://user-images.githubusercontent.com/14329097/44626826-11a07000-a913-11e8-9fba-84f80e7ac8eb.png)

**Comment by devos50** [comment]
I get the same output. I have no idea why mac decides to show a second dock icon then?

**Comment by qstokkink** [comment]
That is almost surely the core subprocess (a child of the main GUI process) being assigned an icon. Why this happens, I do not know.

**Comment by qstokkink** [comment]
The `pid`/`ppid` suggests that the GUI is spawning a core, which spawns a GUI, which spawns a core.

**Comment by devos50** [comment]
Also happens on my machine in a frozen environment. I will have a look.
