### ISSUE TITLE
garbled text in dmg EULA

### ISSUE THREAD

**Issue by l2dy** [Tribler/tribler#3820]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
v7.1.0-beta
##### Operating system and version: #####
macOS 10.13.6
##### Steps to reproduce the behavior: #####
1. Open the `.dmg` file.
##### Expected behavior: #####
No `Ôªø` at the beginning of the EULA.
##### Actual behavior: #####
![geula](https://user-images.githubusercontent.com/14329097/44627839-4f59c480-a924-11e8-97dd-5aa97f1d2d5e.png)

**Comment by qstokkink** [comment]
This might be due to the style hints added to the text (like bold font).
