### ISSUE TITLE
404 - No Such Resource

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3839]
Occasionally, the following log pops on the console.
```python
ERROR   1535726564.08   tribler_request_manager:299  (root)  No json object could be decoded from data: 
<html>
  <head><title>404 - No Such Resource</title></head>
  <body>
    <h1>No Such Resource</h1>
    <p>No such child resource.</p>
  </body>
</html>
```
It seems like request is sent to non-existing endpoint. It is not clear which endpoint but we should investigate it further.

**Comment by devos50** [comment]
Please make sure your submodules are up to date, I recently moved a few (TrustChain) endpoints to IPv8.

**Comment by xoriole** [comment]
Yes, seems like it.
