### ISSUE TITLE
tray_icon should not be called directly

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#3843]
The tray icon should never be used directly, its removal is asynchronous (in C, so actually asynchronous). This means that at any point in the code a `RuntimeError` can be thrown.

We should make sure that all occurrences of interfacing with the tray icon are properly wrapped in a `try .. except` block (https://github.com/Tribler/tribler/search?q=tray_icon&unscoped_q=tray_icon).

Related to https://github.com/Tribler/tribler/pull/3841/files#r214415651

**Comment by devos50** [comment]
Please see #3844, I will check later whether I got them all.

**Comment by qstokkink** [comment]
We should make sure we get them all before 7.1 releases. Each naked tray icon access is an accident waiting to happen.
