### ISSUE TITLE
GUI Error: Could not connect with the Tribler Core within 20 seconds

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3849]
From reporter - Tribler 7.1.0-beta [#15957](http://reporter.tribler.org/stacktrace/15957)

```python

Traceback (most recent call last):
File "/usr/share/tribler/TriblerGUI/event_request_manager.py", line 149, in <lambda>
self.reply.error.connect(lambda error: self.on_error(error, reschedule_on_err=reschedule_on_err))
File "/usr/share/tribler/TriblerGUI/event_request_manager.py", line 54, in on_error
raise RuntimeError("Could not connect with the Tribler Core within 20 seconds")
RuntimeError: Could not connect with the Tribler Core within 20 seconds
```

**Comment by devos50** [comment]
Judging on the fact that Tribler has been running for over 2 hours, I suspect the connection with `/events` broke and it was unable to reconnect within 20 seconds.

Anyway, this one will be hard to debug I think.

**Comment by qstokkink** [comment]
Could this happen if you hard-kill the core?

**Comment by xoriole** [comment]
A comment received in the error reporter [[#18409]](http://reporter.tribler.org/stacktrace/18409)
>tried opening a magnet link after install. Opened it many times and multiple tribler windows popped up (Running a VM at the same time so I am already lagging). I closed most of them and then this happened. Hope this helps

**Comment by devos50** [comment]
Related to #4680 and #4678.

Since this issue is already covered by these two issues, I will close this one.
