### ISSUE TITLE
Add option to restart stalled torrents

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#3857]
I have noticed occasionally over many tribler versions that restarting the application will cause an incomplete inactive (0b/s) torrent to become active (max out the connection)... some torrent clients have a manual "update trackers" button which might help but in this cases DHT is the only peer source... so it seems like something could be more robust. There seem to be a lot of possible causes for a torrent to stall, so maybe list last contact time in the trackers tab, and list inactive peers in the peers tab with last contacted time for a bit of transparency.

Maybe some info on exit node queue though as other torrents perform fine that likely not the issue in this case... in the old UI was there not a routes count?

side note: DHT and the peers tab report 1 peer and the torrent reports 26.

**Comment by ichorid** [comment]
As we know after an epic struggle with #5319, Libtorrent will try to restart stalled torrents automatically every 15 minutes. This is good enough for practical use.
