### ISSUE TITLE
Cannot install on Ubuntu 18.04

### ISSUE THREAD

**Issue by tiotrom** [Tribler/tribler#3864]
tribler_7.0.2_all

![whxe5bs](https://user-images.githubusercontent.com/34804533/45260597-fb52e380-b3eb-11e8-8f65-e892b64de4ac.png)

**Comment by tiotrom** [comment]
Hi I get this error about vlc i.imgur.com/F37OuJy.png and if I try to install vlc I get more errors i.imgur.com/zuf2JEZ.png . So maybe for the new version there is an issue with the fact that it cannot install VLC. I will try to fix that and if that fixes the Tribler installation I'll update this post. Thanks!

**Comment by devos50** [comment]
@tiotrom this sounds like an issue with your Ubuntu installation. If it does not work, maybe you could try to install it from a PPA instead? See https://linuxconfig.org/how-to-install-latest-vlc-media-player-on-ubuntu-18-04-bionic-beaver-using-ppa for instructions.

Please let us know whether this works for you 👍

**Comment by tiotrom** [comment]
I just fixed it after I solved the VLC issue and then

```
 wget https://github.com/Tribler/tribler/releases/download/v7.1.0-rc1/tribler_7.1.0-rc1_all.deb
sudo apt-get install ./tribler_7.1.0-rc1_all.deb
```
