### ISSUE TITLE
Tribler tray indicator / applet dropdown menu is not shown on Ubuntu MATE 18.04 LTS

### ISSUE THREAD

**Issue by N0rbert** [Tribler/tribler#3865]
##### Tribler version/branch+revision: #####
Tribler_7.0.2_all

##### Operating system and version: #####
Ubuntu 18.04 LTS MATE

##### Steps to reproduce the behavior: #####
1. Install Tribler on Ubuntu 18.04 LTS MATE with 
       `wget http://mirrors.kernel.org/ubuntu/pool/universe/libs/libsodium/libsodium18_1.0.8-5_amd64.deb`
       `sudo apt-get install ./libsodium18_1.0.8-5_amd64.deb`
       `wget https://github.com/Tribler/tribler/releases/download/v7.0.2/Tribler_7.0.2_all.deb`
       `sudo apt-get install ./Tribler_7.0.2_all.deb`
2. Launch Tribler, ensure that it has icon ![tribler-icon](https://user-images.githubusercontent.com/309456/45263614-0716c800-b435-11e8-851c-f9cae2fdb675.png) in the tray.
3. Click on Tribler tray icon

##### Expected behavior: #####
Dropdown menu in Tribler tray indicator / applet icon is shown and usable.

##### Actual behavior: #####
Dropdown menu in Tribler tray indicator / applet icon is not shown and unusable.
See image ![tribler-menu](https://user-images.githubusercontent.com/309456/45263624-683e9b80-b435-11e8-8a16-2ee8419e863c.png).

**Comment by xoriole** [comment]
Thank you for the report. I'm not sure if this is ubuntu mate specific bug. We'll look into it. 

Also, we would like you could try our latest pre-release
[https://github.com/Tribler/tribler/releases](https://github.com/Tribler/tribler/releases)

**Comment by N0rbert** [comment]
Tested with tribler_7.1.0-rc1_all.deb. It fixes [bug 3864](https://github.com/Tribler/tribler/issues/3864) and has dropdown menu:

![tribler-tray-rc](https://user-images.githubusercontent.com/309456/45264412-caeb6380-b444-11e8-9dea-7a10264701ac.png)



Thank you!

**Comment by devos50** [comment]
Thanks for letting us know 👍 . Since this issue is considered fixed, I will close this one and #3864.
