### ISSUE TITLE
Tests are not cleaning up the disk

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3867]
We observed that windows tests were not cleaning up the resources properly. Apparently, sqlite directory inside dotTribler was not cleaned. 

Fun fact: the storage space used by these leftover files was 129GB.

**Comment by qstokkink** [comment]
It seems like it should do this though:

https://github.com/Tribler/tribler/blob/fb331f2701249b3e9ced9921556dfb43c8f52212/Tribler/Test/test_as_server.py#L108
