### ISSUE TITLE
Unrealistic number of seeds on torrent

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#3893]
Tribler version: devel.

Tribler FR channel has a crazy number or seeders reported on OpenSUSE torrent.
![too_many](https://user-images.githubusercontent.com/2509103/45828255-66f45500-bcf8-11e8-95dc-eeab38182290.png)

**Comment by qstokkink** [comment]
This reminds me of #3223, where we had -65000 seeders.

**Comment by devos50** [comment]
This is data from the wild and anything could be present there (even non-integer values). We could have a basic sanity check, i.e. if the number of leechers/seeders makes sense (are within a reasonable range).

**Comment by devos50** [comment]
This issue is due to the information returned by the tracker. There is not much we can do to enforce honest reports by the tracker.
