### ISSUE TITLE
IPv8 debug pane master peers are non-descriptive

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#3901]
![afbeelding](https://user-images.githubusercontent.com/3630389/45928981-ecbc0e80-bf4b-11e8-925e-59ec249f0b5c.png)

It looks like all the master peers are equal. We should probably use the `mid`/`sha1` here to differentiate them.

**Comment by devos50** [comment]
All master peers start with `3081a7...`. Maybe we could show the last 6 hex characters instead?

**Comment by qstokkink** [comment]
Also a good idea, anything but this actually 😃
