### ISSUE TITLE
Tribler could crash if navigating to downloads and filtering immediately after startup

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3939]
I saw this one in the error reporter:

```
Traceback (most recent call last):
File "TriblerGUI\widgets\downloadspage.py", line 212, in on_downloads_tab_button_clicked
File "TriblerGUI\widgets\downloadspage.py", line 188, in update_download_visibility
AttributeError: 'QTreeWidgetItem' object has no attribute 'download_info'
```

When loading the list of downloads for the first time, we show a `loading...` indicator, which is a `LoadingListItem` object. When filtering downloads (initiated by clicking on one of the buttons at the top of the downloads page), we assume items in this list are of the `DownloadWidgetItem` type.

**Comment by xoriole** [comment]
Fixed by #3940
