### ISSUE TITLE
Yet another UnicodeDecodeError

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3956]
From reporter []() - Tribler 7.1.0 
Date: [2018-10-10](http://reporter.tribler.org/crashreport_daily/2018-10-10)

platform:	Windows-10-10.0.17134-SP0 (AMD64)
python:	2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
tribler_uptime:	222.899999857

Stacktrace:
```python
Traceback (most recent call last):
File "TriblerGUI\tribler_window.py", line 687, in on_confirm_add_directory_dialog
File "TriblerGUI\tribler_window.py", line 397, in perform_start_download_request
UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 21: ordinal not in range(128)
```

**Comment by qstokkink** [comment]
https://github.com/Tribler/tribler/blob/next/TriblerGUI/tribler_window.py#L397

**Comment by qstokkink** [comment]
This will work, but it is not quite beautiful:

```
>>> g = lambda x: u''.join(unichr(ord(c)) for c in x)
>>> "%s%s" % (g(u''), g('\x92'))
u'\x92'
```

**Comment by xoriole** [comment]
Even with weird unicode characters, Tribler seems to handle it fine. I find it difficult to crash Tribler.
![capture](https://user-images.githubusercontent.com/1442867/46811157-80764300-cd72-11e8-890b-709745903bf3.PNG)

**Comment by xoriole** [comment]
More stacktraces related to unicode
```python
Traceback (most recent call last):
File "TriblerGUI\tribler_window.py", line 681, in on_confirm_add_directory_dialog
File "lib\nturl2path.py", line 67, in pathname2url
File "lib\urllib.py", line 1299, in quote
KeyError: u'\xea'
```

**Comment by xoriole** [comment]
Most of these issues are fixed, closing the issue.
