### ISSUE TITLE
Unusual memory error

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3961]
From reporter - Tribler 7.1.0 [#16988](http://reporter.tribler.org/stacktrace/16998)

Platform:	Windows-10-10.0.17134-SP0(AMD64)
Uptime:	20896.8280001 (5.8hrs)
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 130, in on_read_data
RuntimeError: [Failure instance: Traceback: <type 'exceptions.MemoryError'>: 
lib\site-packages\twisted\internet\base.py:878:runUntilCurrent
lib\site-packages\twisted\internet\task.py:240:__call__
lib\site-packages\twisted\internet\defer.py:321:addCallback
lib\site-packages\twisted\internet\defer.py:310:addCallbacks
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:653:_runCallbacks
lib\site-packages\twisted\internet\task.py:228:cb
lib\site-packages\twisted\internet\task.py:276:_scheduleFrom
lib\site-packages\twisted\internet\base.py:759:callLater
]
```
There does not seem to be much information about the cause of error, so maybe we should add memory usage info (from resource monitor) in the error reporter to have a better idea what's happening.

**Comment by devos50** [comment]
It might be that the system was running out of memory. There is indeed no further information. I like the idea of adding memory information to the error reporter 👍
