### ISSUE TITLE
Recent Tribler versions wont install on Ubuntu 14.04LTS due to unmet dependencies

### ISSUE THREAD

**Issue by MikeHarpes** [Tribler/tribler#3962]
#### Please, fill all relevant items: ####

- [ ] I have read CONTRIBUTING.rst

- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
7.0.2, 7.1.0

##### Operating system and version: #####
Ubuntu 14.04LTS

##### Steps to reproduce the behavior: #####
dpkg -i tribler_<version>_all.deb

##### Expected behavior: #####
Tribler would be installed

##### Actual behavior: #####
Tribler fails to install due to unmet dependencies as per thread:
https://forum.tribler.org/t/tribler-7-0-2-wont-install-on-ubuntu-14-04-lts/4793

##### Relevant log file output: #####
sudo dpkg -i tribler_7.1.0_all.deb
Selecting previously unselected package tribler.
(Reading database … 1988043 files and directories currently installed.)
Preparing to unpack tribler_7.1.0_all.deb …
Unpacking tribler (7.1.0) …
dpkg: dependency problems prevent configuration of tribler:
tribler depends on python-cryptography; however:
Package python-cryptography is not installed.
tribler depends on python-libnacl; however:
Package python-libnacl is not installed.
tribler depends on python-libtorrent (>= 0.16.18); however:
Package python-libtorrent is not installed.
tribler depends on python-networkx; however:
Package python-networkx is not installed.
tribler depends on python-pyqt5; however:
Package python-pyqt5 is not installed.
tribler depends on python-pyqt5.qtsvg; however:
Package python-pyqt5.qtsvg is not installed.

dpkg: error processing package tribler (–install):
dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.22-1ubuntu1.1) …
Processing triggers for gnome-menus (3.10.1-0ubuntu2) …
Processing triggers for bamfdaemon (0.5.1+14.04.20140409-0ubuntu1) …
Rebuilding /usr/share/applications/bamf-2.index…
Processing triggers for mime-support (3.54ubuntu1.1) …
Processing triggers for gconf2 (3.2.6-0ubuntu2) …
Processing triggers for man-db (2.6.7.1-1ubuntu1) …
Errors were encountered while processing:
tribler

Does Tribler depend on some exotic packages which are not available in the standard Ubuntu repositories and if so where can I find these packages ?

**Comment by devos50** [comment]
Tribler requires various packages which seem to not be available in the Ubuntu 14.04 repositories. As far as I'm aware, Tribler should be able to locate all packages when installing on (at least) Ubuntu 16.04. We should make this clear on our website/READMEs.

Alternatively, you could try to compile/install the missing packages from source or by using pip. For instance, you can install `libnacl`, `networkx` and possibly `pyqt5` using pip. Libtorrent and its Python bindings are harder to install from source. Please see [here](https://www.libtorrent.org/python_binding.html) for more details on how to do this.

Please let me know if you have any other question regarding the installation of dependencies!

**Comment by Dmole** [comment]
Ubuntu 14.04 is EOL in ~6 months (April 2019) anyway.

**Comment by devos50** [comment]
Since Ubuntu 14.04 is not supported anymore, I will close this issue.
