### ISSUE TITLE
.Triblerexitnode_cache.dat

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#3963]
.Triblerexitnode_cache.dat
should be
.Tribler/exitnode_cache.dat

**Comment by devos50** [comment]
Thanks for reporting! There is probably an error when constructing the path to this file.

**Comment by qstokkink** [comment]
This should be a `join()` instead of a `+`:

https://github.com/Tribler/tribler/blob/c0c7b5e0162448bad60f907b286300e343dc254f/Tribler/community/triblertunnel/community.py#L42
