### ISSUE TITLE
Cant turn off token mining

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#3965]
Restarted v7.1.0 and it just keeps downloading to credit_mining.

```
grep -A 3 credit_mining ~/.Tribler/triblerd.conf
[credit_mining]
sources = ,
enabled = False
max_disk_space = 53687091200
```

```
rm -r ~/.Tribler/{collected_*,dlcheckpoints,logs}
```
seems to be a workaround (or it coincidentally started behaving)

**Comment by devos50** [comment]
We should prevent credit mining downloads from being loaded from the checkpoints if it's enabled. Should be easy to fix.
