### ISSUE TITLE
True GigaChannels with 1 billion magnet links

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3971]
Tribler aims to be a realistic alternative to Youtube. Goal: support an unbounded wealth of user-generated content. Solution: create a Bittorrent swarm of any magnet link collection.

_1 channel may contain up to 1 billion magnet links_

A Youtube-alternative requires seamless scalability of a server-free video platform; beyond anything scientists have been able to create so far. Fast growth needs to be accommodated, for instance, Netflix has a growth rate 200.000 new users per day.
![image](https://user-images.githubusercontent.com/325224/47154004-693ed480-d2e1-11e8-9074-78490495cee8.png)
Current Tribler channels do not support envisioned growth rate. For instance, Youtube channels obtains lot of new subscribers each day. Taking some [stats](https://socialblade.com/blog/youtube-milestones-four-channels-hit-one-million-subscribers-every-day/) of the Internets, we see that:
- More than 300 channels are hitting the 10,000 subscriber mark every day.
- More than 40 channels are hitting the 100,000 subscriber mark every day.
- Around 4 channels are hitting the 1 million subscriber mark every day.

Youtube channels with a gigantic amount of videos:
1. [1013672 videos](https://www.youtube.com/watch?v=8nW_cPi_Sbs&list=UUtykkZYAT4lbeG3CBhSfLrw)
1. [727931 videos](https://www.youtube.com/watch?v=e8NWj6cMMps&list=UUdf7KqPteLls_gmI7kjntfw)
1. [624745 videos](https://www.youtube.com/watch?v=btPqcoECBeM&list=UUsLiV4WJfkTEHH0b9PmRklw)

The 10 Biggest YouTube Channels Right Now
1. PewDiePie. Subscribers: 66.1 million.
1. Dude Perfect. Subscribers: 34.54 million.
1. HolaSoyGerman. Subscribers: 34.48 million.
1. whinderssonnunes. Subscribers: 31.4 million.
1. elrubiusOMG. Subscribers: 30.83 million.
1. Fernanfloo. Subscribers: 29.34 million.
1. JuegaGerman. Subscribers: 28.95 million.
1. VEGETTA777. Subscribers: 23.85 million.

### Technical Details

Above statistics are about the number of users subscribed to 1 channel. We will create 1 bittorrent swarm for each channel. If we project above subscribed numbers to Gigachannels we can expect near instantaneous access to a random partial selection of magnet links. If changes are made to the channel, the Gigachannel swarm is updated automatically. Changes to the Gigachannel should be quick and never trigger hash re-checks. This issue does not cover the discovery of Gigachannels or spreading update of Gigachannels. Fast incremental and hierarchical traversal of Gigachannels is also very much left as future work. Keep it a huge dumb list for starters.

1 billion magnet links represents a significant storage size. For example, 1 billion times ```magnet:?xt=urn:btih:23ABBAA2A7D44A4EAFCBC907DB475376D1422629``` equals _61 GByte_ at minimum.

Requirement: 1 computer generates 1 billion random magnet links, one valid magnet link, and creates a channel. The channel address is made available to another Tribler instance and download is started. We allow unlimited transfer time, but no errors are allowed to occur.

**Comment by synctext** [comment]
[a large effort is ongoing](https://github.com/Tribler/tribler/tree/f_channel20) to implement above concept. [PR](https://github.com/Tribler/tribler/pull/3923) and early [Jenkins experimental](https://jenkins-ci.tribler.org/job/pers/job/channels2_experiment_devos50/lastSuccessfulBuild/) results with 10k magnet links:
![image](https://user-images.githubusercontent.com/325224/47156733-03098000-d2e8-11e8-90a3-6901739c9aba.png)

**Comment by synctext** [comment]
> nice thing for testing system scalability, but useless to users

Yes, this issue only covers the raw storage of magnet blurbs. For real usage we need magnet links with proper naming and cryptographic signatures.

**Comment by devos50** [comment]
It's not only about naming, but also about _presentation_. When the basic functionality is working, we should discuss a way to make it easy for users to locate their favorite content fast and reliable.

**Comment by devos50** [comment]
More experimental Jenkins results can be found [here](https://jenkins-ci.tribler.org/job/validation_experiments/job/validation_experiment_gigachannels/13/) (small scale, 20 nodes that create a channel with 200 random torrents).

![known_channels](https://user-images.githubusercontent.com/1707075/53255055-1e84fd00-36c5-11e9-99f9-299636307f7a.png)

**Comment by synctext** [comment]
That is a solid starting point. Do we have a Jenkins server with space for 1 billion magnet links?

**Comment by devos50** [comment]
Storage is no problem at all. During the experiment, each instance generates 200 fake torrents and starts sharing them with others. This number can easily be increased, however, I noticed that it takes quite some time to generate these torrents (even a small number) and add them to your channel. To share 1 billion magnet links, I would propose to pre-generate them on one of our servers and not generate them on-demand during the experiment.

**Comment by ichorid** [comment]
@devos50 , generating torrents is much faster than sending them over, if one doesn't impose any correctness constraints on them. In my experiments, creating 1K fake torrents typically took less than a few seconds.

@synctext we can safely assume that a single torrent never takes more than 1K space in storage space (DB and .mdblob forms combined). Therefore, to store 1*10^9 torrent entries we'll have to provide no more than 1TB space on the sender, and the same amount of space on the receiver. A couple of 1 TB HDDs should suffice.

**Comment by synctext** [comment]
@ichorid Just bumping this ticket again. Please make a real 1 billion links script and performance graph, possibly after we are in Release Candidate mode this month.

**Comment by ichorid** [comment]
For all practical purposes, we got channels with millions of torrents in the system right now. Though, the architecture of using torrents to send big channels data is inherently flawed due to the "unstable infohash" problem: #4677 

Closing this one.
