### ISSUE TITLE
Bunch of socket/twisted errors

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3991]
From error reporter - Tribler v7.1.2 [#17688](http://reporter.tribler.org/stacktrace/17688)

Platform:	Windows-7-6.1.7601-SP1 (AMD64)
Tribler_uptime:	8111.59899998
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 130, in on_read_data
RuntimeError: [Failure instance: Traceback (failure with no frames): <class 'twisted.web.client.PartialDownloadError'>: 200 OK
]
```

**Comment by qstokkink** [comment]
This is probably due to some virus scanner blocking network/socket traffic.

**Comment by xoriole** [comment]
I think we can close this
