### ISSUE TITLE
"0 MBytes given to community" even though Tribler is running for a while.

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#4005]
#### Please, fill all relevant items: ####

- [ ] I have read CONTRIBUTING.rst

- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

`HEAD detached at v7.1.2`, window title showing `Tribler 7.0.0-GIT`.

##### Operating system and version: #####

Linux Debian, amd64. Network is behind NAT.

##### Steps to reproduce the behavior: #####

* Checkout tribler from recent tag, update submodules.
* Run `./tribler.sh`.
* Observe downloads from existing, old database being seeded.
* Set "Allow Tribler to be exit node", "Enable token mining" and "Unlimited seeding" settings; save.
* Downloading something anonymously. See token balance drop to negative number.
* Leave Tribler running overnight.

##### Expected behavior: #####

Megabytes getting given to community, "people you helped" counter goes on.
Alternatively, some warning message is displayed explaining why you cannot help the community.

##### Actual behavior: #####

"0 MBytes given to community"
"0 People you helped"
Nothing special being displayed.

**Comment by synctext** [comment]
> Network is behind NAT.

Good to hear about how bad the performance is when you are not connectable. We need to work on that. Guess you will have a 5x ish boost of credits if you manager to get port forwarding going for the several ports used by Tribler.

Btw cool that you are running an exit node!

**Comment by vi** [comment]
Where can I set the forwarded port? I don't see something like "network settings" where I can manually input IP address and port advertised for incoming connections and actual local port to listen.

**Comment by devos50** [comment]
Whether you are selected for relaying services is an unpredicatable process and if there are few people downloading with more than one hop anonymity (which is the default setting), your balance will not increase.

We run a few machines in our lab which balances are sometimes stale and do not increase for hours. Eventually, it is likely to see an increase of the number of tokens but then again, it depends on the network.

> Where can I set the forwarded port?

I think @synctext means that you should do the port forwarding in the router itself, if others are unable to NAT-puncture you. Also, thanks for running an exit node 👍 

I will close this issue. Please let me know if there are other issues related to the balance not increasing.
