### ISSUE TITLE
Remove channel torrents from downloads list

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4014]
At this moment, when the user downloads a channel through the new GigaChannel subsystem, the corresponding torrent download is shown in Tribler "Downloads" list. It's fine for testing and debugging purposes, but unacceptable for production release. We could hide these completely, but we really want this info to be available for debugging purposes (and advanced users might want to see how popular the channel is). Some ways for solving this:

1. Create a new separate tab in the "Downloads" menu, right after the "Inactive" tab.
2. Create a new separate tab in the "Debug" window showing channel downloads.
3. Add "Show channel torrents" option to options menu that would reveal channel torrents in the main "Downloads" list.

Please, put your opinion on what would be better for users.

**Comment by synctext** [comment]
Goid plan:new separate tab in the "Downloads" menu.
Plus additional debug info about the discovered Gigachannels from that IPv8 community.

**Comment by ichorid** [comment]
Fixed by #4040
