### ISSUE TITLE
Full anonymity on torrent download

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4021]
Currently we support anonymous downloading and seeding but still, anonymity is leaked during naked metadata request. We could do the metadata request with the tunnel enabled session to prevent leaking peer IP. Obviously, this will result in slower lookup but it is a trade off for better privacy. We could enable choice in UI whether the user wants to have full anonymity or better performance.

**Comment by ichorid** [comment]
Solved in 7.5
