### ISSUE TITLE
Downloading channels with 0 infohash

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#4032]
Users who have created a channel, but have not added any torrents to it, will share a channel with a `00000000000000000000` infohash. Right now we treat this as any other torrent and join the null swarm. We should only download channels which are not the null swarm.

**Comment by qstokkink** [comment]
@ichorid this is fixed now right?

**Comment by ichorid** [comment]
Good point! I'll fix that.

**Comment by ichorid** [comment]
Yep. Already fixed in #4090
