### ISSUE TITLE
Adding more Github badges: code maintainability

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#4061]
Consider adding pretty badges like [Python FifoLock](https://github.com/michalc/fifolock/blob/master/README.md) people have
https://codeclimate.com/github/Tribler/tribler

**Comment by qstokkink** [comment]
We have accrued a nice Christmas tree of badges now. I consider this solved.

![badges](https://github.com/Tribler/tribler/assets/3630389/ccbc9e2e-68f8-4814-b5e9-3f9966c9fd48)
