### ISSUE TITLE
Can't name created torrents.

### ISSUE THREAD

**Issue by slayerbrk** [Tribler/tribler#4077]
##### Tribler version/branch+revision: #####
7.1.3
##### Operating system and version: #####
Windows 10 Insider Preview 18290.1000
##### Steps to reproduce the behavior: #####
Create custom torrent
Add torent name
Name listed as base file name rather than added name
##### Expected behavior: #####
Custom name used.
##### Actual behavior: #####
Custom name ignored.

**Comment by daddydeadpool** [comment]
I'm trying to create a custom channel but all my torrents show up with the name shows and category xxx, which it is not, rather than the given name. I was hoping to be able to share my vast library of files but due to them lacking any form of searchability I'm unable to do so.

**Comment by xoriole** [comment]
Currently, it is a known limitation but we're working on a new mechanism for creating and sharing scalable channels. Checkout [True GigaChannels](https://github.com/Tribler/tribler/issues/3971). We'll be releasing an experimental version soon and we would like you to try out and give us your valuable feedback if you would.

**Comment by qstokkink** [comment]
@ichorid in the new system: torrents now use the mdblob-based name, instead of the file name right? Meaning this is solved.

**Comment by ichorid** [comment]
@qstokkink , yep. But we still have to add the option to edit mdblob-based name, though.

**Comment by devos50** [comment]
I consider this issue solved in 7.3.
