### ISSUE TITLE
Streaming video anonymity mode selection

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4084]
When a user clicks "Play" button on Tribler video torrent, the video starts streaming in anonymous mode by default. It could take **up to several minutes** to build a tunnel circuit for a download, but users' typical attention span is **no more than 10 seconds.** This performance is unacceptable, especially for new users that just open Tribler, click on something, get frustrated and then close it to delete and never install again.

Therefore, we should provide an option for users to select whether they want anonymous or non-anonymous streaming video experience. This could be done by, e.g. raising a popup window on clicking "Play" button. This window will contain two big icons with descriptions of download modes.

**Comment by devos50** [comment]
We have a feature freeze for 7.5 now, moving this issue to the next milestone.

**Comment by hbiyik** [comment]
Now there is a progress indicator in player page for qt ui. Users have a visual sense of speed and an idea when to expect for the video to start streaming, i think this solves most of the misexpectations.

**Comment by ichorid** [comment]
@hbiyik , thanks for your contribution, it really adds clarity to the GUI. However, anonymity mode selection is still important.
BTW, how do you mostly use Tribler for streaming in Kodi: with or without anonymity?

**Comment by hbiyik** [comment]
I personally use it in anon mode, and i dont see a use case where someone would download anon, but stream non-anon (or vice-versa). If a user would be ok to stream "non-anon", then it wouldn't make much sense to start the download in anon mode in the first place.

The problem for me was, i had no idea what was going on when entered in the stream mode, a black screen, nothing was hapenning etc..

**Comment by ichorid** [comment]
Seems like [adding a toggle button](https://github.com/Tribler/tribler/issues/4854) is going to be the best solution after all...

**Comment by hbiyik** [comment]
may be right click context menu item to downloads page to exit from streaming mode would help also, currently streaming mode only exits when player clicks stop button in the video player. A context menu will save few clicks if the user is already in download window.

**Comment by ichorid** [comment]
VLC is dead
