### ISSUE TITLE
Tribler shows "0.0 GB Token balance" when not fully initialized

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#4087]
##### Tribler version/branch+revision: #####

v7.1.3

##### Operating system and version: #####

Linux

##### Steps to reproduce the behavior: #####

1. Cold-start Tribler
2. Wait for about 10 seconds until window appears
3. Wait for a minute until cogs stop spinning and it shows the main window
4. Check token balance at the top

##### Expected behavior: #####

It either shows actual token balance or nothing (or something like "--.- GB Token balance").

##### Actual behavior: #####

It displays zero token balance for some time, before revealing the real balance.

**Comment by xoriole** [comment]
Thank you for the suggestion
