### ISSUE TITLE
Undefined name: 'MediaDiscovererDescription' in vlc.py

### ISSUE THREAD

**Issue by cclauss** [Tribler/tribler#4093]
- [x] I have read CONTRIBUTING.rst

This was [__fixed in upstream__](https://github.com/oaubert/python-vlc/issues/55#ref-issue-340153679) with the class defined at https://github.com/oaubert/python-vlc/blob/bcd28a7c4fdaa38a0a272fd4617741c740c30de0/generated/3.0/vlc.py#L1591-L1599 so it might be useful to re-vendor a current version of __vlc.py__.

```
./TriblerGUI/vlc.py:4784:50: F821 undefined name 'MediaDiscovererDescription'
                   ctypes.POINTER(ctypes.POINTER(MediaDiscovererDescription)))
                                                 ^
./TriblerGUI/vlc.py:4796:41: F821 undefined name 'MediaDiscovererDescription'
                   None, ctypes.POINTER(MediaDiscovererDescription), ctypes.c_size_t)
                                        ^
```

**Comment by cclauss** [comment]
On the label...  This is Python issue but it is not a Python3 issue.

**Comment by devos50** [comment]
Thanks!
