### ISSUE TITLE
Build: Can we eliminate pylint: disable=redefined-builtin for six.moves imports?

### ISSUE THREAD

**Issue by cclauss** [Tribler/tribler#4122]
__from six import unichr__  # pylint: disable=redefined-builtin

These pylint directives clutter the code.  We are ___purposefully___ using the six module to redefine certain builtins like __unichr__ that are incompatible with Python 3.  The default PyLint configurations allows __six.moves__ redefinition because it is such a common practice these daze.

Even when we [modify our .pylintrc file to allow __six.moves__ redefinition](https://github.com/Tribler/tribler/pull/4121/files#diff-d6d3d73911fd3ad6f39e4027f763b307R117) our PyLint _still_ flags these and forces us to clutter up our code with distracting comments.

Does the build PyLint command resets __--redefining-builtins-modules__ to have a more restrictive value than the PyLint default?

**Comment by qstokkink** [comment]
Shouldn't that exception allow `six` instead of `six.moves`?

**Comment by devos50** [comment]
As an alternative, we can ignore these pylint errors. Note that our Pylinter does only check *changed* lines and not all lines.

**Comment by cclauss** [comment]
How do we find out _exact_ PyLint command that is used in the build process.  Normally changes to __.pylintrc__ should determine what happens but this could be overridden on the command line.

**Comment by qstokkink** [comment]
>  _exact_ PyLint command that is used

https://github.com/Tribler/gumby/blob/devel/scripts/run_nosetests_for_jenkins.sh#L51

**Comment by cclauss** [comment]
Fixed in Tribler/gumby#388
