### ISSUE TITLE
Trustchain scalability and stess testing experiment

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#4140]
Having a Trustchain database with infinite growth is a problem. 

_task: build a Trustchain block collector and automatic generator_

Trustchain is becoming a key performance bottleneck, as our network is growing to 20k concurrent users. We are experiencing the limits of our performance. Overlap with prior issue: https://github.com/Tribler/tribler/issues/3861

Solution: dedicated experiment with 1 real full Tribler instance and an emulated "mocked" network of thousands or even over a million peers. All communication with the network will result in a response from a single generator that generates IPv8-based and Trustchain-compliant return traffic. The generator of an infinite amount of faked Trustchain records is then used for performance analysis. These Trustchain records have valid binary content, but the data is fake. The Tribler Trustchain community can be tested and we will able to conduct a performance analysis. 

**Desired outcome** Repeatable performance numbers for a nightly job and performance regression analysis. For instance, after collecting 1 million Trustchain records the read performance for a random Trustchain lookup becomes 500 ms and writing a newly discovered Trustchain record becomes 300 ms.

Background reading: [thesis using the same technique](https://github.com/Tribler/tribler/issues/2623#issuecomment-420220536) plus [.PDF file](https://repository.tudelft.nl/islandora/object/uuid:af9b2fe1-7055-42ce-a513-1d6b1a6cc041/datastream/OBJ/download)
[Source code](https://github.com/YourDaddyIsHere/Local_Virtual_Walker_Network_without_port_limit)

**Comment by grimadas** [comment]
Please assign me to this task

**Comment by grimadas** [comment]
Progress so far:
- I run the crawler twisted 
- Have local code running 

![image](https://user-images.githubusercontent.com/5897440/52468537-4d5d8800-2b89-11e9-8912-5597e2cd9c72.png)

Plans for the next week: 
- Single mocked interface with generated Trustchain blocks

**Comment by synctext** [comment]
Latest numbers: 1 million peers databases, 10 trustchain records per peer and 21 KByte per Trustchain record = 210 GByte.

**Comment by grimadas** [comment]
**Update:** 

The number i mentioned before is the size of a block as a Python object - 21 KB.  
The half-block in serialised format takes only 290 bytes.  

 
**Database testing**

I tested on the scalability of the database (sqlite).
Whole database is stored in two files WAL and db. 
All transactions first go through write-ahead log, that grows linearly with 60 KB per transaction(see figure).    
![image](https://user-images.githubusercontent.com/5897440/52846378-bdc85400-3109-11e9-9805-94c7f140ab07.png)

After collecting 9 MB sqlite initiates vacuum and flushes to db file. 
The db file is growing linearly with with each block adding 500 bytes.

![image](https://user-images.githubusercontent.com/5897440/52850293-6b8c3080-3113-11e9-8370-ba87334d66e9.png)


![image](https://user-images.githubusercontent.com/5897440/52850021-ca9d7580-3112-11e9-9b22-1238095f069c.png)

![image](https://user-images.githubusercontent.com/5897440/52851325-1e5d8e00-3116-11e9-9774-684d88f94972.png)

**Comment by grimadas** [comment]
We can now try our stress testing and scalability on DAS5 and Jenkins.  

For example, 9 peers sending 100 blocks per sec to one peer(let's say leader node).
https://jenkins-ci.tribler.org/job/pers/job/validation_experiment_trustchain_bulat/44/
See attached histogram of blocks arrived at leader node.
![image](https://user-images.githubusercontent.com/5897440/53202290-6b65c680-3626-11e9-9253-960b1bb6b5ed.png)
![image](https://user-images.githubusercontent.com/5897440/53202305-728cd480-3626-11e9-97c6-fe833f4f0b35.png)

**Comment by devos50** [comment]
Cool!

**Comment by synctext** [comment]
#4471 Overlap.
Possible new 1st year thesis direction: heavy benchmarking of Trustchain and compare to Holochain, [blockbench](https://www.comp.nus.edu.sg/~ooibc/blockbench.pdf), and the seminal PeerReview publication. Input for a Usenix submission. We have freeriding detection that scales.

**Comment by synctext** [comment]
Storing Trustchain records is rational and incentive compatible: prevent being defrauded by malicious actors.

**Comment by synctext** [comment]
Update....We need performance understanding, "fault attribution", and "fault resolution". Fault is a neutral term which covers both malicious and non-malicious (e.g. Byzantine failure) violations of the protocol, possibly resulting in double spending.
Scalability of fault detection, fault attribution and fault resolution is a worthy thesis chapter. Heavy benchmarking of Trustchain before X-Mas 2019 is required for Usenix.

**Comment by devos50** [comment]
I already have some experiments for extensive double-spend detection, which shows that if everyone crawls the network and requests chains of others, double-spend can be detected within seconds. I included this graph in the (rejected) workshop submission of the market paper. The experiment should still be around on Github.

**Comment by qstokkink** [comment]
Trustchain has been removed and, therefore, this issue is no longer relevant.
