### ISSUE TITLE
Proof of Authorship on GigaChannel with TrustChain

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4144]
When an author adds a torrent of their work to GigaChannel(GC), this action could be recorded into the author's TrustChain(TC), effectively creating a **Proof of Authorship**. TC being a DAG, coupled with a working Trust Function(TF), allows any GC user to determine the original author of the infohash, thus enabling [**donation-based media economy**](#1).

The same mechanism can be used to publish any kind of publicly domain contents: government reports, notarized documents, Linux distro releases, etc.

This is the reason to record the creation of each mdblob entity with TrustChain.

**Comment by devos50** [comment]
I like the idea of this 'proof-of-ownership'. It aligns well with our other research work. As we have seen before, solid trust estimation functions are the main problem here but establishing a trust score for channel authors can definitely help us with sybil attacks and/or spam prevention.

> This is the reason to record the creation of each mdblob entity with TrustChain.

Recording every single .mdblob might be a bit much for now. I wonder whether it might be enough to record only mdblobs that specify channel creation? In a sense, this would store the channel metadata on-chain and the torrent metadata off-chain. In other words, we only store the root metadata entry on TrustChain. Would this be sufficient?

Related to #1

**Comment by qstokkink** [comment]
Why would a digital signature not suffice?

**Comment by ichorid** [comment]
@qstokkink , because a signature alone is not enough to determine who was first to sign a message.
Imagine Alice produces a music album and put it in public access with a signed mdblob on my channel. Then Bob can copy the infohash and publish it as if he was the original author. If Charlie then wants to donate to the album's author, he can't really decide who was the first to publish. TrustChain signing allows Charile to determine exactly who was the first to publish.

**Comment by devos50** [comment]
> TrustChain signing allows Charile to determine exactly who was the first to publish.

Unfortunately, this is not entirely true. Although we have a total ordering in each individual chain, there are situations where we cannot determine who was the first to publish (unlike linear blockchains like Bitcoin/Ethereum). I make the assumption here that we cannot rely on the timestamp in a TrustChain block. Note that it is possible to defer order information from transactions but if there is no transaction made between Alice and Bob, Charlie is unable to determine who was first.

**Comment by ichorid** [comment]
There can be established trusted parties in the network that provide just that - blocks with trusted timestamps. If Alice transacts with any of those after her publication, the order of authorship can be established.

**Comment by ichorid** [comment]
Another option is to use the trust function to break ties in this corner cases.

**Comment by synctext** [comment]
Let keep it as simple as possible for Gigachannel upcoming improvement releases: you can donate to a Gigachannel owner public key. Minimal viable product for a gift-based media economy.

**Comment by ichorid** [comment]
RIP TrustChain
