### ISSUE TITLE
Serving TrustChain as a Torrent

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4145]
TrustChain blocks can have arbitrary size and contents. Currently, we store the user's TrustChain in the SQLite database and spread it out using IPv8 queries. But TrustChain is, by definition, an _append-only_ data structure. This means we can write it into a file on disk as it grows, and periodically publish it in a torrent, as we do with GigaChannels.

In fact, GigaChannel already feature simple and efficient code to do just that: periodically dump binary data into file chunks, dynamically compressing the dumped data with LZ4 (and serving queries through IPv8).
GigaChannel allows us to hone our methods of managing collective-access to append-only data created by users. If it proves to be successful, eventually **GigaChannel can become a primary distribution method for TrustChain**.

As a first step towards this goal, we can add sidechain support to TrustChain, so we can experiment with various forms of sidechain offloading.

**Comment by devos50** [comment]
Partial overlap with #3484

**Comment by ichorid** [comment]
Yeah, a duplicate of #3484. Forgot about that one.
