### ISSUE TITLE
Error Insufficient Permissions

### ISSUE THREAD

**Issue by Aldo-f** [Tribler/tribler#4166]
##### Tribler version/branch+revision: #####
7.1.5

##### Operating system and version: #####
Windows 10 Pro - 1809
Build 17763.253

##### Steps to reproduce the behavior: #####
1) Add torrent
2) Click browse to choose new location
3) Don't choose a location / Hit cancel
4) See error:
Can't find path [error 3] **u''**
![](https://i.imgur.com/Ak2KnuG.png)

##### Expected behavior: #####
Don't show any error. (this is the tested path if no path is selected **u''**)
Or test the old path variable instead of no path.

**Comment by devos50** [comment]
Thank you for your feedback!
