### ISSUE TITLE
Feature request: "Import torrents from magnet/URL" should have a keyboard shortcut

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#4168]
##### Tribler version/branch+revision: #####

v7.1.5, from Git tag.

##### Steps to reproduce the behavior: #####

1. Look up for Ctrl+something near commonly used menu items like "Import torrents ..."
2. Try various Ctrl+O, Ctrl+I, etc.

##### Expected behavior: #####

There is some way to trigger that window mouse-free.
Obviously, after inserting a link with Ctrl+V, pressing Enter twice should finish adding it to Triber downloads and distributed torrent database.

##### Actual behavior: #####

Only "(+) -> Import ..." works.

---

Keyboard navigation is not a good part of current Tribler UI in general...

**Comment by Thomasedv** [comment]
In my opinion, should have a button for the drop down menu with add torrent options, since you can navigate the menu with arrow keys. I don't know if it would fit any standard keyboard shortcuts, but i keep wanting to use Ctrl + + (Plus sign).

**Comment by heldersepu** [comment]
Big +1 to this, there should be keyboard shortcuts to everything
