### ISSUE TITLE
'NoneType' object has no attribute 'is_valid'

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4190]
From error reporter - Tribler 7.2.0
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 133, in on_read_data
RuntimeError: [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'is_valid'
Tribler\Core\CreditMining\CreditMiningPolicy.py:243:run
Tribler\Core\Libtorrent\LibtorrentDownloadImpl.py:997:restart
Tribler\Core\Libtorrent\LibtorrentDownloadImpl.py:323:network_create_engine_wrapper
lib\site-packages\twisted\internet\defer.py:310:addCallbacks
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:653:_runCallbacks
Tribler\Core\Libtorrent\LibtorrentDownloadImpl.py:298:on_torrent_added
]
```

**Comment by qstokkink** [comment]
The assumption is that `def on_torrent_added(handle):` always gets called with a `handle` that is not `None`. Evidently, this is not the case.

**Comment by devos50** [comment]
The `on_torrent_added` method is the callback when adding a new torrent with `add_torrent` in the `LibtorrentMgr` class. It seems that [this line](https://github.com/Tribler/tribler/blob/release-7.2.0/Tribler/Core/Libtorrent/LibtorrentMgr.py#L342) does not return a handle.

**Comment by devos50** [comment]
@qstokkink you were nine seconds earlier :D

**Comment by qstokkink** [comment]
Actually, what the hell are we doing here anyway. `get_torrents()` returns a list of handles:

https://github.com/Tribler/tribler/blob/26db75db0be5376142a9b5ea6d77bcdf0ddd4a52/Tribler/Core/Libtorrent/LibtorrentMgr.py#L338

If we rewrite that line to:

```python
known = {str(h.info_hash()): h for h in ltsession.get_torrents()}
```

..and then return the `h` belonging to the `infohash`, we're done.

**Comment by qstokkink** [comment]
Could also possibly come from here:

https://github.com/Tribler/tribler/blob/26db75db0be5376142a9b5ea6d77bcdf0ddd4a52/Tribler/Core/Libtorrent/LibtorrentMgr.py#L402

**Comment by xoriole** [comment]
The issue is only reported in Linux2
