### ISSUE TITLE
Tribler for Linux stuck at Loading...

### ISSUE THREAD

**Issue by Tanath** [Tribler/tribler#4192]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
various
##### Operating system and version: #####
Manjaro Linux, various
##### Steps to reproduce the behavior: #####
Install & run Tribler on Manjaro, or clone github repo and run `./tribler.sh`.
##### Actual behavior: #####
The gears spin, it says "Loading..." but never progresses beyond that point. I've tried wiping Tribler config to start fresh, I've tried multiple computers. In over a year I haven't been able to get Tribler working on Linux.
##### Relevant log file output: #####
Nothing in logs. 0b files, nothing in `dmesg`.
GH repo version said in terminal: `ImportError: No module named pyipv8.ipv8.keyvault.private.libnaclkey` until I installed `python-cryptography`. Docs said only to install python2 version, which is in the dependencies. Now it gives `ImportError: No module named OpenSSL`. I think the dependencies need fixing.

**Comment by xoriole** [comment]
@Tanath Is it also the issue with the latest release 7.2.0?  If not, you could try installing the package from:
https://github.com/Tribler/tribler/releases/tag/v7.2.0

To be able to run from the source code obtained from github, you'll need to install all the dependencies. Here is a supporting documentation page.
https://tribler.readthedocs.io/en/next/development/development_on_linux.html

**Comment by Tanath** [comment]
I still have the package installed, so I should have all the dependencies. I still have all the ones it says I should from that page. 7.2.0-exp1 is the version I'm running currently. If I `git checkout v7.2.0` there's no difference - I still get the OpenSSL import error.

**Comment by qstokkink** [comment]
Just to be safe, did you also run this command: https://github.com/Tribler/py-ipv8#dependencies

**Comment by TheUserCreated** [comment]
You are most likely missing this dependency; `sudo pacman -S python2-pyopenssl`
However bear in mind if you are in fact missing this dependency, you are likely missing others, please see the link shared by @qstokkink

**Comment by Tanath** [comment]
I don't wish to use pip. I want to use repo packages so I can easily maintain my system, like keeping things up to date.

The `python2-pyopenssl` package was indeed missing. It's not listed as a dependency or in the Arch Linux command from the docs page. It and `python-cryptography` should be added.
