### ISSUE TITLE
Distribution via Flatpak, snap and/or appimage

### ISSUE THREAD

**Issue by QEDeD** [Tribler/tribler#4194]
This seems like a really awesome project you got going. I hope you will consider distributing via flatpak, snap and/or appimage, when time and resources allow :)

**Comment by qstokkink** [comment]
We have been looking at snap. As we are currently in the process of a major refactor (which eliminates a lot of dependencies), it will take a little time before we make a switch though.

**Comment by QEDeD** [comment]
> We have been looking at snap. As we are currently in the process of a major refactor (which eliminates a lot of dependencies), it will take a little time before we make a switch though.

Sounds like things are heading in the right direction!
