### ISSUE TITLE
Bug: Torrent seed reports continued downloading & ratio at 0 | Tribler 7.2.1, Win10x64

### ISSUE THREAD

**Issue by Brassfield** [Tribler/tribler#4195]
#### Please, fill all relevant items: ####

- [Y ] I have read CONTRIBUTING.rst

- [N ] I have tried with the latest pre-release version and I still can reproduce the issue.
_But it happened on both 7.2 and 7.2.1_
##### Tribler version/branch+revision: #####
7.2.1
##### Operating system and version: #####
Windows 10 64bit
##### Steps to reproduce the behavior: #####

Copy file/folder into TribblerDownload tree (e.g. latest Kali images, etc.)
Add existing torrent of file into Tribbler
Begin seeding

*adding additional testing in comment below - strange behavior continues after deleting a file and force rechecking the torrent*

##### Expected behavior: #####
Torrent reports sending data, but not downloading data
Ratio null or positive
Token balance increasing?

##### Actual behavior: #####

e.g. kali light 2018-4-amd64
Details: Ratio 0, up: 808.5 kb, down: 332.4kb

Both download and upload continue to increase. I don't know why download is increasing, as the file was complete when initially added to Tribbler & the client hasn't reported any download speed. 

As well, my token balance continues to increase.

##### Relevant log file output: #####
![ratio](https://user-images.githubusercontent.com/22226136/52148868-dfacdb80-261f-11e9-84dd-23f6b987b0a7.jpg)

**Comment by Brassfield** [comment]
This is likely related to: https://github.com/Tribler/tribler/issues/4161
But I didn't see any phantom download reported there.

**Comment by Brassfield** [comment]
This torrent has 2 files - the iso and a 100B sha hash.

I stopped the torrent, deleted the sha hash file, force rechecked the torrent. It's correctly recognized as 99% complete. I restart the torrent.

Acc'd to details:
the 100b file required >400kb data to download
ratio is now reported at >22x  (reported up/down should be more like 2x; assuming up figure is accurate, the actual ratio should be 13000x (~1.3M : 100b)

![image](https://user-images.githubusercontent.com/22226136/52149840-f1dc4900-2622-11e9-9b74-490cf237b149.png)

**Comment by ichorid** [comment]
Token mining and torrent ratio-related stuff to be discussed and reported in #4363
