### ISSUE TITLE
TunnelCommunity is very broken

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#4197]
After 60h uptime, no new credits have come in. Nothing earned in a whole week. Statistical implausible. Possible related to overloaded overlay. Also would explain the plummeting explorer.tribler.org stats. 
![screenshot from 2019-02-04 09-16-22](https://user-images.githubusercontent.com/325224/52196872-baa5ac00-285d-11e9-8422-3fad24dd0199.png)

**Comment by qstokkink** [comment]
We should probably set the default hop count to 2.

**Comment by devos50** [comment]
Changing of the TrustChain keys explains the lower block rate in explorer.tribler.org - this will be fixed automatically when the crawler uses the new keys, and it will fetch the missing blocks. I asked @xoriole to update the crawlers (and testnet crawler).

Regarding not getting credits, I will inspect this when I’m back.

**Comment by synctext** [comment]
Latest thought: this might be a demand issue. We have forked the network. We do not yet have much anon proxy demand on the new 7.2.1 network. 80% ish of our users are on old network.
Or could be a bug.

**Comment by qstokkink** [comment]
Possibly the TunnelCommunity is very broken (`7.2.2`).

I only have two circuits (for two downloads) which are closing after only transferring a few bytes:

![afbeelding](https://user-images.githubusercontent.com/3630389/52522440-c9d59100-2c85-11e9-9ee4-a17e485254e1.png)

My best circuit in an hour transferred 65kB before closing. For a torrent with thousands of seeders (Ubuntu 18.04).

**Comment by devos50** [comment]
Small chance that the exit nodes are overloaded (it’s weekend). Will check this when I’m home.

**Comment by synctext** [comment]
Confirmed on Ubuntu: "TunnelCommunity is very broken". This is a reason our token economy has collapsed. Exit nodes work great, tested with 1-hop. 60 seconds **animation** of Tribler 7.2.2 struggle with creating tunnel circuits:
![tribler_7 2 2-failures_to_make_2-hop_circuites_feb2019](https://user-images.githubusercontent.com/325224/52532967-f5f81d00-2d2c-11e9-8376-1bad9ffef2a7.gif)
Almost nothing get's through on 2-hops. Downloaded [1000+ seeder Ubuntu](http://torrent.ubuntu.com:6969/) torrent and the [.torrent for Debian](https://cdimage.debian.org/debian-cd/current/amd64/bt-cd/debian-9.7.0-amd64-xfce-CD-1.iso.torrent)
![screenshot from 2019-02-10 08-47-45](https://user-images.githubusercontent.com/325224/52532982-3c4d7c00-2d2d-11e9-84ec-3e8ba6312a29.png)
Above screenshot got some peers on DHT and even got through to the tracker! It downloaded 144.8 MByte succesfully. However, this download then get's stuck at 0 Kbps (sounds familiar from our users..). After the circuits get killed after 10minutes or MByte quota reached or some other unknown events; download stops and fails to recover:
![screenshot from 2019-02-10 12-26-06](https://user-images.githubusercontent.com/325224/52533099-1b862600-2d2f-11e9-9f1a-74ebba83ab1d.png)
We need integration testing and tooling to detect this. Would be great if we could detect bugs like this automatically and get confidence in our releases.

**Comment by devos50** [comment]
I suspect that this issue is somewhat related to the changes in the walking behaviour and Tribler might have trouble finding sufficient exit nodes (see https://github.com/Tribler/tribler/issues/4171#issuecomment-462126131). However, I'm not fully confident about the exact root cause of this yet.

**Comment by qstokkink** [comment]
> I suspect that this issue is somewhat related to the changes in the walking behaviour

This also happens with 1 hop circuits.

**Comment by synctext** [comment]
Solid stress testing with mainnet before release sounds good.

**Comment by qstokkink** [comment]
When scrolling through the issues, we may have actually already detected this before: #4089

**Comment by synctext** [comment]
OK, moving to that 2018 issue; #4089.
