### ISSUE TITLE
Signed hashes

### ISSUE THREAD

**Issue by amuuza** [Tribler/tribler#4198]
Hi,
https://github.com/Tribler/tribler/releases shows signed breakable hashes (MD5 and SHA1).
It also shows SHA256 hashes, but these ones, which are considered secure, are not signed.
Why?

**Comment by synctext** [comment]
Sadly, Bittorrent technology from June 2001 is based on sha1. Backwards compatibility requires sha1 support. We very much want to move the protocol beyond sha1 wuth our onion crypto.

**Comment by xoriole** [comment]
@amuuza Thank you for pointing out. Our build script was set up that way for a long time which signed MD5 and SHA1 hashes. I have just updated the build script to generate the signature for SHA256 hashes as well. So all the future releases will have them.
