### ISSUE TITLE
Watch folder - corrupted torrents

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4200]
From error reporter - Tribler 7.2.1 [[#20828]](http://reporter.tribler.org/stacktrace/20828)
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 133, in on_read_data
RuntimeError: [Failure instance: Traceback: <type 'exceptions.WindowsError'>: [Error 32] The process cannot access the file because it is being used by another process
lib\site-packages\twisted\internet\base.py:1243:run
lib\site-packages\twisted\internet\base.py:1252:mainLoop
lib\site-packages\twisted\internet\base.py:878:runUntilCurrent
lib\site-packages\twisted\internet\task.py:239:__call__
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:150:maybeDeferred
Tribler\Core\Modules\watch_folder.py:50:check_watch_folder
Tribler\Core\Modules\watch_folder.py:34:cleanup_torrent_file
]
```
Reported message from the user
>Somehow the .torrent files become corrupted & Tribler crashes when it rescans the files. Deleting teh files & restarting Tribler works fine until another file becomes corrupted & Tribler tries to rescan it, crashing the program again.

**Comment by qstokkink** [comment]
Perhaps `fix_torrent` is misbehaving?

**Comment by qstokkink** [comment]
I don't think we can solve this without a torrent file which triggers this. Specifically we need the torrent and the file path it resides on.
