### ISSUE TITLE
Set IPv8 default port back to 7759

### ISSUE THREAD

**Issue by noughtmare** [Tribler/tribler#4202]
I've read in the [FAQ](https://www.tribler.org/faq.html) that tribler uses port 7760 and 7759, but when I run netstat it doesn't show those as being used. The FAQ also says that this port is configurable in the settings menu, but I can only see the GUI/core connection port setting. (I suspect that the FAQ is outdated).

I've tried both version 7.1.5 and 7.2.1.

**Comment by qstokkink** [comment]
Even though `7759` is supposed to be the default port, we had a minor bug sneak into the codebase:

https://github.com/Tribler/tribler/blob/25fefdc3cd0ba0026225a417425c0de7f12fa535/Tribler/Core/Config/config.spec#L102

The default port is now randomly selected (defaulting to `-1`). You can change this by editing your `triblerd.conf` file in the `~/.Tribler` folder. Under the category `[dispersy]` you can then set the `port` to one of your liking. It should look something like this:

```
[dispersy]
port = 7759
```

**Comment by noughtmare** [comment]
Thanks. I see that [mainline_dht] and [libtorrent] have the same port option. Should those ports also be set and forwarded?

**Comment by qstokkink** [comment]
Short answer: yes.

However, normally Tribler performs the NAT hole punching of all of these ports by itself. You should only have to forward ports in case of very strict firewall settings.

**Comment by Anth0rx** [comment]
@qstokkink Is port 7759 the only port that is used for incoming connections? Behind a firewall I tried allowing and forwarding port 7759 for TCP and UDP to my system running Tribler. Are there any other ports that need to be allowed and forwarded?

**Comment by qstokkink** [comment]
@Anth0rx correct, that is indeed the port Tribler will try to claim. _However_, Tribler is made in such a way that you really shouldn't have to do any port forwarding on your hardware or in your firewall(s) and you shouldn't have to run Tribler in administrator mode or anything. If your Tribler is not working, there's probably something else going on. What issue are you experiencing?

**Comment by Anth0rx** [comment]
I am currently running Tribler as a flatpak. Could that be the cause of the problem?

**Comment by xoriole** [comment]
When running with existing state directory, Tribler flatpak worked for me but on an empty state directory, Tribler failed to work, core failed to start.
```
[PID:3] 2021-09-24 12:18:13,186 - INFO - TriblerGUI(147) - Will connect to events endpoint
[PID:3] 2021-09-24 12:18:13,237 - INFO - TriblerGUI(83) - Got Tribler core error: 1
Error in sys.excepthook:
Traceback (most recent call last):
  File "tribler_gui/error_handler.py", line 34, in gui_error
TypeError: can only concatenate str (not "NoneType") to str

Original exception was:
tribler_gui.utilities.CreationTraceback: 
  File "run_tribler.py", line 213, in <module>
  File "tribler_gui/utilities.py", line 395, in trackback_wrapper
  File "tribler_gui/event_request_manager.py", line 151, in connect


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tribler_gui/utilities.py", line 398, in trackback_wrapper
  File "tribler_gui/utilities.py", line 395, in trackback_wrapper
  File "tribler_gui/event_request_manager.py", line 151, in <lambda>
  File "tribler_gui/event_request_manager.py", line 87, in on_error
tribler_gui.event_request_manager.CoreConnectTimeoutError: Could not connect with the Tribler Core within 60 seconds
^C

```
