### ISSUE TITLE
Malicious torrents scanning

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4203]
Tribler does not do scans for malware in torrents and is not expected to do so but maybe in future, we would like to support it. Integrating a basic malware check does not seem like a big task though.

**Comment by ichorid** [comment]
"Every piece of software eventually wants to become the whole operating system" :wink:

**Comment by ichorid** [comment]
It is better to leave this out of scope. We don't need more bloat in Tribler, and our users can stand for themselves.
