### ISSUE TITLE
New version upgrade popup broken

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#4212]
Latest V7.2.2 of Tribler has a version checker for new releases. The GUI popup on Ubuntu has a bug. Clicking "OK" correctly opens a new tab within the default browser. Both clicking "ignore" and "later" failed to remove the popup. The only remedy was to Close Tribler, that worked. Note this was after 2 days of Tribler online time. Running the GIT version, which was not tagged "7.2.2" yet. Speculating that it could be that it sees this as a version downgrade in the string compare with ```tribler_7.2.1-9-g0186d3fc3_all.deb```.
![screenshot from 2019-02-11 09-50-44](https://user-images.githubusercontent.com/325224/52554380-f05f0d80-2de6-11e9-9eb6-40637f7f3d03.png)

**Comment by egbertbouman** [comment]
Just tested this with Tribler 7.5 and the popup closes correctly.
