### ISSUE TITLE
Twisted DNS lookup error in logs

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4228]
Lines like this appear in the latest builds regularly:
(moved from #4225 )
```python
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:653:_runCallbacks
/usr/lib/python2.7/dist-packages/twisted/internet/endpoints.py:954:startConnectionAttempts
] http://tracker.Debian--bay.org/announce
INFO    1550062866.55                   session:264  (HttpTrackerSession)  Error when querying http tracker: [Failure instance: Traceback: <class 'twisted.internet.error.DNSLookupError'>: DNS lookup failed: no results for hostname lookup: tracker.Debian--bay.org.
/usr/lib/python2.7/dist-packages/twisted/internet/_resolver.py:137:deliverResults
/usr/lib/python2.7/dist-packages/twisted/internet/endpoints.py:900:resolutionComplete
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:459:callback
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:567:_startRunCallbacks
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:653:_runCallbacks
/usr/lib/python2.7/dist-packages/twisted/internet/endpoints.py:954:startConnectionAttempts
] http://tracker.Debian--bay.org/announce
```

**Comment by ichorid** [comment]
@qstokkink,  @xoriole , could you please look into this?

**Comment by devos50** [comment]
When the UDP or HTTP tracker fails to get a response from a tracker, it simply logs the complete stack trace. Since a vast majority of trackers are dead and/or unreachable, this error occasionally shows up in the logs. We could log this stack trace in a less verbose way probably.

**Comment by synctext** [comment]
That would be great: a single line error

**Comment by devos50** [comment]
@ichorid please see [this](https://github.com/Tribler/tribler/blob/devel/Tribler/Core/TorrentChecker/session.py#L264) and [this](https://github.com/Tribler/tribler/blob/devel/Tribler/Core/TorrentChecker/session.py#L426) line. Instead of logging the complete `Failure` object, I believe we can print something like `failure.message` to only log a single line.

**Comment by ichorid** [comment]
Now we only have to figure out which code line actually produces this, and why this is not caught by lines @devos50 described above...
