### ISSUE TITLE
Cannot search for phrases

### ISSUE THREAD

**Issue by kazerniel** [Tribler/tribler#4229]
##### Tribler version/branch+revision: #####
7.2.2

##### Steps to reproduce the behavior: #####

Try to search for anything with multiple words.

##### Expected behavior: #####
To either show only results containing all the words, or at least show those results on top.

##### Actual behavior: #####

It shows lots of single-word-matching results, completely drowning out any relevant results.

--
When I try to search with quotes around the phrase, it makes no difference in the results. And if I'm typing the quoted phrase (instead of pasting as a whole), it gives the following error message (I guess because it's missing the closing quote, as I haven't finished typing) :
` Request error
` 
` An error occurred during the request:  
` 
` SQLError: malformed MATCH expression: [""word1 word2*"]`

**Comment by ichorid** [comment]
Solved by #4090
