### ISSUE TITLE
Fatal Error! Failed to execute script pyi_rth_qt5plugins  

### ISSUE THREAD

**Issue by enoloo** [Tribler/tribler#4237]
##### OPENING THE exe FILE. #####

---------------------------
Fatal Error!
---------------------------
Failed to execute script pyi_rth_qt5plugins

---------------------------
确定   
---------------------------

thx.

**Comment by xoriole** [comment]
@enoloo Is it a first time installation or upgrade from previous versions?

Just to make sure that it is not a proxy config issue.
Could you try removing these two lines from `%APPDATA%/.Tribler/triblerd.conf` file?
```
proxy_server = “”
proxy_auth = “”
```

**Comment by enoloo** [comment]
FIXED. thx.
