### ISSUE TITLE
GigaChannel community DB access batching

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4249]
Currently, for each incoming GigaChannel community gossip packet we open a separate DB session and process packets individually. This will really start to stress the DB when the gossip stream will rise to dozens of packets per second. We should solve this problem somehow, for example by batching DB access.

**Comment by synctext** [comment]
Note, IO Batching slowed us down in the past.

**Comment by ichorid** [comment]
That's why we're gonna "science this out" by setting up some meaningful experiments.

**Comment by synctext** [comment]
@kozlovsky Are we still closing and opening DB sessions for each incoming UDP packet?
Are we expecting any gains from refactoring this?

**Comment by drew2a** [comment]
It is not relevant anymore:
- #7669
