### ISSUE TITLE
RuntimeError on Twisted

### ISSUE THREAD

**Issue by bodobodak** [Tribler/tribler#4303]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Relevant log file output: #####
```python
RuntimeError: Unhandled Error Traceback (most recent call last):
   File "lib\site-packages\twisted\internet\base.py", line 428, in fireEvent
        File "lib\site-packages\twisted\internet\defer.py", line 321, in addCallback
        File "lib\site-packages\twisted\internet\defer.py", line 310, in addCallbacks
        File "lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
```

**Comment by devos50** [comment]
@bodobodak thank you for your report. Do you have any more information about this error? Did it happen when you performed a specific action in Tribler?

**Comment by bodobodak** [comment]
It happened at the opening of the tribble.
Tribler did not open.

**Comment by bodobodak** [comment]
It happened at the opening of the tribble.
Tribler did not open.Versions 7.2.2
______________________________________________________________
> Od: "Martijn de Vos" <notifications@github.com>
> Komu: "Tribler/tribler" <tribler@noreply.github.com>
> Dátum: 06.03.2019 11:04
> Predmet: Re: [Tribler/tribler] RuntimeError: Unhandled Error Traceback (most recent call last): File "lib\site-packages\twisted\internet\base.py", line 428, in fireEvent File "lib\site-packages\twisted\internet\defer.py", line 321, in addCallback File "lib\site-packages\twisted\internet\defer.py", line 310, in addCallbacks File "lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks (#4303)
>
@bodobodak <https://github.com/bodobodak> thank you for your report. Do you have any more information about this error? Did it happen when you performed a specific action in Tribler?

**Comment by devos50** [comment]
@bodobodak On what operating system did you see this error?

**Comment by bodobodak** [comment]
WINDOWS 10 Home 64bit
______________________________________________________________
> Od: "Martijn de Vos" <notifications@github.com>
> Komu: "Tribler/tribler" <tribler@noreply.github.com>
> Dátum: 08.03.2019 14:37
> Predmet: Re: [Tribler/tribler] RuntimeError on Twisted (#4303)
>
@bodobodak <https://github.com/bodobodak> On what operating system did you see this error?
