### ISSUE TITLE
Loading screen stays up

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#4317]
- [x] I have tried with the latest pre-release version and I still can reproduce the issue.
Even 7.3.0
##### Tribler version/branch+revision: #####
7.2.2 and 7.1.1
##### Operating system and version: #####
Windows 10 Insider build 18348
##### Steps to reproduce the behavior: #####
Start Tribler
##### Expected behavior: #####
Tribler to startup normally and show home screen
##### Actual behavior: #####
Tribler start and shows loading screen and stays there for xx hours.
When I installed 7.3, I was able to start download a Torrent and when that got initiated, I got an extra normal screen, where the download started and when that was finished, I was able to export each Torrent in my Library one by one (!! not all in once!!!). Uninstalled, removed .Tribler folder and reinstalled, to try and rebuild Library, but loading screen appeared again and stayed. Tried a second machine which had not changed and that ALSO stayed on loading, as if a server within the Tribler network isn't responding?
Tried a 3rd machine with just 1 entry within its Library and that started normal in 7.3.0, so???
What is causing Tribler to stay in the loading screen and what can I do to get you some more information?

**Comment by Nubro01** [comment]
I just read thet the latest version I run, Insider 18348 has a spectre build fix. The machine that does run well and which does NOT show the loading screen is running Windows 10 1809. My laptop AND dersktop with the loading problem are on 18348 and the problems started AFTER I updated to 18348, so???

**Comment by xoriole** [comment]
@Nubro01 It is difficult to estimate the cause for this issue. As you mentioned about in your comment about Win10 18348 build, we'll have to investigate that and get back to you.

In the meantime, could you check if there are logs present?

**Comment by Nubro01** [comment]
Just a 1k resource log and 1k gui info.log the rest is empty within C:\Users\userid\AppData\Roaming\.Tribler\logs

**Comment by Nubro01** [comment]
Today I received build 18351 and that resolved the problem. After instaall was finished, I started Tribler and that showed the loading screen, but a few seconds later the normal screen.
I have no clue what caused this?
