### ISSUE TITLE
Add a separate queue for threaded asynchronous Channels DB access

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4320]
I've just done an improvised benchmark of anonymous downloading Ubuntu torrent while simultaneously processing a large GigaChannel from disk. DB i/o **definitely** affects tunnels performance. Badly.

If the database is allowed to take as much time as it wants, even on a separate thread, and even if I break up the transaction into small batches that take approx 100ms each, tunnels performance drops from 600-700 kb/s to 150-350 kb/s and GigaChannel-related GUI becomes unresponsive. If I add `sleep(0.05)` after each batch, the responsiveness and performance are restored to 80% of their original levels (at least it feels so).

Apparently, we've hit both the [thread starvation problem](https://stackoverflow.com/questions/37123486/thread-starvation-while-locking-in-a-loop-in-python) and the limits of Twisted reactor scheduling. The only way to fix this problem is to **move GigaChannel and TorrentChecker into a separate process with a separate REST endpoint**.

**Comment by devos50** [comment]
Nice that we have some numbers on the impact of database I/O now! I must say that the drop in tunnel performance is not that bad and better than I expected (I expected it to drop significantly, to only a few kb/s).

A suggestion made by @synctext is to notify the user by displaying the status bar when a (big) channel is being processed. We could make a new event for this, and transmit it to the GUI over the events socket.

For further optimization, I would suggest to first focus on a (more formal) experiment (e.g. written in Gumby) which we can quickly repeat with different parameters.

**Comment by qstokkink** [comment]
[I have some master thesis work on fast platform independent inter-process communication](https://github.com/qstokkink/tribler/tree/tunnelprocess_rc2/Tribler/community/tunnel/processes) (almost most of the logic on top of the communication logic will be out-of-date by now). This should give a nice copy-paste basis for testing some stuff.

Do we want this for 7.3 already though?

**Comment by ichorid** [comment]
On my workplace PC, when I download Ubuntu torrent over the tunnels, it gives me 2.1 MB/s. If GigaChannel database just **contains** a channel of 1 million entries, the speed drops to 600-800 KB/s.
If I start to upload the channel to the database, the connection dies almost completely, dropping to 50-150 KB/s. Now that's in the case of unoptimized upload routine (500ms batches).

When I set the batch size to 100ms and add 50ms `sleep` periods, the download is able to proceed with 600-800 KB/s.

However, when I search for "test", the core becomes frozen for 30 seconds. The result is that the background disk-reading thread time-outs and the directory reading process stops.

**Comment by qstokkink** [comment]
@ichorid could you check out what happens to your CPU while this is happening?

**Comment by ichorid** [comment]
![cpu](https://user-images.githubusercontent.com/2509103/53957516-d6aba000-40de-11e9-87e6-3e72b8e00176.png)

**Comment by qstokkink** [comment]
Thanks, doesn't seem like there are any CPU issues then.

**Comment by ichorid** [comment]
@qstokkink , the disk activity goes crazy, though. I think that is because we are forced to do a lot of small-scale writes to the database, to maintain the responsiveness, and that results in write amplification, WAL thrashing, etc. Adding `sleep` between batches definitely helps with that, but throughput obviously suffers.

**Comment by qstokkink** [comment]
Is there some sort of SQLite configuration for small writes?

**Comment by synctext** [comment]
Is is possible to reproduce these results into Jenkins without too much (Gumby) efforts?

If Tribler never uses over 10% of CPU that's fine (e.g. IPv8 for the win). For now the priority is to get everything working and get an operational "downloading 1 billion item channel" and "downloading through 2-hops anonymously". Performance analysis for CPU and IO are **definitely** next.

**Comment by ichorid** [comment]
SQLite is optimized for small writes. It is just we have to do *big* writes in really *small* batches for reasons of concurrency.

**Comment by ichorid** [comment]
BTW, DB upgrader moved into background thread and forced to run in 100ms batches **runs 30x times slower than without batching**. We really, really want to move DB i/o to a separate process, and make a special scheduler for it...

**Comment by synctext** [comment]
#4459 is now main performance ticket for tunnels. Its not about IO. See cpu breakdown. Plus code needs repairing...

**Comment by viric** [comment]
Isn't it that sqlite is a bit unfit to this database task? Maybe a different persistent storage would fit better these conditions. I don't know which, though.

**Comment by ichorid** [comment]
> Isn't it that sqlite is a bit unfit to this database task? 

Please, argue :wink:

**Comment by viric** [comment]
I have no idea about what cheap options there are, but here we talk about data that likely fits just fine in RAM, and we are updating a sqlite disk database synchronously every 100ms (gigachannel processing), with multiple indices in the table. Isn't it?

**Comment by ichorid** [comment]
Good point, but that depends on the DB size and the RAM size. Currently, if you subscribe to three biggest channels, your DB will take more than 3 GBs on disk. Also, the biggest problem is that the DB solution must conform to a pretty strict list of requirements, such as:
 1. Be a natively compiled library available for each major platform (Python is very slow)
 2. Allow for fas full-text searches and offer robust query language
 3. Allow for asynchronous access from Python (<- SQLite is lacking in this, but this ticket is about that)
 4. Provide at least some form of disk persistence (<- thanks for pointing out this is a pretty loose requirement)
 
Of all options I studied, SQLite fits the best. Also, AFAIK, there is no DB that can provide both sub-linear _insert_ and _query_ performance. Maybe you know one?

**Comment by viric** [comment]
Processing 2 milion payloads that translate to queries and inserts in a DB should be doable quite fast. But currently each insert is synchronised to disk, and each operation is serialized and operating in the new updated dataset, with atomic updates.

I think the point should come from not needing atomic updates to the db for every payload, and even less, to disk. journal_mode memory maybe could help from sqlite, for this last part.

I don't know tribler enough but I think that some parts of tribler can be fine working with an outdated view of the DB while the gigachannel processing builds a big update, not needing a global view update for every payload.

**Comment by ichorid** [comment]
> I don't know tribler enough but I think that some parts of tribler can be fine working with an outdated view of the DB while the gigachannel processing builds a big update, not needing a global view update for every payload.

Google had to solve this kind of problem about 10 years ago when they learned to update indexes without downtime. The problem is not as easy as it looks like, as it requires an intricate custom locking/versioning system to maintain the illusion of uninterrupted operation while doing big changes to the index. I hope we will be able to pull off something like that in the future.

**Comment by viric** [comment]
I still naively think that there is something fundamentally wrong for such contention between operations. :)

I will write if I have any clear idea to handle this.

**Comment by ichorid** [comment]
> I still naively think that there is something fundamentally wrong for such contention between operations. :)

Well, that's basically the same problem that prevents Bitcoin from scaling to more than a few dozens transactions per second: contention on central index.

**Comment by viric** [comment]
Ah, but bitcoin is a *distributed* ledger shared among not-trusted accountants! Here we talk about a local database of a single process.

I saw https://www.sqlite.org/cgi/src/doc/begin-concurrent/doc/begin_concurrent.md but I'd have to try some benchmarks.

**Comment by ichorid** [comment]
Thanks for pointing out the possiblity of creating Concurren Transactions in SQLite. From that page:

> then monotonically increasing values are assigned automatically. This is terrible for concurrency, as it all but ensures that all new rows are added to the same database page. In such situations, it is better to explicitly assign random values to INTEGER PRIMARY KEY fields.


>The nature of some types of indexes, for example indexes on timestamp fields, can also cause problems (as concurrent transactions may assign similar timestamps that will be stored on the same db page to new records). In these cases the database schema may need to be rethought to increase the concurrency provided by page-level-locking

This underlines my previous point about doing a careful redesign of the schema.

**Comment by viric** [comment]
Couldn't you create a temporary table quickly with all inserts/updates and then sql merge quickly to the main table? Like queuing all the inserts for a given squashed mdblob for the end of the mdblob

**Comment by ichorid** [comment]
AFAIK, SQLIte b-trees are not optimized for merging... The tables would still have to be locked for the duration of the merge, at least for the sake of FTS index. `Select`'s should still be possible though, but the GUI should be aware of the locking. That **is** the idea of a separate queue. We'll have to manage the locking ourseleves at the Python level manuall, instead of pushing it to SQLite level.

**Comment by viric** [comment]
I'd have to see a benchmark first. Maybe the table is only locked a very little amount of time.

**Comment by ichorid** [comment]
I did a benchmark for this some time ago. Doing the stuff directly, table-to-table is approximately 20 times faster than doing it the way it is done now (at least on my PC). On a slow machine the delta should be even more.

Anyways, how about helping us by doing a benchmark yourself, eh? :wink:

**Comment by ichorid** [comment]
Also, see https://github.com/Tribler/tribler/issues/5469 for similar stuff.

**Comment by viric** [comment]
I didn't say I won't do a benchmark. I'm just starting on this :)

**Comment by ichorid** [comment]
:facepalm:

SQLite usese `DELETE` synchronization mode by default, not `WAL`. I thought `WAL` is the default and built the system accordingly. The thing is `WAL` is a _persistent flag_, meaning that at some point I've set it to my test database (probably manually), and then happily used it afterwards.

So, @viric , you can try setting `PRAGMA synchronous = WAL;` and see if it increases your performance. It should, especially in the case of small writes (hello, channels processing!).

**Comment by viric** [comment]
All my tests were using WAL. That's the first I thought and the first
switch I touched.

**Comment by ichorid** [comment]
Did you use `PRAGMA synchronous = NORMAL;` though?

**Comment by viric** [comment]
I did in the very beggining and noticed it was very slow, and quickly
switched to wal. I can't report much about normal.

**Comment by ichorid** [comment]
Measuring GIL contention with `gil-load` during processing the channel blob (only the batch-processing part):
```
held: 0.799 (0.799, 0.799, 0.799)
wait: 0.602 (0.602, 0.602, 0.602)
  <140213046888256>
    held: 0.784 (0.784, 0.784, 0.784)
    wait: 0.136 (0.136, 0.136, 0.136)
  <140212433307392>
    held: 0.015 (0.015, 0.015, 0.015)
    wait: 0.583 (0.583, 0.583, 0.583)
```

The background thread is *holding* GIL for 1% of time, while *waiting* for it for 58% of time. :facepalm:

**Comment by drew2a** [comment]
It is not relevant anymore:
- #7669
