### ISSUE TITLE
Token Mining 2.0

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4363]
**Token Mining 2.0**
*Improving credit mining to be intuitive, user-friendly and profitable*

2.0 Features:
- Add/remove multiple channels as the source
- Add/remove multiple torrents from different channels
- Support selection of policies
- Support auto addition of popular dark hashes
- Persistent upload/download statistics
- Visible buttons to start/stop mining
- Ability to mine from unsubscribed channels
- Support [0 hops mining](https://github.com/Tribler/tribler/issues/4065), e.g. to boost balance for people who are already on VPNs. 

Currently, a single channel is only supported and new torrents cannot be added for mining. The mining statistics are only session based and are not persisted across restarts. Even though the policy seems to be working, the feature seems to be confusing to users. We should make this Tribler feature better.

Related: https://github.com/Tribler/tribler/issues/4241

**Comment by trevorhough802** [comment]
The ability to change where the mining content is downloaded would be a huge help too.. my downloads are set to a different "Storage" hard drive and yet my mining content is downloaded to my Downloads folder (Windows) on the main system hard drive.

**Comment by devos50** [comment]
Like #3778, this issue is quite some work still and might be better suited for a release after 7.4. @xoriole do you agree?

**Comment by xoriole** [comment]
Yes, I agree to move it to 7.4+ release

**Comment by ichorid** [comment]
By @devos50  in https://github.com/Tribler/tribler/issues/4161#issuecomment-469643741 regarding the torrent ratios:

>We did some investigation of this issue. The ratio is computed from the `all_time_upload` and `all_time_download` fields, whereas the numbers shown in the torrent details pane are derived from `total_upload` and `total_download` in a `torrent_status` object.

>We should keep track of *all* bytes being uploaded and downloaded since these are the bytes you actually pay for if you are using an exit node. So this includes communication overhead which does not directly include "useful" traffic (where you exchange pieces with others). One workaround for this is to manually keep track of all bytes exchanged in a libtorrent download, by using the `total_upload` and `total_download` fields. These values can be written away during checkpointing.

>This issue is a bit more involved than we thought and at this point, it might not be a good idea to make changes to the way we manage data reported by libtorrent. We will fix this later.

**Comment by ichorid** [comment]
:skull: RIP credit mining :skull:
