### ISSUE TITLE
snap crashes on start-up (missing wayland-egl)

### ISSUE THREAD

**Issue by da2x** [Tribler/tribler#4367]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
7.2.0-exp1

##### Operating system and version: #####
Fedora Workstation 29

##### Steps to reproduce the behavior: #####
1. sudo dnf install snapd -y && reboot
2. [sudo snap install --edge tribler-bittorrent --devmode](https://github.com/Tribler/tribler/pull/4240#issuecomment-467404148)
3. tribler-bittorrent
##### Expected behavior: #####
The program should run.

##### Actual behavior: #####
```
INFO    1552353564.48        single_application:23   (root)  __init__()
This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)
```

cc/@xoriole

**Comment by da2x** [comment]
This may be relevant: https://github.com/pbek/QOwnNotes/pull/1012/files

**Comment by xoriole** [comment]
@da2x I haven't tried installing the snap in Fedora. I'll check and update the snap. Thank you for reporting.

**Comment by devos50** [comment]
@xoriole we also do not have a machine with Fedora installed. This might be a valuable addition to our infrastructure 👍

**Comment by da2x** [comment]
You should be able to reproduce this on Ubuntu or any other Linux distribution too. Assuming you’re using GNOME, you can choose to login to a GNOME on Wayland session from the login screen. This is the default on GNOME and on Fedora, but Ubuntu does some customization and I don’t believe they ship with Wayland by default.

**Comment by FlorianFranzen** [comment]
If you use Wayland, chances are that the environmental variable ```QT_QPA_PLATFORM``` is to ```wayland-egl``` by default to use Qt's Wayland platform plugin, which turns most Qt apps into native Wayland apps (as opposed to using a compatibility layer like xwayland).
However for this to work you will have to install the QtWayland module for the version of Qt that Tribler is using. If you are for some reason not able to do so, you can always unset the environmental variable or set it to ```xcb``` to force Qt and thereby Tribler to use X11 instead, e.g. by running ```QT_QPA_PLATFORM=xcb tribler``` on the Terminal.

**Comment by devos50** [comment]
Since our snap build is too unstable at the moment, let's defer this issue to 7.5 and focus on the remaining issues.

**Comment by bam80** [comment]
Have there been some progress since then?

**Comment by devos50** [comment]
@bam80 unfortunately not. We are quite understaffed at the moment so we focus mostly on the stability of our Windows, Mac and our `.deb` build. Any contributions are welcome, however!

**Comment by Dmole** [comment]
The Flatpak partly works on Fedora https://github.com/Tribler/tribler/issues/4938

**Comment by ichorid** [comment]
Probably fixed, but we don't really support Snap at the moment :shrug:
