### ISSUE TITLE
Help podcasters get into P2P with RSS-to-torrent magic channels

### ISSUE THREAD

**Issue by da2x** [Tribler/tribler#4371]
Every podcast have an RSS feed with audio files enclosured in the feed. Tribler should automatically download the attached audio files, create torrents for them, and attach them to their channel. This would make it easy for podcasters to get into peer-to-peer distribution to their audiences. All they’d need is to download and run the Tribler client, create a channel, and link their existing feeds.

**Comment by drew2a** [comment]
It is not relevant anymore:
- #7669
