### ISSUE TITLE
Streaming mode should get a caching progress indicator

### ISSUE THREAD

**Issue by tiotrom** [Tribler/tribler#4376]
I have Manjaro Gnome with Tribler tribler  7.2.2-1
It works to find files but streaming simply does nothing. Can it stream before the download or do I have to wait for the download to then stream through Tribler? 
Cheers!

EDIT: It seems that if you let it download a file for longer and has like 20% downloaded it will start streaming. Maybe you can close this thread. It just is confusing when clicking the play video and you see no loading. I suggest adding the peers and download speed on the player somewhere in plain sight else people might think it is not working.

**Comment by devos50** [comment]
Thank you for your feedback!

Note that if you play a download (by pressing the play button), it will enter linear mode download. Besides this, there is no toggle to download the torrent in linear (streaming) mode. I think this is a valuable enhancement to Tribler and it would be nice to have this feature in our 7.4 release.

> It just is confusing when clicking the play video and you see no loading

I agree. We spent some time in the past on having some kind of 'buffering' indicator when playing a video, however, there are some technical limitations that prevents us from showing text on top of a VLC player screen.

**Comment by hbiyik** [comment]
Stream prebuffering status indication is implemented in this PR.

Now also there is an option to toggle between stream and download mode

https://github.com/Tribler/tribler/pull/5301
