### ISSUE TITLE
Remaining issues for stable 7.3 release

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4390]
- [x] **Gossip for empty channels**
There are cases where there are no torrents in the channel even though the channel metadata might indicate X number of torrents. In the GUI, if we have such empty channels, we should download preview torrents from the channel to populate at least a few popular torrents.
PR: https://github.com/Tribler/tribler/pull/4450 partly covers this issue

- [x] **Add to torrents to your channel; context menu**
To add a torrent to a channel, we specifically have to add it through the channel. We should make it easier to add torrent from any part of Tribler. One option is to add a context right-click menu with 'Add to My Channel' option.

- [x] **Heart icon hover issue**
The subscribe heart icon shows the same icon over hover and selected state.

- [x] **Subscription (-1) issue**
The subscription count could go below zero which should not happen.

- [x] **Move create torrent button to the top right + icon**
We should move 'Create torrent' button currently present inside My Channel to the top right + icon and include a checkbox in the dialog whether to include the created torrent in My Channel.

- [x] **Checkbox to add a download to my channel**
A checkbox in the download dialog to add the torrent to My Channel will make it easier for the user to add more content to channel.

- [x] **Add channel preview notification**
At the moment, the channel view provides no indication about the current status of a channel. It is frustrating to look at the channel that boasts thousands of torrents, but is actually near-empty. Instead, if a channel is still in a preview state, we must indicate it to the user.

- [x] **Torrent info never disappears**
Currently, torrent info never disappears once a torrent is selected. This should be fixed.

- [x] **One-shot pop-up dialog to add existing downloads to personal channel**
When the conversion process is finished if the user's personal channel have already been created, there should arise a pop-up window asking the user if they want to add their old Tribler downloads to it. If the personal channel was never created, the same pop-up should be shown when the user *creates* the personal channel.

- [x] **Search shows only remote results sometimes**
BUG: when doing global search for any term, sometimes only remote results appear. Repeat the search, and all results can come up. This should be fixed before release.
Fixed in #4483 

- [x] **PageDown does not work properly**
(Introduced in #4373)
BUG: when trying to scroll down a table view in GigaChannel with PgDn button, it only works until the next part of the table is loaded from DB. Then it loses focus and one can't scroll further. The same is true for cursor buttons scrolling. Note that scrolling with buttons worked a couple of months ago.
Fixed in #4483

**Comment by devos50** [comment]
@xoriole could you specify these issues in more detail? I want to address some of these issues but I don't have a clear idea on them.

**Comment by ichorid** [comment]
The remaining issues were closed by #4505
