### ISSUE TITLE
Inconsistent whitespace stripping from magnet URIs

### ISSUE THREAD

**Issue by da2x** [Tribler/tribler#4422]
#### Please, fill all relevant items: ####

- [X] I have read CONTRIBUTING.rst

- [X] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
V7.2.2

##### Operating system and version: #####
macOS 10.14.3

##### Steps to reproduce the behavior: #####
1. Copy the following string (including leading and trailing whitespace):
```
  magnet:?xt=urn:btih:0b31508aeb0634b347b8270c7bee4d411b5d4109  
```
2. Paste it into the Import torrent from magnet/URL dialog.
3. Click Add

##### Expected behavior: #####
Leading and trailing whitespace should be stripped from the string.

##### Actual behavior: #####
The dialog passes the initial checks and continues to the next dialog and loads the list of files included in the torrent. Then you’re also told the URI is invalid.

**Comment by devos50** [comment]
Thank for your report!

**Comment by AE-001-1001** [comment]
0b31508aeb0634b347b8270c7bee4d411b5d4109
So i found this while I was poking around in the webarchive.
