### ISSUE TITLE
Magnet link not working

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#4438]
##### Tribler version/branch+revision: #####
7.3 march 26th build
##### Operating system and version: #####
Windows 10 Insider 18362
##### Steps to reproduce the behavior: #####
Find a Torrent and click the magnet link
##### Expected behavior: #####
Tribler is accepting the link and opens a download location and file selection dialog window
##### Actual behavior: #####
A second tribler task is started and a blank screen is shown, after a while the screen closes, but nothing is started or downloaded.
The last couple of builds also did not show the files to select for download, if I just select ok, then torrent is started and all files are downloaded.

**Comment by xoriole** [comment]
@Nubro01 Thank you for reporting. I'm not sure if I can understand what you meant.
> A second tribler task is started and a blank screen is shown, after a while the screen closes, but nothing is started or downloaded.

When you try to download a torrent using magnet link, Tribler should show a dialog box either with a list of files inside the torrent or display a timeout message as shown in the pic below. I'm not sure what you are referring as blank screen and closing of the screen after a while. Could you possibly attach a (safe) screenshot?
![timeout](https://user-images.githubusercontent.com/1442867/55062200-bdf73000-5075-11e9-9cc2-dfcf22a6d2c9.png)

**Comment by Nubro01** [comment]
I know how Tribler works, I have been testing it for ages! When I select a Magnet Link with the latest 7.3 versions under windows 10 build 1903 (!!!) I get a blank white screen for a few seconds, no time and no cause to print  just a white screen, I would think. The above dialog is not appearing!
If I manage to download the torrent and add it manually to Tribler, the dialog indeed appears, but the files to select are never show, when I just select download, the torrents is started and all files are downloaded, when I try to exclude a file, in the previous versions of 7.3, Tribler would abend. 
I'll try it again as soon as I have a new file to download.

**Comment by synctext** [comment]
Complex issue. Trying to understand..
Are you opening a magnet link from a browser, while Tribler is already running? So we messed up the 2nd instance check logic. You have tested a 7.3 version that did work?
A white screen glitch..

Btw it would be really efficient to fix your bugs with instant visualisation of the Tribler flaw. Any Ubuntu download as a test case.
Animated Gif creation Tool: https://github.com/phw/peek
.gif uploads are supported by Github.

**Comment by devos50** [comment]
I see several problems here.

First, I think the issue here is that clicking on a magnet link (outside of Tribler) leads to a white screen. I just tested this on our Windows 10 machine and it seems to work fine. @Nubro01 a screenshot would indeed be helpful to better understand this issue.

> when I try to exclude a file, in the previous versions of 7.3, Tribler would abend.

Do you mean that Tribler crashes when you try to exclude a file from a download? Does this issue persist in version 7.3?

**Comment by Nubro01** [comment]
Below the message from the app log that appears when I select a magnet link. a new Tribler task is started, because another entry appears on my taskbar, when I click fast enough a white screen is shown with the title "tribler", it disappears, hence the error and the download is not started.
Remember this is Windows 10 1903 build 18362, so it might also be this Windows build!!!
In previous builds of Tribler a new Tribler windows was opened and the download dialog was shown in that new window and it stayed active showing a duplicate Tribler windows, until I stopped it, in the meantime the orginal tribler windows would continued running.

Logboeknaam:   Application
Bron:          Application Error
Datum:         31-3-2019 10:45:58
Gebeurtenis-id:1000
Taakcategorie: (100)
Niveau:        Fout
Trefwoorden:   Klassiek
Gebruiker:     n.v.t.
Computer:      NUBRO01-W10
Beschrijving:
Naam van toepassing met fout: Tribler.exe, versie: 0.0.0.0, tijdstempel: 0x5b8e995f
Naam van module met fout: faulthandler.pyd, versie: 0.0.0.0, tijdstempel: 0x59bc66d9
Uitzonderingscode: 0xc0000005
Foutmarge: 0x00000000000027c3
Id van proces met fout: 0x2894
Starttijd van toepassing met fout: 0x01d4e79e261c8c36
Pad naar toepassing met fout: D:\Program Files\Tribler\Tribler.exe
Pad naar module met fout: D:\Program Files\Tribler\faulthandler.pyd
Rapport-id: 5626785c-80c0-47b2-9002-b9dbda78e38e
Volledige pakketnaam met fout: 
Relatieve toepassings-id van pakket met fout: 
Gebeurtenis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-03-31T08:45:58.985368700Z" />
    <EventRecordID>23116</EventRecordID>
    <Channel>Application</Channel>
    <Computer>NUBRO01-W10</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Tribler.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5b8e995f</Data>
    <Data>faulthandler.pyd</Data>
    <Data>0.0.0.0</Data>
    <Data>59bc66d9</Data>
    <Data>c0000005</Data>
    <Data>00000000000027c3</Data>
    <Data>2894</Data>
    <Data>01d4e79e261c8c36</Data>
    <Data>D:\Program Files\Tribler\Tribler.exe</Data>
    <Data>D:\Program Files\Tribler\faulthandler.pyd</Data>
    <Data>5626785c-80c0-47b2-9002-b9dbda78e38e</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by devos50** [comment]
Thank you for the report! The error seems to be in the `faulthandler` module:

> Pad naar module met fout: D:\Program Files\Tribler\faulthandler.pyd

**Comment by Nubro01** [comment]
![afbeelding](https://user-images.githubusercontent.com/1146496/55287013-e186e700-53a3-11e9-832f-6b3cda501383.png)

**Comment by Nubro01** [comment]
As you see, not much info!

**Comment by devos50** [comment]
@Nubro01 could you try to **backup** and temporarily remove the `D:\Program Files\Tribler\faulthandler.pyd` and try again?

**Comment by Nubro01** [comment]
This is an example of a Torrent, never showing the containing files, but as soon as I select download, the Torrents is started and all files are downloaded.

![afbeelding](https://user-images.githubusercontent.com/1146496/55287050-7c7fc100-53a4-11e9-8999-7c505e7b6096.png)

**Comment by Nubro01** [comment]
Removing \faulthandler.pyd, makes the windows appear and show much shorter and the windows log still shows the same error, I'll try a reboot, maybe \faulthandler.pyd is cached.

**Comment by Nubro01** [comment]
After a reboot no windows log entry is created, but as said, a second tribler windows is started and gone even faster. The funy thing is, when I select the hidden pictograms, a number Tribler icons is shown, equal to the number of download trials. When I place the mouse over them, they disappear.
This time I just tried once, so
![afbeelding](https://user-images.githubusercontent.com/1146496/55287312-91aa1f00-53a7-11e9-9abf-2183a1ce60bc.png)

**Comment by Thomasedv** [comment]
Regarding the tray icons, I'm gonna have a guess that each Tribler program is creating it's own icon for each process opened by a link, before handing the magnet til the running instance, and then terminating. Window being windows, icons rarely disappear until you try to hover them in the tray. So i don't think that's a symptom of the problem at all.  I see this with many programs myself.

**Comment by devos50** [comment]
The problem with the tray icon is there for quite a long time already. We have tried various solutions which all did not work out. I believe that the problem is related to the Qt library somehow.

**Comment by Thomasedv** [comment]
You mean, they remain even after Tribler should have closed? 
Windows is lazy with cleanup, so it doesn't usually remove icons until the user hovers them, so i wouldn't really put it as a bug unless the icons don't go away when they mouse hovers them. 

I'm assuming you get that many icons because you create one every time someone tries to open .torrent or magnet links. So possibly, just delay they creation til you know you want to run a proper instance/GUI. 

Also, i tested quickly with opening a .torrent file for Tribler 7.3-beta1, and i got a white window myself. Removing the .pyd file as suggested, made the window only flicker for an instant. I'd go as far as to say, Tribler might be trying to make it's GUI, instead of doing whatever that it's supposed to do when there already is an instance running?  The running instance doesn't get any prompt to add the torrent file i clicked. Tribler opens as normal with a prompt to add the clicked file with Tribler already running, so i just feel that some conditions fails to trigger and it tries to open a GUI or something, which fails because of another instance is already running. (Well, not all too sure on this last part, because i have had 2 GUI instances up at the same time before..., but that's beside the point anyways.)

Either way, since i'm getting this problem, i'm up to try/test things if any help is needed.

**Comment by Nubro01** [comment]
I was just pointing out that as soon as I select a Magnet link, a second Tribler window is opened to handdle that Magnet link, that windows is now just a white screen and the Magnet link is never handled and no download is started. I geuss I just wait on a new version or a new Windows 10 Insider build.

**Comment by devos50** [comment]
@Nubro01 we have a detection mechanism in place that checks whether Tribler is already running. It relies on the ability to open a local socket. This might be prevented by some kind of firewall. Do you have any antivirus/firewall running on your computer? If so, could you try to temporarily disable it and try again?

**Comment by Thomasedv** [comment]
Relevant crash-report.log output with the faulthandler.pyd file included. (Doesn't get made without it)
> Windows exception: code 0x4001000a
> 
> Current thread 0x00006078 (most recent call first):
>   File "lib\site-packages\PyQt5\uic\properties.py", line 358 in _font
>   File "lib\site-packages\PyQt5\uic\properties.py", line 378 in convert
>   File "lib\site-packages\PyQt5\uic\properties.py", line 415 in setProperties
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 230 in setupObject
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 264 in createWidget
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 806 in traverseWidgetTree
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 546 in handleItem
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 806 in traverseWidgetTree
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 503 in createLayout
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 806 in traverseWidgetTree
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 273 in createWidget
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 806 in traverseWidgetTree
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 546 in handleItem
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 806 in traverseWidgetTree
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 503 in createLayout
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 806 in traverseWidgetTree
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 273 in createWidget
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 806 in traverseWidgetTree
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 546 in handleItem
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 806 in traverseWidgetTree
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 503 in createLayout
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 806 in traverseWidgetTree
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 273 in createWidget
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 806 in traverseWidgetTree
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 273 in createWidget
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 806 in traverseWidgetTree
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 546 in handleItem
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 806 in traverseWidgetTree
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 503 in createLayout
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 806 in traverseWidgetTree
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 546 in handleItem
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 806 in traverseWidgetTree
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 503 in createLayout
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 806 in traverseWidgetTree
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 273 in createWidget
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 806 in traverseWidgetTree
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 828 in createUserInterface
>   File "lib\site-packages\PyQt5\uic\uiparser.py", line 1021 in parse
>   File "lib\site-packages\PyQt5\uic\Loader\loader.py", line 72 in loadUi
>   File "lib\site-packages\PyQt5\uic\__init__.py", line 226 in loadUi
>   File "TriblerGUI\tribler_window.py", line 130 in __init__
>   File "run_tribler.py", line 120 in <module>
> Windows exception: code 0x40010006

From googling, this is what i could find out about the error code, but it's out of my water, so i can't really tell if it's useful: 
https://ntquery.wordpress.com/2015/09/07/windows-10-new-anti-debug-outputdebugstringw/

**Comment by Nubro01** [comment]
I just have Defender running and disabling it, makes no difference.

**Comment by Nubro01** [comment]
Strange, tried this Torrent located on this url https://1337x.to/search/American%20Gods%20S02E04%20XVID/1/ clicked the magnet link and it worked!!!
Tried again with those that do not work on https://1337x.to/search/The%20Blacklist%20S06E13%20XVID/1/ 
and selecting the Magnet link caused the problem and it does not start!
I wonder if the last one works for you.

**Comment by devos50** [comment]
@Nubro01 we will try to reproduce this with your posted magnet links.

Also, please avoid posting magnet links on Github that point to (potentially) copyrighted material. It is better to email such links to us 👍

**Comment by Nubro01** [comment]
Martijn,

De eerste Magnet link is The Big bang Theory and de keuze dialog blijft bij mij op loading staan, als ik downlaod selecteer dan worden alle bestanden gedownload waaronder allerlei (in mijn ogen) rommel.
De tweede is Greys Anatomy en beide deze krijg ik wel de keuze welke bestanden te downloaden.
Bij beide lukte het niet om via een weblink ze in Tribler te krijgen.
https://1337x.to/torrent/3690473/The-Big-Bang-Theory-S12E18-XviD-AFG-TGx/

https://1337x.to/torrent/3689582/Greys-Anatomy-S15E20-XviD-AFG-TGx/

Ron

________________________________
Van: Martijn de Vos <notifications@github.com>
Verzonden: vrijdag 5 april 2019 09:32
Aan: Tribler/tribler
CC: Ron Nuberg; Mention
Onderwerp: Re: [Tribler/tribler] Magnet link not working (#4438)


@Nubro01<https://github.com/Nubro01> we will try to reproduce this with your posted magnet links.

Also, please avoid posting magnet links on Github that point to (potentially) copyrighted material. It is better to email such links to us 👍

**Comment by Nubro01** [comment]
The last couple of days, I had to manually download magnet links, because the problem was still there. Today I clicked a magnet link and it worked and the dialog appeared????? The last version was April 9th build and I have tried several magnet links since then!

**Comment by Nubro01** [comment]
It appears that the torrent data has influence on how Tribler reacts, I forgot for which Torrent is went ok, but all others still go wrong. I have to download the torrents manually and add them to Tribler manually. this is on windows 10 1903 build 18362.

**Comment by Nubro01** [comment]
Today for the first time I did not start Tribler before downloading and when I selected a magnet link, Tribler was started and I was able to pick a location, I was not able to select which files to download, because the dialog kept stating on loading and as soon as I selected download the download started including all files!
With tribler started, I tried the same magnetlink and then the error occured that started this thread.
Closing Tribler every time I select a Magnet link is not an option, but maybe it helps you guys to finally track down this issue.

**Comment by Nubro01** [comment]
Closing tribler and selecting a magnet link works every time.
Downloading a magnet link and adding it manually give to a list to pick which files to download everytime.
When selecting a magnet link and tribler is started, a loading files stays up, I can pick a location, but the files never show, as said, when selecting downloading the download is started for all files and I am unable to unselect targeted files, so in all 3 bugs in one. **Those things used to work**!

**Comment by xoriole** [comment]
@Nubro01 I'm not able to reproduce the issue with magnet link (latest devel  https://github.com/Tribler/tribler/commit/b6b52333908773bd303d64bcad48fbcdc897374e). Could you privately send me an example magnet link that fails? 

About the file selection for inclusion or exclusion, there was indeed a bug addressed here (https://github.com/Tribler/tribler/pull/4476).

**Comment by Nubro01** [comment]
How can I send it privately, what is your private email address?

Regards

Ron

________________________________
Van: Sandip Pandey <notifications@github.com>
Verzonden: dinsdag 30 april 2019 15:52
Aan: Tribler/tribler
CC: Ron Nuberg; Mention
Onderwerp: Re: [Tribler/tribler] Magnet link not working (#4438)


@Nubro01<https://github.com/Nubro01> I'm not able to reproduce the issue with magnet link (latest devel b6b5233<https://github.com/Tribler/tribler/commit/b6b52333908773bd303d64bcad48fbcdc897374e>). Could you privately send me an example magnet link that fails?

About the file selection for inclusion or exclusion, there was indeed a bug addressed here (#4476<https://github.com/Tribler/tribler/pull/4476>).

**Comment by Nubro01** [comment]
Forgot to answer on this, but I replied on your mail with a magnet link, but all of you guys, have an email address that says notifications@github.com, so things go directly to github. I do not see your private email address, so?

Ron

________________________________
Van: Martijn de Vos <notifications@github.com>
Verzonden: vrijdag 5 april 2019 09:32
Aan: Tribler/tribler
CC: Ron Nuberg; Mention
Onderwerp: Re: [Tribler/tribler] Magnet link not working (#4438)


@Nubro01<https://github.com/Nubro01> we will try to reproduce this with your posted magnet links.

Also, please avoid posting magnet links on Github that point to (potentially) copyrighted material. It is better to email such links to us 👍

**Comment by devos50** [comment]
@Nubro01 you should see my private email address on my GitHub profile.

**Comment by qstokkink** [comment]
Do we have any updates on this?

@devos50 were you able to drag-and-drop the offending magnet link into Tribler successfully?

**Comment by Nubro01** [comment]
Still the same, when Tribler is stopped and I select a magnet link, Tribler is started and I am able to select a location, sometimes I am also able to pick which files to download, but mostly I just have to give an ok and all files are downloaded. When Tribler is running I still get the extra Tribler blank screen and nothing happens.

**Comment by ichorid** [comment]
This is basically the same problem as #4524. Our magnet link downloader downloads metainfo as unicode sometimes. TorrentDef handler can't process it because of Libtorrent-based check, the same problem as in #4524. We never detected this problem before, because downloading a magnet link invokes two different code paths, which are **never tested together**:

 * Checking DHT for metainfo (handled by torrentinfo_endpoint).
 * Creating TorrentDef from received metainfo and downloading torrent with it.

I stumbled upon this problem when added TorrendDef usage to TorrentInfo endpoint to add the torrent to Gigachannnel as FFA entry. I even had to comment out the corresponding part of TorrentInfo Endpoint test to force it to pass:
https://github.com/Tribler/tribler/blob/b26512ec5fbb6ad5e70262af534c6fba59bc0c66/Tribler/Test/Core/Modules/RestApi/test_torrentinfo_endpoint.py#L65

**Comment by xoriole** [comment]
@Nubro01 Could you kindly test out this custom build and let us know if the issue with the magnet link still exists? 

https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Build-Custom/99/

**Comment by Nubro01** [comment]
Tribler Juli 14th version accepts a Magnet link when I select it within a browser. It does NOT start Tribler and then accepts the Magnet link, but now Tribler has to started before it succesfully accepts the selection.
A small improvement, because loading files is still happening when ok is selected, download starts immediately with all files.

**Comment by xoriole** [comment]
@Nubro01 There was an issue with loading torrent metadata on Windows via clicking a magnet link or torrent file. The following build should fix that. Could you try it out?
https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Build-Custom/107/

**Comment by Nubro01** [comment]
I tried an already downloaded Torrent, by removing it from my library and when selecting the Magnet link, no second screen was opened and the normal dialog screen to select the output destination was shown.
So I geus you solved the problem.

Thanks
