### ISSUE TITLE
Almost no content found by Triber v7.3.0-beta1

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#4439]
##### Tribler version/branch+revision: #####

release-7.3.0-beta1 branch, 65d974cfa262d55f342fb06d6ca1c7b7d6f82e0d

##### Operating system and version: #####

Linux

##### Steps to reproduce the behavior: #####

Use Tribler v7.2 for a while, ensure some content get found. Then try 7.3.

##### Expected behavior: #####

Content continues to be found. My own downloads are also found using search.

##### Actual behavior: #####

Only test channels and torrents seem to be available. Even my own downloads do not seem to be indexed.

### Note ###

Now I see "Upgrading Tribler database". I assume searching starts working after this.

Is there a transitional period where both old and new distributed storages work together? Or it is a full "network split" between legacy and new Triblers, disincentivising users from switching to new version because of nobody switched yet?

**Comment by xoriole** [comment]
@vi With 7.3 release we have new channel implementation with different database structure. Your own channel and other channels from the old version are upgraded to the new channel structure gradually in the background. It could take some time (hours) depending on the size of your old database. 

One big impact of this release is that the old legacy channels even though upgraded to new channel structure are not gossipped around in the network anymore. The only channel shared in the network is your own channel. For more content to becomes available, it can take some time but will be available eventually.

> Only test channels and torrents seem to be available. Even my own downloads do not seem to be indexed.

This seems like a bug. I'll take a look.

**Comment by vi** [comment]
Shall the "Upgrading Tribler database" banner include some info like "Search results may be incomplete until upgrade completes"?

Also the banner appeared not immediately after starting Tribler, but after a while, which I already checked how downloads and searching works.

**Comment by vi** [comment]
Database migration finished, I restarted Tribler to get rid of the banner showing results (20 somethings per second, with `eatmydata`).

Some content is now being found if I type common words in the search field.

Yet my own downloads do not show up in search results if I type words from filenames or even copy and paste entire "name" of the download there.

**Comment by ichorid** [comment]
@vi, to speed-up the new Channels implementation, it holds no information about torrents' contents. Thus, file names are not indexed.
Your own downloads will not show up in search results, because you had not added them to your personal channel. This behaviour is not intuitive, and we're going to change it in the final release by optionally adding your downloads to your personal channel.

Thanks for your report!
