### ISSUE TITLE
7.3 database migration stuck.

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#4440]
##### Tribler version/branch+revision: #####

release-7.3.0-beta1 branch, 65d974cfa262d55f342fb06d6ca1c7b7d6f82e0d

##### Operating system and version: #####

Linux

##### Steps to reproduce the behavior: #####

Run Tribler 7.3 after using previous Tribler versions, leave it running overnight.

##### Expected behavior: #####

Database migration completes successfully.

##### Actual behavior: #####

Stuck at "Upgrading Tribler database: 8313/147866", not counting forward.

Restarting Tribler resumed migration process although.

##### Relevant log file output: #####

Inaccessible due to log flood flushing away terminal history fast.

**Comment by loadletter** [comment]
I have a similar issue, it arrives to around 112000/150000~ and then it just stops, even after restarting.
The db72 to pony log entry and the GUI progress bar just stops appearing, but conversion_from_72_discovered in the database is marked as started

**Comment by ichorid** [comment]
@loadletter, is it reproducible? If so, could you please send us your `tribler.sdb`?

**Comment by loadletter** [comment]
@ichorid I've tried a couple of times with the same db and it stopped both times, here's [tribler.sdb](https://void.cat/#C9DM9K9MyvcrEM8VCauQR2N46Av:9a793b5a0af027ca259f1c9e2f4aaf77:5b52c6e21229a07a7c6684ca63b74613)

**Comment by ichorid** [comment]
@loadletter , many thanks! I'll check out the DB ASAP.

**Comment by ichorid** [comment]
I was able to reproduce the problem with @loadletter's `tribler.sdb` file. The upgrader stops at 112621/150470. However, when I use Tribler version from PR #4480 , everything works fine.
