### ISSUE TITLE
Tribler exits if it fails to parse a query to its REST interface

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#4445]
##### Tribler version/branch+revision: #####

release-7.3.0-beta1 65d974cfa262d55f342fb06d6ca1c7b7d6f82e0d

##### Operating system and version: #####

Linux

##### Steps to reproduce the behavior: #####

1. Start Tribler
2. Wait for it to be "started"
3. `curl 'http://localhost:8085/search?filter=test.test&last=50&uuid=e09774f87c32414cad817e6d643a7235&sort_by=category&metadata_type=torrent&hide_xxx=1&sort_asc=1&first=1'` - instead of `test.test` it can be `test-test` or some other character.

##### Expected behavior: #####

Tribler <s>interprets symbols  as a part of `filter` parameter or</s> returns some `400 Invalid Request` and continues working

##### Actual behavior: #####

GUI shows core error, reply to the request is missing, Tribler exits.

**Comment by vi** [comment]
(Encountered duing experimenting with [my Tribler CLI in development](https://github.com/vi/tribler-rs))

**Comment by xoriole** [comment]
@vi Thank you for reporting. It is a good point. We should only convert search keywords to match query in the Core instead of GUI
