### ISSUE TITLE
Tribler likes Logging

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#4447]
Logs grow quickly when using the latest 7.3 Beta1 for several days. Mostly this message:

```INFO    1554183783.30                 community:82   (Request)  Timeout for find to Peer<3.4.5.6:35005,```

Note that storage is _not_ the issue. This noise level most likely impacts effectiveness. Perhaps this should be compressed into periodic aggregate statistics. For instance, 'Counted 78  "Timeout for find to Peer" errors in past hour'. Or only logs this if the DHT debug mode is enabled.  My 55MB of errors:

```
-rw-r--r-- 1 pouwelse pouwelse 1.9M Apr  2 09:49 resources.log
-rw-r--r-- 1 pouwelse pouwelse 2.1K Apr  1 09:48 tribler-core-error.log
-rw-r--r-- 1 pouwelse pouwelse 2.2M Apr  2 09:18 tribler-core-info.log
-rw-r--r-- 1 pouwelse pouwelse  10M Apr  2 05:20 tribler-core-info.log.1
-rw-r--r-- 1 pouwelse pouwelse  10M Apr  1 12:26 tribler-core-info.log.2
-rw-r--r-- 1 pouwelse pouwelse  10M Mar 31 18:36 tribler-core-info.log.3
-rw-r--r-- 1 pouwelse pouwelse  10M Mar 31 03:51 tribler-core-info.log.4
-rw-r--r-- 1 pouwelse pouwelse  10M Mar 30 08:05 tribler-core-info.log.5
-rw-r--r-- 1 pouwelse pouwelse    0 Mar 28 16:11 tribler-gui-error.log
-rw-r--r-- 1 pouwelse pouwelse 1.2K Mar 29 15:37 tribler-gui-info.log
```

**Comment by egbertbouman** [comment]
I've lowered the log level of the offending line in the latest IPv8 version.
