### ISSUE TITLE
"Added on" for some torrents is set to time at Tribler startup

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#4451]
##### Tribler version/branch+revision: #####
Tribler 7.3 beta1

##### Operating system and version: #####
Windows 10, most recent update

##### Steps to reproduce the behavior: #####
Unclear, possibly related to sommertime change in EU, as that's when the error was noticed.
Have some downloaded torrents, restart Tribler, and some of those torrents will have "added on" be the same as when tribler started.

##### Expected behavior: #####
Torrents keep their added date. 

##### Actual behavior: #####
Some torrents upon restart of Tribler will have their added date set to the startup date of the Tribler instance. It happened to the same torrents every time. And does not seem to change.

Additional info:
* All affected torrents are from watch folder, but not all from watch folder are bugged.
* The affected torrents were added over the span of at least a month, randomly, and affects torrents added both before and after the timezone change.
* The affected torrents show up in the downloads list after all other torrents are loaded. As if something is holding them up. (Or that tribler is "readding" from the watch folder, but i don't see any checking or anything of that sort, so i kind of doubt it)

This is a minor issue, but i thought i'd mention it anyways, as well as add that if finding the cause is a problem, it might just be worth preventing the same files getting a new date on each restart of Tribler, to prevent hurting the "sort by added on" category permanently.

**Comment by devos50** [comment]
Thank you for your report. I tried to reproduce this issue but I did not observe this error. What is the state of the the downloads that exhibit? Are they fully downloaded?

The `added on` field is written away to `pstate` files, which stores various settings and data associated to the download. You can find them in the `.Tribler/dlcheckpoints` directory. Could you check whether these `.pstate` files are created for the downloads with the invalid `added on` field?

**Comment by Thomasedv** [comment]
The files are created for invalid files, and exist both when Tribler is running and when it's not. 
The time_added is set to the time it shows in the GUI. (I copy pasted both a correct and changed time to a webpage and got the date, which corresponds to what the GUI shows.) 

The files have some differences though in terms of fields included (both have same state, seeding). Left is a normal working file, with it's original date, and the right one is one that keeps changing on Tribler restart. 
![image](https://user-images.githubusercontent.com/1584461/55615620-250c9700-5790-11e9-8bbf-a39926bfd056.png)

**Comment by devos50** [comment]
The files indeed persist after Tribler closes. The `time_added` field is the info being shown in the GUI.

Even in the `engineresumedata` is corrupt, the pstate file should not be regenerated.

At first, I thought that this could happen when a download is re-added when hidden seeding is being initiated but it seems that the `time_added` is preserved, even when changing anonymity. Could you try to add these seeding field (`seeding_ratio`, `seeding_time` and `seeding_mode` to the right config file and see whether the error persists?

**Comment by Thomasedv** [comment]
Unfortunately, it does not seem to help. Still happens, and the fields are gone when Tribler restarts.

I also tried to change the `engineresumedata` to match that of a working file, by removing the excess fields, and adding some missing ones (`unfinished` and `file sizes`) as well as replacing the `peers` value string with an empty one. And that did not work either. 

Next up i will try to remove .torrent files from the watch folder and see what happens.

**Comment by Thomasedv** [comment]
Oh, that's interesting. The problem doesn't lie in the `pstate` file at all. It's simply the fact that it checks for a `pstate` when adding a torrent and reusing the information there (to tell if it's downloaded or not)

Because i removed the .torrent files in the watch folder and now the torrent is gone from Tribler. Which is not something that is supposed to happen when you remove torrents in the watch folder. Tribler fails to record the existence of the torrent somewhere else.

**Comment by devos50** [comment]
Hmm maybe the watch folder adds the torrent again and overrides its current pstate file? Let me try.

**Comment by devos50** [comment]
When removing the torrent from the watch folder, the download still exists for me. In general, if there is a `.pstate` file, Tribler should re-add the download when Tribler is starting (in fact, it scans the `dlcheckpoints` directory and re-adds all downloads according to the information in the pstate files).

Are you sure that there is a pstate file written away for the torrent that you removed from the watch folder? The name of the pstate file corresponds to the info hash of the torrent so that should be an easy way to verify this.

**Comment by Thomasedv** [comment]
Hard to say why though, it does add and work with many torrents, including recent ones. 

My process of checking is quite simple i got a series that releases weekly, episodes 76 works fine, episode 75 and 77 are corrupt. All are added from watch folder. 
Removing the folder, torrents for ep 75 and 77 are gone from the GUI and thus Tribler. Episode 76 remains as expected.

No indication of why so far. I'll have to take a look at the .torrent files and see if there is something out of order, but i suspect that's not it. I'm currently guessing there is corruption in my torrent database or however that is stored.

**Comment by Thomasedv** [comment]
No apparent error with the .torrent files at least. Not that i know much about them. I can add though, that this problem seemed to happen instantly for all files it affected. One day i just booted Tribler, sorted by recently added as i always do, and didn't find my just added torrent at the top, rather it far down under all the torrents which was readded. 

I feel that it's something on Triblers end, but i can't tell what, but likely some for of corruption on my end. Like a torrent fails to get added to the whatever that tells Tribler that it has a torrent (since pstate only has information about added torrents, not if it's added or not). Like, could it fail if a torrent is already added but somehow corrupted? A silent drop of attempting to add it? I don't see errors in the log, at least nothing that seems related to my issue. 

I just find it odd that Tribler adds a torrent, but can't hold that information from one instance til the next one. Given that `engineresumedata` preserved `added_time` between additions, i am also a bit confused as to how it loads a pstate, rewrites the pstate with some the engineresumedata, and then fails to add it to Tribler. It could happen that Tribler assumes the .torrent is already in the database when the `.pstate` exists?

**Comment by Thomasedv** [comment]
I'm doing some "debugging" to the best of my ability, and need some advice:
In the following link, the if statement should only be called for new torrents, right? 
https://github.com/Tribler/tribler/blob/ec240afd6bf21f033d55966a0b30b9d459de81cd/Tribler/Core/Modules/watch_folder.py#L61

Looking at the logs, the log is called only for the readded torrents, which means, that the torrents that are supposed to be added aren't in the session. Which is true, but what prevents Tribler from saving that they've been added? 

Going a bit futher down the chain, the download seems to added to the "session" here: https://github.com/Tribler/tribler/blob/ec240afd6bf21f033d55966a0b30b9d459de81cd/Tribler/Core/APIImplementation/LaunchManyCore.py#L396

That seems to work all right as far as i can see. 
So i'm my current idea, would be to look at where the self.downloads is loaded/save on startup/shutdown of Tribler, and see if any recent changes has been made. It's very odd that some select torrents keep giving an error. I also redownloaded the torrent file, and the problem is still there for that file. I also added another completely new file just now, and the same problem happened. 
Gotta give another computer a try with the same files and see what happens.

**Comment by Thomasedv** [comment]
I removed most of my .Tribler folder and the problem so far seems to be resolved. I guess we can put it up as some sort of corruption on my side, either random, some user error by me, or a result of trying various dev builds that cause some sort of error. 

So for now, i'll close the issue.
