### ISSUE TITLE
Settings editor seems to have problems after upgrade

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#4455]
##### Tribler version/branch+revision: #####

v7.3.0-beta1 65d974cfa262d55f342fb06d6ca1c7b7d6f82e0d

##### Operating system and version: #####

Linux

##### Steps to reproduce the behavior: #####

1. Use older Tribler, configure it.
2. Upgrade to 7.3.
3. Go to settings

##### Expected behavior: #####

Settings editor works properly even after upgrade.

##### Actual behavior: #####

Settings are clear (many fields are empty, validation not passes if just click "save"), requiring to re-filling them again.
Tribler's behaviour does correspond although to normal settings even though they are not viewable.
Manually entering settings again and saving seems to workaround the problem.

**Comment by vi** [comment]
Also "Enable token mining" checkbox seems to been saved fully only after second attempt. After first setting re-edit and Tribler restart it somehow has cleared itself.

**Comment by devos50** [comment]
It could be that the settings are not loaded correctly. This unfortunately is not really presented to the user. I think we should clearly indicate if the settings are currently being loaded and only allow changing the settings if these actually did load.
