### ISSUE TITLE
Legalised notary signature using Self-Sovereign Identity

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#4458]
Goal is simply to have the first legalised electronic signatures.

Deisng this from scratch, while re-using software components such as IPv8 and trustchain. Creating the exact design, detailed requirement, and user-interface structure is part of this project. Even understanding the legal domain somewhat is part of this project.

Introduction to self-sovereign identity: https://bitsonblocks.net/2017/05/17/gentle-introduction-self-sovereign-identity/
Example project: http://www.ondertekenen.nl/
Their notary declaration (in Dutch): https://www.ondertekenen.nl/wp-content/uploads/2018/07/Juridische_Verklaring_OndertekenenNL_Evidos_okt_2016.pdf

Extends SSI: #2682

**Comment by synctext** [comment]
Meeting notes from earlier discussion: https://github.com/Tribler/document-attestation-service/issues/1#issuecomment-475974671

**Comment by dsluijk** [comment]
Progress this week:
 - Use the demo code to create a frontend for the attestation community.

![2019-04-12 13 52 21 localhost 3908800c49c5](https://user-images.githubusercontent.com/8537327/56035399-6110a080-5d2a-11e9-9bc5-9da797657243.png)

**Comment by synctext** [comment]
Plans for coming sprint:
- get [Libutp operational](https://github.com/bittorrent/libutp) 
- transfer 1 byte from a well known server
- transfer a GByte between two processes

Future options:
- look into the lawyer stuff
- .APK version using Webkit?

**Comment by synctext** [comment]
Most senior researcher now assigned to take the legalised signature concept to technology readiness level 9. Important builder of confidence for our technology, ourselves, and identity research. Use thorough authentication for enrollment (passport, etc.), 2-factor authentication for re-authentication (what you own, what you know).

**Comment by synctext** [comment]
Ready for student (team) to work on. Superapp would be the new codebase.
Key step is to get a notary onboard for real-world trail usage.
