### ISSUE TITLE
Tunnel improvements

### ISSUE THREAD

**Issue by egbertbouman** [Tribler/tribler#4459]
There are still some improvements that I would like to make to the TunnelCommunity in the coming weeks:
* Let peers within the TunnelCommunity announce how they would like to participate in the network. For instance, a node may want to:
  * Relay data
  * Act as an IPv8 and/or uTP exit
  * Be an introduction/rendezvous point for hidden services
* Set up an experiment for donating to the network and obtaining tokens for end-to-end encrypted relaying:
  * Observe operational performance on these machines
  * Tweak and boost the performance
* Since CPU still seems to be the bottleneck, I'd like to make the code a bit more efficient.
Some examples of what can be improved:
  * Message (de)serialization
  * Before Twisted writes to a socket, it first spends a lot of time in `isIPAddress` /  `isIPv6Address`
  * Remove `isinstance` calls from byte counting functions
  * Packet demultiplexing (at Community level)
  * Crypto (also investigate https://github.com/Tribler/tribler/issues/3099)

Function duration breakdown of on_cell:
![image](https://user-images.githubusercontent.com/3785124/56023541-5cd68a00-5d0e-11e9-8eec-86fca34cdb86.png)

**Comment by devos50** [comment]
Should this be assigned to the Tribler 7.3 milestone?

**Comment by egbertbouman** [comment]
@devos50 Since 7.3 is already in beta, I think this is something for 7.4.

**Comment by synctext** [comment]
We can hopefully have the doubling of tunnel speed for final Beta of 7.3... Plus trust animation. Then into code freeze and stability only.

**Comment by synctext** [comment]
ToDo: discuss raw speed, faster download starts, robustness versus security properties such as equal packet size. @egbertbouman

**Comment by egbertbouman** [comment]
Just a few things that are on my tunnel wishlist:
- [ ] Create a live circuit speed test (bytes/s up and down, including hidden services). I'd like to add some speed test specific messages that allow us to do a speed test without involving a real-world BitTorrent swarm. Using the `peer_flags` we can extend the tunnel protocol without breaking compatibility.
- [ ] Build more endpoints/tools that allow us to gain insight into the inner workings of the tunnel community, especially hidden services. For instance, the status of the PexCommunities, the sizes of hidden swarms, and tunnel packet loss.
- [ ] Remove `PEER_FLAG_EXIT_ANY`, and only use more specific flags: `PEER_FLAG_EXIT_IPV8/BT/HTTP`. Since the meaning of `PEER_FLAG_EXIT_ANY` changes as we extend the protocol, we can't use it to determine which extensions a particular peer supports.
- [ ] Change tunnel crypto from AES-GCM to AES-CTR for all layers except the inner-most layer (_breaking change_).
- [ ] Consider optional support for Chacha20 (and Chacha20-Poly1305 for the inner-most layer) to improve performance for peers without hardware acceleration (_breaking change_).
- [ ] Add early relay logic to limit the maximum number of hops (_breaking change_, unless we implement it as a new type of cell).  
- [ ] Optional support for padding cells (_breaking change_). 
- [ ] Make a decision about padding. In case we start padding cell messages, investigate what the best packet size would be and how this would affect performance.
- [ ] More tunnel performance improvements. This time don't just focus on CPU but also memory.
- [ ] IPv6 support for tunnels/DHT. This also affects the IPv8 core.
- [ ] Add typing (although this is not really tunnel-specific)

**Comment by egbertbouman** [comment]
Just a few things that are on my tunnel wishlist:
- [ ] Create a live circuit speed test ( bytes/s up and down, including hidden services). I'd like to add some speed test specific messages that allow us to do a speed test without involving a real-world BitTorrent swarm. Using the `peer_flags` we can extend the tunnel protocol without breaking compatibility.
- [ ] Build more endpoints/tools that allow us to gain insight into the inner workings of the tunnel community, especially hidden services. For instance, the status of the PexCommunities, the sizes of hidden swarms, and tunnel packet loss.
- [ ] Remove `PEER_FLAG_EXIT_ANY`, and only use more specific flags: `PEER_FLAG_EXIT_IPV8/BT/HTTP`. Since the meaning of `PEER_FLAG_EXIT_ANY` changes as we extend the protocol, we can't really use it to determine which extensions a particular peer supports.
- [ ] Add early relay logic to limit the maximum number of hops.
- [ ] Support for padded cells.
- [ ] In case we start padding cell messages, investigate what the best packet size would be and how this would affect performance.
- [ ] Further tunnel performance improvements. This time don't just focus on CPU but also memory.
- [ ] IPv6 support for tunnels/DHT. This also affects the IPv8 core.

**Comment by egbertbouman** [comment]
Just a few things that are on my tunnel wishlist:
- [ ] Create a live circuit speed test ( bytes/s up and down, including hidden services). I'd like to add some speed test specific messages that allow us to do a speed test without involving a real-world BitTorrent swarm. Using the `peer_flags` we can extend the tunnel protocol without breaking compatibility.
- [ ] Build more endpoints/tools that allow us to gain insight into the inner workings of the tunnel community, especially hidden services. For instance, the status of the PexCommunities, the sizes of hidden swarms, and tunnel packet loss.
- [ ] Remove `PEER_FLAG_EXIT_ANY`, and only use more specific flags: `PEER_FLAG_EXIT_IPV8/BT/HTTP`. Since the meaning of `PEER_FLAG_EXIT_ANY` changes as we extend the protocol, we can't really use it to determine which extensions a particular peer supports.
- [ ] Switch from `cryptography` to `libnacl`, since it seems to be considerably faster. Since we currently use AES-128-GCM, and `libnacl` only supports AES-256-GCM, this will be a breaking change.
- [ ] Add logic to limit the maximum number of hops.
