### ISSUE TITLE
CPU consumption is not reflected correctly in the system monitor of debug panel

### ISSUE THREAD

**Issue by cuileri** [Tribler/tribler#4464]
##### Tribler version/branch+revision: #####
7.0.0-GIT
##### Operating system and version: #####
Ubuntu 18.04.2 LTS
##### Steps to reproduce the behavior: #####
Open debug window's System/CPU tab and OS's system monitor at the same time
##### Expected behavior: #####
Debug panel's System/CPU tab shows actual CPU usage of _all_ subprocesses related to Tribler
##### Actual behavior: #####
Debug panel's System/CPU tab shows missing information on Tribler's CPU usage. It only reports the main process.
##### Relevant log file output: #####
![Screenshot from 2019-04-16 15-55-23](https://user-images.githubusercontent.com/22027137/56216309-7c98e580-6061-11e9-9a67-c0aaff4c3453.png)

**Comment by xoriole** [comment]
It seems the matplotlib trust graph creates a separate process instead of running within the core process and this new process is consuming high cpu. If Trust graph is not enabled, there is no such process. We should investigate more on this to make it efficient.

**Comment by qstokkink** [comment]
The mentioned code has been removed and this issue is no longer relevant.
