### ISSUE TITLE
Lot of 162 Byte tunnels

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#4465]
Is this normal behavior?

When running 7.3.0-Beta1 on Ubuntu with an uptime of 4 days. +139GByte token balance.
![Screenshot from 2019-04-17 08-54-00](https://user-images.githubusercontent.com/325224/56270374-3f326780-60f6-11e9-864b-957f3c9f014b.png)

No anonymous seeding or downloading, yet:
![Screenshot from 2019-04-17 09-51-57](https://user-images.githubusercontent.com/325224/56270481-80c31280-60f6-11e9-9e8a-8d6a0e10e8be.png)

**Comment by qstokkink** [comment]
By default you can be part of up to 100 relay circuits:

https://github.com/Tribler/py-ipv8/blob/f9fc03951e23af9f4830d8e48d1eef6a9ba94a49/ipv8/messaging/anonymization/community.py#L90

**Comment by devos50** [comment]
We should check whether this issue persists now that #4494 is merged.

**Comment by egbertbouman** [comment]
I'm thinking that most of these circuits have been created to serve as introduction points. Hopefully, in the new version we'll see more fully established e2e circuits that transfer more than just a few bytes data.

**Comment by qstokkink** [comment]
@egbertbouman is this fixed now?

**Comment by egbertbouman** [comment]
@qstokkink If these circuits are introduction points, this is expected behavior (both in the old and new version).

**Comment by qstokkink** [comment]
If there was nothing to fix in the first place, I will consider this fixed.
