### ISSUE TITLE
Custom CSS for Tribler

### ISSUE THREAD

**Issue by grimadas** [Tribler/tribler#4467]
Moving towards 8.0 we need to support custom GUI layouts to change easily change  GUI.
As an option we might also create a channel with different layouts to support community layouts.

**Comment by synctext** [comment]
> create a channel with different layouts to support community layouts.

With CSS you mean integrating browser technology (and 50-100MByte installer bloat)?
I'm very skeptical that introduces any value for Tribler, coming year we need to get all our features rock-solid first (like PopularityCommunity).

**Comment by devos50** [comment]
I'm not sure if a fully fletched browser has to be integrated to support this, since PyQt already supports CSS-based layouts, and injection of CSS should be relatively easy to realise.

I agree that this is a cool feature to have, but we have more pressing issues to consider at the moment.

**Comment by qstokkink** [comment]
The new Tribler web GUI now allows light and dark themes. More themes can now be added on demand.
