### ISSUE TITLE
UI becomes unresponsive on large torrent

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#4468]
##### Tribler version/branch+revision: #####
7.3.0-beta1

##### Operating system and version: #####
Ubuntu 18.04

##### Steps to reproduce the behavior: #####
1) Add a large torrent to Tribler ([example](https://send.firefox.com/download/2f909b488a6ed987/#Yp_aa9G2vr_geDzqxZFwnQ))
2) Try to exclude all but the last file, and fail.

##### Expected behavior: #####
UI maintains responsiveness

##### Actual behavior: #####
UI won't respond (for ~2 minutes)

**Comment by Thomasedv** [comment]
For me, Windows 10 (64 bit version of Tribler), it doesn't become unresponsive, but i am unable to exclude files in torrents. Tested with a ~4GB torrent with two files in it. Nothing happens and the files are still downloaded. 
Tested with both Beta-1 and Beta-1-60-something (one of the latest version i found on Jenkins)

**Comment by Dmole** [comment]
2 files are not going to slow down the UI like 7000 will. (UI is not loading the file contents, so file size is not relevant)

**Comment by synctext** [comment]
Great feedback. Thnx. We should have a Beta2 this week with several fixes and the new trust graph system. 

@Tribler Could we have a 100k included filenames .torrent file in the unit tests?

**Comment by qstokkink** [comment]
This is probably due to the (more than 10 years old) code in [TorrentDef](https://github.com/Tribler/tribler/blob/devel/Tribler/Core/TorrentDef.py). We were planning on fixing this (and other inefficiencies in our downloading core) in the [V7.4: Libtorrent wrapper refactor milestone](https://github.com/Tribler/tribler/milestone/32).
