### ISSUE TITLE
exclude file regression

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#4469]
As noted 
https://github.com/Tribler/tribler/issues/4468#issuecomment-485161320
The exclude file feature has regressed.

##### Tribler version/branch+revision: #####
7.3.0-beta1
and
Tribler_7.3.0-beta1-60-g7cd70d486_x64.exe

##### Operating system and version: #####
Ubuntu 18.04
and
Windows 10

##### Steps to reproduce the behavior: #####
try to exclude any file from any torrent

##### Expected behavior: #####
File shows as "no" in the DL column

##### Actual behavior: #####
File still listed as "yes"

**Comment by devos50** [comment]
@Dmole can you still reproduce this issue in the released 7.3 version?

**Comment by ichorid** [comment]
I was using this feature several times on both Windows and Ubuntu. It works fine.
@Dmole , if you can reproduce it, please do not hesitate to report here.
For now, I close the issue.

**Comment by Dmole** [comment]
Yes thanks I see it is fixed.
