### ISSUE TITLE
Better database for Tribler/ Prevent Trustchain exit nodes wiping out  

### ISSUE THREAD

**Issue by grimadas** [Tribler/tribler#4471]
### Current problems for scalability

Current database cannot scale well and handling big amount of trustchain records. After some number of records we see a degradation in performance for exit nodes.   
One of the solutions is to wipe out database and start over, but that results in identity, reputation lose.
Alternately, we can improve underlying trustchain database. I think a good start is to look into workload and see how other databases can handle that.    

### Abstract Database module 

Currently we have at least three different entries to the database with hardcoded sql queries in the codebase: `Upgrade`, `IPv8/Database.py` and `Metastore` using `pony-orm`.
To simplify the migration from one database to another to improve salability and latency we need to abstract database access( we might want to look into graph, key/value databases in future). 

A good starting point would be a database adapter and an sqlite implementation of it.

**Comment by ichorid** [comment]
I doubt it will be possible to abstract out Metadata Store access in the foreseeable future. PonyORM already provides a good level of abstraction. However, Trustchain can benefit greatly from switching to some NoSQL-based store (e.g. LevelDB). Building an abstraction level for storing blocks could become a nice step in that direction.

@qstokkink , @devos50, do any components of Tribler beside Trustchain use `IPv8/Database.py`?

**Comment by devos50** [comment]
@ichorid No, I don't think so.

**Comment by qstokkink** [comment]
The attestation community has its own Database + database schema.

**Comment by ichorid** [comment]
@qstokkink , would you consider moving the attestation community to use Pony?

**Comment by qstokkink** [comment]
@ichorid I just went through the code with @grimadas, doesn't seem like a good idea right now.

**Comment by grimadas** [comment]
I'll first do quick and dirty check if it is worth to migrate to db other than sqlite, and proceed after.

**Comment by synctext** [comment]
We require DB embedding! As just discussed: our choice and selection of database technology is significantly limited due to our requirement that everything is bundled within our installer. We can't rely on big servers with dedicated database services, our DB is running locally and competing for resources.

**Comment by grimadas** [comment]
These are benchmarking results for database behind tribler explorer. 
![avg](https://user-images.githubusercontent.com/5897440/56968267-28165f80-6b63-11e9-8beb-e78934e47480.png)
Figure 1 is the average execution time for a query. You see that one query `get_block_creation` takes more than 40 sec. 
![times](https://user-images.githubusercontent.com/5897440/56968279-2a78b980-6b63-11e9-98cc-72ad63781764.png)
Figure 2 is showing number of times when query was executed. 

![total](https://user-images.githubusercontent.com/5897440/56968280-2a78b980-6b63-11e9-89aa-3ed56cba272a.png)
Figure 3 is the total time for the experiment.

**Comment by ichorid** [comment]
Block explorer is a special case. Could you try to capture a typical client Tribler workload session and build the same charts for it?

**Comment by qstokkink** [comment]
Maybe it would make sense then for the block explorer to use a different database type. As this is not used by our users anyway, we can change this without any major repercussions (we'll just have to sit through the databse conversion).

I also agree with @ichorid, this tells us nothing about the Tribler user load.

**Comment by grimadas** [comment]
I'll do local experiments now, imitating typical workload of a Tribler user: idle, downloading etc.

**Comment by grimadas** [comment]
![image](https://user-images.githubusercontent.com/5897440/57437949-258ec680-7243-11e9-9c4b-df5cb93144b9.png)
Some results from the exit node. It seems that database queries are not the bottleneck.

**Comment by grimadas** [comment]
![image](https://user-images.githubusercontent.com/5897440/57444848-5fff6000-7251-11e9-822b-51b3588fc8d9.png)

**Comment by devos50** [comment]
I made some modifications to the TrustChain crawler. First, I increased the statistics maintainance interval to one hour, which means that block creation statistics (the graph) is rebuilt every hour, instead of every five minutes. Aggregation of statistics is a major bottleneck as it executes a resource-intensive SQL query.

Second, I started to explore whether a key-value store can be utilized to improve the performance of the _TrustChain crawler_. Last week I was told that there was some initial work to rewrite the TrustChain persistence layer to use key-value (we also received various questions already why we were not using one already). @grimadas do you have some initial code/results for this?

**Comment by grimadas** [comment]
There are several options with good python bindings, but I guess one of the best matches for us is [lmdb](https://lmdb.readthedocs.io/en/release/). It is pretty easy and supports async read/write with multiple threads.

**Comment by synctext** [comment]
Multi-core crawling is possible in near future?

**Comment by ichorid** [comment]
This is a good target for 7.5 release, not for the technical 7.4.

**Comment by qstokkink** [comment]
Looking at this issue, I think it is no longer applicable for the current state of affairs: exit nodes no longer run any database.
