### ISSUE TITLE
Endless spinning gears

### ISSUE THREAD

**Issue by Harapuia** [Tribler/tribler#4477]
#### Please, fill all relevant items: ####

- [X] I have read CONTRIBUTING.rst

- [X] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
V7.3.0-beta2
##### Operating system and version: #####
Windows 10 1709
##### Steps to reproduce the behavior: #####
Launch Tribler
##### Expected behavior: #####
Tribler to be launched!
##### Actual behavior: #####
Endless spinning gears
##### Relevant log file output: #####
No log file created at %appdata%/Tribler.exe.log (dates from 2017)

Crash-report updated today, may have been caused by a kill from the task manager
[crash-report.log](https://github.com/Tribler/tribler/files/3132976/crash-report.log)

As discussed earlier today this issue is 100% reproducible. Windows 10 is forcing me to update to 1809, right now. I'll report if the issue persists.

**Comment by qstokkink** [comment]
Does the issue persist if you change the name of `%APPDATA%/.Tribler`?

**Comment by Harapuia** [comment]
Issue persists. .Tribler folder gets created with the following structure:

```
AppData/Roaming/.Tribler$ tree -fis
.
[        512]  ./channels
[        512]  ./dlcheckpoints
[         64]  ./ec_multichain.pem
[         32]  ./ecpub_multichain.pem
[         32]  ./ecpub_trustchain_testnet.pem
[         64]  ./ec_trustchain_testnet.pem
[        512]  ./logs
[    2553582]  ./logs/crash-report.log
[          0]  ./logs/tribler-core-error.log
[          0]  ./logs/tribler-core-info.log
[          0]  ./logs/tribler-gui-error.log
[          0]  ./logs/tribler-gui-info.log
[        512]  ./sqlite
[          4]  ./triblerd.lock
[        512]  ./wallet

5 directories, 10 files
```

Directory listing and their respective filesizes created using the windows subsystem for linux.
Also: Windows update conked out and i remain on 1709 for now

**Comment by synctext** [comment]
Can confirm, it fails to start on Ubuntu 18.04.2 LTS with a clean .Tribler directory and no logs are every produced

```
Collecting lz4
  Downloading https://files.pythonhosted.org/packages/a7/cc/6355827ab12ac573c0647fcc79ba87d455a204ef17469d1e266ff3798957/lz4-2.1.6-cp27-cp27mu-manylinux1_x86_64.whl (360kB)
     |████████████████████████████████| 368kB 827kB/s 
Requirement already satisfied: future in /home/pouwelse/.local/lib/python2.7/site-packages (from lz4) (0.17.1)
Installing collected packages: lz4
Successfully installed lz4-2.1.6
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for gconf2 (3.2.6-4ubuntu1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
[snip]
-rw-r--r-- 1 pouwelse pouwelse    0 May  2 13:40 tribler-core-error.log
-rw-r--r-- 1 pouwelse pouwelse    0 May  2 13:40 tribler-core-info.log
-rw-r--r-- 1 pouwelse pouwelse    0 May  2 13:39 tribler-gui-error.log
-rw-r--r-- 1 pouwelse pouwelse    0 May  2 13:39 tribler-gui-info.log
```

**Comment by synctext** [comment]
Just to add newly discovered info. Seems to be stuck very early, almost no files created yet:
```
~/.Tribler$ ls -lah
total 12K
drwxr-xr-x  3 pouwelse pouwelse 4.0K May  2 13:39 .
drwxr-xr-x 79 pouwelse pouwelse 4.0K May  2 13:39 ..
drwxr-xr-x  2 pouwelse pouwelse 4.0K May  2 13:40 logs
```

**Comment by synctext** [comment]
Background process running:
![Screenshot from 2019-05-02 14-03-39](https://user-images.githubusercontent.com/325224/57074030-24114b80-6ce3-11e9-823b-a35448b0005a.png)

**Comment by devos50** [comment]
The logging to file is not always reliable since Python internally buffers the output. When the Python process crashes, it could be that the content of this buffer is lost forever.

**Comment by synctext** [comment]
OK, fixed for me by reinstalling pip, pony, and lz4 on Ubuntu.
It's a dependency not found problem.

**Comment by Harapuia** [comment]
Not an option on windows installs, to my knowledge. Unless tribler depends on an external python install?
Is there a way to make it output to a terminal? Or run it through a python debugger, i'm not too familiar with how the windows installation package works. Might give us the extra information we need?

**Comment by qstokkink** [comment]
@Harapuia you can open a Command Prompt (from the windows start menu), `cd` to the tribler folder and then run `tribler.exe` from there. This should give you all the additional output, if there is any.

However, if it is indeed the same problem as on Ubuntu, we will have to fix it on our side before compiling the binary.

**Comment by Harapuia** [comment]
Ah, that was one of the first things I did. So I can confirm it gives no
additional output.

**Comment by ichorid** [comment]
Seems to be working fine since 7.3.0
