### ISSUE TITLE
Collective authoring in GigaChannels

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4486]
### Information integration
To facilitate [information integration](https://en.wikipedia.org/wiki/Integrated_information_theory) in Tribler Channels, **users must be able to change Channels data while passing it to others**.

### Inline editing
Every Channels entry *in any channel* should be editable inline. Whenever the user edits an entry, it is immediately added to the hidden "Updates" personal sub-channel (ID 1). This entry will never be replaced since the user trust themselves more than anyone ("my opinion is far more important than anyone else's").

### Changes to others' channels
Changes to others' channels are sent to the original author's by gossip packets of the form:
`[channel_entry_md; changed_md|new_md]`. Changed and `TO_DELETE` entries have `pending` flag in the DB set to `True`. When the change is propagated upstream to the original author it is set to `False`. On receiving an update from a subscribed channel, `TO_DELETE` entries and changes are cleaned up if they seem to be accepted, and are set back to `pending` otherwise. `pending` changed entries are gossiped as normal, possibly propagating through the network and reaching the original author through other peers.

Overall, the network should be in the state of a constant "creative chaos" in the sense that there will be no guarantees on eventual consistency. The same is true for the human mind: conflicting thoughts constantly arise in it, tides of idle thoughts wander through it, yet *most of the time it is able to function properly*.

### Sybil defense
To prevent Sybil attacks and spam, Tribler Channels should employ some automated information filtering mechanism. In other words, *automated attacks can only be beaten by automated defense*. This defense can be provided by prioritizing information updates with higher [Channels Trust score](#4485).

### Pull-based gossip
Information transfer in the Lightnet should be based exclusively on pull-based, or in other words, "push-request"-based gossip. Pull-based gossip ensures that no *direct* Sybil attack is possible. As soon as social connections are settled, group selection starts filtering out bad actors and practices. Any person can comment and change any element of other's channel, but only subscribed peers ("friends") will *ask* for these changes/comments and *accept* them.

### New Arrivals feed
Tribler home screen should feature a Facebook-like "New Arrivals" feed dynamically showing the most recent changes in the subscribed channels, sorted by the Channels Trust score.

### Approval of changes
If Tribler would receive a conflicting entry from one of the "liked" peers, the change will be suggested at the "My Channel" page. If the user approves it, the change is signed by their public key.

**Comment by synctext** [comment]
What is exactly the problem with duplicates?
Storage?

**Comment by ichorid** [comment]
There are numerous problems with duplicates, namely:
 * Storage. In the case of a 'fork war', DB's will blow up instantly.
 * Performance. Bigger DB's lose a lot of performance as my tests show, especially due to FTS index.
 * Gossip efficiency. If there is no selection mechanism, gossiping around duplicates drowns Matthew effect in the noise.
 * Human mind processing capabilities. Users do not want to stare at 20 copies of the same thing.

In addition, just copying around stuff produces no new [integrated information](https://en.wikipedia.org/wiki/Integrated_information_theory). Instead, we want our network to become a giant information integration engine, akin to Wikipedia. To achieve this goal, users must get some influence on *any* data that they see, even if this influence will be weak and stochastic.

**Comment by synctext** [comment]
## Crowdsourcing brainstorm for 2020
(our platform is not ready this year for sophisticated features, we need to have more mature anonymous download first!)

Making local edits to channels seems trivial to implement, but not easy from user experience perspective.
Suggesting to keep the channel owner in firm control. Each channel owner competes for eyeballs and votes with other channels. That is the driving incentive. Highly voted channels have more prominence in the GUI. @ichorid is that inline with your thinking?

To keep matters future-proof we could enable crowdsourcing and create contributions per channel. This reduces fragmentation. There is an "inbox" of incoming 1) renaming suggestions 2) new magnets to add. This inbox is as-simple-as-possible and has only a 1 week viewing history. It is more a recent suggested changes with 1) reject change and 2) accept suggestion for the channel owner.

**Comment by ichorid** [comment]
@synctext , you nailed it! That is exactly how I see it. Essentially, we recreate a simplified version of the tried-and-true GitHub pull request process.

**Comment by triblerteam** [comment]
> Tribler home screen should feature a Facebook-like "New Arrivals" feed dynamically showing the most recent changes in the subscribed channels, sorted by the Channels Trust score.

This is a big feature! Love to have it in Tribler! Lots of user impact and visibility. Please put that in another separate issue. With other improvements that could be the 7.6 release, while the "inbox for edits" would then be a 7.7 feature.

**Comment by ichorid** [comment]
Duplicate of #6217
