### ISSUE TITLE
CTRL+SCRL change font size!

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#4487]
##### Tribler version/branch+revision: #####
Latest beta may 7th 2019
##### Operating system and version: #####
WIndows 10 1903
##### Steps to reproduce the behavior: #####
STart Tribler
##### Expected behavior: #####
When using CTRL+SCRL font is enlarged or decreased in size
##### Actual behavior: #####
On a 4k screen things are VERY small!
##### Relevant log file output: #####
![image](https://user-images.githubusercontent.com/1146496/57440973-4823de00-7249-11e9-8a58-ad528008c337.png)

**Comment by devos50** [comment]
We should fix Tribler on a 4k screen, see also [here](https://doc.qt.io/qt-5/highdpi.html).

**Comment by qstokkink** [comment]
Tribler now has a web-based front end and this issue should be resolved.
