### ISSUE TITLE
Support for changing network interfaces in Tribler

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4489]
Some users desire to be able to select a different network interface to use for Tribler. We only allow localhost(lo) as of now. Supporting different interfaces through the config should be relatively easy for the REST APIs but need to check for libtorrent.

**Comment by ichorid** [comment]
If we add support for non-local interfaces for the REST API, we should add HTTPS and authentication. Otherwise, our users could face severe security consequences.

**Comment by qstokkink** [comment]
It is now possible to bind to non-local interfaces.
