### ISSUE TITLE
Tribler and Ipv6

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#4492]
##### Tribler version/branch+revision: #####
any
##### Operating system and version: #####
Windows 10 build 18894
##### Steps to reproduce the behavior: #####
Ipv6 ds-lite
##### Expected behavior: #####
Upload works
##### Actual behavior: #####
SInce a few days a have Ipv6 from Ziggo.nl, they implement Ipv6 DS-lite in which I have an Ipv6 address but my Ipv4 address is one of theirs. 
It looks like, that while I am downloading I seed to ipv4 addresses, but as soon as I am finished downloading and the file is anonymous I see no uploads at all.
Also I would expect to se Ipv6 address froom seeders and leechers, but I see none!
Is Tribler able to handle Ipv6 address? And why does the seeding seem to stop.
I know that my internal port 80 was Not reachable when I tested, because of the way Ziggo implemented Ipv6. I know for certain that if I would have gotten Ipv6-ds-full I would have had my own ipv4 address. Please advice.
Thanks

**Comment by Nubro01** [comment]
As soon as I make an entry none anonymous then the connections start appearing and stay when I turn on anynomous to yes. Seems to me we have a problem with anonymous and tcpv6 with ds-lite.

**Comment by xoriole** [comment]
@Nubro01 As of now, we do not have support for IPv6. We should start planning the support soon.
About anonymous seeding, it should be working, however, it is normal to see a low number of peers in anonymous mode. We'll look into it.

Related issues: 
[#3202 Add support for IPV6 when tunneling data](https://github.com/Tribler/tribler/issues/3202)
[#4127 No more TCP/IP V6 seeders and leechers](https://github.com/Tribler/tribler/issues/4127)

**Comment by Nubro01** [comment]
Hi,

You may contact me whenever you need access to an external Ipv6 address and I'll send you my current Ipv6 address.
If you give we yours then I'll open up my modems firewall for that traffic.

Regards

Ron

________________________________
Van: Sandip Pandey <notifications@github.com>
Verzonden: maandag 13 mei 2019 10:44
Aan: Tribler/tribler
CC: Ron Nuberg; Mention
Onderwerp: Re: [Tribler/tribler] Tribler and Ipv6 (#4492)


@Nubro01<https://github.com/Nubro01> As of now, we do not have support for IPv6. We should start planning the support soon.
About anonymous seeding, it should be working, however, it is normal to see a low number of peers in anonymous mode. We'll look into it.

Related issues:
#3202 Add support for IPV6 when tunneling data<https://github.com/Tribler/tribler/issues/3202>
#4127 No more TCP/IP V6 seeders and leechers<https://github.com/Tribler/tribler/issues/4127>

**Comment by Nubro01** [comment]
Today I disabled IPv4 and watched what happened. Thanks to the IPv6 DS-Lite of my provider I did see leechers IPv4 baddress making connections with anonymous torents. As soon as I switch anonymous off the leecher addresses disappeared, not to return until I made it anonymous again. an address which often appears is 1.1.1.1:1024 ???? The Tribler.org site is, as expected, not reachable with IPv6!
Since you are in a University, would it be an idea to assign somebody to this? IPv6 is more secure and about to happen and some articles regarding Tribler and IPv6 would be very interesting.

**Comment by Nubro01** [comment]
Today in the version of Beta5 June20th I saw saw Ipv7 seeders.
![afbeelding](https://user-images.githubusercontent.com/1146496/59864732-c49cf700-9387-11e9-903b-b0f12008b3ea.png)

**Comment by Nubro01** [comment]
Today, since a long time I again saw a Ipv6 address giving me download, so???
![afbeelding](https://user-images.githubusercontent.com/1146496/68993173-4df02100-0875-11ea-8e69-74de9cce4602.png)

**Comment by synctext** [comment]
thank you for reporting that. Good to know IPv6 support is spotted in the wild.

**Comment by qstokkink** [comment]
The only remaining part of Tribler that does not support IPv6 is the anonymization. For that, a separate issue already exists #3202 Therefore, I'll close this issue (please refer to #3202 instead.
