### ISSUE TITLE
How to translate?

### ISSUE THREAD

**Issue by linsui** [Tribler/tribler#4513]
How can I translate Tribler? Is there any guide?

**Comment by xoriole** [comment]
@linsui Currently, we only support English language and don't have language translation support so it is not possible to translate to other languages. However, with a diverse user base, I think we should start supporting different languages in future releases (7.3 +). We'll keep you informed when we add the feature to support language translations and would welcome any translation contributions.

**Comment by linsui** [comment]
Thanks!
