### ISSUE TITLE
Add native unsigned payloads format for FFA entries in GigaChannel

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4543]
Currently, when we serialize free-for-all payloads, we fill `public_key` and `signature` fields with zeroes. This is efficient enough because we use LZ4 compression. However, the proper solution is to add support for completely unsigned blobs. To do this, we have to change the serialization/deserialization routines.

**Comment by qstokkink** [comment]
@ichorid this was solved by the free for all payloads right?

**Comment by ichorid** [comment]
No. This ticket is about the *serialization format* for FFA payloads. We already use FFA entries, but their payloads format could have been more efficient. This is the reminder-ticket to add the specific serialization format for these.

**Comment by ichorid** [comment]
Not needed, since lz4 is good enough at packing zeroes efficiently
