### ISSUE TITLE
TriblerUpgrader runs after upgrading v7.3.0-beta2 to v7.3.0-beta4

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#4545]
##### Tribler version/branch+revision: #####

d6cb10efd60fc995f0db1ac07406715e96f422e6 v7.3.0-beta4

##### Operating system and version: #####

Linux 

##### Steps to reproduce the behavior: #####

Follow Tribler beta versions, approximately this path:

1. older Tribler
1. v7.3.0-beta1 (online slow conversion)
2. v7.3.0-beta2
3. v7.3.0-beta3
4. v7.3.0-beta3 + master pyipv8
5. rollback to v7.3.0-beta2
6.  v7.3.0-beta4

##### Expected behavior: #####

Tribler just starts normally, without redoing the 7.2 -> 7.3 migration.

##### Actual behavior: #####

Torrents getting converted, like as if it was a pre-7.3.0 version.

After converting it seems to work and search normally. Restarting Tribler also does not trigger the conversion again.

##### Relevant log file output: #####

    INFO    1560044123.61              db72_to_pony:325  (TriblerUpgrader)  Converted old torrents: 200/147866 0.080359

**Comment by qstokkink** [comment]
@ichorid as you made this: is this expected behavior or a bug?

**Comment by ichorid** [comment]
Yes, this is expected behavior. Database format changed again in beta4. I did not want to spend time on doing beta-to-beta DB upgrader, so beta4 just removes the previous beta DB if it finds one and re-runs the conversion process.
