### ISSUE TITLE
Beta 4 en latest Beta abend at startup

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#4555]
#### Please, fill all relevant items: ####

- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Operating system and version: #####
WIndows 10 build 18912
##### Steps to reproduce the behavior: #####
Start Beta 4
##### Expected behavior: #####
Normal startup
##### Actual behavior: #####
When running Beta 3, Tribler would abend while running and a report was send each time.
Now with Beta 4 I get an abend at startup.
When i rename the .Tribler folder aall is fine, but then I loose my Library and my Token balance and ratio.
When I install the lastest Beta 2 all is fine!!!!
Dumping all Torrents is a pain, one by one under Beta 2, loading all Torrents gives me an abend after two Torrents loads, dump also send.

**Comment by ichorid** [comment]
@Nubro01 , do your username in the system or the path to the Tribler dir contain non-ASCII (non-latin, unicode,  etc.) characters?
Do some of the torrents you seeded in the previous version of Tribler contain files or dirs with non-ASCII characters?

**Comment by ichorid** [comment]
Today, I got a similar problem while trying to run Beta4 on Windows with username in non-ASCII characters.

**Comment by Nubro01** [comment]
None that I see, unless you meen [ ] _

**Comment by Nubro01** [comment]
Beta 4 of the 11th also fails at startup, report was just send! Hope you received it.

**Comment by ichorid** [comment]
Thanks for your report! Unfortunately, it is impossible to identify it among other reports...
If you would kindly copy-paste the error in this GitHub issue, it will be easier for us to solve your problem.

**Comment by Nubro01** [comment]
I was expecting that you would receiced this automatically since a report was send!
In the mean time I have send the torrents by private mail and you were able to get the same error.

**Comment by ichorid** [comment]
@Nubro01 , of course we received the report. We try to fix every error that we receive. However, there are dozens of reports for every beta, and there is no way for us to associate some report with some github account (like @Nubro01) or some real person's name (like Ron Nuberg). We only collect depersonalized data to preserve our users' privacy.

That is why we don't know which one exact report was sent by you (or any other person).

Nonetheless, my colleague sent me the torrents you sent him, and we were able to reproduce the problem. Apparently, many users reported this problem through the reporter, and I fixed it immediately. However, the fix will only be available in the next beta (beta5).

Again, thanks for your involvement!

**Comment by Nubro01** [comment]
With the June 13th version I was able to import my beta 2 dumped Torrents and I could rebuild my library, just once, because after I imported that one Torrent and it was added to my library. So that portion is fixed.
But when I tried switching back to my orginal .Tribler folder , then tribler still abends at start up.
DO you want me to zip my .Tribler folder and send it?

**Comment by Nubro01** [comment]
I wonder if the trust graph or data has something to do with this error. The new build .Tribler used has a much smaller trust graph then my old .tribler had?

**Comment by qstokkink** [comment]
I think just removing the `metadata.db` in the `.Tribler/sqlite` folder would be enough.

**Comment by Nubro01** [comment]
Makes no difference, report was send with issue description an number within report description. Hopes this helps to find the problem.
The new .Tribler folder works just fine, but if I rename folders and use theBeta 2 .Tribler folder then tribler abends at startup.
Is there a way to get my ratio and token balence back? backup and restore, would be nice for the future if library problems occur again.

**Comment by Nubro01** [comment]
Was unable to find a private email address, so I used wetransfer to send mdmartijndevos@gmail.com my .Tribler folder. This folder works in 7.3 Beta2, but fails at staratup in Beta 3 and 4.
Hope it helps to determine what is causing the problem.

**Comment by Nubro01** [comment]
Juli 20th version opened my Beta 2 .tribler folder, thanks.
What caused the problem?
