### ISSUE TITLE
Error on shutdown in latest devel

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#4578]
```python
ERROR   1560869708.24            tribler_window:74   (root)  Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/TriblerGUI/event_request_manager.py", line 136, in <lambda>
    self.reply.error.connect(lambda error: self.on_error(error, reschedule_on_err=reschedule_on_err))
  File "/home/quinten/Documents/tribler/TriblerGUI/event_request_manager.py", line 81, in on_error
    raise RuntimeError("Could not connect with the Tribler Core within 20 seconds")
RuntimeError: Could not connect with the Tribler Core within 20 seconds
```

**Comment by ichorid** [comment]
I've seen this too a couple of times. It mostly happens if I skip database conversion on a very large database, and then try to shutdown immediately.

**Comment by qstokkink** [comment]
I did have a newly subscribed channel which wasn't done doing stuff with its torrents (I assume database stuff).
The subscribed channel torrent was completely downloaded though.

**Comment by ichorid** [comment]
Channel processing is done in a background thread. On shutdown, the thread is signaled by the core to stop processing .mdblobs by setting `self._shutting_down` flag on the MetadataStore object.

**Comment by qstokkink** [comment]
So the underlying issue is that `LaunchManyCore` does not wait for the `MetadataStore` to completely shut down?

**Comment by ichorid** [comment]
Probably so.

**Comment by ichorid** [comment]
I'll try to make MetadataStore shutdown procedure use Deferreds to solve this.
