### ISSUE TITLE
Metainfo lookup not done when BEP33 is not available

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#4614]
The torrent health check is simply not done if BEP33 is not available. This means that torrents without any tracker attached will not be checked in that case. We should have a fallback on the 'old' torrent health lookup mechanism to prevent this.

**Comment by ichorid** [comment]
On what platform do you observe this behavior? How can one check this?

**Comment by qstokkink** [comment]
@ichorid I believe @devos50 is fixing this, but if you're interested it's this `if`-statement:

https://github.com/Tribler/tribler/blob/981e0bcceb67ab64db8ac971c70b2524421bb5a7/Tribler/Core/TorrentChecker/torrent_checker.py#L296-L301

**Comment by ichorid** [comment]
I'm interested because of my Tribler on Linux checking torrents health almost instantly, but only in the case Tribler or Transmission was running on my machine for some time. I guess that is somehow related to the fact that I got a real IP on my testing machine.
