### ISSUE TITLE
Channel reports completion but seems incomplete

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#4627]
On my Mac at home, I subscribed to a channel with many torrents. It downloaded successfully and then started to process mdblobs (this process actually became slower over time). When it appeared to be done, it reports completed, even though the counter seems to indicate that I do not have all the processed items.

![Schermafbeelding 2019-06-25 om 21 35 42](https://user-images.githubusercontent.com/1707075/60127852-8477b300-9791-11e9-9dc8-26ecf87f1fe5.png)

**Comment by xoriole** [comment]
I think this is because of the bug in committing the channel. This is related to https://github.com/Tribler/tribler/issues/4639 where discovered channels show an incorrect number of torrents for own channel. I believe fixing #4639 should also fix this.

**Comment by qstokkink** [comment]
Also overlap with #4638
