### ISSUE TITLE
GigaChannel Community 100% CPU

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4636]
GigaChannel Community somehow causes up to 100% load on the core and lots of DB i/o. I suspect this is caused by inefficient Pony queries on push-based gossip.

**Comment by ichorid** [comment]
Note that this only becomes apparent when the database is really big.

**Comment by qstokkink** [comment]
Would this be solved by #4249 ?

**Comment by qstokkink** [comment]
Also, I notice some "CPU storms", but overall the GigaChannelCommunity seems pretty healthy:

![afbeelding](https://user-images.githubusercontent.com/3630389/60249070-43cc8680-98c4-11e9-9a09-000738740f1e.png)

**Comment by ichorid** [comment]
#4249 will only be a part of the solution. We'll have to start caching some SQL queries (for example, selection of random entries for gossip) and do some other stuff.

This is not like finding a bottleneck and fixing it, but more like charting a safe path through a minefield...

**Comment by qstokkink** [comment]
> charting a safe path through a minefield...

I agree, maybe we should leave this for `7.4` then and focus on other stuff right now.

**Comment by ichorid** [comment]
For 7.3 I'm going to address the most offending problems that are relatively simple to fix.
