### ISSUE TITLE
knowledge crowdsourcing

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#4642]
# Idea brainstorming issue

With Gigachannels and our contributing crowdsourcing community we're taking the first step of evolving beyond Bittorrent and Tor. We want to evolve further in coming decade and make "hive mind" fantasies a scientific reality. (see #4475)

TUDelft faculty member Prof. @Christophlo has published several works on scientific crowdsourcing, [Large Scale Cooperation Scenarios – Crowdsourcing and its Societal Implications (2016)](https://github.com/ChristophLo/publications/raw/master/16TIR_LargeScaleCooperationScenariosCrowdsourcingAndItsSocietalImplication.pdf). He is willing to help us. Other publications on this topic are:
- [KATARA: A Data Cleaning System Powered by Knowledge Bases and Crowdsourcing](https://dl.acm.org/citation.cfm?id=2749431)
- [DOCS: a domain-aware crowdsourcing system using knowledge bases](https://dl.acm.org/citation.cfm?id=3025118)

The Tribler platforms requires a trust function and anti-spam measures to facilitate further crowdsourcing. Most of the effort will be hard-core engineering and numerous improvement cycles. Knowledge crowdsourcing requires intense platform engineering, not a dramatic enabling scientific breakthrough. It is essential that the crowsourcing community grows steadily and instantly starts using new features. We envision two primary use-cases: science and entertainment. Using the same platform any artist or scientist should be able to upload and share their creativity with the world. We aim that our generic editing mechanism support both music metadata and musical score (crowdsourcing cultural heritage) as well as scientific articles and citation culture.

Possible evolution steps:
- [ ] _links_ Every channel owner can provide a portion of a page of text about the channel with inclusion of magnet links.
- [ ] _markup and pictures_ Pictures are somehow supported in the "channel page" and markdown editor gets integrated into Tribler, [like this one](https://github.com/ncornette/Python-Markdown-Editor)
![screenshot-editor-md](https://user-images.githubusercontent.com/325224/60359369-2ccb8880-99d9-11e9-99b7-85e69f3693ff.png)
- [ ] _science channels_ Scientific articles in .pdf format get explicit channels support with title and author metadata. Support for cloning, commenting and enhancing scientific publications. For instance, a living survey channel with the state-of-the-art in a scientific field and markdown-based overview.
- [ ] _scientific reputations_ Somehow we show the karma and citations of scientific authors and their work.
- [ ] Usage of reputations and richer editing practices, as shown on Wikipedia.

**Comment by synctext** [comment]
Focus: alternative scientific publication method
- IdeaDAO
- open market of ideas
- strong IDs
  - trustchain
  - Github
  - BTC
- secure code contributions by strangers
- secure online voting
- Both core platforms PRs and plugin contributions.

**Comment by synctext** [comment]
### Markdown embedding - Web3 exploration

Tribler is torrent download client, it is completely "web-free". We do not use HTTP or Javascript technology (well, except for our own integrated webserver to expose the Tribler with a REST API). Explore for 2 weeks how easy it is to embed rich text browsing, hypertext and picture embedding into Tribler. Focus is the GUI part and library linkage. Download engine is out of scope, just bundle the content locally as a shortcut. This is a exploratory step for broader "knowledge crowdsourcing" in the 2022 or 2021 timeframe. Possibly we will put a master student on this topic.

Desired outcome, Markdown viewer embedded into Tribler to view markdown, images and can follow 1 hard-coded link:
![Tribler_7 5_simplificatio3](https://user-images.githubusercontent.com/325224/99967090-a2d34b00-2d97-11eb-8185-af0b8a795c91.png)

- Goal: explore how difficult or easy it will be to take Tribler beyond torrents
  - establish the difficulty of markdown integration
  - complete re-use of our _existing_ QT interface (years of work to debug)
  - streaming, credit mining, and tokens took us years and we never got it operational
- Time boxed effort: strict 2 weeks exploratory prototype
- Library code:
  - https://pypi.org/project/markdown-viewer/ (non-QT)
  - https://pypi.org/project/Markdown-Editor/
  - https://github.com/Python-Markdown/markdown
- Demo content: [wiki page](https://simple.wikipedia.org/wiki/Pyotr_Ilyich_Tchaikovsky), out-of-copyright [sheet](https://files.musopen.org/sheetmusic/96087364-b23d-4705-b5c2-7bafb14acec5.pdf?filename=Childrens%20Album%2C%20Op.39%20-%20Complete%20Score%201.pdf), Portugeese [scientific article](https://doi.org/10.1590/S1517-75992012000200009), and [libretext entry](https://human.libretexts.org/Bookshelves/Music/Book%3A_Music_Appreciation_I_(Lumen)/08%3A_Late_Romantic_Era/8.09%3A_Peter_Ilyich_Tchaikovsky).
  - focus on markdown please, store demo content locally in source code repo
  - demonstrate embedding principle: magnet link to a swarm (.mdblob) and filename
  - metadata and storage are not not the focus of this sprint
  - not about the editor, just the content viewer for now
- Deliverable after 2 weeks
  - running code with limited usability (Ubuntu, Windows,Mac)
  - single animated .GIF file suitable for .PPT presentations of max. 2 MByte 
![image_insert_markdown](https://user-images.githubusercontent.com/325224/99965356-0b6cf880-2d95-11eb-8dde-c6eba733a05f.gif)

**Comment by drew2a** [comment]
Related:
- #6214

**Comment by qstokkink** [comment]
Since the inception of this issue, we have done away with channels entirely, obsoleting the idea of markdown embedding. Furthermore, the similar approach of Jupyter was also rejected and abandoned.

The successor to these ideas is linked in the post above and, with that, this issue can now be closed.
