### ISSUE TITLE
Show precise number of torrents in the channel

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#4645]
Right now we have some issues regarding the determining of the state of a channel.
It seems to be impossible to say which torrents have been removed in the latest state of a channel, given gossip from a previous state.

Concretely, we appear to be unable to do the following:

 - _Upon receiving gossip (1) about channel A_: determine if (1) is part of A at timestamp t

This causes old information to be included in the views of channels and giving results like `300% completion`.

**Comment by ichorid** [comment]
The ability to get excess torrents is a feature, and not a bug. For example, if you already got a channel complete and after that, you receive some new torrent from the newer version of the same channel, you do not drop it, but include it in the same channel. That is how you get 101/100 torrents.

This may be ugly, but this is better than just dropping useful and legit information. The proper way to fix it is to show only the stuff that is covered by the current timestamp range of the channel known to you and hide everything else. In this scenario, receiving any torrent with a timestamp that is higher than the highest timestamp of a channel with the same public key means its author had updated their channel. This means we need to take some *actions* to get the updated channel entry. This should be served by some form of global search such as DHT. Unfortunately, our DHT is still not ready.

So, my design decision was to keep showing excess entries until we get working DHT-based channel updates checks.

**Comment by qstokkink** [comment]
Fair enough from a technical standpoint, but we need to communicate this properly to our users.

> Unfortunately, our DHT is still not ready.

It is available and used in IPv8, you should be able to hook into it.

**Comment by ichorid** [comment]
> It is available and used in IPv8, you should be able to hook into it.
Good! I'll make this an issue for 7.4

**Comment by qstokkink** [comment]
![afbeelding](https://user-images.githubusercontent.com/3630389/63033470-f4640900-beb7-11e9-99cb-2ac9131c4ce8.png)

`(Complete) 8/11` feels a bit weird. Should we maybe just hide the completion rate for the time being?

**Comment by ichorid** [comment]
@qstokkink , IDK, really. It is hard to guarantee that the channel's author will not screw the count up by their actions.
