### ISSUE TITLE
Efficient order of checks processing payloads in GigaChannel

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4650]
At the heart of GigaChannel is the [`process_payload`](https://github.com/Tribler/tribler/blob/01c88f20c13552035f78418206f41fcb037f7508/Tribler/Core/Modules/MetadataStore/store.py#L360) method, which acts as a firewall for all incoming GigaChannel data.

This method features a lot of checks that evoke costly SQL queries for each processed payload, such as checks for duplicates, old versions, etc. The order in which these checks run does not affect the fate of the packet (they all just drop it). However, some orders can be much more efficient in terms of SQL requests. The higher the probability of the check, the higher it should be moved in the checking order, so we do not waste i/o on rarely used checks.

One way to solve this problem is to gather some statistics on what checks trigger most often, and then reorder the checks accordingly. Unfortunately:
 1. we don't do telemetry on our users.
 2. in some modes, like uploading data from a channel torrent, patterns of triggered checks are very different from the average.

This problem reminds the problem of scheduling operations in the CPU conveyor and can be solved accordingly, by introducing a *dynamic* ordering of the checks, based on some recent stats. The ordering can be determined by, e.g. VSIDs heuristics.

**Comment by qstokkink** [comment]
For reference on (1), telemetry nearly killed GitLab:
https://gitlab.com/gitlab-com/www-gitlab-com/issues/5672

**Comment by ichorid** [comment]
> For reference on (1), telemetry nearly killed GitLab:
> https://gitlab.com/gitlab-com/www-gitlab-com/issues/5672

That's why I'm gonna try determine the order *dynamically*, on the client's side.
