### ISSUE TITLE
documentation is very out of date, especially Trustchain

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#4656]
https://github.com/Tribler/tribler/blob/devel/doc/trustchain.rst

We still refer to Dispersy even 😃

**Comment by synctext** [comment]
Got feedback from an excellent technical writer on working for us. Writing down priorities and schedule for a 4 month documentation refactoring.

|  Duration | activity | Audience |
|-----|-----|---|
| ??? weeks | Conduct deep-dive into Tribler as preparation; [rewriting the main wiki project overview page](https://github.com/Tribler/tribler/wiki#tribler-an-attack-resilient-micro-economy-for-media) plus short [readme.md](https://github.com/Tribler/tribler#tribler) | General Public |
| ? weeks | 1 web page fluffy promo. Accomplishments of past 17 years, [self-replication AI and alternative Big Tech](https://github.com/Tribler/tribler/issues/4659) in future | General Public | 
| ? weeks | promo: "tokens for cultural heritage". From Trustchain, [credit mining](https://github.com/Tribler/tribler/issues/3337), with [artist income of 100%](https://github.com/Tribler/tribler/issues/3326#issuecomment-507672326) to [trust function against spam and evilness](#10)  | General Public |
| ? weeks | [Trustchain](https://github.com/Tribler/tribler/wiki/Multichain-specifications) mild overview | General Public |
| ? weeks | [Trustchain IETF](https://tools.ietf.org/id/draft-pouwelse-trustchain-01.html) technical documentation |  technical |
| ? weeks | [IPv8](https://github.com/Tribler/py-ipv8/tree/master/doc) | developers |

**Comment by drew2a** [comment]
We do not have `trustchain.rst` anymore.
