### ISSUE TITLE
Metainfo error in loading torrent info 

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4663]
![Screenshot from 2019-07-06 10-34-46](https://user-images.githubusercontent.com/1442867/60753920-d2828700-9fd9-11e9-8aa9-f97edbc77b93.png)

```
WARNING 1562402054.91             LibtorrentMgr:506  (LibtorrentMgr)  Handle is not valid - returning None as metainfo lookup result
WARNING 1562402054.92      torrentinfo_endpoint:72   (TorrentInfoEndpoint)  Received metainfo is not a valid dictionary
```

**Comment by qstokkink** [comment]
Could you print and share this particular metainfo dict?

**Comment by xoriole** [comment]
The metainfo dict is `None`. I noticed that some of the torrents still do return good metainfo.

These are other relevant log lines
```
WARNING 1562403673.34             LibtorrentMgr:475  (LibtorrentMgr)  Failed to add torrent with infohash dcaff6b8b4b11215629e93add0950df3ec66e24d, attempting to use it as it is and hoping for the best
WARNING 1562403673.34             LibtorrentMgr:476  (LibtorrentMgr)  Error was: No registered converter was able to produce a C++ rvalue of type bytes from this Python object of type sha1_hash
```
(Infohash is of Debian torrent)

**Comment by xoriole** [comment]
Checking the alerts received after adding the torrent in the session, found that `metadata_received_alert` is never received within the timeout interval which is why we were getting metainfo error. After some retries (add to session, wait for metadata, remove torrent), it does seem to get the results but this is not very user-friendly.

PR https://github.com/Tribler/tribler/pull/4665 fixes some minor issues related to fetching meta info but does not fix the issue. For now, I'm moving this issue to 7.4

**Comment by qstokkink** [comment]
This is assumed fixed now.
