### ISSUE TITLE
Trust Graph 2.0

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4668]
Even though, computation for Trust graph generation only happens when the graph is in the view, it still consumes quite a high amount of CPU. This is because `matplotlib` is not efficient when rendering real-time visualization. A good alternative seems to be `pyqtgraph` where the performance and responsiveness are very good compared to the current implementation. Here is a sample 2D graph based on `pyqtgraph`.
![trust-graph-2 0](https://user-images.githubusercontent.com/1442867/60961886-5eafe980-a30d-11e9-9e94-524b459a79e5.png)

**Comment by synctext** [comment]
CPU is indeed bad, but rendering time is really an issue now. Let's set this at 2 seconds maximum. 

With one test it took 9.8k edges over 10 seconds to render, something we want to get better in a new version. We don't need a 3D version of this, anything that renders the first batch of edges in 1-2 seconds is perfect. Better to visualize this incrementally, rendering wait is unacceptable to impatient Youtube-like users. Using 3D might be costly in developers time to get this deployed on Win,Mac,Deb? Plus, people rarely click-and-drag such graphs. It needs to look appealing without any interaction or understanding of the user. For instance, if we go 3D it needs to slowly rotate to show depth.

**Comment by ichorid** [comment]
Tried it out with the latest RC. It is super fast. The only problem is that I can't really see *my* connections on the graph. Other nodes' connections just overwhelm the picture with grey lines.

We should highlight personal connections in some way.

![graph](https://user-images.githubusercontent.com/2509103/63191240-53688000-c068-11e9-85e3-acfb74bfd52a.png)

**Comment by xoriole** [comment]
The purpose of this issue is done, so let's create a new issue for the improvements.
Closing this issue for now.
