### ISSUE TITLE
Alt+F4 closes whole Tribler instead of a pop-up window.

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#4675]
##### Tribler version/branch+revision: #####

v7.3.0-beta6 + patches

##### Operating system and version: #####

Linux, X11

##### Steps to reproduce the behavior: #####

1. Open Tribler
2. Press "+" button
3. Create torrent from files
4. Close the torrent creation window with Alt+F4

##### Expected behavior: #####

Torrent creating window closes

##### Actual behavior: #####

Tribler shuts down

**Comment by qstokkink** [comment]
Hmm.. I would consider it expected behavior to close the window on `ALT+F4`. At the very least I would not say this is a bug.

We should discuss what we want to happen on `ALT+F4`. In this case, I would vote to keep the current behavior.

**Comment by ichorid** [comment]
In every major application I know, Alt-F4 closes the window that is currently open (e.g. file selector dialog, History/Settings in Firefox, etc). I think this is the *de facto* standard. I am no expert in UI/UX, though.

**Comment by devos50** [comment]
I also agree to just close the window when the user presses ALT+F4. We could however show a new dialog and ask whether the user really wants to close Tribler on a close event, but this would be a different issue I guess. Therefore, I'm closing this issue.

**Comment by vi** [comment]
If it is intended behaviour then maybe torrent creation/adding dialog should not look like a pop-up window?
