### ISSUE TITLE
Adding to search results?

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#4683]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.
Juli 18th 2019 version
##### Tribler version/branch+revision: #####
7.3
##### Operating system and version: #####
Windows 10 insider  18936
##### Steps to reproduce the behavior: #####
Search with Tribler and no result found. Find Torrent in different way and download.
Search again with Tribler and some Torrents you just downloaded are now found, but not all of them
##### Expected behavior: #####
Every Torrent in my lybrary should be added to Tribler search result!
##### Actual behavior: #####
Not every entry of my library is found when searching for it through the tribler search.
Please explain how this should work and please add a right click action to add to search results.

**Comment by qstokkink** [comment]
This is probably a duplicate of #4674

**Comment by ichorid** [comment]
@Nubro01 , thank you for your report!
If you're using the latest beta (7.3-beta6), when you download a torrent from any source, the torrent is always added to your database as a so-called free-for-all (FFA) entry. It is searchable, but it is not in your (or anyone else's) channel. You can search for it and add to your channel later by right-clicking on the FFA entry you found. Torrents downloaded before 7.3 are not added to the database (but your old database is converted on startup).

When you start downloading a torrent, there is a checkbox in the dialog window that allows you to add this torrent to your personal channel. Also, there is a right-click menu option in the downloads screen to the selected torrent to your channel.

In Tribler, there are many ways to add torrents. Please, could you describe **exactly** what sequence of actions leads to torrents not being added to the database?

**Comment by synctext** [comment]
Interesting... Please try:
Do a search
Manual downloaded file in library, also matches prior search
Do 2nd search, do results increase?
User intuition says that all files in library + discovered channels should show up in a search. What is Tribler behavior now?

**Comment by ichorid** [comment]
@synctext , this is exactly how it works now: all downloaded torrents are added to DB as FFA entries. They are perfectly searchable.

**Comment by Nubro01** [comment]
Sorry was away, troubles with my 96 year old mother.
As I said, before when I search for a specific torrent using the Tribler search then I mostly do not find the brand new files that I am looking for. When I find them in a different way and I download them using Tribler, then SOMETIMES I am able to find them, as soon as they are finished downloading, with the Tribler search, but most of the time I do not find them. 
Since Tribler is all about sharing, I hoped this was the way it would work.
If I add the extra checkbox and add them to my channel, then I can find them, but I wonder if other Tribler users can find them too. I hope so, since Tribler is all about sharing! Meaning we would not need sites like thepiratebay, etc. anymore.

**Comment by ichorid** [comment]
@Nubro01 , sorry to hear about your mother. Hope she is all right now!

In the latest version, we made the decision to only make torrent titles searchable. This means that when you download torrent with the name "Foo" that contains some files like "bar1.mkv", "bar2.mkv", you will only be able to search for "Foo". We have plans to add support for torrents' contents. However, for now, it only should work like this:
 * when you download a torrent, it becomes searchable by its name as FFA entry for you and other users;
 * if you check the checkbox, it is added to your personal channel, and it becomes searchable too and shared as a part of your personal channel for you and other users.

This means that whenever you download a torrent or check a magnet link, it should become searchable. If sometimes it would not become searchable immediately, that is a bug. We need your help to pinpoint it. Please, try to reproduce it several times reliably, and report the exact sequence that leads to it, describing all the clicks, buttons pressed, etc. Otherwise, we can't fix it.

**Comment by Nubro01** [comment]
Can I send you the files in private, or can I mention them in the issue?
Did not find your private email within your github profile.

**Comment by ichorid** [comment]
Yeah, you can send it to `v.g.bulavintsev@gmail.com`

**Comment by Nubro01** [comment]
Send info and I will leave Tribler running today, Sun is shining and I have solar panels, so..... ;-)

**Comment by Nubro01** [comment]
I was just thinking, since a couple of months I am on Ziggo TCPIP V6 with a NATTED IPv4 of Ziggo, might that be the cause of my downloads not always updating to the general database? If I search on seriename S03E05 xvid, I find one result and a recheck does not see me seeding it!

**Comment by ichorid** [comment]
I've tried to add the torrents you sent me, and every one of them was immediately searchable. Note, though, that the torrent health info is unreliable, and we can't do anything about it. It is slow to show the changes in the swarm, it will not show people behind a NAT, and it will not count *you* as a seeder. It will count you eventually as a part of the swarm, and only if you are connectable (meaning not behind a NAT).

>  I am on Ziggo TCPIP V6 with a NATTED IPv4 of Ziggo,
yes this means you're not connectable from outside, at least until Tribler supports IPv6. We're planning to add IPv6 support at the beginning of 2020.

**Comment by Nubro01** [comment]
Ok, clear, my luck ... 
But when I search now, I would expect to find the ones you uploaded, but it is still the same. I only see S03E05.

**Comment by ichorid** [comment]
If you mean you expect to find the ones uploaded by *me*, you will probably not find them for two reasons:
 1. Tribler only searches torrents in the immediate peer proximity. This means that there is no global search for torrents based on names, but there are plans for that. Global fuzzy string-based search is an extremely difficult topic and no one was able to do it properly to this day. We decided to polish our database procedures based on 1-hop search only for this year.
 1. As a developer, I run Tribler with temporary database and only for a brief time. Therefore, there is almost no chance that your Tribler instance would connect, by pure chance, with *my* Tribler instance.

Don't worry, when the majority of the Tribler network will upgrade to 7.3, there will be plenty of channels/peers to search for. Popular torrents will propagate very fast.

**Comment by Nubro01** [comment]
Ok, I remember my metadata.db was very large in the past, I asumed that all data about Torrents was stored there, my current is just 2 MB, and trustchain.db is 60 mb.
I hope you hurry up with the TCP/IP v6 support, more and more we need Tribler to replace things like piratebay and VPN and communicate securely with ip v6.
