### ISSUE TITLE
ambiGUIty

### ISSUE THREAD

**Issue by MeadowHillSoftware** [Tribler/tribler#4693]
##### Tribler version/branch+revision: #####
7.3.0 Beta 4
##### Operating system and version: #####
Manjaro
##### Steps to reproduce the behavior: #####
Run Tribler
##### Expected behavior: #####
It is easy to distinguish between checked and unchecked boxes in GUI
##### Actual behavior: #####
It is not easy to distinguish between checked and unchecked boxes in GUI

It's confusing to have disabled options represented by a square with an "X" in it. When I first looked at the options, I thought my client was set up to run as an exit node so I clicked the box to disable that option and the "X" was replaced by a checkmark. I said, "Wait, that was disabled?" I had to click it again to re-disable it. I would suggest using an empty box to represent a disabled option.

**Comment by qstokkink** [comment]
On all machines we test with they do look like empty boxes. Could you provide a screenshot?

**Comment by ichorid** [comment]
On @xoriole 's machine they looked like "X"-es, I've seen it many times. I didn't like it too, though I  @xoriole is gonna fix it. This looked really annoying.

**Comment by MeadowHillSoftware** [comment]
Can't provide a screenshot. It's crashing.

Meant to file a bug report before it starting crashing but never got around to it.

**Comment by devos50** [comment]
@MeadowHillSoftware which version of Tribler are you using that's crashing?

**Comment by MeadowHillSoftware** [comment]
Beta 4: https://github.com/Tribler/tribler/issues/4666#issuecomment-513479259

**Comment by MeadowHillSoftware** [comment]
[RC1 Build #96](https://jenkins-ci.tribler.org/job/_One-Click-Release-Custom/96/) fixes this.

**Comment by devos50** [comment]
Nice, thank you for your feedback!
