### ISSUE TITLE
Meaningful data for bootstrap file

### ISSUE THREAD

**Issue by grimadas** [Tribler/tribler#4704]
Now bootstrap file includes a random blob that doesn't provide any useful information for the TrustGraph. A good next step would be to put some fixed set of selected transactions that helps to enrich TrustGraph from the start.

**Comment by grimadas** [comment]
I have a progress on this issue. I fetched top 400 peers based on the number of blocks that were also online recently.  I also included last interactions between these 400 peers(last blocks between them). Resulting database dumb is around `32 MB` and `~38.000 blocks`. 

When this database dumb is  downloaded peer adds block into local database. This allow quickly(~1 min) get network of top peers and build a trustgraph that you would normally build within days or even months.   

![image](https://user-images.githubusercontent.com/5897440/61946200-39c0a500-afa2-11e9-8f24-c27fc644f586.png)

**Comment by devos50** [comment]
Resolved by #4714.
