### ISSUE TITLE
Mac App -- Endless "Loading…", never loads; unusable

### ISSUE THREAD

**Issue by SainteCelery** [Tribler/tribler#4715]
#### Please, fill all relevant items: ####

- [x ] I have read CONTRIBUTING.rst

- [x ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
7.2.2 rc

##### Operating system and version: #####
MacOS Mojave

##### Steps to reproduce the behavior: #####
Open the app. It never finishes "Loading…". Spinning gears. Have left running for hours with no change. Have reinstalled 3 times.

##### Expected behavior: #####
App should start up and become usable.

##### Actual behavior: #####
Endless "Loading…" with spinning gears

##### Relevant log file output: #####
No log output at all

**Comment by synctext** [comment]
Never even starts, that's bad. Is this 7.3 RC1 you tested from forum.tribler or 7.2.2 release on Tribler.org ?

**Comment by SainteCelery** [comment]
7.2.2 [latest non-beta/pre-release candidate]

Looking back through older issues people have submitted, it seems this specific endless loading glitch has cropped up occasionally on a variety of platform releases. So, I'm thinking there's likely a common cause and it's probably something super minute like a space in front of a comma.

**Comment by devos50** [comment]
Could you please test out [the RC build of Tribler 7.3.0](https://github.com/tribler/tribler/releases) and check whether Tribler starts?

We have indeed received multiple reports about Tribler not starting, especially on Mac. So far, however, we have been unable to pinpoint the exact cause of this issue (we have access to several mac machines where Tribler does not show this behaviour unfortunately).

**Comment by SainteCelery** [comment]
7.3.0rc loads up fine and as expected! 

Maybe you could diff the two versions & see if anything pops out as a culprit-?

While trying to get 7.2.2 going, I disabled security apps, went back to the default host file, dns cache flushed, & set Little Snitch to accept everything. With all that stuff going again 7.3.0rc worked. So, I don't really have any clues to follow.

**Comment by devos50** [comment]
That's interesting. We have many changes between 7.2.2 and 7.3 so diff-ing them is a lot of work. In particular, we have removed some dependencies but also added a few. If i have to guess, it was caused by the `M2Crypto` library which has been removed now. At least I'm glad to hear that it is working for you now!

**Comment by ManifoldSky** [comment]
FTR, the thing that is "loading" is the settings file. For whatever reason, as mentioned, this is corrected in the RC.
This may be related to the fact that that MacOS 7.2.2 disk image can not be mounted by DiskImageMounter (OS X default) and has to be opened manually with Disk Utility. The RC opens just fine.
Playback streaming of active torrent, however….

**Comment by devos50** [comment]
@ManifoldSky I never noticed any problem with mounting the .dmg file on Mac. Do you see any error when you try to mount it?

Also, I agree that the playback of torrents requires some serious engineering love. We will see what we can do for this or maybe the next release.
