### ISSUE TITLE
No seeding setting broken

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#4716]
RC1 on Mac.

Seed and see the upload continue.

**Comment by devos50** [comment]
Hmm, maybe Tribler needs a restart in order for this change to be effective? If so, we should clearly communicate this to the user.

**Comment by synctext** [comment]
Still broken after restart.

**Comment by qstokkink** [comment]
Cannot be reproduced by me or @grimadas, moving to `7.4`.

**Comment by egbertbouman** [comment]
I just found that this is related to the download_defaults not being copied into the DownloadConfig. This means that the defaults come from download_config.spec.

**Comment by ichorid** [comment]
:man_facepalming:
