### ISSUE TITLE
popup fails to open on Ubuntu with seconds screen

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#4735]
"Plus" does not work/open.
Having a primary and secondary screen. Fails when Tribler GUI is inside primary desktop. Works fine on secondary screen. Ubuntu 18.04.2 LTS
![image](https://user-images.githubusercontent.com/325224/62855876-a4d4e000-bcf3-11e9-9a14-e55d3c5ac6be.png)

**Comment by devos50** [comment]
Could be related to this issue? https://bugreports.qt.io/browse/QTBUG-60513?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true

**Comment by synctext** [comment]
```
dpkg-query -l | grep -y python |grep qt
ii  python-pyqt5                                         5.10.1+dfsg-1ubuntu2                            amd64        Python 2 bindings for Qt5
ii  python-pyqt5.qtsvg                                   5.10.1+dfsg-1ubuntu2                            amd64        Python 2 bindings for Qt5's SVG module
ii  python3-pyqt5                                        5.10.1+dfsg-1ubuntu2                            amd64        Python 3 bindings for Qt5
```
