### ISSUE TITLE
Automate fake Tribler API responses generation

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4750]
Currently, we are forced to duplicate our endpoints code and program REST API responses for the GUI tests by hand. Fake Tribler API code quality is horrible. It is basically the old copy-pasted Tribler code patched with ad-hoc mock objects. Also, whenever someone changes something in the Core, they have no way to say **if** and **how** it will affect the endpoints responses.

Instead, we can just run the GUI script against a real Tribler Core once and **record the responses**. The Fake Tribler API then essentially becomes a [Chinese Room](https://en.wikipedia.org/wiki/Chinese_room) for REST requests. Switching to a fixed playbook will have the following effects:
 * GUI tests become deterministic;
 * developers don't have to tediously copy-paste code into Fake Tribler API;
 * less code, fewer errors;
 * we get the ability to **get diffs** between a REST playbook generated by a pull request and a an existing one;
 * we gain the ability to **get visual diffs** between the GUI screenshots to see the changes immediately.

It should be straightforward to implement this, as the change requires just recording the JSON exchange between the Core and the GUI during the GUI tests.

**Comment by ichorid** [comment]
Apparently, there is already a Python library to do this kind of stuff:
[VCRPY](https://github.com/kevin1024/vcrpy)

**Comment by ichorid** [comment]
After a day of :heart: with `vcrpy`'s patching system, I managed to provide a compatibility wrapper for `TriblerRequestManager`.

**Comment by qstokkink** [comment]
Cool! Do you have an example/screenshot of the output of vcrpy applied to Tribler?

**Comment by ichorid** [comment]
Well, the screenshots aren't gonna show anything. I'll post some more info as soon as at least a single GUI test will work this way.

**Comment by ichorid** [comment]
After a few days of experimenting, I found myself replacing more and more of `vcrpy` code with custom solutions. In the end, `vcrpy` proved to be incompatible with our requests patterns for several reasons (e.g. Tribler pushing messages through Events endpoint, etc.)

On the other hand, I figured out it will be pretty easy to build our own `vcrpy`-*like* request player-recorder.

**Comment by synctext** [comment]
Great investigation! Does this vcrpy direction feel good for production usage?

**Comment by ichorid** [comment]
Yes, definitely. I'm working on it right now.

**Comment by ichorid** [comment]
To make it work, we first need to separate the GUI from the Core... As usual, nothing is easy with Tribler... :facepalm:

**Comment by ichorid** [comment]
And now after recording the responses, etc., I figured out it will be much more convenient and productive to just use the real Core to generate responses. We'll have to add a special "deterministic" mode to it though. The mode will disable/emulate network connectivity, use fixed seeds for RNGs, etc.
