### ISSUE TITLE
Channel subscriptions outnumber discovered

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#4753]
Somehow I am subscribed to more channels (4 unique) than I have discovered (3 unique):

![afbeelding](https://user-images.githubusercontent.com/3630389/63042409-39913680-beca-11e9-85d9-d7ba6a1a14e0.png)

These channels have been subscribed to through the discovered channels though.
Seems like something is broken.

**Comment by qstokkink** [comment]
Confirmed after removing metadata db file:

![afbeelding](https://user-images.githubusercontent.com/3630389/63088043-098e7580-bf54-11e9-8a18-f6ad4e91ef59.png)

**Comment by ichorid** [comment]
It would be nice if you provide the database file...

**Comment by qstokkink** [comment]
Sure, here you go:

[metadata_db.zip](https://github.com/Tribler/tribler/files/3510331/metadata_db.zip)

**Comment by ichorid** [comment]
Checked that out. The channel that is not there was graded as XXX and thus not shown on the "Discovered" page. If you turn the filter off in the settings and restart Tribler, you'll be able to see it.

**Comment by qstokkink** [comment]
Makes sense, by design then.
