### ISSUE TITLE
Unresizable window when adding a torrent with magnet link

### ISSUE THREAD

**Issue by FXlife** [Tribler/tribler#4756]
#### Please, fill all relevant items: ####

- [ X ] I have read CONTRIBUTING.rst

- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
tribler_7.2.2

##### Operating system and version: #####
Debian 10

##### Steps to reproduce the behavior: #####
Just add a link with the " + " button on a 800x600 screen resolution laptop

##### Expected behavior: #####
Having a resizable window

##### Actual behavior: #####
Unresizable window so can't see or choose any option for downloading or even cancel. Only force close in the task manager can exit this window

##### Relevant log file output: #####
Don't have any

**Comment by devos50** [comment]
This is probably due to the minimum window size required by the Qt widgets. I'm not sure whether it is desired to override this behaviour. Fixing it requires us to make changes to the layout properties of the Qt widgets in the GUI.

**Comment by imstanz** [comment]
Same over-sized window issue.
I have not got as far as this issue - but at startup, window is larger then my 1366x768
laptop screen.
No way to shut down either. Unresizable window so can't see or choose any option for minimize or close. Can only force close-  in the task manager can exit this window.
![1st run window](https://user-images.githubusercontent.com/1240082/64990315-6f885880-d884-11e9-83a1-008d982b319f.png)
No acces to top menu-bar or "if" there's an included "close" button, on bottom!

**Comment by imstanz** [comment]
Found and edited my: ~/.config/TUDelft/Tribler.conf
`[General]`
`autocommit_enabled=true`
`family_filter=false`
`first_discover=true`
`pos=@Point(188 -10)`
`size=@Size(1048 755)`
Changing "pos" and "size", centered window abit more, AND lowered the window enough
to view the top...better! **I hope the adjustments sticks!?**
![resulted window](https://user-images.githubusercontent.com/1240082/64998296-699c7280-d898-11e9-8b64-f7ff4a5d2936.png)

**Comment by xoriole** [comment]
@imstanz glad that it works for you. Unless the window is resized, the changes should be persistent.

**Comment by qstokkink** [comment]
Maybe we should add  a startup flag or a config file for the window position. I had to jump into regedit on Windows once as well, after Qt decided to place my window at `(16000, 16000)`.

**Comment by drew2a** [comment]
Fixed in #7008
