### ISSUE TITLE
tribler fails to start on debian9; 7.3.0-rc4_all.deb

### ISSUE THREAD

**Issue by imstanz** [Tribler/tribler#4767]
#### Please, fill all relevant items: ####

- [ nope ] I have read CONTRIBUTING.rst

- [ yep ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
tribler_7.3.0-rc4_all.deb

##### Operating system and version: #####
Debian 9,  Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 GNU/Linux
##### Steps to reproduce the behavior: #####
just install & try to start. both from menu or terminal
##### Expected behavior: #####
start & run
##### Actual behavior: #####
no response at 1st startup attempt. 
Checked for and Install remaining 'Recommends', and install for
development environment
[tribler_error.TXT](https://github.com/Tribler/tribler/files/3536685/tribler_error.TXT)

. 
blt (2.5.3+dfsg-3)
libtcl8.6 (8.6.6+dfsg-1+b1)
libtk8.6 (8.6.6-1+b1)
python-faulthandler (2.4-1)
python-tk (2.7.13-1)
tk8.6-blt2.5 (2.5.3+dfsg-3)
##### anything odd to report: #####
could not connect to core within 60 secs.
A few error reports have been submitted by me, after failed attempts.

**Comment by qstokkink** [comment]
As per https://stackoverflow.com/questions/34819221/why-is-python-setup-py-saying-invalid-command-bdist-wheel-on-travis-ci, seems like `pip install wheel` is also required in our deb file.

**Comment by synctext** [comment]
Ai, good we did another RC to test the installer. Still a missing dependency.

**Comment by xoriole** [comment]
@imstanz could you write the output of pip version?
```
pip -V
```
also, try to install `wheel` followed by `pony` and `lz4`
```
pip install --user wheel
pip install --user pony lz4
```
Keep us informed if that works for you.

**Comment by xoriole** [comment]
There seems to be issues with ubuntu 19.04 and Debian 10.
Many dependencies are missing because of Python 2.7
![ubuntu-19 04](https://user-images.githubusercontent.com/1442867/63694476-d763fa00-c816-11e9-9909-40046e7adf56.png)

**Comment by xoriole** [comment]
@imstanz Could you try the latest release and let us know if it works for you?
https://github.com/Tribler/tribler/releases/tag/v7.3.0

**Comment by imstanz** [comment]
@xoriole 
Hello,
I'll install pip-pkgs & test first, 
...if it still fails, then I'll try latest version (wondering if uninstall is necessary?).

$ pip -V
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

Ok,
`Successfully installed wheel-0.33.6`
`Successfully installed future-0.17.1 lz4-2.2.1 pony-0.7.10`

brb...

**Comment by imstanz** [comment]
Sorry folks...1st cup of coffee -- I didn't mean to close!!!
`$ pip -V
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)`
and..
`Successfully installed wheel-0.33.6`
`Successfully installed future-0.17.1 lz4-2.2.1 pony-0.7.10`
It failed again, I'll reboot and try again - before trying the latest release.
If "uninstall first" is required - please request!
brb

**Comment by xoriole** [comment]
@imstanz could you attach the logs?

**Comment by imstanz** [comment]
@xoriole , these are the only logs with info.
/.Tribler/logs:
[tribler-gui-info.log](https://github.com/Tribler/tribler/files/3617060/tribler-gui-info.log)

[tribler-gui-error.log](https://github.com/Tribler/tribler/files/3617064/tribler-gui-error.log)

**Comment by imstanz** [comment]
With no clear list of required dependencies for regular user install, I tried to full-fill them,
by installing for "Development Environment".
This seems to duplicate 'above' ubuntu error pic.
[Required pkgs for dev environment_apt errors.txt](https://github.com/Tribler/tribler/files/3617089/Required.pkgs.for.dev.environment_apt.errors.txt)
I will uninstall/purge this version, and reinstall requested version.

**Comment by imstanz** [comment]
@xoriole 
It Loaded!! 
I installed the 2 pkgs (above post) and ran: "pip install --user aead" (from post).
Ran tribler from menu and it progressed to loading 'channels'.
Right now, it shows "Discovered channels", with a terribly over-sized window!

I also find, other previous "empty" log files, now contain information (from: /.Tribler/logs).
I will open a new issue, about over-sized window.
ANY other info or help I can offer -- just ask!!  :)
imstanz

**Comment by xoriole** [comment]
@imstanz Glad that you're able to run Tribler.
`freeglut3` and `python-opengl` should be installed already when installing `python-pyqtgraph`. I'll put a check on all the dependencies during startup so the errors on missing dependencies become more clear. Thank you for trying out the release.
