### ISSUE TITLE
Tribler release roadmap

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4772]
![Tribler-roadmap (1)](https://user-images.githubusercontent.com/1442867/63777888-2deb3a00-c8e4-11e9-9b2d-c8fb16da9b91.png)

The current stable release is `Tribler 7.3.0` released today which runs on Python 2. The next release is `Tribler 7.4.0` which will be more or less like `Tribler 7.3.0` without any major feature but running just on Python 3. This release will be the base for `Tribler 7.4.X` releases. All the release dedicated to Usenix research will go on `Tribler 7.4.X` releases planned to be released on a monthly schedule.

In the meantime, on the `devel` branch, `Nested channels` and `Async IO` will be worked on and each will likely produce experimental releases of `Tribler 7.5.0`.

After the Usenix research is done, anything useful from `Tribler 7.4.X` branch will be cherry-picked to `devel` and added to Tribler.

**Comment by ichorid** [comment]
Don't forget we still have to merge the current 7.3.0 release branch into `devel` after Python3 infrastructure changes are ready.

**Comment by synctext** [comment]
Very useful picture. If you find too much instability in devel or Python3 switching will not be done before 15Sep, please feel free to alter the plans and update this ticket.
It is possible to branch out from 7.3.0 instead of devel, if (Gumby,Py3,devel,..) fact-finding missions dictate this.

**Comment by synctext** [comment]
### Release 7.4.0 for 15 Sep

Our requirement is to have an Internet-deployed deceptively simply trust system by 15 November. This is input for a major scientific publication. The reason for the rapid release cycle is to keep the core stable and only improve the trust function and trustchain. The majority of the development and research team will contribute to this sprint. 

PGP has for decades been the only practical means of deploying public keys and building a web-of-trust. The scientific aim is to grow Trustchain towards the size of the PGP strong set (or al least more edges):
![image](https://user-images.githubusercontent.com/325224/63870072-893b2c00-c9b9-11e9-9713-eec574941a68.png)
At some point we'll do a self-attack. Obtain quantitative data on the effect of various types of attacks.

**Comment by ichorid** [comment]
After a quick chat with the Usenix team and a day of fixing Python 3 compatibility issues introduced by `release-7.3.0 -> devel` merge, we decided that the Usenix team should fork off from `release-7.3.0` and continue development in Python 2.

**Comment by ichorid** [comment]
Closing for now, as there is almost nothing to plan, and almost no one to execute the plans...
