### ISSUE TITLE
RuntimeError: wrapped C/C++ object has been deleted

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4779]
Version: 7.3.0
Platform: Windows-7-6.1.7601-SP1
Uptime:1687.55800009
Report: [26546](http://reporter.tribler.org/stacktrace/26546)

```python
Traceback (most recent call last):
File "TriblerGUI\dialogs\startdownloaddialog.py", line 142, in perform_files_request
RuntimeError: wrapped C/C++ object of type ClickableLabel has been deleted
```

**Comment by devos50** [comment]
This might have happened just after closing the start download dialog. Catching the `RuntimeError` could be enough I guess?

**Comment by drew2a** [comment]
It should be fixed in https://github.com/Tribler/tribler/pull/5888
