### ISSUE TITLE
Unable to convert a Python 'unicode' object to a C++ 'QString' instance

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4785]
Version: 7.3.0
Platform: Linux-5.2.9-arch1-1-ARCH-x86_64-with-glibc2.2.5
uptime: 67.2126891613
Report: [#26580](http://reporter.tribler.org/stacktrace/26580)

Stacktrace
```python
TypeError: invalid result from ChannelsContentModel.data(), unable to convert a Python 'unicode' object to a C++ 'QString' instance
```

**Comment by ichorid** [comment]
This happens sometimes on Arch, as they seem to always do bleeding edge stuff...
[PyQt bindings are the offender here](https://bitbucket.org/tortoisehg/thg/issues/5438/problem-to-start-tortoisehg-502-unicode). Fixed in upstream PyQt. We can safely ignore this.
