### ISSUE TITLE
Drop Tkinter

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#4799]
At some point in time `tkinter` was shipped with Python.

However, this is no longer the case. 

Therefore we should not use `tkinter` anymore as a fallback option and switch to some other library we already use anyway (like Qt).

**Comment by ichorid** [comment]
Very nice idea, indeed!

**Comment by ichorid** [comment]
This will align well with @egbertbouman removing Twisted and many other unnecessary dependencies.
