### ISSUE TITLE
Trust graph is still slow

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4823]
Even with depth limited to 3, Trust graph loading is slow for a huge database. A limit should be implemented to prevent CPU overload. 

See screenshot below:
![IMG_20190907_172740](https://user-images.githubusercontent.com/1442867/64515319-a8f11f00-d2ec-11e9-9311-b5997da11bc5.jpg)

**Comment by qstokkink** [comment]
To maintain an accurate graph of interactions and also alleviate pressure on the CPU, we could also render static images per slice and overlap the outputs.

**Comment by grimadas** [comment]
I guess when graph gets bigger there is no point in showing the whole graph. Maybe we can only show part of the connections/nodes, while maintaining statistics of the nodes/interactions.

**Comment by devos50** [comment]
> Maybe we can only show part of the connections/nodes

One of the issues is that there are many low-valued connections (e.g., users that transferred like 1MB). We could prune the graph and only show the 'important' interactions, based on the total amount of bandwidth transferred.

**Comment by ichorid** [comment]
Personally, I don't see any sense in showing this graph at all. Any kind of information is only good if it will eventually affect some decision. Otherwise, the information is just noise. **What kind of decision this graph is going to affect?** When we answer this question, we will know exactly what it must show.

**Comment by xoriole** [comment]
https://github.com/Tribler/tribler/pull/4834 addresses the issue about the slow rendering of the Trust graph by limiting the number of nodes (500 max) and transactions (2500 max, latest). Regarding the quality of the connections, we can have a separate discussion on which nodes or transactions to show in the graph on a separate issue.

**Comment by synctext** [comment]
Is the slowness reproduced in the lab? Plus fixed in this PR?

**Comment by xoriole** [comment]
Yes, to some extend. Here are some results:

**Case 1: Before limiting the graph**
Nodes: 2K+, Transactions: 15K
Time to load: **12.2345 seconds**
![j-2](https://user-images.githubusercontent.com/1442867/65245070-2a665f80-daec-11e9-828a-b3c4a2c52a43.png)

**Case 2: After limiting the graph**
Nodes: 323, Transactions: 793
Time to load: **0.142 seconds**
![j-3](https://user-images.githubusercontent.com/1442867/65245262-8c26c980-daec-11e9-9169-39add5387ba6.png)

This was tested on my workstation PC which is quite strong so the numbers might not represent normal user's machine but the difference is (quite) observable.
