### ISSUE TITLE
Stuck on "Shutting down Torrent Checker"

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#4839]
##### Tribler version/branch+revision: #####

v7.3.0 360172b579b2d2140d9bd675ed1804efd161a7f4

##### Operating system and version: #####

Linux

##### Steps to reproduce the behavior: #####

Start Tribler, use it for a while (more than a day), close it.

As far as I remember, all [visible] downloads were at "Seeding" state.

##### Expected behavior: #####

It closes normally.

##### Actual behavior: #####

Shutting down gets stuck on `Shutting down Torrent Checker...`. Eventually "Force shutdown" button appear. Pressing it finally shuts down Tribler.

##### Relevant log file output: #####

```
INFO    1568592495.65            LaunchManyCore:728  (TriblerLaunchMany)  tlm: early_shutdown
INFO    1568592495.65                   Session:564  (Session)  Tribler shutdown state notification:Shutting down Credit Mining...
INFO    1568592495.65       CreditMiningManager:107  (CreditMiningManager)  Shutting down CreditMiningManager
INFO    1568592495.65                   Session:564  (Session)  Tribler shutdown state notification:Shutting down Torrent Checker...
...[force shutdown]...
INFO    1568592611.68                 community:61   (DiscoveryCommunity)  Dropping introduction request from (131.180.27.137, 8090): too many peers!
INFO    1568592613.47                 community:61   (DiscoveryCommunity)  Dropping introduction request from (131.180.27.137, 8090): too many peers!
INFO    1568592664.10               run_tribler:142  (root)  Shutting down Tribler
```

**Comment by devos50** [comment]
The torrent checker is apparently still a problem when shutting down, even though we already have tried to close it a bit more aggressive. We should look into this again.

**Comment by ichorid** [comment]
I guess we should really address it only in 7.5, when asyncio stuff will be merged. That will change the mechanism for shutting down stuck reactor tasks.

**Comment by Solomon1732** [comment]
I also have the app stuck for windows v7.3.1 and v7.3.2 except that in my case it's stuck on "Checkpointing downloads...". I don't know if it's due to the same cause or not. I also get a lot of exceptions in the log file during shutdown.

Relevant log file output:
https://gist.github.com/Solomon1732/01dc82a38ff068389e9a04a420e6d495

**Comment by ichorid** [comment]
Closing this, as in 7.5 Twisted got dumped in favor of asyncio, and libtorrent wrapper was partially refactored. Feel free to reopen if you see this problem **in 7.5**.
