### ISSUE TITLE
Add toggle button to control anonymity in the download dialog

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4854]
There are two problems with our "Download torrent" dialog window:
 1. Anonymity control is done by a small checkbox that is hard to notice. Instead, the current anonymity mode should be instantly visible and toggleable.
 2. DHT requests go through the regular connection, which are [observable](https://iknowwhatyoudownload.com) (see #4021). Instead, if anonymity is on, the DHT request should go through the tunnels as well. But if the user toggles anonymity mode, the DHT request should be immediately sent again directly. This is non-intuitive with the checkbox.

The solution is to use a toggle button, like this:
![LHLiq](https://user-images.githubusercontent.com/2509103/65426842-59910f80-de11-11e9-82e5-e909bf97782c.gif)

One implementation of a toggle control in pure QT: https://stackoverflow.com/a/51825815/5553928

The button for anonymity should be "ON" by default, and the file list dialog should show a ticker with time till DHT request timeout. As soon as the timeout is reached, a suggestion to try the request again in non-anonymous mode should be shown to the user.

**Comment by hbiyik** [comment]
for 2: %100 agree, I was trying to tweak out this behavoir for a while, but the code is still to complex for my mortal brain. tunnel dht please

**Comment by ichorid** [comment]
Well, turned out tunneled DHT requests are very unreliable. This makes adding this toggle control top priority, so users who do not use anonymity will not suffer from bad DHT performance over the tunnels.

**Comment by qstokkink** [comment]
This should be resolved now: anonymity is on by default and metadata retrieval when adding torrents should be tunneled.
