### ISSUE TITLE
Does Tribler still use BuddyCast?

### ISSUE THREAD

**Issue by cattaneomn** [Tribler/tribler#4860]
Hi, im reading about Tribler and the code on github, many documents says that Tribler use the BuddyCast Protocol, but i see that it was delete from the code on github.
My doubts are:
-Does Tribler still use BuddyCast?
-If yes, i guess i just keep looking for it on the code XD 
-If not, someone could tell me wich is the new protocol that remplace BuddyCast.

**Comment by qstokkink** [comment]
No. BuddyCast is our founding protocol. It was the simple idea that led to our complex stack as it is now.

The first iteration after BuddyCast was formed by Dispersy, the AllChannelCommunity, the DiscoveryCommunity and MultiChain.

Currently our stack consists of IPv8, the GigaChannelCommunity, the DiscoveryCommunity and TrustChain. Many of the core concepts and ideas from the original BuddyCast protocol still survive though. Only the social network distance and taste have been thoroughly reworked as we have become more of a privacy preserving client.

**Comment by cattaneomn** [comment]
Thanks for your quick answer, it helps me a lot :).

**Comment by cattaneomn** [comment]
Sorry to reopen it, just a doubt that comes to my mind.
The BuddyCast taste buddies, that improves the Gossip over a metric of "taste" was refactored on the code for something else for preserving privacy?

**Comment by ichorid** [comment]
@cattaneomn , the "taste" subsystem was removed completely. Instead, now we only have tunnels for anonymity (served by IPv8), push-based gossiping of subscribed channels, and remote search of random peers for keywords. That is it. Not social-network-like features.

In the future, the current GigaChannel subsystem will add features for collective editing, nested channel, global search, and rich metadata. Currently, there are no short- or mid- term plans for a recommendation system.
