### ISSUE TITLE
Error opening debug panel

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4865]
```python
Traceback (most recent call last):
File "TriblerGUI\tribler_window.py", line 912, in clicked_menu_button_debug
File "TriblerGUI\debug_window.py", line 156, in __init__
TypeError: setTabEnabled(self, int, bool): argument 2 has unexpected type 'NoneType'
```
Reporter [#27954](http://reporter.tribler.org/stacktrace/27594)
```
platform win32
platform.details Windows-10.0.18980
platform.machine x86
python.version 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
indebug True
tribler_uptime 789.044000149
```

**Comment by ichorid** [comment]
https://github.com/Tribler/tribler/blob/d7c5a0a0fafb5628a6d6b2b7cf1ad14a71a12191/src/tribler-gui/tribler_gui/debug_window.py#L93-L96

This kind of thing should only happen in case the user somehow managed to make the setting `None`. We haven't seen this in a while. Closing it.
