### ISSUE TITLE
Is it still an issue?

### ISSUE THREAD

**Issue by necros2k7** [Tribler/tribler#4870]
https://lists.torproject.org/pipermail/tor-dev/2014-December/007999.html

**Comment by egbertbouman** [comment]
@necros2k7 In 2015 we have rewritten much of our tunnel crypto. See https://github.com/Tribler/tribler/issues/1066 for the related issue.

**Comment by necros2k7** [comment]
Long story short - can tribler user still be exit node for person who share illegal content?

**Comment by synctext** [comment]
We focus on end-2-end encryption now.

You can become an exit node if you insist. Goto Tribler setting and click "enable exut node", then click away the warning popup, plus restart Tribler. Not enabled by default.

**Comment by necros2k7** [comment]
It was security related user side questions not a feature request)
