### ISSUE TITLE
Lack of significant information on the token balance chart

### ISSUE THREAD

**Issue by cuileri** [Tribler/tribler#4873]
Current State:
- In the current version of the given/taken data chart on "Token Balance" page shows the total amount of data given to and taken from the community since the installation of tribler. The graph spans only a short period of time (18 days in my case).

![chart](https://user-images.githubusercontent.com/22027137/65877174-450dc380-e38b-11e9-81d4-bdb9254fd7e7.png)

The problem:
- The information given in the chart is not significant. 
The daily increase in the download/upload amounts are negligible with respect to the total amounts. For example, for the users who have already uploaded/downloaded hundreds of GB of data, the chart is quite guaranteed to show nothing different than two horizontal lines.

Suggestion for solution:
- Chart can span a longer time interval.
- Chart can have an additional layer of information, for example daily average download/upload, as below.

![mean](https://user-images.githubusercontent.com/22027137/65877066-0415af00-e38b-11e9-9e04-aa3becbe58d5.png)

**Comment by ichorid** [comment]
Just make it RRD-style, i.e. logarithmic time axis.

**Comment by drew2a** [comment]
@cuileri sorry :) but it is not relevant anymore:
- #7761
- #7798
