### ISSUE TITLE
"dropping a complex remote search query" in error log

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#4889]
RC 7.3.1RC3 on Mac
Seeing a lot of these. Can this be more documented, or did I miss something? Please cleanup the error log output for privacy. Only abstract info.

Like: Remote query contains 11 keywords, ignoring all except the first 4.
Like: Remote query contains a suspicious SQL command from IPv4 address "8.8.8.8", dropping.
Like: Remote query contains keywords from IPv4 address "8.8.8.8" which are blacklisted, dropping.

**Comment by ichorid** [comment]
These messages indicate a situation when some other peer queried your GigaChannel DB with a query that is considered to be incorrect or unsafe. The sender' address is not indicated in the log messages, so this poses no danger to privacy. Also, it is very helpful to see what kind of messages are dropped, for debugging purposes.

**Comment by ichorid** [comment]
Closing this. @synctext , please reopen if you still think it poses some danger.
