### ISSUE TITLE
Log exception instead of ignoring it

### ISSUE THREAD

**Issue by Solomon1732** [Tribler/tribler#4891]
- [x] I have read CONTRIBUTING.rst

##### Tribler version/branch+revision: #####
V7.3.1-RC3 and devel
##### Operating system and version: #####
All
##### Expected behavior: #####
Exception should at least be logged to aid developers' debugging and users' error submissions.
##### Actual behavior: #####
Exception ignored and swallowed.
##### Location In Codebase: #####
https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Upgrade/upgrade.py#L57

**Comment by devos50** [comment]
I think logging the error you linked could indeed be helpful for both users and developers. @ichorid is there a reason why this exception is not logged?

**Comment by ichorid** [comment]
The line @Solomon1732 is pointing out is in 7.3.0->7.3.1 conversion procedure. It checks `.pstate` files for the files not confromant to the channel torrent format and deletes them. This kind of files can only appear in two cases:
* the channel creator produced a non-conformant channel torrent file, and it was downloaded in 7.3.0 (7.3.1 checks the channels torrent for conformance *before* downloading);
* some local error resulted in malformed `.pstate` file.

The first case is handled by the upgrader script. The second case (malformed file) should be handled upstream by Libtorrent wrapper. Therefore, there is no reason for us to put something in the log in this case during the upgrade procedure: the same files will be read again and handled appropriately at the later stages of Tribler startup.

@Solomon1732 , however if you want, you can create a PR to add some logging statement.

**Comment by Solomon1732** [comment]
Would "debug" level suffice? Or should it be something like "warning"?

**Comment by Solomon1732** [comment]
Created pull request at "debug" level #4894

**Comment by Solomon1732** [comment]
I'm closing the issue since #4894 , which was based on this issue, was merged
