### ISSUE TITLE
Channels discovery/search returns little results

### ISSUE THREAD

**Issue by zS3mNH2** [Tribler/tribler#4906]
#### Tribler version/branch+revision: #####
7.3.2

##### Operating system and version: #####
Linux

##### Steps to reproduce the behavior: #####
I ran the client for 24 hours to allow it to be fully connected to the network.

Search for content. For example input "movie" or "2018" or "horriblesubs" or "english" something generic that should return lots of results

I have 61 "discovered" channels. The largest is NyaaTorrents with 550k torrents. However, the client has only downloaded and made available for viewing 160 of these titles so I cannot see what the other torrents are. It says "downloading" so I expect it would eventually download all 550k so that they are known content, but it takes a long time.

No other channels have a considerable amount of content.

In the debug screen it says "795 torrents known" and 53 channels (despite saying 61 results on the channels page). 

##### Expected behavior: #####
Presented with thousands of search results

##### Actual behavior: #####
Searching for "2018" which basically will be included in most movies / series only resulted in 53 search results. I would expect thousands to be returned. There seems to be a real issue with content discovery.

**Comment by ichorid** [comment]
Thanks for reporting!
The Channels system was redesigned completely for 7.3.0 and later versions. However, old collected torrents were lost in the process. Also, only a small fraction of users have yet upgraded to the new version. At the moment, there are only about 160 channels in the network.

The reason why a channel can become stuck in "Downloading" state is that BitTorrent is now used as a backend for fetching channels contents. And that means the channel torrent should have seeds. Also, to prevent system abuse, we only seed subscribed channels. Moreover, we used a very conservative approach for gossiping and search algorithms for this version to keep things as simple as possible for the first version of the redesigned Channels.

The next Tribler release 7.4 will still feature these conservative algorithms. Next-next release 7.5 is planned for January, and that will include much more aggressive gossiping, bootstrapping and search algorithms, as well as a complete refactoring of the Tribler core.

I'm sorry to say that, but there is only so much we can do within the confines of our current userbase and development team sizes. However, the team is confident that much more content will flow into the system in the upcoming months.

If you're interested in learning/discussing the current and future Channels design, please see #3615

**Comment by ichorid** [comment]
Mostly solved by RemoteQuery community.
