### ISSUE TITLE
Some out of date wiki information

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#4931]
The wiki section *overlay protocol for synchronization* is out of date: https://github.com/Tribler/tribler/wiki#overlay-protocol-for-synchronization

This still mentions Dispersy as our main messaging infrastructure and links to my personal fork of IPv8 as a "new overlay".

We can still keep the description of Dispersy for historic reasons, but we should update this section to better reflect the current architecture of Tribler.

Lastly, the "Tribler history" section (https://github.com/Tribler/tribler/wiki#tribler-history) mentions the release of IPv8 in 2019. Actually IPv8 was first released in october 2017 (the attestation layer in december 2017), first deployed in Tribler in 2018 (deprecating Dispersy) and we fully switched all Tribler communication to IPv8 in 2019.

**Comment by synctext** [comment]
feel free to make big changes!

**Comment by ichorid** [comment]
We can remove it now. My plan was to describe the GigaChannel protocol after 7.5 release, which will feature the nested channels feature and pull-based gossip scheme.

**Comment by qstokkink** [comment]
> We can remove it now.

The purpose of this Wiki page is to show the evolution of the science around Tribler and the future vision for the project. We shouldn't just remove our entire heritage. Documenting our successes and failures allows us to learn from the past.

I do agree with *adding* a section for the new GigaChannel stuff and an in-depth Wiki page on the GigaChannel protocol.

**Comment by qstokkink** [comment]
I added in Dispersy and fixed the IPv8 first release in the timeline. Do we also want to mention the Bartercast -> Multichain -> TrustChain evolution in this timeline?

**Comment by synctext** [comment]
Would limit the wiki to current state. Gigachannel capabilities and IPv8 offerings.
Historical evolution is best kept brief. Developers are not digital historians in most cases. Aug 2007 roots is sufficient I guess, with reference to Bartercast.

**Comment by qstokkink** [comment]
@synctext all of the wiki? Most of the pages (for example https://github.com/Tribler/tribler/wiki/Multichain-Milestones) are basically historical curiosities with little value for the current way of working. We can throw out 95% of our wiki material then.

**Comment by qstokkink** [comment]
I want to start on this by removing old pages. We currently have the following pages:

- Home
- "TrustChain" architecture
- Anonymous Downloading and Streaming specifications
- Compiling Tribler from sources under Eclipse
- Getting back your Tribler state dir after update to 7.4.2
- Hidden Services Specifications for anonymous seeding
- How to move Tribler state directory to another computer
- MasterThesis
- Paying out bandwidth tokens in TrustChain
- Related Research Groups
- Removal Guide
- Scientific publication venues for ledger science
- The design of a trustworthy ecosystem around media sharing
- Tribler Development Pointers

I think we should remove all but the following pages, i.e., keep:

- Home
- Anonymous Downloading and Streaming specifications
- Hidden Services Specifications for anonymous seeding
- MasterThesis

@synctext I think the only controversial removals are "Scientific publication venues for ledger science" and "Related Research Groups". However, these pages are no longer maintained so I think they can go too. Do you agree, or, do you want to start maintaining them (either personally or by proxy)?

**Comment by synctext** [comment]
Please remove all information which is outdated. Scientific venues and related group are [semi-actively maintained by me since 2018](https://github.com/Tribler/tribler/wiki/Scientific-publication-venues-for-ledger-science/_history?page=3).

**Comment by qstokkink** [comment]
Alright, we'll keep the following then:

 - Home
 - Anonymous Downloading and Streaming specifications
 - Hidden Services Specifications for anonymous seeding
 - MasterThesis
 - Scientific publication venues for ledger science
 - Related Research Groups
 - The design of a trustworthy ecosystem around media sharing

**Comment by qstokkink** [comment]
Alright, the pages have been culled. Now for the updates.

**Comment by qstokkink** [comment]
I updated the remaining pages to reflect the current state of Tribler. With that, this issue should be solved.

**Comment by synctext** [comment]
```641 deletions``` [Historical wiki info is still here](https://github.com/Tribler/tribler/wiki/_compare/f36e46bad3bc6ffcef36a9c3a00cadf111f93174...cf56d5e7b0465ddd26cbd7456e6deb40167748e6)
