### ISSUE TITLE
Unicode error in the gui

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4934]
Latest 7.4.0exp1-64 on Windows10. 

GUI log:

```python
ERROR   1571685427.33            tribler_window:73   (root)  Traceback (most recent call last):
  File "run_tribler.py", line 130, in <module>
  File "TriblerGUI\tribler_app.py", line 34, in parse_sys_args
  File "lib\encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd1 in position 33: invalid continuation byte
```

**Comment by qstokkink** [comment]
What branch is the `7.4.0exp1` release on? If I go to the tag, this is line 34:

https://github.com/Tribler/tribler/blob/dcea801c7509734d74736054c9aad92240156504/TriblerGUI/tribler_app.py#L34

The stacktrace suggests that this line is the offending line though (and an invalid utf-8 encoded arg was passed):
https://github.com/Tribler/tribler/blob/release-7.4.0/TriblerGUI/tribler_app.py#L40

Was `7.4.0exp1-64` compiled wrong?

**Comment by qstokkink** [comment]
@ichorid could you double check if you are really using `7.4.0exp1`?
Assuming you are, we should then double check the build process: we seem to be shipping wrong code.

**Comment by ichorid** [comment]
@qstokkink , you're right, this error is from the older part of the log :face_with_head_bandage: 
Closing this.
