### ISSUE TITLE
Can't find pygtgraph on ubuntu 19.10 amd64

### ISSUE THREAD

**Issue by mkg20001** [Tribler/tribler#4936]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
master dcea801c7509734d74736054c9aad92240156504

##### Operating system and version: #####
ubuntu 19.10 amd64

##### Steps to reproduce the behavior: #####
Start the app

##### Expected behavior: #####
It starts

##### Actual behavior: #####
It tells me it can't find pygtgraph

Oddly enough it's already installed

```console
$ sudo pip3 install pyqtgraph 
Requirement already satisfied: pyqtgraph in /usr/lib/python3/dist-packages (0.11.0.dev0)
```

##### Relevant log file output: #####
```
********************************************************************************
Dependencies missing!
********************************************************************************
Tribler -  found missing dependencies in both!
Please install the following dependencies to continue:
 
 pip3 install pyqtgraph 


********************************************************************************
```

**Comment by xoriole** [comment]
Thank you for the report. For some reason, Tribler is not able to find pyqtgraph even though it seems the dependency is already installed. I'll try to reproduce the issue and update based on the findings.

**Comment by xoriole** [comment]
I can reproduce the issue. A different version of `pyqtgraph` is installed when installing through `apt` in Ubuntu 19.10. Expected version to be installed is `0.10.0` while `0.11.0.dev0` is actually installed. Checking the package available for Ubuntu 19.10, it seems `0.10.0`  should be the correct one.
https://pkgs.org/download/python3-pyqtgraph
weird!

**Comment by xoriole** [comment]
As a temporary fix, I'll put pyqtgraph as a pip dependency instead of using debian package `python3-pyqtgraph`, hot patch the release deb file.

**Comment by mkg20001** [comment]
@xoriole Installation could possibly fail via pip3 since it's already installed via apt, so possibly just add "conflicts: pyqtgraph==0.11.0dev0" to the deb?

**Comment by xoriole** [comment]
@mkg20001 Thank you for the suggestion. In the PR I removed pyqtgraph as apt dependency and added as a pip dependency so conflict statement is likely not necessary. 

Here is a build with the merged PR, would you like to try?
https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Py3-Build-Ubuntu64/35/

**Comment by mkg20001** [comment]
> In the PR I removed pyqtgraph as apt dependency and added as a pip dependency so conflict statement is likely not necessary.

Unsure if apt autoremoves it. Conflict would force it. Also, app won't work if another app depends on (the dev version of) pyqtgraph.

**Comment by mkg20001** [comment]
```
Requirement already up-to-date: pyqtgraph in /usr/lib/python3/dist-packages (0.11.0.dev0)
```

> Unsure if apt autoremoves it.

Exactly that. It didn't.

**Comment by xoriole** [comment]
Could you try to remove it individually and reinstall Tribler again? something like this:
```
sudo apt remove python3-pyqtgraph
sudo apt install ./tribler_*.deb
```

**Comment by mkg20001** [comment]
Now it works

> Also, app won't work if another app depends on (the dev version of) pyqtgraph.

Just that would be causing troubles for all folks using ubuntu 19.10
