### ISSUE TITLE
Interface is not simple to use. Needs better ease-ability

### ISSUE THREAD

**Issue by zS3mNH2** [Tribler/tribler#4947]
I am using 7.2.2 because 7.3 is broken in content discovery. I am finding the interface almost impossible to use. For example, clicking on a collection shows a screen that says it must be "subscribed" to to see the full content.

How am I supposed to subscribe? There are random icons everywhere such as a heart, a pair of tools crossing each other, etc. What do those things do? I have no idea because the interface is impossible to use!

At a minimum every icon should have a tooltip that explains what it does. My guess is the "heart" is some kind of subscribe toggle. The other tool icon I have no idea. Truth is it is impossible to know because there is no tooltip, so as a user I am left clicking around randomly and hoping clicking does something useful

**Comment by xoriole** [comment]
@zS3mNH2 Thank you for the feedback. UI refactor/redesign is a discussed topic but hasn't got the priority because of other issues. We welcome your feedback and if you have more feedback on the UI, please feel free to post it here or in the forum.

**Comment by ichorid** [comment]
@zS3mNH2 , yep, more feedback is always good! Especially in case of UI/UX, because our developers are CS scholars, not the GUI specialists!

Please, point out your suggestions on how the interface should look like and function. Prefereably, with examples.

**Comment by synctext** [comment]
great feedback! We do not even have a "subscribe" button. Thnx
