### ISSUE TITLE
Cannot share when adding tribler created torrent to my share

### ISSUE THREAD

**Issue by Druzle** [Tribler/tribler#4954]
#### Please, fill all relevant items: ####

- [x ] I have read CONTRIBUTING.rst

- [x ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Tribler 7.3.2
##### Operating system and version: #####
Windows 10 pro
Version 1903
OS Build 18362.476
System Type 64 bit
Installed Ram 16.0 GB
Processor Intel(R) Core(TM) I7-7700K CPU @ 4.20GHz

##### Steps to reproduce the behavior: #####
1. Create torrent from file
2. Add Created torrent into my Channel

##### Expected behavior: #####
The Torrent is shared in my Channel and upload/ Download/ Ratio/Peers and seeders are shown correctly
##### Actual behavior: #####
The torrent appears not to be shared. 
The seeders indicator does show seeders after a while
The peers indicator does show peers after a while.
The upload and download indicators always show 0
The ratio always shows (0)
clicking the download button again from MY Channel causes the torrent to reset to 0% in the downloads screen and never downloads.

**Comment by ichorid** [comment]
Thanks for reporting! I was able to reproduce the "0% after clicking download" problem. That is definitely a bug! However, other points are not clear. What did you mean by "the torrent appears not to be shared"? How could you tell if it is shared or not? How it is different from other torrents that **are** shared?
We're really interested in our users' opinion about the Channels look, as we're actively redesigning it now.

**Comment by Druzle** [comment]
What did you mean by "the torrent appears not to be shared"? How could you tell if it is shared or not? How it is different from other torrents that are shared?

Clicking on the generated torrent from the download list I look at the details section and see that the availability is 0 (even after 4 days). below is what i see in the under panel after clicking on the generated torrent in the download list. 

Info Hash of generated file.
577c614fce702fbf41ffd6a47ac9fc3d5d79b72f

After adding the generated torrent to MY CHANNEL and then clicking on the download icon the following occurs.

1. The download appears in the download list
2. Peers start to appear in the peers column
3. No seeds appear in the Seeds column (although i am seeding)
4. No upload speed is recorded in the upload column
5. No Download speed is recorded in the download column
6. No ratio is recorded in the Ratio column

Clicking on the torrent and looking at the DETAILS in the under panel shows.
Name:          Correct
Status:          Downloading
Filesize:         30.3GB in 0 files. (Incorrect there are 74 files spread across 7 directories.)
Health:          Seeds 0, leeches correct with download panel 
Infohash:       Is displayed
Destination:  is correct to what i set tribler to be
Ratio:             0 up: 469KB, Down 26KB (This is after 4 days and trying to download myself)
Availability:    0.00 (Although I am the seed)

Clicking on the FILES tab in the under panel shows the files listed correctly

Clicking the TRACKERS tab shows
[DHT] Working
[PEX] Working
Peers 0 (on both DHT and PEX)

clicking on the PEERS tab shows no results in any of the columns.

I deliberately chose a file set of large size and directory complexity.

I hope this helps.

**Comment by ichorid** [comment]
Thanks for the comment, the problem becomes clear now.

**Comment by ichorid** [comment]
torrent-replacing problem fixed in #4969. The GUI problem is discussed in #4968
