### ISSUE TITLE
[py3, 7.4.0]: Non-Latin filenames displayed wrongly

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4958]
Continued from #4957 

Py3, Linux, 7.4.0: download a torrent with files that have non-Latin characters and observe them appear garbled, like this:
![p3-7 4](https://user-images.githubusercontent.com/2509103/69245920-0dabde00-0ba8-11ea-9338-73df9c22b4bd.png)

**Comment by qstokkink** [comment]
Looks like a `str()` "cast" of a `bytes` object.

**Comment by ichorid** [comment]
Fixed in #4966
