### ISSUE TITLE
Conversion of downloads 7.3.2 -> 7.4.0 is broken

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4959]
Steps to reproduce:
(Linux) download a torrent in 7.3.2 (py2), then fire up 7.4.0 (py3). All the downloads will be gone.
```
ERROR   1574258838.18    LibtorrentDownloadImpl:801  (LibtorrentDownloadImpl)  Resume data failed to save: <class 'Tribler.Core.exceptions.SaveResumeDataError'>: torrent has no metadata
```

**Comment by xoriole** [comment]
I just checked the conversion. Indeed, it is broken. Only the bootstrap `.state` file is converted to `.conf` file and the rest `.state` files are not converted.

**Comment by xoriole** [comment]
It is an issue with converting the config. It should be using `.Tribler` state directory instead of the versioned state directory (eg. `.Tribler/7.4.0/exp1`). I have a fix here https://github.com/Tribler/tribler/pull/4960
