### ISSUE TITLE
Seeded torrents status should be indicated in Channels GUI

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4968]
Continued from #4954 

If a torrent is already downloaded, it's status should be indicated in the Channels GUI. Otherwise, situations like "I created a torrent, and then tried to download it from my channel" can arise.
Personally created torrents should be indicated in a special way because their seeds number can be misleading.

**Comment by devos50** [comment]
@ichorid I suppose this will go to 7.6?

**Comment by ichorid** [comment]
Solved already
