### ISSUE TITLE
Downloads always start in VOD mode

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4987]
Every download seems to start in VOD mode. This is reflected in the log, and can be seen as well in the download pieces map prioritizing the beginning of the torrent. This reduces download performance.

Instead, VOD should be used **only** if the user clicked the "Play" button.

```python
INFO    1575206079.86             LibtorrentMgr:671  (LibtorrentMgr)  start_download: Starting in VOD mode
```

**Comment by egbertbouman** [comment]
Could just be a bad log statement. This mode is set [here](https://github.com/Tribler/tribler/blob/release-7.4.0/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py#L312).

**Comment by devos50** [comment]
This is indeed a very misleading logging statement. IIRC, the VOD state is set to `False` again shortly after initializing the download. Apparently, no one cared enough to fix this statement/behavior 😄

**Comment by ichorid** [comment]
I've checked the download mode selector, it works as it should, except for the logging statement...
