### ISSUE TITLE
Secret key / rng storage question

### ISSUE THREAD

**Issue by rahulsharma311** [Tribler/tribler#4998]
#### Please, fill all relevant items: ####

- [ ] I have read CONTRIBUTING.rst

- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

how the secret key is stored inside the sram storage and also the seed for the random number? Is the secret key ever stored inside the sram puf or is it generated everytime we need to encrypt something?

**Comment by devos50** [comment]
I'm not sure if your question is entirely clear to me. Throughout the application, we have various use-cases where we encrypt/decrypt content or create digital signature to ensure the authenticity of data (e.g., TrustChain blocks). For that, we use the [libsodium](https://libsodium.gitbook.io/doc/) library.

**Comment by ichorid** [comment]
The random generator is seeded from system random device, as per Python best practices (we leave it to python). The secret key is stored on disk in a plaintext file. It is only read once when Tribler starts.

**Comment by ichorid** [comment]
No PUF is used in Tribler, at the moment.
@rahulsharma311 , if you have more questions, feel free to reopen the issue.

**Comment by synctext** [comment]
PUF is a separate student project. private key is not stored anywhere! very unique property, generated from physical properties everytime when needed.
