### ISSUE TITLE
Rewarding good behavior

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#5]
Determine the contributions of peers using our blockchain.

Track freeriders using MultiChain, compatible with anonymous seeding, relaying, and downloading mode.

Goal: superior performance compared to tit-for-tat, reduce freeriding and promote cooperation.
usage: accounting of bytes for seeding and Proxy bandwidth donations
Security: Sybil attack hardened, misreporting, lying, cheating, white washing and spoofing-proof.

_Previously: Vlad thesis project, now Ewout!_

**Comment by VoR0220** [comment]
Hi synctext. I'm interested in learning more about what you learned from doing proportional bandwidth sharing. Where can I look to learn? Thanks in advance.

**Comment by synctext** [comment]
@VoR0220 The final thesis report and overview can be found here:
https://github.com/Tribler/tribler/wiki/BarterCast3

But: the key lesson is don't try this (not in report). Better approach is to deny service if a user is below "freerider level" and just let all the non-freerider sharing according to network conditions.

**Comment by VoR0220** [comment]
Thanks a ton @synctext  I can't wait to read what you found and learn from you :)

**Comment by synctext** [comment]
[Incentives and Prosocial Behavior]
(http://psydok.psycharchives.de/jspui/bitstream/20.500.11780/1104/1/dp1695.pdf) good work with 1800 cites

**Comment by synctext** [comment]
Closing this ticket and work moves to "strongest possible reputation system" #31 
plus #2571
