### ISSUE TITLE
Can't delete/download chanel while processing a channel torrent 

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5009]
The problem is in current `devel`. After `asyncio` refactoring, GigaChannel Manager can't simultaneously process a channel torrent and manage (download/delete) other channel torrents. This happens because of the asyncio PR making all calls in `service_channel` method `await` on their execution, and the looping call itself blocking on finishing the previous iteration.
To fix this we should either make the calls non-`await` again (to make them run in parallel) or create a separate per-channel queue of events.

**Comment by Solomon1732** [comment]
What was the reason(s) the calls were refractored to use `await`?

**Comment by ichorid** [comment]
@Solomon1732 , see https://github.com/Tribler/tribler/issues/4646

**Comment by ichorid** [comment]
And then @egbertbouman accidentally converted the calls to asynchronous over the course of refactoring. I guess, he did it just in case, for safety reasons. Nothing ruins your debug session like a non-`await`ed asynchronous call...

**Comment by egbertbouman** [comment]
Luckily, we can easily solve this by registering the `check_channels_updates`/`process_queued_channels` calls using the `TaskManager`. However, before doing so I would like to make some small changes to the `TaskManager` in IPv8.

**Comment by ichorid** [comment]
@egbertbouman , thanks for https://github.com/Tribler/py-ipv8/pull/637 . That should make the fix a bit prettier.
