### ISSUE TITLE
Ship SQLite DBs with channel data in channel torrents

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5010]
Currently, we store channel data as serialized entries in lz4-compressed binary blobs. This is very efficient in terms of bandwidth but produces almost 10x write amplification when stored on disk when used with small updates to channels. The problem is, a typical channel entry `.mdblob.lz4`  is smaller than the filesystem block size, and most filesystems can't handle that efficiently.
Also, the procedure of integrating the channel data into the user's PonyORM-managed SQLite DB is very slow because it runs a lot of checks in Python for every entry. That is mandatory for data coming from the network but inefficient for bulk upload from torrent-based channels.

Instead, we can store channels data in a small SQLite DB shared in the channel torrent. With the help of `ATTACH` command, `UPSERT` procedure, and some clever SQL queries, this will allow us to process the channel completely in SQLite without involving Python interpreter at all, possibly in a separate thread. The speedup of channel processing should be around 10-100 times. This change will not break the compatibility with 7.3-7.4 clients, as we will continue to ship channel updates in the old format alongside the new one.

**Comment by viric** [comment]
I gues that there could be specific code that can build that particular sqlite table quickly, instead of transferring the sqlite table. Currently the creation of the table is mixed with the rest of tribler disk data structures, and that's very slow.

**Comment by ichorid** [comment]
I recommend you look at [this post](https://github.com/Tribler/tribler/issues/3615#issuecomment-651091413) for details of potential problems and design space for Channels DB.

**Comment by ichorid** [comment]
SQLite supports merge-like functionality to store, apply and combine DB diffs through its [Session Extension](https://sqlite.org/sessionintro.html). This is worth investigating.

**Comment by ichorid** [comment]
According to @kozlovsky , shipping databases opens an opportunity for code injection. So, closing this one.
