### ISSUE TITLE
Provide precompiled libtorrent binaries for development

### ISSUE THREAD

**Issue by Solomon1732** [Tribler/tribler#5020]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Devel
##### Operating system and version: #####
Windows
##### Expected behavior: #####
Libtorrent binaries provided in ready form
##### Actual behavior: #####
Libtorrent binaries have to be downloaded and compiled. This is a non-trivial task on windows, especially since the information provided on https://libtorrent.org/python_binding.html is somewhat outdated.

In addition, the python bindings on pypi (can be seen [here](https://pypi.org/project/python-libtorrent/)) do not provide any downloadable distributional package. It is a known issue:
https://stackoverflow.com/questions/39069168/pip-install-python-libtorrent-1-1-0-fails-on-linux
https://pypi.org/project/python-libtorrent/
For the maintainer it seems like it's not a priority:
https://github.com/arvidn/libtorrent/issues/319

Opening issue here since it was recommended by @ichorid in #5018 in [this](https://github.com/Tribler/tribler/pull/5018#issuecomment-568806409) comment

**Comment by drew2a** [comment]
It seems not relevant anymore as Tribler uses 
https://github.com/Tribler/tribler/blob/035bab82fdf863bff8d1ea81c30dbdc4aeabb3d1/requirements-core.txt#L22

as a dependency.
