### ISSUE TITLE
Refractor util.py

### ISSUE THREAD

**Issue by Solomon1732** [Tribler/tribler#5022]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
devel
##### Expected behavior: #####
Change assigned lambda into a function. Also drop support for python 2.
##### Actual behavior: #####
Code assigns a lambda -- an anonymous function -- is assigned to a variable, thus making the whole point of it being a lambda moot. In addition, it supports python 2, which is a version that the codebase, afaik, seeks to stop supporting in favor of python 3

https://github.com/Tribler/tribler/blob/devel/Tribler/util.py

**Comment by Solomon1732** [comment]
I'm willing to PR it 😄 It doesn't look super complex.

**Comment by Solomon1732** [comment]
If I PR this, to which branch should it go to? `devel`?

**Comment by devos50** [comment]
Yes, devel please
