### ISSUE TITLE
Clean up path_util compatibility wrapper

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5030]
[Moving](https://github.com/Tribler/tribler/pull/5025) to `Pathlib` required creating a compatibility wrapper module `path_util` implementing some `os.path`-like functions. Cleaning it up will make the code cleaner and will reduce the probability of masking path-handling errors.

So, everyone is welcome to try removing `path_util.*` lines from the code and replace them with proper Pathlib methods!

**Comment by Solomon1732** [comment]
I'm willing to tackle it

**Comment by Solomon1732** [comment]
There is a reference in the code to a `path_util.splitdrive` function which I can't find anywhere. What should I use instead?
https://github.com/Tribler/tribler/blob/bcf03e0ea696ce0c704426a5b4120bc5c675d6de/src/tribler-core/tribler_core/utilities/osutils.py#L122

**Comment by Solomon1732** [comment]
Can I get unassigned from this bug report? This is getting too much for me.

**Comment by devos50** [comment]
Note that I did some work on this in #5573. This migration is not completely finished though.

**Comment by devos50** [comment]
The `fix_win_long_file` method in our wrapper should probably be preserved since we are using that in a few locations.

**Comment by qstokkink** [comment]
It seems like this has now been sufficiently addressed.
