### ISSUE TITLE
Post-renaming issues

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5035]
Stuff to do after adopting new dirs structure #5032 

- [x]  Jenkins MacOS tester script
- [x]  Jenkins Linux tester script
- [x]  Jenkins Win64 tester script
- [x]  Coverage
- [x]  Pylint
- [x]  Sonar cloud
- [x]  PyInstaller script
- [x]  MacOS builder
- [x]  Windows builder
- [x]  Debian builder
- [x] Snap package
- [x] Github PR checklist
- [x] Application tester (Async IO) (by Martijn)
- [ ] Run app test please (command for jenkins)
- [x] 7.5.0-exp1 (Deadline: 31st January, 2020)
- [ ] Contributing.rst (by Vadim)
- [x] Fix logger.conf

Migrate to Python 3:
- [x] bootstrap servers
- [x] tunnel helpers (depends on #5060)
- [x] TrustChain crawler
- [ ] statistics crawler
- [x] [the tester against various versions of libtorrent](https://jenkins-ci.tribler.org/job/validation_experiments/job/validation_experiment_libtorrent_compatibility/)
- [x] PR new import checker
- [x] PR print statements checker

**Comment by devos50** [comment]
The `Test_tribler_devel` job (see [here](https://jenkins-ci.tribler.org/job/Test_tribler_devel/83/console)) is currently broken. You could start with fixing that one?

**Comment by vandenheuvel** [comment]
I can't call `python src/run_tribler` without:
```git
diff --git a/src/run_tribler.py b/src/run_tribler.py
index fd717cd63..0e78701b6 100644
--- a/src/run_tribler.py
+++ b/src/run_tribler.py
@@ -4,6 +4,7 @@ import signal
 import sys
 from asyncio import ensure_future, get_event_loop
 
+sys.path.append("src/tribler-core")
 from tribler_core.dependencies import check_for_missing_dependencies
 
 # https://github.com/Tribler/tribler/issues/3702
```

**Comment by ichorid** [comment]
You must call it like this now:
(provided you're in the Tribler repo directory)
`env PYTHONPATH=src/tribler-core:src/tribler-gui:src/tribler-common:src/anydex:src/pyipv8 python3 src/run_tribler.py`

Alternatively, if you use PyCharm, you can mark the abovementioned directories as source.

**Comment by Solomon1732** [comment]
I wrote about it in #1728 , but I guess it also belongs to here: pylint seems to be oriented towards python 2, rather than 3. in PRs it keeps detecting stuff like old-style class declarations (gone from python 3, which has only the new style ones), f-strings as invalid syntax, etc.
https://github.com/Tribler/tribler/issues/1728#issuecomment-573073378

**Comment by vandenheuvel** [comment]
@ichorid thanks, that helped. I also needed to mark the anydex and ipv8 folders as source folders. Perhaps this could be included in the dev on linux guide.

**Comment by devos50** [comment]
I just added a few more items that require migration to Python 3.

**Comment by devos50** [comment]
Just upgraded all bootstrap servers to the latest IPv8 commit 👍 . The [Jenkins job](https://jenkins-ci.tribler.org/job/Test_BootstrapServers/) seems to still work and I'm still able to discover peers in Tribler.

**Comment by devos50** [comment]
See https://github.com/Tribler/application-tester/pull/23 for an ongoing port of the application tester to `asyncio` (just need to test it).

**Comment by devos50** [comment]
I just updated the application tester and the environments on our deployment tester (removed Python 2.7 and installed Python 3 instead). The pipeline when building Tribler seems to pass now, see [here](https://jenkins-ci.tribler.org/job/Async-Release-Py3/11/).

**Comment by devos50** [comment]
All [validation experiments on Jenkins](https://jenkins-ci.tribler.org/job/validation_experiments/) have been upgraded to Python 3 and Asyncio 👍

**Comment by devos50** [comment]
I think this issue is sufficiently addressed, up to a point where we can make individual issues out of the remaining items in the list. I will do so in a moment.
