### ISSUE TITLE
Both win32api and xmessage not found

### ISSUE THREAD

**Issue by vandenheuvel** [Tribler/tribler#5040]
devel, bcf03e0ea696ce0c704426a5b4120bc5c675d6de
Arch, python 3.8.1

Install dependencies for Arch, create venv, activate, install dependencies for ipv8, install dependencies via pip, try to start tribler with `env PYTHONPATH=src/tribler-core:src/tribler-gui:src/tribler-common:src/anydex:src/pyipv8 python3 src/run_tribler.py`.
```
Traceback (most recent call last):
  File "/home/bram/git/tribler/src/tribler-core/tribler_core/dependencies.py", line 40, in _show_system_popup
    import win32api
ModuleNotFoundError: No module named 'win32api'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/run_tribler.py", line 101, in <module>
    check_for_missing_dependencies(scope='both')
  File "/home/bram/git/tribler/src/tribler-core/tribler_core/dependencies.py", line 71, in check_for_missing_dependencies
    _show_system_popup("Dependencies missing!",
  File "/home/bram/git/tribler/src/tribler-core/tribler_core/dependencies.py", line 44, in _show_system_popup
    subprocess.Popen(['xmessage', '-center', text], shell=False)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xmessage'
```

**Comment by vandenheuvel** [comment]
Note that installing `pywin32` via pip doesn't work:
```
ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32
```

**Comment by qstokkink** [comment]
https://github.com/Tribler/tribler/blob/e891497e7fbe5ec01259ca77a5b75f576f7b3eff/src/tribler-core/tribler_core/dependencies.py#L39-L46

What it's supposed to do:
1. The fact that Arch isn't Windows is fine.
2. In case the platform is not Windows, we attempt to use `xmessage`.
3. Just in case all else fails, we print to the `stderr`

Solution to this issue:

The `xmessage` subprocess call should also be in a `try .. except.`

**Comment by xoriole** [comment]
I agree with @qstokkink.  The `xmessage` subprocess call should also be in a `try .. except.`
@vandenheuvel you could print `text` and`title` args to the method to see what was the missing dependency.

**Comment by devos50** [comment]
I'm closing this issue since we don't really have the time and resources to support archlinux.
