### ISSUE TITLE
GUI fuzzing

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5042]
[Fuzzing](https://en.wikipedia.org/wiki/Fuzzing) is the most efficient method of testing complex GUIs. However, implementing one can be a tricky task, especially in the case of desktop applications that are written in more than one language and splitted into several parts (hello, Tribler, I'm looking at you!).

To implement fuzzing in Tribler, we'll need:
 * [a framework for Qt scripting](https://github.com/linotex/quelenium), or [a bridge](https://github.com/cisco-open-source/qtwebdriver) to [a popular GUI testing platform](https://en.wikipedia.org/wiki/Selenium_(software)).
 * a way to automatically build an FSM for the GUI.
 * a [library](https://en.wikipedia.org/wiki/American_fuzzy_lop_(fuzzer)) to fuzz and explore the GUI FSM.

Good read on the topic:
https://www.fuzzingbook.org/html/GUIFuzzer.html#

**Comment by synctext** [comment]
GUI testing is a part of [deployment testing](https://jenkins-ci.tribler.org/job/Deployment-Tests/)

**Comment by Dmole** [comment]
Qt LTS Releases To Be Restricted To Commercial Customers, Other Commercial Changes[[1]](https://www.phoronix.com/scan.php?page=news_item&px=Qt-Going-More-Commercial)...
So one might expect some fast version hopping.

**Comment by synctext** [comment]
We're moving to a new GUI framework: The Web!
With Javascript React framework we've seen it all. Just to document:
- WxWindows (2005)
- QT
- HTML web control
- Javascript React

Fuzzing would be an awesome quality assurance feature to have! However, it's not that realistic given the level of resourcing we have. First we need to get that million users with what we have.
