### ISSUE TITLE
Wrong variable passed to function

### ISSUE THREAD

**Issue by Solomon1732** [Tribler/tribler#5050]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
devel
##### Operating system and version: #####
All
##### Expected behavior: #####
`fileindex` should be passed into a function.
##### Actual behavior: #####
`filename` is passed into the function.

https://github.com/Tribler/tribler/pull/5043#issuecomment-572079210
https://github.com/Tribler/tribler/blob/devel/src/tribler-core/tribler_core/modules/libtorrent/download_config.py#L132
https://github.com/Tribler/tribler/blob/devel/src/tribler-core/tribler_core/modules/video_server.py#L156

**Comment by ichorid** [comment]
How can it be that when `filename` is passed into the function the thing does not crash? Or why the test does not fail?

**Comment by Solomon1732** [comment]
The function doesn't check the type that is passed in it. All it does is this
```python
def set_selected_files(self, file_indexes):
    """ Select which files in the torrent to download.
    @param file_indexes List of file indexes as ordered in the torrent (e.g. [0,1])
    """
    if self.get_mode() == DLMODE_VOD and len(file_indexes) > 1:
        raise ValueError("In Video-On-Demand mode only 1 file can be selected for download")
     self.config['download_defaults']['selected_file_indexes'] = file_indexes
```
Which does not check the type of the list (or object, rather) that's passed into it. It fails other tests much later -- the tests for `VODFile`, specifically in this code segment:
```python

@check_handle(0)
def get_vod_filesize(self):
    fileindex = self.get_vod_fileindex()
    torrent_info = get_info_from_handle(self.handle)
    # Tests fail here
    if fileindex >= 0 and torrent_info:
        file_entry = torrent_info.file_at(fileindex)
        return file_entry.size
    return 0
```
Since `VODFile` uses `DownloadConfig`, and uses the file index functionality, it raises an error during its tests.

**Comment by Solomon1732** [comment]
The only test which checks that it fails for passing the wrong type of list fails for another reason entirely: the list's length, rather than the type of arguments passed
https://github.com/Tribler/tribler/blob/bcf03e0ea696ce0c704426a5b4120bc5c675d6de/src/tribler-core/tribler_core/modules/libtorrent/tests/test_downloadconfig.py#L46
```python
@raises(ValueError)
def test_downloadconfig_set_vod_multiple_files(self):
    dlcfg = DownloadConfig()
    dlcfg.set_mode(DLMODE_VOD)
    dlcfg.set_selected_files(["foo.txt", "bar.txt"])
```

**Comment by ichorid** [comment]
So, this problem applies only to VOD mode and its tests, right?

**Comment by Solomon1732** [comment]
As far as I can tell, yes.
