### ISSUE TITLE
Unused index from `enumerate`

### ISSUE THREAD

**Issue by Solomon1732** [Tribler/tribler#5061]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
`devel`
##### Expected behavior: #####
Use the index value from `enumerate` or directly iterate the object.
##### Actual behavior: #####
Use of `enumerate` without using the `index` value.
```python
async def load_checkpoints(self):
    for i, filename in enumerate(self.get_checkpoint_dir().glob('*.conf')):
        self.load_checkpoint(filename)
        await sleep(.01)
```

https://github.com/Tribler/tribler/blob/devel/src/tribler-core/tribler_core/modules/libtorrent/libtorrent_mgr.py#L730

**Comment by devos50** [comment]
@Solomon1732 you want to address this issue?

**Comment by Solomon1732** [comment]
Sure 😄
