### ISSUE TITLE
Temporarily skipped tests

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5065]
In #5059, I disabled various tests to ensure that the PR testers are passing. From now on, I propose to ensure that the testers are passing before merging new PRs.

To fix:
- [x] (Mac) anon download test
- [x] (Mac) hidden seeding test
- [x] (Windows) anon download test
- [x] (Windows) hidden seeding test
- [ ] (Windows) (big) channel download test

**Comment by synctext** [comment]
Excellent point.

**Comment by devos50** [comment]
@ichorid could you prioritize fixing the channel download test on Windows, so we can close this issue?

**Comment by devos50** [comment]
This should be fixed by #5094
