### ISSUE TITLE
home screen recommended for you suggests adult content

### ISSUE THREAD

**Issue by py563** [Tribler/tribler#5071]
##### Tribler version/branch+revision: #####
latest from website
##### Operating system and version: #####
Windows 10 Build 19451

##### Steps to reproduce the behavior: #####
I opened after few days tribler to download linux distro from torrent and i see all porn torrent. I have only used to download a kali linux image using tribler then how come my recommendations are those when i haven't watched any porn in my laptop

##### Expected behavior: #####
maybe something based on my downloads

one question how does recommendations work actually, i just downloaded tribler two weeks back.

**Comment by devos50** [comment]
Adult content should be filtered out and not displayed to users if the family filter is enabled (which is the default behavior). This could either be that the specific content is not catched by our family filter, or it could be a bug when loading the front page items.

> one question how does recommendations work actually

Currently, it just fetches random torrents from the backend. A more sophisticated recommendation engine is something we might implement in the future.

**Comment by py563** [comment]
here is an image of my home screen

![2020-01-25](https://user-images.githubusercontent.com/6139284/73123588-9cc5df80-3fb7-11ea-99c2-e00e6b202369.png)

thanks @devos50 for changing title i kept on wondering what should i write for that word

**Comment by ichorid** [comment]
We're probaly going to remove the thing altogether and replace it with "Discovered" screen.

**Comment by ichorid** [comment]
Closed by removing the Home screen altogether.
