### ISSUE TITLE
[7.4.0] Torrent checker uses DHT directly

### ISSUE THREAD

**Issue by meilamodr** [Tribler/tribler#5103]
I didn't tick off "Allow Tribler as exit node" option but I just wanted to check if Tribler works well, so I visited iknowwhatyoudownload site. But iknowwhatyoudownload site alleges that I downloaded some files I didn't actually download.

I used Tribler on Linux. Ubuntu 19.10 Eoan Ermine. However it is rather horrifying that it could be possible that Tribler could work as an exit node even though I turned off "working as an exit node".

I don't know whether it is bug, or is it normal that there can be some files that site can allege I downloaded it even though I didn't download?

If it is a bug, i hope it fixed soon.

Below are lists of files that site allges I downloaded them. I didn't download all of them.

![fsdffdsfdsfdsdfsfdsfdsdsffdsdfs](https://user-images.githubusercontent.com/60726025/73906752-53469000-48e7-11ea-9095-b0bba5836895.jpg)

**Comment by devos50** [comment]
I am pretty sure that by default, Tribler does not act as an exit node. To confirm this, you could check if there are any enabled exit sockets running on your computer. To do so, please go to the settings panel -> debug and check 'Enable developer mode'. Now you will see a 'Debug' tab in the left menu. Click on that and go to Tunnels -> exit sockets. You should not see any enabled exit sockets here.

Could it be that your IP adres is used by multiple machines in the same internal network? The content you posted in the screenshot could have been downloaded by others.

**Comment by meilamodr** [comment]
> I am pretty sure that by default, Tribler does not act as an exit node. To confirm this, you could check if there are any enabled exit sockets running on your computer. To do so, please go to the settings panel -> debug and check 'Enable developer mode'. Now you will see a 'Debug' tab in the left menu. Click on that and go to Tunnels -> exit sockets. You should not see any enabled exit sockets here.
> 
> Could it be that your IP adres is used by multiple machines in the same internal network? The content you posted in the screenshot could have been downloaded by others.

I thought those possibilities. Yes, Tribler does not act as an exit node. The reason why I wrote this is that I did those things

I checked if "Tribler as exit node" was checked, and it wasn't checked, and then I also checked other computers but on other computers Tribler is only torrent client which installed except computers run Linux, torrent clients is pre-installed but I haven't used those clients since installation of Linux, and there is noone who download torrents without me.

After, I checked If someone using my router but noone used my router. I checked that several times.

Even though, I removed Tribler, I install Tribler, and use debug menu to check it.

**Comment by devos50** [comment]
Another consideration is that each peer in the Tribler network by default *relays* traffic for others (this is how you earn bandwidth tokens). This traffic, however, is encrypted and cannot be inspected by others. Furthermore, this encrypted data stream flows separately from the BitTorrent network so I highly doubt that a website like iknowwhatyoudownload is able to see this data.

**Comment by qstokkink** [comment]
I assume this is the TorrentChecker randomly checking the health of torrents (which are being gossipped around) and _false positives_ from iknowwhatyoudownload.

You could verify this by going to your discovered channels and selecting a lot of torrents in your discovered channels. Tribler will then check the health of these torrents by asking the trackers for the peer counts (the green/red orbs next to the amount of seeders and leechers in a torrent swarm). iknowwhatyoudownload should then explode with all sorts of torrents you "downloaded".

**Comment by devos50** [comment]
> I assume this is the TorrentChecker randomly checking the health of torrents (which are being gossipped around) and false positives from iknowwhatyoudownload.

Good point, forgot about that one. When checking the health of an individual torrent, you actually join the swarm for a brief moment, to download the torrent metadata.

Actually, BEP33 health checking avoids joining the swarm, which is an inaccurate way of estimating the torrent health anyway. However, BEP33 support got dropped after the move to Python 3. Hopefully we can bring it back soon.

**Comment by egbertbouman** [comment]
This should be fixed in Tribler 7.5 (our devel branch), which ensures that torrent health request are also tunneled. Unfortunately, this didn't make it's way into 7.4.

**Comment by meilamodr** [comment]
I turned on debug, and I checked if there was an enabled exit socket several minutes. There was no enabled exit socket. It can be torrent health checking problem as qstokkink said. I don't know what caused this but I hope it fixed soon.

**Comment by ichorid** [comment]
This is definitely TorrentChecker's activity. I've provided a [thorough explanation](https://forum.tribler.org/t/dht-based-download-scanners-vs-torrent-checker/5544) of the phenomena at our forum.

7.5 is moving all DHT checks to tunnels by default.
