### ISSUE TITLE
TypeError: unable to convert a QVariant back to a Python object

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5108]
At some circumstances, Qt cannot read the API key back from `Tribler.conf` file. In this case GUI refuses to run with `TypeError: unable to convert a QVariant back to a Python object` error. We must catch this error and re-generate the key.

**Comment by devos50** [comment]
@ichorid What's the status of this issue?

**Comment by ichorid** [comment]
This is still active. I hope to fix it sometime later in 7.5.x or 7.6

**Comment by devos50** [comment]
Fixed by #5283
