### ISSUE TITLE
PGP key expired

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5126]
From Tribler forum post:

> Ive been trying to look for the gpg release key so that i can verify the files downloaded. But the one listed in Github is expired since 2017.
I am extremely shocked the fact that no one else has even asked about this and that this key has not even been updated since 2017
pub rsa2048 2015-02-03 [SC] [expired: 2017-02-11]
1A83A9A76A516EE3FD7054F5F33BAE29011D6ABC
uid [ expired] Tribler release key
The only issue i found related to this is https://github.com/Tribler/tribler/issues/2257 2
Still i dont understand why something that is of major priority has been neglected like this. Unless im too blind to find it? (and why must i go searching for it on https://pgp.mit.edu ??) Please update your release key on Github and on your site.

**Comment by devos50** [comment]
In 2017, we switched the public key used to sign the builds. The new key, which we use since then is the following: `700924EB2BF09E54920751549DD1E058B9FCA9DC`. This one should be available in the MIT PGP Key server.

**Comment by jdsys271** [comment]
@devos50 ok can you please then update the release.key here https://github.com/Tribler/tribler/blob/devel/release_key.gpg ?  Since that one is the 2017 expired one.
The MIT PGP Key server is laggy and non-responsive most times.

**Comment by devos50** [comment]
See #5289
