### ISSUE TITLE
Please label Units

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#5130]
In the attached image one can't determine the units of the X axis.
Are they Planck times, attoseconds, clock cycles, galactic years?

![units](https://user-images.githubusercontent.com/1793802/74590851-5e34ab00-4fe0-11ea-98ef-987aac8886a4.png)

```
> date -I
2020-02-15
```
https://en.wikipedia.org/wiki/ISO_8601
https://xkcd.com/833/

**Comment by devos50** [comment]
This seems to be an issue when on a specific time scale, since zooming out more reveals the month: https://gyazo.com/cb280b962ca9e3b3530066c1f59e0ffc.

I will defer this issue to 7.6.

**Comment by drew2a** [comment]
It is not relevant anymore:
- #7761
- #7798
