### ISSUE TITLE
CPU load: spikes and minimised state;

### ISSUE THREAD

**Issue by irvnriir** [Tribler/tribler#5133]
### Operating system and version: ###

latest Stable Win10

### Expected behavior: ###

1. some other torrent Clients load the CPU on ~2-5% .

2. since Tribler doesn't minimize to Tray, its expected that it will run in background mode, when minimized to Taskbar .

### Actual behavior: ###

1. about each 10-30 seconds, for ~1s, Tribler doubles+ the default ~5% CPU load .

switching "Enable token mining", "Enable resource monitoring", "Enable developer mode" and anonymity at all downloads, seem to have no effect on the spikes and almost no on the load .

2. when minimized with Downloads screen open, it keeps the 18-25% load .

![piZiZ_CPU_XdownloadsWindow_minimizedXtribler](https://user-images.githubusercontent.com/13949704/74610444-61c15280-5104-11ea-9649-5410d1f33e7b.png)

### p.s. ###

i currently use some more pragmatic laptop than usual, but still want to seed some torrents (extended privacy not required), since the CPU has only 2 cores, the spikes are meaningful when i use some {graphical editing}/modeling software .

related: #2444, #2504 ;

**Comment by ichorid** [comment]
Hi!
Thanks for reporting. Could you please try this [7.5 pre-release build](https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Async-Py3-Build-Win64/22/artifact/tribler/dist/Tribler_7.5.0-alpha1_x64.exe) and see if spikes go away?

For 7.5, we're switching from Twisted asynchronous framework to Asyncio, that should help with performance and stability. Also, 7.5. adds Nested Channels support, alongside with much-needed SQLite indexes. Unfortunately, the code to add indexes to the old database scheme is not ready yet. So, to experience the effect of the indexes on this build's performance you'll have to delete your channels database. It is located at `.Tribler/7.*/sqlite/metadata.db`.

As usual with pre-releases, it is **strongly** advised to backup your `.Tribler` state dir before installing it.

**Comment by irvnriir** [comment]
@ichorid . all user-data got reset . after i set the downloads folder and imported the torrents, they started to re-download (instead of checking and seeding . so i can't even resume the torrents that was seeded mainly by me) . performance seem to become ~x2 better, but the Discovery started from 0, so not sure .

**Comment by ichorid** [comment]
Closing this for now.
