### ISSUE TITLE
Blockchain Engineering Class of 2020: Delft-DAO - Create your own currency (Team II)

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#5144]
### Delft-DAO
What is a DAO? Within the coming decade the future of jobs, employment and the nature of the firm will change profoundly. Automation, AI, and robots will replace many of today's jobs. A new type of company is a company without any employees, without any machines or physical infrastructure. A Decentralized Autonomous Organizations, DAO, only exists in software. It goes beyond smart contracts, it is a complete company inside software. DAO development is still in the experimental stage.

Within this course you can create your very own autonomous organisation, the Delft-DAO. Learn to engineer a decentralised autonomous organisation, use the existing tools, and understand the security risks. The aim is to alter the nature of the firm in the Internet age, [see the Nobel prize winning theory](https://en.wikipedia.org/wiki/The_Nature_of_the_Firm). Production cost become essentially cost-free. An organisation which exists purely in cyberspace. The Delft-DAO is designed to be the first sustainable DAO. How can we empower leaderless organizations? How can it earn money from manipulating bits? 

Advisor: J.A. Pouwelse, TUDelft blockchain lab founder (weekly meetings on Wednesdays)

Several teams from the class will create running code (requirements for a passing grade..) for one of the following functionalities. Four teams together create the building blocks of the complete Delft-DAO (time consuming integration step is outside our scope).

**Create your own currency** 
First step of building a DAO is creating money. This enables the Delft-DAO micro-economy. Mark Zuckerberg is creating his own currency for a few billion users, called "Facebook Libra". For this assignment you will also create your own currency in 10 weeks, almost from scratch! Obviously security and usability is somewhat limited. You will investigate methods for minting and transfer of tokens. You will designate yourself as "trusted nodes", able to generate cash. [Mandatory starting point for your code is this Kotlin app](https://github.com/Tribler/kotlin-ipv8)
  - create finite number of tokens by a central authority
  - encode in [Trustchain](https://py-ipv8.readthedocs.io/en/latest/further-reading/trustchain/)
  - transfer of tokens between two Android phones
  - wallet support and offline transfer
  - usable in the future as DAO ownership token or voting pass
  - align your work with the DAO voting team
  - _Bonus_: your currency is usable as a DAO token 

**Team II**

**Comment by synctext** [comment]
@invictusrmc @brian2509 @mkuijpers @pjvanderlaan
Welcome to the course!
Sprint proposal divided on team of 5 students :
- get familiar with [Trustchain concept read docs](https://github.com/Tribler/kotlin-ipv8/blob/master/doc/INDEX.md)
- get familiar with [existing app](https://github.com/Tribler/kotlin-ipv8)
- Real money handling:
  - find a library for Bitcoin ?in Kotlin?
  - show balance in the app
  - devise method to fill the wallet
- read about [creation of money](https://github.com/Tribler/tribler/issues/4629)
- read [about gossip-based AI](https://github.com/Tribler/distributed-ai-kernel)

**Comment by Bloodyfool** [comment]
Related:
 - Vitalik, founder of Ethereum, [has a talk](https://www.youtube.com/watch?v=6LbRtvdRVBw) about common pitfalls in decentralized governance, how to prevent oligarchies, and how to incentivise people from always voting for themselves. He had to solve this to make Proof of Stake work in Ethereum 2.0.
- [Kleros decentralised arbitration platform](https://kleros.io) is a system that settles legal disputes through community voting.
 - [Augur decentralised prediction markets](https://www.augur.net/) is a system that implements a prediction market on the blockchain. Prediction markets are a tool to have financial markets vote (bet) on future events in order to (hopefully) predict outcomes.

**Comment by MKuijpers** [comment]
We would like to tell what we have done last week and what questions we have for the current meeting.

Done this week:
- Research into the relevant literature from this issue
- Delve into the Kotlin app project
- Add a page in the app in order to get used to the app development. We added a simple page to add blocks with custom information to the trustchain. These messages are customizable from an interface in the app

Questions:
- What are the concrete deliverables of the project?
- What part does Bitcoin play in this project?

**Comment by PJvanderLaan** [comment]
This week's APK file

[demo-android-debug.apk.zip](https://github.com/Tribler/tribler/files/4275372/demo-android-debug.apk.zip)

**Comment by synctext** [comment]
Next sprint comments:
- no unit tests yet
- start putting pointers to related work in README.md documentation
- use real testnet Bitcoins please
  - transfer of tokens between two Android phones
  - generic coin handling
  - wallet support and offline transfer (QR code)
- operational MultiSig wallet
- send money to MultiSig wallet

**Comment by PJvanderLaan** [comment]
Initial design idea for the next sprint (not very specific):

### Onboarding
- Any individual user can start a shared bitcoin wallet ('genesis' user)
- Any user can join the shared wallet
  - Start with a transaction to the shared wallet (bitcoins). Larger bitcoin contribution equals a larger voting right
  - Transaction valid: voting process starts by the users in the shared wallet
    - @DAO_Voting_group
  - If voting succeeded, the user is added to the shared wallet
    - New bitcoin wallet (multi-signature) is created
    - Each user of the shared wallet should receive a 'part' of the private key
  - Broadcast in trustchain: public key of new shared wallet, hash of the previous known block of the old shared wallet

### Transaction
- Any user can start a proposal for a transaction
- Broadcast a proposal with the public key of the shared wallet and the private key part (encrypted or something)
- Anyone that is part of the shared wallet (same public key) votes -> voting process
- If voting succeeded, the transaction starts, using the private key parts

### Known issues that are ignored (for now)
- Any rich user can take control of the shared wallet
- We need to decide how much voting power a user receives after contributing bitcoins to the shared wallet
- Possibility to make the shared transactions private (for everyone not part of the shared wallet)

**Comment by synctext** [comment]
good stuff! 
btw Please simplify as much as possible. Like, 'genesis' user determines the DAO-capital-fee, the fixed amount of Bitcoin that represents a single fixed vote. Be inspired by others (e.g. rip existing code): https://github.com/anders94/bitcoin-2-of-3-multisig

**Comment by MattSkala** [comment]
For integrating work of all teams with the existing codebase, we have decided to take the [super app](https://home.kpmg/xx/en/home/insights/2019/06/super-app-or-super-disruption.html) approach. To separate IPv8 library from the app, we have moved `demo-android` app from kotlin-ipv8 to [trustchain-superapp](https://github.com/Tribler/trustchain-superapp) repository. Please create a module for your app and add a link to the dashboard according to the provided [tutorial](https://github.com/Tribler/trustchain-superapp/blob/master/AppTutorial.md). When you feel ready (in the upcoming weeks), you can create a pull request with your contribution.

**Comment by InvictusRMC** [comment]
### Progress update:
- UI
  - Added ability to use subviews:
  - Create a shared wallet screen
  - Search a shared wallet screen
- BitcoinJ
  - BitcoinJ proved to be a cumbersome process: downloading test-chain on Android took ~60 minutes.
  - Started code for creation of multi-sig wallet and transactions
  - Testnet balance seems to be incorrect
  - Normal bitcoin blockchain downloads in ~10 minutes. (Satisfactory?)
- Onboarding process
  - Code is implemented per proposed design, however not fully tested due to BitcoinJ issues.
    1. Find most recent SW_JOIN in TrustChain
    2. Pay entrance fee
    3. Make new shared wallet with users and own BTC pk
    4. Create SW_JOIN on Trustchain
    5. Wait for M-out-of-N VOTING_AGREEMENT
    6. Transfer funds to a new wallet on Bitcoin Blockchain

**Comment by synctext** [comment]
Sprint feedback:
  - 40% of the course is now integration with the other teams, [see here](https://github.com/Tribler/tribler/issues/4863#issuecomment-596526327)
  - Nice progress post, very helpful
  - testnet SPV versus production network? 10 minutes on real phone, mainnet
  - please experiment on mainnet with <100 Euro of Bitcoins (refund available if you have receipts)
  - cast your votes in coming ```X``` Bitcoin blocks
  - please make thing (embarrassingly) simple in order to get a final operational Delft-DAO
    - no offline support
    - everybody actually votes
    - we assume last minute vote changes don't 
    - not allowed to abstain
    - simplify: no vote is a vote against (so needing to meet the quorum)
    - transferred funds into DAO, but not voted in to join :angry: 
      - permissionless DAO, permissioned, membership
      - indiscriminately: pay-to-play
- team magical idea:
  - enrollment: new person 
  - everybody checks out if existing Delft-DAO members and stake in new shared wallet
  - re-think about ```locking out attack```, a few member of existing Delft-DAO could be sabotaged
  - coordinate through Trustchain

**Comment by InvictusRMC** [comment]
We're running into a minor issue:

![image](https://user-images.githubusercontent.com/22516119/76454269-a8892c00-63d4-11ea-94a7-3b171cd47d5c.png)

Bitcoin's transaction fees are quite high, meaning that we can perform "merely" up to 150 transactions before we run out of funds. Something to keep in mind.

**Comment by synctext** [comment]
No problem, TUDelft has .73 dollar to spend on science :smile:

**Comment by synctext** [comment]
Actually, the latest info I got is that your script is likely to be big an cost at least $10 per transaction.. Industry expert: you probably need a week to compress it, once you have it working.

**Comment by PJvanderLaan** [comment]
## Progress

UI/Trustchain:
- Connected the UI with the (new) Trustchain code
   - Create, join and view your shared wallets
- Loading screen for (bitcoin) blockchain download, can be skipped for now
- Added (semi-mockup) Trustchain proposal screen for shared wallets (Your Shared Wallet > Click on 1)
- Bought <100 EU in bitcoin and spread it over 3 wallets for testing

Bitcoin:
- Fetch transactions to check whether entrance fee is paid
  - Use blockchain API and check for inputs, outputs and BTC amount

Progress update:
- Multichain wallet creation possible with custom public keys/thresh-hold/initial fee
  - Possible in a (simple) UI for now
  - All the relevant data (transactions, public keys, signatures) made serializable for use in Trustchain blocks (message field)
- Ability (in code) to sign transactions.
- Ability (in code) to send a transaction from a multi-signature wallet (given enough signatures).

## APK
[demo-android-debug.apk.zip](https://github.com/Tribler/tribler/files/4348474/demo-android-debug.apk.zip)

## Screenshots
<img src="https://user-images.githubusercontent.com/23525907/76952160-f8a04b00-690c-11ea-9092-c11601abbd39.png" width="250">

<img src="https://user-images.githubusercontent.com/23525907/76952174-fe962c00-690c-11ea-8c51-48e9b2588984.png" width="250">

**Comment by synctext** [comment]
Sprint progress:
- great screenshots!
- not talked to 2 other groups yet
- code coverage is not too good right now :cry: 
-

**Comment by PJvanderLaan** [comment]
## Done this week (2020-03-18 - 2020-03-25)

- Finalize back-end methods of multisig transactions
    - Sending from a multi-sig wallet
    - Changed onboarding process
- Connecting bitcoin, trustchain and UI code
    - Hard to test, since we need multiple devices
    - Connection took (a lot!!) longer than expected
    - Code is finished, but there are still some bugs
    - Cleanup of code, refactors, bugfixes
    - We were missing the trustchain code for transfering funds from an existing shared wallet on both the bitcoin and trustchain blockchain. We added the functions for this
- Add ability to import custom keys to wallet for User
- Improve navigation (UI stuff)
- Improve UX (UI stuff)


### Example multisig transaction:
*(With an entrance fee of 10.000 satoshi)*

Create wallet as the first person. ```zHeLWRUv1jJn6ciWYMjJrPxv6Gg96US6Fz``` is the shared wallet address. [Transaction](https://live.blockcypher.com/btc-testnet/tx/14781fbecf604e5c6cf67d6383dfc9f3f7d8a163e3a82b1154b90675f0a7752c/)

Add the first person. ```zHeLWRUv1jJn6ciWYMjJrPxv6Gg96US6Fz``` now has 20.000 satoshi inside it. [Transaction](https://live.blockcypher.com/btc-testnet/tx/6e46f9179269ce9e3145db2b2753e7fe2c12e87320c081bb0add096afd155dc8/)

Make payment to another address. Pay 1000 to  ```mo4nNbGVfJGozjtD9ViXvcgW1fjq9stdzd``` from the shared wallet. [Transaction](https://live.blockcypher.com/btc-testnet/tx/768876624493431b079ec883326e4c23bddba20a0c870bfe23989ca0991c88fc/)

**Comment by synctext** [comment]
Sprint progress:
- [ ] Anybody can start their own DAO with their rules
- [ ] Anybody is free
- [X] Trustchain integration: serialised Bitcoin Multisig 
- Real Bitcoin are almost untouched (minor Tx costs)
- [ ] integration started with democracy group, finalise in Week 4.8
- [ ] what can demo inside a "BTC hello world" distributed app

**Comment by InvictusRMC** [comment]
# Progress last week (25-03-2020 - 01-04-2020)

* Test trustchain interactions from CoinCommunity
    * Fix related bugs
* Discuss integration with voting group
* Block discovery on trustchain
* Shared wallet discovery through block discovery on trustchain
* Ability to import seed and changes to UI
* Started integration with super app (not succesful yet)
  * However commit history is preserved  

<img src="https://i.imgur.com/Qqi9Qhn.png" width=350px/>
<img src="https://i.imgur.com/NnoQ8cV.png" width=350px/>

**Comment by synctext** [comment]
- [ ] [initial code somewhat running](https://github.com/InvictusRMC/trustchain-superapp/blob/472d532875bedf8f9fbe7c8f3cdbddfbab141893/currencyii/src/main/java/nl/tudelft/ipv8/android/demo/CoinCommunity.kt#L18)
- [ ] Integrate with Superapp by Friday using PR
- [ ] Bundle documentation

**Comment by PJvanderLaan** [comment]
This week's progress:
- Fixed the issues related to trustchain/bitcoin shared wallet connection
  - Creating a shared wallet with initial fee (tested with real fake bitcoins)
  - Transfering funds from an existing shared wallet
- Integrated our app in the superapp (took longer than expected!)
  - Fixed all related issues, ie. linting and merge conflicts
- UI improvements (mostly navigation control)
- Other small bug fixes and small improvements

**Comment by MKuijpers** [comment]
This weeks apk:
[app-debug.zip](https://github.com/Tribler/tribler/files/4449516/app-debug.zip)

Note: there are some navgraph conflicts causing some navigation to not be behaving as planned

**Comment by synctext** [comment]
Sprint progress:
- .APK to test?
- almost does not crash inside Superapp :clap: 
-

**Comment by synctext** [comment]
new apk?

**Comment by PJvanderLaan** [comment]
- UI:
  - Fixed navigation issues
  - Worked on redesigning UI
- Switched from testnet to bitcoin
  - Fixed related bugs
- Increased test coverage by a lot!
- Fixed join wallet trustchain issues
- Lots of small bug fixes and improvements

**Comment by InvictusRMC** [comment]
# Progress
* Proposal screen where join and transfer proposals are shown with ability to vote on them
* Fixed bugs related to transfer, join and create DAO
* Structured the code in a better way, cleanup
* GUI stuff (improvements)
    * Consistency across screens (BTC/Satoshi)
    * Fix crashes and better user feedback on failures
    * Add validity checks for fields and actions to protect the user
* Some of the broadcasted trustchain blocks do not fit in the UDP packet -> silent failure.
    * Possible solution:
        * Split up blocks and have a single block to store information about all blocks 
        * Send multiple blocks, which has data split up

[app-debug.zip](https://github.com/Tribler/tribler/files/4518962/app-debug.zip)

**Comment by synctext** [comment]
near final sprint comments:
- great GUI
  - "DAO logout", can that be a setting screen with "cog wheel".
  - please rename "Currency II" into "Bitcoin DAO" or something more hipster-like.
  - "import or Create new Account", replace with something like "Bitcoin wallet management".
  - "Load Existing", "if you previsouly created/imported and want to enter again, use this option". Replace with

**Comment by brian2509** [comment]
The main final documentation file in our folder [README.md](https://github.com/Tribler/trustchain-superapp/blob/dao/currencyii/README.md) has been created with details about the protocol, structure, and issues. As well as an additional section in the main [README.md](https://github.com/Tribler/trustchain-superapp/tree/dao).

**Comment by InvictusRMC** [comment]
### Final Release
[app-debug.zip](https://github.com/Tribler/tribler/files/4557200/app-debug.zip)
