### ISSUE TITLE
[7.4.x-7.5] QT.AA_EnableHighDpiScaling results in wrong DPI on some screens

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5155]
A user on the forum [reported](https://forum.tribler.org/t/7-4-x-gui-issue/5782) detected a QT bug with auto-scaling.

This happens for all the 7.4.x series along with the experimental build or 7.5.

**Comment by ichorid** [comment]
The user tried a custom Tribler build that does not include https://github.com/Tribler/tribler/blob/3afa97fd6b93e05fae0adab843daccbbcba94cf1/src/tribler-gui/tribler_gui/tribler_app.py#L13

lines. It solved his problem.

Apparently, QT DPI scaling detects DPI wrongly on some Windows machines.

**Comment by Rik44444** [comment]
same problem here, i am not using a custom build, i'm using the most recent stable build from tribler.org
<img width="960" alt="temp" src="https://user-images.githubusercontent.com/42555414/81650010-7ece9e80-9431-11ea-8484-64b9ec0a199f.png">

**Comment by ichorid** [comment]
@Rik44444 , thanks for reporting! We're probably going to include some kind of option to turn the scaling off in the upcoming 7.5 release.

**Comment by ichorid** [comment]
For 7.5 we're not going to provide the settings option as it will require some pretty invasive changes in how our GUI settings are processed. To solve this properly we should do as the QT manual [states](https://doc.qt.io/archives/qt-5.6/highdpi.html):
>
    Always use the qreal versions of the QPainter drawing API.
    Size windows and dialogs in relation to the corresponding screen size.
    Replace hard-coded sizes in layouts and drawing code with values calculated from font metrics or screen size.

*and* change the GUI settings loading order so the GUI will first load its settings, and only then will create the window. This will enable us to create a "scaling factor" option in the GUI that will be available for tuning by the user.


For people who are affected by this problem:
you can try adding `QT_SCALE_FACTOR=1` environment variable, and/or play with the value to adjust it to DPI.

**Comment by ichorid** [comment]
[Another report on the forum.](https://forum.tribler.org/t/gui-display-issue-on-7-8-x/6566/2)

**Comment by drew2a** [comment]
This could be fixed by
- #7736

**Comment by qstokkink** [comment]
Tribler now has a web-based front end and this issue is no longer relevant.
