### ISSUE TITLE
Error on including/excluding files in a download

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5169]
Reported by a user on Tribler forum for 7.5.0-exp1 and confirmed on `devel`.
When trying to include/exclude a file in the file list of a torrrent in the downloads list, Tribler produces an error message: "An error occurred during the request: ‘LibtorrentDownloadImpl’ object has no attribute ‘set_selected_file_indexes’."

**Comment by egbertbouman** [comment]
Fixed by https://github.com/Tribler/tribler/pull/5185.
