### ISSUE TITLE
"Remove download + data" does not remove download files (probably Libtorrent fault)

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5174]
Latest `devel`: clicking "Remove download" and then selecting "Remove download + data" does not delete the downloaded files.

**Comment by ichorid** [comment]
Aside from:
* our endpoint having a bug not passing the "remove_content" parameter correctly (`True == "1"` anyone?
* our test not testing the actual removing of the file during download removal
* our test skipping on empty download handle and reporting everything is fine (effectively not testing anything)

libtorrent seems to ignore the `1` flag to `remove_torrent`!

I've started a (now defunct) PR with a sample test for that: https://github.com/Tribler/tribler/pull/5186

**Comment by ichorid** [comment]
@egbertbouman , could you please look at this? I need a second opinion, before digging into Libtorrent debugging.

**Comment by egbertbouman** [comment]
@ichorid I'll fix it right now...
