### ISSUE TITLE
test_get_stats_for_uninitialized_session fails randomly on Linux

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5180]
`test_libtorrent_endpoint.TestLibTorrentSessionEndpoint.test_get_stats_for_uninitialized_session (from nosetests)`
sometimes [fails](https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_async_linux/399/testReport/test_libtorrent_endpoint/TestLibTorrentSessionEndpoint/test_get_stats_for_uninitialized_session/) on Linux.

**Comment by devos50** [comment]
I haven't seen this issue recently. Considering it fixed.
