### ISSUE TITLE
Separate version_id for the Core and the GUI

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5197]
Currently, the GUI receives version_id from the Core with `NTFY.TRIBLER_STARTED` event. Later, this version_id is used when sending crash reports through the GUI. However, this creates two time-windows where the GUI does not know the Core version and does not even know its own version! If the GUI or the Core crashes in one of these moments (namely, important start-up moments), the reports will be sent with `None` as version_id.

The proper way to solve this is to:
1. send version_id with each crash-JSON-notification-message going from the Core to the GUI
2. put version_id in the GUI separately and adjust version_id-changing logic it Jenkins jobs accordingly
3. make the GUI decide what version to use in a report based on what generated the crash (the Core or the GUI itself), and include both components' versions in the report.
4. ensure the reporter dialog is able to catch errors in the GUI as early as possible.

Another possible way to handle this is to move version_id in the Tribler Common package. Though, it can definitely result in inaccurate reports if someone will try to mix Tribler GUI and Core from different versions (say, on different hosts).

**Comment by qstokkink** [comment]
Tribler now has a web-based front end and this issue is no longer relevant.
