### ISSUE TITLE
set_selected_file_indexes strikes back

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5201]
Latest `devel` and 7.5.0-exp3: 
```
'DownloadConfig' object has no attribute 'set_selected_file_indexes'
```

Again.

**Comment by egbertbouman** [comment]
I know, this is really annoying. The unit tests were all passing, and the error reporter shows nothing because the error is handled by the GUI. There is a fix for it in https://github.com/Tribler/tribler/pull/5200.

**Comment by ichorid** [comment]
:man_facepalming:
