### ISSUE TITLE
Game theoretical proofs of cooperation in Trustchain

### ISSUE THREAD

**Issue by cuileri** [Tribler/tribler#5202]
**Motivation:**
- Our lab has recently submitted a manuscript for the extended version of the lab's blockchain solution Trustchain. We have argued that the vested interest of peers on a specific peer brings forth the notion of “interest-based communities”, which relies on the cooperation of community members for the security promises such as fraud detection. However, the incentive / motivation / cost / feasibility / advantages of the cooperation of members are not explored. We can use game theoretical methods to model the users' interactions as a game and show that strategic cooperation is stable in equilibrium, even though it does not dominate free-riding.

After the initial literature review, it is observed that [costly signaling](http://www.academia.edu/download/47090707/costly.pdf) can be used for the proof. This term is mainly used in evolutionary biology in an attempt to explain self-sacrificial behavior of individuals towards the benefit of the group. According to the theory, individuals send honest signals to the group by performing costly and hard-to-fake works, to increase their likelihood for an alliance (or a reciprocation). 

[A recent study](https://dl.acm.org/doi/pdf/10.1145/3190836) built a model (which involves costly signaling) in which deception is a sybil attack. 

**Scope:**
- Scope of the research is not restricted yet. The problem may be generalized to the case of drivers of cooperation in decentralized systems (even markets), as it may be specialized to “the drivers of participation in the validation and audit processes of Trustchain”

**Initial Hypothesis:** 
- Given a high threshold for the fraction of free-riders and benevolent users, a cooperative strategy towards the security promises of Trustchain is evolutionary stable.

**Work flow:**  
- Read the costly-signaling literature. See whether the notion of costly-signaling is applicable to community based weak consensus idea in Truschain. 
- If not, derive a new model out of it. Explore game theory to find which type of game suits our case.
- Find all literature on the game-theoretical modeling of the consensusless blockchains.

**Next sprint:**
- Initial listing of related literature
- A game model of fraud in interest-based communities of Trustchain. Initial definitions of players, profit/loss and strategies.

**Comment by synctext** [comment]
[remarks on this work, a year ago](https://github.com/Tribler/tribler/issues/2805#issuecomment-453552267). Might be incorrect. Other

**Comment by qstokkink** [comment]
It seems like the project proposal of this issue will never get its first sprint and the technology that is addresses (Trustchain) has been removed from Tribler. Therefore, I'll close this.
