### ISSUE TITLE
Memory dumps don't work as Meliae does not support Python3

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5203]
Meliae development had stopped some time ago, so we can't make memory dumps anymore.

**Comment by devos50** [comment]
No we can't. The application tester suggests that the memory usage of Tribler is stable, even when downloading/relaying data. So let's hope that we do not need extensive memory profiling in 7.5.

Still, I would be in favour to get at least some memory dumper back in Tribler, but this is more suited for the 7.6 release.

**Comment by ichorid** [comment]
Agree. Personally, I use `mem_top` to profile memory usage in Tribler.

**Comment by qstokkink** [comment]
In the deep dark annals of history I made this #3603 . But it's pretty slow.

**Comment by qstokkink** [comment]
I don't believe we're interested in making memory dumps anymore.
