### ISSUE TITLE
Request error upon cancelling move file storage operation

### ISSUE THREAD

**Issue by Koen1999** [Tribler/tribler#5205]
This is just a small bug

#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Tribler 7.4.4

##### Operating system and version: #####
Windows 10, latest updates installed

##### Steps to reproduce the behavior: #####
Right click on a torrent (download still in progress), select move file storage, then cancel.

##### Expected behavior: #####
Just return to the torrent overview without throwing an error or making any modifications

##### Actual behavior: #####
Request error: Target directory () does not exist
The torrent is not moved and still works correctly

##### Relevant log file output: #####
I was not able to find any information in the log file related to this issue.

**Comment by ichorid** [comment]
Confirmed on 7.5. GUI produces a pop-up with:
```
An error occurred during the request:

Python argument types in
    torrent_handle.move_storage(torrent_handle, Path)
did not match C++ signature:
    move_storage(libtorrent::torrent_handle {lvalue}, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > path, int flags=libtorrent.deprecated_move_flags_t.always_replace_files)
    move_storage(libtorrent::torrent_handle {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > path, libtorrent::move_flags_t flags=libtorrent.move_flags_t.always_replace_files)
```


This happens on both selecting the dir, **and** cancelling it.
