### ISSUE TITLE
Keyword search performance and RemoteQuery community

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5208]
Currently, RemoteQuery Community does not cache any remote requests. Caching typical requests like queries for subscribed channels should help with database performance.

**Comment by triblerteam** [comment]
Could you please post a performance analysis of expensive queries? I prefer to keep Tribler code as simple as possible.

**Comment by synctext** [comment]
Adding performance results here for keyword search: **8 seconds** in some cases. In other cases it is a snappy fast sub-second local result. Something is seemingly blocking in some corner cases. Or the database is simply 4.4 GByte big :+1:
![Search_duration_Tribler7 5 0RC6](https://user-images.githubusercontent.com/325224/84592743-2cc1d400-ae48-11ea-8c94-dc0430c09748.gif)
Ubuntu 18.04 with 7.5.0RC6 and 1953 discovered channels.
```
-rw-r--r-- 1 pouwelse pouwelse 4.4G Jun 14 14:07 metadata.db
-rw-r--r-- 1 pouwelse pouwelse 273M Feb 12  2019 dispersy.db
-rw-r--r-- 1 pouwelse pouwelse 335M Jan 15 12:37 noodle.db
-rw-r--r-- 1 pouwelse pouwelse 400M Feb 12  2019 tribler.sdb
-rw-r--r-- 1 pouwelse pouwelse 342M Jun 14 14:03 trustchain.db
```

**Comment by ichorid** [comment]
@kozlovsky  solved most of DB performance problems! Thank, you Alexander! :+1:
