### ISSUE TITLE
Deb-file in installation guide missing

### ISSUE THREAD

**Issue by dymbe** [Tribler/tribler#5223]
The link to the deb-file in the [Debian/Ubuntu/Mint installation-guide](https://github.com/Tribler/tribler/blob/devel/doc/development/development_on_linux.rst#debianubuntumint) gives a 404.

The link: https://jenkins-ci.tribler.org/job/Build-Tribler_Ubuntu-64_devel/lastStableBuild/

**Comment by qstokkink** [comment]
It seems we lost a header: https://github.com/Tribler/tribler/commit/fd5f8b7ef4822f22f94c54df3bf0c2b06f43eed0#diff-579c8e8eb793757e6a26a28853445394L59

The `.deb` file, should have been the alternative to installing dependencies manually through the previous steps.

**Comment by devos50** [comment]
We should fix this before the 7.5 release.

Also related to #4892
