### ISSUE TITLE
Temporary values (ports) get written into config

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5224]
Steps to reproduce:
run `run_tribler_headless.py` without options, see ipv8 port number in `triblerd.conf` rewritten with 8085.

There is another minor bug: default ipv8 port number should not be 8085 in `run_tribler_headless.py`.

**Comment by ichorid** [comment]
The true reason for this is that we use `config` object to pass around runtime-assigned values like dynamically assigned port numbers and API key value.

**Comment by devos50** [comment]
@ichorid do we want to fix this for the 7.5 release?

**Comment by ichorid** [comment]
We can fix it in later 7.5.x bugfix releases. It only affects people who run Tribler headless.

**Comment by devos50** [comment]
Fixed by #5275
