### ISSUE TITLE
integrate Python notebooks into standard documentation of Tribler

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#5225]
Besides #4521 and #4656.
We have several .ipynb files
- [Trustchain sim tutorial](https://github.com/grimadas/BlockchainEngineering)
  - https://github.com/grimadas/BlockchainEngineering/blob/master/00_Overview.ipynb
  - https://github.com/grimadas/BlockchainEngineering/blob/master/02_Services.ipynb
- [incremental-pagerank](https://github.com/Tribler/incremental-pagerank/blob/master/Report.ipynb)
- from [ctc-executioner wiki](https://github.com/mjuchli/ctc-executioner/wiki)
  - https://github.com/backender/ctc-executioner/blob/master/notebooks/order_execution_behaviour.ipynb
  - https://github.com/backender/ctc-executioner/blob/master/notebooks/order_execution_behaviour_artificial.ipynb
  - https://github.com/backender/ctc-executioner/blob/master/notebooks/orderbook_features.ipynb

**Comment by grimadas** [comment]
This is no longer relevant, as Tribler is a system not an algorithm.
