### ISSUE TITLE
Fatal error detected: Failed to execute script pyi_rth_twisted

### ISSUE THREAD

**Issue by Zoner23** [Tribler/tribler#5227]
#### Please, fill all relevant items: ####

- [X] I have read CONTRIBUTING.rst

- [X] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

7.4.4 stable

##### Operating system and version: #####

Windows 10 Pro Version 1903

##### Steps to reproduce the behavior: #####

Start Tribler.exe

##### Expected behavior: #####

Start Tribler

##### Actual behavior: #####

Error Window

##### Relevant log file output: #####

I'm following the instructions for reporting bugs.
I'm staring at the "_.Tribler_" folder and I do not see a way to get to "_/var/log/system.log_".
I have a "_logs_" folder with no files named "_system.log_".

I'm trying to run vanilla Tribler 7.4.4 with no additional code or modules added.
I have not had this issue previously with prior uses. Granted I haven't used Tribler in quite some time.

**Comment by ichorid** [comment]
Could you please provide us with a screenshot of the error?

**Comment by devos50** [comment]
This error shows up (in a Windows dialog) when Tribler is unable to boot. This error is particularly hard to debug since there are no traces available. When we encountered this error in the past, it was often because of a missing runtime library. It might be that we forgot to update the Visual C/C++ runtime dependencies during our migration to Python 3.

**Comment by devos50** [comment]
@Zoner23 could you try out [the latest release candidate of Tribler 7.5](https://github.com/tribler/tribler/releases) and see if this issue is resolved?

**Comment by devos50** [comment]
This error have not been reported ever since so I'm closing the issue. Please re-open this issue of the problem persists.
