### ISSUE TITLE
Build from current devel branch not starting on Mac and Windows (32-bit and 64-bit)

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5229]
I'm getting the following error when starting `Tribler.dmg` or `tribler.exe`, after Tribler has been stuck on the loading screen for 60 seconds:

```
Traceback (most recent call last):
  File "tribler_gui/event_request_manager.py", line 136, in <lambda>
  File "tribler_gui/event_request_manager.py", line 78, in on_error
RuntimeError: Could not connect with the Tribler Core within 60 seconds
```

This is with a clean state directory.

**Comment by devos50** [comment]
The actual error seems to be hidden by the following warning: `Logger config not found in tribler-core/tribler_core/logger.yaml. Using default configs.`. I think that the location of this file is different in a frozen environment.

**Comment by devos50** [comment]
It also seems to fail on Windows, both 32-bit and 64-bit.

**Comment by egbertbouman** [comment]
I hope I'm wrong here, but it could be related to aiohttp-apispec.

**Comment by egbertbouman** [comment]
Yep, it was aiohttp-apispec. It wasn't able to find the static html/js files, and produced no error message. I'll make a PR.

**Comment by devos50** [comment]
Nice find!

**Comment by ichorid** [comment]
I've tested rc1 on Julia's PC before releasing it. There was no problem (used x64 version).

**Comment by egbertbouman** [comment]
It's broken on devel only.
