### ISSUE TITLE
No relaying // no credit

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5231]
[Users](https://github.com/Tribler/tribler/issues/5220#issuecomment-602202461) [report](https://forum.tribler.org/t/something-wrong-with-trust-graph/5825/2) that 7.5.0 (and possibly 7.4.4) does not work as a relay by default, resulting in no credit gain when Tribler is idle.

**Comment by egbertbouman** [comment]
Considering the default hop count is 1, it's no suprise there is little need for relays. Of course, some users will change the hop count and hidden services also requires relays. So, I would at least expect an occosional relay. I'll take a look at this.

**Comment by devos50** [comment]
In the application tester, I'm seeing tons of timeouts on crawl requests and payouts. If half blocks are not counter-signed, it would explain the negative balances. I will debug it more.

**Comment by ichorid** [comment]
Probably closed by #5245
