### ISSUE TITLE
Problem on Streaming with Kodi

### ISSUE THREAD

**Issue by hbiyik** [Tribler/tribler#5249]
Hello Tribler Team

Since tribler is getting more and more stable everyday i started kodi addon development.
https://github.com/hbiyik/repository.biyik/tree/master/plugin.program.tribler
But i have a problem when streaming an unfinished torrent with kodi player.

When kodi starts streaming the torrent, the torrent sets the state DLSTATUS_SEEDING and progress hits to %100 and the download does not download anymore but still keeps seeding. However the torrent is in reality halfly downloaded.

To better describe the problem let me explain how kodi player streams an http media.

1) Send a HEAD request to check if media is available and get basic meta info like content length and type
2) Send a 2nd HEAD request to either validate the previous HEAD request or just some bug in kodi. idk.
3) Start GET request with rage 0- and get the header information of the media, as long as header is received close the TCP session. Generally reset around 1-2 mb of data.
4) Start GET request with range 0- and play the media with the header information parsed from previous request. This will continuously download the media until playback is stopped.
5) After GET request in step 4 is sent, send another GET request in another thread with range %99-%100 of file. Basically the footer of the file to parse metadata of some specific formats.

For HEAD requests i fixed the issues at:
https://github.com/hbiyik/tribler/blob/fdc589488238c93ea9a4d0b9da69af1b9d2fe37b/src/tribler-core/tribler_core/modules/libtorrent/restapi/downloads_endpoint.py#L622

But i speculatively think that step 5 causes the problem I described above (DLSTATUS_SEEDING %100 issue). But not sure, i fiddled the code a lot but could not identify the root cause.

You can duplicate the problem with.
1) Install kodi >= 17 to a linux machine where tribler is installed. And run tribler and kodi at the same time
2) Download my repo at https://github.com/hbiyik/repository.biyik/blob/master/repository.biyik.dist/repository.biyik/repository.biyik-0.0.2.zip
3) On kodi, navigate to addons, install from zip file, allow unknown sources, browse the repo zip file and install.
4) On kodi, navigate to addons, install from repo, select "biyik kodi repo", program addons, and tribler, select install.
5) Then navigate to addons, programm addons, tribler.
6) Add a torrent from url or local file.
7) Go to downloads, downloading, right click the newly added torrent and select play.

Thanks for your help :)

**Comment by devos50** [comment]
@egbertbouman could you have a look at this?

**Comment by egbertbouman** [comment]
@hbiyik I agree, this issue is most likely step 5. Every time a http request is made, the piece priorities in libtorrent change. Because step 5 requests only the end of the file, Tribler will simply download it, and afterwards report that the download is finished (so it starts seeding).

I'll have a look and see if I can also make it work for multiple simultaneously requests, assuming the required changes don't break our own videoplayer of course.

**Comment by hbiyik** [comment]
thanks for the support, I just added giga channels and remote query support to the addon, it works awesome.

**Comment by egbertbouman** [comment]
Nice plugin, it works really well!

After some testing, it seems sometimes Tribler does recover after some time and the video starts playing. I did use non-anonymous downloads since they tend to have a higher download speed. If the download speed is too slow, Kodi just seems to abort playing entirely.

I think streaming needs a lot of work to get it to work properly with Kodi. However, considering we're understaffed as it is, I don't think I have time to make this a priority right now.

**Comment by hbiyik** [comment]
Ok, may be I can progress if i struggle more :)

**Comment by synctext** [comment]
@hbiyik We have received funding till 1 Sep 2025! We're currently trying to fill 4 openings for phd students within the lab. As usual the Tribler Lab has trouble delivering quickly, but we'll get there slowly.

**Comment by hbiyik** [comment]
@synctext these new refactoring was very affective. Definetely right track, we have been waiting for > 10 years so, it is ok :)

**Comment by hbiyik** [comment]
i think i found the root cause of garbeling, stream object is using single local file opened to read from, while concurrent http requests are processed, local file seeks to different segments of the file resulting junk output. I will fix this in my repo

**Comment by hbiyik** [comment]
Here is the update:

1) Currently concurrent streams work properly. It is possible to seek forward/backwards or directly start from middle of the file

2) Stream endpoint can serve concurrent clients at the same time. Concurrency is under the aasumption that everyone is streaming the same fiile in the torrent, if they stream different files from the same torrent clients will receive garbage.

Here is he WIP commit.
https://github.com/hbiyik/tribler/commit/a01ba0850ae1f26f26c54f5a999c82e2e01f988d

About the stuterring problem, I actually found the root cause.
When a client opens concurrent TCP streams and sets one of the streams TCP window size to 0, AIOHTTP is dump enough to think that this is for all of the transport associated to endpoint. This is why server responds the HTTP request with TCP ACK but does not really write any more data because transport is full.

I dont know in which version this issue is fixed with AIOHttp but with python3.8 there is no problem at all. May be this can be another motivation to upgrade to py3.8.

**Comment by hbiyik** [comment]
@egbertbouman 

I have re-written the streamer in kodi and there are a lot of changes. So I think this is good checkpoint to align.

Design Changes:
1) The streamer no more relies on libtorrenthandle.sequential_download(true). Because when this piece selector is activated, regardless of piece priority, piece selector always selects the lowest number. This prevents seeking to a further piece of the torrent when the pieces before the seeked cursor are not downloaded.

2) With the new design, tribler itself is managing the sequential download with setting prios to 7-6-6-6-6-6 .... and so on. The trick with the piece priorty 7 is, when a piece priority is 7, regardless of piece selector decision, always piece 7 will be selected. since there is only 1 priority 7 piece selected for a chunk, the download sequence is forced to be sequential. And this piece prio 7 will be moved along with the local cursor that the player is using with a prebuffer size.

3) There are at least now 3 prebuffers now, 1st is the 5MB of the file: Header prebuffer, 2nd last 1MB of the file: Footer prebuffer. From seek position to + %10 of the filesize: this is called prebuffer.

For a stream to work properly all those above must be downloaded, those prebuffers are forced to prio 7 and they are all prerequisite for streaming to start, and their progresses are exposed to API. (There is no  7-6-6-6-6 trickery here, since streaming must no start before ) 

There are also Chunk Buffers. Besides those 3 prebuffers mentioned above, when a player actually reads the actual file either with a range request of without a range request, a moving prebuffer is reserved in tribler according the actual read position + prebuffersize (%10 of the file size). This prebuffer is maintanied with self written sequential download with (7-6-6-6-.. logic), not with libtorrent sequential logic.

In practice for kodi there are 2 parallel chunk reads (depending on the file it can be 1) 1 for the audio data, 1 for the video data. So in practice this new prioritization logic handles 4-5 prebuffers at the same time for a single streaming.

Currently i have seeked an unanon dowload succesfully (see above picture in action), and streamed anon download without issues.  Download speed is too slow to compenste player timeout in anon mode but i think there may be some stuff there to improve player behaviour as well (through kodi addon to tell kodi to wait up etc...).

**Comment by hbiyik** [comment]
But now the code interfaces are changed little bit.

A downloads relations with streaming is now handled in download module, thus there are new methods for Download Class related to streaming.

There is a class now called StreamState, which holds all the downloads streamin status in a Singleton pattern internally, so he download instances can interact with their own streaming states.
The instance of the StreamState are responsible for managing the chunk positions and their respective representations in torrent pieces.

There is also another new Class called StreamChunk, as the name suggests, it represents a chunk of the streaming file that is read through localfile, and responsible for synchronizing its own chunk position with the torrent prio position.

**Comment by egbertbouman** [comment]
> The streamer no more relies on libtorrenthandle.sequential_download(true). Because when this piece selector is activated, regardless of piece priority, piece selector always selects the lowest number. This prevents seeking to a further piece of the torrent when the pieces before the seeked cursor are not downloaded.

If I remember correctly, seeking does work with sequential downloading if you use a 0 priority for pieces prior to the position of the cursor. 

> With the new design, tribler itself is managing the sequential download with setting prios to 7-6-6-6-6-6 .... and so on. The trick with the piece priorty 7 is, when a piece priority is 7, regardless of piece selector decision, always piece 7 will be selected. since there is only 1 priority 7 piece selected for a chunk, the download sequence is forced to be sequential. And this piece prio 7 will be moved along with the local cursor that the player is using with a prebuffer size.

Sounds great! We actually used to use piece priorities as well (quite a few years back), but since users did not always understand that Tribler was downloading pieces that were far away from the cursor, at the time we decided to just use sequential downloading. Having said that, personally I prefer using your solution.

> There are at least now 3 prebuffers now, 1st is the 5MB of the file: Header prebuffer, 2nd last 1MB of the file: Footer prebuffer. From seek position to + %10 of the filesize: this is called prebuffer.

I think we currently already have 3 prebuffers (one of them is hidden in the endpoint itself), although the sizes seem to have changed.

> A downloads relations with streaming is now handled in download module, thus there are new methods for Download Class related to streaming.

Since I felt the `Download` class was getting a bit big, I actually removed the streaming methods out of the `Download` class. So, I'm not sure about this.

By the way, does the internal player in Tribler still work?

**Comment by hbiyik** [comment]
> By the way, does the internal player in Tribler still 

Yes internal player works, vlc works, several mplayer based stuff also works. Actually they work concurrently as well, you can stream same file to different clients at the same time, since there are independant cursor trackers now.

> Since I felt the Download class was getting a bit big, I actually removed the streaming methods out of the Download class. So, I'm not sure about this.

The problem is streamer depends on torrent handle heavily now, and all the utils methods are already in download instances. I tried to keep it on stream module but it looks ugly and at some point they look like they don't even belong there: ie: iter_torrent_pieces. And to me it looks cleaner this way.

> If I remember correctly, seeking does work with sequential downloading if you use a 0 priority for pieces prior to the position of the cursor.

It only works if the buffer is downloaded, this practically means it does not work because massive delay is introduced by finishing the old buffer, seeking new position and so on. This is for players which uses single cursors, for kodi there are concurrent cursors, which make it technically impossible.

Currently the implementation is a little bit crude, I am experimenting with piece_deadlines and selector strategy tuning to improve the responsivenes on seek times. And also the code interfaces are a bit WIP, and needs tuning/cleaning/improving etc..

**Comment by hbiyik** [comment]
@egbertbouman 
https://github.com/hbiyik/tribler/blob/139ed485ed17d3223016c8ba03fb1d031b3ee22f/src/tribler-core/tribler_core/modules/libtorrent/stream.py#L71

I removed the modifications in the downloads module and referenced the all used method to stream module, now i think it is pretty clear and more managable. Do you think this approach is ok?

**Comment by egbertbouman** [comment]
It's great to see you've moved this code back to the `Stream` class. But why not just keep a reference to the `Download` object and call these functions directly, like it was before? To me this seems a bit unnecessary.

**Comment by hbiyik** [comment]
@egbertbouman because now the instances of stream class, will be a member of download class.

Regardless of the download is streaming or not, they will instantiate stream class.

https://github.com/hbiyik/tribler/blob/139ed485ed17d3223016c8ba03fb1d031b3ee22f/src/tribler-core/tribler_core/modules/libtorrent/download.py#L79

Please see how it is instantiated above. Thus i didnt want to reference download instance stream because, downloads will have sth like:

download.stream.download.stream.download.....

I could mangle it with self.__download = download but, the membership loop would still be there, there is no technical drawback of this situation, i just want the code to look clean and well interfaced.

**Comment by hbiyik** [comment]
The idea here is having the stream module as a sub scope of download scope, this way code level abstraction is done on source level, and applition level integrity is cleaner with stream subscope of download.

**Comment by hbiyik** [comment]
@egbertbouman 

i noticed some issue with, excluding, including files on download details. 

When a file in a download is set to include/exclude, the operation is done in in downloadconfig object, but during runtime, this is never reflected to filepriorities in libtorrent. So in gui it is shown according to config, but in libtorrent all files are downloaded.

Is this a known issue.

I noticed this problem when streaming individual f

**Comment by egbertbouman** [comment]
We used to have an issue like this, but that one was fixed weeks ago. So if you're working on up-to-date code, you seem to have found a bug.

When including/excluding files, `Download.set_selected_files` should be called. That function will then update both the file priorities and the config. Could you point me to the `DownloadConfig` call that you are referring to?

**Comment by hbiyik** [comment]
@egbertbouman I think there were several issues:

1) QT UI was using sort index when sending selected files instead of torrent fileindexes, this is fixed when i rebased to release7.5. I was on some sort of master, may be I have created this regression dunno, nevertheless fixed.

2) download.set_selected_files sets both config and lt file prios on runtime, downloads_endpoint.get_files_info_json gets the file status from the config (not libtorrent) this way there file download state (inclusion/exclusion) is synched. This only a statement

https://github.com/Tribler/tribler/blob/09fbd720a6c251ffa76bfb2d2560b60a6920994d/src/tribler-core/tribler_core/modules/libtorrent/restapi/downloads_endpoint.py#L121

https://github.com/Tribler/tribler/blob/09fbd720a6c251ffa76bfb2d2560b60a6920994d/src/tribler-core/tribler_core/modules/libtorrent/download.py#L382

4) Problem 0.5 (sort of a problem):
download.set_selected_files sets sets the file prio to 1 when enabled, but the default prio in lt is 4. This will cause disabled/enabled files to downloaded later, also some discrepencies here and there.

 https://github.com/Tribler/tribler/blob/09fbd720a6c251ffa76bfb2d2560b60a6920994d/src/tribler-core/tribler_core/modules/libtorrent/download.py#L398

3) Problem 1: Stream is direclty manipulating the fileprios when stream is enabled without updating the download config. Thus file inclusion / exclusion is not shown properly because it reads the config.

https://github.com/Tribler/tribler/blob/09fbd720a6c251ffa76bfb2d2560b60a6920994d/src/tribler-core/tribler_core/modules/libtorrent/stream.py#L105

4) Problem 2: When streaming is enabled, user can somehow change the inclusion of file on the gui, this will update lt file prios, and streamer will then stop streaming because it depends on the selected file stream prios.

5) Problem 3: for the scenario above when the stream is closed it will revert the file prios when the stream started, so the user selection will be lost.

What I suggest is:
1) download.set_selected_file should get an optional argument for enable priority and should be set default to 4.

2) Stream should directly use download.set_selected_file when streaming and backup the original prios before starting.

3) download.set_selected_file is now aware of the particalr torrent is on streaming mode, if the downlaod is in streaming mode, it should raise an exception and not allow inclusion to be manipulated when streaming. This will translate an HTTP 500 to the gui.

https://github.com/hbiyik/tribler/blob/68e798734292226daaf9f22fc092d59f7e30db72/src/tribler-core/tribler_core/modules/libtorrent/stream.py#L34

I already created an exception for streaming that can used for this purpose.

4) When streaming is done, the backed up prios shuld be reloaded to the download instance again with  download.set_selected_file

**Comment by egbertbouman** [comment]
You're right, Tribler is currently bypassing the Download class by talking to the handle directly. That's definitely a bug.

All your suggestions make perfect sense and sound like a good way to improve our streaming experience!

**Comment by hbiyik** [comment]
fixed in https://github.com/Tribler/tribler/pull/5301
