### ISSUE TITLE
[Software Project 2019/2020] Building a critical infrastructure for the nation-wide identification of recovered COVID-19 (Corona) patients

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5251]
This issue hosts references and discussion related to the software project we added to ProjectForum.

# Description in ProjectForum

The research of the Delft Blockchain Lab orients around digital identity, cryptographic key management, verifiable claims, self-organisation, trust, and tamper-proof datastructures (e.g. blockchain). In collaboration with the Dutch National Institute for Public Health and the Environment (RIVM) and the Ministry of Internal Affairs, the Delft Blockchain Lab offers a unique project on building critical infrastructure during the Corona crisis.

The ongoing outbreak of the novel COVID-19 (Corona) virus is an unprecedented threats to humanity. The developments around the Corona virus across the world are demonstrating the fragility of current organisational models, usually involving a political model where decisions flow from top (a government) down to municipalities and individuals. One of the objectives of our lab is to explore and deploy bottom-up organizational paradigms that put citizens in power, instead of authorities. The main goal of this project is to build open-source, critical infrastructure for the identification of recovered Corona patients. The project aligns with digital companies and health initiatives around the world, like VODAN (Virus Outbreak Data Network) and the medical centers of Rotterdam and Leiden.

## Problem Description

As a first step towards this goal, we seek to expand our Self-Sovereign Identity (SSI) library with health features. Delft University of Technology, together with the ministry of internal affairs [developed a library for SSI](https://github.com/Tribler/py-ipv8/tree/master/ipv8/attestation) that enables the creation of attestations and privacy-preserving proving of claims. Our mobile Android application has the potential to provide passport-grade identities to every citizen of the Netherlands. Specifically, this project would entail the integration of a Corona blood test where you can prove to other users (and businesses) whether you recovered from the Corona virus and therefore has built up resistance. During the coming months, quickly proving such resistance might become a key requirement by certain sectors, e.g., health care, and to better quantify the progress of herd immunity. Integration of a "Corona check" is a small, yet critical step towards a full health record database later on, based on a Self-Sovereign Identity solution.

*Note that your work has the potential to be deployed on a larger scale. Therefore, we are specifically looking for motivated students with interest in digital identity solutions.*

## Self-Sovereign Identity

SSI puts people in charge of their own digital identities. The key idea is that companies can provide attestations to the digital identities of users. Users can then use these attestations in interactions with others to prove various claims, e.g., whether they have the legal age to buy alcoholic drinks from stores, without revealing sensitive information. Since 2016, our research line on SSI has been covered by several media outlets and currently, the third generation of prototypes is being defined together with the RvIG.

More information about our SSI solution can be found [here](https://www.blockchain-lab.org/trust/).

**Comment by devos50** [comment]
A list of references for this project

## Primary references

- [Oxford project](https://045.medsci.ox.ac.uk/mobile-app)
- [Radbound project](https://blog.xot.nl/2020/03/25/hansel-and-gretel-and-the-virus-privacy-conscious-contact-tracing/)
- [Reverse engineering of ‘TraceTogether’ in Singapore](https://medium.com/@frankvolkel/tracetogether-under-the-hood-7d5e509aeb5d)
- [MIT app](http://safepaths.mit.edu/)
- [Criticism on the value of cell-tower data](https://www.axios.com/location-data-likely-to-play-limited-role-in-fighting-coronavirus-9cb140a9-3e63-4142-8879-41370dd3002e.html)
- [Detailed explanation on the types of data for epidemic tracking](https://fpf.org/2020/03/25/a-closer-look-at-location-data-privacy-and-pandemics/)
- [Science magazine publication](https://www.sciencemag.org/news/2020/03/cellphone-tracking-could-help-stem-spread-coronavirus-privacy-price)
- [Privacy explanation from EDPB](https://edpb.europa.eu/news/news/2020/statement-edpb-chair-processing-personal-data-context-covid-19-outbreak_en)
- [Zerocash project for decentralized tracking](https://www.zfnd.org/blog/decentralized-contact-tracing/)

## Secondary references
- [US government announces health surveillance](https://www.wsj.com/articles/to-track-virus-governments-weigh-surveillance-tools-that-push-privacy-limits-11584479841)
- [Phone for spread tracking](https://www.wired.com/story/phones-track-spread-covid19-good-idea/)
- [Privacy regulations are changing around the world](https://www.cnet.com/news/coronavirus-pandemic-changes-how-your-privacy-is-protected/)
- ["A team of medical research and bioethics experts at Oxford University are supporting European governments to explore the feasibility of rapidly and widely deploying a coronavirus mobile app for instant contact tracing.”](https://www.eurekalert.org/pub_releases/2020-03/oubd-oup031720.php)
- [App for contact tracing in Singapore](https://www.zdnet.com/article/singapore-introduces-contact-tracing-app-to-slow-coronavirus-spread/)
- [Cambridge ‘FluPhone’ app and others mentioned in Guardian](https://www.theguardian.com/commentisfree/2020/mar/21/smartphones-could-help-track-coronavirus-but-at-what-cost)
- [Spain uses drones for tracking](https://www.forbes.com/sites/zakdoffman/2020/03/16/coronavirus-spy-drones-hit-europe-police-surveillance-enforces-new-covid-19-lockdowns/#4e620c7471c0)
- [Israel leverages anti-terrorist surveillance](https://www.nytimes.com/2020/03/16/world/middleeast/israel-coronavirus-cellphone-tracking.html)
- [More Israel](https://foreignpolicy.com/2020/03/16/israel-coronavirus-mass-surveillance-pandemic/)
[Opinion on health-tracking](https://lens.monash.edu/@education/2020/03/09/1379796/the-new-transparency-smartphones-data-tracking-and-covid-19)
- [Using existing surveillance in china](https://www.handelsblatt.com/technik/digitale-revolution/digitale-revolution-chinas-code-system-wie-die-coronakrise-zu-noch-mehr-ueberwachung-fuehrte/25653166.html?ticket=ST-2217109-cHDGsmYkcohxcB6CaVkP-ap1)

**Comment by synctext** [comment]
Bizarre background reading from Wuhan Institute of Virology. [They predict an outbreak of "Bat Coronaviruses in China", published March 2019](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6466186/).

**Comment by devos50** [comment]
Kick-off meeting:
- Current goal (subject to change!): make a prototype that allows a health expert to provide a COVID-19 attestation to an individual. Individuals should prove the validity of the attestation to others.
- The first week: start reading the documentation on SSI and Corona identification.
- Complete the [attestation tutorial](https://github.com/Tribler/py-ipv8/blob/master/doc/basics/attestation_tutorial.rst)
- Come up with a few interesting idea's 
- Bonus objective (possibly out of scope): how does the health expert assess that you have/had Corona? Questionnaire?

**Comment by devos50** [comment]
Notes meeting 27th April:
- Did brainstorm session to get the idea more clear, came up with some ideas
- Proximity tracking vs. secure claims if you are infected/have been infected
- Please post your documents on this issue
- Generalization is good but always focus on the main goal: a working application with source code. Running code is a must-have
- Consider a web-app (e.g., React) so it can easily be ported to mobile
- How can we share 'immunity proofs' while keeping the distance?

**Comment by kkostadinov99** [comment]
[Project Plan.pdf](https://github.com/Tribler/tribler/files/4571959/Project.Plan.pdf)
This is our Project Plan.

**Comment by kkostadinov99** [comment]
This is our Project Plan. Revised version. Fixed "certificate" and "use case" confusion.
[Project Plan.pdf](https://github.com/Tribler/tribler/files/4577340/Project.Plan.pdf)

**Comment by kkostadinov99** [comment]
Revised Project Plan - The names of all people involved were included; Fixed some formating issues; Referring to the virus as "SARS-CoV-2"; Added references to the technologies that are going to be used; Made the risk analysis more related to the project; Added a MoSCoW list, summarizing all requirements; Fixed paragraphs of the "Elicitation and Analysis of the Requirements" section that might cause confusion; Updated the "Roadmap" chapter.
[Project Plan.pdf](https://github.com/Tribler/tribler/files/4593981/Project.Plan.pdf)

**Comment by kkostadinov99** [comment]
Link to the code repository: https://github.com/kkostadinov99/covid-19-recovery-identification

**Comment by kkostadinov99** [comment]
Our Draft Report
[Draft_Report_6D.pdf](https://github.com/Tribler/tribler/files/4770377/Draft_Report_6D.pdf)

**Comment by kkostadinov99** [comment]
The app's screenshots:
https://imgur.com/a/cVvkkE0

**Comment by kkostadinov99** [comment]
The app's demo video:
https://drive.google.com/file/d/1CiMfFrc6dPKal7rwt9xmK0Y8b1oNJPwN/view?usp=sharing

**Comment by kkostadinov99** [comment]
The app's APK:
https://drive.google.com/file/d/1caGHLJ2ixuKyJqbrA7Eq02wCqMaABJ5H/view?usp=sharing

**Comment by devos50** [comment]
Thanks! Could you please post the screenshots here in GitHub directly?

**Comment by kkostadinov99** [comment]
![Screenshot_1593035040](https://user-images.githubusercontent.com/45499461/85759191-48af5a80-b711-11ea-81d1-0913afcef463.png)
![Screenshot_1593035076](https://user-images.githubusercontent.com/45499461/85759205-4b11b480-b711-11ea-8f05-8cb8b9afe997.png)
![Screenshot_1593035091](https://user-images.githubusercontent.com/45499461/85759444-5d8bee00-b711-11ea-8ae2-dd27cc5ec740.png)
![Screenshot_1593034397](https://user-images.githubusercontent.com/45499461/85759653-6da3cd80-b711-11ea-8a7f-716de9dfefd7.png)
![Screenshot_1593034548](https://user-images.githubusercontent.com/45499461/85759695-7399ae80-b711-11ea-85ef-970b26eb2a39.png)
![device-2020-06-24-234851](https://user-images.githubusercontent.com/45499461/85759747-7d231680-b711-11ea-88ee-0cfe82d196fc.png)
![device-2020-06-24-233851](https://user-images.githubusercontent.com/45499461/85759754-7eecda00-b711-11ea-8027-a90a662caa8e.png)
![device-2020-06-24-233711](https://user-images.githubusercontent.com/45499461/85759761-7f857080-b711-11ea-81a0-13f2cf5bfa46.png)
![Screenshot_1593035695](https://user-images.githubusercontent.com/45499461/85759780-84e2bb00-b711-11ea-8778-cb2e4a4875ee.png)
![Screenshot_1593034433](https://user-images.githubusercontent.com/45499461/85759804-89a76f00-b711-11ea-9aab-1a8e56f3f698.png)

**Comment by devos50** [comment]
This project has finished 👍
