### ISSUE TITLE
Poor exception Handling in Torrent Checker and Session

### ISSUE THREAD

**Issue by hbiyik** [Tribler/tribler#5261]
This is just the summary of another issue found in:

https://github.com/Tribler/tribler/pull/5253#discussion_r400412715

The torrent Checkers are caching * exceptions and supressing the errors and redirects the excetion message to response dict. This is itself a weak design to my pov never the less it does not stop there, 

the exception result dict is then redirected in the checker session and checker session redirects this response to restapi, with status ok 200 code.

So 
1) Catching base exceptions without any trace handling
2) Redirecting the exceptions on rest api with 200
3) Redirecting the exceptions to basically another process (core -> gui)

i can name above as major flaws in this process, and i think it is an open

 invitation to weird undetected bugs, basically perfect recipe to shot urself in the foot.

Just raised this issue for the record sorry if you are already aware of this.

İ can provide code references if statements are not clear.

**Comment by ichorid** [comment]
Thanks for the report. We were not aware of this.

**Comment by devos50** [comment]
I think solving this issue requires some extensive refactoring of the torrent checker/session. Postponing this issue.

**Comment by qstokkink** [comment]
This code has been reworked in the latest Tribler version and this issue should now be resolved.
