### ISSUE TITLE
DNS leak?

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5262]
Some of our users showed concern about their system's resolver leaking DNS queries when checking trackers, etc. We should investigate it.

**Comment by qstokkink** [comment]
Isn't this fixed in 7.5?

**Comment by ichorid** [comment]
DHT leak is fixed in 7.5. This one is talking about DNS hostnames for trackers, which are served by system resolver.

**Comment by qstokkink** [comment]
Oh my bad, I thought that was also anonymized now.

**Comment by egbertbouman** [comment]
Torrent checking is not anonymous, only `DownloadManager.get_metainfo` is.

**Comment by qstokkink** [comment]
Should we create a feature to only use anonymized DHT lookups?

**Comment by egbertbouman** [comment]
DHT lookups all rely on `get_metainfo`, so they shouldn't leak. To fix any leakage in `TorrentChecker`, we need to allow it to use a SOCKS5 proxy, and also allow TCP scrape requests in the `TunnelCommunity`.

**Comment by qstokkink** [comment]
> To fix any leakage in TorrentChecker, we need to allow it to use a SOCKS5 proxy, and also allow TCP scrape requests in the TunnelCommunity.

Seems like a reasonable feature for `7.6` to me.

**Comment by egbertbouman** [comment]
I was thinking that maybe we should just allow all TCP requests that have a bencoded response. This would automatically allow both scrape and announce requests to TCP trackers while avoiding tracker specific logic/messages in the `TunnelCommunity`.

**Comment by ichorid** [comment]
@egbertbouman , sounds like a (relatively) simple and robust solution.
