### ISSUE TITLE
visualization issue when changing screens (4k screen issue?)

### ISSUE THREAD

**Issue by herrJones** [Tribler/tribler#5294]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Tribler 7.5.0-rc5

##### Operating system and version: #####
Win10

##### Steps to reproduce the behavior: #####
open tribler on screen 1 (4k in my case)
move to another screen
output is visually garbled. links/commands no longer functioning
![image](https://user-images.githubusercontent.com/1090348/79633188-3f7b9d80-8164-11ea-9273-2711388bc2ed.png)

move back to 1st screen, take full window. links/commands are functioning again
when moving back to the 2nd screen, window looks better but still...
![image](https://user-images.githubusercontent.com/1090348/79633228-78b40d80-8164-11ea-850c-8faba12ffcd0.png)

##### Expected behavior: #####
window + elements should scale properly

##### Actual behavior: #####
they do not :-)  (not always)

**Comment by herrJones** [comment]
to be clear, it also behaves like this in the stable branch.
So: it's not new ;-)
to be improved, no blocking issue

**Comment by devos50** [comment]
Thank you for your report! This is something we should definitely address but most likely not for our upcoming 7.5 release. I will put it in the 7.6 milestone 👍

**Comment by herrJones** [comment]
OK, happy to help you test it!

**Comment by herrJones** [comment]
Hello,
This seems to be resolved!
I don't see this behaviour anymore
