### ISSUE TITLE
Deadlock in VLC causes ui to lock

### ISSUE THREAD

**Issue by hbiyik** [Tribler/tribler#5302]
duplication steps:
add a torrent which has multiple files and stream.
quicly change the files from left menu (basically click spam) after some time ui will freezes.

root cause:
widgets/videoplayerpage.py uses deprecated libvlc.media.parse method to parse metadata. When a new video is set to open when vlc is also trying to parse the metadata of the previos file, it locks, this also locks ui as well.

proposed solution: (currently testing)
not to parse at all, current video player does not use any benefit from parsing.

```
    def parse(self):
        '''Parse a media.
        This fetches (local) art, meta data and tracks information.
        The method is synchronous.
        \deprecated This function could block indefinitely.
                    Use L{parse_with_options}() instead
```

**Comment by devos50** [comment]
Nice find, thanks for investigating! 👍

**Comment by hbiyik** [comment]
Fixed in

https://github.com/Tribler/tribler/pull/5301
