### ISSUE TITLE
[7.5.0-rc5] Headless

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#5303]
https://github.com/Tribler/tribler/blob/devel/src/tribler-core/run_tribler_headless.py

Does not appear to be included in the deb.

`cd /usr/share/tribler && env CORE_PROCESS=1 CORE_BASE_PATH=$(pwd) CORE_API_PORT=8085 /usr/bin/tribler >/dev/null 2>&1 &`

no longer works, falling back to 

```
/usr/bin/tribler >/dev/null 2>&1 &
sleep 10
kill "$(pgrep -f tribler | head -n 1)"
```

is there a more elegant solution like

`/usr/bin/tribler --headless`

?
why is there not even a

`/usr/bin/tribler --help`

?

**Comment by devos50** [comment]
Valid points! I remember that I added the `--headless` flag a long time ago, but that was removed for some reason. We should add it back.

Also, a `--help` flag is helpful but not a top priority at the moment.

**Comment by Dmole** [comment]
Apart from bugs preventing people from using the application, the most fragile parts are the payed exit nodes which occasionally disappear leaving the network un-usable. Having a usable CLI is one part to attracting more exit nodes.

**Comment by Dmole** [comment]
Also 

curl -sX GET "http://localhost:8085/downloads"
{"error": "Unauthorized access"}

What changed there and what is the workaround?

**Comment by hbiyik** [comment]
related: https://github.com/Tribler/tribler/issues/5327

**Comment by Dmole** [comment]
Would a no GUI option count as a GUI suggesstion?
#6113

**Comment by drew2a** [comment]
Now it is possible to run Tribler headless by running it with `--core` argument
https://github.com/Tribler/tribler/blob/035bab82fdf863bff8d1ea81c30dbdc4aeabb3d1/src/run_tribler.py#L33

**Comment by Dmole** [comment]
Why is there

```
run_tribler.py --core
```

and

```
run_tribler_headless.py
```

?
