### ISSUE TITLE
API change without documentation

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#5305]
I used to do such things as

`curl -sX PATCH -H "X-Api-Key: $KEY" "$T/downloads/$H" --data "state=stop"`

but that now results in

`{"error": {"handled": false, "code": "JSONDecodeError", "message": "Expecting value: line 1 column 1 (char 0)"}}`

and both 

https://github.com/Tribler/tribler/blob/devel/doc/restapi/downloads.rst

and 

https://tribler.readthedocs.io/en/devel/restapi/downloads.html

are useless. The API documentation auto generation needs fixing. 

https://github.com/Tribler/tribler/blob/devel/src/tribler-core/tribler_core/modules/libtorrent/restapi/downloads_endpoint.py#L477

indicates it's not completely changed, and "JSONDecodeError" led me to try `--data "{state:\"stop\"}"` but that errored with 

`{"error": {"handled": false, "code": "JSONDecodeError", "message": "Expecting property name enclosed in double quotes: line 1 column 2 (char 1)"}}

so I ended up with  `--data "{\"state\":\"stop\"}"` but all that "@docs(" code looks like dead code at the moment.

**Comment by devos50** [comment]
Thanks for finding this! I agree, docs should be autogenerated and I believe that's the reason why we are using the `aiohttp_apispec` to annotate our endpoints. @egbertbouman could you look into this?

**Comment by egbertbouman** [comment]
To make the REST API more consistent, we made all endpoints use JSON encoding, while before some endpoints also used url-encoding.

For testing, I recommend the Swagger UI, which is available under `/docs`.

**Comment by Dmole** [comment]
@egbertbouman clearly I already figured out the change to a verbose implementation of JSON. This issue is about the dead code and broken documentation as a result said change.

**Comment by hbiyik** [comment]
@Dmole 
If you are looking for a quick solution you can refer to the client api i throw here based on requests module.

https://github.com/hbiyik/repository.biyik/blob/master/plugin.program.tribler/tribler/api/download.py

**Comment by egbertbouman** [comment]
@Dmole My remark about JSON was just to explain _why_ we changed this.

Anyway, the `@docs` decorators are not dead code, they are used to generate Swagger docs. You'll find the docs by starting Tribler, opening a browser, and going to `localhost:8085/docs`.

We haven't really discussed yet what to do with the readthedocs site and the .rst files. I'll look into updating these using the Swagger docs.

**Comment by Dmole** [comment]
@egbertbouman Thanks, I see it's bound;
```
netstat -nl | grep -P "8085|Address"
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 127.0.0.1:8085          0.0.0.0:*               LISTEN
```
My attempt to get at it with a SOCKS proxy did not work,
is there a way to un-bind it?

(I'd check the docs but can't without knowing how to bind to another IP lol)

**Comment by Dmole** [comment]
@egbertbouman nope that documentation is also broken; I installed local copy of Tribler, put localhost:8085/docs in chromium, and got 
`{"error": "Unauthorized access"}`

**Comment by egbertbouman** [comment]
Which version of Tribler are you running? Currently, only the devel branch has Swagger support.

**Comment by Dmole** [comment]
@egbertbouman 7.5.0-rc5, so It appears there is no user documentation (users are not likely to build their own from the devel branch).

**Comment by Dmole** [comment]
Looks like someone fixed readthedocs so that it's no longer empty.
