### ISSUE TITLE
File checking is back!

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#5306]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
7.5.0 >rc3
##### Operating system and version: #####
Windows 10
##### Steps to reproduce the behavior: #####
Switch anonymous to normal
##### Expected behavior: #####
No file checking
##### Actual behavior: #####
File is checked again and again as soon as you switch from anonymous to none and back!!!!

**Comment by ichorid** [comment]
This is a known issue. Each anonymity level uses its own Libtorrent session. Sessions are independent of each other, so when you switch anonymity level you essentially reload the torrent. We will consider speeding up torrent reloading in the future.

p.s.
this is a minor issue, so using three exclamation marks in your report is a bit of an overkill :wink:

**Comment by ichorid** [comment]
Fixed in #5317
