### ISSUE TITLE
Libtorrent downloads require a Tribler restart

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#5307]
Seen several times on Mac with 7.5 RC5.

Downloads stall to 0 Kbps, with well seeded torrents of 100+ peers. Tribler restart resumes downloading to 5+ MBps. This performance bug is reproducible when downloading an extra file within a multi-file swarm. Feels like some sort of locking issue introduced with refactoring. Can we add this performance bug to the application tester infrastructure? A time investment in this test tooling is very much appreciated.

Happens on regular basis, leading to a frustrating tribler usage experience. Given our high ambitions around critical infrastructure and solid funding position, we need to shift to delivery of [medical-grade software reliability](https://github.com/Tribler/tribler/issues/1#issuecomment-548706741) as discussed on _issue 1_.

**Comment by qstokkink** [comment]
We've seen this sort of behavior in the past:
https://github.com/Tribler/tribler/issues/3379#issue-290404226
https://github.com/Tribler/tribler/issues/5290#issuecomment-612870277
Could be related.

**Comment by ichorid** [comment]
@synctext , does the problem only manifests itself with anonymous downloads?

**Comment by synctext** [comment]
This is only with direct download. No anon tunnels.

**Comment by aaguilarjimenez** [comment]
> This is only with direct download. No anon tunnels.

In my case (explained on #5319 ) I always use 1 hop of anonymity. As a refresher: Ubuntu MATE 20.04, Tribler 7.5.0-rc5.

**Comment by synctext** [comment]
closing this older issue, as the newer issue has more user reports and details.
