### ISSUE TITLE
[7.5-rc5] Excluding files blocks included files from download when sharing a piece

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5326]
Exclude some files from a multifile torrent. If one of the excluded files shares a piece with included file, included file will never finish downloading. In other words, excluding files/pieces take priority over including files/pieces.

Libtorrent version 1.2.2.0

**Comment by synctext** [comment]
Sadly, if Tribler fails to download it is definitely our problem.
Re-open if still also occurs within latest Tribler shipped libtorrent.

**Comment by ichorid** [comment]
Using Tribler daily, never seen since :shrug:
