### ISSUE TITLE
[7.5-rc5] Ask invalid

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5329]
After running Tribler for awhile.
Also there are lots of reports on Reporter for this.
![image](https://user-images.githubusercontent.com/2509103/82916420-4f13b080-9f72-11ea-95b1-42cbe502bf43.png)

**Comment by loadletter** [comment]
I've had that issue running the latest release-7.5 https://github.com/Tribler/tribler/commit/8acd2f942d2d884c49ec3142803ef066287513b5
But it happened a couple of minutes after startup and after restarting it ran fine for hours

**Comment by devos50** [comment]
The issue is most likely that an incoming, invalid ask (or bid) in the market is triggering a `RuntimeError` which is not catched correctly. I will fix it after our paper deadline tomorrow.
