### ISSUE TITLE
[7.5-rc5] Getting a large list of downloads is super-slow when processing a channel

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5330]
On a weak machine with approx 500 downloads (mostly channels) requesting the list of downloads from the core via the `/downloads` REST endpoint takes about 60 seconds. During this period nothing is written in the console, implying the core is stuck.

Possibly related to #5296

**Comment by ichorid** [comment]
@egbertbouman  , could you please comment on this?

**Comment by egbertbouman** [comment]
Do you have the details panel open to the peers or files tab? If so, Tribler will also add peers/files to the downloads, which is an expensive operation. Having said that, 60 s seems *way* too high.

I'll see if I can reproduce it.

**Comment by ichorid** [comment]
@egbertbouman , you were right, the problem was in the channels. Apparently, when a big channel is being processed (which was the case), downloads endpoint would get stuck on channels query.

**Comment by egbertbouman** [comment]
I see that the download endpoint is getting stuff from the database. I guess channel processing is also doing a lot of database stuff. Could it be blocking there?

**Comment by synctext** [comment]
@ichorid do you have or can you craft a unit test to trigger this bug? 
(btw as briefly discussed, I've tentatively added you to the reputation system team, Issue 31 from 7 years ago).

**Comment by ichorid** [comment]
@synctext , I'll have to think about how to build a unit test for this. I only noticed it on a super-slow machine seeding hundreds of torrents.
