### ISSUE TITLE
Trackers are lost when download is added with magnet url.

### ISSUE THREAD

**Issue by hbiyik** [Tribler/tribler#5332]
How to reproduce:

Add a download in the gui, where metadata does not exits and wait for torrent info endoint fully download the metadata.

Add the torrent after metadata is download. The trackers from the magents are lost in he download, only pex and dht is available.

To my analysis,

When metadata info is queried, the query is done only with infohash without the trackers. And response is chached.
https://github.com/Tribler/tribler/blob/7c955cb2f6ec6463321b65ecae0436041a464aca/src/tribler-core/tribler_core/modules/libtorrent/restapi/torrentinfo_endpoint.py#L83

https://github.com/Tribler/tribler/blob/7c955cb2f6ec6463321b65ecae0436041a464aca/src/tribler-core/tribler_core/modules/libtorrent/restapi/torrentinfo_endpoint.py#L90

When the download is added, the metadata from the cache is used, therefore the trackers are lost.
https://github.com/Tribler/tribler/blob/7c955cb2f6ec6463321b65ecae0436041a464aca/src/tribler-core/tribler_core/modules/libtorrent/download_manager.py#L459

I did provide a fix as below commit, but not sure this is the best way..
https://github.com/hbiyik/tribler/commit/4d712cb8bb9db7240d8a6ffaa9916d96f0d834bf#

**Comment by egbertbouman** [comment]
You're right, thanks for letting us know! Your fix seems fine to me, so feel free to open a PR if you like.

I guess this is only the case when the magnet link includes trackers that aren't included in the metainfo, which is why we missed it.

**Comment by ichorid** [comment]
@hbiyik , thanks for finding both the bug and the solution! :+1: 
If you're going to open a PR for this, please do it against the current `release-7.5` branch. Also, don't forget to add a unit test for this.

**Comment by hbiyik** [comment]
Ok, currently i am working on https://github.com/Tribler/tribler/issues/5327. So i wont put a pr for this for a while.
