### ISSUE TITLE
[7.5-rc5] on_core_memory_history crash on shutdown

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5352]
Tribler crashes on shutdown sometimes:

```python
[PID:26512] 2020-06-04 10:27:21,536 - ERROR <tribler_window:107> root.on_exception(): Traceback (most recent call last):
  File "/home/tribler/src/tribler-gui/tribler_gui/debug_window.py", line 630, in on_core_memory_history
    for mem_info in data["memory_history"]:
KeyError: 'memory_history'
```

**Comment by devos50** [comment]
IIRC, the debug window object is only created once a user clicks the 'debug' button in the GUI. So would this only happen when the debug window is open?

Should be easy to fix by just checking whether the `memory_history` key exists.

**Comment by ichorid** [comment]
Yes, the debug window was open

**Comment by egbertbouman** [comment]
Should be fixed in https://github.com/Tribler/tribler/pull/5356.
