### ISSUE TITLE
[7.5] Subscribed channels list not updated dynamically

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5358]
7.5-rc6
When subscribing to a channel, the subscribed channel does not appear in the "subscribed" list unless the list is regenerated by clicking the "Subscribed" button another time. The list should be updated dynamically on Core notifications instead.

**Comment by devos50** [comment]
@ichorid do we want this for the 7.5.2 release?

**Comment by ichorid** [comment]
Probably not. Fixing this can bring more problems with the GUI. Let's move it to 7.6

**Comment by ichorid** [comment]
Fixed in 7.6.0 by total refactoring of channels interfase.
