### ISSUE TITLE
GUI crash on DHT debug tab

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5359]
Latest release-7.5.

Clicking on DHT tab in the Debug window crashes Tribler.

```
Traceback (most recent call last):
  File "/home/tribler/src/tribler-gui/tribler_gui/debug_window.py", line 456, in on_dht_statistics
    def load_dht_statistics_tab(self):
AttributeError: 'DebugWindow' object has no attribute 'dht_tree_widget'
```

**Comment by egbertbouman** [comment]
It has been running fine for me. Also, I can't find any mention of `dht_tree_widget` anywhere in release-7.5. Could you point me to the offending line on GitHub?

**Comment by ichorid** [comment]
That is really strange. You removed `dht_tree_widget` in the latest PR. Was I so quick that I ran into a race condition between `git` and Pycharm? :dizzy_face:
