### ISSUE TITLE
The Tribler GUI is not catching import errors in the core

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5360]
The Tribler GUI won't show the crash dialog when there is an import error in the core. This is trivial to reproduce by having an incorrect IPv8 pointer. The `ImportError` is logged to stdout, but not communicated to the core.

To catch nasty Windows errors (e.g., failure to load DLL files or incompatibilities with libraries), it is important that we also capture these errors. We used to use `sys.excepthook` for this, but that has been removed during the `asyncio` refactoring.

**Comment by egbertbouman** [comment]
I just checked out both v7.4.2 and v7.5.0-RC6 and searched for `sys.excepthook`. I can't find any use that was in v7.4.2 but not in v7.5.0-RC6, so at least it's not removed during the refactoring. It's still in `TriblerWindow`.

**Comment by ichorid** [comment]
I just tested out @devos50 's solution from #5361. Works perfectly.
Without it, core crashes result in "Could not connect to the core" timeouts.
