### ISSUE TITLE
Use uvloop where available

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5374]
Moving to Asyncio enables us to use faster, `uvloop` reactor on those systems (Linux, Mac?) where available. Tests with Tribler exit nodes show that `uvloop` reduces CPU usage by 30% while also improving memory usage. This is especially important for low-tier platforms, such as [ARM](#5327).

Enabling it is a matter of literally two lines of code:
```python
import uvloop
asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
```
for systems with older `uvloop` version (e.g. Debian) or

```python
import uvloop
uvloop.install()
```
for everything else.

**Comment by synctext** [comment]
interesting. We need this indeed to build our community of users. Given the facinating findings of our bug reporter. Let's edit the next 7.6 milestone. "Amazing stability" as the first keywords of that release. No big changes for now, perfect tuning like this.

**Comment by devos50** [comment]
I would recommend to look into this once [our application tester](https://github.com/tribler/application-tester) is stable again. Then we can more easily test for unexpected behaviour/edge cases.

**Comment by qstokkink** [comment]
We will not include uvloop. Our network activity that requires high throughput has now been implemented in Rust.
