### ISSUE TITLE
I can't open Tribler.

### ISSUE THREAD

**Issue by PhantomXL** [Tribler/tribler#5380]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

Tribler 7.4.4 Ubuntu

##### Operating system and version: #####

Ubuntu 20.04 LTS

##### Steps to reproduce the behavior: #####

1st method:

I used the command "/usr/bin/tribler", with which I have opened Tribler multiple times.

2nd method:

I clicked the GUI icon from the start menu.

##### Expected behavior: #####

Tribler opens.

##### Actual behavior: #####

1st method:

![Screenshot at 2020-06-17 22-11-01](https://user-images.githubusercontent.com/45405952/84941009-67966700-b0e9-11ea-9607-d790f3a1b434.png)

2nd method:

It just didn't open. (I checked the system monitor and through the terminal.)

##### Relevant log file output: #####

I couldn't find any useful logs.

//I did reinstall it and try again and it didn't work.

**Comment by devos50** [comment]
On Ubuntu, we write the log files to `/tmp`. Could you check that directory and see if there are any errors in these logs?

**Comment by PhantomXL** [comment]
I know. I just didn't know how far to look. I think I found the faulty line.

The error reads as follows:

util:68 (ipv8.util) Deferred errback fired: [Failure instance: Traceback (failure with no frames): <class'RuntimeError'>: Peers request timeout

This particular error is the only one I have encountered that was classified as an error and appears more than 20 times in one specific log. There are also a ton of warnings in this log and another one that has no errors. If it helps, I can send the log files through mail.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by devos50** [comment]
That's not a criticial error (e.g., does not crash Tribler) and can happen if a peer goes offline. For some easier debugging, could you make a modification in your `tribler` startup script? You can find the location of this script by running the following command: `which tribler`. If you open that file, you will the following line:

```
exec /usr/share/tribler/tribler "$@" > `mktemp /tmp/$USER-tribler-XXXXXXXX.log` 2>&1
```

Changing that line to `exec /usr/share/tribler/tribler "$@"` will redirect all stdout/stderr to your terminal. Feel free to post the terminal output here 👍

**Comment by ichorid** [comment]
@PhantomXL also could you please try out our latest RC6 for the upcoming Tribler 7.5? It is on the same "Releases" page on GitHub.
7.5 changes quite a lot, so that could solve your problem.

**Comment by PhantomXL** [comment]
7.5 fixed it. Thanks for your help.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by devos50** [comment]
Great!
