### ISSUE TITLE
Stop packing test data in the pyinstaller package

### ISSUE THREAD

**Issue by hbiyik** [Tribler/tribler#5382]
the test files are located in the source directory and pyinstaller directly bundles all the subfolders in it it.

this causes extra 5~10 mb in the packaged application. May be tests should be in a total seperate dir rather than inside the module:

ie under tribler-core
 -> tests (and all tests under here)
 ->  tribler_core (the main module)

![resim](https://user-images.githubusercontent.com/24766436/84963061-a7207b80-b108-11ea-915a-bfbff3483eda.png)

**Comment by devos50** [comment]
Good find, thanks!

The problem here is that the tests are now part of the source code, therefore making it non-trivial to filter out the tests. However, at the very least, we can remove the large files that we use during our unit tests. @ichorid your thoughts?

**Comment by qstokkink** [comment]
@devos50 you don't consider the x86 installer being broken to be a blocker?

**Comment by ichorid** [comment]
The problem with placing tests in a separate directory structure is that it makes harder to organize them. I would say we should add some kind of filename filter for omitting `test_` files and directories from being packaged by the installer.

**Comment by devos50** [comment]
My apologies, I didn't properly parse the second part of the issue. That is indeed a major problem.

One thing I particularly like about the new file structure is the fact that tests are close to the source code they tests. I think having some filter in the pyinstaller script that removes the files with a `test_` prefix should work (but this is a separate issue).

**Comment by qstokkink** [comment]
Maybe we should fork this issue into two issues for clarity?

**Comment by devos50** [comment]
The critical issue is moved into #5385

**Comment by hbiyik** [comment]
https://github.com/Tribler/tribler/issues/5385

seperated the missing libraries issue to another ticket

**Comment by qstokkink** [comment]
Nice. I'd propose we move the remainder of this issue to 7.6 then, as it is non-critical.

**Comment by devos50** [comment]
Yeah good point, let's not mess too much with our installers so close before a release.

**Comment by qstokkink** [comment]
In the Docker build of PR #8108 there is a list of test directories that need to be stripped before building.

Our `build.yml` can adopt/copy the same strategy to remove non-essential files. That will finally resolve this issue.
