### ISSUE TITLE
Codec libs are missing in windows pacakge

### ISSUE THREAD

**Issue by hbiyik** [Tribler/tribler#5385]
codecs seems to be missing in x86 package, this is also visible from the size of the packages 32 it package (~50mb) is half the size of 64 bit (~100Mb)

![resim](https://user-images.githubusercontent.com/24766436/84965185-7fccad00-b10e-11ea-8105-2e9bb675b07e.png)

**Comment by devos50** [comment]
Thanks for splitting the issue!

**Comment by ichorid** [comment]
We can fix it later in 7.5 bugfix releases.

**Comment by hbiyik** [comment]
Good thing is, it is in 32bit windows package, which i think a very few users would prefer. I read somewhere windows even will drop 32bit in some time.

**Comment by devos50** [comment]
It seems that we are copying fewer files on 32-bit, resulting in a (hidden) error when loading the VLC libraries.
