### ISSUE TITLE
test_recursive_commit_channel_torrent hangs on Windows

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5391]
Encountered during the tests, also see [here](https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_async_win64/696/console).

It seems that `test_recursive_commit_channel_torrent` hangs since the tests timed out after six minutes:

```
test_recursive_commit_channel_torrent (test_channel_metadata.TestChannelMetadata) ... + FAILURE=127
```

@ichorid do you have any idea what could be causing this?

**Comment by ichorid** [comment]
No idea. I'll handle this.

**Comment by ichorid** [comment]
The test is deterministic but can be quite long. Is it possible that the tester machine's disk was busy with something at that moment?

**Comment by devos50** [comment]
> Is it possible that the tester machine's disk was busy with something at that moment?

That's always possible but I don't think there was much other activity when that test was running. At least not so much activity that the test suite is timing out.

**Comment by devos50** [comment]
It also hangs on Mac:

```
test_recursive_commit_channel_torrent (test_channel_metadata.TestChannelMetadata) ... /Users/tribler/Documents/workspace2/workspace/GH_Tribler_PR_Tests/PR_async_mac/gumby/scripts/wrap_in_temp_home.sh: line 34: 62378 Terminated: 15          $*
```

**Comment by ichorid** [comment]
Also hangs on Linux after about two dozen trys

**Comment by devos50** [comment]
I don't think this is still an issue with pytest right?
