### ISSUE TITLE
Our arch linux builder is broken

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5393]
It seems that our [Arch Linux builder](https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Build-ArchLinux/) does not work anymore after the refactoring. We do not officially support Arch Linux so this issue should not give much priority to this issue. However, having a build pipeline for Arch that at least passes can help us to expand Tribler to more platforms.

**Comment by drew2a** [comment]
We do not support arch anymore.
