### ISSUE TITLE
[7.5.0] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 108: invalid continuation byte

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5394]
From the error reporter (happens on Windows):

```
Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\core_manager.py", line 48, in on_core_read_ready
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 108: invalid continuation byte
```

This happens immediately on startup. The error points to the following line in `core_manager.py`:

```
print(raw_output.decode().strip())
```

**Comment by devos50** [comment]
Out of the 42 crash reports, 19 are due to this error (or variations of it). Increasing the ticket priority.

**Comment by synctext** [comment]
This is preventing users from starting Tribler! Reported in the wild on TorrentFreak:
> "[error on win 10 and do not start](https://torrentfreak.com/academic-torrent-client-offers-a-safe-haven-for-pirate-sites-200623/#comment-4967431249)"

Please release this as a "hotfix" and push 7.5.1 to the frontpage. @ichorid @devos50 Only a 3-line change, guess a code review will do.
