### ISSUE TITLE
Forum.Tribler.org not reachable

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#5404]
Forum not reachable!!!!

**Comment by devos50** [comment]
We are aware of the issue (infrastructure hiccups). It will most likely be fixed tomorrow, early in the morning. In the meantime, please post any issues on GitHub 👍

**Comment by devos50** [comment]
The forums are up again!

**Comment by synctext** [comment]
http://explorer.tribler.org/statistics and http://statistics.tribler.org/ also on ToDo list?

**Comment by devos50** [comment]
Working on it!
