### ISSUE TITLE
Himba guest OSes can't connect to network after reboot

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5406]
We got a problem after updating Debian Proxmox host OS. After reboot, `sysctl` does not apply proxmox-specific kernel parameters stored in `/etc/sysctl.d/pve.conf`, namely `bridge-nf-call-iptables` and friends. This parameter must be set to `0`. Otherwise, the system **drops packets addressed to bridged virtual machines**.

Most probably, the problem is a result of Debian/Ubuntu `sysctl` [applied too early during the boot process](https://bugs.launchpad.net/ubuntu/+source/procps/+bug/50093), when some drivers are still not loaded. 

In the latest version of Debian `/etc/rc.local` is deprecated, so no easy solution...

Until we solve this problem, the following command must be applied manually after each Himba reboot:
`sysctl -p /etc/sysctl.d/pve.conf`

**Comment by devos50** [comment]
This is also required when restarting `pve-firewall` (e.g., after whitelisting IPs through the command line).

**Comment by qstokkink** [comment]
This no longer seems relevant now that we have switched to GitHub Actions for all our activities.
