### ISSUE TITLE
broken link in wiki page

### ISSUE THREAD

**Issue by smichea** [Tribler/tribler#5407]
in the [specification wiki page](https://github.com/Tribler/tribler/wiki/Anonymous-Downloading-and-Streaming-specifications) the link to   "main parts of the Tor wire protocol within Tribler" (https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/conversion.py#L19) is broken.

**Comment by qstokkink** [comment]
Thanks for the heads-up, that was quite out of date. I updated the link with the current wire-format specification.

**Comment by egbertbouman** [comment]
I also just updated the encryption section a bit since it was saying we were still using ECB.
