### ISSUE TITLE
Hidden seeding experiment broken after merge in devel branch

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5408]
It seems that our validation experiments are broken after the latest release commit merge into `devel`, see [here](https://jenkins-ci.tribler.org/job/validation_experiments/job/validation_experiments/706/).

**Comment by devos50** [comment]
https://github.com/Tribler/gumby/pull/456 fixes most validation experiments, but the hidden seeding experiment remains broken. @egbertbouman could you have a look at this?

**Comment by egbertbouman** [comment]
Sure, I'll take a look.

**Comment by egbertbouman** [comment]
It took a while to find the issue since there were no errors. It should be fixed in https://github.com/Tribler/gumby/pull/457.

**Comment by qstokkink** [comment]
I restarted the validation experiments after the merge, see: https://jenkins-ci.tribler.org/job/validation_experiments/job/validation_experiments/711/

**Comment by devos50** [comment]
Thanks, seems to work now!
