### ISSUE TITLE
Collection node object has no attribute 'torrent_exists'

### ISSUE THREAD

**Issue by hbiyik** [Tribler/tribler#5411]
Steps to duplicate:
add a channel
add a sub channel (collection) to this channel
add a torrent to this subchannel from magnet url.

Result is:
![resim](https://user-images.githubusercontent.com/24766436/85768984-e0b14200-b719-11ea-82cc-0ee5bfd3a74e.png)

I think it is referring this part:
https://github.com/Tribler/tribler/blob/c98871b033ac9e1ccc9cecd242734e8b9bf3e1d0/src/tribler-core/tribler_core/modules/metadata_store/restapi/channels_endpoint.py#L281

**Comment by boogieeeee** [comment]
this seems like fixing it, not sure about the consequences

https://github.com/hbiyik/tribler/commit/de22997baf4e46c8b09d950f68b06ba0be62fd43

**Comment by EZhivaikin** [comment]
Same error on Tribbler 7.5.1
