### ISSUE TITLE
[7.5.1] Mac Yosemite - Import error: dlopen(/Applications/Tribler.app/Contents/MacOS/..., 2): Symbol not found: __os_activity_create

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#5419]
User reporting on broken Mac installer here: https://torrentfreak.com/academic-torrent-client-offers-a-safe-haven-for-pirate-sites-200623/#comment-4968486884
```
sadly support appears to have skipped 2 versions, now leaving Yosemite and El Capitan behind (OSX 10 and 11). Contrary to what it says on the download page (from yosemite and up).

Error message when opening the Tribler unix executable in terminal, following the reluctance of Tribler to open:

Import error: dlopen(/Applications/Tribler.app/Contents/MacOS/..., 2): Symbol not found: __os_activity_create
Referenced from: /Applications/Tribler.app/Contents/MacOS/... (which was built for Mac OS X 10.12)
Expected in: /usr/lib/libSystem.B.dylib
in /Applications/Tribler.app/Contents/MacOS/...
```

**Comment by devos50** [comment]
Tribler supports Mojave and higher. Given that Yosemite released in 2014, that older macs have pretty decent (long-term) support for an upgrade to Yosemite, and that Big Sur is coming out this fall, I would say that Tribler currently supports a large user base on Mac. That said, if we would wish to support older OS X versions, I have to wipe all data from the current Mac builder, downgrade its OS and setup the build process all over again. I am not sure if this is worth the time investment.

So, we should either update the website or modify our Mac machines.

**Comment by synctext** [comment]
ahh, OK, no easy fix.

**Comment by devos50** [comment]
Unfortunately not. Therefore, I suggest to bump the minimum required version of macOS on the website.

**Comment by devos50** [comment]
Fixed by https://github.com/Tribler/tribler.github.com/pull/67
