### ISSUE TITLE
Please add support for foreign languages (Russian, Chinese, Arabic, etc.)

### ISSUE THREAD

**Issue by pbuk2** [Tribler/tribler#5424]
#### Please, fill all relevant items: ####

- [ ] I have read CONTRIBUTING.rst

- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

**Comment by devos50** [comment]
Thanks for your feedback! This is definitely something we want to implement in an upcoming version of Tribler, however, our current focus is on performance and stability. It seems that we already have [this](https://github.com/Tribler/tribler/issues/1753) open issue, addressing the same. Therefore, let's discuss progress of a multi-langual Tribler on that ticket. 👍
