### ISSUE TITLE
0-size channels appear in "Discovered" tab

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5442]
Empty channels must be filtered out and don't clog the channels list.

**Comment by synctext** [comment]
Usually users leave them named "New Channel". The rename function is difficult to find. The old channels interface forced users to enter a unique channel name after "create channel" button was activated. Please consider using that approach or alternative solution. Same for "create directory" perhaps.

**Comment by hbiyik** [comment]
I can confirm that i had to look around to find rename button then found it in the context menu. May be when first created channel name can be in edit mode, after user enters name, then create request can be posted.

**Comment by ichorid** [comment]
Dialog for new names is now added in #5446
