### ISSUE TITLE
Revisit the bundling of the Visual C++ runtimes in Windows

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5444]
In Windows 64-bit, we are bundling the Visual C++ runtime (`MSVCP140.dll`) by embedding an installer. In our 32-bit builds, we are bundling both `MSVCP120.dll` and `MSVCP140.dll`. After our migration to Python 3, there are two issues:
- ~On 32-bit, there are no dependencies that load `MSVCP120.dll`. Therefore, this DLL can be removed.~
- It seems that pyinstaller already bundles the C++ runtimes, so it might be worthwhile to see if Tribler runs without having these DLLs installed system-wide.

**Comment by hbiyik** [comment]
Acthung though.

I am not %100 sure that latest windows (win10) C runtime dlls would also work in earlier versions of windows (ie: win8, vista etc). Never the less they seem to work, but no guarantee to my knowledge.

https://pyinstaller.readthedocs.io/en/stable/usage.html#windows

**Comment by devos50** [comment]
You're right. This is quite something and it might not be preferable for a minor release. I will postpone this issue to the next release.

I updated the 32-bit build already so we can use that .exe as a test if building with the v142 tools works correctly on all platforms 👍

**Comment by devos50** [comment]
Observations:
- I removed the system-wide runtime from one of our deployment machines (Windows 64-bit) and Tribler seems to run fine.
- PyInstaller seems to bundle `MSVCP140.dll` and `MSVCP140_1.dll`.

**Comment by hbiyik** [comment]
I think it is bundled from the redistributed vcruntime of python installation however, Win7 cases still should be a problem:
https://github.com/pyinstaller/pyinstaller/pull/2487

**Comment by qstokkink** [comment]
The builders have recently been updated and minimized. That should resolve this issue.
