### ISSUE TITLE
The identity database is created in ./sqlite when running Tribler

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5450]
When running Tribler, the `IdentityDatabase` is created in the current work directory (`./sqlite/identity.db`), and not in the state directory where the other databases are also located (`~/.Tribler/sqlite/identity.db)`. This behaviour is resulting in an error when running the tunnel helpers, since the current working directory is not writable for the `tunnel_helper` process. I'm not sure what happens in a frozen environment and where the identity database is being written away.

Furthermore, I found out that the `CommunicationManager` (which in turns creates the `IdentityManager` which creates the `IdentityDatabase`) is loaded in the `initialize` method of the `IdentityEndpoint` class. I'm not sure if this is a preferred design since the sqlite database is now managed by the `REST` endpoint.

@qstokkink can you comment on the above points?

**Comment by qstokkink** [comment]
The whole Identity framework is _supposed_ to be a lazy-load mechanism. It _should_ only produce files if the community is loaded or a call is made.

**Comment by qstokkink** [comment]
You could temporarily alleviate this issue by setting the `working_directory` of the IPv8 instance to the appropriate folder: `~/.Tribler/sqlite/`. However, still, this database file should not be there in the first place.

**Comment by qstokkink** [comment]
I can reproduce this when running IPv8 standalone, it is not a configuration error.

**Comment by devos50** [comment]
We probably have to pass the right state directory to [here](https://github.com/Tribler/py-ipv8/blob/13d933461d5cdbe6224066799186b377c905786f/ipv8/attestation/communication_manager.py#L198) when starting the REST API.

> The whole Identity framework is supposed to be a lazy-load mechanism. It should only produce files if the community is loaded or a call is made.

If I start Tribler (either in release mode or locally), the `identity.db` file is created even when I do not explicitly make calls to the identity framework.

**Comment by qstokkink** [comment]
> We probably have to pass the right state directory to here when starting the REST API.

Yes, that pulls from the IPv8 `working_directory` field.

> If I start Tribler (either in release mode or locally), the identity.db file is created even when I do not explicitly make calls to the identity framework.

I can reproduce this when running IPv8 standalone, it is not a configuration error.
