### ISSUE TITLE
Tunnel test fails on Windows

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5461]
After merging `release-7.5` into `devel` I had to disable a couple of failing tests:
https://github.com/Tribler/tribler/commit/c1df2bbac897b8e63f889ca8d8598bd3f62796be

We should fix these ASAP because :godmode:  knows what kind of problem lurks behind them...

**Comment by egbertbouman** [comment]
Fixed in https://github.com/Tribler/tribler/pull/5517.
