### ISSUE TITLE
Setting up Linux development guide is outdated

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5467]
We need to make a few changes to the guide [on how to setup a dev environment on Linux](https://github.com/Tribler/tribler/blob/devel/doc/development/development_on_linux.rst):
- The dependencies of Bitcoinlib are not needed anymore - bitcoinlib should be installed separately.
- Tribler also needs the `libnacl`, `aiohttp` and `aiohttp_apispec` dependencies. They are not only for IPv8.

**Comment by qstokkink** [comment]
>     * Tribler also needs the `libnacl`, `aiohttp` and `aiohttp_apispec` dependencies. They are not only for IPv8.

That should already be covered by:

> ``cd src/pyipv8``
> ``pip install --upgrade -r requirements.txt``
