### ISSUE TITLE
Download location option does not work

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5470]
To reproduce, change the option through the GUI, then try downloading something. Observe the download going into the default (e.g. "Downloads/TriblerDownloads") dir. 

I experienced it on Ubuntu 20.04 with the target dir path containing Cyrillic characters.

**Comment by devos50** [comment]
I cannot reproduce it on Mac when trying to change the download location to a directory named `шшшшш`: the files end up in that directory. What does the 'destination' say in the GUI? Can you reproduce it with non-Cyrillic characters in the path?
