### ISSUE TITLE
Remove run_tribler.py cp65001 support

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#5481]
For some reason the `cp65001` fix has been moved to after the imports, but it should be the first thing in the file https://github.com/Tribler/tribler/blob/devel/src/run_tribler.py:

https://github.com/Tribler/tribler/blob/1aea0280026841fc740e7e302156616473dafaa7/src/run_tribler.py#L7-L34

Interestingly enough the comment is still at the top of the file though, maybe some formatting tool automatically changed this?

UPDATE: This code can now be completely removed, `cp65001` is supported by default since Python 3.3.

**Comment by ichorid** [comment]
Yep, this is probably moved by the pre-commit thing.

Is this still a problem in Python3?

**Comment by qstokkink** [comment]
Just checked, this code can now be removed:

https://docs.python.org/3/library/codecs.html#standard-encodings

Since Python 3.3 there is cp65001 support by default!

**Comment by qstokkink** [comment]
I guess this is not actively hurting anything, so I'll label it as an enhancement.
