### ISSUE TITLE
Changing a file in the video player freezes Tribler

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5483]
When running Tribler in a frozen environment on Mac, I can make Tribler frozen by streaming a video, and changing to another file. I suspect that this is related to the VLC library loading behaviour that also caused the core to crash when loading it early.

**Comment by hbiyik** [comment]
I remember i fixed similar case in devel branch, is it on 7.5?

https://github.com/Tribler/tribler/issues/5302

**Comment by devos50** [comment]
Thanks for the link! Does this freeze also happen on Linux?

This fix is indeed not in the `release-7.5` branch. We are using `media.parse` to get the duration of the full video, ensuring that we can seek in the video. Removing the call to `self.media.parse` seems to break this functionality.

**Comment by hbiyik** [comment]
Yes it is happening in linux also, since the seeking feature was not properly working in past (before i rewrote torrent sequential download mechanism), i just disabled seeking, and both parsing, so it wont seek and and it wot deadlock  as well.

It is possible both seek, and parse with the updated VLC interface, effort /benefit ratio was meh to me at that time.

**Comment by devos50** [comment]
@hbiyik that's good to know! It might have something to do with the VLC version.

So, our options are:
1) Disable media parsing, resulting in the situation where a user is unable to seek since the duration of a media file is not determined. I argue this completely breaks the video player.
2) Disable the entire VLC player for this release.
3) Investigate time to investigate this bug, knowing that this might be something within VLC.

I do not think it is worth exploring this further. For the upcoming release, I'm fine with disabling it until we have reached consensus on what the future of the embedded video player is.

**Comment by devos50** [comment]
@ichorid @qstokkink @egbertbouman what's your opinion on the course of action to address this? We can also discuss this Tuesday if needed.

**Comment by qstokkink** [comment]
Wednesday this week right?

On topic: I feel as though we're slowing moving towards stripping out VLC anyway, so disabling should be fine.

**Comment by devos50** [comment]
@qstokkink ah yes it's Wednesday indeed! Thanks for your feedback 👍

**Comment by ichorid** [comment]
Just disable VLC on Mac completely.

**Comment by devos50** [comment]
@ichorid note that it also happens on Linux and possibly on Windows

**Comment by ichorid** [comment]
I would say disable it completely then.

**Comment by devos50** [comment]
Given the current sentiment towards the video player, and its very uncertain future, I will disable loading the VLC library for now.

**Comment by devos50** [comment]
Since we are disabling VLC and we have to discuss some other stuff about the video player, I will move this issue to the 7.6 milestone.

**Comment by ichorid** [comment]
RIP VLC
