### ISSUE TITLE
Peers are being dropped when running Tribler on Windows

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5485]
After our upgrade to Python 3.8, it seems that shortly after starting Tribler, peers are being dropped. The debug panel shows a few peers, but after a few minutes, these peers are gone. Anonymous downloads/TrustChain introduction requests are failing after around one minute.

Observations:
- This happens both when running Tribler from source on our Windows building machine as well as running it from a frozen environment.
- I have seen it both on 32-bit and 64-bit.

**Comment by devos50** [comment]
After some testing, it seems to occur when the `ProactorEventLoop` is used, which is the default loop in Python 3.8. I would suggest to fallback to the `SelectorEventLoop` for now, until we debugged/investigated the bug further.

**Comment by egbertbouman** [comment]
Nice, good to hear my tip seems to have worked!

**Comment by ichorid** [comment]
:facepalm: :face_with_head_bandage:

**Comment by egbertbouman** [comment]
UDP support was only added recently to `ProactorEventLoop`, so maybe there are still some issues with it?

**Comment by qstokkink** [comment]
> I would suggest to fallback to the SelectorEventLoop for now, until we debugged/investigated the bug further.

The only downside I see to using the `SelectorEventLoop` is that it does not support Windows pipes (which we don't use) and doesn't use Windows IOCP, which is a bit better for multicore event handling.

I'd vote for just using `SelectorEventLoop` for the foreseeable future, without further debugging/investigating the `ProactorEventLoop`.

**Comment by ichorid** [comment]
Reopened https://github.com/Tribler/tribler/issues/5435. That's the downside.

**Comment by qstokkink** [comment]
Ok, in that case I guess it's still worth it to try and get the `ProactorEventLoop` up and running.

**Comment by devos50** [comment]
Given that the `SelectorEventLoop` seems to still work, I do not consider this as a blocker for the 7.5.2 release anymore.
