### ISSUE TITLE
Windows GUI tests randomly failing

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5494]
The GUI tests on Windows are randomly failing after our upgrade to Python 3.8. See for example [here](https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_GUI_win64/795/console). From the output, it seems that it still uses an `IocpProactor` proactor, even though this is disabled on Windows.

**Comment by devos50** [comment]
Still not fixed, see https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_GUI_win64/800/

**Comment by devos50** [comment]
Still failing, even after merging https://github.com/Tribler/tribler/pull/5502 ...

**Comment by qstokkink** [comment]
This also happened on Mac: https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_GUI_macOS/855/console

**Comment by devos50** [comment]
I haven't seen this issue after we migrated to pytest. Note that we also made some improvements to the GUI tests, in particular, using a real Tribler core. Therefore, let's close this issue for now.
