### ISSUE TITLE
Gui streaming layout problem

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/tribler#550]
I found a couple problems while streaming a file using the home/thumbnail stuff. When the streaming started this happened:
![streaming_bog](https://cloud.githubusercontent.com/assets/3777585/2681700/4c2ac26c-c190-11e3-86c2-d549c298d03a.png)

Additionally, the wait animation had a white background, not a blue one. And the progress bar seemed to be broken, it shows only green bug streaming progress was 55%? The progress bar of the videoplayer did work.

**Comment by synctext** [comment]
Closing, we're redoing the whole GUI.
