### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by mrcruz** [Tribler/tribler#5510]
How many people are using tribler? what speeds are people downloading? Do we have any problems with the latest released version?

These are some questions that can help making decisions and prioritize work. The way I see, having data of how people use an app is integral to development of complex projects. One reference project from me is Syncthing and, if you check their usage data ([data.syncthing.net/](https://data.syncthing.net/)), you can get a very good idea on what is important and what is not. I feel like Tribler could benefit a lot from having at least some basic data.

**Comment by ichorid** [comment]
@xoriole recently had the same ideas and started to implement something like this.

**Comment by xoriole** [comment]
> How many people are using tribler? what speeds are people downloading? Do we have any problems with the latest released version?

These are interesting questions that I would also love to know the (more accurate) answers to. We can already infer a few things from the network data but we'll need to put more effort into it to have better insights.

I totally agree that analytics would be very helpful in understanding the usage of different features in Tribler and prioritizing future (development) work based on data-driven decisions. But it is equally important that we do it right and in **a privacy-preserving way**. The plan is to do it incrementally one thing at a time using we already know and gradually collect properly anonymized usage data (with explicit user consent/ opt-in mechanism).

I'll keep this thread updated as more progress is made and we have numbers and graphs to disclose.
@mrcruz Thank you for your suggestion and for opening an issue.

**Comment by xoriole** [comment]
The work done for analytics is available at 
https://release.tribler.org/dashboard/

As no immediate further work is planned for this ticket, I'm unassigning myself.

**Comment by qstokkink** [comment]
There is a slippery slope from release statistics, to telemetry and down to spying on users. Sticking with release statistics is good enough and I consider this issue closed now.
