### ISSUE TITLE
Separate release URL for Tribler besides GitHub for download statistics

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#5523]
Right now, we do release via GitHub which is great but we lack some important insights on release statistics. 

For example, from Github API, 
- We know how many downloads were done for each of the release artifacts but we don't know the distribution over time. 
- Daily/Weekly/Monthly downloads data is not available. 
- Global spread information is also not available. 
- How long does it take the majority of the users to download/switch to the newly released version? We don't know.

I believe release statistics will be useful to better understand our users to some extent and improve our release cycle. Therefore, as the first step towards https://github.com/Tribler/tribler/issues/5510, I propose to develop a separate release website/service/API that shows all the release statistics based on public information.

Update: https://releases.tribler.org (available now)

**Comment by devos50** [comment]
@xoriole with #5524 merged, is this issue considered solved?

**Comment by xoriole** [comment]
@devos50  yes, it is resolved. We can close this.
