### ISSUE TITLE
[7.5.2] CancelledError in Tunnels

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5532]
Reported with early versions of 7.5.2

```
Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\event_request_manager.py", line 116, in on_read_data
RuntimeError:
--LONG TEXT--
Traceback (most recent call last):
File "lib\asyncio\events.py", line 81, in _run
File "ipv8\messaging\anonymization\tunnel.py", line 149, in on_ip_address
asyncio.exceptions.CancelledError

--CONTEXT--
{'message': 'Exception in callback TunnelExitSocket.sendto.<locals>.on_ip_address(<Task cancell...unnel.py:171>>) at ipv8\\messaging\\anonymization\\tunnel.py:147', 'exception': CancelledError(), 'handle': <Handle TunnelExitSocket.sendto.<locals>.on_ip_address(<Task cancell...unnel.py:171>>) at ipv8\messaging\anonymization\tunnel.py:147>}
```

**Comment by qstokkink** [comment]
This seems to be a Python 3.7 vs Python 3.8 thing:

 - https://docs.python.org/3.7/library/asyncio-exceptions.html#asyncio.CancelledError
 - https://docs.python.org/3.8/library/asyncio-exceptions.html#asyncio.CancelledError

In Python 3.7 `except Exception` apparently doesn't catch `asyncio.CancelledError`.

**Comment by egbertbouman** [comment]
I just verified this. In Python 3.8, `CancelledError` no longer inherits from `Exception`, so we'll have to catch it separately. I'll fix this in IPv8.

**Comment by ichorid** [comment]
When does it trigger? We've just released 7.5.2 with this bug. Should we create a hotfix immediately or this is a fairly rare problem and we can safely ignore it?

**Comment by egbertbouman** [comment]
Since this is happening in the `TunnelExitSocket` it's probably a rare problem. We do have multiple reports, but they all seem to be coming from the same user.

**Comment by devos50** [comment]
This should be fixed now with the merge of https://github.com/Tribler/py-ipv8/commit/8c4e7328e427e384c4c59ef6f96e1ec4f992f92c by #5538. I also think there is no need to make a new release, only for solving this bug.

**Comment by xoriole** [comment]
This issue is also reported on 7.5.3 (first issue). Since the fix is in devel, we'll have to wait until 7.6 release I guess.

**Comment by ichorid** [comment]
I guess we should slightly(!) bump the IPv8 pointer on `release-7.5` to fix this.

**Comment by qstokkink** [comment]
Here's the diff between commits: https://github.com/Tribler/py-ipv8/compare/465cddd87eaa73f4f974e21a125d4a38c4a0ff0c...8c4e7328e427e384c4c59ef6f96e1ec4f992f92c

It seems this commit may need some Tribler changes: https://github.com/Tribler/py-ipv8/commit/f38405bb48cce561a29699edeb37014e248252df

**Comment by egbertbouman** [comment]
I ended up moving the pointer a bit further: https://github.com/Tribler/py-ipv8/compare/465cddd87eaa73f4f974e21a125d4a38c4a0ff0c...8b55295696b6e0493d77a7d099ae72ab6927c084. This way I could cherry-pick a commit from devel.
