### ISSUE TITLE
tribler_7.5.2_all.deb fails to start

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#5533]
[15820] Error loading Python lib '/usr/share/tribler/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/tribler/libpython3.8.so.1.0)

**Comment by Dmole** [comment]
```
apt show glibc-source | grep Version
Version: 2.27-3ubuntu1.2
```
v2.27 will be in an Ubuntu LTS until 2028.
The deb should fail to install due to the missing v2.29 dependency,
or Tribler should go all in and ship glibc,
or Tribler should stop trying to do it's own package management.

**Comment by devos50** [comment]
Thanks for your report!

We recently upgraded the build environment of Tribler to Ubuntu 20.04 to have Python 3.8 support (to fix a specific bug). However, it seems that `glibc` is forwards compatible but not backwards compatible. Therefore, we must build Tribler with the lowest `glibc` that we support.

> or Tribler should go all in and ship glibc, or Tribler should stop trying to do it's own package management.

Since we moved to PyInstaller, Tribler is not doing its own package management anymore (which caused a lot of problems). Instead, we bundle all required dependencies in our `.deb`. However, this does not include the `glibc` shared library, causing incompatibility issues when running Tribler on older platforms.

The key question here is what the lowest version of `glibc` is that we would like to support. @Dmole what Linux distribution are you using, and what version?

**Comment by Dmole** [comment]
18.04 is the "Ubuntu LTS until 2028".

**Comment by ichorid** [comment]
I guess the only way to support every platform while keeping our sanity intact :dizzy_face:  is to use Snap and hope for the best.

**Comment by Dmole** [comment]
Tribler insists on not using the system packagemanager Please don't use Snap.

https://github.com/AppImage/AppImageKit/wiki/Similar-projects#comparison

If there is not a way to convince PyInstaller to ship an older version of libpython,
and Tribler insists on not using the system packagemanager

**Comment by oecsea** [comment]
The main page lists "7.5.2 (stable)" as the main download but 7.5.0 is the last version that works for me.
Better than when the download link listed an ancient version that did not work,
But it maybe best if every release could have a 1 week release candidate period where people can test before it's marked "stable".

**Comment by Dmole** [comment]
The main page lists "7.5.2 (stable)" as the main download but 7.5.0 is the last version that works for me.
Better than when the download link listed an ancient version that did not work,
But it maybe best if every release could have a 1 week release candidate period where people can test before it's marked "stable".

**Comment by synctext** [comment]
Reproduced this bug on my Ubuntu box. Libc 2.27 of Ubuntu LTS is no longer supported.

> Python 3.8 is not available in Ubuntu’s default repositories.

**Comment by oecsea** [comment]
In "Ubuntu 18.04.5 LTS",  "python3.8" is in "universe/python"

**Comment by Dmole** [comment]
In "Ubuntu 18.04.5 LTS", "python3.8" is in "universe/python"

**Comment by synctext** [comment]
> In "Ubuntu 18.04.5 LTS", "python3.8" is in "universe/python"

Yeah, you are right. but there is this to fix :fearful: Multiple GLibC versions https://stackoverflow.com/questions/847179/multiple-glibc-libraries-on-a-single-host

**Comment by Dmole** [comment]
Thus the original issue was opened;
A) Tribler should either use a package container (the Windows/MacOS solution) or avoid libraries not available on LTSs.
B) Tribler should have more automated testing (many VMs or containers sequentially on one cheap box) or have a 1 week RC before every release.

**Comment by devos50** [comment]
Even when installing Python 3.8 system-wide, the runtime environment is frozen (with PyInstaller) and uses a bundled `libpython.so`. This shared library then depends on glibc which is _not_ bundled. Instead, PyInstaller uses the `glibc` that the system provides.

As I mentioned, `glibc` is forward compatible but not backwards compatible. Therefore, I think that the only solution is to build Tribler on a machine with a lower version of `glibc` (e.g., as provided in Ubuntu 18.04 or 18.10). This requires us to setup a new machine though and install the required dependencies, which is not trivial. Also, we might have to bundle a lower version of Python, e.g., 3.7 or manually compile + install Python 3.8 on this machine.

> Yeah, you are right. but there is this to fix 😨 Multiple GLibC versions https://stackoverflow.com/questions/847179/multiple-glibc-libraries-on-a-single-host

The solution discussed in the SO post would require us to tinker with the `LD_LIBRARY_PATH` and/or to ship our own version of `glibc`, which can have very nasty side effects. I argue that the solution that I proposed above is, at least for now, not optimal but the least time-consuming.

> B) Tribler should have more automated testing (many VMs or containers sequentially on one cheap box) or have a 1 week RC before every release.

Agreed, we will discuss this matter internally.

**Comment by Thatoo** [comment]
It doesn't work for me neither...

**Comment by devos50** [comment]
I did spend some time on setting up a new (Ubuntu 18.04) machine, and installed the required dependencies on there. I also build with Python 3.8 and libtorrent 1.2.7.

For everyone experiencing issues with running Tribler on Linux, can you please try our [this build](https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Build-Ubuntu64/111/) and let us know if that works for you? Thanks!

**Comment by Dmole** [comment]
Thanks, that's the first build since 7.5.0 that works for me.

**Comment by synctext** [comment]
fixed!
![Screenshot from 2020-08-26 15-29-15](https://user-images.githubusercontent.com/325224/91309577-0ce84e00-e7b1-11ea-8548-c787ac8c41f0.png)

**Comment by Thatoo** [comment]
It works. Thanks!

**Comment by rockroux** [comment]
Hello, I'm a new Tribler user on Ubuntu 18.04 and was having similar problems with 7.5.2. I was able to get 7.5.0 to work and found this thread. The link provided above seems to 404 now, so I assume it was only a test.
What action do you recommend for other Ubuntu users? Is 7.5.2 expected to work if I upgrade to Ubuntu 20.04? Or is it best to simply stick to 7.5.0 and wait for a future release?

**Comment by qstokkink** [comment]
@rockroux the next release should include this fix, that should take a week or two until it's released.

**Comment by Deemattic** [comment]
same
link pls

**Comment by devos50** [comment]
It seems that our Jenkins job only keeps releases for ten days. I changed that setting so that older builds do not get lost from now on.

I prepared #5563 in order to make a new build.

**Comment by devos50** [comment]
You can download a pending 7.5.3 release from [here](https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Build/92/). It should work on Linux distros with an older version of `glibc`. Note that we are still discussing whether this will become the final 7.5.3 release.

**Comment by devos50** [comment]
Tribler 7.5.3 [has been released](https://github.com/Tribler/tribler/releases/tag/v7.5.3), solving this issue.
