### ISSUE TITLE
Tribler won't work on Debian 10

### ISSUE THREAD

**Issue by stevavoliajvar** [Tribler/tribler#5536]
- [ x] I have read CONTRIBUTING.rst

- [x ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Tribler 7.5.2 - from website
8f1ab43f2d1049bb0e4db0a0b683c74f0474adb5 from github

##### Operating system and version: #####
Debian 10, `unam -a` output:

`Linux ephemeral 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux`
##### Steps to reproduce the behavior: #####
Download Tribler from tribler.org, follow instruction from tribler.org/linux.html
Clone Tribler from github repo, follow instructions
##### Expected behavior: #####
Tribler working
##### Actual behavior: #####
Tribler not working.

First I installed it via trbiler.org/linux.html, wget + apt-get method. It wasn't working, didn't even start.
I get this as output:
```
Starting Tribler...
/usr/share/tribler ~/installs
```

Then I uninstalled tribler and tried to install from github. Followed instructions and I'm getting this as output when I run ./tribler.sh
```
Traceback (most recent call last):
  File "/home/void/installs/tribler/src/run_tribler.py", line 127, in <module>
    from tribler_gui.tribler_app import TriblerApplication
  File "/home/void/installs/tribler/src/tribler-gui/tribler_gui/tribler_app.py", line 4, in <module>
    from PyQt5.QtCore import QCoreApplication, QEvent, Qt
RuntimeError: the PyQt5.QtCore and PyQt4.QtCore modules both wrap the QObject class
```
##### Relevant log file output: #####
I pasted logs above.

**Comment by devos50** [comment]
Thank you for reporting this!

It seems that there is an error while loading Tribler, when installing the `deb` file. You should be able to find the log file in `/tmp` (the log should be named something like`$USER-tribler-XXXXXXXX.log`). Can you inspect these logs and check if there is any error in there? If so, please post that error so we can debug this issue further 👍 

The second error you linked seems to be related to PyQt, in particular, it looks like both PyQt4 and PyQt5 are installed.

**Comment by stevavoliajvar** [comment]
@devos50 here is output from /tmp
```
[19508] Error loading Python lib '/usr/share/tribler/libpython3.8.so.1.0': d    lopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (requ    ired by /usr/share/tribler/libpython3.8.so.1.0)
```

As for second error i removed pytq4 and it works now, only during removal it removed pyqtgraph so I had to reinstall that package with pip3, now it starts up. Thanks for help!

**Comment by devos50** [comment]
Good to hear that it works now!

This error seems to be because we are building Tribler with a newer version of the `glibc` library. Also see #5533. Let's continue the discussion there.
