### ISSUE TITLE
Add bandwidth usage control for exit nodes

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#5539]
- [x] I have tried with the latest pre-release version and I still can reproduce the issue.
Aug 10th 2020 build
##### Tribler version/branch+revision: #####
7.5
##### Operating system and version: #####
Windos 10 Insider build 20190
##### Steps to reproduce the behavior: #####
Just start tribler
##### Expected behavior: #####
browsing should be possible on all Intranet machines
##### Actual behavior: #####
Local machine unable to browse using other webbrowser, timeout's addresses not found.
As soon as I stop Tribler, all is normal again. Seems Tribler hardly returns cycles to the OS.

**Comment by Nubro01** [comment]
Disabling "use tribler as Exit node" at anonymous settings, seems to improve Intranet access to others.

**Comment by qstokkink** [comment]
At the moment the exit node setting is binary: on or off. This means that it will either use all bandwidth available or not.

We can add settings to the Tribler configuration to limit the bandwidth usage of exit sockets. This would allow users to tweak their settings to fit the bandwidth of their network.

**Comment by egbertbouman** [comment]
This will hopefully be fixed by `ipv8-rust-tunnels`, which will be part of Tribler 8.0
