### ISSUE TITLE
Tribler wiki: 404 error at link to "analysis of Bittorrent"

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#5546]
Page: https://github.com/Tribler/tribler/wiki#aim-solving-trust

Link:
![image](https://user-images.githubusercontent.com/13798583/91715936-53fe8680-eb97-11ea-869b-e1c601bd79ca.png)

Error:
![image](https://user-images.githubusercontent.com/13798583/91715999-71335500-eb97-11ea-8105-274339f908a0.png)

**Comment by qstokkink** [comment]
I suppose that should point to this publication:

```
Pouwelse, J. A., Garbacki, P., Epema, D. H. J., & Sips, H. J. (2004, October).
An introduction to the bittorrent peer-to-peer file-sharing system.
In 19th IEEE Annual Computer Communications Workshop, IEEE Technical Committee on Computer Communications.
```

**Comment by synctext** [comment]
fixed!
Thnx, that is our 1000+ citations paper (The bittorrent p2p file-sharing system: Measurements and analysis)
