### ISSUE TITLE
[7.5.2] [macOS] Wrong QT styles

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#5554]
- [x] I have read CONTRIBUTING.rst

- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
7.5.2

##### Operating system and version: #####
macOS 10.15.6

##### Steps to reproduce the behavior: #####
Move the mouse to the clock icon

##### Expected behavior: #####
A readable label will appear

##### Actual behavior: #####
The unreadable label appeared:
![image](https://user-images.githubusercontent.com/13798583/93097142-dc0f8080-f6ad-11ea-9259-71bd52856f99.png)

**Comment by devos50** [comment]
Yeah this is a known issue on Mac. I'm not sure what's causing it since the layout when running from source (on Mac) seems to be better. Maybe PyInstaller is stripping out important stuff from PyQt5.

**Comment by devos50** [comment]
@drew2a also, please add the appropriate labels, project + milestone to each new issue. If you're not sure about some label/milestone, we can add it :)

**Comment by drew2a** [comment]
@devos50 🆗

**Comment by ichorid** [comment]
@drew2a , could you please tell if it was resolved in 7.6.0? I did some style changes there.

**Comment by drew2a** [comment]
Seems to be fixed :)
