### ISSUE TITLE
We should review our Jenkins plugins and remove unnecessary ones

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5574]
We have many plugins installed and enabled on our Jenkins server. It seems that we have many plugins installed that are not used anymore and can be disabled, or removed (e.g., plugins for emailing from Jenkins). We should review these plugins and see if we can clean them up.

**Comment by devos50** [comment]
@xoriole would you have time to look at this somewhere soon? This has a bit lower priority but it would be nice if it's done.

**Comment by xoriole** [comment]
yes, I reviewed that when I upgraded jenkins last week. Will do later this week after I make some more progress on popularity community.

**Comment by devos50** [comment]
Thanks! In addition, it might also be a good idea to go through the list of users that can access Jenkins, and remove users that do not require access anymore 👍

**Comment by ichorid** [comment]
> Thanks! In addition, it might also be a good idea to go through the list of users that can access Jenkins, and remove users that do not require access anymore +1

We should do the same with our GitHub organisation.

**Comment by xoriole** [comment]
Updates:
- Unused and outdated plugins are removed but there are a few deprecated left which are currently used in some jobs. Additionally, Plugin usage plugin is installed that shows which plugins are used by which jobs.
- Users and permissions list is cleaned
- Github access right is reviewed

**Comment by devos50** [comment]
Good, I think that sufficiently addresses this issue! 👍

**Comment by ichorid** [comment]
Plugin usage plugin is smart! If we only could do the same thing for Tribler lines of code...
