### ISSUE TITLE
[PopularityCommunity] Get velocity of torrents list filling

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#5580]
#### Experiment

Given: the real network.

Action: 
* add a new node
* every `N` seconds check how long torrent's list are

Result will be stored in a csv file.

Extracted and finalized from https://github.com/Tribler/tribler/issues/3868#issuecomment-698247389

**Comment by ichorid** [comment]
How about first establishing *how many live torrents* are out there at any given moment?

**Comment by drew2a** [comment]
> How about first establishing _how many live torrents_ are out there at any given moment?

I'll show both `live` and `total` torrents count. Thanks.

**Comment by ichorid** [comment]
What I actually meant, is we should first establish a holistic picture of the BitTorrent network. Like, estimate how many live torrents are out there in the whole network, not just Tribler network. See how [Torrents.csv does it](https://gitlab.com/dessalines/torrents.csv).

**Comment by drew2a** [comment]
### Experiment results
Velocity for the first `10` minutes
Total: `572`
Alive: `40`

![image](https://user-images.githubusercontent.com/13798583/94370663-ed1eaf80-00f9-11eb-9622-2ae2135583ff.png)

Velocity for the first `30` minutes
Total: `2817`
Alive: `145`

![image](https://user-images.githubusercontent.com/13798583/94375081-ad67c000-0119-11eb-93fe-f135f56863db.png)

More details: https://github.com/Tribler/tribler/pull/5586

**Comment by ichorid** [comment]
Hint: if you have two series that differ in their growth rate so much that one looks alomost flat in comparison to another, use logarithmic Y-scale :wink:

**Comment by drew2a** [comment]
@ichorid thank you for this tip. 
I've started to use it in https://jenkins-ci.tribler.org/job/popularity_experiments/job/Initial_filling_velocity/plot/ and the plot is looking better.

**Comment by drew2a** [comment]
How to understand the Jenkins ["Velocity of initial feeling" plot](https://jenkins-ci.tribler.org/job/popularity_experiments/job/Initial_filling_velocity/plot/):

The goal of a new node: as fast as it possible get as much as possible alive torrents (`100k`).

That means Popularity Community should minimise time (blue dots) and maximise alive torrents (green dots).

![image](https://user-images.githubusercontent.com/13798583/94540498-33395780-024f-11eb-8ba2-ab906a5ce657.png)

**Comment by synctext** [comment]
> Velocity for the first 30 minutes
> Total: 2817
> Alive: 145

Those are all very insightful plots. Exciting progress @drew2a. Seems we have various sub-problems:
- fast bootstrap
- capture swarm size in 5 levels (tracker,DHT,BEP33, direct-join)
- coverage
- plus we need to deal later with the "90% dead swarms" issue

**Comment by ichorid** [comment]
Oh, there is a solution to the dead-swarms problem! We must teach Tribler how to *forget* about dead stuff. Like: "if I checked a swarm and it is dead, just to be sure, I ask some random people to check it too, and if it is *really* dead - I *delete the corresponding Channels entry* (and probably add the infohash to a giant Bloom filter of dead swarms)"

This way, the network will gradually self-clean of irrelevant entries.

**Comment by drew2a** [comment]
Jenkin's job has been scheduled for 8:00, every day.
