### ISSUE TITLE
Export .torrent file on all selected torrents

### ISSUE THREAD

**Issue by balupton** [Tribler/tribler#5591]
Currently Tribler only allows "Export .torrent file" on a single selected item.

It would be preferable if you could select multiple items, and have it enabled, such that you can export the torrent file for each selected item at once.

**Comment by devos50** [comment]
Thanks for your suggestion!

**Comment by balupton** [comment]
Is there any workaround in the meantime?

**Comment by drew2a** [comment]
Hi, @balupton,

If I understand your request correctly, you want to export multiple torrents at once. As a workaround, you can use the watch folder functionality:
- #1038
- #2065

**Comment by balupton** [comment]
@drew2a does the watch folder batch export all existing torrents to torrent files inside the watch folder? If so, that'll work. However, isn't it just for importing torrent files into Tribler, and not for getting torrent files out of Tribler?

**Comment by drew2a** [comment]
@balupton, I think I misunderstood your initial request. Do you want to export multiple torrents from Tribler to `.torrent` files? If so, there is no workaround. 

However, if you want to import multiple torrent files from `.torrent` to Tribler, you can use the watch folder.
