### ISSUE TITLE
Modularize IPv8 community loading

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#5593]
As the Tribler repository now features an `experiment/` folder, we are seeing the same staging procedures being implemented as already available in Gumby. One of these features is the staging of IPv8 communities. In order for both repositories to benefit, I propose moving this from Gumby into the Tribler experiment infrastructure.

Loading communities in the `Session` is currently one big line of `if .. else` statements, see https://github.com/Tribler/tribler/blob/devel/src/tribler-core/tribler_core/session.py#L146
Instead, in Gumby, this is completely modularized, see https://github.com/Tribler/gumby/blob/devel/gumby/modules/gumby_session.py

This modularization of loading communities improves the Tribler code in four ways:

 - It shortens the `Session` code (making it more of a manager and less of a god class).
 - Allows for isolation and staging of community loading.
 - Reduces the complexity of staging components.
 - Allows for declarative programming.

There is also a downside: a big `if .. else` construction is slightly faster than a modular loading system. But, considering the direction we are heading, that seems like an acceptable sacrifice.

**Comment by devos50** [comment]
I think this would be a good idea to avoid further code duplication. I wonder though if Gumby can be split in such a way that we move the community loading stuff to Tribler, and leave infrastructure-related code in a separate repository. Or maybe we should just move the entire Gumby code base in the Tribler repository?

**Comment by qstokkink** [comment]
To be honest, Gumby is like bringing a nuclear bomb to a knife fight. It is hard to control and too fat for the type of experiments in Tribler.

My intention with this issue is to bring the functional components of Gumby into Tribler, so we can have lean and mean experiments in the Tribler repository. While, at the same time, leaving Gumby as the all-powerful alternative for mass deployment of isolated experiments.

**Comment by ichorid** [comment]
Related to #4953 #3896 #2029

**Comment by qstokkink** [comment]
I guess I can do this today.
