### ISSUE TITLE
Tunnel tests should be using a mock IPv8

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5599]
Currently, the tunnel tests are using a real IPv8 instance. Even though we disable the discovery community immediately after starting IPv8, this is quite dangerous since a bootstrap request might have gone through. Furthermore, the real IPv8 will consume ports on the local machine.

Instead, we should be using the `MockIPv8` that is already used by many IPv8 tests. By abstracting away the network layer, we can hopefully make these tests more stable. After all, what we need to test is the SOCKS5/libtorrent combination, and not the network traffic.

**Comment by devos50** [comment]
I made some progress on this. Specifically, I managed to replace the real IPv8 with `MockIPv8` for the `test_anon_download`, which seems to work fine. However, the `test_hidden_services` is giving me a headache (as usual). My progress so far can be found [here](https://github.com/devos50/tribler/tree/mock_ipv8_tunnel_tests).

@egbertbouman since my understanding of the full e2e protocol is limited, can you try to get this test working with a `MockIPv8`?

**Comment by egbertbouman** [comment]
@devos50 Sure, I'll take a look.

**Comment by egbertbouman** [comment]
@devos50 It just needed some `MockTunnelExitSocket` magic and now it works (see [here](https://github.com/egbertbouman/tribler/commits/mock_ipv8_tunnel_tests)). Do you want to make the PR or should I?

**Comment by devos50** [comment]
Oh cool! Feel free to take the credits and make PR :D

**Comment by egbertbouman** [comment]
Taking credits...
