### ISSUE TITLE
Some answers in the FAQ on our website are outdated

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5604]
[A reddit user](https://www.reddit.com/r/tribler/comments/j4z32g/how_do_i_upload_new_files_anonymously/) noticed that some answers in the FAQ are worded strangely or are outdated. We should go through the questions/answers and rewrite stuff where needed.

**Comment by drew2a** [comment]
Outdated information is present not only on the website but also in the [wiki](https://github.com/Tribler/tribler/wiki) and [readthedocs](https://tribler.readthedocs.io/en/latest/metadata_store/channels_architecture.html).
