### ISSUE TITLE
Segmentation fault on startup

### ISSUE THREAD

**Issue by da2x** [Tribler/tribler#5605]
#### Please, fill all relevant items: ####

- [x] I have NOT read CONTRIBUTING.rst (no such file)
- [x] I have tried with the latest pre-release version and I still can reproduce the issue. (no prerelease)

##### Tribler version/branch+revision: #####
7.5.2 from source

##### Operating system and version: #####
Fedora 32

##### Steps to reproduce the behavior: #####
0. Downloadtribler-7.5.2, unpack, and change into its directory.
1. `sudo dnf python3-configobj python3-aiohttp python3-aiorestapi python3-lz4 python3-pynacl python3-netifaces python3-networkx python3-psutil python3-pyqtgraph python3-pillow-qt`
2. `pip3 install --user -r src/requirements.txt pyipv8` (for anything missing in Fedora repos)
3. `src/tribler.sh`

##### Actual behavior: ##### 
```
[PID:54667] 2020-10-05 14:19:59,721 - INFO - root(24) - __init__()
[PID:54667] 2020-10-05 14:19:59,762 - INFO - root(50) -   self._outSocket.error() = '2'
[PID:54667] 2020-10-05 14:19:59,762 - INFO - root(60) - __init__(): returning
src/tribler.sh: line 43: 54667 Segmentation fault      (core dumped) python3 $TRIBLER_SCRIPT "$@"
```

##### Relevant log file output: #####
gdb  backtrace: https://gist.github.com/da2x/84519514a65ca0e7a7c42e9fb123c918

**Comment by qstokkink** [comment]
Let me preface this by saying we don't have any Fedora developers, so you're basically on your own 😃 Nonetheless, I'll try to help you as best I can.

>  I have NOT read CONTRIBUTING.rst (no such file)

Touché, you can find it here: https://github.com/Tribler/tribler/blob/devel/doc/contributing.rst

> I have tried with the latest pre-release version and I still can reproduce the issue. (no prerelease)

You can find the current `7.5.x`-series release code (which will be `7.5.3`) here: https://github.com/Tribler/tribler/archive/release-7.5.zip

Now, for the real issue.

From your gdb backtrace I see you have some PyQt4 font database initialization issues going on. Which is interesting, as we use PyQt5. This is probably a side effect from installing `python3-pyqtgraph`, but who knows what is actually going on there. If you want a fighting chance at getting this running, I'd recommend removing the packages you installed and sticking to this guide:

https://github.com/Tribler/tribler/blob/devel/doc/development/development_on_linux.rst

**Comment by devos50** [comment]
Thanks for your report. As @qstokkink already pointed out, we do not support Fedora currently. However, we are trying to ship a Snap container with Tribler 7.6.

That said, the issue indeed seems to be related to PyQt4, which is used judging from `/usr/lib64/python3.8/site-packages/PyQt4/QtGui.so`. The `.so` for PyQt4 is definitely not compatible with Tribler, hence resulting in the segmentation fault.

Please let us know if this helps!

**Comment by da2x** [comment]
>> CONTRIBUTING.rst (no such file)
>
> Touché, you can find it here: https://github.com/Tribler/tribler/blob/devel/doc/contributing.rst

I only looked for it in the repo root (that’s usually where the file is located.) Could you update the bug template and *link it* to the right location? I can’t miss it next time if there’s a link! 😉

> https://github.com/Tribler/tribler/blob/devel/doc/development/development_on_linux.rst

Could you please add that to [https://www.tribler.org/linux.html](https://www.tribler.org/linux.html)?

**Comment by da2x** [comment]
> That said, the issue indeed seems to be related to PyQt4, which is used judging from /usr/lib64/python3.8/site-packages/PyQt4/QtGui.so. The .so for PyQt4 is definitely not compatible with Tribler, hence resulting in the segmentation fault.

That helps a lot. If I move `/usr/lib64/python3.8/site-packages/PyQt4/` to `PyQt4-begone` then Tribler starts. I don’t quite understand why the presence of PyQt4 should be an issue, though.

> https://github.com/Tribler/tribler/blob/devel/doc/development/development_on_linux.rst

`pip3 install --user --upgrade -r requirements.txt` says everything is already up to date.

**Comment by devos50** [comment]
> I don’t quite understand why the presence of PyQt4 should be an issue, though.

Likely, the path to `PyQt4.so` has priority over the path to `PyQt5.so` when initializing shared libraries. I think you can confirm this by either checking the `PATH` or `LD_LIBRARY_PATH` environment variable 👍

**Comment by da2x** [comment]
[pyqtgraph prefers Qt4 over Qt5](https://github.com/pyqtgraph/pyqtgraph/blob/0a8ad6b1aae733a2dbd5026b6b1011238aa75548/pyqtgraph/Qt.py#L29). This can be overridden by setting the environmental variable `PYQTGRAPH_QT_LIB=PyQt5`.
