### ISSUE TITLE
Running app has no icon

### ISSUE THREAD

**Issue by da2x** [Tribler/tribler#5606]
#### Please, fill all relevant items: ####

- [x] I have NOT read CONTRIBUTING.rst (no such file)
- [x] I have tried with the latest pre-release version and I still can reproduce the issue. (no prerelease)

##### Tribler version/branch+revision: #####
7.5.2

##### Operating system and version: #####
* Windows 10.2004
* Fedora Linux 32, KDE

##### Steps to reproduce the behavior: #####
Install Tribler and run it.

##### Expected behavior: #####
Icon in the top left corner of the title bar. Icon on the task manager.

##### Actual behavior: #####
No icon.

##### Relevant screenshots: #####
![Screenshot of missing icons](https://user-images.githubusercontent.com/1102886/95086149-6f255e80-0720-11eb-91e5-2d7572d1044c.png)

**Comment by devos50** [comment]
Thanks for reporting this issue.

My first thought was that this is somehow related to NSIS, which bundles the application icon. However, it seems that we are missing a call to `setWindowIcon`. Some further digging, however, reveals that the issue might be more complicated than that. Specifically, the icon being shown in the task bar can differ from the one shown in the top-left corner of the application window, see [here](https://stackoverflow.com/questions/1551605/how-to-set-applications-taskbar-icon-in-windows-7/1552105#1552105).

It would be nice if someone with a Windows development environment can have a look at this 👍

**Comment by da2x** [comment]
Same issue on Linux.
