### ISSUE TITLE
Not responding on start-up on macOS

### ISSUE THREAD

**Issue by da2x** [Tribler/tribler#5609]
##### Tribler version/branch+revision: #####
7.5.2

##### Operating system and version: #####
* macOS 11.20A5384c (Big Sur beta 5)
* macOS 10.15.4

##### Steps to reproduce the behavior: #####
1. Download Tribler.
2. Right-click on it and chose Open.
3. Ignore the warning about it not being signed.
4. Repeat two and chose Open in the dialog to bypass gatekeeper.

##### Expected behavior: #####
Tribler should start.

##### Actual behavior: #####
Tribler doesn't start. The top bar changes the current app name to Tribler and then beachballs (stops responding) indefinitely.

##### Relevant log file output: #####
Nothing in ~/.Trilber/, spindump can't sample the process either.

**Comment by xoriole** [comment]
@da2x Thank you for reporting. I'm running 10.15.5 and I cannot reproduce the issue. Tribler.dmg is not signed yet so it shows the warning but it should have worked. 
@devos50 any ideas?

**Comment by da2x** [comment]
```
/Applications/Tribler.app/Contents/MacOS/tribler
INFO - root(24) - __init__()
INFO - root(50) -   self._outSocket.error() = '0'
INFO - root(52) - received QLocalSocket.ConnectionRefusedError; removing server.
INFO - root(64) - close()
INFO - root(71) - close(): returning
INFO - root(60) - __init__(): returning
INFO - TriblerGUI(134) - Will connect to events endpoint
```

**Comment by devos50** [comment]
@da2x thank you! Do you, by any chance, still have a Tribler background process running?

If that's not the case, this might be a gatekeeper issue. Maybe you could try to **temporarily** disable gatekeeper, see [here](https://osxdaily.com/2015/05/04/disable-gatekeeper-command-line-mac-osx/)? Please don't forget to re-enable it when you are done 👍

**Comment by da2x** [comment]
> still have a Tribler background process running?

```
killall tribler
No matching processes belonging to you were found
```

> Maybe you could try to temporarily disable gatekeeper, see here? Please don't forget to re-enable it when you are done 👍

That made no difference.

However, I turned off the firewall and got one more line of output:

```
/Applications/Tribler.app/Contents/MacOS/tribler
INFO - root(24) - __init__()
INFO - root(50) -   self._outSocket.error() = '0'
INFO - root(52) - received QLocalSocket.ConnectionRefusedError; removing server.
INFO - root(64) - close()
INFO - root(71) - close(): returning
INFO - root(60) - __init__(): returning
INFO - TriblerGUI(134) - Will connect to events endpoint
INFO - TriblerGUI(78) - Got Tribler core error: 1
```

I turned everything back on again and rebooted. When I tried Tribler again, I finally got something in ~/.Tribler/ (this folder was empty before):

* tribler-gui-info.log is empty
* tribler-gui-error.log is empty
* crash-report.log is empty
* [tribler-core-error.log](https://github.com/Tribler/tribler/files/5328152/tribler-core-error.log)
* [tribler-core-info.log](https://github.com/Tribler/tribler/files/5328167/tribler-core-info.log)
* version_history.json, populated with version data
* triblerd.lock, contains a number

**Comment by balupton** [comment]
Just upgraded to Big Sur, same issue. Tribler never starts.

**Comment by balupton** [comment]
Can still use other apps, right clicking the icon reveals it has stopped responding. Force quit does close it.

<img width="325" alt="Screen Shot 2020-11-13 at 6 12 30 pm" src="https://user-images.githubusercontent.com/61148/99039638-cc43e800-25db-11eb-8584-031e1b292d8c.png">

**Comment by devos50** [comment]
@balupton thanks for reporting this issue! I am currently upgrading my Mac to Big Sur and I will let you know if I can reproduce this 👍 . Are you trying to run Tribler 7.5.4?

**Comment by balupton** [comment]
Whichever is the latest

**Comment by devos50** [comment]
I can reproduce this. Tribler is indeed not starting on Big Sur. It does not even load the GUI, so I'm suspecting that the issue is related to PyQt.

```
martijndevos@MacBook-Pro-van-Martijn MacOS % ./tribler
[PID:49492] 2020-11-13 10:26:41,750 - INFO - root(24) - __init__()
[PID:49492] 2020-11-13 10:26:41,850 - INFO - root(50) -   self._outSocket.error() = '2'
[PID:49492] 2020-11-13 10:26:41,850 - INFO - root(60) - __init__(): returning
[PID:49492] 2020-11-13 10:26:42,488 - INFO - TriblerGUI(134) - Will connect to events endpoint
[PID:49492] 2020-11-13 10:26:42,566 - INFO - TriblerGUI(78) - Got Tribler core error: 1
```

**Comment by balupton** [comment]
Seems force quit from the dock does not actually close Tribler

<img width="975" alt="Screen Shot 2020-11-14 at 11 03 17 am" src="https://user-images.githubusercontent.com/61148/99132095-276fec00-2669-11eb-9f7a-577f22a81b22.png">

**Comment by madcat-nl** [comment]
I got the same issue on my machine, sorry opened Duplicate of #5776

**Comment by balupton** [comment]
Does https://github.com/Tribler/tribler/releases/tag/v7.6.0 fix this?

**Comment by da2x** [comment]
This started working on my mac in version 7.9. I deleted my profile and retested with 7.7 and 7.8, but neither worked.
