### ISSUE TITLE
Source releases are missing submodules

### ISSUE THREAD

**Issue by da2x** [Tribler/tribler#5610]
All the git submodules are missing in the source releases (the tar.gz and zip deliverables). Everything is included in the tar.xz.

**Comment by xoriole** [comment]
`zip` and `tar.gz` files are auto generated by Github on each release which excludes the submodules. There is not much we can do about that. 

The `tar.xz` file, on the other hand, is generated by us as source package. It includes all the submodules.

![screenshot-github com-2020 10 29-13_15_49](https://user-images.githubusercontent.com/1442867/97572926-4aec3300-19e9-11eb-90e0-0fd5c706bccb.png)
