### ISSUE TITLE
Move register_default_launchers into Session.__init__

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#5613]
Currently `register_default_launchers()` is called in the `Session.load_ipv8_overlays()` method. To load custom/non-default `Community` subclasses this is fine for Gumby, as [it includes a subclass of `Session`](https://github.com/Tribler/gumby/blob/devel/gumby/modules/gumby_session.py). But, we can do better.

If `register_default_launchers()` is moved into the `Session.__init__()` we can control the loaded communities _without a subclass_. The following (much shorter and without subclasses) would be possible for example:

```python
session = Session(config)
session.ipv8_community_loader.community_launchers.clear()  # Or omit this line and keep the defaults.
session.ipv8_community_loader.set_launcher(my_community_launcher)
await session.start()
```

**Comment by ichorid** [comment]
This is a good idea. Though we must ensure that `register_default_launchers` does not do any state-changing stuff, like obtaining ports, etc. We do not want to break our promise that only the `start` method really *starts* anything.

**Comment by qstokkink** [comment]
For now it is absolutely state safe. But, that is a good point, we should plaster a big warning in the `register_default_launchers` docstring not to do anything but add the launchers.
