### ISSUE TITLE
run_tribler does not separate core form GUI imports

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#5620]
Related to #4953

In the header of the `run_tribler.py` file there are imports from both the core and the GUI. As these imports are loaded by both the core and the GUI, only imports from the `tribler-common` package should be here.

https://github.com/Tribler/tribler/blob/fecebd68eb0609016711bf8bdd2ec9d93f0f5a07/src/run_tribler.py#L8-L15

Common resources (classes/functions) should be in the `tribler-common` folder and all imports from the core and the GUI should be in their respective scope (`tribler-core` or `tribler-gui`). The scoping is inferred by this `if`-statement:

https://github.com/Tribler/tribler/blob/fecebd68eb0609016711bf8bdd2ec9d93f0f5a07/src/run_tribler.py#L93

**Comment by devos50** [comment]
Good find, thanks!

We can probably also make most of these imports local, instead of declaring them at the top of the file.

**Comment by ichorid** [comment]
That's another reason why we probably want to use a separate executable for the Core...

**Comment by qstokkink** [comment]
> separate executable for the Core

We have tried this in the past and ran into Operating System specific issues, like inconsistent executable naming, inconsistent launching and jumbling of arguments. The current way of spawning a secondary process at least works on all supported platforms without any OS-specific nonsense.

**Comment by ichorid** [comment]
> We have tried this in the past and ran into Operating System specific issues

Yep, these problems definitely exist. But maybe the time has come to give it another try?

**Comment by devos50** [comment]
> Yep, these problems definitely exist. But maybe the time has come to give it another try?

Given our current focus on stability and incremental improvements, I don't think we should look into this now.

**Comment by qstokkink** [comment]
Bump: still an issue with the latest changes, but the other way around. Now there are core imports inside the GUI block. These should either not be there or this functionality should be in `common`.

https://github.com/Tribler/tribler/blob/409d5f6650cb8438b5967169e44d47d72422f231/src/run_tribler.py#L51-L89

**Comment by qstokkink** [comment]
Tribler now has a web-based front end and this issue is no longer relevant.
