### ISSUE TITLE
Sleeker Discovered channels design

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#5629]
In the future we may want to move toward a more industry-standard way of representing channels. This mock-up uses more vertical space per entry and removes column headers. This design also adds a small icon and a short description per channel.

![tribler_interface_mockup_sfw](https://user-images.githubusercontent.com/3630389/95740145-45be8280-0c8c-11eb-9b28-8ffc53dfed37.png)

**Comment by drew2a** [comment]
This issue is no longer relevant due to:
- #7726
