### ISSUE TITLE
The tests are loading the DiscoveryCommunity by default

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5634]
Since we move the community loader from Gumby to IPv8/Tribler, the discovery community is started by default, and there is no option to disable the loading of the `DiscoveryCommunity`. In particular, `test_load_ipv8_overlays` will load the discovery community and starts to bootstrap, since it loads a full Tribler session.

**Comment by qstokkink** [comment]
That makes it sound like this was broken by the CommunityLoader port. This was, however, always the case:
https://github.com/Tribler/tribler/pull/5597/files#diff-5aa22213705973d49dfc932a922429b51df32f4c04cb03d9846ef9ee755c2355L152-L161

**Comment by devos50** [comment]
Oh, I was not aware that it was always loaded in the tests. Anyway, this should be disabled.
