### ISSUE TITLE
Move code from the tribler_core module to tribler_common module where appropriate

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5645]
Currently, we have many occurrences in the code where the GUI is importing modules in the `tribler_core` module directly. This imported code usually consists of identifiers and utility functions (e.g., JSON encode/decode). Code that is used by both the GUI and the core, should go to the `tribler_common` module instead.

**Comment by drew2a** [comment]
The `tribler_core` occurrences in the GUI package:

![image](https://user-images.githubusercontent.com/13798583/152527848-262d3835-e220-4194-978b-6ea753068ff3.png)
