### ISSUE TITLE
Our win64 unit tests on the devel branch are broken

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5651]
It seems that since yesterday, [our tests on win64](https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_win64_pytest/) are broken. Specifically, the libtorrent tests are failing which is probably related to the BEP33 upgrade of the libtorrent versions.

**Comment by xoriole** [comment]
Yes, I see. Seems to be related to BEP33. I'll look into it. Strangely, it works on my linux dev machine with libtorrent 1.2.10 with DHT scrape enabled.

**Comment by xoriole** [comment]
The tests are stable again. Win64 machine now has Libtorrent 1.2.7 with BEP33 DHT scrape enabled.
