### ISSUE TITLE
Enhancement to rename files within the torrent payload.

### ISSUE THREAD

**Issue by snakyjake1** [Tribler/tribler#5653]
I would like an enhancement to rename files within the torrent payload.

Why?  I like to remove the junk that other seeders add to the filename and conform to Kodi naming conventions.

##### Tribler version/branch+revision: #####
7.5.2

**Comment by synctext** [comment]
interesting, would that be renaming the local files?
Or global files and alter the magnet link of the swarm? (requires global crowdsourcing, spam, and moderation stuff)

**Comment by ichorid** [comment]
Possible duplicate of #3455 
Related to #4222

**Comment by snakyjake1** [comment]
> 
> 
> interesting, would that be renaming the local files?
> Or global files and alter the magnet link of the swarm? (requires global crowdsourcing, spam, and moderation stuff)

Rename local files.
Main purpose is to follow naming standards for movie/tv scraping (Kodi) and cleaning up the name.

I do not wish to alter anything that would generate a new torrent hash, and divide the swarm health.

**Comment by ichorid** [comment]
AFAIK, Libtorrent supports renaming files locally. We supported this feature through the GUI, but removed it during refactoring some time ago.
