### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#5659]
##### Tribler version/branch+revision: #####

Docker image  5a5d40220b8b from tribler/docker-tribler-prod   

##### Operating system and version: #####

Linux + Docker

##### Steps to reproduce the behavior: #####

1. Start Tribler with a fresh profile
2. Subscribe to a channel
3. Add a download
4. Wait

##### Expected behavior: #####

It goes smoothly

##### Actual behavior: #####

It shows error box and exits.

Error report also cannot be sent - the button gets stuck at "Sending".

##### Relevant log file output: #####

```
Traceback (most recent call last):
  File "/home/tribler/tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 114, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/tribler/tribler/src/pyipv8/ipv8/taskmanager.py", line 108, in done_cb
    future.result()
  File "/home/tribler/tribler/src/pyipv8/ipv8/messaging/anonymization/tunnel.py", line 166, in resolve
    infos = await get_event_loop().getaddrinfo(host, 0, family=socket.AF_INET)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

Those "key-value" things cannot be copied from report.

I also see those things in log:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 1046, in sendto
    self._sock.sendto(data, addr)
AttributeError: 'NoneType' object has no attribute 'sendto'
```

```
AttributeError: 'NoneType' object has no attribute 'call_exception_handler'
```

**Comment by vi** [comment]
Another spurious failure:

```
Traceback (most recent call last):
  File "/home/tribler/tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 114, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: Task was destroyed but it is pending!
```
---

Is `tribler/docker-tribler-prod` a good way to run Tribler in general? Or is it some abandoned experiment?

**Comment by vi** [comment]
```
Traceback (most recent call last):
  File "/home/tribler/tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 114, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: Task was destroyed but it is pending!
```

**Comment by devos50** [comment]
> Is tribler/docker-tribler-prod a good way to run Tribler in general? Or is it some abandoned experiment?

First of all, we are not actively maintaining our docker file so it might contain outdated references. @xoriole maybe you want to maintain this/update it?

Regarding the error, it seems that the error is happening in IPv8, specifically [here](https://github.com/Tribler/py-ipv8/blob/4c96d27bca866fa9a27267fc2c6b19822e1e2e54/ipv8/messaging/anonymization/tunnel.py#L164). It also seems that this error only occurs when you act as an exit node, so please double-check whether this is the case and whether this is intended. This particular error _should_ have been fixed already, since we are catching `OSError` and `ValueError` when DNS resolution fails.

Since this is not a Tribler issue, and an IPv8 issue instead, I will close this one. Please double-check whether you are running the latest version of Tribler and the IPv8 submodule. If the issue persists after you checked that, feel free to leave another comment on this issue and we can debug it further 👍

**Comment by vi** [comment]
It's the latest version of `tribler/docker-tribler-prod` image. But it was `CREATED` `7 months ago`, so I doubt it's has the last version of Triber&deps inside.

**Comment by egbertbouman** [comment]
@vi Regarding the first error. I did some digging in the Git history, and it seems you're using an older version of IPv8 (b330ca9b0ff2b9166765a12f6c72c20bfa601e38 or earlier) where the resolve error wasn't caught properly. So, you're right. It's using older versions of Tribler/IPv8.

**Comment by vi** [comment]
Shall new version of Docker image be published to Hub each time new stable Triber version is tagged?

**Comment by xoriole** [comment]
Regarding the Tribler docker image, I have published a few repositories for running (popularity) experiments. However, it does not include a full Tribler at the moment. 

This is the docker image used to run the core only.
https://hub.docker.com/repository/docker/triblercore/core

>@xoriole maybe you want to maintain this/update it?
I can create a Jenkins job that pushes the latest devel or release image to the docker hub.

**Comment by vi** [comment]
Will it include `tribler/docker-tribler-prod`?

Also can Triber run core and GUI separate again, like long ago?

**Comment by xoriole** [comment]
>Will it include tribler/docker-tribler-prod?

Yes

> Also can Triber run core and GUI separate again, like long ago?

Ideally, it should but there are some issues to fix atm.

**Comment by vi** [comment]
>> Will it include tribler/docker-tribler-prod?
> Yes

Currently the image is still version  5a5d40220b8b (8 months ago).
When will it be updated?
