### ISSUE TITLE
[Crash reporter] Bad gateway error on loading bulky pages

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#5663]
Crash reporter currently fails to load pages which includes huge amount of data (issues) which should be fixed.

While the crash reporter could be improved, a quick fix could be to increase the data loading timeout (as suggested by @devos50)

![Screenshot from 2020-10-20 13-22-23](https://user-images.githubusercontent.com/1442867/96580088-133e0680-12d8-11eb-9bea-1d3f0aa207bd.png)

**Comment by kozlovsky** [comment]
Fixed
