### ISSUE TITLE
Soft-crash of all 7.5.2 instances (Mac,Linux)

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#5670]
With a historic bug we might have managed to kill off all online instances of Tribler 7.5.2

Every online Tribler peers running 7.5.2 (reproduced on Ubuntu and Mac) who conducts a ```New_Tribler_Version()``` check has a popup window which overwrites the default Tribler GUI from which there is no escape:
![Screenshot from 2020-10-22 17-34-34](https://user-images.githubusercontent.com/325224/96895731-feef3a80-148c-11eb-85f1-d03ec69116ef.png)
Both the "Ignore" and the "Later" button do not make the blocking popup go away. The "OK" button opens a new browser window on both Ubuntu and Mac successfully, but does not close the popup. Open questions: is this also happening on Windows?

**Comment by devos50** [comment]
I am unable to reproduce this on both my Mac and the Win10-64bit machine in proxmox.

**Comment by synctext** [comment]
On Linux I just discovered I was running: ```tribler_7.5.2-2-g33fa321bb_all.deb```.

**Comment by xoriole** [comment]
I think it is because there are multiple popup stacked. Not sure how that happened since the version check duration is 6 hours unless it is running for a long time.

To reproduce the issue, I tried reducing the version check duration to a few seconds and I had a similar screen quickly. The popup should be a singleton and dispose any previous popus.

**Comment by ichorid** [comment]
Installed 7.5.2 on Ubuntu 20.04, everything works fine :shrug:

**Comment by synctext** [comment]
> I think it is because there are multiple popup stacked. Not sure how that happened since the version check duration is 6 hours unless it is running for a long time.

Great to hear this! That could explain a lot. Tribler usually runs for at least a week. For past 15 years its been often in the background on one or two laptops.

Capturing these cornercases has consistently been hard. For many years we needed an easier way for our users to report bug and capture state in detail.

**Comment by xoriole** [comment]
> Can we have a unit test reproducing the multiple popups?

https://github.com/Tribler/tribler/pull/5700 includes a test for it
