### ISSUE TITLE
Tribler GUI Test to test sending crash report works 

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#5671]
We have 12 reports today with the following stacktrace:

```
Tribler GUI Test to test sending crash report works
```

![image](https://user-images.githubusercontent.com/13798583/96898987-074d7280-1499-11eb-9e49-55dae24fbeb7.png)

Maybe it is related to #5670

**Comment by drew2a** [comment]
Maybe it is just a real test event?

**Comment by devos50** [comment]
We are indeed sending these GUI test reports to the backend. IRC, @xoriole made that back in the days.

**Comment by drew2a** [comment]
@devos50 thanks for the information.
