### ISSUE TITLE
config_converter.convert_state_file_to_conf_74: TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#5672]
The error was reported from some old version of Tribler ("Tribler version: None"), but looking at the code, it seems actual for the current `devel` branch:

It seems that in the code below, the `value` returned from `config.get(...)` might be None, and then `value + '\n'` generates `TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`:

```python
   # in tribler_core/upgrade/config_converter.py
   def _fix_state_config(config):
        for section, option in [('state', 'metainfo'), ('state', 'engineresumedata')]:
            value = config.get(section, option, literal_eval=False)
            try:
                value = str(refactoring_tool.refactor_string(value + '\n', option + '_2to3'))
                ...
            except (ValueError, SyntaxError, ParseError) as ex:
                logger.error("Config could not be fixed, probably corrupted. Exception: %s %s", type(ex), str(ex))
                return None
```

So, after retrieving the value it should be checked for `None`, but then what? How should this situation be handled?

**Comment by devos50** [comment]
First of all, even though we haven't fully discussed how we are going to utilize milestones, please try to assign each new issue to one. When in doubt, you can always assign it to the next release. This prevents us from having 'dangling' issues that might be overlooked later.

Now, that logic is related to an upgrade from Tribler 7.4.0, where we converted older `.pstate` files to `.conf` files. I'm not sure if we have a test for this but it looks easy to reproduce.

**Comment by drew2a** [comment]
The code that caused the error seems to have been removed.
