### ISSUE TITLE
Remove references to illegal content

### ISSUE THREAD

**Issue by Eonfge** [Tribler/tribler#5674]
In light of the recent removal of [youtube-dl](https://www.theregister.com/2020/10/23/riaa_youtube_dl_github/) I implore you to review your own site, documentation and (test-)code for possible references to copyrighted work.

In the statement of the RIAA, they have one of the following arguments:

> We also note that the source code prominently includes as sample uses of the source code the downloading of copies of our members’ copyrighted sound recordings and music videos, as noted in Exhibit A hereto. For example, as shown on Exhibit A, the source code expressly suggests its use to copy and/or distribute the following copyrighted works owned by our member companies:
> - Icona Pop – I Love It (feat. Charli XCX) [Official Video], owned by Warner Music Group
> - Justin Timberlake – Tunnel Vision (Explicit), owned by Sony Music Group
> - Taylor Swift – Shake it Off, owned/exclusively licensed by Universal Music Group

https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md

This is also the case with your screenshot material for example, which makes reverences to products like:
- [Swing it!](https://www.imdb.com/title/tt1653074/)
- [Deadside](https://www.imdb.com/title/tt2330681/)

These screenshots should be replaced, and for certainty, you should check the rest of your documentation

**Comment by devos50** [comment]
Thank you, we will look into this! 👍

**Comment by synctext** [comment]
Thnx for the help! Yes, as an alternative to Youtube, Spotify, [and TikTok](https://www.bbc.com/news/newsbeat-54059334) we don't want to get into legal trouble. Things are heating up... [Swing it! from 2010 on Archive.org](https://archive.org/details/VODO201SwingIt/Swing.It.2010.Xvid-VODO.avi), this VODO content is OK to mention. 
![Screenshot from 2020-10-24 11-14-31](https://user-images.githubusercontent.com/325224/97078134-20b20400-15ea-11eb-870d-5a72dc718148.png)
The "Deadside 2012" also is VODO Creative Commons content licence, [also legit and OK to mention](http://www.legittorrents.info/index.php?page=torrent-details&id=e3867473ac97b23489efe0eb820241aabd678611). 
Please let us know if you find other mentions which might be questionable.

**Comment by synctext** [comment]
Vodo.net died, great example of reason for Tribler to exist. Their VODO Creative Commons content is no longer available on [archive.org](https://web.archive.org/web/20190302132943/http://vodo.net/films/). Deadside is dead, broken link..
![Screenshot from 2020-10-24 11-52-30](https://user-images.githubusercontent.com/325224/97078852-76d57600-15ef-11eb-8c3f-37ae418e94b7.png)

**Comment by qstokkink** [comment]
It seems that this issue has been sufficiently addressed now.
