### ISSUE TITLE
[devel] Fix the trust graph to use our new bandwidth accounting mechanism

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5675]
In #5623, we described and implemented a new mechanism for bandwidth accounting. Now that #5626 has been merged, the trust graph needs to be improved to use the information generated by our new bandwidth accounting mechanism. @xoriole already indicated that he would like to fix t his.

I think this is the only location in the code where TrustChain is still used. So, after this has been addressed, we can finally move TrustChain to AnyDex.

**Comment by xoriole** [comment]
The new trust graph
![trust-graph-new](https://user-images.githubusercontent.com/1442867/98003462-10223a80-1def-11eb-865a-56093930b56b.png)

**Comment by Houkime** [comment]
Master at 8f8272d6b9ae1dbcc4b64fa18f0fdd0ae8ec752e   
When opening trust graph:

```
 File "/home/user/tribler/src/tribler-core/tribler_core/restapi/rest_manager.py", line 43, in error_middleware
    response = await handler(request)
  File "/usr/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/home/user/tribler/src/tribler-core/tribler_core/restapi/trustview_endpoint.py", line 209, in get_view
    self.initialize_graph()
  File "/home/user/tribler/src/tribler-core/tribler_core/restapi/trustview_endpoint.py", line 161, in initialize_graph
    if self.session.trustchain_community:
AttributeError: 'Session' object has no attribute 'trustchain_community'
```

It seems like trustchain thing is already absent from session, but trust graph still uses it.

**Comment by devos50** [comment]
Thanks for pointing this out! @xoriole is currently working on it and we aim to address this issue very soon (likely somewhere next week) 👍
