### ISSUE TITLE
[devel] Implement a crawling mechanism for our new bandwidth accounting mechanism

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5676]
Now that #5626 has been merged, we require a mechanism for peers to construct the global work graph. Specifically, each peer should slowly explore the (latest) transactions of other peers, which acts as input for our upcoming reputation mechanism. #5626 does not implement the required primitives for requesting transactions from other peers. We also need this to deploy a crawler that monitors network health.

### The approach

The mechanism relies on simple pull-based gossip. Peers send out `TransactionQuery` message to other peers of which it would like to request the latest, pairwise transactions. Peers send back individual `Transaction` messages. Queries do not have an associated request cache, to keep the mechanism simple. In fact, our mechanism can deal with missing messages or peers that go offline quickly after receiving a query.

For now, we will query the immediate neighbours in a round-robin fashion. We can later extend our approach to also query the transactions of two-hop/three-hop peers.

**Comment by drew2a** [comment]
@devos50 should we add this issue to `7.6.0` milestone?

**Comment by devos50** [comment]
Sure, we can do that 👍
