### ISSUE TITLE
[7.5.3] Debug Pane - error loading IPv8 stats

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#5679]
From error reporter [#36072](http://reporter.tribler.org/stacktrace/36072) 
```python
Traceback (most recent call last):
File "tribler_gui/debug_window.py", line 328, in on_ipv8_community_stats
KeyError: 'master_peer'
```
Platform: Linux
Uptime: 99.89 seconds

**Comment by devos50** [comment]
Interesting. We removed the master peer from IPv8 communities but this change should not be in 7.5.3 (it is on devel instead). I cannot reproduce this one on 7.5.3 on Mac.

Could this be with a custom IPv8 pointer?

**Comment by xoriole** [comment]
This should be fixed by now. Cannot reproduce the issue, closing.
