### ISSUE TITLE
[devel] Peer explosion

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#5699]
![oh no!](https://user-images.githubusercontent.com/3630389/97414937-e2c42100-1904-11eb-9cfb-4d538638d728.png)

We have a new peer explosion bug. The RemoteQueryCommunity sets a custom `max_peers` count and custom `RandomWalk` target peer count, but **uses the same Network instance** as all other communities. This causes the peer balancing to break (note that some Communities get LESS peers due to this).

To fix this, the RemoteQueryCommunity should either:

 1. Stick to the defaults.
 2. Use its own `Network()` to not kill off the other communities.

**Comment by qstokkink** [comment]
The fixes themselves aren't that much work, but one of these should be chosen:

Option 1:

```patch
diff --git a/src/tribler-core/tribler_core/modules/ipv8_module_catalog.py b/src/tribler-core/tribler_core/modules/ipv8_module_catalog.py
index 73e65e326..40b093f0a 100644
--- a/src/tribler-core/tribler_core/modules/ipv8_module_catalog.py
+++ b/src/tribler-core/tribler_core/modules/ipv8_module_catalog.py
@@ -122,7 +122,7 @@ class GigaChannelTestnetCommunityLauncher(TestnetMixIn, GigaChannelCommunityLaun
 @set_in_session('remote_query_community')
 @overlay('tribler_core.modules.metadata_store.community.remote_query_community', 'RemoteQueryCommunity')
 @kwargs(metadata_store='session.mds', notifier='session.notifier')
-@walk_strategy('ipv8.peerdiscovery.discovery', 'RandomWalk', target_peers=50)
+@walk_strategy('ipv8.peerdiscovery.discovery', 'RandomWalk')
 class RemoteQueryCommunityLauncher(IPv8CommunityLauncher):
     pass
 
diff --git a/src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py b/src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py
index 894a59c43..89646f9c2 100644
--- a/src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py
+++ b/src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py
@@ -76,7 +76,6 @@ class RemoteQueryCommunity(Community):
         super(RemoteQueryCommunity, self).__init__(my_peer, endpoint, network)
 
         self.notifier = notifier
-        self.max_peers = 60
 
         self.settings = settings or RemoteQueryCommunitySettings()

```

Option 2:

```patch
diff --git a/src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py b/src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py
index 894a59c43..96d3f9ba2 100644
--- a/src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py
+++ b/src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py
@@ -5,6 +5,7 @@ from random import sample
 from ipv8.community import Community
 from ipv8.lazy_community import lazy_wrapper
 from ipv8.messaging.lazy_payload import VariablePayload, vp_compile
+from ipv8.peerdiscovery.network import Network
 from ipv8.requestcache import RandomNumberCache, RequestCache
 
 from tribler_common.simpledefs import CHANNELS_VIEW_UUID, NTFY
@@ -73,6 +74,7 @@ class RemoteQueryCommunity(Community):
     community_id = unhexlify('dc43e3465cbd83948f30d3d3e8336d71cce33aa7')
 
     def __init__(self, my_peer, endpoint, network, metadata_store, settings=None, notifier=None):
+        network = Network()
         super(RemoteQueryCommunity, self).__init__(my_peer, endpoint, network)
 
         self.notifier = notifier
```

**Comment by devos50** [comment]
Why do we need 60 peers in the search community? To get more diverse results? I remember that we always used a lower number (around 30).

**Comment by drew2a** [comment]
Do we have documentation on "peer balancing"?

**Comment by qstokkink** [comment]
In this case https://www.usenix.org/legacy/events/nsdi0/tech/full_papers/shen/shen_html/ seems applicable: there is no real difference between a degree of 8-32 and 16-64 for information propagation speed. I also know of research that suggests a degree of 12 for Internet use (but I can't find it right this moment 😃). IPv8 is already rather conservative with its default of 20-30 peers. Might as well use the default 🤷.

> Do we have documentation on "peer balancing"?

Sort of. Essentially, the documentation is the list of papers @synctext has produced and the references surrounding that. Most of these settings are very fragile and can explode in your face. If you want to deviate from the defaults, you'll have to read most of that and perform some experiments at scale (or ask us if what you're doing is a good idea). We only guarantee that the defaults work, as they've proven themselves over years of use.

So, is there documentation on these parameters: yes an entire scientific field of it. Is it easy to read? no.

**Comment by ichorid** [comment]
Actually, RQC does not need more than an average amount of peers for search queries. But it wants to constantly walk and never stop, like a shark :shark: , because it wants to query as much peers as possible for Channel entries in the background. This is especially important for new peers for bootstrapping Channels contents.

@qstokkink , what settings should we use for RQC to achieve this mode (average number of peers + constant restless walking)?

**Comment by qstokkink** [comment]
> @qstokkink , what settings should we use for RQC to achieve this mode (average number of peers + constant restless walking)?

Given your requirements, the RQC should use "option 2" and then also add a custom discovery strategy. I can whip that up for you if you want.

**Comment by ichorid** [comment]
Shouldn't it be possible to achieve the same thing without creating a custom `Network` instance? I would expect creating a custom discovery strategy to be enough to solve this kind of problems.

**Comment by ichorid** [comment]
Also, is there some kind of documentation about how `Network` relates to DiscoveryCommunity and walk strategies?

**Comment by qstokkink** [comment]
No, that would always unbalance the peer counts and---even worse---if you hook in a custom walking strategy: destabilize the network topology. Generally, it is very hard to build trust or reputation in a network that continuously serves you new people to interact with.

That is why I recommended option 2, to not mix strategies: if you isolate your custom walking from the other walkers, everything still works, no matter what peers you add or remove.

I would urge you to forward random information in the established topology though, instead of continuously looking for new peers with a custom strategy: puncturing NATs is not as nice and efficient as it sounds.

**Comment by qstokkink** [comment]
I am too slow in responding apparently 😞 

> Also, is there some kind of documentation about how Network relates to DiscoveryCommunity and walk strategies?

This is based on the `4P: Performant Private Peer-to-Peer File Sharing` paper.

**Comment by ichorid** [comment]
>if you isolate your custom walking from the other walkers, everything still works, no matter what peers you add or remove.

Ok, this means I don't understand how our walkers work :face_with_head_bandage:. I thought each community walks independently.

**Comment by ichorid** [comment]
@qstokkink , could you please prepare a patch for "Option 2" into `release-7.5` branch then? It is the best option for the moment, as you pointed out. Meanwhile, I'll think about redesigning the information forwarding pattern.

**Comment by qstokkink** [comment]
> I thought each community walks independently.

They do, initially. After this comes the next phase where you try to converge to a set of peers with the highest similarity (for reasons: see the paper I linked). That is where the story of blocking introduction requests and responses come in and the Churn strategy.

> @qstokkink , could you please prepare a patch for "Option 2" into release-7.5 branch then? It is the best option for the moment, as you pointed out. Meanwhile, I'll think about redesigning the information forwarding pattern.

👍  on it.
