### ISSUE TITLE
Add Sentry error reporting to the Tribler Client

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#5727]
This issue is linked to https://github.com/Tribler/tribler/issues/5715

Updated version:

As a developer, I want to increase the quality of receiving debug information and decrease the count of supported entities (Reporter).

So let's add Sentry to Tribler Client as a "backup system" that will accomplish the same work as the current Reporter do. Keep all the UX unchanged.

Will release it in `7.6.0` and evaluate how it works.

Old version:
```
Now we use Sentry as a mirror for the actual reporter. This has greatly increased the convenience of working with error reports. But the way we use Sentry is unnatural for Sentry itself and leaves an intermediate entity (reporter) that is used as a proxy.

The idea is to send crash reports directly to Sentry.

Changes:
1. Add to the installer a checkbox "Automatically sends crash reports to the Tribler team?"
2. Add to the crash reporter dialog the same checkbox.
3. If the checkbox is set, then let's sentry to be initialized and be able to send crash reports.

Note. Before sending a crash report we should cut all sensitive information.

In the first month, we will use both the old reporter and Sentry. 
After the first month, we have to review how it works.
```

**Comment by devos50** [comment]
If this option is enabled by the user during installation, do we still show the stack trace when a crash occurs? But automatically send the crash report without explicit action by the user?

**Comment by drew2a** [comment]
I was thinking about not showing the stack trace when a crash occurs.

But maybe the approach is too radical for now ;)

Probably, it is better to leave all logic the same, but only to send additional reports to a different Sentry project.
And then review how it works.

**Comment by devos50** [comment]
> But maybe the approach is too radical for now ;)

It's not radical at all but I wonder if there is really much to win when we send these reports automatically :)

**Comment by drew2a** [comment]
If I understand user behavior right, then we will get more error reports in case of "automatically sent is enabled".
Also, probably we can detect some crashes that do not come to GUI.

**Comment by synctext** [comment]
For long-term future:
- Sentry bug report upload from within Tribler
  - reproducing user bugs is key bottleneck for fixing them
  - hardest part is capturing bug in the wild
  - filter out issues we don't yet support (full hard-disk etc) (user is never to blame, Tribler should be robust to anything)
- Custom bug builds
  - we make a pledge to hunt down every bug until its fixed
  - for an upcoming release we could focus on "custom bug hunting"
  - make easy build process for single-user builds 
  - increase debugging info
  - we dont give up, if you dont give up!

**Comment by drew2a** [comment]
@synctext sure :)
