### ISSUE TITLE
Youtube-like streaming focus and auto-seeding

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#573]
Youtube does not have explicit management of your streaming cache.
No local file storage is needed if streaming simply always works!

The "Downloads" section is used to stop and delete files.  The long-term evolution of Tribler is removal of the explicit file management for users. Only optionally users can manage their files explicitly.

We only need a small play-out buffer for streaming. Additionally, seed a certain amount of the last downloaded GBytes to ensure swarm health. Optionally, rely on credit mining only for upload.

**Comment by ichorid** [comment]
RIP VLC and our GUI-video ambitions
