### ISSUE TITLE
Popularity community - network experiment

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#5742]
Most popularity community experiments that we currently have either observe the network or change its own behaviour and take measurements. This does not give the bigger picture of the effect of algorithmic change in the network scale. Therefore, the issue here is about network experiments observing the network behavior instead of a single node.

**Current behavior**
1. Max 10 torrent health info is sent in a community message that is sent to a randomly chosen peer at an interval of 5 seconds.
2. Periodically a random tracker is checked every 20 seconds which further checks some torrents on that tracker
3. Periodically a maximum of 10 random torrents is checked every 120 seconds

Ignoring the fact that the user is checking some torrents manually via the GUI, the random tracker and torrent check are the mechanism that produces the fresh torrent health info which is shared by the popularity community.

**Experiment 1**

Experiment 1 is about increasing the number of health info that can be fitted into a message payload and observing the network behavior.

Cases:
- [x] ~~10 torrents info (current behavior)~~
- [x] ~~20 torrents info~~
- [x] ~~40 torrents info or more~~

***Experiment 1 is not significant itself unless there are sufficient torrents checked to fill up the message in a short experiment duration***

**Experiment 2**

Experiment 2 is about increasing the delay before the first message is sent to the neighbor peers. Since in the first 5 seconds when the first message is sent out, there would not be enough data to send. Previously, this resulted in sending dead torrents information in the message.

Cases:
- [x]  ~~5 seconds (current)~~
- [x] ~~15 seconds~~
- [x] ~~60 seconds~~
- [x]  ~~until a full message can be filled~~

***Initial buffer time does not seem signficant in the default implementation because there are not enough torrents checked to compose a full message to share***

**Experiment 3**

Experiment 3 is about updating the periodic selection of random torrents to check health to prioritize on popular torrents on the database based on last check and size of seeders. This enforces checks of received popular torrent info from other peers which in turn verifies the health info and propagate in the network.

Cases:
Random torrent check outputs
- [ ] 5 random + 5 popular torrents from DB
- [ ] 10 random + 10 popular torrents  from DB

**Setup**
The setup is a controlled gumby environment. Each node peer is setup initially with 100 torrents in the database.

The experiment runs for
- [ ] 5 minutes (DAS5)
- [ ] 10 minutes (Zulu)
- [ ] 1 hour (Zulu)

None of the above experiments or the changes should break the compatibility with the existing popularity community.

**Comment by xoriole** [comment]
The following graph shows the current behavior of popularity community on idle Tribler run. The local database had 664 torrents setup before execution. During the 20 minutes experiment, there are barely enough checked torrents that fill up a single message size (currently supports 10 torrents). There were a total of 215 messages shared by the peer during the execution. Since there were not enough torrent information share, it makes sense that several peers were receiving the same duplicate message.

![1  Torrents gossipped over time (20 mins)](https://user-images.githubusercontent.com/1442867/100093216-81399880-2e57-11eb-8799-60735b104a31.png)
![2  Gossipped torrents classification (20 mins)](https://user-images.githubusercontent.com/1442867/100093227-85fe4c80-2e57-11eb-96e2-24d02876446c.png)

From the graph, 
- It seems that it takes a long time to bootstrap the network (on idle run). This experiment ignore the user clicking on torrent to check the health or download.
- The proposed duration of the experiments (5 minutes, 10 minutes, 1 hr) would not sufficiently cover the case where the effect of increasing the number of torrents in a message is seen. So, the experiment time should be sufficiently large spanning several hours.

**Comment by synctext** [comment]
Policy idea: 50% of time check swarms from your subscribed channels.
50% random swarm check.
Check swarms 1 time per hour, you collected 1 unique outgoing message, repeat same outgoing info

**Comment by synctext** [comment]
Future Goal: 10k people which are in your ledger and your trust their torrent checks (E.g. Ledger-based in future). As proposed in #3868, we could do a dynamic refresh loop. My proposal is to keep this static for now: refresh your swarm check you broadcast once per hour.

**Comment by xoriole** [comment]
**Experiment results**
<br/>
``default`` - Current implementation, after 120 seconds 3 torrents are checked, then 1 random torrent periodically
``default-10`` - Current implementation, after 120 seconds 10 torrents are checked, then 1 random torrent periodically

---
``new-1/1-pop/rand`` - New implementation, every 120 seconds, 1 random and 1 popular torrent is checked
``new-2/2-pop/rand`` - New implementation, every 120 seconds, 2 random and 2 popular torrents are checked
``new-5/5-pop/rand`` - New implementation, every 120 seconds, 5 random and 5 popular torrents are checked
`new-10/10-pop/rand` - New implementation, every 120 seconds, 10 random and 10 popular torrents are checked

---
``new-db-5/5-pop/rand`` - New implementation, torrents checked in last 4 hours are included, every 120 seconds 5 random and 5 popular torrents are checked
``new-db-10/10-pop/rand`` - New implementation, torrents checked in the last 4 hours are included, every 120 seconds 10 random and 10 popular torrents are checked

---


![Popularity community performance(1)](https://user-images.githubusercontent.com/1442867/101906038-a0a32600-3bb8-11eb-98c0-bd0cd10be10b.png)
![pop-com-result](https://user-images.githubusercontent.com/1442867/101908001-aa7a5880-3bbb-11eb-8fc7-57cc5e2962d0.png)

All 20 nodes started with 100 initial torrents

**Comment by qstokkink** [comment]
It seems like this experiment is now concluded and no further work is to be done. I'll close this issue.
