### ISSUE TITLE
Encoding argument removed in Python 3.9

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5744]
In Python 3.9, the `encoding` keyword argument got removed from the call to `json.loads`. This results in the following error:

```
[PID:55108] 2020-11-21 16:58:23,992 - ERROR <tribler_window:108> root.on_exception(): Traceback (most recent call last):
  File "/Users/martijndevos/Documents/tribler/src/tribler-gui/tribler_gui/tribler_request_manager.py", line 120, in <lambda>
    request.reply.finished.connect(lambda: request.on_finished(request))
  File "/Users/martijndevos/Documents/tribler/src/tribler-gui/tribler_gui/tribler_request_manager.py", line 203, in on_finished
    json_result = json.loads(bytes(data), encoding='latin_1')
  File "/Users/martijndevos/Documents/tribler/src/tribler-core/tribler_core/utilities/json_util.py", line 112, in loads
    return json.loads(s, *args, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

I'm not entirely sure why we have chosen for that particular encoding, but removing the keyword argument seems to correctly start Tribler.

**Comment by qstokkink** [comment]
The reason is that `latin_1` can encode and decode just about anything, which made it a good fit for sending binary data through JSON (even though JSON *should* only send `UTF-8`).

Now that the majority of the interfaces are sanitized and no more binary garbage is being sent, crashing on non-utf-8 data should be fine.

**Comment by synctext** [comment]
Continuous breakage when upgrading... Just wait till you read the Python4 features:-)
https://charlesleifer.com/blog/new-features-planned-for-python-4-0/

**Comment by devos50** [comment]
> The GIL has been removed.
Just kidding! Instead we've been focusing all our effort on making it easier to juggle multiple interpreter data-structures within a single thread. No, no, you can thank us later!

😅
