### ISSUE TITLE
Replace PR "Print statements checker" with Flake-8 plugin

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#5749]
We can obsolete the "Print statements checker" check on PRs (which was essential at the time, as neither `pylint` nor `flake8` detect this in Python 3.x) with the https://pypi.org/project/flake8-print/ plugin.

This change would make print statement detection simply another check in the Flake 8 report.

Required changes:

 - Install the `flake8-print` pip package on `bbq`.
 - Enable the `T001`, `T002`, `T003`, `T004` errors in the PR Flake 8 Jenkins job.

**Comment by qstokkink** [comment]
I'll hook this in.

**Comment by qstokkink** [comment]
- The `flake8-print` Flake8 plugin has been added to `bbq`.

 - The `PR_prints_check` on Jenkins has been **disabled** (note: not removed).

If we don't experience any problems in the coming month or so we can probably completely remove the `PR_prints_check` permanently. I'll keep this issue open until that has happened.

**Comment by ichorid** [comment]
Also, try running `pyupgrade` through `pre-commit` on the whole codebase. Fun stuff!

**Comment by qstokkink** [comment]
Oops, forgot to close this. This has been done long ago.
