### ISSUE TITLE
API breakage

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#5756]
```
grep api .Tribler/7.5/triblerd.conf
[http_api]
[api]
```

Is that just a name change that was not cleaned up by an upgrade or are they actually different things?

**Comment by devos50** [comment]
IIRC, the name of the configuration section was changed from `http_api` to `api` when upgrading Tribler from 7.4 to 7.5. Leaving the old one there should not causing any issues.

**Comment by Dmole** [comment]
Thanks.
