### ISSUE TITLE
Cannot stop torrent downloading using devel branch of Tribler

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#5762]
If I start downloading some torrent using devel branch (let's say [Ubuntu 20.10 torrent](https://releases.ubuntu.com/20.10/ubuntu-20.10-desktop-amd64.iso.torrent) for specificity), and then press the "stop" button (looked as a square in a circle), or select the "Stop" command of the drop-down menu for this torrent file, I see the following:

In the next few seconds, the torrent status switches several times between "Downloading" and "Stopped" back and force, and then stabilizes on "Stopped". But then, half a minute later, the torrent again become "Downloading". It was not possible for me to stop downloading completely, it always started again after some time.

When I try the same on the 7.5.3 release, everything works as expected. The torrent switches from "Downloading" to "Stopped" (well, there is actually a very short switch back to "Downloading" and then finally to "Stopped"), and then it remains in the "Stopped" state without a spontaneous switch to "Downloading" state again.

**Comment by ichorid** [comment]
Ok, I confirm the thing will jump back and forth between states for a second, but then it stabilized on "Stopped" for me.

**Comment by devos50** [comment]
This has actually been the case for a very, very long time already. It should eventually stop, but if that's not the case, there's probably something wrong.

@kozlovsky which lib torrent version are you running with?

**Comment by kozlovsky** [comment]
@devos50 my lintorrent version is 1.2.10

I can stable reproduce this bug on my machine: if I stop any torrent, it will switch again to "Downloading" or "Seeding" after approximately 15-25 seconds. I will investigate it.
