### ISSUE TITLE
[Sentry] Increase event fields size limit

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#5781]
Some of the fields inside our crash reports are truncated.
Eg `message` here: https://sentry.tribler.org/organizations/tribler/issues/210

This is because sentry Sentry truncates events just before sending:
https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/serializer.py#L61
https://develop.sentry.dev/sdk/data-handling/#variable-size

We have to increase this number both in the client and in the server to make sure that important information will not be cut.

**Comment by qstokkink** [comment]
The exception message itself showcases another error:

```python
Exception occurred while handling packet!
Traceback (most recent call last):
  File "ipv8\messaging\anonymization\community.py", line 640, in on_packet_from_circuit
  File "ipv8\messaging\anonymization\community.py", line 41, in wrapper
  File "ipv8\messaging\anonymization\community.py", line 785, in on_extended
  File "src\tribler-core\tribler_core\modules\tunnel\community\triblertunnel_community.py", line 438, in _ours_on_created_extended
  File "ipv8\messaging\anonymization\community.py", line 505, in...
```

This traceback comes from https://github.com/Tribler/py-ipv8/blob/ef8b40963127f174025d6542c715cb06d33ebd5d/ipv8/community.py#L465-L466 : 

```python
self.logger.error("Exception occurred while handling packet!\n"
                  + ''.join(format_exception(*sys.exc_info())))
```

Tribler shouldn't crash on a logging statement and it probably actually also doesn't.

This was identified by @egbertbouman a while ago, but we sort-of forgot about it and never fixed it 🤓: 
https://github.com/Tribler/tribler/blob/334e32de83548e4ccafd9ca2918e72b68c877961/src/tribler-gui/tribler_gui/core_manager.py#L52-L56

The log statement prints something with the word "Traceback" in it and this is set as the `core_traceback`, even though it's not the offending line but probably the result of an earlier failure. Maybe we should actually make an issue for this now.

**Comment by drew2a** [comment]
I made a small research on how Sentry processed events on a client-side.

The news:
1. Serialisation, in general, is happened before `before_sent` procedure: https://github.com/Tribler/tribler/blob/b29e4a6739d57e887bc9a738584d1ee84d1669d2/src/tribler-common/tribler_common/sentry_reporter/sentry_reporter.py#L308
2. The data in the event['context'] field remains untrimmed because `context` field recognizes as not a `databag`
https://github.com/getsentry/sentry-python/blob/b7816b0cc100a47082922b8dd3e058134ad75d7c/sentry_sdk/serializer.py#L253

For us, that means it is possible to increase an event's field size limit only on the server-side to get untrimmed events and a stacktrace.
