### ISSUE TITLE
"recreating indexes..." database migration phase has no progress indication despite of being the slowest step

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#5785]
##### Tribler version/branch+revision: #####

v7.6.0-exp1, upgrading from v7.5.4

##### Operating system and version: #####

Linux, Docker

##### Steps to reproduce the behavior: #####

1. Use Tribler 7.5.4, have downloads, channel subscriptions, etc.
2. Upgrade to 7.6.0-exp1
3. Observe database migration process in GUI

##### Expected behavior: #####

It displays some percentage constantly, showing that it is not stuck.

##### Actual behavior: #####

"creating indexes..." and "adding full text search index..." seems to be longer than initial phases for which estimate and percentage is shown.

If those phases typically take, for example, twice as long as initial phase, it may show approximate time estimate based on duration of the initial phases.

**Comment by ichorid** [comment]
Unfortunately, we can't break down the indexes creation process: it is controlled by SQLite internally. Maybe we can show at least *something* to soothe the user that the process is not stuck.

Also, I'm pretty sure it is impossible to estimate the time it takes to recreate the indexes. These are highly non-linear and depend heavily both on the PC's RAM size, CPU, HDD/SSD speed and the size of the database.

**Comment by vi** [comment]
Does [this callback](https://www.sqlite.org/c3ref/progress_handler.html) not work when creating indexes?

**Comment by qstokkink** [comment]
For reference, that callback does exist in the Python API: https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.set_progress_handler
We could investigate.

**Comment by hbiyik** [comment]
liked this thing, thanks!
![image](https://user-images.githubusercontent.com/24766436/101268593-f3b64c80-3764-11eb-85bf-a221b78c423d.png)
