### ISSUE TITLE
[7.6.0-exp1] Tribler refuses to start properly when forced closed

### ISSUE THREAD

**Issue by Shidouuu** [Tribler/tribler#5790]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

7.6.0-exp1; Also happens with 7.5.4

##### Operating system and version: #####

Windows 10 2004

##### Steps to reproduce the behavior: #####

Close Tribler by shutting down Windows. I have not tested it with task manager.

##### Expected behavior: #####

Tribler closes.

##### Actual behavior: #####

After booting up Windows again and starting Tribler, a message pops up saying that a Tribler core process is already running, and prompts the user if they want a clean restart or not. If the user clicks yes, then you get sent to an indefinite loading screen, which closes Tribler after awhile. While it is doing this, if you close it normally and start it again, it will work normally.

##### Relevant log file output: #####

"tribler.exe.log" is empty.

**Comment by ichorid** [comment]
Could you please send your `.Tribler` directory to us somehow? Say, pack it in a torrent and post the infohash here. To keep your private key, you can exclude all the `*.pem` files from all the subdirectories of `.Tribler` config dir.

**Comment by Shidouuu** [comment]
8828fed72106584bc55d7645a2f57caa4c4218e6

**Comment by Shidouuu** [comment]
As of 7.6.1 I no longer encounter this issue so I'll be closing it now

**Comment by JeffRockatansky** [comment]
Still experiencing this bug in v7.12 on Linux

**Comment by kozlovsky** [comment]
@JeffRockatansky thank you for reporting! It was fixed in #6941, and the fix will be available in 7.12.1 in a few days
