### ISSUE TITLE
[7.5.4] Our version checker triggers on the 7.6 experimental release

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5791]
When running 7.5.4, I get the pop-up to update to the experimental version of 7.6. This has caused many users to update to an experimental version which can still be unstable.

The issue is in the version check manager, where we query `releases.tribler.org`. This URL includes unstable releases and as such, triggers the version checker.

**Comment by devos50** [comment]
@xoriole this has been fixed right?

**Comment by xoriole** [comment]
Yes, this is fixed and deployed to release.tribler.org. No client side changes are necessary.
