### ISSUE TITLE
[devel] Core is importing from PyQt5

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5799]
Minor issue, but I found that the core is importing Qt stuff through the packages in `tribler-common`:

```
Traceback (most recent call last):
  File "/Users/martijndevos/Documents/tribler/src/tribler-core/run_bandwidth_crawler.py", line 20, in <module>
    from tribler_core.session import Session
  File "/Users/martijndevos/Documents/tribler/src/tribler-core/tribler_core/session.py", line 23, in <module>
    from tribler_common.sentry_reporter.sentry_reporter import SentryReporter
  File "/Users/martijndevos/Documents/tribler/src/tribler-common/tribler_common/sentry_reporter/sentry_reporter.py", line 7, in <module>
    from PyQt5.QtWidgets import QApplication, QMessageBox
```

When running the core, I would like to avoid importing from `PyQt5` as much as possible.

**Comment by ichorid** [comment]
Yep, totally agree. The Core should be completely independent of the QT stuff.

**Comment by ichorid** [comment]
@drew2a , could you come up with some way to move the stuff to e.g. `run_tribler.py`?

**Comment by drew2a** [comment]
`QMessageBox` needs to confirm sending unhandled errors without interaction with GUI.

**Comment by drew2a** [comment]
Two cases:
1. An error had occurred before core-GUI interaction has been established.
2. An error has been occurred in `self.unhandled_error_observer`

**Comment by Dmole** [comment]
> `QMessageBox` needs to confirm sending unhandled errors without interaction with GUI.

It really need not.
Have a setting to auto send or not in the config.
And/or dump it in the log file (assuming it's not already,  that's what it's for)

**Comment by devos50** [comment]
It now also requires the DAS5 nodes to have PyQt5 installed:

```
INFO:ProcessRunner:[] ERR: 2020-12-07 04:08:56,575:INFO:All subscribers connected!
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: 2020-12-07 04:08:56,574:INFO:Scenario file found, using /var/scratch/pouwelse/jenkins2/workspace/validation_experiments/validation_experiment_dht/gumby/experiments/dht/dht_experiment.das4.scenario
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: 2020-12-07 04:08:57,095:INFO:Unable to load gumby.modules.tribler_module as a local module, exception: No module named 'PyQt5'
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: 2020-12-07 04:08:57,098:ERROR:Unable to import tribler_module from /var/scratch/pouwelse/jenkins2/workspace/validation_experiments/validation_experiment_dht/gumby/gumby/modules as gumby.modules.tribler_module: No module named 'PyQt5'
```

@drew2a when running Tribler in headless mode, I do not want to install a GUI library only for a single dialog that only triggers when an error occurs. Note that it is also likely to fail when running Tribler on (headless) remote servers without VNC installed. Can we/do we want to send these reports automatically, without showing a dialog?
