### ISSUE TITLE
Downloads Pane/Section

### ISSUE THREAD

**Issue by snakyjake1** [Tribler/tribler#5803]
##### Actual behavior: #####
I think the section in the left pane that says "Downloads", and the main tab that says "Downloads" should be changed to something else.

![image](https://user-images.githubusercontent.com/8312560/101196806-1f4c1080-3659-11eb-85ef-338d61083e55.png)

##### Expected behavior: #####
Why?
Because there's more activity going on than just downloading.
I'm seeding.
I'm also passing/contributing data to the Tribler network (which would be nice to see in near real time so I know what's going on with my own network).

I think the pane titles should be changed from "Downloads" to "Activity" or "Activities".

Also, I think the headers "ALL", "DOWNLOADING", "COMPLETED", "ACTIVE", "INACTIVE" should match and be filters for the torrent STATUS.

##### Tribler version/branch+revision: #####
v7.6.0-exp1

##### Operating system and version: #####
Windows

**Comment by ichorid** [comment]
Thanks for the suggestion! We already changed a lot in the GUI for this release. Also, we're still a torrent client after all, and torrent clients tend to have the "Downloads" section :wink:. So we will keep this for awhile.

Though, I agree that at least _something_ should be done with the downloads section appearance.
