### ISSUE TITLE
Token balance is hidden for now

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5807]
The token balance has been hidden until we fix the issue with the "magic" payouts. Also see #5804.

**Comment by Dmole** [comment]
Thanks, it's been flawed since inception.
It's now 2 clicks away for anyone interested ("Trust Graph > YOU").

**Comment by graphixillusion** [comment]
@Dmole I just updated to 7.6.1 and if i click on "Trust Graph > YOU" i got everything to ZERO. Previously my token was around 150GB

**Comment by heldersepu** [comment]
same issue as @graphixillusion  after upgrade (`7.5.1 > 7.6.1`) my token balance down to 0

**Comment by heldersepu** [comment]
Also, the Trust Graph seems to be broken after a few downloads it still shows the same
![Screenshot from 2020-12-29 09-49-55](https://user-images.githubusercontent.com/545474/103292473-d79c7880-49bb-11eb-8cc2-6e908ca2b002.png)

**Comment by xoriole** [comment]
token balance is back so closing this issue
