### ISSUE TITLE
[7.6.0] Settings lost on upgrade

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#5811]
Download location, watch_folder, bandwidth, etc were all blanked.

maybe related;
https://github.com/Tribler/tribler/issues/5129

**Comment by ichorid** [comment]
Would you kindly send us the config file from the version you upgraded from? For instance, if you upgraded from 7.5 to 7.6, your 7.5 config is `.Tribler/7.5/triblerd.conf`
