### ISSUE TITLE
Get GUI connect() pyqtSignal creation traceback

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#5818]
In #5754 we encountered a single-line traceback, namely:

```python
TypeError: <lambda>() missing 1 required positional argument: '_'
```

The reason this "traceback" is only 1 line is because `pyqtSignal` pretty much strips all context info when calling registered callbacks. We could add context to this type of error ourselves by adding information about the calling stack to the `pyqtSignal.connect(...)` call by wrapping it. Here is a prototype hooked into only the `received_json` signal of the `TriblerNetworkRequest` class:

```patch
diff --git a/src/tribler-gui/tribler_gui/tribler_request_manager.py b/src/tribler-gui/tribler_gui/tribler_request_manager.py
index 872deae24..e7c7ebc45 100644
--- a/src/tribler-gui/tribler_gui/tribler_request_manager.py
+++ b/src/tribler-gui/tribler_gui/tribler_request_manager.py
@@ -13,6 +13,26 @@ from tribler_gui.defs import BUTTON_TYPE_NORMAL, DEFAULT_API_HOST, DEFAULT_API_P
 from tribler_gui.dialogs.confirmationdialog import ConfirmationDialog
 
 
+def rich_connect(signal, callback):
+    import inspect
+    import types
+
+    source = None
+    for frame in list(inspect.stack())[1:]:
+        source = types.TracebackType(source,
+                                     frame.frame,
+                                     frame.index,
+                                     frame.lineno)
+
+    def trackback_wrapper(*args, **kwargs):
+        try:
+            callback(*args, **kwargs)
+        except BaseException as e:
+            raise e.with_traceback(source)
+
+    signal.connect(trackback_wrapper)
+
+
 def tribler_urlencode(data):
     # Convert all keys and values in the data to utf-8 unicode strings
     utf8_items = []
@@ -172,7 +192,7 @@ class TriblerNetworkRequest(QObject):
         self.raw_data = raw_data if (issubclass(type(raw_data), bytes) or raw_data is None) else raw_data.encode('utf8')
         self.reply_callback = reply_callback
         if self.reply_callback:
-            self.received_json.connect(self.reply_callback)
+            rich_connect(self.received_json, self.reply_callback)
 
         self.on_error_callback = on_error_callback
         if on_error_callback is not None:
```

This would extend the example traceback from a single line to the following:

```python
[PID:10274] 2020-12-07 15:31:18,863 - ERROR <tribler_window:117> root.on_exception(): Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/src/tribler-gui/tribler_gui/tribler_request_manager.py", line 31, in trackback_wrapper
    raise e.with_traceback(source)
  File "/home/quinten/Documents/tribler/src/run_tribler.py", line 154, in <module>
    sys.exit(app.exec_())
  File "/home/quinten/Documents/tribler/src/tribler-gui/tribler_gui/widgets/downloadspage.py", line 538, in on_right_click_item
    menu.exec_(self.window().downloads_list.mapToGlobal(pos))
  File "/home/quinten/Documents/tribler/src/tribler-gui/tribler_gui/widgets/downloadspage.py", line 392, in on_move_files
    TriblerNetworkRequest(
  File "/home/quinten/Documents/tribler/src/tribler-gui/tribler_gui/tribler_request_manager.py", line 196, in __init__
    rich_connect(self.received_json, self.reply_callback)
TypeError: <lambda>() missing 1 required positional argument: '_'
```

There are two downsides to this approach:

 1. Our code will become slightly slower. So this would not be a great fit for callbacks that need to be highly performant (though I don't think we really have any of those).
 2. We have to enforce that everyone uses this method for every `connect()` (which could also count as an upside if we do have calls which need to be performant).

**Comment by ichorid** [comment]
Well, the only thing in the GUI that relies heavily on signals is the Channels table lazy loading. Adding this method at least as another tool for programmer should not affect the performance *per se*. I would say, let's try it out. Also, we can decide if the thing should decorate the calls in the runtime, say if we're running in the debug mode. One way or another, it adds more control over the execution.

**Comment by qstokkink** [comment]
Converted all of the calls, ran into this type of error:

```python
[PID:3991] 2020-12-08 11:06:41,826 - ERROR <tribler_window:117> root.on_exception(): Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/src/tribler-gui/tribler_gui/utilities.py", line 383, in trackback_wrapper
    raise e.with_traceback(source)
  File "/home/quinten/Documents/tribler/src/run_tribler.py", line 154, in <module>
    sys.exit(app.exec_())
  File "/home/quinten/Documents/tribler/src/tribler-gui/tribler_gui/utilities.py", line 381, in trackback_wrapper
    callback(*args, **kwargs)
  File "/home/quinten/Documents/tribler/src/tribler-gui/tribler_gui/widgets/downloadspage.py", line 500, in on_right_click_item
    connect(move_files_action.triggered, self.on_move_files)
TypeError: on_move_files() takes 1 positional argument but 2 were given
```

By default, `pyqtSignal`s apparently fit the amount of arguments they deliver to the amount of arguments the function takes. If a signal is emitted with more arguments, they are not delivered to the callback. Basically, we are silently dropping emit arguments.

For example:

```python
callback = lambda data: None  # Note: takes 1 argument.
signal.connect(callback)

signal.emit("Here, have some data", ":)")  # Perfectly fine.
callback("Here, have some data", ":)")  # TypeError: callback() takes 1 positional argument but 2 were given
```

We could do one of two things:

 1. Force all callbacks to handle the arguments that are emitted.
 2. Mimic `pyqtSignal` and drop extra arguments (and perhaps log that).

Now in principle I am in favor of not silently dropping stuff (option 1). But, transitionally, it might be better to start by just mimicing what we have right now. So, perhaps a two-phase approach would be best?

**Comment by ichorid** [comment]
That C++ - style behaviour of silently *overloading* signals with no-arguments versions had already bitten quite a few times. I would prefer the Python-style behaviour (arguments must match strictly).
