### ISSUE TITLE
tribler crashes on linux when trying to build myself

### ISSUE THREAD

**Issue by damnms** [Tribler/tribler#5822]
#### Please, fill all relevant items: ####

- [ n ] I have read CONTRIBUTING.rst

- [ n ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
7.6.0

##### Operating system and version: #####
Fedora 33
##### Steps to reproduce the behavior: #####
download sources, install required deps, start with ./src/tribler.sh
##### Expected behavior: #####
the gui should popup with no error
##### Actual behavior: #####
tribler crashes with a stacktrace
##### Relevant log file output: #####
[oli@DESKTOP-DM65VNV tribler-7.6.0]$ ./src/tribler.sh 
[PID:29674] 2020-12-08 15:07:26,871 - INFO - root(24) - __init__()
[PID:29674] 2020-12-08 15:07:26,911 - INFO - root(50) -   self._outSocket.error() = '2'
[PID:29674] 2020-12-08 15:07:26,912 - INFO - root(60) - __init__(): returning
[PID:29674] 2020-12-08 15:07:27,137 - INFO - TriblerGUI(126) - Will connect to events endpoint
[PID:29674] 2020-12-08 15:07:27,181 - INFO - TriblerGUI(68) - Got Tribler core error: 1
[PID:29674] 2020-12-08 15:07:27,656 - INFO - TriblerGUI(126) - Will connect to events endpoint
[PID:29674] 2020-12-08 15:07:27,657 - INFO - TriblerGUI(68) - Got Tribler core error: 1
Traceback (most recent call last):
  File "/home/oli/Downloads/tribler-7.6.0/src/run_tribler.py", line 105, in <module>
start_tribler_core(base_path, api_port, api_key, root_state_dir, core_test_mode=core_test_mode)
  File "/home/oli/Downloads/tribler-7.6.0/src/run_tribler.py", line 32, in start_tribler_core
    from tribler_core.session import Session
  File "/home/oli/Downloads/tribler-7.6.0/src/tribler-core/tribler_core/session.py", line 40, in <module>
    from tribler_core.modules.ipv8_module_catalog import register_default_launchers
  File "/home/oli/Downloads/tribler-7.6.0/src/tribler-core/tribler_core/modules/ipv8_module_catalog.py", line 5, in <module>
    from ipv8.loader import CommunityLauncher, after, kwargs, overlay, precondition, set_in_session, walk_strategy
ImportError: cannot import name 'after' from 'ipv8.loader' (/home/oli/.local/lib/python3.9/site-packages/ipv8/loader.py)
[PID:29674] 2020-12-08 15:07:27,727 - INFO - SentryReporter(224) - Event from exception: The Tribler core has unexpectedly finished with exit code 1 and status: 0!

Traceback (most recent call last):
  File "/home/oli/Downloads/tribler-7.6.0/src/run_tribler.py", line 105, in <module>

(Timestamp: 1607436447727, traceback timestamp: 1607436447662)
[PID:29674] 2020-12-08 15:07:27,727 - ERROR <tribler_window:117> root.on_exception(): Traceback (most recent call last):
  File "/home/oli/Downloads/tribler-7.6.0/src/tribler-gui/tribler_gui/core_manager.py", line 79, in on_core_finished
    raise RuntimeError(exception_msg)
RuntimeError: The Tribler core has unexpectedly finished with exit code 1 and status: 0!

Traceback (most recent call last):
  File "/home/oli/Downloads/tribler-7.6.0/src/run_tribler.py", line 105, in <module>

(Timestamp: 1607436447727, traceback timestamp: 1607436447662)

[PID:29674] 2020-12-08 15:07:49,599 - INFO - SentryReporter(137) - Send: {'version': '7.6.0-GIT', 'machine': 'x86_64', 'os': 'Linux-5.10.0-0.rc6.90.vanilla.1.fc33.x86_64-x86_64-with-glibc2.32', 'timestamp': 1607436469, 'sysinfo': 'os.getcwd\t/home/oli/Downloads/tribler-7.6.0/src\nsys.executable\t/usr/bin/python3\nos\tposix\nplatform\tlinux\nplatform.details\tLinux-5.10.0-0.rc6.90.vanilla.1.fc33.x86_64-x86_64-with-glibc2.32\nplatform.machine\tx86_64\npython.version\t3.9.0 (default, Oct  6 2020, 00:00:00) \n[GCC 10.2.1 20200826 (Red Hat 10.2.1-3)]\nindebug\tTrue\ntribler_uptime\t0.8341038227081299\nsys.argv\t/home/oli/Downloads/tribler-7.6.0/src/run_tribler.py\nsys.path\t/home/oli/Downloads/tribler-7.6.0/src/pyipv8\nsys.path\t/home/oli/Downloads/tribler-7.6.0/src\nsys.path\t/home/oli/Downloads/tribler-7.6.0/src\nsys.path\t/home/oli/Downloads/tribler-7.6.0/src/pyipv8\nsys.path\t/home/oli/Downloads/tribler-7.6.0/src/anydex\nsys.path\t/home/oli/Downloads/tribler-7.6.0/src/tribler-common\nsys.path\t/home/oli/Downloads/tribler-7.6.0/src/tribler-core\nsys.path\t/home/oli/Downloads/tribler-7.6.0/src/tribler-gui\nsys.path\t/usr/lib64/python39.zip\nsys.path\t/usr/lib64/python3.9\nsys.path\t/usr/lib64/python3.9/lib-dynload\nsys.path\t/home/oli/.local/lib/python3.9/site-packages\nsys.path\t/usr/lib64/python3.9/site-packages\nsys.path\t/usr/lib/python3.9/site-packages\nsys.path\t.\nos.environ\tIMSETTINGS_INTEGRATE_DESKTOP: yes\nos.environ\tSHELL: /bin/bash\nos.environ\tSESSION_MANAGER: local/unix:@/tmp/.ICE-unix/2589,unix/unix:/tmp/.ICE-unix/2589\nos.environ\tWINDOWID: 77594800\nos.environ\tPYQTGRAPH_QT_LIB: PyQt5\nos.environ\tCOLORTERM: truecolor\nos.environ\tXDG_CONFIG_DIRS: /etc/xdg\nos.environ\tXDG_SESSION_PATH: /org/freedesktop/DisplayManager/Session0\nos.environ\tHISTCONTROL: ignoredups\nos.environ\tXDG_MENU_PREFIX: xfce-\nos.environ\tHOSTNAME: DESKTOP-DM65VNV\nos.environ\tHISTSIZE: 1000\nos.environ\tSSH_AUTH_SOCK: /tmp/ssh-a2JfHbNaOKgv/agent.2589\nos.environ\tXMODIFIERS: @im=none\nos.environ\tDESKTOP_SESSION: xfce\nos.environ\tSSH_AGENT_PID: 2752\nos.environ\tEDITOR: /usr/bin/nano\nos.environ\tXDG_SEAT: seat0\nos.environ\tPWD: /home/oli/Downloads/tribler-7.6.0/src\nos.environ\tXDG_SESSION_DESKTOP: xfce\nos.environ\tLOGNAME: oli\nos.environ\tXDG_SESSION_TYPE: x11\nos.environ\tPANEL_GDK_CORE_DEVICE_EVENTS: 0\nos.environ\tXAUTHORITY: /run/lightdm/oli/xauthority\nos.environ\tXDG_GREETER_DATA_DIR: /var/lib/lightdm-data/oli\nos.environ\tHOME: /home/oli\nos.environ\tSSH_ASKPASS: /usr/libexec/openssh/gnome-ssh-askpass\nos.environ\tLANG: de_DE.utf8\nos.environ\tLS_COLORS: rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:\nos.environ\tXDG_CURRENT_DESKTOP: XFCE\nos.environ\tVTE_VERSION: 6201\nos.environ\tXDG_SEAT_PATH: /org/freedesktop/DisplayManager/Seat0\nos.environ\tIMSETTINGS_MODULE: none\nos.environ\tMOZ_GMP_PATH: /usr/lib64/mozilla/plugins/gmp-gmpopenh264/system-installed\nos.environ\tXDG_SESSION_CLASS: user\nos.environ\tPYTHONPATH: :/home/oli/Downloads/tribler-7.6.0/src/pyipv8:/home/oli/Downloads/tribler-7.6.0/src/anydex:/home/oli/Downloads/tribler-7.6.0/src/tribler-common:/home/oli/Downloads/tribler-7.6.0/src/tribler-core:/home/oli/Downloads/tribler-7.6.0/src/tribler-gui\nos.environ\tTERM: xterm-256color\nos.environ\tLESSOPEN: ||/usr/bin/lesspipe.sh %s\nos.environ\tUSER: oli\nos.environ\tDISPLAY: :0.0\nos.environ\tSHLVL: 2\nos.environ\tQT_IM_MODULE: xim\nos.environ\tXDG_VTNR: 1\nos.environ\tXDG_SESSION_ID: 2\nos.environ\tXDG_RUNTIME_DIR: /run/user/1000\nos.environ\tKDEDIRS: /usr\nos.environ\tXDG_DATA_DIRS: /home/oli/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/usr/share\nos.environ\tPATH: /home/oli/bin:/home/oli/.local/bin:/home/oli/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/var/lib/snapd/snap/bin\nos.environ\tGDMSESSION: xfce\nos.environ\tDBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus\nos.environ\tMAIL: /var/spool/mail/oli\nos.environ\tOLDPWD: /home/oli/Downloads/tribler-7.6.0\nos.environ\t_: /usr/bin/python3\nos.environ\tQT_AUTO_SCREEN_SCALE_FACTOR: 1\nos.environ\tTRIBLER_SHUTTING_DOWN: False\nrequest_1\thttp://localhost:8085/channels?include_total=1&first=1&last=50&sort_by=votes&sort_desc=1&hide_xxx=1 GET None (time: 1607436447.1188893, code: None)\nrequest_2\thttp://localhost:8085/state GET None (time: 1607436447.1839185, code: None)\nrequest_3\thttp://localhost:8085/shutdown PUT None (time: 1607436447.7283227, code: 0)\n', 'comments': 'tried to get tribler starting on fedora 33 to create flatpak', 'stack': 'Traceback (most recent call last):\n  File "/home/oli/Downloads/tribler-7.6.0/src/tribler-gui/tribler_gui/core_manager.py", line 79, in on_core_finished\n    raise RuntimeError(exception_msg)\nRuntimeError: The Tribler core has unexpectedly finished with exit code 1 and status: 0!\n\nTraceback (most recent call last):\n  File "/home/oli/Downloads/tribler-7.6.0/src/run_tribler.py", line 105, in <module>\n\n(Timestamp: 1607436447727, traceback timestamp: 1607436447662)'}, None
[PID:29674] 2020-12-08 15:07:53,186 - INFO - root(165) - Shutting down Tribler

**Comment by qstokkink** [comment]
Note that only the `.tar.xz` release contains the submodules required to run Tribler. The `zip` and `tar.gz` do not contain the submodules which you appear to be missing.

**Comment by damnms** [comment]
hm? what submodules? is this documented? guess i missed that.
i thought i can download the .tar.gz and build it myself. i installed (i guess) all dependencies, i dont understand the problem tbh.

**Comment by qstokkink** [comment]
Git has the concept of submodules. Essentially, this is a soft link (a pointer) to another project on GitHub.

In Tribler we have one of these. In the [`src/` source folder](https://github.com/Tribler/tribler/tree/devel/src) you can spot this as `pyipv8 @ c0a6f85`. If you follow the recommended cloning instructions from our `README.md` the `git clone --recursive https://github.com/Tribler/tribler.git` takes care of this fully automatically. However, if you choose to download the sources GitHub provides, you will need to resolve this manually.

The problem is two-fold. Firstly, GitHub provides the `zip` and `tar.gz` source code distributions which we cannot edit. Secondly, these pre-made distributions do not include the submodules we need (only the [`pyipv8`](https://github.com/Tribler/py-ipv8) one in this case).

As we cannot edit the GitHub `zip` and `tar.gz` directly, we instead opted to distribute a `.tar.xz`, that does include all of the required Tribler submodules.

So, if you don't want to use `git clone`, you have one of two options:

 a. Download [the submodule](https://github.com/Tribler/py-ipv8) at the correct pointer and place it in the proper folder (`src/pyip8`).
 b. Download the `tar.xz` release archive we made that includes the required submodule already. Note that _we only make these for releases_ though.

Using `git` with GitHub makes your life a whole lot easier though and we recommend following the steps in the `README.md`.

**Comment by damnms** [comment]
i installed pyipv8 with pip, in that case there is an incompatibility
[oli@DESKTOP-DM65VNV ~]$ pip list | grep pyipv8
pyipv8                   2.4.0

i'll give it a try with git submodules (even tho thats discouraged to use afaik)

**Comment by xoriole** [comment]
Looking at the last comment on the issue, the build from the source with recursive clone is working.
Please reopen the issue if you're having issues building from source in future versions.
