### ISSUE TITLE
[7.6.1] object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#5850]
This issue affects multiple users in 7.6.1 release. As I understand it, the error happens in `ipv8.messaging.anonymization.hidden_services`:

```python
    def create_e2e(self, info_hash, intro_point):
        circuit = self.select_circuit_for_infohash(info_hash)
        if not circuit:
            self.logger.error("No circuit for contacting the introduction point")
            return

        hop = Hop(Peer(LibNaCLPK(intro_point.seeder_pk[10:])))
        ...
```
As I understand it, in the last line `intro_point.seeder_pk` is an empty byte string for some reason, and as a result, `LibNaCLPK` constructor receives `b''` as an argument, and the `pk` value inside `LibNaCLPK.__init__()` becomes `None`.

**Comment by egbertbouman** [comment]
This is probably due to a serialization issue. The error shows up if the last byte of the public key of the introduction point is 0x00. I fixed this in IPv8. As soon as the pointer is updated, this issue can be closed.

**Comment by egbertbouman** [comment]
Note that even though this issue is fixed, the error will continue to show up since the exit nodes are still running the old code.
