### ISSUE TITLE
Setup test nodes to run Tribler 24/7

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#5857]
Setup test nodes to run Tribler 24/7

Why?
- To find out if there are issues on normal Tribler network.
- To find out if there are crashes on the release candidate or past stable versions and report them.

Where to setup?
- Proxmox or Zulu

Tribler version:
- last stable (eg. 7.6.1)
- new candidate (eg. 7.7/ devel)

Requirements:
- Sentry should be configured to report crashes
- Alert developers if a crash is found

**Comment by drew2a** [comment]
There is one more improvement to Sentry, that should be done:
1. We should add a value to the config to allow sending crash reports without confirmations.

**Comment by xoriole** [comment]
Update: Jenkins jobs running the old and newer versions are setup here:
1. https://jenkins-ci.tribler.org/job/Deployment-Tests/job/long-runner-new-release/
2. https://jenkins-ci.tribler.org/job/Deployment-Tests/job/long-runner-old-release/

The newer version installer is obtained via jenkins build and the last stable installer is obtained via Github release URL.

**Comment by xoriole** [comment]
With the above jenkins jobs setup and running, I consider this issue as resolved.
