### ISSUE TITLE
[devel] Tribler crashes on searching 

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#5864]
Tribler crashes on searching (pressing enter after typing query) on the latest devel https://github.com/Tribler/tribler/commit/d0fd7d4712a99183e3269898c7d2da6c312015e9
```
[PID:87260] 2020-12-17 16:27:07,396 - ERROR <tribler_window:124> root.on_exception(): Traceback (most recent call last):
  File "/home/jupiter/tudelft/release/tribler/src/tribler-gui/tribler_gui/tribler_window.py", line 699, in on_top_search_button_click
    self.search_results_page.preview_clicked()
TypeError: preview_clicked() missing 1 required positional argument: 'checked'
```

**Comment by qstokkink** [comment]
https://github.com/Tribler/tribler/blob/d0fd7d4712a99183e3269898c7d2da6c312015e9/src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py#L287

That needs to be:

```python
def preview_clicked(self, checked=False): 
```

**Comment by xoriole** [comment]
Yes, that works. I have a feeling that we might get more of this type of issues in the coming days.
