### ISSUE TITLE
[UX] Progress bar is still visible after downloading has been stopped.

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#5886]
Version: 7.6.1 (latest devel)

![image](https://user-images.githubusercontent.com/13798583/103222304-323ec180-4935-11eb-8cdc-ff564af52d3e.png)

##### Step to reproduce: #####
1. Run a new Tribler instance
2. Start downloading for Ubuntu 19.04
3. Go to the Downloads page
4. Stop Ubuntu downloading
5. Return to Discovered page

##### Expected behavior: #####

No progress bar

##### Actual behavior: #####

The progress bar is visible

**Comment by ichorid** [comment]
Well, this one is a bit harder then it looks on the surface... To solve it properly, we'll have to make Channels views subscribe to downloads-related events. I'm going to handle it later.

**Comment by ichorid** [comment]
I think the progress bar still should be there in case the download is *stopped*, but not deleted.
