### ISSUE TITLE
Maximize DHT swarm size by adding other DHT bootstrap servers

### ISSUE THREAD

**Issue by kilves76** [Tribler/tribler#5900]
These DHT bootstrap servers could be added to maximize the size of the DHT swarm available to a Tribler client:

> dht.libtorrent.org:6881
> dht.transmissionbt.com:6881
> router.utorrent.com:6881
> router.bittorrent.com:6881
> dht.aelitis.com:6881
> router.bitcomet.com:6881

The initial swarms are regimented according to the app as many torrent apps do not permit adding more, or users don't know how. Adding them all as default maximizes a Tribler peer's chances of finding content and is a benefit to everyone.

**Comment by synctext** [comment]
thnx!
Do we override Libtorrent DHT bootstrap defaults?

**Comment by ichorid** [comment]
AFAIK, we don't. At least there are no mentions of it in the code.

**Comment by ichorid** [comment]
By default, Libtorrent uses `dht.libtorrent.org` bootstrap node.

**Comment by qstokkink** [comment]
This does seem like something we could easily implement though: the [add_dht_node and add_dht_router](http://svn.netlabs.org/repos/ports/libtorrent/vendor/0.14.12/docs/manual.html#add-dht-node-add-dht-router) calls exist in libtorrent and should be [available in the bindings](https://github.com/arvidn/libtorrent/blob/RC_2_0/bindings/python/src/session.cpp#L82-L97) (on `session` instances).

**Comment by egbertbouman** [comment]
We're already adding DHT routers manually. We just need to extend the list in the `DownloadManager`:
https://github.com/Tribler/tribler/blob/4999bfc2e9432df49932f709f9d42bb83ba6d21c/src/tribler-core/tribler_core/modules/libtorrent/download_manager.py#L35-L39

**Comment by ichorid** [comment]
@egbertbouman , what's the difference between `add_dht_router` and setting `dht_bootstrap_nodes` then? The former adds to the latter, right?

**Comment by egbertbouman** [comment]
@ichorid Right, the `add_dht_router` function adds to the list and the `dht_bootstrap_nodes` sets the list.

**Comment by arvidn** [comment]
dht routers are not treated as regular nodes. They are only used when bootstrapping the DHT fails. for example if there aren't any nodes saved from the last session, or they all fail to be contacted.

routers *could* also be made to never be saved in the routing table, but I don't think there's any logic like that currently, but doing so might make sense in the future.

**Comment by ichorid** [comment]
@synctext , so, is it possible to increase connectivity and get to bigger swarms by adding more bootstrap nodes to `libtorrent`?

**Comment by arvidn** [comment]
it's not obvious to me that it would have that effect. Especially if the routing table is already "full". And if the routing table isn't full, it may be caused by some connectivity problem where nodes are lost too frequently to be replenished. In which case the tweaks to the table maintenance settings might be in order. Say, more frequent bucket refreshes.
