### ISSUE TITLE
3 Tribler Releases / Branches

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#5917]
Many Tribler releases introduce fatal new bugs.

As Tribler is clearly missing automated testing (many VMs sequentially on one cheap box)

Please adopt main/testing/release branches and builds so bugs can be squashed before hitting the the main download on tribler.org.

example bugs:
7.7.0 - crash on exclude files
7.6.1 - "max node" popup
7.5.2 - crash om load with GLIBC_2.29' not found 
7.5.0 - infinite loop on large torrent 
7.5.0 - no documentation for API change
7.5.0 - removal of headless API
... and many (~[2841](https://github.com/Tribler/tribler/issues?q=is%3Aissue)) more.

Very few if any releases are bug free. A stable branch is long overdue IMO.

devos50 said some internal discussion would happen so here is a public reminder.

**Comment by Shidouuu** [comment]
+1
Something like Pylance which comes with the python extension in VSC would prevent a lot of these bugs.

**Comment by synctext** [comment]
We indeed need to do a better job on bug fixing.

We are doing quick releases to maximize progress on Tribler. We have invested a lot of time in automated testing and deployment monitoring. This should start to pay-off soon with good quality code. Basically our code should never be 'unstable'.

**Comment by Dmole** [comment]
> We are doing quick releases to maximize progress on Tribler.

That is not mutualy exclusive; just have every release go through a 1 week beta, fixing and re-building as bugs are reported, then mark the release as stable.

> We have invested a lot of time in automated testing and deployment monitoring.

Adding a code-coverage metric would quantify if that time payed off. But you need not invest at all just let users do the beta testing.

> Basically our code should never be 'unstable'.

It currently (7.7) is  'unstable'  while advertised as 'stable' on tribler.org thus this issue.

**Comment by Dmole** [comment]
So  14 days ago we had a V7.8.0-RC1 but then instead of making it a release  2 hours ago V7.8.0 was released with a long change log and without any user testing. All non-RC builds should have a 1 item change log "released"... guess I'll go check for bugs after the fact.

**Comment by xoriole** [comment]
@Dmole We understand your concern. We do not want to ship a buggy release as well. In the last two weeks of RC release, we did not receive any critical bug reports, so we're releasing a stable version today. The urgency is also because `7.8.0` includes an important fix to a memory leak issue so we want to get this out there quickly.

Regarding the changelog in the release page, it lists the changes since the last stable version (7.7.1), and not the latest RC (7.8.0-RC1). The actual difference from the lastest RC is very small and also tested.

**Comment by Dmole** [comment]
@xoriole v7.8.0 "Showed token balance again" without fixing any of https://github.com/Tribler/tribler/labels/component%3A%20token%20economy

**Comment by xoriole** [comment]
@Dmole That commit is part of a PR that was added since RC1. The token balance display was hidden earlier because of a bug that caused users to have insane balance. Now that bug is fixed and the balances are wiped so it was added back. It should not affect the normal Tribler usage.

**Comment by Dmole** [comment]
So we agree the release was not done properly because
> All non-RC builds should have a 1 item change log "released"
or are you saying that a release should contain commits that were not in the RC?
That's a rhetorical question; I'm just trying to thank contributers by providing some unsolicited thoughts on best practices effecting user adoption. :)

**Comment by xoriole** [comment]
@Dmole Thank you for the feedback

**Comment by qstokkink** [comment]
Starting from the 8.0 release, we will adopt a different branch management process with more frequent releases.
