### ISSUE TITLE
[7.7.1] "Discovered page" switches to the "Search page" after clicking on torrents column

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#5924]
##### Tribler version/branch+revision: #####
7.7.1, latest release

##### Operating system and version: #####
macOS

##### Steps to reproduce the behavior: #####
1. Open Tribler
2. Search for "some"
3. Go to the Discovered page
4. Press Torrents column for any channel

##### Expected behavior: #####
Nothing should happen

##### Actual behavior: #####
Page switches to the "Search results page"

![image](https://user-images.githubusercontent.com/13798583/104176479-5c55b080-5418-11eb-9c43-c79fd5e6de71.png)

**Comment by xoriole** [comment]
I suppose this is fixed. I can no longer reproduce the issue.
