### ISSUE TITLE
[Wireframes] A better Feedback Dialog

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#5952]
@xoriole requested a better Feedback Dialog to increase the count of error reports and to improve the quality.

Below I propose the new Feedback Dialog's wireframes as a discussion starter.

![Crash Report](https://user-images.githubusercontent.com/13798583/105842006-da4bb700-5fd5-11eb-8845-d97e3cf7b5d1.png)

**Comment by qstokkink** [comment]
Given the latest GUI rework, this issue is no longer relevant.
