### ISSUE TITLE
[7.7.0] ValueError: "File not found in torrent" during config conversion to Tribler 7.5

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#5965]
The error happens during execution of [`convert_config_to_tribler75`](https://github.com/Tribler/tribler/blob/f875e417c14d5c2fb972629954ecc477d18ebdf5/src/tribler-core/tribler_core/upgrade/config_converter.py#L117), in [`TorrentDef.get_index_of_file_in_files`](https://github.com/Tribler/tribler/blob/089fb6ab1c597b90a051f35350d0e3703d3a07a6/src/tribler-core/tribler_core/modules/libtorrent/torrentdef.py#L460):

```python
def convert_config_to_tribler75(state_dir):
    """
    Convert the download config files from Tribler 7.4 to 7.5 format.
    """
    for filename in (state_dir / STATEDIR_CHECKPOINT_DIR).glob('*.conf'):
        try:
            ...
            # Convert metainfo
            metainfo = config.get_metainfo()
            if not config.config['download_defaults'].get('selected_files') or not metainfo:
                continue  # no conversion needed/possible, selected files will be reset to their default (i.e., all files)
            tdef = TorrentDef.load_from_dict(metainfo)
            config.set_selected_files([tdef.get_index_of_file_in_files(fn)
                                       for fn in config.config['download_defaults'].pop('selected_files')])
            ...
```

It affects a small number of users. I can guess it may be caused by some encoding problems.

Maybe we can just skip files which name was not found from the list of selected files?

**Comment by drew2a** [comment]
Closing the issue as it affects only a small amount of users and we (probably) never find a time to fix it in the future.
