### ISSUE TITLE
[Wireframes] Channel's home page

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#5977]
Seems to be rational to implement Channel's home page step-by-step.

Steps:
1. Page edit available for channel's owners only 
1. Page edit available for all contributors (pull request based)

# Page edit available for channel's owners only 

Note: content view can be Table-based or Thumbnail-based. It may be related to https://github.com/Tribler/tribler/issues/5957

![Channel Home Page (step1) (2)](https://user-images.githubusercontent.com/13798583/107029173-e5a99a00-67ae-11eb-8d49-7ffda69783bd.png)

## References
1. [Sentry: Configure Suspect Commits](https://sentry.tribler.org/organizations/tribler/issues/270/?project=7)
1. [Soundcloud: Adding an image when uploading a track](https://help.soundcloud.com/hc/en-us/articles/115003565268-Adding-an-image-when-uploading-a-track)
1. [GitHub: File Edit](https://github.com/Tribler/tribler/edit/devel/README.rst)
1. [YouTube: Channel's header](https://www.youtube.com/user/tudelft)
1. [GitHub: Edit button](https://github.com/Tribler/tribler#tribler)
1. [Spotify: header during scrolling](https://open.spotify.com/playlist/37i9dQZF1DX4je779Ww5L2)

**Comment by drew2a** [comment]
# Page edit available for all contributors (pull request based)

Coming soon...

**Comment by ichorid** [comment]
How do nested channels combine with this?

**Comment by drew2a** [comment]
@ichorid discussed offline. 
The mockup has been updated regarding this conversation.

**Comment by synctext** [comment]
Requires generic UDP-based binary transfer or Libtorrent re-use.
