### ISSUE TITLE
Bounty payout voting and payment execution - self-evolving AI-DAO

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#5986]
### Master course on Blockchain Engineering project 2021

**TEAM P3: Bounty payout voting and payment execution**
Your team ensures people get paid for evolution of features. Use muti-sig wallet and quorum-based voting to create real-world Bitcoin payouts. Sync the vote progress with others, visualise as votes come in (approve or reject) and display the undecided votes. Any developer can contribute code to the DAO and get paid. It disconnects the DAO from any bank, government, and legal system. Help create a global economy that is hyper-efficient, fair, honest, and digital. [prior work](https://github.com/Tribler/trustchain-superapp/blob/7a958aec39b89b8a7015d508ef440553a0403788/currencyii/README.md)

### General Description - self-evolving AI-DAO (https://github.com/Tribler/tribler/issues/5944)
Student from Delft have created a blockchain-based alternative to Spotify. Completely decentralised. Uses Bittorrent for streaming, Bitcoin for payments to artists, Trustchain with IPv8 for music discovery and IPv8 for app-to-app connectivity. With multiple teams the aim is to take this code to the next level: self-evolution.

A total of 4 students teams (4-5 students in each team) will work together on a cutting-edge scientific problem: how to create a software system which can be expanded in real-time and increasingly become more '_intelligent_'. Build upon the existing open source app by TUDelft on the Android Play store using blockchain technology: the [Superapp](https://github.com/Tribler/trustchain-superapp/). You will help transform essential parts of the music industry and replace them with open source software. Current code:

<details>
<summary>GIF: Browsing and streaming music with Bittorrent </summary>
<img src="https://user-images.githubusercontent.com/4957928/103173843-e5d48280-485d-11eb-907a-e20c9b25fbba.gif" width=250/>
</details>
<details>
<summary>GIF: Sending money to artists using Bitcoin</summary>
<img src="https://user-images.githubusercontent.com/4957928/103173848-e836dc80-485d-11eb-9863-660601a5ddf7.gif" width=250/>
</details>

### DAO - organisations in software
To make a "self-evolving" app we use the DAO concept. What is a DAO? Within the coming decades the future of jobs, employment and the nature of the firm will change profoundly. Automation, AI, and robots will replace many of today's jobs. A new type of company is a company without any employees, without any machines or physical infrastructure. A Decentralized Autonomous Organizations, DAO, only exists in software. It goes beyond smart contracts, it is a complete company inside software. DAO development is still in the experimental stage. Background reading. Very optimistic [view on DAO](https://hackernoon.com/the-state-of-the-daos-b7cba318460b), official [US review of DAO](https://www.sec.gov/litigation/investreport/34-81207.pdf) by Securities and Exchange Commission.

Within this master course you can create your very own autonomous organisation, the AI-DAO. Learn to engineer a decentralised autonomous organisation, use the existing tools, and understand the security risks. The aim is to alter the nature of the firm in the Internet age, [see the Nobel prize winning theory](https://en.wikipedia.org/wiki/The_Nature_of_the_Firm). Production cost become essentially cost-free. An organisation which exists purely in cyberspace. The AI-DAO is designed to be the first sustainable DAO. How can we empower leaderless organizations? How can it earn money from manipulating bits? 

### Scientific challenge: Self-evolving
A key step in an autonomous system is that it can evolve independently. This enables growth and evolution independently of any central organisation, sponsoring government, or tribe of volunteers.

You will collectively solve the problem of paying somebody to make new features in open systems which are fully decentralised. This goes further then paying somebody Bitcoins to create a new version. Decentralised technology is very robust to failures, manipulation, faults, and courtcases. For instance, The Internet itself is almost impossible to shutdown so is the "Tor darknet". With other teams you will address a key drawback of decentralised technology: difficult to update, nearly impossible to evolve, and lacks incentives to develop new features. 

### dApp ecosystem
"Distributed Applications" are a distributed way of running code. You will help develop an ecosystem of "global code". Code is running atop a blockchain and peer-to-peer (P2P) network that acts as a kind of operating system. This provides security, resilience, privacy, and novel features. This is related to smart contracts, but has no slow single virtual machine (all discussed in the online classes material). Background material, [read FBASE trustworthy code execution](https://repository.tudelft.nl/islandora/object/uuid%3Ad68197ec-50b9-4452-b9bf-e34a743f165f)
<details>
<summary>PNG: difference between cloud and decentralised Apps</summary>
<img src="https://user-images.githubusercontent.com/325224/107042537-2ced5600-67c2-11eb-8973-d524d5e46d5b.png" width=450/>
</details>

**Comment by synctext** [comment]
Please dive into multi-sig matters: https://github.com/Tribler/tribler/issues/5984

**Comment by StefanWeegink** [comment]
Hey

**Comment by CallumH2410** [comment]
Hello World!

**Comment by RFHuisman** [comment]
Hello World

**Comment by wubero** [comment]
Hello world

**Comment by StevenL98** [comment]
Hello World

**Comment by StevenL98** [comment]
You have to clone the repository as follows: `git clone --recursive <repo-url>`
If the cloning of the submodule of _kotlin-ipv8_ fails, click the repository link and clone it separately within the project that is successfully cloned.
The folder should look as follows: 
```
trustchain-superapp
│   README.md
│   file001    
│
└───kotlin-ipv8
│   │   file011
│   │   file012
│   
└───folder2
    │   file021
    │   file022
```

**Comment by StevenL98** [comment]
![image](https://user-images.githubusercontent.com/23526224/108991070-eb9ce780-7697-11eb-94bd-f5861534c10f.png)
Showing the sync button and the votes below each music album

**Comment by synctext** [comment]
Progress in Week 3.3 of this 10 week course:
- Lost 1 team member
- Not yet at stage that prior MultiSig work is running, understood and even fixed (its unstable sadly) https://github.com/Tribler/trustchain-superapp/blob/7a958aec39b89b8a7015d508ef440553a0403788/currencyii/README.md
- dived into existing code of MusicDAO. Got first first GUI improvement! :+1: 
- Upcoming sprint target: create a fixed Multi-Sig wallet group, broadcast votes other all others, show vote progress, and finalise transaction.
- Next sprints objective: expand this to a DAO with public keys and 'real' Bitcoin transaction in testnet

**Comment by StevenL98** [comment]
![show_votes_gif](https://user-images.githubusercontent.com/23526224/109036732-30da0d00-76ca-11eb-811f-445a04f35e28.gif)

**Comment by synctext** [comment]
Impressive GUI!!
Each bounty payout could be in simple MusicDAO style, like: "Pay 50mBTC from our common funds to artist named "L$D"?
please dive into: https://github.com/bitcoin/bitcoin/issues/21278#issuecomment-785742678

**Comment by StefanWeegink** [comment]
Hey! @RFHuisman and me have just finished implementing a working version of transactions. Currently still parts are hardcoded like public keys but as you can see we have already linked it to the UI, making it easier to test. The video bellow shows how our starting balance is 9.99 btc and then a transaction of 1btc is proposed. This transaction is approved by both users and is then executed and, thus, our balance has updated to 8.99 btc

https://user-images.githubusercontent.com/33690979/109689630-c91e3900-7b85-11eb-8a00-1bfea7e98839.mp4

**Comment by RFHuisman** [comment]
Hi! Taproot meets the requirements that you want once it is activated on the Bitcoin network. Details about the functionalities and confirming that it meets the requirements can be found [here](https://bitcoinmagazine.com/technical/taproot-coming-what-it-and-how-it-will-benefit-bitcoin) and [here](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2018-January/015614.html).

**Comment by synctext** [comment]
Taproot on Android: https://github.com/Tribler/tribler/issues/5996#issuecomment-787834532

**Comment by CallumH2410** [comment]
![Screenshot 2021-03-03 at 14 44 19](https://user-images.githubusercontent.com/15822631/109827690-41473600-7c3c-11eb-8ed7-96c757c53b18.png)

**Comment by CallumH2410** [comment]
![Uploading Screenshot 2021-03-03 at 16.20.13.png…]()

**Comment by CallumH2410** [comment]
![Screenshot 2021-03-03 at 16 20 13](https://user-images.githubusercontent.com/15822631/109827967-7fdcf080-7c3c-11eb-8f75-3f8d5b038354.png)

**Comment by synctext** [comment]
Great progress! Three directions coming together as course goal:
- Taproot Bitcoin for Android, https://github.com/bitcoin/bitcoin/pull/16110
- Luxury communism DAO, https://github.com/Tribler/trustchain-superapp/blob/7a958aec39b89b8a7015d508ef440553a0403788/currencyii/README.md
- Great GUI with bouty proposal, upvotes, downvotes, and undecided
- Plus bug fixes, code coverage, and testing Quality-of-Life improvements are highly approciated!

**Comment by StevenL98** [comment]
I can not start the Gradle daemon when my Mobile Hotspot of my laptop is running. At my parents, I have to because the WiFi is terrible there. It is a known bug mentioned [in this issue](https://github.com/gradle/gradle/issues/14094). 
If you have an idea on how to fix this, please let me know.

**Comment by xoriole** [comment]
@StevenL98 Reading the issue thread, maybe you could try downgrading to a working version.

**Comment by synctext** [comment]
- **Taproot works on Android emulator**, cmdline Bitcoin node is working, tests are passing
- ToDo: document magic recipe, multi-sig transaction (old approach), multi-sig (Taproot)
- ToDo: is there a testnet, see Twitter approach, testnet token?

**Comment by RFHuisman** [comment]
Here are some screenshots showing `bitcoind`, `bench_bitcoin` and `test_bitcoin`, compiled from the latest master branch, successfully running on an Android emulator. I will post a guide later this/next week describing the setup I used and the steps that I took to compile it.

**bitcoind**
![android-bitcoin-screenshot6](https://user-images.githubusercontent.com/25341744/110802979-03bb5c00-827f-11eb-8100-da1776f9013f.png)
![android-bitcoin-screenshot7](https://user-images.githubusercontent.com/25341744/110803038-12a20e80-827f-11eb-9e72-d483ee702ab4.png)

**bench_bitcoin**
![android-bitcoin-screenshot4](https://user-images.githubusercontent.com/25341744/110803094-22b9ee00-827f-11eb-8170-a25b0f2f0472.png)

**test_bitcoin**
![android-bitcoin-screenshot9](https://user-images.githubusercontent.com/25341744/110803132-29e0fc00-827f-11eb-84b2-9184b0bedb3c.png)

**Comment by thversfelt** [comment]
Hi, this is Thijs from Liquidity Pool group 1. We have also been looking into Taproot for our BTC part of the liquidity pool, and would really appreciate a guide for getting it to work on Android. Cheers!

**Comment by RFHuisman** [comment]
### WIP: Guide for compiling Bitcoin Core on Android

_Please contact me on my mail r.f.huisman@student.tudelft.nl if you have questions or are experiencing issues so I can adjust the guide._ 

**NOTE:**
I used Ubuntu 20.04 LTS when writing and testing this guide. Other Ubuntu versions or Linux distributions probably work as well, but verify this on your own.

1. Clone https://github.com/bitcoin/bitcoin locally.
2. Install the Android SDK version 28. More recent ones probably work as well, but I did not test that. You can use Android Studio to install the right SDK.
3. Download the NDK revision 20b here https://developer.android.com/ndk/downloads/older_releases. Other versions did not work for me, but you might be able to figure out how to use later versions as well.
4. Make sure to unzip and place the contents of the NDK in the SDK folder in the subfolder `ndk-bundle`.
2. Follow this guide to install required dependencies when compiling. For Ubuntu, use this one https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#linux-distribution-specific-instructions. Also make sure you have these dependencies installed when cross compiling https://github.com/bitcoin/bitcoin/tree/master/depends#for-linux-including-i386-arm-cross-compilation.
3. `cd` in your terminal to the `depends` folder. 
4. In this folder, run the following command: `sudo make HOST=x86_64-linux-android ANDROID_API_LEVEL=28 ANDROID_TOOLCHAIN_BIN=/home/rick/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin ANDROID_SDK=/home/rick/Android/Sdk/ ANDROID_NDK=/home/rick/Android/Sdk/ndk-bundle/`

**NOTE:**
- In the command above, HOST specifies the architecture that you are running Android on. For a physical device, this could be `aarch64-linux-android`, but I used an emulator, so we need to compile for the `x86_64-linux-android` architecture. Make sure to change this variable to the architecture you are running on your device.
- ANDROID_API_LEVEL is 28 in my case. Make sure this version is the same as the SDK you installed.
- Make sure the paths for `ANDROID_TOOLCHAIN_BIN`, `ANDROID_SDK` and `ANDROID_NDK` are correct on your computer.

5. Now wait to build depends (this takes some time). Make sure there are no errors before continuing.
6. `cd` back to the bitcoin core folder.
7. Run `sudo ./autogen.sh`
7. Run the following command: `sudo ./configure --prefix=/home/rick/Documents/bitcoin/depends/x86_64-linux-android/`. Make sure the folder name is the same as the architecture you chose to compile before and that the path is correct for your computer.
8.  Now run `sudo make -i LDFLAGS="-static-libstdc++"`. The `-i` flag ignores errors during compilation. There are certain files in the folder `test/fuzz` that give errors when compiling and I did not bother fixing them, since they are not needed to run or compile bitcoin core. In addition, `LDFLAGS` makes sure that you do not get a `CANNOT LINK EXECUTABLE "./bitcoind": library "libc++_shared.so" not found` error when trying to run the binary on your device.
9. Wait for all the binaries to be built. Run `file src/bitcoind` and make sure it matches the architecture you compiled for and is runnable on your device.

**NOTE:**
Next steps assume you are running an emulator, but the steps should be fairly similar when you are running on a device. Make sure to adjust the commands and the setup so that it works. Google is your friend here.

10. Download the correct emulator in Android Studio. Make sure that it has the correct architecture that you compiled Bitcoin Core with (for me x86-64), that it runs the right Android version (for me 28) and that the device doesn't contain the Play Store. This is needed since we need to root the device. You can check this by going to the AVD Manager in Android Studio and it should say Google APIs in the Target column instead of Google Play.
11. Start the emulator and open a new terminal. Wait until the emulator shows the home screen.
12. Run `adb devices` to make sure the device is up and running and connected to adb. You probably need to install adb if you haven't before.
13. Run `adb root` to root the device.
14. Run `adb push src/bitcoind /data/local/tmp` to upload the `bitcoind` binary to the device in `/data/local/tmp`.
15. Run `adb shell` and then run `cd /data/local/tmp`.
16. To quickly test if we can run `bitcoind`, run `mkdir .bitcoin` and then `./bitcoind -datadir=.bitcoin`. You can also upload other binaries that we compiled (like `test-bitcoin` or `bench_bitcoin`) and run them to test if it works.
17. If you did not encounter any errors during the steps above and can run the binaries, then congratulations, you successfully compiled Bitcoin Core for Android.

I hope this guide was helpful. If you are stuck at a certain step or encounter other issues, please reach out to me via my mail (see the beginning of the guide) and I will see if I can help you further and potentially update the guide.

**Comment by RFHuisman** [comment]
@thversfelt Please check out the guide above and let me know if it works for you.

**Comment by StefanWeegink** [comment]
> 
> ### WIP: Guide for compiling Bitcoin Core on Android
> 
> _Please contact me on my mail [r.f.huisman@student.tudelft.nl](mailto:r.f.huisman@student.tudelft.nl) if you have questions or are experiencing issues so I can adjust the guide._
> 
> **NOTE:**
> I used Ubuntu 20.04 LTS when writing and testing this guide. Other Ubuntu versions or Linux distributions probably work as well, but verify this on your own.
> 
>     1. Clone https://github.com/bitcoin/bitcoin locally.
> 
>     2. Install Android SDK version 28. More recent ones probably work as well, but I did not test that. You can use Android Studio to install the right SDK.
> 
>     3. Download the NDK revision 20b here https://developer.android.com/ndk/downloads/older_releases. Other versions did not work for me, but you might be able to figure out how to use later versions as well.
> 
>     4. Make sure to unzip and place the contents of the NDK in the SDK folder in the subfolder `ndk-bundle`.
> 
>     5. Follow this guide to install required dependencies when compiling. For Ubuntu, use this one https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#linux-distribution-specific-instructions. Also make sure you have these dependencies installed for cross compiling https://github.com/bitcoin/bitcoin/tree/master/depends#for-linux-including-i386-arm-cross-compilation.
> 
>     6. `cd` in your terminal to the `depends` folder.
> 
>     7. In this folder, run the following command: `sudo make HOST=x86_64-linux-android ANDROID_API_LEVEL=28 ANDROID_TOOLCHAIN_BIN=/home/rick/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin ANDROID_SDK=/home/rick/Android/Sdk/ ANDROID_NDK=/home/rick/Android/Sdk/ndk-bundle/`
> 
> 
> **NOTE:**
> 
>     * In the command above, HOST specifies the architecture that you are running Android on. For a physical device, this could be `aarch64-linux-android`, but I used an emulator, so we need to compile for the `x86_64-linux-android` architecture. Make sure to change this variable to the architecture you are running on your device.
> 
>     * ANDROID_API_LEVEL is 28 in my case. Make sure this version is the same as the SDK you installed.
> 
>     * Make sure the paths for `ANDROID_TOOLCHAIN_BIN`, `ANDROID_SDK` and `ANDROID_NDK` are correct on your computer.
> 
> 
>     1. Now wait to build depends (this takes some time). Make sure there are no errors before continuing.
> 
>     2. `cd` back to the bitcoin core folder.
> 
>     3. Run `sudo ./autogen.sh`
> 
>     4. Run the following command: `sudo ./configure --prefix=/home/rick/Documents/bitcoin/depends/x86_64-linux-android/`. Make sure the folder name is the same as the architecture you chose to compile before and that the path is correct for your computer.
> 
>     5. Now run `sudo make -i LDFLAGS="-static-libstdc++"`. The `-i` flag ignores errors during compilation. There are certain files in the folder `test/fuzz` that give errors when compiling and I did not bother fixing them, since they are not needed to run or compile bitcoin core. In addition, `LDFLAGS` makes sure that you do not get a `CANNOT LINK EXECUTABLE "./bitcoind": library "libc++_shared.so" not found` error when trying to run the binary on your device.
> 
>     6. Wait for all the binaries to be built. Run `file src/bitcoind` and make sure it matches the architecture you compiled for and is runnable on your device.
> 
> 
> **NOTE:**
> Next steps assume you are running an emulator, but the steps should be fairly similar when you are running on a physical device. Make sure to adjust the commands and the setup so that it works. Google is your friend here.
> 
>     1. Download the correct emulator in Android Studio. Make sure that it has the correct architecture that you compiled Bitcoin Core with (for me x86-64), that it runs the right Android version (for me 28) and that the device doesn't contain the Play Store. This is needed since we need to root the device. You can check this by going to the AVD Manager in Android Studio and it should say Google APIs in the Target column instead of Google Play.
> 
>     2. Start the emulator and open a new terminal. Wait until the emulator shows the home screen.
> 
>     3. Run `adb devices` to make sure the device is up and running and connected to adb. You probably need to install adb if you haven't before.
> 
>     4. Run `adb root` to root the device.
> 
>     5. Run `adb push src/bitcoind /data/local/tmp` to upload the `bitcoind` binary to the device in `/data/local/tmp`.
> 
>     6. Run `adb shell` and then run `cd /data/local/tmp`.
> 
>     7. To quickly test if we can run `bitcoind`, run `mkdir .bitcoin` and then `./bitcoind -datadir=.bitcoin`. You can also upload other binaries that we compiled (like `test-bitcoin` or `bench_bitcoin`) and run them to test if it works.
> 
>     8. If you did not encounter any errors during the steps above and can run the binaries, then congratulations, you successfully compiled Bitcoin Core for Android.
> 
> 
> I hope this guide was helpful. If you are stuck at a certain step or encounter other issues, please reach out to me via my mail (see the beginning of the guide) and I will see if I can help you further and potentially update the guide.

I will test this tomorrow on a ubuntu server and run the emulator on windows (@RFHuisman ran it on ubuntu)

**Comment by thversfelt** [comment]
> 
> 
> @thversfelt Please check out the guide above and let me know if it works for you.

Thank you for the comprehensive guide, we'll let you know.

**Comment by StevenL98** [comment]
- Within a voting, you now have the possibility to send a vote against the proposal
- Every proposal now has _the same_ unique id if it is proposed to all the participants of a DAO (this isn't supposed to be right?)
- Transformed a signature to the bitcoin public key, a user can now see who voted already 
- Added a voted stamp when a user has already voted.
- Added a red border when a proposal can't be met at the current state.
- The Pull Request for the bugs, should be online on the Tribler branch on 18/03.
<p float="left">
<img src="https://user-images.githubusercontent.com/23526224/111478102-0c54dc00-8730-11eb-9fbb-3cd65e2ee7ad.gif" width="200"/>
<img src="https://user-images.githubusercontent.com/23526224/111478323-42925b80-8730-11eb-9bb9-d90b703385a3.jpeg" width="200"/>
<img src="https://user-images.githubusercontent.com/23526224/111479002-e2e88000-8730-11eb-9246-dc487e5268b4.jpeg" width="200"/>
</p>

**Comment by RFHuisman** [comment]
https://en.bitcoin.it/wiki/Signet

**Comment by synctext** [comment]
- Solid progress again, impressive work!
- ToDo: Create a testnet/[signet](https://en.bitcoin.it/wiki/Signet) and facet for free 10 BTC for each of our users?
- _Repeating_ issues from above
  - [X] document magic recipe, multi-sig transaction (old approach),
  - Missing wallet support in Taproot Bitcoin code!   :fire: 
  - [ ] multi-sig using Taproot magic :mage_man: 
  - [ ] DAO Bug fixes. 20 minutes delay for discovery of new DAO. UPDATE: peer discovery and discovery of IPv4 addresses seems to have bug(s). @CallumH2410 to main Superapp. Understand gossip, crawl request, and spam trade-offs. Write tests for this?!? Show peers (also their IPv4?) in DAO? 
  - [ ] DAO demo, post fixed .APK on this issue, new screens on voting.

**Comment by StevenL98** [comment]
Make the connection with the RegTest server, set up by Rick and Stefan and make a button that adds bitcoins to your wallet 
Also, add the fee and the balance to DOAs
Added a check that checks if there is sufficient balance on the DAO before sending it
Show the current network in the bitcoin fragment and in the chain downloading
<p float="left">
<img src="https://user-images.githubusercontent.com/23526224/112182315-7a504600-8bfd-11eb-9392-ab8adc75b062.png" height="400"/>
<img src="https://user-images.githubusercontent.com/23526224/112612886-bfec5900-8e1f-11eb-94d4-cfa2a2eb9a64.png" height="400"/>
<img src="https://user-images.githubusercontent.com/23526224/112873182-96eaf300-90c1-11eb-9c1f-372d25b78f99.png" height="400"/>
<img src="https://user-images.githubusercontent.com/23526224/112873236-a79b6900-90c1-11eb-851c-02bfcc774baa.png" height="400"/>
<img src="https://user-images.githubusercontent.com/23526224/112960158-7021d080-9144-11eb-833a-0c748051a920.png" height="400"/>
</p>

**Comment by synctext** [comment]
ToDo for final frading: PR accepted, Readme [1](https://github.com/Tribler/trustchain-superapp/blob/master/README.md#luxury-communism) & [2](https://github.com/Tribler/trustchain-superapp/blob/master/currencyii/README.md), and running .APK

**Comment by synctext** [comment]
Extension beyond Q3 for beating Taproot into submission. Its proven hard to get fully working :hammer: 
Invite for 2nd edition of our workshop in Canada on 6-10 December 2021 with a scientific write-up of your DAO: https://middleware-conf.github.io/2021// https://dicg2020.github.io/

**Comment by synctext** [comment]
For readme, show the system architecture in 1 picture: taproot.tudelft server, regtest, BicoinJ library, rpc calls, regtest server, trustchain, voting system, negative vote spreading, etc.

**Comment by StevenL98** [comment]
We send the .apk file via mail, it can also be downloaded via [this link](https://we.tl/t-DsH1y8MXCZ). We will finish the readme and pull request before tomorrow.

**Comment by RFHuisman** [comment]
PR is ready: https://github.com/Tribler/trustchain-superapp/pull/70.
It contains all of our code and documentation now

**Comment by StevenL98** [comment]
The final .apk file can be downloaded [here!](https://we.tl/t-gab5lfveGK)
