### ISSUE TITLE
the first AI dAPP - self-evolving AI-DAO

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#5987]
### Master course on Blockchain Engineering project 2021

**TEAM1: the first AI-dApp**
Create a dApp with federated machine learning to understand music taste of user and recommend more. Exchange training vectors on the blockchain overlay. Never share with others what Bittorrent music swarms you like. By only sharing training data you can discover new music and still preserve privacy. [Prior work](https://github.com/Tribler/distributed-ai-kernel) and [this](https://github.com/Tribler/tribler/issues/5221).

### General Description - self-evolving AI-DAO (https://github.com/Tribler/tribler/issues/5944)
Student from Delft have created a blockchain-based alternative to Spotify. Completely decentralised. Uses Bittorrent for streaming, Bitcoin for payments to artists, Trustchain with IPv8 for music discovery and IPv8 for app-to-app connectivity. With multiple teams the aim is to take this code to the next level: self-evolution.

A total of 4 students teams (4-5 students in each team) will work together on a cutting-edge scientific problem: how to create a software system which can be expanded in real-time and increasingly become more '_intelligent_'. Build upon the existing open source app by TUDelft on the Android Play store using blockchain technology: the [Superapp](https://github.com/Tribler/trustchain-superapp/). You will help transform essential parts of the music industry and replace them with open source software. Current code:

<details>
<summary>GIF: Browsing and streaming music with Bittorrent </summary>
<img src="https://user-images.githubusercontent.com/4957928/103173843-e5d48280-485d-11eb-907a-e20c9b25fbba.gif" width=250/>
</details>
<details>
<summary>GIF: Sending money to artists using Bitcoin</summary>
<img src="https://user-images.githubusercontent.com/4957928/103173848-e836dc80-485d-11eb-9863-660601a5ddf7.gif" width=250/>
</details>

### DAO - organisations in software
To make a "self-evolving" app we use the DAO concept. What is a DAO? Within the coming decades the future of jobs, employment and the nature of the firm will change profoundly. Automation, AI, and robots will replace many of today's jobs. A new type of company is a company without any employees, without any machines or physical infrastructure. A Decentralized Autonomous Organizations, DAO, only exists in software. It goes beyond smart contracts, it is a complete company inside software. DAO development is still in the experimental stage. Background reading. Very optimistic [view on DAO](https://hackernoon.com/the-state-of-the-daos-b7cba318460b), official [US review of DAO](https://www.sec.gov/litigation/investreport/34-81207.pdf) by Securities and Exchange Commission.

Within this master course you can create your very own autonomous organisation, the AI-DAO. Learn to engineer a decentralised autonomous organisation, use the existing tools, and understand the security risks. The aim is to alter the nature of the firm in the Internet age, [see the Nobel prize winning theory](https://en.wikipedia.org/wiki/The_Nature_of_the_Firm). Production cost become essentially cost-free. An organisation which exists purely in cyberspace. The AI-DAO is designed to be the first sustainable DAO. How can we empower leaderless organizations? How can it earn money from manipulating bits? 

### Scientific challenge: Self-evolving
A key step in an autonomous system is that it can evolve independently. This enables growth and evolution independently of any central organisation, sponsoring government, or tribe of volunteers.

You will collectively solve the problem of paying somebody to make new features in open systems which are fully decentralised. This goes further then paying somebody Bitcoins to create a new version. Decentralised technology is very robust to failures, manipulation, faults, and courtcases. For instance, The Internet itself is almost impossible to shutdown so is the "Tor darknet". With other teams you will address a key drawback of decentralised technology: difficult to update, nearly impossible to evolve, and lacks incentives to develop new features. 

### dApp ecosystem
"Distributed Applications" are a distributed way of running code. You will help develop an ecosystem of "global code". Code is running atop a blockchain and peer-to-peer (P2P) network that acts as a kind of operating system. This provides security, resilience, privacy, and novel features. This is related to smart contracts, but has no slow single virtual machine (all discussed in the online classes material). Background material, [read FBASE trustworthy code execution](https://repository.tudelft.nl/islandora/object/uuid%3Ad68197ec-50b9-4452-b9bf-e34a743f165f)
<details>
<summary>PNG: difference between cloud and decentralised Apps</summary>
<img src="https://user-images.githubusercontent.com/325224/107042537-2ced5600-67c2-11eb-8973-d524d5e46d5b.png" width=450/>
</details>

**Comment by synctext** [comment]
- Compile Superapp from sources
- understand the machine learning parts
- What is a distributed App? compile the FBae code

**Comment by JCBrouwer** [comment]
Hello world

**Comment by nata1y** [comment]
Hello world

**Comment by skullyhoofd** [comment]
Hello world, Ricardo here!

**Comment by ehildebrand** [comment]
hello world, this is esmee, over

**Comment by nata1y** [comment]
Hi,
Is it possible to provide us with a training data file (train_triplets.txt / unique_tracks.txt from distributed-ai-kernel prject) or with a general input format?
Thanks in advance!

**Comment by ehildebrand** [comment]
- What type of information can we find about the user?
- How do we alter the search system for recommendations?

**Comment by JCBrouwer** [comment]
Tasks
1) getting music info from the app
2) finding a dataset
3) feature vectors from music and online svm
4) gossiping models
5) predictions with model in interface
6) like button in interface

**Comment by JCBrouwer** [comment]
## PySyft evaluation

https://github.com/JCBrouwer/fedrecsys

Pros:
- PySyft is super plug and play, it was pretty simple to get a basic recommender and MNIST classifier up & running
- All the training communication stuff is handled for us, we just need to spawn a server on our phone and tell other phones that they should join our training session. This makes it pretty amenable to the gossip training paper Johan linked us
- the maintainers are pretty responsive on slack

Cons:
- Python based. Even though the Syft worker nodes can run in Kotlin, it requires running a coordinator server (PyGrid) which is only available in python. We could still probably wrap this up and call it from Kotlin using e.g. https://github.com/dickensas/kotlin-gradle-templates/tree/master/embed-python but it's less than ideal. Or maybe implement this part ourselves using ipv8 stuff
- It uses PyTorch which is very deep learning focused which we probably don't have the data for
- Syft is undergoing a full rewrite at the moment, so we'd be building on version 0.2.x which is no longer supported

**Comment by nata1y** [comment]
A brief overview of current findings:
We are going to create a separate Android library dedicated to federated ML. We are going to use Online Learning interface for training models in place from smile Kotlin library (https://haifengl.github.io/quickstart.html). We are going to use the supervised model (SVM) since it is implemented in Pegas model from the paper. Not clear yet on concrete features encoding/engineering technique, depends on the type of data we can get from user.

**Comment by JCBrouwer** [comment]
## Some literature

- [Decentralized machine learning using compressed push-pull averaging](http://publicatio.bibl.u-szeged.hu/20177/1/main.pdf)
    -  From the same authors as the paper the distributed-ai-kernel was based on
    - Introduces higher communication-efficient gossiping algorithm (compressed push-pull)
    - Finetunes final layers of pre-trained deep networks for better performance despite training via gossip
- Powergossip [[Code](https://github.com/epfml/powergossip)] [[Paper](https://arxiv.org/abs/2008.01425)]
    - Introduces an algorithm that directly compresses the model differences between neighboring workers using low-rank linear compressors applied on model differences.
    - Builds on + implements ChocoSGD / ChocoGossip [[Summary](https://www.notion.so/Choco-SGD-1b9f9ce78c07457d8859746104639d03)] [[Paper](http://proceedings.mlr.press/v97/koloskova19a/koloskova19a.pdf)]
-  [A Peer-to-Peer Recommender System with Privacy Constraints](ftp://www.kom.tu-darmstadt.de/papers/PKFS09_567.pdf)
    - Builds a federated social network and introduces a privacy preserving item-based collaborative filtering algorithm that uses 'user similarity' in the social network for recommendations.
    - Builds privacy on top of [Distributed Collaborative Filtering for Peer-to-Peer File-Sharing Systems](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.102.338&rep=rep1&type=pdf)
- [A peer-to-peer recommender system for self-emerging user communities based on gossip overlays](https://www.sciencedirect.com/science/article/pii/S0022000012001195)
    - Similar to above, tries to create recommendations by first associating similar users into groups
    - Not privacy-focused, but perhaps extensible to be
- [Radiommender: P2P On-line Radiowith a Distributed Recommender System](https://files.ifi.uzh.ch/CSG/staff/hecht/publications/p2p12demo.pdf)
    - Almost identical task
    - not privacy-focused 
- [Personalized and Private Peer-to-Peer Machine Learning](https://arxiv.org/abs/1705.08435)
- [P2P-based PVR Recommendation using Friends,Taste Buddies and Superpeers](https://grouplens.org/beyond2005/full/pouwelse.pdf)

Many approaches use a centralized parameter server to keep global updates. It seems plausible that a true central server could be replaced by a parameter server running locally on each device. These parameter servers could then share their weight updates via gossiping.
- [Meta Matrix Factorization for Federated Rating Predictions](https://staff.fnwi.uva.nl/m.derijke/wp-content/papercite-data/pdf/lin-2020-meta.pdf)
- [Federated Collaborative Filtering for Privacy-Preserving Personalized Recommendation System](https://arxiv.org/abs/1901.09888)
- [A Novel Privacy-Preserved Recommender System Framework based on Federated Learning](https://arxiv.org/abs/2011.05614)
- [A Simple and Efficient Federated Recommender System](https://dl.acm.org/doi/10.1145/3365109.3368788)
- [Robust Federated Recommendation System](https://arxiv.org/abs/2006.08259)

**Comment by synctext** [comment]
Possible gameplan for this entire project:
- machine learning; please use collaborative filtering
- playlist history (played magnet link since install; create simple database table)
- IPv8 gossip of playlist history for debugging
- User interface

**Comment by drew2a** [comment]
Two suggestions from @drew2a side

### Use a separated branch

As we are "production software" now, I suggest performing all the development of the Superapp in a separate branch to prevent interfering with a published code from the `master` branch.

To do this, we need to create a branch in https://github.com/Tribler/trustchain-superapp (e.g. `feature/music-dao-recommendations`). Then, all of our commits will go to this branch. At the end of the project, this branch will be merged to `master`.

If you are not familiar with `git`, take a look at https://www.gitkraken.com/

### Split a network until the project will be done

It will be tough to debug and test a changed application, within the wild network. 
There are multiple scenarios of how we can make life easier for ourselves.

I propose the following approach:
1. Deploy a dedicated bootstrap server (or a few). I can help with that.
2. Change (or override) a list of bootstrap servers (see an example [here](https://github.com/Tribler/kotlin-ipv8/commit/32a7286e20c254bd747be47c063fbcbdfe93d532)) 

### PS

>@drew2a we can seed this content for you: 917 GiB and 343 days of Creative Commons-licensed audio from 106,574 tracks from 16,341 artists and 14,854 albums, arranged in a hierarchical taxonomy of 161 genres and expand it with a crawl of 55,000 full audio tracks of Jamendo

Wow :)

**Comment by JCBrouwer** [comment]
> ### Use a separated branch
> 
> As we are "production software" now, I suggest performing all the development of the Superapp in a separate branch to prevent interfering with a published code from the `master` branch.

Yes we're developing in branches on [this fork](https://github.com/JCBrouwer/trustchain-superapp/tree/dai-kotlinswift-experiments-nataly). We can merge branches from there directly to the upstream master via pull request.

> I propose the following approach:
> 
>     1. Deploy a dedicated bootstrap server (or a few). I can help with that.
> 
>     2. Change (or override) a list of bootstrap servers (see an example [here](https://github.com/Tribler/kotlin-ipv8/commit/32a7286e20c254bd747be47c063fbcbdfe93d532))

Ok sweet, that sounds good.

> > @drew2a we can seed this content for you: 917 GiB and 343 days of Creative Commons-licensed audio from 106,574 tracks from 16,341 artists and 14,854 albums, arranged in a hierarchical taxonomy of 161 genres and expand it with a crawl of 55,000 full audio tracks of Jamendo

Who sent you this? That definitely sounds like it can help our issues with amount of data!

**Comment by drew2a** [comment]
> Who sent you this? That definitely sounds like it can help our issues with amount of data!

Johan [sent me this](https://github.com/Tribler/tribler/issues/5987#issuecomment-784102857)

**Comment by JCBrouwer** [comment]
> > Who sent you this? That definitely sounds like it can help our issues with amount of data!
> 
> Johan [sent me this](https://github.com/Tribler/tribler/issues/5987#issuecomment-784102857)

Ahh I read over it, nice!

**Comment by ehildebrand** [comment]
Andrei told me you can find the data storage [here](https://github.com/JCBrouwer/trustchain-superapp/blob/master/musicdao/src/main/java/com/example/musicdao/ipv8/MusicCommunity.kt#L27)

**Comment by nata1y** [comment]
Main updates: 
We are in the process of developing a federated ml service for music dao. Currently facing some issues upon trying to integrate it with ipv8 and possibly would like to discuss it during the meeting.
We have changed ml model such that we are not using a feature-based approach anymore. However, due to the limitations of a size of a model that we can send over the net, we likely do not want to store all possible song-song combinations in it (with the corresponding similarity value/weight). Thus, the idea is to choose a predetermined set of songs (most popular? just randomly chosen ones for now?). Is it an acceptable approach?

**Comment by synctext** [comment]
Discussed issues:
- clean ORM for Android, remove loose SQL in Debug, MusicDAO and Peerchat
- Skeleton Machine learning model in superapp and ?  initial exchange of serialised vectors

**Comment by nata1y** [comment]
Current progress:

- Refactoring of ml models to operate with a sparse array instead of normal array

- Tried to migrate trustchain to kotlin 1.4.30, still experiencing some bugs.

- Start with db integration

Questions: it seems that a song that has been listened to gets downloaded into some local directory. We did not seem to find a proper location of this directory?

**Comment by nata1y** [comment]
Here is the link to the repo:
https://github.com/JCBrouwer/trustchain-superapp

main updates are on dev branch

**Comment by synctext** [comment]
Discussion of progress, 1 team member present.
Please focus on getting code to compile and run as :1st_place_medal: priority. Then make stuff fancy. No need to repair or improve the superapp. Smile library is huge with ML,NLP, etc.) please ignore and do a low-performance, simple approach from scratch.

**Comment by nata1y** [comment]
Updates 15.03:
- fully migrated superapp to kotlin 1.4.30
- able to create/restore local recommendation model and display music suggestions based on it
- added recommendation fragment to music DAO (see picture below)

However:
- we are still not sure that gossiping works, we need to test it properly
- we are still experiencing troubles with retrieving local mp3 data and, therefore, current models give almost random recommendations
- trustchain transactions have info about artist, publisher, year, and song. Are we able to retrieve any other type of data? Would it be ok to download "candidate recommendations" somewhere locally so that we are able to access mp3 data as genre or bpm to achieve better predictions?

x-special/nautilus-clipboard
copy
file:///home/natali/Pictures/Screenshot%20from%202021-03-13%2022-52-31.png

**Comment by nata1y** [comment]
Updates 15.03:

fully migrated superapp to kotlin 1.4.30
able to create/restore local recommendation model and display music suggestions based on it
added recommendation fragment to music DAO (see picture below)
However:

we are still not sure that gossiping works, we need to test it properly
we are still experiencing troubles with retrieving local mp3 data and, therefore, current models give almost random recommendations
trustchain transactions have info about artist, publisher, year, and song. Are we able to retrieve any other type of data? Would it be ok to download "candidate recommendations" somewhere locally so that we are able to access mp3 data as genre or bpm to achieve better predictions?
![Screenshot from 2021-03-13 22-52-31](https://user-images.githubusercontent.com/18513617/111081795-5b6af900-8505-11eb-99aa-2c2b386c03a4.png)

**Comment by synctext** [comment]
- Making great progress! Real recommendation screenshot.
- This week sprint: making minimal viable product of recommender that is superior to random
- integration of everything is not easy, especially gossip.
- Focus on feature, something like, creation year. For instance, 2 profiles of old songs; 2 profiles of fresh songs. Recommend based on 1 song that is playing now (either old or fresh).

**Comment by nata1y** [comment]
Main updates:
- we are able to gossip models between our peers when running app in android studio simultaneously
- we came across [this paper](https://dmle.iais.fraunhofer.de/papers/hegedus2019decentralized.pdf) that describes gossiping algorithm for collaborative filtering approach and implemented Matrix factorization model
- in the case of feature-based model, we are able to retrieve song data, however, ioften it is very limited or completely blank. moreover, it does not seem to include (many) useful features. therefore, the only information we use that is already available is 'genre' and 'year'. on top of that, we have integrated [essentia library](https://essentia.upf.edu/) into superapp and now we are able to extract around 225 features for a song (some might be empty). 
- we added model tests
- we added 'feature gossiping' for songs user do not have locally but we haven't tested it properly yet. 

We are planning to concentrate on testing everything with 2+ peers in the upcoming weeks. We would also like to add bayesian learning from [here](https://arxiv.org/pdf/1205.2618.pdf) to achieve more accurate personal ranking learning.

**Comment by synctext** [comment]
- Again, solid progress. 
- Please focus on wrapping up and Superapp polish; "feature freeze"

**Comment by drew2a** [comment]
@nata1y @JCBrouwer 
This is an example of working kotlin-ipv8 outside of android:
https://github.com/Tribler/trustchain-superapp/blob/master/musicdao-datafeeder/src/main/java/com/example/musicdao_datafeeder/DataFeeder.kt

**Comment by drew2a** [comment]
A minimum program might look like this:

```kotlin
private fun musicCommunity(): OverlayConfiguration<MusicCommunity> {
    val driver: SqlDriver = JdbcSqliteDriver(JdbcSqliteDriver.IN_MEMORY)
    Database.Schema.create(driver)
    return OverlayConfiguration(
        factory = MusicCommunity.Factory(
            settings = TrustChainSettings(),
            database = TrustChainSQLiteStore(Database(driver))
        ),
        walkers = listOf(RandomWalk.Factory())
    )
}

private fun discoveryCommunity() = OverlayConfiguration(
    factory = DiscoveryCommunity.Factory(),
    walkers = listOf(
        RandomWalk.Factory(timeout = 3.0, peers = 20),
        RandomChurn.Factory(),
        PeriodicSimilarity.Factory()
    )
)

fun ipv8() = IPv8(
    endpoint = EndpointAggregator(
        udpEndpoint = UdpEndpoint(
            port = 8090,
            ip = InetAddress.getByName("0.0.0.0")
        ), bluetoothEndpoint = null
    ),
    configuration = IPv8Configuration(
        overlays = listOf(
            discoveryCommunity(),
            musicCommunity()
        ), walkerInterval = 1.0
    ),
    myPeer = Peer(JavaCryptoProvider.generateKey())
)


fun main(args: Array<String>) {
    val ipv8 = ipv8()
    ipv8.start()
}
```

**Comment by JCBrouwer** [comment]
### Updates (Penultimate Edition?)
- Added a little randomness to recommendations
- Added a lot of comments and cleaned up code (imports, format, naming, logging)
- Thorough testing of matrix factorization model
    - Validation tests with 10 users in 4 preference groups
        - Each group has 2-3 users that are missing one song from their song group
    - Round robin gossiping converges to the same song features across the network
    - Predictions are correct, suggesting the last song of the group in more than 90% of cases
- Still having issues with the feature based model
    -  Essentia extractor very rarely throws SIGABRTs or segfaults
        - Probably related to corrupted/half-downloaded mp3 files (not easy to replicate on a new install)
        - Cannot catch these errors gracefully because they happen in native code (causes crashes)
    - Possible solutions
        1. More validation of MP3 files before feeding to Essentia
        2. Remove essentia and try to predict only based on block metadata (performance will probably be terrible)
        3. Try to find a different music extractor which is more stable (e.g. [JAudio](http://jaudio.sourceforge.net/jaudio10/embedding.html))
        4. Try [embedding](https://github.com/dickensas/kotlin-gradle-templates/tree/master/embed-python) python essentia API instead (perhaps this happens to catch these errors more robustly)
        5. Remove feature based model altogether :(

**Comment by synctext** [comment]
- Great to see that successful completion is in sight
- Ambition task in this master course and looking very promising
- Focus is on getting everything ready. Then documentation and last-week polish.
- 1 week left: team is confident the'll make the self-imposed deadline

**Comment by JCBrouwer** [comment]
### PR 1
- [ ] validate prediction performance of feature-based model
- [ ] test apk on real phones
- [ ] fix debug application in superapp
- [ ] minimize c++ code for essentia (or move to submodule)
- [ ] squash commits to make main PR easier

### PR 2
- [ ] add comments to matrix factorization code
- [ ] more high-level description in main README
- [ ] describe architecture of our code
- [ ] create diagram of federated gossip learning for recommendations
- [ ] create GIF of recommendations

**Comment by nata1y** [comment]
example gif and diagram are in README of the PR as well

**Comment by synctext** [comment]
Raw .APK: https://github.com/JCBrouwer/trustchain-superapp/raw/federated-music-recommendation/gossipML/app-debug-gossipML.apk

**Comment by JCBrouwer** [comment]
Federated music recommendation has been merged :tada:

**Comment by StevenL98** [comment]
I can't run the master anymore, 
Do you know any tricks to make it build again?
I get the following error:
`Build command failed.
Error while executing process C:\Users\Steven\AppData\Local\Android\Sdk\cmake\3.10.2.4988404\bin\ninja.exe with arguments {-C trustchain-superapp\gossipML\.cxx\cmake\debug\x86 superappessentia}
ninja: Entering directory trustchain-superapp\gossipML\.cxx\cmake\debug\x86
ninja: error: 'trustchain-superapp/gossipML/superapp-essentia/libs/x86/libessentia.a', needed by 'trustchain-superapp/gossipML/build/intermediates/cmake/debug/obj/x86/libsuperappessentia.so', missing and no known rule to make it
`
