### ISSUE TITLE
Missing dependencies in .deb on Debian

### ISSUE THREAD

**Issue by ghost** [Tribler/tribler#5998]
##### Tribler version/branch+revision: #####
7.8.0 , with:
wget https://github.com/Tribler/tribler/releases/download/v7.8.0/tribler_7.8.0_all.deb
apt install ./tribler_7.8.0_all.deb

##### Operating system and version: #####
Debian: Linux debian 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

##### Steps to reproduce the behavior: #####
Install tribler, try to start it

##### Expected behavior: #####
It starts

##### Actual behavior: #####
It does not start

##### Relevant log file output: #####
Fatal Python error: Aborted

Current thread 0x00007fa9c016d740 (most recent call first):
  File "tribler_gui/single_application.py", line 28 in __init__
  File "tribler_gui/tribler_app.py", line 25 in __init__
  File "run_tribler.py", line 164 in <module>

---
What I think is the case is that a dependency was missed/forgotten/accidentally removed.
If I manually install libqt5gui5 (apt install libqt5gui5), things work find afterwards.

I guess whoever has been testing this already had qt5 installed, or it's always available on Ubuntu, or someone never runs apt autoremove.

Probably libqt5gui5 just needs to be added to https://github.com/Tribler/tribler/blob/main/build/debian/tribler/DEBIAN/control
But I'm no debian package expert, don't quote me on it :)

**Comment by xoriole** [comment]
@cranphin Thank you for reporting. It is interesting to know there is a qt dependency issue in Debian. Actually, Qt5 should be bundled into the installer itself and does not require adding a dependency declaration in Debian/control file. Our deployment tests on Ubuntu 20.04 were running fine so we did not catch this. We'll investigate more on this and publish a fix if necessary.

**Comment by cranphin** [comment]
Nice, let me know if you need any more details :)
If I remember correctly, it's a Debian server build  with the xfce desktop dependency added, so pretty much vanilla debian with 'Xfce desktop environment'.
Again, there's a good chance it's different from most systems in that qt5 wasn't pulled in, most systems would have something qt5 based installed :)

**Comment by drew2a** [comment]
Update: checked on a fresh Debian 10. Works fine.

```bash
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -r
4.19.0-10-amd64

```

**Comment by cranphin** [comment]
What does apt list --installed give? :)

**Comment by cranphin** [comment]
Or apt list --installed | grep qt5 if you want something more manageable :)

**Comment by drew2a** [comment]
@cranphin `apt list --installed | grep qt5` gives an empty list :)

**Comment by cranphin** [comment]
Ha, fair, them I'm at a loss where the difference lies :)

**Comment by cranphin** [comment]
I should do a remove on the package I installed to add the dependencies, then autoremove, then see what it actually removes, and then see if tribler stops working again, maybe it's a dependency of qt itself or so :)

**Comment by cranphin** [comment]
Ok, checked all the dependencies, you're right that the qt5 ones aren't needed.
Instead the following dependencies of qt5 itself were all needed, remove any from this list stops Tribler from starting:
- libxcb-render-util0
- libxcb-keysyms1
- libxcb-randr0
- libxcb-image0
- libxcb-xkb1
- libxkbcommon-x11-0
- libxcb-icccm4

**Comment by void-spark** [comment]
For anyone who found this to resolve issues with 7.10.0, this might help you (it's an ugly hack, but it works):
cd /usr/lib/x86_64-linux-gnu/
ln -s libxcb-util.so.0.0.0 libxcb-util.so.1

**Comment by xoriole** [comment]
The latest version 7.10 works on Debian, closing this issue.
Similar issue: https://github.com/Tribler/tribler/issues/6216
