### ISSUE TITLE
Code signing Windows build

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#6000]
To make sure that Tribler is recognized to be from a verified publisher, we need to sign the installer. One option under consideration is using Certum code signing for open source projects. This ticket is to explore this option.

https://www.certum.eu/en/code-signing-certificates/

Reference:
- https://github.com/sqlitebrowser/sqlitebrowser/issues/1229

**Comment by synctext** [comment]
just to document our journey somewhat.
From 2012-2016 ish we used DigiCert. ```Digicert certificate for Build signing```.
