### ISSUE TITLE
A Mobile and Generic Asset Exchange using Liquidity Pooling [intergroup communication]

### ISSUE THREAD

**Issue by daandeheij** [Tribler/tribler#6001]
We (group 1) suggest to use this issue in order to facilitate communication and coordination between the two groups. 

The separate issues for notes for each group are: #5988 and #5996.

@devos50 I do not seem to be able to assign the correct labels and assignees/participants to this issue. If you could do so, it would be appreciated :)

**Comment by thversfelt** [comment]
Group 2 e-mailed about their intent to look into multi-sig wallets and implementing basic transactions in the superapp.

**Comment by daandeheij** [comment]
The past few days, we have been thinking about how each group can develop a distinct app/project. Some possibilities that we consider:

- Developing two different **implementations** for the liquidity pool: e.g. one group uses multi-sig, the other group uses a token-based solution.
- Develop a solution for two **different asset pairs**. E.g.: one group does BTC/ETH, another group does ETH/DOGE.

We are curious to hear about your ideas and thoughts! :D

**Comment by synctext** [comment]
Proposal for next week sprint:
- One team does Multi-Sig wallet for 1 week
- Other team does GUI interface, first implemention, 1 week

**Comment by kchong97** [comment]
@Group1 we are working on a basic GUI interface, for now the idea is to have a page simply for viewing your balance for all the wallets (within this project mainly bitcoins and euro tokens) and another page for exchanging your assets for another. For bitcoin we have used bitcoinj to create a wallet for the user. We are also looking into doing the same for euro tokens.

We are working in [this fork](https://github.com/chrislemaire/trustchain-superapp/pull/1#event-4351679269)

**Comment by thversfelt** [comment]
Possible UI idea:

Start screen:
![image](https://user-images.githubusercontent.com/40113382/109124985-d6819080-774b-11eb-93ed-6b78135675da.png)

Liquidity pool screen for traders/liquidity providers
![image](https://user-images.githubusercontent.com/40113382/109125048-e600d980-774b-11eb-9e4e-df9a0625527d.png)

**Comment by EmielBoss** [comment]
@Group2 Sounds good! Are you guys available tomorrow (Friday) at 10:00 to meet up and synchronize?

**Comment by kchong97** [comment]
> @Group2 Sounds good! Are you guys available tomorrow (Friday) at 10:00 to meet up and synchronize?

Yes! I will send a mail with a link to a Zoom meeting for tomorrow.

**Comment by chrislemaire** [comment]
@kchong97 and @EmielBoss, notice that the group1/2 mentions are notifying random users, of which one seems to be unused and the second seems to be owned by some Chinese users. They both might not appreciate being tagged randomly in this issue :P

**Comment by vstam1** [comment]
We have a first sketch of the personal wallet page and the liquidity pool page: 

![WhatsApp Image 2021-02-26 at 3 02 10 PM](https://user-images.githubusercontent.com/10252263/109472084-f7aaef80-7a71-11eb-9a77-76aeb887ba6e.jpeg)


![WhatsApp Image 2021-02-28 at 11 08 24 AM](https://user-images.githubusercontent.com/10252263/109472089-f974b300-7a71-11eb-9f89-2b3191b33212.jpeg)

**Comment by thversfelt** [comment]
We created BTC multi-sig functionality and created a small demo. Check it out here: https://github.com/Tribler/tribler/issues/5988#issuecomment-789984250

**Comment by synctext** [comment]
https://hummingbot.io/ and https://margin.de/
Documenting related work for future reference (unknown if they have something somewhat operational).

**Comment by daandeheij** [comment]
@chrislemaire '

Could you give me access to the fork of group 2? :D

**Comment by chrislemaire** [comment]
Hmmm I had already invited you but it seems you hadn't accepted it. I will try to resend it.

**Comment by daandeheij** [comment]
My bad! I glanced over it. Thank you :D

**Comment by daandeheij** [comment]
### Meeting 23/03/2021

- Group 1 can try to integrate BTC/ETH pair into liquidity pool coded by group 2
- Group 1 can try to integrate multisignature BTC into group 2's BTC/eurotoken liquidity pool
- Group 2 is working on multi-signature for eurotoken

**Comment by thversfelt** [comment]
BTC multi-sig implementation update (branch: https://github.com/chrislemaire/trustchain-superapp/tree/multi-sig-wallets-implementation):
- Refactored our BTC multi-sig demo into a more Object-Oriented format
- Refactored liquidity pool app code to make place for BTC multi-sig
- Implemented BTC multi-sig wallet creation into the app
- Implemented BTC multis-sig depositing, and withdrawing into the app

The implementation is made on top of what code group 2 has presented last week. This means it only has partial trustchain integration. It required quite some refactoring, so it will look a bit different than what was presented to us. I do think that in its current state, group 2 should be able to use the current BTC implementation, to be able to complete their BTC-EURotoken demo.

Meanwhile, group 1 (us), will create a seperate fragmant in which we will contain and implement our BTC-ETH demo. This should allow us to work more independently from now on. Of course, please communicate any questions regarding BTC multi-sig with us.

**Comment by xoriole** [comment]
https://github.com/Tribler/trustchain-superapp/pull/75 PR is merged, closing the issue
