### ISSUE TITLE
Transport protocol over IPv8

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#6003]
Further development of Tribler Channels features requires adding a way to quickly and reliably transport small files over the network. Libtorrent does not fit this role for too many reasons.
The biggest problem is that we're forced to build the thing atop IPv8 addressing system, which denies us reusing every other non-pure-Python protocol library in existence.

* Sans protocol QUIC implementation is ruled out as too complex.
* No proper TCP implementations in pure Python.

One alternative way is to use IPv8 to coordinate NAT puncture for something like [UDT](https://en.wikipedia.org/wiki/UDP-based_Data_Transfer_Protocol)

My current attempt at solving the problem: #6002 

Some useful links:
* https://github.com/vmarkovtsev/udt4py
* https://github.com/delattj/py_udt

**Comment by qstokkink** [comment]
Short recap of "offline" discussion on using UDT and hooking in external transport libraries into IPv8:

 - Using UDT puncturing is unnecessary, as IPv8 can give you an already punctured port (which it gives you the WAN address estimate for to connect to it).
 - Ideally, just use the IPV8 port with your transport protocol.
 - Less ideally, use IPv8 to puncture a port with `socket.so_reuseaddr` and hand it off to the transport protocol library.
 - Equally less ideally, wrap the external socket in an IPv8 `Endpoint` object and make it available in the `DispatcherEndpoint` mapping.
 - In the worst case: use local socket loopback to feed the data back into your own process.

**Comment by ichorid** [comment]
>Ideally, just use the IPV8 port with your transport protocol.

I still don't get it, what will process the packets in this case: IPv8 or my protocol library? How would they know which packet should be processed by which socket listener? :shrug:

**Comment by qstokkink** [comment]
> IPv8 or my protocol library? 

Both. For receiving, IPv8 first strips its header information from the packet and then the library unserializes the remainder. For sending, IPv8 would add its extra header info to the serialized packet from the external library.

> How would they know which packet should be processed by which socket listener?

If properly layered this should be completely opaque: whether the packet comes from the Internet or not _should_ be a matter of hooking up the streams correctly. For example, if your library of choice supports asyncio transports, you can easily reroute this by overwriting the default transport:

![rerouteexample](https://user-images.githubusercontent.com/3630389/108618698-7378bc80-7420-11eb-8418-dd511cad1721.jpg)
