### ISSUE TITLE
Unable to access the documentation.

### ISSUE THREAD

**Issue by BlurryBat** [Tribler/tribler#6007]
Not sure if this is the right way to report this, but I am not able to view the docs. https://tribler.readthedocs.io/en/main/contributing.html shows "SORRY This page does not exist yet."

**Comment by qstokkink** [comment]
Thanks for reporting this, our `README.rst` is apparently out of date with our latest branch structure.

The link should be:

https://tribler.readthedocs.io/en/latest/contributing.html

**Comment by drew2a** [comment]
I'll check the links from our docs and fix them.
