### ISSUE TITLE
Torrents on the "popular" page are almost always red after health checking

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#6011]
### The problem
Torrents on the "popular" page are almost always become red after health checking.

That is probably because recheck is considered as DHT spamming.

@ichorid @xoriole you are the most knowledgeable persons... how can we solve it?

If I understand correctly this issue should be solved in the `7.9.0` release.

##### Tribler version/branch+revision: #####
latest main

![image](https://user-images.githubusercontent.com/13798583/108705966-41de1f00-750e-11eb-863a-f3863200a830.png)

**Comment by ichorid** [comment]
This one is hard... The only reasonable way to pace down the DHT checks to avoid triggering spam detection is to create a queue (or a stack) for them. That's entirely possible and must be done at the TorrentChecker level. However, that will require rerouting all the DHT checks from all endpoints through the Checker.

As a way to increase the efficiency of these checks, we can gather the information about our current DHT peers from Libtorrent and maintain a separate per-DHT-peer queue.

However, this will hardly improve the user experience. The checks will still be slow as hell :imp:
To make it effective, we'll have to preemptively start rechecking the most popular torrents in the background as soon as we know about them.

**Comment by drew2a** [comment]
What do you think about disallowing "recheck" on this page then?

**Comment by ichorid** [comment]
> What do you think about disallowing "recheck" on this page then?

That will obviously deceive the users. Also, the recheck will still happen when the user tries to download the stuff.

**Comment by drew2a** [comment]
Fixed by https://github.com/Tribler/tribler/pull/6030
