### ISSUE TITLE
Removal of json_util.py

### ISSUE THREAD

**Issue by Solomon1732** [Tribler/tribler#6013]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Tribler-main branch
##### Expected behavior: #####
Usage of the py3 packaged json utilities.
##### Actual behavior: #####
Based on [this discussion](https://github.com/Tribler/tribler/discussions/6012#discussioncomment-393615) the file [`json_util.py`](https://github.com/Tribler/tribler/blob/main/src/tribler-core/tribler_core/utilities/json_util.py) appears to be a leftover from the transition from py2 to py3. Since the file isn't needed anymore it might be possible to remove it in favor of using python's own json utilities. Currently it is used, but in a limited way.

**Comment by ichorid** [comment]
@qstokkink, could you comment on this?

**Comment by qstokkink** [comment]
Beyond [the background information I already gave](https://github.com/Tribler/tribler/discussions/6012#discussioncomment-393471): this would be a matter of replacing all instances of `import tribler_core.utilities.json_util as json` with `import json` and removing the `json_util.py` file.

This is perfectly safe and downsizes our codebase, all without losing any debug information. Win-win.

**Comment by ichorid** [comment]
@xoriole , would you care doing it :wink: ?

**Comment by xoriole** [comment]
@ichorid sure
