### ISSUE TITLE
Digital Basic Identity - EU EBSI gateway and "regie op gegevens"

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#6023]
Topic is determined: Digital Basic identity, see https://www.tweedekamer.nl/kamerstukken/brieven_regering/detail?id=2021Z02985&did=2021D06488

 Estimated timeline (tentative)
- 2 _weeks_: read background, compile prior code, understand ID,wallet and EBSI sandbox
- 2 months: participate in design team of Digitale Bron Identiteit (Deliver a report, English thesis appendix) (possibly with #6029)
- Milestone after 2 months: Problem Decription first draft of 3-5 pages, outlines the _deep dive direction_
- 1 month: [EU EBSI connection](https://api.ebsi.xyz/docs/)/ESSIF with trustchain, our DBI/SSI solution.
- 5-6 months: master thesis deep dive. Possible directions:
  - Revocation (Pallier, Schnorr, buzzword-3, etc. hard-core crypto)
  - eDemocracy (_Bindend Burger Advies_ trail with 25+ people)
  - Secure Data Sharing (data exchange, data box, real-time chat, and key management)
  - Personal data vault (with some machine learning?)

First sprint target of 2 weeks: _see above_

**Comment by sjacobino** [comment]
@synctext you mentioned the groundwork laid by Rowdy for digital identity. Is there something I can start looking into?

**Comment by sjacobino** [comment]
SSI Pull request

https://github.com/Tribler/trustchain-superapp/pull/60/files

**Comment by synctext** [comment]
2 week pause due to circumstances. Code compiles locally, EBSI reading first pass done, pull request Rowdy review on ToDo list.

**Comment by synctext** [comment]
For more context, in [2017 we talked about the "decentralised economy"](http://pure.tudelft.nl/ws/files/41225519/article.pdf). Identity is the foundation. Others are now also doing this in a token hype manner: https://fetch.ai/wp-content/uploads/2019/10/Fetch.AI-Economics-white-paper.pdf This team actually deployed an IPv8 clone: http://www.ifaamas.org/Proceedings/aamas2021/pdfs/p1037.pdf

**Comment by jwbambacht** [comment]
First draft problem description.

[ProblemDescription.pdf](https://github.com/Tribler/tribler/files/6419460/ProblemDescription.pdf)

**Comment by sjacobino** [comment]
Start on the problem description: Self-Sovereign Shared Identity

Use case is SSI for group subscriptions which includes data sharing and some key management.

[SSSI Problem description.pdf](https://github.com/Tribler/tribler/files/6507288/SSSI.Problem.description.pdf)

**Comment by synctext** [comment]
Good readable first version of problem description. Just replace "family plan" with "legal entity", then it becomes economic relevant and key for SSI. Authorisation within huge companies or hierarchical government is unexplored.

**Comment by synctext** [comment]
Possible sprint idea for coming 2+ weeks. Make first Pull Request on the Superapp.
For instance, add address sharing in PeerChat. Any address book entry you have locally (nickname+public key) becomes available to share with your friends.

**Comment by sjacobino** [comment]
Preview contact sharing


Uploading IMG_4267_MED_1_1.mp4…

**Comment by synctext** [comment]
- Working on thesis for 2-3 months now
- Completion of official RvIG onboarding, next step: EBSI intergration of unknown time duration. 
- European Identity wallet: Cross-Country EBSI wallet exchange
  - Ongoing efforts, no real SSI exists yet, see [ongoing projects and wallets](https://github.com/animo/awesome-self-sovereign-identity#%EF%B8%8F-products--services). All focussed on the high-cost, high complexity W3C approach with 'universal resolver'.
  - German solution: online at [play store](https://play.google.com/store/apps/details?id=com.esatus.wallet) and there is a [white paper with some tech details](https://esatus.com/wp-content/uploads/Whitepaper_esatus_SSI_Roll-out_20200224-1.pdf). Verdict: small startup, early stage technology development.

**Comment by sjacobino** [comment]
Preview contact sharing in gif form:

![ezgif com-optimize](https://user-images.githubusercontent.com/5730521/122896479-65449980-d349-11eb-95c5-308ec9647292.gif)

**Comment by sjacobino** [comment]
To do in contact sharing feature: 
- Highlight selected contact in list
- Multiple contacts at once?

**Comment by sjacobino** [comment]
![Screenshot_1624650857](https://user-images.githubusercontent.com/5730521/123479928-e6c65100-d601-11eb-9c01-f64daed84080.png)
![Screenshot_1624651439](https://user-images.githubusercontent.com/5730521/123479941-eaf26e80-d601-11eb-99b5-85f2c115c5e5.png)
![Screenshot_1624651580](https://user-images.githubusercontent.com/5730521/123479960-f2b21300-d601-11eb-9cd0-8a1e9cfaac30.png)
![Screenshot_1624651590](https://user-images.githubusercontent.com/5730521/123479964-f3e34000-d601-11eb-90ab-bdd76ebca229.png)

**Comment by sjacobino** [comment]
Share contacts PR: https://github.com/Tribler/trustchain-superapp/pull/77/commits

Small feature that allows you to send one of your contacts as an attachment in a conversation. Recipient can click on the contact and add it to his/her list.

**Comment by sjacobino** [comment]
- Contact sharing Pull request online. Has lint errors that can be fixed.
- EBSI account is set up. Reading early adopters program, getting feel for Wallet and DID APIs

Next steps:
- Hosting our own EBSI Node with test environment. Requirements: https://ec.europa.eu/cefdigital/wiki/pages/viewpage.action?pageId=390792199
- EBSI nodes come as a bundle: V2 test env, V2 production env, V1 test env
- Test out API using CLI app

Current vision/goal
- IG-SSI integrated into EBSI/ESSIF to send and receive attestations from outside of Trustchain e.g DBI
- Social app based on the concept of Decentralized Social Applications Based on Linked Data (Solid)
- Think about a shared calendar, notes, foto album that collects data from the personal online datastore (pod, basically a data vault with acces control), and aggregates the data into a social experience. Apps within and outside of Trustchain Superapp can access users’ pods.

![TCCommunity_in_EBSI](https://user-images.githubusercontent.com/5730521/124720826-d4ed8380-df08-11eb-867f-fb7d1732ec49.png)

![TC_POD_in_EBSI](https://user-images.githubusercontent.com/5730521/124720843-dae36480-df08-11eb-85ff-5a5309a3a6f9.png)

**Comment by synctext** [comment]
- Superapp as an app store for "social enriched" secure apps. Next level ideas, of MIT Solid initial sketches. Is this really mass-uptake realistic? True, if [we feed into the EU-wide digital wallet](https://ec.europa.eu/commission/presscorner/detail/en/IP_21_2663).
- Trustless execution environment, personal data vault, self-sovereign data access permission and revocation.
- With this thesis direction, reliability is now minor part only.

**Comment by sjacobino** [comment]
Because of electricity/internet problems, no video call on 23/07/2021.

Updates:
- Working API interface with test server EBSI (api.ebsi.xyz). I did not manage to get a meeting with Andre last week to discuss using the actual NL test servers hosted by the TU and I did not try again this week. That's my bad. But everything seems to work using dummy calls to the public test server.
- Instead of making a cmd line app, I directly implemented it in the Super App commons so that it is easier to link it with our wallet code in the next step.
- Working on an introduction for the new aim: Personal data vaults in the super app, that combined with SSI sovereignty not just over identity, but all data that can be accessed by applications within the super app ecosystem, and services outside (read EBSI). This is a work in progress and a first draft can be expected next week.
- The productivity has taken a hit this week but there enough to do still (see uncompleted points in previous post)

**Comment by sjacobino** [comment]
EBSI docs, api and libraries currently a mess. Conflicting information on the different platforms which is making it impossible to make a working connection.

E.g. 

<img alt="Screen Shot 2021-08-30 at 08 55 41" src="https://user-images.githubusercontent.com/5730521/131298919-a74d8a9c-2edf-4100-9ce1-d1a962a25742.png" width=100%>

So let's fix that:

<img width="100%" alt="Screen Shot 2021-08-30 at 08 56 03" src="https://user-images.githubusercontent.com/5730521/131299128-b732fe96-2a88-404e-8a69-144fdb9889f5.png">

**Comment by sjacobino** [comment]
Sample code on NPM site:
https://www.npmjs.com/package/@cef-ebsi/did-auth

<img width="764" alt="Create Auth Response did-auth_0_0_12" src="https://user-images.githubusercontent.com/5730521/131335309-a5411da3-d1e0-4f21-8792-390d677f3081.png">

Sample code on EBSI Doc:
https://ec.europa.eu/cefdigital/wiki/display/EBSIDOC/DID+Authentication+Library

<img width="894" alt="Screen Shot 2021-08-30 at 13 54 30" src="https://user-images.githubusercontent.com/5730521/131335449-a9129d1d-ee37-45a4-9456-8817b0898f94.png">

**Comment by sjacobino** [comment]
[Digital_Basic_Identity_MSc_Thesis___TU_Delft.pdf](https://github.com/Tribler/tribler/files/7076667/Digital_Basic_Identity_MSc_Thesis___TU_Delft.pdf)

**Comment by synctext** [comment]
Personal Data Vault (brainstorm thesis direction):
- [ ] Access Control: sharing with 1 friend, friend-of-friends or whole Internet
- [ ] Scalability: share 1 Byte or share 1 Tera Byte
- [ ] Example personal vault GUI: re-use the existing music playback, magnet-based sharing, album cover art, and operational IPv8 gossip-discovery community

**Comment by sjacobino** [comment]
[Digital_Basic_Identity_MSc_Thesis___TU_Delft-3.pdf](https://github.com/Tribler/tribler/files/7167641/Digital_Basic_Identity_MSc_Thesis___TU_Delft-3.pdf)

**Comment by sjacobino** [comment]
[Digital_Basic_Identity_MSc_Thesis___TU_Delft-3.pdf](https://github.com/Tribler/tribler/files/7167653/Digital_Basic_Identity_MSc_Thesis___TU_Delft-3.pdf)

**Comment by sjacobino** [comment]
Progress on bug report:

![Screen Shot 2021-09-15 at 09 14 42](https://user-images.githubusercontent.com/5730521/133387988-4ff2c3bc-0fe3-41af-9ae0-130627ee75cd.png)

**Comment by synctext** [comment]
Storytelling: immediately reveal the plot and don't write it as a slow tutorial: ```secure sharing of personal data is an unsolved problem.```

**Comment by sjacobino** [comment]
Data Vault Demo Apk: https://drive.google.com/file/d/1qPcO9RoSYthnZXOy6q82dVZlihtIFeji/view?usp=sharing

**Comment by sjacobino** [comment]
What's going on in the demo apk:

Initial data vault directory on the device that is accessible by other devices via the DataVaultCommunity.
Simple access control that takes any verifiable attestation.

The problem now is that messages including attestations don't seem to get to the other side. Solution is likely to copy peer chat's attestation chunk approach, and reassemble back at the other endpoint.

Defining access policy at file or directory level is viable. Files with undefined access policy inherits policy from parent directory.

Biggest challenge seems to be structuring the filesystem to reflect graph-like nature of the linked data.

**Comment by synctext** [comment]
please add 4c69624e61434c504b3a52904df841596dff8149fc41623b91b1149f92fe37f2c1c40c5ffb2867b7a75438e2694ab58b3c280578b80f348ca62fda10372581e3365cbd87c0551f3bc007

**Comment by synctext** [comment]
Fresh related EU work: https://europa.eu/europass/en/european-digital-credentials-learning-interoperability

**Comment by sjacobino** [comment]
No real productivity in last 2 months.

Some further improvements on the EBSI CLI using updated libraries. Problems are still difficult to iron out because error messages from the API are sometimes unclear.

What works:
- Onboarding (getting verifiable authorisation)
- SIOP authentications (verifying request, create and submit response)

Not managed to get working:
- Verifiable presentations (seems to be down to a specific encoding required)

In the end we need the mobile (Android) libraries from EBSI to integrate it into the SuperApp, but those are not on the planning for EBSI v2 ( https://ec.europa.eu/cefdigital/wiki/display/EBSIDOC/Users+Onboarding+API#UsersOnboardingAPI-MobileWallet(NotYetforEBSIV2.0) )

**Comment by synctext** [comment]
Last progress meeting was 2 months ago. 

EBSI v1 was everything server-side. EBSI v2 is typscript based. 
Progress of recent week is that EBSI team did some changes, updates, and repairs. More is operational now, JSON web tokens now appears functional.

Master thesis content: W3C did model versus the Rowdy/Quinten verifiable credentials.
EU EBSI Mobile roadmap for mobile :zap: : ```EBSI compliant data model is not available```

**Comment by sjacobino** [comment]
Brief description of my experience working with European Commission EBSI code:

Working with EBSI code has been a bit cumbersome at times. In some cases example code provided on the npm page is incomplete. If the code is copied and pasted some parameters might be missing. For instance, the sample code for creating SIOP authentication responses (https://www.npmjs.com/package/@cef-ebsi/siop-auth) does not show how to structure include claims/verifiable credentials/verifiable presentations. You have to combine information from the documentation page to get a complete picture. This is the case with most of the EBSI libraries available on npm.

Some information however is nowhere to be found. E.g how to construct a json-rpc request to insert a new DID document (https://ec.europa.eu/cefdigital/wiki/display/EBSIDOC/DID+Registry+API). The parameters used: identifier, didVersionInfo, timestampData, and didVersionMetadata are not explained anywhere leaving you to guess what they are.

As mentioned before, API error messages are often non descriptive and do not state very clear what the error is or what has to be changed.

**Comment by synctext** [comment]
perfect info! please post a reproducible error to EBSI and provide details. Then we can escalate them upwards.

**Comment by sjacobino** [comment]
EBSI+TrustVault poster draft to be discussed.

Main questions: Too abstract/not technical enough? More (specific) technical illustrations? Does it get the message across (especially if orally presented)?

[EBSI+TrustVault Poster.pdf](https://github.com/Tribler/tribler/files/7815172/EBSI%2BTrustVault.Poster.pdf)

**Comment by sjacobino** [comment]
Trustvault + Essif final poster for meeting AFM

[TrustVault+ESSIF Poster-4.pdf](https://github.com/Tribler/tribler/files/7830133/TrustVault%2BESSIF.Poster-4.pdf)

**Comment by sjacobino** [comment]
DataVault prototyped advanced in the last 2 weeks:

The process now goes as follows

1. You get a list of peers from which you can request files
2. You send a request to see which files are accessible to you with the attestations that you have
3. You get a filtered list back from your peer of files you can select from
4. You choose a file and it is retrieved

The advancements are

1. Smooth workflows
2. Attestations are actually verified but no distinction is made yet between the different types of attestations
3. Individual files can be made public so that no credential is required to get them. This menu is will be expanded to set granular, more complex access rules (instead of just public or not)
4. To minimize overhead, attestation only need to be sent at first request. Subsequently a token (derived from the attestations) is used to retrieve subsequent files. (Some interesting caching needed here)
5. Some interface improvements as well, with the goal in mind to migrate everything under one Value Transfer roof.

See Slack for apk file.

**Comment by synctext** [comment]
Very productive sprint !! :tada: 
<IMG src=https://user-images.githubusercontent.com/325224/150541458-9d215218-19d3-4742-a8b1-a249966146d2.png width=200>

**Comment by sjacobino** [comment]
To get to the core of the thesis: giving users full control to define how 3rd parties can retrieve files in his/her vault. This is done by defining what is basically a decision tree for required combination of credentials. This is done granularly at file and folder lever. Credentials can be issued by the user or by trusted 3rd parties (if the stars align, even from EBSI).

**Comment by sjacobino** [comment]
Let's try to find out more about the wallet conformance testing
https://ec.europa.eu/cefdigital/wiki/pages/viewpage.action?pageId=455606439

**Comment by sjacobino** [comment]
This sprint in the end was all about UI/UX taking a lot of time. The browser now looks like a proper file system and has file system functionalities. Files can now inherit access control rules from their parent folder. Having some issues still with loading remote files. So EBSI conformance testing is still on the to-do list.


https://user-images.githubusercontent.com/5730521/155093185-20054916-e12a-4e80-92a7-8b964f07e6fd.mov

**Comment by synctext** [comment]
- ToDo key selling point of thesis? candidate: "EBSI-compatible data vault", 1 TByte, certified, privacy-first, non-custodian, etc.
- eIDAS-high compliance impact is very significant, see Rotterdam municipality [using **commercial** Belgian bank+telco monopoly technology](https://tweakers.net/nieuws/193488/rotterdam-gaat-van-oorsprong-belgische-identiteitsapp-itsme-gebruiken.html)
- for compliance, encrypt the data. ToDo: how to decrypt and make available to the insecure PDF viewer or do we need ["secure viewers" which are 'crypto-aware'](https://github.com/barteksc/AndroidPdfViewer).

**Comment by synctext** [comment]
- progress: EBSI focus last week
  - :heavy_check_mark: EBSI login and token
  - :heavy_check_mark: EBSI simple create credential
  - :x: Advanced EBSI challenge/response authentication responses (create JSON web token, try to verify)

**Comment by sjacobino** [comment]
Similar error messages as a while back. Not really clear what the issue is:

<img width="600" alt="Screen Shot 2022-03-11 at 09 45 43" src="https://user-images.githubusercontent.com/5730521/157833261-cf2ce11c-4347-47b2-81cb-b59d871f63ee.png">

**Comment by sjacobino** [comment]
EBSI is using ECDSA with the secp256k1 curve which is being deprecated by most libraries. The trend is to switch to either 256r1 or to EdDSA. Not really future proof. See https://jwt.io/libraries

**Comment by sjacobino** [comment]
Last sprint:

- Lots of time spend upgrading project to Java 11, necessary to use packages for signing VCs. Lots of refactoring our own code and library Java code to work in Android.

- Some progress made with EBSI conformance (~50%-60%) depending on what coverage we want (only synchronous flows or also asynchronous flows)

-Authentication and so finally succeeded. Current stumbling block is interacting with smart contract end-points. Documentation and examples still very difficult to navigate:

<img width="578" alt="Screenshot 2022-03-29 at 14 50 50" src="https://user-images.githubusercontent.com/5730521/160616599-7130e245-3e11-4ada-8484-8111b655d69f.png">

or

<img width="884" alt="Screenshot 2022-03-29 at 14 52 13" src="https://user-images.githubusercontent.com/5730521/160616671-b6dca8b8-0ecc-45fc-ba95-3eabf939bb3c.png">

Is it it hex or base64????

**Comment by sjacobino** [comment]
EBSI conformance plan:

https://ec.europa.eu/digital-building-blocks/wikis/display/EBSIDOC/EBSI+Wallet+Conformance+Testing

**Comment by sjacobino** [comment]
<img width="689" alt="Screenshot 2022-04-21 at 09 37 11" src="https://user-images.githubusercontent.com/5730521/164403743-76be51ba-37fb-47fd-8a4a-c4ffdaf7b200.png">

<img width="689" alt="Screenshot 2022-04-21 at 09 37 26" src="https://user-images.githubusercontent.com/5730521/164403773-647c206d-7ce3-4c85-ad76-44fc78dc18fc.png">

**Comment by synctext** [comment]
- converging, nice progress
- Start of writing: either do first draft of problem description chapter or (recommended) start with the content, experiments, screenshots. Performance graph of vault read/write, remote vault data transfers.

**Comment by sjacobino** [comment]
Trusted apps registry: https://api.conformance.intebsi.xyz/docs/?urls.primaryName=Trusted%20Apps%20Registry%20API

**Comment by synctext** [comment]
Great find!  [EBSI conformance reports](https://ec.europa.eu/digital-building-blocks/wikis/display/EBSI/Conformant+wallets#find-a-wallet)
<img src=https://user-images.githubusercontent.com/325224/167631108-a26b0adf-5790-444a-aa00-f2546f7189ae.png width=200>

**Comment by sjacobino** [comment]
[TrustVault_MSc_Thesis___TU_Delft-2.pdf](https://github.com/Tribler/tribler/files/9110907/TrustVault_MSc_Thesis___TU_Delft-2.pdf)

**Comment by synctext** [comment]
ToDo: conformance report with Delft University of Technology????

**Comment by sjacobino** [comment]
[0203-Gataca.pdf](https://github.com/Tribler/tribler/files/9111097/0203-Gataca.pdf)
[0303 - Danube.pdf](https://github.com/Tribler/tribler/files/9111098/0303.-.Danube.pdf)

**Comment by synctext** [comment]
Any update for your master thesis?
(btw Walt-ID smells like DiD-based bloatware, not IPv8 with lightning fast zero-knowledge proofs)

**Comment by sjacobino** [comment]
[TrustVault_MSc_Thesis___TU_Delft-3.pdf](https://github.com/Tribler/tribler/files/9335644/TrustVault_MSc_Thesis___TU_Delft-3.pdf)

**Comment by sjacobino** [comment]
Still not EBSI conformant 😢 Whole process has changed and integrating with Walt id was a headache. Not necessarily bloatware as it able to parse complex credentials that I was not able to implement. And code is forked so unnecessary stuff can be removed

**Comment by synctext** [comment]
Did a quick review of Walt ID code (non-Android Kotlin) :
![image](https://user-images.githubusercontent.com/325224/184594844-e561c419-5855-4d32-b646-3658109879b9.png)

**Comment by sjacobino** [comment]
[TrustVault_MSc_Thesis___TU_Delft-4.pdf](https://github.com/Tribler/tribler/files/9392619/TrustVault_MSc_Thesis___TU_Delft-4.pdf)

**Comment by synctext** [comment]
Comments:
- more clarity in the introduction, high impact, EBSI is not a small tech thingie: Digital identity for all Europeans is coming. "In September 2020, Ursula von der Leyen, President of the European Commission, revealed plans for a re-vamp of the system: eIDAS 2.0. [At its centre will be new digital identity wallet.](https://www.thalesgroup.com/en/worldwide-digital-identity-and-security/government/magazine/eu-digital-id-wallet-coming-heres-what#:~:text=In%20September%202020%2C%20Ursula%20von,will%20remain%20voluntary%20for%20citizens).) Any EU citizen or company will be able to request one (although it will remain voluntary for citizens)." and REF: https://ec.europa.eu/info/strategy/priorities-2019-2024/europe-fit-digital-age/european-digital-identity_en

**Comment by sjacobino** [comment]
[TrustVault_MSc_Thesis___TU_Delft-10.pdf](https://github.com/Tribler/tribler/files/9452544/TrustVault_MSc_Thesis___TU_Delft-10.pdf)

**Comment by synctext** [comment]
Review:
- "extend the Security, Control and Portability properties of SSI", no caps here

**Comment by sjacobino** [comment]
Al geüpload zonder    Replace " DV " with data vault everywhere. adds clarity.

**Comment by sjacobino** [comment]
[TrustVault_MSc_Thesis___TU_Delft-FINAL.pdf](https://github.com/Tribler/tribler/files/9459310/TrustVault_MSc_Thesis___TU_Delft-FINAL.pdf)

**Comment by synctext** [comment]
<quick first round feedback> first presentation comment: 58 slides is too much slides for available time. Prune some tutorial-level material. Focus on the _science_ part. What is your related work? Citations towards scientific literature in several slides??

**Comment by sjacobino** [comment]
Some of the slides are duplicates to reveal info bit by bit. Working on related work slides.

**Comment by sjacobino** [comment]
Tutorial-level will be quick

[TrustVault Presentation-2.pdf](https://github.com/Tribler/tribler/files/9460572/TrustVault.Presentation-2.pdf)

**Comment by synctext** [comment]
Great content! Remove empty slides with just 1 line of content --> merge
Lots of slides, then aim for 40 minutes of presentation and _dont_ rush through the material. Explain clearly a& calmy. Looking forward..!

**Comment by synctext** [comment]
brainstorm/ideas for evaluation section:
- performance analysis
  - measure time for credential verification, creation time, and write to Trustchain, etc.
  - measuring CPU usage
  - measure data traffic
  - Conclusion???? crypto == cheap, networking == expensive
- performance breakdown
  - all detailed steps when providing access to your personal data
  - measure required time per task/step

**Comment by synctext** [comment]
Raw measurements from paper above. example: "Measurements re-used with permission from [1]"
[measurements.zip](https://github.com/Tribler/tribler/files/9503223/measurements.zip)

**Comment by sjacobino** [comment]
![ctr-cbc-decryption](https://user-images.githubusercontent.com/5730521/190429295-9e21409a-4ff4-41f2-8bca-2fc4064bc78f.jpg)
![ctr-cbc-encryption](https://user-images.githubusercontent.com/5730521/190429301-2c8f838f-69de-4090-9127-daea7f3d1204.jpg)
![transfer_latnecy](https://user-images.githubusercontent.com/5730521/190429302-b34ff83e-ca5c-4411-81fc-fdb2e9287d16.jpg)

**Comment by synctext** [comment]
- two screens in 1 photo == experimental setup OR screenshots of 1 side in green-on-black cmdline ADB output. Example 
<IMG src=https://user-images.githubusercontent.com/325224/190433801-b2a5f76e-ee34-43e0-af37-2c2d4a02cee9.png width=450>
- process this experiment into storyline of master thesis, before moving to next thing.

**Comment by sjacobino** [comment]
[TrustVault_MSc_Thesis___TU_Delft-4.pdf](https://github.com/Tribler/tribler/files/9624365/TrustVault_MSc_Thesis___TU_Delft-4.pdf)

**Comment by synctext** [comment]
- introduction explains too much. Keep it high level and make 3 research contributions visible with 3 bullets.
- "fined-grained AC without TTPs like distributed ABE schemes" bad style!

**Comment by synctext** [comment]
btw Please post your thesis online in IEEE-like format (_without_ TUDelft cover): https://arxiv.org/a/pouwelse_j_1.html

**Comment by sjacobino** [comment]
[mkrmvqdmdzyjdtmpdqcxmyvgchwrkjmz.zip](https://github.com/Tribler/tribler/files/10466427/mkrmvqdmdzyjdtmpdqcxmyvgchwrkjmz.zip)
