### ISSUE TITLE
Add junit family to pytest.ini

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#6027]
As a workaround, our Jenkins PR test jobs are appending the `junit_family` to the `pytest.ini` file at runtime.

To make this a bit cleaner, we should:

 - Add the line `junit_family=xunit2` to the `pytest.ini` file instead under the `[pytest]` section.
 - Remove the line that is runtime appending to the `pytest.ini` file in each of the three PR test Jenkins jobs.

**Comment by kozlovsky** [comment]
`xunit2` is now default format in pytest since 6.1, so probably we can just remove this line:
https://docs.pytest.org/en/6.2.x/changelog.html?highlight=xunit2#pytest-6-1-0-2020-09-26

**Comment by drew2a** [comment]
After https://github.com/Tribler/tribler/issues/6840 has been done, we can be sure that all corresponding tests run under `pytest==6.2.5`:
 
https://github.com/Tribler/tribler/blob/50e84df930127c4e63aa0eedbb106252ebab325e/requirements-test.txt#L3

I've removed all runtime appending in Jenkins jobs.

This Issue could be closed.
