### ISSUE TITLE
Trust graph doesn't update balance

### ISSUE THREAD

**Issue by kotenok2000** [Tribler/tribler#6057]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
V7.9.0-RC1
##### Operating system and version: #####
Microsoft Windows [Version 10.0.19042.928]
##### Steps to reproduce the behavior: #####
Load tribler.
enable exit.
open Trust graph
wait for a day.
##### Expected behavior: #####
Trust graph gets updated in real time.
##### Actual behavior: #####
Trust graph doesn't update balance
refresh button does not work.
##### Relevant log file output: #####

![Снимок экрана (29)](https://user-images.githubusercontent.com/8822292/115230540-2f9eec80-a11d-11eb-9c59-73b21e564630.png)

**Comment by kotenok2000** [comment]
Channel numbers also do not update.
![Снимок экрана (33)](https://user-images.githubusercontent.com/8822292/115361034-dd1b0a00-a1c8-11eb-8c02-d572cf300840.png)

**Comment by danrobi11** [comment]
Same here. Trust graph does not update.
v.7.9.0 deb file
OS: MX 19.3 (patito feo) x86_64 based Debian GNU/Linux 10 (buster)
Kernel: 4.19.0-14-amd64
