### ISSUE TITLE
Sorting the popular page does not work correctly

### ISSUE THREAD

**Issue by noughtmare** [Tribler/tribler#6058]
##### Tribler version/branch+revision:  #####

tribler_7.9.0_all.deb

##### Operating system and version:  #####

Debian buster

##### Steps to reproduce the behavior: #####

1. open tribler
2. click on popular tab
3. click on the size column to sort by size
4. notice that the results are not sorted correctly

![image](https://user-images.githubusercontent.com/2665074/115283544-08571800-a13b-11eb-823f-a83defa8ec66.png)

(this also happens with the other columns, but size is the easiest to show in this example)

##### Expected behavior: #####

I don't actually know if sorting should be enabled at all. Maybe it is better to always lock the ordering on "most popular", but then the manual sorting should be disabled.

**Comment by kozlovsky** [comment]
Thank you for reporting, we'll fix it

**Comment by kozlovsky** [comment]
Fixed in #6064
