### ISSUE TITLE
I cannot create a folder in my channel anymore.

### ISSUE THREAD

**Issue by dertuxmalwieder** [Tribler/tribler#6061]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

7.9.0

##### Operating system and version: #####

Windows 10

##### Steps to reproduce the behavior: #####

Move a couple of files into your channel and try to create new folders for them.

##### Expected behavior: #####

The "New folder" dialog should appear.

##### Actual behavior: #####

The "New channel" dialog appears.

Here's a video showing the problem:

![pZxBayH](https://user-images.githubusercontent.com/125629/115566133-46c71100-a2ba-11eb-8f63-61fbd41587aa.gif)

**Comment by ichorid** [comment]
Well, that's just a misprint. The dialogue says `channel` but it will create a folder instead.

**Comment by ichorid** [comment]
We will fix the misprint for the next release.
