### ISSUE TITLE
Popular torrents is empty

### ISSUE THREAD

**Issue by da2x** [Tribler/tribler#6062]
##### Tribler version/branch+revision: #####
7.9.0

##### Operating system and version: #####
Windows 10.21364.1

##### Steps to reproduce the behavior: #####
1. Install Tribler
2. Set `[torrent_checking].enabled = False` to make Tribler live up to its privacy ideals.
3. Start it and let it run for 28 hours.
4. Go to Popular 

##### Expected behavior: #####
It should probably list popular torrents, or something? Alternatively, its empty state should explain why its empty and what to do to get something listed.

##### Actual behavior: #####
![tribler-7 9 0-popular-empty](https://user-images.githubusercontent.com/1102886/115635114-3be89c80-a30b-11eb-97a6-c362e14efa7f.png)

**Comment by kozlovsky** [comment]
Thank you for reporting, we are already working on it, the fix should be included in the next release.

**Comment by kozlovsky** [comment]
Fixed in #6064. The `Popular torrents` page should show torrents now. Not all of them will be really highly popular at this moment, but this should be improved soon after fixing the gossiping algorithms.

**Comment by da2x** [comment]
Thanks!
