### ISSUE TITLE
Select different drive/folder for the .Tribler data.

### ISSUE THREAD

**Issue by snakyjake1** [Tribler/tribler#6066]
- [X ] I have read CONTRIBUTING.rst

- [X ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
v7.8.0

##### Operating system and version: #####
Windows

I would like to select a different drive/folder for the Tribler data.  I do not want to use C:\Users\<user>\AppData\Roaming\.Tribler.  Also, my C: drive does not have enough space for the Tribler data.

**Comment by ichorid** [comment]
You can set `TSTATEDIR=<path_to_tribler_config folder>` environment variable to change the home dir.

**Comment by snakyjake1** [comment]
Might there be a feature to set the variable in a config file?

**Comment by ichorid** [comment]
> Might there be a feature to set the variable in a config file?

Well, and where's the config file should be then? :wink:
