### ISSUE TITLE
Stop running the full testsuite on documentation changes

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#6095]
Running the complete Tribler test suite on every typo fix makes writing documentation an overly painful exercise. We isolate the doc tests from the main tests.

**Comment by ichorid** [comment]
@xoriole , how hard would it be to make Jenkins jobs filter on git diff changes? Could you do it?

**Comment by xoriole** [comment]
It is possible with conditional checks. Will require a script to output a boolean whether to do the Tests or not.

**Comment by devos50** [comment]
Is this issue fixed now? 🤔

**Comment by xoriole** [comment]
PR tests are run using Github actions now and the filters are set there. Closing this issue.
