### ISSUE TITLE
Bad colors in Ubuntu Dark theme with Pyinstaller-packed version of Tribler 

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#6114]
Ubuntu 20.04, dark theme enabled, packed version:
![image](https://user-images.githubusercontent.com/2509103/117973236-6b982c80-b32c-11eb-85ce-1f6c3cdfd74d.png)

Dev version, running from pycharm:
![image](https://user-images.githubusercontent.com/2509103/117973432-aef29b00-b32c-11eb-8a67-aa837be6d3b9.png)

As you can see, the screenshots look completely different.

**Comment by ichorid** [comment]
Seems like the QT version that we're packing with the Linux builds does not use the system themes. @sandip, do you have any idea of what happens here?

**Comment by xoriole** [comment]
@ichorid could be, I'm not sure. We're building on a non-GUI environment (ubuntu container) so likely no system themes are included and the default theme is being used.

Looking at the doc, seems we can set style to the application. That could be something to check out.

**Comment by ichorid** [comment]
> @ichorid could be, I'm not sure. We're building on a non-GUI environment (ubuntu container) so likely no system themes are included and the default theme is being used.
> 
> Looking at the doc, seems we can set style to the application. That could be something to check out.

I wonder if themes should be included at all. I would expect QT to use the system theme that is available at the system that runs the application.

**Comment by ichorid** [comment]
@xoriole , could you please try fixing this one?

**Comment by xoriole** [comment]
I tried building on my local machine, and it seems to styles are loaded correctly (at least for Ubuntu). It could likely be the builder is missing some QT GUI files. I'll update the builder. Since we're in 2021, we probably don't need to support 18.04 anymore.

**Comment by ichorid** [comment]
Closed by recent build machine changes by @xoriole :+1:
