### ISSUE TITLE
X11 forwarding not working

### ISSUE THREAD

**Issue by jberkh** [Tribler/tribler#6116]
#### Please, fill all relevant items: ####

- [X] I have read CONTRIBUTING.rst

- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Tribler 7.9.0
##### Operating system and version: #####
Ubuntu Server 20.04
##### Steps to reproduce the behavior: #####
Install Tribler on Ubuntu Server 20.04. 
Ssh to the machine w/ X11 forwarding
Run tribler

##### Expected behavior: #####
I hoped that it would open a Tribler window on my (local) computer

##### Actual behavior: #####
<pre>Starting Tribler...
/usr/share/tribler ~
Aborted (core dumped)
</pre>

##### Relevant log file output: #####
crash-report.log:
<pre>Fatal Python error: Aborted

Current thread 0x00007f2ce8ebb740 (most recent call first):
  File &quot;tribler_gui/single_application.py&quot;, line 26 in __init__
  File &quot;tribler_gui/tribler_app.py&quot;, line 25 in __init__
  File &quot;run_tribler.py&quot;, line 187 in &lt;module&gt;
</pre>

**Comment by qstokkink** [comment]
I can reproduce a core dump if I run Tribler _without X11 forwarding_:

```bash
Fatal Python error: Aborted

Current thread 0x00007f9ebf590740 (most recent call first):
  File "tribler_gui/single_application.py", line 26 in __init__
  File "tribler_gui/tribler_app.py", line 25 in __init__
  File "run_tribler.py", line 187 in <module>
```

```bash
INFO:__main__:Sentry has been initialised in normal mode
INFO:__main__:Root state dir: /home/quinten/.Tribler
INFO:__main__:Running in "normal" mode
INFO:tribler_gui:Load logger config: /home/quinten/.Tribler
[PID:29776] 2021-05-18 08:50:56,391 - INFO - tribler_core.dependencies(78) - Check for missing dependencies. Scope: both
[PID:29776] 2021-05-18 08:50:57,101 - INFO - tribler_core.check_os(226) - Check and enable code tracing. Process name: "gui". Log dir: "/home/quinten/.Tribler"
[PID:29776] 2021-05-18 08:50:57,102 - INFO - tribler_core.check_os(208) - Enable fault handler: "/home/quinten/.Tribler"
[PID:29776] 2021-05-18 08:50:57,102 - INFO - tribler_core.check_os(49) - Check environment
[PID:29776] 2021-05-18 08:50:57,103 - INFO - tribler_core.check_os(80) - Should kill other Tribler instances
[PID:29776] 2021-05-18 08:50:57,103 - INFO - tribler_core.check_os(88) - Old PID: -1. Current PID: 29776
[PID:29776] 2021-05-18 08:50:57,103 - INFO - tribler_core.check_os(54) - Check free space
[PID:29776] 2021-05-18 08:50:57,309 - INFO - TriblerApplication(23) - Start Tribler application. Win id: "triblerapp". Sys argv: "['/usr/share/tribler/tribler']"
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```

However, when I enable X11 forwarding Tribler runs just fine. This makes me believe that somehow your X11 forwarding is being blocked.

Could you verify that you can run other X11 applications?

On a side note, there seems to be a magic fix for some people when installing ` libxcb-xinerama0`.

**Comment by jberkh** [comment]
Thanks for your reply. I verified that X11 forwarding is working properly by running xclock and firefox over X11, both work fine.
I already had ```libxcb-xinerama0``` installed, and both reinstalling it or installing the -dev variant did not work for me.

It does seem that the program behaves exactly the same whether X11 forwarding is enabled or not, as if it can't recognize it being enabled (I get the same errors from my previous post in bash and crash-report.log with X11 disabled). How did you get that output from your second textbox? I could try to see if the output is the same for my situation.

**Comment by qstokkink** [comment]
Sorry about that omission: the second textbox contains the command-line output of running `/usr/share/tribler/tribler` in an interactive ssh session.

**Comment by jberkh** [comment]
I got it to work, finally. It seems the problem was that ```libqt5x11extras5``` was not installed. (Or one of the many dependencies that were installed with it.)

Thank you for your help!

**Comment by qstokkink** [comment]
You're welcome. Thanks for sharing the solution 👍
