### ISSUE TITLE
False-negative checks on a rare content

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#6131]
How to reproduce:
1. Open Tribler
1. Check the content of `fma_medium_april` channel (the content will be mostly "red")
1. Try to download the red content
1. The content will be downloaded successfully

![image](https://user-images.githubusercontent.com/13798583/119814847-2dce0300-beeb-11eb-8d55-19b98a648d44.png)
![image](https://user-images.githubusercontent.com/13798583/119819614-d9c61d00-bef0-11eb-9aeb-26a8c2ab90d6.png)

I see the described behavior on my test channel, but at the same time, I see this behavior on the content in other channels.

**Comment by ichorid** [comment]
DHT checks are unreliable. Good luck fixing this! :four_leaf_clover:

**Comment by drew2a** [comment]
Fixed by @kozlovsky in https://github.com/Tribler/tribler/pull/7286
