### ISSUE TITLE
[7.9.0] FileExistsError: '.Tribler' (in run_tribler > check_os.enable_fault_handler)

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#6157]
[WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\<...>\\AppData\\Roaming\\.Tribler'

[Here](https://github.com/Tribler/tribler/blob/e52c5aca43dbc4df3854334a2f5e9350f88120bd/src/tribler-core/tribler_core/check_os.py#L213):

```python
def enable_fault_handler(log_dir):
    """
    Enables fault handler if the module is available.
    """
    logger.info(f'Enable fault handler: "{log_dir}"')
    try:
        import faulthandler

        if not log_dir.exists():
            path_util.makedirs(log_dir)
```

Happened two times with a month interval. Not very often, probably we can ignore it. Looks like some weird race condition?

**Comment by qstokkink** [comment]
I'd vote for adding `exist_ok=True` to the `Path.mkdir()` call (in `path_util.makedirs()`).

This resolves any weird race conditions, even if they shouldn't occur.
