### ISSUE TITLE
“Could not create circuit, no first hop available”

### ISSUE THREAD

**Issue by da2x** [Tribler/tribler#6169]
##### Tribler version/branch+revision: #####
7.10.0

##### Operating system and version: #####
macOS 11.3

##### Steps to reproduce the behavior: #####
Download some torrents.

##### Expected behavior: #####
Torrents should download.

##### Actual behavior: #####
Every torrent works fine for about two minutes, then only intermittent activity on each every ten minutes or so.

##### Relevant log file output: #####

These messages repeated a thousand times over the course of a day. Maybe related? I’m curios why Tribler so frequently fails to establish circuits. Seems like an essential component that shouldn’t fail this often?

```
01:03:35,739 - TriblerTunnelCommunity(181) - Want 7 data circuits of length 3
01:03:35,739 - TriblerTunnelCommunity(247) - Creating a new circuit of length 3 (type: DATA)
01:03:35,740 - TriblerTunnelCommunity(277) - Look for a first hop that is not an exit node and is not used before
01:03:35,740 - TriblerTunnelCommunity(286) - Could not create circuit, no first hop available
01:03:35,740 - TriblerTunnelCommunity(184) - circuit creation of 7 circuits failed, no need to continue

01:03:36,583 - TriblerTunnelCommunity(452) - Creating introduction point
01:03:36,584 - TriblerTunnelCommunity(247) - Creating a new circuit of length 4 (type: IP_SEEDER)
01:03:36,584 - TriblerTunnelCommunity(277) - Look for a first hop that is not an exit node and is not used before
01:03:36,584 - TriblerTunnelCommunity(286) - Could not create circuit, no first hop available
```
https://github.com/Tribler/py-ipv8/blob/72c304f34891a9e963c444f473ce4f2868cfd711/ipv8/messaging/anonymization/community.py#L286

**Comment by qstokkink** [comment]
You may not be able to connect to others.

Could you enable Settings/DEBUG/Developer mode/Enable developer mode and then go to the Debug/IPv8/Overlays tab and screenshot the results? It should look something like this:

![Debug/IPv8/Overlays tab](https://user-images.githubusercontent.com/3630389/122718112-d1050480-d26c-11eb-834b-8e1c07884778.png)

**Comment by da2x** [comment]
> You may not be able to connect to others.

How do I troubleshoot this problem further? It seems to be a very frequently reoccurring problem, given the number of info messages in my log.

> screenshot the results

![tribler-overlay-stats](https://user-images.githubusercontent.com/1102886/122799081-9b3e3b00-d2c1-11eb-8c8c-5ce18eefc531.png)

**Comment by ichorid** [comment]
@egbertbouman , while are you still with us, could you please comment on this?

**Comment by qstokkink** [comment]
@da2x thanks for sharing. I don't see anything weird from your overall statistics. You are connected to others and seem to be interacting with them "normally". So basic networking is working, the problem lies somewhere else.

**Comment by egbertbouman** [comment]
To debug this further, we need to know how many circuits there are (`Debug/Tunnels/Circuits` tab) and to which peers we are connected (`Debug/Tunnels/Peers` tab).

**Comment by qstokkink** [comment]
After three years without further info and nobody else to reproduce this, I'll close this issue. If more details do become available, this issue can be reopened.
