### ISSUE TITLE
DNS leakage not plugged

### ISSUE THREAD

**Issue by da2x** [Tribler/tribler#6171]
Related to #5262 and #5628. cc/@ichorid cc/@egbertbouman

##### Tribler version/branch+revision: #####
7.10.0-RC2

##### Operating system and version: #####
Any.

##### Steps to reproduce the behavior: #####
1. Clean install of Tribler.
2. Run Wireshark or otherwise observe DNS queries
3. Start Tribler.

##### Expected behavior: #####
No torrent tracker related DNS queries.

##### Actual behavior: #####
Four tracker lookups in the first 30 seconds. Several more over time. (I’m not talking about the DHT bootstrap servers; just a random selection of trackers.)

Update: Five minutes after submitting this, I thought to check if there’s any tracker traffic too. Turns out there’s a lot of HTTP traffic to trackers further down in my traffic logs. I’m seeing the changes from #5628 are included in 7.10.0-RC2. Aren’t they supposed to be enabled by default?

##### Work around: #####
Disable the Torrent Checker and no more queries are sent out.

**Comment by ichorid** [comment]
@xoriole , could you please check this out? We have to postpone 7.10 release until we fix this.

**Comment by ichorid** [comment]
I checked it out and I see at least DNS queries directly from the host, while these should go through tunnels. @egbertbouman , could you please comment on this?

**Comment by egbertbouman** [comment]
At first glance, this looks like a `TorrentChecker` issue. I'll see if I can fix this.

**Comment by da2x** [comment]
@egbertbouman, I applied and tested the patches in #6180 locally. They do not appear to fix the issue. Tribler is still resolving DNS to all sorts of tracking servers even with no transfers in the download list. Disabling the Torrent Checker stops all these requests.

Please reopen the issue.

**Comment by egbertbouman** [comment]
Strange, it seems to fix the issue for me. Perhaps the version of libtorrent also plays a factor. I'm using libtorrent 1.2.0.

**Comment by da2x** [comment]
Here's what I found in Tribler logs from the same time that I saw the DNS requests to the domain mentioned in the log message:

```
02:34:21,687 - INFO - TorrentChecker(136) - Selected 50 new torrents to check on tracker: udp://open.demo ii.com:1337
02:34:51,689 - WARNING - TorrentChecker(151) - Got session error for URL udp://open.demonii.com:1337: udp tracker failed for url udp://open.demonii.com:1337 (error: request timed out)
```

**Comment by ichorid** [comment]
@da2x , I assume you're using the GIT version of Tribler. Could you please post the version of your Libtorrent? it is in your Debug panel:
![изображение](https://user-images.githubusercontent.com/2509103/123409196-354a0000-d5ae-11eb-929f-e0068e36ad51.png)

**Comment by ichorid** [comment]
For my version of Libtorrent (1.1.13), there is no leak too.

**Comment by da2x** [comment]
Libtorrent 1.2.3, same one that’s shipped in the release builds. I’ve tried using git master and I’ve tried applying the patches on top of 7.10-RC2 on Windows and macOS. It takes less than a minute after start-up before Tribler begins connecting to various trackers.

**Comment by ichorid** [comment]
@da2x , would you kindly try [this build](https://jenkins-ci.tribler.org/job/1-Click-Release/171/)? That's the latest one with @egbertbouman 's patches included. I've tested it on my Ubuntu, no leak :shrug: 

Also, could you please try running Tribler with a clean config dir. You can do it like this: `env TSTATEDIR=/tmp/foobar tribler`.   `TSTATEDIR` environment variable will force Tribler to change the default config directory.

**Comment by ichorid** [comment]
I've checked the [patched build](https://jenkins-ci.tribler.org/job/1-Click-Release/171/) in Windows VM. Wireshark shows no leaks.

**Comment by ichorid** [comment]
Related to https://github.com/arvidn/libtorrent/issues/6295

**Comment by egbertbouman** [comment]
Since the `TorrentChecker` doesn't use libtorrent to connect to trackers, which version of libtorrent you're using shouldn't matter.

**Comment by da2x** [comment]
I’m sorry to leave you guys hanging, I thought I had replied to this yesterday.  I’ve tested the indicated builds on macOS, Linux, and Windows 10. They work just fine. I’m not sure what I did wrong when applying the patches locally.
