### ISSUE TITLE
Improvement Request: Restructure of `tribler-core`

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#6177]
The current structure of `core` is definitely better than [7.3.0](https://github.com/Tribler/tribler/tree/release-7.3.0/Tribler/Core) but it is still far from perfection.
I'm almost "one-year-tribler-developer" but still confused with the navigation and with the purpose of some folders.

I want to suggest one small step further.

The structure might look like this:

```python
tribler_core
|
├ communities
|  ├ accounting
|  ├ tunnel
|  ├ popularity
|  ├ gigachannel
|  └ remote_query
|
├ database
|  ├ mds
|  └ ledger_zero
|
├ rest
|  ├ libtorrent
|  ├ channels
|  └ tunnels
|
├ components
|  ├ libtorrent
|  ├ category_filter
|  ├ resource_monitor
|  ├ torrent_checker
|  ├ trust_calculation
|  ├ torrent_checker
|  └ upgrade
|
└ utilities
```

Why `rest` placed outside communities or components? Because it represents the whole Core-API and should be easy to find for those who want to use it.

Why `database` placed outside of `mds`? Because it is one of the core Tribler's parts that has been used from several components and communities and deserves its place in a hi-level of the structure.

Feel free to comments on a structure itself or on naming in particular.
When we will reach a consensus it will take one day of my time to implement the changes.

**Comment by ichorid** [comment]
A couple of important notes:
 * First, there is more than a single set of ORM bindings: LedgerZero's ORM bindings are completely independent of MDS-related bindings. So, putting all the ORM bindings into a single dir will create a total mess.
 * Second, the [original idea behind the structure we're using now](https://github.com/Tribler/tribler/issues/4953) was to eventually support adding _modules_ to Tribler dynamically. 


In the end, it boils down to the classic question of "sort by type vs sort by function". Sort by type is the Unix's approach (`/bin`), while sort by function is the Windows's approach (`c:\Program Files`). The former better fits tight, cleanly designed systems, conservative systems with a limited scope of functionality. The latter is favoured by dynamic, highly extensible systems.
The Unix approach is about enforcing structure. The Windows approach is about isolating chaos.

Which one fits Tribler better at this point in development, I'm unable to tell :shrug:

**Comment by drew2a** [comment]
@ichorid I've added "ledger zero" and "mds" ORM-bindings to the example above.

**Comment by ichorid** [comment]
We had a live discussion with @drew2a , and I am now convinced that this restructuring will do more good for Tribler immediately than it will do harm to our future modularisation goal. :+1:

**Comment by ichorid** [comment]
I've got an even more radical idea: let's just refactor **everything** properly with [FastAPI+DependencyInjector](https://python-dependency-injector.ets-labs.org/examples/fastapi.html)
This combo will nicely solve all of our modularisation+testing+documentation+configuration problems. :tada: :rocket: :tada:

**Comment by drew2a** [comment]
The task is no longer relevant (after merging https://github.com/Tribler/tribler/pull/6206).
