### ISSUE TITLE
[Bug] [GUI] Deselecting all files in a torrent to manually select a few reselects all of them at seemingly random points

### ISSUE THREAD

**Issue by Scripter17** [Tribler/tribler#6213]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
7.10.0
##### Operating system and version: #####
Windows 10 20H2
##### Steps to reproduce the behavior: #####
Add a torrent, click "deselect all" and try manually selecting some of the files
##### Expected behavior: #####
Only the files I manually select will be selected
##### Actual behavior: #####
At random points every file is reselected for download
##### Relevant log file output: #####
N/A

**Comment by ichorid** [comment]
Reproduced with 7.10 by deselecting all items and then clicking on the "Download anonymously" checkbox. Apparently, the state of file selection checkboxes is reset on some actions within dialog.
