### ISSUE TITLE
tribler installer does not remember installation directory

### ISSUE THREAD

**Issue by kotenok2000** [Tribler/tribler#6221]
I have installed Tribler_7.10.0-RC2 at E:\Program Files\Tribler
when i installed Tribler_7.10.0 it tried to install to C:\Program Files\Tribler

#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Operating system and version: #####
Microsoft Windows [Version 10.0.19043.1083]

**Comment by kotenok2000** [comment]
Still happens when installing V7.11.0-RC2
Microsoft Windows [Version 10.0.22000.376]

**Comment by qstokkink** [comment]
By manually setting `Software\Tribler` in `HKCU` I managed to get our current (7.13) installer to recognize the install dir.

![regedit](https://github.com/Tribler/tribler/assets/3630389/c4001119-63ec-45ba-9ebf-a43e09cf734c)

This tells me that our current approach to recover the value works:

https://github.com/Tribler/tribler/blob/cbd15ef5a20e6d36b1c6353c34ac84dded9c8f1d/build/win/resources/tribler.nsi#L34

However, we should actively set this registry value upon successfully installing Tribler. It seems that the solution of #6244 came very close to this.
