### ISSUE TITLE
Torrent incomplete but showing 100% 

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#6229]
Reported by a forum user:
> my download is showing 100% when downloading/checking/seeding.
BUT if I click on the DL and look at details window it shows partial/incomplete files. I have done a force check, several times.
I did not notice the details window at first.
The progress bar in the main downloads showed 100% and that was good. I could not figure out why the files were corrupt for days.
Finally I loaded the torrent in another client and saw the problem. adding screen shots.
the only difference in those screen shots is 10 seconds it takes for the torrent to start seeding. it is seeding very incomplete files.
searched for progress 100percent but files incomplete. 

![bla1](https://user-images.githubusercontent.com/2509103/126066649-b5d50225-d279-48b9-85b4-824b63191307.png)
![bla2](https://user-images.githubusercontent.com/2509103/126066650-1eb31188-41b1-41a1-9ff6-e24f68cebe92.png)

**Comment by drew2a** [comment]
Could be related:
- #7318
- #5930

**Comment by qstokkink** [comment]
This looks like a GUI issue, which should be resolved with the new GUI implementation. We can reopen this if it is still occurring in the new code.

**Comment by AngryRoleplayer** [comment]
I have the same problem by the way. A LOT of incomplete files.

**Comment by qstokkink** [comment]
We hope to have that fixed for you in the upcoming release. `8.0.0` should be releasing reasonably soon.
