### ISSUE TITLE
[Feature Request] Max parallel downloads

### ISSUE THREAD

**Issue by ilko-k** [Tribler/tribler#6234]
Actually, we can only restrict the bandwidth by limiting the speed or the maximum connections per download, but not the number of simultaneous downloads itself. TBH, it's quite surprising for such a software. I can't imagine a download manager without this ability.

It's a great software and I'd like to use Tribler as my main torrent manager, but I can't for the moment because of this simple lacking. A lot of people don't have a high speed internet connection like me so we have to play with it.

**Comment by drew2a** [comment]
@ilko-k thank you for your request! 

We previously had a similar one:
- #3724

Therefore I'm closing the current issue as a duplicate. Please, follow the #3724.
