### ISSUE TITLE
Wrong target peers for DiscoveryCommunity

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#6245]
My comment on https://github.com/Tribler/tribler/pull/6206#discussion_r686574149 got ignored and the PR got merged anyway. So, I'll repost it because this is a decently severe issue.

https://github.com/Tribler/tribler/blob/a15533049ec73a48727e8c784180d9affe2357bb/src/tribler-core/tribler_core/components/implementation/ipv8.py#L105-L108

The parameterization of the `RandomWalk` is wrong. This is an incorrect port of:

https://github.com/Tribler/tribler/blob/1a49341fe739a81f469e11acb37ab883d53f8e60/src/tribler-core/tribler_core/modules/community_loader.py#L77

[The default value of the `target_peers` argument to `walk_strategy` is `20`](https://github.com/Tribler/py-ipv8/blob/master/ipv8/loader.py#L161), not `INFINITE`. The correct port would be:

```python
ipv8.strategies.append((RandomWalk(community), 20)) 
```

This error is actually pretty bad for your network topology. Funny enough, exactly this is the last example I gave [in this post](https://github.com/Tribler/py-ipv8/issues/979#issuecomment-896643760). This creates strong cliques in your network and may lead to (hopefully temporary) overlay network partitions (not good!).

**Comment by kozlovsky** [comment]
@qstokkink thank you for checking this! We were a bit in a rush yesterday to make a merge.

**Comment by qstokkink** [comment]
> We were a bit in a rush yesterday to make a merge.

Good to know; thanks for informing me. I'll double-check the other changes as well then.
