### ISSUE TITLE
Scripts to run Tribler need to be fixed

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#6247]
Yesterday a [massive refactoring of the Tribler core](https://github.com/Tribler/tribler/pull/6206) was merged into the main branch. The goal of refactoring was to split Tribler code into components that can be activated and tested independently and in different combinations using dependency injection.

The refactoring was not completely finished yet: while all tests are passed successfully, only the `run_tribler.py` script was updated. The other scripts, such as `run_tunnel_helper.py` or `run_tribler_headless.py`, still need to be rewritten according to the new paradigm.

While conceptually it was better to fix all these things in #6206 PR itself, it was decided to merge it right now to avoid massive "rebase hell". So, now I plan to fix the remaining scripts in this separate issue.

**Comment by qstokkink** [comment]
These scripts no longer exist and this issue is no longer relevant.
