### ISSUE TITLE
Parts of the Tribler UI not visible when maximizing window with 125 % UI scaling

### ISSUE THREAD

**Issue by da2x** [Tribler/tribler#6253]
##### Tribler version/branch+revision: #####
7.10

##### Operating system and version: #####
Windows 11.22000.120 and Windows 10.

##### Steps to reproduce the behavior: #####
1. Set Windows UI scaling to 125 % (default on pretty much all 14″ laptops.)
2. Maximize the Tribler window using the maximize button on the title bar.

##### Actual behavior: #####
The window scales ×2 instead of ×1,25 in a ×1,25 window. This causes UI controls like Settings, Token balance, Start/Stop/Delete torrents, and others to be pushed outside the visible view.

![Tribler scaling issues.](https://user-images.githubusercontent.com/1102886/129232608-81890c74-689b-4e3f-bcf2-62a85a45e135.png)

##### Expected behavior: #####
All controls should remain visible.

Ideally, Tribler should scale ×1,25 and not ×2, but that is less important than all the controls remaining visible.

##### Other notes: #####

This may be the same root cause as the more serious issue #6243.

**Comment by qstokkink** [comment]
I'll label this as "wontfix", just like #5155, because it is **likely** (but not quite assured) to be superseded by https://github.com/Tribler/tribler/issues/7736 soon.

**Comment by qstokkink** [comment]
Tribler now has a web-based front end and this issue is no longer relevant.
