### ISSUE TITLE
Session has `failfast` configuration attribute

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#6255]
The `Session` now has a `failfast` boolean, which is used to configure the behavior of only the `Session.start()` method and not referenced externally or changed after the `Session` has initialized. Therefore, it should not be bound as a `Session` attribute.

https://github.com/Tribler/tribler/blob/5cb1ee094e5312ede323b4bb1166dea85c379768/src/tribler-core/tribler_core/components/base.py#L40-L49

If there is supposed to be a stable reference to this configuration for external reference, the `failfast` should be part of the `TriblerConfig`. If it is only to be used as it is now (just internally in `Session.start()`), it should be an argument to the `Session.start()` method.

**Comment by kozlovsky** [comment]
I agree with this. An argument of the `Sesstion.start()` method looks better. It may be moved to configuration later if the need arises.
