### ISSUE TITLE
[main] Use `MockIPv8` key injection

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#6273]
The current version of IPv8 on the `main` branch supports key injection for `MockIPv8`. The following workarounds are no longer necessary:

https://github.com/Tribler/tribler/blob/a15533049ec73a48727e8c784180d9affe2357bb/src/tribler-core/tribler_core/modules/tests/bandwidth_accounting/test_bandwidth_endpoint.py#L26-L27

https://github.com/Tribler/tribler/blob/a15533049ec73a48727e8c784180d9affe2357bb/src/tribler-core/tribler_core/modules/tests/bandwidth_accounting/test_community.py#L26-L27

**Comment by qstokkink** [comment]
I still see this in the code base after the fix:

https://github.com/Tribler/tribler/blob/9eb985aafa5177ec7a3cc2d132eefc61701ce078/src/tribler-core/tribler_core/components/bandwidth_accounting/tests/test_community.py#L30-L31

Was this forgotten? Or was it necessary to keep this?

**Comment by drew2a** [comment]
@qstokkink yes it is forgotten. I thought that everything inside `TestBase`(TestBandwidthAccountingCommunity) is correct. 

I'll fix it soon.
