### ISSUE TITLE
[main] TriblerTunnelCommunity randomly removing peers and imbalancing connections

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#6285]
https://github.com/Tribler/tribler/blob/5cb1ee094e5312ede323b4bb1166dea85c379768/src/tribler-core/tribler_core/components/implementation/tunnels.py#L52

The above removes random peers from the `TunnelCommunity`. This is extremely bad for an overlay that wants longer term stable connections. Furthermore, this has replaced the `GoldenRatioStrategy` that was here before:

https://github.com/Tribler/tribler/blob/cdedbec0c69af1c5568b967697d449ef13a1945a/src/tribler-core/tribler_core/modules/ipv8_module_catalog.py#L156

This `GoldenRatioStrategy` is responsible for making sure there is a balance between the connected exit nodes and normal nodes. In other words: we're now doing the complete opposite.

As this is the polar opposite of what this code should be doing and can really screw exit node discovery, I've tagged this as a "blocker".

**Comment by firestorm99** [comment]
Since when does this behaviour exist? 
With at least 7.10 the network experience seems to have suffered, especially for torrents not found over the integrated search..

**Comment by qstokkink** [comment]
@firestorm99 this was still correctly implemented back in `7.10` and this issue has to do with how easily anonymization can be established. 

What you are describing seems to be something different. Could you open a new issue and describe in more detail what part of your network experience is suffering? Is your search giving less results, are you using a large amount of bandwidth, ...? If you give us enough information to reproduce your issue we can fix it.
