### ISSUE TITLE
[main] Stolen code without attribution

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#6289]
https://github.com/Tribler/tribler/blob/3343308ff7aacb184b84255a8eb7c6eb1714ebda/src/tribler-core/tribler_core/utilities/utilities.py#L22-L42

This code is copied from this SO post: https://stackoverflow.com/a/29368642

One of the conditions of using this code from SO is attribution (`CC BY-SA 3.0`, see https://creativecommons.org/licenses/by-sa/3.0/). We should add a comment here that shows where this code comes from and who made it.

**Comment by drew2a** [comment]
It is strange. 

Regarding GitHub history the author of these changes is me.
But, I did not introduce this magic with `@froze_it`.

@ichorid do you know anything about it?

**Comment by ichorid** [comment]
Yep, I copy-pasted it from SO and forgot to attribute it like we usually do, because I was using the wrapper mostly as a convenience tool to detect errors during development. I was not sure it will stay. It proved to be a useful tool over time.
