### ISSUE TITLE
Download progress bar does not get removed in search results when deleting an existing download

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#6303]
Steps to reproduce:
- Start download something from the search results - the download starts and the download progress bar appears.
- Remove the just-added download.
- Go back to the search results.

The download progress bar remains in the search results list, giving a false impression that the download has not correctly been stopped.

**Comment by drew2a** [comment]
This issue probably related to #5886

**Comment by ichorid** [comment]
duplicate of #5886
