### ISSUE TITLE
Fix the validation experiments

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#6309]
We run a number of [validation experiments](https://jenkins-ci.tribler.org/job/validation_experiments/) that run every midnight. After merging #6206 and [extensive refactoring of Gumby](https://github.com/Tribler/gumby/pull/489), these validation experiments are broken.

When these validation experiments have been fixed, it would be nice to have an additional GitHub command (e.g., "validate") that runs these validation experiments with the PR code. Then generate a report containing (granular?) details of Tribler stability.

Our [validation experiments](https://jenkins-ci.tribler.org/job/validation_experiments/) seem to be broken on a compilation error (except for `validation_experiment_libtorrent_compatibility` and `validation_bootstrap`).

This looks like the main cause:

```
./boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
 # include <pyconfig.h>
                       ^
```

**Comment by devos50** [comment]
@kozlovsky To make sure that the virtual env can run Tribler, I had to add the following requirements to the `build_virtualenv.sh` script:

```
faker
sentry_sdk
decorator
anyio
```

**Comment by drew2a** [comment]
@kozlovsky is it fixed?

**Comment by synctext** [comment]
Please fix this. Gumby, DAS6, and CI should not break.

**Comment by qstokkink** [comment]
Validating has now been moved into the PR process.
