### ISSUE TITLE
No thumbnail available shown in start-screen

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/tribler#632]
In the start screen, i'm seeing the "No thumbnail available" thingy in the vertical scrolling thumbnail list.
Could this be caused by a failed swift-thumbnail download?

**Comment by whirm** [comment]
We've disabled thumbnails so this doesn't need attention until we enable it again.

**Comment by devos50** [comment]
This bug is not relevant anymore since we have no thumbnails in the new GUI.
