### ISSUE TITLE
[Components] Suspicious self.release(RESTComponent)

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#6362]
During the refactoring (#6335), we found few suspicious places that can indicate potential problems:

https://github.com/Tribler/tribler/blob/2fa959e8c48a81693eb8239b24db70b5ec57f203/src/tribler-core/tribler_core/components/implementation/gigachannel.py#L59

https://github.com/Tribler/tribler/blob/2fa959e8c48a81693eb8239b24db70b5ec57f203/src/tribler-core/tribler_core/components/implementation/gigachannel_manager.py#L39

https://github.com/Tribler/tribler/blob/2fa959e8c48a81693eb8239b24db70b5ec57f203/src/tribler-core/tribler_core/components/implementation/ipv8.py#L132

https://github.com/Tribler/tribler/blob/2fa959e8c48a81693eb8239b24db70b5ec57f203/src/tribler-core/tribler_core/components/implementation/libtorrent.py#L57

https://github.com/Tribler/tribler/blob/2fa959e8c48a81693eb8239b24db70b5ec57f203/src/tribler-core/tribler_core/components/implementation/metadata_store.py#L63

https://github.com/Tribler/tribler/blob/2fa959e8c48a81693eb8239b24db70b5ec57f203/src/tribler-core/tribler_core/components/implementation/torrent_checker.py#L45

Why they are suspicious? Because they call `self.release(RESTComponent)` manually, but this operation should be performed automatically during `Session.shutdown()`:

```python
class Session:
    async def shutdown(self):
        await gather(*[create_task(component.stop()) for component in self.components.values()])


class Component:
    async def stop(self):
        self.logger.info("Waiting for other components to release me")
        await self.unused.wait()
        self.logger.info("Component free, shutting down")
        await self.shutdown()
        self.stopped = True
        for dep in list(self.components_used_by_me):
            self._release_instance(dep)
        self.logger.info("Component free, shutting down")
    
    async def release_component(self, dependency: Type[T]):
        dep = dependency.instance()
        if dep:
            self._release_instance(dep)

    def _release_instance(self, dep: Component):
        assert dep in self.components_used_by_me
        self.components_used_by_me.discard(dep)
        dep.in_use_by.discard(self)
        if not dep.in_use_by:
            dep.unused.set()

```

**Comment by kozlovsky** [comment]
Fixed in #6381 (a5c774a2)
