### ISSUE TITLE
[main] column_position.get in ChannelContentModel incorrectly used

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#6368]
In the GUI model, we are occasionally using code like:

```
self.column_position.get('name', -1)
self.column_position.get('votes', -1)
...
```

For example, in the `data` and `headerData` methods of the `ChannelContentModel` class. However, `self.column_position` is defined as:

```
self.column_position = {name: i for i, name in enumerate(self.columns_shown)}
```

And `self.columns_shown` is defined as:

```
columns_shown = (Column.ACTIONS, Column.CATEGORY, Column.NAME, Column.SIZE, Column.HEALTH, Column.UPDATED)
```

These are all Enums, so the key of the `self.columns_shown` dictionary should also be an Enum. Adding a few print statements confirms that many of the calls to `self.column_position.get` return `None` because we are using the wrong key. Instead, we should be calling this method as follows:

```
self.column_position.get(Column.NAME, -1)
self.column_position.get(Column.VOTES -1)
...
```

**Comment by ichorid** [comment]
:man_facepalming:
