### ISSUE TITLE
Speed up `PR_clone_tribler`

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#6370]
Currently our PR clone job (the Jenkins job that pulls in all of the files of a GitHub Pull Request) takes roughly 3 minutes. This hampers development and should be sped up.

One possible easy solution is to use a zip or tarball of the artifacts to share them between Jenkins jobs.

It is also possible that the exclude list of the `PR_clone_tribler` can be further optimized. At the moment we only remove `**/.git/modules/**,**/.git/objects/**` (note that removing the entirety of `**/.git/**` is very fast, but it will break our PR testers).

**Comment by drew2a** [comment]
This issue is no longer relevant as we use GitHub Actions for PR checks.
