### ISSUE TITLE
Tribler continuously using ~50% CPU usage in GUI test mode

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#6375]
I noticed on my Mac that the Tribler process continuously uses around 50% CPU usage when running idle. I suspect that the CPU usage originates from the core process as the 'main' process uses only 1% CPU usage.

<img width="1275" alt="Schermafbeelding 2021-09-28 om 09 14 12" src="https://user-images.githubusercontent.com/1707075/135040951-aa6c55f7-3e98-4fc9-8cf0-72ce793ea015.png">

**Comment by drew2a** [comment]
Just for information, the list of components for normal mode and for GUI test mode:
https://github.com/Tribler/tribler/blob/338fd0b94f6dcc95aeae806dc9ede50e30ee8d10/src/tribler-core/tribler_core/start_core.py#L46-L87

**Comment by qstokkink** [comment]
Tribler now has a web-based front end and this issue is no longer relevant.
