### ISSUE TITLE
Content appearing and disappearing when refreshing a channel

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#6395]
I noticed that when going to a channel in Tribler and refreshing it by clicking on the channel name in the breadcrumb navigator, sometimes content appears and disappears. While this is expected (since Tribler can discover new content), sometimes the amount of content is changing significantly. Note that it requires like 20+ or 30+ refreshes sometimes to trigger this behavior.

Below are two screenshots that were taken within the same channel. Refreshing it occasionally gives different content. Note that sometimes, item A in the first screenshot is not present in screenshot B, hinting that this might be a bug somewhere.

<img width="1074" alt="Schermafbeelding 2021-09-30 om 12 20 01" src="https://user-images.githubusercontent.com/1707075/135470145-09df6f91-4eb4-4213-b6d7-cb20e05e6e05.png">

<img width="1074" alt="Schermafbeelding 2021-09-30 om 12 20 06" src="https://user-images.githubusercontent.com/1707075/135470157-eb0459e8-35cb-4783-96df-714e8c295caa.png">

**Comment by devos50** [comment]
I have the impression that #6415 even makes it easier to reproduce. Anyway, in like 20 refreshes of one of the most popular channels in Tribler, I get random content in like 5 refreshes.

**Comment by ichorid** [comment]
I had to click it about 20-30 times to get to see the thing :shrug: . I guess it is highly dependent on network and PC performance.
