### ISSUE TITLE
Icons on Popular Torrents tab broken

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#6440]
PyQt5 version: 5.15.4
Output of `print(QFont().defaultFamily())`: `DejaVu Sans`

This is how I see the icons on the Popular Torrents tab (Ubuntu 20.04):

![popular torrents](https://user-images.githubusercontent.com/3630389/136571670-9043bf9c-e239-4225-9e24-40a9c92232ce.png)

**Comment by qstokkink** [comment]
@devos50 I don't have my Windows development machine on hand: I can check Windows monday.

**Comment by devos50** [comment]
Thanks for testing! Maybe we could use a different font for the widgets that render emojis (either through stylesheets or programmatically using `QFont`)?

**Comment by qstokkink** [comment]
I'd be happy to try that, if someone can point me in the right direction. Where should the code be changed to target the correct widgets?

**Comment by qstokkink** [comment]
Did some digging. Got one step further using this patch:

```patch
diff --git a/src/tribler-gui/tribler_gui/qt_resources/torrents_list.ui b/src/tribler-gui/tribler_gui/qt_resources/torrents_list.ui
index 08826e8f5..c47ecacb9 100644
--- a/src/tribler-gui/tribler_gui/qt_resources/torrents_list.ui
+++ b/src/tribler-gui/tribler_gui/qt_resources/torrents_list.ui
@@ -613,6 +613,11 @@ QToolButton{border:none;margin-left:16px;}</string>
           <verstretch>0</verstretch>
          </sizepolicy>
         </property>
+        <property name="font" >
+         <font>
+          <family>Noto Color Emoji</family>
+         </font>
+        </property>
        </widget>
       </item>
       <item>
diff --git a/src/tribler-gui/tribler_gui/widgets/tablecontentdelegate.py b/src/tribler-gui/tribler_gui/widgets/tablecontentdelegate.py
index 073a62afe..a2bb2edde 100644
--- a/src/tribler-gui/tribler_gui/widgets/tablecontentdelegate.py
+++ b/src/tribler-gui/tribler_gui/widgets/tablecontentdelegate.py
@@ -557,6 +557,8 @@ class CategoryLabel(QObject):
 
         lines = QPen(QColor("#B5B5B5"), 1, Qt.SolidLine, Qt.RoundCap)
         painter.setPen(lines)
+        from PyQt5.QtGui import QFont
+        painter.setFont(QFont("Noto Color Emoji"))
 
         text_flags = Qt.AlignHCenter | Qt.AlignVCenter | Qt.TextSingleLine
         text_box = painter.boundingRect(option.rect, text_flags, self.category)
```

![preview](https://user-images.githubusercontent.com/3630389/137903287-835de7b1-12aa-437a-aa7b-4f6cbe8f9e69.png)

This changes the only the icons/emojis in the channels (without affecting the font of other text). However, this patch does affect the text in the dropdown category filter.
