### ISSUE TITLE
Hard to navigate through search results

### ISSUE THREAD

**Issue by grimadas** [Tribler/tribler#6450]
<img width="888" alt="image" src="https://user-images.githubusercontent.com/5897440/137126595-5f5e2901-0b1a-42f4-9a24-cfc5a441b007.png">

The search results now are not very usable. 
1) They lack context. Where is the item from, descriptions, images. Anything that can help to distinguish. 
2) The items in the list are to close to each other. As a result for me this reads like one giant blob of text.

Suggestions:
- On click - expand the item, give context, then allow to download.  
- Consider different way to organise and present the data. For example, grid like structure. Items grouped by Category, Channels, or Tags.

**Comment by qstokkink** [comment]
Tribler now has a web-based front end and this issue is no longer relevant.
