### ISSUE TITLE
Customized checkbox not visible in Windows GUI tests

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#6459]
It seems that the customized checkbox introduced in #6449 is not visible in Windows.

**On Mac:**
![screenshot_add_torrent_url_startdownload_dialog_files-2](https://user-images.githubusercontent.com/1707075/137523539-b9a37583-9b83-467f-a945-ab098f239c93.jpg)

**On Windows:**
![screenshot_add_torrent_url_startdownload_dialog_files](https://user-images.githubusercontent.com/1707075/137523555-d3285368-c292-4ff8-9c75-28666658ece1.jpg)

(screenshots taken from the GUI tests)

I'm not sure about Linux since we are not running GUI tests on that platform.

**Comment by ichorid** [comment]
That is thrice funny given how I only apply the styles to the table widget itself...

**Comment by ichorid** [comment]
> 
> Maybe someone with quick access to a Windows dev environment could help out here?

That would be most unfortunate :facepalm: 

I believe we can still fix it by inverting slashes to Unix style on Windows:
https://stackoverflow.com/questions/26121737/qt-stylesheet-background-image-from-filepath

As an alternative, we can always pack the images as QT resources, though that's more hassle.
https://stackoverflow.com/questions/4458201/unable-to-set-the-background-image-in-qt-stylesheet
