### ISSUE TITLE
Segmentation fault detection infrastructure and burn-in testing

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#646]
Build an Jenkins-based test for running Tribler for a week. Plus if a seg-fault occurs we should have full debug symbols available.

Could be a duplicate of #448. There has been a "Segmentation fault (core dumped)" occurring occasionally with various code versions. This might be in our torrent-collecting code wrapping BEP9 of Libtorrent. It happened after 4 days of running the code of commit bc58eebee2dbf13194df4dd64216434f6f1224a6. 
![tribler_6 3pre_segmentation_fault_9june14](https://cloud.githubusercontent.com/assets/325224/3241589/d2b9fe1e-f13e-11e3-9784-44c52023d709.png)

**Comment by synctext** [comment]
We should have full debug symbols available when Libtorrent crashes.
After 2 years, we now have the 1 week experiment, but does not include regular Debian ISO download to trigger sef faults.

**Comment by devos50** [comment]
I've spent some time on this and made the following changes:
- extended the application tester with a resource monitor and download monitor
- created various scripts to plot resource usage history
- added various flags to better control the application tester
- made it possible to run the application tester from Jenkins, for a pre-defined time

Running the application tester and plotting resource usage history is as easy as running the following commands (on Mac):

```
python main.py "/Applications/Tribler.app/Contents/MacOS/tribler" --duration 1800 --monitordownloads 10 --monitorresources 60

Rscript scripts/downloads.r
Rscript scripts/resources.r
```

Output of a two-minute run: https://jenkins-ci.tribler.org/job/tribler_application_tester/job/tribler_application_tester_mac/8/

**Comment by devos50** [comment]
Update: Our windows testing machine is now also connected to Jenkins. https://jenkins-ci.tribler.org/job/tribler_application_tester/job/tribler_application_tester_win64/

**Comment by synctext** [comment]
Big achievement! We now have a stable soak test, runs for 6h every midnight.
https://jenkins-ci.tribler.org/job/Deployment-Tests/job/Run_Tribler_Release/
