### ISSUE TITLE
Build script should have a step for installing requrements.txt

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#6518]
Our build script should have a step for installing `requirements.txt` from https://github.com/Tribler/tribler/blob/main/src/requirements.txt

```python
python -m pip install --upgrade -r requirements.txt
```

In case of failure, the build process should be aborted.

**Comment by devos50** [comment]
On our development machines, we use system libraries. I think it would be nice if we add a check if all dependencies are available. We might also consider building a virtual env and sourcing PyInstaller from that. That would make the build process much more producible. However, building Tribler is a task that does not happen that often - usually we build it when we need to debug a feature in a frozen environment or when we are close to a release.

Also, note that libtorrent is not available as a package in PyPi so it should be compiled from source, which can be a complicated task, especially on Windows.

**Comment by xoriole** [comment]
Resolved by PR: https://github.com/Tribler/tribler/pull/6534
