### ISSUE TITLE
Snyk produces three error reports instead of just one.

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#6520]
![image](https://user-images.githubusercontent.com/13798583/140069943-851abf7f-2d33-4a0b-a0a4-1e0d9a4266b5.png)

**Comment by ichorid** [comment]
:facepalm:

**Comment by ichorid** [comment]
Deleted my hooks from Snyk

**Comment by drew2a** [comment]
Seems that hooks are still presented https://github.com/Tribler/tribler/pull/6537:
![image](https://user-images.githubusercontent.com/13798583/140935930-736dd52a-f3e2-4430-abd1-98d3bd003f1b.png)

**Comment by xoriole** [comment]
It seems deleting the project is not sufficient when the project is added via multiple organizations with access. Now, I have deleted all personal references from this article. Hopefully, it works now:
https://support.snyk.io/hc/en-us/articles/360000897837-How-do-I-remove-a-project-snapshot-manifest-file-from-Snyk-

**Comment by drew2a** [comment]
Yes, it seems to be working.

@xoriole reference has been removed
@ichorid reference still presented

![image](https://user-images.githubusercontent.com/13798583/141098975-8e8baf05-3a5b-440d-b80f-7a6440565dcb.png)

**Comment by ichorid** [comment]
@xoriole was right - I had to remove numerous copies of the project references from Snyk.

**Comment by drew2a** [comment]
The check is still in PR

**Comment by ichorid** [comment]
Clicking on the Snyk report link produces 404. I guess it is some kind of cache or something...

**Comment by ichorid** [comment]
Let's see how it fares on a different PR?

**Comment by drew2a** [comment]
@ichorid seems to be fixed 🎊 in https://github.com/Tribler/tribler/pull/6540
![image](https://user-images.githubusercontent.com/13798583/141115887-c7611f89-9029-4b26-bd33-8a02fed2666d.png)
