### ISSUE TITLE
Add new requirements to snyk

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#6523]
There are three new `requirements.txt` that have to be added to snyk:

https://github.com/Tribler/tribler/blob/main/src/tribler-common/tribler_common/requirements.txt
https://github.com/Tribler/tribler/blob/main/src/tribler-core/tribler_core/requirements.txt
https://github.com/Tribler/tribler/blob/main/src/tribler-gui/tribler_gui/requirements.txt

![image](https://user-images.githubusercontent.com/13798583/140071047-229a9764-6c70-4101-8442-8cce39a7d401.png)

**Comment by xoriole** [comment]
Core and GUI requirements.txt are already covered in Snyk. Tribler-common requirements.txt is empty so it is ignored.

<img width="1088" alt="Screenshot 2021-11-29 at 13 17 28" src="https://user-images.githubusercontent.com/1442867/143866803-2226b151-66fb-4e96-adb0-ba2932e59b49.png">
