### ISSUE TITLE
Clicking anywhere on the tags line opens "suggest tags" dialog

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#6531]
Clicking anywhere in the red zone opens the "suggest tags" dialog. This is unintuitive and extremely irritating
![bumb](https://user-images.githubusercontent.com/2509103/140559607-9efd0caf-aaac-4ff2-b70e-2ac48d708fc1.png)

**Comment by devos50** [comment]
IIRC, this was something we decided on in an early stage of the the design process. I will discuss it further on Monday.

**Comment by ichorid** [comment]
Well, this one is really annoying. I see an empty space and click on it, expecting the selection to change. Instead, tags dialog opens :shrug: .
