### ISSUE TITLE
Anonymous seeding and rewards experiments

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#655]
Create a simple operational system and expand.
The most based running code is 1 seeder for 1 file and 1-hop proxies.

Functionality: streaming Darknet
Outcome: running DAS4/Tribler/Gumby code + nice pictures for msc thesis
![design_hidden_seeding_experiment](https://cloud.githubusercontent.com/assets/325224/3290034/94dac50e-f573-11e3-854a-fa164bb8bc93.png)

Several proxies with known hard-coded IP addresses mean that Libtorrent is seeding via multiple addresses. This is impossible. Possible solution is creating multiple Libtorrent sessions, each configured with their own outgoing tunnel/proxy and external IP.

Expand basic scenario with:
- DHT-based discovery of introduction/rendezvous peers
- TOR hidden service protocol
- anonymous 3-hop downloads
- end-2-end encryption and 3-hops seeding
- 100 swarms balanced seeding
- hop-by-hop proof-of-work credits
- proxy fairness and priorities (pre-emption and starvation of freeriders?)
- connectability of introduction/rendezvous peers

**Comment by synctext** [comment]
@rjruigrok Almost done :-) ?

**Comment by rjruigrok** [comment]
Of course! :-)

Op donderdag 2 juli 2015 heeft Johan Pouwelse <notifications@github.com>
het volgende geschreven:

**Comment by devos50** [comment]
@synctext is this one complete?

**Comment by qstokkink** [comment]
This has been done for years now.
