### ISSUE TITLE
test_drop_silent_peer timeout

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#6575]
`test_drop_silent_peer`'s timeout it 5s, while the test takes 2.5 seconds on a pretty fast machine. On a loaded server the test can take even longer, resulting in timeout.
We should either increase the timeout, or simplify the test (preferably).

**Comment by qstokkink** [comment]
If you want to shorten timeouts of caches, I'd recommend looking into using `passthrough()`: https://py-ipv8.readthedocs.io/en/latest/basics/testbase_tutorial.html#using-the-requestcache
