### ISSUE TITLE
FreePortNotFoundError on Windows 11

### ISSUE THREAD

**Issue by dertuxmalwieder** [Tribler/tribler#6579]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

7.10.0

##### Operating system and version: #####

Windows 11 Build 22000.318

##### Steps to reproduce the behavior: #####

Reboot Windows 11 to get the latest update without exiting Tribler first.

##### Expected behavior: #####

Tribler can be started,

##### Actual behavior: #####

![tribler_2021-11-24_01-25-16](https://user-images.githubusercontent.com/125629/143149457-305b7368-b752-4eeb-b526-c6cc01bcf647.png)

I don't know how to fix that without losing everything again.

**Comment by ichorid** [comment]
Thanks for reporting!
We will release 7.11 in a couple of days, that one contains deep refactorings of port allocation methods that should help with this kind of problems.

**Comment by dertuxmalwieder** [comment]
Will there be an RC?

**Comment by ichorid** [comment]
Just follow the forum and "Releases" page

**Comment by ichorid** [comment]
https://github.com/Tribler/tribler/releases/tag/v7.11.0-RC1 :wink:

**Comment by dertuxmalwieder** [comment]
That seems to fix the issue, Tribler starts again. Great! Thank you.
