### ISSUE TITLE
Tribler logging systems need fixes/improvements.

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#6581]
Currently, the logging system has the following problems:
1. Incorrect configuration of stdout/stderr handlers: log messages with WARNING level are silenced and appear neither in stdin nor stdout (discovered by @ichorid).
2. Upgrader configuration is incorrect - the configuration is placed in `tribler_core/logger.yaml`, but the config file used with upgrader is `tribler_gui/logger.yaml`.
3. We have several logger config files with similar settings, and sometimes it is hard to understand which file should be modified.
4. The logger config is overcomplicated, and some settings are actually not used.
5. The code for logging setup is duplicated in GUI and Core with minimal changes.
6. GUI does not separate stdout/stderr output received from Core and redirects everything to stdout.

**Comment by ichorid** [comment]
Note that indentation introduced in https://github.com/Tribler/tribler/pull/6567 is applied inconsistently for some reason.

```

	[PID:25100] 2021-11-25 10:40:59,170 - INFO - PopularityCommunity(13) - Init. Settings: enabled=True cache_dir='health_cache'.
	[PID:25100] 2021-11-25 10:40:59,245 - INFO - RESTManager(134) - Started HTTP REST API: http://localhost:52194
[PID:25060] 2021-11-25 10:40:59,260 - INFO - TriblerGUI(128) - Will connect to events endpoint
	[PID:25100] 2021-11-25 10:40:59,335 - INFO - Socks5Connection(99) - Client has sent METHOD REQUEST
[PID:25100] 2021-11-25 10:40:59,335 - INFO - Socks5Connection(181) - Accepting UDP ASSOCIATE request to 127.0.0.1:50376 (BIND addr 0.0.0.0:0)
[PID:25100] 2021-11-25 10:40:59,714 - INFO - TriblerTunnelCommunity(247) - Creating a new circuit of length 1 (type: DATA)

```
