### ISSUE TITLE
There are three licenses in the Tribler repo instead of just single one

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#6590]
There are three licenses in the Tribler repo:

![image](https://user-images.githubusercontent.com/13798583/143585712-1023f412-9416-4cc9-b87d-74e7e7e17cd3.png)

Which is ambiguous for users and hard to maintain for developers.

Probably we should merge them and use just a single one.

**Comment by dertuxmalwieder** [comment]
Maybe, while cleaning up the license files, it would also make sense to add license headers to the source code files so any ambiguity is impossible? (There is no reason to *not* have them.)

**Comment by drew2a** [comment]
@dertuxmalwieder, are you suggesting we add license headers to each file in our source code?

**Comment by dertuxmalwieder** [comment]
@drew2a At least those files that should be put under the (L)GPL are [actually required](https://www.gnu.org/licenses/gpl-howto.en.html) to have license headers. If they don't have license headers, you basically violate your own license.

**Comment by drew2a** [comment]
Thank you for the clarification!

**Comment by synctext** [comment]
Let's go with GPL as the one and only license. Sound reasoning: most ideologically pure.

**Comment by dertuxmalwieder** [comment]
I don't think that ideology is a good motive for choosing a legally binding license. Then again, I don't use GNU licenses for my stuff.

**Comment by drew2a** [comment]
As the original issue regarding multiple licenses has been resolved in #7692, I am closing this issue.

@dertuxmalwieder, thank you for the input, I've transferred your suggestions to a new issue, #7717.
