### ISSUE TITLE
On Mac, focused and de-focused search result items have incorrect style (blue instead of dark grey)

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#6593]
**Describe the bug**
On OS X, when a user performs a search and clicks on one of the search result items, the item background color changes to blue, while the expected color is dark gray.

Then, if an item becomes deselected, the background color of the item changes to light gray (instead of dark grey)

**To Reproduce**
1. Start Tribler on Mac;
2. Type "ubuntu" into a search field;
3. Click on the first torrent in a search result list. The search result item background turns to blue (instead of dark grey).
![image](https://user-images.githubusercontent.com/2931136/143873664-d07262ad-939f-4822-8147-a66f46621d24.png)
4. Click "be the first to suggest tag" on the item. This opens a dialog window, and the item below the dialog window unexpectedly changes its color to light gray.
![image](https://user-images.githubusercontent.com/2931136/143874513-788bff97-f3ff-490b-91af-6b512dcbd848.png)
5. Close the dialog window. The item remains light gray, while the expected background color is dark grey
![image](https://user-images.githubusercontent.com/2931136/143874650-cc7e942d-2d84-428b-a6e6-a58a5ad7926d.png)

The same behavior is observed on "Popular" and "Discovered" pages: click on the item, and its color changes to blue, while the expected color is dark grey.

**Desktop (please complete the following information):**
 - OS: macOS
 - Tribler's version: at least versions 7.9, 7.10, and 7.11 are affected.

**Comment by qstokkink** [comment]
I had the same issue on Ubuntu for the file list widget. I solved this there as follows:

https://github.com/Tribler/tribler/blob/4e25843a2252a33c0fb286b3b8bd4f2969a64757/src/tribler/gui/widgets/torrentfiletreewidget.py#L471-L474

**Comment by drew2a** [comment]
I was not able to reproduce it with the latest main. @kozlovsky, could you please try to run Tribler from the main and check if the problem is gone?

<img width="859" alt="image" src="https://github.com/Tribler/tribler/assets/13798583/5c220c40-1121-4743-9bb7-58c732958e5e">

**Comment by drew2a** [comment]
As there has been no response from @kozlovsky and I am no longer able to reproduce the bug, I'm closing the issue.
