### ISSUE TITLE
Make sure GUI dialogs are managed by the `MainWindow` instance.

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#6597]
Our usage of dialogs in the GUI code is inconsistent. Specifically, we are creating dialog objects in different widgets classes, which can lead to race conditions and other hidden errors. We suspect that this might be a reason for the (recent) instability of the GUI tests.

I propose to manage all dialogs centrally, i.e., by a single manager. This manager keeps track of the open dialogs and allows us, amongst other features, to close all open dialogs when shutting down. We can also improve the GUI tests by implementing a `wait_for_dialog` method and remove a few hard-coded timeouts in the process.

**Comment by qstokkink** [comment]
Tribler now has a web-based front end and this issue is no longer relevant.
