### ISSUE TITLE
The `--gui-test-mode` option does not work as expected

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#6601]
When `run_tribler.py` is started with the `--gui-test-mode` option, the core process fails to run with the error:
```python
Traceback (most recent call last):
  File "/Users/martijndevos/Documents/tribler/src/run_tribler.py", line 102, in <module>
    start_core.start_tribler_core(api_port, api_key, state_dir,
  File "/Users/martijndevos/Documents/tribler/src/tribler-core/tribler_core/start_core.py", line 126, in start_tribler_core
    config.api.http_port = int(api_port)
TypeError: int() argument must be a string, a bytes-like object, or a number, not 'NoneType'
```

The reason for the error is the incorrect handling of the `--gui-test-mode` option. When Tribler is started with this option, it immediately starts in Core mode, while it should be started in GUI mode.

To fix the problem, `--core` and `--gui-test-mode` should be separate flags (not a mutually exclusive group), and `--gui-test-mode` flag should be processed by both GUI and Core processes.

**Comment by ichorid** [comment]
Well, the thing works just as intended: there is no such thing as "GUI running in GUI test mode" right now...

**Comment by kozlovsky** [comment]
When Tribler started with the `--gui-test-mode` flag, it should initially run GUI, and then GUI should run Core passing that flag to it. So, both GUI and Core should be able to handle this flag.

**Comment by devos50** [comment]
@ichorid this feature was definitely there and previously I could trigger it by setting the `TRIBLER_GUI_TEST_MODE` environment variable IIRC. After the argument refactoring, I would expect that passing the `--gui-test-mode` opens the GUI and spawns the core (in GUI test mode).

**Comment by kozlovsky** [comment]
So, with PR #6602, it becomes possible to use a combination of `--core --gui-test-mode` flags to run just Core with fake data and a single `--gui-test-mode` flag will start GUI with randomly generated content.
