### ISSUE TITLE
Violation of Liskov Substitution Principle in RemoteTableModel

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#6604]
Violation of LSP (which is considered bad practice) has been detected in 

https://github.com/Tribler/tribler/blob/a77ee44039472f0051b703452a7c266df6bf542f/src/tribler-gui/tribler_gui/widgets/tablecontentmodel.py#L265-L287

### Explanation

The function `RemoteTableModel.perform_query` uses attributes `self.text_filter`, `self.hide_xxx`, `self.endpoint_url` which are defined in `ChannelContentModel` class.

`ChannelContentModel` is a child class in relation to `RemoteTableModel`.

Refs:
* https://en.wikipedia.org/wiki/SOLID
* https://en.wikipedia.org/wiki/Liskov_substitution_principle

**Comment by qstokkink** [comment]
Tribler now has a web-based front end and this issue is no longer relevant.
