### ISSUE TITLE
Error when trying to kill a stuck core on Windows

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#6636]
Steps to reproduce:
1. Run Tribler as normal
2. Freeze the Core (e.g. with a big torrent)
3. Kill the GUI
4. Try to restart the GUI
5. See "kill existing Core" dialog window, select "OK" (kill the Core)

![изображение](https://user-images.githubusercontent.com/2509103/145455277-d7c8ce19-4059-45a5-bfe2-171b027e9755.png)

**Comment by drew2a** [comment]
Could be fixed in https://github.com/Tribler/tribler/pull/6941 
(close for now)
