### ISSUE TITLE
[main] Tribler switches to the "search results" page with a single click on the Search Bar.

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#6660]
**Describe the bug**
Tribler switches to the "search results" page with a single click on the Search Bar.

**To Reproduce**
1. Open Tribler
2. Search for something (eg "Ubuntu")
3. Go to the "Discovered" page
4. Click on the search bar

**Expected behavior**
My expectation is that my current page should not change. But it changes to the "Search results" page.

**Screenshots**
![image](https://user-images.githubusercontent.com/13798583/146361749-c66e1711-e860-4b82-ad0a-cff8d00d4d13.png)
![image](https://user-images.githubusercontent.com/13798583/146361779-ccb29b7b-9514-4ce4-b803-d8b257468462.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Tribler's version 7.11

**Comment by devos50** [comment]
This was an intentional change so we could remove the 'search results' from the left menu. The inspiration from this came from a previous iteration in the Spotify UI where they also used this approach.

@drew2a do you think it's too intuitive? If so, we could consider placing back the 'search results' button in the left menu.

**Comment by drew2a** [comment]
Hmm... I have never seen this behavior before, although I use Spotify from time to time.

But I'm ok with it if it is a "common practice".

**Comment by devos50** [comment]
> Hmm... I have never seen this behavior before, although I use Spotify from time to time.

Well, it actually seems that Spotify changed this recently. They now have a 'search' button in their left menu, and clicking on the search bar does not bring me back to the results anymore. 😁

**Comment by ichorid** [comment]
Yep, they changed it recently. But they removed the search bar from the top too. Do we want to do the same change?
