### ISSUE TITLE
tribler.sh says that libtorrent library isn't installed when I just installed the same library for both archs

### ISSUE THREAD

**Issue by Umeaboy** [Tribler/tribler#6677]
I followed the guide https://tribler.readthedocs.io/en/latest/development/development_on_linux.html and as soon as I ran ./tribler.sh  > tribler.log I see this message:

Traceback (most recent call last):
  File "/home/kristoffer/Skrivbord/tribler/src/run_tribler.py", line 19, in <module>
    from tribler_core import start_core
  File "/home/kristoffer/Skrivbord/tribler/src/tribler-core/tribler_core/start_core.py", line 16, in <module>
    from tribler_core.components.gigachannel_manager.gigachannel_manager_component import GigachannelManagerComponent
  File "/home/kristoffer/Skrivbord/tribler/src/tribler-core/tribler_core/components/gigachannel_manager/gigachannel_manager_component.py", line 2, in <module>
    from tribler_core.components.gigachannel_manager.gigachannel_manager import GigaChannelManager
  File "/home/kristoffer/Skrivbord/tribler/src/tribler-core/tribler_core/components/gigachannel_manager/gigachannel_manager.py", line 12, in <module>
    from tribler_core.components.libtorrent.download_manager.download_manager import DownloadManager
  File "/home/kristoffer/Skrivbord/tribler/src/tribler-core/tribler_core/components/libtorrent/download_manager/download_manager.py", line 46, in <module>
    lt.create_ut_metadata_plugin,
  File "/home/kristoffer/Skrivbord/tribler/src/tribler-core/tribler_core/components/libtorrent/utils/libtorrent_helper.py", line 17, in __getattr__
    raise ImportError('libtorrent library is not installed')
ImportError: libtorrent library is not installed

In case you wonder what name related packages Mageia 8 have when it comes to libtorrent, here they are:

libtorrent-debugsource
libtorrent-devel
libtorrent-rasterbar-debugsource
libtorrent-rasterbar-devel
libtorrent-rasterbar10
libtorrent21
python3-libtorrent-rasterbar
python3-libtorrent-rasterbar-debuginfo

For x86_64 I have this result:

lib64torrent-devel
lib64torrent-rasterbar-devel
lib64torrent-rasterbar10
lib64torrent-rasterbar10-debuginfo
lib64torrent21
lib64torrent21-debuginfo

To show you that the library is indeed installed for both archs I did
rpm -q lib64torrent21 which says:
lib64torrent21-0.13.8-2.mga8

and

rpm -q libtorrent21 says:
libtorrent21-0.13.8-2.mga8

I also have the development package for lib64torrent installed

and

rpm -q lib64torrent-devel says:
lib64torrent-devel-0.13.8-2.mga8

libtorrent-devel cannot be installed due to conflict.

Am I missing something here?

**Comment by devos50** [comment]
@Umeaboy it indeed seems that `libtorrent` is correctly installed. However, there might be a version mismatch (e.g., Tribler does not support libtorrent 2 currently). What OS are you using?

To further debug this, could you try to import `libtorrent` from the CLI Python interface? To do so, you can run the following commands:

```
python3
import libtorrent
print(libtorrent.__version__)
```

Please post the output of running these commands in this ticket. Thank you!

**Comment by Umeaboy** [comment]
> @Umeaboy it indeed seems that `libtorrent` is correctly installed. However, there might be a version mismatch (e.g., Tribler does not support libtorrent 2 currently). What OS are you using?
> 
> To further debug this, could you try to import `libtorrent` from the CLI Python interface? To do so, you can run the following commands:
> 
> ```
> python3
> import libtorrent
> print(libtorrent.__version__)
> ```
> 
> Please post the output of these commands in this ticket. Thank you!

I'm using Mageia 8 which is forked from Mandriva.

[kristoffer@ip2-133 ~]$ python3
Python 3.8.12 (default, Sep 12 2021, 19:57:22) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import libtorrent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'libtorrent'
>>> print(libtorrent.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'libtorrent' is not defined

**Comment by devos50** [comment]
@Umeaboy  It seems that libtorrent is either not correctly installed or cannot be found by your Python installation. Do you have a custom Python installation or are you using the systems' Python?

**Comment by Umeaboy** [comment]
> @Umeaboy It seems that libtorrent is either not correctly installed or cannot be found by your Python installation. Do you have a custom Python installation or are you using the systems' Python?

[kristoffer@ip2-133 ~]$ rpm -q python3
python3-3.8.12-1.mga8

I don't know how else to check.
Please advise.

**Comment by Umeaboy** [comment]
Not that I think it helps, but I ran tribler.sh for the release/7.11 branch and now I got this output instead even if it describes the same error:

[kristoffer@ip2-133 src (release/7.11)]$ ./tribler.sh
INFO:__main__:Sentry has been initialised in normal mode
INFO:__main__:Root state dir: /home/kristoffer/.Tribler
INFO:__main__:Running in "normal" mode
INFO:tribler_gui:Load logger config: /home/kristoffer/.Tribler
[PID:371072] 2021-12-26 09:56:17,545 - INFO - tribler_core.check_os(231) - Check and enable code tracing. Process name: "gui". Log dir: "/home/kristoffer/.Tribler"
[PID:371072] 2021-12-26 09:56:17,545 - INFO - tribler_core.check_os(213) - Enable fault handler: "/home/kristoffer/.Tribler"
[PID:371072] 2021-12-26 09:56:17,546 - INFO - tribler_core.check_os(48) - Check environment
[PID:371072] 2021-12-26 09:56:17,547 - INFO - tribler_core.check_os(79) - Should kill other Tribler instances
[PID:371072] 2021-12-26 09:56:17,547 - INFO - tribler_core.check_os(87) - Old PID: -1. Current PID: 371072
[PID:371072] 2021-12-26 09:56:17,548 - INFO - tribler_core.check_os(53) - Check free space
[PID:371072] 2021-12-26 09:56:18,011 - ERROR <run_tribler:131> __main__.<module>(): No module named 'libtorrent'
Traceback (most recent call last):
  File "/home/kristoffer/Skrivbord/tribler/src/run_tribler.py", line 102, in <module>
    from tribler_gui.tribler_window import TriblerWindow
  File "/home/kristoffer/Skrivbord/tribler/src/tribler-gui/tribler_gui/tribler_window.py", line 50, in <module>
    from tribler_gui.debug_window import DebugWindow
  File "/home/kristoffer/Skrivbord/tribler/src/tribler-gui/tribler_gui/debug_window.py", line 16, in <module>
    import libtorrent
ModuleNotFoundError: No module named 'libtorrent'
********************************************************************************
Import Error
********************************************************************************
Import error: No module named 'libtorrent'
********************************************************************************

**Comment by devos50** [comment]
Unfortunately, that does not help us to debug this issue further. What makes it complicated to debug is that the root cause might be an incompatibility when loading the shared library but that error is not properly propagated to Python. I have seen this several times already on Mac, making it quite difficult to debug compilation issues.

I think the best course of action would be to compile and install libtorrent yourself. Personally, I'm using libtorrent 1.2.7 which version is a bit older, but it works fine for me. Note that Tribler is not compatible with libtorrent 2 but we will consider fixing compatibility soon (also see #6184). You can download the libtorrent source code from [here](https://github.com/arvidn/libtorrent/releases). To compile it, please try running from the libtorrent source code directory:

```
./configure --enable-python-binding
make install
```

Please let us know if you run into any issues and we can help you further 👍
