### ISSUE TITLE
Progress bars for file in the Downloads Details tabs freeze Tribler

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#6686]
A forum user [reported](https://forum.tribler.org/t/7-11-0-rc2-is-out/6946/4) that on slower machines drawing progress bars for a torrent of a dozen files makes Tribler unresponsive. That is confirmed on my developer machine with some testing. The problem is, we're using `QTreeWidget`, which becomes super-slow when replacing any column with a widget (such as a progress bar). To solve the problem, we must refactor the Details tab to use QT's Model-View-Delegate pattern.

**Comment by drew2a** [comment]
I'm wondering whether #7705 fixed this issue, @qstokkink?
