### ISSUE TITLE
Radio buttons color wrong

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#6691]
![изображение](https://user-images.githubusercontent.com/2509103/147490952-f03073e0-6491-45b5-bd29-f175575232de.png)

QRadioButtons are black on dark background. We should change the style.

**Comment by devos50** [comment]
We might be able to achieve this with stylesheets only, see [here](https://stackoverflow.com/questions/38714925/qradiobutton-color-change-on-selected-and-deselected-qt).

Related to #6692.

**Comment by NaincyKumariKnoldus** [comment]
Hello @ichorid can I solve this issue?

**Comment by ichorid** [comment]
> Hello @ichorid can I solve this issue?

Well, that depends on you :wink:

[File a PR](https://tribler.readthedocs.io/en/latest/contributing.html) and we will review and accept it, if it solves the problem.

**Comment by qstokkink** [comment]
The new web-based GUI should no longer have this issue.
