### ISSUE TITLE
Branch indicators black on Windows

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#6692]
![изображение](https://user-images.githubusercontent.com/2509103/147491140-ca9dff3a-3b64-4cf0-b2dc-cbc6bbde3804.png)

QTreeView branch indicators on Windows are drawn black, which make them almost invisible

**Comment by devos50** [comment]
A quick search suggests that we might have to create and load a custom image to achieve this, similar to checkboxes (see [here](https://stackoverflow.com/questions/54429355/qt-change-tree-widget-arrow-color-via-stylesheet)).

**Comment by qstokkink** [comment]
The new web-based GUI should no longer have this issue.
