### ISSUE TITLE
Download details: “size” column resized incorrectly

### ISSUE THREAD

**Issue by TriblerFan** [Tribler/tribler#6699]
I’m running Tribler 7.11.0 64-bit on Windows 10 Pro 21H2.

The “size” column is not resized properly on The “Files” tab. It crops the “B” in B, MB, & GB. See images below.

![ArchLinux](https://user-images.githubusercontent.com/78366506/147861732-c58c4464-f42f-436a-b933-53c740875675.png)

![Manjaro](https://user-images.githubusercontent.com/78366506/147861738-23f30280-a960-4696-9a06-92d9b720f836.png)

![Qubes](https://user-images.githubusercontent.com/78366506/147861741-6a4eca24-b382-4d32-bf7c-3380126052e7.png)

**Comment by devos50** [comment]
Thanks for your report! I think the first column should be automatically stretched. Having the widget only occupy like 30% of the full page width looks a bit off and can lead to these cropping issues. I will have a look at this in a moment.

**Comment by devos50** [comment]
@kozlovsky since you are working on Windows, could you maybe try to reproduce this issue?

**Comment by kozlovsky** [comment]
@devos50 sure, can check tomorrow when I return to Delft

**Comment by devos50** [comment]
@kozlovsky any chance you can have a look at this (low priority issue though)?

**Comment by kozlovsky** [comment]
On Windows, I usually have a display scaling of 125%, and with this scaling, the Size column is displayed correctly:

![2022-10-21_15-15-28](https://user-images.githubusercontent.com/2931136/199065014-5d888dd2-eca9-4923-8235-ad0b0fee76d9.png)
![2022-10-21_15-15-55](https://user-images.githubusercontent.com/2931136/199065032-a12b039d-3433-44f7-ae55-ff7cc1562c76.png)

But when I increased scaling to 200%, I indeed encountered that the column size was incorrect:

![2022-10-31_13-52-04](https://user-images.githubusercontent.com/2931136/199065259-e259e190-5ffc-4d0f-bf63-bab71bd1556f.png)
![2022-10-31_13-52-45](https://user-images.githubusercontent.com/2931136/199065245-af419455-10fa-49ae-b30b-666ec00ed03a.png)

As a simple way to fix the problem, we can add unbreakable spaces at the end of the text in the Size column, then it becomes a little wider and looks good with different scale settings:

125%:
![2022-10-31_13-49-48](https://user-images.githubusercontent.com/2931136/199065963-2b84f121-4b90-47b3-819d-76c497d87c3e.png)
![2022-10-31_13-49-22](https://user-images.githubusercontent.com/2931136/199065975-b75bbf6f-abc7-4b76-86e0-396b47123a4b.png)

200%:
![2022-10-31_13-54-22](https://user-images.githubusercontent.com/2931136/199065691-9fdc127e-659c-4c92-8802-e71682d04cbe.png)
![2022-10-31_13-56-05](https://user-images.githubusercontent.com/2931136/199065675-4714d1d7-6f73-4b2a-a273-0696a8f225c2.png)
