### ISSUE TITLE
Logo not visible when installing Tribler through software center on Ubuntu

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#6704]
When installing Tribler by double-clicking on the `.deb` file, the software center opens. However, the icon is not visible, see the screenshot below:
<img width="858" alt="Schermafbeelding 2022-01-04 om 10 18 32" src="https://user-images.githubusercontent.com/1707075/148036905-0d598114-d830-4563-9a1a-ad4f3c830674.png">

**Comment by drew2a** [comment]
Well, I'm not sure, but probably it is impossible:

>But it won't help you put an icon in the software center. No custom packages have icons in the software center.

https://askubuntu.com/questions/371585/how-to-add-icon-and-screenshot-for-my-app-deb-package-to-see-it-in-ubuntu-softw

@xoriole can you confirm or disprove this (as a ubuntu user)?

**Comment by xoriole** [comment]
Yes, I can confirm the logo does not show.
![Screenshot from 2022-07-04 17-41-25](https://user-images.githubusercontent.com/1442867/177274083-b73f9b2c-25d2-4ec4-af60-c3bc590c5776.png)

**Comment by drew2a** [comment]
Close as the issue looked impossible to fix.
