### ISSUE TITLE
Lz4 does not  compress well enough.

### ISSUE THREAD

**Issue by kotenok2000** [Tribler/tribler#6711]
**Describe the bug**

**To Reproduce**
1. Populate channels folder with data (subscribe to channels)
2. navigate to channels folder via cmd
3. Run compact /c /s /a /i /exe:lzx
4. See that it was able to compress files  1,3 to 1 that have already were compressed with lz4

**Expected behavior**
Files are not able to be compressed further
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Tribler's version: 7.11.0

**Additional context**

**Comment by ichorid** [comment]
We're using LZ4 streaming compression feature to fit data into UDP packets and file-based chunks. Streaming mode is less efficient, but it allows us to avoid backtracking (e.g. when adding the last entry will overflow the chunk size). That said, fitting the chunks tightly is not a priority when dumping them to disk. However, using the same code for both network and torrent-based transfers is.
