### ISSUE TITLE
Inconsistent interface while adding magnet link.

### ISSUE THREAD

**Issue by kotenok2000** [Tribler/tribler#6712]
**Describe the bug**

**To Reproduce**
1. Press Add torrent
2. Press import torrent from magnet/url
3. paste magnet link.
4. Look at add button. It is on the left.
5. Press it.
6. Look at download button. It is on the right

**Expected behavior**
Download button is on the left, like add button
Cancel button is on the right

**Screenshots**
![Снимок экрана (106)](https://user-images.githubusercontent.com/8822292/148580060-ab4b6798-b9f6-4d15-95c6-65c3ef08ce7e.png)
![Снимок экрана (107)](https://user-images.githubusercontent.com/8822292/148580058-b1ab41df-3228-4285-8e88-9a38409db061.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Tribler's version 7.11.0

**Additional context**

**Comment by devos50** [comment]
This is inconsistent indeed (probably because the `StartDownloadDialog` is a completely custom GUI element). I can fix this this morning 👍
