### ISSUE TITLE
Upgrade the Tribler GUI to PyQt6

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#6725]
Qt6 has been released over a year ago, and we should update the Tribler GUI to use PyQt6 eventually ([new features](https://wiki.qt.io/New_Features_in_Qt_6.0)). While there do not seem to be very urgent reasons to upgrade, PyQt5 support will eventually be lower. Pyinstaller also seems to [support](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-PyQt6.QtCore.py) PyQt6.

**Comment by qstokkink** [comment]
Tribler now has a web-based front end and this issue is no longer relevant.
