### ISSUE TITLE
Build fails using docker on Arch Linux

### ISSUE THREAD

**Issue by ghost** [Tribler/tribler#6739]
**Describe the bug**
Docker build fails on Linux 5.16.1-arch1-1 #1 SMP PREEMPT x86_64 GNU/Linux and Docker version 20.10.12, build e91ed5707e.

**To Reproduce**
Install Arch Linux (e.g., in a VM), then:

``` bash
sudo pacman -Syu docker
mkdir $HOME/temp
cd $HOME/temp
git clone https://github.com/tribler/tribler --recursive
docker build -t triblercore/triblercore:latest .
```

**Expected**
Docker build succeeds.

**Actual**
Error:

> unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat $HOME/temp/Dockerfile: no such file or directory

**Comment by drew2a** [comment]
Related to #6740

**Comment by qstokkink** [comment]
Now that we have [a GitHub Package](https://github.com/Tribler/tribler/pkgs/container/tribler), the following _should_ work:

```
docker pull ghcr.io/tribler/tribler:sha256-383fc7fce3ae30badc3f1626971505a744b2a451385bf698232a176ef671fc1a
```

This still needs to be tested though.

**Comment by qstokkink** [comment]
The instructions at https://tribler.readthedocs.io/en/latest/basics/docker.html should also work for Arch Linux.
