### ISSUE TITLE
Channel updating is too slow.

### ISSUE THREAD

**Issue by kotenok2000** [Tribler/tribler#6756]
**Describe the bug**

**To Reproduce**
1. Go to discovered channels 
2. Sort by torrent  number in descending order
3. Subscribe to the first channel
4. Wait
5. 
**Expected behavior**

**Screenshots**
<RETRACTED>

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Tribler's version 7.11.0

**Additional context**
I am using spinning hard drive
metadata.db size is 4.21 gb

**Comment by devos50** [comment]
Thank you for your report! For privacy reasons, I have removed the screenshot from your post since it might contain sensitive information.

**Comment by absolutep** [comment]
Channel is not updating properly even though the channel is most popular on Tribler.

**Comment by drew2a** [comment]
This issue is no longer relevant due to:
- #7726
