### ISSUE TITLE
Add checkbox saying "Close to system tray"

### ISSUE THREAD

**Issue by kotenok2000** [Tribler/tribler#6758]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
Change checkbox "Minimize to system tray" to "Close to system tray", and change logic behind it accordingly.
**Additional context**

**Comment by hbiyik** [comment]
+1 i have also closed tribler several times, just because of that.

**Comment by Baeldaeg** [comment]
This is something I keep doing too.
Having the choice for both minimize and close to system tray seems sensible.

**Comment by drew2a** [comment]
As far as I see, the requested feature has been added in [this commit](https://github.com/Tribler/tribler/commit/4f8446c60a7c68fd8455c27b3fe845c5ecb2866c).

Please note that the feature needs to be activated in the settings.

It works for both Ubuntu and Windows.
