### ISSUE TITLE
Clarity needed regarding Channel Privacy

### ISSUE THREAD

**Issue by absolutep** [Tribler/tribler#6764]
So I created a channel & as can be seen from screenshot I set it to 2 hops.

![Untitled](https://user-images.githubusercontent.com/97702149/153505523-31f0dd73-20f9-48db-b401-5315e5cf8d2d.png)

My question is - as far as I have read Tribler literature - Channels are always public.

Then how come this anonymous feature is showing?

Can channel system actually work on anonymously (similar to torrents) or **is it just a bug?**

**Comment by qstokkink** [comment]
We don't have an interface for this. If you want to remove your keys, you'll have to remove the following files from your Tribler configuration folder (typically `~/.Tribler` or `%APPDATA%\.Tribler`):

https://github.com/Tribler/tribler/blob/ebc1d447000ce5bdeffccd8a36af7a025cf5f76c/src/tribler-core/tribler_core/components/key/settings.py#L9-L12

**Comment by absolutep** [comment]
I did remove the aforementioned folder previously but I got the same key again. That's why I am asking.

**Comment by absolutep** [comment]
> The artifacts are [still there](https://github.com/Tribler/tribler/tree/main/build/win/tools),

How can I use this?
