### ISSUE TITLE
Blockchain Engineering - class of 2022 - Team Import Science

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#6783]
Your task is to gather scientific publications and engineer machine reading of scientific knowledge in BrainDAO. [Thousands of scientific articles](https://www.kaggle.com/Cornell-University/arxiv) are available with Creative Commons copyright license in simple .PDF format. Get thousands of such files on each device and start processing. Use a light library for [Natural Language Processing](https://android-developers.googleblog.com/2019/04/ml-kit-expands-into-nlp-with-language.html). Use the Bittorrent engine inside Superapp for efficient file sharing. Use IPv8 community to gossip new content. What does this have to do with our "Blockchain Engineering course? True, this is adding lots of data and processing on top of our blockchain-based BrainDAO. Reading: https://doi.org/10.3389/frma.2019.00002

13 years ago: material from Leonardo: [https://bitbucket.org/ldalonzo/p2p-search-scientific-pubs/src/master/ ](https://bitbucket.org/ldalonzo/p2p-search-scientific-pubs/src/master/). a [thesis](https://bitbucket.org/ldalonzo/p2p-search-scientific-pubs/raw/110c02f75cfcd21d5084e2a2a50577c0b78c0c30/thesis/thesis.pdf).  A few lessons I learnt (COPIED):
- Extracting text from PDFs is (was) not a trivial exercise. At that time I used https://linux.die.net/man/1/pdftohtml. These days there are much better options.
- Parsing citations is a tricky exercise. I used this tool https://github.com/knmnyn/ParsCit. I saw they perfected it using deep learning.
- I wrote code to manually build an inverted index to support full-text search. There's probably something off the shelf that can be reused and I could have better spent the time elsewhere.
- I wrote code to manually cluster documents using Latent Semantic Analysis. Again, there's probably some library out there that does the same and I could have better spent the time performing measurements on how clustering works on very large collections;

Other related work is the MusicDAO: feel free to re-use all that code. First steps:  
- [ ] compiling the superapp from the source
- [ ] select a library and try to get this Natural Language Lib compiling for Android
- [ ] read the pointer on this ticket + read the IPv8 documentation https://py-ipv8.readthedocs.io/ + Trustchain https://trustchain.readthedocs.io/en/latest/trustchain.html.
- [ ] (Manually) create a directory of .PDF files to parse. Creative Commons. At least 25 article for next meeting.  (https://www.ncbi.nlm.nih.gov/pmc/tools/openftlist/)
- [ ] Week 4 goal: automatically parse a .PDF file, extract good possible keywords for possible user search, build 1 index.
- [ ] Week 6 goal: distributed search

Please keep it simple, this will all fail if you try to get something as ambitious as knowledge graph operational on Android with a blockchain. Key points for grading: merged pull request on Superapp and architecture that works; performance and usability is secondairy.

**Comment by synctext** [comment]
- Sisko: found various libraries of .PDF parsing and citations. 
  - https://github.com/knmnyn/ParsCit
  - https://github.com/allenai/s2search
  - https://github.com/itext/itext7/graphs/contributors (library from hell, XML parser, bar codes, full blown SVG, etc.)

**Comment by sisko444** [comment]
### This week's progress
- We got a PDF parser with wrapper for compatibillity with Apache license
- MusicDao code was copied and used as a basis for a stub
- Reading into the android basics of project structure and fragments
- Task division made
- 10 PDF's next to src folder

### Our plan for next week
- First make a more propper and compiling stub (Sisko rush monday)
- Fragments for: catalog, reader, document, dialogue for upload, search, search result
- The uploading and saving of PDF into trustchain
- Maybe some NLP, keyword extraction or extra citation parsing endeavours

### Questions for the meeting
- No images parsing
- What kinds of keyword extration / NLP will be next after the MVP

> To be altered during Johan meeting monday

**Comment by keonchennl** [comment]
![0be50bf6-8799-47b9-a239-0f1ac1b133b5](https://user-images.githubusercontent.com/66115421/157034145-2b78cc22-db18-4766-8c68-f79175a6e35b.jpg)

**Comment by synctext** [comment]
- [X] Parse PDF to HTML (now to text for MvP) (not yet done for 10 pdf dataset)
- [ ] external reader (open .PDF to read)

**Comment by sisko444** [comment]
We have switched from a bottom up to a top down approach, meaning, no stub, rather we will implement sepparte functionalities and later consolidate them together into one app.

**Comment by MMarko333** [comment]
## Progress notes

### Try our apk
https://github.com/keonchennl/trustchain-superapp/blob/db41c2887a37d458e055f1b538d3d9c552bf10da/app-debug.apk

### Work done
 - created UI
 - backend for PDF parsing
 - backend for keyword extraction

### Discussion
 - contact for the musicDAO developer
 - verify query forwarding idea

**Comment by synctext** [comment]
- Solid progress in Week 6 (60% done of course, if nominal and linear) :confetti_ball:

**Comment by synctext** [comment]
PDFs Creative commons: https://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_pdf/d8/1d/ (many GBytes)

**Comment by sisko444** [comment]
This week the query handler was written which includes the document ranking methods. We also have now over 300 PDF for testing. Besides that, we can also pass peer to peer messages now. Below we can see the pdf rating. 
![image](https://user-images.githubusercontent.com/33283063/160085943-1bf9d771-196c-492f-8c00-709c0dc57088.png)

**Comment by synctext** [comment]
- No much visible progress
- 4 people know and understand IPv8, non-visible learnings
- Concerned about [the integration of 6 people and branches](https://github.com/keonchennl/trustchain-superapp/branches/active).

**Comment by sisko444** [comment]
This week I implemented the parsing of PDF's as a coroutine to make it a non stopping process. However it still stops (intuitively i think that is becouse of the nature of the task, not the thread executing it) I also worked on storing and loading the metadata of PDF files for search queries and made sure we can run the app on a physical mobile device.
Peter and Rahul worked on passing the search string from the gui to the backend and implementing a PDF import button into the GUI. Throwing the intend and getting the results back in logging, still a work in progress.
Keon has been working on seeding for downloading the PDF's from peers. I an Keon settled on an architecture to settle queries. We think its best to save the keywords locally and transmit only the results of a query after doing a local comparison.
Quinten worked on the UI layout and also worked on asynchronous tasking. He and I will look at this together more to make the PDF parsing non-stopping.
Continuous scoreing of local parsed documents as a user types in the searchbar: 
![image](https://user-images.githubusercontent.com/33283063/161266247-2232727b-7cf8-4035-ba42-c10bfb4fc863.png)

**Comment by synctext** [comment]
- installs, but fails to run completely; crash of your app. :astonished: (end of week 8, so getting nervous/tight)
- [Feel free to copy this approach](https://github.com/Tribler/tribler/issues/6787#issuecomment-1085692315); their libtorrent and EVA protocol fallback; plus EVA protocol fix.

**Comment by sisko444** [comment]
- PDF selection from internal storage is implemented.
- The local file storage is now implemented to work with persistence.
- The parsing of PDFs is now mostly ran in a coroutine, the part that isn't, still can't for unknown reasons. (it doesnt stop anymore in the simulator and has about 10 seconds of black screen on a phone test)
- EVA was implemented, once a file is parsed, its torrent is generated and will be broadcast to all peers, every 10 seconds.
- Every 20 seconds the client attempts to download a piece of literature from a received torrent. (This is not working optimally yet, a later commit made it work less good)

@TODO
- The remote search back-end is finished, the front end is still in development.
- The display of parsed documents and displaying of EVA operations is also still in development.
- Make it so the entire PDF parsing is in a coroutine.
- Repair whatever is hindering the performance of the downloading using the torrents.

**Comment by synctext** [comment]
- app works !! 
  - blocking main thread upon parsing .PDF
  - no showing yet of .PDF metadata to replace "Lorem ipsum".
- lots of stuff happening in background and things are coming together {hopefully} soon.

**Comment by sisko444** [comment]
The day of reckoning has come and we have to make our final pull request to the actual mother repo.
To tie the current state back to the previous feedback:
- App still works! No more blocking the main thread and we show the .pdf files.
- Things are very much coming more together
- 
- The whole search bar is now clickable.
- This tip is not necessary, the boxes are populated with the actual PDFs
- Sadly we were still working on it until now and there are still test cases to be solved that why there was no pull requests yet
- We now ask for permissions when the app launches for the first time, and there is the option to import PDFs though UTL's aswel
![local_upload](https://user-images.githubusercontent.com/33283063/167591620-a9547f63-e778-4ea9-a594-a7d1d9a4f169.gif)
![peers](https://user-images.githubusercontent.com/33283063/167591634-6e0b8aaf-11c8-4ee7-b36d-616255fa5347.PNG)
![search_in_keywords](https://user-images.githubusercontent.com/33283063/167591635-a68c0d2c-16de-4a44-ba73-fc52688252eb.gif)
![url_upload](https://user-images.githubusercontent.com/33283063/167591643-75a305ae-2098-4138-9f60-14818f63000e.gif)

**Comment by sisko444** [comment]
The APK file download: [link](https://we.tl/t-5uZxy1NlNX)
This expires in one week.

**Comment by synctext** [comment]
Lots more polished level:
- remote download works (eva or magnet)
- 1 search box
- extracts title of .PDF file
- details of ongoing downloads
- etc

**Comment by keonchennl** [comment]
Some changes that have been merged into master involves with a invalid library (info.blockchain.api 1.1.4), which breaks the master pipeline.
https://github.com/Tribler/trustchain-superapp/pull/113#issuecomment-1118951508
https://github.com/Tribler/trustchain-superapp/pull/113#issuecomment-1119337108

**Comment by devos50** [comment]
This work has been completed, closing the issue 👍

**Comment by synctext** [comment]
Related work:
[Novel public review model, great idea. use pre-print services, public review process. No more rejects or accepts](https://elifesciences.org/inside-elife/54d63486/elife-s-new-model-changing-the-way-you-share-your-research)
<IMG src=https://user-images.githubusercontent.com/325224/197795001-7f04355d-a407-4e32-876d-54918f717ea1.png width=400>
