### ISSUE TITLE
Blockchain Engineering - class of 2022 - Team Digital Euro II

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#6784]
**Project description:** Your task is to {partly} realise a new blockchain-based digital Euro. Delft university has obtained permission to [experiment with real digital Euros](https://www.delta.tudelft.nl/article/delft-cafe-premieres-eemcs-blockchain-euro) and live connection to the IBAN bank account system. You can build on this existing open source code. Reading: European Central Bank [report on digital Euro](https://www.ecb.europa.eu/pub/pdf/other/Report_on_a_digital_euro~4d7268b458.en.pdf), digital [Euro master thesis at Delft](https://repository.tudelft.nl/islandora/object/uuid%3A132faae8-6883-454f-a8ce-94735340dce9), the [progress report by China Central Bank](http://www.pbc.gov.cn/en/3688110/3688172/4157443/4293696/2021071614584691871.pdf) who is at least five years ahead of Europe. You are free to set your own target feature to focus on, for instance, high transaction rate, offline support, ease of use, etc.

**Approach:** You will either extend our EuroToken implementation with new functionality, or improve existing functionality. The target feature(s) will be chosen depending on your expertise and interests. Suggestions/ideas are very much appreciated! Please make weekly updates of your progress on this ticket (e.g., with a screenshot). The expected deliverables are:
- A working end-to-end demo of your functionality.
- A __small__ readme.md writeup, describing your product, challenges, and design decisions.
- A merged and reviewed pull request to the [superapp repository](https://github.com/Tribler/trustchain-superapp).

**Possible project direction (subject to discussion next meeting):** Bitcoin-backed EuroTokens. Currently, EuroTokens are backed by Euro in the central bank network. Your project involves extending support for Bitcoin-backed EuroToken. You will have to modify the Bitcoin mining parameters, set up a private Bitcoin network, and mine some Bitcoin. These Bitcoins can be sent to a validator and exchanged for EuroToken. Give each user 10 EuroToken when joining the app.

References:
- [EuroToken: An offline capable Central Bank Digital Currency](https://repository.tudelft.nl/islandora/object/uuid%3A132faae8-6883-454f-a8ce-94735340dce9?collection=education)
- [EuroToken implementation in the Superapp](https://github.com/Tribler/trustchain-superapp/tree/master/eurotoken/src/main/java/nl/tudelft/trustchain/eurotoken) 
- Various applications inside the superapp are using the EuroToken implementation. See for example the work by Joost on the [value transfer application](https://github.com/Tribler/trustchain-superapp/tree/master/valuetransfer/src/main/java/nl/tudelft/trustchain/valuetransfer). [Relevant issue](https://github.com/Tribler/tribler/issues/6029).

ToDo:
- [X] Compile Superapp from the sources and run in emulator
- [ ] ~~Half of the group: investigate the fork of Bitcoin which operational is in [Luxury Communism](https://github.com/Tribler/trustchain-superapp/blob/master/currencyii/README.md) part of Superapp~~
- [ ] Half of group: investigate the digital Euro on Trustchain, part of the Superapp
- [ ] Milestone: each team member has 100 BTC on their phone (forked or real) call it "Euros" in the GUI

**Comment by synctext** [comment]
https://www.dnb.nl/actueel/algemeen-nieuws/dnbulletin-2018/dnb-experimenteert-met-blockchain/

**Comment by dlieuwasoe** [comment]
## Planning (milestones per week)

### Week 5: 
- Add dummy UI options
   - Offline mode alert (dialog)
   - Grey out exchange options
   - Make unconfirmed balance more clear

### Week 6: 
- Implement proper offline detection
- Spend/Receive cap
- Prevent respending of unconfirmed balance

### Week 7: 
- NFC payments

### Week 8:
- Add report functionality
- Show warning when other user has an unverified ID

### Week 9:
- Clone testing
- Findings (document and quantify things that do and do not work)

### Week 10:
- Finishing up + presentation

**Comment by synctext** [comment]
Possible decision: receiving party is in control and does most of the risk assessment; decides to accept or reject proposed transaction. Possible scope of disaster: "[100.000 mensen](https://nl.wikipedia.org/wiki/Lijst_van_rampen_in_Nederland#20e_eeuw) verliezen hun huis en bezittingen"

**Comment by leondeklerk** [comment]
![Screenshot_20220309-150849](https://user-images.githubusercontent.com/22279479/157458046-cac26426-7f8d-456e-9fab-d26784ca80b9.jpg)
![Screenshot_20220309-150826](https://user-images.githubusercontent.com/22279479/157458123-486fb9aa-4ab8-4fde-a46a-4b54acd17a6f.jpg)
![Screenshot_20220309-150831](https://user-images.githubusercontent.com/22279479/157458125-3ec2d0bb-3fe5-47d5-b346-fc7072b94ae5.jpg)
![Screenshot_20220309-150841](https://user-images.githubusercontent.com/22279479/157458127-79e7ef9f-d908-45fa-a09d-9d4ba98941f0.jpg)

**Comment by leondeklerk** [comment]
#### EuroToken Exchange
Made the EuroToken exchange workable and runnable again. Making sure that you can run this as before you needed undocumented documentation. Fixed various minor issues as well (crashing edge cases). Added documentation on how to run the exchange docker/manually.
<img src=https://user-images.githubusercontent.com/22279479/158693415-3ddf699a-ae92-4476-a6b5-1dba2b9fc462.png width=450><img src=https://user-images.githubusercontent.com/22279479/158693525-1bf3e3a8-b775-469a-8935-f25cba25d7bb.jpg width=150><img src=https://user-images.githubusercontent.com/22279479/158694547-01104fa7-af05-4ec2-acd7-9796471308f0.png width=150>

**Comment by synctext** [comment]
- nice that the Tikkie gateway is operational again! ([also](https://github.com/KoningR/stablecoin-exchange))
- ability to re-spend unvalidated tokens (user warning)

**Comment by leondeklerk** [comment]
### Exchange
- Made checkpointing work again
- Add extra QR code containing gateway information
- Documented everything properly in the readme
### App
- Removed default hardcoded gateway
- Add the ability to scan and add gateways via their info QR code
- Add to option to pay a request with unverified money
<img src=https://user-images.githubusercontent.com/22279479/160104128-6da17a79-6b5a-4277-a581-fa0a0df8ce33.png width=150><img src=https://user-images.githubusercontent.com/22279479/160104466-1ed57dc0-a3ca-4ad9-b887-1f03e0642382.jpg width=150>!<img src=https://user-images.githubusercontent.com/22279479/160104474-7f155592-5de5-48e5-a23a-4a598d83fa0d.jpg width=150><img src=https://user-images.githubusercontent.com/22279479/160104475-7d3a0aa9-c965-481b-bf1d-fb10014235b7.jpg width=150>

**Comment by synctext** [comment]
- this work directly conflicts with existing app and Euro III approach. EuroToken App fork or replace?
- team Euro II approach requires the gateway to be online :thinking:

**Comment by leondeklerk** [comment]
### [Trust score](https://github.com/leondeklerk/trustchain-superapp/commit/632665ccb83c0e3071b87e051d66df7ae5604143)
- Added the room database objects/converters etc.
- Added a (random) trust score display to the transaction sign screen
- Transactions are no longer automatically signed but require an explicit sign to show the trust score

### Offline payments
- Added an extra field in the proposal/acceptance blocks for unverified money
- Payments with unverified money are now correctly validated when there is enough balance available. 
  - When there is insufficient balance, however, an error occurs which will be resolved in the upcoming week. Also, the issue of transforming verified tokens to unverified tokens will be taken care of when a transfer is done in offline mode.

<img src=https://user-images.githubusercontent.com/22279479/161265570-e72c6da0-0224-4e71-bf2e-a293c037ffe8.png width=150><img src=https://user-images.githubusercontent.com/22279479/161265710-5a4a3127-cf5c-445a-a2ab-45d151acee67.png width=150>

**Comment by leondeklerk** [comment]
[apk](https://drive.google.com/file/d/1IIqt-fs1BWiFyWXiS_GiifejGLGV9gE4/view?usp=sharing)

**Comment by dlieuwasoe** [comment]
### Paying with unverified tokens
- Now, the receiver has the possibility to specify whether unverified money is accepted.
- If unverified money is not allowed, no transfer proposal block will be created if the sender has a verified balance that is too low.
- In the case that unverified money is allowed by the receiver, there are two possibilities:
    - either the sender does have enough verified money, in which case he/she will automatically pay with verified money,
    - or the sender does not have enough verified money, which is the case where unverified money can be transferred.
- The total balance is calculated by getBalanceForBlock().
- The verified balance is calculated by getVerifiedBalanceForBlock().
- The unverified balance is calculated by subtracting the verified from the unverified balance.
- getVerifiedBalanceForBlock() is modified for this purpose.
    - A new field "unverified" is specified for each proposal block, specifying whether the transfer is done with unverified money.
- The receiver will get a warning when the transfer is performed with unverified money.

<img src="[doc/musicdao/screen2.png](https://user-images.githubusercontent.com/68291392/164196926-eaf11260-ff5e-4d0c-b6dc-b041e6fc665c.png)" width="280">

<img src="[doc/musicdao/screen2.png](https://user-images.githubusercontent.com/68291392/164197110-22e3c143-ad0d-4e42-91d1-719b67e9bc91.png)" width="280">

**Comment by leondeklerk** [comment]
[apk](https://drive.google.com/file/d/1m5Oe7LTn--BtkzRdmJ-sxu7B2xM2euk9/view?usp=sharing)

**Comment by leondeklerk** [comment]
[Updated ConfIDapp level README](https://github.com/leondeklerk/trustchain-superapp/tree/master/valuetransfer)

**Comment by devos50** [comment]
This work has been completed, closing the issue 👍
