### ISSUE TITLE
Blockchain Engineering - class of 2022 - Team Contribute Intelligence

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#6787]
_Your task is to make the BrainDAO expandable._

To make the BrainDAO evolve it is required that everybody can contribute freely, without permission, and without gatekeepers. You enable the system-blocks of BrainDAO for run-time expansion. You will dive deep into the Android run-time system to enable dynamic code loading. [build upon the prior work done in prior years](https://github.com/Tribler/trustchain-superapp/blob/757df98b7846d832a5a91b444ce6aa416241f7fa/freedomOfComputing/README.md). Create a small demo which loads one AI example and can upgrade it at runtime for a smarter AI. This approach should be usable in general for BrainDAO evolution.

Current sprint:
- [x] Everbody compile superapp from source
- [x] Read and study the code of [prior work](https://github.com/Tribler/trustchain-superapp/blob/757df98b7846d832a5a91b444ce6aa416241f7fa/freedomOfComputing/README.md)
- [ ] One has an example plugin up and running. (e.g. “Execute code from jar” works!)
- [ ] [MusicDAO](https://repository.tudelft.nl/islandora/object/uuid:72a5c834-177b-4b3c-a6f8-8e69e65cfdf4/datastream/OBJ1/download) reading plus [robo economy in general](https://dicg2020.github.io/papers/pouwelse.pdf) reading 

Possible target for next sprint:
[From prior work documentation:](https://github.com/Tribler/trustchain-superapp/blob/757df98b7846d832a5a91b444ce6aa416241f7fa/freedomOfComputing/README.md) _Informing the other peers about the seeding torrent. The user presses the “Inform peers about seeding” button, which sends the magnet link to every other peer in the network. Every recipient can now check his incoming magnet links / messages by pressing the “Retrieve list of torrents” button. Upon pressing that button, a list of the available torrents appears at the bottom of the scrollable screen._

Create a pull request which expands this behaviour. Every peer remembers the available torrents currently. Only stored in memory its assumed. The expansion is to create a new ```query known torrents``` message. This is send to a maximum of 20 neighbors around you. Such an incoming search message triggers the generation of an IPv8 UDP response packet. It consists of a single packet maximum filled (1480 Bytes) with one or more magnet links. Random selection is used to facilitate equal spreading of information, [random paper on random gossip protocols](https://www.cs.cornell.edu/lorenzo/papers/p14-alvisi.pdf).

**Comment by synctext** [comment]
All have superapp compiling, successfully repeated the "code injection of apk/jar", [advanced demo is operational](https://github.com/rootmonkey/trustchain-foc-demoapp), and code sharing tested between two isolated devices. What is the exact runtime behavior now? Seems we can pass variables to dexclassloader

**Comment by rmadhwal** [comment]
![image](https://user-images.githubusercontent.com/14342304/156571922-4a1da6c2-323f-461f-9165-8e5e0528e5e8.png)
Example of running https://github.com/rootmonkey/trustchain-foc-demoapp on the Freedom of Computing app

**Comment by ThomasWerthenbach** [comment]
Weekly update:

Done
- Fixed orientation issue
- Created state saving prototype
- APK file name no longer has to equal the package name.
- Looked into alternative solutions and concluded:
    * Running an entire 'heavy' virtual machine is not a viable on android phones without third party apps or on a device which does not have enough resources to support this.
    * An option is to prompt the user to install the torrented APK directly on their device. However, this will decrease user friendliness and will remove control from the superapp.
    * Due to fixes in stability issues, no need to continue researching alternatives.
  
Next week suggestions:
- Improvements in user friendliness:
      * Provide a list of apps the user has downloaded before (also removing the option to provide an APK name yourself)
      * Look into options for improving user friendliness in uploading APKs.
- Discuss and improve state saving.

Additional thoughts:
- Think about security measures, e.g. dynamically loaded code has the same permissions as the superapp, meaning that it can access files on the phone and possibly introduce ransom-/malware

**Comment by synctext** [comment]
- solid progress :medal_sports: 
- This week sprint: post .APK on ticket for public demo purposes
- try to get the dynamic code discovery operational. Thus all phone get a message via IPv8 gossip when somebody uploads new code or ransomware (for this year all security is out of scope).
- Known security issue: give stranger full control of your screen, your network device, your stored data, and device itself

**Comment by ThomasWerthenbach** [comment]
Weekly update:

Done:
- State saving for an arbitrary amount of apps (https://github.com/rmadhwal/trustchain-superapp/pull/2). States are now saved in .dat files in the root directory and loaded whenever a user reopens the dynamic app.
- Demo apk. Performs voice recognition and searches duckduckgo for related topics (https://github.com/rmadhwal/trustchain-voice-search)

https://user-images.githubusercontent.com/29115394/158811710-8edf62b9-f160-4828-91b7-be66a4922d42.mp4


- Made a start in automatic apk gossiping (shares random 10 apks every 10 seconds). (https://github.com/rmadhwal/trustchain-superapp/tree/gossip)

https://user-images.githubusercontent.com/29115394/158811909-85a0fbaa-6dcf-450f-b412-06828bee4674.mp4


- Made a new design (not functional yet due to automatic gossiping not yet merged):
![WhatsApp Image 2022-03-17 at 1 41 08 PM](https://user-images.githubusercontent.com/29115394/158810749-3aee6ca9-14c7-44eb-9f77-76c5d203c362.jpeg)
![WhatsApp Image 2022-03-17 at 1 41 18 PM](https://user-images.githubusercontent.com/29115394/158810758-34905f9b-b5a1-4f38-a256-1f42b2a7f4a2.jpeg)
(https://github.com/rmadhwal/trustchain-superapp/tree/new-design)
- Make uploading more user-friendly: list files from Download directory to be able to choose one. (https://github.com/rmadhwal/trustchain-superapp/tree/new-design)

**Comment by synctext** [comment]
- solid progress
- working in isolation on GUI, gossip, existing FOC, plugin
- goal of system integration, please dont leave the Pull Request merging for the last week!

**Comment by ThomasWerthenbach** [comment]
Weekly update:

Fixed:
-added support for scoped storage
-added temporary file selector (can not be used newer android SDK version)
-fixed the threading issue
-integrated new design with new functionalities
-read background work

Next week suggestions:
-private trackers
-polishing design
-what should be the permanent way to add files and what should the + button do?
-storage permissions in android 11

**Comment by synctext** [comment]
Almost works :boom: :2nd_place_medal: 
<IMG src=https://user-images.githubusercontent.com/325224/159925499-9df0d1ce-1b92-477d-beae-2ac5ab0e8ff0.jpg width=140>

**Comment by ThomasWerthenbach** [comment]
https://user-images.githubusercontent.com/29115394/159925970-b3660a30-b2ab-4ce9-8e7f-657845e43d32.mp4

**Comment by rmadhwal** [comment]
Weekly Update:
Done and in the demo apk:
- Added EVA Protocol as a fallback to when torrents don't work
- Found that EVA Protocol would often result in timeouts, investigated and found [possible cause](https://github.com/Tribler/trustchain-superapp/issues/101) implemented changes locally, a permanent fix would require discussion and finally commiting to ipv8
- Added preloaded APK within the superapp for demo purposes
- Add torrents as gray buttons to UI as soon as they are found, make them blue when we finish downloading
- Update progress bar
- Created our [first Pull Request](https://github.com/Tribler/trustchain-superapp/pull/96)

Done but not in the demo APK (we will demonstrate live):
- Downloading APKs from URL

Done but needs slightly more bug fixing to make it to the demo:
- Added an info popup with failed torrent attempts
- Prevent the entire app list from refreshing
- Populate all found torrents in the app view
- Give the user option to delete .apk or create a torrent out of it

[Demo for this week's updates](https://github.com/rmadhwal/trustchain-superapp/releases/tag/v2.0.0-demo)

**Comment by rmadhwal** [comment]
Progress Report:
(Less progress than average this week since all of us were tied down with exams)
- Fixed state saving bug
- Tried to do a large APK transfer as asked, but ran into an OutOfMemory issue with the EVA Protocol that is being investigated. Once fixed, will commit changes along with other suggested fixes to the kotlin-ipv8 repo
- Worked on merging Download from URL but is pending merge due to some pending threading fixes
-  Still working on finalising new changes to UI

**Comment by rmadhwal** [comment]
Final Weekly Update:

- Finalised improvements to EVA Protocol discovered during experiments and through suggestions from other Tribler developers. Raised PR to kotlin-ipv8: https://github.com/Tribler/kotlin-ipv8/pull/63
- Moved functionality from DemoCommunity to FOCCommunity
- Added integration tests
- Finished functionality to download new apps from URLs
- Updated README.md for app and description of app inside the superadd README.md

Suggested changes in our [PR review](https://github.com/Tribler/trustchain-superapp/pull/96) to the superapp have been implemented, however, PR is still pending approval.

[Final demo APK](https://github.com/rmadhwal/trustchain-superapp/releases/tag/v3.0.0-demo)

**Comment by synctext** [comment]
Total Commander forced to stop letting you install APKs - [The dev took action following a Play Store policy complaint - HNews discussion and link](https://news.ycombinator.com/item?id=31423623). Also: Android 13 restrictions details, https://blog.esper.io/android-13-sideloading-restriction-harder-malware-abuse-accessibility-apis/

**Comment by devos50** [comment]
This work has been completed, closing the issue 👍
