### ISSUE TITLE
Blockchain Engineering - class of 2022 - Team FROST

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#6788]
Focus: multi-signature transactions [using FROST algorithm](https://eprint.iacr.org/2020/852.pdf) for creating a true decentralised DAO.

Re-use the existing source code, as inside [this WIP PR](https://github.com/ElementsProject/secp256k1-zkp/pull/138). See [work by Martijn](https://github.com/Tribler/tribler/issues/5984#issuecomment-913454963). How functional is this Kotlin code? Missing parts? Could Trustchain+IPv8 help with overlay topology for 1+ million users scalability?
We have Taproot somewhat integrated in Superapp. Taproot.tribler.org documentation [```const val REG_TEST_FAUCET_IP = "131.180.27.224"```](https://github.com/Tribler/trustchain-superapp/blob/70c77749f2c517403908b327c3180c24bcaaf36c/currencyii/src/main/java/nl/tudelft/trustchain/currencyii/coin/WalletManager.kt#L40), the call [itself](https://github.com/Tribler/trustchain-superapp/blob/757df98b7846d832a5a91b444ce6aa416241f7fa/currencyii/src/main/java/nl/tudelft/trustchain/currencyii/ui/bitcoin/BitcoinFragment.kt#L225) and [documentation here](https://github.com/Tribler/trustchain-superapp/blob/master/currencyii/README.md#application-architecture)

Application: the Internet-deployed MusicDAO by Delft students enables music streaming and Bitcoin donations. Future step is to integrate [FROST for enabling collective music investment decisions](https://github.com/Tribler/tribler/issues/6714#issuecomment-1050646784)

Grading and outcome: a _merged_ pull request on the Superapp, readme addition to the repo, and some operational code. We do not ask you to solve hard scientific problems within this course, but that you spend 5 x 5 ECTS wisely.

**Comment by dandreescu** [comment]
Update: We were able to compile and produce Schnorr signatures with the FROST pull request code. Next step is to compile the FROST library for JNI and call it in BitcoinJ. The issue is the unrecognized config flag '--enable-jni'.

**Comment by synctext** [comment]
Solid progress! Lesson learned: 5 developers stuck on 1 flag for a whole sprint, that is blockchain engineering for you.

[First Taproot transactions in the wild](https://twitter.com/TomGiuretis/status/1459756741537591299) Transaction fee: $284.86! Goal is to reproduce this type of transactions with multiple smartphones and no servers or PCs in general:
<IMG src=https://user-images.githubusercontent.com/325224/156530545-610c796e-1c42-4143-bcfa-0a8940e61089.png width=250>

More details on 
I use python language and tkinter as GUI.
I followed the tutorial from 
[@bitcoinoptech](https://twitter.com/bitcoinoptech)
 on
https://github.com/bitcoinops/taproot-workshop
I used libraries in their test_framework folder
I also used bitcoin core python files 
https://github.com/bitcoin/bitcoin/tree/master/test/functional/test_framework
And to get my balance I use
[https://github.com/1200wd/bitcoinlib/tree/master/bitcoinlib/services](https://t.co/VEu18ft2Mm)

**Comment by OrestisKan** [comment]
Together with @dandreescu we traced when JNI was removed from secp256k1-zkp, brought it back and set up the frost in it. 
Succesful compilation and generation of the .so file.

The existing frost module is implementation is not in a distributed fashion, so we are re-implementing it. Currently implemented commit generation and aggregation; that is the first of 2 rounds for key generation.

We also created the JNI  methods to call the creation and aggregation from java. 

The key generation is successful but the aggregation is flakey.
Currently trying to figure out why the aggregation sometimes work and sometimes doesn't.

**Comment by synctext** [comment]
- targeting getting everything inside a single APK
- next sprinting target is design and coding of Trustchain-based FROST
- Kotlin IPv8 has its own identity and keys. Just store this for now as plain-text locally and use just IPv8 message content.

**Comment by ioanasv** [comment]
Finished implementing all JNI methods and now PR 138 can be called from java (we have FROST in the BitcoinJ library)! 

Designed all methods such that they would be compatible with Trustchain - currently working on compiling it for Android and adding it into the superapp.

**Comment by synctext** [comment]
please think about the final benchmark. Testing and demonstrating with 10M would obviously be awsome ([see museg benchmark](https://github.com/jonasnick/musig-benchmark)):
```
$ musig-bench keygen 10000000 # ten million
pubkey: F137781B753B22F8CA5450A64104072DAC55A0CCE2B67B3797ED8131E1194D23
# total: 159.30s, gen: 91s, aggregation: 70s
```

**Comment by synctext** [comment]
Seg Fault. :stop_sign: 
Status: stuck on detailed engineering. Works with stand-alone compiling, never tested for Android. Pull request is autoconf, difficult with Superapp integration. No breakpoints, no emulator running, no print statement for fault isolation.

**Comment by ioanasv** [comment]
![warningss](https://user-images.githubusercontent.com/56679711/160831106-c5897ced-d4a2-45e3-a6bd-bab13c459049.gif)

**Comment by iiacoban42** [comment]
Update: we got unstuck. 📈

Fixed our emulators and managed to debug the problem with the `.so` file. 

 `secp256k1.so` with FROST can be loaded from Android now.📱

**Comment by synctext** [comment]
-it works! :1st_place_medal:  but segmentation fault when increasing the Schnorr signatures to 1000-ish.
- Ambitious target of wrapping up by next week.
- ToDo: documentation, pull request accepted, and an animated .GIF please to demonstrate everything in main Readme.md
- Very promising!!!

**Comment by AndrewStefan** [comment]
Update: the integration of FROST into the superapp is working*
The first step of an end to end test works - two users can generate a signer object which is needed to generate the public and private keys through a C function call. Then, ipv8 is used to share this object (including the associated public key) to the other peer.
The next step in the test is sending the shares, for which the FROST function call in C seems to not crash, but there is still an issue when trying to broadcast the shares via ipv8

**Comment by synctext** [comment]
- Sadly the .APK did not yet install
- Draft PR not yet ready: https://github.com/Tribler/trustchain-superapp/compare/master...iiacoban42:final-version
- Readme: please add
  - Title: fully decentralised DAO
  - The superapp contains the foundation for a new type of DAO: fully serverless, no central point at all, no governnance token needed
  - uses the FROST algorithm to enable joint ownership of unlimited amounts of Bitcoin by group of unlimited size. Democratic control of money and means of production.
  - then more tech details.

**Comment by AndrewStefan** [comment]
New apk which hopefully works: https://drive.google.com/file/d/1hi29s_x26iSZZb0Ty5MKvUF2oP_jC7G1/view?usp=sharing

**Comment by AndrewStefan** [comment]
Final apk: https://drive.google.com/file/d/1smkjPhfFnST2gwJVdMipRJ1xjstMkn5E/view?usp=sharing

**Comment by synctext** [comment]
Impressive achievement!!
- No demo with 4 people sadly.
Comments of unclear things in [Readme](https://github.com/iiacoban42/trustchain-superapp/blob/c3b79b07bfe4e889ce3f2f7d2624912d97011426/README.md)
  - Frost algorithm link to .pdf and mention Prof. Ian@University of Waterloo.
  - Be clearer, like: this proof-of-principle does not implement the shared key part. It works only until the key share distribution phase. Locally we have successfully created a shared key inside 1 phone, something with dissemination goes wrong. Link to line 628
  - Be clearer and dont keep secrets: Does not work on Android emulators. We tried to compile with ARM and x86, but our FROST app only works currently on real Android phones.

**Comment by InvictusRMC** [comment]
Hi team, I am wondering what flags you used for compilation.

**Comment by iiacoban42** [comment]
Hi! You should be able to compile the frost code with `./configure --enable-module-ecdh --enable-module-schnorrsig -enable-jni  --enable-experimental --enable-module-musig --enable-module-frost`.

**Comment by synctext** [comment]
The grade has been given, contributed to the main discussion at: 
```https://github.com/ElementsProject/secp256k1-zkp/pull/138#issuecomment-1125963587```
Great running code !
<img src=https://github.com/iiacoban42/trustchain-superapp/raw/c3b79b07bfe4e889ce3f2f7d2624912d97011426/frost/src/img/frost_gif.gif width=200>
