### ISSUE TITLE
Tabs not defaulting to user defined state after every restart

### ISSUE THREAD

**Issue by absolutep** [Tribler/tribler#6791]
**Describe the bug**
The rearrangement of tabs by user is discarded after every restart.

**To Reproduce**
1. Start Tribler
2. Arrange Tabs according to user preferences.
3. Shut down Tribler.
4. Restart Tribler - the tabs will fall back to default state & not user defined.

**Expected behavior**
In every torrent client once tabs are adjusted to user preferences, it stays that way until the user makes some changes.

**Screenshots**
PART 1 - The Tribler default status of Tabs.
![Untitled1](https://user-images.githubusercontent.com/97702149/156309559-823621d4-f5f3-4cb9-93ec-24f96f86220f.png)

PART 2 - User defined status of Tabs.
![Untitled](https://user-images.githubusercontent.com/97702149/156309973-52b1f519-ae1d-4fd3-ab51-432c7d9c54d2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Tribler's version [e.g. 7.11.0]

**Additional context**
It is becoming unbelievably irritating to reset all tabs everyday while starting Tribler.

**Comment by InSimpleTermsJordan** [comment]
Confirmed for Tribler 7.11.0 on Manjaro Linux

**Comment by drew2a** [comment]
Fixed in 
- #8020
