### ISSUE TITLE
Tribler AUR package and tribler.sh only work with python3.9

### ISSUE THREAD

**Issue by 2ico** [Tribler/tribler#6794]
I tried to download the [AUR](https://aur.archlinux.org/packages/tribler) package for Tribler and it couldn't get to see the UI.
I have also tried to run src/tribler.sh with Python3.10 and with Python3.7 in conda, and both didn't work.
It looks like the only supported version is Python3.9. I think this should be written clearly in the README.

**Comment by drew2a** [comment]
Officially we don't support `archlinux`.
Regarding the python version, we support python version >= `3.8`

**Comment by 2ico** [comment]
Well, Python 3.10 is not working.
