### ISSUE TITLE
Libtorrent is not part of requirements.txt

### ISSUE THREAD

**Issue by 2ico** [Tribler/tribler#6795]
**To reproduce**
 - clone branch release/7.11
 - cd src
 - install python3.9 (through Conda)
 - pip install -r requirements.txt
 - ./tribler.sh

`
INFO:__main__:Sentry has been initialised in normal mode
INFO:__main__:Root state dir: /home/george/.Tribler
INFO:__main__:Running in "normal" mode
INFO:tribler_gui:Load logger config: /home/george/.Tribler
[PID:1152352] 2022-03-02 11:52:46,927 - INFO - tribler_core.check_os(231) - Check and enable code tracing. Process name: "gui". Log dir: "/home/george/.Tribler"
[PID:1152352] 2022-03-02 11:52:46,927 - INFO - tribler_core.check_os(213) - Enable fault handler: "/home/george/.Tribler"
[PID:1152352] 2022-03-02 11:52:46,927 - INFO - tribler_core.check_os(48) - Check environment
[PID:1152352] 2022-03-02 11:52:46,928 - INFO - tribler_core.check_os(79) - Should kill other Tribler instances
[PID:1152352] 2022-03-02 11:52:46,928 - INFO - tribler_core.check_os(87) - Old PID: -1. Current PID: 1152352
[PID:1152352] 2022-03-02 11:52:46,928 - INFO - tribler_core.check_os(53) - Check free space
[PID:1152352] 2022-03-02 11:52:47,043 - ERROR <run_tribler:131> __main__.<module>(): No module named 'libtorrent'
Traceback (most recent call last):
  File "/home/george/Documents/TUD/Tribler/tribler-github/src/run_tribler.py", line 102, in <module>
    from tribler_gui.tribler_window import TriblerWindow
  File "/home/george/Documents/TUD/Tribler/tribler-github/src/tribler-gui/tribler_gui/tribler_window.py", line 50, in <module>
    from tribler_gui.debug_window import DebugWindow
  File "/home/george/Documents/TUD/Tribler/tribler-github/src/tribler-gui/tribler_gui/debug_window.py", line 16, in <module>
    import libtorrent
ModuleNotFoundError: No module named 'libtorrent'`

I solved this with `pip install libtorrent==1.2.15`. Installing the latest version (2.0.5) won't work because of some cpp binding error (their fault).

**Comment by drew2a** [comment]
@2ico unfortunately there is no easy way to install `libtorrent` and it differs from OS to OS.

That is why we put the information regarding dependency installation (libtorrent included) to the following documentation: https://github.com/Tribler/tribler/tree/main/doc/development

Normally you could not install `libtorrent` via pip.

For example, for Linux you have to run:

```bash
sudo apt install python3-libtorrent
```

For macOS:

```bash
brew install libtorrent-rasterbar
```

For Windows: https://github.com/Tribler/tribler/blob/main/doc/development/development_on_windows.rst#libtorrent

----
Regarding the `2.x.y` version of `libtorrent`, we don't support it yet.

**Comment by drew2a** [comment]
@2ico thank you to pointing this out.
