### ISSUE TITLE
Dispersy wireprotocol 2.0: use "Cap’n Proto"?

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#68]
Goal: evaluate new package for suitability

Is it possible to start using this to replace encoder.py and decoder.py with the lists and tupple structure? Signature and versioning easy to support?

http://kentonv.github.com/capnproto/
https://news.ycombinator.com/item?id=5482081

**Comment by synctext** [comment]
https://capnproto.org/ Seems capt'proto now has also support for integrity checks. As Boudewijn indicated, these make up the bulk of the current code.

Task: benchmarking serialisation using capnproto and encoder/decoder.py for tunnel community.

**Comment by lfdversluis** [comment]
I think this issue can be closed as @qstokkink has implemented a protobuf oriented solution. Capnp is not available on the official repos and can therefore not be used.
