### ISSUE TITLE
Tribler uses a lot of CPU on Mac OS X

### ISSUE THREAD

**Issue by LipuFei** [Tribler/tribler#680]
System: Mac OS X 10.8.5
Processor: 2 GHz Intel Core 2 Duo
Memory: 4 GB 1067 MHz DDR3

Tested with branch e5d1f3bf51a220815628959a1b538cc395038a97. The GUI response is often very slow.

![screen shot 2014-07-08 at 3 09 07 pm](https://cloud.githubusercontent.com/assets/2630468/3509963/85868eb4-06a1-11e4-92ad-7a0d23b79f0b.png)

**Comment by synctext** [comment]
About Tribler 6.2 closing...
