### ISSUE TITLE
Ability to seed more than 5 torrents at a time

### ISSUE THREAD

**Issue by absolutep** [Tribler/tribler#6801]
**Is your feature request related to a problem? Please describe.**

Seeding is limited to only 5 torrents at a time.

Which is detrimental to torrents because there are no settings to disregard - slow speed seeding torrents(ex - 2kBps torrent) which are inadvertently included in set of 5 maximum torrents being seeded.

This poses an issue where a torrent which can be seeded at 50kBps cannot enter the seeding pool because it is being crowded by, slow torrents(ex - 2kBps speed ones) and thus disregards the potential seeding order.
Very bad for seeding torrents.

**Describe the solution you'd like**

**There should be a settings option which will allow simultaneous seeding of more than 5 torrents** or there should be an option to disregard slow speed seeding torrents by a stipulated speed limit ( **as shown in the screenshot**)
![Untitled](https://user-images.githubusercontent.com/97702149/156915848-be417273-7296-4a24-8722-68ae604841a0.png)

**Comment by devos50** [comment]
Thank you for your report/suggestion. By default, Tribler (and `libtorrent`, the torrent library used by Tribler) should not limit the number of torrents that are seeding simultaneously. If you go to 'settings', the setting 'unlimited seeding' should be turned on (in the 'seeding' tab). Could you verify if this is the case for your Tribler instance?

**Comment by absolutep** [comment]
> If you go to 'settings', the setting 'unlimited seeding' should be turned on (in the 'seeding' tab).

unlimited seeding is turned ON

**Comment by absolutep** [comment]
Here is the screenshot of the issue
![Untitled](https://user-images.githubusercontent.com/97702149/156925123-c128d2bb-fbe1-4ea6-900c-cf9d4466c019.png)


It does not matter if I use anonymous mode or non-anonymous mode. It never works for more than 5 torrents.

**Comment by qstokkink** [comment]
There are settings in `libtorrent` that limit the number of seeded torrents. We/someone should double-check that the `libtorrent` configuration's `active_seeds` and `active_limit` are set to something sensible in the "normal Tribler" configuration, like they are set for the `seedbox/seeder.py` script:

https://github.com/Tribler/tribler/blob/52bbf04454fc893a372343079ee4b03fba4a641d/src/seedbox/seeder.py#L179-L182

On a side note, exposing `high_performance_seed()` to users through the Tribler config screen may also be interesting.

**Comment by absolutep** [comment]
**This is right now**

![Untitled](https://user-images.githubusercontent.com/97702149/157022840-1a1b261c-6aad-4a8c-8fc2-1cd53941b15e.png)

**Comment by absolutep** [comment]
Problem I am facing currently is 

Torrents who are 10gb or higher are always given priority than torrents who are 2-4gb.

**Even though those torrents are new & high in demand**

![Untitled](https://user-images.githubusercontent.com/97702149/158049637-2a013407-0cde-4bb4-af05-62de5b53539c.png)

**Comment by absolutep** [comment]
any update on this?

**Comment by qstokkink** [comment]
I double-checked my previous answer with the [libtorrent docs](https://www.libtorrent.org/reference-Settings.html). The default value for `active_seeds` is set to `5` and Tribler's `DownloadManager` does not edit this value.

Actually, I guess all of the `libtorrent` session customization can be exposed to the GUI:

<table border="1" class="docutils">
<colgroup>
<col width="59%">
<col width="16%">
<col width="24%">
</colgroup>
<thead valign="bottom">
<tr><th class="head">name</th>
<th class="head">type</th>
<th class="head">default</th>
</tr>
</thead>
<tbody valign="top">
<tr><td>active_downloads</td>
<td>int</td>
<td>3</td>
</tr>
<tr><td>active_seeds</td>
<td>int</td>
<td>5</td>
</tr>
<tr><td>active_checking</td>
<td>int</td>
<td>1</td>
</tr>
<tr><td>active_dht_limit</td>
<td>int</td>
<td>88</td>
</tr>
<tr><td>active_tracker_limit</td>
<td>int</td>
<td>1600</td>
</tr>
<tr><td>active_lsd_limit</td>
<td>int</td>
<td>60</td>
</tr>
<tr><td>active_limit</td>
<td>int</td>
<td>500</td>
</tr>
</tbody>
</table>

**Comment by qstokkink** [comment]
I just double-checked with the latest code on the `main` branch. The limits I posted before are not in effect. Perhaps they were when this issue was created? However, in the next release (8.0) this should be resolved.

**Comment by qstokkink** [comment]
It can happen that people don't want to download from you. That is not a bug in Tribler's code. Here's a selection of my torrents: for some torrents there are also no people that want to download from me and for others they do.

![](https://github.com/user-attachments/assets/f7370e3b-883d-4df8-b23e-cd8bc3442aec)
