### ISSUE TITLE
Add info about stopped/finished downloads in logs

### ISSUE THREAD

**Issue by setaur** [Tribler/tribler#6843]
**Is your feature request related to a problem? Please describe.**
I'm trying to build some kind of notification script (via telegram/email) for when a download is finished. If #2901 was finally introduced, that wouldn't be a problem, but without it I have to improvise something else.

**Describe the solution you'd like**
It would be very useful for me to have information about the finished download in the logs. When download is started there is a line in the logs, e.g.:
```
INFO:DownloadManager:Start handle. Download: Download <name: 'b'debian-11.2.0-amd64-DVD-1.iso'' hops: 0 checkpoint_disabled: 0>. Atp: {'save_path': '/home/bart/TriblerDownloads', 'storage_mode': libtorrent.storage_mode_t.storage_mode_sparse, 'flags': 208, 'ti': <libtorrent.torrent_info object at 0x7ffa5855c0f0>, 'resume_data': b'd11:file-format22:libtorrent resume file12:file-versioni1e9:info-hash20:\xc9\xa37V,\xb06\x0f\xd6\xf5\xab@\xfd+\x1b\x81\xd52]\xbde'}
```
But when download is finished, there is none indication about it in the logs. I don't think it would be a big burden to implement something like this? :)

**Comment by drew2a** [comment]
@setaur a PR with the requested feature will be merged soon.

Please take a look at the output:
```python
INFO - Download(257) - On state changed alert: ubuntu-14.10-server-i386.iso: state changed to: finished
INFO - Download(408) - On torrent finished alert: ubuntu-14.10-server-i386.iso torrent finished downloading
INFO - Download(257) - On state changed alert: ubuntu-14.10-server-i386.iso: state changed to: seeding
INFO - Download(276) - On save resume data alert: ubuntu-14.10-server-i386.iso resume data generated.
```

**Comment by setaur** [comment]
Yeah, that would work great for me. Thank you!
