### ISSUE TITLE
Tribler 12 Alpha Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#6892]
Latest Alpha release of April 3th 2022. Windows 11 defender comes up with threats of a Trojan horse in Tribler.

**Comment by Nubro01** [comment]
I meant Tribler 7.12

**Comment by kozlovsky** [comment]
Thank you for the reporting! Can you provide a link to the executable you refer to? Is it 32-bit or 64-bit?
We use PyInstaller to make a binary; it is known for PyInstaller to produce a binary that is falsely reported as infected by some antiviruses (see #5979).

For the release candidate, we'll check that the binary is safe. Alpha releases are for internal testing and are not checked as thoroughly to speed up the build process.

**Comment by drew2a** [comment]
@Nubro01, hey, could you please check the latest version 7.13? Is the warning still there?

[https://github.com/Tribler/tribler/releases/tag/v7.13.0](https://github.com/Tribler/tribler/releases/tag/v7.13.0)

**Comment by drew2a** [comment]
This issue should be fixed in `7.13.0`. However, the newer one has occurred: 
- #7929
