### ISSUE TITLE
tribler update to 7.11.0 failed

### ISSUE THREAD

**Issue by jeffree128** [Tribler/tribler#6906]
update failed  with error response as follow

: Download is performed unsandboxed as root as file '/home/motrend/tribler_7.11.0_all.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: 拒絕不符權限的操作)

E: Sub-process /usr/bin/dpkg returned an error code (2)

**Comment by drew2a** [comment]
@jeffree128 thank you for reporting this behavior.

Could you please add log files to this issue? Otherwise, it is not possible to reproduce and fix a bug.
