### ISSUE TITLE
Lower support

### ISSUE THREAD

**Issue by FITFC** [Tribler/tribler#6911]
Hello, I was testing Tribler on an old laptop with a resolution of 1366x768 and Tribler was very strange in that resolution, would it be possible to add support or fit it better in this type of resolution?

**Comment by drew2a** [comment]
@FITFC thank you for your suggestion. I'm wondering whether your issue is a duplicate of https://github.com/Tribler/tribler/issues/6973 or not.

If it is, could you please try Tribler from the main branch and confirm that it is fixed (or not fixed)?
