### ISSUE TITLE
7.12 rc-1 -  are all of us exit nodes by default in this new version?

### ISSUE THREAD

**Issue by absolutep** [Tribler/tribler#6926]
**Describe the bug**

Under anonymity section there used to be the option to check/uncheck to become exit node.

Cannot find it in this new version 7.12.0 rc-1. Can't find it in debug option.

Has tribler made everyone exit node by default or can we still choose between becoming one or not?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Tribler's version 7.12.0 rc-1

**Comment by kozlovsky** [comment]
Hi! It is the other way around - we delete the option in #6736 to prevent the possibility that a user enables the option without understanding all the consequences. If someone wants to be an exit node, he should explicitly run a separate script [run_exit_node.py](https://github.com/Tribler/tribler/blob/676e02d851f59e367ecf8143a7ff331154c6a7e2/scripts/exit_node/run_exit_node.py)

**Comment by absolutep** [comment]
Isn't this bad for seeding/uploading now?

Since, everyone is only a relay by default with no easy to use option to change into exit node.

Most people won't even run the script due to extra steps involved.

**The option to check/uncheck was far easier to use** or atleast to try the exit node option.

**Comment by absolutep** [comment]
reminder for tribler team

**Comment by devos50** [comment]
> Since, everyone is only a relay by default with no easy to use option to change into exit node.
>
> Most people won't even run the script due to extra steps involved.
>
> The option to check/uncheck was far easier to use or atleast to try the exit node option.

There are indeed extra steps involved now to enable the exit node functionality. However, since running an exit node can be a severe liability in some jurisdictions, we do consider this as a good and meaningful feature. Enabling an exit node is not something we want our users to play with.

We also see that dedicated users who wish to contribute to the network by running an exit node are willing to change their Tribler configuration. In fact, our network right now is supported by hundreds of exit nodes, donated by volunteers.

**Comment by absolutep** [comment]
I understand the legal concerns arising due to becoming an exit node.

My main concern is seeding.

With more than 95% of users not having an option to become exit nodes. Won't it affect the ability to seed?

**Comment by devos50** [comment]
> My main concern is seeding.
>
> With more than 95% of users not having an option to become exit nodes. Won't it affect the ability to seed?

To correctly seed a torrent, a node doesn't have to be an exit node, regardless of whether one has anonymity enabled or not. So this wouldn't affect the ability to seed for end users.

**Comment by absolutep** [comment]
> To correctly seed a torrent, a node doesn't have to be an exit node, regardless of whether one has anonymity enabled or not. So this wouldn't affect the ability to seed for end users.

oh okay. thank you

**Comment by pasabanov** [comment]
> If someone wants to be an exit node, he should explicitly run a separate script [run_exit_node.py](https://github.com/Tribler/tribler/blob/676e02d851f59e367ecf8143a7ff331154c6a7e2/scripts/exit_node/run_exit_node.py)

The script is now removed. How can one run an exit node now?
