### ISSUE TITLE
Student master proposal: Solving Sybil attacks in Gitcoin Grants 2.0

### ISSUE THREAD

**Issue by llegard** [Tribler/tribler#6939]
**Feeding graph analysis into the model of quadratic funding to determine Sybil attacks or colluding behaviour.**  

Gitcoin is a system which divides a few million Euro in grant money for open source coding. Gitcoin is actively experimenting with digital democracy, and solutions that can foster the wisdom of the crowds to determine best way of fund distribution.[Gitcoin](https://gitcoin.co/)
 
One of the key mechanisms in the distribution of grants is via the formula of Quadratic funding, which tries to prioritise votes that have a diverse backing, rather than simple one person one vote scheme. See this link for a shirt read: [Quadratic Funding](https://gitcoin.co/blog/gitcoin-grants-quadratic-funding-for-the-world/) 

However the mechanism of quadratic voting has a distinctive problem of Sybil attacks. 

![maxresdefault](https://user-images.githubusercontent.com/57622550/174306304-33a1c2da-6462-42d0-abda-f96b24c9e646.jpg)

To tackle this problem, Gitcoin is coming with new mechanism one of which is an identity linked to Ethereum address enriched with several verifiable credentials, based on the existence of different accounts, for identity holder. e.g. Google account, Twitter accounts, etc. These credentials are deployed on a [Cermic](https://ceramic.network/) and use IPFS. See the [Gitcoin passport docs](https://docs.passport.gitcoin.co/) for more details.
 
You are provided with datasets from past Gitcoin grants which include participation and data with DIDs, including different credentials. The research problem is to: 

- Analyse quantification of data, to determine what type of credentials can accurately reflect social relations;

- How to score different credentials in this passport in order to indicate Sybil attacks and possibly colluding behaviour; 

- What types of credentials should go into the function that increase or decrease the weights of votes. 

One of this bullet points can be chosen as a narrow focus of the research.

The research is located in Berlin, but can also be hybrid (online/physical). You will be supervised by a Tribler Lab and Gitcoin researcher as official advisor.

### Relevant Literature
- [Overview of our efforts on Sybil Resistance and reputation](https://github.com/Tribler/tribler/issues/31).
- [Foundations of Peer-to-Peer Reputation](https://dl.acm.org/doi/10.1145/3428662.3428790).
- [SybilRes: A sybil-resilient Flow-based decentralized reputation mechanism](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=6257993).
- [TrustChain: A Sybil-resistant scalable blockchain](https://www.sciencedirect.com/science/article/pii/S0167739X17318988).
- [Achieving Sybil-Proofness in Distributed Work Systems](https://pure.tudelft.nl/ws/portalfiles/portal/96914542/p1263.pdf).
- [Improving Efficiency and Fairness in P2P Systems with Effort-Based Incentives](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=5502544).

**Comment by synctext** [comment]
No students has shown interest, please re-open if needed
