### ISSUE TITLE
Watch folder downloads are not started anonymous.

### ISSUE THREAD

**Issue by a-t-0** [Tribler/tribler#6940]
**Describe the bug**
If a `.torrent` is loaded from a watch folder, it will start with the anonymous setting to: `no`, and the number of hops set to `-`, even though the `~/.Tribler/7.12/triblerd.conf` contains:
```
[watch_folder]
    enabled = True
    directory = /home/name/some_folder

[api]
    http_enabled = True
    http_port = some_port
    key = some_key

[download_defaults]
    number_hops = 2
    seeding_mode = ratio
    seeding_ratio = 5.0
```
This is because the `WatchFolder` object loads the `tribler/tribler_source/tribler/core/components/libtorrent/download_manager/download_config.spec` instead of the `~/.Tribler/7.12/triblerd.conf` file.

**To Reproduce**
On Ubuntu 22.04 
0. Download [this](https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Build-Ubuntu64/522/artifact/tribler/build/debian/tribler_7.12.0-alpha.4-3-g0fb222e62_all.deb) `.deb` file to run Tribler. That version 7.12.0-alpha.4-3
1. And install it.
2. Go to:
```
~/.Tribler/7.12/
```
3. Open `triblerd.conf` and append:
```
[watch_folder]
    enabled = True
    directory = /home/some_name/some_folder

[download_defaults]
    number_hops = 2
    seeding_mode = ratio
    seeding_ratio = 5.0
```
4. Save the config file. Then copy a `.torrent` file, like [this one](https://releases.ubuntu.com/22.04/ubuntu-22.04-desktop-amd64.iso.torrent) for the Ubuntu 22.04 operating system into `/home/some_name/some_folder/`
5. Start up Tribler.

**Expected behavior**
I would expect Tribler to start downloading the Ubuntu Operating system torrent with settings: Anonymous: `yes` and `number of hops = 1`.

**Desktop:**
 - OS: Ubuntu 22.04
 - Tribler's version: 7.12.0-alpha.4.3-g0fb222e62]

**Additional context/speculation**
I thought perhaps it is because the `WatchFolder()` object [takes the `DownloadManager` as argument](https://github.com/Tribler/tribler/blob/c54b54fcda9b5f576652e68ba17f6aaa180a8220/src/tribler/core/components/watch_folder/watch_folder_component.py#L17) from `libtorrent_component` in line `download_manager=libtorrent_component.download_manager`. This `libtorrent_component` in turn seems to take the `download_defaults` as `config`, over [here](https://github.com/Tribler/tribler/blob/c54b54fcda9b5f576652e68ba17f6aaa180a8220/src/tribler/core/components/libtorrent/libtorrent_component.py#L27). I thought those `download_defaults` for `libtorrent_component` may be the defaults specified in [here](https://github.com/Tribler/tribler/blob/c54b54fcda9b5f576652e68ba17f6aaa180a8220/src/tribler/core/components/libtorrent/settings.py#L52) or [here](https://github.com/Tribler/tribler/blob/c54b54fcda9b5f576652e68ba17f6aaa180a8220/src/tribler/core/components/libtorrent/download_manager/download_config.spec#L2). 

However, I was not quite sure where this `anonymous = no` setting exactly comes from because I did not quite know how where the `self.session.config` comes from within [libtorrent](https://github.com/Tribler/tribler/blob/c54b54fcda9b5f576652e68ba17f6aaa180a8220/src/tribler/core/components/libtorrent/libtorrent_component.py#L13).

So I tried changing the `download_config.spec` setting to `hops = integer(default=2)` and saw that the download settings was set to anonymous with 2 hops. This confirmed the hypothesis that the `WatchFolder` object uses the `download_config.spec` configuration, instead of the `Triblerd.conf` settings.

I would expect users would expect their settings for Tribler to be applied to `.torrent` files that come out of a watch folder. So I would be in favour of changing the behaviour of Tribler to apply its `Tribler.conf` settings to the `.torrent` files that are loaded through a watch folder/black hole.

**Comment by drew2a** [comment]
@a-t-0 thank you for this bug report!

Possible duplicate of #6842

**Comment by a-t-0** [comment]
@drew2a thank you for your quick response. This issue is indeed a duplicate of #6842. I can confirm the `main` branch commit sha 898bc063bf1c6ef488cc9e2b04f065d2a33b1d1c, which builds upon [your pull request](https://github.com/Tribler/tribler/pull/6863/files) into main, has resolved this issue. 

The main branch indeed uses the Tribler anonymity configuration settings and hops for `.torrent` files that are loaded from a watch folder.
