### ISSUE TITLE
Layout and sorting are not kept over restarts

### ISSUE THREAD

**Issue by dertuxmalwieder** [Tribler/tribler#6972]
**Describe the bug**
I sort my active downloads by progress and my completed downloads by date (so downloads finished today are always at the bottom of the list, as sorting is not applied to new items automatically). I also make the torrent name column wider. When I restart Tribler, however, all sorting and column widths are reset.

**To Reproduce**
1. Change sorting and/or layout of Tribler windows.
2. Restart Tribler.

**Expected behavior**
Sorting and column widths are saved and restored on restarting Tribler.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Tribler's version 7.12.0-RC3 (but the error has been there as long as I've used Tribler).

**Comment by absolutep** [comment]
check #6791 
similar issue and answer provided by tribler team

**Comment by devos50** [comment]
Thank you for your report. Tribler indeed does not currently save the width of columns, nor the sorting properties. Since this issue is already described in #6791, I'm closing this one. Feel free to continue the discussion on the existing ticket 👍 .
