### ISSUE TITLE
Show used ports in settings

### ISSUE THREAD

**Issue by Griss168** [Tribler/tribler#6998]
Please, can be add somewhere in setting tab and JSON API what IP Ports Tribler actually use for communication?

Tribler is based on Torrent protocol and for establishing communication between two peers is necessary, that one of them would have public IP. But a lot of users are behind NAT and need to set up port forward in router.

My use case:
I want distribute Tribler channel, that is not well-known. Tribler channels are distributed by standard torrent protocol like ordinary torrent. If they don't have enough seeders, they need someone, who seed it long time (24/7) and for easiest distribution also with public IP. I use for that Raspberry Pi Zero 2, but is hard to determine, what ports need to be forwarded in router. Tribler use UPnP, but there are some issues like when You are behind double NAT or if Your router don't have UPnP like OpenWRT or if You want use VPS....

Please add somewhere in settings and API list of used ports. And would be nice if user can also define these ports.

Thanks and sorry for my English

**Comment by drew2a** [comment]
Hi, @Griss168, sorry for the late reply.

There are two ways you can seed torrents in Tribler:

1. **Anonymously**: You will use [Tunnels](https://github.com/Tribler/tribler/wiki/Anonymous-Downloading-and-Streaming-specifications) for routing and encryption. In this case, the setting you are looking for is the ipv8 port: [IPv8 Settings](https://github.com/Tribler/tribler/blob/main/src/tribler/core/components/ipv8/settings.py#L27).

2. **Non-anonymously**: You will use pure libtorrent. In this case, the setting you are looking for is the libtorrent port: [Libtorrent Settings](https://github.com/Tribler/tribler/blob/main/src/tribler/core/components/libtorrent/settings.py#L26).

You can specify these settings in `triblerd.conf`, which is basically an `ini` file. You can find this file in the Tribler state directory (for macOS and Ubuntu it is `~/.Tribler/<version>`, for Windows it is `%Appdata%/.Tribler/<version>`).

It is also possible to set the following environment variable to specify the Tribler state directory: `TSTATEDIR`.

An example of `triblerd.conf`:
```
[libtorrent]
    port = 7759

[ipv8]
    port = 7760
```

Regarding the channels, they are no longer supported: 
- #7669

Regarding the GUI, we can redesign the settings representation, but there is an [upcoming migration to WebView](https://github.com/Tribler/tribler/issues/7736#issuecomment-2097909642). Therefore, it is not a good time to make any changes to the current GUI.

Regarding the necessity for a public IP for one of the two peers to communicate in Tribler, it is not mandatory. Both peers can have private IPs, and their communication will still be successful.

>IPv8 can establish direct communication in difficult network situations. This includes connecting people behind a NAT or firewall. IPv8 includes a single simple and effective NAT traversal technique: UDP hole-punching. This is essential when offering privacy without infrastructure and consumer-grade donated resources.

https://github.com/Tribler/py-ipv8

For the BitTorrent protocol, this is also true, as far as I know. It is easier to seed if you have a public IP, but it is not mandatory. For example, both peers can still establish a successful connection and share data even with private IPs: http://bittorrent.org/beps/bep_0055.html

@qstokkink please, correct me if I'm wrong.

**Comment by qstokkink** [comment]
This question seems to be comprehensively answered. I'll close this issue now.
