### ISSUE TITLE
Error on startup: `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by Davem734** [Tribler/tribler#7030]
Using: 
  Ubuntu 18.04.6 LTS

Installed:
  tribler_7.12.1-RC2_all.deb

Error on startup:
  $ /usr/share/tribler/tribler
  [24775] Error loading Python lib '/usr/share/tribler/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/tribler/libpython3.8.so.1.0)

My understanding is that the highest version avalable on Ubuntu 18.04.6 is `GLIBC_2.27'

**Comment by xoriole** [comment]
@Davem734 Ubuntu 18.04 is no longer supported in the release. However, you can try building from the source here: https://tribler.readthedocs.io/en/latest/building/building.html

**Comment by Davem734** [comment]
Thank you for your help.
I tried and there seems to be an issue at this step:

```
$ pip3 install --upgrade -r tribler/requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting aiohttp==3.8.1
  Downloading aiohttp-3.8.1-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)
.
.
.
Collecting netifaces==0.11.0
  Downloading netifaces-0.11.0-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (32 kB)
ERROR: Could not find a version that satisfies the requirement networkx==2.6.3 (from versions: 0.34, 0.35, 0.35.1, 0.36, 0.37, 0.99, 1.0rc1, 1.0, 1.0.1, 1.1, 1.2rc1, 1.2, 1.3rc1, 1.3, 1.4rc1, 1.4, 1.5rc1, 1.5, 1.6rc1, 1.6, 1.7rc1, 1.7, 1.8rc1, 1.8, 1.8.1, 1.9rc1, 1.9, 1.9.1, 1.10rc2, 1.10, 1.11rc1, 1.11rc2, 1.11, 2.0, 2.1, 2.2rc1, 2.2, 2.3rc3, 2.3rc4, 2.3, 2.4rc1, 2.4rc2, 2.4, 2.5rc1, 2.5, 2.5.1)
ERROR: No matching distribution found for networkx==2.6.3
```

**Comment by qstokkink** [comment]
Netifaces is no longer a hard requirement of Tribler and this issue should be resolved in the next release.
