### ISSUE TITLE
Lokinet support via plugin

### ISSUE THREAD

**Issue by absolutep** [Tribler/tribler#7031]
Lokinet is similar to Tribler as in both function sort of TOR-like.

I think it would be a great addition to anonymity aspect of Tribler.

**Comment by synctext** [comment]
Thnx @absolutep for this one. Good to read about this initiative! Duplicates a lot of our work and ideas.
Studied the website and docs: https://github.com/oxen-io/lokinet they are very honest and professional about their work. We have studied attack-resilience by building an explicit trust network for over 25 years (still ongoing :skull_and_crossbones:). They lack the scientific resources to work on Sybil attacks:
```The Tor network relies on volunteer-operated relays, with very little barrier to entry for operating a relay. As a result, the network is vulnerable to something called a Sybil attack, where an attacker initialises a large number of malicious nodes, eventually controlling enough nodes to give them control of the guard and exit nodes for a given target’s circuit. ```
