### ISSUE TITLE
build/debian/makedist_debian.sh: [Errno 2] No such file or directory: '.TriblerVersion'

### ISSUE THREAD

**Issue by LillyWho** [Tribler/tribler#7047]
From a fresh clone, the expected file doesn't exist, so the script ``build/update_version_from_git.py`` fails

``INFO:__main__:Arguments: Namespace(repo='.')
Traceback (most recent call last):
  File "/home/lilly/tribler/build/update_version.py", line 21, in <module>
    ref_name = Path('.TriblerVersion').read_text().rstrip('\n')
  File "/usr/lib/python3.10/pathlib.py", line 1132, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1117, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '.TriblerVersion'``

**Comment by LillyWho** [comment]
So the .TriblerVersion and .TriblerCommit files are missing because the script ``build/update_version_from_git.py`` doesn't exist anymore and ``build/update_version.py`` is expecting those files to be there when they aren't, and running it after creating empty files by that name does nothing.

Seems the build guide for Debian needs an overhaul

**Comment by xoriole** [comment]
@LillyWho The process of building Tribler for different operating systems was recently refactored and the step for generating the version from the latest git tag is separated. Further Linux build is done using Github Actions workflow. You can find out the build instructions here: https://github.com/Tribler/tribler/blob/main/.github/workflows/build_ubuntu.yml

To create the build locally, you'll need to run the following commands from Tribler project directory:
```bash
git describe | python -c "import sys; print(next(sys.stdin).lstrip('v'))" > .TriblerVersion

git rev-parse HEAD > .TriblerCommit

export "TRIBLER_VERSION=$(head -n 1 .TriblerVersion)"

./build/debian/makedist_debian.sh
```

> Seems the build guide for Debian needs an overhaul
Good point! the documentation should be updated here: https://tribler.readthedocs.io/en/latest/building/building.html

**Comment by LillyWho** [comment]
I did manage in the end by taking a mild guess at what those files should contain, pasting accordingly the version and commit and running again. Probably roughly the same as what you did there. Seems to me like the script needs to have that extra step added. That would make things easier.
