### ISSUE TITLE
Hide token balance statistics until the balance algorithm is fixed

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#7048]
The current formula for the token balance calculation leads to surprising results, where most Tribler users see a negative token balance even if they are "good citizens".

Only exit nodes can have a positive balance with the current Tribler implementation.

The balance the user sees should motivate him to some behavior that is desirable to a Tribler community. The current balance algorithm basically encourages a user to be an exit node. That contradicts the latest changes in Tribler when an option to become an exit node was removed to provide better safety for a user who does not understand the consequences of being an exit node.

For balance to be useful, it should use a different algorithm that encourages users to a helpful behavior. Probably it should be adding information about new popular torrents.

We should hide the token balance value until the balance algorithm is fixed to avoid user confusion.

**Comment by synctext** [comment]
Possibly completely different issue or related.
Freeriding prevention mechanism is kicking out some hardcore "TeraByte range" leechers. Perhaps these are actually victim of our inaccurate token balance bug. Or :sos:  we see a mix of 1) real freeriding, 2) real fraudster which misreport their balance, and 3) real TeraByte range leechers. No idea whats happening.
![image](https://user-images.githubusercontent.com/325224/191693617-0430a547-103f-4e48-a729-e61baee21c99.png)
