### ISSUE TITLE
AllChannels V2.0

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#705]
ToDo:
- New community identifier
- Public key inclusion enabled
- Cancel message enabled
- Disable (recursive)-Undo capability 

Crawl and re-insert all votes and channels. ~~Perhaps move from a pre-fix towards a post-fix. To facilitate improved scalability through decay.~~ See remarks below by Niels

We now do 94672 outgoing messages per hour (a few per second). 
![tribler_6 4pre_allchannel_94672_outgoing_packets_per_hour](https://cloud.githubusercontent.com/assets/325224/5366339/450df1e4-7ff3-11e4-991b-218a91392472.png)

**Comment by devos50** [comment]
@whirm maybe move this milestone to V6.6+?

**Comment by whirm** [comment]
@devos50 I guess,

@synctext ?

**Comment by qstokkink** [comment]
Duplicate of #3615 .

**Comment by ichorid** [comment]
Duplicate of #3615
