### ISSUE TITLE
New Conversion.py, lose thousands of lines of code

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#706]
The current code is very flexible: https://github.com/Tribler/dispersy/blob/devel/conversion.py

However, nobody needs this. It results in every community duplicating functionality.
Problematic are the poorly tested security features, such as [_decode_missing_proof()](https://github.com/Tribler/dispersy/blob/devel/conversion.py#L655)

**Comment by synctext** [comment]
Possible cleanup, after scalability is addressed: https://github.com/Tribler/tribler/issues/2039

**Comment by qstokkink** [comment]
[For now the allchannel, bartercast4, channel, demers and template communities have been ported.](https://github.com/qstokkink/tribler/tree/protobufserialization)
I am holding off on the multichain and tunnel community as they are still being edited.
Furthermore, I am holding off on the search community, as it would require major refactoring and should therefore probably have its own separate pull request. 

Should a review/pull request happen before or after on-the-wire backward compatibility has been implemented?

**Comment by qstokkink** [comment]
With IPv8 merged I consider this issue resolved: if you look at #3445 and #3462, you'll see a net loss of 5556 lines.

**Comment by qstokkink** [comment]
Correction: the net loss is now 12718 lines.
