### ISSUE TITLE
Cancel message, alternative for the costly Undo message

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#707]
The costly Undo message can be undone and is being Synced.
Cancel message is the light and simple version.
"everything minus the crazy code"
DO NOT, under any circumstance, use the sequence number!!!!

New feature for new communities such as Anonymousproxy and AllChannel 2.0 (#705)

**Comment by devos50** [comment]
@whirm we think this issue is something for the longer term.

**Comment by qstokkink** [comment]
This will be resolved with #3615 .
