### ISSUE TITLE
Tribler is asking to upgrade version too frequently.

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#7077]
> New version available
> Version 7.12.1 of Tribler is available.Do you want to visit the website to download the newest version?
> [Ignore] [Later] [OK]

I press "Later", expecting to see the notice again in a day or a week. But it seems to postpone it only by an hour or so.

**Comment by devos50** [comment]
Thanks for reporting! This seems to be a bit too aggressive indeed. We'll have a look at it.

**Comment by drew2a** [comment]
According to the code, the check should be postponed for 6 hours: 

https://github.com/Tribler/tribler/blob/c4d7d75a36bebd753d4573aeba9f21bc2e986fbd/src/tribler/core/components/version_check/versioncheck_manager.py#L15
