### ISSUE TITLE
Lost all torrents

### ISSUE THREAD

**Issue by absolutep** [Tribler/tribler#7098]
**Describe the bug**

This happened two days ago. I did not report it instantly as I was travelling and could not find time.

Everything was fine and working. I added 20 torrents to my channel and then buffering sign came, so I minimized and after sometime opened Tribler again.

It was still buffering so I clicked on DOWNLOADS, it still was buffering so I hit the quit button.

It did not quit properly and I had to force shutdown from Tribler button itself.

After sometime, maybe an hour or so, I opened Tribler.

All my torrents were gone and the torrents I tried to add to my channels, didn't add. 

**Expected behavior**

Tribler should have added my torrents (to my channel) and should not lose the torrents I was seeding.

**Desktop (please complete the following information):**

 - OS: [ Windows 10] up-to-date
 - Tribler's version [ 7.12.1]

**Comment by Windos-7** [comment]
Can confirm this, but my issue is slightly different. Everything's at 0% and trying to download (at a speed leaving the download finished within the next 20 years, no less), despite having been downloaded already. The files themselves are still there, like it suddenly isn't recognizing the files

**Comment by SmutnyStefan** [comment]
I stumbled upon a workaround - try moving storage someplace and then force recheck. DO NOT force recheck prior to moving storage, as it will invalidate all further attempts.  Still, ratio is lost anyway, no matter what.

**Comment by drew2a** [comment]
@absolutep @Windos-7 @SmutnyStefan thank you for letting us know about the problem.

Do you have a scenario in which this bug could be reproduced?

**Comment by drew2a** [comment]
@Windos-7 @SmutnyStefan unfortunately the behavior that you described is most likely another bug. 

Could you please open a separate issue to avoid interfering with the "lost all torrent" bug? Then it would be easier to investigate and fix the problem.

**Comment by drew2a** [comment]
The upcoming release [7.13.0](https://github.com/Tribler/tribler/milestone/43) should be more stable than the previous one. We have fixed quite a lot of bugs that could affect almost all parts of the Tribler app.

I hope the "force shutdown" issue is also gone.

**Comment by SmutnyStefan** [comment]
First, I am sorry as I am a non technical person so it is very hard for me to describe a bug in a way that could be useful, as I am often afraid that I might mislead you and add more unnecessary burden. I can onl describe a acertain behaviour the way I perceive it. When I incrementally updated to 7.13 going through all RCs when they were released I ended up with extremely slow speeds in the anonymous mode - like 1/10 of my normal anonymous mode speed. Trying to figure it out I encountered a suggestion on the forum to first try downgrading to the previous version that worked. When downgraded to 7.12 boom - all anonymous mode speeds are back. BUT alas the  download list is "reverted" as well - meaning I have a database from 7.12 and all the torrents and the progress added in 7.13 is lost, however minimal it has been.
To add even more confusion when I decided to go up and test the 7.13 again - the speeds are still slower than 7.12, and the torrents list did not come back, it is still from 7.12. Non anonymous mode is working fine
I really don't know what happened, but it seems a downgrade can somehow corrupt the torrent database and that 7.12 is faster in the anonymous mode. I' am staying with 7.12 for now

**Comment by drew2a** [comment]
@SmutnyStefan 
> When I incrementally updated to 7.13 going through all RCs when they were released I ended up with extremely slow speeds in the anonymous mode - like 1/10 of my normal anonymous mode speed.

We encountered the same. It will be fixed in `7.15` release.
- #7908


Regarding the original issue, this PR should solve it in `7.15` release as well:
- #7762
