### ISSUE TITLE
Sanity check reporter

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#710]
Bugs reports, segmentation faults and TraceBacks can be easier understood with additional information. However, we need to ensure that a sanity check report is limited in KByte size. This sanity check can also be added to the "debug screen".

Basic information:
- free disk space
- usage of multiple partitions or temporary drives
- memory usage
- size of SQL database
- Event scheduler
  - longest task
  - longest sprint of continous activity (back-to-back tasks)
  - longest Bloom create time
  - longest Bloom incoming processing time
  - longest re-scheduling time (planned vs. executed time)

**Comment by devos50** [comment]
It would be nice to automatically add these kind of statistics to the crash report or the debug panel. Note that some of the statistics above can already be observed in the new Tribler 7 debug panel.

**Comment by devos50** [comment]
I suggest that we start doing this now: there are some issues open for the Tribler 7.0 release and most of them are related to memory/CPU/file descriptor usage.

**Comment by qstokkink** [comment]
@devos50 can we close this?

**Comment by devos50** [comment]
I think we have most relevant data in the debug screen now.
