### ISSUE TITLE
/tmp .log file filling up disk

### ISSUE THREAD

**Issue by Davem734** [Tribler/tribler#7158]
Tribler 7.11.0

I am getting multi-gigabyte log files in the /tmp directory. Eventually they fill up the disk and crash my system (Ubuntu 18.04)

Is there any way to turn off these log files?
Limit their size?

**Comment by drew2a** [comment]
@Davem734 thank you for pointing this out.

We will include the fix (log size limitation) in the `7.13` release.

As a quick fix, you can just stop Tribler, remove all the logs, and run Tribler again.
