### ISSUE TITLE
Using the latest tag for the version on the builder scripts

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#7174]
Right now, we use `git describe` to get the version. Sometimes this can return the earlier version if the last annotated tag is older and the newer tags were not annotated.

> By default (without --all or --tags) git describe only shows annotated tags. 

> Tag objects (created with -a, -s, or -u) are called "annotated" tags; they contain a creation date, the tagger name and e-mail, a tagging message, and an optional GnuPG signature. Whereas a "lightweight" tag is simply a name for an object (usually a commit object).

At the current commit of main:
```bash
$ git describe
>> v7.11.0-RC1-908-g9aba4ae00

$ git describe --tags
>> v7.12.1-405-g9aba4ae00
```

Using `--tags` switch will return the last reachable tag irrespective of annotated or not which would be a better indication of the current version of Tribler.

Expected changes in:
- [x] Github workflows (`build_*.yml`)
- [x] Jenkins build jobs

References:
- https://git-scm.com/docs/git-describe
- https://git-scm.com/docs/git-tag

**Comment by drew2a** [comment]
I can implement the change for GitHub Actions.

**Comment by xoriole** [comment]
Jenkins build job is updated and the build artifacts show the correct version. 
https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Build/491/

![build-491-successful](https://user-images.githubusercontent.com/1442867/204515167-2cf325ea-5adc-4ff3-a388-d3579cf19b5a.png)
