### ISSUE TITLE
Disable request to fetch bandwidth statistics

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#7181]
Since bandwidth statistics are currently disabled and not shown on the user interface, it is better to have the timer call to fetch statistics to be disabled as well.

```yaml
GET 'http://localhost:52194/bandwidth/statistics'
```

Currently, it seems it is being called every minute.

**Comment by absolutep** [comment]
What about overhead?
Does this mean there are no overheads in Tribler?
