### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#7280]
Tested with latest and previous version, but since 3 days I do net get any statistics regarding seeds and peers. Is there a server down or does my provider block me? Since 12/12/2022 I have fiber from T-Mobile and been seeding and downloading at 400/400 :-) with every days seeders and peers, but that seems to have stopped.

**Comment by Nubro01** [comment]
Went back to version dd 09-01-2023 and all is fine again.

**Comment by synctext** [comment]
Thnx for helping!! bit of questions... statistics for swarms are down.. is that after a keyword search in the search results screen?
Which 'latest version' is broken?

**Comment by Nubro01** [comment]
The beta from Januari 9th and all of 19th of januari 2023. After normal startup so no seaarch. Version 7.13 and 7.12.1-491

**Comment by qstokkink** [comment]
This should be resolved in the upcoming 8.0 release.
