### ISSUE TITLE
msc placeholder: brainstorm on DAO, leaderless organisations, Cayman island, and understanding international grand challenges

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#7284]
TBM '_business school_' master thesis [within the EPA program (Master Engineering and Policy Analysis)](https://studiegids.tudelft.nl/a101_displayCourse.do?course_id=62437)
Q3: thesis preparation
Q4: thesis start (30 ECTS, 6 months) Completion target Q1, 15 Nov.
advisor2: ??[Nitesh Bharosa](https://www.tudelft.nl/tbm/onze-faculteit/afdelingen/engineering-systems-and-services/people/full-professors/profdrir-n-nitesh-bharosa)??

Brainstorm on direction. Trying to use your two talents; coding and policy analysis:
- tax evasion is a grand challenge
- self-owned [nature 2.0](https://blog.oceanprotocol.com/nature-2-0-27bdf8238071?gi=7998228c635c) with real DAO and tree ownership (drawback: many people don't understand the difference between art-installation-fake and [real Cayman island DAO](https://www.careyolsen.com/briefings/cayman-islands-foundation-companies-daos-defi-and-nfts) and official forest land registration record)
- DAO - future of the firm 
  - The robot economy
  - Automated economy, programmable economy
  - Full frontal megalomaniac: [fourth industrial revolution](https://lawjournal.ku.edu/wp-content/uploads/2019/12/V29_JournalOnline_Sulkowski_Web1.pdf)
- negative side effects of grand challenges: digitisation, [the end of work](http://pinguet.free.fr/rifkin1995.pdf), and robotisation
  - loss of societal cohesion
  - [super wicked problems](https://scholar.google.com/scholar?cluster=8714367581834129734&hl=en&as_sdt=0,5)
- [X] Alternative to extractive capitalism. non-profit, direct democracy, public infrastructure DAO (EPA-approved).
  - automated market regulations
  - [Externalities: Prices Do Not Capture All Costs](https://www.imf.org/external/pubs/ft/fandd/basics/38-externalities.htm)
  - [late-stage capitalism](https://en.wikipedia.org/wiki/Late_capitalism)
  - [The theory of institutional design](https://link.springer.com/content/pdf/10.1023/A:1004929415510.pdf)
  - build the actual future, disrupt capitalism
  - organising principle for economic activity **in general**
  - withstand the global financial system, legal challenges, vandalism, hacking attempts, survive, and even thrive
  - Sisko: capitalism-based market competes with self-regulating market 
  - Showcase alternatives to wealth extraction are possible
  - Requirements: United Nations - Report of the Secretary-General - Roadmap for Digital Cooperation
    - [The Digital Public Goods Alliance is a multi-stakeholder initiative with a mission to accelerate the attainment of the sustainable development goals in low- and middle-income countries by facilitating the discovery, development, use of, and investment in digital public goods](https://digitalpublicgoods.net/roadmap/)
    - [Financial Inclusion DPGs - Digital Public Infrastructures](https://digitalpublicgoods.net/DPGA_Financial-Inclusion-DPG-Technical-Assessment.pdf)
    - attempt at an [open source financial institution](https://mifos.gitbook.io/docs/payment-hub-ee/overview) for low-income countries
  - create the first self-regulated marketplace
    - possible practical experiment for thesis
    - pre-bitcoin idea of thesis advisor: [internet bandwidth as a currency](http://news.bbc.co.uk/2/hi/technology/6971904.stm)
    - [automated bandwidth API](https://sporestack.com/api_documentation/)
- DAO + [cultural heritage preservation](https://www.researchgate.net/profile/Stephane-Derrode-2/publication/280893389_Analysis_of_ancient_mosaic_images_for_dedicated_applications/links/55e6da4a08ae3ad5dab2a8bd/Analysis-of-ancient-mosaic-images-for-dedicated-applications.pdf)
  - [Cultural Heritage and the Future of DAOs - DAO or Never](https://dao-or-never.simplecast.com/episodes/cultural-heritage-and-the-future-of-daos-8h5DikBH)
  - [cultural objects and cultures](https://core.ac.uk/download/pdf/4813873.pdf)
  - [UNESCO: Concept of Digital Heritage](https://en.unesco.org/themes/information-preservation/digital-heritage/concept-digital-heritage)
  - [EU: Digital cultural heritage](https://digital-strategy.ec.europa.eu/en/policies/cultural-heritage)
  - [Internet Archive Projects](https://archive.org/projects/)

Practical target: at the end of your thesis preparation you have a written thesis proposal, 1 page problem description AND 3 screenshots of your ideal (DAO) implementation

**Comment by synctext** [comment]
Other [teams like Chia are also trying to implement](https://roadmap.chia.net/c/50-primitive-dao) DAO features which we have prototyped, our shared ownership of Bitcoins and voting.
```
This serves as the base primitive for DAOs on the Chia Network. This combined with other primitives will
allow varying types of differentiated DAO capabilities. For example, Chia can uniquely enable compliant
issuance and frictionless trading of DAO securities. With verifiable credentials, a DAO can issue governance
tokens, typically viewed as a security by the SEC, and limit access to accredited investors. On Chia, our
Offers primitive enables peer-to-peer trading of these securities and posting offers on a bulletin board,
unlocking a major limitation of security tokens. 
```

**Comment by sisko444** [comment]
Causal loop diagram of blockchain technology relevance in Engineering and Policy Analysis
![image](https://user-images.githubusercontent.com/33283063/222695332-a128abe6-49a2-48f3-8717-c882dfaf305d.png)

**Comment by synctext** [comment]
- You successfully navigated the GoNoGo thesis moment
- Great start of your thesis direction brainstorm. Its actually something we as Computer Science lack: linking self-organisation with the end of civilisation and democracy :beer:

**Comment by synctext** [comment]
- Not all courses finished to begin master thesis (manly due to dyslectic)
- New planning: wrap up courses in Q4. Start thesis in summer/Q1.

**Comment by sisko444** [comment]
Current status of thesis preparation text can always be seen on this read-only overleaf link: https://www.overleaf.com/read/wdxzrnfkggrg
As this is posted a general gist of the problem in the introduction is portrayed and a literature review of current literature regarding "blockchain technology decentralized governance" was done.
The approach is being formulated and the current idea is to develop a "traditional governance" and "blockchain governance" game. And compare the experiences and/or opinions of policy domain participants.

**Comment by synctext** [comment]
- no global digital governance
- problem and cure and mixed (central == fragile)
  - "Systems have a tendency to centralise."
  - Systems have a tendency to centralise.
  - Too-big-to-fail scenarios are a great source of damage to modern society.

**Comment by sisko444** [comment]
Dictating Dr. Johan Pouwelse:
# Thesis proposal session
## Smaller scoping
- Focus on things that can be implemented in android in allocated 20 weeks
- Experiment which we can learn from and observe and see many people voting and participating democratically  because its cool
- Allighnment with current thinking is decentralized redit tweakers post or twitter alternative
- Keep it small one app with integrated bitcoin buying through ideal
- No overengineering, only PHD has possibly the skills to make "the implementation of", minimal implementation.

## Ideas
- Colectively decide to buy a tor end node or mastodon node
- Sponsored decentralized twitter pull request
- Or donate to UN or FSF
- Decentralized reddit option, user revolt
- Who is the new boss of decentralized redit
- Tweakers decentrale voting 
- Constitution dao 
- Together sronger buying power governance 
- TBM dream politica versus the music dao infrastuctuur 1% beter maken 

## Suggestion
- Maybe dive into music dao, real music, really leaderless, forming groups
- Propose apps for thesis each with a gui desighn picture

#Wrap-up
I will get informed on the fomaltities and push forward with the start of the MSc thesis.

**Comment by sisko444** [comment]
Latest brainstorm addition: How to operationalize the musicDao for community elected software updates, in practice, not in the lab.

**Comment by synctext** [comment]
_brainstorm_ desired master thesis outcome, a 8-page IEEE 2-column report on arXiv with this storyline. See [format examples](https://arxiv.org/search/?query=pouwelse&searchtype=all). Open question: how to make this TBM faculty compatible. Goal is to enable computer science students to **immediately** start realising your prototype, expand MusicDAO tech stack, and fix scalability issues for planetary-scale deployment of this dream. :red_circle: 
### Web3: experimental democratic governance, funding model, and information architecture

We see increasing concentrations of power, wealth and power in advanced societies. Since the industrial revolutions we see a consistent increase in monopoly-dominated markets. This increasingly leads to a global crisis when disasters such as war and disease strikes. Capitalist societies are locked into an eternal cycle of market concentration, power polarization, monopoly-dominated markets, too big to fail, catastrophic collapse, chaos, and quick fixes based on central power.
Democracy and capitalism are currently firmly grounded in governments and firms. We present an operational proof-of-principle system which realises the old dream of global democracy and commons-based economics in which ruthless competition in replaced with relentless efficient cooperation. Decentralisation of power and wealth are the key organisational principle of our approach. By giving equal power to any participating citizen we design new types of global institutions, based on democratic governance.
Competition is breaking down in various markets, due to the level of centralisation.
We now specifically look at the failure of competition in digital markets.
A top-to-bottom review of the digital market by the [Subcommittee of the SA House of Representatives](https://www.govinfo.gov/content/pkg/CPRT-117HPRT47832/pdf/CPRT-117HPRT47832.pdf) examined the dominance of Amazon, Apple, Facebook, and Google, and their business practices to determine
how their power affects our economy and our democracy.
Their findings are that _By controlling access to markets, these giants can pick winners and losers throughout our economy. They not only wield tremendous power, but they also abuse it by charging exorbitant fees, imposing oppressive contract terms, and extracting valuable data from the people and businesses that rely on them. Second, each platform uses its gatekeeper position to maintain its market power. By controlling the infrastructure of the digital age, they have surveilled other businesses to identify potential rivals, and have ultimately bought out, copied, or cut off their competitive threats. And, finally, these firms have abused their role as intermediaries to further entrench and expand their dominance._
An analysis on a deeper level show this to be a failure of government regulation. Companies are under increasing competitive pressure. Ruthless companies have a competitive advantage, therefore only the ruthless survive. Competition is increasingly shifting from market-based competition to monopoly battles. Big Tech companies rely on a core market in which they have monopoly pricing power. This has been described as the [competition _for_ markets model](https://link.springer.com/content/pdf/10.1023/A:1027457020332.pdf) instead of the prior competition _within_ markets. Big Tech from an entrenched position occasionally launches a new market attack, for instance [Meta versus Twitter](https://papers.ssrn.com/sol3/Delivery.cfm/SSRN_ID4500582_code5653239.pdf?abstractid=4500582&mirid=1).

We present a decentralised alternative for the Big Tech monopolies and our general economy. In the 2030-2040 timeframe {in our dreams} we believe our presented decentralised approach can offer a superior alternative to rent-seeking platforms. Three cardinal problems are addressed in our proof-of-principle. First is the decision making process. Most experiments with online democracy have failed in the past decades. We believe generation Z has the required digital literacy and self-sovereign culture for online democracy to evolve. Clear evidence of the unique skills of the digital-first generations is their ability to type numerous words per minute on smartphones and quickly navigate apps. Generation Z is even [hoarding more gold when compared to boomers](https://uk.movies.yahoo.com/millennials-hoarding-more-gold-boomers-181301840.html?guccounter=1) due to their deep distrust and desire for autonomy. 
Second is our funding model for platform evolution and maintenance. Based upon incentive alignment and mechanism design we present a non-profit enhancement of the "freemium model". User who donate their time or computational resources to a decentralised commons-based economy obtain premium service from others in return. Donated resources are used to rework specialist workers which expand and evolve the decentralised ecosystem. Third is the information architecture for discovery of information, communities, and socio-economic interaction in general. We use a decentralised, permissionless, crowdsourced information architecture based on hashtags and sophisticated tooling for preventing duplicates, synonyms, pollution, and spam. Building a web-of-trust using tamper-proof accounting of past encounters with strangers is our solution to the Sybils, slandering, and other cyber attacks. See the work on MeritRank and Trustchain for details [[REF](https://arxiv.org/pdf/2207.09950)].

We extend past work called the MusicDAO which provides a fully operational music streaming services and artist investment token with academically-pure decentralisation. MusicDAO provides not only an alternative for Spotify, but also the music industry, Big Tech streaming cloud, and financial payment networks. It combines Bittorrent, Bitcoin, FROST threshold cryptography for [large-scale collective wealth](https://repository.tudelft.nl/islandora/object/uuid%3Af45f85a0-b634-43d9-bd18-2bd9398d2c13), and the IPv8 overlay (see the outdated [IPV8 IETF Internet Standards draft](https://datatracker.ietf.org/doc/html/draft-pouwelse-trustchain-01#section-4)). We extended MusicDAO with a proof-of-principle self-governance layer, based upon the existing DAO proposal voting mechanism. We conducted an expert consultancy of enhanced MusicDAO for feedback. Key question is if our proof-of-principle could possibly grow into a dominant economic paradigm, with characteristics from Linux and Wikipedia. Additionally, what could inhibit this envisioned future.
Finally, we conducted an experiment to demonstrate the viability of self-evolution, in principle. Within a small-scale live trail with a dozen volunteers we successfully paid a developer to fork the open source repository, craft a desired small new feature, and paid this developer without reliance on traditional banks. We believe a circular long-enduring Bitcoin-based economy is therefore possible.

Based upon: 
<img src=https://user-images.githubusercontent.com/33283063/222695332-a128abe6-49a2-48f3-8717-c882dfaf305d.png width=400>

**Comment by sisko444** [comment]
Additionally: A cardinal principle of economics is that more advanced technology requires more investment. For the past centuries since the industrial revolution the number of markets have greatly expanded, but the number of market players has consistently been reduced. Within the current digital age we see in many markets a winner-takes-all dynamic with almost no oxygen for the number two to even survive, let alone thrive. Digital institution building is therefore required, as market competition becomes a historic principle.

**Comment by sisko444** [comment]
Written project proposal for kick-off:
![image](https://github.com/Tribler/tribler/assets/33283063/2e6cf662-d93d-4be9-96d3-b0563848acc7)
[Project_proposal (2).pdf](https://github.com/Tribler/tribler/files/12791382/Project_proposal.2.pdf)

**Comment by synctext** [comment]
Missing elements is the language from a certain field. Don't pick your own language (monopoly premium versus WOPDI):
- Laywers with competition law
  - Example [The Antitrust Duty to Deal in the Age of Big Tech](https://www.yalelawjournal.org/article/the-antitrust-duty-to-deal-in-the-age-of-big-tech)
- Economists with platform capitalism
  - Example: [Google, Facebook, Amazon, eBay: Is the Internet driving competition or market monopolization?](https://link.springer.com/article/10.1007/s10368-013-0247-6)
- Nerds with Web3 lingo
  - example: https://the-looking-glass.mirror.xyz/cEqHyzaripXnY9W4HxfcSo5zEjgV7BpK0_Q5kjGeElk

**Comment by sisko444** [comment]
A possible trajectory right now could be to find a recommended mode of governance for the music dao use case: roadmap/proposals versus compromise seeking resolutions, for instance.
The meriad of decentralised coordination protocols for their own purposes can be analysed aswell as the need for coordination and consensus in the market Music DAO wants to adress can be analysed leading to a recomended mode of goverenance for Music DAO.
