### ISSUE TITLE
Ubuntu sway remix (Wayland): tribler don't work

### ISSUE THREAD

**Issue by 1AntonioOrlo1** [Tribler/tribler#7291]
At old version (7.7.1) i only have taskbar indicator, but no any window
At new version (7.12.1) i have nothing after tribler start

mmn@mmn-ubuntu-pc: ~$ tribler
Starting Tribler...
/usr/share/tribler ~
mmn@mmn-ubuntu-pc: ~$ so it don't work =(

**Comment by drew2a** [comment]
@1AntonioOrlo1 could you please add more information to the issue? Such as OS version and Tribler logs (or a part of them)? Otherwise, it is quite hard to understand the behavior behind the described issue.

**Comment by qstokkink** [comment]
In the upcoming 8.0 release, this should hopefully be resolved.
