### ISSUE TITLE
Blockchain Engineering 2023 - token transaction engine

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#7293]
Token transaction engine. Create a lightweight and fast token transaction engine for mobile devices. Your engine should be able to process 1000 transactions per second with standard 4G connectivity. Record these transactions within a simple SQLite backend. Realise simple primitives such as send/receive token primitives. Required background reading: [ConTrib: Universal and Decentralized Accounting in Shared-Resource Systems](https://dl.acm.org/doi/pdf/10.1145/3428662.3428789).

**Comment by synctext** [comment]
Not yet read the required background reading.
@kandrio checked out the superapp, confused about the modules.

**Comment by AkiSchmatzler** [comment]
## meeting with @kandrio , @mehulbhuradia , and myself
 * trying to compile the skeleton in Android Studio
 * do we need to care about signing in users to the network?
 * look at the example trustchain docs linked previously --> *every block contains exactly **one** transaction* 
 * TrustChainCommunity based transactions --> use of proposal block and agreement block for the transaction *(see doc)* (we have to see if this is feasible for our 1000 transactions per second requirement, but it sounds like a good idea to have transaction be secure and avoid fraud (see detailed description below)
 * upon completion of a transaction, how do we let everyone on the network know?


### transaction possible implementation
*from the example trustchain docs*

Initiator creates a proposal halfBlock, signs it with his private key, creates the wrapper halfBlockBroadcast that contains the proposal block. He sends the broadcast to everyone. The receiver (the one which the transaction is intended for) creates an agreement block (AgreementHalfBlock), they sign it. Then, they put the proposal and the ageeement in a block *(halfBlockPair)* (which represents the completed transaction) and broadcast it to the network *(halfBlockPairBroadcast message)*. The fact that everyone in the network is aware of every step of the transaction (broadcast of proposal and agreement) assures its integrity.

**Comment by synctext** [comment]
- Please no [analysis paralysis](https://www.reddit.com/r/getdisciplined/comments/2mno37/needadvice_how_to_beat_the_ghost_of_analysis/), just dive in and make initial throw-away code.

**Comment by AkiSchmatzler** [comment]
this link contains all the stuff we need to create our community and send our messages over the network : [overlay kotlin ipv8](https://github.com/Tribler/kotlin-ipv8/blob/master/doc/OverlayTutorial.md)

**Comment by kandrio** [comment]
# First Iteration on Transaction Engine

@luukvancampen mainly got his hands dirty with the code in the weekend. At the current state, our app is able to:
1. Present a list with all the peers in the community.
2. Allow the user to choose one peer and send a transaction proposal to that peer
3. Allow the user to receive a transaction proposal (through a pop-up) and confirm it through the click of a button.

_**NOTE**_: It seems that step 2 (sending of proposals) does not work consistently. We noticed that in some cases, the sender sends a proposal and no pop-up shows up in the receiver's device. We have been trying to debug this for hours, but no solution has been found yet. We could use some feedback on if this is expected and how to tackle it.

Development repo: https://github.com/luukvancampen/blockchain-engineering

**Comment by synctext** [comment]
Significant experience with @luukvancampen, the "1000" button is exactly what is needed.

**Comment by kandrio** [comment]
Next **internal** meeting: Wednesday, March 8th at 17:00

# To-do

Here are the next tasks we want to achieve:
1. make 2 emulators communicate with each other: @tudatt 
2. list in the application the bootstrap servers (if not, then the app is not properly connected) @kandrio 
3. check the PR the professor sent us and try to initialize the `community` as shown in the PR (https://github.com/ChrisSBras/trustchain-superapp/pull/4/files) @mehulbhuradia 
4. make 1000 transactions a second work using the new PR that the professor sent @luukvancampen 

@AkiSchmatzler has been a bit sick lately, so we'll sync on Wednesday and assign him with a task as well

**Comment by kandrio** [comment]
# Show Bootstrap Servers

I'll use this comment to expose my progress on extending the `Detoks` app to show the list of connected bootstrap servers.

Currently, this comment is almost empty, but I'll be updating it as find new things.

**Comment by kandrio** [comment]
# Confirm a `Proposal`

## Current Situation

Currently, the following happens:
- In the UI of the App, there is a button to confirm an incoming proposal
- When clicking on the button, an Agreement block is sent
- The button doesn't disappear when clicked.
- If the button gets clicked on again, the sender of the proposal errors out.

**Comment by AkiSchmatzler** [comment]
## about the bootstrap servers

In the bootstrap-servers branch of our development repo, I added a button bootsrap_servers, which when pressed opens a popup window showing the bootsrap servers : 

![slay](https://user-images.githubusercontent.com/65312113/224554343-4a6aa65a-63a7-4b94-b7b1-0b1b665e66a2.png)

**Comment by synctext** [comment]
- framegraph
  - block processing
  - crypto
  - networking delay and overhead
- [Python IPv8 documentation](https://py-ipv8.readthedocs.io/en/latest/) 
![image](https://user-images.githubusercontent.com/325224/224956215-693aa2af-a06f-4a01-aad2-159f997d887c.png)
- Solid progress. Nice bootstrap node inclusion.

**Comment by luukvancampen** [comment]
I made sure that the "1000" button works. It sends 1000 proposals to the specified peer and the peer signs them. The sender of the proposals then shows in the app how many agreements it has received and to what proposals the agreements are, so we can do basic packet drop detection. All proposals are assigned a number from 0 up until 999 in order to count received agreements. Each "benchmark run" get its own UUID so we do not accidentally count an agreement for the wrong benchmark.

**Comment by tudatt** [comment]
Progress last sprint cycle:

**Andrei (tudatt)**:
1. Implemented a "dummy node" in Kotlin, as `LightweightTxAppKt` that can be run seamlessly in the terminal
2. Added `TransactionEngine` API V1 and its implementation `TransactionEngineImpl` that can be extended by any Community, so it can benefit from `sendTransaction` functionality
3. Implemented functionality for sending encrypted/unencrypted blocks to specific/random peers in the `LightweightTxApp` using `TokenTransactionEngine`.

**Comment by kandrio** [comment]
Progress last sprint cycle:

**Kostas** (`kandrio`):
1. Worked on top of @tudatt's "dummy node" implementation and managed to make peers send basic messages to one another.
2. Integrated our progress with the *upstream* master.

**Comment by mehulbhuradia** [comment]
Progress last sprint cycle:

Mehul(mehulbhuradia):
Managed to get the python dummy nodes running but discarded the idea as @tudatt figured out a way to have them in kotlin and this allowed them to reuse existing code.
Worked on top of @tudatt's and @kandrio's implementation of the dummy nodes and the TransactionEngine adding the functionality to receive incoming messages and process them.

**Comment by AkiSchmatzler** [comment]
progress last week:

 * Research about flazmegraphs to profile our code, usage of [this repo](https://github.com/rschlaikjer/erlang-atrace-flamegraphs) to set up flamegraph generation based on CPU traces from an Android emulator.
 * trying to profile with flamegraphs the progress of the dummy nodes --> still to finish as there were some compatibility issues yet to resolve, but should be done in the next day.

**Comment by luukvancampen** [comment]
Luuks progress: 
- The other groups transaction engine now stores its blocks in TrustChain. It still works with their basic token object.

**Comment by synctext** [comment]
- https://stackoverflow.com/questions/59713887/socket-connection-between-two-emulators

**Comment by mehulbhuradia** [comment]
Tasks going forward: (meeting on 25/3/23)
1.  Create the transaction api using code from kandrio-dummy and other-group-progress
2.  Create a pr for the api
3.  Create flamegraphs
4.  Add UI for benchmarking
5.  Extend the API to search and view the blocks?

**Comment by kandrio** [comment]
Progress last sprint cycle:

**Kostas** (`kandrio`):
1. Created our first PR that introduces our `TransactionEngine` API and our `LightweightTxApp`:
    - https://github.com/Tribler/trustchain-superapp/pull/145
2. Addressed review comments.
3. Created review branch with improvements:
    - https://github.com/tudatt/trustchain-superapp/tree/kandrio-introduce-transactions-api-rev
4. Waiting for @OrestisKan follow-up review comments

**Comment by tudatt** [comment]
Progress last sprint cycle:

**Andrei (tudatt)**:
branch `benchmark`:
- created `TransactionEngineBenchmark` class which is to be used for all benchamrk workloads. Its responsibility is to set up benchmarking test cases and then evaluate `TokenTransactionEngine`'s `sendTransaction` functionality called with various parameters
- moved functions designed by @mehulbhuradia  and @luukvancampen in the `TransactionEngineBenchmark` class and added a few myself.
- you can see an example of how an app can call the benchmark functions in `LightweightTxApp.kt`


Questions: Right now we are only sending the block object `TrustchainBlock` because of the convenience of using the Builder. Should we consider creating our own, even simpler block?

**Comment by AkiSchmatzler** [comment]
Progress last sprint cycle.
We now have the falemgraphs for : 
 * unencryptedBasicSameContent bloks
 * unencryptedBasicRandom blocks
 * unencryptedRandomSigned blocks
 * unencrypted RandomSignedTrustchain blocks

We can now identify bottlenecks in those functions. The call to functions that have some pseudo-randomness in them seems to be a bottleneck at the moment.

**Comment by mehulbhuradia** [comment]
Progress last sprint cycle:

Mehul(mehulbhuradia):

1.  Designed the functions for the IPv8 layers in the flamegraph.
2.  Currently redesigning the message handlers to echo messages, these echo messages will be used to record the time taken for the blocks to be recieved and the number of packets lost.

**Comment by luukvancampen** [comment]
Luuks progress:
1. created functions for doing the first layers of benchmarking
2. created UI for benchmakring and made sure ui can be used to run the actual benchmarks.

**Comment by synctext** [comment]
- [ ] big milestone: running .APK on your issue
- [ ] [Example of great performance analysis at 6-levels of a protocol stack {raw sockets, IPv8-Kotlin+EVA}](https://repository.tudelft.nl/islandora/object/uuid:a048eb7d-9c9b-4e59-84f0-9fc76a4d8ee5/datastream/OBJ/download)

**Comment by luukvancampen** [comment]
Unpolished APK: https://luukvancampen.stackstorage.com/s/1RzuNuFYpzLYGrQH

The first few steps of benchmarking can be done and it shows the time in nanoseconds it took. When pressing the 1000 button for a peer, it starts a 1000 trustchain transaction benchmark. There are some bugs in that which I will resolve. 
You can also create a single transaction with a peer, which the other peer then has to confirm.

**Comment by AkiSchmatzler** [comment]
### about the flamegraphs: performance analysis

for signed permanently blocks,  time is equally divided between building the block and storing it in storage, there is not much to optimize here, except if we would try and rewrite the function from the Trustchain to not use `StringBuffer.append()`, as it seems to be the biggest bottleneck. For the SQL storage, the `getLatestQuery()` call seems to be the biggest bottleneck. (same goes for signed blocks that are not permanently stored). 
![image](https://user-images.githubusercontent.com/65312113/230590464-898a05c7-92d9-4a5e-b603-f4c36ba613ca.png)

--> todo: further analysis and write the results in the report, which needs to be linked in the readme

**Comment by luukvancampen** [comment]
Luuk's progress: 
- made UI for benchmarking the non-ipv8 steps. Graphs are generated for time per block, user is able to choose how many blocks to generate or choose an amount of time to run the benchmark for.
- Also possible to press a button to generate a comparison graph of the different IPV8 steps.

**Comment by kandrio** [comment]
Progress last sprint cycle:

**Kostas** (`kandrio`):
1. Addressed review comments for our 1st PR that introduces our `TransactionEngine` API and our `LightweightTxApp`:
    - https://github.com/Tribler/trustchain-superapp/pull/145
    - Waiting for @OrestisKan's follow-up review comments
2. 2nd PR underway that will introduce our entire backend
    - Will have it ready by Saturday 08/04/23

**Comment by synctext** [comment]
- Very happy with this teams progress
- 99.6 MByte .GIF demo, this is an absolute smashing size record :boom:

**Comment by InvictusRMC** [comment]
Hi team, can you please address the email that group II sent to you? Thanks!

**Comment by kandrio** [comment]
@InvictusRMC at what email did they send it?

**Comment by AkiSchmatzler** [comment]
> > @InvictusRMC at what email did they send it?
> 
> @kandrio apparently they only contacted @AkiSchmatzler on [aki.schmatzler@gmail.com](mailto:aki.schmatzler@gmail.com).

I answered the group earlier today w the method i followed; I told them to get back to me if they still any further issues

**Comment by luukvancampen** [comment]
Url to APK:
https://luukvancampen.stackstorage.com/s/1RzuNuFYpzLYGrQH

**Comment by kandrio** [comment]
`README` for presentation: 
- https://github.com/tudatt/trustchain-superapp/blob/kandrio-other-group-progress/detoks/README.md
