### ISSUE TITLE
Blockchain Engineering 2023 - Offline Token Money

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#7296]
Team issue for 10 weeks of blockchain engineering course at Delft University of Technology

**Offline token money.** Your task is to create easy payments using tokens, without Internet. Giving and receiving tokens should be easy and effortless. Special requirement is that it should also work in an emergency: when the Internet is down. Probably you need to use QR-codes scanning to move Tiktok Tokens between devices. The hard scientific task is to address the double spending risk. Required background reading from Delft: [Double spending prevention of digital Euros using a web-of-trust](https://arxiv.org/pdf/2204.06831.pdf).

- Discussed: 20 and 21 April (week 10) final meeting.
- {tentative} final project goal. Create token. Transfer token to another device. Some measure for double spending mitigation. 
- Prior work around Euro token transactions:
  - [digital Euro engine](https://github.com/Tribler/tribler/files/10721496/Performance_Analysis_of_an_Offline_Digital_Euro_Prototype_13_02_23.pdf) {thesis work, nearly finished, https://github.com/KoningR/eurotoken }
  - [Another digital Euro in trustchain-superapp](https://github.com/Tribler/trustchain-superapp#digital-euro)
  - [Github details of previous team: code, links, context, and comments](https://github.com/Tribler/tribler/issues/6785#issuecomment-1098918015)
- You can assume a central authority in the form of a "ECB Digital Euro Public Key", hardcoded public key. Not a central trusted server.
- First sprint goal: Show QR code, scan QR code (all this is already operational inside [Superapp](https://github.com/Tribler/trustchain-superapp/blob/master/valuetransfer/src/main/java/nl/tudelft/trustchain/valuetransfer/dialogs/QRCodeDialog.kt#L26)), copy inside [trustchain data structure](https://github.com/Tribler/kotlin-ipv8/blob/master/doc/TrustChainCommunity.md).

**Comment by gerbentimmerman** [comment]
Until 27/02/2023

Done:
- Compiled the app
- Got QR code via eurotoken app to run
- Some ideas to solve double spending problem



Ideas to solve double spending problem:
- Geo location restrictions
- 

Important terms:
- irrefutable proof of double spending
- Security deposit to have as collateral
-

**Comment by synctext** [comment]
- [Some background work we did](https://github.com/Tribler/tribler/issues/7296). _This double signature scheme acts as a nuclear backdoor for enforcing honest participation and preventing users from committing frauds as they essentially risk leaking their own private keys upon double spending._

**Comment by Robert-ML** [comment]
- investigate the icelandic bank with money transfer between bank account and blockchain address -> @gerbentimmerman 
- nuclear backdoor -> @Robert-ML 
- double spending colateral other's work, look into other approaches and ideeas that we might implement/steal/improve -> @naklecha
- set up a demo network to check how to send money, so in the end we have a token to work with. One looks in other apps in Tribler how they set up their network, one looks into Euro Token ECB. -> EuroToken @AdiDumi, @gerbentimmerman | other tokens (music app for example) @vick0088 
- use the halfblock structure for transactions, also how to populate the transaction structure later when we are back online, how to give information that is needed for the future transcations -> @naklecha, @Robert-ML
- A TASK FOR EVERYBODY -> how Android development works, how stuff is drawn on the display, how stuff is updated on the display: https://duckduckgo.com/?q=android+lifecycle+fragment&t=vivaldi&ia=web . Practically get some basic android development experience.

**Comment by synctext** [comment]
- Lets do a deliberately simple approach, fixed coin denomination: .1 Euro .5 Euro, 1 Euro, 2 Euro, 5 Euro, and 10 Euro. 
- Focus on double spending to the max.

**Comment by AdiDumi** [comment]
- [ ] Currently the app has one wallet, see if we can make multiple
- [ ] There is a shared public key option, can we make this private key as well
- [ ] Redeem private key money (does not need 2-3 but needs 1 so we can redeem money from a random private key)
- [ ] QR code to share private key
- [ ] UI Changes to it shows person sending their money

**Comment by Robert-ML** [comment]
[Promises Approach](https://github.com/Tribler/tribler/files/11012064/blockchain-promises_approach.pdf): devised a signature scheme so that a recipient can hold a sender accountable in case of not fulfilling its promise to send funds (completing the transaction) when he returns back online.

The app: we have a working app where the sender creates a promise which can be scanned and is verifiable proof that the sender has to send money to the recipient when they get back online.

TODOs:
- make the storage of promises persistent after app restart;
- as a sender: see transactions which you have to publish to the network (promises the sender did not yet fulfill);
- as a receiver: see transactions which were not yet published to the network (unfulfilled promises) and have the time since when the promise was created;
- make the offline money exchange more generic to be able to be easily integrated in other blockchains / communities / apps in the supper-app;
- start doing the web of trust approach so that a recipient can measure the risk when getting a promise from a sender;

**Comment by synctext** [comment]
- Please do an issue update for each of the developers (2-3line)
- Brief chat with European Central Bank in Amsterdam about our offline Euro work/offline token research
  - Program Director Digital Euro, European Central Bank
  - Event: https://toekomstbetalingsverkeer.nl/sprekers/

**Comment by Robert-ML** [comment]
@AdiDumi: I've made all the fragments with their UI (the print money and the coin picker most notably) and the navigation between fragments.

@gerbentimmerman: Last week, I mainly focused on data persistance research and created the initial database with some simple backend functionality. Next week, we will add more interactions with the database and connect it with the UI elements.

@naklecha: Last week I worked on the QR code integration, private key generation and passing those values to the QR code.

@Robert-ML: I've made the button interaction logic. Also I integrated the offline money app as a library inside the big super-app.

@vick0088:

**Comment by vick0088** [comment]
@vick0088 I work on the private & public key pair together with nishant.

**Comment by AdiDumi** [comment]
https://user-images.githubusercontent.com/57295921/227885946-caa61326-6c2e-4cf1-a949-fcb6359696ec.mp4

We made a short demo of how the app looks until now, there are still some links to be done between pages and QR code but this is the reference

**Comment by synctext** [comment]
- Great demo video!
- You did a nice productivity sprint!
-

**Comment by Robert-ML** [comment]
- APK at this [link](https://drive.google.com/file/d/19dD_P9Cmo_WPids6NP3rglIDrQ6_6psH/view?usp=sharing)
- transfer tokens through QR code
- data persistency present
- printing money active
- BUG when deleating tokens from data persistency
- team contribution:
- - @AdiDumi: TODO
- - @gerbentimmerman: TODO
- - @naklecha: TODO
- - @Robert-ML: TODO
- - @vick0088: TODO

**Comment by AdiDumi** [comment]
Demo with the printing money functionality working and balance update
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/57295921/229445601-21f70cb7-4794-468a-8080-4c8205057e45.gif)

**Comment by synctext** [comment]
- [X] Working .APK on your issue
- Seems I reproduced an async bug: printing money didn't work as expected
-

**Comment by Robert-ML** [comment]
Assignments:
When anything is done, mention it in Whatsapp so we might test it.

@gerbentimmerman :
- start on the documentation
- start on the DB function for transaction history

@naklecha :
- token signing when transferring ownership

@Robert-ML :
- verifying signatures when receiving money and for now print something tot he log if the validation fails
- - validation: is checking who minted the token (the government) and if the transaction history is valid inside the token
- a private-public key static key pair to act as the central bank (such a key is in the Token's GitHub repo in the validator/validation file)

@vick0088 :
- the printing of money needs to have the first recipient when it is minted, not be left empty (maybe the central authority, but not sure, needs to be checked). Then the coin needs to be transferred to the owner that is printing the money.

@AdiDumi :
- UI for transaction history and navigation to that page and from that page

**Comment by synctext** [comment]
- As asked ```At the moment we don't plan on implementing ideas like web of trust or debt collection in our application```
- please try to at least detect double spending when coming online again. Only implementing a token transfer app is a bit small-ish for this course. Especially, given [prior student work within this course](https://arxiv.org/abs/2204.06831).  By talking with random Ipv8 peers you should after a while stumble upon any cheaters.

**Comment by Robert-ML** [comment]
Implemented transacting tokens through QR and do all the security verifications. Because of limitations to the QR method, we can not put too much data into the QR so for high scanning success rate we recommend making transactions with only one token.

We do double spending token detection and find the culprit through the recipients history of a token. We insert it in our web of trust as a double spender (low trust score). Because of QR size limitation we do not send known users and their trust when doing a transaction, but it can be easily added just that QRs would start failing to generate or high likelihood to fail to be scanned.

New [PR](google.com)

**Comment by synctext** [comment]
- APK works smoothly! :clap: 
- Nice interface with the coins and notes
- Web-of-trust does not display double spenders or ```-1``` distrust people.

**Comment by Robert-ML** [comment]
The [PR](https://github.com/Tribler/trustchain-superapp/pull/157)

[APK](https://drive.google.com/file/d/1Qnf7xYs_wiT8WrfHPvgZTHB5h2eaxtrM/view?usp=sharing)

[README](https://github.com/AdiDumi/trustchain-superapp/blob/modularity_integration/README.md)

**Comment by TimG-NL** [comment]
Offline Digital Euro - DEMO GIF

![Offline Digital Euro - Demo](https://github.com/Tribler/tribler/assets/10922550/1964a022-1c89-4849-8e37-d65e1cec5341)

**Comment by TimG-NL** [comment]
Offline Digital Euro - DEMO GIF

![Blockchain Engineering - Offline Euro Demo](https://github.com/Tribler/tribler/assets/10922550/5e34477d-6ede-46ef-8064-d9df8654b451)
