### ISSUE TITLE
Addressing identified code quality issues?

### ISSUE THREAD

**Issue by chrisdebian** [Tribler/tribler#7303]
Hi, all.

Is anyone working on the issues identified, here:

https://app.codacy.com/gh/Tribler/tribler/issues

This would probably be if higher priority than implementing feature requests. I know it's difficult when resources are stretched.

Thanks for your work/ contributions,

Chris
chris_debian
UK

**Comment by ichorid** [comment]
@chrisdebian , would you consider contributing by taking this "janitor's" job? :wink:

**Comment by chrisdebian** [comment]
Hi, ichorid.

I'm not in a position to do this, I just thought it was strange that a security focused application would not have addressed these findings. I know the reality is that skilled volunteers are needed to help with all projects, and we don't live in an ideal world. Sorry i can't help with this.

Chris.

**Comment by drew2a** [comment]
@chrisdebian thank you for alerting and informing us!
 
Indeed, we have limited resources and as a result, we have not yet addressed the issues. 
The main reason behind this is that the issues are not causing any significant impact on Tribler.

The pull requests #7309 and #7330 have addressed these issues.
