### ISSUE TITLE
Blockchain Engineering 2023 - Token Transaction Engine III

### ISSUE THREAD

**Issue by InvictusRMC** [Tribler/tribler#7311]
Token transaction engine. Create a lightweight and fast token transaction engine for mobile devices. Your engine should be able to process 1000 transactions per second with standard 4G connectivity. Record these transactions within a simple SQLite backend. Realise simple primitives such as send/receive token primitives. Required background reading: [ConTrib: Universal and Decentralized Accounting in Shared-Resource Systems](https://dl.acm.org/doi/pdf/10.1145/3428662.3428789).

**Comment by InvictusRMC** [comment]
Progress all but one teammate. Please help him

* Read IPv8: https://py-ipv8.readthedocs.io/en/latest/basics/overlay_tutorial.html
* Prior work for tokens: 
  - [EuroToken.pdf](https://github.com/Tribler/tribler/files/10837670/Performance_Analysis_of_an_Offline_Digital_Euro_Prototype_13_02_23.pdf)
  - https://github.com/Tribler/trustchain-superapp#digital-euro

**Comment by timhuisman1** [comment]
In the past week, we've set up the project, examined the codebase and got familiar with.

We've set up a basic UI to test our code, but we're struggling to start creating the IPv8 overlay. There are quite some uncertainties and things we'd like to clear up with @InvictusRMC.

Questions:
1. How should we view / create peers? Are we first just creating virtual peers like in the example? And then later, perhaps the trustchain community?
2. What exactly are we sending between users? What does a token exactly represent? Is this even relevant for creating the transaction engine? 
3. Should we be storing a token, a transaction? Do you have any pointers on where we can draw inspiration from in the codebase?
4. How do we reduce build time? Also reduce memory consumption?
5. How should we communicate throughout the week? Via this issue or via email?

**Comment by AlbertoCastagnaro** [comment]
We have been able to implement a basic transaction that the user makes with himself through the ipv8 overlay and the trustchain community, consisting in sending a proposal half-block, receiving it (notifying the user with a pop-up warning), creating and sending back an agreement half-block.
On-going tasks:
- validation of a transaction. How should the validation work?
- Use our community to identify peers, and extend the transaction to peers using different devices (we were able to connect to the community with two different physical devices avoiding using eduroam). We thought about a list of peers from which the user can select with whom to make a transaction. Can it work?
- What about if a user does not want to agree on a transaction?

We have been working on the database to store transactions, trying to embed it with the transaction fragment. Still have some questions:
- Should we have two databases ( 1 for transactions and 1 for tokens owned) or just one for the transactions?
- How to merge two halfblocks to store a full block?
- Clarify how to store /use to validate user-performed transactions vs transactions made by other users. 

Future work idea:
For the benchmark of 1000 transactions, we are working on another UI where there is a button that starts making the 1000 transactions with another peer. We probably want to automate the agreeing process (right now the user needs to manually agree on a transaction) and do some performance analysis, while checking the correctness of every transaction.

**Comment by InvictusRMC** [comment]
✅ Trustchain tokens working! Great work!

Next sprint:

**Comment by Jorgeromeu** [comment]
#Update 20/03

In the past week, we’ve managed to set up two peers that can send blocks to each other with the use of an emulator and a physical phone. However, it is quite inconsistent. Sometimes it works, sometimes it does not.
Q: We are just using TrustChain, is this normal? (only using our community  for peer discovery)

Q: What to do with the most recent code that was merged into the main superapp, Should we build on their progress? It implements a wallet system and a token-sending system that does not use trustchain half-blocks.

Q: Eurotoken as a good example of a token structure? Our idea is to have a unique id, a hash of the latest transaction that involves this token, and the current recipient (public key and signature). How should the token structure affect how we pack half blocks? Should we use Eurotoken as an example?

Storage works, our own SQLDelight DB has been set up. The next step is thinking of how we are going to structure our tokens and how we will store them.

Furthermore, research into UDP packet loss and how we can optimally send transactions with UDP is still a work in progress. Adding debug options to UI to inspect blocks and peers - also a work in progress.

**Comment by timhuisman1** [comment]
Last week, we worked on the following things:

Transaction grouping:
We've set up a benchmark environment where we can see how much time the sending of 10 grouped transactions takes vs. 100 single transactions. Grouping transactions is roughly 10 times faster, as expected. However, we are unsure about how we should validate grouped transactions.

Peer selection & Block lists:
Some UI improvements have been made such that we have scrollable lists of sent blocks, together with a Peer selection UI in which we can view all peers in our community and select to which ones we would like to connect.

Dummy nodes:
Unfortunately, we did not get this to work yet, we have some questions about this as well.

Token & storage structure:
A setup has been made, but we will dive into this in more detail this week.

**Comment by InvictusRMC** [comment]
Example for report: https://github.com/Tribler/trustchain-superapp/blob/master/currencyii/README.md

**Comment by Jorgeromeu** [comment]
Progress update:
- v1 prototype of the transaction API is ready, which relies on trust chain for sending blocks/transactions which supports sending a single transaction and grouping transactions to the same recipient
- Basic performance evaluation, but we have some questions about how to improve it (trustchain usage vs manual sending over ipv8 overlay, and concurrent blocks creation and/or concurrent sending with coroutines)
- For flamegraph generation, some initial work was done in outputting the profile traces, but we have not managed to use them to generate a flamegraph (the trace file is not in the right format)
- Added UI to the transaction benchmark panel, and enabled choosing a target peer

**Comment by InvictusRMC** [comment]
Usage of multiple agreement block for single proposal block: https://github.com/Tribler/tribler/issues/7305

**Comment by AlbertoCastagnaro** [comment]
Progress updates:
- Tried to implement coroutines, but the design of trustchain which we rely on does not allow us to create and send blocks simultaneously. We also encountered problems with congestion of packets
- Flame charts in Android studio are working. However for the Flame graphs the android studio output trace is not accepted as input to create Flame Graphs with the brendangregg repo. There exists site that converts the Android Trace file to flamegraphs https://aflame.rhye.org/ , however it is outdated and does not compile anymore.

**Comment by AlbertoCastagnaro** [comment]
@InvictusRMC final README.md. https://github.com/timhuisman1/trustchain-superapp/blob/master/detoks/README.md

**Comment by InvictusRMC** [comment]
Hi guys, great work! Can you also post your slides here?

**Comment by AlbertoCastagnaro** [comment]
Sure! Here are the presentation slides
[Network Security Final Presentation.pptx](https://github.com/Tribler/tribler/files/11286654/Network.Security.Final.Presentation.pptx)
[Network Security Final Presentation.pdf](https://github.com/Tribler/tribler/files/11286656/Network.Security.Final.Presentation.pdf)
