### ISSUE TITLE
[main] Long Tribler's shutdown

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#7314]
**Describe the bug**
During the Tribler's shutdown, it freezes on this line:
https://github.com/Tribler/tribler/blob/4c7c3aaed69cda21355401a1fef415ceed6b20ca/src/tribler/core/components/restapi/rest/rest_manager.py#L169

**To Reproduce**
1. Open Tribler 
3. Close Tribler

**Screenshots**
<img width="566" alt="image" src="https://user-images.githubusercontent.com/13798583/224270581-c3b89885-4f70-4e06-91b3-c10988159e2f.png">

**Additional context**
The bug doesn't reproduce while running Tribler headless.

**Comment by drew2a** [comment]
Going deeper... The freeze happens here:

https://github.com/aio-libs/aiohttp/blob/3ff81dc9c9ce20efd3bf54cf52adaf438c483a92/aiohttp/web_protocol.py#L287-L288
```python
                if self._task_handler is not None and not self._task_handler.done():
                    await self._task_handler
```

With the following value of `self._task_handler`:
```python
Wait for  <Task pending name='Task-108' coro=<RequestHandler.start() running at /Users/<user>/Projects/github.com/Tribler/tribler/venv/lib/python3.9/site-packages/aiohttp/web_protocol.py:513>
wait_for=<Task pending name='Task-109' coro=<RequestHandler._handle_request() running at /Users/<user>/Projects/github.com/Tribler/tribler/venv/lib/python3.9/site-packages/aiohttp/web_protocol.py:434>
wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10ec27a30>()]> cb=[<TaskWakeupMethWrapper object at 0x10eb73eb0>()]>>

```

**Comment by drew2a** [comment]
The bug started to appear after merge https://github.com/Tribler/tribler/pull/7300

**Comment by kozlovsky** [comment]
As I understand it, the actual reason for the freezing is [here](https://github.com/Tribler/tribler/blob/6f351c079ed328ba1bae9f90ba295ee82e936a74/src/tribler/core/components/restapi/rest/events_endpoint.py#L169):
```python
class EventsEndpoint(RESTEndpoint):
    ...
    async def get_events(self, request):
        ...
        try:
            while True:
                await asyncio.sleep(3600)  # <-- here
        except CancelledError:
            self.events_responses.remove(response)
            return response
```

The EventsEndpoint response is a stream that never finishes. The response handling code even does not have a code path to finish the response during the shutdown. Also, the code eats and does not reraise the `CancelledError` exception, and that does not look good to me. I think the correct code should look like this:

```python
class EventsEndpoint(RESTEndpoint):
    ...
    async def get_events(self, request):
        ...
        try:
            while not self._shutdown:
                await asyncio.sleep(1)
        finally:
            self.events_responses.remove(response)
        return response
```
