### ISSUE TITLE
Empty results in reply.readAll() when receiving response from Core REST API

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#7335]
Sometimes [reply does not contain any data](https://github.com/Tribler/tribler/blob/93927779051ddfe2412731067b5e3d4c14ad162d/src/tribler/gui/network/request.py#L99) (see #7297, #7333). The actual reason for this is currently unclear.

It is possible that sometimes Core REST API actually returns an empty result, although it should not do this. All results from REST API are returned in JSON format, and even if the result by error does not contain any keys and is an empty dict, it is still not empty when serialized as a string: `"{}"`.

Even when request processing leads to an error, the result should not be an empty string - it should still be a JSON dictionary with an `"error"` key that describes the error.

Another possibility is Core correctly returns the result, but on the GUI side, the `QNetworkReply` instance is garbage collected before `reply.readAll()` was called. Looking at the code, it is hard to say how it is possible as:
1. The reference to the `QNetworkReply` instance [is held](https://github.com/Tribler/tribler/blob/93927779051ddfe2412731067b5e3d4c14ad162d/src/tribler/gui/network/request_manager.py#L138) by the `QNetworkRequest` instance.
2. The reference to the `QNetworkRequest` instance [is added](https://github.com/Tribler/tribler/blob/93927779051ddfe2412731067b5e3d4c14ad162d/src/tribler/gui/network/request_manager.py#L120) to the `RequestManager.active_requests` set.
3. The reference to the `QNetworkRequest` instance should be removed from the `RequestManager.active_requests` set only [at the end of the `Request.on_finished` method](https://github.com/Tribler/tribler/blob/93927779051ddfe2412731067b5e3d4c14ad162d/src/tribler/gui/network/request.py#L122) when `reply.readAll()` should be already called.

The problem does not look critical, as it only happens sometimes. It can probably be ignored, but I created the issue so we can refer to this problem later.

**Comment by qstokkink** [comment]
In addition to what you listed, this may be a case of needing to check `self.reply.error() == QtNetwork.QNetworkReply.NoError` before reading the value in `self.reply.readAll()` ([there are many different intermittent errors that can occur](https://doc.qt.io/qtforpython-5/PySide2/QtNetwork/QNetworkReply.html#PySide2.QtNetwork.PySide2.QtNetwork.QNetworkReply) in `QNetworkReply` itself).

**Comment by kozlovsky** [comment]
@qstokkink thank you for this info, I'll add handling of `QNetworkReply` error codes in #7334

**Comment by kozlovsky** [comment]
Should be fixed in #7334
