### ISSUE TITLE
Refactoring: `BandwidthCommunity` may be removed.

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#7336]
We still have issues related to the `BandwidthCommunity` which causes the Tribler crashes.
At the same time, the `BandwidthCommunity` functionality has not been used for at least a couple of years.

It looks like a big piece of code that could be safely removed.

**Comment by synctext** [comment]
can't find the code https://github.com/Tribler/tribler/search?q=BandwidthCommunity&type=code
this is different then the bartercast or ledgerzero community

**Comment by drew2a** [comment]
The core part:
https://github.com/Tribler/tribler/tree/main/src/tribler/core/components/bandwidth_accounting

The GUI part:
https://github.com/Tribler/tribler/blob/main/src/tribler/gui/widgets/trustgraphpage.py

**Comment by synctext** [comment]
This should be repaired for MeritRank. Please fix the stability issues. For long term lab progress we need a reputation graph.

**Comment by drew2a** [comment]
The error continues to occur in `BandwidthCommunity`. See the latest: https://sentry.tribler.org/organizations/tribler/issues/2548/.

Should we continue trying to fix them, or should we remove the entire feature as it will eventually be replaced in favor of MeritRank?

@synctext

**Comment by synctext** [comment]
Indeed, we might as well delete it all now. This commit from [3 weeks ago deleted a lot](https://github.com/Tribler/tribler/commit/7fe164612a112262b404692e86bb916ccb7e7563). 
Then @InvictusRMC and @grimadas can start with a somewhat clean start with MeritRank deployment.
