### ISSUE TITLE
10x speedup of all downloads in Tribler when switching to Search tab and performing a search

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#7360]
We have a user report https://github.com/Tribler/dispersy/issues/576 from @casbtosint; according to it, all downloads are approx 10x faster when switching to the Search tab during the download and performing a search. It looks like we have some bug in Tribler, and opened Downloads page causes some drastic slowdown.

You can see the demonstration of the effect in the following video, starting from 3rd minute:
https://peervideo.club/w/sznmzZvyd4dLm817xgwQwT

We should investigate the reason for the slowdown and fix it; it should have a huge effect on Tribler's performance.

### Steps to reproduce:

1. Start a download in Tribler.
2. Observe the download speed while on the Downloads page.
3. Switch to the Search tab and perform a search.
4. Observe the increase of the network traffic and download speed while the Search tab is open

**Comment by drew2a** [comment]
It could be related to the following behavior of Tribler: if the downloads tab is opened, it produces a lot of `downloads?get_pieces=1` requests to the core:

```python
INFO - RequestManager(128) - Request: GET http://localhost:20100/downloads?get_pieces=1
INFO - RequestManager(128) - Request: GET http://localhost:20100/downloads?get_pieces=1
INFO - RequestManager(128) - Request: GET http://localhost:20100/downloads?get_pieces=1
INFO - RequestManager(128) - Request: GET http://localhost:20100/downloads?get_pieces=1
INFO - RequestManager(128) - Request: GET http://localhost:20100/downloads?get_pieces=1
INFO - RequestManager(128) - Request: GET http://localhost:20100/downloads?get_pieces=1
INFO - RequestManager(128) - Request: GET http://localhost:20100/downloads?get_pieces=1
INFO - RequestManager(128) - Request: GET http://localhost:20100/downloads?get_pieces=1
INFO - RequestManager(128) - Request: GET http://localhost:20100/downloads?get_pieces=1
INFO - RequestManager(128) - Request: GET http://localhost:20100/downloads?get_pieces=1
INFO - RequestManager(128) - Request: GET http://localhost:20100/downloads?get_pieces=1
INFO - RequestManager(128) - Request: GET http://localhost:20100/downloads?get_pieces=1
```

**Comment by ichorid** [comment]
Indeed, `get_downloads` is horribly costly: I've witnessed the call take _up to a minute_ to finish on older machines if there are more than a dozen torrents. After all, there is a reason why Arvid decided on a completely asynchronous, polling-free design with their "alerts" system - Libtorrent tries as hard as it can to avoid polling the states of the torrents (especially with `get_pieces`).

The proper way to fix this is to use Libtorrent's ["alerts" subsystem](https://github.com/Tribler/tribler/blob/066a904a7d2cde4922e036e4832546562e19e99d/src/tribler/core/components/libtorrent/download_manager/download_manager.py#L119) as intended by its authors, and combine that with our Notifier/Events manager **to avoid polling completely**. In this case, the Core will send changes/updates of torrent states to the GUI only when something really changes. I guess a good first step would be to either send changes in torrent state, or torrent progress.

**Comment by egbertbouman** [comment]
As far as I know, alerts are already used in Tribler. Also, Tribler doesn't get the state from all torrents every second, instead it listens for [state-update-alerts](https://www.libtorrent.org/reference-Alerts.html#state-update-alert). These alerts are requested periodically in [_request_torrent_updates](https://github.com/Tribler/tribler/blob/main/src/tribler/core/components/libtorrent/download_manager/download_manager.py#L530-L533.). This call, however, is made whether the downloads tab is selected or not.

I would start by deselecting the download from the downloads tab, and see if the problem still persists. If not, `get_pieces` is indeed a likely culprit.

**Comment by drew2a** [comment]
Could be related to this issue:

@kozlovsky wrote in #7378
>I measured the response time from the /downloads endpoint on my machine, and it is usually 0.3 - 0.5 seconds but periodically 3.7 - 4.0 seconds. Only these two intervals can be observed, nothing in-between, like "1.0 second". It is possible that the endpoint logic sometimes gets blocked by other asynchronous processes, and this causes a bigger delay.

**Comment by synctext** [comment]
On "User 0" extremely old 2016 Mac I've reproduced this bug. Tribler can do **9.0** MByte/seconds downloads on a 2016 machine, amazing. From the original bug report:

>  Observe the increase of the network traffic and download speed while the Search tab is open

There is clearly a efficiency boost with proper async/alert pattern usage. Within 7.12 and earlier there always was my _feeling_ that something was slowing things down. Popular swarms just don't perform much on old Mac after 1-3 minutes. You get the 9 MByte/sec and just stops down to a trickle. Explicitly not happening on Linux!

**Comment by drew2a** [comment]
Related PR:
- #7664
