### ISSUE TITLE
[7.12] binascii.Error: "Odd-length string" in utilites.parse_magnetlink()

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#7366]
[Here](https://github.com/Tribler/tribler/blob/dd8a622f8b8f8be18e0bad24c430b16326e1d0f1/src/tribler/core/utilities/utilities.py#L114):

```python
def parse_magnetlink(url):
    ...
    if len(encoded_infohash) == 32:
        xt = b32decode(encoded_infohash.upper())
    else:
        xt = binascii.unhexlify(encoded_infohash)  # <-- here
```

If a magnet link has an infohash with an incorrect length, the error should be handled, and `(None, None, [])` should be returned from the function.

**Comment by drew2a** [comment]
Should be fixed in https://github.com/Tribler/tribler/pull/7058
