### ISSUE TITLE
The big migration: from the Channels to the Knowledge Graph

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#7398]
This issue describes the migration plan for the Tribler's metadata from the Channels to the KnowledgeDatabase. See more information here: #6214

## The recent history

* **Release 7.11**: that was the first release for #6396
* **Release 7.12**: there we introduced #6708 and #6718 

## Current state

Currently, we have the [7.13 release candidate](https://github.com/Tribler/tribler/releases/tag/v7.13.0-RC1) that includes a migration from the `TagDatabase` to the `KnowledgeDatabase` (as it's a crucial step towards a global knowledge graph): #7070 
After this release is successfully launched, we will be ready for the next steps.

The direction for the next step could involve completing the replacement of Channels with the global Knowledge Graph.

## Future

Questions should be answered before the big migration:
* Spam prevention: Can we use [MeritRank](https://github.com/grimadas/meritrank) for this purpose? (The answer is "No")
*  What is the best way to disseminate knowledge? Is the current mechanism sufficient? Should we use the PopularityCommunity for this purpose, or continue using the KnowledgeCommunity? ~~Should we use Skip Graph?~~

`7.14`
* **Metadata migration**: write a migration for the database:`mds.db`->`knowledge.db`
* **Alternative remote search**: develop a remote search identical to the search by MDS, disabled by default.

Outcome: tribler network is ready for testing search by knowledge.

`7.14-experimental` 
* Enable remote search by Knowledge by default (as a full replacement for the current mechanism).

Outcome: Search quality evaluation based on users' feedback and our own experience.

`7.15`
* Implement `MeritRank` for the `KnowledgeCommunity`

Outcome:
* The Tribler network is ready for testing 'search by knowledge' with spam prevention.
* Search quality evaluation based on users' feedback and our own experience 

`8.0`
* Remove channels from GUI
* Remove channels from core

Outcome: Tribler network migrated from the Channels to the KnowledgeDatabase.

**Comment by xoriole** [comment]
Channels are a way of organizing content on Tribler Network. As it is created by a human (and not autogenerated), the way the channels are organized into a hierarchy of directories and torrents are placed on different directories, makes sense at least to the creator of the channel if not for more people who subscribe to the channel. This involves the channel creator's human intelligence in the organization of content which likely required some time and effort.

While moving away from channels to knowledge database, we should try to incorporate this content organization done by the user and not simply erase it.

**Comment by drew2a** [comment]
Following a discussion with @grimadas, it has become clear that MeritRank cannot be used for spam prevention with the current tags/knowledge.

MeritRank requires peers to interact with each other, whether directly or indirectly. Based on these interactions, peer rank can be calculated, and potential spam can be ignored. As demonstrated by @devos50 in his recent research, Tribler's users are not actively generating tags. Consequently, for the average user, there won't be enough paths in the Knowledge Graph to reach another user and rank their knowledge statements (and, therefore, ignore spam).

Thus, the first problem is that **we need to encourage users to interact with each other** through metadata or content. It remains an open question as to how we can achieve this.

Another issue is that **MeritRank was not designed specifically for spam prevention**, and its effectiveness in addressing this particular problem is uncertain. @grimadas has taken the time to contemplate this and suggest the best way for MeritRank to be utilized.

![IMG_6286](https://user-images.githubusercontent.com/13798583/236176823-b508246a-5f1c-4f34-a6ed-95507ad2a745.jpg)

**Comment by ichorid** [comment]
"[Evil fairy](https://en.wikipedia.org/wiki/Maleficent)" :smiling_imp: :fairy: :laughing: :   kindly reminds:
["Pull requests" for channels](https://github.com/Tribler/tribler/issues/6208) 

Also, https://github.com/Tribler/tribler/issues/6043 , https://github.com/Tribler/tribler/issues/6217 etc.


![img](https://user-images.githubusercontent.com/2509103/236336105-398ddde4-ed96-4718-82aa-7e58ae3a1024.png)
(see https://github.com/Tribler/tribler/issues/6481)

**Comment by synctext** [comment]
First draft of division of responsibilities

Who | What?
---|---
@InvictusRMC | sub-DAO deployment and measure [thesis chapter], 2D MeritRank, Tribler PRO: donate, MeritMiners, proof-of-donation, social recognition, and preemption
@grimadas  | Deployment of MeritRank, measure, stability, correctness
@mg98 | Metadata enrichment, tagging, Meritrank integration, and measurements [thesis chapter(s)]
@drew2a | general development and quality control

When | What?
---|---
June | overall design sketch complete
July | first running IPv8 community with MeritRank
Sep | Test deployment of minimal viable MeritRank
Dec 2023 | Production: Merit-Rank based tagging and 2D MeritRank
Dec 2024 | Tribler PRO

**Comment by synctext** [comment]
Thank you for that solid design sketch for 7.14! Can you make it more minimal and easier please? 

Let's leave the long-tail and rare content search problem out. First do a minimal transition from channels to tags. Minimal viable MeritRank spam prevention. Introducing complexities such as full nodes and metadata-servers is best left after we have tags, Meritrank, and existing PopularityCommunity fully working.

**Comment by drew2a** [comment]
Updated Plan for Upcoming Releases

### 7.14

1. Implement Rendezvous Certificates as the first step toward MeritRank implementation: #7517
2. Partial metadata migration: #7595
3. Enhancements in gossip protocol (will be described and discussed later)
4. Local search improvements using knowledge database
5. Remote search improvements using knowledge database
6. Wireframes for the new GUI

The end of this release may not present noticeable changes for regular Tribler users when comparing version 7.14 to 7.13. The primary search engine and metadata source will continue to be Channels. However, with the extension of Tribler's search API, we as developers can test the new search functionality without disrupting the user experience.

### 8.0

1. Complete metadata migration
2. Switch to the new search engine
3. Transition the GUI from being channels-centric to search-centric 

The MeritRank implementation is difficult to plan at this stage as it's not closely integrated with the Knowledge Graph yet. We've decided that spam prevention and reputation features are not priorities for the upcoming releases. As we gather more information on the MeritRank, I'll update the plan accordingly.

**Comment by drew2a** [comment]
**Migration Strategy**

For the `7.14` release, we plan to implement a partial metadata migration. During this phase, only titles will be transferred from the `mds.db` to the `knowledge.db`. After the migration is complete, the `knowledge.db` will contain three types of statements:

1. Title (new)
2. Tag 
3. Content Item

We have implemented this migration as an extension of the existing `KnowledgeRulesProcessor`. This approach allows for batch processing of `mds.db` in the background, making the transition virtually unnoticeable to our users and preventing any disruption to normal Tribler usage. Eventually, all titles present at the time the migration began will be moved to `knowledge.db`. This will provide us, as developers, with an opportunity to test the search quality in the real network going forward.

For the `8.0` release, we plan to carry out a full metadata migration. In addition to transferring new torrent titles, the relationships between channel items will also be moved to the `knowledge.db`. By "relationships," I mean the hierarchical structure inherent in channels, as well as the information that can be derived from this organizational principle, such as nestedness.

**Comment by drew2a** [comment]
**Enhancements in Gossip Protocol**

There's an ongoing discussion about how we should refine the knowledge gossip protocol.

### Current Algorithm
As it stands, our current algorithm proceeds as follows:
1. Every 5 seconds, select a random peer and send a knowledge request to it.
2. Upon receiving a knowledge request, send 10 random statements to the requesting peer.

This approach was modeled after the Popularity Community gossip algorithm, assuming its long-standing effectiveness would make it a good starting point for the Knowledge Community.

### Potential Improvements
One immediate suggestion to enhance the protocol would be to shift the type of items gossiped. Rather than gossiping single statements, we could share comprehensive information about a specific torrent—its title, tags, and content items. This approach would maintain the integrity of the torrent's information, which could become crucial as we start use it in the search. However, this is based on intuition and may warrant further evaluation.

### Do We Need a Separate Gossip Protocol?
Another significant question is whether a dedicated gossip protocol for knowledge statements is necessary at all. My inclination is that we might be able to leverage the existing gossip mechanisms implemented in the Popularity Community. Here's a brief overview of how the high-level algorithm in the Popularity Community operates:

1. Send information about popular torrents upon introduction requests.
2. Every 5 seconds, select a random peer and send a torrent health request to it.

If a peer receives torrent health info for a torrent whose metadata is missing, the Popularity Community subsequently requests the missing metadata. Given that there is already a mechanism in Tribler for disseminating metadata, it might be sufficient to replace the source of metadata from `mds.db` to `knowledge.db`. This change could potentially eliminate the need for a dedicated gossip mechanism in the Knowledge Community.

This method could be synergized with what intuitively appears to be an efficient way to disseminate metadata—namely, including torrent metadata in the Remote Search Results Response. The logic here is straightforward: the more a specific torrent is searched for by Tribler users, the more widely its metadata will be distributed across the network. This mechanism is currently operational within the Channels.

#The Experimental Approach vs. The Pragmatic Approach 

There's ample opportunity for experimentation here. We could simulate a network with a predefined number of agents, assuming that they have complete and accurate metadata. This would allow us to evaluate the proposed algorithm's impact on search efficiency, network fault tolerance, and the speed of metadata dissemination for both popular and random torrents. Conducting this research rigorously would require the full-time commitment of a dedicated scientist.

Alternatively, we could take a more pragmatic approach by adopting methods that seem effective in existing communities. This would be quicker and easier, but it offers no guarantees that the methods will perform as expected.

**Comment by drew2a** [comment]
## The search algorithm

The most recent version of the Channels Search Algorithm was introduced in #7025. Adapting this existing algorithm for the Knowledge Graph is challenging due to differences in database structure.

Here are some potential approaches for implementing search within the Knowledge Graph, along with rough time estimates for each:

1. Implement Full-Text Search (FTS) for titles using SQL (Estimated time: 3 days).
2. Adapt the latest algorithm from @kozlovsky, excluding health info (Estimated time: 1 week).
3. Fully adapt the latest algorithm from @kozlovsky, including health info (Estimated time: 1-3 months).
4. Develop a completely new algorithm tailored to the graph-based structure of the Knowledge Graph. This approach could necessitate switching from an SQL database to a specialized graph database (Estimated time: Unknown, requires further analysis).

These are rough estimates and the actual time required may vary.

**Comment by drew2a** [comment]
## DB scheme

The `metadata.db` has the following entities:

* MiscData 
* TrackerState 
* TorrentState 
* ChannelNode 
* MetadataNode 
* CollectionNode 
* TorrentMetadata 
* ChannelMetadata
* JsonNode 
* ChannelDescription 
* BinaryNode 
* ChannelThumbnail 
* ChannelVote 
* ChannelPeer 
* Vsids 

They could be divided into 4 groups:

|Tracker Info|Health info|Torrent/Channels metadata|Misc data|
|-|-|-|-|
|TrackerState|TorrentState|ChannelNode, MetadataNode, CollectionNode, TorrentMetadata, ChannelMetadata, JsonNode, ChannelDescription, BinaryNode, ChannelThumbnail, ChannelVote, ChannelPeer, Vsids|MiscData|

The final two categories (`Torrent/Channels metadata` and `Misc data`) can be migrated to `knowledge.db` without necessitating any structural changes within the `knowledge.db` itself.

Regarding `Tracker info` and `Health info`, I envision three potential solutions:
1. Treat them as knowledge entities within the `knowledge.db`.
2. Maintain them as distinct tables inside the `knowledge.db`.
3. Allocate them to a separate database.

From a developmental effort perspective, the first option is the most straightforward. However, this choice comes with two significant disadvantages: 
1. The search speed may considerably decline due to intricate database queries.
2. Operations such as inserting/retrieving torrent health and tracker information might become more complex and time-consuming.

The second option seems like a middle ground. While it may not impact speed as drastically as the first, it does blur the lines of abstraction. One could then question why certain knowledge elements are designated as Statements, while others are treated as distinct entities within the same database. This might also raise questions about the database's name (`knowledge.db`) and if a more general name like `tribler.db` might be more fitting.

The third option is the most abstractly clear, separating different data types into distinct databases. However, it introduces an additional database to the current roster (knowledge.db, bandwidth.db, mds.db (which will eventually be phased out)). In terms of performance, it might not be as efficient as the second option.

**Comment by synctext** [comment]
No exact database schema definition, [```TorrentTag``` was defined here by Martijn in Oct 2021](https://github.com/Tribler/tribler/issues/6214#issuecomment-945682345).
Our roadmap (Johan job) and detailed designs are not documented in detail, it has to be extracted from multiple issues + PR.

**Comment by drew2a** [comment]
The exact database schema definition can be found here:
https://github.com/Tribler/tribler/blob/20fb22453c8c5349c6de4b8e679a5b590792b7df/src/tribler/core/components/database/db/layers/knowledge_data_access_layer.py#L77-L144

**Comment by synctext** [comment]
Complexity is the biggest risk of Tribler failure, hence my obsession with it. Quick list of open issues and priorities (ongoing editing). I'm struggling what to do first. We should collectively think more about this.
1. Improve stability. Fix or close the 150+ open Sentry issues. Actual faults reported by actual users.
2. Learn-to-rank distributed machine learning (@pneague @mg98)
3. new socket and rust module (@egbertbouman)
4. removal of GigaChannel
5. "soft" migration of knowledge DB

**Comment by drew2a** [comment]
The roadmap from the most recent dev meeting:

1. Shipment of `7.13.1`. Awaiting closure of the following issues/PRs:
    * #7660 
    * #7628 
    * #7647 
2. Shipment of `7.14` (Rendezvous certificates) before Christmas. The flagship feature: #7630.
3. Shipment of `7.15` (Partial channels removal).
4. Shipment of `8.0`, with the new Tribler architecture: https://github.com/Tribler/tribler/issues/7632#issuecomment-1778787961.

**Comment by drew2a** [comment]
As the migration is not going to happen (we decided to retain some parts of channels, including the `metadata.db`), I'm closing the issue.

**Comment by synctext** [comment]
One brainstorm idea to complete the migration is to also provide tooling for format compatibility and platform compatibility. Youtube Creative Commons content with metadata in the form of tags could be exported and made compatible with tooling of the Bittorrent swarm world.
