### ISSUE TITLE
Do not send any Request to REST API if Tribler is already shutting down

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#7400]
If Tribler is shutting down, we still have requests being sent to the Core via REST API which are canceled almost immediately. So, it would be better to not send any new requests at all if Tribler is already shutting down.

Since `RequestManager` is responsible for creating Network Requests, if provided the information that Tribler shutting down (could even be detected via shutdown request), the request manager could start rejecting any calls to do any new network request.

Request Manager returns the `Request` object when any HTTP method actions are called. These returned Request objects are only occasionally used and simply ignored in most of cases. So the changes required on the codebase and the impact is limited. Returning a None request if Tribler is shutting down and handling for None should be sufficient wherever the request object is used. This is up for discussion.

**Comment by drew2a** [comment]
The consequence of this behavior is logs filled with spam:
<img width="594" alt="image" src="https://user-images.githubusercontent.com/13798583/236230953-951f795f-7674-4315-9256-5a88d0e69773.png">
