### ISSUE TITLE
 Notifier: The docstring for notifier.add_observer() is incomplete.

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#7416]
The "synchronous" parameter is not documented:

https://github.com/Tribler/tribler/blob/066a904a7d2cde4922e036e4832546562e19e99d/src/tribler/core/utilities/notifier.py#L122-L136

**Comment by qstokkink** [comment]
The code references in this issue no longer exists and, therefore, this issue is no longer relevant.
