### ISSUE TITLE
msc placeholder: complex coding specialist

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#7423]
Survey plus thesis placeholder. Still exploring directions for research. _starting survey today_ :joy_cat: Due to permanent job msc time is limited to 4 hours/workday. (part-time not allowed US culture)

Committed of doing Survey in this Q4 quarter. For Sep 2023 still 2 master courses left. 

Various background reading:
Topic | Title of paper and URL
---|---
'decentral AI' in 2005 | [P2P-based PVR Recommendation using Friends, Taste Buddies and Superpeers](https://grouplens.org/beyond2005/full/pouwelse.pdf)
decentralisation history | [The fifteen year struggle of decentralizing privacy-enhancing technology](https://arxiv.org/pdf/1404.4818)
collaborative money | [Unstoppable DAOs for Web3 Disruption](https://dl.acm.org/doi/pdf/10.1145/3565383.3566112)
collaborative money | ["Generic DAO primitives for Full Academic Decentralization and Scalability"](https://github.com/Tribler/tribler/files/11352694/Generic_DAO_primitives_for_Full_Academic_Decentralization_and_Scalability.2.pdf)
strong identity | [A Truly Self-Sovereign Identity System](https://arxiv.org/pdf/2007.00415)
strong identity | [TrustVault: A privacy-first data wallet for the European Blockchain Services Infrastructure](https://arxiv.org/pdf/2210.02987)
strong identity | [Zero-Trust Architecture for Legal Entities](https://repository.tudelft.nl/islandora/object/uuid:ac27c1a9-0497-41e2-9fb5-44943b40df0c/datastream/OBJ/download)
strong identity | [Distributed Attestation Revocation in Self-Sovereign Identity](https://arxiv.org/abs/2208.05339)

More on passport-level digital identity. Warning given :smile_cat: "this is complex stuff". identity is the foundation of trust in the old analog world. Please make a reading list about SSI, EBSI, EBP and eIDAS2
- https://en.wikipedia.org/wiki/Self-sovereign_identity
- [The Future of Integrated Digital Governance in the EU: EBSI and GLASS](https://arxiv.org/pdf/2212.03218.pdf)
- https://www.thalesgroup.com/en/markets/digital-identity-and-security/government/identity/eidas-regulations
- https://gouvernement.lu/en/dossiers.gouv_digitalisation%2Ben%2Bdossiers%2B2022%2Bebsilux.html
- https://dl.gi.de/bitstream/handle/20.500.12116/38705/proceedings-05.pdf?sequence=1&isAllowed=y
- [worldcoin](https://spectrum.ieee.org/worldcoin)
- [Rowdy strong identity revocation thesis]()

please note the survey @ Tribler lab methodology: https://github.com/Tribler/tribler/wiki/MasterThesis#10-ects-literature-survey-at-tribler-lab (e.g. try out all known open source wallets for suvey and grade them with stong/weak analysis in a table with screenshots { https://walt.id/ebsi ; https://github.com/walt-id })

_update: government approved an EBSI intership_

**Comment by synctext** [comment]
btw please register today at: https://mare.ewi.tudelft.nl/
(just a tentative commitment, give me teaching credits)

**Comment by tudatt** [comment]
Read the following (10) papers and started on a draft survey paper:

[PB-PKI: a privacy-aware blockchain-based PKI - ORA - Oxford University Research Archive](https://ora.ox.ac.uk/objects/uuid:8bd33c4f-5614-400e-b958-48e53fe1b342)

[An overview of PKI trust models](https://ieeexplore.ieee.org/abstract/document/806987/)

[A blockchain-based PKI management framework](https://orbilu.uni.lu/handle/10993/35468)

[Ten risks of PKI: What you're not being told about public key infrastructure](http://www.lkn.fe.uni-lj.si/gradiva/VarKom/PREDAVANJA/gradiva/Ten%20Risks%20of%20PKI_Ellison&Schneier.pdf)

[J-PAKE: authenticated key exchange without PKI](https://link.springer.com/chapter/10.1007/978-3-642-17697-5_10)

[The importance of PKI today](https://www.lockstep.com.au/wp-content/uploads/2021/06/China-Comms-Importance-of-PKI-Today-Dec05.pdf)

[Implementing SSL/TLS using cryptography and PKI](https://books.google.com/books?hl=nl&lr=&id=LfsC03f8oGsC&oi=fnd&pg=PR27&dq=pki&ots=JYlYKXaxxD&sig=eFvhCo0ZhqDeqH8X2CmE4b8N4Bo)

[Efficient Certificateless One-Pass Key Agreement Protocols](https://www.researchgate.net/profile/Yasmine-Abouelseoud/publication/281291919_Efficient_Certificateless_One-Pass_Key_Agreement_Protocols/links/55e0552e08aede0b572dae3a/Efficient-Certificateless-One-Pass-Key-Agreement-Protocols.pdf)

[Design, analysis, and implementation of ARPKI: an attack-resilient public-key infrastructure](https://ieeexplore.ieee.org/abstract/document/7547899/)

**Comment by tudatt** [comment]
[Essay.pdf](https://github.com/Tribler/tribler/files/13221945/Essay.pdf)

I have started writing a draft literature survey paper and I'm looking for validation of the overall direction and storyline.

**Comment by synctext** [comment]
- nice progress
- ```panoramic view of the academic, technological, and practical landscape surrounding public key cryptography and its integration into digital infrastructure``` Solid idea :rocket: 
- ```Blaise de Vigen`ere created a more complex polyalphabetic cipher``` Please remove all analogue technology. Focus on digital era only, feel free to replace with citation to historical books.
- RSA is not the original :astonished:  :-)
  -  1970 UK secret https://cryptocellar.org/cesg/possnse.pdf
  - overview: https://www.schneier.com/essays/archives/1998/04/the_secret_story_of.html
- Please focus on upcoming sprint on finding out why normal people do not have a public key and not everybody uses this yet?
- Modern twist: [DPKI: A Blockchain-Based Decentralized Public Key Infrastructure System](https://doi.org/10.1109/GIOTS49054.2020.9119673)

**Comment by tudatt** [comment]
[Survey_on_PKC___A__Titu.pdf](https://github.com/Tribler/tribler/files/13347475/Survey_on_PKC___A__Titu.pdf)

**Comment by synctext** [comment]
- Add history of passwords: https://news.mit.edu/2019/mit-professor-emeritus-fernando-corby-corbato-computing-pioneer-dies-0715
- Add passkeys, modern development pioneered by Apple. https://technically.substack.com/p/what-are-passkeys
- blog post on [password-focused history](https://www.beyondidentity.com/blog/history-and-future-passwords)

**Comment by tudatt** [comment]
Update December 12th

Progress: 90% done
[Survey_on_PKC___A__Titu (1).pdf](https://github.com/Tribler/tribler/files/13645261/Survey_on_PKC___A__Titu.1.pdf)

Still needs to happen:

 - spell checking
 - proper formatting
 - write evaluation and conclusion sections
 - add references

**Comment by synctext** [comment]
Lacks an analysis: why are we failing for 53 years? Brainstorm
1. Diverse user needs. No single universal solution. No solution portfolio for various usage patterns.
2. Lack of usability. Too technical tools. Inherent complexity and nobody invested in a solution.
3. Certificate authority approach works for webservers and TLS. However, evolutionary dead end for consumers. Too complex architecture, too demanding for key management, too difficult to use for normal people (requires at least a bsc in computer science).

Please investigate if you agree with my analysis:
- ownership. Owning the digital identity of your users yields profit. User lock-in in your ecosystem, it all starts with identity.
- ownership of the infrastructure. Your ```2.5 Required Infrastructure``` does not mention any profit motive. Big Tech seeks out durable monopolies to extract profit? See [courtcase outcome today of Google versus Epic games](https://www.nytimes.com/2023/12/11/technology/epic-games-google-antitrust-ruling.html) :monocle_face:

**Comment by tudatt** [comment]
9th January: 
[Survey_on_PKC___A__Titu (1)-1.pdf](https://github.com/Tribler/tribler/files/13870851/Survey_on_PKC___A__Titu.1.-1.pdf)

**Comment by synctext** [comment]
From 12Dec - 9Jan not much progress was made. Only few lines added. Hopefully you can make more progress next sprint.

**Comment by tudatt** [comment]
[54 years of evolution survey.pdf](https://github.com/Tribler/tribler/files/14028456/54.years.of.evolution.survey.pdf)

Final version of literature survey - ready for grading.

**Comment by synctext** [comment]
- Contains all this information, nice overview of 54 years.
- The writing itself and the organisation could be much polished.
- Clear example is the passkeys
  - hidden that passkeys represent a significant advancement for usability
  - hidden that you think this standard will be dominant
  - hidden if this solve PKI after 54 years
  - hidden that it requires the fingerprint of the users. ```All the user needs to do is to provide their fingerprint (or any form of biometric authentication the device supports) or device password, when prompted for it.```
