### ISSUE TITLE
Remove list comprehension from `str.join` function calls

### ISSUE THREAD

**Issue by Solomon1732** [Tribler/tribler#7433]
**Describe the bug**
Thanks to generator expressions and other lazy evaluation functions (such as `map`), there's no need to build a list when calling `str.join`. This saves memory during runtime since no list is built. Below each relevant line I wrote a substitute I offer.

https://github.com/Tribler/tribler/blob/8df8154193f404e20ba4ff9ba9d46f082820a132/src/tribler/core/components/libtorrent/torrentdef.py#L306

```py
                    return "".join(map(filter_character, name))
```

https://github.com/Tribler/tribler/blob/8df8154193f404e20ba4ff9ba9d46f082820a132/src/tribler/core/components/libtorrent/torrentdef.py#L386

```py
                            return "".join(map(filter_character, name))
```

https://github.com/Tribler/tribler/blob/8df8154193f404e20ba4ff9ba9d46f082820a132/src/tribler/core/components/metadata_store/remote_query_community/payload_checker.py#L104

```py
                " ".join(getattr(self.payload, attr) for attr in ("title", "tags", "text") if hasattr(self.payload, attr))
```

https://github.com/Tribler/tribler/blob/8df8154193f404e20ba4ff9ba9d46f082820a132/src/tribler/core/components/libtorrent/restapi/downloads_endpoint.py#L53

```py
        return ''.join(map(chr, ext_peer_info))
```

- Tribler's version [main branch]

**Comment by drew2a** [comment]
@Solomon1732 thank you for your contributions to improving Tribler's code quality. If it's not too much trouble, could you kindly convert this issue into a pull request? This way, we could avoid duplication of work, as it would save us the step of implementing the string replacements that you've described. Plus, we could run tests on the modified code to ensure its correctness. 
Thank you in advance for your consideration.

**Comment by Solomon1732** [comment]
No problem. I would be glad to 😄
