### ISSUE TITLE
Watch Folder always uses the default download folder ignoring the folder specified in the settings.

### ISSUE THREAD

**Issue by Baroromka** [Tribler/tribler#7443]
Translated version:

Could be a duplicate of #3543

I add a torrent in the auto download folder and it downloads to the system drive TriblerDownload, but I need a folder for downloads specified in the settings.
I guess I just need some file to replace it, please send it to serv4392@gmail.com with the Tribler prefix or give me an update if I suddenly found the application problem.
I have a hundred and fifty torrents to distribute, I do not really want to tear down the application.
Thank you.

Original version:

Я так понимаю аналог https://github.com/Tribler/tribler/issues/3543
Я решил стать хранителем Rutracker и качаю файлы .торрент пачками.
![Снимок экрана (379)](https://github.com/Tribler/tribler/assets/108141701/148c6903-a490-4719-8f04-3c45dabc1db9)
Добавляю торрент в папку автоскачивания и он качается в системный диск загрузки TriblerDownload, а мне нужно в папку для закачек указанную в настройках.
Я так понимаю мне просто нужен какой то файл который нужно заменить, скиньте его пожалуйста на serv4392@gmail.com с припиской Tribler или дайте обновление если я вдруг нашел проблему приложения.
У меня полторы сотни торрентов на раздаче, сносить приложение не очень хочется.
Спасибо.

**Comment by drew2a** [comment]
To clarify the issue. 

### How to reproduce:
1. Open Tribler
2. Change "Download location" in the settings
3. Add a torrent in the watch folder
4. Torrent will be downloaded to the default download folder (instead of the folder, specified  in (2))

### Expected behavior
The torrent should be downloaded to the specified folder, but it was downloaded to the default download folder.

@Baroromka is this description correct?

---

It looks like the watch folder always uses default settings:

```python
            download_config = DownloadConfig.from_defaults(self.download_manager.download_defaults,
                                                           state_dir=self.state_dir)

            self.download_manager.start_download(torrent_file=path, config=download_config)
```
https://github.com/Tribler/tribler/blob/1335174cd2d3e91ebd8dafa4a4dbc4ad84d47fe8/src/tribler/core/components/watch_folder/watch_folder.py#L97C29-L100

**Comment by Baroromka** [comment]
> Чтобы прояснить проблему.
> 
> ### Как воспроизвести:
> 1. Откройте Tribler
> 2. Измените "Местоположение загрузки" в настройках
> 3. Добавьте торрент в папку просмотра
> 4. Торрент будет загружен в папку загрузки по умолчанию (вместо папки, указанной в (2))
> 
> ### Ожидаемое поведение
> Торрент должен быть загружен в указанную папку, но он был загружен в папку загрузки по умолчанию.
> 
> @Baroromka верно ли это описание?
> 
> Похоже, что папка просмотра всегда использует настройки по умолчанию:
> 
> ```python
>             DownloadConfig = download_config.из_запросов(self.download_manager.download_defaults, 
>  state_dir=self.state_dir)
> 
>  self.download_manager.start_download(torrent_file=path, config=download_config)
> ```
> 
> https://github.com/Tribler/tribler/blob/1335174cd2d3e91ebd8dafa4a4dbc4ad84d47fe8/src/tribler/core/components/watch_folder/watch_folder.py#L97C29-L100

Не совсем понял про папку просмотра. Полагаю имелось ввиду "папка автоскачивания"
Перефразирую
\\
Как воспроизвести:
1. Открыл Tribler
2. Изменил "Местоположение загрузки"(папка для закачек) в настройках на папку "Х"
3. Добавил торрент в папку просмотра(папка автоскачивания)
4. Торрент будет загружен в папку загрузки по умолчанию (вместо папки, указанной в (2) тоесть вместо "Х")
Ожидаемое поведение
Торрент должен быть загружен в указанную в настройках папку "Х", но он был загружен в папку загрузки по умолчанию(C:\Users\user\Downloads\TriblerDownloads , пробовал удалять папку создает заного). Ручной запуск .торрент дает выбрать место установки, но при закачке 20-30 торрентов хотелось бы просто кинуть в папку автозагрузки если есть якобы такая опция. 
Игнорирует настройки, качает в папку по умолчанию (МОЙ ПРИМЕР C:\Users\user\Downloads\TriblerDownloads)
![Снимок экрана (387)](https://github.com/Tribler/tribler/assets/108141701/2411a564-1443-4e37-8756-9ae04ab98690)
![Снимок экрана (388)](https://github.com/Tribler/tribler/assets/108141701/ab565ad0-f574-41a6-8da1-59f5925935f4)
Приложил скрин папки стандартной(ошибочной) и требуемой папки загрузки
\\
Да папка автоскачивания всегда использует стандартную папку на системном диске даже если её удалить или не трогать "C:\Users\user\Downloads\TriblerDownloads". Пробовал менять настройки с админ правами та же беда.
\
Менял предложенный выше файл найдя его через поиск, предварительно скопировав оригинал, через перезагрузку приложения - эффекта нет.
Так же поробовал создать в системном диске , в корне, Папку "А" назначив её папкой автоскачивания, через перезагрузку приложения - нет эффекта.
Так же создал папку загрузки "B" на системном диске, в корне, через перезагрузку приложения после применения настроек добавил в папку "А" торрент - нет эффекта. Менял местами так же.
