### ISSUE TITLE
Tribler window cannot restore fullscreen mode after reopening

### ISSUE THREAD

**Issue by nullptr-deref** [Tribler/tribler#7458]
**Description**
After setting Tribler window to fullscreen mode and reopening it, it opens strangely resized instead of being opened fullscreen again.

**Reproduction**
1. Open Tribler.
2. Enter fullscreen mode (click 2nd button on the top right side of the Windows window).
3. Exit Tribler entirely and reopen it.
4. Window appears non-fullscreen but resized awkwardly to fit entire screen.

**Expected behavior**
Window should appear in a fullscreen mode.

**Screenshots**
This is how Tribler window looks like right before closing it (as you can see, it fits available screen space properly)...
![How Tribler window looks like right before closing](https://github.com/Tribler/tribler/assets/55032128/88e69f89-eb95-4cba-a465-4bce5f375ccf)

...And this is how it looks like after reopening (pay attention that desktop background is visible on the left side of the screen, between taskbar and actual Tribler window).
![Tribler window after reopening](https://github.com/Tribler/tribler/assets/55032128/321f066b-f0c4-499b-8424-2f40e393b05d)

As you can see, it's translated somehow inappropriately and with fullscreen mode disabled.

**Desktop (please complete the following information):**

- OS: Windows 10 Pro 22H2
- Tribler's version: 7.12.1 stable

**Additional context**
As far as I've understood, Tribler window remembers its size and position and writes it to GUI settings. I suppose additional field remembering whether it was closed while being opened fullscreen or not should fix the problem.

**Comment by drew2a** [comment]
I can not reproduce it on macOS (tried both `7.12` and `7.13`)

**Comment by nullptr-deref** [comment]
Seems like this issue appears only under Windows. Will try to install Tribler under Arch Linux and see what'll happen.

**Comment by nullptr-deref** [comment]
Btw, is there any way to install Tribler under Arch Linux properly? Couldn't manage to do it 'cause `pacman` repos don't have anything near to `python[3]-libtorrent` so script `makedist_debian.sh` fails with the following message:

```
ERROR: Could not find a version that satisfies the requirement libtorrent==1.2.15 (from versions: none)
ERROR: No matching distribution found for libtorrent==1.2.15
```

My system is Arch Linux x86_64, kernel: `6.4.3-arch1-1`.

**Comment by drew2a** [comment]
> Btw, is there any way to install Tribler under Arch Linux properly? 

We don't support Arch Linux (see supported distributions [here]( https://tribler.readthedocs.io/en/latest/development/development_on_linux.html)), but you can try to build libtorrent from source: https://github.com/arvidn/libtorrent/blob/RC_2_0/docs/building.rst

**Comment by nullptr-deref** [comment]
Ah, I see. Will try in a couple of days.

**Comment by heldersepu** [comment]
Just tested on Ubuntu & is working as expected

@nullptr-deref  What if you manually resize the window to a fullscreen size then exit and reopen...

I get a feeling that this issue is windows been weird and not reporting a the resize when clicking the , then tribler does not update the size in the gui_settings, also can you check the value of size in your `~/.config/nl.tudelft.tribler.conf` 

you should see something like:
```
family_filter=true
first_discover=true
last_reported_version=7.13.3
minimize_to_tray=false
pos=@Point(578 644)
size=@Size(2149 1119)
translation=@Invalid()
use_monochrome_icon=true
```
pos and size are the interesting values there from your side

**Comment by qstokkink** [comment]
Tribler now has a web-based front end and this issue is no longer relevant.
