### ISSUE TITLE
Remove old state directories doesn't work.

### ISSUE THREAD

**Issue by kotenok2000** [Tribler/tribler#7476]
**Describe the bug**
When i upgraded 7.12 to 7.13-КС2, ticked 7.12 state directory and pressed "Remove selected versions" nothing happened.
**To Reproduce**

1. Install 7.12
2. Upgrade to 7.13-RC2
3. open data tab in settings.
4. Try to remove old data directory.

**Expected behavior**
Tribler removes 7.12 datadir
**Screenshots**

**Desktop (please complete the following information):**

- OS: Microsoft Windows [Version 10.0.22621.1702]
- Tribler's version: 7.13.0-RC2_x64
**Additional context**
![image](https://github.com/Tribler/tribler/assets/8822292/b8d8d092-eb89-4056-9de8-6f807d3d73cb)

**Comment by drew2a** [comment]
I've attempted to reproduce this bug on my macOS system, and it seems to operate correctly.

@kotenok2000, can you consistently reproduce this bug on your machine, or does it only occur sporadically?

**Comment by kotenok2000** [comment]
It happens on my Windows machine.

**Comment by qstokkink** [comment]
I can reproduce this on Windows 10. Steps followed:

1. Install Tribler 7.12 and run once (apparently I still had a state dir from before).
2. Install Tribler 7.13 RC2 and run.
3. Click the remove selected versions button.

Result, no update in the GUI and the selected version folder is still in my `%APPDATA%/.Tribler/` file list:

![screenshot](https://github.com/Tribler/tribler/assets/3630389/a8f98c97-4012-48be-9114-3c2ddc976d38)

**Comment by qstokkink** [comment]
This seems like a very high priority issue, actually. In the worst case, we are removing a use folder that Tribler did not create.

The filtering on our settings pages seems to be made for UNIX `os.sep` (`/`):

https://github.com/Tribler/tribler/blob/1484896af9f646ee650ef4573344372e6b806894/src/tribler/gui/widgets/settingspage.py#L271-L279

This causes my version (on Windows) to be set to `\7.12`, see the previously posted log output.

Then, `remove_state_dirs(self, state_dirs: List[str])` is called with `["\\7.12"]`.

This causes `os.path.join(self.root_state_dir, state_dir)` to be called with `os.path.join("%APPDATA%\\.Tribler", "\\7.12")` (I shortened the actual absolute appdata folder here to `%APPDATA%`).

https://github.com/Tribler/tribler/blob/1484896af9f646ee650ef4573344372e6b806894/src/tribler/core/upgrade/version_manager.py#L429-L430

**This is where it gets bad.**

```python
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>>
>>> # This is what we expect
>>> state_dir = os.path.join("%APPDATA%\\.Tribler", "7.12")
>>> state_dir
'%APPDATA%\\.Tribler\\7.12'
>>>
>>> # This is what is actually being fed to remove_state_dirs
>>> state_dir = os.path.join("%APPDATA%\\.Tribler", "\\7.12")
>>> state_dir
'C:\\7.12'
```

**[CONFIRMED] If the user happens to have a folder on their C drive that happens to be the same as the Tribler version, it gets removed (`C:\7.12` in this case).**

**Comment by drew2a** [comment]
Could be related: #7098
