### ISSUE TITLE
Text in drop-down menu for choosing file formats during search is unreadable 

### ISSUE THREAD

**Issue by kotenok2000** [Tribler/tribler#7488]
**Describe the bug**
Text in drop-down menu for choosing file formats during search is unreadable
It is The text is white on white.
**To Reproduce**

1. Go to search
2. Search something

**Expected behavior**
The text is black on white.
**Screenshots**
![image](https://github.com/Tribler/tribler/assets/8822292/0a1a625b-7473-49c8-9faf-faab312b9332)
![image](https://github.com/Tribler/tribler/assets/8822292/5018225a-9526-4640-9b53-9fa94215db2e)

**Desktop (please complete the following information):**

- OS: Microsoft Windows [Version 10.0.22621.1848]
- Tribler's version 7.13.0-RC2

**Additional context**

**Comment by drew2a** [comment]
I wasn't able to reproduce the issue on macOS. It's possible that this bug is OS-dependent.
