### ISSUE TITLE
Seeding option only follow HH:MM data format & not the others

### ISSUE THREAD

**Issue by absolutep** [Tribler/tribler#7519]
**Describe the bug**

Seeding option only follows the HH:MM data & all the other options are neglected.
Meaning, if you selected unlimited seeding or seeding according to ratio, eg, 2:1. Tribler will not follow this rule but instead will follow the rule written in HH:MM

**To Reproduce**

Go to tribler settings >> write any amount of time in HH:MM option >> save >> quit >> check Tribler config file >> HH:MM format seeding time is denoted in overall seconds.

Now,

Go to Tribler settings >> seeding options >> select unlimited seeding >> save >> quit >> check Tribler config file >> HH:MM format seeding time is denoted in overall seconds and not the unlimited seeding or any ratio seeding.

**Expected behavior**

When Unlimited seeding is selected - Tribler should follow this rule.

When Specific ratio seeding is selected, for eg, 2:1, Tribler should follow this rule.

Instead Tribler only follows the HH:MM format rule, irrespective of your seeding choice.

**Screenshots**

Unlimited seeding is chosen & data entered in HH:MM format.

Tribler Config shows - Tribler choses HH:MM format data everytime irrespective of user's chosen option.

![1](https://github.com/Tribler/tribler/assets/97702149/931985c5-58e1-482b-9bad-71f0c34972b5)

![2](https://github.com/Tribler/tribler/assets/97702149/b261cbf6-1a32-4a88-b7cb-81630c99fc81)

![3](https://github.com/Tribler/tribler/assets/97702149/f13d61e6-17df-4ec0-ad3a-7440993cf12d)
![4](https://github.com/Tribler/tribler/assets/97702149/da343598-ce47-40ec-b17a-6649d9b05c83)

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10]
- Tribler's version [e.g. 7.13.RC2]

**Comment by drew2a** [comment]
@absolutep thank you for the report. I was able to reproduce the bug and hopefully can provide a fix for it soon.

**Comment by drew2a** [comment]
After some investigation, I can confirm that this isn't a bug but rather a characteristic of how values are stored in the Config.

Tribler Config does not persist default values, meaning that if a value is set to its default, it won't be written to disk (and vice versa).

Here are the default values for `DownloadDefaultsSettings`:

```python
class DownloadDefaultsSettings(TriblerConfigSection):
    anonymity_enabled: bool = True
    number_hops: int = 1
    safeseeding_enabled: bool = True
    saveas: str = str(get_default_download_dir())
    seeding_mode: SeedingMode = SeedingMode.forever
    seeding_ratio: float = 2.0
    seeding_time: float = 60
    channel_download: bool = False
    add_download_to_channel: bool = False
```

Just because you see `seeding_time` and `seeding_ratio` in your config doesn't imply they are in use.

To determine the currently active seeding option, check the value of `seeding_mode`. If this value is absent, then the default `forever` is applied.
