### ISSUE TITLE
Additional headless command line flags

### ISSUE THREAD

**Issue by jutoft** [Tribler/tribler#7560]
**Is your feature request related to a problem? Please describe.**
I would like to run tribler headless inside a docker container, without having to modify config after startup.

**Describe the solution you'd like**
The option to set the relevant ports and paths using environment variables.

**Describe alternatives you've considered**
Building my own image

I'm a bit confused as to why there is a tribler.py and tribler_headless.py the headless variant allows to set more values, but is it deprecated?

**Additional context**

Example docker container running headless.
```
# libtorrent-1.2.9 does not support python 3.11 yet
FROM python:3.10-slim

RUN apt-get update \
    && apt-get install -y libsodium23 \
    && rm -rf /var/lib/apt/lists/*

# Then, install pip dependencies so that it can be cached and does not
# need to be built every time the source code changes.
# This reduces the docker build time.
COPY ./requirements-core.txt /app/tribler/core-requirements.txt
RUN pip3 install -r /app/tribler/core-requirements.txt

# Copy the source code and set the working directory
COPY ./src /app/tribler/src/
WORKDIR /app/tribler/

# Set to -1 to use the default
ENV CORE_API_PORT=20100
ENV IPV8_PORT=7759
ENV TORRENT_PORT=-1
ENV DOWNLOAD_DIR=/downloads
ENV TSTATEDIR=/config

VOLUME /config
VOLUME /downloads

# Only run the core process with --core switch
CMD exec python3 /app/tribler/src/run_tribler_headless.py --restapi_http_port=${CORE_API_PORT} --ipv8=${IPV8_PORT} --libtorrent=${TORRENT_PORT} --restapi_http_host=0.0.0.0 --restapi_https_host=0.0.0.0 " --statedir=${TSTATEDIR}" "--downloaddir=${DOWNLOAD_DIR}"
```

I introduced a few of the command line arguments to free me from messing around in the config file manually after.
Would a change like this be accepted?

**Comment by xoriole** [comment]
@jutoft It is a good idea to use the environment variable. We would very much welcome a PR.
