### ISSUE TITLE
improved openapi/swagger docs & support for true/false input to boolean arguments

### ISSUE THREAD

**Issue by jutoft** [Tribler/tribler#7562]
**Is your feature request related to a problem? Please describe.**
Tribler is missing a proper web-ui but it does have the openapi /docs endpoint which can be used instead.

**Describe the solution you'd like**
The /docs endpoint that allow setting one of the boolean flags to true or false, currently the code only allows 0 & 1.

**Describe alternatives you've considered**
Calling the endpoints from postman.

**Additional context**
I'm happy to help improve the docs and openapi.

**Comment by xoriole** [comment]
@jutoft Nice! We would welcome contributions to the improvements of OpenAPI docs and UI :+1:
