### ISSUE TITLE
Update docker image to latest versions

### ISSUE THREAD

**Issue by jutoft** [Tribler/tribler#7563]
**Is your feature request related to a problem? Please describe.**
Update python to 3.10 & libtorrent to 1.2.19

**Describe the solution you'd like**
Switch base image to be python:3.10-slim & then rely on libtorrent from pypi

**Describe alternatives you've considered**
using python:311 & builing libtorrent in a builder image, but it's hard to get working. libtorrent is not available for python 3.11 yet.

**Additional context**
Example Dockerfile in #7560

**Comment by xoriole** [comment]
@jutoft You're right. Dockerfile was setup before Libtorrent was available on PyPi. Now, we can use `slim` python docker image and PyPI libtorrent. 

It is not a priority for the current release for us but would welcome a PR if you'd like to contribute :+1:
