### ISSUE TITLE
[7.12.1] Download directory suddenly reverted

### ISSUE THREAD

**Issue by Radnozyp** [Tribler/tribler#7569]
**Describe the bug**

All of a sudden my tribler download directory reverted to a year-old previous download folder. 

Tribler 7.12.1
Windows 11

**Comment by xoriole** [comment]
@Radnozyp Thank you for reporting this bug. This is definitely not the expected behavior. To be able to diagnose the issue, we would need more information. 

What was the last thing you have done before the issue occurred? Have you upgraded recently?

**Comment by synctext** [comment]
@Radnozyp We're trying to figure out your bug. Very strange!
Can you help us out and share more info?

> All of a sudden my tribler download directory reverted

That means you where using Tribler normally? Was during startup or upgrade?

**Comment by Radnozyp** [comment]
Hey, sorry about the late response. 

AFAIK I was using tribler normally when it happened, though I was away travelling so jumping between IP:s alot. I think it happened right after a tribler update.

**Comment by Radnozyp** [comment]
I was just using it normally.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by qstokkink** [comment]
@Radnozyp that should be all you need to do. In the next release, just using it as normal should work again.
