### ISSUE TITLE
pytest-timeout is not working as expected when pytest-rerunfailures is enabled

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#7581]
`pytest-timeout` is not working well with `pytest-rerunfailures`.
See: https://github.com/pytest-dev/pytest-timeout/issues/18

Because of this, the default timeout of 60 seconds is not applied on the tests and sometimes some tests get stuck for several minutes resulting in GitHub action's execution timeout of 10 minutes.

One of the such tests is `test_check_and_regen_personal_channel_torrent_sleep` which was stuck for approx 8 minutes.
Logs here: https://github.com/Tribler/tribler/actions/runs/5937813183/job/16103116115?pr=7575

Link might not be available for long so here is the relevant logs snippet:
```python
...
Tue, 22 Aug 2023 12:08:22 GMT
12:08:22.908 Starting "test_check_channels_updates"...
Tue, 22 Aug 2023 12:08:23 GMT
src/tribler/core/components/gigachannel_manager/tests/test_gigachannel_manager.py::test_check_channels_updates PASSED [ 26%] in 0.204s (a minute in total)
Tue, 22 Aug 2023 12:08:23 GMT
12:08:23.112 Starting "test_check_and_regen_personal_channel_torrent_sleep"...
Tue, 22 Aug 2023 12:16:12 GMT
src/tribler/core/components/gigachannel_manager/tests/test_gigachannel_manager.py::test_check_and_regen_personal_channel_torrent_sleep 
Tue, 22 Aug 2023 12:16:12 GMT
Error: The operation was canceled.
```
---
So, I would be in favor of disabling `pytest-rerunfailures` so we can find out the tests which are getting stuck and fix them properly.

**Comment by drew2a** [comment]
The example provided in the [issue](https://github.com/pytest-dev/pytest-timeout/issues/18) works well with `reruns == 0`

```python
@pytest.mark.timeout(2)
@pytest.mark.flaky(0)
def test_new():
    time.sleep(10)
    assert True
```

Perhaps if we run our tests with this argument, `pytest-sentry` will work as expected (this statement needs verification by doing an experiment).

**Comment by drew2a** [comment]
Seems that we still have tests that could not be stopped by `pytest-timeout` although the pytest-rerunfailures is disabled.
