### ISSUE TITLE
The GPL is not an EULA

### ISSUE THREAD

**Issue by wkrick** [Tribler/tribler#7585]
**Describe the bug**
The Tribler installer includes the GPL text in an End User License Agreement (EULA) click-through page.  The GPL is not a license for end users of the software and it doesn't belong in the installer.  It serves no purpose legally or otherwise.

**To Reproduce**
1. Start the Tribler installer and see the License Agreement click-through

**Expected behavior**
The GPL text should not be in a click-through license during the install

**Screenshots**
![image](https://github.com/Tribler/tribler/assets/10203734/8be41ce6-8a85-4c1b-864e-e7bb4925cd2c)

**Desktop (please complete the following information):**

- OS: Windows 10 64-bit
- Tribler's version: 7.13.0

**Additional context**
References:  
https://flameeyes.blog/2020/03/23/the-gpl-is-not-an-eula/
https://drj11.wordpress.com/2008/02/25/the-gnu-gpl-is-not-an-eula/
https://twitter.com/Foone/status/1528010830448451585
https://digipres.club/@foone/110719488736965037

**Comment by drew2a** [comment]
Related: #6590
