### ISSUE TITLE
Old tunnel traffic due to high turnover in socket and stale DHT info

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#7629]
Receiving incoming old DHT traffic.
A new peer gets a fresh tunnel slot. DHT has stale information. Other peers on the network try to connect to old peer, but they connect to you. You have joined other swarms.

There are graphs!!! these are sort of the background noise radiation https://en.wikipedia.org/wiki/Internet_background_noise, but now the DHT.

Security implication: even a 30 minute DHT cooldown is insufficient :boom: :bomb: :boom: 
Bittorrent traffic is fine, that stops.

**Comment by egbertbouman** [comment]
Unfortunately, there isn't much we can do about it. Currently, if you create a circuit and send a single packet through it (triggering socket creation at the exit node), you get lots of old traffic.

One way of mitigating this somewhat would be to allow the circuit creator to reuse the same port as was used earlier at a specific exit node. Right now peers jump from port to port every time a circuit gets re-created. This would have to be added to IPv8.
