### ISSUE TITLE
Remove outdated migrations (prior to `8.0`)

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#7631]
To maintain a clean and minimalistic codebase for the Upgrader, we should remove outdated migrations (prior to `8.0`) and retain only the newer ones #7622.

Additionally, we need to include a disclaimer stating that direct upgrades from older Tribler versions to versions `8.1+` are not supported. Users must first upgrade their old Tribler version to `8.0`.

Related to #7382

**Comment by qstokkink** [comment]
All migrations have now been removed.
