### ISSUE TITLE
Build failed - ReadTheDocs Tribler

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#7636]
**Error**
The configuration key "build.image" is deprecated. Use "build.os" instead to continue building your project. Read more at https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os

https://readthedocs.org/projects/tribler/builds/22250628/

![screenshot-readthedocs org-2023 10 17-11_07_32](https://github.com/Tribler/tribler/assets/1442867/4db68f48-ea64-47e5-a4fe-f01bddb6da12)

**Comment by qstokkink** [comment]
I also had to fix this in IPv8: https://github.com/Tribler/py-ipv8/pull/1206
