### ISSUE TITLE
`index out of range` error by selecting torrents on the downloads page

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#7646]
When on the downloads page, keeping the "Files" tab open, you can generate errors by simply successively clicking on different downloads.

![state](https://github.com/Tribler/tribler/assets/3630389/c471925b-2915-4c33-8428-79040b6a0f64)
![error](https://github.com/Tribler/tribler/assets/3630389/64214b83-c76f-4db9-9e01-2e84f0e01631)

The stack trace is as follows:

```python
index out of range
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/src/tribler/gui/network/request.py", line 114, in on_finished
    self._handle_http_response(status_code)
  File "/home/quinten/Documents/tribler/src/tribler/gui/network/request.py", line 156, in _handle_http_response
    raise Warning(text)
Warning: An error occurred during the request "PATCH http://localhost:32919/downloads/9eca33223c8b37b7b0ec44355e1abfb812fd43f9":
```

The torrents are:

- magnet:?xt=urn:btih:c398a571976c78d346c325bd75c47b82edf6124e&dn=reddit
- magnet:?xt=urn:btih:9eca33223c8b37b7b0ec44355e1abfb812fd43f9&dn=Unknown+name&tr=https://academictorrents.com/announce.php&tr=udp://tracker.coppersurfer.tk:6969&tr=udp://tracker.opentrackr.org:1337/announce

**Comment by drew2a** [comment]
The caller of the PATCH request is `/Users/drew2a/Projects/github.com/Tribler/tribler/src/tribler/gui/widgets/downloadsdetailstabwidget.py, line 208 in set_included_files`

```python
[tribler-gui PID:13041] 2023-10-31 10:42:18,541 - ERROR <request:123> Request.on_finished(): An error occurred during the request "PATCH http://localhost:58207/downloads/<hash>
Caller: <FrameSummary file /Users/drew2a/Projects/github.com/Tribler/tribler/src/tribler/gui/widgets/downloadsdetailstabwidget.py, line 208 in set_included_files>":
```
