### ISSUE TITLE
Improve Core Process Error Handling: Restart on Crash and Prompt for Error Reporting

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#7647]
## Overview
Currently, when the core process of Tribler encounters a serious error, the application is made to crash. This behavior can be optimized to enhance user experience and provide a more robust error-reporting mechanism. This proposal is to ensure that whenever the core process crashes from an unhandled error, the GUI detects it and initiates a restart of the core process. Furthermore, if the new core process identifies that there was an unreported error from the previous run, it will notify the GUI to prompt the user for error reporting.

## Proposal Details
**1. Detect Core Process Crash in GUI :** Implement a check on the state change of the Core process in CoreManager that checks the status of the core process. If the core process is not running without an intentional shutdown, it should be interpreted as a crash. Additionally, the errors that are propagated via events endpoint that are not subclasses of NoCrashException, also crash the application. This should be handled as well.

**2. Restart the Core Process :** Upon detecting the crash, the GUI should initiate the restart of the core process.

**3. Save Sentry Event on Crash :**  Whenever there's a crash in the core process, save the sentry event locally. This will enable us to access crash details in the subsequent runs. If the event is sent to the error reporter, then the saved event can be removed.

**4. Detect Unreported Errors on Core Start :** When the core process starts, it should first check for any saved sentry events that were not reported in the previous runs.

**5. Communicate Unreported Errors to GUI :** If an unreported error is detected, the core process should notify the GUI about it.

**6. Prompt User for Error Reporting :** Upon receiving a notification about an unreported error, the GUI should display a popup dialog to the user, asking if they'd like to send the error report. This allows users to have a choice whether or not to send the error report.

## Benefits
- **Enhanced User Experience :** By automatically restarting the core process upon a crash, the disruption on using Tribler will likely reduce for the user.
- **Efficient Error Reporting :** Saving the errors that were not sent to the GUI during the crash will get collected in the next run. This increases the chances of finding out the actual cause of the error if the user reports the error. This will give us more insights.

This proposal seeks to improve the resilience of Tribler in the face of unexpected errors and optimize the error-reporting process. Feedback and further suggestions are welcome.

**Comment by drew2a** [comment]
Sounds promising. However, one concern is the potential for an "endless core restart" loop if the same error repeatedly occurs.

1. Launch GUI
2. Start Core
3. Encounter error in Core
4. Restart Core
5. Encounter the same error in Core
6. And so on...

**Comment by xoriole** [comment]
> Sounds promising. However, one concern is the potential for an "endless core restart" loop if the same error repeatedly occurs.
> 
> 1. Launch GUI
> 2. Start Core
> 3. Encounter error in Core
> 4. Restart Core
> 5. Encounter the same error in Core
> 6. And so on...

A simple solution for that could be: Since the GUI is in control of restarting the core, the decision whether or not to restart can be made based on when was the last time the core was restarted and how many times so far.

**Comment by synctext** [comment]
Could you please describe what exact bugs you're thking about? Which bug types are not in a core log file and we can still detect after restart?

**Comment by xoriole** [comment]
@synctext 

The linked issue shows a GUI problem where the connection drops without explaining why. When users see this, they likely restart Tribler and it might work again. But, we don't get to know if they had a core crash earlier.

With this proposal, we can see the exact error from the last crash and also find out if the core has crashed before and how often.


- https://github.com/Tribler/tribler/issues/7603 
- https://sentry.tribler.org/organizations/tribler/issues/2003/events/f1a9c56138aa4dbea5598d00c2a72311/?project=7&query=is%3Aunresolved+version%3A7.13.0&referrer=previous-event&stream_index=2
