### ISSUE TITLE
Anonymous download performance enhancements

### ISSUE THREAD

**Issue by egbertbouman** [Tribler/tribler#7684]
I'm currently doing some performance enhancements to our core, in particular to the IPv8 socket/tunnel community. By moving some code to rust (https://github.com/Tribler/py-ipv8/issues/1119), we're getting much better download speeds:

![rust_25mb](https://github.com/Tribler/tribler/assets/3785124/ba5151b1-7688-4700-adf9-9247669cad4f)

**Comment by synctext** [comment]
25.5 MByte/sec download speed :boom: 
Real results, after starting abandoned experiments in 2019: https://github.com/Tribler/tribler/issues/4567
:rocket:

**Comment by ichorid** [comment]
I wonder how much of increase that will be, if you move _both_ sides of the tunnel (e.g. tunnel helpers too) to Rust... :star_struck:

**Comment by egbertbouman** [comment]
I don't really expect to see speeds beyond what I'm currently seeing. If I look at the speed with just a single circuit, it won't go beyond 3MB/s. So, while testing, I worked around the issue by creating 20 circuits.
At 25MB/s the most CPU intensive thread will use a full core at the downloader side. Of course, it all depends on which machine you use.

**Comment by synctext** [comment]
As discussed in Dev Meeting...this month, Jan 2024 all Rust matters on both IPv4 and IPv6 should come together. Stable performant code is the ambition.

**Comment by egbertbouman** [comment]
IPv8 has now been refactored to support a separate Rust endpoint (https://github.com/Tribler/py-ipv8/pull/1250). There is also a [release](https://pypi.org/project/ipv8-rust-tunnels/) on PyPI.

**Comment by qstokkink** [comment]
For the occasion, I gave the Rust implementation a run on my bare metal machine (AMD Ryzen Threadripper 3970X 32-Core, 64 GB 2666 MHz RAM, from an M2 drive with a gigabit Internet connection).

As a benchmark, using the same torrent, I gathered three results that are more-or-less repeatable:

 - A 0 hop download using the Libtorrent 2.0.7 "simple client" C implementation: the maximum we can achieve with Tribler.
 - A 0 hop download using "Tribler Experimental" and Libtorrent 1.2.19 with everything switched off except the download manager, IPv8, and the tunnel community.
 - A 1 hop download using "Tribler Experimental" and Libtorrent 1.2.19 with everything switched off except the download manager, IPv8, and the tunnel community.
 
 Here are the screenshots:
 
 
# Libtorrent 2.0.7 C implementation +- 110 MB/s
![simpleclient 0 hops](https://github.com/Tribler/tribler/assets/3630389/9ff99d2e-6978-454c-bafe-0478d854f62e)

# Tribler 0 hops +- 67.5 MB/s 
![Tribler 0 hops](https://github.com/Tribler/tribler/assets/3630389/320578e7-e5ed-4680-a949-dfe5aa64aae7)

# Tribler Rust 1 hop anonymous +- 27.5 MB/s 
![Tribler 1 hop](https://github.com/Tribler/tribler/assets/3630389/b9954a84-9853-4b98-ac43-ca95c05825a0)
