### ISSUE TITLE
EVA: enable concurrent transfers to the same peer

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#7698]
[EVA protocol](https://github.com/Tribler/tribler/blob/main/src/tribler/core/components/ipv8/eva/protocol.py) is a binary data transfer protocol based on [TFTP](https://datatracker.ietf.org/doc/html/rfc1350) with [window size (RFC 7440)](https://datatracker.ietf.org/doc/html/rfc7440) implemented on top of the [ipv8 networking layer](https://github.com/Tribler/py-ipv8).

The design initially aimed to facilitate a thumbnail feature for channels, with the first version of the protocol kept as simple as possible. However, this protocol has evolved over time.

The first round of improvements was spearheaded by @devos50, following his experiment with large-scale binary model transfers for distributed machine learning experiments ([#6831](https://github.com/Tribler/tribler/issues/6831)). This enhancement also incorporated a bug fix identified by @rmadhwal and detailed in [trustchain-superapp issue #101](https://github.com/Tribler/trustchain-superapp/issues/101). 

The next set of refinements was led by @kozlovsky in #6845, following his review of #6831.

A possible future enhancement is enabling concurrent transfers to the same peer, as discussed in https://github.com/Tribler/tribler/issues/7074#issuecomment-1628696293, https://github.com/Tribler/tribler/issues/7258#issuecomment-1745109933. Until now, this feature wasn't a priority in Tribler, given the lack of substantial demand for simultaneous binary transfers to the same peer. However, the time may be right to reconsider this?

_It's also important to note that the Python EVA and Kotlin EVA have different implementations and are likely incompatible as of now._

**Comment by qstokkink** [comment]
The code for this feature has been removed and this issue is no longer relevant.
