### ISSUE TITLE
Addition of License Headers to Source Code Files

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#7717]
The purpose of this issue is to address a potential gap in our project's compliance with its own licensing terms. It has been brought to our attention that while [cleaning up the license files](https://github.com/Tribler/tribler/issues/6590), we should also consider adding explicit license headers to each file in our source code, particularly those intended to be under the GPL.

The lack of these headers in our source files could lead to ambiguity regarding the licensing and, more critically, might result in a violation of our own license terms. The suggestion is to systematically add these headers to ensure clarity and legal compliance. This task involves identifying all files that fall under the GPL and updating them with the appropriate license headers.

**Action Items:**

1. Identify all source code files that should be licensed under the (L)GPL.
1. Draft a standard license header template that aligns with our project's licensing terms.
1. Implement a process for adding these headers to the identified files.

This issue aims to enhance the transparency and legal integrity of our project's codebase.

**Comment by dertuxmalwieder** [comment]
I'll put myself on CC here, as I discovered the original problem. To summarise for those who have not been following the discussion: The GNU project [explicitly](https://www.gnu.org/licenses/gpl-howto.en.html) says that code is **only** GPL'd if it includes the licence header.

**Comment by qstokkink** [comment]
This is stated in https://www.gnu.org/licenses/gpl-faq.en.html#LicenseCopyOnly

> This statement should be in each source file. **A clear statement in the program's README file is legally sufficient** as long as that accompanies the code, but it is easy for them to get separated. Why take a risk of uncertainty about your code's license?

Essentially, the only reason to pollute our source code with thousands of lines of copy-pasted non-source-code text is the "risk" of someone violating our license, stealing our code, and putting it up without a license somewhere else.

In the time of mailing lists, I see this "accidental theft" as somewhat of a real issue. But now that everything is bundled in GitHub as one big project, I don't think the "risk" applies to us and we can do with the single "clear statement in the program's README file".

**Comment by dertuxmalwieder** [comment]
> now that everything is bundled in GitHub as one big project

So, in order to put Tribler under Public Domain (which isn’t a valid license in most countries), all I need to do is accidentally move the README files? I mean, a README (or even LICENSE) file is not exactly a legal document in itself.

Also, the GPL claims to be a “free license”. That means that I could take any file from Tribler and use it in my own work, without copying anything else. Nothing bad would happen if the files were clearly copyrighted.

**Comment by qstokkink** [comment]
> all I need to do is accidentally move the README files

Agreed. However, using that same reasoning, you could also accidentally move the headers out of the file. This leads to the same issue and - according to GPL itself - the README solution "is legally sufficient" anyway.

**Comment by dertuxmalwieder** [comment]
I think that “accidentally editing the header of a third-party file” is a weak excuse, but I’m open to be proven wrong. I _never_ accidentally removed a file header.

**Comment by qstokkink** [comment]
I do not want to start a debate on whether it is more likely to remove a header from a file or a file in its entirety. That would derail the conversation. My point is that - legally speaking - both are equivalent in their breach of the GPL. I'll explain my point further.

If a README is already sufficient, does adding statements to every single file make it more (or less) sufficient? No. A license is either legally sufficient or it is not ("sufficienter" does not exist). **There is no ambiguity here**: according to the GPL itself ([link](https://www.gnu.org/licenses/gpl-faq.en.html#LicenseCopyOnly)), specifying the license in the README is sufficient.

Building on the point that both forms of expressing the GPL are sufficient, which is worse: the stripping of (case 1) the README file laying out the GPL license or (case 2) any headers specifying the GPL license? Both instances violate a GPL license that is legally sufficient. Therefore, both are equivalent in their breach of the GPL. There is no lesser (or worse) violation. It does not matter if you "accidentally" lose a file with a README-based license or "accidentally" strip information from a header-based license, both cases are equally bad license violations, regardless of which one is most likely to occur.

With the severity of both violations being equal, we are not more (or less) protected by either option for expressing the GPL statement. At this point becomes a matter of which form is easier to work with for us. In my opinion, having a single statement in the README is easier to maintain.

**Comment by dertuxmalwieder** [comment]
> In my opinion, having a single statement in the README is easier to maintain.

“Maintenance” (here) equals running `sed` over a set of files once.

**Comment by drew2a** [comment]
@dertuxmalwieder do you agree with this statement?

>If a README is already sufficient, does adding statements to every single file make it more (or less) sufficient? No. A license is either legally sufficient or it is not ("sufficienter" does not exist). There is no ambiguity here: according to the GPL itself ([link](https://www.gnu.org/licenses/gpl-faq.en.html#LicenseCopyOnly)), specifying the license in the README is sufficient.

**Comment by drew2a** [comment]
@qstokkink, do you think that the presence of the `LICENSE.txt` file is sufficient, or should we add something directly to `README.rst`?

>This statement should be in each source file. A clear statement in the program's README file is legally sufficient as long as that accompanies the code, but it is easy for them to get separated. Why take a risk of uncertainty about your code's license?

**Comment by dertuxmalwieder** [comment]
I actually wonder why the discussion about something that could be solved with a one-liner (or not ;-)) is taking five days again. Add the header or don't, it's your project and not mine.

**Comment by drew2a** [comment]
@dertuxmalwieder I appreciate your suggestion about adding headers to all source files. Indeed, it's comparable to implementing formatting changes, like adopting black, along with other similar modifications that might seem straightforward to implement. However, it's always important for us to consider whether such changes are truly necessary and beneficial.

Reflecting on the discussion above, it seems the action you're proposing might not be essential, given that the LICENSE file adequately covers our needs in this context. We should carefully weigh the real advantages of any proposed action before deciding to proceed.

Regarding your specific request, it involves more than just adding a header to each source file. It also implies a significant alteration to our developers' workflow, which @qstokkink referred to as "maintenance" (am I right, @qstokkink?). Given that Tribler experiences a relatively high turnover rate among developers due to the nature of our work, implementing this change might not be as straightforward as it appears.

I hope this clarifies our position, and I'm open to further discussions on this matter.

**Comment by qstokkink** [comment]
>@qstokkink, do you think that the presence of the LICENSE.txt file is sufficient, or should we add something directly to README.rst?

The GPL instructions only mention the README file not the LICENSE file. To be safe, I'd say following the GPL verbatim and add something directly to the README.

>It also implies a significant alteration to our developers' workflow, which @qstokkink referred to as "maintenance" (am I right, @qstokkink?). 

Correct.
