### ISSUE TITLE
Add partially selected status for folders in the downloads list

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#7733]
![screenshot](https://github.com/Tribler/tribler/assets/3630389/b5e29fe2-2e68-4958-91e3-e57537087b49)

Currently our folder checkbox in the downloads lists functions as a "(de)select all in (sub)folder" trigger. This is expected and implemented.

It is common to have a "partially selected" state on the folder when the files and folders it contains do not share the same selected state. This is not currently implemented. It would be nice to have this common visual indicator on our folders.

**Comment by egbertbouman** [comment]
This is implemented in the  new web UI, and should be fixed in Tribler 8.
