### ISSUE TITLE
[pre-filelock] [7.13.0] PermissionError: The process cannot access the file because it is being used by another process: processes.sqlite

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#7744]
The error is rare; we have just three reports: two from a single user on Windows 7 32-bit and another report without the OS version specified.

In all three cases, the exact place of the error was different:
* GUI process started the Core process, and the Core process was not able to access the `processes.sqlite` file on startup: [link](https://sentry.tribler.org/organizations/tribler/issues/2504/?project=7)
* GUI process itself can't access the `processes.sqlite` file on startup: [link](https://sentry.tribler.org/organizations/tribler/issues/2297/?project=7)
* GUI process started the Core process and tried to read the REST API port from the `processes.sqlite` file: [link](https://sentry.tribler.org/organizations/tribler/issues/2357/?query=PermissionError&referrer=issue-stream&statsPeriod=14d&stream_index=5)

Why is the error surprising? Because no process should hold the lock to the `processes.sqlite` file for an extended period. All functions that work with this file are supposed to update it and release the lock immediately. There should be no long operations while the transaction is active.

The error may be in the `ProcessManager.connect` context manager. It may not handle the possible exception properly and leaves an open connection that holds the database lock. But this is just a guess.

Let's see if it is fixed in 7.13.1 with the `filelock`-based process lock added.

**Comment by drew2a** [comment]
The error still occurs in 7.13.1:

<img width="300" alt="image" src="https://github.com/Tribler/tribler/assets/13798583/c4acd6a4-b54b-4fe6-ad7f-846bc4f9cb50">

**Comment by qstokkink** [comment]
This issue seems to be about coordination between the GUI and a core process. The newest Tribler code no longer has these two processes and this issue should no longer be relevant.
