### ISSUE TITLE
https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Build-Win64/ not available

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#7763]
https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Build-Win64/ not available

**Comment by Nubro01** [comment]
My signin for user nubro01 does not work anymore, unable to request password.

**Comment by qstokkink** [comment]
We are switching away from Jenkins. In the future (very soon hopefully) builds will be available through the GitHub interface.
