### ISSUE TITLE
Bandwidth accounting tab displays contribution info in bytes instead of human readable format

### ISSUE THREAD

**Issue by kotenok2000** [Tribler/tribler#7765]
**Describe the bug**
Bandwidth accounting tab displays contribution info in bytes.
It should display information in human readable format.
**To Reproduce**

1. Go to 🪲 Debug
2. Click on Bandwidth accounting tab

**Expected behavior**
It displays information in human-readable format (kilobbytes, megabytes...) instead of bytes

**Screenshots**
![image](https://github.com/Tribler/tribler/assets/8822292/4150a441-b0f4-400c-bbdf-4ec1e1e42960)

**Desktop (please complete the following information):**

- OS: 10.0.22631.2715
- Tribler's version 7.13.1-RC2

**Additional context**

**Comment by drew2a** [comment]
@kotenok2000 thank you for this report.

It seems like an easy fix.

Also this could be solved by:
- #7336

**Comment by drew2a** [comment]
Fixed in
- #7336
