### ISSUE TITLE
cpu core is constantly at maximum

### ISSUE THREAD

**Issue by kotenok2000** [Tribler/tribler#7790]
**Describe the bug**

**To Reproduce**

1. Start running tribler
2. wait for a day

**Expected behavior**

**Screenshots**
![image](https://github.com/Tribler/tribler/assets/8822292/a01669c9-412a-4317-bfc9-898d4b41c3f5)

**Desktop (please complete the following information):**

- OS: Microsoft Windows [Version 10.0.22631.2861]
- Tribler's version 7.13.1

**Additional context**

**Comment by synctext** [comment]
Interesting report, thnx!

13.20% of CPU power goes to Trivler.exe... Is that a 16-core or other heavy multicore machine?
Seems also some uploading or anon encrypted relay traffic is going on. Changed the settings? Did you subscribe to many channels possibly?

**Comment by kotenok2000** [comment]
I have 8 hyperthreads

**Comment by qstokkink** [comment]
@xoriole do you think this is related to https://github.com/Tribler/tribler/issues/7711#issuecomment-1836209878 ?

**Comment by xoriole** [comment]
@qstokkink #7711 is for the debug pane for the first time opening, it is unclear if the debug pane was open in this case.

**Comment by drew2a** [comment]
Channels consume a significant amount of CPU, as does anonymous downloading.
The channels are now retired:
- #7669

And the CPU usage for anonymous downloads should be improved:
- #7684  

There is a high percentage chance that the problem will be solved in version `7.14`.

**Comment by kotenok2000** [comment]
Still happens on Tribler_7.14.0-debug_x86
[tribler-core-error.log](https://github.com/Tribler/tribler/files/15159884/tribler-core-error.log)

**Comment by drew2a** [comment]
Sorry for the misinformation. The changes I mentioned were intended to be in `7.14` if we had followed the regular release process. Now, they are scheduled for `7.15`: https://github.com/Tribler/tribler/milestone/44

**Comment by qstokkink** [comment]
The mentioned changes are now part of the release branch for version 8.0. This should now be solved for the next release.
