### ISSUE TITLE
Ancient version detected

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#7802]
I just downloaded Tribler 7.13.1 from tribler.org and I get the following message when launching Tribler. It is unclear to me what version I have now and what the next version is that I should install, or where to get that version from.

![](https://github.com/Tribler/tribler/assets/3630389/518dcadb-b611-431c-90ba-3ae2d3586d43)

**Comment by kotenok2000** [comment]
What version directory does %appdata%\.tribler have? 
My for example
![image](https://github.com/Tribler/tribler/assets/8822292/25201c2d-be43-403a-80fe-ed135fda3af5)

**Comment by qstokkink** [comment]
@kotenok2000 I had one `6.6` folder in `.Tribler` and removing it resolved this issue. I probably lost some data though (maybe?).

**Comment by qstokkink** [comment]
It would also be nice to have an option to skip upgrading and just start the new version without any old data.
