### ISSUE TITLE
Empty popular torrents

### ISSUE THREAD

**Issue by kotenok2000** [Tribler/tribler#7803]
**Describe the bug**
Popular torrents tab is empty

**To Reproduce**

1. Run tribler
2. Reach uptime of 6 hours and 36 minutes 

**Expected behavior**
Popular torrents isn't empty.
**Screenshots**
![image](https://github.com/Tribler/tribler/assets/8822292/ebb05a6f-b5a2-4a68-828e-f168bb192174)

**Desktop (please complete the following information):**

- OS: Windows 11
- Tribler's version 7.13.1

**Additional context**

**Comment by qstokkink** [comment]
Interesting. Big changes were made recently  to the popularity mechanism, on our main development branch. However, in your stable version, this should all still work flawlessly.

Just to check, could you see if you see any peers reported in the Debug screen on the IPv8->overlays tab?

**Comment by drew2a** [comment]
There is a high chance that the issue is fixed in 
- #7970
