### ISSUE TITLE
Tie Breaker

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#7807]
We have had, have, and will have PRs with conflicts between an author and a reviewer. Although it is preferable to find a consensus by the parties alone (by following the [Google Gude Book](https://github.com/google/eng-practices/blob/master/review/reviewer/index.md) for example), it is not always possible.

An example: https://github.com/Tribler/tribler/pull/7764#discussion_r1422051640

To resolve conflicts like this we collectively agreed (@synctext, @xoriole, @egbertbouman, @kozlovsky, @drew2a) to introduce a Tie Breaker mechanism which will follow: in the case of disagreement between the PR author and a reviewer, the PR author or reviewer could ask for a second opinion from a randomly chosen developer (tie breaker); the decision from the tie breaker is the final decision in the dispute, and both parties should adhere to it.

To implement the mechanism, I propose creating a GitHub Action that reacts to a specific comment (like 'second opinion', 'tie breaker', or suggest yours) and adds a randomly chosen developer from the [Tribler Reviewers Team](https://github.com/orgs/Tribler/teams/reviewers) as a reviewer for the PR. The Tie Breaker should provide their resolution for the conflict situation.

Another way to trigger the action is to add a specific label to the PR (like 'conflict', 'need a resolution', 'tie breaker').

Please comment on the idea itself and the way it should be implemented (GitHub actions or not? Comment or label? etc.).

**Comment by kozlovsky** [comment]
>adds a randomly chosen developer from the [Tribler Reviewers Team](https://github.com/orgs/Tribler/teams/reviewers) as a reviewer for the PR

Ideally, a randomly chosen developer should not be the PR author or the original reviewer :)

**Comment by xoriole** [comment]
I like the idea of the label instead of the comment. 
Suggestion for the label: `second reviewer`
