### ISSUE TITLE
Bandwidth Accounting/Tokens/Trust cleanup

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#7809]
**Describe the bug**
In other bug reports it has been stated that bandwidth calculations are not used anymore,
but there are still many bits of code that do;

https://github.com/search?q=repo%3ATribler%2Ftribler+Bandwidth+Tokens&type=code

https://github.com/search?q=repo%3ATribler%2Ftribler%20bandwidth%20accounting&type=code

https://github.com/search?q=repo%3ATribler%2Ftribler+trust&type=code

**To Reproduce**
Look in code for what the UI is not sharing.

**Expected behavior**
Bandwidth calculations should not exist under any name.

**Additional context**
If there is some work in progress feature that is currently dead code take it off the main branch until it works well enough to show in the UI.

**Comment by drew2a** [comment]
@Dmole, thank you for reporting.

I'm not certain it can be classified as a bug since there's nothing dangerous or unintended in the application's behavior. It seems more like a candidate for refactoring. Also, I'm not sure if any of these strings would be visible in the UI.

Related: 
- #7336

**Comment by Dmole** [comment]
> I'm not sure if any of these strings would be visible in the UI.

The first file in the first link above is visible in the UI under Settings > Anonymity

**Comment by Dmole** [comment]
It looks like the links in the OP still return some items that should be cleaned up.

**Comment by Dmole** [comment]
For example 1st link 2nd file "You can build trust by contributing bandwidth to the Tribler network."

Should be removed.

While not all strings show up in the UI, having dead code makes it hard to find the strings that do show up in the UI (as was demonstrated with "Settings > Anonymity").

**Comment by Dmole** [comment]
That's progress but 

> For example 1st link 2nd file 
> "You can build trust by contributing bandwidth to the Tribler network."
> Should be removed.

and other issues linked in the OP persist.

**Comment by drew2a** [comment]
@Dmole, please post here all the places you propose to remove, and we can discuss them in detail.

**Comment by Dmole** [comment]
Looks like the string quoted in my last comment may have just been in a github cache.

Among the other files linked in the OP,
Please remove these files:

1. draft-pouwelse-trustchain-00 never handled negative trust in a tamper proof way (,the channels are cert based, not really "accounting") and is no longer relevant to Tribler:
- https://github.com/Tribler/tribler/blob/main/doc/draft-pouwelse-trustchain-00.txt
- https://github.com/Tribler/tribler/blob/main/doc/draft-pouwelse-trustchain-00.xml

2. "Start a crawler in the bandwidth accounting community" there is no longer any bandwidth accounting right?
- https://github.com/Tribler/tribler/blob/main/scripts/crawler/run_crawler.py

Among the trust search results :

1. There is no longer a "Trust Graph"
- https://github.com/Tribler/tribler/blob/main/src/tribler/gui/i18n/pt_BR.ts#L2411

2. "trustview" is no longer an endpint right?
- https://github.com/Tribler/tribler/edit/main/doc/restapi/introduction.rst

**Comment by drew2a** [comment]
> draft-pouwelse-trustchain-00 never handled negative trust in a tamper proof way (,the channels are cert based, not really "accounting") and is no longer relevant to Tribler:

As far as I understand, this document is still in use. @synctext, could you confirm?


> "Start a crawler in the bandwidth accounting community" there is no longer any bandwidth accounting right?
https://github.com/Tribler/tribler/blob/main/scripts/crawler/run_crawler.py

This crawler is left as an example of how to write a crawler for Tribler. See the description of the file for more details.

> There is no longer a "Trust Graph"
https://github.com/Tribler/tribler/blob/main/src/tribler/gui/i18n/pt_BR.ts#L2411

Confirmed. I'll remove it.

>"trustview" is no longer an endpint right?
https://github.com/Tribler/tribler/edit/main/doc/restapi/introduction.rst

Confirmed. I'll remove it.

**Comment by Dmole** [comment]
@drew2a This page needs a cleanup:

https://github.com/Tribler/tribler/wiki
