### ISSUE TITLE
Add DESTROY cell to TunnelCommunity

### ISSUE THREAD

**Issue by egbertbouman** [Tribler/tribler#783]
When a relay drops a circuit, it sends a DESTROY cell to the adjacent nodes on that circuit. Nodes receiving an DESTROY cell will:
- free resources associated with the corresponding circuit
- drop all subsequent cells for that circuit
- forward the DESTROY message to the next hop (unless it's the end of the circuit)

The payload of a DESTROY cell contains the reason why the circuit is being destroyed. Possible reasons are (subset of TOR):

NONE             - No reason given.
PROTOCOL        - Protocol violation.
INTERNAL        - Internal error.
HIBERNATING     - Not currently operating; trying to save bandwidth.
RESOURCELIMIT   - Out of memory, sockets, or circuit IDs.
CONNECTFAILED   - Unable to reach relay.
FINISHED        - The circuit has expired because it's inactive, old, or has exceeded its traffic limit.
TIMEOUT         - Circuit construction took too long

For now, we only support destroying a circuit completely.

**Comment by whirm** [comment]
Depends on #1066

**Comment by devos50** [comment]
@whirm what's the status of this issue?

**Comment by whirm** [comment]
That's tunnel community stuff, disregard it.

**Comment by devos50** [comment]
This has been implemented already: https://github.com/tribler/tribler/commit/4b098ae284d22ded664d69a439c35e4d85b7947b

Please reopen this issue if I'm incorrect 👍
