### ISSUE TITLE
v7.13.1: .tar.xz missing

### ISSUE THREAD

**Issue by mkg20001** [Tribler/tribler#7838]
**Describe the bug**
https://github.com/Tribler/tribler/releases/tag/v7.13.1 has no .tar.xz, unlike previous releases

**To Reproduce**

1. Go to https://github.com/Tribler/tribler/releases/tag/v7.13.1

**Expected behavior**
Should be there

**Comment by drew2a** [comment]
@mkg20001, thank you for creating the issue and bringing this to our attention.

The file indeed seems to be missing from the list. I can add it, but I'm wondering if it's necessary, as we already have it under a different name: https://github.com/Tribler/tribler/archive/refs/tags/v7.13.1.tar.gz

**Comment by xoriole** [comment]
The build job for creating .tar.xz is added here so the file can be added at the next release.
https://jenkins-ci.tribler.org/job/Tribler/job/Build/job/Checkout/
