### ISSUE TITLE
Tribler can't start downloading until you set downloading without anonymity

### ISSUE THREAD

**Issue by SweetBaget** [Tribler/tribler#7860]
Actually, the whole problem is stated in the title. 
If you initially set download with anonymity - it doesn't download, doesn't see peers and sids, 0kb per second. 
Set download without anonymity - downloads → switch to anonymous mode - continues downloading

**Comment by drew2a** [comment]
@SweetBaget, thank you for creating the issue. The described behavior is possible if there is not enough capacity in the exit nodes. Perhaps @egbertbouman can provide more details.

**Comment by egbertbouman** [comment]
To figure out what's happening we need some additional information from the debug panel. In particular, we need to know what's in the Tunnels/Circuits and Tunnels/Peers tabs. Screenshots would be great, but be sure to anonymize IP addresses.
