### ISSUE TITLE
GitHub Actions: Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#7881]
The following errors have started to appear:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4, syphar/restore-virtualenv@v1, cardinalby/export-env-action@v2, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20
```

Actions that need to be updated:
- [x] actions/checkout
- [x]  actions/setup-python
- [x]  syphar/restore-virtualenv
- [x]  cardinalby/export-env-action https://github.com/cardinalby/export-env-action/issues/9
- [x]   actions/upload-artifact
- [x]  dorny/paths-filter
- [x]  actions/cache
- [x]  andstor/file-existence-action
- [x]  codecov/codecov-action 

See: https://github.com/Tribler/tribler/actions/runs/7782995836

**Comment by drew2a** [comment]
`syphar/restore-virtualenv` can be replaced by https://github.com/actions/setup-python#caching-packages-dependencies

**Comment by cardinalby** [comment]
`cardinalby/export-env-action` author here. Just updated the action to node20

**Comment by drew2a** [comment]
@cardinalby, nice! Thank you very much for the update and for keeping us informed.

**Comment by drew2a** [comment]
All warnings from this issue have been fixed.
