### ISSUE TITLE
Blockchain Engineering - class of 2024 - Team Democracy-2: Cypto Core

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#7909]
Project assignment for Delft University of Technology master course called "[Blockchain Engineering](https://github.com/Tribler/tribler/issues/7691)". 

**Democracy-2**: Cypto Core
- Analyse existing running code with multi-sig, taproot, Schnorr signatures, and threshold voting
- Get existing code running with 4 laptops with Android emulators or real phones. Add new debug dashboard of connected peers with external IPv4, last-response-time, time-outs, new peers discovered, and alerts for incoming packets.
- Identify the exact location of security vulnerabilities such as lack of message signing, lack of pre-commitment, lack of leader election (or leaderless mode), and lack of [FROST-type of security guarantees](https://crysp.uwaterloo.ca/software/frost/).
- FIX and craft hardened code

- Superapp checkout, Emulator working, get BTC operational, 

@mozafar7 @M-butenaerts @QuintenVanOpstal

Sprint goal: 
- get a Regtest/testnet BTC node operational and get working with "Free Bitcoin" button inside superapp.
- fetch major code update for superapp modules and IPv8 sub-module
- understand existing code

**Comment by InvictusRMC** [comment]
Here you can find the Bitcoin node source: https://github.com/Tribler/Bitcoin-Regtest-Server

**Comment by InvictusRMC** [comment]
* Upgrade bitcoin dependency to latest version
* Understand differences between `mainnet`, `testnet`, and `regtest`

**Comment by QuintenVanOpstal** [comment]
* Upgraded my local git library, and compiled a new app
* Looked at differences between mainnet, testnet and regtest. 
* Started my own bitcoin node
* connect multiple devices to this node
* Looked at the dashboard when multiple devices were connected

**Comment by Mozafar7** [comment]
Worked on getting the regtest node working on my device and getting the getBTC button working (with the major code update).  I tried to connect to it from various emulators, but I did not manage to get that working.

**Comment by synctext** [comment]
- No coordination to collaborate and share workload
- Little coordination meetings to help others make progress
- Not on track to pass this course
- Please accelerate
-

**Comment by InvictusRMC** [comment]
Next sprint:

- Please divide work
- Proposal:
  - 2/4 members work on operational bitcoin node:
    - Upgrade to latest bitcoinj
    - Get working with superapp
    - Output: small demo showcasing it works on testnet
  - 2/4 member work on crypto analysis:
    - Read frost & musig papers
    - Analyse current implementation --> make workflow graphs
    - Compile shortcomings of current implementation: what is not safe? how can we improve this? what are bottlenecks crpyto-wise?
    - Output: summery of papers, workflows graphs of current implementation, and plan of improvements to current implementation.
    - Analyse current design

**Comment by InvictusRMC** [comment]
Please read the folllowing papers:

- [FROST](https://eprint.iacr.org/2020/852.pdf)
- [ROAST](https://dl.acm.org/doi/pdf/10.1145/3548606.3560583)
- [SPRINT](https://eprint.iacr.org/2023/427.pdf)
- [The many faces of Schnorr](https://eprint.iacr.org/2023/1019.pdf)

**Comment by JoepMulder** [comment]
- Read & summarized SPRINT
- Read & summarized "The many faces of Schnorr"
- Identified the flaw of current multi signature scheme implementation (MuSig is n-n so all participants must sign, not ideal for DAO purpose)
- Plan of improvement concerning signature schemes: Implement FROST protocol as it supports t-n (t <= n) signing, it suitable for ROAST and FROSTS's main techniques can be combined with SPRINT to improve robustness & efficiency at a later stage.
- Started with analyzing the current MuSig implementation and how we can replace this with FROST.

**Comment by InvictusRMC** [comment]
# Demo goals:
- Showcase code running on testnet!
- Please upgrade core to version 26: https://github.com/bitcoin/bitcoin

**Comment by QuintenVanOpstal** [comment]
We updated the bitcoin configuration file to run the bitcoin daemon on the testnet. We had to debug quite a lot during this process in order to get the testnet working on the server. 

We tested the communication between the android application and the server running on testnet. The communication is working, but since we don't have funds on the testnet wallet, we get an error when retrieving BTC.

Created a new page in app that shows list of connected peers with their external ipv4,last response- & request time

**Comment by InvictusRMC** [comment]
* Testnet Faucet: https://bitcoinfaucet.uo1.net/

**Comment by InvictusRMC** [comment]
### Great progress 🎉
- Continue working on election algorithm:
  - Make a flowchart for the election algorithm and start working on some text reporting on your design
- Push server code and make a PR to our [repository](https://github.com/Tribler/bitcoin-regtest-node)

**Comment by M-Butenaerts** [comment]
- Added first functionalities for leader election to currencyii.
- Updated server read.me file with other.
- Looked into communication through Blockchain and IPv8.
- Added code to send joinDao payload data via ipv8 to Peer in DAO so peer can retrieve signatures and do the joinDaoTransaction instead of the joiner (Question: How should we handle the case where no single member of the DAO is online).

- difficulties:
	- uncertainty about right commmunication channel.
	- push problems with GitHub repository.

**Comment by InvictusRMC** [comment]
### Next Sprint:
- Finish flowchart
- Finish connection with app (and TestNet)
- Implement leader election working on purely IPv8
- Make a pull request to the node repository

**Comment by M-Butenaerts** [comment]
- created diagram
	- ![image](https://github.com/Tribler/tribler/assets/58943362/169e6463-ce3a-4ef5-b135-26056a028473)
	- Each peer starts a personal election and requests alive packets to find candidates.
	- If current peer has the highest hashed public key, it is selected as leader and it broadcast an ElectedPayload.
	- Every peer sets its leader as the peer in the ElectedPayload. In case of multiple ElectedPayload, (faulty behaviour/ attacker) the peer takes the peer with the the highest hashed public key among the payloads.
- constructed communication through IPv8.	
- created following funtionalities:
	- AlivePayload, ElectionPayload, ElectedPayload, SignPayload.
	- leaderSignProposal, checkLeaderExists, electLeader.
	- onAlivePacket, onElectedPacket. 
- bitcoin core updated to 26.
- Server Readme has been expanded and pull request is ready. 
- TODO:
	- OnSignProposal
	- testing

**Comment by InvictusRMC** [comment]
### Grading session
- Finalize implementation
- Create test
- Make performance graphs 
- Write README-style reports
- Make pull request of all code

**Comment by M-Butenaerts** [comment]
- exported first .apks
- testing: 
	- tested electionPayloadRequest
	- tested onAliveResponsePacket
	- tested electionPayload
	- tested alivePayload
- initial version of readme file and graph creation setup

- difficulties: 	
	- creating tests for private functionalities, should we make them public just for testing? 
	- questioning how to handle Ipv8 tests and test related to coinCommunity.
- Continuing with:
	- testing: 
		- testing onElectionRequest
		- testing leaderSignProposal
	- report
	        - continuing expanding and creating with graphs

**Comment by InvictusRMC** [comment]
JVM Example: https://github.com/Tribler/tribler/issues/7914#issuecomment-2051230943

**Comment by JoepMulder** [comment]
Pullrequest: 
https://github.com/Tribler/trustchain-superapp/pull/197

**Comment by JoepMulder** [comment]
Link voor Johan:
https://tud365-my.sharepoint.com/:u:/g/personal/joepmulder_tudelft_nl/EWz2QdVSRaJBlT4Xb8iIvNYBakPac6jLrAZ8GR_aAxWZrQ?email=J.A.Pouwelse%40tudelft.nl&e=7Crod3

**Comment by InvictusRMC** [comment]
https://filesender.surf.nl/?s=download&token=9681d994-946a-472e-9efb-f2fa6ee9de05
