### ISSUE TITLE
Blockchain Engineering - class of 2024 - Team Democracy-3: self-evolving blockchain

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#7910]
Project assignment for Delft University of Technology master course called "[blockchain engineering](https://github.com/Tribler/tribler/issues/7691)".
**Democracy-3 self-evolving blockchain**
- On-chain kickstarter model for discovery and funding of plugins. Or scientific formulation; engineer a ledger-based system which has an internal competitive market for expansions and mutations
- Democratic decision process on which mutations are considered good. When approved by threshold voting code is deployed to all users. Bounty is a multi-sig Bitcoin payment for programmers of mutations. This is based on the running code of a shared wallet and collective money.
- Code and system upgrade using plugins, we have prior permissionless code execution. See running code of Android code which [bypasses censorship by the Google Play Store](https://github.com/Tribler/trustchain-superapp/blob/master/freedomOfComputing/README.md).

All three team members got it compiling.

Background reading: 
- [DevID: Blockchain-based Portfolios for Software Developers](https://research.tudelft.nl/files/97493852/DevID_Blockchain_Based_Portfolios_for_Software_Developers.pdf)

Upcoming sprint assignment
- fetch major code update for superapp modules and IPv8 sub-module
- understand existing code
- Make an "Hello World" .APK which can import inside Superapp
- Fix broken feature: bundling .APK with app and installing it is now broken with upgrade of Android security

**Comment by synctext** [comment]
- confusion on the assignment compile-time versus run-time _self-evolution_.
- Question: most coding will be done is Superapp? Yes :exclamation: 
-

**Comment by JopSchaap** [comment]
### What we did this weak:
* We created a test apk that runs inside the app, using the run-time APK installing
* Made/divided tickets on minor improvements on our repo
* Fixed the run-time APK installing bug. The run-time apk installing now runs on Android 14+
* Set up github repo 
* Adds feature that allows renaming of APK

### Problems we encountered:
* We encountered the problem where APKs do not torrent
  * We suspect this is an issue with the p2p network
  * We saw sometimes no peers showing up in the debug screen
 * Build release apk CI job fails continuously on our github.
   * Is this because of us, or can this just not be fixed.
 * Is there an equivalent to `pretier` in Kotlin? (To format the kotlin files without having to run the gradle thing everytime)

**Comment by synctext** [comment]
- Possibly a port connectivity issue or not? Test with https://canyouseeme.org/ type of tools
- Flaky connectivity ?

**Comment by grimadas** [comment]
Linter for kotlin: https://github.com/pinterest/ktlint

**Comment by JopSchaap** [comment]
### What we did this weak:
* We added a vote button
  * Right now a user is just able to vote once, and cannot cancel their vote
* We added a down-vote button 
* We added the ability of the app to store votes by user id
  * We want to make this signed with the user id so peers can share other peers votes
* We restructured the layout of stored app in the file directory, to store apks in a directory which are named by their hash.
  * This is not yet merged since it doesn't work yet for torrented apks.
* We got wirshark going
* We figured out what to do to make the connectivity issue go away
  * We figured out you should have the app installed in two (physically) different devices. (e.g. two emulators on one machine doesn't work)
    * We are however not sure why this is required
*  We got the debug screen (from the other group) up and running

### Problems we encountered:
* Something we changed caused the delete button to not update the gui anymore. see: [issue](https://github.com/JopSchaap/trustchain-superapp/issues/28)

**Comment by pbhaskaran** [comment]
![Screenshot 2024-03-12 125029](https://github.com/Tribler/tribler/assets/72701519/09d8546b-acf0-40ae-8ad2-c09ec8f36413)

**Comment by grimadas** [comment]
- The votes are persistent 
- 

For the next week: 
- What is member id? When it is created? 
- Display votes on the screen. Now the buttons are not dynamic, find easiest fix for that. 
- Restructure vote object: it should have item_id, public key (or member id), signature, freshness, vote strength (-1 down, 0 neutral, 1 up)  

- Store what you received from the network, you can always garbage collect later. 

- The simplest way to implement the gossip algorithm: send 
- Start with simple gossip algorithm: push-based with ttl (time to live) inside the vote object. Ttl is an integer

**Comment by JopSchaap** [comment]
### What we did this week
* We restructured the vote objects, to include signatures/ public keys
* Signatures are verified with the associated public keys
* Vote objects now also come in a neutral variant
* We implemented a simple hot potato gossip working, that distributes votes to other peers
* The number of votes are now shown next to the vote up/down button
* A very basic pull based gossip, where newly introduced peers ask for votes they are yet unaware of


### Things we ran into this week
* We were unsure how to ensure a peer doesn't generate two keys and uses both to vote twice

**Comment by grimadas** [comment]
Next week: 
- Fix pull based gossip. For example, you can delay it until we are connected. Other option you can used "extra_bits" for introduction_request/response.

**Comment by InvictusRMC** [comment]
> * Now the votes are collected with a queue that is polled every second. What is the easiest way to implement it asynchronously? Implement a singleton? Any ideas @InvictusRMC?
Right now there is indeed a very inefficient implementation. What I would suggest is making use of a [listener](https://github.com/Tribler/kotlin-ipv8/blob/476dc36d0a5208d4a6ef21d953e00e4a440046a4/ipv8/src/main/java/nl/tudelft/ipv8/attestation/trustchain/TrustChainCommunity.kt#L65). That way we can check whether conditions are met whenever receiving a new block, as opposed to checking periodically.

**Comment by AirWinter** [comment]
- Removed all the queues which increased the latency for push & pull-based gossiping
- Improved latency of push based from 5-10 seconds down to 0.1 seconds
- Improved latency of pull based from 10 seconds to 0.2 seconds
- Benchmarked the results and made improvements to reduce message size
- Found that Pull Based gossiping couldn't scale as the message would eventually get too big, so switched to using the EVA protocol and tested that it scales (tested up to 50 votes)
- Fixed a bug that occurred when voting on an APK that was gossiped to us
![Pullbased](https://github.com/Tribler/tribler/assets/72806037/5c510190-92ee-4dd4-96b8-04789fddd210)
This graph shows that the original implementation only scaled to 3 votes, then after reducing the message size it scaled to 4 votes but the latest version that uses the EVA protocol can scale way further. The latency was also improved as previously mentioned, and also removed the operational overhead of repeatedly checking the queue.
![PushBased](https://github.com/Tribler/tribler/assets/72806037/aa81cd3a-d91c-4a7a-a0d8-d966f900c291)
The graph shows how we reduced the message size, but we also reduced the latency and removed the operational overhead of repeatedly checking the queue.

**Comment by grimadas** [comment]
**Solid progress** 

*For the next week*: 

- Keep good documentation to help with onboarding for the next teams 
- Exporting to the main screen
  - Priority: to main screen, first manually  
  - Then switch to manual import to the main screen 
- Gossip improvement: Use short ids when first sending pull-request gossip. The initiator should be the node joining. 
- Improve benchmarking figures to make them more interesting: time to convergence and throughput as metrics. 
- Side-quest: Learn more about set reconciliation to improve your gossip even more: 
https://github.com/AljoschaMeyer/set-reconciliation
https://ics.uci.edu/~eppstein/pubs/EppGooUye-SIGCOMM-11.pdf

**Comment by pbhaskaran** [comment]
![g1](https://github.com/Tribler/tribler/assets/72701519/f62ab7d0-e3e7-42bd-b474-5574652b6c8f)
![g2](https://github.com/Tribler/tribler/assets/72701519/a6ccdfcd-e1c8-412b-b249-e4beaf2bcbea)
![g3](https://github.com/Tribler/tribler/assets/72701519/643e0f1b-5792-44c1-ae30-b9dc498ab013)
![g4](https://github.com/Tribler/tribler/assets/72701519/9a8c2aab-51b3-4e68-8347-1e8c2dca719a)

**Comment by JopSchaap** [comment]
# What we did this week
* We ran tests on the base implementation of pull based vote gossiping see: [https://github.com/Tribler/tribler/issues/7910#issuecomment-2030502261](comment above)
* fixed bugs
* Write kdoc documentation for classes and methods
* Improve FOC README
* Fix issues with "installing" apps
* add vote threshold installing
* Sync branch with main branch over at tribler

# Things we ran into this week
* We were unsure what an appropriate vote treshold would be(right now it is set to 10)
* Should apps also be automatically uninstalled, if # votes drop below treshold?
*

**Comment by AirWinter** [comment]
![PushBasedNoOrigin](https://github.com/Tribler/tribler/assets/72806037/a62be960-f3e1-4668-a413-2e33c1fc2036)
Improved graph for push-based gossip

**Comment by synctext** [comment]
- focus on gossip (mostly ignoring the 4G/5G network connectivity issue)
- 500 votes testing
- pull gossip: advertise all votes you have already (ID for a vote; UUID, why not SHA256 (32 bytes) spoofing :bomb: ?)

**Comment by JopSchaap** [comment]
# What we did this week:
* Quite week: since Exams
* We have demo prepared apk prepared at: https://github.com/JopSchaap/trustchain-superapp/releases/tag/demo-release
  * If nothing shows up your preference store might be corrupt because of an old version of the FOCInstaller. To fix you should clear the local storage of the app, see release on how to do that
* We updated the info screen to include Threshold for install value and total number of votes stored

**Comment by grimadas** [comment]
For next week: 

- Investigate the bug showing different number of torrents 
- Add more apks (10 and more) either into the default app, or prepare a bunch of link with some dummy apks (some sound, image, search) 
- During the demo: show upload of apk and gossip of apk. 
- Another demo: popular apk auto-install (threshold of three votes)
- Prepare a compilation README file with your decisions, and limitations of your protocols (what works and what is future work)
- Hand in Apk and GitHub repo wit the code. 
- @synctext what is the expected deadline to submit the upstream PR? 
- Unit tests and good coverage 
- Corner cases - broken apk gossip, big transfer. Have tests to show the coverage for corner cases.

**Comment by AirWinter** [comment]
# Final Ticket Update

This is just a brief overview of our project, check out the [README](https://github.com/JopSchaap/trustchain-superapp/blob/master/freedomOfComputing/src/main/java/nl/tudelft/trustchain/foc/README.md) for more insights.

## Project Features

1. Fixed issue that prevented APKs from being opened on new versions of Android (14+)
2. Built a [voting system](https://github.com/JopSchaap/trustchain-superapp/blob/master/freedomOfComputing/src/main/java/nl/tudelft/trustchain/foc/README.md#voting-system) for FOC app 
   - Pull-based gossiping 
         - Triggered when opening the `FreedomOfComputing` app
         - Sends request to all your direct neighbours
         - Only respond with votes that you don't already have
         - Benchmarked the performance in terms of latency & message size
   - Push-based gossiping 
          - Triggered when placing a vote, tries to inform others about that specific vote
          - Inform log(n) of your neighbours about this vote, where n is number of direct neighbours
          - Hot potato gossip with TTL set to 2, so neighbours relay it unless TTL is 0
          - Benchmarked the performance in terms of latency & message size
   - Persisting state by writing to `.dat` file
   - Signatures to verify votes
3. Installation of APK to homescreen 
   - APK automatically installed to homescreen once it passes a certain threshold (set to 100)
   - Manual installing APK to homescreen when they haven't passed the threshold

## Documentation

The  [README](https://github.com/JopSchaap/trustchain-superapp/blob/master/freedomOfComputing/src/main/java/nl/tudelft/trustchain/foc/README.md) contains most of our documentation, as it provides a developer onboarding guide explaining the main methods of the `FreedomOfComputing` App. It also contains a section which goes more in depth into the features that we implemented in this project, the key decisions we made and highlights some of the current limitations as well as potential future improvements. We also made sure to include detailed KDocs for all new and most existing methods. These comments cover parameters, return statements, and provide an overview of each method's functionality.

## Testing and Coverage

The new classes with heavy logic that required testing were `FOCVoteTracker` and `FOCSignedVote`
class. For the `FOCVoteTracker` class, we reached 100% method coverage with 90% of lines covered
(The missing lines are just mainly console log statements used for debugging) and on
the `FOCSignedVote` class, we reached 100% method coverage and 100% line coverage.

## Live Demo

For the live demo download this [APK](https://drive.google.com/file/d/1ozkhYjA0DzxeK21vKyZyWuCkJJ_8hOkp/view?usp=sharing) and follow these steps:

Steps:
1. Install the APK
2. Check that you're connected via the debug screen
4. Open FreedomOfComputing
5. This should do a pull request and should fetch all the votes you're behind
6. Place votes on APK which should push to others, also have others place votes which should push to you
7. Have one APK go over the net threshold of 100, this should automatically install it to the superapp home screen
8. Long click on an APK that doesn't have enough votes for the threshold and install it to the home screen manually
9. Have a working APK gossiped automatically
10. Have a broken APK gossiped automatically


Recordings in case live demo doesn't work:
[Demo Voting](https://jam.dev/c/1906fa28-ba36-453d-b10c-42c228acdbcb)
[Demo Downloading APK](https://jam.dev/c/21f60edc-a56f-4400-9254-876ac05fc2c4)
[Demo Torrenting APK](https://jam.dev/c/c58eeddf-e17f-4f3b-bea3-e9ff328c7a02)

**Comment by synctext** [comment]
- clearly a demo designed to impress :tada: :rocket: :tada: 
- 15k votes received in EVA :astonished:
