### ISSUE TITLE
Please add docker version

### ISSUE THREAD

**Issue by febriansasi** [Tribler/tribler#7937]
It would be nice running tribler on headless server and open it on browser like transmission. 
Make it simple using docker container.

**Comment by xoriole** [comment]
@febriansasi We do not have a webui yet.
However, you can run the Tribler core using docker.
https://github.com/Tribler/tribler?tab=readme-ov-file#docker-support

**Comment by heldersepu** [comment]
In theory tribler does have a webui, the swagger-ui
https://github.com/Tribler/tribler/blob/main/doc/restapi/introduction.rst#making-requests

**Comment by qstokkink** [comment]
A small update: we now have a web-based GUI. After PR #8108 is merged, we will be able to use GitHub Actions to generate Docker images.

If everything works out, we should also be able to automatically push to Docker Hub in the future using the GitHub Action. This should either be for the 8.0 release or shortly after.

**Comment by qstokkink** [comment]
So I don't forget, a tip from our Docker master @xoriole: Docker images can be [published to GitHub Packages as well (next to Docker Hub)](https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub-and-github-packages).

**Comment by qstokkink** [comment]
We now have a Docker builder for the latest Tribler version up-and-running: https://github.com/Tribler/tribler/pkgs/container/tribler

I believe this issue is now solved as there is already an issue open for the Docker hub publishing at #6591
