### ISSUE TITLE
Use libtorrent to create torrents

### ISSUE THREAD

**Issue by egbertbouman** [Tribler/tribler#80]
We should use libtorrent to create torrents.

**Comment by NielsZeilemaker** [comment]
@LipuFei you implemented this right?

**Comment by LipuFei** [comment]
@NielsZeilemaker Yes, I did. We are sure that there are duplicate infohashes coming from the channel community.

**Comment by NielsZeilemaker** [comment]
This pull request is about using libtorrent to create .torrents instead of our own finalize stuff we had. I'll close it.
