### ISSUE TITLE
Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format

### ISSUE THREAD

**Issue by gslicer** [Tribler/tribler#8023]
**Describe the bug**
```
(tribler:36998): Gtk-WARNING **: 13:53:14.651: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): 
Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format 
(gdk-pixbuf-error-quark, 3)
fish: Job 1, './tribler' terminated by signal SIGABRT (Abort)
```

**To Reproduce**

1. Go to 'create torrent'
2. Click on 'add file'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [Fedora 40 (extracted deb package)]
- Tribler's version [e.g. 7.14.0]

**Additional context**

**Comment by drew2a** [comment]
@gslicer thank you for the report.

We do not officially support Fedora for Tribler. However, you can attempt to fix this issue by following the steps below, but please note that we cannot take responsibility for any consequences:

1. **Install necessary packages**: Ensure all required dependencies, such as pixbuf loaders and the MIME database, are installed. You can install these packages with:
   ```bash
   sudo dnf install gdk-pixbuf2 shared-mime-info
   ```

2. **Reinstall GTK**: There might be an issue with the GTK installation. Reinstall GTK with:
   ```bash
   sudo dnf reinstall gtk3
   ```

3. **Ensure the icon theme is installed**: Make sure an appropriate icon theme is installed. You can install the standard icon theme with:
   ```bash
   sudo dnf install adwaita-icon-theme
   ```
