### ISSUE TITLE
`FeedbackDialog` triggers multiple times upon en exception in RESTComponent

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#8055]
**Describe the bug**
There is something wrong with the implemented
- #7699

**To Reproduce**

1. Go to RESTComponent and write `        raise ValueError` on line 113:
```python
        rest_manager = RESTManager(config=config.api, root_endpoint=self.root_endpoint, state_dir=config.state_dir)
        raise ValueError
        await rest_manager.start()
```
2. Run Tribler
3. Wait

**Expected behavior**
It should fire FeedbackDialog once.

**Screenshots**

![feedback](https://github.com/Tribler/tribler/assets/13798583/2f61f72e-62ac-4f39-aa1b-1912a9cfb32b)

**Desktop (please complete the following information):**

- OS: macOS
- Tribler's version: https://github.com/Tribler/tribler/commit/035bab82fdf863bff8d1ea81c30dbdc4aeabb3d1

**Comment by xoriole** [comment]
As QT based UI is removed from the main codebase, this issue has become obsolete. Therefore, I'm unassigning myself.

**Comment by qstokkink** [comment]
I'm not sure if a similar issue persists in the new GUI. This still needs to be checked.

**Comment by qstokkink** [comment]
Just checked: this issue indeed no longer seems relevant (or, at least, no longer reproducible) with the new GUI implementation.
