### ISSUE TITLE
Add family filter to completions

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#8056]
This issue was created based on the comment from:

https://github.com/Tribler/tribler/blob/035bab82fdf863bff8d1ea81c30dbdc4aeabb3d1/src/tribler/core/components/database/restapi/database_endpoint.py#L319-L327

@qstokkink cited from #1722:
> Our XXX filtering is now only half-working.

**Comment by qstokkink** [comment]
The family filter has now been removed and this issue is no longer relevant..
