### ISSUE TITLE
Can not install tribler through AUR

### ISSUE THREAD

**Issue by hesshshhs** [Tribler/tribler#8058]
**Describe the bug**
Cannot in stall the package

**To Reproduce**
```
Typed in ❯ yay -S tribler
 
Returned :
Sync Explicit (1): tribler-7.14.0-1
resolving dependencies...
warning: cannot resolve "python-libnacl", a dependency of "tribler"
:: The following package cannot be upgraded due to unresolvable dependencies:
      tribler

:: Do you want to skip the above package for this upgrade? [y/N] 
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'python-libnacl' required by tribler
 -> error installing repo packages
```

**Expected behavior**
it should be installed

*
**Desktop (please complete the following information):**

- OS: Cachy OS (based on arch)
- Tribler's version 7.14

**Additional context**

**Comment by drew2a** [comment]
@hesshshhs Hi, thank you for the error report. Unfortunately, we are not supporting Arch Linux at the moment.

Related:
- #6740
- #6739

**Comment by f1vefour** [comment]
Simply install python-libnacl from AUR then install tribler.
