### ISSUE TITLE
Downloading Torrent files through Tribler GUI crashes the application on Linux (Ubuntu 24.04 LTS)

### ISSUE THREAD

**Issue by DavidGordiienko** [Tribler/tribler#8061]
**Describe the bug**
When I try to download Torrent files through the Tribler GUI on Ubuntu 24.04 LTS, the program crashes. Right clicking on the file and clicking "Open with Tribler" seems to work some of the time, with some files opening Tribler and beginning the download process, and others seemingly never opening Tribler.

**To Reproduce**
1. Go to "Add Torrent" button
2. Click on "Import torrent from file"
3. Program crashes

**Expected behavior**
The program allows me to select the file from my computer and allows me to adjust my download settings before finally adding it to the list of currently downloading torrents and beginning to download it.

**Desktop (please complete the following information):**

- OS: Ubuntu 24.04 LTS
- Tribler's version: 7.14.0 (Stable)

**Comment by xoriole** [comment]
I'm able to reproduce the issue on Ubuntu 24.04. This seems similar to this issue: https://github.com/Tribler/tribler/issues/7457
![tribler-on-ubuntu-24-04-torrent-import](https://github.com/Tribler/tribler/assets/1442867/09417f18-0dbb-449a-8bd5-2664d31bbda0)

**Comment by DavidGordiienko** [comment]
The file you have linked works, the app no longer crashes when I try to import files using the GUI.

**Comment by xoriole** [comment]
I have updated GitHub release with the new Debian package of 7.14.0 version so Tribler website should also be using the latest package now. I'll close this issue.
