### ISSUE TITLE
Enabling statistics causes peers to drop to 0

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#8146]
Run 1:

![screenshot 1](https://github.com/user-attachments/assets/8a3774dc-730b-4ec0-86b9-326ab6a89dc8)

Run 2:

![screenshot 2](https://github.com/user-attachments/assets/5925c2c5-e5a6-48ed-8dc5-2da2f711d116)

My peer counts go up after starting Tribler and then quickly go down to near zero.

**Comment by egbertbouman** [comment]
Strange, counts on my machine seem fine (Win10 + Python 3.9).

**Comment by qstokkink** [comment]
Seemingly, setting `"statistics"` to `false` in the configuration solves this. This might be a coincidence, I'll run a few more tests.

**Comment by qstokkink** [comment]
😮 this might actually be an IPv8 bug.

If I remove `StatisticsEndpoint.__getattribute__` and implement all the `Endpoint` methods like a normal subclass, everything works.

**Comment by qstokkink** [comment]
I thought the `"interface": "UDPIPv6"` could maybe play a part in this. I removed that but this still happens.

**Comment by qstokkink** [comment]
Ok, this took a turn for the weird.

I added a print statement to `UDPEndpoint.datagram_received`. Then I ran Tribler with and without statistics enabled.

When enabling statistics. `datagram_received` gets called a few hundred times and then never gets called again. The result is that a few peers come in and then get dropped (correctly) as we never receive another message.

Without enabling statistics, `datagram_received` never gets called but I get a lot of peers.

**Comment by qstokkink** [comment]
Just tested on Ubuntu 22.04 and this does not happen there. Only on Windows apparently.

Regarding "`datagram_received` never gets called but I get a lot of peers": this is because I installed the rust extension. That should be fine.

**Comment by qstokkink** [comment]
This might be https://bugs.python.org/issue44743

> The bug manifests with all combinations: SelectorEventLoop and ProactorEventLoop, python 3.9 and 3.10, on Windows 10.

**Comment by qstokkink** [comment]
I just brought my _consistently failing_ laptop from the office to my home and now it _consistently works_ without any issues. Same machine and the same code.

**Comment by qstokkink** [comment]
I added a callback to the `UDPEndpoint` class. 

```python
    def error_received(self, exc):
        print("!!! ERROR RECEIVED !!!", exc)
```

Over a run, this outputted three times:

```
!!! ERROR RECEIVED !!! [WinError 1214] The format of the specified network name is invalid
!!! ERROR RECEIVED !!! [WinError 1234] No service is operating at the destination network endpoint on the remote system
!!! ERROR RECEIVED !!! [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
```

After the third message, peers started dropping.

**Comment by qstokkink** [comment]
Wait, hold on, I just discovered that my `DatagramTransport` is a `_ProactorDatagramTransport`. This may be a case of not setting the selector event loop correctly.

**Comment by qstokkink** [comment]
Confirmed:

```python
asyncio.set_event_loop(asyncio.SelectorEventLoop())
asyncio.run(main())
```

Gives me a `<ProactorEventLoop running=True closed=False debug=False>`.


```python
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
asyncio.run(main())
```

Gives me a `<_WindowsSelectorEventLoop running=True closed=False debug=False>`.
