### ISSUE TITLE
Download stops if i select at least "1 proxy"

### ISSUE THREAD

**Issue by AngryRoleplayer** [Tribler/tribler#8168]
If i select no anonymity it slowly crawls, if i select 1 proxy it stops. Has been like this for over 2 days. And last week as well. Then it suddenly started downloading again. Then stopped again. Are there any proxy issues??

**Comment by qstokkink** [comment]
From what I can see, our network is in good health. On my personal machine, anonymous downloading works and has been working for the past weeks.

I think that leaves two options (both can apply): (1) is the torrent you are downloading not well-seeded or (2) are you well-connected to our overlay network? If you want to know which one(s) of the cases apply, I'll need more information from you.

To debug (1), please take a look at the "Peers" tab of your download details and check if you see any peers that want to upload.

For debug (2), please first enable developer statistics in your settings. Second, go to your debug window and browse to the tabs "IPv8" / "overlays" and check if the number of "peers" are in the 20~30's.

**Comment by AngryRoleplayer** [comment]
> From what I can see, our network is in good health. On my personal machine, anonymous downloading works and has been working for the past weeks.
> 
> I think that leaves two options (both can apply): (1) is the torrent you are downloading not well-seeded or (2) are you well-connected to our overlay network? If you want to know which one(s) of the cases apply, I'll need more information from you.
> 
> To debug (1), please take a look at the "Peers" tab of your download details and check if you see any peers that want to upload.
> 
> For debug (2), please first enable developer statistics in your settings. Second, go to your debug window and browse to the tabs "IPv8" / "overlays" and check if the number of "peers" are in the 20~30's.

Thanx for reply!
There are indeed both seeds and peers available. 
It's pretty weird i started Tribler and it started downloading with 1 proxy... downloaded for about 5 minites then stopped completely again. 

For the second debug part: i will attach the picture

**Comment by AngryRoleplayer** [comment]
OK i've made more tests and if i select 2 hops it does not download, very slowly. If i select 1 hop it stops and cannot connect to any peers

**Comment by qstokkink** [comment]
That is very strange. From our downloading protocol's perspective, there should be no difference between one or two hops. In both cases (and even if the circuit was 30 hops), the download is visible to the world from an "exit" proxy node (we have some [more info on our website](https://www.tribler.org/anonymity.html)).

Given your evidence and the way Tribler works, I think you were unlucky with the peer selections in your BitTorrent swarm(s). If I am correct, you could try to pause and unpause a download to force new (and hopefully better) connections for your download.

**Comment by qstokkink** [comment]
As this seems to be a case of bad luck and we cannot fix the Internet or the BitTorrent ecosystem, only our software, there is nothing more we can do for this issue and I'll close it.
