### ISSUE TITLE
Store seeders/leechers for future ranking

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#8183]
In a future release, we will attempt to provide better search results in Tribler. To lay the ground work for this, we already store preference ralations in the database in pre-release `8.0.0`. However, it has already been identified that storing the seeders and leechers that belong to these preference relationships, at the time they were established, will provide better results. With this insight, we should start storing this data before we release the first non-pre-release `8.0.x` version.

**Comment by qstokkink** [comment]
I spent a few days trying to modify the old design to support this. The result is highly complex (and probably fragile) code.

It will be easier (i.e., less code, less time) to just clean-slate this whole thing and start from scratch. So, I'll do just that.

**Comment by qstokkink** [comment]
In the new design, we should probably be a bit more flexible to network changes. I'll follow @egbertbouman's advice and use JSON. This does come at the cost of some overhead in the network packets. We can't fit more than 14 infohashes into a single UDP packet, so we'll need some form of fragmentation protocol.

In the new design, I'll use three different packets: `CrawlInfo` and `Crawl` to crawl peers and `CrawlResponse` for peers to respond. The `CrawlInfo` is fixed-format for forward compatibility, but the other two have free-form JSON data. In the free form version 0, a `Crawl` can have `"query_fragment"` request or a `"query_info"` request. The free-form  `CrawlResponse` version 0 can contain "query_fragment", "query_info", or "table_size".

```python
@vp_compile
class CrawlResponse(VariablePayloadWID):
    msg_id = 1
    format_list = ["varlenH"]
    names = ["data"]

    data: bytes  # Completely free-form

# Response to Crawl({
#     "version": 0,
#     "type": "query_fragment",
#     "query_id": 2147483647,
#     "from": 200,
#     "to": -1
# })
num_torrents = 14  # MAX for one UDP packet
packet1 = overlay.ezr_pack(CrawlResponse.msg_id, CrawlResponse(json.dumps({
    "version": 0,
    "type": "query_fragment",
    "query_id": 2147483647,
    "from": 200,
    "to": 200 + num_torrents,
    "infohashes": ["ab" * 20] * num_torrents,
    "seeders": [2147483647] * num_torrents,
    "leechers": [2147483647] * num_torrents,
}, separators=(',', ':')).encode()))

# Response to Crawl({
#     "version": 0,
#     "type": "query_info",
#     "query_id": 2147483647
# })
packet2 = overlay.ezr_pack(CrawlResponse.msg_id, CrawlResponse(json.dumps({
    "version": 0,
    "type": "query_info",
    "query_id": 2147483647,
    "results": 300,
    "chosen_index": 255,
    "query": "x" * 768,  # MAX 768 character queries
}, separators=(',', ':')).encode()))

# Response to CrawlInfo() request (note: no arguments for forward compatibility)
packet3 = overlay.ezr_pack(CrawlResponse.msg_id, CrawlResponse(json.dumps({
    "version": 0,
    "type": "table_size",
    "total_queries": 2147483647
}, separators=(',', ':')).encode()))
```

Just to give any database people a heart attack, we can use the following free-form database format:

```sql
CREATE TABLE "QUERY"(
  "rowid": INTEGER,
  "version": INTEGER,
  "query": TEXT,
  "results": TEXT
)
```

The results would just be in json format per query.

**Comment by egbertbouman** [comment]
Looks good to me. One thing you could consider is putting the `type` in the database table as well (outside of the JSON blob, without the `_fragment` part). That would avoid having to parse the JSON in the database table in case of future extensions (i.e., `type` would be used for filtering purposes). But perhaps you already intend to use `query` for this.
I'd also consider adding a `raw` datatype of the end of the packets where possible. That would give you the option to add additional fields in the future without breaking compatibility.
