### ISSUE TITLE
Tribler 8.0.0.0 Ubuntu startup Crash 

### ISSUE THREAD

**Issue by nitmeare** [Tribler/tribler#8194]
Installed Tribler 8.0.0.0 on (X)Ubuntu 24.04, it crashes when starting.

```
pirat@Piratenpartei:/var/crash$ tribler
Starting Tribler...
/usr/share/tribler /var/crash
Abgebrochen (Speicherabzug geschrieben)
```
6.8.0-45-generic #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Crash Dump provided as Attachment:
[dump.zip](https://github.com/user-attachments/files/17260832/dump.zip)

**Comment by nitmeare** [comment]
> I could also observe a crush on the 8.0 release after upgrading from the most recent version 7 release on Windows. Might be related?

I made a clean new install on my Tor Relay and I2P Relay Vserver. No pervious Tribler Installation was there.

Tribler 8.0.0.0 is running on Linux Mint though, where i upgraded from the 7.x version. (Linux LINUX 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux)

**Comment by qstokkink** [comment]
@nitmeare Thanks for the report. I can install the `.deb` without issues on my `6.8.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Sep 11 15:25:05 UTC 2 x86_64 x86_64 x86_64 GNU/Linux` machine and on another Ubuntu 24.04 machine. I'm thinking that either (1) we missed some vital dependency in our `.deb` file that just happens to be on my Ubuntus and your Mint or (2) your Ubuntu has some interfering library installed. I'll try spinning up a brand new Ubuntu 24.04 to see if I can reproduce this and - if it doesn't crash - slowly work my way through your 375 dependencies to see which one conflicts. This will take a little while.

@Koen1999 For some reason, your private key material got corrupted. Tribler uses two keys. In your `%APPDATA%/.Tribler` folder there should be a `ec_multichain.pem` and a `secondary_key.pem` file. If you move (or even remove) these two keys, Tribler should regenerate them and work. If that does not resolve your issue, there is something even worse going on.

**Comment by nitmeare** [comment]
> @nitmeare Thanks for the report. I can install the `.deb` without issues on my `6.8.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Sep 11 15:25:05 UTC 2 x86_64 x86_64 x86_64 GNU/Linux` machine and on another Ubuntu 24.04 machine. I'm thinking that either (1) we missed some vital dependency in our `.deb` file that just happens to be on my Ubuntus and your Mint or (2) your Ubuntu has some interfering library installed. I'll try spinning up a brand new Ubuntu 24.04 to see if I can reproduce this and - if it doesn't crash - slowly work my way through your 375 dependencies to see which one conflicts. This will take a little while.
> 
> @Koen1999 For some reason, your private key material got corrupted. Tribler uses two keys. In your `%APPDATA%/.Tribler` folder there should be a `ec_multichain.pem` and a `secondary_key.pem` file. If you move (or even remove) these two keys, Tribler should regenerate them and work. If that does not resolve your issue, there is something even worse going on.

Hm, thanks. Had it installed on a Xubuntu Server... Maybe there are some depencies that are different from standard Ubuntu but the .deb should usually list uninstalled depencies during install i think...

**Comment by synctext** [comment]
> we missed some vital dependency in our .deb file that just happens to be on my Ubuntus and your Mint

We seen this a lot the past 19 years. Please think of the most user friendly checker. For instance, a try...catch with hard popup: missing M2crypto package dependency.

**Comment by qstokkink** [comment]
@nitmeare There may be an easier way to debug your issue. While running the `.deb` file, all process output is piped to file in `/tmp/<your username>-tribler-<8 random character>.log`:

https://github.com/Tribler/tribler/blob/2c4b354a20c5fc29b21c8b59a4bb1e142c65842e/build/debian/tribler/usr/bin/tribler#L7

![Screenshot](https://github.com/user-attachments/assets/752b31cb-ae64-4ec0-b1e8-e15b2dcb0977)

Could you share what is in your log file? For me, it looks something like this:

```
INFO:__main__:Run Tribler: {'torrent': '', 'log_level': 'INFO', 'server': False}
INFO:__main__:Root state dir: /home/quinten/.Tribler
INFO:tribler.tribler_config:Load: /home/quinten/.Tribler/git/configuration.json.
INFO:__main__:Creating session. API port: 0. API key: 5bad44e131d42533c496f4c08fa2c0bc.
INFO:RESTManager:Starting RESTManager...
INFO:RESTManager:Set security scheme and apply to all endpoints
INFO:RESTManager:Remove head
 ... and many more lines
```

@synctext Sure, we can make an issue for that.

**Comment by qstokkink** [comment]
Small update: I installed Xubuntu 24.04.1 LTS and the `tribler_8.0.0_ambd64.deb` works out-of-the-box.

That said, `dpkg` does complain:

```
dpkg: dependency problems prevent configuration of tribler:
 tribler depends on gir1.2-gtk-4.0; however:
  Package gir1.2-gtk-4.0 is not installed.
 tribler depends on libgirepository1.0-dev; however:
  Package libgirepository1.0-dev is not installed.

dpkg: error processing package tribler (--install):
 dependency problems - leaving unconfigured
```

I resolved those errors with:

```
sudo apt-get install --fix-broken
```

After that, Tribler still works for me.

So, good news: Tribler can work on Xubuntu. Bad news: @nitmeare there is something specific to your system that is causing a crash.

**Comment by qstokkink** [comment]
We just created a new pre-release, `8.0.1`, that might shed some new light on this issue. It will (probably) not solve your issue but `/tmp/<your username>-tribler-<8 random characters>.log` should have some additional information.

**Comment by nitmeare** [comment]
> We just created a new pre-release, `8.0.1`, that might shed some new light on this issue. It will (probably) not solve your issue but `/tmp/<your username>-tribler-<8 random characters>.log` should have some additional information.

Hi, here is my Log output:

```
INFO:__main__:Run Tribler: {'torrent': '', 'log_level': 'INFO', 'server': False}
INFO:__main__:Root state dir: /home/kehmax/.Tribler
INFO:tribler.tribler_config:Load: /home/kehmax/.Tribler/8.0/configuration.json.
INFO:__main__:Creating session. API port: 0. API key: 5215cb13feb3b452ced5f9dc6d1dd079.
INFO:RESTManager:Starting RESTManager...
INFO:RESTManager:Set security scheme and apply to all endpoints
INFO:RESTManager:Remove head
/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/apispec/ext/marshmallow/openapi.py:135: UserWarning: Multiple schemas resolved to the name AddTrackerRequest. The name has been modified. Either manually add each of the schemas with a different name or provide a custom schema_name_resolver.
/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/apispec/ext/marshmallow/openapi.py:135: UserWarning: Multiple schemas resolved to the name AddTrackerResponse. The name has been modified. Either manually add each of the schemas with a different name or provide a custom schema_name_resolver.
/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/apispec/ext/marshmallow/openapi.py:135: UserWarning: Multiple schemas resolved to the name File. The name has been modified. Either manually add each of the schemas with a different name or provide a custom schema_name_resolver.
/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/apispec/ext/marshmallow/openapi.py:135: UserWarning: Multiple schemas resolved to the name GetMetainfoResponse. The name has been modified. Either manually add each of the schemas with a different name or provide a custom schema_name_resolver.
INFO:RESTManager:Http enabled
INFO:RESTManager:Starting HTTP REST API server on port 0...
INFO:RESTManager:HTTP REST API server started on port 39195
INFO:RESTManager:Swagger docs: http://127.0.0.1:39195/docs
INFO:RESTManager:Swagger JSON: http://127.0.0.1:39195/docs/swagger.json
INFO:Socks5Server:Started SOCKS5 server on port 42855
INFO:Socks5Server:Started SOCKS5 server on port 35193
INFO:Socks5Server:Started SOCKS5 server on port 34205
INFO:Socks5Server:Started SOCKS5 server on port 37327
INFO:Socks5Server:Started SOCKS5 server on port 45691
INFO:tribler.core.libtorrent.download_manager.download_manager:Creating a session
INFO:tribler.core.libtorrent.download_manager.download_manager:Hops: 0.
INFO:tribler.core.libtorrent.download_manager.download_manager:Libtorrent port: 0
INFO:tribler.core.libtorrent.download_manager.download_manager:could not load libtorrent state, got exception: FileNotFoundError(2, 'Datei oder Verzeichnis nicht gefunden'). starting from scratch
INFO:tribler.core.libtorrent.download_manager.download_manager:Started libtorrent session for 0 hops on port 45027
INFO:IPv8CommunityLoader:Loading overlay <class 'abc.DatabaseComponent'>
INFO:IPv8CommunityLoader:Loading overlay <class 'ipv8.dht.discovery.DHTDiscoveryCommunity'>
INFO:DHTDiscoveryCommunity:DHT community initialized (peer mid b'90d2ea3f78bcb360c4d035ed5cfd553ba162c876')
INFO:IPv8CommunityLoader:Loading overlay <class 'tribler.core.knowledge.community.KnowledgeCommunity'>
INFO:KnowledgeCommunity:Knowledge community initialized
INFO:IPv8CommunityLoader:Loading overlay <class 'tribler.core.recommender.community.RecommenderCommunity'>
INFO:IPv8CommunityLoader:Loading overlay <class 'tribler.core.rendezvous.community.RendezvousCommunity'>
INFO:TrackerManager:No tracker blacklist file found at /home/kehmax/.Tribler/8.0/tracker_blacklist.txt.
INFO:IPv8CommunityLoader:Loading overlay <class 'abc.TorrentCheckerComponent'>
INFO:IPv8CommunityLoader:Loading overlay <class 'tribler.core.tunnel.community.TriblerTunnelCommunity'>
INFO:TriblerTunnelCommunity:Exit settings: BT=False, IPv8=False
INFO:TriblerTunnelCommunity:Using DispatcherEndpoint with flags {8, 1}
INFO:IPv8CommunityLoader:Loading overlay <class 'abc.VersioningComponent'>
INFO:IPv8CommunityLoader:Loading overlay <class 'tribler.core.content_discovery.community.ContentDiscoveryCommunity'>
INFO:ContentDiscoveryCommunity:Content Discovery Community initialized (peer mid b'90d2ea3f78bcb360c4d035ed5cfd553ba162c876')
INFO:IPv8CommunityLoader:Finished loading communities!
INFO:DownloadManager:Load checkpoints...
INFO:DownloadManager:Checkpoints are loaded

(tribler:158893): dbind-WARNING **: 14:17:59.359: Couldn't connect to accessibility bus: Failed to connect to socket /root/.cache/at-spi/bus_10.0: Keine Berechtigung
ERROR:tribler.core.session:Uncaught exception: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pystray/_appindicator.py", line 24, in <module>
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/gi/__init__.py", line 122, in require_version
ValueError: Namespace AppIndicator3 not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/cx_Freeze/initscripts/__startup__.py", line 140, in run
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/cx_Freeze/initscripts/console.py", line 25, in run
  File "src/tribler/run.py", line 209, in <module>
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/runners.py", line 44, in run
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
  File "src/tribler/run.py", line 188, in main
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pystray/__init__.py", line 64, in <module>
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pystray/__init__.py", line 56, in backend
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pystray/__init__.py", line 28, in appindicator
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pystray/_appindicator.py", line 27, in <module>
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/gi/__init__.py", line 122, in require_version
ValueError: Namespace AyatanaAppIndicator3 not available
NoneType: None
FATAL: exception not rethrown


```

I gave this Output to ChatGPT:

_

> It seems like Tribler encountered multiple issues during startup, particularly with the AppIndicator or Ayatana AppIndicator namespaces. Here’s a breakdown of the log and steps to resolve these:
> 
> AppIndicator Issue:
> 
> The error indicates that the AppIndicator3 or AyatanaAppIndicator3 namespace isn't available, causing the pystray library to fail. This is common in systems without the required AppIndicator libraries.
> Solution: Try installing the required libraries:
> bash
> Code kopieren
> sudo apt install gir1.2-appindicator3-0.1
> If you’re using a more recent distribution that supports Ayatana, install:
> bash
> Code kopieren
> sudo apt install libayatana-appindicator3-1
> DBus Accessibility Warning:
> 
> The warning Couldn't connect to accessibility bus may indicate missing permissions, though it typically doesn't stop Tribler from running.
> Solution: You can ignore this if Tribler runs successfully after resolving the primary issue, as it’s mostly related to UI accessibility.
> FileNotFoundError:
> 
> The log shows Tribler couldn’t find the libtorrent state file, suggesting it’s starting from scratch. If it’s a first-time run or the directory was cleared, this is expected.
> After installing the required AppIndicator packages, try launching Tribler again. If further issues persist, let me know for additional troubleshooting steps.

_

ChatGPT solved this issue, installing this dependencies solved the Problem. It may be that they did not come pre installed in Xubuntu-Minimal or so... However now it is working and starting the Tribler web interface.

Maybe you can configure the .deb install file so that it is going to automatically install this dependencies then this problem should possibly not appear anymore and also avoid problems for other people.
