### ISSUE TITLE
[8.0.1] Downloads list disappears

### ISSUE THREAD

**Issue by herrJones** [Tribler/tribler#8209]
After navigating to other sections, the list with downloads gets cleared.
It still functions in the background though. Only a webinterface problem it seems.

This situation is only resolved by stopping and restarting Tribler.

X64 - Win11 - 8.0.1

(on the other hand: v8.0.x immediately resolved the connectivity errors I had since v7.12 or so)

**Comment by egbertbouman** [comment]
Thanks for the report! To figure out whether it's indeed a problem on the webui side, could you please try refreshing the page? You can also try opening /api/downloads in your browser and see if that return an empty list (e.g. `http://127.0.0.1:8085/ui/#/downloads/all` would become `http://127.0.0.1:8085/api/downloads`).

**Comment by herrJones** [comment]
Hello,
That does not seem to work


When I restart and try, I get:


All downloads remain in 'searching for circuits' forever, so maybe the error in the json causes something?
    Op maandag 14 oktober 2024 om 10:20:33 CEST schreef Egbert Bouman ***@***.***>:  
 
 


Thanks for the report! To figure out whether it's indeed a problem on the webui side, could you please try refreshing the page? You can also try opening /api/downloads in your browser and see if that return an empty list (e.g. http://127.0.0.1:8085/ui/#/downloads/all would become http://127.0.0.1:8085/api/downloads).

**Comment by egbertbouman** [comment]
It sounds like the error is outside of the webui. Just to be sure, there is nothing in `/api/downloads`?

**Comment by herrJones** [comment]
Hello,
Sorry for the confusion.
When the downloads-list in the GUI is empty, the api call returns nothing.When the downloads-list is not empty, I do get output, but an invalid character seems to be detected somewhere.
A larger (and redacted) screenshot below



    Op maandag 14 oktober 2024 om 13:02:22 CEST schreef Egbert Bouman ***@***.***>:  
 
 


It sounds like the error is outside of the webui. Just to be sure, there is nothing in /api/downloads?

**Comment by egbertbouman** [comment]
I'm not seeing any screenshots. I guess that's because you're responding by email.

**Comment by nitmeare** [comment]
Same here under Mint/Xubuntu.... after some random interactions sometimes the download list just disappears. Hard restart (kill tribler) is needed to make it visible again.

**Comment by egbertbouman** [comment]
It's going to be tough debugging this further without additional information. It sounds like Python's `json.dumps` is somehow producing JSON that the browser can't decode (`json.dumps` must have succeeded or we'd be seeing an error+traceback in the UI).

If this is indeed the case `/api/download` should show the raw/unparsed response. To test that the output is invalid, you could use [JSONLint](https://jsonlint.com/). But what we really need is a (highly redacted) string that doesn't pass JSONLint.

**Comment by herrJones** [comment]
Hello,
I exported the JSON into VSCode and JSLint.
JSLint complains about:
Error: Parse error on line 1:
..., "all_time_ratio": Infinity, "trackers"
-----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
so I think the problem may be related to:
{  "name": "download_name",  "progress": 1.0,  "infohash": "2aaxxyyzzd334f675556a116a1d196707f8",  "speed_down": 0,  "speed_up": 0,  "status": "SEEDING",  "status_code": 4,  "size": 181236440,  "eta": 0.0,  "num_peers": 162,  "num_seeds": 2,  "num_connected_peers": 1,  "num_connected_seeds": 0,  "all_time_upload": 174321221,  "all_time_download": 0,  "all_time_ratio": Infinity,  "trackers": [                {                    "url": "[DHT]",                    "peers": 1,                    "status": "Working"                },                {                    "url": "[PeX]",                    "peers": 0,                    "status": "Working"                }  ],  "hops": 1,  "anon_download": true,  "safe_seeding": true,  "max_upload_speed": 0,  "max_download_speed": 0,  "destination": "My_Destination_Folder",  "total_pieces": 512,  "vod_mode": null,  "error": "",  "time_added": 1732170195}

    Op vrijdag 18 oktober 2024 om 12:29:47 CEST schreef Egbert Bouman ***@***.***>:  
 
 


It's going to be tough debugging this further without additional information. It sounds like Python's json.dumps is somehow producing JSON that the browser can't decode (json.dumps must have succeeded or we'd be seeing an error+traceback in the UI).

If this is indeed the case /api/download should show the raw/unparsed response. To test that the output is invalid, you could use JSONLint. But what we really need is a (highly redacted) string that doesn't pass JSONLint.

**Comment by egbertbouman** [comment]
Thanks, that's really helpful!

The issue seems to be the use of `math.inf`, which the browser can't decode (introduced by https://github.com/Tribler/tribler/commit/4a1811d88c589b4dbbba35c4386e73ac681a7e30).
Now that we know what's causing this, fixing the issue seems pretty straightforward.
