### ISSUE TITLE
8.0.1 [Ubuntu 24.04] libgirepository-dev required for .deb

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#8217]
`sudo dpkg -i ./tribler_8.0.1_amd64.deb`
results in an error: `dpkg` requires `libgirepository1.0-dev` which is not installed.
Apparently, this development library is used to build Rust code bindings to Python somehow slipped into the release.

**Comment by qstokkink** [comment]
`dpkg -i` does not pull in missing dependencies, it only shows errors when they are not found.

`sudo apt install ./tribler_8.0.1_all.deb` should pull in your missing dependencies.

**Comment by ichorid** [comment]
I know, but the dependency in question is a "-dev" dependency. It should not be required for non-dev packages.

**Comment by qstokkink** [comment]
If I interpret https://pygobject.gnome.org/getting_started.html#ubuntu-logo-ubuntu-debian-logo-debian correctly, we might be able to substitute `libgirepository1.0-dev` with `python3-gi python3-gi-cairo` inside the deb's `Depends:`.

I would need to make a test build to confirm if that is possible. It would indeed be nice not to depend on a `-dev` package. I'll put this on the shortlist for the next pre-release.

**Comment by qstokkink** [comment]
I just tested this. `libgirepository1.0-dev` is not required, nor is `python3-gi python3-gi-cairo`. We can just straight-up remove this from the `Depends`. That cleans up nicely. Thanks @ichorid 🙏
