### ISSUE TITLE
8.0.3 fails to run on Ubuntu 22.04

### ISSUE THREAD

**Issue by Davem734** [Tribler/tribler#8241]
Installed 8.0.3 on Ubuntu 22.04.
When I execute tribler, nothing happens. 
Log file contains:

/usr/bin/tribler: line 7: /usr/share/tribler/tribler: cannot execute binary file: Exec format error
/usr/bin/tribler: line 7: /usr/share/tribler/tribler: Success

**Comment by qstokkink** [comment]
Thank you for trying our pre-release. The error you got (usually) indicates that you have the wrong executable for your platform.

Our pre-release includes an `x64` and an `aarch64` version:
https://github.com/Tribler/tribler/releases/tag/v8.0.3

For most CPU architectures you'll want the `x64` version. Could you verify that you installed the right version for you machine?

I just visited `tribler.org` and I noticed that our version detection script automatically picks `aarch64` for my `x64` machine.

**Comment by qstokkink** [comment]
As an emergency patch, I made tribler.org automatically point to the `x64.deb` (CC: @egbertbouman). We need to update our website to properly detect the system architecture.

**Comment by Davem734** [comment]
I haven't tried it yet but I am sure that is the problem...
