### ISSUE TITLE
liblzma: cannot open shared object

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#8243]
Tribler 8.0.3

Ubuntu 24.10

when trying to run Tribler, the following message windo appears:

`liblzma-c9407571.so.5.6.3: cannot open shared object file: No such file or directory`
![image](https://github.com/user-attachments/assets/9a444a1d-6011-4917-bdbe-759fca2abbd6)

**Comment by qstokkink** [comment]
Thanks for the report. I can reproduce this. I'll rebuild 8.0.3 A.S.A.P.

![screenshot](https://github.com/user-attachments/assets/9f022615-c8de-4ed7-95db-e5d03826b815)

**Comment by qstokkink** [comment]
I uploaded a new build of 8.0.3: https://github.com/Tribler/tribler/releases/tag/v8.0.3 This should no longer have this error.
