### ISSUE TITLE
Character Broken in Download Torrent Setting Layer

### ISSUE THREAD

**Issue by MARIUSVAMPIRE** [Tribler/tribler#8249]
![image 001](https://github.com/user-attachments/assets/57fbc4aa-2c96-4071-ad8d-fd2ca19a2030)

After Add Torrent, Characters (Korean) is normal in Files Tab 

![image 002](https://github.com/user-attachments/assets/bca98906-ac9e-4d4e-b4a5-33644e167895)

**Comment by qstokkink** [comment]
Thank you for the report! We'll try to reproduce this. The `.torrent` file helps a lot but I'm not sure GitHub wants to host torrents so I'll remove it from your post.

**Comment by qstokkink** [comment]
I found the issue. Our `unhexlify` method seems to decode UTF-8 from singular bytes. However, UTF-8 is variable length encoding. So, this won't work for characters (like Korean apparently) that require multiple bytes per character.

https://github.com/Tribler/tribler/blob/4d42f972fa72ac25b36151c70ca96874beaa55a0/src/tribler/ui/src/lib/utils.ts#L33-L39
