### ISSUE TITLE
NotFoundError: Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by iyagicom** [Tribler/tribler#8251]
Hi! I was using Tribler and THIS happened! :cry:
```
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Yx (http://127.0.0.1:44027/ui/assets/index.4e0ae77f.js:32:26251)
    at Er (http://127.0.0.1:44027/ui/assets/index.4e0ae77f.js:32:25938)
    at Yx (http://127.0.0.1:44027/ui/assets/index.4e0ae77f.js:32:26699)
    at Sn (http://127.0.0.1:44027/ui/assets/index.4e0ae77f.js:32:27553)
    at Qx (http://127.0.0.1:44027/ui/assets/index.4e0ae77f.js:32:28013)
    at Sn (http://127.0.0.1:44027/ui/assets/index.4e0ae77f.js:32:27703)
    at Qx (http://127.0.0.1:44027/ui/assets/index.4e0ae77f.js:32:27816)
    at Sn (http://127.0.0.1:44027/ui/assets/index.4e0ae77f.js:32:27703)
    at Qx (http://127.0.0.1:44027/ui/assets/index.4e0ae77f.js:32:28013)
    at Sn (http://127.0.0.1:44027/ui/assets/index.4e0ae77f.js:32:27703)
```

**Comment by synctext** [comment]
Big oops. Sorry. Something really broke Tribler.

We need a bit more info to fix this. Please tell us if you are a Mac or Windows users. You used latest experimental 8.0.3 of Tribler?

If you have any memory of what caused Tribler to crash, that would be most helpful. Where you doing search, downloading, playing with anon mode, or background seeding?

**Comment by qstokkink** [comment]
`4e0ae77f` is the fingerprint for https://jenkins.tribler.org/job/Tribler/job/Build/job/Build-macOS/229 (you can find it in the corresponding logs). 
This is Mac `Tribler-8.0.0.dmg`.

This might already be fixed in a newer version. That said, it would be nicer to publish a source map with every release to deobfuscate tracebacks.

**Comment by qstokkink** [comment]
> This might already be fixed in a newer version.

It is probably not. I followed the code into line 32 of the traceback in the minified `index.4e0ae77f.js`.

The good news is that I can see that there is only one problematic source file in this traceback: `react-dom.production.min.js` (v18.2.0). The bad news is that this is an external dependency and we do not have the mapping to this file. The worse news is that this traceback does not start from any of our code and it must be some internal React update. The worst news is that other people on the Internet have reported that this error happens sporadically and I do not see one consistent fix being reported (the most feasible seems that `router` cannot deal with React fragments).

**Comment by qstokkink** [comment]
At this point, my (scattered) thoughts on this matter are:
 - Source maps are not going to help us. At least not with this issue.
 - Let's upgrade our React to the latest version.
 - I would like to know the fingerprints of the `index.<fing>.js` we ship with each release. I think we should make them part of each release message.
 - Eliminate fragments (`<></>`) from our ui code and replace them with normal divs (`<div></div>`).
 - There is no way to reproduce this particular issue and we'll have to hope that the above is enough.

@egbertbouman There are many different possible approaches here: what are your thoughts on this?

**Comment by qstokkink** [comment]
Cool find! Also, very weird. Let's go with your fix if you can actually reproduce this 👍
