### ISSUE TITLE
Inadequate keywords blocked by "Family filter"

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#827]
For example, searching on "russian channel" shows no obviously "explicit" results, yet both "russian" and "channel" trigger "At least one of the keywords that you used has been blocked by the family filter".

The list of innosent words that trigger the message I found so far:
- surprise
- channel, channels
- anime
- miss (but not "mister")
- closeup (but not "zoom" and not "macro")
- latina, latinos, russian, russians, chinese, indian, polish, mexican (most other nationalities work fine, although "malaysian" leads to 100% filtered results)
- asian (but not "european", "american", "african" or "australian")
- spice
- foot, legs, toe, finger, mouth  (but not "wrist, elbow, eye, nose, ear, shoulder[s], head, hand")
- kitten (but not "puppy")
- male, female (but not "masculine" or "feminine")
- girl, schoolgirl (but not "boy" or "schoolboy")
- Junge, Opa, Oma, Eltern, Tante, Familie (but not "Mädchen", "Tochter" or "Onkel")

Why do we need "At least one of keywords..." at all? Just show "N items were blocked by family filter" (for example, search query "qwerty" leads to "7 items were blocked" with 0 shown.

**Comment by ichorid** [comment]
There is already a ticked for familiy filter stuff #1052
