### ISSUE TITLE
installing tribler 8.0.5 on debian missing gir1.2-appindicator3-0.1

### ISSUE THREAD

**Issue by johannesvig** [Tribler/tribler#8277]
When trying to install Tribler 8.0.5 on a fully updatet debian system i get this error
Depends: gir1.2-appindicator3-0.1 but it is not installable

My system is Debian 12 (aka bookworm) amd64 

The package does not appear in Synaptic.

**Comment by qstokkink** [comment]
Thanks for reporting. Apparently, `gir1.2-appindicator3-0.1` is not available on your system. We hooked in a workaround.

**Comment by qstokkink** [comment]
I ran a build with the workaround implemented. Are you able to download and test from our latest bleeding edge build here: https://github.com/Tribler/tribler/actions/runs/12072194226 (Linux x64 Build)?

**Comment by johannesvig** [comment]
Hi! 
Thank you for your effort.
I can now install and run Tribler, but upgrading (importing?) settings from tribler 7.14 caused an error (already reported as a separate bugreport.)

**Comment by johannesvig** [comment]
Update:
After killing tribler and restarting, everything seems to be working.
The "ratio" column is missing though.

**Comment by qstokkink** [comment]
Thanks for testing! We'll try to get that fixed as soon as possible.
