### ISSUE TITLE
WatchFolder settings missing in new version 8.0.5

### ISSUE THREAD

**Issue by SpudmanWP** [Tribler/tribler#8280]
When checking all of the settings pages in the Web UI (version 8.0.5), there is no setting to update or set the WatchFolder location.
I checked the  ~/.Tribler folder for the config file in case it was imported from the previous version (7.13), but no mention of the word "watch" or the folder name of my last watch folder.

**Comment by qstokkink** [comment]
The watch folder was indeed removed. If you are/were using it, we can add it back for you in `8.1`.
