### ISSUE TITLE
8.0.5 win10 64

### ISSUE THREAD

**Issue by mselkabong** [Tribler/tribler#8281]
![Untitled](https://github.com/user-attachments/assets/e694c05f-9752-4d1e-9c23-f85ef9df1127)

**Comment by synctext** [comment]
Wow, thnx for reporting!

**Comment by qstokkink** [comment]
@mselkabong could you try browsing to the `%APPDATA%/.Tribler` directory and moving, removing, or renaming your `ec_multichain.pem` file?

**Comment by mselkabong** [comment]
evidently not no items match for your search

**Comment by qstokkink** [comment]
Thanks for trying. I think we should be able to solve this for the next release.

I managed to reproduce this by copying over an old Tribler private key (that does not include a key format, just 64 raw bytes):

![](https://github.com/user-attachments/assets/cd0dd6b0-cad0-4b5b-b4e0-f276b6c5722b)
