### ISSUE TITLE
Unable to open Tribler on MacOS Mojave 10.14.6

### ISSUE THREAD

**Issue by liuyujung** [Tribler/tribler#8282]
3.2 GHz Intel Core i5

[PYI-10794:ERROR] Failed to load Python shared library '/Applications/Tribler.app/Contents/Frameworks/libpython3.10.dylib': dlopen: dlopen(/Applications/Tribler.app/Contents/Frameworks/libpython3.10.dylib, 10): no suitable image found.  Did find:
	/Applications/Tribler.app/Contents/Frameworks/libpython3.10.dylib: cannot load 'libpython3.10.dylib' (load command 0x80000034 is unknown)
	/Applications/Tribler.app/Contents/Frameworks/libpython3.10.dylib: cannot load 'libpython3.10.dylib' (load command 0x80000034 is unknown)

**Comment by qstokkink** [comment]
Thanks for your report. It seems we should update our website, which claims your setup is supported.

I am sad to say that Tribler, its (external) dependencies, and our infrastructure do not support macOS < 12. If we try really hard and pull some tricks, we can feasibly make macOS 11 work. However, we can **really not** make macOS Mojave builds anymore.
