### ISSUE TITLE
Torrent does not appear in search results

### ISSUE THREAD

**Issue by absolutep** [Tribler/tribler#8286]
Torrent that I am downloading [now completed & seeded for 2 hours atleast] does not appear in the search results.

I searched the exact "file name" but still the torrent does not appear in the search results. 

It has been more than two hours, which I think is more than enough to register it on search.

It is a new torrent and has atleast 400 peers at the moment.

**Comment by synctext** [comment]
thnx for reporting!
Ai, that seemed to have slipped through the pre-release testing.

**Comment by absolutep** [comment]
Thanks for reply.

While you are at it, could you please add a feature in search - in which - we can search torrents via Infohash of the torrents.

Use case :- get an obscure & alive torrent from a website and add it into tribler to download as well as register it into tribler search.

Thanks.

**Comment by qstokkink** [comment]
Thanks for the report! When you add a torrent it should immediately be locally searchable. That is a bug.

If you have an infohash, you can prepend `magnet:?xt=urn:btih:` to it and use `+ Add torrent` / `Import torrent from magnet/URL` to fetch its metadata and/or download it. We could add some functionality there to allow infohashes too (you may also be interested in #7540).

**Comment by absolutep** [comment]
> Thanks for the report! When you add a torrent it should immediately be locally searchable. That is a bug.

Yes.

_And as for my second request, I envision it as per the below image_

![2](https://github.com/user-attachments/assets/79262744-4540-4c1c-8909-88187ad2bd8b)
