### ISSUE TITLE
Accessing the web page remotely from outside the PC it's installed on.

### ISSUE THREAD

**Issue by SpudmanWP** [Tribler/tribler#8293]
I am running Tribler from a TrueNAS VM with a fresh and latest LUbuntu LTS build (v20.04).

Tribler launches fine and pops up on a page pointing to the localhost 127 address.
I tried connecting to the public IP of the instance (10.0.0.241) but got a 404 error.

I changed the configuration files to enable https as the 1st step, but I get an error (file not found) when launching Tribler.  This is likely due to missing the https cert file.

Next, I changed the localhost address (127.0.0.1) to 10.0.0.241 in the conf file and Tribler launched and the web page was viewable on the VM itself.

Lastly, I tried launching the page from my laptop with the 10.0.0.241 address.  The page started to load with the basic menus & status bars showing.  However, I then get a popup that says "Failed to connect to Tribler" with a description of "Tribler may not be running or your browser is missing a cookie.   In latter case please re-open Tribler from the system tray"  

I tried a direct URL with the key "http://10.0.0.241:64692/ui/#/downloads/all?key={Put_actual_key_here_in_brackets}" but I get the same error.

An API call from another PC returns an error.
API Call:
http://10.0.0.241:64692/api/downloads?key={Put_actual_key_here_in_brackets}
returns:
{"error": {"handled": true, "message": "Unauthorized access"}}

Not sure if this is a bug or feature request, but I will assume that "remote access" was not included in the 1st build but should be included in a future build.

Here is the API section of the conf file that I am using:

`{
    "api": {
        "http_enabled": true,
        "http_port": 64692,
        "http_host": "10.0.0.241",
        "https_enabled": false,
        "https_host": "127.0.0.1",
        "https_port": 0,
        "https_certfile": "https_certfile",
        "http_port_running": 64692,
        "https_port_running": 0,
        "key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    },`

**Comment by synctext** [comment]
Great analysis, many thanks!!
Indeed, next version(s) we will try to get remote operation going. However, any security issues need to be solved.

**Comment by SpudmanWP** [comment]
Thanks and appreciate the quick reply.

**Comment by qstokkink** [comment]
I don't think it's a good idea to use HTTP instead of HTTPS. However, it should already work. Could you try:

```
http://10.0.0.241:64692/ui/#/downloads/all?key=00000000000000000000000000000000
```

where `00000000000000000000000000000000` is your key (without quotation marks or other things).

**Comment by SpudmanWP** [comment]
I agree that https would be the preferred choice.

Now the fun part... it worked.

I am baffled as that URL was the first one I tried.  I must have fat-fingered the key.
Thanks again.

**Comment by qstokkink** [comment]
Good to hear and you're welcome. Enabling https should not be that much harder (and a lot safer!). Generating a certificate file should just be a matter of generating the file:

```
openssl req -newkey rsa:2048 -nodes -keyout private.key -x509 -days 365 -out certfile.pem
cat private.key >> certfile.pem
rm private.key
```

and then linking to the `certfile.pem` in your configuration and enabling the `https_enabled`, setting the `https` host and port.

**Comment by SpudmanWP** [comment]
Thanks for the detailed instructions.
I was able to generate the cert file just fine and updated the conf file.
I am still getting the message "No such File or Directory" when I launch Tribler.

Ass you can see in the attached, I created the perm file and put it in the Tribler folder with the other pem files.
I also referenced it in the conf file in the same way 9and path) that the other pem files are referenced.
I tried the path both with and without the certfile.pem name.
I'll just assume that I did something wrong.

<img width="581" alt="2024-12-02 17_20_16-Spice Javascript client" src="https://github.com/user-attachments/assets/678952ac-e985-4fe9-ac02-a92c1d72dd9c">

**Comment by qstokkink** [comment]
This is the code that loads the "https_certfile":

https://github.com/Tribler/tribler/blob/67750fd55456e5cd182afecf0799e79edd8902cd/src/tribler/core/restapi/rest_manager.py#L277-L282

This seems to ignore the setting in `api / https_certfile` and just looks for **a file named** `https_certfile` inside whatever your `state_dir` is set to. Unless I'm misinterpreting our own code, this seems like a Tribler bug.

Assuming the `state_dir` is `/home/owner/.Tribler`, renaming `certfile.pem` to `https_certfile` should work.

**Comment by SpudmanWP** [comment]
That makes sense.

Don't worry, I've done MUCH worse ;)

It works, but I think I did the certfile incorrectly

![image](https://github.com/user-attachments/assets/25ba5617-e56f-43c6-af8b-1426d1b15f5d)

**Comment by qstokkink** [comment]
🎉 that is working correctly. You will only need to make sure that your remote laptop trusts the certificate on your server. Following guide for your particular operating system on how to install a custom ssl certificate locally should be the last thing you need.

**Comment by qstokkink** [comment]
In the next version of Tribler, the `https_certfile` should be respected again and you can save your certificate to a more convenient location.
