### ISSUE TITLE
Sort by Status is now only sorting by name and not Percent Complete

### ISSUE THREAD

**Issue by SpudmanWP** [Tribler/tribler#8294]
In previous versions of Tribler, it let me sort by Status (ie percent downloaded) with the most complete at the top.  Now it shows that I am sorting, but I think that it's only sorting on the name (ie Complete, Downloading, etc)

Here is just the Downloads folder showing the "sort descending" arrow.

![2024-11-30 20_00_16-Spice Javascript client](https://github.com/user-attachments/assets/1d890640-8e4e-4136-b80d-eed39a1abfe0)

If you look at the "All" folder, you can see that the sorting is alphabetic ("Stopped", " Seeding", then "Downloading")

![2024-11-30 19_58_22-Spice Javascript client](https://github.com/user-attachments/assets/d5270299-d5be-4378-9d07-d3a0bf4662bf)

**Comment by egbertbouman** [comment]
You're right, it's sorting by state now, not by progress.
I agree that the old way seems to make more sense, especially since you can easily filter by state using the menu. We'll go back to sorting by progress in the next release.

**Comment by SpudmanWP** [comment]
Thanks for the reply and I look forward to it.
