### ISSUE TITLE
Wrong Seeding Ratio displayed.

### ISSUE THREAD

**Issue by absolutep** [Tribler/tribler#8300]
1] Grab a torrent which is already present in your computer. 
2] Add torrent file into your torrent client. 
3] Seeding should start after rechecking of files.
4] Seeding ratio should display proper number.

**Tribler does not show proper seeding ratio while qBittorent does it properly.**

Image attached below.

Windows 10
Tribler 8.5.0
![Untitled](https://github.com/user-attachments/assets/0a23a973-ba5a-49a2-8d0c-2411a8efbf6e)

**Comment by qstokkink** [comment]
I'm not sure I understand your intended outcome. Why is 7.92 the correct ratio for 45.32 up and 0 down? It seems to me like Tribler is correct here by stating that anything divided by 0 is undefined/infinity.

**Comment by absolutep** [comment]
> Why is 7.92 the correct ratio for 45.32 up and 0 down?

Torrent file size = 5.72 gb
Torrent uploaded = 45.32 gb
Torrent ratio = 7.92


As stated in point (1) - file was already present in my computer.

I just grabbed the magnet link(torrent) from a tracker and started to seed the file again.

**Comment by absolutep** [comment]
> I'm not sure I understand your intended outcome

_It helps me seed properly_, i.e., **torrents that need to be seeded 24x7**  versus  `torrents that already have hundreds or thousands of seeders`.

### As seen in image below, some torrents are dire need of seeders.

![1](https://github.com/user-attachments/assets/23b7409c-e259-4e87-a65b-5d16b98733c3)

**Comment by qstokkink** [comment]
Aha! I believe we have a different definition of `Ratio`.

What we have now is:

```
Ratio = Uploaded / Downloaded
```

What I believe you want is:

```
Ratio = Uploaded / File_Size
```

Is that correct?

**Comment by qstokkink** [comment]
I think both statistics are useful. Perhaps we should simply include both and have a `Up/Down Ratio` and `Share Ratio`. @egbertbouman do you have any feelings regarding this issue?

---

I also just noticed this says "dowload":

https://github.com/Tribler/tribler/blob/d40cb8adc03b533e2d276802a883b5fe513175b5/src/tribler/ui/src/pages/Downloads/Details.tsx#L88

**Comment by egbertbouman** [comment]
We could also modify our own definition of ratio a bit: `upload / (filesize * progress)`.
This will ensure that downloads that you add back to Tribler don't have the infinity problem.
