### ISSUE TITLE
SELECT ALL Feature

### ISSUE THREAD

**Issue by absolutep** [Tribler/tribler#8302]
At the moment, Tribler 8.0.5 lacks a "**Select All**" feature.

### Usecase = Change anonymity of all torrents, Delete all torrents, STOP/RESUME all torrents, Edit Trackers etc. in the Tribler in an instant.

Reference image of qBittorrent where you can do all the aforementioned.

![Untitled](https://github.com/user-attachments/assets/2190a4ca-6ad1-4167-9941-3ea6cb5c9d0f)

**Comment by egbertbouman** [comment]
That would be useful, indeed. We'll try to address this in the next release.
