### ISSUE TITLE
[Feature request] Display download upload speeds as well as data transferred

### ISSUE THREAD

**Issue by absolutep** [Tribler/tribler#8305]
This is a Feature request.

Display of real time download/upload speeds as well as data downloaded/uploaded in current session.

### IMAGE 1 = How qBittorrent does it

![1](https://github.com/user-attachments/assets/833431e3-8280-4e29-aaa1-72ccb62849ea)

### IMAGE 2 = How I envision it in Tribler.

![5](https://github.com/user-attachments/assets/e995436c-7d38-4fe0-b8f8-8b6423157a9b)

**Comment by absolutep** [comment]
In Tribler you do not have to necessarily show it in two places, displaying it over in any one of the place is fine.

**Comment by synctext** [comment]
@absolutep This is an interesting feature request. We're trying to evolve beyond Bittorrent.
We're slowly moving towards an open source serverless Tiktok/Youtube/Wikipedia/scholar.google.

So our GUI will become simpler the coming years. Swipe-as-interface without spyware servers, misinformation, doom-scrolling, and addition. So sadly I'll close most requests that make the GUI more "expert-like". Hopefully our hard-core early users will not leave us. With "mouse-over" based info we can enrich Tribler with expert info, without clutter.
