### ISSUE TITLE
Ability to permanently default to light/dark themes preference

### ISSUE THREAD

**Issue by absolutep** [Tribler/tribler#8310]
Right now, after every restart Tribler defaults to light theme. So, the option to select light/dark/system is pretty much useless.

**Use case** :- When dark theme is selected Tribler should always start in dark theme mode, irrespective of how many restarts has happened.

**Comment by egbertbouman** [comment]
Tribler is saving the `theme` setting to the local storage of the browser. However, by default we use port 0. This means that everything in localstorage will effectively be ignored after the next restart. I'll move the setting to the `guiSettings`, which should solve this issue.
