### ISSUE TITLE
Triber 8.0.6 datas importation

### ISSUE THREAD

**Issue by Pixel-FR** [Tribler/tribler#8321]
Hi

I've upgraded Tribler version 7.14 to 8.0.6 and i've start the datas importation. The script didn't stop alone. After a long time, i needed reboot my computer and i restarted Tribler. All my "torrents" files are present but i have no "Channels" !
There is a long filename made of hexadecimal numbers instead. Are "Channels" abandoned ? How to retrieve them ?

Thanks for your help !

**Comment by qstokkink** [comment]
Hey! Depending on how big your previous database was, upgrading can take quite a while. You can shut down Tribler and restart the upgrade.

If you restart the upgrade process, it should skip all the entries that have been previously upgraded, making it go faster and faster until you eventually finish upgrading.

Channels have indeed been abandoned. I don't think there's an easy way to view them anymore.
