### ISSUE TITLE
Move Debug Information to Each Torrent's Menu

### ISSUE THREAD

**Issue by teddyrogers** [Tribler/tribler#8336]
Request to relocate or replicate some (or all) of the information from the debug menu to each torrents menu. This will make it easier to understand which circuit, relays, etc. are related to each torrent. Currently in the debug menu its all collated and difficult to breakdown to each torrent.

![394264471-dc40489c-e392-4c76-9343-62ec8b31aac0](https://github.com/user-attachments/assets/13ff1fc9-f87e-48ef-8640-13d58b4821a8)

**Comment by egbertbouman** [comment]
Unfortunately, this isn't something we can do. It's simply not possible to track which circuits a certain download is using. All information we have is in the debug panel.

**Comment by egbertbouman** [comment]
We did indeed have a circuits tab in the past. However, from what I remember, this tab was showing the complete list of circuits used by all downloads. That's pretty much the same information that you'll find in the debug panel.
