### ISSUE TITLE
Store thumb images in datafile and not seperate files

### ISSUE THREAD

**Issue by michielha** [Tribler/tribler#834]
Tribler has the habit creating a TON of seperate files for thumbnails. This has two problems:

1. indexing and such file/folder operations take long. Even deleting the thumbnails folder can take quite some time due to the large number of files.
2. filenames and thumbnails can contain explicit words/images. I don't prefer having that kind of stuff lingering around on my harddrive.

So either make a function to hide these files (Store them as blobs in a db?) Or pack them all up in 1 zip, and use that internally. Other solutions also welcome. But having 9000+ files after a couple of hours of running tribler is quite too much for my taste.

**Comment by whirm** [comment]
We are working on moving the collected torrent files to a key value store (levelDB) it should be trivial to do the same for thumbnails when we reenable them.

**Comment by whirm** [comment]
This was done months ago, but the issue wasn't closed.
