### ISSUE TITLE
TCP: Possible SYN flooding on port 7760. Sending cookies.  Check SNMP counters.

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#859]
Maybe Tribler using the network a bit too aggressively?

**Comment by jesshaas** [comment]
I also get this error anytime I am running tribler.I am using version 6.5.2

**Comment by ichorid** [comment]
Haven't seen this in a while. Closing.

**Comment by devos50** [comment]
Possibly related to Swift 😅

**Comment by synctext** [comment]
LOL, Ok. Issue cleanup was more needed then I realised. You found quite a relic. One school says, any issue older then 3 weeks is not anybody's priority, close it. I'm more somebody who never throws stuff out, our closes it.
We need a issue policy, process, and cleanup..
