### ISSUE TITLE
Feature request: intermediate (semi-streaming) mode.

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#870]
Currently I see two general modes:
- Streaming (sequential download, can't include more files (e.g. subtitles `srt` file), VLC keeps initialized);
- Download (random download, can include more files, no player instance around);

I want some "intermediate" mode. It should be like "Download" for the GUI, but like the sequential mode for the library. This can be useful when viewing the video with external players.

**Comment by devos50** [comment]
@whirm This is a nice addition for the new API (we can have a parameter like `sequential` when starting a download). I would move this to the new GUI milestone.

**Comment by synctext** [comment]
Quite an expert mode feature. We sadly have to keep Tribler simple, due to our limited non-profit budget.
