### ISSUE TITLE
migrate to wxpython3.0

### ISSUE THREAD

**Issue by grandpaul** [Tribler/tribler#875]
Dear Tribler developers,

In Debian, currently wxwidgets2.8 is dropping for jessie release.
So a migration from 2.8 to 3.0 is needed.
It is described in https://bugs.debian.org/759044 

Olly Betts made a patch for this. But there's still some issue. Please see the attachment in Debian bug report. It is named tribler-6.3.1+git20140902.9a5a2604-1.1-nmu.diff
Thanks a lot.

Yours Sincerely,
Paul

**Comment by hoxu** [comment]
Are there any plans to work on this? Would be nice to have Tribler installable on Debian Jessie (and derivatives).

**Comment by whirm** [comment]
There's a WIP branch dealing with this:

https://github.com/Tribler/tribler/pull/1786

Seems to work, but it still gives some warnings and needs more testing.

**Comment by synctext** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=759044
This started in 2014, but will be finished early 2016 :-)

**Comment by synctext** [comment]
We will put out a specific release focused exclusively on WX3 support in coming weeks.
We have been kicked out of Debian and need to get back in.

**Comment by whirm** [comment]
@devos50 could you focus on dealing with the remaining wx bugs assinged to this milestone so we can release a first Alpha?

**Comment by devos50** [comment]
@whirm will do!
