### ISSUE TITLE
Tracebacks in Tribler output when out of disk space for collected_torrent_files

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#886]
```
Traceback (most recent call last):
  File "/home/vi/home/tribler/tribler/Tribler/Utilities/TimedTaskQueue.py", line 136, in run
    task()
  File "/home/vi/home/tribler/tribler/Tribler/Core/RemoteTorrentHandler.py", line 289, in <lambda>
    raw_lambda = lambda: callback(None)
  File "/home/vi/home/tribler/tribler/Tribler/Core/RemoteTorrentHandler.py", line 296, in do_schedule
    self._save_torrent(tdef, callback)
  File "/home/vi/home/tribler/tribler/Tribler/Core/RemoteTorrentHandler.py", line 313, in _save_torrent
    tdef.save(tmp_filename)
  File "/home/vi/home/tribler/tribler/Tribler/Core/TorrentDef.py", line 894, in save
    f = open(filename, "wb")
IOError: [Errno 28] No space left on device: u'/home/vi/home/tribler/TriblerDownloads/collected_torrent_files/tmp_b15351e59256070921825dbd78b1c2409b8b3da2.torrent'
```

I expect all "No space left on device" to be handled appropriately in TriblerDownloads, including in collected_torrent_files, which is a separate partition for me.

Version is v6.3.3

**Comment by synctext** [comment]
Gigachannels altered this behavior

**Comment by vi** [comment]
What are Gigachannels? Google Search links back to Tribler issues.

**Comment by devos50** [comment]
@vi Gigachannels is our new technology in Tribler 7.3 to enable the creation and dissemination of channels with millions of entries. Our old system, Dispersy, is not scalable enough for this. We now use libtorrent to disseminate (compressed) channel entries, which unlocks superior performance.

**Comment by vi** [comment]
Like torrents containing lists of other torrents?

**Comment by devos50** [comment]
Essentially yes. Each torrent in your channel is encoded in a metadata blob, containing the infohash, name and optionally some trackers, and digitally signed by the creator.

**Comment by vi** [comment]
> Gigachannels is our new technology in Tribler 7.3
> 7.3

Does migration to a new distributed backbone grant a major version increase, Tribler 8.0. Looks backwars-incompatible enough for it.
