### ISSUE TITLE
Tribler not working on Fedora

### ISSUE THREAD

**Issue by setupminimal** [Tribler/tribler#893]
When I try to start Tribler, I get:

Traceback (most recent call last):
  File "/home/daroc/Downloads/tribler/Tribler/Main/tribler_main.py", line 190, in **init**
    s = self.startAPI(self.splash.tick)
  File "/home/daroc/Downloads/tribler/Tribler/Main/tribler_main.py", line 469, in startAPI
    session = Session(self.sconfig)
  File "/home/daroc/Downloads/tribler/Tribler/Core/Session.py", line 126, in **init**
    self.keypair = permidmod.generate_keypair()
  File "/home/daroc/Downloads/tribler/Tribler/Core/permid.py", line 25, in generate_keypair
    ec_keypair = EC.gen_params(KEYPAIR_ECC_CURVE)
  File "/usr/lib64/python2.7/site-packages/M2Crypto/EC.py", line 269, in gen_params
    return EC(m2.ec_key_new_by_curve_name(curve), 1)
  File "/usr/lib64/python2.7/site-packages/M2Crypto/EC.py", line 106, in **init**
    assert m2.ec_key_type_check(ec), "'ec' type error"
ValueError: Received a NULL pointer.

and then Tribler hangs. I think, based on my investegations so far, that this is because the function ec_key_type_check does not exist in my OpenSSL, and so when M2Crypto wraps it it returns null?

Versions of things:
Openssl: OpenSSL 1.0.1e-fips 11 Feb 2013
M2Crypto: 0.22
Tribler: Yesterday's git

I would appreciate any help available, because Tribler looks like a really neat concept, and would be to Tor as I2Bote is to I2P.

**Comment by sergiomb2** [comment]
By https://bugzilla.redhat.com/show_bug.cgi?id=1019390 elliptic curves should be enabled by now ! I going test it right now , but IMO the solution is enable ECC in Fedora not disable it in Tribler.

**Comment by whirm** [comment]
@sergiomb2 that's great! 
Please, let me know whether it worked or not.

**Comment by sergiomb2** [comment]
I couldn't solve it yet , I also tried compile openssl without restrictions but :
tribler 
Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/Main/tribler_main.py", line 1061, in run
    use_torrent_search=use_torrent_search, use_channel_search=use_channel_search)
  File "/usr/share/tribler/Tribler/Main/tribler_main.py", line 143, in __init__
    use_torrent_search=use_torrent_search, use_channel_search=use_channel_search)
  File "/usr/share/tribler/Tribler/Main/tribler_main.py", line 383, in InitStage1
    session = Session(self.sconfig, autoload_discovery=autoload_discovery)
  File "/usr/share/tribler/Tribler/Core/Session.py", line 120, in __init__
    self.keypair = permidmod.generate_keypair()
  File "/usr/share/tribler/Tribler/Core/permid.py", line 22, in generate_keypair
    ec_keypair.gen_key()
  File "/usr/lib64/python2.7/site-packages/M2Crypto/EC.py", line 126, in gen_key
    m2.ec_key_gen_key(self.ec)
ValueError: Received a NULL pointer.
Exception ValueError: 'Received a NULL pointer.' in <bound method EC.__del__ of <M2Crypto.EC.EC instance at 0x7fbd3e013e60>> ignored

**Comment by whirm** [comment]
You will also need to recompile m2crypto then.

**Comment by sergiomb2** [comment]
openssl ecparam -list_curves 

    secp256k1 : SECG curve over a 256 bit prime field
    secp384r1 : NIST/SECG curve over a 384 bit prime field
    secp521r1 : NIST/SECG curve over a 521 bit prime field
    prime256v1: X9.62/SECG curve over a 256 bit prime field

So: 

    ec_keypair = M2Crypto.EC.gen_params(M2Crypto.EC.NID_sect233k1) 

fails I think 

Can't I try use one of ecparam available ? until I manage to build openssl with sect233k1 support.

Thanks

**Comment by whirm** [comment]
Maybe you could send a PR with instructions on how to do that? (that's if you are doing everything on the user's dir)

**Comment by kc1212** [comment]
I also have this problem. My workaround is to use [Nix](https://nixos.org/nix/) in Fedora. I created an Nix expression https://github.com/kc1212/tribler-in-nix/blob/master/tribler.nix for use with `nix-shell`. So to get an interactive shell with all the dependencies to run Tribler you simply download the file and do `nix-shell ./tribler.nix`. Of course, you need to have Nix installed.

The advantage of this approach is that it works on all Linux distributions and also macOS. Also, it doesn't pollute your system with 100s of libraries.

Tribler runs fine for me, but I'm not sure whether it passes all the tests. Perhaps it is useful to put this in the README, what do you think @devos50?

**Comment by devos50** [comment]
@kc1212 can you try to run the unit tests to see whether it works correctly?

Command: `nosetests Tribler/Test` (you can exclude the GUI tests located in `Tribler/Test/GUI` if you want).

If it does and you have some time, it would be nice if we can create a guide to setup Tribler with Nix. Please let me know!

**Comment by kc1212** [comment]
@devos50 I tried to run the tests, but it got stuck at `testing channel source.` (no progress in stdout after ~30 minutes and I can't ctrl+c). My oblivious debugging using gdb shows some kind of deadlock, most of the threads are stuck on either `do_futex_wait.constprop`, `pthread_cond_wait@@GLIBC_2.3.2` or `epoll_wait`. Is this a known problem?

**Comment by devos50** [comment]
@kc1212 are you using an `EPollReactor` when running Twisted (to find out, you can print the `reactor` object)?

**Comment by sergiomb2** [comment]
@devos50  could we have, please, releases of v7.0.0-alpha1 like we have in 6.6.0-0.exp1 , release have the source modules , while tag haven't .
Thanks.

**Comment by devos50** [comment]
Closing this issue since a solution has been proposed in this thread.

**Comment by Hans2004** [comment]
> I also have this problem. My workaround is to use Nix in Fedora. I created an Nix expression https://github.com/kc1212/tribler-in-nix/blob/master/tribler.nix for use with nix-shell. So to get an interactive shell with all the dependencies to run Tribler you simply download the file and do nix-shell ./tribler.nix. Of course, you need to have Nix installed.
> 
> The advantage of this approach is that it works on all Linux distributions and also macOS. Also, it doesn't pollute your system with 100s of libraries.
> 
> Tribler runs fine for me, but I'm not sure whether it passes all the tests. Perhaps it is useful to put this in the README, what do you think @devos50?

I have tried your method on version 7.0.0.3rc3. I had to modify your tribler.nix file slightly by adding     python27Packages.tkinter, and python27Packages.psutil. But now tribler complains about not having module meliae. But module maliae is not available as a package for nix. Do you know what I should do next @kc1212?

**Comment by kc1212** [comment]
In my .nix file, I also used dependencies that are not in the nix repo, e.g. [leveldb](https://github.com/kc1212/tribler-in-nix/blob/master/tribler.nix#L4) and [libnacl](https://github.com/kc1212/tribler-in-nix/blob/master/tribler.nix#L11). If meliae is in pypi and has a standard installation procedure, then just do something similar to the examples above.

**Comment by Hans2004** [comment]
I have tried your suggestion and added the following to your script, but I am still a beginner with nix:
```
_meliae = with python27Packages; buildPythonPackage {
    name = "meliae-0.4.0";
    src = fetchurl {
      url = "https://pypi.python.org/packages/98/c6/7fa12062ddfe1732d43b34b64a3fe99da958a88fa1d8b7550fe386a9ca01/meliae-0.4.0.tar.gz";
      sha256 = "976519ab02aaa6a8fb5f596dc4dd9f64fc9510b00e054979566e51c9be7cec99";
    };
  };
```

But now, when starting nix-shell with the script, it complains:
```
these derivations will be built:
  /nix/store/09fvg66zj0i09v6ybpwapvb1150gr3ab-python2.7-meliae-0.4.0.drv
  /nix/store/f77wnlhq5jfmm3pd4rykir67kn4f1acn-tribler.drv
building path(s) ‘/nix/store/zqazcisn828sciq137gz38ifh4dcx2mj-python2.7-meliae-0.4.0’
unpacking sources
unpacking source archive /nix/store/4yx8y61pqy25yl1k4hw02wd6lh490jy7-meliae-0.4.0.tar.gz
source root is meliae-0.4.0
setting SOURCE_DATE_EPOCH to timestamp 1310129288 of file meliae-0.4.0/track_memory.py
patching sources
configuring
building
We require Cython to be installed.
installing
/nix/store/4lc3fnkx542pb8va085lg6x464fd8wxq-stdenv/setup: line 1052: pushd: dist: No such file or directory
builder for ‘/nix/store/09fvg66zj0i09v6ybpwapvb1150gr3ab-python2.7-meliae-0.4.0.drv’ failed with exit code 1
error: build of ‘/nix/store/09fvg66zj0i09v6ybpwapvb1150gr3ab-python2.7-meliae-0.4.0.drv’ failed
/home/hans/.nix-profile/bin/nix-shell: failed to build all dependencies
```

**Comment by kc1212** [comment]
Try specify cython as one of the dependencies of meliae using `buildInputs`.

Some examples are https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.md under "Handling dependencies"



On 15 October 2017 22:44:03 GMT+13:00, Hans2004 <notifications@github.com> wrote:
>I have tried your suggestion and added the following to your script,
>but I am still a beginner with nix:
>```
>_meliae = with python27Packages; buildPythonPackage {
>    name = "meliae-0.4.0";
>    src = fetchurl {
>url =
>"https://pypi.python.org/packages/98/c6/7fa12062ddfe1732d43b34b64a3fe99da958a88fa1d8b7550fe386a9ca01/meliae-0.4.0.tar.gz";
>sha256 =
>"976519ab02aaa6a8fb5f596dc4dd9f64fc9510b00e054979566e51c9be7cec99";
>    };
>  };
>```
>
>But now, when starting nix-shell with the script, it complains:
>```
>these derivations will be built:
> /nix/store/09fvg66zj0i09v6ybpwapvb1150gr3ab-python2.7-meliae-0.4.0.drv
>  /nix/store/f77wnlhq5jfmm3pd4rykir67kn4f1acn-tribler.drv
>building path(s)
>‘/nix/store/zqazcisn828sciq137gz38ifh4dcx2mj-python2.7-meliae-0.4.0’
>unpacking sources
>unpacking source archive
>/nix/store/4yx8y61pqy25yl1k4hw02wd6lh490jy7-meliae-0.4.0.tar.gz
>source root is meliae-0.4.0
>setting SOURCE_DATE_EPOCH to timestamp 1310129288 of file
>meliae-0.4.0/track_memory.py
>patching sources
>configuring
>building
>We require Cython to be installed.
>installing
>/nix/store/4lc3fnkx542pb8va085lg6x464fd8wxq-stdenv/setup: line 1052:
>pushd: dist: No such file or directory
>builder for
>‘/nix/store/09fvg66zj0i09v6ybpwapvb1150gr3ab-python2.7-meliae-0.4.0.drv’
>failed with exit code 1
>error: build of
>‘/nix/store/09fvg66zj0i09v6ybpwapvb1150gr3ab-python2.7-meliae-0.4.0.drv’
>failed
>/home/hans/.nix-profile/bin/nix-shell: failed to build all dependencies
>```
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Tribler/tribler/issues/893#issuecomment-336698757

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
