### ISSUE TITLE
Finish remaining features for TFTP

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#903]
In the future we will remove Libswift, as it is not sufficiently stable and too complex.

We will test TFTP protocol, from 22 years ago. (https://tools.ietf.org/html/rfc1350)

Priorities and steps:
- [x] integrate TFTP with rawserver.py
- [x] most basic service: single 1MByte hard-coded test file transfer
- [x] ability to serve small files from a given working directory
- [x] add a first and simple timeout
- [x] a downloader gets no response for 5 seconds, we timeout and abort
- [x] do a clean abort, use a temp file or something
- [x] only deliver fully downloaded files
- [x] Fancy timeout and retransmit mechanism
- [x] do a re-transmit of last data packet after 5 seconds, if no ACK is received
- [x] receiver has the ability to ignore duplicated data packets
- [x] simple and effective content correctnes
- [x] the filename contains or is equal to a SHA1 hash check
- [x] after file is downloaded, check the hash.
- [x] if it is incorrect, simply abort
- [x] we do not try to recover from this type of error, too complex

**Comment by whirm** [comment]
@LipuFei is this issue up to date?

**Comment by LipuFei** [comment]
@whirm yes, but I don't think this is NOT a TOP PRIORITY now.

**Comment by LipuFei** [comment]
@whirm Our current TFTP implementation is good enough for the torrent collecting, so I don't think implementing those fancy stuff is really necessary. You can remove the top priority tag and perhaps close this issue as well.

**Comment by whirm** [comment]
I agree, @synctext what do you say?

**Comment by whirm** [comment]
This will give trouble for big files, so we need the rest implemented for thumbnails and such. (>100KB)

**Comment by LipuFei** [comment]
Done through #1404
