### ISSUE TITLE
Change everything to use unicode

### ISSUE THREAD

**Issue by LipuFei** [Tribler/tribler#917]
Now we get another unicode problem in config files, see #871

**Comment by lesmo** [comment]
Also, how does using Python 3.4+ solve anything? As I said in #871 I'm not a Python guy, but I'd say it can be fixed as that issue got fixed then without going all weird on Python versions.

**Comment by whirm** [comment]
@lesmo sure it can be fixed without migrating to 3.4, I was just answering @snapy666 on why migrating to 3.4 wouldn't happen any time soon :)
