### ISSUE TITLE
Encrypted megacache

### ISSUE THREAD

**Issue by vvs-** [Tribler/tribler#980]
According to some posts on the forum there is a legal danger of downloading thumbnails in some countries. Please, implement encryption of stored megacache files using a key from secret store.

A possible Python implementation is packaged in Ubuntu and Fedora as python-keyring. It supports Linux, Windows and Mac.

**Comment by synctext** [comment]
We now have it stored in a LevelDB database, using our own format. So it does not show up in simple searches. 
Creating an encrypted store shounds safe, but the access key also is stored on the same machine. We need to improve the crowdsourcing and voting mechanism. Then then community can filter the really bad stuff out.
