### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'on_puncture'

### ISSUE THREAD

**Issue by LipuFei** [Tribler/tribler#985]
```
Traceback (most recent call last):
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/dispersy/dispersy.py", line 1720, in _update
    messages[0].handle_callback(messages)
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/dispersy/community.py", line 2850, in on_puncture
    cache.on_puncture()
AttributeError: 'NoneType' object has no attribute 'on_puncture'
```

**Comment by whirm** [comment]
I really don't see how this can happen. There's no way to Cache.add(None) without raising and exception. All the method that touch Cache._identifiers check if they are on twisted's thread except for .clear() I've added an assertion there. Let's see if we catch something.

**Comment by whirm** [comment]
@LipuFei Also, did this happen while doing a test run or running tribler.sh?

**Comment by whirm** [comment]
This will fix the issue: https://github.com/Tribler/dispersy/pull/394
